// =====================================================================
// I Coríntios — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["1corintios"][1] = [
{s:"Saudação"},
{v:1,t:"Paulo, chamado a ser apóstolo de Cristo Jesus pela vontade de Deus, e o irmão Sóstenes,"},
{v:2,t:"à Igreja de Deus que está em Corinto, aos santificados em Cristo Jesus, chamados a ser santos, com todos os que invocam em todo lugar o nome de nosso Senhor Jesus Cristo, Senhor deles e nosso:"},
{v:3,t:"graça a vós e paz, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo."},
{s:"Ação de graças"},
{v:4,t:"Dou graças ao meu Deus sempre, a vosso respeito, pela graça de Deus que vos foi dada em Cristo Jesus;"},
{v:5,t:"porque nele fostes enriquecidos em tudo, em toda palavra e em todo conhecimento,"},
{v:6,t:"na medida em que o testemunho de Cristo se confirmou entre vós,"},
{v:7,t:"de modo que não vos falta nenhum dom, enquanto aguardais a revelação de nosso Senhor Jesus Cristo."},
{v:8,t:"Ele vos confirmará até o fim, para serdes irrepreensíveis no dia de nosso Senhor Jesus Cristo."},
{v:9,t:"Fiel é Deus, por quem fostes chamados à comunhão de seu Filho Jesus Cristo, nosso Senhor."},
{s:"As divisões em Corinto"},
{v:10,t:"Rogo a vós, irmãos, pelo nome de nosso Senhor Jesus Cristo, que digais todos a mesma coisa e que não haja divisões entre vós, mas sejais perfeitamente unidos, no mesmo pensamento e no mesmo parecer."},
{v:11,t:"Porque a vosso respeito, meus irmãos, fui informado pelos da casa de Cloé de que há contendas entre vós."},
{v:12,t:"Refiro-me a isto: cada um de vós diz: Eu sou de Paulo; eu, de Apolo; eu, de Cefas; eu, de Cristo.",n:"Cefas é o nome aramaico de Pedro, que significa rocha."},
{v:13,t:"Está dividido Cristo? Acaso Paulo foi crucificado por vós? Ou fostes batizados no nome de Paulo?",np:1},
{v:14,t:"Dou graças a Deus por não ter batizado nenhum de vós, a não ser Crispo e Gaio,"},
{v:15,t:"para que ninguém diga que fostes batizados no meu nome."},
{v:16,t:"Batizei também a família de Estéfanas; quanto ao resto, não sei se batizei mais alguém."},
{v:17,t:"Porque Cristo não me enviou para batizar, mas para evangelizar, e não com sabedoria de palavras, para que a cruz de Cristo não se esvazie."},
{s:"A loucura da cruz"},
{v:18,t:"Porque a palavra da cruz é loucura para os que se perdem; mas, para nós, que somos salvos, é poder de Deus."},
{v:19,l:["Pois está escrito:","Destruirei a sabedoria dos sábios","e rejeitarei a inteligência dos inteligentes."]},
{v:20,t:"Onde está o sábio? Onde, o escriba? Onde, o argumentador deste século? Acaso Deus não tornou louca a sabedoria do mundo?"},
{v:21,t:"Porque, como na sabedoria de Deus o mundo não conheceu a Deus pela sabedoria, aprouve a Deus salvar os que creem pela loucura da pregação.",np:1},
{v:22,t:"Os judeus pedem sinais, e os gregos buscam sabedoria;"},
{v:23,t:"nós, porém, pregamos Cristo crucificado, escândalo para os judeus e loucura para os gentios;"},
{v:24,t:"mas, para os chamados, tanto judeus como gregos, Cristo, poder de Deus e sabedoria de Deus."},
{v:25,t:"Porque a loucura de Deus é mais sábia do que os homens, e a fraqueza de Deus é mais forte do que os homens."},
{s:"Deus escolheu os fracos"},
{v:26,t:"Vede, irmãos, a vossa vocação: não há entre vós muitos sábios segundo a carne, nem muitos poderosos, nem muitos de nobre nascimento."},
{v:27,t:"Mas Deus escolheu as coisas loucas do mundo para envergonhar os sábios, e Deus escolheu as coisas fracas do mundo para envergonhar as fortes;"},
{v:28,t:"Deus escolheu as coisas vis do mundo, as desprezadas, as que não são, para reduzir a nada as que são,"},
{v:29,t:"a fim de que nenhuma carne se glorie diante de Deus."},
{v:30,t:"É por ele que vós estais em Cristo Jesus, que se tornou para nós sabedoria da parte de Deus, justiça, santificação e redenção,",np:1},
{v:31,t:"para que, como está escrito: Quem se gloria, glorie-se no Senhor."}
];

window.TEXTOS_SEED["1corintios"][2] = [
{s:"A pregação sem eloquência"},
{v:1,t:"Também eu, irmãos, quando fui a vós, não fui anunciar a vós o mistério de Deus com superioridade de palavra ou de sabedoria.",n:"Alguns manuscritos leem o testemunho de Deus; sigo a leitura mistério, adotada pela Nova Vulgata."},
{v:2,t:"Porque decidi não saber coisa alguma entre vós, senão Jesus Cristo, e este crucificado."},
{v:3,t:"E foi em fraqueza, em temor e em grande tremor que estive entre vós."},
{v:4,t:"A minha palavra e a minha pregação não consistiram em persuasivas palavras de sabedoria, mas em demonstração do Espírito e de poder,"},
{v:5,t:"para que a vossa fé não se apoiasse na sabedoria dos homens, mas no poder de Deus."},
{s:"A sabedoria de Deus, revelada pelo Espírito"},
{v:6,t:"Contudo, falamos sabedoria entre os perfeitos; sabedoria, porém, que não é deste século nem dos príncipes deste século, que são reduzidos a nada."},
{v:7,t:"Mas falamos a sabedoria de Deus em mistério, a sabedoria escondida que Deus predestinou antes dos séculos para a nossa glória,"},
{v:8,t:"que nenhum dos príncipes deste século conheceu; porque, se a tivessem conhecido, jamais teriam crucificado o Senhor da glória."},
{v:9,l:["Mas, como está escrito:","O que o olho não viu, nem o ouvido ouviu,","nem subiu ao coração do homem,","é o que Deus preparou para os que o amam."]},
{v:10,t:"A nós, porém, Deus o revelou pelo Espírito; porque o Espírito sonda todas as coisas, até as profundezas de Deus.",np:1},
{v:11,t:"Pois quem, dentre os homens, conhece as coisas do homem, senão o espírito do homem, que nele está? Assim também as coisas de Deus, ninguém as conhece, senão o Espírito de Deus."},
{v:12,t:"Nós não recebemos o espírito do mundo, mas o Espírito que vem de Deus, para conhecermos o que Deus nos deu por graça;"},
{v:13,t:"e disso também falamos, não com palavras ensinadas pela sabedoria humana, mas com as ensinadas pelo Espírito, exprimindo realidades espirituais em termos espirituais."},
{v:14,t:"O homem natural não acolhe as coisas do Espírito de Deus, porque para ele são loucura; e não pode conhecê-las, porque se discernem espiritualmente.",np:1,n:"Homem natural traduz psychikos: o homem reduzido à vida da alma natural (psyche), sem o Espírito; opõe-se ao espiritual (pneumatikos) do versículo seguinte."},
{v:15,t:"O homem espiritual, porém, discerne todas as coisas, e ele não é discernido por ninguém."},
{v:16,t:"Pois quem conheceu a mente do Senhor, para o instruir? Nós, porém, temos a mente de Cristo."}
];

window.TEXTOS_SEED["1corintios"][3] = [
{s:"Ainda carnais"},
{v:1,t:"E eu, irmãos, não pude falar a vós como a espirituais, mas como a carnais, como a criancinhas em Cristo."},
{v:2,t:"Dei a vós leite a beber, não alimento sólido, porque ainda não podíeis. Aliás, nem agora podeis,"},
{v:3,t:"porque ainda sois carnais. Pois, havendo entre vós ciúme e contenda, não sois carnais e não andais segundo o homem?"},
{v:4,t:"Quando um diz: Eu sou de Paulo, e outro: Eu, de Apolo, não sois meros homens?"},
{s:"Cooperadores de Deus"},
{v:5,t:"Que é, afinal, Apolo? E que é Paulo? Servidores, por meio dos quais crestes, e conforme o que o Senhor deu a cada um."},
{v:6,t:"Eu plantei, Apolo regou, mas era Deus quem fazia crescer."},
{v:7,t:"De modo que nem o que planta é alguma coisa, nem o que rega, mas Deus, que faz crescer."},
{v:8,t:"O que planta e o que rega são um; e cada um receberá a sua recompensa segundo o seu trabalho."},
{v:9,t:"Porque somos cooperadores de Deus; vós sois lavoura de Deus, edifício de Deus."},
{s:"O único fundamento"},
{v:10,t:"Segundo a graça de Deus que me foi dada, como sábio arquiteto lancei o fundamento; outro edifica sobre ele. Mas cada um veja como edifica."},
{v:11,t:"Porque ninguém pode lançar outro fundamento além do que foi lançado, que é Jesus Cristo."},
{v:12,t:"Se alguém edifica sobre o fundamento com ouro, prata, pedras preciosas, madeira, feno, palha,",np:1},
{v:13,t:"a obra de cada um se tornará manifesta; pois o dia a mostrará, porque se revela no fogo, e o fogo provará qual é a obra de cada um."},
{v:14,t:"Se permanecer a obra que alguém edificou, ele receberá recompensa;"},
{v:15,t:"se a obra de alguém se queimar, ele sofrerá o prejuízo; ele mesmo, porém, será salvo, mas como que através do fogo.",n:"A tradição, desde os Padres, vê nesta salvação como que através do fogo um apoio à doutrina da purificação depois da morte."},
{s:"Templo de Deus sois vós"},
{v:16,t:"Não sabeis que sois templo de Deus e que o Espírito de Deus habita em vós?"},
{v:17,t:"Se alguém destruir o templo de Deus, Deus o destruirá; porque o templo de Deus é santo, e esse templo sois vós."},
{s:"Tudo é vosso"},
{v:18,t:"Ninguém se engane: se alguém dentre vós se julga sábio neste século, faça-se louco para se tornar sábio."},
{v:19,l:["Porque a sabedoria deste mundo é loucura diante de Deus. Pois está escrito:","Ele apanha os sábios na sua própria astúcia."]},
{v:20,l:["E ainda:","O Senhor conhece os pensamentos dos sábios,","e sabe que são vãos."]},
{v:21,t:"Portanto, ninguém se glorie nos homens. Porque tudo é vosso:"},
{v:22,t:"seja Paulo, seja Apolo, seja Cefas, seja o mundo, seja a vida, seja a morte, seja o presente, seja o futuro, tudo é vosso;"},
{v:23,t:"mas vós sois de Cristo, e Cristo, de Deus."}
];

window.TEXTOS_SEED["1corintios"][4] = [
{s:"Servos e administradores dos mistérios"},
{v:1,t:"Que os homens nos considerem, pois, como servidores de Cristo e administradores dos mistérios de Deus."},
{v:2,t:"Ora, o que se exige dos administradores é que cada um seja encontrado fiel."},
{v:3,t:"Quanto a mim, pouco me importa ser julgado por vós ou por tribunal humano; nem eu julgo a mim mesmo."},
{v:4,t:"Porque de nada me acusa a consciência, mas não é por isso que estou justificado: quem me julga é o Senhor."},
{v:5,t:"Portanto, não julgueis nada antes do tempo, até que venha o Senhor, que iluminará o que está escondido nas trevas e manifestará os desígnios dos corações; e então cada um receberá de Deus o seu louvor."},
{s:"A loucura dos apóstolos"},
{v:6,t:"Estas coisas, irmãos, apliquei figuradamente a mim e a Apolo por causa de vós, para que aprendais, em nós, o não ir além do que está escrito, a fim de que ninguém se encha de orgulho, a favor de um contra o outro."},
{v:7,t:"Pois quem te distingue? Que tens tu que não tenhas recebido? E, se recebeste, por que te glorias, como se não tivesses recebido?"},
{v:8,t:"Já estais saciados, já estais ricos, já reinais sem nós! E oxalá reinásseis, para que também nós reinássemos convosco."},
{v:9,t:"Porque me parece que Deus nos expôs, a nós, apóstolos, em último lugar, como condenados à morte; porque nos tornamos espetáculo para o mundo, para os anjos e para os homens.",np:1},
{v:10,t:"Nós, loucos por causa de Cristo, e vós, sábios em Cristo; nós, fracos, e vós, fortes; vós, honrados, e nós, desprezados."},
{v:11,t:"Até a presente hora sofremos fome e sede, andamos maltrapilhos, somos esbofeteados e não temos morada certa;"},
{v:12,t:"e nos afadigamos, trabalhando com as nossas próprias mãos. Injuriados, bendizemos; perseguidos, suportamos;"},
{v:13,t:"caluniados, respondemos com bondade. Tornamo-nos como o lixo do mundo, a escória de todos, até agora."},
{s:"O pai na fé"},
{v:14,t:"Não escrevo estas coisas para vos envergonhar, mas para vos admoestar, como a meus filhos amados."},
{v:15,t:"Porque, ainda que tivésseis dez mil pedagogos em Cristo, não teríeis muitos pais; pois fui eu que vos gerei em Cristo Jesus, por meio do Evangelho.",n:"O pedagogo era o escravo que acompanhava a criança à escola: muitos guias, um só pai."},
{v:16,t:"Rogo a vós, portanto: sede meus imitadores."},
{v:17,t:"Por isso vos enviei Timóteo, que é meu filho amado e fiel no Senhor; ele vos recordará os meus caminhos em Cristo Jesus, como ensino por toda parte, em todas as igrejas."},
{s:"A próxima visita"},
{v:18,t:"Alguns se encheram de orgulho, como se eu não fosse mais a vós."},
{v:19,t:"Mas irei a vós em breve, se o Senhor quiser, e conhecerei, não a palavra dos orgulhosos, mas o seu poder."},
{v:20,t:"Porque o Reino de Deus não consiste em palavra, mas em poder."},
{v:21,t:"Que preferis? Que eu vá a vós com a vara, ou com amor e espírito de mansidão?"}
];

window.TEXTOS_SEED["1corintios"][5] = [
{s:"O incestuoso"},
{v:1,t:"Ouve-se por toda parte que há entre vós fornicação, e fornicação tal que não existe nem entre os gentios: haver quem viva com a mulher do próprio pai."},
{v:2,t:"E vós estais cheios de orgulho! Não devíeis, antes, ter ficado de luto, para que fosse tirado do vosso meio quem praticou tal ação?"},
{v:3,t:"Eu, de minha parte, ausente no corpo mas presente no espírito, já julguei, como se estivesse presente, aquele que assim procedeu:"},
{v:4,t:"em nome do Senhor Jesus, reunidos vós e o meu espírito, com o poder de nosso Senhor Jesus,"},
{v:5,t:"seja esse homem entregue a Satanás para a ruína da carne, a fim de que o espírito seja salvo no dia do Senhor."},
{s:"O fermento velho"},
{v:6,t:"Não é boa a vossa jactância. Não sabeis que um pouco de fermento leveda toda a massa?"},
{v:7,t:"Purificai-vos do fermento velho, para serdes massa nova, como sois ázimos. Porque Cristo, nossa Páscoa, foi imolado."},
{v:8,t:"Celebremos, pois, a festa, não com o fermento velho, nem com o fermento da malícia e da perversidade, mas com os ázimos da sinceridade e da verdade."},
{s:"Não vos misturar com os corruptos"},
{v:9,t:"Escrevi a vós, na carta, que não vos misturásseis com os fornicadores;",n:"Alusão a uma carta anterior do Apóstolo aos coríntios, que não chegou até nós."},
{v:10,t:"não me referia, em absoluto, aos fornicadores deste mundo, ou aos avarentos, ladrões e idólatras; de outro modo, deveríeis sair do mundo."},
{v:11,t:"Mas agora vos escrevo que não vos mistureis com quem, chamando-se irmão, for fornicador, ou avarento, ou idólatra, ou maldizente, ou beberrão, ou ladrão; com alguém assim, nem sequer comais."},
{v:12,t:"Pois cabe a mim julgar os de fora? Não é aos de dentro que vós julgais?"},
{v:13,t:"Os de fora, Deus os julgará. Tirai o mau do meio de vós."}
];

window.TEXTOS_SEED["1corintios"][6] = [
{s:"Demandas entre irmãos"},
{v:1,t:"Quando um de vós tem litígio contra outro, atreve-se a levar a causa aos injustos, e não aos santos?"},
{v:2,t:"Ou não sabeis que os santos julgarão o mundo? E, se o mundo há de ser julgado por vós, sereis indignos de julgar as causas mínimas?"},
{v:3,t:"Não sabeis que julgaremos os anjos? Quanto mais as coisas desta vida!"},
{v:4,t:"Se tiverdes, pois, litígios sobre as coisas desta vida, tomais por juízes os que não contam nada na Igreja?"},
{v:5,t:"Digo isto para vossa vergonha. Será que não há entre vós nenhum sábio, capaz de julgar entre os seus irmãos?"},
{v:6,t:"Mas um irmão vai a juízo contra outro irmão, e isso diante de incrédulos!"},
{v:7,t:"De qualquer modo, já é uma derrota para vós haver litígios entre vós. Por que não preferis sofrer a injustiça? Por que não preferis ser lesados?"},
{v:8,t:"Mas vós mesmos cometeis injustiça e lesais, e isso a irmãos!"},
{s:"Os que não herdarão o Reino"},
{v:9,t:"Ou não sabeis que os injustos não herdarão o Reino de Deus? Não vos enganeis: nem fornicadores, nem idólatras, nem adúlteros, nem efeminados, nem sodomitas,"},
{v:10,t:"nem ladrões, nem avarentos, nem beberrões, nem maldizentes, nem assaltantes herdarão o Reino de Deus."},
{v:11,t:"E isto fostes alguns de vós; mas fostes lavados, mas fostes santificados, mas fostes justificados, no nome do Senhor Jesus Cristo e no Espírito do nosso Deus."},
{s:"O corpo é para o Senhor"},
{v:12,t:"Tudo me é lícito, mas nem tudo convém. Tudo me é lícito, mas eu não me deixarei dominar por coisa alguma.",n:"Tudo me é lícito parece ser uma máxima corrente entre os coríntios, que o Apóstolo cita para corrigir; o mesmo em 10, 23."},
{v:13,t:"Os alimentos são para o ventre, e o ventre, para os alimentos; mas Deus destruirá tanto um como os outros. O corpo, porém, não é para a fornicação, mas para o Senhor, e o Senhor, para o corpo."},
{v:14,t:"E Deus, que ressuscitou o Senhor, também nos ressuscitará pelo seu poder."},
{v:15,t:"Não sabeis que os vossos corpos são membros de Cristo? Tomarei, pois, os membros de Cristo, para os tornar membros de uma prostituta? De modo algum!"},
{v:16,t:"Ou não sabeis que quem se une à prostituta é um só corpo com ela? Porque, diz a Escritura, serão os dois uma só carne."},
{v:17,t:"Mas quem se une ao Senhor é um só espírito com ele."},
{v:18,t:"Fugi da fornicação. Todo pecado que o homem cometer está fora do corpo; mas quem fornica peca contra o próprio corpo."},
{v:19,t:"Ou não sabeis que o vosso corpo é templo do Espírito Santo, que está em vós e que recebestes de Deus, e que não pertenceis a vós mesmos?"},
{v:20,t:"Porque fostes comprados por um preço. Glorificai, pois, a Deus no vosso corpo."}
];

window.TEXTOS_SEED["1corintios"][7] = [
{s:"O matrimônio"},
{v:1,t:"Quanto ao que me escrevestes: é bom para o homem não tocar mulher.",n:"Provavelmente o Apóstolo cita de novo uma frase da carta dos coríntios, para a seguir precisar o seu alcance."},
{v:2,t:"Mas, por causa da fornicação, tenha cada um a sua própria mulher, e tenha cada uma o seu próprio marido."},
{v:3,t:"O marido cumpra o seu dever para com a mulher, e igualmente a mulher para com o marido."},
{v:4,t:"A mulher não dispõe do próprio corpo: quem dispõe é o marido; igualmente o marido não dispõe do próprio corpo: quem dispõe é a mulher."},
{v:5,t:"Não vos priveis um do outro, a não ser de comum acordo, por algum tempo, para vos dedicardes à oração; e depois voltai a estar juntos, para que Satanás não vos tente pela vossa incontinência."},
{v:6,t:"Digo isto como concessão, não como ordem."},
{v:7,t:"Quisera que todos os homens fossem como eu; mas cada um recebe de Deus o seu próprio dom: um de um modo, outro de outro."},
{s:"Aos solteiros e às viúvas"},
{v:8,t:"Aos solteiros e às viúvas digo: é bom para eles permanecerem como eu;"},
{v:9,t:"mas, se não conseguem guardar a continência, casem-se; porque é melhor casar do que arder."},
{s:"Aos casados"},
{v:10,t:"Aos casados ordeno, não eu, mas o Senhor: que a mulher não se separe do marido"},
{v:11,t:"— e, se vier a separar-se, permaneça sem casar ou se reconcilie com o marido — e que o marido não repudie a mulher."},
{s:"Casamento com quem não crê"},
{v:12,t:"Aos demais digo eu, não o Senhor: se um irmão tem mulher incrédula, e ela consente em morar com ele, não a repudie;"},
{v:13,t:"e, se uma mulher tem marido incrédulo, e ele consente em morar com ela, não repudie o marido."},
{v:14,t:"Porque o marido incrédulo é santificado pela mulher, e a mulher incrédula é santificada pelo irmão; de outro modo, os vossos filhos seriam impuros; agora, porém, são santos."},
{v:15,t:"Mas, se o incrédulo quer separar-se, que se separe; em tais casos, o irmão ou a irmã não ficam escravizados; Deus vos chamou à paz.",n:"É o fundamento do chamado privilégio paulino, acolhido pelo direito da Igreja."},
{v:16,t:"Pois como sabes, mulher, se salvarás o teu marido? Ou como sabes, marido, se salvarás a tua mulher?"},
{s:"Cada um permaneça como foi chamado"},
{v:17,t:"De resto, cada um ande como o Senhor lhe repartiu, cada um como Deus o chamou. É assim que ordeno em todas as igrejas."},
{v:18,t:"Alguém foi chamado já circuncidado? Não disfarce a circuncisão. Alguém foi chamado incircunciso? Não se circuncide."},
{v:19,t:"A circuncisão nada é, e a incircuncisão nada é: o que importa é guardar os mandamentos de Deus."},
{v:20,t:"Cada um permaneça na condição em que foi chamado."},
{v:21,t:"Foste chamado sendo escravo? Não te preocupes com isso; mas, se também podes tornar-te livre, aproveita antes a ocasião.",n:"O grego é ambíguo: aproveita antes pode referir-se à liberdade oferecida ou à própria condição de escravo; sigo o sentido mais comum, o da Nova Vulgata."},
{v:22,t:"Porque o escravo que foi chamado no Senhor é um liberto do Senhor; igualmente, o livre que foi chamado é escravo de Cristo."},
{v:23,t:"Fostes comprados por um preço: não vos torneis escravos de homens."},
{v:24,t:"Cada um, irmãos, permaneça diante de Deus na condição em que foi chamado."},
{s:"As virgens"},
{v:25,t:"Quanto às virgens, não tenho mandamento do Senhor; mas dou um parecer, como quem alcançou do Senhor a misericórdia de ser digno de confiança."},
{v:26,t:"Julgo, pois, que isto é bom, por causa da necessidade presente: é bom para o homem permanecer assim."},
{v:27,t:"Estás ligado a uma mulher? Não busques a separação. Estás livre de mulher? Não busques mulher."},
{v:28,t:"Mas, se te casares, não pecas; e, se a virgem se casar, não peca. Contudo, esses terão tribulação na carne, e eu quisera poupar a vós."},
{v:29,t:"Digo isto, irmãos: o tempo é breve. Resta que os que têm mulher sejam como se não a tivessem;"},
{v:30,t:"os que choram, como se não chorassem; os que se alegram, como se não se alegrassem; os que compram, como se não possuíssem;"},
{v:31,t:"os que usam do mundo, como se dele não usassem; porque passa a figura deste mundo."},
{s:"As preocupações deste mundo"},
{v:32,t:"Quero que estejais livres de preocupações. O solteiro preocupa-se com as coisas do Senhor, com o modo de agradar ao Senhor;"},
{v:33,t:"o casado preocupa-se com as coisas do mundo, com o modo de agradar à mulher,"},
{v:34,t:"e está dividido. A mulher sem marido e a virgem preocupam-se com as coisas do Senhor, para serem santas no corpo e no espírito; a casada preocupa-se com as coisas do mundo, com o modo de agradar ao marido."},
{v:35,t:"Digo isto para o vosso próprio proveito, não para vos armar um laço, mas em vista do que é digno e vos une ao Senhor sem distração."},
{v:36,t:"Se alguém julga que age de modo inconveniente com a sua virgem, por ter passado a flor da idade, e que assim deve ser, faça o que quer: não peca; casem-se.",n:"Passagem difícil: entende-se do noivo em relação à sua prometida ou, segundo outros, do pai em relação à filha. Sigo a primeira interpretação, a da Nova Vulgata."},
{v:37,t:"Mas quem está firme no seu coração e, sem estar constrangido, tem domínio da própria vontade, e resolveu no seu coração guardar a sua virgem, fará bem."},
{v:38,t:"De modo que quem se casa com a sua virgem faz bem, e quem não se casa fará melhor."},
{s:"As segundas núpcias"},
{v:39,t:"A mulher está ligada durante todo o tempo em que vive o seu marido; mas, se o marido morrer, fica livre para se casar com quem quiser, contanto que no Senhor."},
{v:40,t:"Contudo, segundo o meu parecer, será mais feliz se permanecer assim; e julgo que também eu tenho o Espírito de Deus."}
];

window.TEXTOS_SEED["1corintios"][8] = [
{s:"A ciência incha, a caridade edifica"},
{v:1,t:"Quanto às carnes imoladas aos ídolos: sabemos que todos temos conhecimento. O conhecimento incha; o amor edifica."},
{v:2,t:"Se alguém julga conhecer alguma coisa, ainda não conheceu como convém conhecer."},
{v:3,t:"Mas, se alguém ama a Deus, esse é conhecido por ele."},
{v:4,t:"Quanto, pois, ao comer das carnes imoladas aos ídolos, sabemos que o ídolo não é nada no mundo e que não há Deus senão um só."},
{v:5,t:"Porque, ainda que haja os chamados deuses, seja no céu, seja na terra — como de fato há muitos deuses e muitos senhores —,"},
{v:6,t:"para nós, contudo, há um só Deus, o Pai, de quem procedem todas as coisas e para quem nós existimos, e um só Senhor, Jesus Cristo, por quem são todas as coisas e por quem nós existimos."},
{s:"O escândalo do irmão fraco"},
{v:7,t:"Mas nem todos têm o conhecimento. Alguns, pelo costume que até agora tiveram com o ídolo, comem dessas carnes como imoladas ao ídolo, e a sua consciência, que é fraca, contamina-se."},
{v:8,t:"Não é um alimento que nos aproximará de Deus: nem, se deixarmos de comer, ficamos com menos, nem, se comermos, ficamos com mais."},
{v:9,t:"Mas vede que esta vossa liberdade não se torne ocasião de queda para os fracos."},
{v:10,t:"Porque, se alguém vir a ti, que tens conhecimento, à mesa num templo de ídolos, a consciência desse, que é fraco, não será encorajada a comer das carnes imoladas aos ídolos?"},
{v:11,t:"E assim, pelo teu conhecimento, perece o fraco, o irmão pelo qual Cristo morreu."},
{v:12,t:"Ora, pecando assim contra os irmãos e ferindo a sua consciência fraca, é contra Cristo que pecais."},
{v:13,t:"Portanto, se um alimento escandaliza o meu irmão, nunca mais comerei carne, para não escandalizar o meu irmão."}
];

window.TEXTOS_SEED["1corintios"][9] = [
{s:"Os direitos do apóstolo"},
{v:1,t:"Não sou livre? Não sou apóstolo? Não vi Jesus, nosso Senhor? Não sois vós a minha obra no Senhor?"},
{v:2,t:"Se para outros não sou apóstolo, para vós ao menos o sou; porque vós sois, no Senhor, o selo do meu apostolado."},
{v:3,t:"A minha defesa perante os que me julgam é esta:"},
{v:4,t:"Não temos direito de comer e beber?"},
{v:5,t:"Não temos direito de levar conosco uma mulher irmã, como os demais apóstolos, os irmãos do Senhor e Cefas?",n:"Mulher irmã: uma mulher crente que acompanhava e servia os apóstolos, como as que seguiam o Senhor (Lc 8, 2-3)."},
{v:6,t:"Ou somente eu e Barnabé não temos direito de deixar de trabalhar?"},
{v:7,t:"Quem jamais serve como soldado à própria custa? Quem planta uma vinha e não come do seu fruto? Quem apascenta um rebanho e não se alimenta do leite do rebanho?"},
{v:8,t:"Digo isto apenas à maneira dos homens? Não o diz também a Lei?"},
{v:9,t:"Pois na Lei de Moisés está escrito: Não amordaçarás o boi que debulha. Acaso é dos bois que Deus se preocupa?"},
{v:10,t:"Não é evidentemente por nós que ele o diz? Sim, por nós foi escrito; porque quem lavra deve lavrar com esperança, e quem debulha, com a esperança de receber a sua parte."},
{v:11,t:"Se nós semeamos para vós os bens espirituais, será demais colhermos dos vossos bens materiais?"},
{s:"Paulo renuncia ao seu direito"},
{v:12,t:"Se outros têm sobre vós esse direito, não o temos nós ainda mais? Contudo, não fizemos uso desse direito; antes, tudo suportamos, para não criar obstáculo ao Evangelho de Cristo."},
{v:13,t:"Não sabeis que os que exercem o serviço sagrado comem do que é do templo, e os que servem ao altar têm a sua parte no altar?"},
{v:14,t:"Assim também o Senhor ordenou aos que anunciam o Evangelho que vivam do Evangelho."},
{v:15,t:"Eu, porém, não fiz uso de nenhuma dessas coisas. E não escrevo isto para que assim se faça comigo; porque para mim seria melhor morrer do que deixar que alguém esvazie este meu motivo de glória."},
{v:16,t:"Porque, se anuncio o Evangelho, não tenho de que me gloriar, pois me foi imposta essa necessidade: ai de mim se eu não evangelizar!"},
{v:17,t:"Se o faço de bom grado, tenho recompensa; se contra a vontade, é uma administração que me foi confiada."},
{v:18,t:"Qual é, então, a minha recompensa? É que, ao evangelizar, eu ofereça gratuitamente o Evangelho, sem usar do direito que o Evangelho me dá."},
{s:"Fez-se tudo para todos"},
{v:19,t:"Porque, sendo livre em relação a todos, fiz-me escravo de todos, para ganhar o maior número possível."},
{v:20,t:"Para os judeus, fiz-me como judeu, a fim de ganhar os judeus; para os que estão sob a Lei, como se eu estivesse sob a Lei — embora eu não esteja sob a Lei —, a fim de ganhar os que estão sob a Lei;"},
{v:21,t:"para os que estão sem a Lei, como se eu estivesse sem a Lei — embora eu não esteja sem a lei de Deus, mas sob a lei de Cristo —, a fim de ganhar os que estão sem a Lei."},
{v:22,t:"Fiz-me fraco para os fracos, a fim de ganhar os fracos. Fiz-me tudo para todos, a fim de salvar alguns, custe o que custar."},
{v:23,t:"E tudo faço por causa do Evangelho, para me tornar participante dele."},
{s:"A corrida no estádio"},
{v:24,t:"Não sabeis que os que correm no estádio, todos correm, mas um só recebe o prêmio? Correi de tal modo que o alcanceis."},
{v:25,t:"Todo atleta se abstém de tudo; eles, para receber uma coroa corruptível; nós, uma incorruptível."},
{v:26,t:"Eu, portanto, corro assim: não como quem corre sem rumo; luto assim: não como quem golpeia o ar."},
{v:27,t:"Mas trato duramente o meu corpo e o reduzo à servidão, para que, tendo pregado aos outros, não venha eu mesmo a ser reprovado."}
];

window.TEXTOS_SEED["1corintios"][10] = [
{s:"O exemplo dos padres no deserto"},
{v:1,t:"Não quero que ignoreis, irmãos, que os nossos pais estiveram todos sob a nuvem, e todos passaram através do mar,"},
{v:2,t:"e todos foram batizados em Moisés, na nuvem e no mar;"},
{v:3,t:"todos comeram do mesmo alimento espiritual"},
{v:4,t:"e todos beberam da mesma bebida espiritual; porque bebiam de uma rocha espiritual que os seguia, e a rocha era Cristo.",n:"O Apóstolo retoma a tradição judaica da rocha que acompanhava Israel no deserto e a lê como figura de Cristo."},
{v:5,t:"Contudo, Deus não se agradou da maioria deles, pois os seus corpos ficaram estendidos no deserto."},
{v:6,t:"Essas coisas aconteceram como figuras para nós, a fim de que não cobicemos coisas más, como eles cobiçaram.",np:1},
{v:7,t:"Nem vos torneis idólatras, como alguns deles, conforme está escrito: O povo sentou-se para comer e beber, e levantou-se para se divertir."},
{v:8,t:"Nem pratiquemos a fornicação, como alguns deles a praticaram, e caíram, num só dia, vinte e três mil.",n:"Em Nm 25, 9 o número é de vinte e quatro mil; o Apóstolo cita de memória, segundo o costume rabínico."},
{v:9,t:"Nem tentemos a Cristo, como alguns deles o tentaram, e pereceram pelas serpentes."},
{v:10,t:"Nem murmureis, como alguns deles murmuraram, e pereceram pelo exterminador."},
{v:11,t:"Essas coisas lhes aconteciam em figura, e foram escritas para advertência de nós, aos quais chegou o fim dos séculos.",np:1},
{v:12,t:"Portanto, quem julga estar de pé, veja que não caia."},
{v:13,t:"Não vos sobreveio tentação que não fosse humana; e Deus é fiel: ele não permitirá que sejais tentados acima das vossas forças, mas, com a tentação, dará também a saída, para que possais suportar."},
{s:"Fugi da idolatria"},
{v:14,t:"Portanto, meus amados, fugi da idolatria."},
{v:15,t:"Falo como a pessoas sensatas: julgai vós mesmos o que digo."},
{v:16,t:"O cálice da bênção, que abençoamos, não é comunhão com o sangue de Cristo? O pão que partimos não é comunhão com o corpo de Cristo?"},
{v:17,t:"Porque há um só pão, nós, embora muitos, somos um só corpo, pois todos participamos do único pão."},
{v:18,t:"Vede Israel segundo a carne: os que comem dos sacrifícios não estão em comunhão com o altar?",np:1},
{v:19,t:"Que digo, então? Que a carne imolada ao ídolo é alguma coisa? Ou que o ídolo é alguma coisa?"},
{v:20,t:"Não; mas o que imolam, imolam aos demônios, e não a Deus; e não quero que entreis em comunhão com os demônios."},
{v:21,t:"Não podeis beber o cálice do Senhor e o cálice dos demônios; não podeis participar da mesa do Senhor e da mesa dos demônios."},
{v:22,t:"Ou queremos provocar o ciúme do Senhor? Somos, acaso, mais fortes do que ele?"},
{s:"Tudo é lícito, nem tudo convém"},
{v:23,t:"Tudo é lícito, mas nem tudo convém. Tudo é lícito, mas nem tudo edifica."},
{v:24,t:"Ninguém busque o próprio interesse, mas o do outro."},
{v:25,t:"Comei de tudo o que se vende no mercado, sem indagar nada por motivo de consciência;"},
{v:26,t:"porque do Senhor é a terra e a sua plenitude."},
{v:27,t:"Se algum dos incrédulos vos convidar, e quiserdes ir, comei de tudo o que vos for servido, sem indagar nada por motivo de consciência."},
{v:28,t:"Mas, se alguém vos disser: Isto foi oferecido em sacrifício, não comais, por causa daquele que avisou e por causa da consciência;",np:1},
{v:29,t:"consciência, digo, não a tua, mas a do outro. Pois por que haveria a minha liberdade de ser julgada por uma consciência alheia?"},
{v:30,t:"Se eu participo com ação de graças, por que hei de ser difamado por aquilo por que dou graças?"},
{v:31,t:"Portanto, quer comais, quer bebais, quer façais qualquer outra coisa, fazei tudo para a glória de Deus."},
{v:32,t:"Não vos torneis motivo de escândalo nem para os judeus, nem para os gregos, nem para a Igreja de Deus,"},
{v:33,t:"como também eu procuro agradar a todos em tudo, não buscando o meu próprio proveito, mas o de muitos, para que sejam salvos."}
];

window.TEXTOS_SEED["1corintios"][11] = [
{s:"Sede meus imitadores"},
{v:1,t:"Sede meus imitadores, como eu o sou de Cristo."},
{s:"O véu das mulheres"},
{v:2,t:"Eu vos louvo porque em tudo vos lembrais de mim e guardais as tradições tal como eu as transmiti a vós."},
{v:3,t:"Quero, porém, que saibais que a cabeça de todo homem é Cristo; a cabeça da mulher é o homem; e a cabeça de Cristo é Deus."},
{v:4,t:"Todo homem que ora ou profetiza com a cabeça coberta desonra a sua cabeça;"},
{v:5,t:"mas toda mulher que ora ou profetiza com a cabeça descoberta desonra a sua cabeça, porque é como se estivesse rapada."},
{v:6,t:"Se a mulher não se cobre, corte também o cabelo; mas, se é vergonhoso para a mulher cortar o cabelo ou rapar-se, que se cubra."},
{v:7,t:"O homem não deve cobrir a cabeça, porque é imagem e glória de Deus; a mulher, porém, é glória do homem."},
{v:8,t:"Porque o homem não veio da mulher, mas a mulher, do homem;"},
{v:9,t:"nem o homem foi criado por causa da mulher, mas a mulher, por causa do homem."},
{v:10,t:"Por isso a mulher deve trazer sobre a cabeça um sinal de autoridade, por causa dos anjos.",n:"Literalmente, deve ter autoridade sobre a cabeça: o véu como sinal. A menção dos anjos, presentes à assembleia litúrgica, permanece de interpretação discutida."},
{v:11,t:"Contudo, no Senhor, nem a mulher existe sem o homem, nem o homem, sem a mulher;"},
{v:12,t:"porque, assim como a mulher veio do homem, assim também o homem nasce da mulher; e tudo vem de Deus."},
{v:13,t:"Julgai vós mesmos: é conveniente que a mulher ore a Deus com a cabeça descoberta?"},
{v:14,t:"A própria natureza não vos ensina que é desonra para o homem usar cabelos compridos,"},
{v:15,t:"mas que, para a mulher, usar cabelos compridos é uma glória? Porque a cabeleira lhe foi dada como véu."},
{v:16,t:"Se, porém, alguém quiser ser contencioso, nós não temos tal costume, nem as igrejas de Deus."},
{s:"As divisões nas reuniões"},
{v:17,t:"Ao dar estas instruções, não vos louvo, porque as vossas reuniões não são para melhor, mas para pior."},
{v:18,t:"Em primeiro lugar, ouço que, quando vos reunis em assembleia, há divisões entre vós; e em parte o creio."},
{v:19,t:"Porque é preciso que haja entre vós até partidos, para que se tornem manifestos entre vós os que são aprovados."},
{v:20,t:"Quando, pois, vos reunis, já não é para comer a Ceia do Senhor;"},
{v:21,t:"porque cada um se antecipa a comer a própria ceia, e um passa fome, enquanto outro se embriaga."},
{v:22,t:"Acaso não tendes casas para comer e beber? Ou desprezais a Igreja de Deus e envergonhais os que nada têm? Que direi a vós? Devo louvar-vos? Nisto não vos louvo."},
{s:"A ceia do Senhor"},
{v:23,t:"Porque eu recebi do Senhor o que também transmiti a vós: que o Senhor Jesus, na noite em que foi entregue, tomou o pão"},
{v:24,t:"e, tendo dado graças, o partiu e disse: Isto é o meu corpo, que é por vós; fazei isto em minha memória."},
{v:25,t:"Do mesmo modo, depois de cear, tomou também o cálice, dizendo: Este cálice é a nova aliança no meu sangue; fazei isto, todas as vezes que o beberdes, em minha memória."},
{v:26,t:"Porque, todas as vezes que comerdes este pão e beberdes o cálice, anunciais a morte do Senhor, até que ele venha."},
{s:"Examine-se cada um a si mesmo"},
{v:27,t:"Portanto, quem comer o pão ou beber o cálice do Senhor indignamente será réu do corpo e do sangue do Senhor."},
{v:28,t:"Examine-se, pois, o homem a si mesmo, e assim coma do pão e beba do cálice;"},
{v:29,t:"porque quem come e bebe sem discernir o corpo, come e bebe a própria condenação."},
{v:30,t:"Por isso há entre vós muitos fracos e doentes, e vários já adormeceram."},
{v:31,t:"Se nós examinássemos a nós mesmos, não seríamos julgados;"},
{v:32,t:"mas, quando somos julgados pelo Senhor, somos corrigidos, para não sermos condenados com o mundo."},
{v:33,t:"Portanto, meus irmãos, quando vos reunirdes para comer, esperai uns pelos outros."},
{v:34,t:"Se alguém tem fome, coma em casa, para que não vos reunais para a condenação. As demais coisas, eu as ordenarei quando for."}
];

window.TEXTOS_SEED["1corintios"][12] = [
{s:"Os dons espirituais"},
{v:1,t:"Quanto aos dons espirituais, irmãos, não quero que sejais ignorantes."},
{v:2,t:"Sabeis que, quando éreis gentios, éreis arrastados, conforme vos levavam, aos ídolos mudos."},
{v:3,t:"Por isso vos declaro: ninguém, falando no Espírito de Deus, diz: Jesus seja maldito; e ninguém pode dizer: Jesus é o Senhor, senão no Espírito Santo."},
{s:"Diversidade de dons, um só Espírito"},
{v:4,t:"Há diversidade de dons, mas o Espírito é o mesmo;"},
{v:5,t:"há diversidade de ministérios, mas o Senhor é o mesmo;"},
{v:6,t:"há diversidade de operações, mas é o mesmo Deus que opera tudo em todos."},
{v:7,t:"A cada um é dada a manifestação do Espírito em vista do bem comum."},
{v:8,t:"A um é dada, pelo Espírito, a palavra de sabedoria; a outro, a palavra de conhecimento, segundo o mesmo Espírito;",np:1},
{v:9,t:"a outro, a fé, no mesmo Espírito; a outro, dons de curas, no único Espírito;"},
{v:10,t:"a outro, operações de milagres; a outro, profecia; a outro, discernimento de espíritos; a outro, variedade de línguas; a outro, interpretação de línguas."},
{v:11,t:"Mas tudo isto opera o único e mesmo Espírito, que distribui a cada um, em particular, como quer."},
{s:"Um corpo e muitos membros"},
{v:12,t:"Porque, assim como o corpo é um e tem muitos membros, e todos os membros do corpo, embora muitos, são um só corpo, assim também Cristo."},
{v:13,t:"Pois num só Espírito todos nós fomos batizados para formar um só corpo — judeus ou gregos, escravos ou livres —, e a todos foi dado beber um só Espírito."},
{v:14,t:"Também o corpo não é um só membro, mas muitos."},
{v:15,t:"Se o pé disser: Como não sou mão, não sou do corpo, nem por isso deixa de ser do corpo."},
{v:16,t:"E, se a orelha disser: Como não sou olho, não sou do corpo, nem por isso deixa de ser do corpo."},
{v:17,t:"Se todo o corpo fosse olho, onde estaria a audição? Se todo fosse audição, onde, o olfato?"},
{v:18,t:"Mas Deus dispôs os membros no corpo, cada um deles como quis."},
{v:19,t:"Se todos fossem um só membro, onde estaria o corpo?"},
{v:20,t:"Assim, há muitos membros, mas um só corpo."},
{v:21,t:"O olho não pode dizer à mão: Não preciso de ti; nem a cabeça, aos pés: Não preciso de vós."},
{v:22,t:"Muito pelo contrário: os membros do corpo que parecem mais fracos são necessários,"},
{v:23,t:"e os que julgamos menos honrosos no corpo, a esses cercamos de maior honra; e os nossos membros menos decorosos são tratados com maior decoro,"},
{v:24,t:"de que não precisam os nossos membros decorosos. Mas Deus compôs o corpo dando maior honra ao que dela tem falta,"},
{v:25,t:"para que não haja divisão no corpo, mas os membros tenham o mesmo cuidado uns pelos outros."},
{v:26,t:"Se um membro sofre, todos os membros sofrem com ele; se um membro é honrado, todos os membros se alegram com ele."},
{s:"Vós sois o corpo de Cristo"},
{v:27,t:"Ora, vós sois o corpo de Cristo e, cada um por sua parte, seus membros."},
{v:28,t:"E Deus estabeleceu na Igreja, em primeiro lugar, apóstolos; em segundo, profetas; em terceiro, mestres; depois, milagres; depois, dons de curas, assistências, governos, variedades de línguas."},
{v:29,t:"Acaso são todos apóstolos? Todos, profetas? Todos, mestres? Todos operam milagres?"},
{v:30,t:"Têm todos dons de curas? Falam todos em línguas? Todos interpretam?"},
{v:31,t:"Aspirai, porém, aos dons maiores. E eu vos mostro ainda um caminho que ultrapassa todos."}
];

window.TEXTOS_SEED["1corintios"][13] = [
{s:"Sem a caridade, nada sou"},
{v:1,t:"Ainda que eu fale as línguas dos homens e dos anjos, se não tiver amor, sou como bronze que soa ou címbalo que retine.",n:"Amor traduz agape, que a tradição latina verteu por caritas, caridade: o amor sobrenatural, dom de Deus."},
{v:2,t:"Ainda que eu tenha o dom de profecia e conheça todos os mistérios e toda a ciência, ainda que eu tenha toda a fé, a ponto de transportar montanhas, se não tiver amor, nada sou."},
{v:3,t:"Ainda que eu distribua todos os meus bens e entregue o meu corpo para ser queimado, se não tiver amor, nada disso me aproveita.",n:"Alguns manuscritos antigos leem: e entregue o meu corpo para me gloriar; sigo a leitura tradicional, a da Nova Vulgata."},
{s:"A caridade é paciente"},
{v:4,t:"O amor é paciente, o amor é benigno; não é invejoso, não é jactancioso, não se incha de orgulho;"},
{v:5,t:"não faz nada de inconveniente, não busca o próprio interesse, não se irrita, não leva em conta o mal;"},
{v:6,t:"não se alegra com a injustiça, mas se alegra com a verdade;"},
{v:7,t:"tudo desculpa, tudo crê, tudo espera, tudo suporta."},
{s:"A caridade não acaba nunca"},
{v:8,t:"O amor jamais acaba. As profecias desaparecerão, as línguas cessarão, a ciência desaparecerá;"},
{v:9,t:"porque conhecemos em parte e profetizamos em parte."},
{v:10,t:"Quando vier o que é perfeito, desaparecerá o que é em parte."},
{v:11,t:"Quando eu era criança, falava como criança, pensava como criança, raciocinava como criança; quando me tornei homem, deixei o que era de criança."},
{v:12,t:"Agora vemos em espelho, de maneira obscura; então veremos face a face. Agora conheço em parte; então conhecerei como sou conhecido.",n:"De maneira obscura é, literalmente, em enigma; os espelhos antigos, de metal polido, davam uma imagem imperfeita."},
{v:13,t:"Agora, portanto, permanecem a fé, a esperança e o amor, estes três; mas o maior deles é o amor."}
];

window.TEXTOS_SEED["1corintios"][14] = [
{s:"Profecia e dom das línguas"},
{v:1,t:"Buscai o amor; aspirai também aos dons espirituais, sobretudo ao de profetizar."},
{v:2,t:"Porque quem fala em línguas não fala aos homens, mas a Deus: ninguém o entende, e ele diz coisas misteriosas no Espírito."},
{v:3,t:"Mas quem profetiza fala aos homens: edifica, exorta e consola."},
{v:4,t:"Quem fala em línguas edifica a si mesmo; quem profetiza edifica a Igreja."},
{v:5,t:"Quisera que todos vós falásseis em línguas, mas ainda mais que profetizásseis; porque quem profetiza é maior do que quem fala em línguas, a não ser que este interprete, para que a Igreja receba edificação."},
{s:"Falar de modo inteligível"},
{v:6,t:"Agora, irmãos, se eu for a vós falando em línguas, em que vos aproveitarei, se não vos falar por revelação, ou ciência, ou profecia, ou doutrina?"},
{v:7,t:"É o que acontece com os instrumentos inanimados que emitem som, como a flauta ou a cítara: se não derem sons distintos, como se reconhecerá o que se toca na flauta ou na cítara?"},
{v:8,t:"E, se a trombeta der um som confuso, quem se preparará para a batalha?"},
{v:9,t:"Assim também vós: se com a língua não proferirdes palavra inteligível, como se saberá o que dizeis? Estareis falando ao vento."},
{v:10,t:"Há no mundo não sei quantas espécies de sons, e nada é sem som."},
{v:11,t:"Mas, se eu não conhecer o valor do som, serei um estrangeiro para quem fala, e quem fala será um estrangeiro para mim."},
{v:12,t:"Assim também vós: já que aspirais aos dons do Espírito, procurai tê-los em abundância para a edificação da Igreja."},
{v:13,t:"Por isso, quem fala em línguas ore para que possa interpretar."},
{v:14,t:"Porque, se oro em línguas, o meu espírito ora, mas a minha mente fica sem fruto."},
{v:15,t:"Que fazer, então? Orarei com o espírito, mas orarei também com a mente; salmodiarei com o espírito, mas salmodiarei também com a mente."},
{v:16,t:"De outro modo, se bendisseres apenas com o espírito, como dirá o Amém à tua ação de graças aquele que ocupa o lugar do simples ouvinte, se não sabe o que dizes?"},
{v:17,t:"Tu, de fato, dás graças muito bem, mas o outro não é edificado."},
{v:18,t:"Dou graças a Deus por falar em línguas mais do que todos vós;"},
{v:19,t:"mas, na assembleia, prefiro dizer cinco palavras com a minha mente, para instruir também os outros, a dez mil palavras em línguas."},
{s:"Sinal para os que não creem"},
{v:20,t:"Irmãos, não sejais crianças no juízo; sede crianças na malícia, mas adultos no juízo."},
{v:21,l:["Na Lei está escrito:","Por homens de outras línguas e por lábios de estrangeiros","falarei a este povo,","e nem assim me ouvirão, diz o Senhor."]},
{v:22,t:"De modo que as línguas são um sinal, não para os que creem, mas para os incrédulos; a profecia, porém, não é para os incrédulos, mas para os que creem."},
{v:23,t:"Se, pois, a Igreja inteira se reunir e todos falarem em línguas, e entrarem simples ouvintes ou incrédulos, não dirão que estais loucos?"},
{v:24,t:"Mas, se todos profetizarem e entrar algum incrédulo ou simples ouvinte, ele é convencido por todos, é julgado por todos;"},
{v:25,t:"os segredos do seu coração tornam-se manifestos e, prostrando-se com o rosto em terra, adorará a Deus, proclamando: Deus está verdadeiramente no meio de vós."},
{s:"A ordem nas assembleias"},
{v:26,t:"Que fazer, então, irmãos? Quando vos reunis, cada um tem um salmo, uma doutrina, uma revelação, uma língua, uma interpretação: tudo se faça para a edificação."},
{v:27,t:"Se alguém falar em línguas, que sejam dois, ou no máximo três, e cada um por sua vez, e um interprete;"},
{v:28,t:"mas, se não houver intérprete, cale-se na assembleia e fale consigo mesmo e com Deus."},
{v:29,t:"Quanto aos profetas, falem dois ou três, e os outros julguem."},
{v:30,t:"Se outro, que está sentado, receber uma revelação, cale-se o primeiro."},
{v:31,t:"Porque todos podeis profetizar, um por um, para que todos aprendam e todos sejam exortados."},
{v:32,t:"Os espíritos dos profetas estão sujeitos aos profetas,"},
{v:33,t:"porque Deus não é Deus de desordem, mas de paz. Como em todas as igrejas dos santos,"},
{v:34,t:"as mulheres estejam caladas nas assembleias, porque não lhes é permitido falar; estejam submissas, como também diz a Lei."},
{v:35,t:"Se querem aprender alguma coisa, perguntem em casa aos seus maridos; porque é inconveniente para a mulher falar na assembleia."},
{v:36,t:"Acaso a palavra de Deus saiu de vós? Ou chegou somente a vós?"},
{s:"Conclusão"},
{v:37,t:"Se alguém se julga profeta ou espiritual, reconheça que as coisas que vos escrevo são mandamento do Senhor."},
{v:38,t:"Se alguém o ignora, será ignorado."},
{v:39,t:"Portanto, meus irmãos, aspirai ao dom de profetizar e não impeçais que se fale em línguas."},
{v:40,t:"Mas faça-se tudo com decoro e com ordem."}
];

window.TEXTOS_SEED["1corintios"][15] = [
{s:"O Evangelho que vos preguei"},
{v:1,t:"Eu vos recordo, irmãos, o Evangelho que vos anunciei, que recebestes e no qual permaneceis firmes,"},
{v:2,t:"e pelo qual sois salvos, se o guardais tal como vos anunciei; a não ser que tenhais crido em vão."},
{v:3,t:"Porque vos transmiti, em primeiro lugar, o que também recebi: que Cristo morreu pelos nossos pecados, segundo as Escrituras;"},
{v:4,t:"que foi sepultado; que ressuscitou ao terceiro dia, segundo as Escrituras;"},
{v:5,t:"e que apareceu a Cefas e, depois, aos Doze.",n:"Os versículos 3 a 5 conservam uma das mais antigas fórmulas da fé da Igreja, anterior à própria carta, que o Apóstolo declara ter recebido."},
{v:6,t:"Depois apareceu a mais de quinhentos irmãos de uma só vez, dos quais a maioria vive até hoje, embora alguns tenham adormecido."},
{v:7,t:"Depois apareceu a Tiago e, em seguida, a todos os apóstolos."},
{v:8,t:"Por último, apareceu também a mim, como a um abortivo."},
{v:9,t:"Porque eu sou o menor dos apóstolos, e nem sou digno de ser chamado apóstolo, porque persegui a Igreja de Deus."},
{v:10,t:"Mas, pela graça de Deus, sou o que sou, e a sua graça para comigo não foi vã; antes, trabalhei mais do que todos eles; não eu, porém, mas a graça de Deus comigo."},
{v:11,t:"Portanto, seja eu, sejam eles, assim pregamos, e assim crestes."},
{s:"Se Cristo não ressuscitou"},
{v:12,t:"Ora, se se prega que Cristo ressuscitou dos mortos, como dizem alguns dentre vós que não há ressurreição dos mortos?"},
{v:13,t:"Se não há ressurreição dos mortos, então nem Cristo ressuscitou;"},
{v:14,t:"e, se Cristo não ressuscitou, vã é a nossa pregação, vã também é a vossa fé."},
{v:15,t:"E somos até encontrados como falsas testemunhas de Deus, porque testemunhamos contra Deus que ele ressuscitou a Cristo, a quem não ressuscitou, se de fato os mortos não ressuscitam."},
{v:16,t:"Porque, se os mortos não ressuscitam, nem Cristo ressuscitou;"},
{v:17,t:"e, se Cristo não ressuscitou, é inútil a vossa fé: ainda estais nos vossos pecados."},
{v:18,t:"E também os que adormeceram em Cristo pereceram."},
{v:19,t:"Se é somente para esta vida que temos esperança em Cristo, somos os mais miseráveis de todos os homens."},
{s:"Cristo, primícias dos que morreram"},
{v:20,t:"Mas, de fato, Cristo ressuscitou dos mortos, como primícias dos que adormeceram."},
{v:21,t:"Porque, assim como por um homem veio a morte, também por um homem veio a ressurreição dos mortos."},
{v:22,t:"E, assim como em Adão todos morrem, assim também em Cristo todos serão vivificados."},
{v:23,t:"Cada um, porém, na sua ordem: Cristo, as primícias; depois, os que são de Cristo, na sua vinda;"},
{v:24,t:"em seguida, o fim, quando ele entregar o Reino a Deus e Pai, depois de destruir todo principado e toda autoridade e poder.",np:1},
{v:25,t:"Porque é preciso que ele reine, até que ponha todos os inimigos debaixo dos seus pés."},
{v:26,t:"O último inimigo a ser destruído é a morte."},
{v:27,t:"Porque todas as coisas ele sujeitou debaixo dos seus pés. E, quando diz que todas as coisas estão sujeitas, é claro que se excetua aquele que lhe sujeitou todas as coisas."},
{v:28,t:"E, quando todas as coisas lhe estiverem sujeitas, então também o próprio Filho se sujeitará àquele que lhe sujeitou todas as coisas, para que Deus seja tudo em todos."},
{s:"Por que nos expomos ao perigo?"},
{v:29,t:"De outro modo, que farão os que se batizam pelos mortos? Se os mortos absolutamente não ressuscitam, por que ainda se batizam por eles?",n:"Prática obscura da comunidade de Corinto, que o Apóstolo apenas menciona como argumento, sem aprovar."},
{v:30,t:"E por que também nós nos expomos a perigos a toda hora?"},
{v:31,t:"Cada dia eu morro, irmãos, tão certo como sois a minha glória em Cristo Jesus, nosso Senhor."},
{v:32,t:"Se foi por motivos humanos que lutei com as feras em Éfeso, que proveito tenho? Se os mortos não ressuscitam, comamos e bebamos, porque amanhã morreremos."},
{v:33,t:"Não vos deixeis enganar: as más companhias corrompem os bons costumes.",n:"Verso do poeta cômico grego Menandro, tornado provérbio."},
{v:34,t:"Despertai para a justiça e não pequeis; porque alguns não têm o conhecimento de Deus. Digo isto para vossa vergonha."},
{s:"Como ressuscitam os mortos?"},
{v:35,t:"Mas dirá alguém: Como ressuscitam os mortos? Com que corpo virão?"},
{v:36,t:"Insensato! O que tu semeias não é vivificado, se não morrer;"},
{v:37,t:"e, quando semeias, não semeias o corpo que há de nascer, mas o simples grão, de trigo ou de qualquer outra semente."},
{v:38,t:"Mas Deus lhe dá o corpo como quis, e a cada semente, o seu próprio corpo."},
{v:39,t:"Nem toda carne é a mesma carne: uma é a dos homens, outra a dos animais, outra a das aves, outra a dos peixes."},
{v:40,t:"Há corpos celestes e corpos terrestres; mas uma é a glória dos celestes, outra a dos terrestres."},
{v:41,t:"Uma é a glória do sol, outra a glória da lua, outra a glória das estrelas; e uma estrela difere de outra em glória."},
{s:"Corpo animal e corpo espiritual"},
{v:42,t:"Assim também a ressurreição dos mortos: semeia-se na corrupção, ressuscita na incorrupção;"},
{v:43,t:"semeia-se na desonra, ressuscita na glória; semeia-se na fraqueza, ressuscita no poder;"},
{v:44,t:"semeia-se corpo natural, ressuscita corpo espiritual. Se há corpo natural, há também corpo espiritual.",n:"Corpo natural verte soma psychikon, o corpo animado pela alma natural (cf. a nota a 2, 14); espiritual não significa imaterial, mas totalmente penetrado pelo Espírito."},
{v:45,t:"Assim também está escrito: O primeiro homem, Adão, tornou-se alma vivente; o último Adão, espírito vivificante.",np:1},
{v:46,t:"Mas não é primeiro o espiritual: primeiro é o natural; depois, o espiritual."},
{v:47,t:"O primeiro homem, tirado da terra, é terreno; o segundo homem vem do céu."},
{v:48,t:"Qual o terreno, tais também os terrenos; e, qual o celeste, tais também os celestes."},
{v:49,t:"E, assim como trouxemos a imagem do terreno, traremos também a imagem do celeste."},
{s:"A vitória sobre a morte"},
{v:50,t:"Digo isto, irmãos: carne e sangue não podem herdar o Reino de Deus, nem a corrupção herda a incorrupção."},
{v:51,t:"Eis que vos digo um mistério: nem todos adormeceremos, mas todos seremos transformados,"},
{v:52,t:"num instante, num piscar de olhos, ao som da última trombeta; porque a trombeta soará, os mortos ressuscitarão incorruptíveis, e nós seremos transformados."},
{v:53,t:"Porque é preciso que isto que é corruptível se revista da incorruptibilidade, e que isto que é mortal se revista da imortalidade."},
{v:54,l:["Quando isto que é corruptível se revestir da incorruptibilidade, e isto que é mortal se revestir da imortalidade, então se cumprirá a palavra que está escrita:","A morte foi tragada pela vitória."]},
{v:55,l:["Onde está, ó morte, a tua vitória?","Onde está, ó morte, o teu aguilhão?"]},
{v:56,t:"O aguilhão da morte é o pecado, e a força do pecado é a Lei."},
{v:57,t:"Graças, porém, a Deus, que nos dá a vitória por nosso Senhor Jesus Cristo."},
{v:58,t:"Portanto, meus irmãos amados, sede firmes, inabaláveis, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor."}
];

window.TEXTOS_SEED["1corintios"][16] = [
{s:"A coleta para os santos"},
{v:1,t:"Quanto à coleta em favor dos santos, fazei também vós como determinei às igrejas da Galácia."},
{v:2,t:"No primeiro dia da semana, cada um de vós ponha de parte, em casa, o que puder poupar, para que não se façam coletas quando eu for.",n:"O primeiro dia da semana é o domingo, dia da ressurreição do Senhor, em que os cristãos já se reuniam (cf. At 20, 7)."},
{v:3,t:"Quando eu chegar, enviarei, com cartas, os que aprovardes, para levarem a vossa dádiva a Jerusalém;"},
{v:4,t:"e, se convier que eu também vá, irão comigo."},
{s:"Os planos de Paulo"},
{v:5,t:"Irei a vós depois de passar pela Macedônia, pois passarei pela Macedônia."},
{v:6,t:"Talvez fique convosco, ou até passe o inverno, para que me encaminheis para onde eu tiver de ir."},
{v:7,t:"Não quero, desta vez, ver-vos apenas de passagem; espero permanecer algum tempo convosco, se o Senhor o permitir."},
{v:8,t:"Ficarei em Éfeso até Pentecostes;"},
{v:9,t:"porque se me abriu uma porta grande e eficaz, e os adversários são muitos."},
{s:"Timóteo e Apolo"},
{v:10,t:"Se Timóteo for, cuidai de que esteja sem temor entre vós, porque trabalha na obra do Senhor, como eu."},
{v:11,t:"Portanto, ninguém o despreze. Encaminhai-o em paz, para que venha a mim, porque o espero com os irmãos."},
{v:12,t:"Quanto ao irmão Apolo, roguei muito a ele que fosse a vós com os irmãos, mas de modo algum quis ir agora; irá, porém, quando tiver oportunidade."},
{s:"Recomendações finais"},
{v:13,t:"Vigiai, permanecei firmes na fé, sede varonis, sede fortes."},
{v:14,t:"Tudo entre vós se faça no amor."},
{v:15,t:"Faço um pedido a vós, irmãos: sabeis que a família de Estéfanas são as primícias da Acaia e que se dedicaram ao serviço dos santos;"},
{v:16,t:"sede também vós submissos a pessoas assim e a todo aquele que coopera e trabalha."},
{v:17,t:"Alegro-me com a vinda de Estéfanas, de Fortunato e de Acaico, porque supriram a vossa ausência;"},
{v:18,t:"pois deram descanso ao meu espírito e ao vosso. Reconhecei, portanto, homens assim."},
{s:"Saudações"},
{v:19,t:"As igrejas da Ásia vos saúdam. Áquila e Prisca, com a igreja que se reúne na sua casa, vos saúdam muito no Senhor."},
{v:20,t:"Todos os irmãos vos saúdam. Saudai-vos uns aos outros com o ósculo santo."},
{v:21,t:"A saudação é da minha própria mão: Paulo."},
{v:22,t:"Se alguém não ama o Senhor, seja anátema. Marana tha!",n:"Marana tha, em aramaico: Vem, Senhor! (ou, com outra divisão das palavras, O Senhor vem). Anátema: separado, entregue à maldição."},
{v:23,t:"A graça do Senhor Jesus esteja convosco."},
{v:24,t:"O meu amor está com todos vós, em Cristo Jesus."}
];
