// =====================================================================
// I Crônicas — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["1cronicas"][1] = [
{s:"De Adão a Abraão"},
{v:1,t:"Adão, Set, Enos,",n:"Os livros das Crônicas, que os gregos chamaram Paralipômenos, isto é, as coisas deixadas de lado, releem toda a história de Israel, de Adão até o edito de Ciro, em torno de Davi, do templo e do culto. Foram escritos depois do exílio, talvez por volta de 400 antes de Cristo, por um levita de Jerusalém. Os nove primeiros capítulos são genealogias: resumem a história desde a criação e mostram que a pequena comunidade que voltou do exílio é herdeira de todas as promessas."},
{v:2,t:"Cainã, Malaleel, Jared,"},
{v:3,t:"Henoc, Matusalém, Lamec,"},
{v:4,t:"Noé, Sem, Cam e Jafé."},
{v:5,t:"Filhos de Jafé: Gomer, Magog, Madai, Javã, Tubal, Mosoc e Tiras.",np:1,n:"A lista das nações segue Gênesis 10: toda a humanidade entra na história antes que ela se concentre em Israel."},
{v:6,t:"Filhos de Gomer: Asquenez, Rifat e Togorma."},
{v:7,t:"Filhos de Javã: Elisa, Társis, Quitim e Rodanim."},
{v:8,t:"Filhos de Cam: Cuxe, Mesraim, Fut e Canaã."},
{v:9,t:"Filhos de Cuxe: Sabá, Havilá, Sabata, Regma e Sabataca. Filhos de Regma: Sabá e Dedan."},
{v:10,t:"Cuxe gerou Nemrod, que foi o primeiro homem poderoso na terra."},
{v:11,t:"Mesraim gerou os ludim, os anamim, os laabim, os neftuim,"},
{v:12,t:"os fetrusim e os casluim, dos quais saíram os filisteus, e os caftorim."},
{v:13,t:"Canaã gerou Sidon, seu primogênito, e Het,"},
{v:14,t:"o jebuseu, o amorreu, o gergeseu,"},
{v:15,t:"o heveu, o araceu, o sineu,"},
{v:16,t:"o aradeu, o samareu e o amateu."},
{v:17,t:"Filhos de Sem: Elam, Assur, Arfaxad, Lud e Aram. Filhos de Aram: Us, Hul, Geter e Mes.",np:1},
{v:18,t:"Arfaxad gerou Sala, e Sala gerou Héber."},
{v:19,t:"A Héber nasceram dois filhos: um chamou-se Faleg, porque no seu tempo a terra foi dividida; e seu irmão chamou-se Jectan."},
{v:20,t:"Jectan gerou Elmodad, Salef, Asarmot, Jaré,"},
{v:21,t:"Adoram, Uzal, Decla,"},
{v:22,t:"Ebal, Abimael, Sabá,"},
{v:23,t:"Ofir, Havilá e Jobab: todos estes eram filhos de Jectan."},
{v:24,t:"Sem, Arfaxad, Sala,",np:1},
{v:25,t:"Héber, Faleg, Reu,"},
{v:26,t:"Serug, Nacor, Taré,"},
{v:27,t:"Abrão, que é Abraão.",n:"A linha que vai de Adão a Abraão, em vinte gerações, desemboca na escolha de um homem, com quem começa a história da salvação."},
{s:"Os descendentes de Abraão"},
{v:28,t:"Filhos de Abraão: Isaac e Ismael.",np:1},
{v:29,t:"Estas são as suas gerações: o primogênito de Ismael foi Nabaiot; depois Cedar, Adbeel, Mabsam,"},
{v:30,t:"Masma, Duma, Massa, Hadad, Tema,"},
{v:31,t:"Jetur, Nafis e Cedma. Estes são os filhos de Ismael."},
{v:32,t:"Filhos de Quetura, concubina de Abraão: ela deu à luz Zamran, Jecsan, Madan, Madiã, Jesboc e Sué. Filhos de Jecsan: Sabá e Dedan. Filhos de Dedan: os assurim, os latusim e os loomim.",n:"Os filhos de Dedan vêm de Gênesis 25,3: a Nova Vulgata os acrescenta aqui."},
{v:33,t:"Filhos de Madiã: Efa, Ofer, Henoc, Abida e Eldaa. Todos estes são filhos de Quetura."},
{v:34,t:"Abraão gerou Isaac. Filhos de Isaac: Esaú e Israel.",np:1,n:"O cronista chama Jacó sempre de Israel: é o pai do povo."},
{s:"Os descendentes de Esaú"},
{v:35,t:"Filhos de Esaú: Elifaz, Rauel, Jeús, Ialam e Coré.",np:1,n:"Esta lista resume Gênesis 36."},
{v:36,t:"Filhos de Elifaz: Temã, Omar, Sefo, Gatam, Cenez, Tamna e Amalec."},
{v:37,t:"Filhos de Rauel: Naat, Zara, Sama e Meza."},
{v:38,t:"Filhos de Seir: Lotã, Sobal, Sebeon, Ana, Dison, Eser e Disã.",n:"Seir, a montanha de Edom, era habitada antes pelos hurritas, descendentes de Seir, com quem os de Esaú se misturaram."},
{v:39,t:"Filhos de Lotã: Hori e Hemã; e a irmã de Lotã era Tamna."},
{v:40,t:"Filhos de Sobal: Alvã, Manaat, Ebal, Sefo e Onam. Filhos de Sebeon: Aia e Ana."},
{v:41,t:"Filho de Ana: Dison. Filhos de Dison: Hendã, Esebã, Jetrã e Carã."},
{v:42,t:"Filhos de Eser: Bilã, Zavã e Jacã. Filhos de Disã: Us e Arã."},
{v:43,t:"Estes são os reis que reinaram na terra de Edom, antes que houvesse rei sobre os filhos de Israel: Bela, filho de Beor; a sua cidade chamava-se Denaba.",np:1},
{v:44,t:"Bela morreu, e reinou em seu lugar Jobab, filho de Zara, de Bosra."},
{v:45,t:"Jobab morreu, e reinou em seu lugar Husam, da terra dos temanitas."},
{v:46,t:"Husam morreu, e reinou em seu lugar Adad, filho de Badad, que derrotou os madianitas no território de Moab; a sua cidade chamava-se Avit."},
{v:47,t:"Adad morreu, e reinou em seu lugar Semla, de Masreca."},
{v:48,t:"Semla morreu, e reinou em seu lugar Saul, de Reobot do Rio."},
{v:49,t:"Saul morreu, e reinou em seu lugar Baal-Hanã, filho de Acobor."},
{v:50,t:"Baal-Hanã morreu, e reinou em seu lugar Adad; a sua cidade chamava-se Fau, e a sua mulher chamava-se Meetabel, filha de Matred, filha de Mezaab."},
{v:51,t:"Adad morreu. Os chefes de Edom foram: o chefe Tamna, o chefe Alva, o chefe Jetet,"},
{v:52,t:"o chefe Oolibama, o chefe Ela, o chefe Finon,"},
{v:53,t:"o chefe Cenez, o chefe Temã, o chefe Mabsar,"},
{v:54,t:"o chefe Magdiel e o chefe Iram. Estes foram os chefes de Edom."}
];

window.TEXTOS_SEED["1cronicas"][2] = [
{s:"Os filhos de Israel"},
{v:1,t:"Estes são os filhos de Israel: Rúben, Simeão, Levi, Judá, Issacar e Zabulon,"},
{v:2,t:"Dã, José, Benjamim, Neftali, Gad e Aser."},
{s:"Os descendentes de Judá"},
{v:3,t:"Filhos de Judá: Her, Onã e Sela; estes três lhe nasceram da filha de Sué, a cananeia. Her, primogênito de Judá, foi mau aos olhos do Senhor, e o Senhor o fez morrer.",np:1,n:"O cronista começa pela tribo de Judá, a tribo de Davi, e dedica-lhe mais espaço que a qualquer outra. A história de Judá e Tamar está em Gênesis 38."},
{v:4,t:"Tamar, sua nora, deu-lhe Farés e Zara. Ao todo, os filhos de Judá foram cinco."},
{v:5,t:"Filhos de Farés: Esrom e Hamul."},
{v:6,t:"Filhos de Zara: Zambri, Etã, Hemã, Calcol e Darda: cinco ao todo.",n:"Etã, Hemã, Calcol e Darda são os sábios famosos de 1 Reis 5,11."},
{v:7,t:"Filho de Carmi: Acar, que trouxe a desgraça a Israel, violando o anátema.",n:"Acar é o Acã do livro de Josué (Josué 7). O cronista escreve Acar, que soa como trazer desgraça, akhar em hebraico."},
{v:8,t:"Filho de Etã: Azarias."},
{s:"A família de Davi"},
{v:9,t:"Filhos que nasceram a Esrom: Jerameel, Aram e Caleb.",np:1},
{v:10,t:"Aram gerou Aminadab, e Aminadab gerou Naasson, chefe dos filhos de Judá.",n:"A mesma linhagem aparece no fim do livro de Rute (Rute 4,18-22) e na genealogia de Jesus (Mateus 1,3-6)."},
{v:11,t:"Naasson gerou Salmon, de quem nasceu Booz."},
{v:12,t:"Booz gerou Obed, e Obed gerou Jessé."},
{v:13,t:"Jessé gerou Eliab, o primogênito; o segundo, Abinadab; o terceiro, Samá;"},
{v:14,t:"o quarto, Natanael; o quinto, Radai;"},
{v:15,t:"o sexto, Asom; o sétimo, Davi.",n:"Segundo 1 Samuel 16,10-11, Davi era o oitavo filho. O cronista faz dele o sétimo, número da plenitude."},
{v:16,t:"As irmãs deles foram Sárvia e Abigail. Filhos de Sárvia: Abisai, Joab e Asael, três."},
{v:17,t:"Abigail deu à luz Amasa, cujo pai foi Jeter, o ismaelita."},
{s:"Os descendentes de Caleb"},
{v:18,t:"Caleb, filho de Esrom, teve filhos de sua mulher Azuba; os filhos dela foram Jeriot, Jeser, Sobab e Ardon.",np:1,n:"Este Caleb, descendente de Judá, é o antepassado dos clãs que habitavam o sul de Judá; tem o mesmo nome que o companheiro de Josué."},
{v:19,t:"Quando Azuba morreu, Caleb tomou por mulher Efrata, que lhe deu Hur."},
{v:20,t:"Hur gerou Uri, e Uri gerou Beseleel.",n:"Beseleel, o artista a quem Deus confiou a construção do santuário do deserto (Êxodo 31,2)."},
{v:21,t:"Depois disso, Esrom uniu-se à filha de Maquir, pai de Galaad; tomou-a por mulher quando tinha sessenta anos, e ela lhe deu Segub."},
{v:22,t:"Segub gerou Jair, que possuiu vinte e três cidades na terra de Galaad."},
{v:23,t:"Gessur e Aram tomaram-lhes as aldeias de Jair, com Canat e as suas dependências: sessenta cidades. Todos estes eram filhos de Maquir, pai de Galaad."},
{v:24,t:"Depois da morte de Esrom, Caleb uniu-se a Efrata, mulher de Esrom, seu pai. Esrom tinha também como mulher Abia, que lhe deu Asur, pai de Técua.",n:"Assim a Nova Vulgata, com a versão grega; o hebraico, obscuro, diz: depois da morte de Esrom em Caleb-Efrata. Pai de uma cidade quer dizer fundador ou chefe do clã que a habitava."},
{s:"Os descendentes de Jerameel"},
{v:25,t:"Os filhos de Jerameel, primogênito de Esrom, foram: Ram, o primogênito, Buna, Arã, Asom e Aías.",np:1},
{v:26,t:"Jerameel teve outra mulher, chamada Atara, que foi mãe de Onam."},
{v:27,t:"Os filhos de Ram, primogênito de Jerameel, foram: Moos, Jamin e Acar."},
{v:28,t:"Os filhos de Onam foram Samai e Jada. Filhos de Samai: Nadab e Abisur."},
{v:29,t:"A mulher de Abisur chamava-se Abiail, e deu-lhe Aobã e Molid."},
{v:30,t:"Filhos de Nadab: Saled e Afaim. Saled morreu sem filhos."},
{v:31,t:"Filho de Afaim: Jesi. Jesi gerou Sesã, e Sesã gerou Oolai."},
{v:32,t:"Filhos de Jada, irmão de Samai: Jeter e Jônatas. Jeter morreu sem filhos."},
{v:33,t:"Jônatas gerou Falet e Ziza. Estes foram os filhos de Jerameel."},
{v:34,t:"Sesã não teve filhos, mas só filhas; e tinha um escravo egípcio chamado Jeraa.",np:1},
{v:35,t:"Sesã deu ao seu escravo Jeraa uma filha por mulher, e ela lhe deu Etei.",n:"O escravo estrangeiro, casado com a filha do senhor, entra na linhagem de Judá: as genealogias acolhem também os de fora."},
{v:36,t:"Etei gerou Natã, e Natã gerou Zabad;"},
{v:37,t:"Zabad gerou Oflal, e Oflal gerou Obed."},
{v:38,t:"Obed gerou Jeú, e Jeú gerou Azarias;"},
{v:39,t:"Azarias gerou Heles, e Heles gerou Elasa."},
{v:40,t:"Elasa gerou Sisamoi, e Sisamoi gerou Selum;"},
{v:41,t:"Selum gerou Jecemias, e Jecemias gerou Elisama."},
{s:"Outros descendentes de Caleb"},
{v:42,t:"Filhos de Caleb, irmão de Jerameel: Mesa, o seu primogênito, que foi pai de Zif; e o seu filho Maresa, pai de Hebron.",np:1},
{v:43,t:"Filhos de Hebron: Coré, Tafua, Recém e Samá."},
{v:44,t:"Samá gerou Raam, pai de Jercaam; e Recém gerou Samai."},
{v:45,t:"Filho de Samai: Maon; e Maon foi pai de Bet-Sur."},
{v:46,t:"Efa, concubina de Caleb, deu à luz Harã, Mosa e Gezez; e Harã gerou Gezez."},
{v:47,t:"Filhos de Jaadai: Regém, Joatão, Gesã, Falet, Efa e Saaf."},
{v:48,t:"Maaca, concubina de Caleb, deu à luz Saber e Tarana."},
{v:49,t:"Saaf, pai de Madmena, gerou também Sué, pai de Macbena e pai de Gabaá. A filha de Caleb foi Acsa.",n:"Acsa, a filha que Caleb deu por mulher a Otoniel (Josué 15,16-17)."},
{v:50,t:"Estes foram os filhos de Caleb. Filhos de Hur, primogênito de Efrata: Sobal, pai de Cariat-Iarim,",np:1},
{v:51,t:"Salmon, pai de Belém, e Harif, pai de Bet-Gader.",n:"Salmon, pai de Belém: as genealogias ligam também a cidade de Davi à família de Caleb."},
{v:52,t:"Os filhos de Sobal, pai de Cariat-Iarim, foram: Raaia e metade dos manaatitas,"},
{v:53,t:"e as famílias de Cariat-Iarim: os jetreus, os futeus, os sumateus e os maseraus. Destes saíram os saraítas e os estaolitas."},
{v:54,t:"Filhos de Salmon: Belém, os netofatitas, Atarot-Bet-Joab e metade dos manaatitas, de Saraá;"},
{v:55,t:"e as famílias de Cariat-Séfer, que habitavam em Jabes: os tiratitas, os simeatitas e os sucatitas. Estes são os quenitas, descendentes de Amat, pai da casa de Recab.",n:"Cariat-Séfer: assim a Nova Vulgata; o hebraico diz as famílias dos escribas. Os quenitas e os recabitas, estrangeiros de origem, foram incorporados a Judá."}
];

window.TEXTOS_SEED["1cronicas"][3] = [
{s:"Os filhos de Davi"},
{v:1,t:"Estes são os filhos de Davi que lhe nasceram em Hebron: o primogênito, Amnon, de Aquinoam de Jezrael; o segundo, Daniel, de Abigail de Carmel;",n:"Daniel é o Queleab de 2 Samuel 3,3."},
{v:2,t:"o terceiro, Absalão, filho de Maaca, filha de Tolmai, rei de Gessur; o quarto, Adonias, filho de Hagit;"},
{v:3,t:"o quinto, Safatias, de Abital; o sexto, Jetraam, de Egla, sua mulher."},
{v:4,t:"Seis lhe nasceram em Hebron, onde reinou sete anos e seis meses. Em Jerusalém reinou trinta e três anos."},
{v:5,t:"Os filhos que lhe nasceram em Jerusalém foram estes: Samua, Sobab, Natã e Salomão, quatro de Betsabeia, filha de Amiel;",np:1,n:"Amiel é o Eliam de 2 Samuel 11,3: os dois nomes têm o mesmo sentido."},
{v:6,t:"e ainda Jebaar, Elisama, Elifalet,"},
{v:7,t:"Noga, Nefeg, Jafia,"},
{v:8,t:"Elisama, Eliada e Elifalet: nove."},
{v:9,t:"Todos estes eram filhos de Davi, sem contar os filhos das concubinas; e Tamar era irmã deles."},
{s:"Os reis de Judá"},
{v:10,t:"O filho de Salomão foi Roboão; seu filho, Abias; seu filho, Asa; seu filho, Josafá;",np:1,n:"A lista dos reis de Judá, de pai para filho, sem interrupção: é a prova da fidelidade de Deus à promessa feita a Davi."},
{v:11,t:"seu filho, Jorão; seu filho, Ocozias; seu filho, Joás;"},
{v:12,t:"seu filho, Amasias; seu filho, Azarias; seu filho, Joatão;"},
{v:13,t:"seu filho, Acaz; seu filho, Ezequias; seu filho, Manassés;"},
{v:14,t:"seu filho, Amon; seu filho, Josias."},
{v:15,t:"Filhos de Josias: o primogênito, Joanã; o segundo, Joaquim; o terceiro, Sedecias; o quarto, Selum.",n:"Selum é o nome que Jeremias dá a Joacaz (Jeremias 22,11)."},
{v:16,t:"Filhos de Joaquim: Jeconias, seu filho; Sedecias, seu filho."},
{s:"Os descendentes de Jeconias"},
{v:17,t:"Filhos de Jeconias, o cativo: Salatiel, seu filho,",np:1,n:"A dinastia de Davi continua depois do exílio: as genealogias a acompanham até o tempo do cronista, umas oito gerações depois de Jeconias."},
{v:18,t:"Melquiram, Fadaías, Senaser, Jecemias, Hosama e Nadabias."},
{v:19,t:"De Fadaías nasceram Zorobabel e Semei. Zorobabel gerou Mosolam, Hananias e Salomit, irmã deles;",n:"Em outros lugares, Zorobabel, que conduzirá a volta do exílio, é chamado filho de Salatiel (Esdras 3,2; Ageu 1,1; Mateus 1,12)."},
{v:20,t:"e também Hasaba, Ool, Baraquias, Hasadias e Josab-Hesed: cinco."},
{v:21,t:"Filhos de Hananias: Feltias, Jesaías, Rafaías, Arnã, Abdias e Secenias."},
{v:22,t:"Filhos de Secenias: Semeías, Hatus, Igal, Baria, Naarias e Safat: seis."},
{v:23,t:"Filhos de Naarias: Elioenai, Ezequias e Ezricam: três."},
{v:24,t:"Filhos de Elioenai: Odovias, Eliasib, Feleías, Acub, Joanã, Dalaías e Anani: sete."}
];

window.TEXTOS_SEED["1cronicas"][4] = [
{s:"Outros clãs de Judá"},
{v:1,t:"Filhos de Judá: Farés, Esrom, Carmi, Hur e Sobal.",n:"Não são filhos no sentido estrito, mas uma linha de descendência: as genealogias bíblicas chamam filhos também os descendentes distantes."},
{v:2,t:"Reaías, filho de Sobal, gerou Jaat, e de Jaat nasceram Aumai e Laad: estas são as famílias dos saraítas."},
{v:3,t:"Estes são os de Etam: Jezrael, Jesema e Jedebos; e a irmã deles chamava-se Asalelfuni."},
{v:4,t:"Fanuel foi pai de Gedor, e Ezer, pai de Hosa. Estes são os filhos de Hur, primogênito de Efrata, pai de Belém."},
{v:5,t:"Asur, pai de Técua, teve duas mulheres: Halaa e Naara.",np:1},
{v:6,t:"Naara deu-lhe Ozam, Héfer, Temani e Aastari. Estes são os filhos de Naara."},
{v:7,t:"Filhos de Halaa: Seret, Soar e Etnã."},
{v:8,t:"Cos gerou Anob, Sobeba e as famílias de Aarel, filho de Arum."},
{s:"A oração de Jabes"},
{v:9,t:"Jabes foi mais ilustre que os seus irmãos; sua mãe lhe dera o nome de Jabes, dizendo: Porque o dei à luz com dor.",np:1,n:"Jabes soa em hebraico como dor, otsev, com as letras trocadas. No meio das listas de nomes, o cronista conta a história de um homem que transformou o nome de dor numa oração."},
{v:10,t:"Jabes invocou o Deus de Israel, dizendo: Ah, se me abençoares, se alargares o meu território, se a tua mão estiver comigo e me livrares do mal, para que eu não seja atormentado! E Deus lhe concedeu o que tinha pedido."},
{v:11,t:"Quelub, irmão de Suaa, gerou Mair, que foi pai de Eston.",np:1},
{v:12,t:"Eston gerou Bet-Rafa, Fasea e Teína, pai de Ir-Naás, isto é, a cidade de Naás. Estes são os homens de Reca."},
{v:13,t:"Filhos de Cenez: Otoniel e Saraías. Filhos de Otoniel: Hatat e Maonati.",n:"Otoniel, o primeiro dos juízes (Juízes 3,9-11)."},
{v:14,t:"Maonati gerou Ofra; e Saraías gerou Joab, pai de Ge-Harasim, isto é, o vale dos Artesãos, porque eram artesãos."},
{v:15,t:"Filhos de Caleb, filho de Jefoné: Hir, Ela e Naam. Filho de Ela: Cenez."},
{v:16,t:"Filhos de Jalelel: Zif, Zifa, Tiria e Asarel."},
{v:17,t:"Filhos de Ezra: Jeter, Mered, Éfer e Jalon. Jeter gerou Míriam, Samai e Jesba, pai de Estemo."},
{v:18,t:"Estes são os filhos de Bítia, filha do faraó, com quem Mered se casou: ela deu à luz Jared, pai de Gedor, Héber, pai de Soco, e Jecutiel, pai de Zanoa.",n:"A Nova Vulgata reordena as frases dos versículos 17 e 18, que no hebraico estão fora de lugar. Uma princesa egípcia entra na linhagem de Judá."},
{v:19,t:"Filhos da sua mulher judia, irmã de Naam, pai de Ceila: Dalaías e Simeão, pai de Joman. Filhos de Naam, pai de Ceila: os garmitas e Estemo, dos maacatitas."},
{v:20,t:"Filhos de Simão: Amnon, Rina, Ben-Hanã e Tilon. Filhos de Jesi: Zoet e Ben-Zoet."},
{v:21,t:"Filhos de Sela, filho de Judá: Her, pai de Leca; Laada, pai de Maresa; e as famílias da casa dos tecelões de linho fino, em Bet-Asbea;",np:1},
{v:22,t:"Joquim, os homens de Cozeba, Joás e Saraf, que dominaram em Moab e depois voltaram a Belém. Mas são coisas antigas."},
{v:23,t:"Eram oleiros, e habitavam em Netaim e em Gedera; moravam ali junto do rei, trabalhando para ele.",n:"Os oleiros do rei: foram encontrados muitos jarros marcados com o selo real de Judá, fabricados em oficinas da coroa."},
{s:"Os descendentes de Simeão"},
{v:24,t:"Filhos de Simeão: Namuel, Jamin, Jarib, Zara e Saul;",np:1,n:"A tribo de Simeão, pouco numerosa, vivia dentro do território de Judá, no Negueb, e acabou absorvida por ele (Josué 19,1-9)."},
{v:25,t:"Selum, seu filho; Mabsam, seu filho; Masma, seu filho."},
{v:26,t:"Filhos de Masma: Hamuel, seu filho; Zacur, seu filho; Semei, seu filho."},
{v:27,t:"Semei teve dezesseis filhos e seis filhas; mas os seus irmãos não tiveram muitos filhos, e todas as suas famílias juntas não chegaram ao número dos filhos de Judá."},
{v:28,t:"Habitaram em Bersabeia, em Molada, em Hasar-Sual,"},
{v:29,t:"em Bala, em Esem, em Tolad,"},
{v:30,t:"em Batuel, em Horma, em Siceleg,"},
{v:31,t:"em Bet-Marcabot, em Hasar-Susim, em Bet-Berai e em Saarim. Estas foram as suas cidades até o reinado de Davi."},
{v:32,t:"As suas aldeias eram Etam, Ain, Remon, Toquen e Asã: cinco cidades,"},
{v:33,t:"com todas as povoações que havia em volta destas cidades, até Baal. Esta é a sua morada e a sua genealogia."},
{v:34,t:"Masobab, Jemlec, Josa, filho de Amasias,",np:1},
{v:35,t:"Joel, Jeú, filho de Josabias, filho de Saraías, filho de Asiel,"},
{v:36,t:"Elioenai, Jacoba, Isuaías, Asaías, Adiel, Isimiel, Banaías,"},
{v:37,t:"Ziza, filho de Sefei, filho de Alon, filho de Jedaías, filho de Semri, filho de Samaías."},
{v:38,t:"Estes, inscritos pelo nome, eram chefes nas suas famílias; e as suas casas se multiplicaram muito."},
{v:39,t:"Foram até a entrada de Gedor, a leste do vale, em busca de pastagens para os seus rebanhos."},
{v:40,t:"Encontraram pastagens férteis e boas, e uma terra vasta, tranquila e segura; porque antes tinham morado ali descendentes de Cam."},
{v:41,t:"Estes homens, inscritos pelo nome, vieram no tempo de Ezequias, rei de Judá, atacaram as tendas deles e os meunitas que ali se encontravam, e os exterminaram até hoje; e habitaram em lugar deles, porque encontraram ali pastagens para os seus rebanhos."},
{v:42,t:"Alguns dos filhos de Simeão, quinhentos homens, foram para a montanha de Seir, tendo como chefes Feltias, Naarias, Rafaías e Oziel, filhos de Jesi;"},
{v:43,t:"e bateram o resto dos amalecitas que tinham escapado, e habitaram ali até hoje."}
];
