// =====================================================================
// I Crônicas — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["1cronicas"][1] = [
{s:"De Adão a Abraão"},
{v:1,t:"Adão, Set, Enos,",n:"Os livros das Crônicas, que os gregos chamaram Paralipômenos, isto é, as coisas deixadas de lado, releem toda a história de Israel, de Adão até o edito de Ciro, em torno de Davi, do templo e do culto. Foram escritos depois do exílio, talvez por volta de 400 antes de Cristo, por um levita de Jerusalém. Os nove primeiros capítulos são genealogias: resumem a história desde a criação e mostram que a pequena comunidade que voltou do exílio é herdeira de todas as promessas."},
{v:2,t:"Cainã, Malaleel, Jared,"},
{v:3,t:"Henoc, Matusalém, Lamec,"},
{v:4,t:"Noé, Sem, Cam e Jafé."},
{v:5,t:"Filhos de Jafé: Gomer, Magog, Madai, Javã, Tubal, Mosoc e Tiras.",np:1,n:"A lista das nações segue Gênesis 10: toda a humanidade entra na história antes que ela se concentre em Israel."},
{v:6,t:"Filhos de Gomer: Asquenez, Rifat e Togorma."},
{v:7,t:"Filhos de Javã: Elisa, Társis, Quitim e Rodanim."},
{v:8,t:"Filhos de Cam: Cuxe, Mesraim, Fut e Canaã."},
{v:9,t:"Filhos de Cuxe: Sabá, Havilá, Sabata, Regma e Sabataca. Filhos de Regma: Sabá e Dedan."},
{v:10,t:"Cuxe gerou Nemrod, que foi o primeiro homem poderoso na terra."},
{v:11,t:"Mesraim gerou os ludim, os anamim, os laabim, os neftuim,"},
{v:12,t:"os fetrusim e os casluim, dos quais saíram os filisteus, e os caftorim."},
{v:13,t:"Canaã gerou Sidon, seu primogênito, e Het,"},
{v:14,t:"o jebuseu, o amorreu, o gergeseu,"},
{v:15,t:"o heveu, o araceu, o sineu,"},
{v:16,t:"o aradeu, o samareu e o amateu."},
{v:17,t:"Filhos de Sem: Elam, Assur, Arfaxad, Lud e Aram. Filhos de Aram: Us, Hul, Geter e Mes.",np:1},
{v:18,t:"Arfaxad gerou Sala, e Sala gerou Héber."},
{v:19,t:"A Héber nasceram dois filhos: um chamou-se Faleg, porque no seu tempo a terra foi dividida; e seu irmão chamou-se Jectan."},
{v:20,t:"Jectan gerou Elmodad, Salef, Asarmot, Jaré,"},
{v:21,t:"Adoram, Uzal, Decla,"},
{v:22,t:"Ebal, Abimael, Sabá,"},
{v:23,t:"Ofir, Havilá e Jobab: todos estes eram filhos de Jectan."},
{v:24,t:"Sem, Arfaxad, Sala,",np:1},
{v:25,t:"Héber, Faleg, Reu,"},
{v:26,t:"Serug, Nacor, Taré,"},
{v:27,t:"Abrão, que é Abraão.",n:"A linha que vai de Adão a Abraão, em vinte gerações, desemboca na escolha de um homem, com quem começa a história da salvação."},
{s:"Os descendentes de Abraão"},
{v:28,t:"Filhos de Abraão: Isaac e Ismael.",np:1},
{v:29,t:"Estas são as suas gerações: o primogênito de Ismael foi Nabaiot; depois Cedar, Adbeel, Mabsam,"},
{v:30,t:"Masma, Duma, Massa, Hadad, Tema,"},
{v:31,t:"Jetur, Nafis e Cedma. Estes são os filhos de Ismael."},
{v:32,t:"Filhos de Quetura, concubina de Abraão: ela deu à luz Zamran, Jecsan, Madan, Madiã, Jesboc e Sué. Filhos de Jecsan: Sabá e Dedan. Filhos de Dedan: os assurim, os latusim e os loomim.",n:"Os filhos de Dedan vêm de Gênesis 25,3: a Nova Vulgata os acrescenta aqui."},
{v:33,t:"Filhos de Madiã: Efa, Ofer, Henoc, Abida e Eldaa. Todos estes são filhos de Quetura."},
{v:34,t:"Abraão gerou Isaac. Filhos de Isaac: Esaú e Israel.",np:1,n:"O cronista chama Jacó sempre de Israel: é o pai do povo."},
{s:"Os descendentes de Esaú"},
{v:35,t:"Filhos de Esaú: Elifaz, Rauel, Jeús, Ialam e Coré.",np:1,n:"Esta lista resume Gênesis 36."},
{v:36,t:"Filhos de Elifaz: Temã, Omar, Sefo, Gatam, Cenez, Tamna e Amalec."},
{v:37,t:"Filhos de Rauel: Naat, Zara, Sama e Meza."},
{v:38,t:"Filhos de Seir: Lotã, Sobal, Sebeon, Ana, Dison, Eser e Disã.",n:"Seir, a montanha de Edom, era habitada antes pelos hurritas, descendentes de Seir, com quem os de Esaú se misturaram."},
{v:39,t:"Filhos de Lotã: Hori e Hemã; e a irmã de Lotã era Tamna."},
{v:40,t:"Filhos de Sobal: Alvã, Manaat, Ebal, Sefo e Onam. Filhos de Sebeon: Aia e Ana."},
{v:41,t:"Filho de Ana: Dison. Filhos de Dison: Hendã, Esebã, Jetrã e Carã."},
{v:42,t:"Filhos de Eser: Bilã, Zavã e Jacã. Filhos de Disã: Us e Arã."},
{v:43,t:"Estes são os reis que reinaram na terra de Edom, antes que houvesse rei sobre os filhos de Israel: Bela, filho de Beor; a sua cidade chamava-se Denaba.",np:1},
{v:44,t:"Bela morreu, e reinou em seu lugar Jobab, filho de Zara, de Bosra."},
{v:45,t:"Jobab morreu, e reinou em seu lugar Husam, da terra dos temanitas."},
{v:46,t:"Husam morreu, e reinou em seu lugar Adad, filho de Badad, que derrotou os madianitas no território de Moab; a sua cidade chamava-se Avit."},
{v:47,t:"Adad morreu, e reinou em seu lugar Semla, de Masreca."},
{v:48,t:"Semla morreu, e reinou em seu lugar Saul, de Reobot do Rio."},
{v:49,t:"Saul morreu, e reinou em seu lugar Baal-Hanã, filho de Acobor."},
{v:50,t:"Baal-Hanã morreu, e reinou em seu lugar Adad; a sua cidade chamava-se Fau, e a sua mulher chamava-se Meetabel, filha de Matred, filha de Mezaab."},
{v:51,t:"Adad morreu. Os chefes de Edom foram: o chefe Tamna, o chefe Alva, o chefe Jetet,"},
{v:52,t:"o chefe Oolibama, o chefe Ela, o chefe Finon,"},
{v:53,t:"o chefe Cenez, o chefe Temã, o chefe Mabsar,"},
{v:54,t:"o chefe Magdiel e o chefe Iram. Estes foram os chefes de Edom."}
];

window.TEXTOS_SEED["1cronicas"][2] = [
{s:"Os filhos de Israel"},
{v:1,t:"Estes são os filhos de Israel: Rúben, Simeão, Levi, Judá, Issacar e Zabulon,"},
{v:2,t:"Dã, José, Benjamim, Neftali, Gad e Aser."},
{s:"Os descendentes de Judá"},
{v:3,t:"Filhos de Judá: Her, Onã e Sela; estes três lhe nasceram da filha de Sué, a cananeia. Her, primogênito de Judá, foi mau aos olhos do Senhor, e o Senhor o fez morrer.",np:1,n:"O cronista começa pela tribo de Judá, a tribo de Davi, e dedica-lhe mais espaço que a qualquer outra. A história de Judá e Tamar está em Gênesis 38."},
{v:4,t:"Tamar, sua nora, deu-lhe Farés e Zara. Ao todo, os filhos de Judá foram cinco."},
{v:5,t:"Filhos de Farés: Esrom e Hamul."},
{v:6,t:"Filhos de Zara: Zambri, Etã, Hemã, Calcol e Darda: cinco ao todo.",n:"Etã, Hemã, Calcol e Darda são os sábios famosos de 1 Reis 5,11."},
{v:7,t:"Filho de Carmi: Acar, que trouxe a desgraça a Israel, violando o anátema.",n:"Acar é o Acã do livro de Josué (Josué 7). O cronista escreve Acar, que soa como trazer desgraça, akhar em hebraico."},
{v:8,t:"Filho de Etã: Azarias."},
{s:"A família de Davi"},
{v:9,t:"Filhos que nasceram a Esrom: Jerameel, Aram e Caleb.",np:1},
{v:10,t:"Aram gerou Aminadab, e Aminadab gerou Naasson, chefe dos filhos de Judá.",n:"A mesma linhagem aparece no fim do livro de Rute (Rute 4,18-22) e na genealogia de Jesus (Mateus 1,3-6)."},
{v:11,t:"Naasson gerou Salmon, de quem nasceu Booz."},
{v:12,t:"Booz gerou Obed, e Obed gerou Jessé."},
{v:13,t:"Jessé gerou Eliab, o primogênito; o segundo, Abinadab; o terceiro, Samá;"},
{v:14,t:"o quarto, Natanael; o quinto, Radai;"},
{v:15,t:"o sexto, Asom; o sétimo, Davi.",n:"Segundo 1 Samuel 16,10-11, Davi era o oitavo filho. O cronista faz dele o sétimo, número da plenitude."},
{v:16,t:"As irmãs deles foram Sárvia e Abigail. Filhos de Sárvia: Abisai, Joab e Asael, três."},
{v:17,t:"Abigail deu à luz Amasa, cujo pai foi Jeter, o ismaelita."},
{s:"Os descendentes de Caleb"},
{v:18,t:"Caleb, filho de Esrom, teve filhos de sua mulher Azuba; os filhos dela foram Jeriot, Jeser, Sobab e Ardon.",np:1,n:"Este Caleb, descendente de Judá, é o antepassado dos clãs que habitavam o sul de Judá; tem o mesmo nome que o companheiro de Josué."},
{v:19,t:"Quando Azuba morreu, Caleb tomou por mulher Efrata, que lhe deu Hur."},
{v:20,t:"Hur gerou Uri, e Uri gerou Beseleel.",n:"Beseleel, o artista a quem Deus confiou a construção do santuário do deserto (Êxodo 31,2)."},
{v:21,t:"Depois disso, Esrom uniu-se à filha de Maquir, pai de Galaad; tomou-a por mulher quando tinha sessenta anos, e ela lhe deu Segub."},
{v:22,t:"Segub gerou Jair, que possuiu vinte e três cidades na terra de Galaad."},
{v:23,t:"Gessur e Aram tomaram-lhes as aldeias de Jair, com Canat e as suas dependências: sessenta cidades. Todos estes eram filhos de Maquir, pai de Galaad."},
{v:24,t:"Depois da morte de Esrom, Caleb uniu-se a Efrata, mulher de Esrom, seu pai. Esrom tinha também como mulher Abia, que lhe deu Asur, pai de Técua.",n:"Assim a Nova Vulgata, com a versão grega; o hebraico, obscuro, diz: depois da morte de Esrom em Caleb-Efrata. Pai de uma cidade quer dizer fundador ou chefe do clã que a habitava."},
{s:"Os descendentes de Jerameel"},
{v:25,t:"Os filhos de Jerameel, primogênito de Esrom, foram: Ram, o primogênito, Buna, Arã, Asom e Aías.",np:1},
{v:26,t:"Jerameel teve outra mulher, chamada Atara, que foi mãe de Onam."},
{v:27,t:"Os filhos de Ram, primogênito de Jerameel, foram: Moos, Jamin e Acar."},
{v:28,t:"Os filhos de Onam foram Samai e Jada. Filhos de Samai: Nadab e Abisur."},
{v:29,t:"A mulher de Abisur chamava-se Abiail, e deu-lhe Aobã e Molid."},
{v:30,t:"Filhos de Nadab: Saled e Afaim. Saled morreu sem filhos."},
{v:31,t:"Filho de Afaim: Jesi. Jesi gerou Sesã, e Sesã gerou Oolai."},
{v:32,t:"Filhos de Jada, irmão de Samai: Jeter e Jônatas. Jeter morreu sem filhos."},
{v:33,t:"Jônatas gerou Falet e Ziza. Estes foram os filhos de Jerameel."},
{v:34,t:"Sesã não teve filhos, mas só filhas; e tinha um escravo egípcio chamado Jeraa.",np:1},
{v:35,t:"Sesã deu ao seu escravo Jeraa uma filha por mulher, e ela lhe deu Etei.",n:"O escravo estrangeiro, casado com a filha do senhor, entra na linhagem de Judá: as genealogias acolhem também os de fora."},
{v:36,t:"Etei gerou Natã, e Natã gerou Zabad;"},
{v:37,t:"Zabad gerou Oflal, e Oflal gerou Obed."},
{v:38,t:"Obed gerou Jeú, e Jeú gerou Azarias;"},
{v:39,t:"Azarias gerou Heles, e Heles gerou Elasa."},
{v:40,t:"Elasa gerou Sisamoi, e Sisamoi gerou Selum;"},
{v:41,t:"Selum gerou Jecemias, e Jecemias gerou Elisama."},
{s:"Outros descendentes de Caleb"},
{v:42,t:"Filhos de Caleb, irmão de Jerameel: Mesa, o seu primogênito, que foi pai de Zif; e o seu filho Maresa, pai de Hebron.",np:1},
{v:43,t:"Filhos de Hebron: Coré, Tafua, Recém e Samá."},
{v:44,t:"Samá gerou Raam, pai de Jercaam; e Recém gerou Samai."},
{v:45,t:"Filho de Samai: Maon; e Maon foi pai de Bet-Sur."},
{v:46,t:"Efa, concubina de Caleb, deu à luz Harã, Mosa e Gezez; e Harã gerou Gezez."},
{v:47,t:"Filhos de Jaadai: Regém, Joatão, Gesã, Falet, Efa e Saaf."},
{v:48,t:"Maaca, concubina de Caleb, deu à luz Saber e Tarana."},
{v:49,t:"Saaf, pai de Madmena, gerou também Sué, pai de Macbena e pai de Gabaá. A filha de Caleb foi Acsa.",n:"Acsa, a filha que Caleb deu por mulher a Otoniel (Josué 15,16-17)."},
{v:50,t:"Estes foram os filhos de Caleb. Filhos de Hur, primogênito de Efrata: Sobal, pai de Cariat-Iarim,",np:1},
{v:51,t:"Salmon, pai de Belém, e Harif, pai de Bet-Gader.",n:"Salmon, pai de Belém: as genealogias ligam também a cidade de Davi à família de Caleb."},
{v:52,t:"Os filhos de Sobal, pai de Cariat-Iarim, foram: Raaia e metade dos manaatitas,"},
{v:53,t:"e as famílias de Cariat-Iarim: os jetreus, os futeus, os sumateus e os maseraus. Destes saíram os saraítas e os estaolitas."},
{v:54,t:"Filhos de Salmon: Belém, os netofatitas, Atarot-Bet-Joab e metade dos manaatitas, de Saraá;"},
{v:55,t:"e as famílias de Cariat-Séfer, que habitavam em Jabes: os tiratitas, os simeatitas e os sucatitas. Estes são os quenitas, descendentes de Amat, pai da casa de Recab.",n:"Cariat-Séfer: assim a Nova Vulgata; o hebraico diz as famílias dos escribas. Os quenitas e os recabitas, estrangeiros de origem, foram incorporados a Judá."}
];

window.TEXTOS_SEED["1cronicas"][3] = [
{s:"Os filhos de Davi"},
{v:1,t:"Estes são os filhos de Davi que lhe nasceram em Hebron: o primogênito, Amnon, de Aquinoam de Jezrael; o segundo, Daniel, de Abigail de Carmel;",n:"Daniel é o Queleab de 2 Samuel 3,3."},
{v:2,t:"o terceiro, Absalão, filho de Maaca, filha de Tolmai, rei de Gessur; o quarto, Adonias, filho de Hagit;"},
{v:3,t:"o quinto, Safatias, de Abital; o sexto, Jetraam, de Egla, sua mulher."},
{v:4,t:"Seis lhe nasceram em Hebron, onde reinou sete anos e seis meses. Em Jerusalém reinou trinta e três anos."},
{v:5,t:"Os filhos que lhe nasceram em Jerusalém foram estes: Samua, Sobab, Natã e Salomão, quatro de Betsabeia, filha de Amiel;",np:1,n:"Amiel é o Eliam de 2 Samuel 11,3: os dois nomes têm o mesmo sentido."},
{v:6,t:"e ainda Jebaar, Elisama, Elifalet,"},
{v:7,t:"Noga, Nefeg, Jafia,"},
{v:8,t:"Elisama, Eliada e Elifalet: nove."},
{v:9,t:"Todos estes eram filhos de Davi, sem contar os filhos das concubinas; e Tamar era irmã deles."},
{s:"Os reis de Judá"},
{v:10,t:"O filho de Salomão foi Roboão; seu filho, Abias; seu filho, Asa; seu filho, Josafá;",np:1,n:"A lista dos reis de Judá, de pai para filho, sem interrupção: é a prova da fidelidade de Deus à promessa feita a Davi."},
{v:11,t:"seu filho, Jorão; seu filho, Ocozias; seu filho, Joás;"},
{v:12,t:"seu filho, Amasias; seu filho, Azarias; seu filho, Joatão;"},
{v:13,t:"seu filho, Acaz; seu filho, Ezequias; seu filho, Manassés;"},
{v:14,t:"seu filho, Amon; seu filho, Josias."},
{v:15,t:"Filhos de Josias: o primogênito, Joanã; o segundo, Joaquim; o terceiro, Sedecias; o quarto, Selum.",n:"Selum é o nome que Jeremias dá a Joacaz (Jeremias 22,11)."},
{v:16,t:"Filhos de Joaquim: Jeconias, seu filho; Sedecias, seu filho."},
{s:"Os descendentes de Jeconias"},
{v:17,t:"Filhos de Jeconias, o cativo: Salatiel, seu filho,",np:1,n:"A dinastia de Davi continua depois do exílio: as genealogias a acompanham até o tempo do cronista, umas oito gerações depois de Jeconias."},
{v:18,t:"Melquiram, Fadaías, Senaser, Jecemias, Hosama e Nadabias."},
{v:19,t:"De Fadaías nasceram Zorobabel e Semei. Zorobabel gerou Mosolam, Hananias e Salomit, irmã deles;",n:"Em outros lugares, Zorobabel, que conduzirá a volta do exílio, é chamado filho de Salatiel (Esdras 3,2; Ageu 1,1; Mateus 1,12)."},
{v:20,t:"e também Hasaba, Ool, Baraquias, Hasadias e Josab-Hesed: cinco."},
{v:21,t:"Filhos de Hananias: Feltias, Jesaías, Rafaías, Arnã, Abdias e Secenias."},
{v:22,t:"Filhos de Secenias: Semeías, Hatus, Igal, Baria, Naarias e Safat: seis."},
{v:23,t:"Filhos de Naarias: Elioenai, Ezequias e Ezricam: três."},
{v:24,t:"Filhos de Elioenai: Odovias, Eliasib, Feleías, Acub, Joanã, Dalaías e Anani: sete."}
];

window.TEXTOS_SEED["1cronicas"][4] = [
{s:"Outros clãs de Judá"},
{v:1,t:"Filhos de Judá: Farés, Esrom, Carmi, Hur e Sobal.",n:"Não são filhos no sentido estrito, mas uma linha de descendência: as genealogias bíblicas chamam filhos também os descendentes distantes."},
{v:2,t:"Reaías, filho de Sobal, gerou Jaat, e de Jaat nasceram Aumai e Laad: estas são as famílias dos saraítas."},
{v:3,t:"Estes são os de Etam: Jezrael, Jesema e Jedebos; e a irmã deles chamava-se Asalelfuni."},
{v:4,t:"Fanuel foi pai de Gedor, e Ezer, pai de Hosa. Estes são os filhos de Hur, primogênito de Efrata, pai de Belém."},
{v:5,t:"Asur, pai de Técua, teve duas mulheres: Halaa e Naara.",np:1},
{v:6,t:"Naara deu-lhe Ozam, Héfer, Temani e Aastari. Estes são os filhos de Naara."},
{v:7,t:"Filhos de Halaa: Seret, Soar e Etnã."},
{v:8,t:"Cos gerou Anob, Sobeba e as famílias de Aarel, filho de Arum."},
{s:"A oração de Jabes"},
{v:9,t:"Jabes foi mais ilustre que os seus irmãos; sua mãe lhe dera o nome de Jabes, dizendo: Porque o dei à luz com dor.",np:1,n:"Jabes soa em hebraico como dor, otsev, com as letras trocadas. No meio das listas de nomes, o cronista conta a história de um homem que transformou o nome de dor numa oração."},
{v:10,t:"Jabes invocou o Deus de Israel, dizendo: Ah, se me abençoares, se alargares o meu território, se a tua mão estiver comigo e me livrares do mal, para que eu não seja atormentado! E Deus lhe concedeu o que tinha pedido."},
{v:11,t:"Quelub, irmão de Suaa, gerou Mair, que foi pai de Eston.",np:1},
{v:12,t:"Eston gerou Bet-Rafa, Fasea e Teína, pai de Ir-Naás, isto é, a cidade de Naás. Estes são os homens de Reca."},
{v:13,t:"Filhos de Cenez: Otoniel e Saraías. Filhos de Otoniel: Hatat e Maonati.",n:"Otoniel, o primeiro dos juízes (Juízes 3,9-11)."},
{v:14,t:"Maonati gerou Ofra; e Saraías gerou Joab, pai de Ge-Harasim, isto é, o vale dos Artesãos, porque eram artesãos."},
{v:15,t:"Filhos de Caleb, filho de Jefoné: Hir, Ela e Naam. Filho de Ela: Cenez."},
{v:16,t:"Filhos de Jalelel: Zif, Zifa, Tiria e Asarel."},
{v:17,t:"Filhos de Ezra: Jeter, Mered, Éfer e Jalon. Jeter gerou Míriam, Samai e Jesba, pai de Estemo."},
{v:18,t:"Estes são os filhos de Bítia, filha do faraó, com quem Mered se casou: ela deu à luz Jared, pai de Gedor, Héber, pai de Soco, e Jecutiel, pai de Zanoa.",n:"A Nova Vulgata reordena as frases dos versículos 17 e 18, que no hebraico estão fora de lugar. Uma princesa egípcia entra na linhagem de Judá."},
{v:19,t:"Filhos da sua mulher judia, irmã de Naam, pai de Ceila: Dalaías e Simeão, pai de Joman. Filhos de Naam, pai de Ceila: os garmitas e Estemo, dos maacatitas."},
{v:20,t:"Filhos de Simão: Amnon, Rina, Ben-Hanã e Tilon. Filhos de Jesi: Zoet e Ben-Zoet."},
{v:21,t:"Filhos de Sela, filho de Judá: Her, pai de Leca; Laada, pai de Maresa; e as famílias da casa dos tecelões de linho fino, em Bet-Asbea;",np:1},
{v:22,t:"Joquim, os homens de Cozeba, Joás e Saraf, que dominaram em Moab e depois voltaram a Belém. Mas são coisas antigas."},
{v:23,t:"Eram oleiros, e habitavam em Netaim e em Gedera; moravam ali junto do rei, trabalhando para ele.",n:"Os oleiros do rei: foram encontrados muitos jarros marcados com o selo real de Judá, fabricados em oficinas da coroa."},
{s:"Os descendentes de Simeão"},
{v:24,t:"Filhos de Simeão: Namuel, Jamin, Jarib, Zara e Saul;",np:1,n:"A tribo de Simeão, pouco numerosa, vivia dentro do território de Judá, no Negueb, e acabou absorvida por ele (Josué 19,1-9)."},
{v:25,t:"Selum, seu filho; Mabsam, seu filho; Masma, seu filho."},
{v:26,t:"Filhos de Masma: Hamuel, seu filho; Zacur, seu filho; Semei, seu filho."},
{v:27,t:"Semei teve dezesseis filhos e seis filhas; mas os seus irmãos não tiveram muitos filhos, e todas as suas famílias juntas não chegaram ao número dos filhos de Judá."},
{v:28,t:"Habitaram em Bersabeia, em Molada, em Hasar-Sual,"},
{v:29,t:"em Bala, em Esem, em Tolad,"},
{v:30,t:"em Batuel, em Horma, em Siceleg,"},
{v:31,t:"em Bet-Marcabot, em Hasar-Susim, em Bet-Berai e em Saarim. Estas foram as suas cidades até o reinado de Davi."},
{v:32,t:"As suas aldeias eram Etam, Ain, Remon, Toquen e Asã: cinco cidades,"},
{v:33,t:"com todas as povoações que havia em volta destas cidades, até Baal. Esta é a sua morada e a sua genealogia."},
{v:34,t:"Masobab, Jemlec, Josa, filho de Amasias,",np:1},
{v:35,t:"Joel, Jeú, filho de Josabias, filho de Saraías, filho de Asiel,"},
{v:36,t:"Elioenai, Jacoba, Isuaías, Asaías, Adiel, Isimiel, Banaías,"},
{v:37,t:"Ziza, filho de Sefei, filho de Alon, filho de Jedaías, filho de Semri, filho de Samaías."},
{v:38,t:"Estes, inscritos pelo nome, eram chefes nas suas famílias; e as suas casas se multiplicaram muito."},
{v:39,t:"Foram até a entrada de Gedor, a leste do vale, em busca de pastagens para os seus rebanhos."},
{v:40,t:"Encontraram pastagens férteis e boas, e uma terra vasta, tranquila e segura; porque antes tinham morado ali descendentes de Cam."},
{v:41,t:"Estes homens, inscritos pelo nome, vieram no tempo de Ezequias, rei de Judá, atacaram as tendas deles e os meunitas que ali se encontravam, e os exterminaram até hoje; e habitaram em lugar deles, porque encontraram ali pastagens para os seus rebanhos."},
{v:42,t:"Alguns dos filhos de Simeão, quinhentos homens, foram para a montanha de Seir, tendo como chefes Feltias, Naarias, Rafaías e Oziel, filhos de Jesi;"},
{v:43,t:"e bateram o resto dos amalecitas que tinham escapado, e habitaram ali até hoje."}
];

window.TEXTOS_SEED["1cronicas"][5] = [
{s:"Os descendentes de Rúben"},
{v:1,t:"Filhos de Rúben, primogênito de Israel. Ele era o primogênito; mas, por ter profanado o leito de seu pai, o seu direito de primogenitura foi dado aos filhos de José, filho de Israel, de modo que não foi inscrito como primogênito.",n:"Rúben unira-se a Bala, concubina de seu pai (Gênesis 35,22; 49,4)."},
{v:2,t:"Judá, de fato, foi o mais forte entre os seus irmãos, e dele saiu um chefe; mas o direito de primogenitura foi atribuído a José.",n:"Um chefe: Davi, e depois dele o Messias. O cronista distingue a primogenitura, que passou a José, e a realeza, dada a Judá."},
{v:3,t:"Filhos de Rúben, primogênito de Israel: Henoc, Falu, Hesron e Carmi."},
{v:4,t:"Filhos de Joel: Semeías, seu filho; Gog, seu filho; Semei, seu filho;"},
{v:5,t:"Mica, seu filho; Reaías, seu filho; Baal, seu filho;"},
{v:6,t:"Beera, seu filho, que Teglat-Falasar, rei da Assíria, levou cativo; era chefe da tribo de Rúben."},
{v:7,t:"Os seus irmãos, segundo as suas famílias, quando foram inscritos nas genealogias segundo as suas gerações, foram: o primeiro, Jeiel, depois Zacarias,"},
{v:8,t:"e Bela, filho de Azaz, filho de Samá, filho de Joel. Este habitava em Aroer, até Nebo e Baal-Meon."},
{v:9,t:"Para o oriente, habitava até a entrada do deserto que se estende a partir do rio Eufrates, porque os seus rebanhos se tinham multiplicado muito na terra de Galaad."},
{v:10,t:"No tempo de Saul, fizeram guerra aos agarenos, que caíram nas suas mãos; e habitaram nas tendas deles em toda a região a leste de Galaad.",n:"Os agarenos eram tribos nômades, que se diziam descendentes de Agar, mãe de Ismael."},
{s:"Os descendentes de Gad"},
{v:11,t:"Os filhos de Gad habitavam defronte deles, na terra de Basã, até Salca:",np:1},
{v:12,t:"Joel, o chefe; Safã, o segundo; Janai e Safat, em Basã."},
{v:13,t:"Os seus irmãos, segundo as suas famílias, foram: Micael, Mosolam, Seba, Jorai, Jacã, Zie e Héber: sete."},
{v:14,t:"Estes eram os filhos de Abiail, filho de Huri, filho de Jaroe, filho de Galaad, filho de Micael, filho de Jesesi, filho de Jedo, filho de Buz."},
{v:15,t:"Ai, filho de Abdiel, filho de Guni, era o chefe das suas famílias."},
{v:16,t:"Habitavam em Galaad, em Basã e nas suas aldeias, e em todas as pastagens de Saron, até os seus limites."},
{v:17,t:"Todos estes foram recenseados no tempo de Joatão, rei de Judá, e no tempo de Jeroboão, rei de Israel."},
{s:"As guerras das tribos da Transjordânia"},
{v:18,t:"Os filhos de Rúben, de Gad e da meia tribo de Manassés tinham guerreiros valentes, homens que traziam escudo e espada, atiravam com o arco e eram treinados para a guerra: quarenta e quatro mil setecentos e sessenta, aptos para sair a combate.",np:1},
{v:19,t:"Fizeram guerra aos agarenos, aos itureus, aos nafiseus e aos nodabeus."},
{v:20,t:"Receberam ajuda contra eles, e os agarenos e todos os que estavam com eles foram entregues nas suas mãos, porque durante o combate clamaram a Deus, e ele os ouviu, porque tinham confiado nele.",n:"É a teologia do cronista: a vitória vem da oração e da confiança em Deus."},
{v:21,t:"Tomaram os seus rebanhos: cinquenta mil camelos, duzentas e cinquenta mil ovelhas e dois mil jumentos, e cem mil pessoas."},
{v:22,t:"Muitos caíram mortos, porque a guerra era de Deus. E habitaram no lugar deles até o exílio."},
{s:"A meia tribo de Manassés"},
{v:23,t:"Os filhos da meia tribo de Manassés habitaram no país, desde Basã até Baal-Hermon, Sanir e o monte Hermon; e eram muito numerosos.",np:1},
{v:24,t:"Estes foram os chefes das suas famílias: Éfer, Jesi, Eliel, Azriel, Jeremias, Odovias e Jediel, guerreiros valentes, homens famosos, chefes das suas famílias."},
{v:25,t:"Mas foram infiéis ao Deus de seus pais e se prostituíram com os deuses dos povos da terra, que Deus tinha destruído diante deles.",np:1},
{v:26,t:"Então o Deus de Israel suscitou o espírito de Ful, rei da Assíria, e o espírito de Teglat-Falasar, rei da Assíria, que deportou os rubenitas, os gaditas e a meia tribo de Manassés, e os levou para Hala, Habor, Ara e o rio de Gozã, onde estão até hoje.",n:"Ful e Teglat-Falasar são o mesmo rei (2 Reis 15,19). O exílio das tribos do Norte é, também para o cronista, o castigo da infidelidade."},
{s:"Os descendentes de Levi: os sumos sacerdotes"},
{v:27,t:"Filhos de Levi: Gérson, Caat e Merari.",np:1,n:"Nas traduções que seguem a numeração grega, os versículos 5,27-41 são 6,1-15, e todo o capítulo 6 tem outra numeração. A tribo de Levi, a do cronista, ocupa o centro das genealogias."},
{v:28,t:"Filhos de Caat: Amram, Isaar, Hebron e Oziel."},
{v:29,t:"Filhos de Amram: Aarão, Moisés e Míriam. Filhos de Aarão: Nadab, Abiú, Eleazar e Itamar."},
{v:30,t:"Eleazar gerou Fineias, e Fineias gerou Abisue;"},
{v:31,t:"Abisue gerou Boci, e Boci gerou Ozi;"},
{v:32,t:"Ozi gerou Zaraías, e Zaraías gerou Meraiot;"},
{v:33,t:"Meraiot gerou Amarias, e Amarias gerou Aquitob;"},
{v:34,t:"Aquitob gerou Sadoc, e Sadoc gerou Aquimaás;",n:"A linhagem dos sumos sacerdotes, de Aarão a Josedec, liga Sadoc diretamente a Aarão: legitima o sacerdócio do templo de Jerusalém."},
{v:35,t:"Aquimaás gerou Azarias, e Azarias gerou Joanã;"},
{v:36,t:"Joanã gerou Azarias: foi ele que exerceu o sacerdócio no templo que Salomão construiu em Jerusalém."},
{v:37,t:"Azarias gerou Amarias, e Amarias gerou Aquitob;"},
{v:38,t:"Aquitob gerou Sadoc, e Sadoc gerou Selum;"},
{v:39,t:"Selum gerou Helcias, e Helcias gerou Azarias;",n:"Helcias é o sumo sacerdote que encontrou o livro da Lei no tempo de Josias (2 Reis 22,8)."},
{v:40,t:"Azarias gerou Saraías, e Saraías gerou Josedec;"},
{v:41,t:"e Josedec partiu para o exílio, quando o Senhor deportou Judá e Jerusalém pelas mãos de Nabucodonosor.",n:"Josedec será o pai de Josué, o sumo sacerdote da volta do exílio (Ageu 1,1)."}
];

window.TEXTOS_SEED["1cronicas"][6] = [
{s:"As famílias dos levitas"},
{v:1,t:"Filhos de Levi: Gérson, Caat e Merari."},
{v:2,t:"Estes são os nomes dos filhos de Gérson: Lobni e Semei."},
{v:3,t:"Filhos de Caat: Amram, Isaar, Hebron e Oziel."},
{v:4,t:"Filhos de Merari: Mooli e Musi. Estas são as famílias de Levi, segundo os seus pais:"},
{v:5,t:"de Gérson: Lobni, seu filho; Jaat, seu filho; Zama, seu filho;",np:1},
{v:6,t:"Joá, seu filho; Ado, seu filho; Zara, seu filho; Jetrai, seu filho."},
{v:7,t:"Filhos de Caat: Aminadab, seu filho; Coré, seu filho; Asir, seu filho;"},
{v:8,t:"Elcana, seu filho; Abiasaf, seu filho; Asir, seu filho;"},
{v:9,t:"Taat, seu filho; Uriel, seu filho; Ozias, seu filho; Saul, seu filho."},
{v:10,t:"Filhos de Elcana: Amasai e Aquimot;"},
{v:11,t:"Elcana, seu filho; Sofai, seu filho; Naat, seu filho;"},
{v:12,t:"Eliab, seu filho; Jeroam, seu filho; Elcana, seu filho; Samuel, seu filho.",n:"O profeta Samuel, efraimita segundo 1 Samuel 1,1, é aqui inserido entre os levitas: o cronista vê nele um homem do culto."},
{v:13,t:"Filhos de Samuel: o primogênito, Joel, e o segundo, Abias."},
{v:14,t:"Filhos de Merari: Mooli; Lobni, seu filho; Semei, seu filho; Oza, seu filho;"},
{v:15,t:"Samaá, seu filho; Hagias, seu filho; Asaías, seu filho."},
{s:"Os cantores do templo"},
{v:16,t:"Estes são os que Davi encarregou do canto na casa do Senhor, desde que a arca ali repousou.",np:1,n:"Para o cronista, Davi é o fundador da liturgia do templo, e sobretudo do canto. Hemã, Asaf e Etã são os nomes que aparecem nos títulos de vários Salmos."},
{v:17,t:"Exerciam o seu ministério cantando diante da tenda da reunião, até que Salomão construiu a casa do Senhor em Jerusalém; e desempenhavam o seu serviço segundo a sua ordem."},
{v:18,t:"Estes são os que exerciam o ministério, com os seus filhos. Dos filhos de Caat: Hemã, o cantor, filho de Joel, filho de Samuel,"},
{v:19,t:"filho de Elcana, filho de Jeroam, filho de Eliel, filho de Toú,"},
{v:20,t:"filho de Suf, filho de Elcana, filho de Maat, filho de Amasai,"},
{v:21,t:"filho de Elcana, filho de Joel, filho de Azarias, filho de Sofonias,"},
{v:22,t:"filho de Taat, filho de Asir, filho de Abiasaf, filho de Coré,"},
{v:23,t:"filho de Isaar, filho de Caat, filho de Levi, filho de Israel."},
{v:24,t:"À sua direita estava o seu irmão Asaf: Asaf, filho de Baraquias, filho de Samaá,",np:1},
{v:25,t:"filho de Micael, filho de Basaías, filho de Melquias,"},
{v:26,t:"filho de Atanai, filho de Zara, filho de Adaías,"},
{v:27,t:"filho de Etã, filho de Zama, filho de Semei,"},
{v:28,t:"filho de Jaat, filho de Gérson, filho de Levi."},
{v:29,t:"À esquerda, os seus irmãos, filhos de Merari: Etã, filho de Cusi, filho de Abdi, filho de Meluc,",np:1},
{v:30,t:"filho de Hasabias, filho de Amasias, filho de Helcias,"},
{v:31,t:"filho de Amsi, filho de Bani, filho de Somer,"},
{v:32,t:"filho de Mooli, filho de Musi, filho de Merari, filho de Levi."},
{v:33,t:"Os seus irmãos, os levitas, estavam encarregados de todo o serviço da morada da casa do Senhor.",np:1},
{v:34,t:"Mas Aarão e os seus filhos queimavam as ofertas sobre o altar dos holocaustos e sobre o altar do incenso, cuidando de todo o serviço do Santo dos Santos e fazendo a expiação por Israel, segundo tudo o que Moisés, servo de Deus, tinha ordenado.",n:"O cronista distingue com cuidado os sacerdotes, descendentes de Aarão, que oferecem os sacrifícios, e os levitas, que os ajudam."},
{v:35,t:"Estes são os filhos de Aarão: Eleazar, seu filho; Fineias, seu filho; Abisue, seu filho;"},
{v:36,t:"Boci, seu filho; Ozi, seu filho; Zaraías, seu filho;"},
{v:37,t:"Meraiot, seu filho; Amarias, seu filho; Aquitob, seu filho;"},
{v:38,t:"Sadoc, seu filho; Aquimaás, seu filho."},
{s:"As cidades dos levitas"},
{v:39,t:"Estas são as suas moradas, segundo os seus acampamentos e os seus territórios. Aos filhos de Aarão, do clã dos caatitas, porque a primeira sorte foi para eles,",np:1,n:"A lista segue a de Josué 21, com pequenas diferenças nos nomes."},
{v:40,t:"deram Hebron, na terra de Judá, com as suas pastagens em volta;"},
{v:41,t:"mas os campos da cidade e as suas aldeias deram-nos a Caleb, filho de Jefoné."},
{v:42,t:"Aos filhos de Aarão deram as cidades de refúgio: Hebron e Lebna com as suas pastagens,"},
{v:43,t:"Jeter e Estemo com as suas pastagens, Helon e Dabir com as suas pastagens,"},
{v:44,t:"Asã, Jota e Bet-Sames com as suas pastagens;"},
{v:45,t:"e da tribo de Benjamim, Gabaon, Gaba e as suas pastagens, Almat e Anatot com as suas pastagens: ao todo, treze cidades, segundo as suas famílias."},
{v:46,t:"Aos outros filhos de Caat, segundo as suas famílias, deram por sorte dez cidades da tribo de Efraim, da tribo de Dã e da meia tribo de Manassés."},
{v:47,t:"Aos filhos de Gérson, segundo as suas famílias, deram treze cidades da tribo de Issacar, da tribo de Aser, da tribo de Neftali e da tribo de Manassés, em Basã."},
{v:48,t:"Aos filhos de Merari, segundo as suas famílias, deram por sorte doze cidades da tribo de Rúben, da tribo de Gad e da tribo de Zabulon."},
{v:49,t:"Os filhos de Israel deram aos levitas estas cidades com as suas pastagens.",np:1},
{v:50,t:"Deram por sorte, da tribo dos filhos de Judá, da tribo dos filhos de Simeão e da tribo dos filhos de Benjamim, estas cidades que designaram pelos seus nomes."},
{v:51,t:"Às famílias dos filhos de Caat couberam cidades no território da tribo de Efraim."},
{v:52,t:"Deram-lhes as cidades de refúgio: Siquém com as suas pastagens, na montanha de Efraim, Gazer com as suas pastagens,"},
{v:53,t:"Jecmaam com as suas pastagens, Bet-Horon com as suas pastagens,"},
{v:54,t:"Aialon com as suas pastagens e Gat-Remon com as suas pastagens."},
{v:55,t:"Da meia tribo de Manassés, Tanac com as suas pastagens e Jeblaam com as suas pastagens, para as famílias dos outros filhos de Caat."},
{v:56,t:"Aos filhos de Gérson, das famílias da meia tribo de Manassés: Golã, em Basã, com as suas pastagens, e Astarot com as suas pastagens.",np:1},
{v:57,t:"Da tribo de Issacar: Cedes com as suas pastagens, Daberet com as suas pastagens,"},
{v:58,t:"Ramot com as suas pastagens e Anem com as suas pastagens."},
{v:59,t:"Da tribo de Aser: Masal com as suas pastagens, Abdon com as suas pastagens,"},
{v:60,t:"Hucoc com as suas pastagens e Roob com as suas pastagens."},
{v:61,t:"Da tribo de Neftali: Cedes, na Galileia, com as suas pastagens, Hamon com as suas pastagens e Cariataim com as suas pastagens."},
{v:62,t:"Aos outros filhos de Merari, da tribo de Zabulon: Remon com as suas pastagens e Tabor com as suas pastagens.",np:1},
{v:63,t:"Do outro lado do Jordão, defronte de Jericó, a leste do Jordão, da tribo de Rúben: Bosor, no deserto, com as suas pastagens, Jasa com as suas pastagens,"},
{v:64,t:"Cedemot com as suas pastagens e Mefaat com as suas pastagens;"},
{v:65,t:"e da tribo de Gad: Ramot, em Galaad, com as suas pastagens, Maanaim com as suas pastagens,"},
{v:66,t:"Hesbon com as suas pastagens e Jazer com as suas pastagens."}
];

window.TEXTOS_SEED["1cronicas"][7] = [
{s:"Os descendentes de Issacar"},
{v:1,t:"Filhos de Issacar: Tola, Fua, Jasub e Semron: quatro.",n:"As listas das tribos do Norte, mais breves, parecem tiradas de antigos registros militares: indicam o número de guerreiros de cada clã."},
{v:2,t:"Filhos de Tola: Ozi, Rafaías, Jeriel, Jemai, Jebsem e Samuel, chefes das suas famílias. Os descendentes de Tola, homens valentes, recenseados segundo as suas genealogias no tempo de Davi, eram vinte e dois mil e seiscentos."},
{v:3,t:"Filho de Ozi: Izraías; filhos de Izraías: Micael, Obadias, Joel e Jesias: cinco, todos chefes."},
{v:4,t:"Tinham, segundo as genealogias das suas famílias, tropas prontas para a guerra, homens valentes, trinta e seis mil; porque tinham muitas mulheres e filhos."},
{v:5,t:"Os seus irmãos, de todas as famílias de Issacar, homens muito valentes, recenseados, eram oitenta e sete mil."},
{s:"Os descendentes de Benjamim"},
{v:6,t:"Filhos de Benjamim: Bela, Bocor e Jediel: três.",np:1},
{v:7,t:"Filhos de Bela: Esebon, Ozi, Oziel, Jerimot e Urai: cinco chefes de famílias, guerreiros valentes; o seu número era de vinte e dois mil e trinta e quatro."},
{v:8,t:"Filhos de Bocor: Zamira, Joás, Eliezer, Elioenai, Amri, Jerimot, Abias, Anatot e Almat. Todos estes eram filhos de Bocor."},
{v:9,t:"Recenseados nas suas genealogias, os chefes das suas famílias, homens valentes, eram vinte mil e duzentos."},
{v:10,t:"Filho de Jediel: Bilã; filhos de Bilã: Jeús, Benjamim, Aod, Canaana, Zetã, Társis e Aisaar."},
{v:11,t:"Todos estes eram filhos de Jediel, chefes de famílias, homens valentes, dezessete mil e duzentos, prontos para sair à guerra."},
{v:12,t:"E também Sufim e Hufim, filhos de Hir, e Husim, filho de Aer."},
{s:"Os descendentes de Neftali e de Manassés"},
{v:13,t:"Filhos de Neftali: Jasiel, Guni, Jeser e Selum, filhos de Bala.",np:1,n:"Bala, a serva de Raquel, mãe de Dã e de Neftali (Gênesis 30,7-8). A tribo de Dã não aparece nestas genealogias."},
{v:14,t:"Filho de Manassés: Asriel, que lhe deu a sua concubina síria; ela deu à luz também Maquir, pai de Galaad."},
{v:15,t:"Maquir tomou mulher de Hufim e de Sufim; a sua irmã chamava-se Maaca. O nome do segundo filho era Salfaad, e Salfaad teve filhas.",n:"As filhas de Salfaad, que obtiveram de Moisés o direito à herança do pai (Números 27,1-11)."},
{v:16,t:"Maaca, mulher de Maquir, deu à luz um filho e lhe deu o nome de Farés; o seu irmão chamava-se Sares, e os seus filhos foram Ulam e Recém."},
{v:17,t:"Filho de Ulam: Badã. Estes são os filhos de Galaad, filho de Maquir, filho de Manassés."},
{v:18,t:"A sua irmã, Amaleguet, deu à luz Isod, Abiezer e Maala.",n:"Abiezer: o clã de Gedeão (Juízes 6,11)."},
{v:19,t:"Os filhos de Semida eram Ain, Siquém, Leci e Aniam."},
{s:"Os descendentes de Efraim"},
{v:20,t:"Filhos de Efraim: Sutala; Bared, seu filho; Taat, seu filho; Elada, seu filho; Taat, seu filho;",np:1},
{v:21,t:"Zabad, seu filho; Sutala, seu filho; e Ezer e Elad. Os homens de Gat, nativos do país, os mataram, porque tinham descido para roubar os seus rebanhos."},
{v:22,t:"Efraim, seu pai, fez luto por muitos dias, e os seus irmãos vieram consolá-lo."},
{v:23,t:"Depois ele se uniu à sua mulher, que concebeu e deu à luz um filho; e ele lhe deu o nome de Beria, porque tinha nascido quando a desgraça estava na sua casa.",n:"Beria soa como bera'á, na desgraça. Uma pequena história de luto e de consolo no meio das listas."},
{v:24,t:"Sua filha foi Sara, que construiu Bet-Horon de baixo e de cima, e Ozen-Sara."},
{v:25,t:"Seu filho foi Rafa, e também Resef; Tale, seu filho, de quem nasceu Taã;"},
{v:26,t:"este gerou Laadã; seu filho Amiud gerou Elisama,"},
{v:27,t:"de quem nasceu Nun, que teve por filho Josué.",n:"Josué, o sucessor de Moisés, era efraimita."},
{v:28,t:"As suas propriedades e moradas eram: Betel e as suas aldeias; a leste, Norã; a oeste, Gazer e as suas aldeias; Siquém e as suas aldeias, até Hai e as suas aldeias.",np:1},
{v:29,t:"Junto dos filhos de Manassés: Bet-San e as suas aldeias, Tanac e as suas aldeias, Meguido e as suas aldeias, Dor e as suas aldeias. Nestas cidades habitaram os filhos de José, filho de Israel."},
{s:"Os descendentes de Aser"},
{v:30,t:"Filhos de Aser: Jemna, Jesua, Isui e Beria, e Sara, irmã deles.",np:1},
{v:31,t:"Filhos de Beria: Héber e Melquiel, que foi pai de Barzait."},
{v:32,t:"Héber gerou Jeflat, Somer e Hotam, e Suaa, irmã deles."},
{v:33,t:"Filhos de Jeflat: Fosec, Bamaal e Asot. Estes são os filhos de Jeflat."},
{v:34,t:"Filhos de Somer, seu irmão: Roaga, Haba e Aram."},
{v:35,t:"Filhos de Hotam, seu irmão: Sufa, Jemna, Seles e Amal."},
{v:36,t:"Filhos de Sufa: Sué, Harnafer, Sual, Beri, Jamra,"},
{v:37,t:"Bosor, Od, Samá, Salusa, Jetrã e Beera."},
{v:38,t:"Filhos de Jeter: Jefoné, Fasfa e Ara."},
{v:39,t:"Filhos de Ola: Area, Haniel e Resia."},
{v:40,t:"Todos estes eram filhos de Aser, chefes de famílias, homens escolhidos e valentes, chefes dos príncipes. O número dos que foram inscritos no exército para a guerra era de vinte e seis mil."}
];

window.TEXTOS_SEED["1cronicas"][8] = [
{s:"Os descendentes de Benjamim"},
{v:1,t:"Benjamim gerou Bela, seu primogênito; o segundo, Asbel; o terceiro, Aara;",n:"Benjamim recebe uma segunda genealogia, mais longa: é a tribo de Saul, e a que ficou unida a Judá depois da divisão do reino."},
{v:2,t:"o quarto, Noaa; o quinto, Rafa."},
{v:3,t:"Os filhos de Bela foram Adar e Gera, pai de Aod,"},
{v:4,t:"Abisue, Naamã, Aoé,"},
{v:5,t:"Gera, Sefufã e Huram."},
{v:6,t:"Estes são os filhos de Aod, chefes das famílias dos habitantes de Gaba, que foram deportados para Manaat:",n:"Aod, o juiz benjaminita que libertou Israel de Eglon, rei de Moab (Juízes 3,15)."},
{v:7,t:"Naamã, Aías e Gera: foi este que os deportou; e gerou Oza e Aiud."},
{v:8,t:"Saaraim teve filhos na terra de Moab, depois de ter repudiado as suas mulheres Husim e Bara;",np:1},
{v:9,t:"de Hodes, sua mulher, gerou Jobab, Sébia, Mesa, Malcam,"},
{v:10,t:"Jeús, Sequias e Marma. Estes foram os seus filhos, chefes de famílias."},
{v:11,t:"De Husim gerou Abitob e Elfaal."},
{v:12,t:"Filhos de Elfaal: Héber, Misaam e Samad, que construiu Ono e Lod com as suas aldeias."},
{v:13,t:"Beria e Samá, chefes das famílias dos habitantes de Aialon, puseram em fuga os habitantes de Gat."},
{v:14,t:"Aio, Sesac, Jerimot,",np:1},
{v:15,t:"Zabadias, Arad, Eder,"},
{v:16,t:"Micael, Jesfa e Joá eram filhos de Beria."},
{v:17,t:"Zabadias, Mosolam, Hezeci, Héber,"},
{v:18,t:"Jesamari, Jezlias e Jobab eram filhos de Elfaal."},
{v:19,t:"Jacim, Zecri, Zabdi,"},
{v:20,t:"Elioenai, Seletai, Eliel,"},
{v:21,t:"Adaías, Baraías e Samarat eram filhos de Semei."},
{v:22,t:"Jesfã, Héber, Eliel,"},
{v:23,t:"Abdon, Zecri, Hanã,"},
{v:24,t:"Hananias, Elam, Anatotias,"},
{v:25,t:"Jefdaías e Fanuel eram filhos de Sesac."},
{v:26,t:"Samsari, Soorias, Otolias,"},
{v:27,t:"Jersias, Elias e Zecri eram filhos de Jeroam."},
{v:28,t:"Estes eram os chefes de famílias, segundo as suas genealogias, que habitaram em Jerusalém."},
{s:"A família de Saul"},
{v:29,t:"Em Gabaon habitaram Jeiel, pai de Gabaon, cuja mulher se chamava Maaca,",np:1,n:"A genealogia de Saul é repetida em 9,35-44, como introdução à sua história."},
{v:30,t:"e o seu filho primogênito, Abdon, e Sur, Cis, Baal, Ner, Nadab,"},
{v:31,t:"Gedor, Aio, Zaquer e Macelot."},
{v:32,t:"Macelot gerou Samaá. Estes também habitaram em Jerusalém, defronte dos seus irmãos, com os seus irmãos."},
{v:33,t:"Ner gerou Cis, e Cis gerou Saul. Saul gerou Jônatas, Melquisua, Abinadab e Isbaal.",n:"Segundo 1 Samuel 9,1, Cis era filho de Abiel; aqui é neto de Jeiel, por meio de Ner."},
{v:34,t:"O filho de Jônatas foi Meribaal, e Meribaal gerou Mica."},
{v:35,t:"Filhos de Mica: Piton, Melec, Taraa e Acaz."},
{v:36,t:"Acaz gerou Joada, e Joada gerou Almat, Azmavet e Zambri; e Zambri gerou Mosa."},
{v:37,t:"Mosa gerou Banaa, cujo filho foi Rafaías, de quem nasceu Elasa, que gerou Asel."},
{v:38,t:"Asel teve seis filhos, cujos nomes eram: Ezricam, o primogênito, Ismael, Saria, Azarias, Obdias e Hanã. Todos estes eram filhos de Asel.",n:"A família de Saul sobreviveu por muitas gerações, embora sem o trono."},
{v:39,t:"Filhos de Esec, seu irmão: Ulam, o primogênito; Jeús, o segundo; Elifalet, o terceiro."},
{v:40,t:"Os filhos de Ulam eram homens valentes, hábeis no tiro com o arco; tiveram muitos filhos e netos: cento e cinquenta. Todos estes eram descendentes de Benjamim."}
];

window.TEXTOS_SEED["1cronicas"][9] = [
{s:"Os habitantes de Jerusalém depois do exílio"},
{v:1,t:"Todo o Israel foi recenseado, e o seu registro está escrito no livro dos reis de Israel e de Judá. E foram deportados para a Babilônia por causa da sua infidelidade.",n:"Com uma só frase o cronista salta da monarquia ao exílio: as genealogias desembocam na comunidade que voltou da Babilônia. A lista seguinte tem muitos pontos em comum com Neemias 11."},
{v:2,t:"Os primeiros que voltaram a habitar nas suas propriedades, nas suas cidades, foram israelitas, sacerdotes, levitas e natineus.",np:1,n:"Os natineus, isto é, os doados, eram servidores do templo, talvez descendentes de estrangeiros postos a serviço do santuário (Josué 9,27)."},
{v:3,t:"Em Jerusalém habitaram filhos de Judá, de Benjamim, de Efraim e de Manassés.",n:"Efraim e Manassés: também gente das tribos do Norte veio juntar-se a Jerusalém. Para o cronista, Israel inteiro está representado na comunidade restaurada."},
{v:4,t:"Utai, filho de Amiud, filho de Amri, filho de Imri, filho de Bani, dos filhos de Farés, filho de Judá;"},
{v:5,t:"dos selanitas: Asaías, o primogênito, e os seus filhos;"},
{v:6,t:"dos filhos de Zara: Jeuel e os seus irmãos: seiscentos e noventa."},
{v:7,t:"Dos filhos de Benjamim: Salu, filho de Mosolam, filho de Odovias, filho de Asana;"},
{v:8,t:"Jobanias, filho de Jeroam; Ela, filho de Ozi, filho de Mocori; e Mosolam, filho de Safatias, filho de Rauel, filho de Jebanias;"},
{v:9,t:"e os seus irmãos, segundo as suas genealogias: novecentos e cinquenta e seis. Todos estes eram chefes de famílias, segundo as suas famílias."},
{s:"Os sacerdotes"},
{v:10,t:"Dos sacerdotes: Jedaías, Joiarib e Jaquin;",np:1},
{v:11,t:"Azarias, filho de Helcias, filho de Mosolam, filho de Sadoc, filho de Meraiot, filho de Aquitob, chefe da casa de Deus;"},
{v:12,t:"Adaías, filho de Jeroam, filho de Fassur, filho de Melquias; e Maasai, filho de Adiel, filho de Jezra, filho de Mosolam, filho de Mosolamot, filho de Emer;"},
{v:13,t:"e os seus irmãos, chefes das suas famílias: mil setecentos e sessenta, homens muito capazes para o serviço da casa de Deus."},
{s:"Os levitas e os porteiros"},
{v:14,t:"Dos levitas: Semeías, filho de Hassub, filho de Ezricam, filho de Hasabias, dos filhos de Merari;",np:1},
{v:15,t:"Bacbacar, Hares, Galal e Matanias, filho de Mica, filho de Zecri, filho de Asaf;"},
{v:16,t:"Abdias, filho de Semeías, filho de Galal, filho de Iditun; e Baraquias, filho de Asa, filho de Elcana, que habitava nas aldeias dos netofatitas."},
{v:17,t:"Os porteiros: Selum, Acub, Telmon, Aimã e os seus irmãos; Selum era o chefe,",np:1},
{v:18,t:"e até hoje está na porta do rei, a oriente. Estes eram os porteiros dos acampamentos dos filhos de Levi.",n:"Os acampamentos dos filhos de Levi: o templo é imaginado como o acampamento de Israel no deserto, guardado pelos levitas em volta da tenda."},
{v:19,t:"Selum, filho de Coré, filho de Abiasaf, filho de Coré, e os seus irmãos da casa de seu pai, os coreítas, estavam encarregados do serviço, guardando as soleiras da tenda; os seus pais tinham guardado a entrada do acampamento do Senhor,"},
{v:20,t:"e Fineias, filho de Eleazar, fora outrora o seu chefe — o Senhor esteja com ele!",n:"Fineias, neto de Aarão, que mostrou o seu zelo pelo Senhor (Números 25,7-13)."},
{v:21,t:"Zacarias, filho de Mosolamias, era o porteiro da entrada da tenda da reunião."},
{v:22,t:"Todos estes, escolhidos para guardar as soleiras, eram duzentos e doze, inscritos nas genealogias das suas aldeias. Davi e o vidente Samuel os tinham estabelecido no seu cargo permanente,"},
{v:23,t:"a eles e aos seus filhos, para guardarem as portas da casa do Senhor, a casa da tenda."},
{v:24,t:"Os porteiros estavam dos quatro lados: a oriente, a ocidente, ao norte e ao sul."},
{v:25,t:"Os seus irmãos, que moravam nas suas aldeias, vinham de tempos em tempos, por sete dias, para ficar com eles."},
{v:26,t:"Porque estes quatro chefes dos porteiros tinham um cargo permanente. Eram levitas, e estavam encarregados das salas e dos tesouros da casa do Senhor;"},
{v:27,t:"passavam a noite em volta da casa de Deus, de guarda, e deviam abri-la todas as manhãs."},
{v:28,t:"Alguns deles cuidavam dos objetos do culto, que contavam ao trazê-los e ao levá-los;",np:1},
{v:29,t:"outros estavam encarregados dos utensílios, de todos os objetos sagrados, da flor de farinha, do vinho, do azeite, do incenso e dos perfumes."},
{v:30,t:"Alguns filhos dos sacerdotes preparavam a mistura dos perfumes."},
{v:31,t:"Matatias, levita, primogênito de Selum, o coreíta, tinha a seu cargo permanente as oferendas fritas na assadeira."},
{v:32,t:"Alguns dos filhos de Caat, seus irmãos, cuidavam dos pães da proposição, para prepará-los de novo todos os sábados."},
{v:33,t:"Estes eram os cantores, chefes de famílias levitas, que moravam nas salas do templo, livres de outros serviços, porque estavam ocupados no seu ministério dia e noite.",n:"Dia e noite: o louvor contínuo no templo, que a oração das Horas da Igreja quer prolongar."},
{v:34,t:"Estes eram os chefes das famílias levitas, segundo as suas genealogias; moravam em Jerusalém."},
{s:"A família de Saul"},
{v:35,t:"Em Gabaon habitaram o pai de Gabaon, Jeiel, cuja mulher se chamava Maaca,",np:1,n:"A genealogia de Saul, já dada em 8,29-38, é repetida para introduzir a narrativa da sua morte."},
{v:36,t:"e o seu filho primogênito, Abdon, e Sur, Cis, Baal, Ner, Nadab,"},
{v:37,t:"Gedor, Aio, Zacarias e Macelot."},
{v:38,t:"Macelot gerou Samaam. Estes também habitaram em Jerusalém, defronte dos seus irmãos, com os seus irmãos."},
{v:39,t:"Ner gerou Cis, e Cis gerou Saul. Saul gerou Jônatas, Melquisua, Abinadab e Isbaal."},
{v:40,t:"O filho de Jônatas foi Meribaal, e Meribaal gerou Mica."},
{v:41,t:"Filhos de Mica: Piton, Melec, Taraa e Acaz."},
{v:42,t:"Acaz gerou Jara, e Jara gerou Almat, Azmavet e Zambri; e Zambri gerou Mosa."},
{v:43,t:"Mosa gerou Banaa, cujo filho Rafaías gerou Elasa, de quem nasceu Asel."},
{v:44,t:"Asel teve seis filhos, cujos nomes eram: Ezricam, o primogênito, Ismael, Saria, Azarias, Obdias e Hanã. Estes eram os filhos de Asel."}
];

window.TEXTOS_SEED["1cronicas"][10] = [
{s:"A morte de Saul"},
{v:1,t:"Os filisteus combateram contra Israel; os homens de Israel fugiram diante dos filisteus e caíram mortos no monte Gelboé.",n:"A história propriamente dita começa com a morte de Saul, contada quase como em 1 Samuel 31: o cronista não conta nada do reinado de Saul, e passa logo a Davi."},
{v:2,t:"Os filisteus perseguiram de perto Saul e os seus filhos, e mataram Jônatas, Abinadab e Melquisua, filhos de Saul."},
{v:3,t:"O combate tornou-se violento contra Saul; os arqueiros o alcançaram e o feriram com as suas flechas."},
{v:4,t:"Saul disse ao seu escudeiro: Desembainha a tua espada e mata-me, para que não venham esses incircuncisos zombar de mim. Mas o escudeiro não quis, porque estava tomado de grande temor. Então Saul tomou a espada e lançou-se sobre ela."},
{v:5,t:"Vendo que Saul estava morto, o escudeiro lançou-se também sobre a sua espada e morreu."},
{v:6,t:"Assim morreram Saul e os seus três filhos: toda a sua casa pereceu com ele.",n:"Toda a sua casa: o cronista simplifica, porque a família de Saul sobreviveu (8,33-40); quer dizer que a dinastia de Saul acabou ali."},
{v:7,t:"Quando os homens de Israel que habitavam no vale viram que os israelitas tinham fugido e que Saul e os seus filhos estavam mortos, abandonaram as suas cidades e se dispersaram; e os filisteus vieram e se estabeleceram nelas.",np:1},
{v:8,t:"No dia seguinte, os filisteus vieram despojar os mortos e encontraram Saul e os seus filhos caídos no monte Gelboé."},
{v:9,t:"Despojaram-no, cortaram-lhe a cabeça, tiraram-lhe as armas e mandaram mensageiros por toda a terra dos filisteus, para anunciar a notícia nos templos dos seus ídolos e aos seus povos."},
{v:10,t:"Puseram as suas armas no templo de Astarte e pregaram a sua cabeça no templo de Dagon."},
{v:11,t:"Quando os homens de Jabes de Galaad souberam tudo o que os filisteus tinham feito a Saul,",np:1},
{v:12,t:"todos os homens valentes se levantaram, tomaram os corpos de Saul e dos seus filhos e os levaram a Jabes; sepultaram os seus ossos debaixo do carvalho de Jabes e jejuaram sete dias."},
{v:13,t:"Assim morreu Saul, por causa da sua infidelidade: tinha transgredido a palavra que o Senhor lhe dera e não a tinha guardado; e, além disso, tinha consultado uma necromante",np:1,n:"O cronista lembra a desobediência de 1 Samuel 13 e 15, e a consulta à necromante de En-Dor (1 Samuel 28)."},
{v:14,t:"e não tinha buscado o Senhor. Por isso o Senhor o fez morrer e transferiu o reino a Davi, filho de Jessé.",n:"Segundo 1 Samuel 28,6, Saul consultou o Senhor, mas sem resposta. Para o cronista, buscar o Senhor é mais que consultá-lo: é voltar-se para ele com todo o coração. É o critério com que julgará todos os reis."}
];
