// =====================================================================
// I João — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["1joao"][1] = [
{s:"O Verbo da vida"},
{v:1,t:"O que existia desde o princípio, o que ouvimos, o que vimos com os nossos olhos, o que contemplamos e as nossas mãos tocaram, a respeito do Verbo da vida —",n:"A carta abre como o Evangelho de João, mas acrescenta o tato: as mãos tocaram. Contra os que negavam a carne de Cristo, a fé começa por um corpo que se pôde tocar."},
{v:2,t:"porque a vida se manifestou, e nós a vimos, e damos testemunho, e vos anunciamos a vida eterna, que estava junto do Pai e se nos manifestou —,"},
{v:3,t:"o que vimos e ouvimos, isso vos anunciamos, para que também vós tenhais comunhão conosco. E a nossa comunhão é com o Pai e com seu Filho Jesus Cristo."},
{v:4,t:"Escrevemo-vos estas coisas para que a nossa alegria seja completa."},
{s:"Deus é luz"},
{v:5,t:"E esta é a mensagem que dele ouvimos e vos anunciamos: Deus é luz, e nele não há treva alguma."},
{v:6,t:"Se dizemos que estamos em comunhão com ele e caminhamos nas trevas, mentimos e não praticamos a verdade."},
{v:7,t:"Mas, se caminhamos na luz, como ele está na luz, temos comunhão uns com os outros, e o sangue de Jesus, seu Filho, purifica-nos de todo pecado."},
{v:8,t:"Se dizemos que não temos pecado, enganamo-nos a nós mesmos, e a verdade não está em nós."},
{v:9,t:"Se confessamos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça."},
{v:10,t:"Se dizemos que não pecamos, fazemos dele um mentiroso, e a sua palavra não está em nós."}
];

window.TEXTOS_SEED["1joao"][2] = [
{s:"Guardar os mandamentos"},
{v:1,t:"Meus filhinhos, escrevo-vos estas coisas para que não pequeis. Mas, se alguém pecar, temos junto do Pai um advogado: Jesus Cristo, o justo."},
{v:2,t:"Ele é a vítima de expiação pelos nossos pecados; e não só pelos nossos, mas também pelos do mundo inteiro."},
{v:3,t:"E nisto sabemos que o conhecemos: se guardamos os seus mandamentos."},
{v:4,t:"Quem diz que o conhece e não guarda os seus mandamentos é mentiroso, e nele não está a verdade."},
{v:5,t:"Mas, em quem guarda a sua palavra, o amor de Deus é verdadeiramente perfeito. Nisto conhecemos que estamos nele."},
{v:6,t:"Quem diz que permanece nele deve caminhar como ele caminhou."},
{s:"O mandamento antigo e novo"},
{v:7,t:"Caríssimos, não vos escrevo um mandamento novo, mas um mandamento antigo, que tendes desde o princípio: o mandamento antigo é a palavra que ouvistes."},
{v:8,t:"E, no entanto, é um mandamento novo que vos escrevo — o que é verdadeiro nele e em vós —, porque as trevas passam e já brilha a verdadeira luz."},
{v:9,t:"Quem diz que está na luz e odeia o seu irmão ainda está nas trevas."},
{v:10,t:"Quem ama o seu irmão permanece na luz, e nele não há escândalo."},
{v:11,t:"Mas quem odeia o seu irmão está nas trevas, caminha nas trevas e não sabe para onde vai, porque as trevas lhe cegaram os olhos."},
{s:"Não ameis o mundo"},
{v:12,t:"Escrevo-vos, filhinhos, porque os vossos pecados vos foram perdoados por causa do seu nome."},
{v:13,t:"Escrevo-vos, pais, porque conheceis aquele que existe desde o princípio. Escrevo-vos, jovens, porque vencestes o maligno."},
{v:14,t:"Escrevi-vos, crianças, porque conheceis o Pai. Escrevi-vos, pais, porque conheceis aquele que existe desde o princípio. Escrevi-vos, jovens, porque sois fortes, e a palavra de Deus permanece em vós, e vencestes o maligno."},
{v:15,t:"Não ameis o mundo, nem o que há no mundo. Se alguém ama o mundo, o amor do Pai não está nele;",np:1},
{v:16,t:"porque tudo o que há no mundo — a concupiscência da carne, a concupiscência dos olhos e a soberba da vida — não vem do Pai, mas do mundo."},
{v:17,t:"E o mundo passa, com a sua concupiscência; mas quem faz a vontade de Deus permanece para sempre."},
{s:"Os anticristos"},
{v:18,t:"Filhinhos, é a última hora. E, como ouvistes que vem o anticristo, já agora surgiram muitos anticristos; por isso sabemos que é a última hora."},
{v:19,t:"Saíram de entre nós, mas não eram dos nossos; porque, se fossem dos nossos, teriam permanecido conosco. Assim se manifestou que nem todos são dos nossos."},
{v:20,t:"Vós, porém, tendes a unção que vem do Santo, e todos vós o sabeis."},
{v:21,t:"Não vos escrevi porque ignoreis a verdade, mas porque a conheceis, e porque nenhuma mentira vem da verdade."},
{v:22,t:"Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? Esse é o anticristo, que nega o Pai e o Filho."},
{v:23,t:"Todo o que nega o Filho não tem o Pai; quem confessa o Filho tem também o Pai."},
{v:24,t:"Permaneça em vós o que ouvistes desde o princípio. Se em vós permanecer o que ouvistes desde o princípio, também vós permanecereis no Filho e no Pai.",np:1},
{v:25,t:"E esta é a promessa que ele nos fez: a vida eterna."},
{v:26,t:"Escrevi-vos estas coisas a respeito dos que vos procuram desencaminhar."},
{v:27,t:"Quanto a vós, a unção que dele recebestes permanece em vós, e não tendes necessidade de que alguém vos ensine. Mas, assim como a sua unção vos ensina acerca de tudo — e é verdadeira, não mentira —, permanecei nele, como ela vos ensinou."},
{v:28,t:"Agora, filhinhos, permanecei nele, para que, quando se manifestar, tenhamos confiança e não fiquemos envergonhados diante dele na sua vinda."},
{v:29,t:"Se sabeis que ele é justo, reconhecei que todo o que pratica a justiça nasceu dele."}
];

window.TEXTOS_SEED["1joao"][3] = [
{s:"Filhos de Deus"},
{v:1,t:"Vede que amor nos deu o Pai: que fôssemos chamados filhos de Deus — e nós o somos! Se o mundo não nos conhece, é porque não o conheceu a ele."},
{v:2,t:"Caríssimos, agora somos filhos de Deus, e ainda não se manifestou o que havemos de ser. Sabemos que, quando ele se manifestar, seremos semelhantes a ele, porque o veremos tal como é."},
{v:3,t:"E todo o que tem nele esta esperança purifica-se a si mesmo, como ele é puro."},
{v:4,t:"Todo o que comete o pecado comete também a iniquidade, porque o pecado é a iniquidade."},
{v:5,t:"E sabeis que ele se manifestou para tirar os pecados; e nele não há pecado."},
{v:6,t:"Todo o que nele permanece não peca; todo o que peca não o viu nem o conheceu."},
{v:7,t:"Filhinhos, ninguém vos engane: quem pratica a justiça é justo, como ele é justo.",np:1},
{v:8,t:"Quem comete o pecado é do diabo, porque o diabo peca desde o princípio. Foi para isso que o Filho de Deus se manifestou: para destruir as obras do diabo."},
{v:9,t:"Todo o que nasceu de Deus não comete pecado, porque a semente de Deus permanece nele; e não pode pecar, porque nasceu de Deus."},
{v:10,t:"Nisto se manifestam os filhos de Deus e os filhos do diabo: todo o que não pratica a justiça não é de Deus, nem o que não ama o seu irmão."},
{s:"Amemo-nos uns aos outros"},
{v:11,t:"Porque esta é a mensagem que ouvistes desde o princípio: que nos amemos uns aos outros."},
{v:12,t:"Não como Caim, que era do maligno e matou o irmão. E por que o matou? Porque as suas obras eram más, e as do irmão, justas."},
{v:13,t:"Não vos admireis, irmãos, se o mundo vos odeia."},
{v:14,t:"Nós sabemos que passamos da morte para a vida, porque amamos os irmãos. Quem não ama permanece na morte."},
{v:15,t:"Todo o que odeia o seu irmão é homicida; e sabeis que nenhum homicida tem a vida eterna permanente em si."},
{v:16,t:"Nisto conhecemos o amor: ele deu a sua vida por nós. Também nós devemos dar a vida pelos irmãos."},
{v:17,t:"Se alguém possui os bens deste mundo e vê o irmão passar necessidade, mas lhe fecha o coração, como pode estar nele o amor de Deus?"},
{v:18,t:"Filhinhos, não amemos com palavras nem com a língua, mas com obras e em verdade."},
{s:"A confiança diante de Deus"},
{v:19,t:"Nisto conheceremos que somos da verdade, e diante dele tranquilizaremos o nosso coração,"},
{v:20,t:"seja no que for que o coração nos condene; porque Deus é maior que o nosso coração e conhece todas as coisas."},
{v:21,t:"Caríssimos, se o coração não nos condena, temos confiança diante de Deus;"},
{v:22,t:"e tudo o que pedimos, dele recebemos, porque guardamos os seus mandamentos e fazemos o que lhe é agradável."},
{v:23,t:"E este é o seu mandamento: que creiamos no nome de seu Filho Jesus Cristo e nos amemos uns aos outros, como ele nos ordenou."},
{v:24,t:"Quem guarda os seus mandamentos permanece em Deus, e Deus nele. E nisto sabemos que ele permanece em nós: pelo Espírito que nos deu."}
];

window.TEXTOS_SEED["1joao"][4] = [
{s:"Provai os espíritos"},
{v:1,t:"Caríssimos, não deis crédito a todo espírito; provai os espíritos, para ver se são de Deus, porque muitos falsos profetas saíram pelo mundo."},
{v:2,t:"Nisto conheceis o Espírito de Deus: todo espírito que confessa Jesus Cristo vindo na carne é de Deus;"},
{v:3,t:"e todo espírito que não confessa Jesus não é de Deus. Esse é o espírito do anticristo, de quem ouvistes que vem — e já está no mundo."},
{v:4,t:"Vós, filhinhos, sois de Deus, e os vencestes, porque aquele que está em vós é maior do que aquele que está no mundo."},
{v:5,t:"Eles são do mundo; por isso falam a linguagem do mundo, e o mundo os ouve."},
{v:6,t:"Nós somos de Deus. Quem conhece a Deus, ouve-nos; quem não é de Deus, não nos ouve. Nisto conhecemos o espírito da verdade e o espírito do erro."},
{s:"Deus é amor"},
{v:7,t:"Caríssimos, amemo-nos uns aos outros, porque o amor vem de Deus; e todo o que ama nasceu de Deus e conhece a Deus."},
{v:8,t:"Quem não ama não conheceu a Deus, porque Deus é amor."},
{v:9,t:"Nisto se manifestou entre nós o amor de Deus: Deus enviou ao mundo o seu Filho único, para que por ele vivamos."},
{v:10,t:"Nisto está o amor: não fomos nós que amamos a Deus, mas foi ele que nos amou e enviou o seu Filho como vítima de expiação pelos nossos pecados."},
{v:11,t:"Caríssimos, se Deus assim nos amou, também nós devemos amar-nos uns aos outros."},
{v:12,t:"Ninguém jamais viu a Deus. Se nos amamos uns aos outros, Deus permanece em nós, e o seu amor em nós é perfeito."},
{v:13,t:"Nisto conhecemos que permanecemos nele, e ele em nós: porque nos deu do seu Espírito.",np:1},
{v:14,t:"E nós vimos e damos testemunho de que o Pai enviou o Filho como salvador do mundo."},
{v:15,t:"Todo o que confessa que Jesus é o Filho de Deus, Deus permanece nele, e ele em Deus."},
{v:16,t:"E nós conhecemos e cremos no amor que Deus nos tem. Deus é amor, e quem permanece no amor permanece em Deus, e Deus nele."},
{v:17,t:"Nisto o amor é perfeito em nós: que tenhamos confiança no dia do juízo; porque, assim como ele é, assim somos nós neste mundo."},
{v:18,t:"No amor não há temor; ao contrário, o amor perfeito lança fora o temor, porque o temor supõe castigo. Quem teme não é perfeito no amor."},
{v:19,t:"Nós amamos porque ele nos amou primeiro."},
{v:20,t:"Se alguém diz: Amo a Deus, e odeia o seu irmão, é mentiroso. Pois quem não ama o irmão, a quem vê, não pode amar a Deus, a quem não vê."},
{v:21,t:"E dele recebemos este mandamento: que quem ama a Deus ame também o seu irmão."}
];

window.TEXTOS_SEED["1joao"][5] = [
{s:"A fé que vence o mundo"},
{v:1,t:"Todo o que crê que Jesus é o Cristo nasceu de Deus; e todo o que ama aquele que gerou ama também o que dele nasceu."},
{v:2,t:"Nisto conhecemos que amamos os filhos de Deus: quando amamos a Deus e cumprimos os seus mandamentos."},
{v:3,t:"Porque o amor de Deus consiste em guardarmos os seus mandamentos — e os seus mandamentos não são pesados."},
{v:4,t:"Pois tudo o que nasceu de Deus vence o mundo; e esta é a vitória que venceu o mundo: a nossa fé."},
{v:5,t:"Quem é o que vence o mundo, senão aquele que crê que Jesus é o Filho de Deus?"},
{s:"O testemunho de Deus"},
{v:6,t:"Ele é aquele que veio pela água e pelo sangue: Jesus Cristo; não só com a água, mas com a água e com o sangue. E é o Espírito que dá testemunho, porque o Espírito é a verdade."},
{v:7,t:"Porque são três os que dão testemunho:"},
{v:8,t:"o Espírito, a água e o sangue; e os três convergem no mesmo.",n:"Edições antigas traziam aqui um acréscimo sobre as três pessoas divinas, ausente dos manuscritos gregos e abandonado pela Nova Vulgata. A doutrina trinitária não depende dele."},
{v:9,t:"Se aceitamos o testemunho dos homens, o testemunho de Deus é maior; e este é o testemunho de Deus: o que ele deu a respeito de seu Filho."},
{v:10,t:"Quem crê no Filho de Deus tem em si esse testemunho. Quem não crê em Deus faz dele um mentiroso, por não crer no testemunho que Deus deu a respeito de seu Filho."},
{v:11,t:"E o testemunho é este: Deus nos deu a vida eterna, e essa vida está no seu Filho."},
{v:12,t:"Quem tem o Filho tem a vida; quem não tem o Filho de Deus não tem a vida."},
{s:"A confiança na oração"},
{v:13,t:"Escrevi-vos estas coisas, a vós que credes no nome do Filho de Deus, para que saibais que tendes a vida eterna."},
{v:14,t:"E esta é a confiança que temos nele: se pedimos alguma coisa segundo a sua vontade, ele nos ouve."},
{v:15,t:"E, se sabemos que ele nos ouve no que lhe pedimos, sabemos também que já obtivemos o que dele pedimos."},
{v:16,t:"Se alguém vê o seu irmão cometer um pecado que não leva à morte, ore, e Deus lhe dará a vida — a esses, cujo pecado não leva à morte. Há um pecado que leva à morte; não digo que se ore por esse."},
{v:17,t:"Toda injustiça é pecado; mas há pecado que não leva à morte."},
{v:18,t:"Sabemos que todo o que nasceu de Deus não peca; aquele que nasceu de Deus guarda-o, e o maligno não lhe toca.",np:1},
{v:19,t:"Sabemos que somos de Deus, e que o mundo inteiro jaz sob o poder do maligno."},
{v:20,t:"E sabemos que o Filho de Deus veio e nos deu inteligência para conhecermos aquele que é verdadeiro. E nós estamos naquele que é verdadeiro, em seu Filho Jesus Cristo. Ele é o Deus verdadeiro e a vida eterna."},
{v:21,t:"Filhinhos, guardai-vos dos ídolos."}
];
