// =====================================================================
// I Macabeus — tradução do grego, cotejado com a Nova Vulgata (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["1macabeus"][1] = [
{s:"Alexandre Magno e os seus sucessores"},
{v:1,t:"Depois que Alexandre, filho de Filipe, o macedônio, que antes reinara sobre a Grécia, saiu da terra de Cetim, derrotou Dario, rei dos persas e dos medos, e reinou em seu lugar,",n:"O primeiro livro dos Macabeus narra a resistência dos judeus contra os reis selêucidas da Síria, de 175 a 134 a.C., desde Antíoco IV Epífanes até a morte de Simão. Foi escrito em hebraico, por volta de 100 a.C., mas só chegou até nós em grego. Cetim é propriamente Chipre; aqui designa a Grécia e a Macedônia."},
{v:2,t:"travou muitas guerras, apoderou-se de fortalezas e matou reis da terra;"},
{v:3,t:"avançou até os confins da terra e tomou despojos de uma multidão de nações. A terra calou-se diante dele; e ele se exaltou, e o seu coração se ensoberbeceu."},
{v:4,t:"Reuniu um exército muito poderoso e dominou países, nações e soberanos, que lhe pagaram tributo."},
{v:5,t:"Depois disso caiu de cama e percebeu que ia morrer."},
{v:6,t:"Chamou os seus oficiais mais ilustres, que tinham sido criados com ele desde a juventude, e repartiu entre eles o seu reino, enquanto ainda vivia.",n:"Na realidade, Alexandre não repartiu o império; os seus generais o dividiram entre si depois da morte dele, em 323 a.C."},
{v:7,t:"Alexandre reinou doze anos e morreu."},
{v:8,t:"Os seus oficiais assumiram o poder, cada um na sua região."},
{v:9,t:"Depois da morte dele, todos cingiram o diadema, e depois deles os seus filhos, durante muitos anos; e multiplicaram os males sobre a terra."},
{s:"Antíoco Epífanes e os judeus helenizantes"},
{v:10,t:"Deles saiu um rebento pecador, Antíoco Epífanes, filho do rei Antíoco, que tinha estado em Roma como refém; e começou a reinar no ano cento e trinta e sete do reino dos gregos.",n:"O livro conta os anos pela era dos selêucidas, que começa em 312 a.C.; o ano cento e trinta e sete corresponde a 175 a.C."},
{v:11,t:"Naqueles dias surgiram de Israel homens sem lei, que seduziram muitos, dizendo: Vamos fazer aliança com as nações que nos rodeiam, porque, desde que nos separamos delas, caíram sobre nós muitos males."},
{v:12,t:"A proposta pareceu-lhes boa,"},
{v:13,t:"e alguns do povo se apressaram a ir ter com o rei, que lhes deu autorização para seguirem os costumes das nações."},
{v:14,t:"Construíram em Jerusalém um ginásio, segundo os costumes das nações;",np:1},
{v:15,t:"disfarçaram a circuncisão, abandonaram a aliança santa, associaram-se às nações e venderam-se para fazer o mal.",n:"Literalmente: refizeram os prepúcios. Com uma operação, apagavam o sinal da circuncisão, para não serem ridicularizados nos exercícios do ginásio, que se praticavam nus."},
{s:"Antíoco saqueia o templo"},
{v:16,t:"Quando se sentiu firme no reino, Antíoco decidiu apoderar-se também da terra do Egito, para reinar sobre os dois reinos."},
{v:17,t:"Entrou no Egito com um exército imponente, com carros, elefantes, cavaleiros e uma grande frota;"},
{v:18,t:"travou guerra contra Ptolomeu, rei do Egito; Ptolomeu recuou diante dele e fugiu, e muitos caíram feridos.",np:1},
{v:19,t:"Tomaram as cidades fortificadas do Egito, e Antíoco levou os despojos da terra do Egito."},
{v:20,t:"Depois de ter vencido o Egito, no ano cento e quarenta e três, Antíoco voltou e subiu contra Israel; subiu a Jerusalém com um exército imponente.",n:"Ano cento e quarenta e três: 169 a.C."},
{v:21,t:"Entrou com arrogância no santuário e levou o altar de ouro, o candelabro da luz com todos os seus utensílios,"},
{v:22,t:"a mesa dos pães da oferenda, os vasos das libações, as taças, os incensórios de ouro, o véu, as coroas e os ornamentos de ouro da fachada do templo; e arrancou todo o ouro."},
{v:23,t:"Tomou a prata, o ouro e os objetos preciosos, e tomou os tesouros escondidos que encontrou;",np:1},
{v:24,t:"e, levando tudo, voltou para a sua terra. Fez uma matança e proferiu palavras de grande arrogância."},
{v:25,t:"Houve grande luto em Israel, em todo lugar onde habitavam.",np:1},
{v:26,t:"Gemeram os chefes e os anciãos, as virgens e os jovens perderam as forças, e a beleza das mulheres se desfez."},
{v:27,t:"Todo noivo entoou um lamento, e a noiva sentada no quarto nupcial chorava."},
{v:28,t:"A terra estremeceu por causa dos seus habitantes, e toda a casa de Jacó se vestiu de vergonha."},
{s:"A destruição de Jerusalém e a Cidadela"},
{v:29,t:"Dois anos depois, o rei enviou às cidades de Judá um cobrador de tributos, que chegou a Jerusalém com um exército imponente.",n:"Cobrador de tributos: talvez uma leitura errada do hebraico; 2 Macabeus 5,24 diz que era Apolônio, chefe dos mísios, e em hebraico as duas expressões se parecem."},
{v:30,t:"Falou-lhes com palavras de paz, mas com astúcia, e eles acreditaram nele. Então atacou a cidade de surpresa, feriu-a com um golpe terrível e matou muita gente de Israel."},
{v:31,t:"Saqueou a cidade, incendiou-a e derrubou as suas casas e as muralhas ao redor."},
{v:32,t:"Levaram cativas as mulheres e as crianças e apoderaram-se do gado."},
{v:33,t:"Depois fortificaram a Cidade de Davi com uma muralha grande e forte, com torres fortes, e ela se tornou a sua cidadela.",np:1,n:"Cidadela: em grego, Acra, a fortaleza selêucida dentro de Jerusalém, junto ao templo, que só será tomada por Simão em 141 a.C. (13,49–51)."},
{v:34,t:"Puseram ali uma gente pecadora, homens sem lei, que se fortificaram nela."},
{v:35,t:"Armazenaram armas e víveres, reuniram os despojos de Jerusalém e os depositaram ali; e a cidadela tornou-se uma grande armadilha."},
{v:36,t:"Foi uma cilada para o santuário e um adversário perverso para Israel, continuamente."},
{v:37,t:"Derramaram sangue inocente ao redor do santuário e profanaram o santuário."},
{v:38,t:"Por causa deles, os habitantes de Jerusalém fugiram; ela tornou-se morada de estrangeiros, tornou-se estranha à sua própria descendência, e os seus filhos a abandonaram."},
{v:39,t:"O seu santuário ficou deserto como um ermo, as suas festas se transformaram em luto, os seus sábados em opróbrio, a sua honra em desprezo."},
{v:40,t:"Tão grande quanto a sua glória foi a sua desonra, e a sua grandeza se transformou em luto."},
{s:"A perseguição religiosa"},
{v:41,t:"O rei escreveu a todo o seu reino que todos formassem um só povo"},
{v:42,t:"e que cada um abandonasse os seus costumes. Todas as nações aceitaram a ordem do rei."},
{v:43,t:"Também muitos de Israel se agradaram do seu culto: ofereceram sacrifícios aos ídolos e profanaram o sábado."},
{v:44,t:"O rei enviou, por meio de mensageiros, cartas a Jerusalém e às cidades de Judá, ordenando que seguissem costumes estranhos à terra,"},
{v:45,t:"que suprimissem do santuário os holocaustos, o sacrifício e a libação, que profanassem os sábados e as festas,"},
{v:46,t:"que contaminassem o lugar santo e os santos,"},
{v:47,t:"que construíssem altares, recintos sagrados e templos de ídolos, que sacrificassem porcos e animais impuros,"},
{v:48,t:"que deixassem os seus filhos incircuncisos e se tornassem abomináveis com toda espécie de impureza e profanação,"},
{v:49,t:"de modo que esquecessem a Lei e mudassem todos os preceitos."},
{v:50,t:"Quem não agisse conforme a ordem do rei seria morto."},
{v:51,t:"Foi nesses termos que escreveu a todo o seu reino; nomeou inspetores sobre todo o povo e ordenou às cidades de Judá que oferecessem sacrifícios, cidade por cidade."},
{v:52,t:"Muitos do povo se juntaram a eles, todos os que abandonavam a Lei, e fizeram o mal na terra;"},
{v:53,t:"e obrigaram Israel a esconder-se em todos os seus refúgios."},
{v:54,t:"No dia quinze do mês de Casleu, no ano cento e quarenta e cinco, o rei erigiu sobre o altar a abominação da desolação; e nas cidades de Judá, ao redor, construíram altares;",np:1,n:"Ano cento e quarenta e cinco: dezembro de 167 a.C. A abominação da desolação era um altar pagão, dedicado a Zeus Olímpico (2 Macabeus 6,2), levantado sobre o altar dos holocaustos. A expressão vem de Daniel 9,27; 11,31; 12,11, e Jesus a retoma (Mateus 24,15)."},
{v:55,t:"e queimavam incenso às portas das casas e nas praças."},
{v:56,t:"Rasgavam e queimavam os livros da Lei que encontravam."},
{v:57,t:"Se encontravam com alguém um livro da aliança, ou se alguém se mostrava fiel à Lei, o decreto do rei o condenava à morte."},
{v:58,t:"Assim, com a força que tinham, agiam mês após mês contra os israelitas que encontravam nas cidades."},
{v:59,t:"No dia vinte e cinco de cada mês, ofereciam sacrifícios no altar pagão levantado sobre o altar dos holocaustos.",n:"O dia vinte e cinco era, provavelmente, a data em que se celebrava todo mês o aniversário do rei."},
{v:60,t:"As mulheres que tinham feito circuncidar os seus filhos eram mortas, conforme o decreto"},
{v:61,t:"— e penduravam as criancinhas ao pescoço delas —, e também as suas famílias e os que os tinham circuncidado."},
{v:62,t:"Mas muitos em Israel se mantiveram firmes e resolveram no seu íntimo não comer nada de impuro;"},
{v:63,t:"preferiram morrer a contaminar-se com aqueles alimentos e profanar a aliança santa; e morreram."},
{v:64,t:"Uma ira muito grande caiu sobre Israel."}
];

window.TEXTOS_SEED["1macabeus"][2] = [
{s:"Matatias e os seus filhos"},
{v:1,t:"Naqueles dias, Matatias, filho de João, filho de Simeão, sacerdote da descendência de Joiarib, partiu de Jerusalém e foi morar em Modin."},
{v:2,t:"Tinha cinco filhos: João, chamado Gadis;"},
{v:3,t:"Simão, chamado Tasi;"},
{v:4,t:"Judas, chamado Macabeu;",n:"Macabeu: apelido de sentido incerto, talvez martelo (em hebraico, maqqebet). Passou depois a designar toda a família e os que combateram com ela."},
{v:5,t:"Eleazar, chamado Abaran; e Jônatas, chamado Afus."},
{v:6,t:"Vendo as blasfêmias que se cometiam em Judá e em Jerusalém,",np:1},
{v:7,t:"Matatias disse: Ai de mim! Por que nasci para ver a ruína do meu povo e a ruína da cidade santa, e ficar aqui sentado enquanto ela é entregue nas mãos dos inimigos, e o santuário nas mãos de estrangeiros?"},
{v:8,t:"O seu templo tornou-se como um homem desonrado;"},
{v:9,t:"os seus objetos preciosos foram levados como presa; as suas crianças foram mortas nas praças, os seus jovens, pela espada do inimigo."},
{v:10,t:"Que nação não herdou o seu reino e não se apossou dos seus despojos?"},
{v:11,t:"Todos os seus adornos lhe foram arrancados; de livre que era, tornou-se escrava."},
{v:12,t:"Eis que o nosso santuário, a nossa beleza e a nossa glória foram devastados, e as nações os profanaram."},
{v:13,t:"Para que continuar vivendo?",np:1},
{v:14,t:"Matatias e os seus filhos rasgaram as vestes, vestiram-se de saco e fizeram grande luto."},
{s:"A revolta de Modin"},
{v:15,t:"Os oficiais do rei, encarregados de impor a apostasia, chegaram à cidade de Modin para fazer oferecer os sacrifícios."},
{v:16,t:"Muitos israelitas foram ter com eles; Matatias e os seus filhos também se reuniram ali."},
{v:17,t:"Os enviados do rei tomaram a palavra e disseram a Matatias: Tu és um chefe ilustre e poderoso nesta cidade, apoiado por filhos e irmãos."},
{v:18,t:"Aproxima-te, pois, tu primeiro e cumpre a ordem do rei, como fizeram todas as nações, os homens de Judá e os que ficaram em Jerusalém; e tu e a tua casa sereis contados entre os amigos do rei, e tu e os teus filhos sereis honrados com prata, ouro e muitos presentes.",n:"Amigos do rei: título oficial da corte selêucida."},
{v:19,t:"Matatias respondeu em alta voz: Ainda que todas as nações que estão no domínio do rei lhe obedeçam, abandonando cada uma o culto dos seus pais, e se submetam às suas ordens,"},
{v:20,t:"eu, os meus filhos e os meus irmãos seguiremos a aliança dos nossos pais."},
{v:21,t:"Deus nos livre de abandonar a Lei e os preceitos!"},
{v:22,t:"Não obedeceremos às ordens do rei, desviando-nos do nosso culto nem para a direita nem para a esquerda."},
{v:23,t:"Mal acabou de dizer estas palavras, um judeu se adiantou, à vista de todos, para oferecer sacrifício no altar de Modin, conforme a ordem do rei."},
{v:24,t:"Ao ver isso, Matatias inflamou-se de zelo, as suas entranhas estremeceram e deixou explodir uma justa ira: correu e o degolou sobre o altar.",n:"Nota do tradutor: O gesto de Matatias, que mata um compatriota no ato de sacrificar aos ídolos, é narrado como zelo pela Lei, à maneira de Fineias (Números 25,6–13). O texto não o atenua; reflete a gravidade que a idolatria tinha para a fé de Israel naquela hora de perseguição."},
{v:25,t:"Matou no mesmo instante o oficial do rei que obrigava a sacrificar e derrubou o altar."},
{v:26,t:"Assim mostrou o seu zelo pela Lei, como Fineias fez com Zambri, filho de Salu."},
{v:27,t:"Então Matatias gritou em alta voz pela cidade: Todo aquele que tem zelo pela Lei e se mantém fiel à aliança, venha comigo!"},
{v:28,t:"E fugiu com os seus filhos para as montanhas, deixando na cidade tudo o que possuíam."},
{s:"O massacre no deserto em dia de sábado"},
{v:29,t:"Então muitos que buscavam a justiça e o direito desceram ao deserto para morar ali,"},
{v:30,t:"eles, os seus filhos, as suas mulheres e os seus rebanhos, porque os males tinham caído pesadamente sobre eles."},
{v:31,t:"Os oficiais do rei e as tropas que estavam em Jerusalém, na Cidade de Davi, foram informados de que alguns homens que tinham desprezado a ordem do rei haviam descido aos esconderijos do deserto.",np:1},
{v:32,t:"Muitos correram atrás deles, alcançaram-nos, acamparam diante deles e prepararam-se para atacá-los no dia de sábado."},
{v:33,t:"E disseram-lhes: Basta! Saí, obedecei à ordem do rei e vivereis."},
{v:34,t:"Eles responderam: Não sairemos nem obedeceremos à ordem do rei, profanando o dia de sábado."},
{v:35,t:"Então os atacaram imediatamente."},
{v:36,t:"Mas eles não lhes responderam, nem lhes atiraram uma pedra, nem obstruíram os seus esconderijos;"},
{v:37,t:"diziam: Morramos todos na nossa inocência; o céu e a terra são testemunhas de que nos matais injustamente."},
{v:38,t:"Os inimigos os atacaram em pleno sábado, e morreram eles, as suas mulheres, os seus filhos e o seu gado: cerca de mil pessoas."},
{v:39,t:"Quando Matatias e os seus amigos o souberam, fizeram por eles um grande luto;",np:1},
{v:40,t:"e disseram uns aos outros: Se todos fizermos como os nossos irmãos fizeram, e não combatermos contra as nações pela nossa vida e pelos nossos preceitos, em pouco tempo nos farão desaparecer da terra."},
{v:41,t:"Naquele dia tomaram esta decisão: Se alguém vier atacar-nos em dia de sábado, combateremos contra ele, e não morreremos todos, como morreram os nossos irmãos nos esconderijos."},
{v:42,t:"Juntou-se a eles, então, a comunidade dos assideus, homens valentes de Israel, todos dedicados de coração à Lei.",n:"Assideus: em hebraico, hassidim, os piedosos, grupo de judeus fiéis de onde sairão mais tarde os fariseus e, talvez, os essênios."},
{v:43,t:"Todos os que fugiam dos males se uniram a eles e lhes deram apoio."},
{v:44,t:"Formaram um exército e feriram os pecadores na sua ira e os homens sem lei no seu furor; os que restaram fugiram para junto das nações, para se salvar.",np:1},
{v:45,t:"Matatias e os seus amigos percorreram o país e derrubaram os altares;",np:1},
{v:46,t:"circuncidaram à força todos os meninos incircuncisos que encontraram no território de Israel;"},
{v:47,t:"perseguiram os soberbos, e a obra prosperou nas suas mãos."},
{v:48,t:"Arrancaram a Lei das mãos das nações e das mãos dos reis, e não deixaram que o pecador prevalecesse."},
{s:"O testamento de Matatias"},
{v:49,t:"Quando se aproximaram os dias da sua morte, Matatias disse aos filhos: Agora triunfam a soberba e o insulto; é tempo de ruína e de ira furiosa."},
{v:50,t:"Agora, filhos, tende zelo pela Lei e dai a vida pela aliança dos nossos pais.",np:1},
{v:51,t:"Lembrai-vos das obras que os nossos pais realizaram no seu tempo, e alcançareis grande glória e um nome eterno."},
{v:52,t:"Abraão não foi achado fiel na provação, e isso não lhe foi contado como justiça?"},
{v:53,t:"José, no tempo da sua angústia, guardou o mandamento e tornou-se senhor do Egito."},
{v:54,t:"Fineias, nosso pai, pelo seu ardente zelo, recebeu a aliança de um sacerdócio eterno."},
{v:55,t:"Josué, por ter cumprido a palavra, tornou-se juiz em Israel."},
{v:56,t:"Caleb, por ter dado testemunho diante da assembleia, recebeu uma herança na terra."},
{v:57,t:"Davi, pela sua piedade, herdou o trono real para sempre."},
{v:58,t:"Elias, pelo seu ardente zelo pela Lei, foi arrebatado ao céu."},
{v:59,t:"Ananias, Azarias e Misael, por terem crido, foram salvos das chamas."},
{v:60,t:"Daniel, pela sua integridade, foi livrado da boca dos leões."},
{v:61,t:"Considerai, assim, de geração em geração: todos os que esperam nele não desfalecerão."},
{v:62,t:"Não temais as palavras do homem pecador, porque a sua glória acabará no esterco e nos vermes.",np:1},
{v:63,t:"Hoje se exalta, e amanhã já não será encontrado, porque terá voltado ao seu pó, e os seus projetos perecerão."},
{v:64,t:"E vós, filhos, sede fortes e corajosos na Lei, porque nela sereis glorificados.",np:1},
{v:65,t:"Aqui está Simão, vosso irmão: sei que é homem de conselho; escutai-o sempre; ele será para vós um pai."},
{v:66,t:"E Judas Macabeu, valente desde a juventude, será o chefe do vosso exército e conduzirá a guerra contra os povos."},
{v:67,t:"Reuni junto de vós todos os que praticam a Lei e vingai o vosso povo.",np:1},
{v:68,t:"Pagai às nações o que merecem e ficai atentos ao mandamento da Lei."},
{v:69,t:"Depois os abençoou e foi reunido aos seus pais.",np:1},
{v:70,t:"Morreu no ano cento e quarenta e seis e foi sepultado no túmulo dos seus pais, em Modin; e todo o Israel fez por ele um grande luto.",n:"Ano cento e quarenta e seis: 166 a.C."}
];
