// =====================================================================
// I Macabeus — tradução do grego, cotejado com a Nova Vulgata (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["1macabeus"][1] = [
{s:"Alexandre Magno e os seus sucessores"},
{v:1,t:"Depois que Alexandre, filho de Filipe, o macedônio, que antes reinara sobre a Grécia, saiu da terra de Cetim, derrotou Dario, rei dos persas e dos medos, e reinou em seu lugar,",n:"O primeiro livro dos Macabeus narra a resistência dos judeus contra os reis selêucidas da Síria, de 175 a 134 a.C., desde Antíoco IV Epífanes até a morte de Simão. Foi escrito em hebraico, por volta de 100 a.C., mas só chegou até nós em grego. Cetim é propriamente Chipre; aqui designa a Grécia e a Macedônia."},
{v:2,t:"travou muitas guerras, apoderou-se de fortalezas e matou reis da terra;"},
{v:3,t:"avançou até os confins da terra e tomou despojos de uma multidão de nações. A terra calou-se diante dele; e ele se exaltou, e o seu coração se ensoberbeceu."},
{v:4,t:"Reuniu um exército muito poderoso e dominou países, nações e soberanos, que lhe pagaram tributo."},
{v:5,t:"Depois disso caiu de cama e percebeu que ia morrer."},
{v:6,t:"Chamou os seus oficiais mais ilustres, que tinham sido criados com ele desde a juventude, e repartiu entre eles o seu reino, enquanto ainda vivia.",n:"Na realidade, Alexandre não repartiu o império; os seus generais o dividiram entre si depois da morte dele, em 323 a.C."},
{v:7,t:"Alexandre reinou doze anos e morreu."},
{v:8,t:"Os seus oficiais assumiram o poder, cada um na sua região."},
{v:9,t:"Depois da morte dele, todos cingiram o diadema, e depois deles os seus filhos, durante muitos anos; e multiplicaram os males sobre a terra."},
{s:"Antíoco Epífanes e os judeus helenizantes"},
{v:10,t:"Deles saiu um rebento pecador, Antíoco Epífanes, filho do rei Antíoco, que tinha estado em Roma como refém; e começou a reinar no ano cento e trinta e sete do reino dos gregos.",n:"O livro conta os anos pela era dos selêucidas, que começa em 312 a.C.; o ano cento e trinta e sete corresponde a 175 a.C."},
{v:11,t:"Naqueles dias surgiram de Israel homens sem lei, que seduziram muitos, dizendo: Vamos fazer aliança com as nações que nos rodeiam, porque, desde que nos separamos delas, caíram sobre nós muitos males."},
{v:12,t:"A proposta pareceu-lhes boa,"},
{v:13,t:"e alguns do povo se apressaram a ir ter com o rei, que lhes deu autorização para seguirem os costumes das nações."},
{v:14,t:"Construíram em Jerusalém um ginásio, segundo os costumes das nações;",np:1},
{v:15,t:"disfarçaram a circuncisão, abandonaram a aliança santa, associaram-se às nações e venderam-se para fazer o mal.",n:"Literalmente: refizeram os prepúcios. Com uma operação, apagavam o sinal da circuncisão, para não serem ridicularizados nos exercícios do ginásio, que se praticavam nus."},
{s:"Antíoco saqueia o templo"},
{v:16,t:"Quando se sentiu firme no reino, Antíoco decidiu apoderar-se também da terra do Egito, para reinar sobre os dois reinos."},
{v:17,t:"Entrou no Egito com um exército imponente, com carros, elefantes, cavaleiros e uma grande frota;"},
{v:18,t:"travou guerra contra Ptolomeu, rei do Egito; Ptolomeu recuou diante dele e fugiu, e muitos caíram feridos.",np:1},
{v:19,t:"Tomaram as cidades fortificadas do Egito, e Antíoco levou os despojos da terra do Egito."},
{v:20,t:"Depois de ter vencido o Egito, no ano cento e quarenta e três, Antíoco voltou e subiu contra Israel; subiu a Jerusalém com um exército imponente.",n:"Ano cento e quarenta e três: 169 a.C."},
{v:21,t:"Entrou com arrogância no santuário e levou o altar de ouro, o candelabro da luz com todos os seus utensílios,"},
{v:22,t:"a mesa dos pães da oferenda, os vasos das libações, as taças, os incensórios de ouro, o véu, as coroas e os ornamentos de ouro da fachada do templo; e arrancou todo o ouro."},
{v:23,t:"Tomou a prata, o ouro e os objetos preciosos, e tomou os tesouros escondidos que encontrou;",np:1},
{v:24,t:"e, levando tudo, voltou para a sua terra. Fez uma matança e proferiu palavras de grande arrogância."},
{v:25,t:"Houve grande luto em Israel, em todo lugar onde habitavam.",np:1},
{v:26,t:"Gemeram os chefes e os anciãos, as virgens e os jovens perderam as forças, e a beleza das mulheres se desfez."},
{v:27,t:"Todo noivo entoou um lamento, e a noiva sentada no quarto nupcial chorava."},
{v:28,t:"A terra estremeceu por causa dos seus habitantes, e toda a casa de Jacó se vestiu de vergonha."},
{s:"A destruição de Jerusalém e a Cidadela"},
{v:29,t:"Dois anos depois, o rei enviou às cidades de Judá um cobrador de tributos, que chegou a Jerusalém com um exército imponente.",n:"Cobrador de tributos: talvez uma leitura errada do hebraico; 2 Macabeus 5,24 diz que era Apolônio, chefe dos mísios, e em hebraico as duas expressões se parecem."},
{v:30,t:"Falou-lhes com palavras de paz, mas com astúcia, e eles acreditaram nele. Então atacou a cidade de surpresa, feriu-a com um golpe terrível e matou muita gente de Israel."},
{v:31,t:"Saqueou a cidade, incendiou-a e derrubou as suas casas e as muralhas ao redor."},
{v:32,t:"Levaram cativas as mulheres e as crianças e apoderaram-se do gado."},
{v:33,t:"Depois fortificaram a Cidade de Davi com uma muralha grande e forte, com torres fortes, e ela se tornou a sua cidadela.",np:1,n:"Cidadela: em grego, Acra, a fortaleza selêucida dentro de Jerusalém, junto ao templo, que só será tomada por Simão em 141 a.C. (13,49–51)."},
{v:34,t:"Puseram ali uma gente pecadora, homens sem lei, que se fortificaram nela."},
{v:35,t:"Armazenaram armas e víveres, reuniram os despojos de Jerusalém e os depositaram ali; e a cidadela tornou-se uma grande armadilha."},
{v:36,t:"Foi uma cilada para o santuário e um adversário perverso para Israel, continuamente."},
{v:37,t:"Derramaram sangue inocente ao redor do santuário e profanaram o santuário."},
{v:38,t:"Por causa deles, os habitantes de Jerusalém fugiram; ela tornou-se morada de estrangeiros, tornou-se estranha à sua própria descendência, e os seus filhos a abandonaram."},
{v:39,t:"O seu santuário ficou deserto como um ermo, as suas festas se transformaram em luto, os seus sábados em opróbrio, a sua honra em desprezo."},
{v:40,t:"Tão grande quanto a sua glória foi a sua desonra, e a sua grandeza se transformou em luto."},
{s:"A perseguição religiosa"},
{v:41,t:"O rei escreveu a todo o seu reino que todos formassem um só povo"},
{v:42,t:"e que cada um abandonasse os seus costumes. Todas as nações aceitaram a ordem do rei."},
{v:43,t:"Também muitos de Israel se agradaram do seu culto: ofereceram sacrifícios aos ídolos e profanaram o sábado."},
{v:44,t:"O rei enviou, por meio de mensageiros, cartas a Jerusalém e às cidades de Judá, ordenando que seguissem costumes estranhos à terra,"},
{v:45,t:"que suprimissem do santuário os holocaustos, o sacrifício e a libação, que profanassem os sábados e as festas,"},
{v:46,t:"que contaminassem o lugar santo e os santos,"},
{v:47,t:"que construíssem altares, recintos sagrados e templos de ídolos, que sacrificassem porcos e animais impuros,"},
{v:48,t:"que deixassem os seus filhos incircuncisos e se tornassem abomináveis com toda espécie de impureza e profanação,"},
{v:49,t:"de modo que esquecessem a Lei e mudassem todos os preceitos."},
{v:50,t:"Quem não agisse conforme a ordem do rei seria morto."},
{v:51,t:"Foi nesses termos que escreveu a todo o seu reino; nomeou inspetores sobre todo o povo e ordenou às cidades de Judá que oferecessem sacrifícios, cidade por cidade."},
{v:52,t:"Muitos do povo se juntaram a eles, todos os que abandonavam a Lei, e fizeram o mal na terra;"},
{v:53,t:"e obrigaram Israel a esconder-se em todos os seus refúgios."},
{v:54,t:"No dia quinze do mês de Casleu, no ano cento e quarenta e cinco, o rei erigiu sobre o altar a abominação da desolação; e nas cidades de Judá, ao redor, construíram altares;",np:1,n:"Ano cento e quarenta e cinco: dezembro de 167 a.C. A abominação da desolação era um altar pagão, dedicado a Zeus Olímpico (2 Macabeus 6,2), levantado sobre o altar dos holocaustos. A expressão vem de Daniel 9,27; 11,31; 12,11, e Jesus a retoma (Mateus 24,15)."},
{v:55,t:"e queimavam incenso às portas das casas e nas praças."},
{v:56,t:"Rasgavam e queimavam os livros da Lei que encontravam."},
{v:57,t:"Se encontravam com alguém um livro da aliança, ou se alguém se mostrava fiel à Lei, o decreto do rei o condenava à morte."},
{v:58,t:"Assim, com a força que tinham, agiam mês após mês contra os israelitas que encontravam nas cidades."},
{v:59,t:"No dia vinte e cinco de cada mês, ofereciam sacrifícios no altar pagão levantado sobre o altar dos holocaustos.",n:"O dia vinte e cinco era, provavelmente, a data em que se celebrava todo mês o aniversário do rei."},
{v:60,t:"As mulheres que tinham feito circuncidar os seus filhos eram mortas, conforme o decreto"},
{v:61,t:"— e penduravam as criancinhas ao pescoço delas —, e também as suas famílias e os que os tinham circuncidado."},
{v:62,t:"Mas muitos em Israel se mantiveram firmes e resolveram no seu íntimo não comer nada de impuro;"},
{v:63,t:"preferiram morrer a contaminar-se com aqueles alimentos e profanar a aliança santa; e morreram."},
{v:64,t:"Uma ira muito grande caiu sobre Israel."}
];

window.TEXTOS_SEED["1macabeus"][2] = [
{s:"Matatias e os seus filhos"},
{v:1,t:"Naqueles dias, Matatias, filho de João, filho de Simeão, sacerdote da descendência de Joiarib, partiu de Jerusalém e foi morar em Modin."},
{v:2,t:"Tinha cinco filhos: João, chamado Gadis;"},
{v:3,t:"Simão, chamado Tasi;"},
{v:4,t:"Judas, chamado Macabeu;",n:"Macabeu: apelido de sentido incerto, talvez martelo (em hebraico, maqqebet). Passou depois a designar toda a família e os que combateram com ela."},
{v:5,t:"Eleazar, chamado Abaran; e Jônatas, chamado Afus."},
{v:6,t:"Vendo as blasfêmias que se cometiam em Judá e em Jerusalém,",np:1},
{v:7,t:"Matatias disse: Ai de mim! Por que nasci para ver a ruína do meu povo e a ruína da cidade santa, e ficar aqui sentado enquanto ela é entregue nas mãos dos inimigos, e o santuário nas mãos de estrangeiros?"},
{v:8,t:"O seu templo tornou-se como um homem desonrado;"},
{v:9,t:"os seus objetos preciosos foram levados como presa; as suas crianças foram mortas nas praças, os seus jovens, pela espada do inimigo."},
{v:10,t:"Que nação não herdou o seu reino e não se apossou dos seus despojos?"},
{v:11,t:"Todos os seus adornos lhe foram arrancados; de livre que era, tornou-se escrava."},
{v:12,t:"Eis que o nosso santuário, a nossa beleza e a nossa glória foram devastados, e as nações os profanaram."},
{v:13,t:"Para que continuar vivendo?",np:1},
{v:14,t:"Matatias e os seus filhos rasgaram as vestes, vestiram-se de saco e fizeram grande luto."},
{s:"A revolta de Modin"},
{v:15,t:"Os oficiais do rei, encarregados de impor a apostasia, chegaram à cidade de Modin para fazer oferecer os sacrifícios."},
{v:16,t:"Muitos israelitas foram ter com eles; Matatias e os seus filhos também se reuniram ali."},
{v:17,t:"Os enviados do rei tomaram a palavra e disseram a Matatias: Tu és um chefe ilustre e poderoso nesta cidade, apoiado por filhos e irmãos."},
{v:18,t:"Aproxima-te, pois, tu primeiro e cumpre a ordem do rei, como fizeram todas as nações, os homens de Judá e os que ficaram em Jerusalém; e tu e a tua casa sereis contados entre os amigos do rei, e tu e os teus filhos sereis honrados com prata, ouro e muitos presentes.",n:"Amigos do rei: título oficial da corte selêucida."},
{v:19,t:"Matatias respondeu em alta voz: Ainda que todas as nações que estão no domínio do rei lhe obedeçam, abandonando cada uma o culto dos seus pais, e se submetam às suas ordens,"},
{v:20,t:"eu, os meus filhos e os meus irmãos seguiremos a aliança dos nossos pais."},
{v:21,t:"Deus nos livre de abandonar a Lei e os preceitos!"},
{v:22,t:"Não obedeceremos às ordens do rei, desviando-nos do nosso culto nem para a direita nem para a esquerda."},
{v:23,t:"Mal acabou de dizer estas palavras, um judeu se adiantou, à vista de todos, para oferecer sacrifício no altar de Modin, conforme a ordem do rei."},
{v:24,t:"Ao ver isso, Matatias inflamou-se de zelo, as suas entranhas estremeceram e deixou explodir uma justa ira: correu e o degolou sobre o altar.",n:"Nota do tradutor: O gesto de Matatias, que mata um compatriota no ato de sacrificar aos ídolos, é narrado como zelo pela Lei, à maneira de Fineias (Números 25,6–13). O texto não o atenua; reflete a gravidade que a idolatria tinha para a fé de Israel naquela hora de perseguição."},
{v:25,t:"Matou no mesmo instante o oficial do rei que obrigava a sacrificar e derrubou o altar."},
{v:26,t:"Assim mostrou o seu zelo pela Lei, como Fineias fez com Zambri, filho de Salu."},
{v:27,t:"Então Matatias gritou em alta voz pela cidade: Todo aquele que tem zelo pela Lei e se mantém fiel à aliança, venha comigo!"},
{v:28,t:"E fugiu com os seus filhos para as montanhas, deixando na cidade tudo o que possuíam."},
{s:"O massacre no deserto em dia de sábado"},
{v:29,t:"Então muitos que buscavam a justiça e o direito desceram ao deserto para morar ali,"},
{v:30,t:"eles, os seus filhos, as suas mulheres e os seus rebanhos, porque os males tinham caído pesadamente sobre eles."},
{v:31,t:"Os oficiais do rei e as tropas que estavam em Jerusalém, na Cidade de Davi, foram informados de que alguns homens que tinham desprezado a ordem do rei haviam descido aos esconderijos do deserto.",np:1},
{v:32,t:"Muitos correram atrás deles, alcançaram-nos, acamparam diante deles e prepararam-se para atacá-los no dia de sábado."},
{v:33,t:"E disseram-lhes: Basta! Saí, obedecei à ordem do rei e vivereis."},
{v:34,t:"Eles responderam: Não sairemos nem obedeceremos à ordem do rei, profanando o dia de sábado."},
{v:35,t:"Então os atacaram imediatamente."},
{v:36,t:"Mas eles não lhes responderam, nem lhes atiraram uma pedra, nem obstruíram os seus esconderijos;"},
{v:37,t:"diziam: Morramos todos na nossa inocência; o céu e a terra são testemunhas de que nos matais injustamente."},
{v:38,t:"Os inimigos os atacaram em pleno sábado, e morreram eles, as suas mulheres, os seus filhos e o seu gado: cerca de mil pessoas."},
{v:39,t:"Quando Matatias e os seus amigos o souberam, fizeram por eles um grande luto;",np:1},
{v:40,t:"e disseram uns aos outros: Se todos fizermos como os nossos irmãos fizeram, e não combatermos contra as nações pela nossa vida e pelos nossos preceitos, em pouco tempo nos farão desaparecer da terra."},
{v:41,t:"Naquele dia tomaram esta decisão: Se alguém vier atacar-nos em dia de sábado, combateremos contra ele, e não morreremos todos, como morreram os nossos irmãos nos esconderijos."},
{v:42,t:"Juntou-se a eles, então, a comunidade dos assideus, homens valentes de Israel, todos dedicados de coração à Lei.",n:"Assideus: em hebraico, hassidim, os piedosos, grupo de judeus fiéis de onde sairão mais tarde os fariseus e, talvez, os essênios."},
{v:43,t:"Todos os que fugiam dos males se uniram a eles e lhes deram apoio."},
{v:44,t:"Formaram um exército e feriram os pecadores na sua ira e os homens sem lei no seu furor; os que restaram fugiram para junto das nações, para se salvar.",np:1},
{v:45,t:"Matatias e os seus amigos percorreram o país e derrubaram os altares;",np:1},
{v:46,t:"circuncidaram à força todos os meninos incircuncisos que encontraram no território de Israel;"},
{v:47,t:"perseguiram os soberbos, e a obra prosperou nas suas mãos."},
{v:48,t:"Arrancaram a Lei das mãos das nações e das mãos dos reis, e não deixaram que o pecador prevalecesse."},
{s:"O testamento de Matatias"},
{v:49,t:"Quando se aproximaram os dias da sua morte, Matatias disse aos filhos: Agora triunfam a soberba e o insulto; é tempo de ruína e de ira furiosa."},
{v:50,t:"Agora, filhos, tende zelo pela Lei e dai a vida pela aliança dos nossos pais.",np:1},
{v:51,t:"Lembrai-vos das obras que os nossos pais realizaram no seu tempo, e alcançareis grande glória e um nome eterno."},
{v:52,t:"Abraão não foi achado fiel na provação, e isso não lhe foi contado como justiça?"},
{v:53,t:"José, no tempo da sua angústia, guardou o mandamento e tornou-se senhor do Egito."},
{v:54,t:"Fineias, nosso pai, pelo seu ardente zelo, recebeu a aliança de um sacerdócio eterno."},
{v:55,t:"Josué, por ter cumprido a palavra, tornou-se juiz em Israel."},
{v:56,t:"Caleb, por ter dado testemunho diante da assembleia, recebeu uma herança na terra."},
{v:57,t:"Davi, pela sua piedade, herdou o trono real para sempre."},
{v:58,t:"Elias, pelo seu ardente zelo pela Lei, foi arrebatado ao céu."},
{v:59,t:"Ananias, Azarias e Misael, por terem crido, foram salvos das chamas."},
{v:60,t:"Daniel, pela sua integridade, foi livrado da boca dos leões."},
{v:61,t:"Considerai, assim, de geração em geração: todos os que esperam nele não desfalecerão."},
{v:62,t:"Não temais as palavras do homem pecador, porque a sua glória acabará no esterco e nos vermes.",np:1},
{v:63,t:"Hoje se exalta, e amanhã já não será encontrado, porque terá voltado ao seu pó, e os seus projetos perecerão."},
{v:64,t:"E vós, filhos, sede fortes e corajosos na Lei, porque nela sereis glorificados.",np:1},
{v:65,t:"Aqui está Simão, vosso irmão: sei que é homem de conselho; escutai-o sempre; ele será para vós um pai."},
{v:66,t:"E Judas Macabeu, valente desde a juventude, será o chefe do vosso exército e conduzirá a guerra contra os povos."},
{v:67,t:"Reuni junto de vós todos os que praticam a Lei e vingai o vosso povo.",np:1},
{v:68,t:"Pagai às nações o que merecem e ficai atentos ao mandamento da Lei."},
{v:69,t:"Depois os abençoou e foi reunido aos seus pais.",np:1},
{v:70,t:"Morreu no ano cento e quarenta e seis e foi sepultado no túmulo dos seus pais, em Modin; e todo o Israel fez por ele um grande luto.",n:"Ano cento e quarenta e seis: 166 a.C."}
];

window.TEXTOS_SEED["1macabeus"][3] = [
{s:"O elogio de Judas Macabeu"},
{v:1,t:"Em seu lugar levantou-se o seu filho Judas, chamado Macabeu."},
{v:2,t:"Todos os seus irmãos e todos os que tinham seguido o seu pai o apoiavam, e combatiam com alegria as batalhas de Israel."},
{v:3,t:"Ele estendeu a glória do seu povo; vestiu a couraça como um gigante, cingiu as suas armas de guerra e travou batalhas, protegendo o acampamento com a espada."},
{v:4,t:"Nas suas façanhas era semelhante a um leão, a um leãozinho que ruge sobre a presa."},
{v:5,t:"Perseguiu os ímpios, procurando-os por toda parte, e entregou às chamas os que perturbavam o seu povo."},
{v:6,t:"Os ímpios se encolheram de medo diante dele, todos os que praticavam a iniquidade ficaram perturbados, e a salvação prosperou nas suas mãos."},
{v:7,t:"Causou amargura a muitos reis e alegrou Jacó com as suas façanhas; a sua memória será abençoada para sempre."},
{v:8,t:"Percorreu as cidades de Judá, exterminou delas os ímpios e afastou de Israel a ira."},
{v:9,t:"O seu nome chegou aos confins da terra, e ele reuniu os que estavam perdidos."},
{s:"As vitórias sobre Apolônio e Seron"},
{v:10,t:"Apolônio reuniu gente das nações e um grande exército da Samaria para combater contra Israel."},
{v:11,t:"Ao saber disso, Judas saiu ao seu encontro, derrotou-o e o matou. Muitos caíram mortos, e os restantes fugiram."},
{v:12,t:"Recolheram os seus despojos; Judas ficou com a espada de Apolônio e combateu com ela todos os dias da sua vida."},
{v:13,t:"Seron, comandante do exército da Síria, soube que Judas tinha reunido em torno de si uma multidão, uma assembleia de fiéis prontos para a guerra,"},
{v:14,t:"e disse: Vou fazer um nome e cobrir-me de glória no reino: combaterei Judas e os seus companheiros, que desprezam as ordens do rei."},
{v:15,t:"Preparou-se, e com ele subiu um forte exército de ímpios, para ajudá-lo a vingar-se dos filhos de Israel."},
{v:16,t:"Chegou à subida de Bet-Horon, e Judas saiu ao seu encontro com poucos homens."},
{v:17,t:"Quando viram o exército que vinha contra eles, disseram a Judas: Como poderemos, sendo tão poucos, combater contra uma multidão tão numerosa e forte? E nós estamos esgotados, porque hoje não comemos nada."},
{v:18,t:"Judas respondeu: É fácil que muitos caiam nas mãos de poucos; para o Céu não há diferença entre salvar com muitos ou com poucos,",n:"O Céu: modo respeitoso de designar Deus, frequente neste livro, que evita pronunciar o seu nome."},
{v:19,t:"porque a vitória na guerra não depende do tamanho do exército, mas a força vem do Céu."},
{v:20,t:"Eles vêm contra nós cheios de insolência e de iniquidade, para nos exterminar, a nós, às nossas mulheres e aos nossos filhos, e para nos saquear;",np:1},
{v:21,t:"nós, porém, combatemos pela nossa vida e pelas nossas leis."},
{v:22,t:"Ele mesmo os esmagará diante de nós; não tenhais medo deles."},
{v:23,t:"Quando acabou de falar, lançou-se de surpresa sobre eles, e Seron e o seu exército foram esmagados diante dele."},
{v:24,t:"Perseguiram-no pela descida de Bet-Horon até a planície; caíram uns oitocentos deles, e os restantes fugiram para a terra dos filisteus."},
{v:25,t:"Judas e os seus irmãos começaram a ser temidos, e o pavor caiu sobre as nações ao redor."},
{v:26,t:"A sua fama chegou até o rei, e todas as nações falavam das batalhas de Judas."},
{s:"Antíoco parte para a Pérsia"},
{v:27,t:"Quando o rei Antíoco ouviu essas notícias, enfureceu-se; mandou reunir todas as forças do seu reino, um exército muito poderoso."},
{v:28,t:"Abriu o seu tesouro, pagou às tropas o soldo de um ano e ordenou-lhes que estivessem prontas para qualquer necessidade."},
{v:29,t:"Mas viu que o dinheiro faltava nos seus cofres e que os tributos da região eram poucos, por causa da discórdia e da calamidade que ele mesmo provocara na terra, ao abolir as leis que vigoravam desde os tempos antigos;"},
{v:30,t:"e teve medo de não ter, como já acontecera uma ou duas vezes, com que pagar as despesas e os presentes que antes distribuía com mão generosa, superando nisso os reis que o precederam."},
{v:31,t:"Muito perplexo, decidiu ir à Pérsia para cobrar os tributos daquelas regiões e juntar muito dinheiro."},
{v:32,t:"Deixou Lísias, homem ilustre e de linhagem real, à frente dos negócios do rei, desde o rio Eufrates até a fronteira do Egito,"},
{v:33,t:"e encarregado de educar o seu filho Antíoco até a sua volta."},
{v:34,t:"Entregou-lhe metade das tropas e os elefantes, e deu-lhe instruções sobre tudo o que queria, especialmente sobre os habitantes da Judeia e de Jerusalém:"},
{v:35,t:"que enviasse contra eles um exército para esmagar e aniquilar a força de Israel e o que restava de Jerusalém, e apagar deste lugar a sua memória;"},
{v:36,t:"que estabelecesse estrangeiros em todo o seu território e distribuísse a sua terra em lotes."},
{v:37,t:"O rei tomou a outra metade das tropas e partiu de Antioquia, capital do seu reino, no ano cento e quarenta e sete; atravessou o rio Eufrates e percorreu as províncias altas.",n:"Ano cento e quarenta e sete: 165 a.C. As províncias altas são as do planalto do Irã."},
{s:"A expedição de Nicanor e Górgias"},
{v:38,t:"Lísias escolheu Ptolomeu, filho de Dorímenes, Nicanor e Górgias, homens poderosos entre os amigos do rei,"},
{v:39,t:"e enviou com eles quarenta mil homens e sete mil cavaleiros, para invadirem a terra de Judá e a devastarem, conforme a ordem do rei."},
{v:40,t:"Partiram com todas as suas tropas e vieram acampar perto de Emaús, na planície."},
{v:41,t:"Os mercadores da região ouviram falar deles; tomaram muita prata e muito ouro, e também grilhões, e foram ao acampamento para comprar os filhos de Israel como escravos. Juntaram-se a eles tropas da Síria e da terra dos estrangeiros.",n:"Síria: talvez se deva ler Edom, porque em hebraico as duas palavras se parecem. A terra dos estrangeiros é a Filisteia."},
{v:42,t:"Judas e os seus irmãos viram que os males se multiplicavam e que os exércitos acampavam no seu território; souberam também das ordens do rei, que mandara destruir e exterminar o povo.",np:1},
{v:43,t:"E disseram uns aos outros: Reergamos o nosso povo da sua ruína e combatamos pelo nosso povo e pelo santuário."},
{v:44,t:"Reuniu-se a assembleia, para se preparar para a guerra, para rezar e pedir misericórdia e compaixão."},
{v:45,t:"Jerusalém estava despovoada como um deserto; nenhum dos seus filhos entrava nem saía. O santuário era pisado, estrangeiros ocupavam a Cidadela, feita pousada das nações. A alegria desaparecera de Jacó, calaram-se a flauta e a cítara.",np:1},
{s:"A assembleia de Masfa"},
{v:46,t:"Reuniram-se e foram a Masfa, em frente a Jerusalém, porque antigamente Masfa era para Israel um lugar de oração."},
{v:47,t:"Jejuaram naquele dia, vestiram-se de saco, puseram cinza sobre a cabeça e rasgaram as vestes."},
{v:48,t:"Abriram o livro da Lei para nele buscar aquilo que os pagãos procuravam junto às imagens dos seus ídolos.",n:"Frase obscura. Talvez queira dizer que os judeus consultaram a Lei, como os pagãos consultavam os seus ídolos; outros entendem que os pagãos pintavam figuras dos seus ídolos nos livros da Lei."},
{v:49,t:"Trouxeram as vestes sacerdotais, as primícias e os dízimos, e fizeram vir os nazireus que tinham completado os dias do seu voto;"},
{v:50,t:"e clamaram em alta voz ao Céu: Que faremos com estes, e para onde os levaremos?",n:"Sem o templo, não havia como oferecer as primícias e os dízimos, nem como concluir o voto dos nazireus (Números 6,13–20)."},
{v:51,t:"O teu santuário foi pisado e profanado, e os teus sacerdotes estão de luto e humilhados."},
{v:52,t:"Eis que as nações se reuniram contra nós para nos exterminar; tu sabes o que tramam contra nós."},
{v:53,t:"Como poderemos resistir diante deles, se tu não nos ajudares?"},
{v:54,t:"Tocaram as trombetas e gritaram em alta voz."},
{v:55,t:"Depois disso, Judas nomeou chefes do povo: chefes de mil, de cem, de cinquenta e de dez."},
{v:56,t:"Aos que estavam construindo casa, aos que estavam noivos, aos que tinham plantado vinha e aos medrosos, disse que voltasse cada um para a sua casa, conforme a Lei.",n:"Veja Deuteronômio 20,5–8."},
{v:57,t:"Então o exército partiu e acampou ao sul de Emaús."},
{v:58,t:"Judas disse: Cingi-vos, sede valentes e estai prontos, amanhã de manhã, para combater contra essas nações que se reuniram contra nós para nos exterminar, a nós e ao nosso santuário."},
{v:59,t:"Porque é melhor morrermos combatendo do que ver as desgraças do nosso povo e do santuário."},
{v:60,t:"Seja qual for a vontade do Céu, ele a cumprirá."}
];

window.TEXTOS_SEED["1macabeus"][4] = [
{s:"A vitória de Emaús"},
{v:1,t:"Górgias tomou cinco mil homens e mil cavaleiros escolhidos, e o destacamento partiu de noite,"},
{v:2,t:"para cair sobre o acampamento dos judeus e atacá-los de surpresa; os homens da Cidadela lhe serviam de guias."},
{v:3,t:"Judas soube disso e partiu com os seus valentes, para atacar o exército do rei que estava em Emaús,"},
{v:4,t:"enquanto as tropas ainda estavam dispersas fora do acampamento."},
{v:5,t:"Górgias chegou de noite ao acampamento de Judas e não encontrou ninguém; então foi procurá-los nas montanhas, pensando: Estes fogem de nós."},
{v:6,t:"Ao romper do dia, Judas apareceu na planície com três mil homens, que não tinham as armaduras e as espadas que desejariam."},
{v:7,t:"Viram o acampamento dos pagãos, forte e bem armado, com a cavalaria ao redor, gente adestrada para a guerra."},
{v:8,t:"Judas disse aos homens que estavam com ele: Não temais a sua multidão, nem vos assusteis com o seu ataque."},
{v:9,t:"Lembrai-vos de como os nossos pais foram salvos no mar Vermelho, quando o faraó os perseguia com o seu exército."},
{v:10,t:"Clamemos agora ao Céu, para ver se ele terá compaixão de nós, se lembrará da aliança dos nossos pais e esmagará hoje este exército diante de nós."},
{v:11,t:"E todas as nações saberão que há quem resgate e salve Israel."},
{v:12,t:"Os estrangeiros ergueram os olhos e viram que eles vinham ao seu encontro;",np:1},
{v:13,t:"saíram do acampamento para a batalha. Os homens de Judas tocaram as trombetas"},
{v:14,t:"e travaram combate; os pagãos foram derrotados e fugiram para a planície."},
{v:15,t:"Todos os da retaguarda caíram pela espada. Perseguiram-nos até Gazer e até as planícies da Idumeia, de Azoto e de Jâmnia; e caíram deles uns três mil homens.",np:1},
{v:16,t:"Judas e o exército voltaram da perseguição,"},
{v:17,t:"e ele disse ao povo: Não cobiceis o saque, porque temos ainda uma batalha pela frente:"},
{v:18,t:"Górgias e o seu exército estão perto de nós, na montanha. Enfrentai agora os nossos inimigos e combatei-os; depois recolhereis o saque com segurança."},
{v:19,t:"Judas ainda estava falando quando apareceu um destacamento, espreitando do alto da montanha."},
{v:20,t:"Viram que os seus tinham sido postos em fuga e que o acampamento estava sendo incendiado; a fumaça que se via mostrava o que tinha acontecido."},
{v:21,t:"Diante disso, ficaram apavorados; e, vendo também o exército de Judas na planície, pronto para o combate,",np:1},
{v:22,t:"fugiram todos para a terra dos estrangeiros."},
{v:23,t:"Judas voltou para saquear o acampamento; recolheram muito ouro e prata, tecidos de púrpura violeta e de púrpura marinha, e grandes riquezas.",np:1},
{v:24,t:"Na volta, cantavam hinos e bendiziam o Céu: Porque ele é bom, porque o seu amor é para sempre."},
{v:25,t:"Naquele dia houve uma grande salvação para Israel."},
{s:"A vitória sobre Lísias em Bet-Sur"},
{v:26,t:"Os estrangeiros que escaparam foram contar a Lísias tudo o que tinha acontecido."},
{v:27,t:"Ao ouvir isso, ele ficou consternado e desanimado, porque as coisas não tinham acontecido em Israel como ele queria, nem saíram como o rei lhe ordenara."},
{v:28,t:"No ano seguinte, reuniu sessenta mil homens escolhidos e cinco mil cavaleiros, para acabar com eles.",np:1},
{v:29,t:"Vieram pela Idumeia e acamparam em Bet-Sur; Judas saiu ao seu encontro com dez mil homens."},
{v:30,t:"Vendo aquele exército poderoso, rezou assim: Bendito és tu, Salvador de Israel, que quebraste o ímpeto do guerreiro poderoso pela mão do teu servo Davi e entregaste o acampamento dos filisteus nas mãos de Jônatas, filho de Saul, e do seu escudeiro."},
{v:31,t:"Entrega também este exército nas mãos do teu povo, Israel, e que fiquem envergonhados com as suas tropas e a sua cavalaria."},
{v:32,t:"Infunde-lhes medo, derrete a audácia da sua força, e que vacilem na sua derrota."},
{v:33,t:"Abate-os pela espada dos que te amam, e que todos os que conhecem o teu nome te louvem com hinos."},
{v:34,t:"Travou-se o combate, e caíram do exército de Lísias uns cinco mil homens, abatidos diante deles.",np:1},
{v:35,t:"Quando Lísias viu a derrota das suas tropas e a coragem das de Judas, e como estavam prontos para viver ou morrer com valentia, voltou para Antioquia e recrutou mercenários, para voltar à Judeia com forças ainda maiores.",n:"Segundo 2 Macabeus 11,13–15, Lísias fez então um acordo de paz com os judeus."},
{s:"A purificação do templo"},
{v:36,t:"Então Judas e os seus irmãos disseram: Os nossos inimigos foram esmagados; subamos para purificar o santuário e consagrá-lo de novo."},
{v:37,t:"Todo o exército se reuniu, e subiram ao monte Sião.",np:1},
{v:38,t:"Viram o santuário abandonado, o altar profanado, as portas queimadas, e nos pátios o mato crescido como num bosque ou num monte, e as salas dos sacerdotes em ruínas."},
{v:39,t:"Rasgaram as vestes, fizeram grande lamentação, cobriram-se de cinza"},
{v:40,t:"e prostraram-se com o rosto em terra; tocaram as trombetas de sinal e clamaram ao Céu."},
{v:41,t:"Então Judas ordenou a alguns homens que combatessem os da Cidadela, até que ele terminasse de purificar o santuário."},
{v:42,t:"Escolheu sacerdotes sem defeito, dedicados à Lei,",np:1},
{v:43,t:"que purificaram o santuário e levaram para um lugar impuro as pedras da profanação."},
{v:44,t:"Discutiram o que fazer com o altar dos holocaustos, que tinha sido profanado,"},
{v:45,t:"e tiveram a boa ideia de demoli-lo, para que não lhes fosse motivo de vergonha, pois os pagãos o tinham contaminado. Demoliram, pois, o altar"},
{v:46,t:"e guardaram as pedras no monte do templo, num lugar conveniente, até que surgisse um profeta que decidisse o que fazer com elas."},
{v:47,t:"Tomaram pedras não lavradas, conforme a Lei, e construíram um altar novo, semelhante ao anterior.",n:"Pedras não lavradas: veja Êxodo 20,25 e Deuteronômio 27,5–6."},
{v:48,t:"Restauraram o santuário e o interior do templo, e consagraram os pátios."},
{v:49,t:"Fizeram novos objetos sagrados e levaram para dentro do templo o candelabro, o altar dos perfumes e a mesa.",np:1},
{v:50,t:"Queimaram incenso sobre o altar e acenderam as lâmpadas do candelabro, que iluminaram o templo."},
{v:51,t:"Puseram os pães sobre a mesa e penduraram as cortinas. Assim terminaram todas as obras que tinham empreendido."},
{s:"A dedicação do altar"},
{v:52,t:"No dia vinte e cinco do nono mês, que é o mês de Casleu, do ano cento e quarenta e oito, levantaram-se de madrugada",n:"Ano cento e quarenta e oito: dezembro de 164 a.C., três anos depois da profanação (1,54)."},
{v:53,t:"e ofereceram o sacrifício, conforme a Lei, sobre o novo altar dos holocaustos que tinham construído."},
{v:54,t:"No mesmo tempo e no mesmo dia em que os pagãos o tinham profanado, o altar foi consagrado de novo, com cânticos, cítaras, harpas e címbalos."},
{v:55,t:"Todo o povo se prostrou com o rosto em terra, adorou e bendisse o Céu, que lhes tinha dado a vitória.",np:1},
{v:56,t:"Celebraram durante oito dias a consagração do altar, oferecendo com alegria holocaustos e sacrifícios de comunhão e de louvor."},
{v:57,t:"Adornaram a fachada do templo com coroas de ouro e pequenos escudos, restauraram as portas e as salas dos sacerdotes e puseram-lhes portas."},
{v:58,t:"Houve imensa alegria entre o povo, e foi apagada a afronta dos pagãos."},
{v:59,t:"Judas, os seus irmãos e toda a assembleia de Israel determinaram que os dias da consagração do altar fossem celebrados a seu tempo, todos os anos, durante oito dias, a partir do dia vinte e cinco do mês de Casleu, com alegria e júbilo.",np:1,n:"É a festa da Dedicação, em hebraico Hanucá, que Jesus celebrou em Jerusalém (João 10,22)."},
{v:60,t:"Naquele tempo, cercaram o monte Sião de muralhas altas e torres fortes, para que os pagãos não viessem pisá-lo, como tinham feito antes."},
{v:61,t:"Judas deixou ali uma guarnição para defendê-lo; fortificou também Bet-Sur, para que o povo tivesse uma fortaleza diante da Idumeia."}
];

window.TEXTOS_SEED["1macabeus"][5] = [
{s:"Guerras contra os povos vizinhos"},
{v:1,t:"Quando as nações ao redor souberam que o altar tinha sido reconstruído e o santuário consagrado de novo como antes, ficaram muito irritadas"},
{v:2,t:"e resolveram exterminar os da raça de Jacó que viviam no meio delas; e começaram a matar e a destruir gente do povo."},
{v:3,t:"Judas combateu contra os filhos de Esaú na Idumeia, em Acrabatena, porque cercavam Israel; infligiu-lhes uma grande derrota, abateu-os e tomou os seus despojos."},
{v:4,t:"Lembrou-se também da maldade dos filhos de Bean, que eram para o povo um laço e uma armadilha, emboscando-o nos caminhos."},
{v:5,t:"Encurralou-os nas suas torres, sitiou-os, votou-os ao extermínio e incendiou as torres com todos os que estavam dentro.",n:"Nota do tradutor: Votar ao extermínio traduz o antigo herem, a lei de guerra que consagrava a Deus, pela destruição total, o inimigo vencido (Deuteronômio 20,16–18; Josué 6,17). O livro narra estas campanhas, com a matança dos homens e o incêndio das cidades (5,28.35.44.51), sem as atenuar."},
{v:6,t:"Depois passou contra os amonitas, onde encontrou uma força poderosa e muita gente, comandada por Timóteo."},
{v:7,t:"Travou com eles muitos combates; foram esmagados diante dele, e ele os derrotou."},
{v:8,t:"Tomou Jazer e as suas aldeias e voltou para a Judeia."},
{s:"Pedidos de socorro de Galaad e da Galileia"},
{v:9,t:"As nações de Galaad se coligaram contra os israelitas que viviam no seu território, para exterminá-los; e estes se refugiaram na fortaleza de Datema."},
{v:10,t:"Enviaram cartas a Judas e aos seus irmãos, dizendo: As nações ao redor se coligaram contra nós para nos exterminar;"},
{v:11,t:"preparam-se para vir tomar a fortaleza em que nos refugiamos, e Timóteo comanda o seu exército."},
{v:12,t:"Vem, pois, agora e livra-nos das suas mãos, porque muitos de nós já caíram;"},
{v:13,t:"todos os nossos irmãos que viviam na região de Tubin foram mortos; levaram cativas as suas mulheres e os seus filhos, com os seus bens, e mataram ali cerca de mil homens.",n:"No grego, na terra de Tobias, região a leste do Jordão."},
{v:14,t:"Ainda estavam lendo essas cartas, quando chegaram da Galileia outros mensageiros, com as vestes rasgadas, trazendo notícias semelhantes.",np:1},
{v:15,t:"Diziam: Os de Ptolemaida, de Tiro e de Sidônia, e toda a Galileia dos estrangeiros, se coligaram contra nós para nos exterminar."},
{v:16,t:"Quando Judas e o povo ouviram essas notícias, reuniu-se uma grande assembleia para decidir o que fazer pelos seus irmãos, que estavam em aflição e eram atacados pelos inimigos."},
{v:17,t:"Judas disse ao seu irmão Simão: Escolhe homens e vai libertar os teus irmãos da Galileia; eu e o meu irmão Jônatas iremos à região de Galaad."},
{v:18,t:"Deixou José, filho de Zacarias, e Azarias, chefe do povo, com o restante do exército na Judeia, para guardá-la,"},
{v:19,t:"e deu-lhes esta ordem: Tomai conta deste povo e não entreis em combate com as nações até que voltemos.",np:1},
{v:20,t:"Foram destinados três mil homens a Simão, para ir à Galileia, e oito mil a Judas, para a região de Galaad."},
{v:21,t:"Simão foi à Galileia e travou muitos combates com as nações, que foram esmagadas diante dele;",np:1},
{v:22,t:"perseguiu-as até a porta de Ptolemaida. Caíram uns três mil homens das nações, e ele tomou os seus despojos."},
{v:23,t:"Tomou consigo os judeus da Galileia e de Arbates, com as mulheres, os filhos e tudo o que possuíam, e levou-os para a Judeia com grande alegria."},
{s:"Judas em Galaad"},
{v:24,t:"Judas Macabeu e o seu irmão Jônatas atravessaram o Jordão e caminharam três dias pelo deserto."},
{v:25,t:"Encontraram os nabateus, que os receberam em paz e lhes contaram tudo o que acontecera aos seus irmãos na região de Galaad:"},
{v:26,t:"que muitos deles estavam cercados em Bosora e em Bosor, em Alema, em Casfo, em Maced e em Carnaim, todas cidades fortificadas e grandes;"},
{v:27,t:"que outros estavam cercados nas demais cidades de Galaad; e que os inimigos tinham decidido atacar as fortalezas no dia seguinte, tomá-las e exterminar todos num só dia."},
{v:28,t:"Judas e o seu exército mudaram de rumo de repente e foram pelo deserto até Bosora; tomaram a cidade, passaram ao fio da espada todos os homens, levaram todos os despojos e a incendiaram."},
{v:29,t:"Partiram dali de noite e marcharam até a fortaleza."},
{v:30,t:"Ao amanhecer, levantaram os olhos e viram uma multidão incontável, com escadas e máquinas de guerra, para tomar a fortaleza; já estavam atacando os que estavam dentro."},
{v:31,t:"Judas viu que o combate tinha começado e que o clamor da cidade subia ao céu, com trombetas e grandes gritos;"},
{v:32,t:"e disse aos homens do seu exército: Combatei hoje pelos nossos irmãos!"},
{v:33,t:"Avançou em três colunas pela retaguarda dos inimigos; tocaram as trombetas e clamaram em oração."},
{v:34,t:"O exército de Timóteo reconheceu que era o Macabeu e fugiu diante dele; Judas infligiu-lhes uma grande derrota, e naquele dia caíram deles uns oito mil homens."},
{v:35,t:"Depois Judas se desviou para Masfa, atacou-a e tomou-a; matou todos os seus homens, tomou os despojos e a incendiou.",n:"Masfa: assim a Nova Vulgata, com parte dos manuscritos gregos; outros leem Alema."},
{v:36,t:"De lá partiu e tomou Casfo, Maced, Bosor e as outras cidades de Galaad."},
{v:37,t:"Depois desses acontecimentos, Timóteo reuniu outro exército e acampou diante de Rafon, do outro lado da torrente."},
{v:38,t:"Judas mandou espiar o acampamento, e os espiões lhe informaram: Todas as nações ao nosso redor se juntaram a ele, um exército muito numeroso;"},
{v:39,t:"contrataram também árabes para os ajudar, e estão acampados do outro lado da torrente, prontos para vir atacar-te. Judas saiu ao encontro deles."},
{v:40,t:"Timóteo disse aos comandantes do seu exército: Quando Judas e o seu exército chegarem à torrente, se ele passar primeiro para o nosso lado, não conseguiremos resistir-lhe, porque certamente nos vencerá;"},
{v:41,t:"mas, se tiver medo e acampar do outro lado do rio, atravessaremos até ele e o venceremos."},
{v:42,t:"Quando Judas chegou à torrente, pôs os escribas do povo à beira da água e deu-lhes esta ordem: Não deixeis ninguém ficar acampado; que todos venham para o combate."},
{v:43,t:"Ele foi o primeiro a atravessar contra eles, e todo o povo atrás dele. Todas as nações foram esmagadas diante deles; largaram as armas e fugiram para o santuário pagão de Carnaim."},
{v:44,t:"Tomaram a cidade e incendiaram o santuário com todos os que estavam dentro. Carnaim foi abatida e não pôde mais resistir diante de Judas."},
{v:45,t:"Judas reuniu todos os israelitas que estavam na região de Galaad, do menor ao maior, com as mulheres, os filhos e os bens, uma caravana muito grande, para irem à terra de Judá."},
{v:46,t:"Chegaram a Efron, cidade grande e muito fortificada, situada no caminho; não havia como desviar-se dela, nem pela direita nem pela esquerda: era preciso passar pelo meio dela."},
{v:47,t:"Mas os habitantes da cidade fecharam-se dentro e obstruíram as portas com pedras. Judas mandou-lhes mensageiros com palavras de paz,",np:1},
{v:48,t:"dizendo: Deixai-nos passar pela vossa terra, para irmos à nossa; ninguém vos fará mal, só passaremos a pé. Mas eles não quiseram abrir-lhe as portas."},
{v:49,t:"Então Judas mandou anunciar no acampamento que cada um tomasse posição onde estava."},
{v:50,t:"Os guerreiros tomaram posição, e ele atacou a cidade durante todo aquele dia e toda a noite; e a cidade lhe foi entregue nas mãos."},
{v:51,t:"Passou ao fio da espada todos os homens, arrasou a cidade, tomou os seus despojos e atravessou-a por cima dos cadáveres."},
{v:52,t:"Atravessaram o Jordão para a grande planície, diante de Bet-San."},
{v:53,t:"Durante todo o caminho, Judas ia reunindo os que ficavam para trás e animando o povo, até chegarem à terra de Judá."},
{v:54,t:"Subiram ao monte Sião com alegria e júbilo e ofereceram holocaustos, porque nenhum deles tinha caído até voltarem em paz."},
{s:"A derrota de José e Azarias"},
{v:55,t:"Enquanto Judas e Jônatas estavam na terra de Galaad, e o seu irmão Simão na Galileia, diante de Ptolemaida,"},
{v:56,t:"José, filho de Zacarias, e Azarias, comandantes do exército, ouviram falar das façanhas e dos combates que eles tinham realizado,"},
{v:57,t:"e disseram: Façamos também nós um nome; vamos combater as nações ao nosso redor."},
{v:58,t:"Deram ordens às tropas que estavam com eles e marcharam contra Jâmnia."},
{v:59,t:"Górgias saiu da cidade com os seus homens para combatê-los."},
{v:60,t:"José e Azarias foram derrotados e perseguidos até a fronteira da Judeia; naquele dia caíram do povo de Israel uns dois mil homens. Foi uma grande derrota para o povo,"},
{v:61,t:"porque não tinham obedecido a Judas e aos seus irmãos, julgando que fariam proezas."},
{v:62,t:"Mas eles não eram da estirpe daqueles homens a quem fora confiada a salvação de Israel."},
{s:"Novas vitórias de Judas"},
{v:63,t:"O valente Judas e os seus irmãos foram muito honrados diante de todo o Israel e de todas as nações aonde chegava a sua fama;"},
{v:64,t:"e as pessoas acorriam a eles para os aclamar."},
{v:65,t:"Judas e os seus irmãos saíram para combater os filhos de Esaú na terra do sul. Tomou Hebron e as suas aldeias, demoliu as suas fortificações e incendiou as torres ao redor."},
{v:66,t:"Depois partiu para a terra dos filisteus e atravessou Maresa."},
{v:67,t:"Naquele dia caíram em combate alguns sacerdotes que, querendo mostrar a sua valentia, saíram imprudentemente para a batalha."},
{v:68,t:"Judas desviou-se para Azoto, na terra dos filisteus; derrubou os seus altares, queimou as imagens esculpidas dos seus deuses, saqueou as cidades e voltou para a terra de Judá."}
];

window.TEXTOS_SEED["1macabeus"][6] = [
{s:"A morte de Antíoco Epífanes"},
{v:1,t:"Enquanto isso, o rei Antíoco percorria as províncias altas. Soube que na Pérsia havia uma cidade chamada Elimaida, famosa pelas suas riquezas, pela prata e pelo ouro,",n:"Elimaida era na verdade uma região, no sudoeste do Irã. Ali Antíoco tentou saquear um templo e morreu pouco depois, em 164 a.C.; 2 Macabeus 1,13–17 e 9,1–29 contam a sua morte de outros modos."},
{v:2,t:"e que o seu templo era muito rico, com adornos de ouro, couraças e armas que ali deixara Alexandre, filho de Filipe, o rei macedônio, o primeiro a reinar sobre os gregos."},
{v:3,t:"Foi até lá e tentou tomar a cidade e saqueá-la, mas não conseguiu, porque os habitantes da cidade souberam do seu plano",np:1},
{v:4,t:"e o enfrentaram em combate. Ele fugiu e partiu dali, muito abatido, para voltar à Babilônia."},
{v:5,t:"Ainda na Pérsia, chegou-lhe um mensageiro com a notícia de que os exércitos enviados à terra de Judá tinham sido derrotados;"},
{v:6,t:"que Lísias, que fora à frente com um exército poderoso, tinha recuado diante deles; que os judeus se tinham fortalecido com as armas, as tropas e os muitos despojos tomados dos exércitos que tinham destroçado;"},
{v:7,t:"que tinham derrubado a abominação que ele erigira sobre o altar de Jerusalém, e que tinham cercado o santuário de muralhas altas, como antes, e também Bet-Sur, uma das suas cidades."},
{v:8,t:"Ao ouvir essas notícias, o rei ficou consternado e profundamente abalado; caiu de cama e adoeceu de tristeza, porque as coisas não tinham acontecido como ele queria."},
{v:9,t:"Ficou ali muitos dias, porque uma grande tristeza voltava sempre a tomá-lo, e pensou que ia morrer."},
{v:10,t:"Chamou todos os seus amigos e disse-lhes: O sono foge dos meus olhos, e o meu coração desfalece de preocupação."},
{v:11,t:"E disse comigo: A que aflição cheguei, e em que grande tormenta estou agora! Eu, que era bondoso e amado no meu poder!"},
{v:12,t:"Mas agora me lembro dos males que fiz em Jerusalém: levei todos os objetos de prata e de ouro que havia nela e mandei exterminar sem motivo os habitantes de Judá."},
{v:13,t:"Reconheço que é por isso que me sobrevieram esses males; e eis que morro de profunda tristeza em terra estrangeira."},
{v:14,t:"Chamou Filipe, um dos seus amigos, e o pôs à frente de todo o seu reino;"},
{v:15,t:"deu-lhe o diadema, o manto e o anel, para que conduzisse o seu filho Antíoco e o educasse para reinar."},
{v:16,t:"E o rei Antíoco morreu ali, no ano cento e quarenta e nove.",n:"Ano cento e quarenta e nove: 164–163 a.C."},
{v:17,t:"Quando Lísias soube que o rei tinha morrido, pôs no trono o filho dele, Antíoco, que ele educara desde menino, e deu-lhe o nome de Eupátor."},
{s:"O cerco da Cidadela"},
{v:18,t:"Os que ocupavam a Cidadela mantinham Israel encurralado ao redor do santuário e procuravam sempre fazer-lhe mal, servindo de apoio aos pagãos."},
{v:19,t:"Judas decidiu acabar com eles e convocou todo o povo para sitiá-los."},
{v:20,t:"Reuniram-se e sitiaram a Cidadela no ano cento e cinquenta; e construíram plataformas de tiro e máquinas de guerra.",n:"Ano cento e cinquenta: 163–162 a.C."},
{v:21,t:"Mas alguns dos sitiados escaparam, e juntaram-se a eles alguns ímpios de Israel;"},
{v:22,t:"foram ter com o rei e disseram: Até quando deixarás de fazer justiça e de vingar os nossos irmãos?"},
{v:23,t:"Nós aceitamos de boa vontade servir o teu pai, seguir as suas palavras e obedecer aos seus decretos."},
{v:24,t:"Por isso os filhos do nosso povo sitiaram a Cidadela e se tornaram nossos inimigos; mataram todos os nossos que encontraram e saquearam as nossas herdades."},
{v:25,t:"E não levantaram a mão só contra nós, mas também contra todo o território vizinho."},
{v:26,t:"Eis que hoje estão sitiando a Cidadela de Jerusalém para tomá-la; e fortificaram o santuário e Bet-Sur."},
{v:27,t:"Se não te antecipares a eles depressa, farão coisas ainda piores, e não poderás mais contê-los."},
{s:"A batalha de Bet-Zacarias"},
{v:28,t:"Ao ouvir isso, o rei enfureceu-se e reuniu todos os seus amigos, os comandantes do seu exército e os chefes da cavalaria."},
{v:29,t:"Vieram-lhe também tropas mercenárias de outros reinos e das ilhas do mar."},
{v:30,t:"O seu exército contava cem mil soldados de infantaria, vinte mil cavaleiros e trinta e dois elefantes adestrados para a guerra."},
{v:31,t:"Vieram pela Idumeia e acamparam diante de Bet-Sur; atacaram-na durante muitos dias e construíram máquinas de guerra; mas os sitiados saíram, incendiaram-nas e combateram com valentia."},
{v:32,t:"Então Judas retirou-se da Cidadela e acampou em Bet-Zacarias, diante do acampamento do rei."},
{v:33,t:"O rei levantou-se de madrugada e lançou o exército em marcha acelerada pelo caminho de Bet-Zacarias; as tropas se dispuseram para a batalha e tocaram as trombetas."},
{v:34,t:"Mostraram aos elefantes suco de uva e de amoras, para excitá-los ao combate."},
{v:35,t:"Distribuíram os animais pelas falanges; junto de cada elefante puseram mil homens com cotas de malha e capacetes de bronze na cabeça, e para cada animal foram destacados quinhentos cavaleiros escolhidos.",np:1},
{v:36,t:"Estes estavam sempre onde estava o animal e iam aonde ele ia, sem se afastar dele."},
{v:37,t:"Sobre cada animal havia uma torre de madeira, forte e coberta, presa a ele com correias; em cada torre iam quatro guerreiros, que combatiam de cima, além do condutor indiano."},
{v:38,t:"O restante da cavalaria, o rei o dispôs de um lado e do outro, nos dois flancos do exército, para inquietar o inimigo e proteger as falanges."},
{v:39,t:"Quando o sol brilhou sobre os escudos de ouro e de bronze, as montanhas resplandeceram com eles e brilharam como tochas acesas."},
{v:40,t:"Uma parte do exército do rei estendeu-se pelas alturas, e outra pelas partes baixas; e avançavam com segurança e em boa ordem."},
{v:41,t:"Todos os que ouviam o clamor daquela multidão, o marchar da tropa e o entrechocar das armas tremiam, porque o exército era imenso e poderoso."},
{v:42,t:"Judas e o seu exército avançaram para o combate, e caíram do exército do rei seiscentos homens.",np:1},
{v:43,t:"Eleazar, chamado Abaran, viu um dos animais coberto com a couraça real, mais alto que todos os outros, e pensou que nele estivesse o rei.",np:1},
{v:44,t:"Então se entregou à morte para salvar o seu povo e conquistar para si um nome eterno."},
{v:45,t:"Correu com audácia contra ele, pelo meio da falange, matando à direita e à esquerda, e os inimigos se abriam diante dele de um lado e de outro."},
{v:46,t:"Meteu-se debaixo do elefante, feriu-o por baixo e o matou; o animal caiu por terra sobre ele, e ele morreu ali."},
{v:47,t:"Os judeus, vendo a força do reino e o ímpeto das tropas, retiraram-se diante delas.",np:1},
{s:"O cerco do monte Sião"},
{v:48,t:"O exército do rei subiu atrás deles até Jerusalém, e o rei acampou contra a Judeia e contra o monte Sião."},
{v:49,t:"Fez as pazes com os de Bet-Sur, que saíram da cidade porque não tinham ali víveres para suportar o cerco, pois era um ano sabático para a terra.",n:"Ano sabático: a cada sete anos, a terra devia ficar em descanso, sem ser cultivada (Levítico 25,1–7)."},
{v:50,t:"O rei ocupou Bet-Sur e deixou ali uma guarnição para guardá-la."},
{v:51,t:"Depois sitiou o santuário durante muitos dias; montou ali plataformas de tiro, máquinas de guerra, lança-chamas, catapultas, escorpiões para disparar flechas e fundas."},
{v:52,t:"Os sitiados também construíram máquinas contra as máquinas deles e resistiram durante muitos dias."},
{v:53,t:"Mas não havia víveres nos depósitos, porque era o sétimo ano, e os que tinham fugido das nações para a Judeia tinham consumido o resto das provisões."},
{v:54,t:"Ficaram poucos homens no santuário, porque a fome os dominava; os outros se dispersaram, cada um para a sua casa."},
{s:"Lísias faz a paz com os judeus"},
{v:55,t:"Lísias soube então que Filipe, a quem o rei Antíoco, ainda em vida, encarregara de educar o seu filho Antíoco para reinar,"},
{v:56,t:"tinha voltado da Pérsia e da Média com as tropas que tinham ido com o rei, e que procurava assumir o governo."},
{v:57,t:"Apressou-se então a dar o sinal de partida e disse ao rei, aos comandantes do exército e aos soldados: Enfraquecemos a cada dia, os víveres são escassos, o lugar que sitiamos é bem fortificado, e os negócios do reino nos pressionam."},
{v:58,t:"Estendamos, pois, a mão direita a esses homens; façamos a paz com eles e com todo o seu povo,"},
{v:59,t:"e permitamos que vivam segundo as suas leis, como antes; pois foi por causa das suas leis, que nós abolimos, que eles se irritaram e fizeram tudo isso."},
{v:60,t:"A proposta agradou ao rei e aos chefes; mandou propor-lhes a paz, e eles a aceitaram."},
{v:61,t:"O rei e os chefes lhes fizeram um juramento, e com essas garantias eles saíram da fortaleza."},
{v:62,t:"Mas, quando o rei entrou no monte Sião e viu como o lugar era fortificado, violou o juramento que tinha feito e mandou demolir a muralha ao redor."},
{v:63,t:"Depois partiu às pressas e voltou para Antioquia, onde encontrou Filipe senhor da cidade; combateu contra ele e tomou a cidade à força."}
];
