// =====================================================================
// I Pedro — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["1pedro"][1] = [
{s:"Saudação"},
{v:1,t:"Pedro, apóstolo de Jesus Cristo, aos eleitos que vivem como estrangeiros, dispersos pelo Ponto, pela Galácia, pela Capadócia, pela Ásia e pela Bitínia,",n:"A carta dirige-se a comunidades da Ásia Menor que começavam a sofrer hostilidade. Fala a cristãos que são estrangeiros onde moram, e o tema do batismo atravessa-a de ponta a ponta."},
{v:2,t:"escolhidos segundo a presciência de Deus Pai, pela santificação do Espírito, para obedecerem a Jesus Cristo e serem aspergidos com o seu sangue: graça e paz vos sejam dadas em abundância."},
{s:"A esperança viva"},
{v:3,t:"Bendito seja Deus, Pai de nosso Senhor Jesus Cristo, que, na sua grande misericórdia, nos fez renascer para uma esperança viva, pela ressurreição de Jesus Cristo dentre os mortos;"},
{v:4,t:"para uma herança incorruptível, imaculada e que não murcha, reservada nos céus para vós,"},
{v:5,t:"que, pela fé, sois guardados pelo poder de Deus, em vista da salvação pronta a manifestar-se no último tempo."},
{v:6,t:"Nisso exultais, embora agora, por pouco tempo, tenhais de ser entristecidos por várias provações,"},
{v:7,t:"para que a prova da vossa fé — mais preciosa que o ouro perecível, que todavia se prova pelo fogo — redunde em louvor, glória e honra, na manifestação de Jesus Cristo."},
{v:8,t:"Sem o terdes visto, vós o amais; sem agora o verdes, nele credes; e exultais com alegria indizível e cheia de glória,"},
{v:9,t:"alcançando o fim da vossa fé: a salvação das almas."},
{v:10,t:"Foi acerca dessa salvação que indagaram e perscrutaram os profetas, quando profetizaram sobre a graça que vos era destinada.",np:1},
{v:11,t:"Procuravam saber a que tempo e a que circunstâncias se referia o Espírito de Cristo, que neles estava e de antemão testemunhava os sofrimentos de Cristo e as glórias que se lhes seguiriam."},
{v:12,t:"Foi-lhes revelado que não era para si mesmos, mas para vós, que administravam essas coisas, agora anunciadas por aqueles que vos pregaram o Evangelho, no Espírito Santo enviado do céu; coisas que os próprios anjos desejam contemplar."},
{s:"Sede santos"},
{v:13,t:"Por isso, cingindo os rins do vosso entendimento, sede sóbrios e ponde toda a vossa esperança na graça que vos será trazida na manifestação de Jesus Cristo."},
{v:14,t:"Como filhos obedientes, não vos conformeis às concupiscências de outrora, do tempo da vossa ignorância."},
{v:15,t:"Ao contrário: assim como é santo aquele que vos chamou, sede também vós santos em todo o vosso proceder,"},
{v:16,t:"porque está escrito: Sede santos, porque eu sou santo."},
{v:17,t:"E, se invocais como Pai aquele que julga a cada um, sem acepção de pessoas, segundo as suas obras, vivei no temor durante o tempo da vossa peregrinação;",np:1},
{v:18,t:"sabendo que fostes resgatados do vosso vão modo de viver, herdado dos pais, não com coisas corruptíveis, como a prata ou o ouro,"},
{v:19,t:"mas com o sangue precioso de Cristo, cordeiro sem defeito e sem mancha."},
{v:20,t:"Ele foi conhecido antes da criação do mundo e manifestado, no fim dos tempos, por amor de vós,"},
{v:21,t:"que por ele credes em Deus, o qual o ressuscitou dos mortos e lhe deu a glória, para que a vossa fé e a vossa esperança estejam em Deus."},
{v:22,t:"Tendo purificado as vossas almas pela obediência à verdade, para um amor fraterno sem fingimento, amai-vos intensamente uns aos outros, de coração puro;",np:1},
{v:23,t:"pois fostes regenerados não de uma semente corruptível, mas incorruptível: pela palavra de Deus, viva e permanente."},
{v:24,l:["Porque toda carne é como a erva,","e toda a sua glória, como a flor da erva.","Seca a erva, e cai a flor;"]},
{v:25,l:["mas a palavra do Senhor permanece para sempre.","E esta é a palavra que vos foi anunciada."]}
];

window.TEXTOS_SEED["1pedro"][2] = [
{s:"A pedra viva e o povo sacerdotal"},
{v:1,t:"Deixando, pois, toda malícia, todo engano, fingimentos, invejas e toda maledicência,"},
{v:2,t:"desejai, como crianças recém-nascidas, o leite puro da palavra, para por ele crescerdes em vista da salvação,"},
{v:3,t:"se é que provastes como é bom o Senhor."},
{v:4,t:"Aproximando-vos dele, pedra viva, rejeitada pelos homens, mas escolhida e preciosa diante de Deus,"},
{v:5,t:"também vós, como pedras vivas, sois edificados em casa espiritual, para um sacerdócio santo, a fim de oferecerdes sacrifícios espirituais, agradáveis a Deus por Jesus Cristo."},
{v:6,l:["Por isso se lê na Escritura:","Eis que ponho em Sião uma pedra angular, escolhida e preciosa;","e quem nela crer não será confundido."]},
{v:7,t:"Para vós, pois, que credes, é honra; mas, para os que não creem: A pedra que os construtores rejeitaram tornou-se a pedra angular,",np:1},
{v:8,t:"e pedra de tropeço, e rocha de escândalo. Eles tropeçam por não obedecerem à palavra — e para isso foram destinados."},
{v:9,t:"Vós, porém, sois a raça escolhida, o sacerdócio régio, a nação santa, o povo que Deus adquiriu, para anunciardes as maravilhas daquele que vos chamou das trevas para a sua luz admirável.",n:"São os títulos que o Êxodo dava a Israel no Sinai, e que aqui passam à Igreja. Deles vem a doutrina do sacerdócio comum de todos os batizados."},
{v:10,t:"Outrora não éreis povo; agora, porém, sois povo de Deus. Não tínheis alcançado misericórdia; agora, porém, alcançastes misericórdia."},
{s:"A conduta entre os gentios"},
{v:11,t:"Caríssimos, exorto-vos, como a estrangeiros e peregrinos, a que vos abstenhais dos desejos carnais, que fazem guerra contra a alma."},
{v:12,t:"Tende entre os gentios uma conduta exemplar, para que, no ponto em que vos caluniam como malfeitores, considerem as vossas boas obras e glorifiquem a Deus no dia da visita."},
{v:13,t:"Sujeitai-vos, por causa do Senhor, a toda instituição humana: seja ao rei, como soberano,"},
{v:14,t:"seja aos governadores, como enviados por ele para castigo dos malfeitores e louvor dos que fazem o bem."},
{v:15,t:"Porque esta é a vontade de Deus: que, fazendo o bem, façais calar a ignorância dos insensatos."},
{v:16,t:"Vivei como homens livres — não usando a liberdade como véu para a malícia —, mas como servos de Deus."},
{v:17,t:"Honrai a todos, amai os irmãos, temei a Deus, honrai o rei."},
{s:"O exemplo de Cristo"},
{v:18,t:"Servos, sede submissos com todo respeito aos vossos senhores, não só aos bons e moderados, mas também aos difíceis."},
{v:19,t:"Porque é uma graça suportar tristezas, sofrendo injustamente, por consideração a Deus."},
{v:20,t:"Que mérito há em suportar os golpes, se pecastes? Mas, se fazendo o bem sofreis e o suportais, isso é uma graça diante de Deus."},
{v:21,t:"É para isso que fostes chamados; porque também Cristo sofreu por vós, deixando-vos o exemplo, para que sigais os seus passos."},
{v:22,t:"Ele não cometeu pecado, nem se achou engano na sua boca."},
{v:23,t:"Injuriado, não injuriava; maltratado, não ameaçava; ao contrário, entregava-se àquele que julga com justiça."},
{v:24,t:"Ele mesmo levou os nossos pecados no seu corpo, sobre o madeiro, para que, mortos aos pecados, vivamos para a justiça. Pelas suas chagas fostes curados."},
{v:25,t:"Porque éreis como ovelhas desgarradas; agora, porém, voltastes ao pastor e guardião das vossas almas."}
];

window.TEXTOS_SEED["1pedro"][3] = [
{s:"Mulheres e maridos"},
{v:1,t:"Do mesmo modo, mulheres, sede submissas aos vossos maridos, para que, mesmo que alguns não obedeçam à palavra, sejam ganhos, sem palavra alguma, pelo proceder de suas mulheres,"},
{v:2,t:"ao verem a vossa conduta casta e respeitosa."},
{v:3,t:"Que o vosso adorno não seja o exterior: os cabelos trançados, os enfeites de ouro, os vestidos que se põem;"},
{v:4,t:"mas o homem escondido do coração, na incorruptibilidade de um espírito manso e tranquilo, que é precioso diante de Deus."},
{v:5,t:"Assim se adornavam outrora as santas mulheres que esperavam em Deus, submissas aos seus maridos,"},
{v:6,t:"como Sara, que obedecia a Abraão, chamando-lhe senhor. Dela vos tornastes filhas, se fazeis o bem e não vos deixais perturbar por temor algum."},
{v:7,t:"Do mesmo modo, maridos, vivei com elas segundo o conhecimento, dando honra à mulher como ao vaso mais frágil e como coerdeira da graça da vida, para que as vossas orações não encontrem obstáculo."},
{s:"Sofrer por causa da justiça"},
{v:8,t:"Enfim, tende todos o mesmo sentir, sede compassivos, cheios de amor fraterno, misericordiosos, humildes."},
{v:9,t:"Não pagueis mal com mal, nem injúria com injúria; ao contrário, abençoai, porque para isso fostes chamados: para herdardes a bênção."},
{v:10,l:["Porque quem quer amar a vida","e ver dias felizes","refreie a língua do mal","e os lábios, de falar com engano;"]},
{v:11,l:["afaste-se do mal e faça o bem;","busque a paz e corra atrás dela."]},
{v:12,l:["Porque os olhos do Senhor estão sobre os justos,","e os seus ouvidos, atentos às suas súplicas;","mas o rosto do Senhor volta-se contra os que fazem o mal."]},
{v:13,t:"E quem vos fará mal, se fordes zelosos do bem?",np:1},
{v:14,t:"Mas, ainda que tenhais de sofrer por causa da justiça, sois bem-aventurados. Não temais as suas ameaças, nem vos perturbeis."},
{v:15,t:"Antes, santificai em vossos corações Cristo como Senhor, sempre prontos a responder a todo o que vos pedir razão da esperança que há em vós —"},
{v:16,t:"mas com mansidão e respeito, tendo boa consciência, para que, naquilo em que sois caluniados, fiquem confundidos os que difamam o vosso bom proceder em Cristo."},
{v:17,t:"Porque é melhor sofrer fazendo o bem, se assim quiser Deus, do que fazendo o mal."},
{v:18,t:"Também Cristo morreu uma vez pelos pecados, o justo pelos injustos, para vos conduzir a Deus; morto na carne, foi vivificado no Espírito.",np:1},
{v:19,t:"Nele foi também pregar aos espíritos que estavam na prisão,",n:"É a passagem em que o Símbolo funda o artigo da descida à mansão dos mortos. Cristo leva a sua vitória até onde esperavam os que morreram antes dele."},
{v:20,t:"aos que outrora foram rebeldes, quando a paciência de Deus esperava, nos dias de Noé, enquanto se construía a arca, na qual poucos — isto é, oito pessoas — foram salvos através da água."},
{v:21,t:"Essa água era figura do batismo, que agora vos salva: não a remoção da sujeira do corpo, mas o compromisso de uma boa consciência para com Deus, pela ressurreição de Jesus Cristo."},
{v:22,t:"Ele está à direita de Deus, tendo subido ao céu, com anjos, potestades e poderes submetidos a ele."}
];

window.TEXTOS_SEED["1pedro"][4] = [
{s:"Romper com o pecado"},
{v:1,t:"Portanto, tendo Cristo sofrido na carne, armai-vos também vós do mesmo pensamento: quem sofreu na carne rompeu com o pecado,"},
{v:2,t:"para viver o resto do tempo na carne, já não segundo os desejos humanos, mas segundo a vontade de Deus."},
{v:3,t:"Basta o tempo passado em que fizestes a vontade dos gentios, vivendo na devassidão, nas paixões, nas bebedeiras, nas orgias, nos excessos e nas idolatrias criminosas."},
{v:4,t:"Por isso estranham que não corrais com eles para a mesma torrente de desregramento, e vos injuriam."},
{v:5,t:"Mas hão de prestar contas àquele que está pronto a julgar os vivos e os mortos."},
{v:6,t:"Foi para isso que se anunciou o Evangelho também aos mortos: para que, julgados segundo os homens na carne, vivam segundo Deus no espírito."},
{s:"O fim está próximo"},
{v:7,t:"O fim de todas as coisas está próximo. Sede, pois, prudentes e sóbrios, para vos dedicardes à oração."},
{v:8,t:"Antes de tudo, tende entre vós um amor intenso, porque o amor cobre uma multidão de pecados."},
{v:9,t:"Exercei a hospitalidade uns para com os outros, sem murmurar."},
{v:10,t:"Cada um ponha ao serviço dos outros o dom que recebeu, como bons administradores da multiforme graça de Deus."},
{v:11,t:"Se alguém fala, fale as palavras de Deus; se alguém serve, sirva com a força que Deus lhe dá, para que em tudo Deus seja glorificado por Jesus Cristo, a quem pertence a glória e o poder pelos séculos dos séculos. Amém."},
{s:"Sofrer como cristão"},
{v:12,t:"Caríssimos, não estranheis o incêndio que arde no meio de vós para vos provar, como se vos acontecesse coisa estranha."},
{v:13,t:"Ao contrário, alegrai-vos por participardes dos sofrimentos de Cristo, para que também na revelação da sua glória vos alegreis e exulteis."},
{v:14,t:"Se sois injuriados por causa do nome de Cristo, sois bem-aventurados, porque o Espírito da glória, que é o Espírito de Deus, repousa sobre vós."},
{v:15,t:"Que nenhum de vós sofra como homicida, ladrão, malfeitor ou como quem se intromete nos assuntos alheios."},
{v:16,t:"Mas, se sofre como cristão, não se envergonhe; antes, glorifique a Deus por esse nome.",n:"O nome cristão nasceu em Antioquia como alcunha de fora. Aqui já é assumido como título, e num contexto em que trazê-lo podia custar caro."},
{v:17,t:"Porque é chegado o tempo de começar o juízo pela casa de Deus. E, se começa por nós, qual será o fim dos que não obedecem ao Evangelho de Deus?"},
{v:18,t:"E, se o justo dificilmente se salva, que será do ímpio e do pecador?"},
{v:19,t:"Por isso, os que sofrem segundo a vontade de Deus confiem as suas almas ao Criador fiel, fazendo o bem."}
];

window.TEXTOS_SEED["1pedro"][5] = [
{s:"Aos pastores do rebanho"},
{v:1,t:"Aos presbíteros que estão entre vós, exorto eu, presbítero como eles, testemunha dos sofrimentos de Cristo e participante da glória que há de manifestar-se:"},
{v:2,t:"apascentai o rebanho de Deus que vos foi confiado, velando por ele, não por obrigação, mas de boa vontade, segundo Deus; não por torpe ganância, mas com generosidade;"},
{v:3,t:"não como quem domina sobre os que lhe couberam em partilha, mas tornando-vos modelo do rebanho."},
{v:4,t:"E, quando aparecer o pastor supremo, recebereis a coroa imarcescível da glória."},
{v:5,t:"Do mesmo modo, vós, os mais jovens, sede submissos aos presbíteros. E todos, uns para com os outros, revesti-vos de humildade, porque Deus resiste aos soberbos, mas dá graça aos humildes."},
{s:"Vigiai"},
{v:6,t:"Humilhai-vos, pois, sob a poderosa mão de Deus, para que ele vos exalte no tempo devido."},
{v:7,t:"Lançai sobre ele toda a vossa inquietação, porque ele tem cuidado de vós."},
{v:8,t:"Sede sóbrios e vigiai. O vosso adversário, o diabo, ronda como leão que ruge, procurando a quem devorar."},
{v:9,t:"Resisti-lhe, firmes na fé, sabendo que os mesmos sofrimentos se cumprem nos vossos irmãos espalhados pelo mundo."},
{v:10,t:"O Deus de toda graça, que vos chamou à sua glória eterna em Cristo, depois de um breve sofrimento, ele mesmo vos há de aperfeiçoar, firmar, fortalecer e consolidar."},
{v:11,t:"A ele o poder pelos séculos dos séculos. Amém."},
{s:"Saudações finais"},
{v:12,t:"Por Silvano, que tenho por irmão fiel, escrevi-vos brevemente, para vos exortar e atestar que esta é a verdadeira graça de Deus: nela ficai firmes."},
{v:13,t:"Saúda-vos a Igreja que está na Babilônia, eleita como vós, e também Marcos, meu filho.",n:"Babilônia é aqui o nome cifrado de Roma, como no Apocalipse. É o indício mais antigo da presença de Pedro na capital do Império."},
{v:14,t:"Saudai-vos uns aos outros com o ósculo do amor. Paz a todos vós, que estais em Cristo."}
];
