// =====================================================================
// I Reis — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["1reis"][1] = [
{s:"A velhice de Davi"},
{v:1,t:"O rei Davi estava velho, de idade muito avançada; cobriam-no de roupas, mas ele não se aquecia.",n:"Os livros dos Reis continuam a história de Samuel, da morte de Davi até o exílio da Babilônia. Na Bíblia hebraica formavam um só livro; a antiga Vulgata chamava-os Terceiro e Quarto dos Reis. Julgam cada rei pela sua fidelidade ao Senhor, segundo a lei do Deuteronômio, e ao único templo de Jerusalém."},
{v:2,t:"Os seus servos lhe disseram: Procure-se para o rei, nosso senhor, uma jovem virgem, que o assista e cuide dele; que durma nos teus braços, e o rei, nosso senhor, se aquecerá."},
{v:3,t:"Procuraram uma jovem bonita por todo o território de Israel; encontraram Abisag, a sunamita, e levaram-na ao rei."},
{v:4,t:"A jovem era muito bonita; cuidava do rei e o servia, mas o rei não a conheceu.",n:"O detalhe é importante para o capítulo seguinte: Abisag passa por concubina do rei, e pedi-la como esposa será reivindicar o trono (2,22)."},
{s:"A conspiração de Adonias"},
{v:5,t:"Adonias, filho de Hagit, encheu-se de pretensões, dizendo: Eu serei rei! Arranjou para si carros e cavaleiros, e cinquenta homens que corriam à sua frente.",np:1,n:"Adonias era o mais velho dos filhos vivos de Davi, depois da morte de Amnon e de Absalão; o direito de primogenitura parecia estar do seu lado. Imita Absalão (2 Samuel 15,1)."},
{v:6,t:"Seu pai nunca o tinha contrariado, dizendo: Por que fazes isso? Ele também era muito bonito, e tinha nascido depois de Absalão.",n:"Davi, pai fraco com os filhos, como com Amnon e Absalão."},
{v:7,t:"Entendeu-se com Joab, filho de Sárvia, e com o sacerdote Abiatar, que tomaram o partido de Adonias."},
{v:8,t:"Mas o sacerdote Sadoc, Banaías, filho de Joiada, o profeta Natã, Semei, Rei e os valentes de Davi não estavam com Adonias.",n:"Dois partidos na corte: de um lado, os velhos companheiros de Hebron, Joab e Abiatar; do outro, os homens de Jerusalém, Sadoc, Natã e a guarda de Banaías."},
{v:9,t:"Adonias sacrificou ovelhas, bois e bezerros cevados junto à pedra de Zoelet, que fica perto da fonte de Rogel, e convidou todos os seus irmãos, filhos do rei, e todos os homens de Judá que estavam a serviço do rei;"},
{v:10,t:"mas não convidou o profeta Natã, nem Banaías, nem os valentes, nem Salomão, seu irmão."},
{s:"Natã e Betsabeia"},
{v:11,t:"Então Natã disse a Betsabeia, mãe de Salomão: Não ouviste que Adonias, filho de Hagit, se fez rei, sem que Davi, nosso senhor, o saiba?",np:1},
{v:12,t:"Agora, pois, vem, deixa-me dar-te um conselho, para salvares a tua vida e a de teu filho Salomão.",n:"O novo rei costumava eliminar os rivais: se Adonias reinasse, Salomão e sua mãe corriam perigo de morte."},
{v:13,t:"Vai, entra na presença do rei Davi e dize-lhe: Ó rei, meu senhor, não juraste à tua serva: Teu filho Salomão reinará depois de mim e se sentará no meu trono? Por que, então, reina Adonias?",n:"Esse juramento não aparece em outro lugar. Natã e Betsabeia talvez se aproveitem da memória fraca do velho rei; mas a escolha de Salomão está de acordo com o amor de Deus por ele (2 Samuel 12,24-25)."},
{v:14,t:"E, enquanto ainda estiveres falando com o rei, eu entrarei depois de ti e confirmarei as tuas palavras."},
{v:15,t:"Betsabeia entrou no quarto do rei. O rei estava muito velho, e Abisag, a sunamita, o servia.",np:1},
{v:16,t:"Betsabeia inclinou-se e prostrou-se diante do rei, e o rei lhe perguntou: Que desejas?"},
{v:17,t:"Ela respondeu: Meu senhor, tu juraste à tua serva pelo Senhor teu Deus: Teu filho Salomão reinará depois de mim e se sentará no meu trono."},
{v:18,t:"E agora Adonias se fez rei, sem que tu, ó rei, meu senhor, o saibas."},
{v:19,t:"Sacrificou bois, bezerros cevados e grande quantidade de ovelhas, e convidou todos os filhos do rei, o sacerdote Abiatar e Joab, chefe do exército; mas não convidou Salomão, teu servo."},
{v:20,t:"E agora, ó rei, meu senhor, os olhos de todo o Israel estão voltados para ti, para que lhes anuncies quem se sentará no trono do rei, meu senhor, depois dele."},
{v:21,t:"Senão, quando o rei, meu senhor, repousar com seus pais, eu e meu filho Salomão seremos tratados como culpados."},
{v:22,t:"Ela ainda falava com o rei quando chegou o profeta Natã.",np:1},
{v:23,t:"Anunciaram ao rei: Está aqui o profeta Natã. Ele entrou na presença do rei e prostrou-se diante dele com o rosto em terra,"},
{v:24,t:"e disse: Ó rei, meu senhor, disseste então: Adonias reinará depois de mim e se sentará no meu trono?"},
{v:25,t:"Porque ele desceu hoje e sacrificou bois, bezerros cevados e grande quantidade de carneiros, e convidou todos os filhos do rei, os chefes do exército e o sacerdote Abiatar; e eles estão comendo e bebendo na sua presença e dizendo: Viva o rei Adonias!"},
{v:26,t:"Mas a mim, teu servo, ao sacerdote Sadoc, a Banaías, filho de Joiada, e a Salomão, teu servo, não convidou."},
{v:27,t:"Foi o rei, meu senhor, que ordenou isso, sem dizer aos teus servos quem se sentaria no trono do rei, meu senhor, depois dele?"},
{s:"Salomão ungido rei"},
{v:28,t:"O rei Davi respondeu: Chamai-me Betsabeia. Ela entrou na presença do rei e ficou de pé diante dele.",np:1},
{v:29,t:"E o rei jurou: Pela vida do Senhor, que me livrou de toda angústia,"},
{v:30,t:"assim como te jurei pelo Senhor, Deus de Israel, dizendo: Teu filho Salomão reinará depois de mim e se sentará no meu trono em meu lugar, assim farei hoje mesmo."},
{v:31,t:"Betsabeia inclinou-se com o rosto em terra, prostrou-se diante do rei e disse: Viva para sempre o rei Davi, meu senhor!"},
{v:32,t:"Depois o rei Davi disse: Chamai-me o sacerdote Sadoc, o profeta Natã e Banaías, filho de Joiada. Eles entraram na presença do rei,",np:1},
{v:33,t:"e o rei lhes disse: Tomai convosco os servos do vosso senhor, fazei montar meu filho Salomão na minha mula e levai-o a Gion.",n:"A mula do rei: montá-la era já tomar posse do trono. Gion é a fonte que abastecia Jerusalém, no vale do Cedron, não longe da fonte de Rogel, onde Adonias fazia festa."},
{v:34,t:"Ali o sacerdote Sadoc e o profeta Natã o ungirão rei sobre Israel; tocareis a trombeta e direis: Viva o rei Salomão!"},
{v:35,t:"Depois subireis atrás dele, e ele virá sentar-se no meu trono e reinará em meu lugar; porque é a ele que designo como chefe de Israel e de Judá."},
{v:36,t:"Banaías, filho de Joiada, respondeu ao rei: Amém! Assim o diga o Senhor, Deus do rei, meu senhor."},
{v:37,t:"Assim como o Senhor esteve com o rei, meu senhor, assim esteja com Salomão, e torne o seu trono ainda maior que o trono do rei Davi, meu senhor!"},
{v:38,t:"O sacerdote Sadoc, o profeta Natã, Banaías, filho de Joiada, os cereteus e os feleteus desceram, fizeram Salomão montar na mula do rei Davi e o levaram a Gion.",np:1},
{v:39,t:"O sacerdote Sadoc tomou da tenda o chifre de óleo e ungiu Salomão; tocaram a trombeta, e todo o povo disse: Viva o rei Salomão!",n:"A tenda onde estava a arca, em Jerusalém (2 Samuel 6,17). A unção de Salomão é, desde então, cantada na liturgia da sagração dos reis cristãos."},
{v:40,t:"Todo o povo subiu atrás dele, tocando flautas e com grande alegria, e a terra estremecia com os seus gritos."},
{s:"O medo de Adonias"},
{v:41,t:"Adonias e todos os seus convidados ouviram o barulho, quando já tinham acabado de comer. Joab, ouvindo o som da trombeta, perguntou: Que significa este barulho da cidade em alvoroço?",np:1},
{v:42,t:"Ainda estava falando quando chegou Jônatas, filho do sacerdote Abiatar. Adonias lhe disse: Entra, porque és um homem de bem e trazes boas notícias."},
{v:43,t:"Jônatas respondeu a Adonias: Pelo contrário! O rei Davi, nosso senhor, fez rei Salomão;"},
{v:44,t:"enviou com ele o sacerdote Sadoc, o profeta Natã, Banaías, filho de Joiada, os cereteus e os feleteus, e eles o fizeram montar na mula do rei."},
{v:45,t:"O sacerdote Sadoc e o profeta Natã ungiram-no rei em Gion, e de lá subiram com alegria, e a cidade está em alvoroço: é esse o barulho que ouvistes."},
{v:46,t:"E Salomão já se sentou no trono real;"},
{v:47,t:"e os servos do rei vieram felicitar o rei Davi, nosso senhor, dizendo: Que Deus torne o nome de Salomão ainda mais célebre que o teu, e o seu trono ainda maior que o teu! E o rei prostrou-se no seu leito."},
{v:48,t:"E disse ainda: Bendito seja o Senhor, Deus de Israel, que hoje concedeu que alguém se sentasse no meu trono, e os meus olhos o veem!"},
{v:49,t:"Todos os convidados de Adonias, apavorados, levantaram-se e foram-se, cada um para o seu lado.",np:1},
{v:50,t:"Adonias, com medo de Salomão, levantou-se e foi agarrar-se às pontas do altar.",n:"As pontas do altar, em forma de chifres, davam direito de asilo a quem tivesse matado sem intenção (Êxodo 21,13-14)."},
{v:51,t:"Foram dizer a Salomão: Adonias tem medo do rei Salomão e está agarrado às pontas do altar, dizendo: Que o rei Salomão me jure hoje que não matará o seu servo à espada."},
{v:52,t:"Salomão disse: Se ele se portar como homem de bem, não cairá por terra um só cabelo da sua cabeça; mas, se for achado nele algum mal, morrerá."},
{v:53,t:"O rei Salomão mandou tirá-lo do altar, e ele veio prostrar-se diante do rei Salomão; e Salomão lhe disse: Vai para tua casa."}
];

window.TEXTOS_SEED["1reis"][2] = [
{s:"O testamento de Davi"},
{v:1,t:"Aproximando-se o dia da sua morte, Davi deu estas instruções a seu filho Salomão:"},
{v:2,t:"Eu vou pelo caminho de todos os mortais. Sê forte e porta-te como homem.",n:"O caminho de todos os mortais: a mesma expressão com que Josué se despede (Josué 23,14)."},
{v:3,t:"Guarda as ordens do Senhor teu Deus, andando nos seus caminhos e observando os seus estatutos, os seus mandamentos, os seus preceitos e os seus testemunhos, como está escrito na Lei de Moisés, para que prosperes em tudo o que fizeres e para onde quer que te voltes;",n:"A linguagem é a do Deuteronômio: é a medida pela qual o livro julgará todos os reis."},
{v:4,t:"para que o Senhor cumpra a palavra que disse a meu respeito: Se os teus filhos guardarem o seu caminho, andando diante de mim com fidelidade, de todo o coração e de toda a alma, não te faltará um descendente no trono de Israel."},
{v:5,t:"Tu sabes também o que me fez Joab, filho de Sárvia, o que fez aos dois chefes do exército de Israel, Abner, filho de Ner, e Amasa, filho de Jeter, a quem matou: derramou em tempo de paz sangue de guerra e manchou de sangue de guerra o cinturão que tinha à cintura e as sandálias que tinha nos pés.",np:1,n:"Davi pede a Salomão a justiça que ele mesmo não pôde fazer (2 Samuel 3,39). A lógica é também política: afastar do novo reino os homens perigosos."},
{v:6,t:"Faze, pois, segundo a tua sabedoria, e não deixes os seus cabelos brancos descerem em paz à morada dos mortos."},
{v:7,t:"Mas aos filhos de Berzelai, o galaadita, mostra a tua gratidão: que eles comam à tua mesa, porque me acolheram quando eu fugia de Absalão, teu irmão."},
{v:8,t:"Tens também junto de ti Semei, filho de Gera, benjaminita de Baurim, que me amaldiçoou com uma maldição terrível no dia em que eu ia para Maanaim; mas ele desceu ao meu encontro no Jordão, e eu lhe jurei pelo Senhor: Não te matarei à espada."},
{v:9,t:"Tu, porém, não o deixes impune; és um homem sábio e saberás o que fazer com ele: farás descer com sangue os seus cabelos brancos à morada dos mortos.",n:"Davi respeitou o juramento durante a sua vida, mas não o estende ao filho. A maldição de Semei pesava, segundo a mentalidade da época, sobre a dinastia."},
{s:"A morte de Davi"},
{v:10,t:"Davi repousou com seus pais e foi sepultado na Cidade de Davi.",np:1,n:"No dia de Pentecostes, Pedro lembrará que o túmulo de Davi ainda estava entre eles (Atos 2,29)."},
{v:11,t:"Davi reinou sobre Israel quarenta anos: sete anos em Hebron e trinta e três em Jerusalém."},
{v:12,t:"Salomão sentou-se no trono de Davi, seu pai, e o seu reino ficou muito firme."},
{s:"Salomão elimina os seus adversários"},
{v:13,t:"Adonias, filho de Hagit, foi ter com Betsabeia, mãe de Salomão. Ela lhe perguntou: Vens em paz? Ele respondeu: Em paz.",np:1},
{v:14,t:"E acrescentou: Tenho uma coisa a te dizer. Ela respondeu: Fala. E ele disse:"},
{v:15,t:"Tu sabes que o reino era meu, e que todo o Israel esperava que eu fosse rei; mas o reino passou para meu irmão, porque lhe foi dado pelo Senhor."},
{v:16,t:"Agora, pois, tenho um só pedido a te fazer; não me recuses. Ela lhe disse: Fala."},
{v:17,t:"Ele disse: Peço-te que digas ao rei Salomão — porque ele nada te recusará — que me dê por mulher Abisag, a sunamita."},
{v:18,t:"Betsabeia respondeu: Está bem; falarei ao rei a teu respeito."},
{v:19,t:"Betsabeia foi ter com o rei Salomão, para lhe falar a respeito de Adonias. O rei levantou-se para ir ao seu encontro, inclinou-se diante dela e sentou-se no seu trono; mandou pôr um trono para a mãe do rei, e ela se sentou à sua direita.",n:"A mãe do rei, a gebirá, tinha na corte uma dignidade própria: sentava-se à direita do filho e intercedia junto dele. A tradição cristã viu nesta cena uma imagem de Maria, mãe do Rei messiânico."},
{v:20,t:"Ela disse: Tenho um pequeno pedido a te fazer; não me recuses. O rei lhe disse: Pede, minha mãe, porque não te recusarei."},
{v:21,t:"Ela disse: Que Abisag, a sunamita, seja dada por mulher a teu irmão Adonias."},
{v:22,t:"O rei Salomão respondeu a sua mãe: Por que pedes Abisag, a sunamita, para Adonias? Pede para ele também o reino! Ele é meu irmão mais velho, e tem a seu favor o sacerdote Abiatar e Joab, filho de Sárvia.",n:"Tomar a mulher do harém do rei morto era reivindicar a sua sucessão (2 Samuel 16,21-22). Salomão entende o pedido como nova tentativa de golpe."},
{v:23,t:"E o rei Salomão jurou pelo Senhor: Que Deus me faça isto e mais aquilo, se não for à custa da própria vida que Adonias disse esta palavra!"},
{v:24,t:"E agora, pela vida do Senhor, que me firmou e me fez sentar no trono de Davi, meu pai, e que me fez uma casa, como tinha prometido: hoje mesmo Adonias morrerá."},
{v:25,t:"O rei Salomão deu a ordem a Banaías, filho de Joiada, que o feriu, e ele morreu."},
{v:26,t:"Ao sacerdote Abiatar o rei disse: Vai para Anatot, para as tuas terras. Mereces a morte, mas hoje não te farei morrer, porque levaste a arca do Senhor Deus diante de Davi, meu pai, e partilhaste todos os sofrimentos de meu pai.",np:1,n:"Anatot, perto de Jerusalém, será a terra do profeta Jeremias, de família sacerdotal, talvez descendente de Abiatar."},
{v:27,t:"Assim Salomão afastou Abiatar do sacerdócio do Senhor, cumprindo a palavra que o Senhor tinha dito contra a casa de Heli, em Silo.",n:"Cumpre-se a profecia de 1 Samuel 2,30-35: Abiatar é o último descendente de Heli no sacerdócio; o sacerdócio passa a Sadoc e aos seus filhos."},
{v:28,t:"A notícia chegou a Joab, que tinha tomado o partido de Adonias, embora não tivesse tomado o de Absalão. Joab fugiu para a tenda do Senhor e agarrou-se às pontas do altar.",np:1},
{v:29,t:"Informaram o rei Salomão de que Joab tinha fugido para a tenda do Senhor e estava junto do altar; e Salomão enviou Banaías, filho de Joiada, dizendo: Vai e mata-o!"},
{v:30,t:"Banaías foi à tenda do Senhor e lhe disse: Assim diz o rei: Sai daí! Ele respondeu: Não; morrerei aqui. Banaías levou a resposta ao rei, dizendo: Assim falou Joab, e assim me respondeu."},
{v:31,t:"O rei lhe disse: Faze como ele disse: mata-o e sepulta-o; assim tirarás de mim e da casa de meu pai o sangue inocente que Joab derramou.",n:"O asilo do altar não protegia o assassino deliberado (Êxodo 21,14)."},
{v:32,t:"O Senhor fará recair o seu sangue sobre a sua cabeça, porque feriu dois homens mais justos e melhores do que ele e os matou à espada, sem que Davi, meu pai, o soubesse: Abner, filho de Ner, chefe do exército de Israel, e Amasa, filho de Jeter, chefe do exército de Judá."},
{v:33,t:"Que o sangue deles recaia sobre a cabeça de Joab e da sua descendência para sempre; mas que haja paz da parte do Senhor, para sempre, para Davi e a sua descendência, para a sua casa e o seu trono."},
{v:34,t:"Banaías, filho de Joiada, subiu, atacou-o e o matou; e ele foi sepultado em sua casa, no deserto."},
{v:35,t:"O rei pôs em seu lugar, à frente do exército, Banaías, filho de Joiada; e pôs o sacerdote Sadoc no lugar de Abiatar."},
{v:36,t:"Depois o rei mandou chamar Semei e lhe disse: Constrói para ti uma casa em Jerusalém e mora nela; não sairás de lá para parte alguma.",np:1},
{v:37,t:"No dia em que saíres e atravessares a torrente do Cedron, fica sabendo que morrerás; o teu sangue cairá sobre a tua cabeça."},
{v:38,t:"Semei respondeu ao rei: Está bem; o teu servo fará como disse o rei, meu senhor. E Semei morou em Jerusalém por muito tempo."},
{v:39,t:"Mas, três anos depois, dois escravos de Semei fugiram para junto de Aquis, filho de Maaca, rei de Gat; e disseram a Semei: Os teus escravos estão em Gat."},
{v:40,t:"Semei levantou-se, selou o seu jumento e foi a Gat, a Aquis, procurar os seus escravos; e voltou de Gat com eles."},
{v:41,t:"Informaram Salomão de que Semei tinha ido de Jerusalém a Gat e voltado."},
{v:42,t:"O rei mandou chamar Semei e lhe disse: Não te fiz jurar pelo Senhor e não te avisei: No dia em que saíres para qualquer parte, fica sabendo que morrerás? E tu me respondeste: Está bem; ouvi."},
{v:43,t:"Por que, então, não guardaste o juramento do Senhor e a ordem que eu te dei?"},
{v:44,t:"E o rei disse a Semei: Tu sabes, no teu coração, todo o mal que fizeste a Davi, meu pai; o Senhor faz recair a tua maldade sobre a tua cabeça."},
{v:45,t:"Mas o rei Salomão será bendito, e o trono de Davi será firme diante do Senhor para sempre."},
{v:46,t:"O rei deu a ordem a Banaías, filho de Joiada, que saiu e o feriu, e ele morreu. Assim o reino ficou firme nas mãos de Salomão.",n:"O narrador não esconde que o reino de Salomão se firmou com sangue. O rei da paz começa pela espada."}
];
