// =====================================================================
// I Reis — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["1reis"][1] = [
{s:"A velhice de Davi"},
{v:1,t:"O rei Davi estava velho, de idade muito avançada; cobriam-no de roupas, mas ele não se aquecia.",n:"Os livros dos Reis continuam a história de Samuel, da morte de Davi até o exílio da Babilônia. Na Bíblia hebraica formavam um só livro; a antiga Vulgata chamava-os Terceiro e Quarto dos Reis. Julgam cada rei pela sua fidelidade ao Senhor, segundo a lei do Deuteronômio, e ao único templo de Jerusalém."},
{v:2,t:"Os seus servos lhe disseram: Procure-se para o rei, nosso senhor, uma jovem virgem, que o assista e cuide dele; que durma nos teus braços, e o rei, nosso senhor, se aquecerá."},
{v:3,t:"Procuraram uma jovem bonita por todo o território de Israel; encontraram Abisag, a sunamita, e levaram-na ao rei."},
{v:4,t:"A jovem era muito bonita; cuidava do rei e o servia, mas o rei não a conheceu.",n:"O detalhe é importante para o capítulo seguinte: Abisag passa por concubina do rei, e pedi-la como esposa será reivindicar o trono (2,22)."},
{s:"A conspiração de Adonias"},
{v:5,t:"Adonias, filho de Hagit, encheu-se de pretensões, dizendo: Eu serei rei! Arranjou para si carros e cavaleiros, e cinquenta homens que corriam à sua frente.",np:1,n:"Adonias era o mais velho dos filhos vivos de Davi, depois da morte de Amnon e de Absalão; o direito de primogenitura parecia estar do seu lado. Imita Absalão (2 Samuel 15,1)."},
{v:6,t:"Seu pai nunca o tinha contrariado, dizendo: Por que fazes isso? Ele também era muito bonito, e tinha nascido depois de Absalão.",n:"Davi, pai fraco com os filhos, como com Amnon e Absalão."},
{v:7,t:"Entendeu-se com Joab, filho de Sárvia, e com o sacerdote Abiatar, que tomaram o partido de Adonias."},
{v:8,t:"Mas o sacerdote Sadoc, Banaías, filho de Joiada, o profeta Natã, Semei, Rei e os valentes de Davi não estavam com Adonias.",n:"Dois partidos na corte: de um lado, os velhos companheiros de Hebron, Joab e Abiatar; do outro, os homens de Jerusalém, Sadoc, Natã e a guarda de Banaías."},
{v:9,t:"Adonias sacrificou ovelhas, bois e bezerros cevados junto à pedra de Zoelet, que fica perto da fonte de Rogel, e convidou todos os seus irmãos, filhos do rei, e todos os homens de Judá que estavam a serviço do rei;"},
{v:10,t:"mas não convidou o profeta Natã, nem Banaías, nem os valentes, nem Salomão, seu irmão."},
{s:"Natã e Betsabeia"},
{v:11,t:"Então Natã disse a Betsabeia, mãe de Salomão: Não ouviste que Adonias, filho de Hagit, se fez rei, sem que Davi, nosso senhor, o saiba?",np:1},
{v:12,t:"Agora, pois, vem, deixa-me dar-te um conselho, para salvares a tua vida e a de teu filho Salomão.",n:"O novo rei costumava eliminar os rivais: se Adonias reinasse, Salomão e sua mãe corriam perigo de morte."},
{v:13,t:"Vai, entra na presença do rei Davi e dize-lhe: Ó rei, meu senhor, não juraste à tua serva: Teu filho Salomão reinará depois de mim e se sentará no meu trono? Por que, então, reina Adonias?",n:"Esse juramento não aparece em outro lugar. Natã e Betsabeia talvez se aproveitem da memória fraca do velho rei; mas a escolha de Salomão está de acordo com o amor de Deus por ele (2 Samuel 12,24-25)."},
{v:14,t:"E, enquanto ainda estiveres falando com o rei, eu entrarei depois de ti e confirmarei as tuas palavras."},
{v:15,t:"Betsabeia entrou no quarto do rei. O rei estava muito velho, e Abisag, a sunamita, o servia.",np:1},
{v:16,t:"Betsabeia inclinou-se e prostrou-se diante do rei, e o rei lhe perguntou: Que desejas?"},
{v:17,t:"Ela respondeu: Meu senhor, tu juraste à tua serva pelo Senhor teu Deus: Teu filho Salomão reinará depois de mim e se sentará no meu trono."},
{v:18,t:"E agora Adonias se fez rei, sem que tu, ó rei, meu senhor, o saibas."},
{v:19,t:"Sacrificou bois, bezerros cevados e grande quantidade de ovelhas, e convidou todos os filhos do rei, o sacerdote Abiatar e Joab, chefe do exército; mas não convidou Salomão, teu servo."},
{v:20,t:"E agora, ó rei, meu senhor, os olhos de todo o Israel estão voltados para ti, para que lhes anuncies quem se sentará no trono do rei, meu senhor, depois dele."},
{v:21,t:"Senão, quando o rei, meu senhor, repousar com seus pais, eu e meu filho Salomão seremos tratados como culpados."},
{v:22,t:"Ela ainda falava com o rei quando chegou o profeta Natã.",np:1},
{v:23,t:"Anunciaram ao rei: Está aqui o profeta Natã. Ele entrou na presença do rei e prostrou-se diante dele com o rosto em terra,"},
{v:24,t:"e disse: Ó rei, meu senhor, disseste então: Adonias reinará depois de mim e se sentará no meu trono?"},
{v:25,t:"Porque ele desceu hoje e sacrificou bois, bezerros cevados e grande quantidade de carneiros, e convidou todos os filhos do rei, os chefes do exército e o sacerdote Abiatar; e eles estão comendo e bebendo na sua presença e dizendo: Viva o rei Adonias!"},
{v:26,t:"Mas a mim, teu servo, ao sacerdote Sadoc, a Banaías, filho de Joiada, e a Salomão, teu servo, não convidou."},
{v:27,t:"Foi o rei, meu senhor, que ordenou isso, sem dizer aos teus servos quem se sentaria no trono do rei, meu senhor, depois dele?"},
{s:"Salomão ungido rei"},
{v:28,t:"O rei Davi respondeu: Chamai-me Betsabeia. Ela entrou na presença do rei e ficou de pé diante dele.",np:1},
{v:29,t:"E o rei jurou: Pela vida do Senhor, que me livrou de toda angústia,"},
{v:30,t:"assim como te jurei pelo Senhor, Deus de Israel, dizendo: Teu filho Salomão reinará depois de mim e se sentará no meu trono em meu lugar, assim farei hoje mesmo."},
{v:31,t:"Betsabeia inclinou-se com o rosto em terra, prostrou-se diante do rei e disse: Viva para sempre o rei Davi, meu senhor!"},
{v:32,t:"Depois o rei Davi disse: Chamai-me o sacerdote Sadoc, o profeta Natã e Banaías, filho de Joiada. Eles entraram na presença do rei,",np:1},
{v:33,t:"e o rei lhes disse: Tomai convosco os servos do vosso senhor, fazei montar meu filho Salomão na minha mula e levai-o a Gion.",n:"A mula do rei: montá-la era já tomar posse do trono. Gion é a fonte que abastecia Jerusalém, no vale do Cedron, não longe da fonte de Rogel, onde Adonias fazia festa."},
{v:34,t:"Ali o sacerdote Sadoc e o profeta Natã o ungirão rei sobre Israel; tocareis a trombeta e direis: Viva o rei Salomão!"},
{v:35,t:"Depois subireis atrás dele, e ele virá sentar-se no meu trono e reinará em meu lugar; porque é a ele que designo como chefe de Israel e de Judá."},
{v:36,t:"Banaías, filho de Joiada, respondeu ao rei: Amém! Assim o diga o Senhor, Deus do rei, meu senhor."},
{v:37,t:"Assim como o Senhor esteve com o rei, meu senhor, assim esteja com Salomão, e torne o seu trono ainda maior que o trono do rei Davi, meu senhor!"},
{v:38,t:"O sacerdote Sadoc, o profeta Natã, Banaías, filho de Joiada, os cereteus e os feleteus desceram, fizeram Salomão montar na mula do rei Davi e o levaram a Gion.",np:1},
{v:39,t:"O sacerdote Sadoc tomou da tenda o chifre de óleo e ungiu Salomão; tocaram a trombeta, e todo o povo disse: Viva o rei Salomão!",n:"A tenda onde estava a arca, em Jerusalém (2 Samuel 6,17). A unção de Salomão é, desde então, cantada na liturgia da sagração dos reis cristãos."},
{v:40,t:"Todo o povo subiu atrás dele, tocando flautas e com grande alegria, e a terra estremecia com os seus gritos."},
{s:"O medo de Adonias"},
{v:41,t:"Adonias e todos os seus convidados ouviram o barulho, quando já tinham acabado de comer. Joab, ouvindo o som da trombeta, perguntou: Que significa este barulho da cidade em alvoroço?",np:1},
{v:42,t:"Ainda estava falando quando chegou Jônatas, filho do sacerdote Abiatar. Adonias lhe disse: Entra, porque és um homem de bem e trazes boas notícias."},
{v:43,t:"Jônatas respondeu a Adonias: Pelo contrário! O rei Davi, nosso senhor, fez rei Salomão;"},
{v:44,t:"enviou com ele o sacerdote Sadoc, o profeta Natã, Banaías, filho de Joiada, os cereteus e os feleteus, e eles o fizeram montar na mula do rei."},
{v:45,t:"O sacerdote Sadoc e o profeta Natã ungiram-no rei em Gion, e de lá subiram com alegria, e a cidade está em alvoroço: é esse o barulho que ouvistes."},
{v:46,t:"E Salomão já se sentou no trono real;"},
{v:47,t:"e os servos do rei vieram felicitar o rei Davi, nosso senhor, dizendo: Que Deus torne o nome de Salomão ainda mais célebre que o teu, e o seu trono ainda maior que o teu! E o rei prostrou-se no seu leito."},
{v:48,t:"E disse ainda: Bendito seja o Senhor, Deus de Israel, que hoje concedeu que alguém se sentasse no meu trono, e os meus olhos o veem!"},
{v:49,t:"Todos os convidados de Adonias, apavorados, levantaram-se e foram-se, cada um para o seu lado.",np:1},
{v:50,t:"Adonias, com medo de Salomão, levantou-se e foi agarrar-se às pontas do altar.",n:"As pontas do altar, em forma de chifres, davam direito de asilo a quem tivesse matado sem intenção (Êxodo 21,13-14)."},
{v:51,t:"Foram dizer a Salomão: Adonias tem medo do rei Salomão e está agarrado às pontas do altar, dizendo: Que o rei Salomão me jure hoje que não matará o seu servo à espada."},
{v:52,t:"Salomão disse: Se ele se portar como homem de bem, não cairá por terra um só cabelo da sua cabeça; mas, se for achado nele algum mal, morrerá."},
{v:53,t:"O rei Salomão mandou tirá-lo do altar, e ele veio prostrar-se diante do rei Salomão; e Salomão lhe disse: Vai para tua casa."}
];

window.TEXTOS_SEED["1reis"][2] = [
{s:"O testamento de Davi"},
{v:1,t:"Aproximando-se o dia da sua morte, Davi deu estas instruções a seu filho Salomão:"},
{v:2,t:"Eu vou pelo caminho de todos os mortais. Sê forte e porta-te como homem.",n:"O caminho de todos os mortais: a mesma expressão com que Josué se despede (Josué 23,14)."},
{v:3,t:"Guarda as ordens do Senhor teu Deus, andando nos seus caminhos e observando os seus estatutos, os seus mandamentos, os seus preceitos e os seus testemunhos, como está escrito na Lei de Moisés, para que prosperes em tudo o que fizeres e para onde quer que te voltes;",n:"A linguagem é a do Deuteronômio: é a medida pela qual o livro julgará todos os reis."},
{v:4,t:"para que o Senhor cumpra a palavra que disse a meu respeito: Se os teus filhos guardarem o seu caminho, andando diante de mim com fidelidade, de todo o coração e de toda a alma, não te faltará um descendente no trono de Israel."},
{v:5,t:"Tu sabes também o que me fez Joab, filho de Sárvia, o que fez aos dois chefes do exército de Israel, Abner, filho de Ner, e Amasa, filho de Jeter, a quem matou: derramou em tempo de paz sangue de guerra e manchou de sangue de guerra o cinturão que tinha à cintura e as sandálias que tinha nos pés.",np:1,n:"Davi pede a Salomão a justiça que ele mesmo não pôde fazer (2 Samuel 3,39). A lógica é também política: afastar do novo reino os homens perigosos."},
{v:6,t:"Faze, pois, segundo a tua sabedoria, e não deixes os seus cabelos brancos descerem em paz à morada dos mortos."},
{v:7,t:"Mas aos filhos de Berzelai, o galaadita, mostra a tua gratidão: que eles comam à tua mesa, porque me acolheram quando eu fugia de Absalão, teu irmão."},
{v:8,t:"Tens também junto de ti Semei, filho de Gera, benjaminita de Baurim, que me amaldiçoou com uma maldição terrível no dia em que eu ia para Maanaim; mas ele desceu ao meu encontro no Jordão, e eu lhe jurei pelo Senhor: Não te matarei à espada."},
{v:9,t:"Tu, porém, não o deixes impune; és um homem sábio e saberás o que fazer com ele: farás descer com sangue os seus cabelos brancos à morada dos mortos.",n:"Davi respeitou o juramento durante a sua vida, mas não o estende ao filho. A maldição de Semei pesava, segundo a mentalidade da época, sobre a dinastia."},
{s:"A morte de Davi"},
{v:10,t:"Davi repousou com seus pais e foi sepultado na Cidade de Davi.",np:1,n:"No dia de Pentecostes, Pedro lembrará que o túmulo de Davi ainda estava entre eles (Atos 2,29)."},
{v:11,t:"Davi reinou sobre Israel quarenta anos: sete anos em Hebron e trinta e três em Jerusalém."},
{v:12,t:"Salomão sentou-se no trono de Davi, seu pai, e o seu reino ficou muito firme."},
{s:"Salomão elimina os seus adversários"},
{v:13,t:"Adonias, filho de Hagit, foi ter com Betsabeia, mãe de Salomão. Ela lhe perguntou: Vens em paz? Ele respondeu: Em paz.",np:1},
{v:14,t:"E acrescentou: Tenho uma coisa a te dizer. Ela respondeu: Fala. E ele disse:"},
{v:15,t:"Tu sabes que o reino era meu, e que todo o Israel esperava que eu fosse rei; mas o reino passou para meu irmão, porque lhe foi dado pelo Senhor."},
{v:16,t:"Agora, pois, tenho um só pedido a te fazer; não me recuses. Ela lhe disse: Fala."},
{v:17,t:"Ele disse: Peço-te que digas ao rei Salomão — porque ele nada te recusará — que me dê por mulher Abisag, a sunamita."},
{v:18,t:"Betsabeia respondeu: Está bem; falarei ao rei a teu respeito."},
{v:19,t:"Betsabeia foi ter com o rei Salomão, para lhe falar a respeito de Adonias. O rei levantou-se para ir ao seu encontro, inclinou-se diante dela e sentou-se no seu trono; mandou pôr um trono para a mãe do rei, e ela se sentou à sua direita.",n:"A mãe do rei, a gebirá, tinha na corte uma dignidade própria: sentava-se à direita do filho e intercedia junto dele. A tradição cristã viu nesta cena uma imagem de Maria, mãe do Rei messiânico."},
{v:20,t:"Ela disse: Tenho um pequeno pedido a te fazer; não me recuses. O rei lhe disse: Pede, minha mãe, porque não te recusarei."},
{v:21,t:"Ela disse: Que Abisag, a sunamita, seja dada por mulher a teu irmão Adonias."},
{v:22,t:"O rei Salomão respondeu a sua mãe: Por que pedes Abisag, a sunamita, para Adonias? Pede para ele também o reino! Ele é meu irmão mais velho, e tem a seu favor o sacerdote Abiatar e Joab, filho de Sárvia.",n:"Tomar a mulher do harém do rei morto era reivindicar a sua sucessão (2 Samuel 16,21-22). Salomão entende o pedido como nova tentativa de golpe."},
{v:23,t:"E o rei Salomão jurou pelo Senhor: Que Deus me faça isto e mais aquilo, se não for à custa da própria vida que Adonias disse esta palavra!"},
{v:24,t:"E agora, pela vida do Senhor, que me firmou e me fez sentar no trono de Davi, meu pai, e que me fez uma casa, como tinha prometido: hoje mesmo Adonias morrerá."},
{v:25,t:"O rei Salomão deu a ordem a Banaías, filho de Joiada, que o feriu, e ele morreu."},
{v:26,t:"Ao sacerdote Abiatar o rei disse: Vai para Anatot, para as tuas terras. Mereces a morte, mas hoje não te farei morrer, porque levaste a arca do Senhor Deus diante de Davi, meu pai, e partilhaste todos os sofrimentos de meu pai.",np:1,n:"Anatot, perto de Jerusalém, será a terra do profeta Jeremias, de família sacerdotal, talvez descendente de Abiatar."},
{v:27,t:"Assim Salomão afastou Abiatar do sacerdócio do Senhor, cumprindo a palavra que o Senhor tinha dito contra a casa de Heli, em Silo.",n:"Cumpre-se a profecia de 1 Samuel 2,30-35: Abiatar é o último descendente de Heli no sacerdócio; o sacerdócio passa a Sadoc e aos seus filhos."},
{v:28,t:"A notícia chegou a Joab, que tinha tomado o partido de Adonias, embora não tivesse tomado o de Absalão. Joab fugiu para a tenda do Senhor e agarrou-se às pontas do altar.",np:1},
{v:29,t:"Informaram o rei Salomão de que Joab tinha fugido para a tenda do Senhor e estava junto do altar; e Salomão enviou Banaías, filho de Joiada, dizendo: Vai e mata-o!"},
{v:30,t:"Banaías foi à tenda do Senhor e lhe disse: Assim diz o rei: Sai daí! Ele respondeu: Não; morrerei aqui. Banaías levou a resposta ao rei, dizendo: Assim falou Joab, e assim me respondeu."},
{v:31,t:"O rei lhe disse: Faze como ele disse: mata-o e sepulta-o; assim tirarás de mim e da casa de meu pai o sangue inocente que Joab derramou.",n:"O asilo do altar não protegia o assassino deliberado (Êxodo 21,14)."},
{v:32,t:"O Senhor fará recair o seu sangue sobre a sua cabeça, porque feriu dois homens mais justos e melhores do que ele e os matou à espada, sem que Davi, meu pai, o soubesse: Abner, filho de Ner, chefe do exército de Israel, e Amasa, filho de Jeter, chefe do exército de Judá."},
{v:33,t:"Que o sangue deles recaia sobre a cabeça de Joab e da sua descendência para sempre; mas que haja paz da parte do Senhor, para sempre, para Davi e a sua descendência, para a sua casa e o seu trono."},
{v:34,t:"Banaías, filho de Joiada, subiu, atacou-o e o matou; e ele foi sepultado em sua casa, no deserto."},
{v:35,t:"O rei pôs em seu lugar, à frente do exército, Banaías, filho de Joiada; e pôs o sacerdote Sadoc no lugar de Abiatar."},
{v:36,t:"Depois o rei mandou chamar Semei e lhe disse: Constrói para ti uma casa em Jerusalém e mora nela; não sairás de lá para parte alguma.",np:1},
{v:37,t:"No dia em que saíres e atravessares a torrente do Cedron, fica sabendo que morrerás; o teu sangue cairá sobre a tua cabeça."},
{v:38,t:"Semei respondeu ao rei: Está bem; o teu servo fará como disse o rei, meu senhor. E Semei morou em Jerusalém por muito tempo."},
{v:39,t:"Mas, três anos depois, dois escravos de Semei fugiram para junto de Aquis, filho de Maaca, rei de Gat; e disseram a Semei: Os teus escravos estão em Gat."},
{v:40,t:"Semei levantou-se, selou o seu jumento e foi a Gat, a Aquis, procurar os seus escravos; e voltou de Gat com eles."},
{v:41,t:"Informaram Salomão de que Semei tinha ido de Jerusalém a Gat e voltado."},
{v:42,t:"O rei mandou chamar Semei e lhe disse: Não te fiz jurar pelo Senhor e não te avisei: No dia em que saíres para qualquer parte, fica sabendo que morrerás? E tu me respondeste: Está bem; ouvi."},
{v:43,t:"Por que, então, não guardaste o juramento do Senhor e a ordem que eu te dei?"},
{v:44,t:"E o rei disse a Semei: Tu sabes, no teu coração, todo o mal que fizeste a Davi, meu pai; o Senhor faz recair a tua maldade sobre a tua cabeça."},
{v:45,t:"Mas o rei Salomão será bendito, e o trono de Davi será firme diante do Senhor para sempre."},
{v:46,t:"O rei deu a ordem a Banaías, filho de Joiada, que saiu e o feriu, e ele morreu. Assim o reino ficou firme nas mãos de Salomão.",n:"O narrador não esconde que o reino de Salomão se firmou com sangue. O rei da paz começa pela espada."}
];

window.TEXTOS_SEED["1reis"][3] = [
{s:"O sonho de Salomão em Gabaon"},
{v:1,t:"Salomão aparentou-se com o faraó, rei do Egito: casou-se com a filha dele e trouxe-a para a Cidade de Davi, enquanto acabava de construir o seu palácio, a casa do Senhor e a muralha em volta de Jerusalém.",n:"O casamento com a filha do faraó mostra o prestígio do novo reino: o Egito não costumava dar as suas princesas a reis estrangeiros. Mas é também o primeiro passo das alianças que levarão Salomão à idolatria (11,1-8)."},
{v:2,t:"O povo, porém, oferecia sacrifícios nos lugares altos, porque até aquele tempo ainda não se tinha construído uma casa ao nome do Senhor.",n:"Os lugares altos eram santuários locais, muitas vezes herdados dos cananeus. O livro dos Reis, escrito depois da reforma que concentrou o culto em Jerusalém, desculpa aqui o seu uso: o templo ainda não existia."},
{v:3,t:"Salomão amava o Senhor, andando segundo os preceitos de Davi, seu pai; mas oferecia sacrifícios e queimava incenso nos lugares altos."},
{v:4,t:"O rei foi a Gabaon para oferecer ali sacrifícios, porque era aquele o lugar alto mais importante; Salomão ofereceu mil holocaustos sobre aquele altar.",np:1,n:"Segundo as Crônicas, estava em Gabaon a tenda da reunião, feita por Moisés no deserto (2 Crônicas 1,3)."},
{v:5,t:"Em Gabaon, o Senhor apareceu a Salomão num sonho, durante a noite, e Deus lhe disse: Pede o que queres que eu te dê."},
{v:6,t:"Salomão respondeu: Tu usaste de grande bondade com o teu servo Davi, meu pai, porque ele andou diante de ti com fidelidade, com justiça e com retidão de coração para contigo; e lhe guardaste esta grande bondade, dando-lhe um filho que se senta no seu trono, como hoje se vê."},
{v:7,t:"Agora, Senhor meu Deus, tu fizeste reinar o teu servo em lugar de Davi, meu pai; mas eu sou apenas um menino e não sei como conduzir-me.",n:"À letra, não sei sair nem entrar: não sei governar. Salomão devia ter uns vinte anos."},
{v:8,t:"O teu servo está no meio do povo que escolheste, um povo tão numeroso que não se pode contar nem calcular."},
{v:9,t:"Dá, pois, ao teu servo um coração que escute, para julgar o teu povo e discernir entre o bem e o mal; pois quem poderia julgar este teu povo tão grande?",n:"Um coração que escute: em hebraico lev shomea, um coração dócil, atento à palavra de Deus e à causa dos homens. A sabedoria bíblica começa por escutar."},
{v:10,t:"Agradou ao Senhor que Salomão lhe tivesse pedido isso,",np:1},
{v:11,t:"e Deus lhe disse: Porque pediste isto, e não pediste para ti vida longa, nem riquezas, nem a vida dos teus inimigos, mas pediste para ti discernimento para julgar com justiça,"},
{v:12,t:"eu faço o que pediste: dou-te um coração sábio e inteligente, como ninguém teve antes de ti, nem terá depois de ti."},
{v:13,t:"E também o que não pediste eu te dou: riquezas e glória, de modo que não haverá rei como tu durante toda a tua vida.",n:"Jesus dirá: buscai primeiro o reino de Deus e a sua justiça, e todas estas coisas vos serão dadas por acréscimo (Mateus 6,33)."},
{v:14,t:"E, se andares nos meus caminhos, guardando os meus preceitos e os meus mandamentos, como andou Davi, teu pai, prolongarei os teus dias."},
{v:15,t:"Salomão acordou, e viu que era um sonho. Voltou a Jerusalém, apresentou-se diante da arca da aliança do Senhor, ofereceu holocaustos e sacrifícios de comunhão e deu um banquete a todos os seus servos."},
{s:"O julgamento de Salomão"},
{v:16,t:"Então vieram ao rei duas prostitutas e apresentaram-se diante dele.",np:1,n:"O episódio mostra, logo depois do sonho, a sabedoria recebida: um juízo impossível resolvido pela compreensão do coração humano."},
{v:17,t:"Uma delas disse: Ah, meu senhor! Eu e esta mulher morávamos na mesma casa, e eu dei à luz perto dela, em casa."},
{v:18,t:"Três dias depois do meu parto, esta mulher também deu à luz; estávamos juntas, e não havia estranho algum conosco em casa: só nós duas."},
{v:19,t:"Uma noite, o filho desta mulher morreu, porque ela se deitou sobre ele enquanto dormia."},
{v:20,t:"Ela levantou-se no meio da noite e, enquanto a tua serva dormia, tirou o meu filho do meu lado e o pôs no seu colo, e pôs no meu colo o seu filho morto."},
{v:21,t:"Quando me levantei de manhã para amamentar o meu filho, ele estava morto; mas, olhando-o bem à luz do dia, vi que não era o filho que eu tinha dado à luz."},
{v:22,t:"A outra mulher respondeu: Não é verdade! O meu filho é o vivo, e o teu é o morto. E a primeira dizia: Mentira! O teu filho é o morto, e o meu é o vivo. E assim discutiam diante do rei."},
{v:23,t:"Então o rei disse: Esta diz: O meu filho é o vivo, e o teu é o morto; e aquela diz: Não! O teu filho é o morto, e o meu é o vivo.",np:1},
{v:24,t:"E o rei ordenou: Trazei-me uma espada! Trouxeram uma espada diante do rei,"},
{v:25,t:"e o rei disse: Cortai em duas partes o menino vivo, e dai metade a uma e metade à outra."},
{v:26,t:"Então a mulher de quem era o filho vivo, porque as suas entranhas se comoveram pelo filho, disse ao rei: Ah, meu senhor! Dai-lhe o menino vivo; não o mateis! Mas a outra dizia: Não seja nem meu nem teu: cortai-o!"},
{v:27,t:"Então o rei tomou a palavra e disse: Dai à primeira o menino vivo; não o mateis: ela é a mãe dele."},
{v:28,t:"Todo o Israel soube da sentença que o rei tinha dado, e temeram o rei, porque viram que havia nele uma sabedoria divina para fazer justiça."}
];

window.TEXTOS_SEED["1reis"][4] = [
{s:"Os oficiais de Salomão"},
{v:1,t:"O rei Salomão reinava sobre todo o Israel.",n:"A lista dos oficiais mostra a organização de um verdadeiro Estado, à maneira do Egito: o reino de Davi tornou-se uma monarquia administrativa."},
{v:2,t:"Estes eram os seus altos funcionários: Azarias, filho de Sadoc, era o sacerdote;"},
{v:3,t:"Elioref e Aías, filhos de Sisa, eram secretários; Josafá, filho de Ailud, era o arauto;"},
{v:4,t:"Banaías, filho de Joiada, comandava o exército; Sadoc e Abiatar eram sacerdotes;",n:"A menção de Abiatar, exilado em 2,26-27, vem talvez de uma lista mais antiga."},
{v:5,t:"Azarias, filho de Natã, era o chefe dos intendentes; Zabud, filho de Natã, sacerdote, era o amigo do rei;"},
{v:6,t:"Aisar era o mordomo do palácio; e Adoniram, filho de Abda, era o encarregado dos trabalhos forçados."},
{s:"Os doze intendentes"},
{v:7,t:"Salomão tinha doze intendentes sobre todo o Israel, que abasteciam o rei e a sua casa; cada um se encarregava do abastecimento durante um mês do ano.",np:1,n:"Os distritos não coincidem com os territórios das tribos: Salomão reorganiza o país segundo as necessidades do Estado. Judá, a tribo do rei, parece isento, o que alimentará o ressentimento do Norte."},
{v:8,t:"Estes são os seus nomes: Ben-Hur, na montanha de Efraim;"},
{v:9,t:"Ben-Decar, em Macés, em Salebim, em Bet-Sames, em Elon e em Bet-Hanã;"},
{v:10,t:"Ben-Hesed, em Arubot: pertenciam-lhe Soco e toda a terra de Éfer;"},
{v:11,t:"Ben-Abinadab, que tinha toda a região de Dor; era casado com Tafat, filha de Salomão;"},
{v:12,t:"Baana, filho de Ailud, governava Tanac e Meguido e toda a região de Bet-San, que fica junto de Sartã, abaixo de Jezrael, desde Bet-San até Abel-Meula e até além de Jecmaam;"},
{v:13,t:"Ben-Gaber, em Ramot de Galaad: tinha as aldeias de Jair, filho de Manassés, em Galaad, e governava também toda a região de Argob, em Basã: sessenta cidades grandes, com muralhas e ferrolhos de bronze;"},
{v:14,t:"Ainadab, filho de Ado, em Maanaim;"},
{v:15,t:"Aquimaás, em Neftali; também ele se casara com uma filha de Salomão, Basemat;"},
{v:16,t:"Baana, filho de Cusai, em Aser e em Balot;"},
{v:17,t:"Josafá, filho de Farué, em Issacar;"},
{v:18,t:"Semei, filho de Ela, em Benjamim;"},
{v:19,t:"Gaber, filho de Uri, na terra de Galaad, a terra de Seon, rei dos amorreus, e de Og, rei de Basã; e havia um único intendente na terra.",n:"Um único intendente na terra: talvez a terra de Judá, que teria um regime à parte."},
{v:20,t:"Judá e Israel eram inumeráveis como a areia do mar; comiam, bebiam e viviam contentes.",np:1,n:"Cumpre-se a promessa feita a Abraão: uma descendência numerosa como a areia do mar (Gênesis 22,17)."}
];

window.TEXTOS_SEED["1reis"][5] = [
{s:"A prosperidade do reino"},
{v:1,t:"Salomão dominava todos os reinos, desde o Rio até a terra dos filisteus e até a fronteira do Egito; eles lhe pagavam tributo e lhe foram sujeitos durante toda a sua vida.",n:"O Rio é o Eufrates. É o território prometido a Abraão (Gênesis 15,18), talvez idealizado pelo narrador."},
{v:2,t:"As provisões de Salomão, para cada dia, eram de trinta coros de flor de farinha e sessenta coros de farinha,",n:"Um coro valia cerca de duzentos e vinte litros: a corte de Salomão era uma pequena cidade."},
{v:3,t:"dez bois cevados, vinte bois de pasto e cem ovelhas, além de veados, gazelas, antílopes e aves cevadas."},
{v:4,t:"Porque ele dominava toda a região a oeste do Rio, desde Tafsa até Gaza, e todos os reis daquelas regiões; e tinha paz com todos os povos ao redor.",n:"À letra, além do Rio: visto da Mesopotâmia, o lado ocidental do Eufrates. A expressão trai a época do exílio, em que o livro foi concluído. Tafsa, junto ao Eufrates, era o grande vau do rio."},
{v:5,t:"Judá e Israel viveram em segurança, cada um debaixo da sua videira e da sua figueira, desde Dã até Bersabeia, durante toda a vida de Salomão.",n:"Cada um debaixo da sua videira e da sua figueira: a imagem proverbial da paz, que os profetas retomarão para os tempos messiânicos (Miqueias 4,4; Zacarias 3,10)."},
{v:6,t:"Salomão tinha quatro mil estábulos para os cavalos dos seus carros, e doze mil cavaleiros.",n:"Quatro mil: assim a Nova Vulgata, com 2 Crônicas 9,25; o hebraico diz quarenta mil."},
{v:7,t:"Os intendentes já mencionados abasteciam, cada um no seu mês, com todo o cuidado, a mesa do rei Salomão e de todos os que a ela se sentavam."},
{v:8,t:"Traziam também a cevada e a palha para os cavalos e as parelhas, ao lugar onde cada um estava designado."},
{s:"A sabedoria de Salomão"},
{v:9,t:"Deus deu a Salomão sabedoria e muita inteligência, e um espírito vasto como a areia da praia do mar.",np:1},
{v:10,t:"A sabedoria de Salomão superava a de todos os filhos do Oriente e a de todo o Egito.",n:"A sabedoria do Oriente e do Egito era famosa: coleções de provérbios e instruções circulavam nas cortes. O livro dos Provérbios incorpora algumas delas."},
{v:11,t:"Era mais sábio que todos os homens, mais sábio que Etã, o ezraíta, e que Hemã, Calcol e Darda, filhos de Maol; e a sua fama espalhou-se por todas as nações vizinhas.",n:"Etã e Hemã aparecem nos títulos dos Salmos 88 e 89. Eram sábios famosos daquele tempo."},
{v:12,t:"Pronunciou três mil provérbios, e os seus cânticos foram mil e cinco.",n:"A tradição atribuiu a Salomão os Provérbios, o Eclesiastes, o Cântico dos Cânticos e, mais tarde, a Sabedoria; e dois Salmos (72 e 127)."},
{v:13,t:"Falou das árvores, desde o cedro do Líbano até o hissopo que brota na parede; falou também dos quadrúpedes, das aves, dos répteis e dos peixes."},
{v:14,t:"De todos os povos vinham ouvir a sabedoria de Salomão, da parte de todos os reis da terra que tinham ouvido falar da sua sabedoria."},
{s:"O acordo com Hiram"},
{v:15,t:"Hiram, rei de Tiro, enviou os seus servos a Salomão, quando soube que ele tinha sido ungido rei no lugar de seu pai, porque Hiram tinha sido sempre amigo de Davi.",np:1},
{v:16,t:"E Salomão mandou dizer a Hiram:"},
{v:17,t:"Tu sabes que Davi, meu pai, não pôde construir uma casa ao nome do Senhor seu Deus, por causa das guerras que o cercavam, até que o Senhor pusesse os inimigos debaixo dos seus pés.",n:"As Crônicas darão outra razão: Davi derramou muito sangue (1 Crônicas 22,8)."},
{v:18,t:"Mas agora o Senhor meu Deus me deu descanso por todos os lados: não há adversário nem desgraça."},
{v:19,t:"Por isso penso construir um templo ao nome do Senhor meu Deus, como o Senhor disse a Davi, meu pai: Teu filho, que eu porei no teu trono em teu lugar, é ele que construirá uma casa ao meu nome."},
{v:20,t:"Manda, pois, que cortem para mim cedros do Líbano; os meus servos estarão com os teus servos, e eu te darei pelo trabalho dos teus servos o salário que fixares; porque bem sabes que não há entre nós ninguém que saiba cortar madeira como os sidônios."},
{v:21,t:"Quando Hiram ouviu as palavras de Salomão, alegrou-se muito e disse: Bendito seja hoje o Senhor, que deu a Davi um filho sábio para governar este povo tão numeroso!",np:1},
{v:22,t:"E Hiram mandou dizer a Salomão: Recebi a tua mensagem. Farei tudo o que desejas quanto à madeira de cedro e de cipreste."},
{v:23,t:"Os meus servos a descerão do Líbano até o mar; eu a farei levar por mar em jangadas até o lugar que me indicares, e ali a desmancharei, e tu a receberás. Tu, por tua vez, fornecerás o que desejo: víveres para a minha casa."},
{v:24,t:"Hiram fornecia a Salomão madeira de cedro e de cipreste, tanto quanto ele queria;"},
{v:25,t:"e Salomão dava a Hiram, todos os anos, vinte mil coros de trigo para o sustento da sua casa, e vinte coros de azeite puríssimo."},
{v:26,t:"O Senhor deu sabedoria a Salomão, como lhe tinha prometido; e houve paz entre Hiram e Salomão, e os dois fizeram aliança."},
{s:"Os trabalhos forçados"},
{v:27,t:"O rei Salomão recrutou trabalhadores forçados em todo o Israel: a leva foi de trinta mil homens.",np:1,n:"A corveia, o trabalho forçado ao serviço do rei, era o que Samuel tinha anunciado (1 Samuel 8,16). Pesará sobre as tribos do Norte e será a causa da revolta contra o filho de Salomão (12,4)."},
{v:28,t:"Mandava-os ao Líbano, dez mil por mês, em turnos: passavam um mês no Líbano e dois meses em casa. Adoniram era o encarregado da leva."},
{v:29,t:"Salomão tinha também setenta mil carregadores e oitenta mil cortadores de pedra na montanha,"},
{v:30,t:"sem contar os chefes que dirigiam as obras, três mil e trezentos, que davam ordens ao povo que trabalhava."},
{v:31,t:"O rei ordenou que se extraíssem pedras grandes, pedras de valor, pedras talhadas para os alicerces do templo."},
{v:32,t:"Os pedreiros de Salomão, os de Hiram e os homens de Biblos talharam a madeira e as pedras, e prepararam o material para a construção do templo.",n:"Biblos, cidade fenícia ao norte de Sidônia, era famosa pelos seus artesãos."}
];

window.TEXTOS_SEED["1reis"][6] = [
{s:"A construção do templo"},
{v:1,t:"No ano quatrocentos e oitenta depois da saída dos filhos de Israel da terra do Egito, no quarto ano do reinado de Salomão sobre Israel, no mês de Ziv, que é o segundo mês, ele começou a construir a casa do Senhor.",n:"Quatrocentos e oitenta anos: doze gerações de quarenta anos, número simbólico que faz do templo o centro da história de Israel desde o Êxodo. O mês de Ziv corresponde a abril e maio."},
{v:2,t:"A casa que o rei Salomão construiu para o Senhor tinha sessenta côvados de comprimento, vinte de largura e trinta de altura.",n:"Cerca de trinta metros de comprimento, dez de largura e quinze de altura: um edifício modesto em tamanho, mas de grande riqueza. O templo não era lugar de reunião do povo, que ficava nos átrios, mas a morada de Deus."},
{v:3,t:"O vestíbulo diante do templo tinha vinte côvados de comprimento, igual à largura do templo, e dez côvados de profundidade diante do templo."},
{v:4,t:"Fez no templo janelas com molduras e grades."},
{v:5,t:"Construiu, encostado à parede do templo, um anexo ao redor, contra as paredes do templo e do Debir, e fez câmaras laterais em toda a volta.",n:"O Debir era a sala do fundo, o Santo dos Santos, onde ficaria a arca. O nome quer dizer talvez a parte de trás."},
{v:6,t:"O andar de baixo tinha cinco côvados de largura; o do meio, seis; e o terceiro, sete; porque ele fez reentrâncias na parede do templo, por fora, em toda a volta, para que as vigas não penetrassem nas paredes do templo."},
{v:7,t:"A casa foi construída com pedras já preparadas na pedreira; e não se ouviu na casa, enquanto era construída, nem martelo, nem machado, nem instrumento algum de ferro.",n:"O silêncio do canteiro exprime o respeito pelo lugar santo; o ferro, instrumento de guerra, não devia tocar as pedras do altar (Êxodo 20,25)."},
{v:8,t:"A entrada do andar de baixo ficava do lado direito da casa; por uma escada em caracol subia-se ao andar do meio, e do andar do meio ao terceiro."},
{v:9,t:"Assim ele construiu a casa e a terminou; e cobriu-a com um teto de vigas e tábuas de cedro."},
{v:10,t:"Construiu o anexo em volta de toda a casa, com cinco côvados de altura, e ligou-o à casa com vigas de cedro."},
{s:"A promessa do Senhor"},
{v:11,t:"A palavra do Senhor foi dirigida a Salomão nestes termos:",np:1},
{v:12,t:"Quanto a esta casa que constróis: se andares nos meus preceitos, se praticares as minhas normas e guardares todos os meus mandamentos, andando neles, cumprirei a teu respeito a palavra que eu disse a Davi, teu pai;",n:"No meio da descrição, a palavra de Deus lembra que o templo não garante nada por si mesmo: o que conta é a fidelidade. Jeremias o repetirá (Jeremias 7,4)."},
{v:13,t:"e habitarei no meio dos filhos de Israel, e não abandonarei o meu povo Israel."},
{s:"O revestimento interior e o Debir"},
{v:14,t:"Salomão construiu a casa e a terminou.",np:1},
{v:15,t:"Revestiu as paredes da casa, por dentro, com tábuas de cedro: desde o chão da casa até as vigas do teto revestiu-as de madeira por dentro; e cobriu o chão da casa com tábuas de cipreste."},
{v:16,t:"Revestiu com tábuas de cedro, desde o chão até o alto, um espaço de vinte côvados no fundo da casa, e fez dele, por dentro, o Debir, isto é, o Santo dos Santos."},
{v:17,t:"O templo propriamente dito, diante do Debir, tinha quarenta côvados."},
{v:18,t:"O cedro no interior da casa tinha esculpidos coloquíntidas e flores abertas. Tudo era revestido de cedro, e não se via pedra nenhuma na parede.",n:"As coloquíntidas eram frutos silvestres em forma de pequenas abóboras, motivo decorativo comum na arte do Oriente."},
{v:19,t:"Salomão preparou o Debir no meio da casa, na parte interior, para ali colocar a arca da aliança do Senhor."},
{v:20,t:"O Debir tinha vinte côvados de comprimento, vinte de largura e vinte de altura, e ele o revestiu de ouro puríssimo; e fez um altar de cedro diante do Debir.",n:"Um cubo perfeito, como a Jerusalém celeste do Apocalipse (Apocalipse 21,16). O altar de cedro, revestido de ouro, era o altar do incenso."},
{v:21,t:"Salomão revestiu de ouro puríssimo o interior da casa, e estendeu correntes de ouro diante do Debir."},
{v:22,t:"Não havia nada no templo que não fosse revestido de ouro; e revestiu também de ouro todo o altar que estava diante do Debir."},
{s:"Os querubins e as portas"},
{v:23,t:"Fez no Debir dois querubins de madeira de oliveira, com dez côvados de altura.",np:1,n:"Os querubins, seres alados com corpo de animal e rosto humano, guardavam os tronos e os santuários no Oriente antigo. Sobre as suas asas estendidas repousava, invisível, o trono do Senhor."},
{v:24,t:"Uma asa do querubim tinha cinco côvados, e a outra asa do querubim tinha também cinco côvados: dez côvados da ponta de uma asa à ponta da outra."},
{v:25,t:"O segundo querubim também tinha dez côvados: os dois querubins tinham a mesma medida e a mesma forma."},
{v:26,t:"A altura de um querubim era de dez côvados, e a do segundo querubim também."},
{v:27,t:"Colocou os querubins no meio da sala interior. Os querubins estendiam as asas, de modo que uma asa de um tocava uma parede, e uma asa do outro tocava a outra parede; e as outras duas asas tocavam-se uma na outra no meio da sala."},
{v:28,t:"E revestiu de ouro os querubins."},
{v:29,t:"Em todas as paredes da casa, ao redor, esculpiu figuras em relevo: querubins, palmeiras e flores abertas, na sala interior e na exterior.",n:"Querubins, palmeiras e flores: o templo evoca o jardim do Éden, guardado pelos querubins (Gênesis 3,24)."},
{v:30,t:"Revestiu também de ouro o chão da casa, na sala interior e na exterior."},
{v:31,t:"Para a entrada do Debir fez portas de madeira de oliveira, com umbrais de cinco molduras."},
{v:32,t:"Nas duas portas de madeira de oliveira esculpiu querubins, palmeiras e flores abertas, e revestiu-as de ouro, estendendo o ouro sobre os querubins, as palmeiras e tudo o mais."},
{v:33,t:"Do mesmo modo fez, para a entrada do templo, umbrais de madeira de oliveira, com quatro molduras,"},
{v:34,t:"e duas portas de madeira de cipreste; cada porta tinha duas folhas que giravam."},
{v:35,t:"Esculpiu nelas querubins, palmeiras e flores abertas, e revestiu tudo de lâminas de ouro."},
{v:36,t:"Construiu o átrio interior com três fileiras de pedras lavradas e uma fileira de vigas de cedro.",n:"A mesma técnica, alternando pedra e madeira, foi encontrada pelos arqueólogos em construções da época em Israel."},
{v:37,t:"No quarto ano foram lançados os alicerces da casa do Senhor, no mês de Ziv;",np:1},
{v:38,t:"e no décimo primeiro ano, no mês de Bul, que é o oitavo mês, a casa ficou terminada em todas as suas partes e com todo o seu mobiliário. Levou sete anos para construí-la.",n:"O mês de Bul corresponde a outubro e novembro."}
];

window.TEXTOS_SEED["1reis"][7] = [
{s:"O palácio de Salomão"},
{v:1,t:"Salomão construiu o seu palácio em treze anos, até acabá-lo por completo.",n:"Treze anos para o palácio, sete para o templo: o narrador deixa o leitor tirar a conclusão."},
{v:2,t:"Construiu também a Casa da Floresta do Líbano, com cem côvados de comprimento, cinquenta de largura e trinta de altura, sobre quatro fileiras de colunas de cedro, com vigas de cedro sobre as colunas.",n:"A Casa da Floresta do Líbano, assim chamada por causa das suas colunas de cedro, servia de arsenal e de sala de recepção (10,17)."},
{v:3,t:"Era coberta de cedro por cima das vigas que se apoiavam nas colunas: quarenta e cinco colunas, quinze em cada fileira."},
{v:4,t:"Havia três fileiras de janelas, janela diante de janela, três vezes."},
{v:5,t:"Todas as portas e umbrais tinham molduras quadradas."},
{v:6,t:"Fez também o pórtico das colunas, com cinquenta côvados de comprimento e trinta de largura; e diante dele, outro pórtico, com colunas e um alpendre."},
{v:7,t:"Fez o pórtico do trono, onde ele julgava, o pórtico do julgamento, e revestiu-o de cedro do chão ao teto."},
{v:8,t:"O palácio onde ele morava ficava em outro átrio, por trás do pórtico, e era da mesma construção. Fez também, para a filha do faraó, com quem Salomão se casara, uma casa semelhante a esse pórtico."},
{v:9,t:"Tudo era de pedras de valor, talhadas sob medida e serradas por dentro e por fora, desde os alicerces até o alto das paredes, e por fora até o grande átrio."},
{v:10,t:"Os alicerces eram de pedras de valor, pedras grandes, de dez e de oito côvados;"},
{v:11,t:"e por cima, pedras de valor talhadas sob medida, e madeira de cedro."},
{v:12,t:"O grande átrio tinha, em toda a volta, três fileiras de pedras lavradas e uma fileira de vigas de cedro, como o átrio interior da casa do Senhor e o vestíbulo da casa."},
{s:"Hiram, o artífice do bronze"},
{v:13,t:"O rei Salomão mandou buscar Hiram, de Tiro.",np:1},
{v:14,t:"Era filho de uma viúva da tribo de Neftali, e o pai era de Tiro; trabalhava o bronze, e era cheio de sabedoria, de inteligência e de habilidade para fazer toda obra de bronze. Ele veio ter com o rei Salomão e fez todas as suas obras.",n:"Não é o rei Hiram, mas um artesão do mesmo nome. Como Beseleel, o artífice do santuário do deserto, é cheio de sabedoria (Êxodo 31,3)."},
{v:15,t:"Moldou as duas colunas de bronze: cada coluna tinha dezoito côvados de altura, e um fio de doze côvados media a sua circunferência; a espessura era de quatro dedos, e era oca por dentro; assim também a outra coluna.",n:"A espessura e o interior oco vêm da versão grega, que a Nova Vulgata segue."},
{v:16,t:"Fez também dois capitéis de bronze fundido, para pôr no alto das colunas: um capitel tinha cinco côvados de altura, e o outro capitel também cinco côvados de altura;"},
{v:17,t:"e redes em forma de trança, franjas em forma de correntes entrelaçadas com arte, para os capitéis que estavam no alto das colunas: sete para um capitel e sete para o outro."},
{v:18,t:"Fez também romãs, em duas fileiras, ao redor de cada rede, para cobrir os capitéis que estavam no alto das colunas; e fez o mesmo para o segundo capitel."},
{v:19,t:"Os capitéis que estavam no alto das colunas, no vestíbulo, tinham a forma de lírio, de quatro côvados."},
{v:20,t:"E havia ainda capitéis no alto das duas colunas, por cima, junto à parte arredondada que ficava sobre a rede. Havia duzentas romãs, em duas fileiras, ao redor de cada capitel."},
{v:21,t:"Ergueu as colunas no vestíbulo do templo: erguendo a coluna da direita, deu-lhe o nome de Jaquin; e erguendo a coluna da esquerda, deu-lhe o nome de Booz.",n:"Jaquin quer dizer ele firma; Booz, nele está a força. Os nomes formavam talvez uma frase de bênção sobre a dinastia: que o Senhor firme o trono com força."},
{v:22,t:"No alto das colunas pôs uma obra em forma de lírio. Assim ficou terminada a obra das colunas."},
{s:"O mar de bronze"},
{v:23,t:"Fez também o mar de metal fundido: tinha dez côvados de uma borda à outra, e era redondo; tinha cinco côvados de altura, e um cordão de trinta côvados media a sua circunferência.",np:1,n:"O mar era um enorme reservatório de água para as abluções dos sacerdotes (2 Crônicas 4,6). O nome evoca também o oceano primordial, dominado pelo Criador."},
{v:24,t:"Por baixo da borda, ao redor, havia coloquíntidas em relevo, em duas fileiras, fundidas numa só peça com o mar."},
{v:25,t:"Assentava sobre doze bois: três voltados para o norte, três para o oeste, três para o sul e três para o leste; o mar estava por cima deles, e as suas ancas ficavam todas para dentro.",n:"Os doze bois lembram as doze tribos, em volta dos quatro pontos cardeais."},
{v:26,t:"A sua espessura era de um palmo, e a borda era como a borda de um cálice, como a flor do lírio aberta. Levava dois mil batos.",n:"Mais de quarenta mil litros."},
{s:"As bases e as bacias"},
{v:27,t:"Fez também dez bases de bronze: cada base tinha quatro côvados de comprimento, quatro de largura e três de altura.",np:1,n:"As bases eram carrinhos de bronze com rodas, que levavam bacias de água para o serviço do altar. A descrição, muito técnica, é às vezes obscura."},
{v:28,t:"As bases eram feitas assim: tinham painéis, e os painéis ficavam entre as travessas."},
{v:29,t:"Nos painéis entre as travessas havia leões, bois e querubins, e também sobre as travessas; por cima e por baixo dos leões e dos bois havia grinaldas em relevo, obra martelada."},
{v:30,t:"Cada base tinha quatro rodas de bronze, com eixos de bronze; e os quatro pés tinham suportes fundidos por baixo da bacia, com grinaldas de cada lado."},
{v:31,t:"A boca da base era redonda, obra de base, de um côvado e meio; também na sua boca havia esculturas; mas os seus painéis eram quadrados, não redondos."},
{v:32,t:"As quatro rodas ficavam por baixo dos painéis, e os eixos das rodas estavam presos à base; cada roda tinha um côvado e meio de altura."},
{v:33,t:"As rodas eram como as rodas de um carro: os eixos, os aros, os raios e os cubos, tudo era de metal fundido."},
{v:34,t:"Os quatro suportes nos quatro cantos de cada base faziam uma só peça com a base."},
{v:35,t:"No alto da base havia um aro de meio côvado de altura; e no alto da base os seus suportes e os seus painéis faziam uma só peça com ela."},
{v:36,t:"Nas superfícies dos suportes e dos painéis, gravou querubins, leões e palmeiras, conforme o espaço de cada um, e grinaldas ao redor."},
{v:37,t:"Assim fez as dez bases: todas tinham a mesma fundição, a mesma medida e a mesma forma."},
{v:38,t:"Fez também dez bacias de bronze: cada bacia levava quarenta batos e media quatro côvados; e pôs uma bacia sobre cada uma das dez bases."},
{v:39,t:"Colocou cinco bases do lado direito da casa e cinco do lado esquerdo; e pôs o mar do lado direito da casa, a sudeste."},
{s:"Os utensílios do templo"},
{v:40,t:"Hiram fez também as panelas, as pás e as bacias de aspersão. Assim Hiram terminou toda a obra que fazia para o rei Salomão na casa do Senhor:",np:1},
{v:41,t:"as duas colunas, os dois capitéis arredondados no alto das colunas, as duas redes para cobrir os dois capitéis arredondados no alto das colunas;"},
{v:42,t:"as quatrocentas romãs para as duas redes, duas fileiras de romãs em cada rede, para cobrir os dois capitéis arredondados no alto das colunas;"},
{v:43,t:"as dez bases e as dez bacias sobre as bases;"},
{v:44,t:"o mar, único, e os doze bois debaixo do mar;"},
{v:45,t:"as panelas, as pás e as bacias de aspersão. Todos esses objetos que Hiram fez para o rei Salomão, para a casa do Senhor, eram de bronze polido."},
{v:46,t:"O rei os fundiu na planície do Jordão, em moldes de argila, entre Sucot e Sartã.",n:"O vale do Jordão, rico em argila, prestava-se à fundição de grandes peças."},
{v:47,t:"Salomão colocou todos esses objetos no seu lugar; e, por serem tantos, não se calculou o peso do bronze."},
{v:48,t:"Salomão fez também todos os objetos da casa do Senhor: o altar de ouro e a mesa de ouro sobre a qual se colocavam os pães da proposição;",np:1},
{v:49,t:"os candelabros de ouro puro, cinco à direita e cinco à esquerda, diante do Debir, com as flores, as lâmpadas e as tenazes de ouro;",n:"No santuário do deserto havia um só candelabro de sete braços (Êxodo 25,31-40); o templo de Salomão tem dez."},
{v:50,t:"as taças, as facas, as bacias de aspersão, as colheres e os incensórios de ouro puríssimo; e as dobradiças das portas da sala interior, o Santo dos Santos, e das portas do templo, de ouro."},
{v:51,t:"Assim ficou terminada toda a obra que o rei Salomão fez para a casa do Senhor. E Salomão trouxe as coisas que Davi, seu pai, tinha consagrado: a prata, o ouro e os objetos, e os depositou nos tesouros da casa do Senhor."}
];

window.TEXTOS_SEED["1reis"][8] = [
{s:"A arca levada ao templo"},
{v:1,t:"Então Salomão reuniu junto de si, em Jerusalém, os anciãos de Israel — todos os chefes das tribos, os chefes das famílias dos filhos de Israel —, para trazer da Cidade de Davi, isto é, de Sião, a arca da aliança do Senhor.",n:"A arca estava na tenda armada por Davi, na colina de Sião (2 Samuel 6,17); o templo ficava mais ao norte, na colina mais alta."},
{v:2,t:"Todos os homens de Israel reuniram-se junto do rei Salomão no mês de Etanim, na festa, que é o sétimo mês.",n:"O mês de Etanim, setembro e outubro, era o da festa das Tendas, a grande festa da colheita. O templo, terminado no oitavo mês (6,38), foi dedicado quase um ano depois."},
{v:3,t:"Vieram todos os anciãos de Israel, e os sacerdotes levaram a arca;"},
{v:4,t:"levaram a arca do Senhor, a tenda da reunião e todos os objetos sagrados que havia na tenda: os sacerdotes e os levitas os levavam."},
{v:5,t:"O rei Salomão e toda a assembleia de Israel, reunida junto dele, sacrificavam diante da arca ovelhas e bois em quantidade tal que não se podia contar nem calcular."},
{v:6,t:"Os sacerdotes introduziram a arca da aliança do Senhor no seu lugar, no Debir do templo, no Santo dos Santos, debaixo das asas dos querubins.",np:1},
{v:7,t:"Pois os querubins estendiam as asas sobre o lugar da arca, e cobriam por cima a arca e os seus varais."},
{v:8,t:"Os varais eram tão compridos que as suas pontas se viam do Santo, diante do Debir, mas não se viam de fora; e estão lá até o dia de hoje.",n:"Até o dia de hoje: a frase foi escrita antes da destruição do templo pelos babilônios, em 587 antes de Cristo. A arca desapareceu nessa catástrofe."},
{v:9,t:"Na arca não havia outra coisa senão as duas tábuas de pedra que Moisés ali tinha posto no Horeb, quando o Senhor fez aliança com os filhos de Israel, ao saírem da terra do Egito."},
{v:10,t:"Quando os sacerdotes saíram do santuário, a nuvem encheu a casa do Senhor,",np:1},
{v:11,t:"e os sacerdotes não puderam ficar ali para fazer o seu serviço, por causa da nuvem, porque a glória do Senhor enchia a casa do Senhor.",n:"Como no deserto, quando a nuvem cobriu a tenda da reunião (Êxodo 40,34-35): o Deus do Sinai toma posse da sua casa."},
{v:12,l:["Então Salomão disse:","O Senhor disse que habitaria na nuvem escura."],n:"Pequeno poema de dedicação, de que a versão grega conserva uma forma mais longa, atribuída ao livro do Cântico. Deus habita na obscuridade: está presente, mas não se deixa ver."},
{v:13,l:["Eu te construí uma casa para morada,","um lugar firme para o teu trono para sempre."]},
{s:"O discurso de Salomão ao povo"},
{v:14,t:"Depois o rei voltou-se e abençoou toda a assembleia de Israel, enquanto toda a assembleia de Israel estava de pé.",np:1},
{v:15,t:"E disse: Bendito seja o Senhor, Deus de Israel, que falou com a sua boca a Davi, meu pai, e com a sua mão cumpriu o que dissera:"},
{v:16,t:"Desde o dia em que tirei do Egito o meu povo Israel, não escolhi cidade alguma, entre todas as tribos de Israel, para nela se construir uma casa onde estivesse o meu nome; mas escolhi Davi, para que estivesse à frente do meu povo Israel."},
{v:17,t:"Davi, meu pai, desejou construir uma casa ao nome do Senhor, Deus de Israel;"},
{v:18,t:"mas o Senhor disse a Davi, meu pai: Pensaste no teu coração em construir uma casa ao meu nome, e fizeste bem em pensar nisso;"},
{v:19,t:"mas não serás tu que construirás a casa, e sim o teu filho, que sairá das tuas entranhas: ele construirá a casa ao meu nome."},
{v:20,t:"O Senhor cumpriu a palavra que tinha dito: eu sucedi a Davi, meu pai, e sentei-me no trono de Israel, como o Senhor tinha dito, e construí a casa ao nome do Senhor, Deus de Israel."},
{v:21,t:"E ali preparei um lugar para a arca, onde está a aliança que o Senhor fez com os nossos pais, quando os tirou da terra do Egito."},
{s:"A oração de Salomão"},
{v:22,t:"Salomão pôs-se diante do altar do Senhor, em presença de toda a assembleia de Israel, estendeu as mãos para o céu",np:1,n:"A grande oração da dedicação, na linguagem do Deuteronômio, foi talvez desenvolvida no tempo do exílio: pensa num povo que perdeu a terra e que só pode orar voltado para o templo distante (versículos 46-51)."},
{v:23,t:"e disse: Senhor, Deus de Israel, não há Deus como tu, nem lá em cima no céu, nem cá embaixo na terra; tu guardas a aliança e a misericórdia para com os teus servos que andam diante de ti de todo o coração."},
{v:24,t:"Cumpriste para com o teu servo Davi, meu pai, o que lhe tinhas dito: o que prometeste com a tua boca, cumpriste com a tua mão, como hoje se vê."},
{v:25,t:"Agora, pois, Senhor, Deus de Israel, guarda para o teu servo Davi, meu pai, o que lhe prometeste, dizendo: Não te faltará diante de mim um descendente que se sente no trono de Israel, contanto que os teus filhos vigiem o seu caminho, andando diante de mim como tu andaste."},
{v:26,t:"Agora, pois, Deus de Israel, cumpra-se a palavra que disseste ao teu servo Davi, meu pai."},
{v:27,t:"Mas será que Deus habitará verdadeiramente na terra? Se os céus e os céus dos céus não te podem conter, quanto menos esta casa que construí!",n:"O ponto mais alto da oração: o templo não encerra Deus. É o lugar onde o seu nome é invocado e de onde a oração sobe até ele. Estêvão citará esta verdade diante do Sinédrio (Atos 7,48-49)."},
{v:28,t:"Mas volta-te para a oração e para a súplica do teu servo, Senhor meu Deus; ouve o clamor e a oração que o teu servo hoje te dirige,"},
{v:29,t:"para que os teus olhos estejam abertos noite e dia sobre esta casa, sobre o lugar do qual disseste: Ali estará o meu nome; para que ouças a oração que o teu servo fizer neste lugar."},
{v:30,t:"Ouve a súplica do teu servo e do teu povo Israel, quando orarem neste lugar; ouve do lugar da tua morada, no céu; ouve e perdoa."},
{v:31,t:"Se alguém pecar contra o seu próximo, e lhe for imposto um juramento que o obrigue, e ele vier jurar diante do teu altar, nesta casa,",np:1},
{v:32,t:"ouve do céu e age; julga os teus servos, condenando o culpado e fazendo recair sobre a sua cabeça o seu procedimento, e justificando o inocente, dando-lhe segundo a sua justiça."},
{v:33,t:"Se o teu povo Israel for derrotado pelos inimigos, por ter pecado contra ti, e depois se converter a ti, louvar o teu nome, orar e suplicar a ti nesta casa,",np:1},
{v:34,t:"ouve do céu, perdoa o pecado do teu povo Israel e faze-os voltar à terra que deste aos seus pais."},
{v:35,t:"Se o céu se fechar e não houver chuva, porque pecaram contra ti, e eles orarem neste lugar, louvarem o teu nome e se converterem do seu pecado, por causa da aflição que lhes enviaste,",np:1},
{v:36,t:"ouve do céu e perdoa o pecado dos teus servos e do teu povo Israel, ensinando-lhes o bom caminho por onde devem andar; e manda a chuva sobre a tua terra, que deste ao teu povo como herança."},
{v:37,t:"Se houver na terra fome ou peste, ferrugem ou mangra, gafanhotos ou larvas; se o inimigo o oprimir, sitiando as suas cidades; qualquer praga, qualquer doença,",np:1},
{v:38,t:"toda oração, toda súplica que fizer qualquer homem do teu povo Israel, reconhecendo cada um a chaga do seu coração e estendendo as mãos para esta casa,",n:"A chaga do coração: a consciência do próprio pecado, ou a própria dor. A oração parte do coração ferido."},
{v:39,t:"ouve do céu, do lugar da tua morada, perdoa e age: dá a cada um segundo todos os seus caminhos, tu que conheces o seu coração, porque só tu conheces o coração de todos os filhos dos homens,"},
{v:40,t:"para que te temam durante todos os dias que viverem sobre a terra que deste aos nossos pais."},
{v:41,t:"Também o estrangeiro, que não é do teu povo Israel, quando vier de uma terra distante por causa do teu nome",np:1,n:"A oração abre-se aos estrangeiros: o templo de Israel será casa de oração para todos os povos, como dirá Isaías (Isaías 56,7) e Jesus lembrará ao purificar o templo (Marcos 11,17)."},
{v:42,t:"— porque ouvirão falar do teu grande nome, da tua mão forte e do teu braço estendido —, quando vier orar nesta casa,"},
{v:43,t:"ouve do céu, do lugar da tua morada, e faze tudo o que o estrangeiro te pedir, para que todos os povos da terra conheçam o teu nome e te temam, como o teu povo Israel, e saibam que o teu nome é invocado sobre esta casa que construí."},
{v:44,t:"Se o teu povo sair à guerra contra os seus inimigos, pelo caminho por onde os enviares, e orarem a ti voltados para a cidade que escolheste e para a casa que construí ao teu nome,",np:1},
{v:45,t:"ouve do céu a sua oração e a sua súplica e faze-lhes justiça."},
{v:46,t:"Se pecarem contra ti — pois não há homem que não peque — e tu, irritado, os entregares aos seus inimigos, e estes os levarem cativos para a terra do inimigo, longe ou perto;",np:1},
{v:47,t:"se, na terra para onde foram levados cativos, eles caírem em si e se converterem, e te suplicarem na terra do seu cativeiro, dizendo: Pecamos, agimos mal, fomos ímpios;",n:"É a confissão que os exilados farão na Babilônia (Daniel 9,5; Salmo 106,6)."},
{v:48,t:"se voltarem a ti de todo o coração e de toda a alma, na terra dos seus inimigos que os levaram cativos, e orarem a ti voltados para a terra que deste aos seus pais, para a cidade que escolheste e para a casa que construí ao teu nome,",n:"Voltados para Jerusalém: é o costume que Daniel guardará na Babilônia, orando três vezes ao dia com as janelas abertas na direção de Jerusalém (Daniel 6,11)."},
{v:49,t:"ouve do céu, do lugar firme do teu trono, a sua oração e a sua súplica, e faze-lhes justiça;"},
{v:50,t:"perdoa ao teu povo, que pecou contra ti, e todas as faltas que cometeram contra ti, e faze com que encontrem compaixão junto dos que os levaram cativos, para que estes tenham piedade deles"},
{v:51,t:"— porque são o teu povo e a tua herança, que tiraste do Egito, do meio da fornalha de ferro —,"},
{v:52,t:"para que os teus olhos estejam abertos à súplica do teu servo e à súplica do teu povo Israel, e os ouças sempre que te invocarem."},
{v:53,t:"Porque tu os separaste de todos os povos da terra para serem a tua herança, como disseste por meio de Moisés, teu servo, quando tiraste os nossos pais do Egito, Senhor Deus."},
{s:"A bênção do povo"},
{v:54,t:"Quando Salomão acabou de dirigir ao Senhor toda esta oração e esta súplica, levantou-se de diante do altar do Senhor, onde estava ajoelhado, com as mãos estendidas para o céu.",np:1},
{v:55,t:"De pé, abençoou em alta voz toda a assembleia de Israel, dizendo:"},
{v:56,t:"Bendito seja o Senhor, que deu descanso ao seu povo Israel, conforme tudo o que tinha prometido! Não falhou uma só palavra de todas as boas promessas que fez por meio de Moisés, seu servo.",n:"O descanso prometido no Deuteronômio (Deuteronômio 12,9-10) chega com o templo: a história começada no Êxodo encontra aqui o seu termo."},
{v:57,t:"Que o Senhor nosso Deus esteja conosco, como esteve com os nossos pais; que não nos abandone nem nos rejeite,"},
{v:58,t:"mas incline para si os nossos corações, para que andemos em todos os seus caminhos e guardemos os mandamentos, os estatutos e as normas que prescreveu aos nossos pais."},
{v:59,t:"Que estas palavras da minha súplica diante do Senhor estejam presentes junto do Senhor nosso Deus dia e noite, para que ele faça justiça ao seu servo e ao seu povo Israel, dia após dia,"},
{v:60,t:"a fim de que todos os povos da terra saibam que o Senhor é Deus, e que não há outro."},
{v:61,t:"Que o vosso coração seja íntegro para com o Senhor nosso Deus, para andardes nos seus estatutos e guardardes os seus mandamentos, como hoje."},
{s:"A dedicação do templo"},
{v:62,t:"O rei, e todo o Israel com ele, ofereceram sacrifícios diante do Senhor.",np:1},
{v:63,t:"Salomão ofereceu, como sacrifícios de comunhão ao Senhor, vinte e dois mil bois e cento e vinte mil ovelhas. Assim o rei e todos os filhos de Israel dedicaram a casa do Senhor.",n:"Números enormes, que exprimem a grandeza da festa. A carne dos sacrifícios de comunhão era comida pelos fiéis: a dedicação foi um imenso banquete."},
{v:64,t:"Naquele dia o rei consagrou o meio do átrio que ficava diante da casa do Senhor; porque ali ofereceu os holocaustos, as oblações e a gordura dos sacrifícios de comunhão, uma vez que o altar de bronze que estava diante do Senhor era pequeno demais para conter os holocaustos, as oblações e a gordura dos sacrifícios de comunhão."},
{v:65,t:"Naquele tempo Salomão celebrou a festa, e com ele todo o Israel, uma grande assembleia, vinda desde a entrada de Emat até a torrente do Egito, diante do Senhor nosso Deus, durante sete dias.",n:"De Emat, ao norte, até a torrente do Egito, ao sul: todo o território do reino, na sua maior extensão."},
{v:66,t:"No oitavo dia despediu o povo; e eles abençoaram o rei e voltaram para as suas tendas, alegres e de coração contente por todo o bem que o Senhor tinha feito a Davi, seu servo, e a Israel, seu povo."}
];

window.TEXTOS_SEED["1reis"][9] = [
{s:"O Senhor aparece de novo a Salomão"},
{v:1,t:"Quando Salomão acabou de construir a casa do Senhor, o palácio real e tudo o que desejara fazer,"},
{v:2,t:"o Senhor apareceu-lhe pela segunda vez, como lhe tinha aparecido em Gabaon."},
{v:3,t:"E o Senhor lhe disse: Ouvi a oração e a súplica que me dirigiste. Consagrei esta casa que construíste, para nela pôr o meu nome para sempre; e os meus olhos e o meu coração estarão ali todos os dias."},
{v:4,t:"Quanto a ti, se andares diante de mim como andou Davi, teu pai, com integridade de coração e retidão, fazendo tudo o que te ordenei e guardando os meus estatutos e as minhas normas,"},
{v:5,t:"firmarei para sempre o trono do teu reino sobre Israel, como prometi a Davi, teu pai, dizendo: Não faltará à tua descendência um homem no trono de Israel."},
{v:6,t:"Mas, se vós e os vossos filhos vos afastardes de mim, não seguindo os meus mandamentos e os meus estatutos que vos propus, e fordes servir a outros deuses e adorá-los,",np:1,n:"A ameaça fala já do exílio e da destruição do templo: o livro foi terminado depois dessas catástrofes, e explica-as como castigo da infidelidade."},
{v:7,t:"eliminarei Israel da face da terra que lhes dei, e rejeitarei de diante de mim o templo que consagrei ao meu nome; e Israel será objeto de provérbio e de zombaria entre todos os povos."},
{v:8,t:"E esta casa ficará em ruínas; todo aquele que passar junto dela ficará espantado, assobiará e dirá: Por que fez o Senhor isto a esta terra e a esta casa?"},
{v:9,t:"E responderão: Porque abandonaram o Senhor seu Deus, que tirou os seus pais da terra do Egito, e seguiram outros deuses, adoraram-nos e os serviram; por isso o Senhor fez vir sobre eles todo este mal."},
{s:"As obras de Salomão"},
{v:10,t:"Ao fim de vinte anos, durante os quais Salomão construiu as duas casas, a casa do Senhor e o palácio real",np:1},
{v:11,t:"— Hiram, rei de Tiro, tinha fornecido a Salomão madeira de cedro e de cipreste e ouro, tanto quanto ele quis —, o rei Salomão deu a Hiram vinte cidades na terra da Galileia."},
{v:12,t:"Hiram saiu de Tiro para ver as cidades que Salomão lhe tinha dado, e elas não lhe agradaram."},
{v:13,t:"E disse: Que cidades são estas que me deste, meu irmão? E chamou-as terra de Cabul, nome que conservam até hoje.",n:"Cabul soava talvez como nada, ou terra sem valor. Salomão, endividado com Hiram, pagava em território."},
{v:14,t:"Hiram tinha enviado ao rei cento e vinte talentos de ouro."},
{v:15,t:"Esta é a razão dos trabalhos forçados que o rei Salomão impôs para construir a casa do Senhor, o seu palácio, o Milo, a muralha de Jerusalém, Hasor, Meguido e Gazer.",np:1,n:"Os arqueólogos encontraram em Hasor, Meguido e Gazer portas fortificadas quase idênticas, atribuídas a esta época."},
{v:16,t:"O faraó, rei do Egito, tinha subido e tomado Gazer; incendiou-a, matou os cananeus que habitavam a cidade e deu-a como dote à sua filha, mulher de Salomão."},
{v:17,t:"Salomão reconstruiu Gazer, Bet-Horon de baixo,"},
{v:18,t:"Baalat e Tamar, no deserto,",n:"Tamar, no sul de Judá. As Crônicas leem Tadmor, a futura Palmira, no deserto da Síria (2 Crônicas 8,4)."},
{v:19,t:"todas as cidades de armazéns que lhe pertenciam, as cidades dos carros e as cidades dos cavalos, e tudo o que Salomão quis construir em Jerusalém, no Líbano e em todo o território do seu domínio."},
{v:20,t:"Todo o povo que restava dos amorreus, dos heteus, dos ferezeus, dos heveus e dos jebuseus, que não eram dos filhos de Israel,"},
{v:21,t:"os seus descendentes, que tinham ficado depois deles na terra, e que os filhos de Israel não tinham podido exterminar, Salomão sujeitou-os ao trabalho forçado, até hoje."},
{v:22,t:"Mas dos filhos de Israel Salomão não fez escravo nenhum: eram os seus soldados, os seus servidores, os seus oficiais, os seus combatentes e os comandantes dos seus carros e da sua cavalaria.",n:"Esta afirmação suaviza a de 5,27, onde se diz que Salomão impôs a corveia a todo o Israel: talvez duas formas de trabalho, uma permanente para os cananeus e outra temporária para os israelitas."},
{v:23,t:"Os chefes dos intendentes que dirigiam as obras de Salomão eram quinhentos e cinquenta; tinham autoridade sobre o povo que trabalhava nas obras."},
{v:24,t:"A filha do faraó subiu da Cidade de Davi para a casa que Salomão lhe tinha construído; então ele construiu o Milo.",np:1},
{v:25,t:"Três vezes por ano Salomão oferecia holocaustos e sacrifícios de comunhão sobre o altar que tinha construído ao Senhor, e queimava incenso diante do Senhor. Assim ficou terminado o templo.",n:"Três vezes por ano: nas três festas de peregrinação, a Páscoa, as Semanas e as Tendas (Êxodo 23,14-17)."},
{s:"A frota de Salomão"},
{v:26,t:"O rei Salomão construiu também uma frota em Asion-Gaber, perto de Elat, na costa do mar Vermelho, na terra de Edom.",np:1},
{v:27,t:"Hiram mandou naquela frota os seus servos, marinheiros que conheciam o mar, com os servos de Salomão."},
{v:28,t:"Eles foram a Ofir, tomaram de lá quatrocentos e vinte talentos de ouro e os trouxeram ao rei Salomão.",n:"Ofir, a terra do ouro, ficava talvez no sul da Arábia ou na costa oriental da África."}
];

window.TEXTOS_SEED["1reis"][10] = [
{s:"A rainha de Sabá"},
{v:1,t:"A rainha de Sabá ouviu falar da fama de Salomão, por causa do nome do Senhor, e veio pô-lo à prova com enigmas.",n:"Sabá ficava no sul da Arábia, no atual Iêmen, e enriquecia com o comércio do incenso. Jesus lembrará a rainha do Sul, que veio dos confins da terra para ouvir a sabedoria de Salomão (Mateus 12,42)."},
{v:2,t:"Chegou a Jerusalém com um séquito muito numeroso, com camelos carregados de perfumes, de ouro em grande quantidade e de pedras preciosas; foi ter com Salomão e falou-lhe de tudo o que tinha no coração."},
{v:3,t:"Salomão respondeu a todas as suas perguntas: não houve pergunta tão oculta que o rei não soubesse responder."},
{v:4,t:"Quando a rainha de Sabá viu toda a sabedoria de Salomão, o palácio que ele tinha construído,",np:1},
{v:5,t:"as iguarias da sua mesa, os aposentos dos seus oficiais, o serviço dos seus criados e as suas librés, os seus copeiros e os holocaustos que ele oferecia na casa do Senhor, ficou sem fôlego,"},
{v:6,t:"e disse ao rei: Era verdade o que ouvi na minha terra acerca de ti e da tua sabedoria!"},
{v:7,t:"Eu não acreditava no que me contavam, até que vim e vi com os meus próprios olhos: e não me tinham contado nem a metade! A tua sabedoria e a tua prosperidade superam a fama que ouvi."},
{v:8,t:"Felizes os teus homens, felizes estes teus servos, que estão sempre diante de ti e ouvem a tua sabedoria!"},
{v:9,t:"Bendito seja o Senhor teu Deus, que se agradou de ti e te pôs no trono de Israel! Porque o Senhor ama Israel para sempre, constituiu-te rei, para praticares o direito e a justiça.",n:"A estrangeira reconhece o Deus de Israel e o sentido da realeza: o rei existe para o direito e a justiça."},
{v:10,t:"Ela deu ao rei cento e vinte talentos de ouro, grande quantidade de perfumes e pedras preciosas. Nunca mais chegaram tantos perfumes como os que a rainha de Sabá deu ao rei Salomão."},
{v:11,t:"Também a frota de Hiram, que trazia ouro de Ofir, trouxe de Ofir grande quantidade de madeira de sândalo e pedras preciosas.",n:"Madeira de sândalo: identificação provável da madeira que o hebraico chama almuguim."},
{v:12,t:"Com a madeira de sândalo o rei fez balaustradas para a casa do Senhor e para o palácio real, e cítaras e harpas para os cantores. Nunca mais chegou nem se viu madeira de sândalo como aquela, até hoje."},
{v:13,t:"O rei Salomão deu à rainha de Sabá tudo o que ela desejou e pediu, além do que ele mesmo lhe ofereceu com generosidade real. Depois ela voltou para a sua terra com os seus servos."},
{s:"As riquezas de Salomão"},
{v:14,t:"O peso do ouro que chegava a Salomão cada ano era de seiscentos e sessenta e seis talentos de ouro,",np:1,n:"Mais de vinte toneladas. As riquezas de Salomão tornaram-se lendárias; mas o Deuteronômio mandava o rei não acumular ouro nem prata (Deuteronômio 17,17)."},
{v:15,t:"sem contar o que vinha dos tributos dos povos sujeitos, do comércio dos mercadores, de todos os reis da Arábia e dos governadores do país."},
{v:16,t:"O rei Salomão fez duzentos escudos grandes de ouro puro, empregando seiscentos siclos de ouro em cada escudo;"},
{v:17,t:"e trezentos escudos pequenos de ouro fino, empregando três minas de ouro em cada escudo; e o rei os pôs na Casa da Floresta do Líbano.",n:"Os escudos de ouro, que serviam só para as cerimônias, serão levados pelo faraó Sesac no tempo de Roboão (14,26)."},
{v:18,t:"O rei fez também um grande trono de marfim e revestiu-o de ouro fino."},
{v:19,t:"O trono tinha seis degraus; o espaldar era arredondado na parte de trás; havia braços de um lado e de outro do assento, e dois leões de pé junto dos braços;"},
{v:20,t:"e doze leões estavam de pé sobre os seis degraus, de um lado e de outro. Nada de semelhante se fez em reino algum."},
{v:21,t:"Todas as taças em que o rei Salomão bebia eram de ouro, e todos os utensílios da Casa da Floresta do Líbano eram de ouro puríssimo; não havia prata, que no tempo de Salomão não tinha valor algum,"},
{v:22,t:"porque o rei tinha no mar navios de Társis, com a frota de Hiram, e de três em três anos os navios de Társis voltavam trazendo ouro, prata, marfim, macacos e pavões.",n:"Navios de Társis: navios de alto-mar, capazes de ir até Társis, no extremo ocidente."},
{v:23,t:"Assim o rei Salomão superou todos os reis da terra em riqueza e em sabedoria.",np:1},
{v:24,t:"Toda a terra desejava ver o rosto de Salomão, para ouvir a sabedoria que Deus lhe tinha posto no coração."},
{v:25,t:"E cada um lhe trazia o seu presente, todos os anos: objetos de prata e de ouro, vestes, armas, perfumes, cavalos e mulas."},
{v:26,t:"Salomão reuniu carros e cavaleiros: tinha mil e quatrocentos carros e doze mil cavaleiros, que distribuiu pelas cidades dos carros e junto do rei, em Jerusalém.",np:1},
{v:27,t:"O rei fez que em Jerusalém a prata fosse tão comum como as pedras, e os cedros tão numerosos como os sicômoros que crescem na Sefelá."},
{v:28,t:"Os cavalos de Salomão vinham do Egito e de Cua; os mercadores do rei os compravam em Cua por um preço fixo.",n:"Cua é a Cilícia, no sudeste da atual Turquia, famosa pelos seus cavalos."},
{v:29,t:"Um carro trazido do Egito custava seiscentos siclos de prata, e um cavalo, cento e cinquenta; e da mesma forma, por meio deles, eram exportados para todos os reis dos heteus e da Síria.",n:"Salomão enriquece também como intermediário no comércio de cavalos e carros. O Deuteronômio proibia ao rei multiplicar os cavalos e fazer o povo voltar ao Egito para isso (Deuteronômio 17,16): a glória de Salomão já traz as sementes da sua queda."}
];

window.TEXTOS_SEED["1reis"][11] = [
{s:"As mulheres de Salomão"},
{v:1,t:"O rei Salomão amou muitas mulheres estrangeiras: além da filha do faraó, moabitas, amonitas, edomitas, sidônias e heteias,",n:"Os casamentos com princesas estrangeiras eram alianças políticas. Mas o narrador julga-os segundo a Lei, que os proibia por causa dos deuses que elas traziam (Deuteronômio 7,3-4; 17,17)."},
{v:2,t:"mulheres dos povos dos quais o Senhor tinha dito aos filhos de Israel: Não vos unireis a elas, nem elas a vós, porque certamente elas desviarão os vossos corações para os seus deuses. A esses povos Salomão se apegou com amor."},
{v:3,t:"Teve setecentas mulheres princesas e trezentas concubinas; e as suas mulheres desviaram o seu coração."},
{v:4,t:"Na velhice de Salomão, as suas mulheres desviaram o seu coração para outros deuses, e o seu coração já não era íntegro para com o Senhor seu Deus, como o coração de Davi, seu pai.",n:"O homem que pedira um coração que escuta (3,9) acaba com o coração dividido. O pecado de Salomão é o do homem que tudo recebeu e nada soube guardar."},
{v:5,t:"Salomão seguiu Astarte, a deusa dos sidônios, e Milcom, o ídolo abominável dos amonitas."},
{v:6,t:"Salomão fez o que é mau aos olhos do Senhor, e não seguiu plenamente o Senhor, como Davi, seu pai."},
{v:7,t:"Construiu então um lugar alto para Camos, o ídolo de Moab, no monte que fica defronte de Jerusalém, e para Milcom, o ídolo dos amonitas.",n:"O monte defronte de Jerusalém é o monte das Oliveiras. Esses santuários só serão destruídos três séculos depois, pelo rei Josias (2 Reis 23,13)."},
{v:8,t:"E fez o mesmo para todas as suas mulheres estrangeiras, que queimavam incenso e ofereciam sacrifícios aos seus deuses."},
{v:9,t:"O Senhor irritou-se contra Salomão, porque o seu coração se desviara do Senhor, Deus de Israel, que lhe tinha aparecido duas vezes",np:1},
{v:10,t:"e lhe tinha ordenado precisamente que não seguisse outros deuses; mas ele não guardou o que o Senhor lhe tinha ordenado."},
{v:11,t:"Então o Senhor disse a Salomão: Já que procedeste assim e não guardaste a minha aliança e os meus estatutos que te prescrevi, arrancarei de ti o reino e o darei a um dos teus servos."},
{v:12,t:"Mas não o farei durante a tua vida, por amor de Davi, teu pai; é da mão de teu filho que o arrancarei."},
{v:13,t:"E não lhe tirarei todo o reino: darei uma tribo a teu filho, por amor de Davi, meu servo, e de Jerusalém, que escolhi.",n:"Uma tribo: Judá, à qual se juntará Benjamim. A fidelidade de Deus à promessa feita a Davi é mais forte que a infidelidade de Salomão."},
{s:"Os adversários de Salomão"},
{v:14,t:"O Senhor suscitou um adversário contra Salomão: Adad, o edomita, que era da família real de Edom.",np:1,n:"Adversário, em hebraico satã. A paz do reino de Salomão (5,18: não há adversário) chega ao fim."},
{v:15,t:"Quando Davi derrotou Edom, e Joab, chefe do exército, subiu para sepultar os mortos, e matou todos os homens de Edom",n:"Episódio não contado em 2 Samuel 8,13-14."},
{v:16,t:"— Joab e todo o Israel ficaram lá seis meses, até exterminar todos os homens de Edom —,"},
{v:17,t:"Adad fugiu para o Egito com alguns edomitas, servos de seu pai; Adad era então um menino."},
{v:18,t:"Partiram de Madiã e chegaram a Farã; tomaram consigo homens de Farã e chegaram ao Egito, junto do faraó, rei do Egito, que lhe deu uma casa, lhe assegurou o sustento e lhe deu terras."},
{v:19,t:"Adad caiu tanto nas graças do faraó que este lhe deu por mulher a sua cunhada, irmã da rainha Táfnes."},
{v:20,t:"A irmã de Táfnes deu-lhe um filho, Genubat, que Táfnes criou no palácio do faraó; e Genubat viveu no palácio do faraó, entre os filhos do faraó."},
{v:21,t:"Quando Adad soube, no Egito, que Davi tinha adormecido com seus pais e que Joab, chefe do exército, tinha morrido, disse ao faraó: Deixa-me partir para a minha terra."},
{v:22,t:"O faraó lhe perguntou: Que te falta junto de mim, para quereres ir para a tua terra? Ele respondeu: Nada; mas deixa-me partir, peço-te."},
{v:23,t:"Deus suscitou contra Salomão outro adversário: Razon, filho de Eliada, que tinha fugido do seu senhor Adadezer, rei de Soba.",np:1},
{v:24,t:"Reuniu homens em torno de si e tornou-se chefe de um bando, quando Davi os massacrou; foram para Damasco, estabeleceram-se ali e reinaram em Damasco.",n:"O reino arameu de Damasco será, durante dois séculos, o grande inimigo de Israel."},
{v:25,t:"Foi adversário de Israel durante toda a vida de Salomão, além do mal que fazia Adad. Detestava Israel e reinou sobre a Síria."},
{s:"Jeroboão e o profeta Aías"},
{v:26,t:"Também Jeroboão, filho de Nabat, efraimita de Sareda, servo de Salomão, cuja mãe, viúva, se chamava Sarva, levantou a mão contra o rei.",np:1},
{v:27,t:"Eis o motivo da sua revolta contra o rei: Salomão construía o Milo e fechava a brecha da Cidade de Davi, seu pai."},
{v:28,t:"Jeroboão era um homem forte e valente; e Salomão, vendo que o jovem era trabalhador, tinha-o posto à frente de todos os trabalhos forçados da casa de José.",n:"A casa de José: as tribos de Efraim e Manassés. Encarregado da corveia da sua própria gente, Jeroboão conhecia bem o descontentamento do Norte."},
{v:29,t:"Naquele tempo, Jeroboão saiu de Jerusalém, e o profeta Aías, de Silo, encontrou-o no caminho; Aías estava vestido com um manto novo, e os dois estavam sozinhos no campo."},
{v:30,t:"Aías tomou o manto novo que vestia e rasgou-o em doze pedaços,",n:"Uma ação simbólica, como as dos profetas depois dele: o manto rasgado é o reino dividido. Lembra o manto de Samuel, rasgado por Saul (1 Samuel 15,27-28)."},
{v:31,t:"e disse a Jeroboão: Toma para ti dez pedaços, porque assim diz o Senhor, Deus de Israel: Vou arrancar o reino da mão de Salomão e te darei dez tribos."},
{v:32,t:"Mas ficará para ele uma tribo, por amor de Davi, meu servo, e de Jerusalém, a cidade que escolhi entre todas as tribos de Israel;"},
{v:33,t:"porque me abandonaram e adoraram Astarte, a deusa dos sidônios, Camos, o deus de Moab, e Milcom, o deus dos amonitas, e não andaram nos meus caminhos, praticando o que é reto aos meus olhos, os meus estatutos e as minhas normas, como Davi, seu pai."},
{v:34,t:"Mas não tirarei da sua mão todo o reino; eu o manterei como chefe durante toda a sua vida, por amor de Davi, meu servo, a quem escolhi, e que guardou os meus mandamentos e os meus estatutos."},
{v:35,t:"Tirarei o reino da mão de seu filho e te darei dez tribos;"},
{v:36,t:"e a seu filho darei uma tribo, para que Davi, meu servo, tenha sempre uma lâmpada diante de mim em Jerusalém, a cidade que escolhi para nela pôr o meu nome.",n:"A lâmpada de Davi: a dinastia que não se apaga, sinal da fidelidade de Deus (2 Samuel 21,17)."},
{v:37,t:"Quanto a ti, eu te tomarei, e reinarás sobre tudo o que desejares: serás rei de Israel."},
{v:38,t:"Se ouvires tudo o que eu te ordenar, se andares nos meus caminhos e fizeres o que é reto aos meus olhos, guardando os meus estatutos e os meus mandamentos, como fez Davi, meu servo, estarei contigo e te construirei uma casa estável, como a construí para Davi, e te darei Israel."},
{v:39,t:"E humilharei por isso a descendência de Davi, mas não para sempre.",n:"Não para sempre: uma pequena frase de esperança, que abre caminho à expectativa do Messias, filho de Davi."},
{v:40,t:"Salomão procurou matar Jeroboão; mas Jeroboão levantou-se e fugiu para o Egito, para junto de Sesac, rei do Egito, e ficou no Egito até a morte de Salomão.",n:"Sesac é o faraó Sheshonq I, que invadirá Judá no tempo de Roboão (14,25)."},
{s:"A morte de Salomão"},
{v:41,t:"O resto dos feitos de Salomão, tudo o que ele fez e a sua sabedoria, está escrito no livro dos Atos de Salomão.",np:1,n:"O autor dos Reis cita as suas fontes: crônicas da corte hoje perdidas."},
{v:42,t:"Salomão reinou em Jerusalém sobre todo o Israel quarenta anos."},
{v:43,t:"Salomão adormeceu com seus pais e foi sepultado na Cidade de Davi, seu pai; e seu filho Roboão reinou em seu lugar."}
];
