// =====================================================================
// I Samuel — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["1samuel"][1] = [
{s:"Ana, mãe de Samuel"},
{v:1,t:"Havia um homem de Ramataim-Sofim, da montanha de Efraim, chamado Elcana, filho de Jeroam, filho de Eliú, filho de Tou, filho de Suf, efraimita.",n:"Os livros de Samuel, que eram um só na Bíblia hebraica, contam a passagem de Israel do tempo dos juízes à monarquia: Samuel, o último juiz; Saul, o primeiro rei; Davi, o rei segundo o coração de Deus. A Vulgata antiga chamava-os Primeiro e Segundo dos Reis."},
{v:2,t:"Tinha duas mulheres: uma chamava-se Ana, e a outra, Fenena. Fenena tinha filhos, mas Ana não tinha."},
{v:3,t:"Todos os anos, esse homem subia da sua cidade para adorar e oferecer sacrifícios ao Senhor dos exércitos em Silo; ali estavam os dois filhos de Heli, Ofni e Fineias, sacerdotes do Senhor.",n:"Senhor dos exércitos, Yahweh Sabaot, aparece aqui pela primeira vez na Bíblia, ligado ao santuário de Silo e à arca. Os exércitos são os astros e os anjos, e também as tropas de Israel."},
{v:4,t:"No dia em que Elcana oferecia o sacrifício, dava porções a Fenena, sua mulher, e a todos os filhos e filhas dela;",np:1},
{v:5,t:"mas a Ana dava uma porção escolhida, porque amava Ana, embora o Senhor lhe tivesse fechado o ventre."},
{v:6,t:"A sua rival a afligia duramente, para irritá-la, porque o Senhor lhe tinha fechado o ventre."},
{v:7,t:"Assim acontecia todos os anos: sempre que subiam à casa do Senhor, a outra a irritava; e Ana chorava e não comia."},
{v:8,t:"Elcana, seu marido, disse-lhe: Ana, por que choras? Por que não comes? Por que está triste o teu coração? Não sou eu para ti melhor do que dez filhos?",n:"O amor de Elcana é sincero e um pouco desajeitado: não entende que um marido não substitui um filho."},
{v:9,t:"Depois que comeram e beberam em Silo, Ana levantou-se. O sacerdote Heli estava sentado na cadeira, junto à ombreira do templo do Senhor.",np:1},
{v:10,t:"Ela, com a alma amargurada, orou ao Senhor, chorando muito,"},
{v:11,t:"e fez este voto: Senhor dos exércitos, se olhares para a aflição da tua serva e te lembrares de mim, se não te esqueceres da tua serva e deres à tua serva um filho homem, eu o darei ao Senhor por todos os dias da sua vida, e a navalha não passará pela sua cabeça.",n:"Ana promete um nazireu, como a mãe de Sansão. O Magnificat de Maria ecoará esta oração: olhou para a humildade da sua serva."},
{v:12,t:"Enquanto ela prolongava a sua oração diante do Senhor, Heli observava-lhe a boca."},
{v:13,t:"Ana falava no seu coração; só os lábios se moviam, mas não se ouvia a voz. Heli pensou que ela estivesse embriagada,",n:"Rezava-se em voz alta. A oração silenciosa de Ana é a primeira da Bíblia, e o sacerdote não a compreende."},
{v:14,t:"e disse-lhe: Até quando estarás embriagada? Livra-te do teu vinho!"},
{v:15,t:"Ana respondeu: Não, meu senhor; sou uma mulher angustiada. Não bebi vinho nem bebida fermentada, mas derramava a minha alma diante do Senhor.",n:"Derramar a alma diante de Deus: a expressão dos salmos para a oração de quem sofre."},
{v:16,t:"Não tomes a tua serva por uma mulher perversa; foi pela grandeza da minha dor e da minha aflição que falei até agora."},
{v:17,t:"Heli respondeu: Vai em paz, e o Deus de Israel te conceda o que lhe pediste."},
{v:18,t:"Ela disse: Que a tua serva encontre graça aos teus olhos. E a mulher seguiu o seu caminho e comeu, e o seu rosto não era mais o mesmo."},
{v:19,t:"Levantaram-se cedo e prostraram-se diante do Senhor; depois voltaram para casa, em Ramá. Elcana uniu-se a Ana, sua mulher, e o Senhor lembrou-se dela."},
{v:20,t:"Passado algum tempo, Ana concebeu e deu à luz um filho, e pôs-lhe o nome de Samuel, porque disse: Pedi-o ao Senhor.",np:1,n:"A etimologia popular liga o nome Samuel ao verbo pedir, shaal, que atravessa todo o capítulo; o nome significa, antes, o seu nome é Deus."},
{v:21,t:"Elcana subiu com toda a sua família para oferecer ao Senhor o sacrifício anual e cumprir o seu voto.",np:1},
{v:22,t:"Mas Ana não subiu, porque disse ao marido: Não irei até que o menino seja desmamado; então o levarei, para que seja apresentado diante do Senhor e fique ali para sempre.",n:"O desmame dava-se então por volta dos três anos."},
{v:23,t:"Elcana, seu marido, respondeu-lhe: Faze o que te parecer bem; fica até que o desmames; somente o Senhor cumpra a sua palavra. A mulher ficou e amamentou o filho até desmamá-lo."},
{v:24,t:"Depois de desmamado, levou-o consigo, com um novilho de três anos, um efá de farinha e um odre de vinho, e levou-o à casa do Senhor, em Silo. O menino era ainda muito pequeno."},
{v:25,t:"Imolaram o novilho e apresentaram o menino a Heli."},
{v:26,t:"Ana disse: Com licença, meu senhor! Pela tua vida, meu senhor, eu sou aquela mulher que esteve aqui junto de ti, orando ao Senhor."},
{v:27,t:"Foi por este menino que orei, e o Senhor concedeu-me o que lhe pedi."},
{v:28,t:"Por isso também eu o cedo ao Senhor: por todos os dias da sua vida, ele será cedido ao Senhor. E prostraram-se ali diante do Senhor.",n:"Cedido, à letra pedido: o mesmo verbo do nome de Samuel. Ana devolve a Deus o que lhe pediu."}
];

window.TEXTOS_SEED["1samuel"][2] = [
{s:"O cântico de Ana"},
{v:1,l:["E Ana orou, dizendo:","O meu coração exulta no Senhor,","a minha força se eleva no meu Deus;","a minha boca se abre contra os meus inimigos,","porque me alegro na tua salvação."],n:"O cântico de Ana é o modelo do Magnificat de Maria, que retoma o seu movimento: Deus derruba os poderosos e exalta os humildes. A força, à letra o chifre, é a imagem do vigor do animal que ergue a cabeça."},
{v:2,l:["Não há santo como o Senhor;","não há outro além de ti,","não há rocha como o nosso Deus."]},
{v:3,l:["Não multipliqueis palavras soberbas,","nem saia arrogância da vossa boca,","porque o Senhor é um Deus que sabe tudo, e é ele quem pesa as ações."]},
{v:4,l:["O arco dos poderosos é quebrado,","e os fracos são cingidos de força."]},
{v:5,l:["Os fartos alugam-se por pão,","e os famintos já não passam fome;","a estéril deu à luz sete vezes,","e a mãe de muitos filhos definha."],n:"Sete é o número da plenitude. Ana terá cinco filhos: o cântico canta mais do que a sua história, canta o modo de agir de Deus."},
{v:6,l:["O Senhor dá a morte e dá a vida,","faz descer à morada dos mortos e faz subir de lá."],n:"Faz subir da morada dos mortos: uma das primeiras expressões da esperança de Israel diante da morte."},
{v:7,l:["O Senhor empobrece e enriquece,","humilha e exalta;"]},
{v:8,l:["levanta do pó o fraco","e do monturo ergue o pobre,","para fazê-lo sentar-se com os príncipes","e ocupar um trono de glória.","Porque ao Senhor pertencem as colunas da terra, e sobre elas assentou o mundo."]},
{v:9,l:["Ele guarda os passos dos seus fiéis,","mas os ímpios calam-se nas trevas;","porque não é pela força que o homem triunfa."]},
{v:10,l:["O Senhor quebra os seus adversários;","do céu troveja contra eles.","O Senhor julga os confins da terra,","dá força ao seu rei","e exalta o poder do seu ungido."],n:"Ungido, em hebraico mashiah, Messias; em grego, Christos. É a primeira vez que a Bíblia usa a palavra para o rei — e Israel ainda não tem rei. O cântico olha para Davi e, para além dele, para o Messias."},
{s:"Os filhos de Heli"},
{v:11,t:"Elcana voltou para Ramá, para sua casa; e o menino ficou a serviço do Senhor, diante do sacerdote Heli.",np:1},
{v:12,t:"Os filhos de Heli eram homens perversos; não conheciam o Senhor",n:"Perversos, à letra filhos de Belial, como os homens de Gabaá no livro dos Juízes."},
{v:13,t:"nem o dever dos sacerdotes para com o povo. Quando alguém oferecia um sacrifício, o servo do sacerdote vinha, enquanto a carne cozia, com um garfo de três dentes na mão,"},
{v:14,t:"e o metia no caldeirão, na panela, no tacho ou na marmita; e tudo o que o garfo tirava, o sacerdote tomava para si. Assim faziam com todos os israelitas que iam a Silo.",n:"A Lei fixava a parte do sacerdote nos sacrifícios; os filhos de Heli tomam o que querem."},
{v:15,t:"Além disso, antes que se queimasse a gordura, o servo do sacerdote vinha e dizia ao que oferecia o sacrifício: Dá carne para assar para o sacerdote; ele não aceitará de ti carne cozida, só crua.",n:"A gordura pertencia a Deus e devia ser queimada primeiro. Os filhos de Heli passam à frente de Deus."},
{v:16,t:"E, se o homem lhe dizia: Primeiro queime-se a gordura, como é costume, e depois toma o que quiseres, ele respondia: Não; dá agora, senão tomarei à força."},
{v:17,t:"O pecado daqueles jovens era muito grande diante do Senhor, porque desprezavam a oferta do Senhor."},
{v:18,t:"Samuel servia diante do Senhor; era um menino, vestido com um efod de linho.",np:1,n:"O efod de linho era uma veste sacerdotal simples. O menino que serve contrasta com os sacerdotes que se servem."},
{v:19,t:"Sua mãe fazia-lhe uma pequena túnica e levava-a todos os anos, quando subia com o marido para oferecer o sacrifício anual."},
{v:20,t:"Heli abençoava Elcana e a sua mulher, dizendo: O Senhor te dê descendência desta mulher, em troca daquele que foi cedido ao Senhor. E eles voltavam para casa."},
{v:21,t:"O Senhor visitou Ana, e ela concebeu e deu à luz três filhos e duas filhas. E o menino Samuel crescia junto do Senhor."},
{v:22,t:"Heli era muito velho e ouviu tudo o que os seus filhos faziam a todo o Israel, e como se deitavam com as mulheres que serviam à entrada da tenda do encontro.",np:1},
{v:23,t:"E disse-lhes: Por que fazeis tais coisas? Ouço todo o povo falar das vossas más ações."},
{v:24,t:"Não, meus filhos; não é boa a fama que ouço: levais o povo do Senhor a pecar."},
{v:25,l:["Se um homem peca contra outro homem,","Deus pode ser o árbitro;","mas, se um homem peca contra o Senhor,","quem intercederá por ele?","Mas eles não escutaram a voz de seu pai, porque o Senhor queria fazê-los morrer."],n:"Nota do tradutor: o Senhor queria fazê-los morrer é o modo hebraico de dizer que a obstinação deles já os condenava; a Bíblia atribui a Deus o desfecho que o pecado prepara. Não quer dizer que Deus os impedisse de se converter."},
{v:26,t:"Mas o menino Samuel ia crescendo e agradava tanto ao Senhor como aos homens.",n:"São Lucas dirá o mesmo de Jesus menino: crescia em sabedoria, em estatura e em graça diante de Deus e dos homens."},
{s:"O anúncio contra a casa de Heli"},
{v:27,t:"Um homem de Deus veio ter com Heli e disse-lhe: Assim diz o Senhor: Não me revelei eu claramente à casa de teu pai, quando estavam no Egito, na casa do faraó?",np:1},
{v:28,t:"Escolhi-o dentre todas as tribos de Israel para ser meu sacerdote, para subir ao meu altar, queimar incenso e levar o efod diante de mim; e dei à casa de teu pai todas as ofertas queimadas dos filhos de Israel."},
{v:29,t:"Por que calcais aos pés os meus sacrifícios e as minhas ofertas, que ordenei para a minha morada? Por que honras os teus filhos mais do que a mim, engordando-vos com o melhor de todas as ofertas de Israel, meu povo?"},
{v:30,t:"Por isso diz o Senhor, Deus de Israel: Eu tinha dito que a tua casa e a casa de teu pai andariam diante de mim para sempre; mas agora, diz o Senhor, longe de mim tal coisa! Pois eu honro os que me honram, e os que me desprezam serão desprezados."},
{v:31,t:"Eis que virão dias em que cortarei o teu braço e o braço da casa de teu pai, de modo que não haverá velho na tua casa."},
{v:32,t:"Verás um rival na minha morada, em todo o bem que eu fizer a Israel; e não haverá mais velho na tua casa, em todos os dias."},
{v:33,t:"Não cortarei inteiramente do meu altar os teus descendentes, para que se consumam os teus olhos e se aflija a tua alma; mas a maior parte da tua casa morrerá na idade adulta.",n:"O anúncio cumpre-se em etapas: a morte de Ofni e Fineias, o massacre dos sacerdotes de Nob por Saul, e o afastamento de Abiatar por Salomão."},
{v:34,t:"Será para ti um sinal o que acontecerá a teus dois filhos, Ofni e Fineias: morrerão ambos no mesmo dia."},
{v:35,t:"Suscitarei para mim um sacerdote fiel, que agirá segundo o meu coração e a minha alma; edificarei para ele uma casa duradoura, e ele andará sempre diante do meu ungido.",n:"O sacerdote fiel será Sadoc, no tempo de Salomão. A Igreja viu, para além dele, Cristo, o sumo sacerdote fiel de que fala a Carta aos Hebreus."},
{v:36,t:"E todo aquele que restar da tua casa virá prostrar-se diante dele por uma moeda de prata e um pedaço de pão, e dirá: Admite-me, por favor, a alguma função sacerdotal, para que eu tenha um bocado de pão para comer."}
];

window.TEXTOS_SEED["1samuel"][3] = [
{s:"O chamado de Samuel"},
{v:1,t:"O menino Samuel servia o Senhor diante de Heli. Naqueles dias, a palavra do Senhor era rara, e as visões não eram frequentes.",n:"Rara, à letra preciosa, como o que escasseia. O livro começa num tempo de silêncio de Deus."},
{v:2,t:"Certo dia, Heli estava deitado no seu lugar; os seus olhos tinham começado a enfraquecer, e já não podia ver."},
{v:3,t:"A lâmpada de Deus ainda não se tinha apagado, e Samuel dormia no templo do Senhor, onde estava a arca de Deus.",n:"A lâmpada do santuário ardia de noite até a madrugada. Ainda não se apagara: é pouco antes do amanhecer — e também, na história de Israel, a luz de Deus ainda não se extinguiu."},
{v:4,t:"O Senhor chamou Samuel, e ele respondeu: Eis-me aqui!"},
{v:5,t:"Correu a Heli e disse: Eis-me aqui, porque me chamaste. Heli respondeu: Não te chamei; volta a deitar-te. E ele foi deitar-se."},
{v:6,t:"O Senhor chamou de novo: Samuel! Samuel levantou-se, foi a Heli e disse: Eis-me aqui, porque me chamaste. Heli respondeu: Não te chamei, meu filho; volta a deitar-te."},
{v:7,t:"Samuel ainda não conhecia o Senhor, e a palavra do Senhor ainda não lhe tinha sido revelada."},
{v:8,t:"O Senhor chamou Samuel pela terceira vez; ele levantou-se e foi a Heli"},
{v:9,t:"e disse: Eis-me aqui, porque me chamaste. Então Heli compreendeu que era o Senhor que chamava o menino, e disse a Samuel: Vai deitar-te; e, se te chamarem de novo, dirás: Fala, Senhor, porque o teu servo escuta. Samuel foi e deitou-se no seu lugar.",n:"O velho sacerdote, que não soube guiar os filhos, sabe ainda ensinar o menino a escutar. É a oração de todo chamado."},
{v:10,t:"O Senhor veio, pôs-se ali e chamou como das outras vezes: Samuel, Samuel! Samuel respondeu: Fala, porque o teu servo escuta.",np:1},
{v:11,t:"O Senhor disse a Samuel: Eis que vou fazer em Israel uma coisa que fará zunir os dois ouvidos de quem a ouvir."},
{v:12,t:"Naquele dia cumprirei contra Heli tudo o que disse a respeito da sua casa, do princípio ao fim."},
{v:13,t:"Anunciei-lhe que vou julgar a sua casa para sempre, por causa do pecado que ele conhecia: os seus filhos desprezavam a Deus, e ele não os repreendeu.",n:"O hebraico diz, por correção dos escribas, que os filhos se amaldiçoavam a si mesmos; a leitura antiga, conservada pela versão grega e pela Nova Vulgata, diz que desprezavam a Deus."},
{v:14,t:"Por isso jurei à casa de Heli que o pecado da casa de Heli jamais será expiado, nem por sacrifícios nem por ofertas."},
{v:15,t:"Samuel ficou deitado até de manhã; depois abriu as portas da casa do Senhor. Mas tinha medo de contar a visão a Heli.",np:1},
{v:16,t:"Heli chamou Samuel e disse: Samuel, meu filho! Ele respondeu: Eis-me aqui."},
{v:17,t:"Heli perguntou: Que foi que ele te disse? Não me escondas nada. Que Deus te faça isto e mais aquilo, se me esconderes uma só palavra de tudo o que ele te disse."},
{v:18,t:"Samuel contou-lhe tudo, sem nada esconder. E Heli disse: Ele é o Senhor; faça o que lhe parecer bom.",n:"A resignação de Heli tem grandeza: aceita o juízo de Deus sobre a sua casa."},
{v:19,t:"Samuel crescia, e o Senhor estava com ele e não deixava cair por terra nenhuma das suas palavras.",np:1,n:"Não deixava cair por terra: todas se cumpriam. É o sinal do verdadeiro profeta, segundo o Deuteronômio."},
{v:20,t:"Todo o Israel, desde Dã até Bersabeia, reconheceu que Samuel era um profeta acreditado do Senhor."},
{v:21,t:"O Senhor continuou a manifestar-se em Silo, porque o Senhor se revelava a Samuel em Silo, pela sua palavra. E a palavra de Samuel chegava a todo o Israel."}
];

window.TEXTOS_SEED["1samuel"][4] = [
{s:"A arca tomada pelos filisteus"},
{v:1,t:"Naqueles dias, os filisteus reuniram-se para a guerra contra Israel, e Israel saiu ao encontro dos filisteus para o combate e acampou junto a Ebenézer; os filisteus acamparam em Afec.",n:"O começo da guerra vem da versão grega, que a Nova Vulgata segue; o hebraico é aqui mais breve. Ebenézer quer dizer pedra do socorro: o nome só lhe será dado no capítulo 7, e o narrador o antecipa."},
{v:2,t:"Os filisteus dispuseram-se em linha de batalha contra Israel. Travou-se o combate, e Israel foi derrotado pelos filisteus, que mataram no campo de batalha cerca de quatro mil homens."},
{v:3,t:"O povo voltou ao acampamento, e os anciãos de Israel disseram: Por que o Senhor nos deixou derrotar hoje diante dos filisteus? Vamos buscar em Silo a arca da aliança do Senhor, para que venha para o meio de nós e nos salve da mão dos nossos inimigos.",n:"Os anciãos tratam a arca como um amuleto que obrigaria Deus a combater. O capítulo mostra que Deus não se deixa manipular."},
{v:4,t:"O povo mandou buscar em Silo a arca da aliança do Senhor dos exércitos, que está sentado sobre os querubins; e os dois filhos de Heli, Ofni e Fineias, estavam ali com a arca da aliança de Deus.",n:"Sentado sobre os querubins: a arca era o escabelo do trono invisível de Deus, guardado por dois querubins de ouro."},
{v:5,t:"Quando a arca da aliança do Senhor chegou ao acampamento, todo o Israel soltou um grande grito de guerra, e a terra estremeceu."},
{v:6,t:"Os filisteus ouviram o barulho do grito e disseram: Que significa este grande grito no acampamento dos hebreus? E souberam que a arca do Senhor tinha chegado ao acampamento.",n:"Hebreus é o nome que os estrangeiros dão aos israelitas, com uma ponta de desprezo."},
{v:7,t:"Os filisteus tiveram medo, porque diziam: Deus veio ao acampamento! E gemiam, dizendo:"},
{v:8,t:"Ai de nós! Nunca, até agora, houve tal júbilo entre eles. Ai de nós! Quem nos livrará da mão destes deuses poderosos? São os deuses que feriram o Egito com toda espécie de pragas no deserto."},
{v:9,t:"Coragem, filisteus, e sede homens, para não serdes escravos dos hebreus, como eles foram vossos escravos! Sede homens e combatei!"},
{v:10,t:"Os filisteus combateram, e Israel foi derrotado; cada um fugiu para a sua tenda. A derrota foi muito grande: caíram de Israel trinta mil homens de infantaria.",np:1},
{v:11,t:"A arca de Deus foi tomada, e os dois filhos de Heli, Ofni e Fineias, morreram.",n:"Cumpre-se o sinal anunciado a Heli: os dois filhos morrem no mesmo dia."},
{s:"A morte de Heli"},
{v:12,t:"Um homem de Benjamim correu do campo de batalha e chegou a Silo naquele mesmo dia, com as vestes rasgadas e a cabeça coberta de terra.",np:1,n:"Uma tradição judaica diz que esse mensageiro era Saul."},
{v:13,t:"Quando chegou, Heli estava sentado na cadeira, junto à porta, olhando para o caminho, porque o seu coração tremia pela arca de Deus. O homem entrou na cidade para dar a notícia, e toda a cidade soltou gritos."},
{v:14,t:"Heli ouviu o barulho dos gritos e perguntou: Que barulho é este? O homem veio depressa e deu a notícia a Heli."},
{v:15,t:"Heli tinha noventa e oito anos; os seus olhos tinham escurecido, e já não podia ver."},
{v:16,t:"O homem disse a Heli: Sou eu que vim do campo de batalha; fugi hoje do campo de batalha. Heli perguntou: Que aconteceu, meu filho?"},
{v:17,t:"O mensageiro respondeu: Israel fugiu diante dos filisteus, e houve grande mortandade entre o povo; também os teus dois filhos, Ofni e Fineias, morreram, e a arca de Deus foi tomada."},
{v:18,t:"Quando ele mencionou a arca de Deus, Heli caiu da cadeira para trás, junto à porta, quebrou o pescoço e morreu, porque era velho e pesado. Tinha julgado Israel durante quarenta anos.",n:"Não é a morte dos filhos que o derruba, mas a notícia da arca: o velho sacerdote amava a Deus mais do que soubera mostrar."},
{v:19,t:"Sua nora, mulher de Fineias, estava grávida e prestes a dar à luz. Quando ouviu a notícia de que a arca de Deus tinha sido tomada e de que o sogro e o marido tinham morrido, curvou-se e deu à luz, porque lhe sobrevieram as dores.",np:1},
{v:20,t:"No momento em que ia morrer, as mulheres que a assistiam disseram-lhe: Não tenhas medo, porque deste à luz um filho. Mas ela não respondeu nem fez caso."},
{v:21,t:"Deu ao menino o nome de Icabod, por causa da arca de Deus, que tinha sido tomada, e por causa do sogro e do marido; e disse: A glória foi exilada de Israel!",n:"Icabod quer dizer onde está a glória?, ou sem glória. A glória de Deus, a sua presença, parte para o exílio com a arca."},
{v:22,t:"E disse: A glória foi exilada de Israel, porque a arca de Deus foi tomada."}
];

window.TEXTOS_SEED["1samuel"][5] = [
{s:"A arca entre os filisteus"},
{v:1,t:"Os filisteus tomaram a arca de Deus e levaram-na de Ebenézer para Azoto."},
{v:2,t:"Tomaram a arca de Deus, levaram-na ao templo de Dagon e colocaram-na ao lado de Dagon.",n:"Pôr a arca junto do deus vencedor era o costume com os deuses dos vencidos: um troféu. O capítulo narra, com humor, a humilhação do deus vencedor."},
{v:3,t:"No dia seguinte, os habitantes de Azoto levantaram-se de madrugada, e eis que Dagon estava caído com o rosto por terra diante da arca do Senhor. Tomaram Dagon e o repuseram no seu lugar."},
{v:4,t:"No dia seguinte, levantaram-se de madrugada, e eis que Dagon estava de novo caído com o rosto por terra diante da arca do Senhor; e a cabeça de Dagon e as duas mãos estavam cortadas, sobre a soleira;"},
{v:5,t:"só o tronco de Dagon tinha ficado no seu lugar. Por isso, os sacerdotes de Dagon e todos os que entram no templo de Dagon não pisam a soleira de Dagon, em Azoto, até o dia de hoje.",n:"Dagon prostrado diante da arca: o deus dos vencedores adora o Deus dos vencidos. O costume de saltar a soleira, conhecido também em outros povos, é explicado pela história."},
{v:6,t:"A mão do Senhor pesou sobre os habitantes de Azoto; devastou-os e feriu-os de tumores, em Azoto e no seu território.",np:1,n:"Tumores: provavelmente a peste bubônica, transmitida pelos ratos, que o capítulo seguinte mencionará."},
{v:7,t:"Vendo o que acontecia, os homens de Azoto disseram: Que a arca do Deus de Israel não fique entre nós, porque a sua mão é dura contra nós e contra Dagon, o nosso deus."},
{v:8,t:"Mandaram reunir junto de si todos os príncipes dos filisteus e disseram: Que faremos com a arca do Deus de Israel? Eles responderam: Que a arca do Deus de Israel seja levada a Gat. E levaram para lá a arca do Deus de Israel."},
{v:9,t:"Depois que a levaram, a mão do Senhor pesou sobre a cidade, com um pânico muito grande; e feriu os homens da cidade, do menor ao maior, e brotaram-lhes tumores."},
{v:10,t:"Então mandaram a arca de Deus para Acaron. Mas, quando a arca de Deus chegou a Acaron, os acaronitas gritaram: Trouxeram-nos a arca do Deus de Israel, para nos matar, a nós e ao nosso povo!"},
{v:11,t:"Mandaram reunir todos os príncipes dos filisteus e disseram: Mandai embora a arca do Deus de Israel; volte ela para o seu lugar, e não nos mate, a nós e ao nosso povo."},
{v:12,t:"Pois havia um pânico mortal em toda a cidade, e a mão de Deus pesava muito sobre ela. Os que não morriam eram feridos de tumores, e o clamor da cidade subia até o céu."}
];

window.TEXTOS_SEED["1samuel"][6] = [
{s:"A arca devolvida a Israel"},
{v:1,t:"A arca do Senhor ficou sete meses na terra dos filisteus."},
{v:2,t:"Os filisteus chamaram os sacerdotes e os adivinhos e disseram: Que faremos com a arca do Senhor? Dizei-nos como a devolveremos ao seu lugar. Eles responderam:"},
{v:3,t:"Se devolverdes a arca do Deus de Israel, não a mandeis vazia, mas pagai-lhe uma oferta de reparação; então sereis curados e sabereis por que a sua mão não se afastava de vós."},
{v:4,t:"Eles perguntaram: Que oferta de reparação lhe devemos pagar? Responderam:"},
{v:5,t:"Segundo o número dos príncipes dos filisteus, cinco tumores de ouro e cinco ratos de ouro, porque a mesma praga atingiu todos vós e os vossos príncipes. Fareis imagens dos vossos tumores e imagens dos ratos que devastam a terra, e dareis glória ao Deus de Israel; talvez ele alivie a sua mão de sobre vós, de sobre os vossos deuses e de sobre a vossa terra.",n:"As imagens de ouro dos males eram oferendas conhecidas na antiguidade: devolvia-se à divindade a imagem da doença de que se pedia a cura."},
{v:6,t:"Por que endureceríeis o vosso coração, como os egípcios e o faraó endureceram o seu? Não foi depois de castigados por ele que os egípcios deixaram partir os israelitas, e eles se foram?",n:"Os filisteus conhecem a história do Êxodo: a fama do Deus de Israel corre entre os pagãos."},
{v:7,t:"Agora, pois, preparai um carro novo e tomai duas vacas que estejam amamentando, e que nunca tenham levado jugo; atrelai as vacas ao carro e prendei em casa os seus bezerros.",np:1},
{v:8,t:"Tomai a arca do Senhor e ponde-a no carro; e os objetos de ouro que lhe pagais como oferta de reparação, ponde-os numa caixa ao lado dela; e deixai-a ir."},
{v:9,t:"E observai: se ela subir pelo caminho do seu território, em direção a Bet-Sames, foi ele quem nos fez este grande mal; se não, saberemos que não foi a sua mão que nos feriu, mas foi um acaso que nos aconteceu.",n:"Vacas que amamentam, com os bezerros presos em casa, voltariam naturalmente para eles. Se forem na direção oposta, contra o instinto, é Deus quem as leva."},
{v:10,t:"Assim fizeram: tomaram duas vacas que amamentavam, atrelaram-nas ao carro e prenderam os bezerros em casa."},
{v:11,t:"Puseram no carro a arca do Senhor e a caixa com os ratos de ouro e as imagens dos tumores."},
{v:12,t:"As vacas foram direto pelo caminho de Bet-Sames; seguiam por uma única estrada, mugindo enquanto andavam, sem se desviarem nem para a direita nem para a esquerda. Os príncipes dos filisteus foram atrás delas até a fronteira de Bet-Sames.",n:"Mugindo: chamam os bezerros, e seguem no sentido contrário. É a imagem do sinal pedido."},
{v:13,t:"Os habitantes de Bet-Sames ceifavam o trigo no vale; levantaram os olhos, viram a arca e alegraram-se ao vê-la.",np:1},
{v:14,t:"O carro chegou ao campo de Josué, o betsamita, e parou ali. Havia ali uma grande pedra; racharam a madeira do carro e ofereceram as vacas em holocausto ao Senhor."},
{v:15,t:"Os levitas desceram a arca do Senhor e a caixa que estava junto dela, com os objetos de ouro, e puseram-nas sobre a grande pedra. Naquele dia, os homens de Bet-Sames ofereceram holocaustos e sacrifícios ao Senhor."},
{v:16,t:"Os cinco príncipes dos filisteus viram isso e voltaram a Acaron naquele mesmo dia."},
{v:17,t:"Estes são os tumores de ouro que os filisteus pagaram ao Senhor como oferta de reparação: um por Azoto, um por Gaza, um por Ascalon, um por Gat e um por Acaron;",np:1},
{v:18,t:"e os ratos de ouro eram tantos quantas as cidades dos filisteus pertencentes aos cinco príncipes, desde as cidades fortificadas até as aldeias sem muralha. E a grande pedra, sobre a qual puseram a arca do Senhor, está ainda hoje como testemunha no campo de Josué, o betsamita."},
{v:19,t:"Mas os filhos de Jeconias não se alegraram com os homens de Bet-Sames, quando viram a arca do Senhor; e o Senhor feriu setenta homens do povo. O povo ficou de luto, porque o Senhor ferira o povo com uma grande mortandade.",np:1,n:"Nota do tradutor: o hebraico diz que o Senhor feriu os homens de Bet-Sames por terem olhado para a arca do Senhor, e feriu do povo setenta homens, cinquenta mil homens — número duplo, que parece somar duas tradições. A Nova Vulgata segue aqui a versão grega, na qual a culpa é de um clã, os filhos de Jeconias, que ficaram indiferentes à volta da arca; e conserva só os setenta. Em um caso ou em outro, a lição é a mesma: a santidade de Deus não é coisa com que se brinque."},
{v:20,t:"E os homens de Bet-Sames disseram: Quem pode subsistir diante do Senhor, este Deus santo? E para quem subirá ele, saindo de nós?"},
{v:21,t:"Enviaram mensageiros aos habitantes de Cariat-Iarim, dizendo: Os filisteus devolveram a arca do Senhor; descei e levai-a para junto de vós."}
];

window.TEXTOS_SEED["1samuel"][7] = [
{s:"Samuel, juiz de Israel"},
{v:1,t:"Os homens de Cariat-Iarim vieram e levaram a arca do Senhor; introduziram-na na casa de Abinadab, na colina, e consagraram Eleazar, seu filho, para guardar a arca do Senhor.",n:"A arca ficará em Cariat-Iarim até que Davi a leve para Jerusalém. Silo, segundo Jeremias, foi destruída: por isso a arca não volta para lá."},
{v:2,t:"Desde o dia em que a arca ficou em Cariat-Iarim, passou muito tempo — vinte anos —, e toda a casa de Israel suspirava pelo Senhor.",np:1},
{v:3,t:"Samuel disse a toda a casa de Israel: Se é de todo o coração que voltais ao Senhor, tirai do meio de vós os deuses estrangeiros e as Astartes, dirigi o vosso coração para o Senhor e servi somente a ele; e ele vos livrará da mão dos filisteus."},
{v:4,t:"Os filhos de Israel tiraram do meio deles os baais e as Astartes e serviram somente ao Senhor."},
{v:5,t:"Samuel disse: Reuni todo o Israel em Masfa, e eu orarei ao Senhor por vós.",np:1},
{v:6,t:"Reuniram-se em Masfa, tiraram água e derramaram-na diante do Senhor; jejuaram naquele dia e disseram ali: Pecamos contra o Senhor. E Samuel julgou os filhos de Israel em Masfa.",n:"Derramar água diante do Senhor: rito de penitência de que não há outro exemplo na Bíblia. Talvez significasse o coração derramado como água, na expressão das Lamentações."},
{v:7,t:"Quando os filisteus souberam que os filhos de Israel se tinham reunido em Masfa, os príncipes dos filisteus subiram contra Israel. Os filhos de Israel souberam disso e tiveram medo dos filisteus,",np:1},
{v:8,t:"e disseram a Samuel: Não deixes de clamar por nós ao Senhor nosso Deus, para que nos salve da mão dos filisteus."},
{v:9,t:"Samuel tomou um cordeiro de leite e ofereceu-o inteiro em holocausto ao Senhor; e Samuel clamou ao Senhor por Israel, e o Senhor o atendeu."},
{v:10,t:"Enquanto Samuel oferecia o holocausto, os filisteus avançaram para combater contra Israel; mas o Senhor trovejou naquele dia com grande estrondo sobre os filisteus, lançou-os em pânico, e foram derrotados diante de Israel.",n:"Samuel vence como Moisés, pela oração: o povo não combate, e o céu troveja."},
{v:11,t:"Os homens de Israel saíram de Masfa, perseguiram os filisteus e derrotaram-nos até abaixo de Bet-Car."},
{v:12,t:"Samuel tomou uma pedra e colocou-a entre Masfa e Sen, e deu àquele lugar o nome de Ebenézer, isto é, Pedra do Socorro, dizendo: Até aqui o Senhor nos socorreu.",np:1,n:"O nome de Ebenézer, que no capítulo 4 marcava a derrota, marca agora a vitória. A frase de Samuel, até aqui o Senhor nos socorreu, tornou-se oração de agradecimento na tradição cristã."},
{v:13,t:"Os filisteus foram humilhados e não voltaram mais a entrar no território de Israel; e a mão do Senhor pesou sobre os filisteus durante todos os dias de Samuel."},
{v:14,t:"As cidades que os filisteus tinham tomado de Israel voltaram a Israel, desde Acaron até Gat; e Israel libertou o seu território da mão dos filisteus. E havia paz entre Israel e os amorreus."},
{v:15,t:"Samuel julgou Israel durante todos os dias da sua vida.",np:1},
{v:16,t:"Todos os anos, fazia um percurso por Betel, Guilgal e Masfa, e julgava Israel em todos esses lugares."},
{v:17,t:"Depois voltava a Ramá, porque ali estava a sua casa; e ali julgava Israel. E construiu ali um altar ao Senhor."}
];

window.TEXTOS_SEED["1samuel"][8] = [
{s:"O povo pede um rei"},
{v:1,t:"Quando Samuel envelheceu, constituiu seus filhos juízes de Israel."},
{v:2,t:"O primogênito chamava-se Joel, e o segundo, Abia; eram juízes em Bersabeia."},
{v:3,t:"Mas os filhos não andaram pelos caminhos do pai: desviaram-se atrás do lucro, aceitaram subornos e perverteram o direito.",n:"O drama de Heli repete-se com Samuel: os filhos do juiz justo não seguem o pai. É a ocasião do pedido de um rei."},
{v:4,t:"Então todos os anciãos de Israel se reuniram e foram ter com Samuel em Ramá,",np:1},
{v:5,t:"e disseram-lhe: Tu envelheceste, e os teus filhos não andam pelos teus caminhos. Agora, pois, constitui-nos um rei, para que nos julgue, como têm todas as nações.",n:"Como têm todas as nações: o povo escolhido quer ser como os outros. O Deuteronômio já previa este pedido e punha limites ao rei (Deuteronômio 17,14-20)."},
{v:6,t:"A palavra desagradou a Samuel, porque tinham dito: Dá-nos um rei, para que nos julgue. E Samuel orou ao Senhor."},
{v:7,t:"O Senhor disse a Samuel: Ouve a voz do povo em tudo o que te dizem; porque não é a ti que rejeitaram, é a mim que rejeitaram, para que eu não reine sobre eles.",n:"O verdadeiro rei de Israel é Deus, como dissera Gedeão: o Senhor reinará sobre vós. Deus consente no pedido, mas lhe dá o seu nome: uma rejeição."},
{v:8,t:"Conforme todas as obras que fizeram desde o dia em que os tirei do Egito até hoje, abandonando-me e servindo a outros deuses, assim fazem também contigo."},
{v:9,t:"Agora, pois, ouve a sua voz; mas adverte-os solenemente e dá-lhes a conhecer o direito do rei que reinará sobre eles."},
{v:10,t:"Samuel repetiu todas as palavras do Senhor ao povo que lhe pedia um rei,",np:1},
{v:11,t:"e disse: Este será o direito do rei que reinará sobre vós: tomará os vossos filhos e os destinará aos seus carros e à sua cavalaria, e eles correrão diante do seu carro;"},
{v:12,t:"fará deles chefes de mil e chefes de cinquenta, lavradores dos seus campos e ceifeiros das suas colheitas, fabricantes das suas armas de guerra e dos arreios dos seus carros."},
{v:13,t:"Tomará as vossas filhas para perfumistas, cozinheiras e padeiras."},
{v:14,t:"Tomará os vossos campos, as vossas vinhas e os vossos melhores olivais, e os dará aos seus servos."},
{v:15,t:"Cobrará o dízimo das vossas sementeiras e das vossas vinhas, para dá-lo aos seus eunucos e aos seus servos."},
{v:16,t:"Tomará os vossos servos e as vossas servas, os vossos melhores bois e os vossos jumentos, e os empregará nos seus trabalhos.",n:"Os melhores bois: assim a versão grega, que a Nova Vulgata segue; o hebraico diz os vossos melhores jovens."},
{v:17,t:"Cobrará o dízimo dos vossos rebanhos, e vós mesmos sereis seus escravos."},
{v:18,t:"Naquele dia clamareis por causa do rei que tiverdes escolhido, e o Senhor não vos responderá naquele dia.",n:"O retrato é o dos reis do Oriente, e será, com poucas exceções, o dos reis de Israel: Salomão e Roboão o cumprirão à letra."},
{v:19,t:"Mas o povo recusou-se a ouvir a voz de Samuel e disse: Não! Haverá um rei sobre nós,",np:1},
{v:20,t:"e seremos também nós como todas as nações: o nosso rei nos julgará, sairá à nossa frente e combaterá as nossas batalhas."},
{v:21,t:"Samuel ouviu todas as palavras do povo e repetiu-as aos ouvidos do Senhor."},
{v:22,t:"O Senhor disse a Samuel: Ouve a sua voz e constitui-lhes um rei. E Samuel disse aos homens de Israel: Volte cada um para a sua cidade."}
];

window.TEXTOS_SEED["1samuel"][9] = [
{s:"Saul procura as jumentas de seu pai"},
{v:1,t:"Havia um homem de Benjamim chamado Cis, filho de Abiel, filho de Seror, filho de Becorat, filho de Afia, benjaminita, homem poderoso."},
{v:2,t:"Tinha um filho chamado Saul, jovem e belo; não havia entre os filhos de Israel ninguém mais belo do que ele: dos ombros para cima, ultrapassava todo o povo.",n:"Saul quer dizer pedido: o nome lembra o pedido do povo. É o rei que o povo queria, alto e belo como os reis das nações."},
{v:3,t:"As jumentas de Cis, pai de Saul, extraviaram-se, e Cis disse a seu filho Saul: Leva contigo um dos servos, levanta-te e vai procurar as jumentas. Eles atravessaram a montanha de Efraim",np:1},
{v:4,t:"e a terra de Salisa, e não as encontraram; passaram pela terra de Salim, e não estavam lá; passaram pela terra de Benjamim, e não as acharam."},
{v:5,t:"Quando chegaram à terra de Suf, Saul disse ao servo que estava com ele: Vem, voltemos, para que meu pai não deixe de pensar nas jumentas e fique inquieto por nós."},
{v:6,t:"O servo respondeu-lhe: Há nesta cidade um homem de Deus, homem respeitado: tudo o que ele diz acontece sem falta. Vamos até lá; talvez nos oriente sobre a viagem que nos trouxe aqui."},
{v:7,t:"Saul disse ao seu servo: Pois bem, vamos; mas que levaremos ao homem? O pão acabou nos nossos alforjes, e não temos presente para dar ao homem de Deus. Que temos?",n:"Não se consultava um vidente de mãos vazias: o presente era o costume."},
{v:8,t:"O servo tornou a responder a Saul: Tenho aqui na mão um quarto de siclo de prata; nós o daremos ao homem de Deus, para que nos indique o caminho."},
{v:9,t:"Antigamente, em Israel, quem ia consultar a Deus dizia: Vinde, vamos ao vidente; porque o que hoje se chama profeta chamava-se antigamente vidente.",n:"Observação do narrador, que explica aos leitores do seu tempo uma palavra antiga, que vai aparecer logo adiante."},
{v:10,t:"Saul disse ao seu servo: Dizes bem; vem, vamos. E foram à cidade onde estava o homem de Deus."},
{v:11,t:"Subindo a ladeira da cidade, encontraram umas moças que saíam para tirar água e perguntaram-lhes: O vidente está aqui?",np:1},
{v:12,t:"Elas responderam: Está, sim; está aí à tua frente. Apressa-te agora, porque ele veio hoje à cidade, pois hoje há um sacrifício do povo no lugar alto.",n:"O lugar alto era o santuário ao ar livre, no alto de uma colina. Antes do templo de Jerusalém, o culto nesses lugares era legítimo."},
{v:13,t:"Logo que entrardes na cidade, o encontrareis, antes que ele suba ao lugar alto para comer; o povo não comerá antes que ele chegue, porque é ele quem abençoa o sacrifício, e depois comem os convidados. Subi, pois, agora, e logo o encontrareis."},
{v:14,t:"Subiram à cidade. Quando entravam na cidade, Samuel vinha saindo ao encontro deles, para subir ao lugar alto."},
{v:15,t:"Ora, um dia antes da chegada de Saul, o Senhor tinha feito a Samuel esta revelação:",np:1,n:"À letra, o Senhor tinha descoberto o ouvido de Samuel: tinha-lhe falado em segredo."},
{v:16,t:"Amanhã, a esta mesma hora, enviarei a ti um homem da terra de Benjamim; tu o ungirás como chefe do meu povo Israel, e ele salvará o meu povo da mão dos filisteus, porque olhei para o meu povo, pois o seu clamor chegou até mim.",n:"Chefe, em hebraico nagid: o designado, o príncipe escolhido por Deus. O texto ainda evita a palavra rei."},
{v:17,t:"Quando Samuel viu Saul, o Senhor lhe disse: Eis o homem de quem te falei; é ele quem governará o meu povo."},
{v:18,t:"Saul aproximou-se de Samuel no meio da porta e disse: Indica-me, por favor, onde é a casa do vidente."},
{v:19,t:"Samuel respondeu a Saul: O vidente sou eu. Sobe à minha frente ao lugar alto, e hoje comereis comigo. Amanhã cedo te deixarei partir, e te direi tudo o que tens no coração."},
{v:20,t:"Quanto às jumentas que perdeste há três dias, não te preocupes com elas, porque já foram encontradas. E para quem será tudo o que Israel tem de mais precioso? Não será para ti e para toda a casa de teu pai?",n:"Samuel responde à preocupação de Saul antes de ser perguntado, e já alude à realeza."},
{v:21,t:"Saul respondeu: Não sou eu um benjaminita, da menor das tribos de Israel? E a minha família não é a menor de todas as famílias da tribo de Benjamim? Por que, pois, me falas deste modo?",n:"Benjamim quase desaparecera na guerra contada no fim dos Juízes. A humildade de Saul lembra a de Gedeão."},
{v:22,t:"Samuel tomou Saul e o seu servo, levou-os à sala e deu-lhes lugar à cabeceira dos convidados, que eram cerca de trinta homens.",np:1},
{v:23,t:"Samuel disse ao cozinheiro: Traze a porção que te dei, aquela que te mandei guardar à parte."},
{v:24,t:"O cozinheiro tirou a coxa e a cauda e colocou-as diante de Saul. Samuel disse: Aqui está o que foi reservado; serve-te e come, porque foi guardado de propósito para ti, quando convidei o povo. E Saul comeu com Samuel naquele dia.",n:"A coxa era a porção de honra. A cauda: a Nova Vulgata segue uma correção provável do hebraico, que diz e o que estava sobre ela; a cauda gorda dos carneiros era parte escolhida."},
{v:25,t:"Desceram do lugar alto para a cidade. Prepararam uma cama para Saul no terraço, e ele dormiu.",np:1,n:"Assim a versão grega, que a Nova Vulgata segue; o hebraico diz que Samuel conversou com Saul no terraço. Os terraços planos das casas serviam de dormitório nas noites quentes."},
{v:26,t:"Levantaram-se cedo; ao romper do dia, Samuel chamou Saul no terraço, dizendo: Levanta-te, e eu te deixarei partir. Saul levantou-se, e saíram os dois, ele e Samuel."},
{v:27,t:"Quando desciam para a saída da cidade, Samuel disse a Saul: Dize ao servo que passe adiante de nós — e ele passou adiante —; tu, porém, para um momento, para que eu te faça ouvir a palavra do Senhor."}
];

window.TEXTOS_SEED["1samuel"][10] = [
{s:"Samuel unge Saul"},
{v:1,t:"Samuel tomou o frasco de óleo, derramou-o sobre a cabeça de Saul, beijou-o e disse: O Senhor te ungiu como chefe do seu povo Israel. Tu governarás o povo do Senhor e o livrarás da mão dos inimigos que o cercam. E este será para ti o sinal de que Deus te ungiu como chefe da sua herança:",n:"Grande parte do versículo, de tu governarás até da sua herança, falta no hebraico, por um salto do copista entre duas frases iguais; a Nova Vulgata a restitui a partir da versão grega. A unção fazia do rei o ungido do Senhor, em hebraico messias."},
{v:2,t:"quando hoje te afastares de mim, encontrarás dois homens junto ao sepulcro de Raquel, na fronteira de Benjamim, e eles te dirão: As jumentas que foste procurar foram encontradas; teu pai já não pensa nas jumentas, mas está inquieto por vós e diz: Que farei por meu filho?",n:"O hebraico acrescenta em Selsa, lugar desconhecido. Segundo esta tradição, o sepulcro de Raquel ficava no território de Benjamim, ao norte de Jerusalém; outra o põe junto de Belém."},
{v:3,t:"Partindo dali, irás mais adiante e chegarás ao carvalho do Tabor; ali te encontrarão três homens que sobem a Deus em Betel: um levando três cabritos, outro, três pães, e outro, um odre de vinho."},
{v:4,t:"Eles te saudarão e te darão dois pães, e tu os aceitarás das suas mãos."},
{v:5,t:"Depois disso, chegarás a Gabaá de Deus, onde há uma guarnição dos filisteus; e, ao entrares na cidade, encontrarás um grupo de profetas descendo do lugar alto, precedidos de harpa, tamborim, flauta e lira, e eles estarão profetizando.",n:"Gabaá de Deus é talvez a própria Gabaá de Saul. Os grupos de profetas cantavam e dançavam ao som da música, num entusiasmo contagioso."},
{v:6,t:"O Espírito do Senhor se apoderará de ti, profetizarás com eles e serás mudado em outro homem."},
{v:7,t:"Quando esses sinais te acontecerem, faze o que a ocasião pedir, porque Deus está contigo."},
{v:8,t:"Depois descerás antes de mim a Guilgal; eu descerei para junto de ti, para oferecer holocaustos e sacrifícios de comunhão. Esperarás sete dias, até que eu chegue junto de ti e te mostre o que deves fazer.",n:"Esta ordem prepara a primeira falta de Saul, no capítulo 13."},
{s:"Saul entre os profetas"},
{v:9,t:"Assim que Saul voltou as costas para deixar Samuel, Deus lhe mudou o coração, e todos aqueles sinais se cumpriram naquele dia.",np:1},
{v:10,t:"Chegaram a Gabaá, e eis que um grupo de profetas veio ao seu encontro; o Espírito de Deus apoderou-se dele, e ele profetizou no meio deles."},
{v:11,t:"Todos os que o conheciam de antes, vendo-o profetizar com os profetas, diziam uns aos outros: Que aconteceu ao filho de Cis? Também Saul está entre os profetas?"},
{v:12,t:"Um homem do lugar respondeu: E quem é o pai deles? Por isso se tornou proverbial: Também Saul está entre os profetas?",n:"O pai era o mestre de um grupo de profetas. A resposta quer dizer: a profecia não se herda, é dom de Deus, que a dá a quem quer. O provérbio servia para falar de alguém que aparece onde não se esperava."},
{v:13,t:"Quando acabou de profetizar, foi a Gabaá.",n:"Assim a Nova Vulgata; o hebraico diz: foi ao lugar alto."},
{v:14,t:"O tio de Saul perguntou a ele e ao seu servo: Aonde fostes? Ele respondeu: Procurar as jumentas; e, como não as encontramos, fomos ter com Samuel.",np:1},
{v:15,t:"O tio disse: Conta-me, por favor, o que Samuel vos disse."},
{v:16,t:"Saul respondeu ao tio: Disse-nos que as jumentas tinham sido encontradas. Mas do assunto da realeza, de que Samuel lhe falara, não lhe contou nada."},
{s:"Saul escolhido rei por sorteio"},
{v:17,t:"Samuel convocou o povo diante do Senhor, em Masfa,",np:1},
{v:18,t:"e disse aos filhos de Israel: Assim diz o Senhor, Deus de Israel: Eu fiz Israel subir do Egito e vos livrei da mão dos egípcios e da mão de todos os reinos que vos oprimiam."},
{v:19,t:"Mas vós rejeitastes hoje o vosso Deus, que sozinho vos salvou de todos os vossos males e das vossas angústias, e dissestes: Não! Constitui um rei sobre nós! Agora, pois, apresentai-vos diante do Senhor por tribos e por clãs."},
{v:20,t:"Samuel fez aproximar todas as tribos de Israel, e a sorte caiu sobre a tribo de Benjamim.",np:1},
{v:21,t:"Fez aproximar a tribo de Benjamim por clãs, e a sorte caiu sobre o clã de Metri, e chegou até Saul, filho de Cis. Procuraram-no, mas ele não foi encontrado.",n:"O sorteio, como no caso de Acã no livro de Josué, deixa a escolha nas mãos de Deus."},
{v:22,t:"Consultaram de novo o Senhor, perguntando se o homem tinha vindo para ali; e o Senhor respondeu: Ei-lo escondido no meio das bagagens."},
{v:23,t:"Correram e tiraram-no dali; e, quando ele se pôs de pé no meio do povo, era mais alto do que todo o povo, dos ombros para cima."},
{v:24,t:"Samuel disse a todo o povo: Vedes aquele que o Senhor escolheu? Não há ninguém como ele em todo o povo. E todo o povo aclamou, gritando: Viva o rei!"},
{v:25,t:"Samuel expôs ao povo o direito da realeza, escreveu-o num livro e depositou-o diante do Senhor. Depois Samuel despediu todo o povo, cada um para a sua casa.",np:1,n:"O direito da realeza não é o direito do rei descrito em 8,11-18, mas o estatuto que limitava o poder do rei, à maneira do Deuteronômio. Depositado diante do Senhor, isto é, no santuário."},
{v:26,t:"Saul também voltou para sua casa, em Gabaá, e foram com ele os homens valentes cujo coração Deus tinha tocado."},
{v:27,t:"Mas alguns perversos disseram: Como poderá este nos salvar? E o desprezaram e não lhe trouxeram presentes. Ele, porém, fingiu não ouvir.",n:"Perversos: à letra filhos de Belial. Um manuscrito de Qumran traz aqui um parágrafo a mais, que conta como Naás, rei dos amonitas, oprimia as tribos da Transjordânia, arrancando-lhes o olho direito; a Nova Vulgata não o inclui."}
];

window.TEXTOS_SEED["1samuel"][11] = [
{s:"Saul liberta Jabes de Galaad"},
{v:1,t:"Naás, o amonita, subiu e começou a atacar Jabes de Galaad. Todos os homens de Jabes disseram a Naás: Faze aliança conosco, e nós te serviremos."},
{v:2,t:"Naás, o amonita, respondeu-lhes: Farei aliança convosco com esta condição: que eu arranque a todos vós o olho direito, e faça de vós a vergonha de todo o Israel.",n:"Sem o olho direito, o homem ficava inútil para a guerra, porque o escudo cobria o olho esquerdo, como explica Flávio Josefo; e a mutilação era uma humilhação para todo o povo."},
{v:3,t:"Os anciãos de Jabes disseram-lhe: Dá-nos sete dias, para enviarmos mensageiros por todo o território de Israel; e, se não houver quem nos defenda, sairemos e nos entregaremos a ti."},
{v:4,t:"Os mensageiros chegaram a Gabaá de Saul e referiram essas palavras aos ouvidos do povo; e todo o povo levantou a voz e chorou.",np:1,n:"Jabes de Galaad tinha laços de sangue com Benjamim: depois da guerra contada no fim dos Juízes, as moças de Jabes foram dadas como mulheres aos benjaminitas."},
{v:5,t:"Nisso Saul vinha do campo, atrás dos bois, e perguntou: Por que o povo está chorando? E contaram-lhe as palavras dos homens de Jabes.",n:"O rei ungido ainda lavra a terra: como os juízes, é chamado do meio da vida comum."},
{v:6,t:"Ao ouvir essas palavras, o Espírito do Senhor apoderou-se de Saul, e a sua ira se inflamou muito."},
{v:7,t:"Tomou uma junta de bois, cortou-os em pedaços e enviou-os por todo o território de Israel, por meio dos mensageiros, dizendo: Assim se fará com os bois de quem não sair atrás de Saul e de Samuel. O temor do Senhor caiu sobre o povo, e saíram como um só homem.",n:"O gesto lembra o do levita que esquartejou a concubina e enviou os pedaços às tribos, contra Benjamim (Juízes 19,29); agora é um benjaminita que convoca as tribos para salvar."},
{v:8,t:"Saul passou-os em revista em Bezec: os filhos de Israel eram trezentos mil, e os homens de Judá, trinta mil.",n:"A menção separada de Judá reflete a divisão posterior entre os reinos de Israel e de Judá."},
{v:9,t:"Saul disse aos mensageiros que tinham vindo: Assim direis aos homens de Jabes de Galaad: Amanhã, quando o sol aquecer, tereis a salvação. Os mensageiros foram e anunciaram isso aos homens de Jabes, que se alegraram,",np:1},
{v:10,t:"e disseram: Amanhã sairemos a vós, e fareis conosco tudo o que vos parecer bem.",n:"Dizem-no aos amonitas, com ironia: fingem render-se, para que o inimigo se descuide."},
{v:11,t:"No dia seguinte, Saul dividiu o povo em três grupos; eles penetraram no meio do acampamento na vigília da manhã e bateram os amonitas até o calor do dia. Os que sobreviveram dispersaram-se, de modo que não ficaram dois deles juntos.",np:1,n:"A vigília da manhã era a última parte da noite, antes da aurora."},
{s:"A realeza renovada em Guilgal"},
{v:12,t:"O povo disse a Samuel: Quem é que dizia: Acaso Saul reinará sobre nós? Entregai esses homens, e nós os mataremos.",np:1},
{v:13,t:"Mas Saul disse: Ninguém será morto neste dia, porque hoje o Senhor realizou a salvação em Israel.",n:"O primeiro ato de Saul depois da vitória é o perdão: a vitória é do Senhor, e não dele."},
{v:14,t:"Samuel disse ao povo: Vinde, vamos a Guilgal, e renovemos ali a realeza."},
{v:15,t:"Todo o povo foi a Guilgal, e ali proclamaram Saul rei diante do Senhor, em Guilgal; ofereceram ali sacrifícios de comunhão diante do Senhor, e Saul e todos os homens de Israel se alegraram muito."}
];
