// =====================================================================
// II Crônicas — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["2cronicas"][1] = [
{s:"Salomão pede a sabedoria"},
{v:1,t:"Salomão, filho de Davi, firmou-se no seu reino; o Senhor seu Deus estava com ele e o engrandeceu sobremaneira.",n:"Os dois livros das Crônicas formavam na origem uma só obra. O segundo começa com o reinado de Salomão, o construtor do templo (capítulos 1 a 9), e depois acompanha só os reis de Judá, da divisão do reino até o exílio e o edito de Ciro."},
{v:2,t:"Salomão falou a todo o Israel, aos chefes de mil e de cem, aos juízes e a todos os príncipes de todo o Israel, chefes das famílias;"},
{v:3,t:"e foi, com toda a assembleia, ao lugar alto de Gabaon, porque ali estava a tenda da reunião de Deus, que Moisés, servo do Senhor, tinha feito no deserto.",n:"Para o cronista, o culto de Salomão em Gabaon é legítimo, porque ali estavam a tenda de Moisés e o altar dos holocaustos (1 Crônicas 16,39; 21,29)."},
{v:4,t:"A arca de Deus, porém, Davi a tinha trazido de Cariat-Iarim para o lugar que lhe tinha preparado, porque lhe tinha armado uma tenda em Jerusalém."},
{v:5,t:"E o altar de bronze feito por Beseleel, filho de Uri, filho de Hur, estava ali, diante da morada do Senhor; e ali Salomão e a assembleia buscaram o Senhor."},
{v:6,t:"Salomão subiu ali ao altar de bronze, diante do Senhor, junto à tenda da reunião, e ofereceu sobre ele mil holocaustos."},
{v:7,t:"Naquela noite, Deus apareceu a Salomão e lhe disse: Pede o que queres que eu te dê.",np:1},
{v:8,t:"Salomão respondeu a Deus: Tu usaste de grande bondade com Davi, meu pai, e me fizeste reinar em seu lugar."},
{v:9,t:"Agora, Senhor Deus, que se cumpra a palavra que deste a Davi, meu pai; porque tu me fizeste reinar sobre um povo numeroso como o pó da terra."},
{v:10,t:"Dá-me, pois, sabedoria e conhecimento, para que eu saiba sair e entrar à frente deste povo; pois quem poderia julgar este teu povo tão grande?"},
{v:11,t:"Deus respondeu a Salomão: Porque foi isto que desejaste no teu coração, e não pediste riquezas, nem bens, nem glória, nem a vida dos teus inimigos, nem mesmo vida longa, mas pediste para ti sabedoria e conhecimento para julgar o meu povo, sobre o qual te fiz reinar,"},
{v:12,t:"a sabedoria e o conhecimento te são dados; e te darei também riquezas, bens e glória, como não tiveram os reis que houve antes de ti, nem terão os que virão depois de ti."},
{v:13,t:"Salomão voltou do lugar alto de Gabaon, de diante da tenda da reunião, para Jerusalém, e reinou sobre Israel."},
{s:"A riqueza de Salomão"},
{v:14,t:"Salomão reuniu carros e cavaleiros: tinha mil e quatrocentos carros e doze mil cavaleiros, que distribuiu pelas cidades dos carros e junto do rei, em Jerusalém.",np:1,n:"Ver 1 Reis 10,26-29. O cronista põe aqui, logo depois do sonho de Gabaon, o cumprimento da promessa de riquezas."},
{v:15,t:"O rei fez que em Jerusalém a prata e o ouro fossem tão comuns como as pedras, e os cedros tão numerosos como os sicômoros que crescem na Sefelá."},
{v:16,t:"Os cavalos de Salomão vinham do Egito e de Cua; os mercadores do rei os compravam em Cua por um preço fixo."},
{v:17,t:"Um carro trazido do Egito custava seiscentos siclos de prata, e um cavalo, cento e cinquenta; e da mesma forma, por meio deles, eram exportados para todos os reis dos heteus e da Síria."},
{v:18,t:"Salomão decidiu construir uma casa ao nome do Senhor e um palácio real para si.",np:1}
];

window.TEXTOS_SEED["2cronicas"][2] = [
{s:"Salomão e Hiram, rei de Tiro"},
{v:1,t:"Salomão recrutou setenta mil carregadores e oitenta mil cortadores de pedra na montanha, e três mil e seiscentos capatazes para dirigi-los."},
{v:2,t:"E Salomão mandou dizer a Hiram, rei de Tiro: Como fizeste com Davi, meu pai, a quem enviaste madeira de cedro para construir uma casa onde habitasse,",np:1},
{v:3,t:"faze também comigo, pois vou construir uma casa ao nome do Senhor meu Deus, para consagrá-la a ele, para queimar diante dele incenso aromático, para a apresentação contínua dos pães e para os holocaustos da manhã e da tarde, dos sábados, das luas novas e das festas do Senhor nosso Deus, como é prescrito para sempre a Israel."},
{v:4,t:"A casa que vou construir será grande, porque o nosso Deus é maior que todos os deuses."},
{v:5,t:"Mas quem será capaz de lhe construir uma casa digna dele, se os céus, e os céus dos céus, não o podem conter? E quem sou eu para lhe construir uma casa, a não ser para queimar incenso diante dele?",n:"A mesma consciência aparece na oração da dedicação (6,18): Deus não cabe num templo; o templo é o lugar onde o povo o encontra e lhe presta culto."},
{v:6,t:"Envia-me, pois, um homem hábil em trabalhar o ouro, a prata, o bronze e o ferro, a púrpura, o carmesim e a púrpura violeta, e que saiba fazer esculturas, para trabalhar com os artesãos que tenho comigo em Judá e em Jerusalém, e que Davi, meu pai, preparou."},
{v:7,t:"Envia-me também do Líbano madeira de cedro, de cipreste e de sândalo, porque sei que os teus servos sabem cortar as árvores do Líbano; e os meus servos estarão com os teus servos,"},
{v:8,t:"para me prepararem madeira em grande quantidade, porque a casa que vou construir será grande e maravilhosa."},
{v:9,t:"Aos teus servos, os lenhadores que cortarem as árvores, darei vinte mil coros de trigo, vinte mil coros de cevada, vinte mil batos de vinho e vinte mil batos de azeite.",n:"Em 1 Reis 5,25, as provisões são para a casa de Hiram; aqui, para os operários."},
{v:10,t:"Hiram, rei de Tiro, respondeu numa carta que enviou a Salomão: Porque o Senhor ama o seu povo, ele te fez rei sobre ele.",np:1},
{v:11,t:"E acrescentou: Bendito seja o Senhor, Deus de Israel, que fez o céu e a terra, porque deu ao rei Davi um filho sábio, dotado de prudência e de inteligência, que vai construir uma casa ao Senhor e um palácio real para si!"},
{v:12,t:"Envio-te, pois, um homem hábil e muito entendido, o mestre Hiram,",n:"À letra, Hiram, meu pai: título de honra de um mestre artesão. Não é o rei, mas o artífice de 1 Reis 7,13-14."},
{v:13,t:"filho de uma mulher das filhas de Dã e de pai tírio. Sabe trabalhar o ouro, a prata, o bronze, o ferro, a pedra e a madeira, a púrpura, a púrpura violeta, o linho fino e o carmesim; sabe fazer toda espécie de esculturas e executar qualquer projeto que se lhe confie, com os teus artesãos e com os artesãos do meu senhor Davi, teu pai.",n:"Em 1 Reis 7,14, a mãe é da tribo de Neftali. Como Ooliab, companheiro de Beseleel no deserto, que também era da tribo de Dã (Êxodo 31,6)."},
{v:14,t:"Agora, pois, o trigo, a cevada, o azeite e o vinho de que falou o meu senhor, que ele os mande aos seus servos."},
{v:15,t:"Nós cortaremos no Líbano toda a madeira de que precisares e a levaremos em jangadas, por mar, até Jope; e tu a farás subir a Jerusalém."},
{v:16,t:"Salomão fez o recenseamento de todos os estrangeiros que viviam na terra de Israel, depois do recenseamento que Davi, seu pai, tinha feito; e encontraram-se cento e cinquenta e três mil e seiscentos.",np:1,n:"O cronista atribui o trabalho forçado aos estrangeiros, e não aos israelitas, como em 1 Reis 5,27; ver também 8,9."},
{v:17,t:"Deles, fez setenta mil carregadores, oitenta mil cortadores de pedra na montanha e três mil e seiscentos capatazes, para fazer trabalhar o povo."}
];

window.TEXTOS_SEED["2cronicas"][3] = [
{s:"A construção do templo"},
{v:1,t:"Salomão começou a construir a casa do Senhor em Jerusalém, no monte Moriá, onde o Senhor tinha aparecido a Davi, seu pai, no lugar que Davi tinha preparado, na eira de Ornã, o jebuseu.",n:"Moriá: o monte onde Abraão ia sacrificar Isaac (Gênesis 22,2). Só aqui a Bíblia identifica o monte do templo com o lugar do sacrifício de Abraão: onde Deus proveu o cordeiro, Israel oferecerá os seus sacrifícios."},
{v:2,t:"Começou a construção no segundo mês do quarto ano do seu reinado."},
{v:3,t:"Estas são as medidas que Salomão estabeleceu para a construção da casa de Deus: sessenta côvados de comprimento, segundo a medida antiga, e vinte côvados de largura.",np:1,n:"A medida antiga: o côvado de antes do exílio, um pouco maior que o côvado comum (Ezequiel 40,5)."},
{v:4,t:"O vestíbulo, na frente, tinha vinte côvados de comprimento, igual à largura da casa, e cento e vinte de altura; e ele o revestiu por dentro de ouro puro.",n:"Cento e vinte côvados, uns sessenta metros: uma torre desproporcionada ao edifício. Talvez se deva ler vinte, como em algumas versões antigas."},
{v:5,t:"Revestiu a sala maior de madeira de cipreste, que cobriu de ouro fino, e fez esculpir nela palmeiras e correntes."},
{v:6,t:"Adornou a casa com pedras preciosas, para lhe dar beleza."},
{v:7,t:"O ouro era ouro de Parvaim; com ele revestiu a casa, as vigas, os umbrais, as paredes e as portas; e esculpiu querubins nas paredes.",n:"Parvaim: região de localização desconhecida, famosa pelo seu ouro."},
{v:8,t:"Fez também a sala do Santo dos Santos: tinha vinte côvados de comprimento, igual à largura da casa, e vinte côvados de largura; e revestiu-a de ouro fino, no valor de seiscentos talentos.",np:1},
{v:9,t:"O peso dos pregos era de cinquenta siclos de ouro. Revestiu também de ouro as salas superiores."},
{v:10,t:"Na sala do Santo dos Santos fez dois querubins, obra de escultura, e revestiu-os de ouro."},
{v:11,t:"As asas dos querubins tinham vinte côvados de comprimento: uma asa do primeiro, de cinco côvados, tocava a parede da casa; e a outra asa, de cinco côvados, tocava a asa do outro querubim."},
{v:12,t:"Do mesmo modo, uma asa do segundo querubim, de cinco côvados, tocava a parede da casa; e a outra asa, de cinco côvados, tocava a asa do primeiro querubim."},
{v:13,t:"As asas destes querubins estendiam-se por vinte côvados. Eles estavam de pé, com o rosto voltado para a sala."},
{v:14,t:"Fez também o véu de púrpura violeta, de púrpura, de carmesim e de linho fino, e bordou nele querubins.",n:"O véu que fechava o Santo dos Santos; 1 Reis fala de portas. No templo reconstruído, será o véu que se rasgará na morte de Jesus (Marcos 15,38)."},
{v:15,t:"Diante da casa fez duas colunas de trinta e cinco côvados de altura, e o capitel que estava no alto de cada uma tinha cinco côvados.",np:1,n:"Em 1 Reis 7,15, dezoito côvados cada uma: talvez aqui se some a altura das duas."},
{v:16,t:"Fez também correntes em forma de colar e pô-las no alto das colunas; e fez cem romãs, que pôs nas correntes."},
{v:17,t:"Ergueu as colunas diante do templo, uma à direita e outra à esquerda; à da direita deu o nome de Jaquin, e à da esquerda, o de Booz."}
];

window.TEXTOS_SEED["2cronicas"][4] = [
{s:"Os objetos do templo"},
{v:1,t:"Fez também um altar de bronze de vinte côvados de comprimento, vinte côvados de largura e dez côvados de altura.",n:"O altar dos holocaustos, no átrio: 1 Reis não o descreve."},
{v:2,t:"Fez também o mar de metal fundido: tinha dez côvados de uma borda à outra, e era redondo; tinha cinco côvados de altura, e um cordão de trinta côvados media a sua circunferência.",np:1},
{v:3,t:"Por baixo dele, ao redor, havia figuras de bois, dez por côvado, que o cercavam em toda a volta; os bois estavam em duas fileiras, fundidos numa só peça com o mar.",n:"Em 1 Reis 7,24, coloquíntidas; as duas palavras hebraicas se parecem."},
{v:4,t:"Assentava sobre doze bois: três voltados para o norte, três para o oeste, três para o sul e três para o leste; o mar estava por cima deles, e as suas ancas ficavam todas para dentro."},
{v:5,t:"A sua espessura era de um palmo, e a borda era como a borda de um cálice, como a flor do lírio aberta. Levava três mil batos.",n:"Em 1 Reis 7,26: dois mil batos."},
{v:6,t:"Fez também dez bacias e pôs cinco à direita e cinco à esquerda, para nelas se lavar o que se oferecia em holocausto; o mar, porém, servia para as abluções dos sacerdotes."},
{v:7,t:"Fez os dez candelabros de ouro, segundo o modelo prescrito, e colocou-os no templo, cinco à direita e cinco à esquerda.",np:1},
{v:8,t:"Fez também dez mesas e colocou-as no templo, cinco à direita e cinco à esquerda; e fez cem bacias de aspersão de ouro."},
{v:9,t:"Fez o átrio dos sacerdotes e o grande átrio, com as suas portas, que revestiu de bronze."},
{v:10,t:"Colocou o mar do lado direito, a sudeste."},
{v:11,t:"Hiram fez também as panelas, as pás e as bacias de aspersão. Assim Hiram terminou a obra que fazia para o rei Salomão na casa de Deus:",np:1},
{v:12,t:"as duas colunas, os dois capitéis arredondados no alto das colunas, as duas redes para cobrir os dois capitéis arredondados no alto das colunas;"},
{v:13,t:"as quatrocentas romãs para as duas redes, duas fileiras de romãs em cada rede, para cobrir os dois capitéis arredondados no alto das colunas;"},
{v:14,t:"fez também as bases, e as bacias sobre as bases;"},
{v:15,t:"o mar, único, e os doze bois debaixo dele;"},
{v:16,t:"as panelas, as pás e os garfos. Todos esses objetos, o mestre Hiram os fez de bronze polido para o rei Salomão, para a casa do Senhor."},
{v:17,t:"O rei os fundiu na planície do Jordão, em moldes de argila, entre Sucot e Sareda."},
{v:18,t:"Salomão fez todos esses objetos em tão grande quantidade que não se pôde calcular o peso do bronze."},
{v:19,t:"Salomão fez também todos os objetos da casa de Deus: o altar de ouro e as mesas sobre as quais se colocavam os pães da proposição;",np:1},
{v:20,t:"os candelabros e as suas lâmpadas de ouro puro, para arderem, segundo o rito, diante do Debir;"},
{v:21,t:"as flores, as lâmpadas e as tenazes de ouro, do ouro mais puro;"},
{v:22,t:"as facas, as bacias de aspersão, as colheres e os incensórios de ouro puro. E, na entrada da casa, as portas interiores do Santo dos Santos e as portas da sala do templo eram de ouro."}
];

window.TEXTOS_SEED["2cronicas"][5] = [
{s:"A arca é levada para o templo"},
{v:1,t:"Assim ficou terminada toda a obra que Salomão fez para a casa do Senhor. E Salomão trouxe as coisas que Davi, seu pai, tinha consagrado: a prata, o ouro e todos os objetos, e os depositou nos tesouros da casa de Deus."},
{v:2,t:"Então Salomão reuniu em Jerusalém os anciãos de Israel, todos os chefes das tribos e os chefes das famílias dos filhos de Israel, para trazer da Cidade de Davi, isto é, de Sião, a arca da aliança do Senhor.",np:1},
{v:3,t:"Todos os homens de Israel reuniram-se junto do rei na festa, que é no sétimo mês.",n:"A festa das Tendas, a grande festa da colheita, no outono."},
{v:4,t:"Vieram todos os anciãos de Israel, e os levitas levaram a arca.",n:"Em 1 Reis 8,3, os sacerdotes. O cronista, fiel à Lei (Deuteronômio 10,8; 1 Crônicas 15,2), atribui aos levitas o transporte da arca."},
{v:5,t:"Levaram a arca, a tenda da reunião e todos os objetos sagrados que havia na tenda: os sacerdotes levitas os levavam."},
{v:6,t:"O rei Salomão e toda a assembleia de Israel, reunida junto dele diante da arca, sacrificavam ovelhas e bois em quantidade tal que não se podia contar nem calcular."},
{v:7,t:"Os sacerdotes introduziram a arca da aliança do Senhor no seu lugar, no Debir do templo, no Santo dos Santos, debaixo das asas dos querubins.",np:1},
{v:8,t:"Os querubins estendiam as asas sobre o lugar da arca, e cobriam por cima a arca e os seus varais."},
{v:9,t:"Os varais eram tão compridos que as suas pontas se viam diante do Debir, mas não se viam de fora; e a arca está lá até o dia de hoje.",n:"Até o dia de hoje: o cronista copia a frase da sua fonte, escrita antes da destruição do templo."},
{v:10,t:"Na arca não havia outra coisa senão as duas tábuas que Moisés ali tinha posto no Horeb, quando o Senhor fez aliança com os filhos de Israel, ao saírem do Egito."},
{s:"A glória do Senhor enche o templo"},
{v:11,t:"Quando os sacerdotes saíram do santuário — pois todos os sacerdotes que ali se encontravam se tinham santificado, sem observar a ordem das classes;",np:1},
{v:12,t:"e os levitas cantores, todos, os de Asaf, de Hemã e de Iditun, com os seus filhos e os seus irmãos, vestidos de linho fino, estavam de pé a oriente do altar, com címbalos, harpas e cítaras, e com eles cento e vinte sacerdotes que tocavam as trombetas —"},
{v:13,t:"quando todos juntos, os que tocavam as trombetas e os cantores, fizeram ouvir em uníssono uma só voz para louvar e dar graças ao Senhor, e ergueram a voz com as trombetas, os címbalos e os outros instrumentos de música, louvando o Senhor: Porque ele é bom, porque é eterna a sua misericórdia, então a casa de Deus encheu-se de uma nuvem,",n:"O cronista acrescenta a 1 Reis 8 o louvor dos levitas: é quando o povo canta a misericórdia de Deus que a glória desce sobre o templo."},
{v:14,t:"e os sacerdotes não puderam ficar ali para fazer o seu serviço, por causa da nuvem, porque a glória do Senhor enchia a casa de Deus."}
];

window.TEXTOS_SEED["2cronicas"][6] = [
{s:"O discurso de Salomão ao povo"},
{v:1,t:"Então Salomão disse: O Senhor disse que habitaria na nuvem escura;",n:"Deus habita na obscuridade: está presente, mas não se deixa ver."},
{v:2,t:"e eu te construí uma casa para morada, um lugar onde habites para sempre."},
{v:3,t:"Depois o rei voltou-se e abençoou toda a assembleia de Israel, enquanto toda a assembleia de Israel estava de pé,",np:1},
{v:4,t:"e disse: Bendito seja o Senhor, Deus de Israel, que falou com a sua boca a Davi, meu pai, e com a sua mão cumpriu o que dissera:"},
{v:5,t:"Desde o dia em que tirei do Egito o meu povo, não escolhi cidade alguma, entre todas as tribos de Israel, para nela se construir uma casa onde estivesse o meu nome, nem escolhi homem algum para ser chefe do meu povo Israel;"},
{v:6,t:"mas escolhi Jerusalém, para que ali estivesse o meu nome, e escolhi Davi, para que estivesse à frente do meu povo Israel.",n:"O texto de 1 Reis 8,16 parece ter perdido uma parte na cópia; o cronista a conserva: a escolha de Jerusalém e a de Davi andam juntas."},
{v:7,t:"Davi, meu pai, desejou construir uma casa ao nome do Senhor, Deus de Israel;"},
{v:8,t:"mas o Senhor disse a Davi, meu pai: Pensaste no teu coração em construir uma casa ao meu nome, e fizeste bem em pensar nisso;"},
{v:9,t:"mas não serás tu que construirás a casa, e sim o teu filho, que sairá das tuas entranhas: ele construirá a casa ao meu nome."},
{v:10,t:"O Senhor cumpriu a palavra que tinha dito: eu sucedi a Davi, meu pai, e sentei-me no trono de Israel, como o Senhor tinha dito, e construí a casa ao nome do Senhor, Deus de Israel."},
{v:11,t:"E ali coloquei a arca, onde está a aliança que o Senhor fez com os filhos de Israel."},
{s:"A oração de Salomão"},
{v:12,t:"Salomão pôs-se diante do altar do Senhor, em presença de toda a assembleia de Israel, e estendeu as mãos.",np:1},
{v:13,t:"Pois Salomão tinha feito um estrado de bronze, de cinco côvados de comprimento, cinco côvados de largura e três côvados de altura, e o tinha colocado no meio do átrio; subiu nele, ajoelhou-se diante de toda a assembleia de Israel, estendeu as mãos para o céu",n:"O estrado de bronze é um pormenor próprio do cronista: o rei ora no átrio, diante do povo, e não no santuário, reservado aos sacerdotes."},
{v:14,t:"e disse: Senhor, Deus de Israel, não há Deus como tu, nem no céu nem na terra; tu guardas a aliança e a misericórdia para com os teus servos que andam diante de ti de todo o coração."},
{v:15,t:"Cumpriste para com o teu servo Davi, meu pai, o que lhe tinhas dito: o que prometeste com a tua boca, cumpriste com a tua mão, como hoje se vê."},
{v:16,t:"Agora, pois, Senhor, Deus de Israel, guarda para o teu servo Davi, meu pai, o que lhe prometeste, dizendo: Não te faltará diante de mim um descendente que se sente no trono de Israel, contanto que os teus filhos vigiem o seu caminho, andando na minha lei como tu andaste diante de mim.",n:"Andando na minha lei: em 1 Reis 8,25, andando diante de mim. Para o cronista, a fidelidade se mede pela Lei."},
{v:17,t:"Agora, pois, Senhor, Deus de Israel, cumpra-se a palavra que disseste ao teu servo Davi!"},
{v:18,t:"Mas será que Deus habitará verdadeiramente com os homens na terra? Se os céus e os céus dos céus não te podem conter, quanto menos esta casa que construí!",np:1},
{v:19,t:"Mas volta-te para a oração e para a súplica do teu servo, Senhor meu Deus; ouve o clamor e a oração que o teu servo te dirige,"},
{v:20,t:"para que os teus olhos estejam abertos dia e noite sobre esta casa, sobre o lugar onde prometeste pôr o teu nome; para que ouças a oração que o teu servo fizer neste lugar."},
{v:21,t:"Ouve as súplicas do teu servo e do teu povo Israel, quando orarem neste lugar; ouve do lugar da tua morada, do céu; ouve e perdoa."},
{v:22,t:"Se alguém pecar contra o seu próximo, e lhe for imposto um juramento que o obrigue, e ele vier jurar diante do teu altar, nesta casa,",np:1},
{v:23,t:"ouve do céu e age; julga os teus servos, retribuindo ao culpado, fazendo recair sobre a sua cabeça o seu procedimento, e justificando o inocente, dando-lhe segundo a sua justiça."},
{v:24,t:"Se o teu povo Israel for derrotado pelo inimigo, por ter pecado contra ti, e depois se converter, louvar o teu nome, orar e suplicar diante de ti nesta casa,",np:1},
{v:25,t:"ouve do céu, perdoa o pecado do teu povo Israel e faze-os voltar à terra que deste a eles e aos seus pais."},
{v:26,t:"Se o céu se fechar e não houver chuva, porque pecaram contra ti, e eles orarem neste lugar, louvarem o teu nome e se converterem do seu pecado, por causa da aflição que lhes enviaste,",np:1},
{v:27,t:"ouve do céu e perdoa o pecado dos teus servos e do teu povo Israel, ensinando-lhes o bom caminho por onde devem andar; e manda a chuva sobre a tua terra, que deste ao teu povo como herança."},
{v:28,t:"Se houver na terra fome ou peste, ferrugem ou mangra, gafanhotos ou larvas; se o inimigo o oprimir, sitiando as suas cidades; qualquer praga, qualquer doença,",np:1},
{v:29,t:"toda oração, toda súplica que fizer qualquer homem do teu povo Israel, reconhecendo cada um a sua chaga e a sua dor e estendendo as mãos para esta casa,"},
{v:30,t:"ouve do céu, do lugar da tua morada, perdoa e dá a cada um segundo todos os seus caminhos, tu que conheces o seu coração, porque só tu conheces o coração dos filhos dos homens,"},
{v:31,t:"para que te temam e andem nos teus caminhos todos os dias que viverem sobre a terra que deste aos nossos pais."},
{v:32,t:"Também o estrangeiro, que não é do teu povo Israel, quando vier de uma terra distante por causa do teu grande nome, da tua mão forte e do teu braço estendido, quando vier orar nesta casa,",np:1,n:"A oração abre-se aos estrangeiros: o templo de Israel será casa de oração para todos os povos (Isaías 56,7; Marcos 11,17)."},
{v:33,t:"ouve do céu, do lugar da tua morada, e faze tudo o que o estrangeiro te pedir, para que todos os povos da terra conheçam o teu nome e te temam, como o teu povo Israel, e saibam que o teu nome é invocado sobre esta casa que construí."},
{v:34,t:"Se o teu povo sair à guerra contra os seus inimigos, pelo caminho por onde os enviares, e orarem a ti voltados para esta cidade que escolheste e para a casa que construí ao teu nome,",np:1},
{v:35,t:"ouve do céu a sua oração e a sua súplica e faze-lhes justiça."},
{v:36,t:"Se pecarem contra ti — pois não há homem que não peque — e tu, irritado, os entregares aos seus inimigos, e estes os levarem cativos para uma terra distante ou próxima;",np:1},
{v:37,t:"se, na terra para onde foram levados cativos, eles caírem em si e se converterem, e te suplicarem na terra do seu cativeiro, dizendo: Pecamos, agimos mal, fomos ímpios;"},
{v:38,t:"se voltarem a ti de todo o coração e de toda a alma, na terra do cativeiro para onde os levaram, e orarem voltados para a terra que deste aos seus pais, para a cidade que escolheste e para a casa que construí ao teu nome,"},
{v:39,t:"ouve do céu, do lugar da tua morada, a sua oração e as suas súplicas, faze-lhes justiça e perdoa ao teu povo, que pecou contra ti."},
{v:40,t:"Agora, meu Deus, que os teus olhos estejam abertos e os teus ouvidos atentos à oração feita neste lugar.",np:1},
{v:41,t:"Agora, pois, levanta-te, Senhor Deus, e vem para o teu repouso, tu e a arca do teu poder. Que os teus sacerdotes, Senhor Deus, se vistam de salvação, e os teus fiéis se alegrem no bem.",n:"Os dois últimos versículos citam o Salmo 132,8-10, em lugar do final de 1 Reis 8,50-53: o cronista termina a oração com a arca e com Davi."},
{v:42,t:"Senhor Deus, não rejeites a face do teu ungido; lembra-te dos favores prometidos a Davi, teu servo.",n:"Os favores prometidos a Davi: a aliança eterna de Isaías 55,3. A oração do templo termina pedindo o cumprimento da promessa messiânica."}
];

window.TEXTOS_SEED["2cronicas"][7] = [
{s:"A dedicação do templo"},
{v:1,t:"Quando Salomão acabou de orar, desceu fogo do céu e consumiu o holocausto e os sacrifícios, e a glória do Senhor encheu a casa.",n:"O fogo do céu, como na inauguração do altar do deserto (Levítico 9,24) e no altar de Davi (1 Crônicas 21,26): Deus aceita o templo."},
{v:2,t:"Os sacerdotes não podiam entrar na casa do Senhor, porque a glória do Senhor enchia a casa do Senhor."},
{v:3,t:"Todos os filhos de Israel, vendo descer o fogo e a glória do Senhor sobre a casa, prostraram-se com o rosto em terra, sobre o pavimento, adoraram e louvaram o Senhor: Porque ele é bom, porque é eterna a sua misericórdia."},
{v:4,t:"O rei e todo o povo ofereceram sacrifícios diante do Senhor.",np:1},
{v:5,t:"O rei Salomão ofereceu em sacrifício vinte e dois mil bois e cento e vinte mil ovelhas. Assim o rei e todo o povo dedicaram a casa de Deus."},
{v:6,t:"Os sacerdotes estavam nos seus postos, e os levitas com os instrumentos de música do Senhor, que o rei Davi tinha feito para louvar o Senhor, cantando os hinos de Davi: Porque é eterna a sua misericórdia. Os sacerdotes tocavam as trombetas diante deles, e todo o Israel estava de pé."},
{v:7,t:"Salomão consagrou o meio do átrio que ficava diante da casa do Senhor; porque ali ofereceu os holocaustos e a gordura dos sacrifícios de comunhão, uma vez que o altar de bronze que Salomão tinha feito não podia conter os holocaustos, as oblações e a gordura."},
{v:8,t:"Naquele tempo Salomão celebrou a festa durante sete dias, e com ele todo o Israel, uma assembleia muito grande, vinda desde a entrada de Emat até a torrente do Egito.",np:1},
{v:9,t:"No oitavo dia fizeram uma assembleia solene, porque tinham celebrado a dedicação do altar durante sete dias, e a festa durante sete dias.",n:"Sete dias de dedicação, seguidos dos sete dias da festa das Tendas, que terminava com uma assembleia solene no oitavo dia (Levítico 23,36)."},
{v:10,t:"No vigésimo terceiro dia do sétimo mês, despediu o povo para as suas tendas, alegre e de coração contente pelo bem que o Senhor tinha feito a Davi, a Salomão e a Israel, seu povo."},
{s:"O Senhor aparece de novo a Salomão"},
{v:11,t:"Salomão terminou a casa do Senhor e o palácio real, e realizou com êxito tudo o que tinha no coração fazer na casa do Senhor e no seu palácio.",np:1},
{v:12,t:"O Senhor apareceu a Salomão de noite e lhe disse: Ouvi a tua oração e escolhi para mim este lugar como casa de sacrifício."},
{v:13,t:"Se eu fechar o céu e não houver chuva, se eu ordenar aos gafanhotos que devorem a terra, se eu mandar a peste contra o meu povo,"},
{v:14,t:"e o meu povo, sobre o qual é invocado o meu nome, se humilhar, orar, buscar a minha face e se converter dos seus maus caminhos, eu o ouvirei do céu, perdoarei o seu pecado e curarei a sua terra.",n:"Resposta à oração de Salomão, própria do cronista: humilhar-se, orar, buscar a face de Deus e converter-se são o caminho da cura. É o critério com que ele julgará os reis de Judá."},
{v:15,t:"Agora os meus olhos estarão abertos e os meus ouvidos atentos à oração feita neste lugar;"},
{v:16,t:"porque agora escolhi e consagrei esta casa, para que o meu nome esteja nela para sempre; e os meus olhos e o meu coração estarão ali todos os dias."},
{v:17,t:"Quanto a ti, se andares diante de mim como andou Davi, teu pai, fazendo tudo o que te ordenei e guardando os meus estatutos e as minhas normas,",np:1},
{v:18,t:"firmarei o trono do teu reino, como prometi a Davi, teu pai, dizendo: Não te faltará um homem que governe Israel.",n:"Que governe Israel: eco de Miqueias 5,1, a profecia do chefe que sairá de Belém."},
{v:19,t:"Mas, se vos afastardes e abandonardes os meus estatutos e os meus mandamentos que vos propus, e fordes servir a outros deuses e adorá-los,"},
{v:20,t:"eu vos arrancarei da minha terra que vos dei, rejeitarei de diante de mim esta casa que consagrei ao meu nome, e farei dela objeto de provérbio e de zombaria entre todos os povos."},
{v:21,t:"E esta casa, que era tão elevada, será motivo de espanto para todos os que passarem junto dela, e dirão: Por que fez o Senhor isto a esta terra e a esta casa?"},
{v:22,t:"E responderão: Porque abandonaram o Senhor, Deus de seus pais, que os tirou da terra do Egito, e se apegaram a outros deuses, os adoraram e os serviram; por isso ele fez vir sobre eles todo este mal."}
];

window.TEXTOS_SEED["2cronicas"][8] = [
{s:"As obras de Salomão"},
{v:1,t:"Ao fim de vinte anos, durante os quais Salomão construiu a casa do Senhor e o seu palácio,"},
{v:2,t:"Salomão reconstruiu as cidades que Hiram lhe tinha dado e estabeleceu nelas os filhos de Israel.",n:"Em 1 Reis 9,11-13, é Salomão quem dá cidades a Hiram. O cronista não conta que o rei de Israel tenha cedido território da terra santa."},
{v:3,t:"Salomão foi a Emat-Soba e apoderou-se dela.",n:"A única campanha militar atribuída a Salomão, no território do antigo reino de Soba, ao norte."},
{v:4,t:"Reconstruiu Tadmor, no deserto, e todas as cidades de armazéns que construíra em Emat.",n:"Tadmor, a futura Palmira, oásis no deserto da Síria. Em 1 Reis 9,18 se lê Tamar."},
{v:5,t:"Reconstruiu Bet-Horon de cima e Bet-Horon de baixo, cidades fortificadas, com muralhas, portas e ferrolhos;"},
{v:6,t:"e também Baalat, e todas as cidades de armazéns que pertenciam a Salomão, todas as cidades dos carros e as cidades dos cavalos, e tudo o que Salomão quis construir em Jerusalém, no Líbano e em todo o território do seu domínio."},
{v:7,t:"Todo o povo que restava dos heteus, dos amorreus, dos ferezeus, dos heveus e dos jebuseus, que não eram de Israel,",np:1},
{v:8,t:"os seus descendentes, que tinham ficado depois deles na terra, e que os filhos de Israel não tinham exterminado, Salomão sujeitou-os ao trabalho forçado, até hoje."},
{v:9,t:"Mas dos filhos de Israel Salomão não fez escravo nenhum para as suas obras: eram os seus guerreiros, os chefes dos seus oficiais e os comandantes dos seus carros e da sua cavalaria."},
{v:10,t:"Os chefes dos intendentes do rei Salomão eram duzentos e cinquenta; tinham autoridade sobre o povo.",n:"1 Reis 9,23 diz quinhentos e cinquenta."},
{v:11,t:"Salomão fez subir a filha do faraó da Cidade de Davi para a casa que lhe tinha construído, porque dizia: A minha mulher não deve habitar na casa de Davi, rei de Israel, porque são santos os lugares onde entrou a arca do Senhor.",np:1,n:"Explicação própria do cronista: uma estrangeira não devia morar junto dos lugares santificados pela arca."},
{v:12,t:"Então Salomão ofereceu holocaustos ao Senhor sobre o altar do Senhor que tinha construído diante do vestíbulo,",np:1},
{v:13,t:"segundo o que era prescrito para cada dia, conforme o mandamento de Moisés: nos sábados, nas luas novas e nas festas, três vezes por ano: na festa dos Pães sem Fermento, na festa das Semanas e na festa das Tendas."},
{v:14,t:"Segundo as disposições de Davi, seu pai, estabeleceu as classes dos sacerdotes no seu serviço, e os levitas nos seus ofícios, para louvar e servir diante dos sacerdotes, segundo o que era prescrito para cada dia, e os porteiros, segundo as suas classes, em cada porta; porque assim o tinha ordenado Davi, homem de Deus."},
{v:15,t:"Não se afastaram em nada das ordens do rei a respeito dos sacerdotes e dos levitas, nem a respeito dos tesouros."},
{v:16,t:"Assim foi executada toda a obra de Salomão, desde o dia em que foram lançados os alicerces da casa do Senhor até o dia em que foi terminada. A casa do Senhor ficou concluída."},
{v:17,t:"Então Salomão foi a Asion-Gaber e a Elat, na costa do mar Vermelho, na terra de Edom.",np:1},
{v:18,t:"Hiram mandou-lhe, por meio dos seus servos, navios e marinheiros que conheciam o mar; e eles foram com os servos de Salomão a Ofir, tomaram de lá quatrocentos e cinquenta talentos de ouro e os trouxeram ao rei Salomão.",n:"1 Reis 9,28 diz quatrocentos e vinte."}
];

window.TEXTOS_SEED["2cronicas"][9] = [
{s:"A visita da rainha de Sabá"},
{v:1,t:"A rainha de Sabá ouviu falar da fama de Salomão e veio a Jerusalém pô-lo à prova com enigmas, com um séquito muito numeroso, com camelos carregados de perfumes, de ouro em grande quantidade e de pedras preciosas. Foi ter com Salomão e falou-lhe de tudo o que tinha no coração.",n:"Sabá ficava no sul da Arábia. Jesus lembrará a rainha do Sul, que veio dos confins da terra para ouvir a sabedoria de Salomão (Mateus 12,42)."},
{v:2,t:"Salomão respondeu a todas as suas perguntas: não houve nada tão oculto que Salomão não lhe explicasse."},
{v:3,t:"Quando a rainha de Sabá viu a sabedoria de Salomão, o palácio que ele tinha construído,"},
{v:4,t:"as iguarias da sua mesa, os aposentos dos seus oficiais, o serviço dos seus criados e as suas librés, os seus copeiros e as librés deles, e os holocaustos que ele oferecia na casa do Senhor, ficou sem fôlego,"},
{v:5,t:"e disse ao rei: Era verdade o que ouvi na minha terra acerca de ti e da tua sabedoria!"},
{v:6,t:"Eu não acreditava no que me contavam, até que vim e vi com os meus próprios olhos: e não me tinham contado nem a metade da grandeza da tua sabedoria! Superas a fama que ouvi."},
{v:7,t:"Felizes os teus homens, felizes estes teus servos, que estão sempre diante de ti e ouvem a tua sabedoria!"},
{v:8,t:"Bendito seja o Senhor teu Deus, que se agradou de ti e te pôs no seu trono, como rei para o Senhor teu Deus! Porque o teu Deus ama Israel e quer mantê-lo para sempre, constituiu-te rei sobre ele, para praticares o direito e a justiça.",n:"No seu trono: em 1 Reis 10,9, no trono de Israel. Para o cronista, o trono de Israel é o trono de Deus (1 Crônicas 28,5; 29,23)."},
{v:9,t:"Ela deu ao rei cento e vinte talentos de ouro, grande quantidade de perfumes e pedras preciosas. Nunca houve perfumes como os que a rainha de Sabá deu ao rei Salomão."},
{v:10,t:"Também os servos de Hiram e os servos de Salomão, que traziam ouro de Ofir, trouxeram madeira de sândalo e pedras preciosas.",np:1},
{v:11,t:"Com a madeira de sândalo o rei fez escadas para a casa do Senhor e para o palácio real, e cítaras e harpas para os cantores. Nunca se tinha visto coisa igual na terra de Judá."},
{v:12,t:"O rei Salomão deu à rainha de Sabá tudo o que ela desejou e pediu, mais do que ela tinha trazido ao rei. Depois ela voltou para a sua terra com os seus servos."},
{s:"A riqueza e a sabedoria de Salomão"},
{v:13,t:"O peso do ouro que chegava a Salomão cada ano era de seiscentos e sessenta e seis talentos de ouro,",np:1},
{v:14,t:"sem contar o que traziam os mercadores e os negociantes; e todos os reis da Arábia e os governadores do país traziam ouro e prata a Salomão."},
{v:15,t:"O rei Salomão fez duzentos escudos grandes de ouro batido, empregando seiscentos siclos de ouro batido em cada escudo;"},
{v:16,t:"e trezentos escudos pequenos de ouro batido, empregando trezentos siclos de ouro em cada escudo; e o rei os pôs na Casa da Floresta do Líbano."},
{v:17,t:"O rei fez também um grande trono de marfim e revestiu-o de ouro puro."},
{v:18,t:"O trono tinha seis degraus e um escabelo de ouro, presos ao trono; havia braços de um lado e de outro do assento, e dois leões de pé junto dos braços;"},
{v:19,t:"e doze leões estavam de pé sobre os seis degraus, de um lado e de outro. Nada de semelhante se fez em reino algum."},
{v:20,t:"Todas as taças em que o rei Salomão bebia eram de ouro, e todos os utensílios da Casa da Floresta do Líbano eram de ouro puro; a prata não tinha valor algum no tempo de Salomão."},
{v:21,t:"Porque os navios do rei iam a Társis com os servos de Hiram; e de três em três anos os navios de Társis voltavam trazendo ouro, prata, marfim, macacos e pavões.",n:"O cronista entende navios de Társis como navios que iam a Társis, no extremo ocidente; mas a frota partia do mar Vermelho (8,17-18). Em 1 Reis 10,22, a expressão designa navios de alto-mar."},
{v:22,t:"Assim o rei Salomão superou todos os reis da terra em riqueza e em sabedoria.",np:1},
{v:23,t:"Todos os reis da terra desejavam ver o rosto de Salomão, para ouvir a sabedoria que Deus lhe tinha posto no coração."},
{v:24,t:"E cada um lhe trazia o seu presente, todos os anos: objetos de prata e de ouro, vestes, armas, perfumes, cavalos e mulas."},
{v:25,t:"Salomão tinha quatro mil estrebarias para os cavalos e os carros, e doze mil cavaleiros, que distribuiu pelas cidades dos carros e junto do rei, em Jerusalém.",n:"1 Reis 5,6 diz quarenta mil estrebarias."},
{v:26,t:"Ele dominava sobre todos os reis, desde o rio Eufrates até a terra dos filisteus e até a fronteira do Egito.",n:"É a extensão da terra prometida a Abraão (Gênesis 15,18)."},
{v:27,t:"O rei fez que em Jerusalém a prata fosse tão comum como as pedras, e os cedros tão numerosos como os sicômoros que crescem na Sefelá."},
{v:28,t:"Traziam cavalos para Salomão do Egito e de todos os países."},
{s:"A morte de Salomão"},
{v:29,t:"O resto dos feitos de Salomão, os primeiros e os últimos, está escrito na história do profeta Natã, na profecia de Aías, de Silo, e nas visões do vidente Ado a respeito de Jeroboão, filho de Nabat.",np:1,n:"O cronista não fala das mulheres estrangeiras de Salomão nem da sua idolatria na velhice (1 Reis 11): o construtor do templo permanece, para ele, um rei ideal."},
{v:30,t:"Salomão reinou em Jerusalém sobre todo o Israel quarenta anos."},
{v:31,t:"Salomão adormeceu com seus pais e foi sepultado na Cidade de Davi, seu pai; e seu filho Roboão reinou em seu lugar."}
];

window.TEXTOS_SEED["2cronicas"][10] = [
{s:"A divisão do reino"},
{v:1,t:"Roboão foi a Siquém, porque todo o Israel se tinha reunido ali para o proclamar rei."},
{v:2,t:"Jeroboão, filho de Nabat, que estava no Egito, para onde tinha fugido do rei Salomão, soube disso e voltou do Egito.",n:"O cronista supõe conhecida a história de Jeroboão e da profecia de Aías (1 Reis 11,26-40)."},
{v:3,t:"Mandaram chamá-lo, e Jeroboão veio com todo o Israel; e disseram a Roboão:"},
{v:4,t:"Teu pai tornou pesado o nosso jugo; alivia agora a dura servidão de teu pai e o jugo pesado que ele pôs sobre nós, e nós te serviremos."},
{v:5,t:"Ele lhes respondeu: Voltai a mim daqui a três dias. E o povo se retirou."},
{v:6,t:"O rei Roboão consultou os anciãos que tinham estado a serviço de Salomão, seu pai, durante a vida dele, e perguntou-lhes: Que me aconselhais responder a este povo?",np:1},
{v:7,t:"Eles lhe disseram: Se fores bondoso para com este povo, se lhes agradares e lhes falares com boas palavras, eles serão teus servos para sempre.",n:"Em 1 Reis 12,7: se hoje te fizeres servo deste povo. O cronista suaviza a expressão."},
{v:8,t:"Mas ele rejeitou o conselho que os anciãos lhe tinham dado e consultou os jovens que tinham crescido com ele e que estavam a seu serviço,"},
{v:9,t:"e perguntou-lhes: Que me aconselhais responder a este povo, que me disse: Alivia o jugo que teu pai pôs sobre nós?"},
{v:10,t:"Os jovens que tinham crescido com ele responderam: Assim falarás a este povo, que te disse: Teu pai tornou pesado o nosso jugo, alivia-o tu; assim lhes dirás: O meu dedo mínimo é mais grosso que a cintura de meu pai."},
{v:11,t:"Meu pai vos impôs um jugo pesado, e eu o tornarei ainda mais pesado; meu pai vos castigou com açoites, e eu vos castigarei com escorpiões."},
{v:12,t:"Ao terceiro dia, Jeroboão e todo o povo vieram ter com Roboão, como o rei tinha dito: Voltai a mim daqui a três dias.",np:1},
{v:13,t:"O rei respondeu-lhes duramente; o rei Roboão rejeitou o conselho dos anciãos"},
{v:14,l:["e falou-lhes segundo o conselho dos jovens:","Meu pai tornou pesado o vosso jugo,","e eu o tornarei ainda mais pesado;","meu pai vos castigou com açoites,","e eu vos castigarei com escorpiões."]},
{v:15,t:"O rei não atendeu o povo, porque Deus tinha disposto assim, para cumprir a palavra que o Senhor tinha dito a Jeroboão, filho de Nabat, por meio de Aías, de Silo."},
{v:16,l:["Todo o Israel, vendo que o rei não os queria ouvir, respondeu ao rei:","Que parte temos nós com Davi?","Que herança com o filho de Jessé?","Às tuas tendas, Israel!","Agora, Davi, cuida da tua casa!","E todo o Israel foi para as suas tendas."]},
{v:17,t:"Quanto aos filhos de Israel que moravam nas cidades de Judá, Roboão reinou sobre eles.",np:1},
{v:18,t:"O rei Roboão enviou Adoram, encarregado dos trabalhos forçados, mas os filhos de Israel o apedrejaram, e ele morreu. Então o rei Roboão subiu depressa ao seu carro e fugiu para Jerusalém.",n:"Adoram é o Adoniram de 1 Reis 12,18."},
{v:19,t:"Assim Israel se separou da casa de Davi, até hoje.",n:"Para o cronista, o reino do Norte, separado da casa de Davi e do templo, afastou-se do caminho de Deus; só falará dele quando a sua história se cruzar com a de Judá."}
];
