// =====================================================================
// II Macabeus — tradução do grego, cotejado com a Nova Vulgata (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["2macabeus"][1] = [
{s:"Primeira carta aos judeus do Egito"},
{v:1,t:"Aos irmãos judeus que estão no Egito, saudações! Os irmãos judeus que estão em Jerusalém e na região da Judeia vos desejam uma paz feliz.",n:"O segundo livro dos Macabeus não continua o primeiro: conta de novo, com outro estilo e outro propósito, os fatos de 175 a 160 a.C., até a vitória de Judas sobre Nicanor. É o resumo de uma obra maior de Jasão de Cirene (2,23), escrito em grego, e começa com duas cartas dos judeus de Jerusalém aos do Egito (1,1–9 e 1,10–2,18), que os convidam a celebrar a festa da purificação do templo."},
{v:2,t:"Que Deus vos faça o bem e se lembre da sua aliança com Abraão, Isaac e Jacó, seus servos fiéis;",np:1},
{v:3,t:"que dê a todos vós um coração para adorá-lo e fazer a sua vontade com coração generoso e alma disposta;"},
{v:4,t:"que abra o vosso coração à sua Lei e aos seus preceitos e vos dê a paz;"},
{v:5,t:"que ouça as vossas orações, se reconcilie convosco e não vos abandone no tempo da desgraça."},
{v:6,t:"Nós, aqui, estamos rezando por vós."},
{v:7,t:"No reinado de Demétrio, no ano cento e sessenta e nove, nós, judeus, vos escrevemos, no auge da tribulação que caiu sobre nós nestes anos, desde que Jasão e os seus partidários traíram a terra santa e o reino:",n:"Ano cento e sessenta e nove: 143 a.C. Jasão é o sumo sacerdote helenizante do capítulo 4."},
{v:8,t:"incendiaram o pórtico e derramaram sangue inocente; mas nós suplicamos ao Senhor e fomos ouvidos; oferecemos sacrifícios e flor de farinha, acendemos as lâmpadas e apresentamos os pães."},
{v:9,t:"Agora, pois, celebrai os dias da festa das Tendas do mês de Casleu,",n:"A festa das Tendas do mês de Casleu é a festa da Dedicação (1 Macabeus 4,59), que se celebrava durante oito dias, como a das Tendas (10,6)."},
{s:"Segunda carta: a morte de Antíoco"},
{v:10,t:"no ano cento e oitenta e oito. Os que estão em Jerusalém e na Judeia, o conselho dos anciãos e Judas saúdam e desejam boa saúde a Aristóbulo, preceptor do rei Ptolomeu, que é da família dos sacerdotes ungidos, e aos judeus que estão no Egito.",n:"Ano cento e oitenta e oito: 124 a.C.; com esta data termina a primeira carta. A segunda se apresenta como escrita em 164 a.C., logo depois da purificação do templo. Aristóbulo era um filósofo judeu de Alexandria, conselheiro de Ptolomeu VI."},
{v:11,t:"Salvos por Deus de grandes perigos, nós lhe damos muitas graças, pois combatemos contra o rei;"},
{v:12,t:"foi ele quem expulsou os que combatiam contra a cidade santa."},
{v:13,t:"Quando o chefe chegou à Pérsia, com um exército que parecia invencível, foram trucidados no templo de Naneia, graças a um ardil dos sacerdotes de Naneia.",n:"Naneia era uma deusa venerada na Mesopotâmia e na Pérsia. Este relato da morte de Antíoco Epífanes difere do de 9,1–29 e do de 1 Macabeus 6,1–16."},
{v:14,t:"Antíoco foi àquele lugar com os seus amigos, a pretexto de desposar a deusa, para receber como dote as riquezas do templo."},
{v:15,t:"Os sacerdotes de Naneia expuseram as riquezas, e ele entrou com poucos acompanhantes no recinto do santuário; mal Antíoco entrou, os sacerdotes fecharam o templo,"},
{v:16,t:"abriram uma porta secreta do teto e, atirando pedras, fulminaram o chefe e os seus; esquartejaram-nos, cortaram-lhes a cabeça e os atiraram aos que estavam fora."},
{v:17,t:"Em tudo seja bendito o nosso Deus, que entregou os ímpios à morte!"},
{s:"O fogo sagrado"},
{v:18,t:"Como vamos celebrar, no dia vinte e cinco de Casleu, a purificação do templo, julgamos necessário avisar-vos, para que também vós celebreis a festa das Tendas e a do fogo que apareceu quando Neemias, depois de reconstruir o templo e o altar, ofereceu sacrifícios.",n:"Na verdade, o templo e o altar foram reconstruídos no tempo de Zorobabel e de Josué (Esdras 3–6), antes de Neemias."},
{v:19,t:"Pois, quando os nossos pais foram levados para a Pérsia, os piedosos sacerdotes de então tomaram às escondidas o fogo do altar e o esconderam na cavidade de um poço seco, onde o puseram em segurança, de modo que o lugar ficou desconhecido de todos."},
{v:20,t:"Passados muitos anos, quando aprouve a Deus, Neemias, enviado pelo rei da Pérsia, mandou os descendentes dos sacerdotes que o tinham escondido procurar o fogo."},
{v:21,t:"Como nos relataram, não encontraram fogo, e sim um líquido espesso; Neemias mandou-os tirar dele e trazê-lo. Quando o material dos sacrifícios foi posto sobre o altar, Neemias ordenou aos sacerdotes que aspergissem com aquele líquido a lenha e o que estava em cima dela."},
{v:22,t:"Feito isso, depois de algum tempo, quando o sol, antes encoberto pelas nuvens, voltou a brilhar, acendeu-se uma grande fogueira, de modo que todos ficaram maravilhados."},
{v:23,t:"Enquanto o sacrifício se consumia, os sacerdotes faziam uma oração, os sacerdotes e todos os presentes: Jônatas entoava, e os outros respondiam, como também Neemias."},
{v:24,t:"A oração era esta: Senhor, Senhor Deus, criador de todas as coisas, terrível e forte, justo e misericordioso, único rei e bom,",np:1},
{v:25,t:"o único generoso, o único justo, todo-poderoso e eterno, que salvas Israel de todo mal, que fizeste dos nossos pais os teus eleitos e os santificaste:"},
{v:26,t:"aceita o sacrifício por todo o teu povo Israel, guarda a tua herança e santifica-a."},
{v:27,t:"Reúne os nossos dispersos, liberta os que são escravos entre as nações, olha para os desprezados e abominados, e saibam as nações que tu és o nosso Deus.",np:1},
{v:28,t:"Castiga os que nos oprimem e nos ultrajam com arrogância.",np:1},
{v:29,t:"Planta o teu povo no teu lugar santo, como disse Moisés."},
{v:30,t:"E os sacerdotes cantavam os hinos."},
{v:31,t:"Quando o sacrifício foi consumido, Neemias mandou derramar o resto do líquido sobre umas pedras grandes."},
{v:32,t:"Feito isso, acendeu-se uma chama, que se extinguiu diante da luz que resplandecia do altar."},
{v:33,t:"Quando o fato se tornou conhecido, contaram ao rei dos persas que, no lugar onde os sacerdotes deportados tinham escondido o fogo, aparecera aquele líquido, com o qual Neemias e os seus companheiros tinham purificado o material do sacrifício."},
{v:34,t:"Depois de examinar o caso, o rei mandou cercar o lugar e fez dele um lugar sagrado."},
{v:35,t:"E o rei recebia muitos presentes e os repartia com aqueles a quem queria favorecer."},
{v:36,t:"Neemias e os seus companheiros deram a este lugar o nome de Neftar, que quer dizer purificação; mas muitos o chamam de Neftai.",n:"No grego, o nome parece referir-se ao próprio líquido, provavelmente nafta, que se inflama ao calor do sol; neftar, purificação, é uma explicação popular."}
];

window.TEXTOS_SEED["2macabeus"][2] = [
{s:"Jeremias esconde a tenda e a arca"},
{v:1,t:"Encontra-se nos documentos que o profeta Jeremias ordenou aos que eram deportados que levassem do fogo, como foi dito,"},
{v:2,t:"e que o profeta, dando-lhes a Lei, recomendou aos deportados que não esquecessem os mandamentos do Senhor e não se deixassem desviar no pensamento ao ver as estátuas de ouro e de prata e os seus adornos."},
{v:3,t:"E, com outras palavras semelhantes, exortava-os a não afastar a Lei do seu coração."},
{v:4,t:"Dizia-se também no mesmo escrito que o profeta, advertido por um oráculo, mandou que a tenda e a arca o acompanhassem, e foi até o monte em que Moisés subira para contemplar a herança de Deus.",n:"O monte Nebo (Deuteronômio 34,1–4)."},
{v:5,t:"Chegando lá, Jeremias encontrou uma habitação em forma de gruta; levou para dentro a tenda, a arca e o altar do incenso, e fechou a entrada."},
{v:6,t:"Alguns dos que o acompanhavam voltaram para marcar o caminho, mas não conseguiram encontrá-lo."},
{v:7,t:"Quando Jeremias soube disso, repreendeu-os, dizendo: Este lugar ficará desconhecido até que Deus reúna de novo o seu povo e lhe mostre a sua misericórdia."},
{v:8,t:"Então o Senhor mostrará de novo essas coisas, e aparecerão a glória do Senhor e a nuvem, como se manifestou no tempo de Moisés e quando Salomão pediu que o lugar fosse solenemente consagrado."},
{v:9,t:"Contava-se também como Salomão, cheio de sabedoria, ofereceu o sacrifício da dedicação e da conclusão do templo.",np:1},
{v:10,t:"Assim como Moisés rezou ao Senhor e desceu fogo do céu, que consumiu o sacrifício, assim também Salomão rezou, e o fogo desceu e consumiu os holocaustos."},
{v:11,t:"Moisés disse: Porque o sacrifício pelo pecado não foi comido, foi consumido pelo fogo.",n:"Alusão a Levítico 10,16–20."},
{v:12,t:"Do mesmo modo, Salomão celebrou a festa durante oito dias."},
{s:"A biblioteca de Neemias e de Judas"},
{v:13,t:"Essas mesmas coisas eram contadas nos documentos e nas memórias de Neemias, e também como ele fundou uma biblioteca, reunindo os livros dos reis e dos profetas, os de Davi e as cartas dos reis sobre as ofertas."},
{v:14,t:"Do mesmo modo, Judas reuniu todos os livros que se tinham dispersado por causa da guerra que tivemos, e estão conosco."},
{v:15,t:"Se precisardes de algum deles, mandai alguém buscá-los."},
{v:16,t:"Estando para celebrar a purificação, nós vos escrevemos; fareis bem, pois, em celebrar esses dias.",np:1},
{v:17,t:"Deus, que salvou todo o seu povo e devolveu a todos a herança, o reino, o sacerdócio e a santificação,"},
{v:18,t:"como tinha prometido pela Lei, esse mesmo Deus, esperamos, em breve terá piedade de nós e nos reunirá de todas as partes debaixo do céu no lugar santo; pois ele nos livrou de grandes males e purificou o lugar."},
{s:"Prefácio do autor"},
{v:19,t:"A história de Judas Macabeu e dos seus irmãos, a purificação do grande templo e a dedicação do altar,",n:"Aqui começa o prefácio do autor, que resumiu a obra de Jasão de Cirene."},
{v:20,t:"as guerras contra Antíoco Epífanes e contra o seu filho Eupátor,"},
{v:21,t:"as aparições vindas do céu em favor dos que combateram generosamente pelo judaísmo, de modo que, sendo poucos, reconquistaram todo o país e puseram em fuga as multidões bárbaras,",n:"Judaísmo: a palavra aparece aqui pela primeira vez na literatura, para designar o modo de vida judaico, em oposição ao helenismo (4,13)."},
{v:22,t:"recuperaram o templo, famoso em todo o mundo, libertaram a cidade e restabeleceram as leis que estavam para ser abolidas, porque o Senhor, com toda a bondade, lhes foi propício:"},
{v:23,t:"tudo isso, que Jasão de Cirene expôs em cinco livros, procuraremos resumir num só volume."},
{v:24,t:"Considerando a enxurrada de números e a dificuldade que, pela abundância da matéria, encontram os que querem entrar nas narrativas da história,"},
{v:25,t:"procuramos oferecer prazer aos que gostam de ler, facilidade aos que querem guardar os fatos na memória, e proveito a todos os que tiverem este livro nas mãos."},
{v:26,t:"Para nós, que assumimos o trabalho penoso deste resumo, não foi tarefa fácil, mas coisa de suor e de vigílias,"},
{v:27,t:"como não é fácil para quem prepara um banquete e procura agradar aos outros; mesmo assim, pela gratidão de muitos, suportaremos de boa vontade este trabalho,"},
{v:28,t:"deixando ao autor o cuidado de tratar cada coisa com exatidão, e esforçando-nos por seguir as linhas de um resumo."},
{v:29,t:"Pois, assim como o arquiteto de uma casa nova deve cuidar de toda a construção, e quem se encarrega de pintá-la e decorá-la deve procurar o que convém ao ornamento, assim penso que acontece conosco."},
{v:30,t:"Aprofundar o assunto, discorrer longamente e examinar os pormenores cabe ao autor da história;",np:1},
{v:31,t:"mas a quem faz uma adaptação deve permitir-se buscar a brevidade da expressão e dispensar a exposição exaustiva dos fatos."},
{v:32,t:"Comecemos, pois, a narrativa, sem acrescentar mais nada ao que foi dito; seria tolice alongar-se no que vem antes da história e encurtar a própria história."}
];
