// =====================================================================
// II Macabeus — tradução do grego, cotejado com a Nova Vulgata (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["2macabeus"][1] = [
{s:"Primeira carta aos judeus do Egito"},
{v:1,t:"Aos irmãos judeus que estão no Egito, saudações! Os irmãos judeus que estão em Jerusalém e na região da Judeia vos desejam uma paz feliz.",n:"O segundo livro dos Macabeus não continua o primeiro: conta de novo, com outro estilo e outro propósito, os fatos de 175 a 160 a.C., até a vitória de Judas sobre Nicanor. É o resumo de uma obra maior de Jasão de Cirene (2,23), escrito em grego, e começa com duas cartas dos judeus de Jerusalém aos do Egito (1,1–9 e 1,10–2,18), que os convidam a celebrar a festa da purificação do templo."},
{v:2,t:"Que Deus vos faça o bem e se lembre da sua aliança com Abraão, Isaac e Jacó, seus servos fiéis;",np:1},
{v:3,t:"que dê a todos vós um coração para adorá-lo e fazer a sua vontade com coração generoso e alma disposta;"},
{v:4,t:"que abra o vosso coração à sua Lei e aos seus preceitos e vos dê a paz;"},
{v:5,t:"que ouça as vossas orações, se reconcilie convosco e não vos abandone no tempo da desgraça."},
{v:6,t:"Nós, aqui, estamos rezando por vós."},
{v:7,t:"No reinado de Demétrio, no ano cento e sessenta e nove, nós, judeus, vos escrevemos, no auge da tribulação que caiu sobre nós nestes anos, desde que Jasão e os seus partidários traíram a terra santa e o reino:",n:"Ano cento e sessenta e nove: 143 a.C. Jasão é o sumo sacerdote helenizante do capítulo 4."},
{v:8,t:"incendiaram o pórtico e derramaram sangue inocente; mas nós suplicamos ao Senhor e fomos ouvidos; oferecemos sacrifícios e flor de farinha, acendemos as lâmpadas e apresentamos os pães."},
{v:9,t:"Agora, pois, celebrai os dias da festa das Tendas do mês de Casleu,",n:"A festa das Tendas do mês de Casleu é a festa da Dedicação (1 Macabeus 4,59), que se celebrava durante oito dias, como a das Tendas (10,6)."},
{s:"Segunda carta: a morte de Antíoco"},
{v:10,t:"no ano cento e oitenta e oito. Os que estão em Jerusalém e na Judeia, o conselho dos anciãos e Judas saúdam e desejam boa saúde a Aristóbulo, preceptor do rei Ptolomeu, que é da família dos sacerdotes ungidos, e aos judeus que estão no Egito.",n:"Ano cento e oitenta e oito: 124 a.C.; com esta data termina a primeira carta. A segunda se apresenta como escrita em 164 a.C., logo depois da purificação do templo. Aristóbulo era um filósofo judeu de Alexandria, conselheiro de Ptolomeu VI."},
{v:11,t:"Salvos por Deus de grandes perigos, nós lhe damos muitas graças, pois combatemos contra o rei;"},
{v:12,t:"foi ele quem expulsou os que combatiam contra a cidade santa."},
{v:13,t:"Quando o chefe chegou à Pérsia, com um exército que parecia invencível, foram trucidados no templo de Naneia, graças a um ardil dos sacerdotes de Naneia.",n:"Naneia era uma deusa venerada na Mesopotâmia e na Pérsia. Este relato da morte de Antíoco Epífanes difere do de 9,1–29 e do de 1 Macabeus 6,1–16."},
{v:14,t:"Antíoco foi àquele lugar com os seus amigos, a pretexto de desposar a deusa, para receber como dote as riquezas do templo."},
{v:15,t:"Os sacerdotes de Naneia expuseram as riquezas, e ele entrou com poucos acompanhantes no recinto do santuário; mal Antíoco entrou, os sacerdotes fecharam o templo,"},
{v:16,t:"abriram uma porta secreta do teto e, atirando pedras, fulminaram o chefe e os seus; esquartejaram-nos, cortaram-lhes a cabeça e os atiraram aos que estavam fora."},
{v:17,t:"Em tudo seja bendito o nosso Deus, que entregou os ímpios à morte!"},
{s:"O fogo sagrado"},
{v:18,t:"Como vamos celebrar, no dia vinte e cinco de Casleu, a purificação do templo, julgamos necessário avisar-vos, para que também vós celebreis a festa das Tendas e a do fogo que apareceu quando Neemias, depois de reconstruir o templo e o altar, ofereceu sacrifícios.",n:"Na verdade, o templo e o altar foram reconstruídos no tempo de Zorobabel e de Josué (Esdras 3–6), antes de Neemias."},
{v:19,t:"Pois, quando os nossos pais foram levados para a Pérsia, os piedosos sacerdotes de então tomaram às escondidas o fogo do altar e o esconderam na cavidade de um poço seco, onde o puseram em segurança, de modo que o lugar ficou desconhecido de todos."},
{v:20,t:"Passados muitos anos, quando aprouve a Deus, Neemias, enviado pelo rei da Pérsia, mandou os descendentes dos sacerdotes que o tinham escondido procurar o fogo."},
{v:21,t:"Como nos relataram, não encontraram fogo, e sim um líquido espesso; Neemias mandou-os tirar dele e trazê-lo. Quando o material dos sacrifícios foi posto sobre o altar, Neemias ordenou aos sacerdotes que aspergissem com aquele líquido a lenha e o que estava em cima dela."},
{v:22,t:"Feito isso, depois de algum tempo, quando o sol, antes encoberto pelas nuvens, voltou a brilhar, acendeu-se uma grande fogueira, de modo que todos ficaram maravilhados."},
{v:23,t:"Enquanto o sacrifício se consumia, os sacerdotes faziam uma oração, os sacerdotes e todos os presentes: Jônatas entoava, e os outros respondiam, como também Neemias."},
{v:24,t:"A oração era esta: Senhor, Senhor Deus, criador de todas as coisas, terrível e forte, justo e misericordioso, único rei e bom,",np:1},
{v:25,t:"o único generoso, o único justo, todo-poderoso e eterno, que salvas Israel de todo mal, que fizeste dos nossos pais os teus eleitos e os santificaste:"},
{v:26,t:"aceita o sacrifício por todo o teu povo Israel, guarda a tua herança e santifica-a."},
{v:27,t:"Reúne os nossos dispersos, liberta os que são escravos entre as nações, olha para os desprezados e abominados, e saibam as nações que tu és o nosso Deus.",np:1},
{v:28,t:"Castiga os que nos oprimem e nos ultrajam com arrogância.",np:1},
{v:29,t:"Planta o teu povo no teu lugar santo, como disse Moisés."},
{v:30,t:"E os sacerdotes cantavam os hinos."},
{v:31,t:"Quando o sacrifício foi consumido, Neemias mandou derramar o resto do líquido sobre umas pedras grandes."},
{v:32,t:"Feito isso, acendeu-se uma chama, que se extinguiu diante da luz que resplandecia do altar."},
{v:33,t:"Quando o fato se tornou conhecido, contaram ao rei dos persas que, no lugar onde os sacerdotes deportados tinham escondido o fogo, aparecera aquele líquido, com o qual Neemias e os seus companheiros tinham purificado o material do sacrifício."},
{v:34,t:"Depois de examinar o caso, o rei mandou cercar o lugar e fez dele um lugar sagrado."},
{v:35,t:"E o rei recebia muitos presentes e os repartia com aqueles a quem queria favorecer."},
{v:36,t:"Neemias e os seus companheiros deram a este lugar o nome de Neftar, que quer dizer purificação; mas muitos o chamam de Neftai.",n:"No grego, o nome parece referir-se ao próprio líquido, provavelmente nafta, que se inflama ao calor do sol; neftar, purificação, é uma explicação popular."}
];

window.TEXTOS_SEED["2macabeus"][2] = [
{s:"Jeremias esconde a tenda e a arca"},
{v:1,t:"Encontra-se nos documentos que o profeta Jeremias ordenou aos que eram deportados que levassem do fogo, como foi dito,"},
{v:2,t:"e que o profeta, dando-lhes a Lei, recomendou aos deportados que não esquecessem os mandamentos do Senhor e não se deixassem desviar no pensamento ao ver as estátuas de ouro e de prata e os seus adornos."},
{v:3,t:"E, com outras palavras semelhantes, exortava-os a não afastar a Lei do seu coração."},
{v:4,t:"Dizia-se também no mesmo escrito que o profeta, advertido por um oráculo, mandou que a tenda e a arca o acompanhassem, e foi até o monte em que Moisés subira para contemplar a herança de Deus.",n:"O monte Nebo (Deuteronômio 34,1–4)."},
{v:5,t:"Chegando lá, Jeremias encontrou uma habitação em forma de gruta; levou para dentro a tenda, a arca e o altar do incenso, e fechou a entrada."},
{v:6,t:"Alguns dos que o acompanhavam voltaram para marcar o caminho, mas não conseguiram encontrá-lo."},
{v:7,t:"Quando Jeremias soube disso, repreendeu-os, dizendo: Este lugar ficará desconhecido até que Deus reúna de novo o seu povo e lhe mostre a sua misericórdia."},
{v:8,t:"Então o Senhor mostrará de novo essas coisas, e aparecerão a glória do Senhor e a nuvem, como se manifestou no tempo de Moisés e quando Salomão pediu que o lugar fosse solenemente consagrado."},
{v:9,t:"Contava-se também como Salomão, cheio de sabedoria, ofereceu o sacrifício da dedicação e da conclusão do templo.",np:1},
{v:10,t:"Assim como Moisés rezou ao Senhor e desceu fogo do céu, que consumiu o sacrifício, assim também Salomão rezou, e o fogo desceu e consumiu os holocaustos."},
{v:11,t:"Moisés disse: Porque o sacrifício pelo pecado não foi comido, foi consumido pelo fogo.",n:"Alusão a Levítico 10,16–20."},
{v:12,t:"Do mesmo modo, Salomão celebrou a festa durante oito dias."},
{s:"A biblioteca de Neemias e de Judas"},
{v:13,t:"Essas mesmas coisas eram contadas nos documentos e nas memórias de Neemias, e também como ele fundou uma biblioteca, reunindo os livros dos reis e dos profetas, os de Davi e as cartas dos reis sobre as ofertas."},
{v:14,t:"Do mesmo modo, Judas reuniu todos os livros que se tinham dispersado por causa da guerra que tivemos, e estão conosco."},
{v:15,t:"Se precisardes de algum deles, mandai alguém buscá-los."},
{v:16,t:"Estando para celebrar a purificação, nós vos escrevemos; fareis bem, pois, em celebrar esses dias.",np:1},
{v:17,t:"Deus, que salvou todo o seu povo e devolveu a todos a herança, o reino, o sacerdócio e a santificação,"},
{v:18,t:"como tinha prometido pela Lei, esse mesmo Deus, esperamos, em breve terá piedade de nós e nos reunirá de todas as partes debaixo do céu no lugar santo; pois ele nos livrou de grandes males e purificou o lugar."},
{s:"Prefácio do autor"},
{v:19,t:"A história de Judas Macabeu e dos seus irmãos, a purificação do grande templo e a dedicação do altar,",n:"Aqui começa o prefácio do autor, que resumiu a obra de Jasão de Cirene."},
{v:20,t:"as guerras contra Antíoco Epífanes e contra o seu filho Eupátor,"},
{v:21,t:"as aparições vindas do céu em favor dos que combateram generosamente pelo judaísmo, de modo que, sendo poucos, reconquistaram todo o país e puseram em fuga as multidões bárbaras,",n:"Judaísmo: a palavra aparece aqui pela primeira vez na literatura, para designar o modo de vida judaico, em oposição ao helenismo (4,13)."},
{v:22,t:"recuperaram o templo, famoso em todo o mundo, libertaram a cidade e restabeleceram as leis que estavam para ser abolidas, porque o Senhor, com toda a bondade, lhes foi propício:"},
{v:23,t:"tudo isso, que Jasão de Cirene expôs em cinco livros, procuraremos resumir num só volume."},
{v:24,t:"Considerando a enxurrada de números e a dificuldade que, pela abundância da matéria, encontram os que querem entrar nas narrativas da história,"},
{v:25,t:"procuramos oferecer prazer aos que gostam de ler, facilidade aos que querem guardar os fatos na memória, e proveito a todos os que tiverem este livro nas mãos."},
{v:26,t:"Para nós, que assumimos o trabalho penoso deste resumo, não foi tarefa fácil, mas coisa de suor e de vigílias,"},
{v:27,t:"como não é fácil para quem prepara um banquete e procura agradar aos outros; mesmo assim, pela gratidão de muitos, suportaremos de boa vontade este trabalho,"},
{v:28,t:"deixando ao autor o cuidado de tratar cada coisa com exatidão, e esforçando-nos por seguir as linhas de um resumo."},
{v:29,t:"Pois, assim como o arquiteto de uma casa nova deve cuidar de toda a construção, e quem se encarrega de pintá-la e decorá-la deve procurar o que convém ao ornamento, assim penso que acontece conosco."},
{v:30,t:"Aprofundar o assunto, discorrer longamente e examinar os pormenores cabe ao autor da história;",np:1},
{v:31,t:"mas a quem faz uma adaptação deve permitir-se buscar a brevidade da expressão e dispensar a exposição exaustiva dos fatos."},
{v:32,t:"Comecemos, pois, a narrativa, sem acrescentar mais nada ao que foi dito; seria tolice alongar-se no que vem antes da história e encurtar a própria história."}
];

window.TEXTOS_SEED["2macabeus"][3] = [
{s:"Heliodoro no templo de Jerusalém"},
{v:1,t:"Enquanto a cidade santa vivia em plena paz e as leis eram observadas da melhor maneira, graças à piedade do sumo sacerdote Onias e ao seu ódio ao mal,"},
{v:2,t:"acontecia que os próprios reis honravam o lugar e glorificavam o templo com os mais ricos presentes,"},
{v:3,t:"a ponto de Seleuco, rei da Ásia, pagar das suas próprias rendas todas as despesas necessárias ao serviço dos sacrifícios.",n:"Seleuco IV Filopátor (187–175 a.C.), irmão mais velho de Antíoco Epífanes."},
{v:4,t:"Mas um certo Simão, da família sacerdotal de Belga, nomeado administrador do templo, entrou em desacordo com o sumo sacerdote sobre a fiscalização dos mercados da cidade.",n:"Da família sacerdotal de Belga: assim a Nova Vulgata, com a antiga versão latina (compare Neemias 12,5.18); o grego diz: da tribo de Benjamim."},
{v:5,t:"Não conseguindo vencer Onias, foi ter com Apolônio, filho de Tarseu, que naquele tempo era governador da Celessíria e da Fenícia,"},
{v:6,t:"e denunciou-lhe que o tesouro de Jerusalém estava cheio de riquezas incalculáveis, a ponto de ser incontável a quantidade de dinheiro, que não era destinado às despesas dos sacrifícios; e que era possível fazê-lo passar para o poder do rei."},
{v:7,t:"Apolônio foi ter com o rei e informou-o das riquezas que lhe tinham sido denunciadas; o rei escolheu Heliodoro, o seu primeiro-ministro, e o enviou com ordens de trazer aquelas riquezas.",np:1},
{v:8,t:"Heliodoro pôs-se logo a caminho, aparentemente para visitar as cidades da Celessíria e da Fenícia, mas na realidade para cumprir o propósito do rei."},
{v:9,t:"Chegando a Jerusalém, foi recebido amavelmente pelo sumo sacerdote da cidade; contou-lhe a denúncia feita e explicou o motivo da sua vinda, perguntando se as coisas eram realmente assim."},
{v:10,t:"O sumo sacerdote explicou-lhe que se tratava de depósitos de viúvas e de órfãos,"},
{v:11,t:"e que uma parte pertencia a Hircano, filho de Tobias, homem de muito alta posição, e que as coisas não eram como o ímpio Simão caluniava; que ao todo havia quatrocentos talentos de prata e duzentos de ouro;"},
{v:12,t:"e que era absolutamente impossível lesar os que tinham confiado na santidade do lugar e na majestade inviolável do templo, venerado no mundo inteiro."},
{v:13,t:"Mas Heliodoro, por causa das ordens que recebera do rei, insistia em que aquelas riquezas deviam de qualquer modo ser levadas ao tesouro real.",np:1},
{v:14,t:"No dia marcado, entrou para fazer o inventário. Houve então grande angústia em toda a cidade.",np:1},
{v:15,t:"Os sacerdotes, revestidos das vestes sacerdotais, prostraram-se diante do altar e invocavam ao Céu aquele que dera a lei sobre os depósitos, pedindo que os guardasse intactos para os que os tinham depositado."},
{v:16,t:"Quem olhasse o rosto do sumo sacerdote ficava com o coração ferido, porque o seu semblante e a sua cor alterada revelavam a angústia da sua alma."},
{v:17,t:"Um temor e um tremor do corpo se tinham apoderado do homem, e mostravam aos que o viam a dor que tinha no coração."},
{v:18,t:"Outros saíam em massa das casas para uma súplica pública, porque o lugar santo estava para ser profanado."},
{v:19,t:"As mulheres, cingidas de saco abaixo dos seios, enchiam as ruas; as moças, que viviam recolhidas, corriam umas para as portas, outras para os muros, e algumas espiavam pelas janelas;"},
{v:20,t:"e todas, estendendo as mãos para o céu, faziam as suas súplicas."},
{v:21,t:"Dava pena ver aquela multidão confusa prostrada por terra, e a expectativa do sumo sacerdote, cheio de angústia."},
{v:22,t:"Eles invocavam o Senhor todo-poderoso, para que guardasse intactos e em toda a segurança os depósitos dos que os tinham confiado.",np:1},
{s:"O castigo de Heliodoro"},
{v:23,t:"Heliodoro, porém, executava o que tinha decidido."},
{v:24,t:"Mas, quando ele já estava junto do tesouro com a sua escolta, o Soberano dos espíritos e de todo poder fez uma grande manifestação, de modo que todos os que tinham ousado entrar ali, abatidos pela força de Deus, ficaram sem forças e cheios de pavor."},
{v:25,t:"Apareceu-lhes um cavalo montado por um cavaleiro terrível e coberto de um riquíssimo arreio; lançando-se com ímpeto, atacou Heliodoro com as patas dianteiras. O cavaleiro parecia ter uma armadura de ouro."},
{v:26,t:"Apareceram-lhe também dois jovens de força extraordinária, de uma beleza magnífica e esplendidamente vestidos, que se puseram um de cada lado e o açoitavam sem parar, dando-lhe muitos golpes."},
{v:27,t:"Heliodoro caiu de repente por terra, envolto em densa escuridão; os seus homens o levantaram e o puseram numa liteira"},
{v:28,t:"e levaram-no, a ele que pouco antes entrara no tesouro com grande séquito e toda a sua escolta, agora incapaz de se valer das armas, reconhecendo claramente o poder de Deus."},
{v:29,t:"Ele jazia sem fala, pela ação divina, privado de toda esperança de salvação;",np:1},
{v:30,t:"e os judeus bendiziam o Senhor, que glorificara de modo admirável o seu lugar santo; e o templo, pouco antes cheio de medo e de agitação, com a aparição do Senhor todo-poderoso, encheu-se de alegria e de júbilo."},
{v:31,t:"Logo alguns amigos de Heliodoro pediram a Onias que invocasse o Altíssimo e concedesse a vida àquele que estava dando o último suspiro."},
{v:32,t:"O sumo sacerdote, temendo que o rei suspeitasse de algum atentado dos judeus contra Heliodoro, ofereceu um sacrifício pela saúde daquele homem."},
{v:33,t:"Enquanto o sumo sacerdote oferecia o sacrifício de expiação, os mesmos jovens apareceram de novo a Heliodoro, com as mesmas vestes, e disseram-lhe: Agradece muito ao sumo sacerdote Onias, pois foi por causa dele que o Senhor te concedeu a vida."},
{v:34,t:"E tu, que foste açoitado pelo Céu, anuncia a todos o grande poder de Deus. Dito isso, desapareceram."},
{s:"Heliodoro dá testemunho do poder de Deus"},
{v:35,t:"Heliodoro ofereceu um sacrifício ao Senhor e fez grandes votos àquele que lhe tinha conservado a vida; despediu-se amigavelmente de Onias e voltou com a sua tropa para junto do rei."},
{v:36,t:"E dava testemunho diante de todos das obras do Deus altíssimo que tinha visto com os próprios olhos."},
{v:37,t:"Quando o rei perguntou a Heliodoro quem seria o homem indicado para mandar outra vez a Jerusalém, ele respondeu:",np:1},
{v:38,t:"Se tens algum inimigo ou alguém que conspire contra o Estado, manda-o para lá, e tu o receberás de volta bem açoitado, se é que escapará com vida; pois há verdadeiramente naquele lugar uma força divina."},
{v:39,t:"Aquele que tem a sua morada no céu vigia e protege aquele lugar, e fere e destrói os que vêm para lhe fazer mal."},
{v:40,t:"Foi assim que se passaram os fatos relativos a Heliodoro e à defesa do tesouro."}
];

window.TEXTOS_SEED["2macabeus"][4] = [
{s:"Simão calunia Onias"},
{v:1,t:"O referido Simão, delator das riquezas e da pátria, caluniava Onias, como se ele tivesse incitado Heliodoro e fosse o causador daqueles males;"},
{v:2,t:"e ousava chamar de conspirador contra o Estado o benfeitor da cidade, o protetor dos seus compatriotas, o zelador das leis."},
{v:3,t:"Como a inimizade chegou a tal ponto que até assassinatos eram cometidos por um dos partidários de Simão,"},
{v:4,t:"Onias, vendo o perigo dessa rivalidade, e que Apolônio, filho de Menesteu, governador da Celessíria e da Fenícia, aumentava a maldade de Simão,"},
{v:5,t:"foi ter com o rei, não para acusar os seus concidadãos, mas visando o bem comum de todo o povo e de cada um."},
{v:6,t:"Pois via que, sem a intervenção do rei, era impossível que houvesse paz e que Simão pusesse fim à sua loucura."},
{s:"Jasão e a helenização de Jerusalém"},
{v:7,t:"Mas, quando Seleuco morreu e Antíoco, chamado Epífanes, assumiu o reino, Jasão, irmão de Onias, obteve por corrupção o sumo sacerdócio,",n:"Em 175 a.C."},
{v:8,t:"prometendo ao rei, numa audiência, trezentos e sessenta talentos de prata e mais oitenta de outra renda."},
{v:9,t:"Prometia, além disso, pagar mais cento e cinquenta, se lhe fosse concedido, pela autoridade do rei, fundar um ginásio e um centro de formação para os jovens, e inscrever os habitantes de Jerusalém como cidadãos de Antioquia.",n:"Ser cidadão de Antioquia dava privilégios e integrava Jerusalém no mundo das cidades gregas."},
{v:10,t:"O rei consentiu, e Jasão, assim que tomou posse do cargo, fez os seus compatriotas passarem ao modo de vida grego."},
{v:11,t:"Suprimiu os privilégios reais concedidos aos judeus por intermédio de João, pai de Eupólemo, que fora embaixador junto aos romanos para fazer amizade e aliança; e, abolindo as instituições legítimas, introduziu costumes contrários à Lei."},
{v:12,t:"Construiu com gosto um ginásio ao pé da própria acrópole e fez os melhores jovens usar o chapéu grego.",n:"O pétaso, chapéu de abas largas, próprio do deus Hermes, padroeiro dos ginásios."},
{v:13,t:"Assim chegou ao auge a moda grega e o avanço dos costumes estrangeiros, por causa da excessiva perversidade de Jasão, ímpio e não sumo sacerdote,"},
{v:14,t:"a ponto de os sacerdotes já não se dedicarem ao serviço do altar; desprezando o templo e descuidando dos sacrifícios, corriam, ao sinal do disco, para tomar parte nos jogos da palestra, proibidos pela Lei,"},
{v:15,t:"sem dar valor às honras dos seus pais e estimando acima de tudo as glórias gregas."},
{v:16,t:"Por isso mesmo caiu sobre eles uma dura calamidade: aqueles cujos costumes invejavam e a quem queriam imitar em tudo tornaram-se seus inimigos e carrascos."},
{v:17,t:"Porque não se viola impunemente a lei divina; é o que o período seguinte mostrará."},
{v:18,t:"Quando se celebravam em Tiro os jogos que se realizavam de cinco em cinco anos, com a presença do rei,",np:1,n:"Os jogos em honra de Melcart, o Hércules de Tiro."},
{v:19,t:"o infame Jasão enviou representantes, cidadãos de Antioquia de Jerusalém, levando trezentas dracmas de prata para o sacrifício a Hércules. Mas os próprios portadores pediram que o dinheiro não fosse usado no sacrifício, porque não era conveniente, e sim destinado a outra despesa."},
{v:20,t:"Assim, esse dinheiro, que pela intenção de quem o mandou devia servir ao sacrifício a Hércules, serviu, pela decisão dos portadores, para a construção de trirremes."},
{v:21,t:"Apolônio, filho de Menesteu, foi enviado ao Egito para a entronização do rei Filométor; Antíoco, ao saber que este se tornara hostil à sua política, tratou de garantir a própria segurança. Por isso foi a Jope e dali a Jerusalém."},
{v:22,t:"Jasão e a cidade o receberam com magnificência; entrou à luz de tochas e entre aclamações. Depois levou o exército para a Fenícia."},
{s:"Menelau, sumo sacerdote"},
{v:23,t:"Três anos depois, Jasão enviou Menelau, irmão do referido Simão, para levar o dinheiro ao rei e tratar de alguns negócios urgentes."},
{v:24,t:"Mas ele, apresentado ao rei e lisonjeando-o com ares de homem importante, conseguiu para si o sumo sacerdócio, oferecendo trezentos talentos de prata a mais do que Jasão.",np:1},
{v:25,t:"Recebida a nomeação do rei, voltou sem nada digno do sumo sacerdócio, mas com a fúria de um tirano cruel e a raiva de uma fera selvagem."},
{v:26,t:"Assim Jasão, que suplantara o próprio irmão, suplantado por sua vez por outro, teve de fugir para a terra dos amonitas."},
{v:27,t:"Menelau ocupava o cargo, mas não pagava regularmente nada do dinheiro prometido ao rei,"},
{v:28,t:"embora Sóstrato, comandante da acrópole, a quem cabia a cobrança dos impostos, lhe reclamasse. Por isso os dois foram chamados pelo rei."},
{v:29,t:"Menelau deixou como substituto no sumo sacerdócio o seu irmão Lisímaco, e Sóstrato deixou Crates, o comandante dos cipriotas.",np:1},
{s:"O assassinato de Onias"},
{v:30,t:"Nesse meio tempo, os habitantes de Tarso e de Malos se revoltaram, porque as suas cidades tinham sido dadas de presente a Antióquida, concubina do rei."},
{v:31,t:"O rei partiu às pressas para restabelecer a ordem, deixando como seu substituto Andrônico, um dos altos dignitários."},
{v:32,t:"Menelau, achando que chegara a ocasião propícia, furtou alguns objetos de ouro do templo e deu-os de presente a Andrônico; outros, já os tinha vendido em Tiro e nas cidades vizinhas."},
{v:33,t:"Quando Onias soube disso com certeza, denunciou-o, depois de se refugiar num lugar de asilo, em Dafne, perto de Antioquia."},
{v:34,t:"Menelau, então, chamou Andrônico em particular e pediu-lhe que matasse Onias. Andrônico foi ter com Onias e, com astúcia, estendendo-lhe a mão direita com juramentos, persuadiu-o, embora Onias desconfiasse dele, a sair do lugar de asilo; e logo o matou, sem nenhum respeito pela justiça.",np:1,n:"Em 171 a.C. Muitos veem neste assassinato o ungido que é eliminado, de que fala Daniel 9,26."},
{v:35,t:"Por isso, não só os judeus, mas também muitos de outras nações ficaram indignados e revoltados com o assassinato injusto daquele homem."},
{v:36,t:"Quando o rei voltou das regiões da Cilícia, os judeus da cidade, apoiados pelos gregos, que também detestavam o crime, foram queixar-se a ele de que Onias fora morto sem motivo."},
{v:37,t:"Antíoco ficou profundamente triste, comoveu-se e chorou, por causa da sabedoria e da grande dignidade do morto;"},
{v:38,t:"e, inflamado de cólera, mandou logo tirar a púrpura de Andrônico e rasgar-lhe as vestes; fê-lo conduzir por toda a cidade até o próprio lugar onde cometera o crime contra Onias, e ali eliminou do mundo o assassino. Assim o Senhor lhe deu o castigo merecido."},
{s:"A morte de Lisímaco e a absolvição de Menelau"},
{v:39,t:"Como Lisímaco, de acordo com Menelau, tinha cometido muitos roubos sacrílegos na cidade, e a notícia se espalhou, o povo se amotinou contra Lisímaco, quando já muitos objetos de ouro tinham sido levados."},
{v:40,t:"Como a multidão se levantava cheia de cólera, Lisímaco armou uns três mil homens e começou a usar da violência, sob o comando de um tal Aurano, homem avançado em anos e não menos em loucura."},
{v:41,t:"Quando perceberam o ataque de Lisímaco, uns pegaram pedras, outros paus grossos, e alguns, apanhando punhados da cinza que havia ali, atiravam tudo junto contra os homens de Lisímaco."},
{v:42,t:"Assim feriram muitos deles, mataram alguns e puseram todos em fuga; e o próprio ladrão sacrílego, mataram-no junto ao tesouro."},
{v:43,t:"Por causa desses fatos, abriu-se um processo contra Menelau.",np:1},
{v:44,t:"Quando o rei chegou a Tiro, três homens enviados pelo conselho dos anciãos apresentaram diante dele a acusação."},
{v:45,t:"Menelau, já perdido, prometeu muito dinheiro a Ptolomeu, filho de Dorímenes, para que convencesse o rei."},
{v:46,t:"Ptolomeu, então, levou o rei à parte, num pórtico, como para tomar ar fresco, e o fez mudar de ideia."},
{v:47,t:"E o rei absolveu das acusações Menelau, causador de todo o mal, e condenou à morte aqueles infelizes que, se tivessem defendido a sua causa até diante dos citas, teriam sido declarados inocentes."},
{v:48,t:"Assim, os que tinham defendido a cidade, o povo e os objetos sagrados sofreram logo esse castigo injusto."},
{v:49,t:"Por isso, até os tírios, indignados com o crime, providenciaram com magnificência o necessário para o seu sepultamento."},
{v:50,t:"Menelau, graças à cobiça dos poderosos, permaneceu no cargo, crescendo em maldade e tornando-se o grande inimigo dos seus concidadãos.",np:1}
];
