// =====================================================================
// II Reis — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["2reis"][1] = [
{s:"Ocozias consulta Belzebu"},
{v:1,t:"Depois da morte de Acab, Moab revoltou-se contra Israel.",n:"O Segundo Livro dos Reis continua o primeiro sem interrupção: vai do reinado de Ocozias à queda de Jerusalém e ao exílio da Babilônia, em 587 antes de Cristo."},
{v:2,t:"Ocozias caiu pela grade do seu quarto de cima, em Samaria, e ficou doente. Então enviou mensageiros, dizendo-lhes: Ide consultar Belzebu, deus de Acaron, para saber se sobreviverei a esta doença.",n:"Belzebu, à letra senhor das moscas: deformação zombeteira do nome Baal-Zebul, Baal príncipe, venerado em Acaron, cidade filisteia. Nos Evangelhos, Belzebu será o nome do príncipe dos demônios (Mateus 12,24)."},
{v:3,t:"Mas o anjo do Senhor disse a Elias, o tesbita: Levanta-te, sobe ao encontro dos mensageiros do rei de Samaria e dize-lhes: Acaso não há Deus em Israel, para irdes consultar Belzebu, deus de Acaron?"},
{v:4,t:"Por isso assim diz o Senhor: Não descerás da cama a que subiste, mas certamente morrerás. E Elias partiu."},
{v:5,t:"Os mensageiros voltaram a Ocozias, e ele lhes perguntou: Por que voltastes?",np:1},
{v:6,t:"Eles responderam: Um homem veio ao nosso encontro e nos disse: Ide, voltai ao rei que vos enviou e dizei-lhe: Assim diz o Senhor: Acaso não há Deus em Israel, para mandares consultar Belzebu, deus de Acaron? Por isso não descerás da cama a que subiste, mas certamente morrerás."},
{v:7,t:"Ele lhes perguntou: Qual era o aspecto do homem que veio ao vosso encontro e vos disse essas palavras?"},
{v:8,t:"Eles responderam: Era um homem vestido de pelos, com um cinto de couro à cintura. Ele disse: É Elias, o tesbita!",n:"O manto de pelos e o cinto de couro serão também o vestuário de João Batista, o novo Elias (Marcos 1,6; Mateus 11,14)."},
{s:"Elias e os chefes de cinquenta"},
{v:9,t:"O rei enviou-lhe um chefe de cinquenta com os seus cinquenta homens. Ele subiu até Elias, que estava sentado no alto do monte, e disse-lhe: Homem de Deus, o rei ordena: Desce!",np:1},
{v:10,t:"Elias respondeu ao chefe de cinquenta: Se sou homem de Deus, desça fogo do céu e te devore, a ti e aos teus cinquenta! E desceu fogo do céu e o devorou, a ele e aos seus cinquenta.",n:"Tiago e João quererão imitar Elias contra os samaritanos, e Jesus os repreenderá (Lucas 9,54-55)."},
{v:11,t:"O rei tornou a enviar-lhe outro chefe de cinquenta com os seus cinquenta homens, e este lhe disse: Homem de Deus, assim diz o rei: Desce depressa!"},
{v:12,t:"Elias respondeu-lhes: Se sou homem de Deus, desça fogo do céu e te devore, a ti e aos teus cinquenta! E desceu fogo de Deus do céu e o devorou, a ele e aos seus cinquenta."},
{v:13,t:"O rei enviou ainda um terceiro chefe de cinquenta com os seus cinquenta homens. Este subiu e, chegando, dobrou os joelhos diante de Elias e suplicou-lhe: Homem de Deus, que a minha vida e a vida destes cinquenta servos teus sejam preciosas aos teus olhos!",n:"O terceiro chefe não dá ordens ao profeta: suplica. A humildade o salva."},
{v:14,t:"Desceu fogo do céu e devorou os dois primeiros chefes de cinquenta com os seus homens; mas agora, peço-te, tem piedade da minha vida!"},
{v:15,t:"O anjo do Senhor disse a Elias: Desce com ele; não tenhas medo dele. Elias levantou-se e desceu com ele até o rei,"},
{v:16,t:"e disse-lhe: Assim diz o Senhor: Porque enviaste mensageiros para consultar Belzebu, deus de Acaron, como se não houvesse Deus em Israel para consultar a sua palavra, não descerás da cama a que subiste, mas certamente morrerás."},
{v:17,t:"E Ocozias morreu, segundo a palavra do Senhor que Elias tinha dito. Jorão, seu irmão, reinou em seu lugar, no segundo ano de Jorão, filho de Josafá, rei de Judá, porque Ocozias não tinha filho.",np:1,n:"Dois reis do mesmo nome, Jorão, reinam ao mesmo tempo em Israel e em Judá. As datas dos Reis nem sempre concordam entre si: talvez por causa de corregências, em que o filho reinava junto com o pai."},
{v:18,t:"O resto dos feitos de Ocozias, o que ele fez, não está escrito no livro dos Anais dos Reis de Israel?"}
];

window.TEXTOS_SEED["2reis"][2] = [
{s:"Elias arrebatado ao céu"},
{v:1,t:"Quando o Senhor quis arrebatar Elias ao céu num redemoinho, Elias e Eliseu partiram de Guilgal.",n:"Não se trata do Guilgal junto ao Jordão, mas de outro, na montanha, ao norte de Betel."},
{v:2,t:"Elias disse a Eliseu: Fica aqui, porque o Senhor me envia a Betel. Mas Eliseu respondeu: Pela vida do Senhor e pela tua vida, não te deixarei. E desceram a Betel.",n:"Três vezes Elias pede a Eliseu que fique, e três vezes Eliseu recusa: a fidelidade do discípulo é posta à prova."},
{v:3,t:"Os filhos dos profetas que estavam em Betel saíram ao encontro de Eliseu e lhe disseram: Sabes que hoje o Senhor vai tirar o teu senhor de sobre a tua cabeça? Ele respondeu: Eu também sei; calai-vos."},
{v:4,t:"Elias disse-lhe: Eliseu, fica aqui, porque o Senhor me envia a Jericó. Ele respondeu: Pela vida do Senhor e pela tua vida, não te deixarei. E chegaram a Jericó."},
{v:5,t:"Os filhos dos profetas que estavam em Jericó aproximaram-se de Eliseu e lhe disseram: Sabes que hoje o Senhor vai tirar o teu senhor de sobre a tua cabeça? Ele respondeu: Eu também sei; calai-vos."},
{v:6,t:"Elias disse-lhe: Fica aqui, porque o Senhor me envia ao Jordão. Ele respondeu: Pela vida do Senhor e pela tua vida, não te deixarei. E os dois continuaram juntos."},
{v:7,t:"Cinquenta homens dos filhos dos profetas os seguiram e pararam ao longe, defronte deles, enquanto os dois ficavam de pé à beira do Jordão.",np:1},
{v:8,t:"Então Elias tomou o seu manto, enrolou-o e bateu nas águas, que se dividiram de um lado e de outro; e os dois passaram a pé enxuto.",n:"Como Moisés no mar Vermelho e Josué no Jordão: Elias refaz ao contrário o caminho da entrada na terra, e sai dela para o lado do Nebo, onde morreu Moisés."},
{v:9,t:"Depois que passaram, Elias disse a Eliseu: Pede o que queres que eu faça por ti, antes que eu seja arrebatado do teu lado. Eliseu respondeu: Peço-te que eu receba duas partes do teu espírito.",n:"Duas partes: a porção dupla que cabia ao primogênito na herança (Deuteronômio 21,17). Eliseu pede para ser o herdeiro de Elias."},
{v:10,t:"Elias disse: Pedes uma coisa difícil. Mas, se me vires quando eu for arrebatado do teu lado, assim te acontecerá; se não me vires, não acontecerá."},
{v:11,t:"Enquanto iam andando e conversando, eis que um carro de fogo, com cavalos de fogo, os separou um do outro, e Elias subiu ao céu no redemoinho.",n:"Como Henoc (Gênesis 5,24), Elias não morre: é arrebatado. Daí a espera do seu retorno antes do Dia do Senhor (Malaquias 3,23), que os Evangelhos veem cumprida em João Batista; e Elias aparecerá ao lado de Moisés na transfiguração de Jesus."},
{v:12,t:"Eliseu via e gritava: Meu pai, meu pai! Carro de Israel e seu cavaleiro! E não o viu mais. Então tomou as suas vestes e as rasgou em duas partes.",n:"Carro de Israel e seu cavaleiro: Elias era a verdadeira força de Israel, mais que os carros de guerra. Os mesmos títulos serão dados a Eliseu na hora da sua morte (13,14)."},
{v:13,t:"Levantou o manto que tinha caído de Elias, voltou e parou à beira do Jordão."},
{v:14,t:"Com o manto que tinha caído de Elias bateu nas águas e disse: Onde está agora o Senhor, o Deus de Elias? Bateu nas águas, e elas se dividiram de um lado e de outro, e Eliseu passou."},
{v:15,t:"Os filhos dos profetas, que estavam em Jericó, defronte, vendo-o, disseram: O espírito de Elias repousa sobre Eliseu. Vieram ao seu encontro e prostraram-se diante dele com o rosto em terra,",np:1},
{v:16,t:"e lhe disseram: Há entre os teus servos cinquenta homens valentes; deixa-os ir procurar o teu senhor: talvez o Espírito do Senhor o tenha arrebatado e lançado em algum monte ou em algum vale. Ele disse: Não mandeis ninguém."},
{v:17,t:"Mas insistiram tanto com ele, até que, envergonhado, disse: Mandai. Mandaram cinquenta homens, que o procuraram durante três dias, mas não o encontraram,"},
{v:18,t:"e voltaram a Eliseu, que ficara em Jericó. Ele lhes disse: Não vos disse que não fôsseis?"},
{s:"Os primeiros milagres de Eliseu"},
{v:19,t:"Os homens da cidade disseram a Eliseu: A situação desta cidade é boa, como o meu senhor pode ver; mas as águas são más, e a terra faz abortar.",np:1},
{v:20,t:"Ele disse: Trazei-me um prato novo e ponde nele sal. Eles o trouxeram,"},
{v:21,t:"e ele foi à fonte das águas, lançou nela o sal e disse: Assim diz o Senhor: Eu saneei estas águas; já não haverá nelas morte nem aborto.",n:"A fonte de Jericó, abundante, ainda hoje é chamada fonte de Eliseu."},
{v:22,t:"E as águas ficaram saneadas até hoje, segundo a palavra que Eliseu tinha dito."},
{v:23,t:"De lá Eliseu subiu a Betel. Enquanto subia pelo caminho, uns rapazes saíram da cidade e zombavam dele, dizendo: Sobe, careca! Sobe, careca!",np:1,n:"Sobe: os rapazes zombam talvez do arrebatamento de Elias. Betel era o centro do culto do bezerro de ouro, hostil aos profetas do Senhor."},
{v:24,t:"Ele se voltou, olhou para eles e os amaldiçoou em nome do Senhor. Saíram do bosque duas ursas e despedaçaram quarenta e dois deles.",n:"A história, que choca o leitor moderno, quer mostrar que zombar do profeta é zombar de Deus. Pertence ao estilo das lendas populares sobre Eliseu, e não deve ser tomada como modelo: Jesus proibirá aos discípulos amaldiçoar os que os rejeitam."},
{v:25,t:"Dali foi para o monte Carmelo, e depois voltou para Samaria."}
];

window.TEXTOS_SEED["2reis"][3] = [
{s:"Jorão, rei de Israel"},
{v:1,t:"Jorão, filho de Acab, começou a reinar sobre Israel, em Samaria, no décimo oitavo ano de Josafá, rei de Judá, e reinou doze anos."},
{v:2,t:"Fez o que é mau aos olhos do Senhor, mas não como seu pai e sua mãe, pois retirou a estela de Baal que seu pai tinha feito."},
{v:3,t:"Mas apegou-se aos pecados de Jeroboão, filho de Nabat, que tinha feito Israel pecar, e não se afastou deles."},
{s:"A guerra contra Moab"},
{v:4,t:"Mesa, rei de Moab, era criador de ovelhas, e pagava ao rei de Israel um tributo de cem mil cordeiros e a lã de cem mil carneiros.",np:1,n:"Mesa deixou uma inscrição, a estela de Mesa, encontrada em 1868, em que narra a sua revolta contra o filho de Amri e atribui a vitória ao seu deus Camos."},
{v:5,t:"Mas, depois da morte de Acab, o rei de Moab revoltou-se contra o rei de Israel."},
{v:6,t:"Então o rei Jorão saiu de Samaria e passou em revista todo o Israel."},
{v:7,t:"Depois mandou dizer a Josafá, rei de Judá: O rei de Moab revoltou-se contra mim. Queres vir comigo combater contra Moab? Ele respondeu: Irei. Eu sou como tu, o meu povo como o teu povo, os meus cavalos como os teus cavalos."},
{v:8,t:"E perguntou: Por que caminho subiremos? Jorão respondeu: Pelo caminho do deserto de Edom.",n:"Para atacar Moab pelo sul, contornando o mar Morto, com o apoio de Edom, então vassalo de Judá."},
{v:9,t:"Partiram, pois, o rei de Israel, o rei de Judá e o rei de Edom. Depois de uma marcha de sete dias em volta, faltou água para o exército e para os animais que os seguiam."},
{v:10,t:"O rei de Israel disse: Ai de nós! O Senhor reuniu estes três reis para entregá-los nas mãos de Moab!"},
{v:11,t:"Mas Josafá perguntou: Não há aqui algum profeta do Senhor, para consultarmos o Senhor por meio dele? Um dos servos do rei de Israel respondeu: Está aqui Eliseu, filho de Safat, que derramava água nas mãos de Elias.",np:1,n:"Derramava água nas mãos de Elias: era o seu servo e discípulo."},
{v:12,t:"Josafá disse: A palavra do Senhor está com ele. E o rei de Israel, Josafá e o rei de Edom desceram até ele."},
{v:13,t:"Eliseu disse ao rei de Israel: Que tenho eu contigo? Vai aos profetas de teu pai e aos profetas de tua mãe. O rei de Israel lhe respondeu: Não! Foi o Senhor que reuniu estes três reis para entregá-los nas mãos de Moab."},
{v:14,t:"Eliseu disse: Pela vida do Senhor dos exércitos, a quem sirvo: se não fosse por respeito a Josafá, rei de Judá, eu nem olharia para ti nem te veria."},
{v:15,t:"Agora, pois, trazei-me um tocador de harpa. E, enquanto o tocador tocava, a mão do Senhor veio sobre Eliseu,",n:"A música dispunha o profeta ao êxtase, como nos grupos de profetas do tempo de Saul (1 Samuel 10,5)."},
{v:16,t:"e ele disse: Assim diz o Senhor: Cavai neste vale muitas covas."},
{v:17,t:"Porque assim diz o Senhor: Não vereis vento nem chuva, e este vale se encherá de água, e bebereis vós, os vossos rebanhos e os vossos animais."},
{v:18,t:"E isso ainda é pouco aos olhos do Senhor: ele entregará também Moab nas vossas mãos."},
{v:19,t:"Destruireis todas as cidades fortificadas e todas as cidades escolhidas; cortareis todas as árvores frutíferas, tapareis todas as fontes de água e cobrireis de pedras todos os campos férteis.",n:"Práticas de guerra que o Deuteronômio proibia, ao menos quanto às árvores frutíferas (Deuteronômio 20,19-20)."},
{v:20,t:"Na manhã seguinte, na hora em que se oferece o sacrifício, eis que vieram águas pelo caminho de Edom, e a terra ficou cheia de água.",n:"Uma tempestade nas montanhas de Edom encheu de repente o vale seco: fenômeno conhecido no deserto."},
{v:21,t:"Todos os moabitas, sabendo que os reis tinham subido para combatê-los, convocaram todos os que podiam cingir o cinturão, dos mais moços aos mais velhos, e postaram-se na fronteira.",np:1},
{v:22,t:"De manhã cedo, quando se levantaram e o sol brilhava sobre as águas, os moabitas viram defronte deles as águas vermelhas como sangue,"},
{v:23,t:"e disseram: É sangue! Os reis combateram entre si e se mataram uns aos outros. E agora, Moab, ao saque!"},
{v:24,t:"E foram ao acampamento de Israel. Mas os israelitas se levantaram e bateram os moabitas, que fugiram diante deles; e os perseguiram, batendo os moabitas."},
{v:25,t:"Destruíram as cidades; cada um atirou a sua pedra em todos os campos férteis, até enchê-los; taparam todas as fontes de água e cortaram todas as árvores frutíferas; só restaram as muralhas de Quir-Haréset, e os fundibulários a cercaram e a atacaram."},
{v:26,t:"Vendo que a batalha estava perdida, o rei de Moab tomou consigo setecentos homens armados de espada, para abrir caminho até o rei de Edom; mas não conseguiram."},
{v:27,t:"Então tomou o seu filho primogênito, que devia reinar em seu lugar, e o ofereceu em holocausto sobre a muralha. Houve grande indignação contra Israel, e eles se retiraram e voltaram para a sua terra.",n:"O sacrifício do filho do rei, ato extremo de súplica ao deus Camos, aterroriza os sitiantes. O texto não explica de onde vem a indignação: talvez o horror do próprio Israel, que se sente culpado de ter levado o inimigo a tal extremo."}
];

window.TEXTOS_SEED["2reis"][4] = [
{s:"O azeite da viúva"},
{v:1,t:"A mulher de um dos filhos dos profetas clamou a Eliseu: O teu servo, meu marido, morreu, e tu sabes que o teu servo temia o Senhor; e agora o credor veio para levar os meus dois filhos como escravos.",n:"A Lei permitia que o devedor insolvente pagasse com o trabalho dos filhos, mas mandava tratá-los como assalariados e libertá-los no ano jubilar (Levítico 25,39-41). Os milagres de Eliseu, contados como pequenas histórias populares, mostram Deus atento aos pobres."},
{v:2,t:"Eliseu lhe disse: Que queres que eu faça por ti? Dize-me: que tens em casa? Ela respondeu: A tua serva não tem nada em casa, senão uma botija de azeite."},
{v:3,t:"Ele disse: Vai, pede emprestadas a todos os teus vizinhos vasilhas vazias, e não poucas;"},
{v:4,t:"depois entra, fecha a porta atrás de ti e dos teus filhos, e derrama o azeite em todas essas vasilhas; e, à medida que forem ficando cheias, põe-nas de lado."},
{v:5,t:"Ela foi e fechou a porta atrás de si e dos filhos: eles lhe traziam as vasilhas, e ela derramava."},
{v:6,t:"Quando as vasilhas ficaram cheias, ela disse a um dos filhos: Traze-me mais uma vasilha. Ele respondeu: Não há mais nenhuma. E o azeite parou."},
{v:7,t:"Ela foi contá-lo ao homem de Deus, e ele disse: Vai, vende o azeite e paga a tua dívida; e tu e os teus filhos vivereis do resto."},
{s:"A sunamita e o seu filho"},
{v:8,t:"Um dia, Eliseu passava por Sunam. Havia ali uma mulher importante, que insistiu com ele para que comesse em sua casa. E, desde então, sempre que passava por ali, ele se hospedava em sua casa para comer.",np:1},
{v:9,t:"Ela disse ao marido: Tenho reparado que este homem que passa sempre por aqui é um santo homem de Deus."},
{v:10,t:"Façamos em cima, no terraço, um pequeno quarto de alvenaria, e ponhamos nele uma cama, uma mesa, uma cadeira e uma lâmpada; assim, quando ele vier à nossa casa, poderá ficar ali."},
{v:11,t:"Um dia, Eliseu chegou, retirou-se para o quarto de cima e descansou ali."},
{v:12,t:"Disse a Giezi, seu servo: Chama esta sunamita. Ele a chamou, e ela se apresentou diante dele."},
{v:13,t:"Eliseu disse a Giezi: Dize-lhe: Tu te deste a todo este trabalho por nossa causa; que posso fazer por ti? Precisas de alguma coisa? Queres que eu fale por ti ao rei ou ao chefe do exército? Ela respondeu: Eu vivo no meio da minha gente.",n:"Eu vivo no meio da minha gente: não preciso de proteção, tenho a minha família e a minha terra."},
{v:14,t:"Eliseu perguntou: Que se pode fazer por ela? Giezi respondeu: Ela não tem filho, e o marido é velho."},
{v:15,t:"Eliseu disse: Chama-a. Ele a chamou, e ela ficou de pé à porta."},
{v:16,t:"Eliseu disse: Por esta época, daqui a um ano, terás um filho nos braços. Ela respondeu: Não, meu senhor, homem de Deus, não enganes a tua serva!",n:"Como Sara, à qual o Senhor anunciou um filho no mesmo prazo (Gênesis 18,10-14)."},
{v:17,t:"A mulher concebeu e deu à luz um filho, na mesma época, um ano depois, como Eliseu lhe tinha dito."},
{v:18,t:"O menino cresceu. Um dia, foi ter com seu pai, junto dos ceifadores,",np:1},
{v:19,t:"e disse ao pai: Ai, a minha cabeça! Ai, a minha cabeça! O pai disse a um servo: Leva-o à mãe dele.",n:"Talvez uma insolação, no calor da colheita."},
{v:20,t:"O servo o tomou e o levou à mãe. Ela o teve no colo até o meio-dia, e ele morreu."},
{v:21,t:"Ela subiu, deitou-o na cama do homem de Deus, fechou a porta e saiu;"},
{v:22,t:"chamou o marido e lhe disse: Manda-me, por favor, um dos servos com uma jumenta; vou correndo ao homem de Deus e volto."},
{v:23,t:"Ele perguntou: Por que vais hoje ter com ele? Não é lua nova nem sábado. Ela respondeu: Fica em paz.",n:"Nos dias de festa, costumava-se visitar os profetas. A mulher não conta nada ao marido: vai, com fé silenciosa, ao homem de Deus."},
{v:24,t:"Mandou selar a jumenta e disse ao servo: Toca, e depressa; não me faças ir devagar, a não ser que eu te mande."},
{v:25,t:"Ela partiu e chegou junto do homem de Deus, no monte Carmelo. Quando o homem de Deus a viu ao longe, disse a Giezi, seu servo: Aí vem a sunamita."},
{v:26,t:"Corre ao seu encontro e pergunta-lhe: Tudo bem contigo? Tudo bem com o teu marido? Tudo bem com o menino? Ela respondeu: Tudo bem."},
{v:27,t:"Mas, quando chegou junto do homem de Deus, no monte, agarrou-se aos seus pés. Giezi aproximou-se para afastá-la, mas o homem de Deus disse: Deixa-a, porque a sua alma está amargurada, e o Senhor me escondeu isso e não me revelou."},
{v:28,t:"Ela disse: Acaso pedi um filho ao meu senhor? Não te disse: Não me enganes?"},
{v:29,t:"Eliseu disse a Giezi: Cinge os rins, toma o meu bastão na mão e vai. Se encontrares alguém, não o saúdes; e, se alguém te saudar, não lhe respondas. E porás o meu bastão sobre o rosto do menino.",n:"Não saudar ninguém pelo caminho: a missão não admite demora. Jesus dará a mesma ordem aos setenta e dois (Lucas 10,4)."},
{v:30,t:"Mas a mãe do menino disse: Pela vida do Senhor e pela tua vida, não te deixarei! Então ele se levantou e a seguiu."},
{v:31,t:"Giezi tinha ido adiante deles e posto o bastão sobre o rosto do menino; mas não houve voz nem sinal de vida. Voltou ao encontro de Eliseu e lhe disse: O menino não acordou.",n:"O bastão, sem a oração e a presença do profeta, não basta: não há magia."},
{v:32,t:"Eliseu entrou na casa, e eis que o menino estava morto, deitado na sua cama.",np:1},
{v:33,t:"Entrou, fechou a porta atrás de si e do menino, e orou ao Senhor."},
{v:34,t:"Depois subiu na cama e deitou-se sobre o menino, pondo a boca sobre a boca dele, os olhos sobre os olhos dele, as mãos sobre as mãos dele; estendeu-se sobre ele, e o corpo do menino se aqueceu.",n:"Como Elias com o filho da viúva de Sarepta (1 Reis 17,21): o profeta dá ao menino, por assim dizer, a sua própria vida."},
{v:35,t:"Depois desceu, andou pela casa de um lado para outro, tornou a subir e estendeu-se sobre ele; e o menino espirrou sete vezes e abriu os olhos."},
{v:36,t:"Eliseu chamou Giezi e disse: Chama esta sunamita. Ele a chamou, e ela entrou. Eliseu disse: Toma o teu filho."},
{v:37,t:"Ela entrou, lançou-se aos seus pés e prostrou-se por terra; depois tomou o filho e saiu."},
{s:"A panela envenenada"},
{v:38,t:"Eliseu voltou a Guilgal. Havia fome no país, e os filhos dos profetas estavam sentados diante dele. Ele disse ao seu servo: Põe a panela grande no fogo e cozinha um caldo para os filhos dos profetas.",np:1},
{v:39,t:"Um deles saiu ao campo para colher ervas; encontrou uma espécie de trepadeira silvestre e colheu dela coloquíntidas silvestres, até encher o manto. Voltou e cortou-as em pedaços na panela do caldo, sem saber o que eram.",n:"A coloquíntida silvestre é um purgante violento, que pode ser mortal."},
{v:40,t:"Serviram aos homens para comerem; mas, ao provarem o caldo, gritaram: A morte está na panela, homem de Deus! E não puderam comer."},
{v:41,t:"Eliseu disse: Trazei farinha. Lançou-a na panela e disse: Serve ao povo, para que coma. E já não havia nada de nocivo na panela."},
{s:"A multiplicação dos pães"},
{v:42,t:"Veio de Baal-Salisa um homem, trazendo ao homem de Deus pães das primícias: vinte pães de cevada e trigo novo no seu alforje. Eliseu disse: Dá ao povo, para que coma.",np:1,n:"As primícias eram oferecidas aos sacerdotes; aqui são trazidas ao profeta, num tempo em que o templo de Jerusalém estava longe do reino do Norte."},
{v:43,t:"Mas o seu servo respondeu: Como posso servir isto a cem homens? Ele repetiu: Dá ao povo, para que coma; porque assim diz o Senhor: Comerão, e ainda sobrará."},
{v:44,t:"Ele serviu-lhes; comeram, e ainda sobrou, segundo a palavra do Senhor.",n:"Os pães de cevada, a pergunta do servo e as sobras anunciam a multiplicação dos pães por Jesus, que os Evangelhos contam com as mesmas palavras (João 6,9-13)."}
];

window.TEXTOS_SEED["2reis"][5] = [
{s:"A cura de Naamã"},
{v:1,t:"Naamã, chefe do exército do rei da Síria, era um homem importante e estimado pelo seu senhor, porque foi por meio dele que o Senhor deu a vitória à Síria. Mas esse homem valente era leproso.",n:"O Senhor dá a vitória até aos inimigos de Israel: o Deus de Israel é o Senhor de todos os povos. Jesus lembrará que Naamã, um estrangeiro, foi purificado, enquanto muitos leprosos de Israel não o foram (Lucas 4,27)."},
{v:2,t:"Um bando de arameus tinha feito uma incursão na terra de Israel e levado cativa uma menina, que ficou a serviço da mulher de Naamã."},
{v:3,t:"Ela disse à sua senhora: Ah, se o meu senhor fosse ter com o profeta que está em Samaria! Ele o curaria da lepra.",n:"A salvação chega a Naamã pela boca de uma escrava estrangeira, que não guarda rancor aos seus senhores."},
{v:4,t:"Naamã foi contar ao seu senhor: Assim e assim falou a menina da terra de Israel."},
{v:5,t:"O rei da Síria lhe disse: Vai, e eu mandarei uma carta ao rei de Israel. Naamã partiu, levando consigo dez talentos de prata, seis mil siclos de ouro e dez mudas de roupa;"},
{v:6,t:"e entregou ao rei de Israel a carta, que dizia: Com esta carta, fica sabendo que te envio Naamã, meu servo, para que o cures da sua lepra."},
{v:7,t:"Quando o rei de Israel leu a carta, rasgou as vestes e disse: Acaso sou Deus, para dar a morte e a vida, para que este me mande curar um homem da sua lepra? Vede bem: ele procura pretexto contra mim!",n:"Só Deus faz morrer e faz viver (Deuteronômio 32,39). O rei não pensa no profeta."},
{v:8,t:"Quando Eliseu, o homem de Deus, soube que o rei de Israel tinha rasgado as vestes, mandou dizer ao rei: Por que rasgaste as vestes? Que ele venha a mim, e saberá que há um profeta em Israel."},
{v:9,t:"Naamã veio com os seus cavalos e os seus carros, e parou à porta da casa de Eliseu.",np:1},
{v:10,t:"Eliseu mandou-lhe dizer por um mensageiro: Vai, lava-te sete vezes no Jordão, e a tua carne ficará sã, e ficarás puro."},
{v:11,t:"Naamã irritou-se e foi-se embora, dizendo: Eu pensava que ele sairia ao meu encontro e, de pé, invocaria o nome do Senhor seu Deus, passaria a mão sobre o lugar doente e me curaria da lepra.",n:"Naamã esperava uma cerimônia à altura da sua importância; o profeta nem sequer sai de casa. A cura exige primeiro a humildade."},
{v:12,t:"Os rios de Damasco, o Abana e o Farfar, não são melhores que todas as águas de Israel? Não poderia eu lavar-me neles e ficar puro? E, voltando as costas, ia-se embora indignado."},
{v:13,t:"Mas os seus servos aproximaram-se e lhe disseram: Se o profeta te tivesse mandado fazer uma coisa difícil, não a farias? Quanto mais agora que ele te diz: Lava-te e ficarás puro!"},
{v:14,t:"Ele desceu e mergulhou sete vezes no Jordão, segundo a palavra do homem de Deus; e a sua carne tornou-se como a carne de uma criança, e ele ficou puro.",n:"A tradição cristã viu neste banho no Jordão uma figura do batismo."},
{v:15,t:"Voltou ao homem de Deus com toda a sua comitiva, apresentou-se diante dele e disse: Agora sei que não há Deus em toda a terra, senão em Israel! Aceita, pois, peço-te, um presente do teu servo.",np:1},
{v:16,t:"Mas Eliseu respondeu: Pela vida do Senhor, a quem sirvo, não aceitarei nada. Naamã insistiu, mas ele recusou.",n:"O dom de Deus é gratuito: o profeta não se deixa pagar. De graça recebestes, de graça dai (Mateus 10,8)."},
{v:17,t:"Naamã disse: Seja como queres. Mas permite que se dê ao teu servo a terra que duas mulas podem carregar; porque o teu servo não oferecerá mais holocausto nem sacrifício a outros deuses, senão ao Senhor.",n:"Segundo a mentalidade antiga, cada deus era adorado na sua terra: Naamã leva terra de Israel para poder adorar o Senhor em Damasco."},
{v:18,t:"Mas que o Senhor perdoe ao teu servo uma só coisa: quando o meu senhor entrar no templo de Remon para adorar, apoiado no meu braço, e eu me prostrar no templo de Remon enquanto ele ali se prostra, que o Senhor perdoe ao teu servo por isso.",n:"Remon, ou Hadad-Remon, era o deus da tempestade dos arameus. Naamã pede compreensão para um gesto exterior que as suas funções lhe impõem."},
{v:19,t:"Eliseu lhe disse: Vai em paz. E ele se afastou dele uma pequena distância.",n:"O profeta não exige do estrangeiro recém-convertido mais do que ele pode dar."},
{s:"O castigo de Giezi"},
{v:20,t:"Então Giezi, servo de Eliseu, homem de Deus, pensou: O meu senhor poupou este arameu, Naamã, não aceitando nada do que ele trouxe; pela vida do Senhor, vou correr atrás dele e aceitar alguma coisa.",np:1},
{v:21,t:"E Giezi foi atrás de Naamã. Quando Naamã o viu correndo atrás dele, desceu do carro ao seu encontro e perguntou: Está tudo bem?"},
{v:22,t:"Ele respondeu: Está tudo bem. O meu senhor me manda dizer: Acabam de chegar da montanha de Efraim dois jovens dos filhos dos profetas; dá-lhes, por favor, um talento de prata e duas mudas de roupa."},
{v:23,t:"Naamã disse: Aceita, antes, dois talentos. Insistiu com ele, amarrou dois talentos de prata em dois sacos, com duas mudas de roupa, e os deu a dois dos seus servos, que os levaram adiante de Giezi."},
{v:24,t:"Chegando à colina, Giezi tomou-os das mãos deles, guardou-os em casa e despediu os homens, que se foram."},
{v:25,t:"Depois foi apresentar-se diante do seu senhor. Eliseu lhe perguntou: De onde vens, Giezi? Ele respondeu: O teu servo não foi a lugar nenhum."},
{v:26,t:"Mas Eliseu lhe disse: Não estava presente o meu espírito quando o homem desceu do carro ao teu encontro? Acaso é tempo de aceitar prata e roupas, olivais e vinhas, ovelhas e bois, servos e servas?",n:"Giezi vende o dom de Deus que o profeta dera de graça: é o pecado que mais tarde se chamará simonia (Atos 8,18-20)."},
{v:27,t:"Por isso a lepra de Naamã se apegará a ti e à tua descendência para sempre. E Giezi saiu da sua presença leproso, branco como a neve."}
];

window.TEXTOS_SEED["2reis"][6] = [
{s:"O machado que flutuou"},
{v:1,t:"Os filhos dos profetas disseram a Eliseu: O lugar onde moramos junto de ti é pequeno demais para nós."},
{v:2,t:"Vamos até o Jordão; cada um tirará de lá uma viga, e construiremos ali um lugar para morarmos. Ele respondeu: Ide."},
{v:3,t:"Um deles disse: Vem também tu com os teus servos. Ele respondeu: Irei."},
{v:4,t:"E foi com eles. Chegando ao Jordão, começaram a cortar árvores."},
{v:5,t:"Enquanto um deles derrubava uma viga, o ferro do machado caiu na água; e ele gritou: Ai, meu senhor! Era emprestado!",n:"O ferro era raro e caro; o pobre profeta não teria como pagá-lo."},
{v:6,t:"O homem de Deus perguntou: Onde caiu? Ele lhe mostrou o lugar. Então Eliseu cortou um pedaço de pau, lançou-o ali e fez flutuar o ferro."},
{v:7,t:"E disse: Apanha-o. O homem estendeu a mão e o apanhou."},
{s:"Eliseu e os arameus cegos"},
{v:8,t:"O rei da Síria estava em guerra contra Israel. Deliberou com os seus servos, dizendo: Armaremos uma emboscada em tal e tal lugar.",np:1},
{v:9,t:"Mas o homem de Deus mandou dizer ao rei de Israel: Guarda-te de passar por tal lugar, porque os arameus estão ali em emboscada."},
{v:10,t:"O rei de Israel mandou gente ao lugar que o homem de Deus lhe indicara e sobre o qual o prevenira; e assim se guardou dali, não uma nem duas vezes."},
{v:11,t:"O coração do rei da Síria ficou perturbado com isso; convocou os seus servos e lhes disse: Não me direis quem dos nossos está do lado do rei de Israel?"},
{v:12,t:"Um dos seus servos respondeu: Ninguém, ó rei, meu senhor; mas Eliseu, o profeta que está em Israel, revela ao rei de Israel até as palavras que dizes no teu quarto de dormir."},
{v:13,t:"O rei disse: Ide ver onde ele está, para que eu mande prendê-lo. Informaram-lhe: Ele está em Dotã."},
{v:14,t:"O rei mandou para lá cavalos, carros e um forte destacamento, que chegaram de noite e cercaram a cidade."},
{v:15,t:"De manhã cedo, o servo do homem de Deus levantou-se e saiu, e viu que um exército cercava a cidade, com cavalos e carros. E disse a Eliseu: Ai, meu senhor, que faremos?"},
{v:16,t:"Ele respondeu: Não tenhas medo, porque os que estão conosco são mais numerosos que os que estão com eles."},
{v:17,t:"E Eliseu orou: Senhor, abre os olhos deste rapaz, para que ele veja. O Senhor abriu os olhos do rapaz, e ele viu: o monte estava cheio de cavalos e carros de fogo em volta de Eliseu.",n:"Os carros de fogo que levaram Elias protegem agora o seu discípulo. A fé vê o que os olhos não veem."},
{v:18,t:"Os arameus desceram contra ele, e Eliseu orou ao Senhor: Fere esta gente de cegueira! E o Senhor os feriu de cegueira, segundo a palavra de Eliseu."},
{v:19,t:"Eliseu lhes disse: Não é este o caminho, nem é esta a cidade. Segui-me, e eu vos levarei ao homem que procurais. E os levou a Samaria."},
{v:20,t:"Quando entraram em Samaria, Eliseu disse: Senhor, abre os olhos destes homens, para que vejam. O Senhor abriu-lhes os olhos, e eles viram que estavam no meio de Samaria."},
{v:21,t:"Quando o rei de Israel os viu, disse a Eliseu: Devo matá-los, meu pai?"},
{v:22,t:"Ele respondeu: Não os mates. Acaso matas os que fizeste prisioneiros com a tua espada e o teu arco? Serve-lhes pão e água, para que comam e bebam, e depois voltem para o seu senhor.",n:"Em vez da morte, um banquete: o profeta vence o inimigo com a misericórdia. Paulo dirá: se o teu inimigo tiver fome, dá-lhe de comer (Romanos 12,20)."},
{v:23,t:"Prepararam-lhes um grande banquete; comeram e beberam, e ele os despediu, e eles voltaram para o seu senhor. E os bandos arameus não voltaram mais à terra de Israel."},
{s:"A fome em Samaria"},
{v:24,t:"Depois disso, Ben-Adad, rei da Síria, reuniu todo o seu exército, subiu e sitiou Samaria.",np:1,n:"As histórias de Eliseu não seguem uma ordem cronológica: os arameus, que não deviam voltar, voltam."},
{v:25,t:"Houve grande fome em Samaria, e o cerco durou tanto que uma cabeça de jumento chegou a valer oitenta siclos de prata, e um quarto de cabo de esterco de pombas, cinco siclos de prata.",n:"A cabeça de jumento, animal impuro, era o que havia de pior. O esterco de pombas era talvez o nome popular de uma planta silvestre, ou de uma vagem comestível."},
{v:26,t:"Quando o rei de Israel passava pela muralha, uma mulher gritou-lhe: Socorro, ó rei, meu senhor!"},
{v:27,t:"Ele respondeu: Se o Senhor não te socorre, de onde poderei eu socorrer-te? Da eira ou do lagar? E o rei lhe perguntou: Que tens? Ela respondeu:"},
{v:28,t:"Esta mulher me disse: Dá o teu filho, para que o comamos hoje, e amanhã comeremos o meu."},
{v:29,t:"Cozinhamos o meu filho e o comemos. No dia seguinte eu lhe disse: Dá o teu filho, para que o comamos; mas ela escondeu o seu filho.",n:"O horror extremo da fome no cerco, anunciado pela maldição do Deuteronômio (Deuteronômio 28,53-57) e lamentado depois nas Lamentações (4,10)."},
{v:30,t:"Ao ouvir as palavras da mulher, o rei rasgou as vestes; e, como ele passava sobre a muralha, o povo viu que por baixo trazia um pano de saco sobre o corpo."},
{v:31,t:"E ele disse: Que Deus me faça isto e mais aquilo, se hoje a cabeça de Eliseu, filho de Safat, ficar sobre os seus ombros!",n:"O rei culpa o profeta pela desgraça, talvez porque Eliseu aconselhava a resistência."},
{v:32,t:"Eliseu estava sentado em sua casa, e os anciãos estavam sentados com ele. O rei enviou um homem adiante de si; mas, antes que o mensageiro chegasse, Eliseu disse aos anciãos: Vedes que esse filho de assassino mandou cortar-me a cabeça? Prestai atenção: quando o mensageiro chegar, fechai a porta e não o deixeis entrar. Não se ouve já atrás dele o ruído dos passos do seu senhor?",np:1,n:"Filho de assassino: filho de Acab, que matou Nabot e os profetas."},
{v:33,t:"Ele ainda estava falando com eles quando apareceu o rei, que descia até ele, e disse: Eis que esta desgraça vem do Senhor; que posso ainda esperar do Senhor?"}
];

window.TEXTOS_SEED["2reis"][7] = [
{s:"O fim do cerco"},
{v:1,t:"Eliseu disse: Ouvi a palavra do Senhor. Assim diz o Senhor: Amanhã, a esta hora, uma medida de flor de farinha valerá um siclo, e duas medidas de cevada valerão um siclo, à porta de Samaria."},
{v:2,t:"O oficial em cujo braço o rei se apoiava respondeu ao homem de Deus: Ainda que o Senhor abrisse janelas no céu, poderia acontecer o que dizes? Eliseu respondeu: Tu o verás com os teus olhos, mas não comerás disso.",n:"Janelas no céu: as comportas por onde caía a chuva, segundo a imagem antiga do mundo (Gênesis 7,11)."},
{s:"Os quatro leprosos"},
{v:3,t:"Havia quatro leprosos à entrada da porta, que disseram uns aos outros: Por que ficarmos aqui até morrer?",np:1,n:"Os leprosos viviam fora das muralhas (Levítico 13,46). A salvação da cidade será anunciada pelos excluídos."},
{v:4,t:"Se resolvermos entrar na cidade, morreremos lá, porque há fome na cidade; e, se ficarmos aqui, também morreremos. Vamos, pois, passar para o acampamento dos arameus: se nos pouparem a vida, viveremos; se nos matarem, morreremos."},
{v:5,t:"Levantaram-se ao anoitecer para ir ao acampamento dos arameus; e, quando chegaram à entrada do acampamento, não havia ali ninguém."},
{v:6,t:"Porque o Senhor tinha feito ouvir no acampamento dos arameus um ruído de carros, de cavalos e de um grande exército, e eles disseram uns aos outros: O rei de Israel contratou contra nós os reis dos heteus e os reis do Egito, para virem atacar-nos!"},
{v:7,t:"Levantaram-se e fugiram ao escurecer, abandonando as tendas, os cavalos e os jumentos, o acampamento tal como estava; e fugiram para salvar a vida."},
{v:8,t:"Os leprosos chegaram à entrada do acampamento, entraram numa tenda, comeram e beberam, e levaram de lá prata, ouro e roupas, e foram escondê-los. Voltaram, entraram em outra tenda, levaram também o que havia e foram escondê-lo."},
{v:9,t:"Depois disseram uns aos outros: Não estamos agindo bem. Hoje é dia de boas notícias, e nós ficamos calados! Se esperarmos até o amanhecer, seremos castigados. Vamos, pois, avisar o palácio do rei.",n:"A boa notícia não se guarda para si: é preciso anunciá-la. A palavra hebraica, besorá, é a que os gregos traduzirão por evangelho."},
{v:10,t:"Foram, chamaram os porteiros da cidade e lhes contaram: Fomos ao acampamento dos arameus, e não há ali ninguém, nem voz humana; só há cavalos e jumentos amarrados, e as tendas tal como estavam."},
{v:11,t:"Os porteiros gritaram a notícia, e ela foi anunciada dentro do palácio do rei."},
{v:12,t:"O rei levantou-se de noite e disse aos seus servos: Vou dizer-vos o que os arameus nos fizeram. Sabem que estamos passando fome; por isso saíram do acampamento e se esconderam no campo, pensando: Quando saírem da cidade, nós os prenderemos vivos e entraremos na cidade.",np:1},
{v:13,t:"Um dos seus servos respondeu: Tomemos cinco dos cavalos que restam na cidade — de qualquer modo, terão a sorte de toda a multidão de Israel que já pereceu —, e mandemos ver."},
{v:14,t:"Tomaram dois carros com cavalos, e o rei os mandou atrás do exército arameu, dizendo: Ide e vede."},
{v:15,t:"Eles os seguiram até o Jordão; e todo o caminho estava cheio de roupas e objetos que os arameus tinham jogado fora na sua fuga precipitada. Os mensageiros voltaram e contaram tudo ao rei."},
{v:16,t:"Então o povo saiu e saqueou o acampamento dos arameus; e uma medida de flor de farinha passou a valer um siclo, e duas medidas de cevada, um siclo, segundo a palavra do Senhor.",np:1},
{v:17,t:"O rei tinha posto de guarda à porta o oficial em cujo braço se apoiava; e o povo o pisoteou na porta, e ele morreu, como o homem de Deus tinha dito quando o rei descera até ele."},
{v:18,t:"Aconteceu segundo a palavra que o homem de Deus tinha dito ao rei: Amanhã, a esta hora, duas medidas de cevada valerão um siclo, e uma medida de flor de farinha, um siclo, à porta de Samaria;"},
{v:19,t:"quando o oficial respondeu ao homem de Deus: Ainda que o Senhor abrisse janelas no céu, poderia acontecer o que dizes?, e ele lhe disse: Tu o verás com os teus olhos, mas não comerás disso."},
{v:20,t:"Foi isso mesmo o que lhe aconteceu: o povo o pisoteou na porta, e ele morreu.",n:"A repetição insiste: a palavra do profeta se cumpre até o fim, para o bem e para o mal."}
];

window.TEXTOS_SEED["2reis"][8] = [
{s:"A sunamita recupera as suas terras"},
{v:1,t:"Eliseu tinha dito à mulher cujo filho ele fizera reviver: Levanta-te, vai com a tua família morar onde puderes, como estrangeira, porque o Senhor chamou a fome, e ela virá sobre a terra durante sete anos."},
{v:2,t:"A mulher levantou-se e fez segundo a palavra do homem de Deus: partiu com a sua família e morou sete anos como estrangeira na terra dos filisteus."},
{v:3,t:"Ao fim dos sete anos, a mulher voltou da terra dos filisteus e foi reclamar ao rei a sua casa e os seus campos.",n:"Na sua ausência, as terras tinham passado para outros, talvez para a coroa."},
{v:4,t:"O rei estava conversando com Giezi, o servo do homem de Deus, dizendo: Conta-me todas as grandes coisas que Eliseu fez.",n:"Giezi ainda está a serviço do profeta: o episódio é talvez anterior à sua lepra (5,27)."},
{v:5,t:"E, enquanto ele contava ao rei como Eliseu tinha feito reviver um morto, chegou a mulher cujo filho ele fizera reviver, reclamando ao rei a sua casa e os seus campos. E Giezi disse: Ó rei, meu senhor, esta é a mulher, e este é o seu filho, que Eliseu fez reviver!"},
{v:6,t:"O rei interrogou a mulher, e ela lhe contou tudo. Então o rei confiou o caso a um oficial, dizendo: Restitui-lhe tudo o que lhe pertence, com todos os rendimentos dos campos, desde o dia em que ela deixou a terra até hoje."},
{s:"Eliseu e Hazael"},
{v:7,t:"Eliseu foi a Damasco. Ben-Adad, rei da Síria, estava doente, e lhe informaram: O homem de Deus veio até aqui.",np:1},
{v:8,t:"O rei disse a Hazael: Toma contigo um presente, vai ao encontro do homem de Deus e consulta por meio dele o Senhor, perguntando: Sobreviverei a esta doença?"},
{v:9,t:"Hazael foi ao seu encontro, levando consigo um presente, tudo o que havia de melhor em Damasco, a carga de quarenta camelos. Chegando, apresentou-se diante dele e disse: Teu filho Ben-Adad, rei da Síria, mandou-me perguntar-te: Sobreviverei a esta doença?"},
{v:10,t:"Eliseu lhe disse: Vai e dize-lhe: Sararás. Mas o Senhor me mostrou que ele certamente morrerá.",n:"A doença não o matará; mas Hazael o matará. O hebraico pode também ler-se: Dize-lhe: Não viverás."},
{v:11,t:"E o homem de Deus ficou com o olhar fixo nele, perturbado, até que o rosto se lhe cobriu de rubor; e o homem de Deus chorou."},
{v:12,t:"Hazael perguntou: Por que o meu senhor chora? Ele respondeu: Porque sei o mal que farás aos filhos de Israel: incendiarás as suas cidades fortificadas, matarás à espada os seus jovens, esmagarás as suas crianças e rasgarás o ventre das suas mulheres grávidas.",n:"O profeta chora sobre o seu povo, como Jesus chorará sobre Jerusalém (Lucas 19,41-44)."},
{v:13,t:"Hazael disse: Que é o teu servo, este cão, para fazer uma coisa tão grande? Eliseu respondeu: O Senhor me mostrou que serás rei da Síria.",n:"Assim Eliseu cumpre a missão confiada a Elias no Horeb (1 Reis 19,15)."},
{v:14,t:"Hazael deixou Eliseu e voltou ao seu senhor, que lhe perguntou: Que te disse Eliseu? Ele respondeu: Disse-me que certamente sararás."},
{v:15,t:"No dia seguinte, tomou uma coberta, molhou-a na água e estendeu-a sobre o rosto do rei, e ele morreu. E Hazael reinou em seu lugar.",n:"As inscrições assírias chamam Hazael filho de ninguém, isto é, usurpador."},
{s:"Jorão, rei de Judá"},
{v:16,t:"No quinto ano de Jorão, filho de Acab, rei de Israel — sendo Josafá rei de Judá —, Jorão, filho de Josafá, começou a reinar sobre Judá.",np:1},
{v:17,t:"Tinha trinta e dois anos quando começou a reinar, e reinou oito anos em Jerusalém."},
{v:18,t:"Andou no caminho dos reis de Israel, como tinha feito a casa de Acab, porque tinha casado com uma filha de Acab; e fez o que é mau aos olhos do Senhor.",n:"A filha de Acab é Atalia (versículo 26): a aliança com a casa de Acab introduz em Judá o culto de Baal."},
{v:19,t:"Mas o Senhor não quis destruir Judá, por amor de Davi, seu servo, conforme lhe tinha prometido dar sempre uma lâmpada, a ele e aos seus filhos."},
{v:20,t:"No seu tempo, Edom revoltou-se contra o domínio de Judá e fez para si um rei."},
{v:21,t:"Jorão foi a Seira com todos os seus carros; levantou-se de noite e bateu os edomitas, que o tinham cercado, e os comandantes dos carros; mas o povo fugiu para as suas tendas."},
{v:22,t:"Assim Edom se separou do domínio de Judá, até hoje. Naquele tempo também Lebna se revoltou."},
{v:23,t:"O resto dos feitos de Jorão, tudo o que ele fez, não está escrito no livro dos Anais dos Reis de Judá?"},
{v:24,t:"Jorão adormeceu com seus pais e foi sepultado com eles na Cidade de Davi; e seu filho Ocozias reinou em seu lugar."},
{s:"Ocozias, rei de Judá"},
{v:25,t:"No décimo segundo ano de Jorão, filho de Acab, rei de Israel, Ocozias, filho de Jorão, rei de Judá, começou a reinar.",np:1},
{v:26,t:"Ocozias tinha vinte e dois anos quando começou a reinar, e reinou um ano em Jerusalém. Sua mãe chamava-se Atalia, neta de Amri, rei de Israel.",n:"À letra, filha de Amri: na linguagem da Bíblia, a descendente."},
{v:27,t:"Andou no caminho da casa de Acab e fez o que é mau aos olhos do Senhor, como a casa de Acab, porque era aparentado com a casa de Acab."},
{v:28,t:"Foi com Jorão, filho de Acab, combater contra Hazael, rei da Síria, em Ramot de Galaad; e os arameus feriram Jorão."},
{v:29,t:"O rei Jorão voltou a Jezrael para se tratar das feridas que os arameus lhe tinham feito em Ramá, quando combatia contra Hazael, rei da Síria. E Ocozias, filho de Jorão, rei de Judá, desceu a Jezrael para visitar Jorão, filho de Acab, que estava doente.",n:"Os dois reis, primos e aliados, estarão juntos em Jezrael quando chegar a revolta de Jeú."}
];
