// =====================================================================
// II Samuel — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["2samuel"][1] = [
{s:"Davi sabe da morte de Saul"},
{v:1,t:"Depois da morte de Saul, Davi voltou da vitória sobre os amalecitas e ficou dois dias em Siceleg.",n:"O Segundo Livro de Samuel continua sem interrupção o primeiro: na Bíblia hebraica os dois formavam um só livro. É a história do reinado de Davi: a sua ascensão (capítulos 1 a 10), o seu pecado e as desgraças da sua casa (11 a 20), e alguns apêndices (21 a 24)."},
{v:2,t:"No terceiro dia, chegou do acampamento de Saul um homem com as vestes rasgadas e a cabeça coberta de terra. Ao chegar junto de Davi, lançou-se por terra e prostrou-se."},
{v:3,t:"Davi perguntou-lhe: De onde vens? Ele respondeu: Fugi do acampamento de Israel."},
{v:4,t:"Davi perguntou: Que aconteceu? Conta-me. Ele respondeu: O povo fugiu da batalha, e muitos do povo caíram mortos; e também Saul e seu filho Jônatas morreram."},
{v:5,t:"Davi perguntou ao jovem que lhe trazia a notícia: Como sabes que Saul e seu filho Jônatas estão mortos?",np:1},
{v:6,t:"O jovem que lhe dava a notícia respondeu: Por acaso eu estava no monte Gelboé, e Saul estava apoiado na sua lança, e os carros e os cavaleiros se aproximavam dele.",n:"Esta versão contradiz a de 1 Samuel 31, onde Saul se lança sobre a própria espada. O amalecita mente, ou exagera, esperando uma recompensa do novo rei."},
{v:7,t:"Voltando-se para trás, ele me viu e me chamou. Eu respondi: Aqui estou."},
{v:8,t:"Ele me perguntou: Quem és tu? Respondi: Sou um amalecita."},
{v:9,t:"Ele me disse: Põe-te sobre mim e mata-me, porque me tomou a agonia, e a vida ainda está toda em mim."},
{v:10,t:"Pus-me sobre ele e o matei, porque sabia que ele não sobreviveria à sua queda. Depois tomei o diadema que tinha na cabeça e o bracelete que tinha no braço, e os trouxe aqui ao meu senhor."},
{v:11,t:"Davi tomou as suas vestes e as rasgou, e o mesmo fizeram todos os homens que estavam com ele;",np:1},
{v:12,t:"e lamentaram-se, choraram e jejuaram até a tarde por Saul e por seu filho Jônatas, pelo povo do Senhor e pela casa de Israel, porque tinham caído pela espada."},
{v:13,t:"Davi perguntou ao jovem que lhe trouxera a notícia: De onde és? Ele respondeu: Sou filho de um estrangeiro, de um amalecita.",np:1,n:"Filho de um estrangeiro residente: vivia em Israel e estava sujeito às suas leis; não podia alegar ignorância."},
{v:14,t:"Davi lhe disse: Como não tiveste medo de estender a mão para matar o ungido do Senhor?"},
{v:15,t:"Davi chamou um dos seus rapazes e disse: Aproxima-te e mata-o! Ele o feriu, e ele morreu."},
{v:16,t:"E Davi lhe disse: O teu sangue caia sobre a tua cabeça, porque a tua própria boca te acusou, quando disseste: Eu matei o ungido do Senhor.",n:"Davi, que por duas vezes poupou Saul, não pode recompensar quem se gaba de o ter matado. E mostra a todo o Israel que não teve parte na morte do rei."},
{s:"O lamento de Davi por Saul e Jônatas"},
{v:17,t:"Davi entoou esta lamentação sobre Saul e sobre seu filho Jônatas,",np:1},
{v:18,t:"e mandou ensiná-la aos filhos de Judá: é o Cântico do Arco, que está escrito no livro do Justo. Ele disse:",n:"O Cântico do Arco, talvez por causa do arco de Jônatas (versículo 22). O livro do Justo era uma coleção de cânticos antigos, hoje perdida, citada também em Josué 10,13. A elegia é considerada obra autêntica de Davi: nela não se menciona Deus, apenas a dor humana."},
{v:19,l:["Os teus nobres, ó Israel, jazem mortos sobre os teus montes!","Como caíram os heróis!"]},
{v:20,l:["Não o anuncieis em Gat,","não o publiqueis nas ruas de Ascalon,","para que não se alegrem as filhas dos filisteus,","para que não exultem as filhas dos incircuncisos."],n:"As mulheres dos vencedores saíam a cantar a vitória, como as de Israel depois da morte de Golias (1 Samuel 18,6-7)."},
{v:21,l:["Montes de Gelboé, não caia sobre vós orvalho nem chuva,","nem haja em vós campos de primícias!","Porque ali foi aviltado o escudo dos heróis,","o escudo de Saul, como se não fosse ungido com óleo."],n:"Os escudos de couro eram untados com óleo antes do combate. A imagem sugere também a unção do rei, agora profanada."},
{v:22,l:["Do sangue dos feridos, da gordura dos heróis,","o arco de Jônatas nunca recuou,","e a espada de Saul não voltava vazia."]},
{v:23,l:["Saul e Jônatas, amáveis e encantadores na vida,","nem na morte se separaram;","eram mais velozes que as águias,","mais fortes que os leões."],n:"Nem na morte se separaram: apesar do conflito entre pai e filho por causa de Davi, Jônatas morreu ao lado de Saul."},
{v:24,l:["Filhas de Israel, chorai por Saul,","que vos vestia de escarlate e de delícias,","que punha enfeites de ouro nos vossos vestidos."]},
{v:25,l:["Como caíram os heróis no meio da batalha!","Jônatas jaz morto sobre os teus montes."]},
{v:26,l:["Estou em angústia por ti, meu irmão Jônatas;","tu me eras tão querido!","A tua amizade me era mais preciosa","do que o amor das mulheres."],n:"O amor de Jônatas não buscava nada para si: renunciou ao trono por Davi. É o que Davi celebra acima de todo outro afeto."},
{v:27,l:["Como caíram os heróis,","e pereceram as armas de guerra!"]}
];

window.TEXTOS_SEED["2samuel"][2] = [
{s:"Davi rei de Judá em Hebron"},
{v:1,t:"Depois disso, Davi consultou o Senhor, dizendo: Devo subir a alguma das cidades de Judá? O Senhor lhe respondeu: Sobe. Davi perguntou: Para onde subirei? Ele respondeu: Para Hebron.",n:"Hebron, a antiga cidade de Abraão, era o centro da tribo de Judá."},
{v:2,t:"Davi subiu para lá com as suas duas mulheres, Aquinoam de Jezrael e Abigail de Carmel, mulher de Nabal."},
{v:3,t:"Davi fez subir também os homens que estavam com ele, cada um com a sua família, e estabeleceram-se nas cidades dos arredores de Hebron."},
{v:4,t:"Vieram os homens de Judá e ali ungiram Davi rei sobre a casa de Judá. Contaram a Davi que os homens de Jabes de Galaad tinham sepultado Saul,",n:"Davi é ungido pela segunda vez, agora publicamente, pelos homens da sua tribo. Será ungido uma terceira vez por todo o Israel (5,3)."},
{v:5,t:"e Davi enviou mensageiros aos homens de Jabes de Galaad, para lhes dizer: Benditos sejais do Senhor, porque tivestes esta piedade para com Saul, vosso senhor, e o sepultastes.",np:1},
{v:6,t:"Agora, pois, que o Senhor use convosco de bondade e fidelidade; e também eu vos farei bem, porque fizestes isso."},
{v:7,t:"E agora, tende coragem e sede valentes; porque Saul, vosso senhor, morreu, mas a casa de Judá me ungiu seu rei.",n:"Ao agradecer, Davi convida discretamente Jabes a reconhecê-lo como sucessor de Saul."},
{s:"Isbaal rei de Israel"},
{v:8,t:"Abner, filho de Ner, chefe do exército de Saul, tomou Isbaal, filho de Saul, levou-o para Maanaim",np:1,n:"Isbaal quer dizer homem do senhor; baal, senhor, era também o nome do deus cananeu. Por isso o texto hebraico o chama Isbosete, homem da vergonha, substituindo o nome do ídolo. A Nova Vulgata restitui o nome original. Maanaim ficava a leste do Jordão, fora do alcance dos filisteus, que dominavam então o oeste."},
{v:9,t:"e o constituiu rei sobre Galaad, sobre Aser, sobre Jezrael, sobre Efraim, sobre Benjamim e sobre todo o Israel."},
{v:10,t:"Isbaal, filho de Saul, tinha quarenta anos quando começou a reinar sobre Israel, e reinou dois anos. Só a casa de Judá seguia Davi."},
{v:11,t:"O tempo que Davi reinou em Hebron sobre a casa de Judá foi de sete anos e seis meses."},
{s:"A guerra entre as duas casas"},
{v:12,t:"Abner, filho de Ner, saiu de Maanaim com os servos de Isbaal, filho de Saul, em direção a Gabaon.",np:1},
{v:13,t:"Joab, filho de Sárvia, também saiu com os servos de Davi, e encontraram-se junto ao tanque de Gabaon. Pararam uns de um lado do tanque e os outros do outro lado."},
{v:14,t:"Abner disse a Joab: Que os jovens se levantem e lutem diante de nós. Joab respondeu: Que se levantem."},
{v:15,t:"Levantaram-se e avançaram em número igual: doze de Benjamim, por parte de Isbaal, filho de Saul, e doze dos servos de Davi."},
{v:16,t:"Cada um agarrou o adversário pela cabeça e cravou-lhe a espada no flanco, e caíram todos juntos. Por isso aquele lugar, que fica em Gabaon, foi chamado Campo dos Flancos.",n:"Assim a Nova Vulgata, lembrando as espadas cravadas nos flancos; o nome hebraico, Helcat-Hasurim, quer dizer talvez campo das lâminas. O duelo, que devia decidir a guerra, termina empatado e desencadeia a batalha."},
{v:17,t:"Travou-se naquele dia uma batalha muito dura, e Abner e os homens de Israel foram derrotados pelos servos de Davi."},
{v:18,t:"Estavam ali os três filhos de Sárvia: Joab, Abisai e Asael. Asael era ligeiro de pés como uma gazela do campo.",np:1},
{v:19,t:"Asael perseguiu Abner, sem se desviar para a direita nem para a esquerda na perseguição."},
{v:20,t:"Abner olhou para trás e perguntou: És tu Asael? Ele respondeu: Sou eu."},
{v:21,t:"Abner lhe disse: Desvia-te para a direita ou para a esquerda, agarra um dos jovens e toma para ti os seus despojos. Mas Asael não quis deixar de persegui-lo."},
{v:22,t:"Abner tornou a dizer a Asael: Afasta-te, deixa de me seguir; por que hei de ser obrigado a te abater? Como poderia eu olhar de frente para Joab, teu irmão?"},
{v:23,t:"Mas ele não quis desviar-se. Então Abner o feriu no ventre com a ponta traseira da lança, e a lança saiu-lhe pelas costas; e ele caiu e morreu ali mesmo. Todos os que passavam pelo lugar onde Asael tinha caído morto se detinham.",n:"Abner mata o jovem contra a vontade, e sabe que abriu uma dívida de sangue com Joab. Ela será cobrada (3,27)."},
{v:24,t:"Joab e Abisai perseguiram Abner. Ao pôr do sol chegaram à colina de Ama, que fica defronte de Gia, no caminho do deserto de Gabaon.",np:1},
{v:25,t:"Os filhos de Benjamim reuniram-se atrás de Abner, formaram um só grupo e pararam no alto de uma colina."},
{v:26,t:"Abner gritou a Joab: Há de a espada devorar sem fim? Não sabes que o desespero é perigoso? Até quando esperarás para mandar o povo deixar de perseguir os seus irmãos?"},
{v:27,t:"Joab respondeu: Pela vida de Deus, se não tivesses falado, o povo só teria deixado de perseguir cada um o seu irmão pela manhã."},
{v:28,t:"Joab tocou a trombeta, e todo o exército parou; deixaram de perseguir Israel e não combateram mais."},
{v:29,t:"Abner e os seus homens caminharam toda aquela noite pela Arabá, atravessaram o Jordão, percorreram todo o desfiladeiro de Betron e chegaram a Maanaim.",np:1},
{v:30,t:"Joab voltou da perseguição a Abner e reuniu todo o povo: faltavam dos servos de Davi dezenove homens, além de Asael."},
{v:31,t:"Mas os servos de Davi tinham matado trezentos e sessenta homens de Benjamim e dos homens de Abner."},
{v:32,t:"Levaram Asael e o sepultaram no túmulo de seu pai, em Belém. Joab e os seus homens caminharam toda a noite e chegaram a Hebron ao romper do dia."}
];

window.TEXTOS_SEED["2samuel"][3] = [
{s:"Os filhos de Davi nascidos em Hebron"},
{v:1,t:"A guerra entre a casa de Saul e a casa de Davi foi longa: Davi ia-se fortalecendo cada vez mais, e a casa de Saul ia-se enfraquecendo dia após dia."},
{v:2,t:"Nasceram filhos a Davi em Hebron. O primogênito foi Amnon, de Aquinoam de Jezrael;",np:1},
{v:3,t:"o segundo, Queleab, de Abigail de Carmel, mulher de Nabal; o terceiro, Absalão, filho de Maaca, filha de Tolmai, rei de Gessur;",n:"O casamento com a filha do rei de Gessur, pequeno reino arameu a nordeste, era uma aliança política. Absalão se refugiará junto do avô (13,37)."},
{v:4,t:"o quarto, Adonias, filho de Hagit; o quinto, Safatias, filho de Abital;"},
{v:5,t:"o sexto, Jetraam, de Egla, mulher de Davi. Estes nasceram a Davi em Hebron.",n:"Amnon, Absalão e Adonias disputarão a sucessão, e as suas histórias encherão de sangue a casa de Davi."},
{s:"Abner passa para o lado de Davi"},
{v:6,t:"Durante a guerra entre a casa de Saul e a casa de Davi, Abner, filho de Ner, dominava a casa de Saul.",np:1},
{v:7,t:"Saul tinha tido uma concubina chamada Resfa, filha de Aiá. Isbaal disse a Abner:",n:"Tomar a concubina do rei morto era reivindicar a sua herança, isto é, o trono. Absalão fará o mesmo com as concubinas de Davi (16,22)."},
{v:8,t:"Por que te uniste à concubina de meu pai? Abner irritou-se muito com as palavras de Isbaal e disse: Sou eu uma cabeça de cão, de Judá? Até hoje tenho sido leal à casa de Saul, teu pai, a seus irmãos e a seus amigos, e não te entreguei nas mãos de Davi; e hoje me pedes contas por causa de uma mulher?"},
{v:9,t:"Que Deus faça isto a Abner e mais aquilo, se eu não fizer por Davi o que o Senhor lhe jurou:"},
{v:10,t:"transferir o reino da casa de Saul e firmar o trono de Davi sobre Israel e sobre Judá, desde Dã até Bersabeia."},
{v:11,t:"E Isbaal não pôde responder-lhe palavra, porque tinha medo dele."},
{v:12,t:"Abner enviou mensageiros a Davi, para lhe dizerem em seu nome: De quem é a terra? E também: Faze aliança comigo, e a minha mão estará contigo para trazer a ti todo o Israel.",np:1},
{v:13,t:"Davi respondeu: Muito bem; farei aliança contigo, mas exijo de ti uma coisa: não verás o meu rosto se primeiro não me trouxeres Micol, filha de Saul; então virás ver-me.",n:"Micol, filha de Saul, dava a Davi um título legítimo à sucessão da casa real."},
{v:14,t:"E Davi enviou mensageiros a Isbaal, filho de Saul, para lhe dizer: Devolve-me a minha mulher Micol, que desposei pelo preço de cem prepúcios de filisteus."},
{v:15,t:"Isbaal mandou tirá-la do marido, Faltiel, filho de Lais.",n:"Faltiel é o Falti de 1 Samuel 25,44."},
{v:16,t:"O marido a acompanhou, chorando, até Baurim. Então Abner lhe disse: Vai, volta para casa. E ele voltou.",n:"Um dos quadros mais tristes do livro: o homem que a amava segue-a chorando, e Micol torna-se moeda de troca entre os poderosos."},
{v:17,t:"Abner falou com os anciãos de Israel, dizendo: Há muito tempo desejais ter Davi como vosso rei.",np:1},
{v:18,t:"Agora, pois, fazei-o, porque o Senhor falou a Davi, dizendo: Pela mão de Davi, meu servo, salvarei o meu povo Israel da mão dos filisteus e da mão de todos os seus inimigos."},
{v:19,t:"Abner falou também aos benjaminitas; e foi a Hebron dizer a Davi tudo o que parecia bem a Israel e a toda a casa de Benjamim."},
{v:20,t:"Abner chegou a Hebron, junto de Davi, com vinte homens, e Davi ofereceu um banquete a Abner e aos homens que o acompanhavam."},
{v:21,t:"Abner disse a Davi: Vou partir para reunir todo o Israel em torno do rei, meu senhor; eles farão aliança contigo, e reinarás sobre tudo o que desejares. Davi despediu Abner, e ele partiu em paz."},
{s:"Joab assassina Abner"},
{v:22,t:"Nisso, os servos de Davi e Joab voltavam de uma incursão, trazendo grande despojo. Abner já não estava com Davi em Hebron, porque Davi o tinha despedido, e ele tinha partido em paz.",np:1},
{v:23,t:"Quando chegou Joab com todo o exército que estava com ele, contaram-lhe: Abner, filho de Ner, veio ao rei, e o rei o despediu, e ele partiu em paz."},
{v:24,t:"Joab foi ter com o rei e disse: Que fizeste? Abner veio a ti; por que o deixaste ir, e ele se foi embora?"},
{v:25,t:"Não conheces Abner, filho de Ner? Veio para te enganar, para conhecer as tuas entradas e saídas e saber tudo o que fazes."},
{v:26,t:"Joab saiu da presença de Davi e enviou mensageiros atrás de Abner, que o fizeram voltar da cisterna de Sira, sem que Davi o soubesse."},
{v:27,t:"Quando Abner voltou a Hebron, Joab levou-o à parte, para dentro da porta, como para lhe falar em particular, e ali o feriu no ventre; e ele morreu, em vingança do sangue de Asael, irmão de Joab.",n:"Joab vinga o irmão, mas elimina também um rival: Abner seria o chefe do exército do reino unido. Hebron era cidade de refúgio, onde a vingança do sangue era proibida (Josué 20,7)."},
{v:28,t:"Quando Davi soube do fato, disse: Eu e o meu reino somos para sempre inocentes, diante do Senhor, do sangue de Abner, filho de Ner.",np:1},
{v:29,t:"Que ele recaia sobre a cabeça de Joab e sobre toda a casa de seu pai! Que nunca falte na casa de Joab quem sofra de fluxo, ou de lepra, ou quem maneje o fuso, ou quem caia pela espada, ou quem careça de pão!",n:"Quem maneje o fuso: um homem incapaz para a guerra, reduzido aos trabalhos das mulheres; ou, segundo outros, quem ande de muletas."},
{v:30,t:"Joab e seu irmão Abisai mataram Abner porque ele tinha matado Asael, irmão deles, em Gabaon, na batalha."},
{v:31,t:"Davi disse a Joab e a todo o povo que estava com ele: Rasgai as vossas vestes, cingi-vos de pano de saco e fazei luto diante do corpo de Abner. E o rei Davi seguia o féretro.",np:1},
{v:32,t:"Sepultaram Abner em Hebron. O rei levantou a voz e chorou sobre o túmulo de Abner, e todo o povo também chorou."},
{v:33,l:["E o rei entoou esta lamentação sobre Abner:","Devia Abner morrer","como morre o insensato?"],n:"Insensato: em hebraico nabal, o nome do homem de 1 Samuel 25. Abner, o grande guerreiro, morreu como um tolo, numa emboscada."},
{v:34,l:["As tuas mãos não estavam atadas,","nem os teus pés presos em grilhões;","caíste como se cai diante dos malfeitores.","E todo o povo redobrou o pranto por ele."]},
{v:35,t:"Depois todo o povo veio insistir com Davi para que comesse alguma coisa enquanto ainda era dia; mas Davi jurou, dizendo: Que Deus me faça isto e mais aquilo, se eu provar pão ou qualquer outra coisa antes do pôr do sol!",np:1},
{v:36,t:"Todo o povo o soube, e isso lhe agradou, como agradava a todo o povo tudo o que o rei fazia."},
{v:37,t:"Naquele dia, todo o povo e todo o Israel reconheceram que não tinha sido por ordem do rei que Abner, filho de Ner, fora morto."},
{v:38,t:"E o rei disse aos seus servos: Não sabeis que hoje caiu em Israel um chefe, um grande homem?"},
{v:39,t:"Eu ainda sou fraco, embora ungido rei; e esses homens, os filhos de Sárvia, são mais duros do que eu. Que o Senhor retribua ao malfeitor segundo a sua maldade.",n:"Davi não pode punir Joab, de quem depende; deixa a vingança a Deus. Só no leito de morte pedirá a Salomão que faça justiça (1 Reis 2,5-6)."}
];

window.TEXTOS_SEED["2samuel"][4] = [
{s:"O assassinato de Isbaal"},
{v:1,t:"Quando Isbaal, filho de Saul, soube que Abner tinha morrido em Hebron, desfaleceu-lhe a coragem, e todo o Israel ficou consternado."},
{v:2,t:"O filho de Saul tinha dois chefes de bando: um chamava-se Baana, e o outro, Recab; eram filhos de Remon, de Berot, da tribo de Benjamim, pois também Berot era considerada parte de Benjamim.",np:1},
{v:3,t:"Os habitantes de Berot tinham fugido para Getaim, onde vivem como estrangeiros até hoje."},
{v:4,t:"Jônatas, filho de Saul, tinha um filho aleijado dos pés. Tinha cinco anos quando chegou de Jezrael a notícia da morte de Saul e de Jônatas; a sua ama o tomou e fugiu, mas, na pressa da fuga, o menino caiu e ficou coxo. Chamava-se Meribaal.",n:"A nota prepara o capítulo 9: Meribaal é o último descendente de Saul capaz de reivindicar o trono, mas a sua deficiência o afasta. O hebraico chama-o Mefiboset, trocando baal por boset, vergonha, como no nome de Isbaal; a Nova Vulgata restitui o nome original."},
{v:5,t:"Os filhos de Remon, de Berot, Recab e Baana, partiram e chegaram, no maior calor do dia, à casa de Isbaal, que dormia a sesta na sua cama; a porteira da casa, que limpava trigo, tinha adormecido.",np:1,n:"A porteira adormecida vem da versão grega, que a Nova Vulgata segue; o hebraico diz que os assassinos entraram como quem vai buscar trigo."},
{v:6,t:"Entraram até o interior da casa, e Recab e seu irmão Baana o feriram no ventre e fugiram."},
{v:7,t:"Entraram na casa quando ele dormia na cama, no seu quarto; feriram-no, mataram-no e cortaram-lhe a cabeça. Depois, levando a cabeça, caminharam a noite inteira pelo caminho da Arabá."},
{v:8,t:"Levaram a cabeça de Isbaal a Davi, em Hebron, e disseram ao rei: Aqui está a cabeça de Isbaal, filho de Saul, teu inimigo, que procurava tirar-te a vida. Hoje o Senhor concedeu ao rei, meu senhor, vingança de Saul e da sua descendência."},
{v:9,t:"Davi respondeu a Recab e a seu irmão Baana, filhos de Remon, de Berot: Pela vida do Senhor, que me livrou de toda angústia:",np:1},
{v:10,t:"aquele que me trouxe a notícia de que Saul estava morto, julgando trazer uma boa notícia, eu o prendi e o matei em Siceleg; foi essa a recompensa que lhe dei pela notícia."},
{v:11,t:"Quanto mais agora, quando homens perversos mataram um homem inocente em sua casa, na sua cama! Não hei de pedir-vos contas do seu sangue e eliminar-vos da terra?",n:"Mais uma vez, Davi recusa subir ao trono pelo crime alheio e mostra a todo o Israel que não quis a morte do filho de Saul."},
{v:12,t:"Davi deu ordem aos seus rapazes, e eles os mataram; cortaram-lhes as mãos e os pés e os penduraram junto ao tanque de Hebron. A cabeça de Isbaal, tomaram-na e a sepultaram no túmulo de Abner, em Hebron."}
];

window.TEXTOS_SEED["2samuel"][5] = [
{s:"Davi rei de todo o Israel"},
{v:1,t:"Todas as tribos de Israel vieram ter com Davi em Hebron e disseram: Somos teus ossos e tua carne.",n:"A mesma expressão que Adão diz de Eva: somos da mesma família. As tribos do Norte reconhecem o parentesco com o rei de Judá."},
{v:2,t:"Já antes, quando Saul era nosso rei, eras tu que conduzias Israel nas suas saídas e entradas. E o Senhor te disse: Tu apascentarás o meu povo Israel e serás o chefe de Israel.",n:"O rei como pastor: a imagem, comum no Oriente, recebe na Bíblia um sentido novo. Os profetas a retomarão para anunciar o Messias, filho de Davi, e Jesus se dirá o bom pastor."},
{v:3,t:"Todos os anciãos de Israel vieram ter com o rei em Hebron; o rei Davi fez aliança com eles em Hebron, diante do Senhor, e eles ungiram Davi rei sobre Israel.",n:"Terceira unção de Davi: depois da de Samuel, na intimidade da família (1 Samuel 16), e da de Judá (2,4). A aliança com os anciãos define os deveres do rei para com o povo."},
{v:4,t:"Davi tinha trinta anos quando começou a reinar, e reinou quarenta anos:",np:1},
{v:5,t:"em Hebron reinou sobre Judá sete anos e seis meses, e em Jerusalém reinou trinta e três anos sobre todo o Israel e Judá."},
{s:"A conquista de Jerusalém"},
{v:6,t:"O rei marchou com os seus homens sobre Jerusalém, contra os jebuseus que habitavam a região. Estes disseram a Davi: Não entrarás aqui; até os cegos e os coxos te repelirão! Queriam dizer: Davi não entrará aqui.",np:1,n:"Jerusalém, cidade cananeia que nenhuma tribo tinha conquistado, ficava entre Judá e Benjamim. Tomada por Davi com os seus homens, tornou-se a capital neutra do reino, pertencente ao rei e não a uma tribo. Os jebuseus confiavam tanto nas suas muralhas que diziam bastarem cegos e coxos para defendê-las."},
{v:7,t:"Mas Davi tomou a fortaleza de Sião, que é a Cidade de Davi."},
{v:8,t:"Naquele dia Davi dissera: Quem quiser ferir os jebuseus, suba pelo canal da fonte, até esses coxos e cegos que Davi detesta. Por isso se diz: Cego e coxo não entrarão na casa.",n:"O canal da fonte: talvez o poço que levava da cidade à fonte de Gion, pelo qual os homens de Davi teriam entrado. O provérbio foi depois aplicado ao templo, onde os cegos e os coxos não entravam; Jesus curará cegos e coxos no templo (Mateus 21,14)."},
{v:9,t:"Davi estabeleceu-se na fortaleza e chamou-a Cidade de Davi; e construiu ao redor, desde o Milo para dentro.",n:"O Milo, palavra que quer dizer aterro, era talvez um sistema de terraços que sustentava as construções na encosta da colina."},
{v:10,t:"Davi ia crescendo em poder, e o Senhor, Deus dos exércitos, estava com ele."},
{v:11,t:"Hiram, rei de Tiro, enviou mensageiros a Davi, com madeira de cedro, carpinteiros e pedreiros, que construíram uma casa para Davi.",np:1,n:"Hiram será também o aliado de Salomão na construção do templo. Tiro, na costa fenícia, era famosa pelos seus artesãos e pelo comércio marítimo."},
{v:12,t:"E Davi reconheceu que o Senhor o tinha confirmado rei sobre Israel e tinha exaltado o seu reino por amor do seu povo Israel."},
{v:13,t:"Depois de vir de Hebron, Davi tomou ainda concubinas e mulheres de Jerusalém, e nasceram-lhe outros filhos e filhas.",np:1},
{v:14,t:"Estes são os nomes dos que lhe nasceram em Jerusalém: Samua, Sobab, Natã, Salomão,",n:"Natã é, segundo Lucas 3,31, o antepassado de Jesus; Salomão, segundo Mateus 1,6."},
{v:15,t:"Jebaar, Elisua, Nefeg,"},
{v:16,t:"Jafia, Elisama, Eliada e Elifalet."},
{s:"Vitórias sobre os filisteus"},
{v:17,t:"Quando os filisteus souberam que Davi tinha sido ungido rei sobre Israel, subiram todos à sua procura. Davi soube disso e desceu à fortaleza.",np:1,n:"Enquanto Davi era rei só de Judá, os filisteus o consideravam vassalo; rei de todo o Israel, tornava-se um perigo."},
{v:18,t:"Os filisteus chegaram e espalharam-se pelo vale dos Refaim."},
{v:19,t:"Davi consultou o Senhor: Devo subir contra os filisteus? Tu os entregarás nas minhas mãos? O Senhor respondeu a Davi: Sobe, porque certamente entregarei os filisteus nas tuas mãos."},
{v:20,t:"Davi foi a Baal-Farasim, isto é, Senhor das Brechas, e ali os derrotou, e disse: O Senhor abriu brecha entre os meus inimigos diante de mim, como as águas abrem brecha. Por isso deram àquele lugar o nome de Baal-Farasim.",n:"Isaías lembrará esta vitória: o Senhor se levantará como no monte Farasim (Isaías 28,21)."},
{v:21,t:"Os filisteus deixaram ali os seus ídolos, e Davi e os seus homens os levaram.",n:"Assim os filisteus perdem os seus deuses, como Israel perdera a arca (1 Samuel 4). As Crônicas acrescentam que Davi mandou queimá-los (1 Crônicas 14,12)."},
{v:22,t:"Os filisteus tornaram a subir e espalharam-se pelo vale dos Refaim.",np:1},
{v:23,t:"Davi consultou o Senhor, que lhe respondeu: Não subas; dá a volta por trás deles e ataca-os pelo lado das balsameiras.",n:"Balsameiras: árvores de identificação incerta."},
{v:24,t:"Quando ouvires um ruído de passos na copa das balsameiras, então lança-te ao combate, porque o Senhor terá saído à tua frente para ferir o exército dos filisteus.",n:"O ruído de passos nas copas das árvores é o sinal do Senhor que marcha à frente do seu exército."},
{v:25,t:"Davi fez como o Senhor lhe ordenara e bateu os filisteus desde Gabaon até a entrada de Gazer.",n:"Gabaon: assim a versão grega, como em 1 Crônicas 14,16; o hebraico diz Gaba."}
];

window.TEXTOS_SEED["2samuel"][6] = [
{s:"A arca levada para Jerusalém"},
{v:1,t:"Davi reuniu de novo todos os homens escolhidos de Israel, trinta mil."},
{v:2,t:"Levantou-se e partiu, com todo o povo que estava com ele, para Baala de Judá, a fim de trazer de lá a arca de Deus, sobre a qual é invocado o nome do Senhor dos exércitos, que está sentado sobre os querubins.",n:"Baala de Judá é Cariat-Iarim, onde a arca estava desde a sua volta da terra dos filisteus (1 Samuel 7,1). Levando-a para Jerusalém, Davi faz da sua capital política também o centro religioso de todo o Israel."},
{v:3,t:"Puseram a arca de Deus num carro novo e a tiraram da casa de Abinadab, que ficava na colina. Oza e Aio, filhos de Abinadab, conduziam o carro:"},
{v:4,t:"Oza caminhava ao lado da arca, e Aio ia à frente dela."},
{v:5,t:"Davi e todo o Israel dançavam diante do Senhor com todas as forças, com cânticos, cítaras, harpas, tamborins, sistros e címbalos.",n:"Com todas as forças e com cânticos: assim a Nova Vulgata, com 1 Crônicas 13,8; o hebraico diz com toda sorte de instrumentos de cipreste."},
{v:6,t:"Quando chegaram à eira de Nacon, Oza estendeu a mão para a arca de Deus e a segurou, porque os bois a tinham feito balançar.",np:1},
{v:7,t:"A ira do Senhor inflamou-se contra Oza, e Deus o feriu ali por aquela temeridade; e ele morreu ali, junto da arca de Deus.",n:"A arca devia ser levada nos ombros pelos levitas, e ninguém podia tocá-la (Números 4,15). O carro era o modo dos filisteus. A morte de Oza escandaliza o leitor, como escandalizou Davi; a narrativa quer mostrar que a santidade de Deus não se deixa manejar."},
{v:8,t:"Davi ficou aborrecido porque o Senhor tinha aberto uma brecha em Oza; e aquele lugar se chama até hoje Farés-Oza, isto é, Brecha de Oza."},
{v:9,t:"Naquele dia Davi teve medo do Senhor e disse: Como poderá a arca do Senhor vir para junto de mim?"},
{v:10,t:"E Davi não quis levar a arca do Senhor para junto de si, na Cidade de Davi, mas a fez levar para a casa de Obed-Edom, de Gat.",n:"Obed-Edom, de Gat: um filisteu, talvez da guarda estrangeira de Davi, a quem se confia a arca perigosa."},
{v:11,t:"A arca do Senhor ficou três meses na casa de Obed-Edom, de Gat, e o Senhor abençoou Obed-Edom e toda a sua casa."},
{v:12,t:"Contaram ao rei Davi: O Senhor abençoou Obed-Edom e tudo o que ele tem, por causa da arca de Deus. Então Davi foi e fez subir com alegria a arca de Deus da casa de Obed-Edom para a Cidade de Davi.",np:1},
{v:13,t:"Quando os que levavam a arca do Senhor tinham dado seis passos, ele sacrificou um boi e um bezerro cevado.",n:"Agora a arca é levada nos ombros, como a Lei mandava."},
{v:14,t:"E Davi dançava com todas as forças diante do Senhor; Davi estava cingido com um efod de linho.",n:"O efod de linho era uma veste sacerdotal curta, como a que Samuel usava menino (1 Samuel 2,18). Davi age aqui como rei e sacerdote."},
{v:15,t:"Assim Davi e toda a casa de Israel fizeram subir a arca do Senhor entre aclamações e ao som da trombeta."},
{v:16,t:"Quando a arca do Senhor entrou na Cidade de Davi, Micol, filha de Saul, olhando pela janela, viu o rei Davi pulando e dançando diante do Senhor, e desprezou-o no seu coração.",np:1},
{v:17,t:"Introduziram a arca do Senhor e a colocaram no seu lugar, no meio da tenda que Davi tinha armado para ela; e Davi ofereceu diante do Senhor holocaustos e sacrifícios de comunhão."},
{v:18,t:"Quando acabou de oferecer os holocaustos e os sacrifícios de comunhão, Davi abençoou o povo em nome do Senhor dos exércitos."},
{v:19,t:"E distribuiu a toda a multidão de Israel, homens e mulheres, a cada um, um pão redondo, um bolo de tâmaras e um bolo de passas. Depois todo o povo voltou, cada um para a sua casa."},
{s:"Davi e Micol"},
{v:20,t:"Davi voltou para abençoar a sua casa, e Micol, filha de Saul, saiu ao encontro de Davi e disse: Que glória para o rei de Israel, hoje, descobrir-se diante das servas dos seus servos, como se descobre um bufão qualquer!",np:1},
{v:21,t:"Davi respondeu a Micol: É diante do Senhor que eu danço. Bendito seja o Senhor, que me escolheu de preferência a teu pai e a toda a sua casa, para me constituir chefe do povo do Senhor, de Israel!"},
{v:22,t:"Dançarei diante do Senhor e me farei ainda mais desprezível do que isto, e serei humilde aos meus próprios olhos; mas as servas de quem falaste, diante delas serei honrado.",n:"Davi não se envergonha de se rebaixar diante de Deus: a verdadeira grandeza do rei é a humildade diante do Senhor."},
{v:23,t:"E Micol, filha de Saul, não teve filhos até o dia da sua morte.",n:"A esterilidade de Micol encerra a descendência de Saul no trono: nenhum neto de Saul reinará."}
];

window.TEXTOS_SEED["2samuel"][7] = [
{s:"A profecia de Natã"},
{v:1,t:"Quando o rei já habitava em sua casa, e o Senhor lhe tinha dado descanso de todos os inimigos ao redor,"},
{v:2,t:"disse ao profeta Natã: Vê: eu moro numa casa de cedro, e a arca de Deus está no meio de cortinas!",n:"Natã, profeta da corte, aparece aqui pela primeira vez; será ele quem repreenderá Davi pelo seu pecado (capítulo 12)."},
{v:3,t:"Natã respondeu ao rei: Faze tudo o que tens no coração, porque o Senhor está contigo."},
{v:4,t:"Mas naquela mesma noite a palavra do Senhor foi dirigida a Natã nestes termos:",np:1},
{v:5,t:"Vai e dize ao meu servo Davi: Assim diz o Senhor: És tu que me construirás uma casa para eu habitar?",n:"O capítulo joga com a palavra casa: Davi quer construir uma casa, isto é, um templo, para Deus; é Deus quem construirá uma casa, isto é, uma dinastia, para Davi."},
{v:6,t:"Desde o dia em que tirei os filhos de Israel do Egito até hoje, nunca habitei numa casa; andei de um lugar para outro numa tenda e num tabernáculo."},
{v:7,t:"Em todos os lugares por onde andei com todos os filhos de Israel, acaso disse alguma vez a algum dos juízes de Israel, a quem ordenei que apascentasse o meu povo Israel: Por que não me construístes uma casa de cedro?"},
{v:8,t:"Agora, pois, assim dirás ao meu servo Davi: Assim diz o Senhor dos exércitos: Eu te tirei das pastagens, de detrás das ovelhas, para que fosses chefe do meu povo Israel.",np:1},
{v:9,t:"Estive contigo por onde quer que andaste e exterminei diante de ti todos os teus inimigos; e te farei um nome grande como o nome dos grandes da terra."},
{v:10,t:"Prepararei um lugar para o meu povo Israel e o plantarei, e ele habitará no seu lugar e não será mais perturbado; e os perversos não tornarão a oprimi-lo como antes,"},
{v:11,t:"desde o dia em que constituí juízes sobre o meu povo Israel; e te darei descanso de todos os teus inimigos. E o Senhor te anuncia que o Senhor te fará uma casa."},
{v:12,t:"Quando se completarem os teus dias e repousares com teus pais, suscitarei depois de ti a tua descendência, que sairá das tuas entranhas, e firmarei o seu reino.",n:"É a promessa messiânica fundamental do Antigo Testamento. Aplica-se primeiro a Salomão, que construirá o templo; mas o reino para sempre ultrapassa Salomão e a dinastia histórica. Os profetas e os Salmos (Salmo 89; 132) esperarão o filho de Davi, e o Novo Testamento o reconhecerá em Jesus (Lucas 1,32-33)."},
{v:13,t:"Ele construirá uma casa ao meu nome, e eu firmarei para sempre o trono do seu reino."},
{v:14,t:"Eu serei para ele um pai, e ele será para mim um filho. Se ele cometer alguma falta, eu o castigarei com vara de homens e com açoites humanos,",n:"Eu serei para ele um pai: o rei é filho adotivo de Deus. A Carta aos Hebreus aplica estas palavras a Cristo, o Filho (Hebreus 1,5)."},
{v:15,t:"mas não retirarei dele a minha misericórdia, como a retirei de Saul, a quem afastei de diante de ti."},
{v:16,t:"A tua casa e o teu reino serão estáveis para sempre diante de mim, e o teu trono será firme para sempre."},
{v:17,t:"Natã falou a Davi segundo todas estas palavras e toda esta visão."},
{s:"A oração de Davi"},
{v:18,t:"Então o rei Davi entrou, sentou-se diante do Senhor e disse: Quem sou eu, Senhor Deus, e que é a minha casa, para que me tenhas trazido até aqui?",np:1,n:"Diante do Senhor: na tenda da arca."},
{v:19,t:"E ainda isso te pareceu pouco, Senhor Deus: falaste também da casa do teu servo para um futuro distante. Esta é a lei para os homens, Senhor Deus!",n:"A última frase é obscura. Talvez: é assim que tratas um homem? ou: esta é a promessa dada à humanidade."},
{v:20,t:"Que mais poderia Davi dizer-te? Tu conheces o teu servo, Senhor Deus."},
{v:21,t:"Por causa da tua palavra e segundo o teu coração, fizeste todas estas grandes coisas, para dá-las a conhecer ao teu servo."},
{v:22,t:"Por isso és grande, Senhor Deus: não há ninguém como tu, e não há Deus fora de ti, segundo tudo o que ouvimos com os nossos ouvidos."},
{v:23,t:"E que outra nação há na terra como o teu povo Israel, que Deus foi resgatar para fazer dele o seu povo, para dar-lhe um nome e fazer por ele coisas grandes e terríveis, expulsando diante do teu povo, que resgataste do Egito, as nações e os seus deuses?"},
{v:24,t:"Tu firmaste para ti o teu povo Israel, para que fosse o teu povo para sempre; e tu, Senhor, te tornaste o seu Deus."},
{v:25,t:"Agora, pois, Senhor Deus, confirma para sempre a palavra que disseste sobre o teu servo e sobre a sua casa, e faze como disseste!",np:1},
{v:26,t:"Que o teu nome seja engrandecido para sempre, e que se diga: O Senhor dos exércitos é o Deus de Israel! E a casa do teu servo Davi será firme diante de ti,"},
{v:27,t:"porque tu, Senhor dos exércitos, Deus de Israel, fizeste esta revelação ao teu servo: Eu te construirei uma casa. Por isso o teu servo encontrou coragem para te dirigir esta oração."},
{v:28,t:"Agora, pois, Senhor Deus, tu és Deus, e as tuas palavras são verdade; e prometeste ao teu servo este bem."},
{v:29,t:"Digna-te, pois, abençoar a casa do teu servo, para que ela permaneça para sempre diante de ti; porque tu, Senhor Deus, falaste, e com a tua bênção a casa do teu servo será bendita para sempre."}
];

window.TEXTOS_SEED["2samuel"][8] = [
{s:"As vitórias de Davi"},
{v:1,t:"Depois disso, Davi derrotou os filisteus e os humilhou, e tomou das mãos dos filisteus Gat e as suas cidades.",n:"Gat e as suas cidades: assim a Nova Vulgata, com 1 Crônicas 18,1; o hebraico traz uma expressão obscura, Meteg-Ama, talvez a rédea da metrópole, isto é, a hegemonia."},
{v:2,t:"Derrotou também Moab e mediu os moabitas com um cordel, fazendo-os deitar no chão: media dois cordéis para os matar e um cordel inteiro para os deixar com vida. E Moab ficou sujeito a Davi, pagando-lhe tributo.",n:"Um terço dos prisioneiros foi poupado. O tratamento cruel contrasta com a amizade de outrora, quando Davi confiou os pais ao rei de Moab (1 Samuel 22,3-4); o texto não explica a mudança."},
{v:3,t:"Davi derrotou também Adadezer, filho de Roob, rei de Soba, quando este ia estabelecer o seu domínio sobre o rio Eufrates.",np:1,n:"Soba era um reino arameu ao norte de Damasco, o mais poderoso da Síria naquele tempo."},
{v:4,t:"Davi tomou-lhe mil e setecentos cavaleiros e vinte mil soldados de infantaria; e cortou os jarretes a todos os cavalos dos carros, deixando só os necessários para cem carros.",n:"Israel, povo da montanha, não sabia ainda usar os carros de guerra; e a Lei desconfiava dos cavalos, sinal do poder humano (Deuteronômio 17,16)."},
{v:5,t:"Os arameus de Damasco vieram em socorro de Adadezer, rei de Soba, e Davi matou vinte e dois mil homens dos arameus."},
{v:6,t:"E Davi estabeleceu guarnições na Síria de Damasco, e os arameus ficaram sujeitos a Davi, pagando-lhe tributo. O Senhor dava vitória a Davi por onde quer que ele fosse."},
{v:7,t:"Davi tomou as armas de ouro que os servos de Adadezer tinham e levou-as para Jerusalém;"},
{v:8,t:"e de Tebá e de Berotai, cidades de Adadezer, o rei Davi tomou grande quantidade de bronze.",n:"As Crônicas acrescentam que Salomão usou esse bronze para o mar de bronze, as colunas e os utensílios do templo (1 Crônicas 18,8)."},
{v:9,t:"Tou, rei de Emat, soube que Davi tinha derrotado todo o exército de Adadezer,",np:1},
{v:10,t:"e enviou seu filho Adoram ao rei Davi, para saudá-lo e felicitá-lo por ter combatido contra Adadezer e o ter derrotado; porque Adadezer estava em guerra com Tou. Adoram trouxe objetos de prata, de ouro e de bronze,"},
{v:11,t:"que o rei Davi também consagrou ao Senhor, junto com a prata e o ouro que tinha consagrado de todas as nações que submetera:"},
{v:12,t:"da Síria, de Moab, dos amonitas, dos filisteus, de Amalec, e do despojo de Adadezer, filho de Roob, rei de Soba."},
{v:13,t:"Davi ganhou fama quando voltou de derrotar Edom no vale do Sal: dezoito mil homens.",n:"Edom: assim a Nova Vulgata, com 1 Crônicas 18,12; o hebraico diz Aram, confusão fácil entre duas palavras quase iguais na escrita hebraica."},
{v:14,t:"Estabeleceu guarnições em Edom, e todo o Edom ficou sujeito a Davi. O Senhor dava vitória a Davi por onde quer que ele fosse.",n:"Davi constrói um pequeno império, do Egito ao Eufrates: a promessa feita a Abraão (Gênesis 15,18) parece cumprir-se."},
{s:"Os oficiais de Davi"},
{v:15,t:"Davi reinou sobre todo o Israel, e praticava o direito e a justiça para com todo o seu povo.",np:1},
{v:16,t:"Joab, filho de Sárvia, comandava o exército; Josafá, filho de Ailud, era o arauto;"},
{v:17,t:"Sadoc, filho de Aquitob, e Abiatar, filho de Aquimelec, eram sacerdotes; Saraías era o escriba;",n:"Abiatar, filho de Aquimelec: assim a Nova Vulgata; o hebraico inverte os nomes, por erro de copista. Sadoc aparece aqui pela primeira vez; os seus descendentes serão os sumos sacerdotes do templo de Jerusalém."},
{v:18,t:"Banaías, filho de Joiada, comandava os cereteus e os feleteus; e os filhos de Davi eram sacerdotes.",n:"Os cereteus e os feleteus, cretenses e filisteus, formavam a guarda estrangeira do rei, fiel só a ele. Sacerdotes: o título, dado aos filhos do rei, talvez designe uma função na corte; as Crônicas dizem os primeiros ao lado do rei (1 Crônicas 18,17)."}
];

window.TEXTOS_SEED["2samuel"][9] = [
{s:"Davi e Meribaal"},
{v:1,t:"Davi perguntou: Resta ainda alguém da casa de Saul, a quem eu possa fazer bem por amor de Jônatas?",n:"Davi cumpre a promessa feita a Jônatas (1 Samuel 20,14-15). Mas o gesto de bondade é também prudência: o neto de Saul ficará sob os olhos do rei."},
{v:2,t:"Havia um servo da casa de Saul chamado Siba. Chamaram-no à presença de Davi, e o rei lhe perguntou: És tu Siba? Ele respondeu: Sou eu, teu servo."},
{v:3,t:"O rei perguntou: Não resta mais ninguém da casa de Saul, a quem eu possa fazer a bondade de Deus? Siba respondeu ao rei: Resta ainda um filho de Jônatas, aleijado dos pés."},
{v:4,t:"Onde está ele? perguntou o rei. Siba respondeu ao rei: Está na casa de Maquir, filho de Amiel, em Lodabar."},
{v:5,t:"O rei Davi mandou buscá-lo na casa de Maquir, filho de Amiel, em Lodabar.",np:1},
{v:6,t:"Quando Meribaal, filho de Jônatas, filho de Saul, chegou junto de Davi, caiu com o rosto por terra e prostrou-se. Davi disse: Meribaal! Ele respondeu: Aqui está o teu servo."},
{v:7,t:"Davi lhe disse: Não tenhas medo, porque certamente usarei de bondade contigo por amor de Jônatas, teu pai; eu te restituirei todas as terras de Saul, teu pai, e tu comerás sempre à minha mesa.",n:"Não tenhas medo: o novo rei costumava exterminar a família do rei anterior. Meribaal espera o pior."},
{v:8,t:"Ele se prostrou e disse: Quem é o teu servo, para que te voltes para um cão morto como eu?"},
{v:9,t:"Então o rei chamou Siba, servo de Saul, e lhe disse: Tudo o que pertencia a Saul e a toda a sua casa, eu o dou ao filho do teu senhor.",np:1},
{v:10,t:"Tu, os teus filhos e os teus servos lavrareis a terra para ele e recolhereis os frutos, para que a casa do teu senhor tenha pão para comer; mas Meribaal, filho do teu senhor, comerá sempre à minha mesa. Siba tinha quinze filhos e vinte servos."},
{v:11,t:"Siba respondeu ao rei: O teu servo fará tudo o que o rei, meu senhor, ordenou ao seu servo. E Meribaal comia à mesa do rei como um dos filhos do rei."},
{v:12,t:"Meribaal tinha um filho pequeno, chamado Mica; e todos os que moravam na casa de Siba estavam a serviço de Meribaal."},
{v:13,t:"Meribaal morava em Jerusalém, porque comia sempre à mesa do rei; e era coxo dos dois pés."}
];

window.TEXTOS_SEED["2samuel"][10] = [
{s:"A afronta dos amonitas"},
{v:1,t:"Depois disso, morreu o rei dos amonitas, e seu filho Hanon reinou em seu lugar."},
{v:2,t:"Davi disse: Usarei de bondade com Hanon, filho de Naás, como seu pai usou de bondade comigo. E Davi enviou os seus servos para consolá-lo pela morte do pai. Quando os servos de Davi chegaram à terra dos amonitas,",n:"Naás, talvez o mesmo que Saul derrotou em Jabes (1 Samuel 11), tinha ajudado Davi, inimigo de Saul, no tempo da sua fuga."},
{v:3,t:"os chefes dos amonitas disseram a Hanon, seu senhor: Pensas que é para honrar teu pai que Davi te enviou consoladores? Não é antes para investigar e explorar a cidade, e destruí-la, que Davi te enviou os seus servos?"},
{v:4,t:"Hanon tomou os servos de Davi, rapou-lhes metade da barba, cortou-lhes as vestes pelo meio, até as nádegas, e despediu-os.",n:"Cortar a barba de um homem era a pior afronta; a barba era sinal de dignidade e de virilidade."},
{v:5,t:"Contaram isso a Davi, e ele mandou alguém ao encontro deles, porque estavam profundamente envergonhados; e o rei lhes mandou dizer: Ficai em Jericó até que a vossa barba cresça, e depois voltai."},
{s:"Guerra contra os amonitas e os arameus"},
{v:6,t:"Os amonitas, vendo que se tinham tornado odiosos a Davi, mandaram contratar os arameus de Bet-Roob e os arameus de Soba, vinte mil soldados de infantaria, o rei de Maaca, com mil homens, e os homens de Tob, doze mil.",np:1},
{v:7,t:"Quando Davi soube disso, enviou Joab com todo o exército dos valentes."},
{v:8,t:"Os amonitas saíram e dispuseram-se em linha de batalha diante da porta da cidade; os arameus de Soba e de Roob e os homens de Tob e de Maaca estavam à parte, no campo."},
{v:9,t:"Joab, vendo que tinha de enfrentar o combate pela frente e pela retaguarda, escolheu os melhores de Israel e dispôs-se em linha contra os arameus;"},
{v:10,t:"o resto do povo, confiou-o a seu irmão Abisai, que se dispôs em linha contra os amonitas."},
{v:11,t:"E Joab disse: Se os arameus forem mais fortes do que eu, virás em meu socorro; e, se os amonitas forem mais fortes do que tu, eu irei socorrer-te."},
{v:12,t:"Sê valente, e mostremo-nos fortes pelo nosso povo e pelas cidades do nosso Deus; e o Senhor faça o que lhe parecer bem.",n:"A frase de Joab resume a fé do soldado: fazer tudo o que se pode e entregar o resultado a Deus."},
{v:13,t:"Joab e o povo que estava com ele avançaram para o combate contra os arameus, que fugiram diante dele."},
{v:14,t:"Os amonitas, vendo que os arameus fugiam, fugiram também diante de Abisai e entraram na cidade. Joab deixou os amonitas e voltou a Jerusalém."},
{v:15,t:"Os arameus, vendo que tinham sido derrotados por Israel, reuniram-se todos juntos.",np:1},
{v:16,t:"Adadezer mandou buscar os arameus que estavam do outro lado do Rio, e eles vieram a Helam, tendo à frente Sobac, chefe do exército de Adadezer.",n:"O Rio, sem outro nome, é o Eufrates."},
{v:17,t:"Informaram Davi, e ele reuniu todo o Israel, atravessou o Jordão e chegou a Helam. Os arameus dispuseram-se em linha contra Davi e combateram contra ele."},
{v:18,t:"Mas os arameus fugiram diante de Israel; e Davi matou dos arameus os homens de setecentos carros e quarenta mil soldados de infantaria, e feriu Sobac, chefe do exército, que morreu ali."},
{v:19,t:"Todos os reis vassalos de Adadezer, vendo-se derrotados por Israel, fizeram a paz com Israel e ficaram-lhe sujeitos. E os arameus tiveram medo de socorrer de novo os amonitas."}
];

window.TEXTOS_SEED["2samuel"][11] = [
{s:"Davi e Betsabeia"},
{v:1,t:"Na volta do ano, no tempo em que os reis costumam sair para a guerra, Davi enviou Joab, e com ele os seus servos e todo o Israel; eles devastaram a terra dos amonitas e sitiaram Rabá. Mas Davi ficou em Jerusalém.",n:"Começa aqui a história da sucessão de Davi (capítulos 11 a 20 e 1 Reis 1 e 2), talvez escrita por uma testemunha da corte, de um realismo sem igual na literatura antiga. O narrador nota: Davi ficou. O rei que antes saía à frente do povo já não vai à guerra."},
{v:2,t:"Certa tarde, Davi levantou-se da cama e passeava pelo terraço do palácio real. Do terraço viu uma mulher que se banhava; e a mulher era muito bonita."},
{v:3,t:"Davi mandou informar-se sobre a mulher, e disseram-lhe: É Betsabeia, filha de Eliam, mulher de Urias, o heteu.",n:"Eliam e Urias são nomes que aparecem entre os valentes de Davi (23,34.39): Davi sabe que está tomando a mulher de um dos seus soldados mais fiéis."},
{v:4,t:"Davi mandou mensageiros buscá-la. Ela veio a ele, e ele se deitou com ela, que acabava de se purificar da sua impureza. Depois ela voltou para sua casa.",n:"Acabava de se purificar: depois da menstruação (Levítico 15,19-28). O detalhe mostra que a criança só podia ser de Davi."},
{v:5,t:"A mulher concebeu e mandou dizer a Davi: Estou grávida."},
{v:6,t:"Então Davi mandou dizer a Joab: Manda-me Urias, o heteu. E Joab enviou Urias a Davi.",np:1},
{v:7,t:"Quando Urias chegou, Davi perguntou-lhe como estavam Joab e o povo, e como ia a guerra."},
{v:8,t:"Depois Davi disse a Urias: Desce à tua casa e lava os pés. Urias saiu do palácio real, e foi-lhe enviado um presente da mesa do rei.",n:"Davi quer que Urias passe a noite com a mulher, para que o filho pareça dele."},
{v:9,t:"Mas Urias dormiu à porta do palácio real, com os outros servos do seu senhor, e não desceu à sua casa."},
{v:10,t:"Informaram Davi: Urias não desceu à sua casa. Davi disse a Urias: Não vens tu de viagem? Por que não desceste à tua casa?"},
{v:11,t:"Urias respondeu a Davi: A arca, Israel e Judá moram em tendas, e o meu senhor Joab e os servos do meu senhor acampam em campo aberto; e eu iria à minha casa, comer, beber e deitar-me com a minha mulher? Pela tua vida e pela vida da tua alma, não farei tal coisa!",n:"O estrangeiro, o heteu, é mais fiel à lei da guerra santa, que exigia continência dos combatentes (1 Samuel 21,6), do que o rei de Israel. A sua lealdade o condena à morte."},
{v:12,t:"Davi disse a Urias: Fica aqui ainda hoje, e amanhã te deixarei partir. E Urias ficou em Jerusalém aquele dia e o seguinte."},
{v:13,t:"Davi o convidou a comer e beber na sua presença, e o embriagou; mas à tarde Urias saiu para dormir na sua cama, com os servos do seu senhor, e não desceu à sua casa."},
{s:"A morte de Urias"},
{v:14,t:"Na manhã seguinte, Davi escreveu uma carta a Joab e a enviou por meio de Urias.",np:1},
{v:15,t:"Escreveu na carta: Ponde Urias na primeira linha, onde o combate for mais violento, e retirai-vos de junto dele, para que seja ferido e morra.",n:"Urias leva a sua própria sentença de morte. O rei que respeitou a vida do ungido Saul manda matar o seu soldado inocente."},
{v:16,t:"Joab, que sitiava a cidade, pôs Urias no lugar onde sabia que estavam os guerreiros mais valentes."},
{v:17,t:"Os homens da cidade fizeram uma saída e combateram contra Joab; caíram alguns do povo, dos servos de Davi, e morreu também Urias, o heteu."},
{v:18,t:"Joab mandou informar Davi de tudo o que se passara no combate,",np:1},
{v:19,t:"e deu esta ordem ao mensageiro: Quando acabares de contar ao rei tudo o que se passou no combate,"},
{v:20,t:"se o rei se irritar e te disser: Por que vos aproximastes tanto da cidade para combater? Não sabíeis que do alto da muralha eles atiram?"},
{v:21,t:"Quem matou Abimelec, filho de Jerobaal? Não foi uma mulher que lhe atirou do alto da muralha uma pedra de moinho, e ele morreu em Tebes? Por que vos aproximastes tanto da muralha? — então dirás: Também morreu o teu servo Urias, o heteu.",n:"Joab lembra o episódio de Juízes 9,53. Sabe que a notícia da morte de Urias acalmará a ira do rei."},
{v:22,t:"O mensageiro partiu, chegou e contou a Davi tudo o que Joab lhe mandara dizer."},
{v:23,t:"O mensageiro disse a Davi: Aqueles homens foram mais fortes do que nós e saíram contra nós em campo aberto; mas nós os repelimos até a entrada da porta."},
{v:24,t:"Então os arqueiros atiraram do alto da muralha contra os teus servos, e morreram alguns dos servos do rei; morreu também o teu servo Urias, o heteu."},
{v:25,t:"Davi disse ao mensageiro: Assim dirás a Joab: Não te aflijas com isso, porque a espada devora ora um, ora outro; intensifica o ataque contra a cidade e destrói-a. E tu, encoraja-o.",n:"A frieza da resposta mostra quanto o crime endureceu o coração de Davi."},
{v:26,t:"Quando a mulher de Urias soube que Urias, seu marido, tinha morrido, chorou por ele.",np:1},
{v:27,t:"Passado o luto, Davi mandou buscá-la e a recebeu em sua casa; ela se tornou sua mulher e lhe deu um filho. Mas o que Davi tinha feito desagradou ao Senhor.",n:"A última frase é o juízo de Deus sobre tudo o que precede: o narrador, que até aqui não comentou nada, dá a palavra ao Senhor."}
];
