// =====================================================================
// Amós — tradução do hebraico (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["amos"][1] = [
{s:"Título do livro"},
{v:1,t:"Palavras de Amós, um dos pastores de Técua, que ele recebeu em visão a respeito de Israel, no tempo de Ozias, rei de Judá, e no tempo de Jeroboão, filho de Joás, rei de Israel, dois anos antes do terremoto.",n:"Amós, pastor de Judá, pregou no reino do norte por volta de 760 antes de Cristo, sob Jeroboão II, num tempo de prosperidade e de injustiça. O terremoto ficou na memória do povo (Zacarias 14,5)."},
{s:"O rugido do Senhor"},
{v:2,l:["Ele disse:","O Senhor ruge de Sião","e de Jerusalém faz ouvir a sua voz;","as pastagens dos pastores estão de luto,","e o cume do Carmelo se resseca."],n:"Compare Joel 4,16."},
{s:"Contra Damasco"},
{v:3,l:["Assim diz o Senhor:","Pelos três crimes de Damasco,","e pelos quatro, não revogarei a sentença:","porque debulharam Galaad","com debulhadores de ferro,"],n:"Três crimes, e quatro: modo de dizer que a medida está cheia. Damasco era a capital dos arameus, isto é, da Síria."},
{v:4,l:["mandarei fogo contra a casa de Hazael,","e ele devorará os palácios de Ben-Adad;"],np:1},
{v:5,l:["quebrarei o ferrolho de Damasco,","exterminarei o habitante do vale de Áven","e o que empunha o cetro em Bet-Éden,","e o povo da Síria será deportado para Quir,","diz o Senhor."],np:1,n:"Vale de Áven, vale do nada, e Bet-Éden, casa das delícias: nomes talvez irônicos de lugares arameus. Quir: a terra de onde os arameus tinham vindo (9,7; compare 2 Reis 16,9)."},
{s:"Contra Gaza"},
{v:6,l:["Assim diz o Senhor:","Pelos três crimes de Gaza,","e pelos quatro, não revogarei a sentença:","porque deportaram populações inteiras","para entregá-las a Edom,"],n:"Gaza, Azoto, Ascalon e Acaron eram cidades dos filisteus, que vendiam prisioneiros como escravos."},
{v:7,l:["mandarei fogo contra as muralhas de Gaza,","e ele devorará os seus palácios;"],np:1},
{v:8,l:["exterminarei o habitante de Azoto","e o que empunha o cetro em Ascalon;","voltarei a minha mão contra Acaron,","e perecerá o resto dos filisteus,","diz o Senhor Deus."],np:1},
{s:"Contra Tiro"},
{v:9,l:["Assim diz o Senhor:","Pelos três crimes de Tiro,","e pelos quatro, não revogarei a sentença:","porque entregaram a Edom populações inteiras","e não se lembraram da aliança entre irmãos,"],n:"A aliança entre irmãos: talvez o tratado entre Hiram de Tiro e Salomão (1 Reis 5,26)."},
{v:10,l:["mandarei fogo contra as muralhas de Tiro,","e ele devorará os seus palácios."],np:1},
{s:"Contra Edom"},
{v:11,l:["Assim diz o Senhor:","Pelos três crimes de Edom,","e pelos quatro, não revogarei a sentença:","porque perseguiu o seu irmão com a espada","e abafou toda compaixão,","manteve sem fim a sua ira","e guardou para sempre o seu furor,"],n:"O irmão de Edom é Israel: Esaú e Jacó eram irmãos (Gênesis 25,19–26)."},
{v:12,l:["mandarei fogo contra Temã,","e ele devorará os palácios de Bosra."],np:1},
{s:"Contra os amonitas"},
{v:13,l:["Assim diz o Senhor:","Pelos três crimes dos amonitas,","e pelos quatro, não revogarei a sentença:","porque rasgaram o ventre das mulheres grávidas de Galaad","para alargar as suas fronteiras,"],n:"Crueldade de guerra que o profeta denuncia (compare 2 Reis 8,12; 15,16)."},
{v:14,l:["atearei fogo às muralhas de Rabá,","e ele devorará os seus palácios","entre gritos de guerra, no dia da batalha,","entre o turbilhão, no dia da tempestade;"],np:1},
{v:15,l:["e o seu rei irá para o exílio,","ele e os seus chefes com ele,","diz o Senhor."],np:1,n:"O seu rei: o hebraico malkam pode ser lido Milcom, o deus dos amonitas (compare Jeremias 49,3)."}
];

window.TEXTOS_SEED["amos"][2] = [
{s:"Contra Moab"},
{v:1,l:["Assim diz o Senhor:","Pelos três crimes de Moab,","e pelos quatro, não revogarei a sentença:","porque queimou os ossos do rei de Edom","até reduzi-los a cinzas,"],n:"Profanar os restos de um morto, mesmo inimigo, era um crime grave."},
{v:2,l:["mandarei fogo contra Moab,","e ele devorará os palácios de Cariot;","Moab morrerá no tumulto,","entre gritos de guerra e o som da trombeta;"],np:1},
{v:3,l:["exterminarei do meio dele o juiz","e matarei com ele todos os seus chefes,","diz o Senhor."],np:1},
{s:"Contra Judá"},
{v:4,l:["Assim diz o Senhor:","Pelos três crimes de Judá,","e pelos quatro, não revogarei a sentença:","porque rejeitaram a lei do Senhor","e não guardaram os seus mandamentos,","pois se deixaram enganar pelos seus ídolos,","atrás dos quais tinham andado os seus pais,"]},
{v:5,l:["mandarei fogo contra Judá,","e ele devorará os palácios de Jerusalém."],np:1},
{s:"Contra Israel"},
{v:6,l:["Assim diz o Senhor:","Pelos três crimes de Israel,","e pelos quatro, não revogarei a sentença:","porque vendem o justo por dinheiro","e o pobre por um par de sandálias;"],n:"Depois dos vizinhos, o profeta chega ao seu verdadeiro alvo: o próprio Israel. Um par de sandálias: uma dívida insignificante."},
{v:7,l:["esmagam a cabeça dos pobres no pó da terra","e desviam o caminho dos humildes;","o filho e o pai vão à mesma moça,","profanando o meu santo nome;"],np:1},
{v:8,l:["deitam-se junto a qualquer altar","sobre roupas tomadas em penhor","e bebem, na casa do seu Deus,","o vinho cobrado dos multados."],np:1,n:"A lei mandava devolver antes da noite o manto tomado em penhor (Êxodo 22,25–26)."},
{v:9,l:["Contudo, fui eu que exterminei","o amorreu diante deles,","alto como os cedros","e forte como os carvalhos;","destruí o seu fruto por cima","e as suas raízes por baixo."],np:1},
{v:10,l:["Fui eu que vos fiz subir","da terra do Egito","e vos conduzi pelo deserto","durante quarenta anos,","para que possuísseis a terra do amorreu;"],np:1},
{v:11,l:["e suscitei profetas entre os vossos filhos e nazireus entre os vossos jovens.","Não é assim, filhos de Israel?","— oráculo do Senhor."],np:1,n:"Nazireus: consagrados a Deus por um voto que proibia o vinho (Números 6,1–21)."},
{v:12,l:["Mas vós destes vinho aos nazireus","e ordenastes aos profetas:","Não profetizeis!"],np:1},
{v:13,l:["Pois eu vou esmagar-vos contra o chão,","como esmaga uma carroça","carregada de feno."],np:1,n:"Hebraico obscuro; a Nova Vulgata entende assim."},
{v:14,l:["O veloz não conseguirá fugir,","o forte não firmará a sua força,","e o valente não salvará a sua vida;"],np:1},
{v:15,l:["o arqueiro não resistirá,","o de pés ligeiros não escapará,","o cavaleiro não salvará a sua vida,"],np:1},
{v:16,l:["e o mais corajoso entre os valentes","fugirá nu naquele dia,","oráculo do Senhor."],np:1}
];

window.TEXTOS_SEED["amos"][3] = [
{s:"Escolhidos e por isso castigados"},
{v:1,t:"Ouvi esta palavra que o Senhor pronunciou contra vós, filhos de Israel, contra toda a família que eu fiz subir da terra do Egito:"},
{v:2,l:["Só a vós conheci","entre todas as famílias da terra;","por isso vos pedirei contas","de todas as vossas iniquidades."],np:1,n:"Conhecer: aqui, escolher com amor, como numa aliança. A eleição não é privilégio, mas responsabilidade."},
{s:"Quando o leão ruge"},
{v:3,l:["Andam dois juntos sem estarem de acordo?"]},
{v:4,l:["Ruge o leão na floresta","sem ter uma presa?","Solta o leãozinho a sua voz da toca","sem ter apanhado alguma coisa?"],np:1},
{v:5,l:["Cai o pássaro por terra","sem uma armadilha?","Salta do chão a armadilha sem ter apanhado nada?"],np:1},
{v:6,l:["Soa a trombeta na cidade,","e o povo não se assusta?","Acontece uma desgraça na cidade","sem que o Senhor a tenha causado?"],np:1,n:"Nota do tradutor: a desgraça de que se fala é a calamidade, e não o pecado; o profeta não admite que nada aconteça fora do governo de Deus. O texto não foi suavizado."},
{v:7,l:["Pois o Senhor Deus não faz coisa alguma","sem revelar o seu segredo","aos seus servos, os profetas."],np:1},
{v:8,l:["O leão rugiu:","quem não temerá?","O Senhor Deus falou:","quem não profetizará?"],np:1},
{s:"Contra Samaria"},
{v:9,l:["Fazei ouvir nos palácios da Assíria","e nos palácios da terra do Egito","e dizei: Reuni-vos sobre os montes de Samaria","e vede quantas desordens há no meio dela","e quantos oprimidos no seu seio."],n:"Assíria: assim a Nova Vulgata, com a tradução grega; o hebraico diz: Azoto. Os estrangeiros são chamados como testemunhas."},
{v:10,l:["Não sabem agir com retidão,","oráculo do Senhor,","os que acumulam violência e rapina","nos seus palácios."],np:1},
{v:11,l:["Por isso assim diz o Senhor Deus:","O inimigo cercará a terra,","a tua força te será arrancada,","e os teus palácios serão saqueados."],np:1},
{v:12,l:["Assim diz o Senhor:","Como o pastor arranca da boca do leão","duas patas ou a ponta de uma orelha, assim serão arrancados os filhos de Israel","que habitam em Samaria,","na beira de um leito","e num divã de Damasco."],np:1,n:"O pastor devia apresentar os restos do animal devorado, como prova de que não o tinha roubado (Êxodo 22,12): de Israel sobrará tão pouco quanto isso. O fim do versículo é obscuro no hebraico."},
{v:13,l:["Ouvi e testemunhai contra a casa de Jacó,","oráculo do Senhor, o Deus dos exércitos:"],np:1},
{v:14,l:["No dia em que eu castigar os crimes de Israel,","castigarei também os altares de Betel;","os chifres do altar serão cortados","e cairão por terra."],np:1,n:"Os chifres do altar: as pontas dos seus quatro cantos, lugar de refúgio (1 Reis 1,50). Betel era o grande santuário do reino do norte."},
{v:15,l:["Destruirei a casa de inverno","com a casa de verão;","as casas de marfim perecerão,","e os grandes palácios desaparecerão,","oráculo do Senhor."],np:1,n:"Casas de marfim: decoradas com placas de marfim, como as que se encontraram nas escavações de Samaria."}
];

window.TEXTOS_SEED["amos"][4] = [
{s:"Contra as mulheres de Samaria"},
{v:1,l:["Ouvi esta palavra,","vacas de Basã,","que estais no monte de Samaria,","que oprimis os fracos","e maltratais os pobres,","que dizeis aos vossos maridos:","Trazei-nos de beber!"],n:"Vacas de Basã: as senhoras ricas de Samaria; Basã, além do Jordão, era famosa pelo seu gado gordo."},
{v:2,l:["O Senhor Deus jurou","pela sua santidade:","Eis que virão dias sobre vós","em que vos levarão com ganchos,","e os vossos descendentes, com anzóis de pesca;"],np:1},
{v:3,l:["saireis pelas brechas da muralha, uma atrás da outra,","e sereis lançadas no Armon,","oráculo do Senhor."],np:1,n:"Armon: lugar desconhecido; o hebraico é obscuro."},
{s:"Culto sem conversão"},
{v:4,l:["Ide a Betel e pecai,","a Guilgal e multiplicai as transgressões;","oferecei de manhã os vossos sacrifícios","e, a cada três dias, os vossos dízimos;"],n:"Ironia do profeta: sem justiça, o culto nos santuários só multiplica o pecado."},
{v:5,l:["queimai pão fermentado em sacrifício de louvor,","anunciai e proclamai as ofertas voluntárias,","pois é disso que gostais, filhos de Israel,","oráculo do Senhor Deus."],np:1},
{s:"Mas não voltastes para mim"},
{v:6,l:["Também fui eu que vos dei","dentes limpos em todas as vossas cidades","e falta de pão em todos os vossos lugares;","mas não voltastes para mim,","oráculo do Senhor."],n:"Dentes limpos: por não haver nada para comer."},
{v:7,l:["Também vos neguei a chuva,","quando ainda faltavam três meses para a colheita;","mandei chuva sobre uma cidade","e sobre outra cidade não a mandei: um campo recebeu chuva,","e o campo sobre o qual não choveu secou."],np:1},
{v:8,l:["Duas, três cidades corriam","a outra cidade para beber água,","e não se saciavam;","mas não voltastes para mim,","oráculo do Senhor."],np:1},
{v:9,l:["Eu vos feri com o vento abrasador e com a ferrugem;","os vossos numerosos pomares e vinhas,","as vossas figueiras e oliveiras,","o gafanhoto os devorou;","mas não voltastes para mim,","oráculo do Senhor."],np:1,n:"Ferrugem: doença que resseca as espigas."},
{v:10,l:["Mandei contra vós a peste,","como a peste do Egito;","matei à espada os vossos jovens,","enquanto os vossos cavalos eram capturados;","fiz subir às vossas narinas","o mau cheiro dos vossos acampamentos;","mas não voltastes para mim,","oráculo do Senhor."],np:1},
{v:11,l:["Eu vos destruí","como Deus destruiu Sodoma e Gomorra,","e fostes como um tição","arrancado do incêndio;","mas não voltastes para mim,","oráculo do Senhor."],np:1},
{v:12,l:["Por isso assim farei contigo, Israel;","e, porque assim farei contigo,","prepara-te para o encontro com o teu Deus, Israel;"],np:1},
{v:13,l:["pois eis aquele que forma os montes e cria o vento,","que revela ao homem o seu pensamento,","que faz a aurora e as trevas","e caminha sobre as alturas da terra:","Senhor, Deus dos exércitos, é o seu nome."],np:1,n:"Primeiro de três fragmentos de um hino ao Criador que pontuam o livro (5,8–9; 9,5–6)."}
];

window.TEXTOS_SEED["amos"][5] = [
{s:"Lamentação sobre Israel"},
{v:1,l:["Ouvi esta palavra","que entoo sobre vós,","uma lamentação, casa de Israel:"]},
{v:2,l:["Caiu, e não tornará a levantar-se,","a virgem de Israel;","está estendida sobre a sua terra,","e não há quem a levante."],np:1,n:"O profeta canta o lamento fúnebre de Israel, como se ele já estivesse morto."},
{v:3,l:["Pois assim diz o Senhor Deus:","A cidade de onde saíam mil","ficará com cem;","e a de onde saíam cem","ficará com dez,","para a casa de Israel."],np:1},
{s:"Buscai o Senhor e vivereis"},
{v:4,l:["Pois assim diz o Senhor à casa de Israel:","Buscai-me e vivereis;"]},
{v:5,l:["não busqueis Betel,","não entreis em Guilgal","e não passeis para Bersabeia,","pois Guilgal irá para o exílio,","e Betel se tornará iniquidade."],np:1,n:"No hebraico, jogos de palavras: Guilgal irá para o exílio soa como haggilgal galoh yigleh; e Betel, casa de Deus, se tornará Áven, isto é, iniquidade ou nada (compare Oseias 4,15)."},
{v:6,l:["Buscai o Senhor e vivereis,","para que ele não irrompa como fogo","sobre a casa de José","e a devore, sem que haja","quem o apague em Betel."],np:1,n:"A casa de José: as tribos de Efraim e Manassés, o coração do reino do norte."},
{v:7,l:["Eles transformam o direito em absinto","e jogam por terra a justiça."],np:1,n:"Absinto: planta amarga. O versículo 7 continua no 10; os versículos 8–9 são outro fragmento do hino ao Criador (compare 4,13)."},
{v:8,l:["Aquele que fez as Plêiades e o Órion,","que transforma as trevas em manhã","e escurece o dia em noite,","que chama as águas do mar","e as derrama sobre a face da terra:","Senhor é o seu nome."],np:1},
{v:9,l:["Ele faz relampejar a ruína sobre o forte","e faz cair a ruína sobre a fortaleza."],np:1},
{v:10,l:["Odeiam quem os repreende à porta","e detestam quem fala com integridade."],np:1,n:"A porta da cidade era o lugar dos julgamentos."},
{v:11,l:["Por isso, porque pisais o pobre","e lhe tirais a sua parte do trigo,","construístes casas de pedra lavrada,","mas não habitareis nelas;","plantastes vinhas deliciosas,","mas não bebereis o seu vinho."],np:1},
{v:12,l:["Pois conheço os vossos numerosos crimes","e os vossos enormes pecados:","oprimis o justo, aceitais suborno","e, à porta, negais justiça aos pobres."],np:1},
{v:13,l:["Por isso o prudente se cala nesse tempo,","porque é um tempo mau."],np:1},
{v:14,l:["Buscai o bem, e não o mal,","para que vivais;","e assim o Senhor, Deus dos exércitos,","estará convosco, como dizeis."],np:1},
{v:15,l:["Odiai o mal e amai o bem","e estabelecei o direito à porta;","talvez o Senhor, Deus dos exércitos,","tenha compaixão do resto de José."],np:1},
{s:"Luto em todas as praças"},
{v:16,l:["Por isso assim diz o Senhor,","o Deus dos exércitos, o Soberano:","Em todas as praças haverá lamentação,","e em todas as ruas se dirá: Ai! Ai!","Chamarão o lavrador para o luto","e para o pranto os que sabem entoar lamentações."]},
{v:17,l:["Em todas as vinhas haverá luto,","pois passarei no meio de ti,","diz o Senhor."],np:1,n:"Passarei no meio de ti: como na noite da Páscoa, no Egito, mas agora contra Israel (Êxodo 12,12)."},
{s:"O dia do Senhor"},
{v:18,l:["Ai dos que desejam o dia do Senhor!","Que será para vós o dia do Senhor?","Trevas, e não luz."],n:"O povo esperava o dia do Senhor como dia de vitória; Amós o anuncia como dia de julgamento."},
{v:19,l:["É como um homem que foge do leão","e dá com um urso;","entra em casa,","apoia a mão na parede,","e uma cobra o morde."],np:1},
{v:20,l:["Não será trevas o dia do Senhor, e não luz?","Escuridão, sem nenhum brilho?"],np:1},
{s:"Quero o direito, e não sacrifícios"},
{v:21,l:["Odeio, desprezo as vossas festas","e não me agradam as vossas assembleias."]},
{v:22,l:["Ainda que me ofereçais holocaustos,","não aceitarei as vossas oferendas","e não olharei para os sacrifícios dos vossos animais gordos."],np:1},
{v:23,l:["Afasta de mim o barulho dos teus cantos;","não quero ouvir a música das tuas liras."],np:1},
{v:24,l:["Que o direito corra como a água,","e a justiça, como um rio que nunca seca."],np:1},
{v:25,l:["Acaso me oferecestes vítimas e oferendas no deserto,","durante quarenta anos, casa de Israel?"],np:1},
{v:26,l:["Carregastes Sacut, o vosso rei,","e Caivã, as vossas imagens,","a estrela dos vossos deuses, que fizestes para vós."],np:1,n:"Sacut e Caivã: divindades astrais da Assíria, ligadas ao planeta Saturno. Estêvão cita os versículos 25–27 na versão grega (Atos 7,42–43)."},
{v:27,l:["Por isso vos deportarei para além de Damasco,","diz o Senhor: Deus dos exércitos é o seu nome."],np:1}
];

window.TEXTOS_SEED["amos"][6] = [
{s:"Ai dos que vivem tranquilos"},
{v:1,l:["Ai dos que vivem tranquilos em Sião","e dos que se sentem seguros no monte de Samaria,","os notáveis da primeira das nações,","a quem recorre a casa de Israel!"]},
{v:2,l:["Passai por Calane e vede;","ide de lá a Emat, a grande,","e descei a Gat dos filisteus.","Sois melhores do que esses reinos?","Ou é o território deles maior que o vosso?"],np:1,n:"Calane e Emat, cidades da Síria, e Gat, cidade dos filisteus, tinham caído nas mãos de inimigos: Samaria não é mais forte do que elas."},
{v:3,l:["Vós afastais o dia da desgraça","e aproximais o reinado da violência."],np:1},
{v:4,l:["Deitam-se em leitos de marfim,","estendidos nos seus divãs,","comem cordeiros do rebanho","e bezerros tirados do estábulo;"],np:1},
{v:5,l:["cantam ao som da harpa","e, como Davi, inventam para si instrumentos de música;"],np:1},
{v:6,l:["bebem vinho em taças","e se perfumam com os óleos mais finos,","mas não se afligem com a ruína de José."],np:1},
{v:7,l:["Por isso agora irão para o exílio à frente dos deportados,","e acabará a festa dos devassos."],np:1},
{s:"O Senhor detesta o orgulho de Jacó"},
{v:8,l:["O Senhor Deus jurou por si mesmo,","oráculo do Senhor, Deus dos exércitos:","Detesto o orgulho de Jacó","e odeio os seus palácios;","entregarei a cidade com tudo o que ela contém."]},
{v:9,l:["Se restarem","dez homens numa casa,","também eles morrerão;"],np:1},
{v:10,l:["um parente virá buscar o morto","e queimá-lo, para levar os ossos para fora da casa,","e dirá ao que está no fundo da casa:","Há ainda alguém contigo?","Ele responderá: Ninguém.","E o outro dirá: Silêncio!","Não há quem mencione o nome do Senhor."],np:1,n:"Hebraico obscuro. Talvez: não se deve mencionar o nome do Senhor, para não atrair sobre a casa atingida um novo castigo."},
{v:11,l:["Pois eis que o Senhor dá ordens,","e ele reduzirá a escombros a casa grande","e a pedaços a casa pequena."],np:1},
{v:12,l:["Correm cavalos sobre os rochedos,","ou se lavra o mar com bois?","Mas vós transformastes o direito em veneno","e o fruto da justiça em absinto."],np:1,n:"Ou se lavra o mar com bois: assim a Nova Vulgata, com uma pequena correção do hebraico, que diz: ou se lavra com bois?"},
{v:13,l:["Eles se alegram por Lodabar","e dizem: Não foi com a nossa força","que tomamos Carnaim?"],np:1,n:"Lodabar e Carnaim: cidades de Galaad retomadas por Jeroboão II. Jogo de palavras: Lodabar significa coisa de nada; Carnaim, chifres, símbolo de força."},
{v:14,l:["Pois eis que levantarei contra vós, casa de Israel,","oráculo do Senhor, Deus dos exércitos, uma nação,","e ela vos oprimirá desde a entrada de Emat","até a torrente da Arabá."],np:1,n:"De Emat, ao norte, até a torrente da Arabá, ao sul: todo o território que Jeroboão II tinha reconquistado (2 Reis 14,25)."}
];

window.TEXTOS_SEED["amos"][7] = [
{s:"Primeira visão: os gafanhotos"},
{v:1,t:"Eis o que o Senhor Deus me mostrou: ele formava gafanhotos quando começava a brotar a erva tardia, a erva que brota depois da ceifa reservada ao rei.",n:"A ceifa reservada ao rei: o primeiro corte do capim, entregue como tributo para os animais do rei."},
{v:2,t:"Quando eles acabaram de devorar a erva da terra, eu disse: Senhor Deus, perdoa, eu te suplico! Como poderá Jacó subsistir, sendo tão pequeno?"},
{v:3,t:"O Senhor se compadeceu disso: Não acontecerá, disse o Senhor Deus."},
{s:"Segunda visão: o fogo"},
{v:4,t:"Eis o que o Senhor Deus me mostrou: o Senhor Deus convocava o fogo para o julgamento, e o fogo devorou o grande abismo e ia devorando também a terra.",n:"A terra: literalmente, a porção, a terra repartida entre as tribos."},
{v:5,t:"Eu disse: Senhor Deus, para, eu te suplico! Como poderá Jacó subsistir, sendo tão pequeno?"},
{v:6,t:"O Senhor se compadeceu disso: Também isto não acontecerá, disse o Senhor Deus."},
{s:"Terceira visão: a colher de pedreiro"},
{v:7,t:"Eis o que o Senhor Deus me mostrou: um homem de pé sobre um muro rebocado, com uma colher de pedreiro na mão.",n:"Um homem: assim a Nova Vulgata, com a tradução grega; o hebraico diz: o Senhor. A palavra hebraica anak, traduzida aqui por colher de pedreiro, é de sentido incerto; muitos a entendem como fio de prumo."},
{v:8,t:"O Senhor me disse: Que vês, Amós? Respondi: Uma colher de pedreiro. E o Senhor disse: Eis que vou pôr uma colher de pedreiro no meio do meu povo Israel; não tornarei a perdoar-lhe."},
{v:9,t:"Os lugares altos de Isaac serão destruídos, os santuários de Israel serão devastados, e eu me levantarei com a espada contra a casa de Jeroboão."},
{s:"Amós e Amasias"},
{v:10,t:"Então Amasias, sacerdote de Betel, mandou dizer a Jeroboão, rei de Israel: Amós está conspirando contra ti no meio da casa de Israel; a terra não pode mais suportar todas as suas palavras."},
{v:11,t:"Pois assim diz Amós: Jeroboão morrerá pela espada, e Israel será deportado para longe da sua terra."},
{v:12,t:"E Amasias disse a Amós: Vidente, vai-te embora! Foge para a terra de Judá; come lá o teu pão e profetiza lá;"},
{v:13,t:"mas em Betel não profetizes mais, porque é o santuário do rei e um templo do reino."},
{v:14,l:["Amós respondeu a Amasias:","Eu não sou profeta","nem filho de profeta;","sou vaqueiro e cultivo sicômoros."],n:"Filho de profeta: membro de uma confraria de profetas profissionais. Os frutos do sicômoro eram picados para amadurecerem."},
{v:15,l:["Mas o Senhor me tomou","quando eu seguia o rebanho,","e o Senhor me disse:","Vai, profetiza ao meu povo Israel."],np:1},
{v:16,t:"E agora ouve a palavra do Senhor. Tu dizes: Não profetizes contra Israel e não pregues contra a casa de Isaac.",np:1},
{v:17,t:"Por isso assim diz o Senhor: A tua mulher se prostituirá na cidade, os teus filhos e as tuas filhas cairão pela espada, a tua terra será repartida a cordel, e tu morrerás numa terra impura, e Israel será deportado para longe da sua terra.",n:"Nota do tradutor: a sentença descreve o que sofriam as famílias numa cidade conquistada; o texto não foi suavizado. Terra impura: terra estrangeira, onde não se podia oferecer culto ao Senhor."}
];

window.TEXTOS_SEED["amos"][8] = [
{s:"Quarta visão: o cesto de frutas maduras"},
{v:1,l:["Eis o que o Senhor Deus me mostrou:","um cesto de frutas maduras."]},
{v:2,l:["Ele disse: Que vês, Amós?","Respondi: Um cesto de frutas maduras.","E o Senhor me disse:","Chegou o fim para o meu povo Israel;","não tornarei a perdoar-lhe."],np:1,n:"No hebraico, jogo de palavras: qayits, fruta do fim do verão, e qets, fim."},
{v:3,l:["Naquele dia, as cantoras do palácio se lamentarão,","oráculo do Senhor Deus;","serão muitos os cadáveres,","em toda parte serão jogados: silêncio!"],np:1},
{s:"Contra os que exploram os pobres"},
{v:4,l:["Ouvi isto, vós que esmagais o pobre","e quereis eliminar os humildes da terra,"]},
{v:5,l:["vós que dizeis: Quando passará a lua nova,","para vendermos as nossas mercadorias?","E o sábado, para abrirmos os celeiros,","para diminuirmos a medida e aumentarmos o siclo","e usarmos balanças falsas,"],np:1,n:"Diminuíam a medida do trigo vendido e aumentavam o peso da prata recebida."},
{v:6,l:["para comprarmos os fracos por dinheiro","e o pobre por um par de sandálias,","e para vendermos até o refugo do trigo?"],np:1},
{v:7,l:["O Senhor jurou pelo orgulho de Jacó:","Jamais esquecerei nenhuma das suas obras."],np:1,n:"O orgulho de Jacó: talvez o próprio Senhor, a glória de Israel; ou, com ironia, a arrogância do povo (6,8)."},
{v:8,l:["Não tremerá a terra por causa disso,","e não estarão de luto todos os seus habitantes?","Não subirá toda ela como o rio,","não se agitará e baixará como o rio do Egito?"],np:1,n:"O rio do Egito: o Nilo, com as suas cheias anuais."},
{s:"Luto como por um filho único"},
{v:9,l:["Naquele dia acontecerá,","oráculo do Senhor Deus:","farei o sol se pôr ao meio-dia","e escurecerei a terra em pleno dia;"],n:"Talvez lembrança de um eclipse do sol, como o de 763 antes de Cristo."},
{v:10,l:["transformarei as vossas festas em luto","e todos os vossos cantos em lamentação;","farei que todos vistam pano de saco","e que todas as cabeças sejam raspadas;","farei dela um luto como por um filho único,","e o seu fim será como um dia amargo."],np:1},
{s:"Fome da palavra do Senhor"},
{v:11,l:["Eis que vêm dias,","oráculo do Senhor,","em que mandarei fome sobre a terra;","não fome de pão nem sede de água,","mas de ouvir a palavra do Senhor."]},
{v:12,l:["Andarão errantes de mar a mar","e correrão do norte ao oriente,","buscando a palavra do Senhor,","e não a encontrarão."],np:1},
{v:13,l:["Naquele dia desfalecerão de sede","as moças bonitas e os rapazes."],np:1},
{v:14,l:["Os que juram pelo pecado de Samaria","e dizem: Pela vida do teu Deus, Dã!","e: Pela vida do caminho de Bersabeia!","cairão e não se levantarão mais."],np:1,n:"O pecado de Samaria: talvez o bezerro de ouro de Betel, ou uma divindade pagã. Dã e Bersabeia eram santuários do extremo norte e do extremo sul; jurava-se até pela peregrinação a Bersabeia."}
];

window.TEXTOS_SEED["amos"][9] = [
{s:"Quinta visão: ninguém escapará"},
{v:1,l:["Vi o Senhor","de pé junto ao altar,","e ele disse: Golpeia o capitel,","e que tremam os umbrais;","quebra-os sobre a cabeça de todos,","e o resto deles eu matarei à espada;","nenhum deles conseguirá fugir,","nenhum sobrevivente escapará."]},
{v:2,l:["Ainda que desçam à morada dos mortos,","de lá a minha mão os tirará;","ainda que subam ao céu,","de lá os farei descer."],np:1},
{v:3,l:["Ainda que se escondam no alto do Carmelo,","lá os procurarei e os agarrarei;","ainda que se ocultem dos meus olhos","no fundo do mar,","lá ordenarei à serpente que os morda;"],np:1},
{v:4,l:["ainda que vão para o exílio","diante dos seus inimigos,","lá ordenarei à espada que os mate;","porei os meus olhos sobre eles","para o mal, e não para o bem."],np:1},
{v:5,l:["O Senhor, Deus dos exércitos,","toca a terra, e ela se derrete;","todos os seus habitantes ficam de luto;","ela sobe toda como o rio","e baixa como o rio do Egito."],np:1},
{v:6,l:["Ele constrói no céu os seus aposentos","e firma a sua abóbada sobre a terra;","chama as águas do mar","e as derrama sobre a face da terra:","Senhor é o seu nome."],np:1,n:"Último fragmento do hino ao Criador (compare 4,13; 5,8–9)."},
{s:"Israel entre as nações"},
{v:7,l:["Não sois para mim como os etíopes,","filhos de Israel?","— oráculo do Senhor.","Não fiz eu Israel subir","da terra do Egito,","os filisteus de Caftor","e os sírios de Quir?"],n:"Caftor: Creta. O Senhor conduz a história de todos os povos; a saída do Egito não dá a Israel nenhuma garantia, se ele não for fiel."},
{v:8,l:["Eis que os olhos do Senhor Deus","estão sobre o reino pecador,","e eu o exterminarei","da face da terra;","mas não exterminarei por completo","a casa de Jacó,","oráculo do Senhor."],np:1},
{v:9,l:["Pois eis que darei ordens","e sacudirei a casa de Israel entre todas as nações,","como se sacode o trigo na peneira,","sem que caia por terra uma só pedrinha."],np:1},
{v:10,l:["Morrerão à espada todos os pecadores do meu povo,","que dizem: A desgraça não se aproximará","nem nos alcançará."],np:1},
{s:"A tenda de Davi será reerguida"},
{v:11,l:["Naquele dia levantarei","a tenda de Davi, que caiu,","e repararei as suas brechas;","reerguerei o que estava em ruínas","e a reconstruirei como nos dias antigos,"],n:"A tenda de Davi: a dinastia davídica em ruínas. Tiago cita 9,11–12 na versão grega no encontro dos apóstolos em Jerusalém (Atos 15,16–17)."},
{v:12,l:["para que possuam","o resto de Edom","e todas as nações","sobre as quais foi invocado o meu nome,","oráculo do Senhor, que fará estas coisas."],np:1},
{v:13,l:["Eis que vêm dias,","oráculo do Senhor,","em que o lavrador alcançará o ceifeiro,","e o que pisa as uvas, o que semeia; os montes destilarão vinho novo,","e todas as colinas se derreterão."],np:1,n:"Imagem de uma fertilidade tão grande que uma colheita emenda na outra."},
{v:14,l:["Farei voltar os cativos do meu povo Israel;","reconstruirão as cidades devastadas e as habitarão,","plantarão vinhas e beberão o seu vinho,","cultivarão pomares e comerão os seus frutos."],np:1},
{v:15,l:["Eu os plantarei na sua terra,","e não serão mais arrancados","da terra que lhes dei,","diz o Senhor, teu Deus."],np:1}
];
