// =====================================================================
// Apocalipse — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["apocalipse"][1] = [
{s:"Prólogo"},
{v:1,t:"Revelação de Jesus Cristo, que Deus lhe deu para mostrar aos seus servos o que deve acontecer em breve. E ele a deu a conhecer, enviando o seu anjo ao seu servo João,",n:"Apocalipse quer dizer, em grego, o levantar do véu. O livro não foi escrito para adivinhar datas, mas para sustentar comunidades perseguidas, mostrando-lhes o desfecho já garantido."},
{v:2,t:"o qual atesta, como palavra de Deus e testemunho de Jesus Cristo, tudo o que viu."},
{v:3,t:"Bem-aventurado aquele que lê, e os que ouvem as palavras desta profecia e guardam o que nela está escrito; porque o tempo está próximo."},
{s:"Saudação às sete Igrejas"},
{v:4,t:"João, às sete Igrejas que estão na Ásia: graça e paz a vós, da parte daquele que é, que era e que vem, e dos sete espíritos que estão diante do seu trono,"},
{v:5,t:"e da parte de Jesus Cristo, a testemunha fiel, o primogênito dentre os mortos e o príncipe dos reis da terra. Àquele que nos ama e nos libertou dos nossos pecados pelo seu sangue,"},
{v:6,t:"e fez de nós um reino, sacerdotes para Deus, seu Pai — a ele a glória e o poder pelos séculos dos séculos. Amém."},
{v:7,l:["Eis que vem com as nuvens,","e todo olho o verá,","até os que o traspassaram;","e por causa dele hão de bater no peito todas as tribos da terra.","Sim. Amém."]},
{v:8,t:"Eu sou o Alfa e o Ômega, diz o Senhor Deus, aquele que é, que era e que vem, o Todo-Poderoso.",np:1},
{s:"A visão do Filho do homem"},
{v:9,t:"Eu, João, vosso irmão e companheiro na tribulação, no Reino e na perseverança em Jesus, estava na ilha de Patmos, por causa da palavra de Deus e do testemunho de Jesus."},
{v:10,t:"No dia do Senhor, fui arrebatado em espírito e ouvi atrás de mim uma voz forte, como de trombeta,"},
{v:11,t:"que dizia: O que vês, escreve-o num livro e envia-o às sete Igrejas: a Éfeso, a Esmirna, a Pérgamo, a Tiatira, a Sardes, a Filadélfia e a Laodiceia."},
{v:12,t:"Voltei-me para ver a voz que falava comigo; e, ao voltar-me, vi sete candelabros de ouro,"},
{v:13,t:"e no meio dos candelabros alguém semelhante a um filho de homem, vestido de uma túnica até os pés e cingido ao peito com um cinto de ouro."},
{v:14,t:"A sua cabeça e os seus cabelos eram brancos como a lã branca, como a neve; os seus olhos, como chama de fogo;"},
{v:15,t:"os seus pés, semelhantes ao bronze incandescente, como purificado na fornalha; e a sua voz, como a voz de muitas águas."},
{v:16,t:"Tinha na mão direita sete estrelas; da sua boca saía uma espada afiada de dois gumes; e o seu rosto era como o sol quando brilha em todo o seu vigor."},
{v:17,t:"Ao vê-lo, caí a seus pés como morto. Mas ele pôs sobre mim a mão direita e disse: Não temas. Eu sou o primeiro e o último,",np:1},
{v:18,t:"o que vive. Estive morto, e eis que vivo pelos séculos dos séculos, e tenho as chaves da morte e do abismo."},
{v:19,t:"Escreve, pois, o que viste, o que é e o que há de acontecer depois."},
{v:20,t:"Quanto ao mistério das sete estrelas que viste na minha mão direita e dos sete candelabros de ouro: as sete estrelas são os anjos das sete Igrejas, e os sete candelabros são as sete Igrejas."}
];

window.TEXTOS_SEED["apocalipse"][2] = [
{s:"Carta à Igreja de Éfeso"},
{v:1,t:"Ao anjo da Igreja que está em Éfeso, escreve: Assim fala aquele que segura as sete estrelas na mão direita, aquele que anda no meio dos sete candelabros de ouro:",n:"O anjo de cada Igreja pode ser o seu anjo protetor ou, segundo muitos, quem a preside. As sete cartas seguem o mesmo esquema: quem fala, o que ele conhece da Igreja, a advertência e a promessa ao vencedor."},
{v:2,t:"Conheço as tuas obras, o teu esforço e a tua perseverança; sei que não podes suportar os maus, que puseste à prova os que se dizem apóstolos e não o são, e os achaste mentirosos;"},
{v:3,t:"tens perseverança, sofreste por causa do meu nome e não desanimaste."},
{v:4,t:"Mas tenho contra ti que abandonaste o teu primeiro amor."},
{v:5,t:"Lembra-te, pois, de onde caíste, converte-te e volta às obras do princípio; se não, virei a ti e tirarei o teu candelabro do seu lugar, se não te converteres."},
{v:6,t:"Tens, porém, isto a teu favor: odeias as obras dos nicolaítas, que também eu odeio.",n:"Nicolaítas: grupo que, ao que parece, admitia comer carnes sacrificadas aos ídolos e tomar parte nos cultos pagãos (compare 2,14–15). A tradição antiga os ligava ao diácono Nicolau (Atos 6,5), mas sem fundamento seguro."},
{v:7,t:"Quem tem ouvidos ouça o que o Espírito diz às Igrejas. Ao vencedor darei de comer da árvore da vida, que está no paraíso de Deus.",np:1,n:"A árvore da vida, fechada ao homem depois do pecado (Gênesis 3,22–24), volta a ser oferecida no fim (22,2.14)."},
{s:"Carta à Igreja de Esmirna"},
{v:8,t:"Ao anjo da Igreja que está em Esmirna, escreve: Assim fala o Primeiro e o Último, aquele que esteve morto e voltou à vida:"},
{v:9,t:"Conheço a tua tribulação e a tua pobreza — e, no entanto, és rico — e a calúnia dos que se dizem judeus e não o são, mas são uma sinagoga de Satanás.",n:"Nota do tradutor: a expressão é dura, e o texto não foi suavizado. É a polêmica entre comunidades vizinhas num tempo de perseguição: o autor, ele mesmo judeu, nega o nome de judeus aos que denunciavam os cristãos às autoridades. Não é um juízo sobre o povo judeu (compare Romanos 2,28–29; 11,1–2)."},
{v:10,t:"Não tenhas medo do que vais sofrer. Eis que o diabo vai lançar alguns de vós na prisão, para serdes postos à prova, e tereis uma tribulação de dez dias. Sê fiel até a morte, e eu te darei a coroa da vida."},
{v:11,t:"Quem tem ouvidos ouça o que o Espírito diz às Igrejas. O vencedor não sofrerá dano algum da segunda morte.",np:1,n:"A segunda morte é a condenação definitiva (20,14; 21,8)."},
{s:"Carta à Igreja de Pérgamo"},
{v:12,t:"Ao anjo da Igreja que está em Pérgamo, escreve: Assim fala aquele que tem a espada afiada de dois gumes:"},
{v:13,t:"Sei onde moras: onde está o trono de Satanás. E tu seguras firme o meu nome e não renegaste a minha fé, nem mesmo nos dias de Antipas, a minha testemunha fiel, que foi morto entre vós, onde Satanás mora.",n:"O trono de Satanás: talvez o grande altar de Zeus que dominava Pérgamo, ou antes o culto ao imperador, de que a cidade era o centro na província da Ásia."},
{v:14,t:"Mas tenho contra ti algumas coisas: tens aí alguns que seguem a doutrina de Balaão, que ensinava Balac a pôr uma armadilha diante dos filhos de Israel, para que comessem carnes sacrificadas aos ídolos e se prostituíssem;",np:1,n:"Segundo Números 31,16, foi de Balaão o conselho que levou Israel à idolatria e à prostituição em Baal-Fogor (Números 25,1–3)."},
{v:15,t:"assim também tu tens alguns que seguem, do mesmo modo, a doutrina dos nicolaítas."},
{v:16,t:"Converte-te, pois; se não, virei a ti em breve e lutarei contra eles com a espada da minha boca.",np:1},
{v:17,t:"Quem tem ouvidos ouça o que o Espírito diz às Igrejas. Ao vencedor darei do maná escondido, e lhe darei uma pedrinha branca, e na pedrinha está escrito um nome novo, que ninguém conhece, a não ser quem o recebe.",np:1,n:"O maná escondido é o alimento do mundo que há de vir. A pedrinha branca servia na Antiguidade de voto de absolvição num julgamento e de sinal de entrada num banquete."},
{s:"Carta à Igreja de Tiatira"},
{v:18,t:"Ao anjo da Igreja que está em Tiatira, escreve: Assim fala o Filho de Deus, que tem os olhos como chama de fogo e os pés semelhantes ao bronze incandescente:"},
{v:19,t:"Conheço as tuas obras, o teu amor, a tua fé, o teu serviço e a tua perseverança, e sei que as tuas últimas obras são mais numerosas que as primeiras."},
{v:20,t:"Mas tenho contra ti que toleras Jezabel, essa mulher que se diz profetisa e ensina e seduz os meus servos, levando-os a se prostituírem e a comerem carnes sacrificadas aos ídolos.",n:"Jezabel: nome simbólico, tirado da rainha que levou Israel ao culto de Baal (1 Reis 16,31; 2 Reis 9,22); designa uma profetisa da comunidade de Tiatira."},
{v:21,t:"Dei-lhe tempo para se converter, mas ela não quer converter-se da sua prostituição."},
{v:22,t:"Eis que vou lançá-la num leito, e os que cometem adultério com ela, numa grande tribulação, se não se converterem das obras dela.",n:"Num leito: o da doença, castigo que corresponde ao leito do adultério."},
{v:23,t:"Ferirei de morte os seus filhos, e todas as Igrejas saberão que eu sou aquele que sonda os rins e os corações; e darei a cada um de vós segundo as vossas obras.",n:"Os seus filhos: os que seguem o seu ensinamento. Sondar os rins e o coração é, na linguagem bíblica, conhecer o íntimo do homem (Jeremias 17,10)."},
{v:24,t:"Mas a vós, os demais de Tiatira, que não seguis esta doutrina e não conhecestes as profundezas de Satanás, como eles dizem, eu digo: não vos imponho outro fardo;",n:"As profundezas de Satanás: talvez a pretensão de conhecer, pela experiência do mal, segredos profundos. O texto responde com ironia."},
{v:25,t:"somente, segurai firme o que tendes até que eu venha."},
{v:26,t:"E ao vencedor, e a quem guardar até o fim as minhas obras, darei poder sobre as nações,"},
{v:27,l:["e ele as governará com cetro de ferro,","e serão quebradas como vasos de oleiro,"],n:"Citação do Salmo 2,9, aplicado ao Messias também em 12,5 e 19,15."},
{v:28,t:"assim como também eu recebi esse poder de meu Pai; e lhe darei a estrela da manhã.",n:"A estrela da manhã é o próprio Cristo (22,16)."},
{v:29,t:"Quem tem ouvidos ouça o que o Espírito diz às Igrejas.",np:1}
];

window.TEXTOS_SEED["apocalipse"][3] = [
{s:"Carta à Igreja de Sardes"},
{v:1,t:"Ao anjo da Igreja que está em Sardes, escreve: Assim fala aquele que tem os sete espíritos de Deus e as sete estrelas: Conheço as tuas obras; tens fama de estar vivo, mas estás morto."},
{v:2,t:"Sê vigilante e fortalece o que resta e estava para morrer, pois não achei as tuas obras perfeitas diante do meu Deus."},
{v:3,t:"Lembra-te, pois, de como recebeste e ouviste a palavra; guarda-a e converte-te. Se não vigiares, virei como um ladrão, e não saberás a que hora virei a ti.",np:1,n:"Sardes, construída sobre uma colina tida por inexpugnável, foi tomada de surpresa duas vezes, por falta de vigilância. Sobre a vinda como um ladrão, compare Mateus 24,43 e 1 Tessalonicenses 5,2."},
{v:4,t:"Tens, porém, em Sardes algumas pessoas que não mancharam as suas vestes; elas andarão comigo vestidas de branco, porque são dignas.",n:"Algumas pessoas: à letra, alguns nomes."},
{v:5,t:"O vencedor será vestido assim, de vestes brancas, e nunca apagarei o seu nome do livro da vida; e reconhecerei o seu nome diante de meu Pai e diante dos seus anjos.",n:"Compare Mateus 10,32. O livro da vida é o registro dos que pertencem a Deus (Êxodo 32,32–33; Filipenses 4,3)."},
{v:6,t:"Quem tem ouvidos ouça o que o Espírito diz às Igrejas.",np:1},
{s:"Carta à Igreja de Filadélfia"},
{v:7,t:"Ao anjo da Igreja que está em Filadélfia, escreve: Assim fala o Santo, o Verdadeiro, aquele que tem a chave de Davi, que abre, e ninguém fecha; que fecha, e ninguém abre:",n:"Compare Isaías 22,22: a chave da casa de Davi é o poder de admitir no Reino ou de excluir dele."},
{v:8,t:"Conheço as tuas obras. Eis que pus diante de ti uma porta aberta, que ninguém pode fechar, porque, embora tenhas pouca força, guardaste a minha palavra e não renegaste o meu nome."},
{v:9,t:"Eis que te entregarei alguns da sinagoga de Satanás, dos que se dizem judeus e não o são, mas mentem; eis que os farei vir prostrar-se aos teus pés, e saberão que eu te amei.",n:"Sobre esta expressão, veja a nota em 2,9. Em Isaías 60,14 são as nações que vêm prostrar-se diante de Israel; aqui a imagem se aplica à comunidade dos que creem."},
{v:10,t:"Porque guardaste a minha palavra de perseverança, também eu te guardarei da hora da provação que está para vir sobre o mundo inteiro, para pôr à prova os habitantes da terra."},
{v:11,t:"Venho em breve; segura firme o que tens, para que ninguém tome a tua coroa."},
{v:12,t:"Do vencedor farei uma coluna no templo do meu Deus, e ele nunca mais sairá dali; e escreverei sobre ele o nome do meu Deus e o nome da cidade do meu Deus, a nova Jerusalém, que desce do céu, de junto do meu Deus, e o meu nome novo."},
{v:13,t:"Quem tem ouvidos ouça o que o Espírito diz às Igrejas.",np:1},
{s:"Carta à Igreja de Laodiceia"},
{v:14,t:"Ao anjo da Igreja que está em Laodiceia, escreve: Assim fala o Amém, a testemunha fiel e verdadeira, o princípio da criação de Deus:",n:"O Amém: aquele em quem todas as promessas de Deus se cumprem (2 Coríntios 1,20). O princípio da criação: aquele por quem tudo foi feito (Colossenses 1,15–18; João 1,3)."},
{v:15,t:"Conheço as tuas obras: não és frio nem quente. Quem dera fosses frio ou quente!"},
{v:16,t:"Assim, porque és morno, nem quente nem frio, estou para vomitar-te da minha boca.",n:"Laodiceia recebia por aqueduto uma água morna, enquanto a vizinha Hierápolis tinha fontes quentes, e Colossas, água fria: talvez venha daí a imagem."},
{v:17,t:"Dizes que és rico, que enriqueceste e que não precisas de nada, e não sabes que és um infeliz, um miserável, pobre, cego e nu."},
{v:18,t:"Aconselho-te que compres de mim ouro purificado no fogo, para te enriqueceres, e vestes brancas, para te vestires e não aparecer a vergonha da tua nudez, e colírio para ungir os olhos, para que vejas.",np:1,n:"Laodiceia era conhecida pelos seus bancos, pela lã negra das suas ovelhas e por um colírio da sua escola de medicina: o Senhor oferece o verdadeiro ouro, as verdadeiras vestes e o verdadeiro remédio."},
{v:19,t:"Eu repreendo e corrijo todos os que amo. Tem zelo, pois, e converte-te.",n:"Compare Provérbios 3,12 e Hebreus 12,6."},
{v:20,t:"Eis que estou à porta e bato. Se alguém ouvir a minha voz e abrir a porta, entrarei na sua casa e cearei com ele, e ele comigo."},
{v:21,t:"Ao vencedor concederei sentar-se comigo no meu trono, assim como também eu venci e me sentei com meu Pai no seu trono."},
{v:22,t:"Quem tem ouvidos ouça o que o Espírito diz às Igrejas.",np:1}
];

window.TEXTOS_SEED["apocalipse"][4] = [
{s:"O trono de Deus"},
{v:1,t:"Depois disso, olhei, e eis uma porta aberta no céu; e a primeira voz, que eu tinha ouvido falar comigo como uma trombeta, disse: Sobe até aqui, e eu te mostrarei o que deve acontecer depois disso."},
{v:2,t:"Imediatamente fui arrebatado em espírito; e eis que havia um trono posto no céu, e alguém sentado no trono."},
{v:3,t:"Aquele que estava sentado tinha o aspecto semelhante à pedra de jaspe e à de sárdio; e ao redor do trono havia um arco-íris de aspecto semelhante à esmeralda.",n:"João não descreve a figura de Deus: fala só do brilho das pedras e das cores ao redor do trono (compare Ezequiel 1,26–28)."},
{v:4,t:"Ao redor do trono havia vinte e quatro tronos, e sobre os tronos, vinte e quatro anciãos sentados, vestidos de vestes brancas e com coroas de ouro na cabeça.",n:"Os vinte e quatro anciãos representam talvez o povo de Deus inteiro, as doze tribos e os doze apóstolos (compare 21,12–14)."},
{v:5,t:"Do trono saíam relâmpagos, vozes e trovões; e diante do trono ardiam sete lâmpadas de fogo, que são os sete espíritos de Deus;"},
{v:6,t:"e diante do trono havia como que um mar de vidro, semelhante ao cristal. No meio do trono e ao redor do trono havia quatro seres vivos, cheios de olhos pela frente e por trás:",n:"No meio do trono e ao redor do trono: isto é, junto ao trono, em cada um dos lados. Os seres vivos lembram os querubins de Ezequiel 1 e 10 e os serafins de Isaías 6."},
{v:7,t:"o primeiro ser vivo era semelhante a um leão; o segundo ser vivo, semelhante a um novilho; o terceiro ser vivo tinha o rosto como de homem; e o quarto ser vivo era semelhante a uma águia em voo.",n:"Desde os primeiros séculos, a tradição cristã viu nestas quatro figuras os quatro evangelistas: o homem é Mateus, o leão Marcos, o novilho Lucas e a águia João."},
{v:8,t:"Os quatro seres vivos tinham cada um seis asas e estavam cheios de olhos ao redor e por dentro; e dia e noite não cessam de dizer: Santo, santo, santo, o Senhor Deus, o Todo-Poderoso, aquele que era, que é e que vem!",n:"Compare Isaías 6,3. É o hino que a Igreja canta em cada missa, no Santo."},
{v:9,t:"E sempre que os seres vivos dão glória, honra e ação de graças àquele que está sentado no trono, àquele que vive pelos séculos dos séculos,"},
{v:10,t:"os vinte e quatro anciãos se prostram diante daquele que está sentado no trono, adoram aquele que vive pelos séculos dos séculos e lançam as suas coroas diante do trono, dizendo:"},
{v:11,l:["Tu és digno, Senhor e Deus nosso,","de receber a glória, a honra e o poder,","porque tu criaste todas as coisas,","e por tua vontade elas existiam e foram criadas."],np:1,n:"Senhor e Deus nosso: título que o imperador Domiciano, no tempo em que o livro foi provavelmente escrito, exigia que lhe dessem. Os anciãos o reservam a Deus e depõem diante dele as suas coroas."}
];

window.TEXTOS_SEED["apocalipse"][5] = [
{s:"O livro dos sete selos"},
{v:1,t:"Vi na mão direita daquele que estava sentado no trono um livro escrito por dentro e por fora, selado com sete selos.",n:"Livro: um rolo escrito dos dois lados, como o de Ezequiel 2,9–10. Contém o desígnio de Deus sobre a história, que ninguém pode conhecer enquanto está selado."},
{v:2,t:"Vi também um anjo poderoso, que proclamava em alta voz: Quem é digno de abrir o livro e de romper os seus selos?"},
{v:3,t:"E ninguém, nem no céu, nem na terra, nem debaixo da terra, podia abrir o livro nem olhar para ele."},
{v:4,t:"Eu chorava muito, porque não se achou ninguém digno de abrir o livro nem de olhar para ele."},
{v:5,t:"Mas um dos anciãos me disse: Não chores; eis que o Leão da tribo de Judá, a Raiz de Davi, venceu, e pode abrir o livro e os seus sete selos.",n:"Títulos do Messias: compare Gênesis 49,9–10 e Isaías 11,1.10."},
{s:"O Cordeiro recebe o livro"},
{v:6,t:"E vi no meio do trono e dos quatro seres vivos, e no meio dos anciãos, um Cordeiro de pé, como que imolado; tinha sete chifres e sete olhos, que são os sete espíritos de Deus enviados por toda a terra.",n:"Esperava-se um leão, e aparece um Cordeiro: o Messias vence pela sua morte. Como que imolado: traz as marcas da morte, mas está de pé, vivo. Os sete chifres significam a plenitude do poder; os sete olhos, a plenitude do conhecimento (compare Zacarias 4,10)."},
{v:7,t:"Ele veio e o recebeu da mão direita daquele que estava sentado no trono."},
{v:8,t:"Quando recebeu o livro, os quatro seres vivos e os vinte e quatro anciãos se prostraram diante do Cordeiro, tendo cada um uma cítara e taças de ouro cheias de incenso, que são as orações dos santos.",n:"Os santos são os fiéis. As suas orações sobem a Deus como incenso (Salmo 141,2; compare 8,3–4)."},
{v:9,l:["E cantam um cântico novo, dizendo:","Tu és digno de receber o livro","e de abrir os seus selos,","porque foste imolado e, com o teu sangue,","resgataste para Deus","gente de toda tribo, língua, povo e nação,"]},
{v:10,l:["e fizeste deles, para o nosso Deus, um reino e sacerdotes,","e eles reinarão sobre a terra."],n:"Compare Êxodo 19,6 e 1 Pedro 2,9."},
{v:11,t:"Olhei e ouvi a voz de muitos anjos ao redor do trono, dos seres vivos e dos anciãos; o seu número era de miríades de miríades e milhares de milhares,",np:1,n:"Compare Daniel 7,10."},
{v:12,l:["que diziam em alta voz:","Digno é o Cordeiro que foi imolado","de receber o poder, a riqueza, a sabedoria,","a força, a honra, a glória e o louvor."]},
{v:13,t:"E ouvi todas as criaturas que há no céu, na terra, debaixo da terra e no mar, e tudo o que neles existe, que diziam: Àquele que está sentado no trono e ao Cordeiro, o louvor, a honra, a glória e o poder pelos séculos dos séculos.",np:1},
{v:14,t:"E os quatro seres vivos diziam: Amém. E os anciãos se prostraram e adoraram.",np:1}
];

window.TEXTOS_SEED["apocalipse"][6] = [
{s:"Os quatro primeiros selos"},
{v:1,t:"Vi quando o Cordeiro abriu o primeiro dos sete selos, e ouvi um dos quatro seres vivos, que dizia com voz de trovão: Vem!"},
{v:2,t:"Olhei, e eis um cavalo branco; aquele que o montava tinha um arco; foi-lhe dada uma coroa, e ele saiu vencedor e para vencer.",n:"Os quatro cavalos vêm de Zacarias 1,8 e 6,1–3. Muitos Padres viram no cavaleiro do cavalo branco o Cristo vitorioso ou a pregação do Evangelho (compare 19,11); outros, a guerra de conquista, como os três cavaleiros que o seguem."},
{v:3,t:"Quando ele abriu o segundo selo, ouvi o segundo ser vivo, que dizia: Vem!",np:1},
{v:4,t:"E saiu outro cavalo, vermelho como fogo; ao que o montava foi dado o poder de tirar a paz da terra, para que os homens se matassem uns aos outros; e foi-lhe dada uma grande espada.",np:1},
{v:5,t:"Quando ele abriu o terceiro selo, ouvi o terceiro ser vivo, que dizia: Vem! Olhei, e eis um cavalo preto; aquele que o montava tinha na mão uma balança.",np:1},
{v:6,t:"E ouvi como que uma voz no meio dos quatro seres vivos, que dizia: Uma medida de trigo por um denário, e três medidas de cevada por um denário; mas não danifiques o azeite e o vinho.",n:"O denário era o salário de um dia de trabalho (Mateus 20,2); a medida, pouco mais de um litro, a ração diária de um homem. É a carestia: um dia inteiro de trabalho paga apenas o pão desse dia."},
{v:7,t:"Quando ele abriu o quarto selo, ouvi a voz do quarto ser vivo, que dizia: Vem!",np:1},
{v:8,t:"Olhei, e eis um cavalo esverdeado; aquele que o montava chamava-se Morte, e a morada dos mortos o seguia. E foi-lhes dado poder sobre a quarta parte da terra, para matar pela espada, pela fome, pela peste e pelas feras da terra.",n:"Esverdeado: a cor de um cadáver. Morada dos mortos: em grego, Hades, aqui personificado ao lado da Morte, como em 1,18, onde foi traduzido por abismo, e em 20,13–14. Peste: à letra, morte, nome que a tradução grega dá muitas vezes à peste (compare Ezequiel 14,21)."},
{s:"O quinto selo: os mártires"},
{v:9,t:"Quando ele abriu o quinto selo, vi debaixo do altar as almas dos que tinham sido imolados por causa da palavra de Deus e do testemunho que tinham dado."},
{v:10,t:"Eles clamaram em alta voz: Até quando, Senhor santo e verdadeiro, deixarás de julgar e de vingar o nosso sangue nos habitantes da terra?",n:"O clamor pede justiça, como o sangue de Abel (Gênesis 4,10) e muitos salmos; e a resposta de Deus é pedir paciência (compare Lucas 18,7–8)."},
{v:11,t:"Foi dada a cada um deles uma veste branca, e foi-lhes dito que repousassem ainda um pouco de tempo, até que se completasse o número dos seus companheiros de serviço e dos seus irmãos, que iam ser mortos como eles.",np:1},
{s:"O sexto selo: o grande dia da ira"},
{v:12,t:"Quando ele abriu o sexto selo, olhei, e houve um grande terremoto; o sol ficou negro como um saco de crina, e a lua inteira ficou como sangue,",n:"Imagens tradicionais do dia do Senhor: compare Joel 3,4; Isaías 13,10; 34,4; Mateus 24,29."},
{v:13,t:"e as estrelas do céu caíram sobre a terra, como a figueira deixa cair os seus figos verdes quando sacudida por um vento forte,"},
{v:14,t:"e o céu se retirou como um livro que se enrola, e todos os montes e as ilhas foram removidos dos seus lugares."},
{v:15,t:"Os reis da terra, os grandes, os chefes militares, os ricos, os poderosos, e todos, escravos e livres, esconderam-se nas cavernas e entre os rochedos dos montes;"},
{v:16,t:"e diziam aos montes e aos rochedos: Caí sobre nós e escondei-nos da face daquele que está sentado no trono e da ira do Cordeiro,",n:"Compare Oseias 10,8 e Lucas 23,30."},
{v:17,t:"porque chegou o grande dia da ira deles, e quem poderá ficar de pé?"}
];

window.TEXTOS_SEED["apocalipse"][7] = [
{s:"Os servos de Deus marcados com o selo"},
{v:1,t:"Depois disso, vi quatro anjos de pé nos quatro cantos da terra, segurando os quatro ventos da terra, para que nenhum vento soprasse sobre a terra, nem sobre o mar, nem sobre árvore alguma."},
{v:2,t:"Vi também outro anjo que subia do lado do nascente e trazia o selo do Deus vivo; e ele gritou em alta voz aos quatro anjos que tinham recebido o poder de danificar a terra e o mar,"},
{v:3,t:"dizendo: Não danifiqueis a terra, nem o mar, nem as árvores, até que tenhamos marcado com o selo a fronte dos servos do nosso Deus.",n:"Compare Ezequiel 9,4–6, onde os fiéis de Jerusalém recebem um sinal na fronte antes do castigo."},
{v:4,t:"E ouvi o número dos que foram marcados com o selo: cento e quarenta e quatro mil, de todas as tribos dos filhos de Israel:",np:1,n:"Doze vezes doze mil: número simbólico do povo de Deus completo, o novo Israel. Na lista falta Dã, talvez por causa da sua idolatria (Juízes 18), e Judá, a tribo do Messias, vem em primeiro lugar."},
{v:5,t:"da tribo de Judá, doze mil marcados; da tribo de Rúben, doze mil; da tribo de Gad, doze mil;"},
{v:6,t:"da tribo de Aser, doze mil; da tribo de Neftali, doze mil; da tribo de Manassés, doze mil;"},
{v:7,t:"da tribo de Simeão, doze mil; da tribo de Levi, doze mil; da tribo de Issacar, doze mil;"},
{v:8,t:"da tribo de Zabulon, doze mil; da tribo de José, doze mil; da tribo de Benjamim, doze mil marcados."},
{s:"A multidão diante do trono"},
{v:9,t:"Depois disso, olhei, e eis uma grande multidão, que ninguém podia contar, de todas as nações, tribos, povos e línguas, de pé diante do trono e diante do Cordeiro, vestidos de vestes brancas e com palmas nas mãos;"},
{v:10,t:"e clamam em alta voz: A salvação pertence ao nosso Deus, que está sentado no trono, e ao Cordeiro."},
{v:11,t:"Todos os anjos estavam de pé ao redor do trono, dos anciãos e dos quatro seres vivos; e prostraram-se diante do trono com o rosto em terra e adoraram a Deus,",np:1},
{v:12,l:["dizendo:","Amém!","O louvor, a glória, a sabedoria,","a ação de graças, a honra, o poder e a força","ao nosso Deus pelos séculos dos séculos.","Amém."]},
{v:13,t:"Um dos anciãos tomou a palavra e me perguntou: Estes que estão vestidos de vestes brancas, quem são e de onde vieram?",np:1},
{v:14,t:"Eu lhe respondi: Meu senhor, tu o sabes. E ele me disse: Estes são os que vêm da grande tribulação; lavaram as suas vestes e as alvejaram no sangue do Cordeiro.",n:"Paradoxo proposital: as vestes ficam brancas no sangue. É a força da morte de Cristo, de que os fiéis participam pelo batismo e pelo martírio."},
{v:15,t:"Por isso estão diante do trono de Deus e o servem dia e noite no seu templo; e aquele que está sentado no trono estenderá sobre eles a sua tenda.",n:"Estenderá a sua tenda: o verbo lembra a tenda do encontro e a nuvem da glória no deserto (Êxodo 40,34; compare João 1,14)."},
{v:16,t:"Nunca mais terão fome, nem sede; nem os atingirá o sol, nem calor algum,",n:"Compare Isaías 49,10."},
{v:17,t:"porque o Cordeiro, que está no meio do trono, será o seu pastor e os conduzirá às fontes das águas da vida; e Deus enxugará toda lágrima dos seus olhos.",n:"Compare Isaías 25,8; a promessa volta em 21,4."}
];

window.TEXTOS_SEED["apocalipse"][8] = [
{s:"O sétimo selo e as orações dos santos"},
{v:1,t:"Quando o Cordeiro abriu o sétimo selo, fez-se silêncio no céu, cerca de meia hora.",n:"O silêncio antes da ação de Deus (compare Sofonias 1,7; Zacarias 2,17)."},
{v:2,t:"E vi os sete anjos que estão de pé diante de Deus, e foram-lhes dadas sete trombetas."},
{v:3,t:"Veio outro anjo, que se pôs de pé junto ao altar, com um turíbulo de ouro; e foi-lhe dado muito incenso, para que o oferecesse, com as orações de todos os santos, sobre o altar de ouro que está diante do trono."},
{v:4,t:"E da mão do anjo subiu diante de Deus a fumaça do incenso, com as orações dos santos."},
{v:5,t:"Depois o anjo tomou o turíbulo, encheu-o com o fogo do altar e o lançou sobre a terra; e houve trovões, vozes, relâmpagos e um terremoto.",n:"As orações dos fiéis sobem a Deus e voltam à terra como fogo: é em resposta a elas que começam os juízos das trombetas."},
{s:"As quatro primeiras trombetas"},
{v:6,t:"Os sete anjos que tinham as sete trombetas prepararam-se para tocá-las."},
{v:7,t:"O primeiro tocou a trombeta, e houve granizo e fogo misturados com sangue, que foram lançados sobre a terra; e a terça parte da terra foi queimada, a terça parte das árvores foi queimada, e toda a erva verde foi queimada.",np:1,n:"As pragas das trombetas lembram as do Egito (Êxodo 7–10): o granizo, a água transformada em sangue, as trevas, os gafanhotos. Atingem só a terça parte: são ainda avisos, que chamam à conversão (9,20–21)."},
{v:8,t:"O segundo anjo tocou a trombeta, e uma espécie de grande montanha ardendo em fogo foi lançada ao mar; e a terça parte do mar se tornou sangue,",np:1},
{v:9,t:"morreu a terça parte das criaturas que vivem no mar, e a terça parte dos navios foi destruída."},
{v:10,t:"O terceiro anjo tocou a trombeta, e caiu do céu uma grande estrela, ardendo como uma tocha; e caiu sobre a terça parte dos rios e sobre as fontes das águas.",np:1},
{v:11,t:"O nome da estrela é Absinto. A terça parte das águas se converteu em absinto, e muitos homens morreram por causa das águas, porque se tinham tornado amargas.",n:"O absinto é uma planta muito amarga, imagem do castigo nos profetas (Jeremias 9,14; 23,15)."},
{v:12,t:"O quarto anjo tocou a trombeta, e foi ferida a terça parte do sol, a terça parte da lua e a terça parte das estrelas, de modo que a terça parte deles se obscureceu, e o dia perdeu a terça parte da sua luz, e a noite também.",np:1},
{v:13,t:"Olhei e ouvi uma águia que voava no meio do céu e dizia em alta voz: Ai, ai, ai dos habitantes da terra, por causa dos outros toques de trombeta dos três anjos que ainda vão tocar!",np:1}
];

window.TEXTOS_SEED["apocalipse"][9] = [
{s:"A quinta trombeta: os gafanhotos do abismo"},
{v:1,t:"O quinto anjo tocou a trombeta, e vi uma estrela que tinha caído do céu sobre a terra; e foi-lhe dada a chave do poço do abismo.",n:"A estrela caída é um anjo (compare 1,20 e 20,1). O abismo é a prisão dos poderes do mal (Lucas 8,31; 2 Pedro 2,4)."},
{v:2,t:"Ela abriu o poço do abismo, e subiu do poço uma fumaça, como a fumaça de uma grande fornalha; e o sol e o ar escureceram por causa da fumaça do poço."},
{v:3,t:"Da fumaça saíram gafanhotos sobre a terra, e foi-lhes dado um poder semelhante ao que têm os escorpiões da terra.",n:"Compare a praga do Egito (Êxodo 10,12–15) e os gafanhotos de Joel 1–2, descritos como um exército."},
{v:4,t:"Foi-lhes ordenado que não danificassem a erva da terra, nem verdura alguma, nem árvore alguma, mas apenas os homens que não têm o selo de Deus na fronte."},
{v:5,t:"Foi-lhes permitido, não matá-los, mas atormentá-los durante cinco meses; e o tormento que causam é como o do escorpião quando pica um homem.",n:"Cinco meses: o tempo de vida de um gafanhoto. É um castigo com prazo marcado."},
{v:6,t:"Naqueles dias, os homens procurarão a morte e não a acharão; desejarão morrer, e a morte fugirá deles."},
{v:7,t:"Os gafanhotos pareciam cavalos preparados para a batalha; na cabeça tinham como que coroas semelhantes ao ouro, e o seu rosto era como rosto de homem;",np:1,n:"Compare Joel 2,4–5."},
{v:8,t:"tinham cabelos como cabelos de mulher, e os seus dentes eram como os dos leões;"},
{v:9,t:"tinham couraças como couraças de ferro, e o ruído das suas asas era como o ruído de carros de muitos cavalos que correm para a batalha."},
{v:10,t:"Têm caudas semelhantes às dos escorpiões, com ferrões, e nas caudas está o seu poder de danificar os homens durante cinco meses."},
{v:11,t:"Têm como rei o anjo do abismo, cujo nome em hebraico é Abadon, e em grego, Apolion.",n:"Abadon quer dizer em hebraico a Perdição, e designa no Antigo Testamento o lugar dos mortos (Jó 26,6); Apolion quer dizer em grego o Destruidor."},
{v:12,t:"O primeiro ai passou. Eis que depois disso vêm ainda dois ais.",np:1},
{s:"A sexta trombeta: os cavaleiros do Eufrates"},
{v:13,t:"O sexto anjo tocou a trombeta, e ouvi uma voz que vinha dos chifres do altar de ouro que está diante de Deus,",n:"Dos chifres: assim a Nova Vulgata; muitos manuscritos gregos dizem: dos quatro chifres."},
{v:14,t:"e que dizia ao sexto anjo, que tinha a trombeta: Solta os quatro anjos que estão acorrentados junto ao grande rio Eufrates.",n:"O Eufrates era a fronteira do Império Romano com os partos, os temíveis cavaleiros do Oriente."},
{v:15,t:"Foram soltos os quatro anjos, que estavam preparados para a hora, o dia, o mês e o ano, a fim de matarem a terça parte dos homens.",np:1},
{v:16,t:"O número dos soldados da cavalaria era de duzentos milhões; eu ouvi o seu número."},
{v:17,t:"Foi assim que vi na visão os cavalos e os que os montavam: tinham couraças cor de fogo, de jacinto e de enxofre; as cabeças dos cavalos eram como cabeças de leões, e da sua boca saíam fogo, fumaça e enxofre."},
{v:18,t:"Por estas três pragas foi morta a terça parte dos homens: pelo fogo, pela fumaça e pelo enxofre que saíam da sua boca."},
{v:19,t:"Pois o poder dos cavalos está na sua boca e nas suas caudas; as suas caudas, semelhantes a serpentes, têm cabeças, e é com elas que causam dano."},
{v:20,t:"Os outros homens, os que não foram mortos por estas pragas, não se converteram das obras das suas mãos: não deixaram de adorar os demônios e os ídolos de ouro, de prata, de bronze, de pedra e de madeira, que não podem ver, nem ouvir, nem andar;",np:1,n:"Compare Salmo 115,4–7 e Daniel 5,23."},
{v:21,t:"nem se converteram dos seus homicídios, nem das suas feitiçarias, nem da sua prostituição, nem dos seus roubos."}
];

window.TEXTOS_SEED["apocalipse"][10] = [
{s:"O anjo e o livrinho"},
{v:1,t:"Vi outro anjo poderoso, que descia do céu envolto numa nuvem; tinha sobre a cabeça o arco-íris, o seu rosto era como o sol, e os seus pés, como colunas de fogo;"},
{v:2,t:"tinha na mão um livrinho aberto. Pôs o pé direito sobre o mar e o esquerdo sobre a terra,"},
{v:3,t:"e gritou em alta voz, como ruge o leão. Quando gritou, os sete trovões fizeram ouvir as suas vozes."},
{v:4,t:"Quando os sete trovões falaram, eu ia escrever; mas ouvi uma voz do céu, que dizia: Guarda sob selo o que os sete trovões disseram e não o escrevas.",n:"Nem tudo é revelado: compare Daniel 12,4.9 e 2 Coríntios 12,4."},
{v:5,t:"Então o anjo que eu tinha visto de pé sobre o mar e sobre a terra levantou a mão direita para o céu",np:1},
{v:6,t:"e jurou por aquele que vive pelos séculos dos séculos, que criou o céu e o que nele existe, a terra e o que nela existe, o mar e o que nele existe: Não haverá mais demora;",n:"Compare Daniel 12,7. Não haverá mais demora: à letra, não haverá mais tempo."},
{v:7,t:"mas nos dias em que se ouvir a voz do sétimo anjo, quando ele tocar a trombeta, se consumará o mistério de Deus, como ele anunciou aos seus servos, os profetas."},
{s:"João come o livrinho"},
{v:8,t:"A voz que eu tinha ouvido do céu falou-me de novo e disse: Vai, toma o livro aberto da mão do anjo que está de pé sobre o mar e sobre a terra."},
{v:9,t:"Fui ao anjo e pedi-lhe que me desse o livrinho. Ele me disse: Toma-o e come-o; ele te amargará o estômago, mas na tua boca será doce como o mel.",n:"Compare Ezequiel 2,8–3,3. A palavra de Deus é doce quando é recebida e amarga pelo que anuncia."},
{v:10,t:"Tomei o livrinho da mão do anjo e o comi; na minha boca era doce como o mel, mas, depois de o comer, o meu estômago ficou amargo."},
{v:11,t:"E disseram-me: É preciso que profetizes de novo sobre muitos povos, nações, línguas e reis."}
];

window.TEXTOS_SEED["apocalipse"][11] = [
{s:"As duas testemunhas"},
{v:1,t:"Foi-me dada uma cana semelhante a uma vara, e foi-me dito: Levanta-te e mede o templo de Deus, o altar e os que nele adoram.",n:"Medir é pôr sob proteção (compare Ezequiel 40–42; Zacarias 2,5–9): o santuário, isto é, a comunidade dos fiéis, será preservado."},
{v:2,t:"Mas o átrio que fica fora do templo, deixa-o de lado e não o meças, porque foi entregue às nações, e elas pisarão a cidade santa durante quarenta e dois meses.",n:"Quarenta e dois meses, ou mil duzentos e sessenta dias (11,3; 12,6), ou um tempo, dois tempos e metade de um tempo (12,14): são três anos e meio, a metade de sete, o tempo limitado da perseguição (Daniel 7,25; 12,7)."},
{v:3,t:"E farei que as minhas duas testemunhas profetizem, vestidas de saco, durante mil duzentos e sessenta dias."},
{v:4,t:"Elas são as duas oliveiras e os dois candelabros que estão de pé diante do Senhor da terra.",n:"Compare Zacarias 4,3.11–14. As duas testemunhas têm os traços de Moisés e de Elias (11,6); representam o testemunho profético da Igreja."},
{v:5,t:"Se alguém quiser fazer-lhes mal, sai fogo da sua boca e devora os seus inimigos; e, se alguém quiser fazer-lhes mal, é assim que deve morrer.",np:1},
{v:6,t:"Elas têm o poder de fechar o céu, para que não chova durante os dias da sua profecia; e têm poder sobre as águas, para convertê-las em sangue, e para ferir a terra com toda sorte de pragas, todas as vezes que quiserem.",n:"Como Elias, que fechou o céu (1 Reis 17,1), e Moisés, que converteu a água em sangue (Êxodo 7,17–20)."},
{v:7,t:"Quando tiverem terminado o seu testemunho, a fera que sobe do abismo lhes fará guerra, as vencerá e as matará."},
{v:8,t:"Os seus corpos ficarão na praça da grande cidade, que se chama, em sentido espiritual, Sodoma e Egito, onde também o Senhor delas foi crucificado.",n:"A grande cidade é aqui Jerusalém, onde o Senhor foi crucificado, chamada Sodoma e Egito pela sua infidelidade (compare Isaías 1,10). No resto do livro, a grande cidade é Babilônia."},
{v:9,t:"Homens de povos, tribos, línguas e nações contemplam os seus corpos durante três dias e meio e não permitem que sejam sepultados."},
{v:10,t:"Os habitantes da terra se alegram por causa delas e fazem festa, e mandarão presentes uns aos outros, porque esses dois profetas tinham atormentado os habitantes da terra."},
{v:11,t:"Mas, depois dos três dias e meio, um sopro de vida, vindo de Deus, entrou nelas, e elas se puseram de pé; e um grande temor caiu sobre os que as viam.",np:1,n:"Compare Ezequiel 37,5.10."},
{v:12,t:"E ouviram uma voz forte do céu, que lhes dizia: Subi até aqui. E subiram ao céu na nuvem, à vista dos seus inimigos."},
{v:13,t:"Naquela hora houve um grande terremoto; a décima parte da cidade desabou, e morreram no terremoto sete mil pessoas; os demais ficaram cheios de temor e deram glória ao Deus do céu."},
{v:14,t:"O segundo ai passou; eis que o terceiro ai vem em breve.",np:1},
{s:"A sétima trombeta"},
{v:15,t:"O sétimo anjo tocou a trombeta, e houve no céu vozes fortes, que diziam: O reino do mundo passou a ser do nosso Senhor e do seu Cristo, e ele reinará pelos séculos dos séculos."},
{v:16,t:"E os vinte e quatro anciãos, que estão sentados nos seus tronos diante de Deus, prostraram-se com o rosto em terra e adoraram a Deus,",np:1},
{v:17,l:["dizendo:","Nós te damos graças,","Senhor Deus, Todo-Poderoso,","que és e que eras,","porque assumiste o teu grande poder e começaste a reinar."],n:"Já não se diz: e que vem (compare 1,8 e 4,8); ele já veio para reinar."},
{v:18,l:["As nações se enfureceram,","mas chegou a tua ira","e o tempo de julgar os mortos,","de dar a recompensa aos teus servos, os profetas, e aos santos,","e aos que temem o teu nome, pequenos e grandes,","e de destruir os que destroem a terra."],n:"Compare Salmo 2,1."},
{v:19,t:"Então se abriu o templo de Deus que está no céu, e apareceu no seu templo a arca da sua aliança; e houve relâmpagos, vozes, um terremoto e uma grande chuva de granizo.",np:1,n:"A arca, desaparecida desde a destruição do templo de Salomão (compare 2 Macabeus 2,4–8), aparece no céu: Deus não esqueceu a sua aliança. Vozes, terremoto: a Nova Vulgata não traz aqui os trovões, que muitos manuscritos gregos acrescentam."}
];
