// =====================================================================
// Baruc — tradução do grego, cotejada com a Nova Vulgata (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["baruc"][1] = [
{s:"O livro lido na Babilônia"},
{v:1,t:"Estas são as palavras do livro que Baruc, filho de Nerias, filho de Maasias, filho de Sedecias, filho de Asadias, filho de Helcias, escreveu na Babilônia,",n:"Baruc: o secretário de Jeremias (Jeremias 32,12; 36,4; 45,1). O livro chegou até nós em grego; a Vulgata o põe entre os profetas, depois de Lamentações, e junta a ele, como capítulo 6, a Carta de Jeremias."},
{v:2,t:"no quinto ano, no dia sete do mês, no tempo em que os caldeus tomaram Jerusalém e a incendiaram.",n:"O quinto ano: provavelmente depois da tomada de Jerusalém, isto é, 582 antes de Cristo; o mês não é indicado."},
{v:3,t:"Baruc leu as palavras deste livro aos ouvidos de Jeconias, filho de Joaquim, rei de Judá, e aos ouvidos de todo o povo que vinha ouvir a leitura do livro,"},
{v:4,t:"aos ouvidos dos poderosos e dos filhos dos reis, aos ouvidos dos anciãos e aos ouvidos de todo o povo, do menor ao maior, de todos os que moravam na Babilônia, junto ao rio Sud.",n:"Sud: rio ou canal da Babilônia, hoje desconhecido."},
{v:5,t:"Eles choravam, jejuavam e rezavam diante do Senhor."},
{v:6,t:"Fizeram uma coleta de dinheiro, cada um segundo as suas posses,"},
{v:7,t:"e a mandaram a Jerusalém, ao sacerdote Joaquim, filho de Helcias, filho de Salom, aos sacerdotes e a todo o povo que se encontrava com ele em Jerusalém,"},
{v:8,t:"quando ele recebeu os utensílios da casa do Senhor, que tinham sido levados do templo, para devolvê-los à terra de Judá, no dia dez do mês de Sivã: eram os utensílios de prata que Sedecias, filho de Josias, rei de Judá, tinha mandado fazer,"},
{v:9,t:"depois que Nabucodonosor, rei da Babilônia, deportou de Jerusalém Jeconias, os chefes, os ferreiros, os poderosos e o povo da terra, e os levou para a Babilônia."},
{v:10,t:"Mandaram dizer: Eis que vos enviamos dinheiro; comprai com ele holocaustos, sacrifícios pelo pecado e incenso, preparai oferendas e oferecei-as sobre o altar do Senhor, nosso Deus;"},
{v:11,t:"e rezai pela vida de Nabucodonosor, rei da Babilônia, e pela vida de Baltasar, seu filho, para que os seus dias sejam como os dias do céu sobre a terra.",n:"Baltasar era, na verdade, filho de Nabonido; o autor segue uma tradição também presente em Daniel 5,2. Compare a carta de Jeremias aos exilados (Jeremias 29,7)."},
{v:12,t:"O Senhor nos dará força e iluminará os nossos olhos, e viveremos à sombra de Nabucodonosor, rei da Babilônia, e à sombra de Baltasar, seu filho; nós os serviremos por muitos dias e encontraremos graça diante deles."},
{v:13,t:"Rezai também por nós ao Senhor, nosso Deus, porque pecamos contra o Senhor, nosso Deus, e até hoje não se afastaram de nós o furor e a ira do Senhor."},
{v:14,t:"Lede este livro que vos enviamos, para ser lido publicamente na casa do Senhor, no dia da festa e nos dias de reunião."},
{s:"Confissão dos pecados"},
{v:15,t:"E direis: Ao Senhor, nosso Deus, a justiça; a nós, a vergonha no rosto, como acontece hoje aos homens de Judá e aos habitantes de Jerusalém,",n:"A oração de 1,15–3,8 tem muitos paralelos com a de Daniel 9,4–19."},
{v:16,t:"aos nossos reis, aos nossos chefes, aos nossos sacerdotes, aos nossos profetas e aos nossos pais;"},
{v:17,t:"porque pecamos diante do Senhor e lhe fomos desobedientes;"},
{v:18,t:"não escutamos a voz do Senhor, nosso Deus, para andar nos mandamentos que o Senhor pôs diante de nós."},
{v:19,t:"Desde o dia em que o Senhor tirou os nossos pais da terra do Egito até hoje, temos sido rebeldes ao Senhor, nosso Deus, e nos apressamos em não escutar a sua voz."},
{v:20,t:"Por isso se apegaram a nós as desgraças e a maldição que o Senhor anunciou por meio de Moisés, seu servo, no dia em que tirou os nossos pais da terra do Egito para nos dar uma terra onde corre leite e mel, como se vê hoje."},
{v:21,t:"Não escutamos a voz do Senhor, nosso Deus, segundo todas as palavras dos profetas que ele nos enviou,"},
{v:22,t:"mas cada um de nós seguiu a inclinação do seu coração perverso, servindo a outros deuses e fazendo o mal aos olhos do Senhor, nosso Deus."}
];

window.TEXTOS_SEED["baruc"][2] = [
{s:"O castigo anunciado se cumpriu"},
{v:1,t:"Por isso o Senhor cumpriu a palavra que tinha pronunciado contra nós, contra os nossos juízes que governavam Israel, contra os nossos reis, contra os nossos chefes e contra todo homem de Israel e de Judá,"},
{v:2,t:"fazendo vir sobre nós desgraças tão grandes como nunca aconteceram debaixo do céu, como as que aconteceram em Jerusalém, conforme o que está escrito na Lei de Moisés:"},
{v:3,t:"que chegaríamos a comer cada um a carne do próprio filho e cada um a carne da própria filha.",n:"Nota do tradutor: compare Deuteronômio 28,53 e Lamentações 2,20; 4,10; o texto não foi suavizado."},
{v:4,t:"Ele os entregou em sujeição a todos os reinos que nos rodeiam, para serem objeto de insulto e de desolação entre todos os povos vizinhos, entre os quais o Senhor os dispersou."},
{v:5,t:"Ficaram por baixo, e não por cima, porque pecamos contra o Senhor, nosso Deus, não escutando a sua voz."},
{v:6,t:"Ao Senhor, nosso Deus, a justiça; a nós e aos nossos pais, a vergonha no rosto, como acontece hoje."},
{v:7,t:"Todas estas desgraças que o Senhor anunciou contra nós caíram sobre nós;"},
{v:8,t:"e não suplicamos diante do Senhor, para que cada um se afastasse dos pensamentos do seu coração perverso."},
{v:9,t:"O Senhor vigiou sobre essas desgraças e as fez vir sobre nós, pois o Senhor é justo em todas as obras que nos ordenou."},
{v:10,t:"Mas não escutamos a sua voz, para andar nos mandamentos do Senhor, que ele pôs diante de nós."},
{s:"Súplica ao Senhor"},
{v:11,t:"E agora, Senhor, Deus de Israel, que tiraste o teu povo da terra do Egito com mão forte, com sinais e prodígios, com grande poder e braço erguido, e adquiriste para ti um nome, como se vê hoje,"},
{v:12,t:"pecamos, fomos ímpios, agimos injustamente, Senhor, nosso Deus, contra todos os teus mandamentos."},
{v:13,t:"Que a tua ira se afaste de nós, pois ficamos poucos entre as nações para onde nos dispersaste."},
{v:14,t:"Escuta, Senhor, a nossa oração e a nossa súplica, livra-nos por causa de ti mesmo e faze-nos encontrar graça diante daqueles que nos deportaram,",np:1},
{v:15,t:"para que toda a terra saiba que tu és o Senhor, nosso Deus, e que o teu nome é invocado sobre Israel e sobre a sua descendência."},
{v:16,t:"Senhor, olha da tua santa morada e pensa em nós; inclina, Senhor, o teu ouvido e escuta."},
{v:17,t:"Abre, Senhor, os teus olhos e vê: não são os mortos que estão na morada dos mortos, cujo espírito foi tirado das suas entranhas, que darão glória e justiça ao Senhor;",n:"Compare Salmo 6,6; 115,17; Isaías 38,18."},
{v:18,t:"mas a alma profundamente triste, que anda curvada e sem forças, os olhos que desfalecem e a alma faminta, estes te darão glória e justiça, Senhor."},
{v:19,t:"Não é por causa dos méritos dos nossos pais e dos nossos reis que apresentamos a nossa súplica diante de ti, Senhor, nosso Deus;",np:1},
{v:20,t:"pois fizeste vir sobre nós o teu furor e a tua ira, como tinhas anunciado por meio dos teus servos, os profetas, dizendo:"},
{v:21,t:"Assim diz o Senhor: Curvai os ombros e servi o rei da Babilônia, e ficareis na terra que dei aos vossos pais.",n:"Compare Jeremias 27,11–12."},
{v:22,t:"Mas, se não escutardes a voz do Senhor, servindo o rei da Babilônia, farei desaparecer das cidades de Judá e das ruas de Jerusalém"},
{v:23,t:"a voz da alegria e a voz do júbilo, a voz do noivo e a voz da noiva, e toda a terra ficará deserta, sem habitantes.",n:"Compare Jeremias 7,34; 33,10–11."},
{v:24,t:"Mas não escutamos a tua voz, servindo o rei da Babilônia; e cumpriste as palavras que tinhas anunciado por meio dos teus servos, os profetas: que os ossos dos nossos reis e os ossos dos nossos pais seriam tirados do seu lugar.",n:"Compare Jeremias 8,1–2."},
{v:25,t:"E eis que foram lançados ao calor do dia e ao frio da noite; e eles morreram em meio a terríveis sofrimentos, pela fome, pela espada e pela peste."},
{v:26,t:"E fizeste da casa sobre a qual é invocado o teu nome o que ela é hoje, por causa da maldade da casa de Israel e da casa de Judá.",np:1},
{v:27,t:"Mas agiste conosco, Senhor, nosso Deus, segundo toda a tua bondade e segundo toda a tua grande misericórdia,"},
{v:28,t:"como tinhas anunciado por meio do teu servo Moisés, no dia em que lhe ordenaste escrever a tua Lei diante dos filhos de Israel,"},
{v:29,t:"dizendo: Se não escutardes a minha voz, esta multidão grande e numerosa se reduzirá a um pequeno número entre as nações para onde eu os dispersarei;"},
{v:30,t:"pois eu sei que não me escutarão, porque é um povo de dura cerviz. Mas na terra do seu exílio cairão em si"},
{v:31,t:"e saberão que eu sou o Senhor, seu Deus. Eu lhes darei um coração que compreende e ouvidos que escutam,"},
{v:32,t:"e eles me louvarão na terra do seu exílio e se lembrarão do meu nome;"},
{v:33,t:"deixarão a sua dura cerviz e as suas más ações, lembrando-se do caminho dos seus pais, que pecaram diante do Senhor."},
{v:34,t:"Eu os farei voltar à terra que prometi com juramento aos seus pais, Abraão, Isaac e Jacó, e eles a possuirão; eu os multiplicarei, e não diminuirão."},
{v:35,t:"Farei com eles uma aliança eterna, para ser o seu Deus, e eles serão o meu povo; e não expulsarei mais o meu povo Israel da terra que lhes dei.",n:"Compare Jeremias 31,31–33; 32,40."}
];

window.TEXTOS_SEED["baruc"][3] = [
{s:"Ouve, Senhor, e tem piedade"},
{v:1,t:"Senhor todo-poderoso, Deus de Israel, uma alma angustiada e um espírito aflito clamam a ti."},
{v:2,t:"Escuta, Senhor, e tem piedade, porque pecamos diante de ti;"},
{v:3,t:"pois tu reinas para sempre, e nós perecemos para sempre."},
{v:4,t:"Senhor todo-poderoso, Deus de Israel, escuta agora a oração dos mortos de Israel e dos filhos daqueles que pecaram diante de ti, que não escutaram a voz do Senhor, seu Deus, e por isso as desgraças se apegaram a nós.",n:"Os mortos de Israel: o povo exilado, como que morto (compare Ezequiel 37,11); talvez o original hebraico dissesse os homens de Israel."},
{v:5,t:"Não te lembres das iniquidades dos nossos pais, mas lembra-te, neste momento, da tua mão e do teu nome,"},
{v:6,t:"pois tu és o Senhor, nosso Deus, e nós te louvaremos, Senhor;"},
{v:7,t:"pois foi para isso que puseste o teu temor no nosso coração, para que invocássemos o teu nome; e te louvaremos no nosso exílio, porque afastamos do nosso coração toda a iniquidade dos nossos pais, que pecaram diante de ti."},
{v:8,t:"Eis-nos hoje no nosso exílio, para onde nos dispersaste, para sermos objeto de insulto, de maldição e de castigo, por todas as iniquidades dos nossos pais, que se afastaram do Senhor, nosso Deus."},
{s:"Elogio da sabedoria"},
{v:9,l:["Escuta, Israel, os mandamentos da vida;","prestai ouvidos, para conhecer a prudência."]},
{v:10,l:["Por que, Israel,","por que estás em terra de inimigos?"],np:1},
{v:11,l:["Envelheces numa terra estrangeira,","contaminado com os mortos,","contado entre os que descem à morada dos mortos."],np:1},
{v:12,l:["Abandonaste a fonte da sabedoria!"],np:1},
{v:13,l:["Se tivesses andado no caminho de Deus,","habitarias em paz para sempre."],np:1},
{v:14,l:["Aprende onde está a prudência,","onde está a força, onde está a inteligência,","para saberes também onde estão a longa vida e a vida,","onde está a luz dos olhos e a paz."],np:1},
{v:15,l:["Quem encontrou o lugar da sabedoria?","Quem entrou nos seus tesouros?"],np:1},
{v:16,l:["Onde estão os chefes das nações","e os que dominam os animais que estão sobre a terra,"],np:1},
{v:17,l:["os que se divertem com as aves do céu,"],np:1},
{v:18,l:["os que acumulam prata e ouro,","em que os homens confiam,","e cujas aquisições não têm fim;","os que trabalham a prata com tanto cuidado,","e cujas obras não se podem investigar?"],np:1},
{v:19,l:["Desapareceram e desceram à morada dos mortos,","e outros se levantaram no seu lugar."],np:1},
{v:20,l:["Jovens viram a luz e habitaram sobre a terra,","mas não conheceram o caminho do saber"],np:1},
{v:21,l:["nem compreenderam as suas veredas;","os seus filhos também não o acolheram,","ficaram longe do seu caminho."],np:1},
{v:22,l:["Não se ouviu falar dela em Canaã,","nem foi vista em Temã."],np:1},
{v:23,l:["Os filhos de Agar, que procuram a sabedoria sobre a terra,","os mercadores de Merra e de Temã,","os contadores de fábulas e os que buscam a prudência","não conheceram o caminho da sabedoria,","nem se lembraram das suas veredas."],np:1,n:"Os filhos de Agar: os árabes. Temã, em Edom, e Merra eram célebres pela sabedoria e pelo comércio."},
{v:24,l:["Ó Israel, como é grande a casa de Deus,","e quão vasto o lugar do seu domínio!"],np:1,n:"A casa de Deus: aqui, o universo."},
{v:25,l:["É grande e não tem fim,","é alto e sem medida."],np:1},
{v:26,l:["Ali nasceram os famosos gigantes dos tempos antigos,","de grande estatura, peritos na guerra."],np:1,n:"Compare Gênesis 6,4."},
{v:27,l:["Não foi a eles que Deus escolheu,","nem lhes deu o caminho do saber;"],np:1},
{v:28,l:["e pereceram, porque não tinham prudência,","pereceram por causa da sua insensatez."],np:1},
{s:"O dom da sabedoria a Israel"},
{v:29,l:["Quem subiu ao céu para buscá-la","e a fez descer das nuvens?"],n:"Compare Deuteronômio 30,12–13, que o apóstolo Paulo aplica a Cristo (Romanos 10,6–8)."},
{v:30,l:["Quem atravessou o mar e a encontrou,","e a trará a preço de ouro puro?"],np:1},
{v:31,l:["Não há quem conheça o seu caminho,","nem quem compreenda a sua vereda."],np:1},
{v:32,l:["Mas aquele que tudo sabe a conhece,","ele a descobriu com a sua inteligência;","ele, que firmou a terra para sempre","e a encheu de animais quadrúpedes;"],np:1},
{v:33,l:["ele envia a luz, e ela parte;","chama-a, e ela lhe obedece tremendo."],np:1},
{v:34,l:["As estrelas brilham nos seus postos de vigia","e se alegram."],np:1},
{v:35,l:["Ele as chama, e elas respondem: Aqui estamos!","E brilham com alegria para aquele que as criou."],np:1},
{v:36,l:["Este é o nosso Deus;","nenhum outro se compara a ele."],np:1},
{v:37,l:["Ele descobriu todo o caminho do saber","e o deu a Jacó, seu servo,","e a Israel, seu amado."],np:1},
{v:38,l:["Depois disso ela apareceu sobre a terra","e conviveu com os homens."],np:1,n:"Os Padres da Igreja leram neste versículo um anúncio da encarnação da Sabedoria de Deus (compare João 1,14); no contexto, a sabedoria se faz presente entre os homens na Lei dada a Israel (4,1)."}
];

window.TEXTOS_SEED["baruc"][4] = [
{s:"A sabedoria é a Lei de Deus"},
{v:1,l:["Ela é o livro dos mandamentos de Deus","e a Lei que permanece para sempre.","Todos os que a guardam viverão,","mas os que a abandonam morrerão."],n:"Compare Eclesiástico 24,23."},
{v:2,l:["Volta, Jacó, e abraça-a;","caminha para o esplendor, à sua luz."],np:1},
{v:3,l:["Não dês a outro a tua glória,","nem os teus privilégios a uma nação estrangeira."],np:1},
{v:4,l:["Felizes somos nós, Israel,","porque conhecemos o que agrada a Deus!"],np:1},
{s:"Coragem, meu povo"},
{v:5,l:["Coragem, meu povo,","memória de Israel!"]},
{v:6,l:["Fostes vendidos às nações,","não para a destruição;","mas, porque provocastes a ira de Deus,","fostes entregues aos inimigos."],np:1},
{v:7,l:["Irritastes aquele que vos fez,","oferecendo sacrifícios aos demônios, e não a Deus."],np:1,n:"Compare Deuteronômio 32,17."},
{v:8,l:["Esquecestes o Deus eterno, que vos alimentou,","e entristecestes Jerusalém, que vos criou."],np:1},
{v:9,l:["Pois ela viu a ira que vinha de Deus sobre vós","e disse: Escutai, vizinhas de Sião:","Deus me mandou um grande luto."],np:1,n:"Jerusalém, como mãe, fala às cidades vizinhas e depois aos seus filhos (vv. 9–29)."},
{v:10,l:["Vi o cativeiro dos meus filhos e das minhas filhas,","que o Eterno fez vir sobre eles."],np:1},
{v:11,l:["Eu os criei com alegria,","mas os deixei partir com lágrimas e luto."],np:1},
{v:12,l:["Que ninguém se alegre por mim, viúva e abandonada por muitos;","fiquei desolada por causa dos pecados dos meus filhos,","porque se afastaram da Lei de Deus."],np:1},
{v:13,l:["Não conheceram os seus preceitos,","não andaram nos caminhos dos mandamentos de Deus,","nem seguiram as veredas da disciplina, na sua justiça."],np:1},
{v:14,l:["Venham as vizinhas de Sião;","lembrai-vos do cativeiro dos meus filhos e das minhas filhas,","que o Eterno fez vir sobre eles."],np:1},
{v:15,l:["Ele fez vir contra eles uma nação distante,","uma nação insolente, de língua estranha,","que não respeitou o velho","nem teve piedade da criança."],np:1},
{v:16,l:["Levaram os filhos queridos da viúva","e deixaram sozinha a que estava privada das filhas."],np:1},
{v:17,l:["E eu, como poderei ajudar-vos?"],np:1},
{v:18,l:["Aquele que fez vir sobre vós essas desgraças","vos livrará das mãos dos vossos inimigos."],np:1},
{v:19,l:["Ide, filhos, ide;","pois eu fiquei sozinha."],np:1},
{v:20,l:["Tirei a veste da paz","e vesti o pano de saco da súplica;","clamarei ao Eterno enquanto viver."],np:1},
{v:21,l:["Coragem, filhos, clamai a Deus,","e ele vos livrará da opressão, das mãos dos inimigos."],np:1},
{v:22,l:["Pois eu espero do Eterno a vossa salvação,","e do Santo me veio a alegria","pela misericórdia que em breve vos virá","do Eterno, vosso salvador."],np:1},
{v:23,l:["Eu vos deixei partir com luto e lágrimas,","mas Deus vos devolverá a mim","com alegria e júbilo para sempre."],np:1},
{v:24,l:["Pois, assim como as vizinhas de Sião viram agora o vosso cativeiro,","assim verão em breve a vossa salvação, que vem de Deus","e que virá sobre vós com a grande glória e o esplendor do Eterno."],np:1},
{v:25,l:["Filhos, suportai com paciência a ira que vos veio de Deus;","o teu inimigo te perseguiu,","mas em breve verás a sua ruína","e porás o pé sobre o seu pescoço."],np:1},
{v:26,l:["Os meus filhos delicados andaram por caminhos ásperos,","foram levados como um rebanho roubado pelos inimigos."],np:1},
{v:27,l:["Coragem, filhos, clamai a Deus,","pois aquele que vos castigou se lembrará de vós."],np:1},
{v:28,l:["Assim como o vosso pensamento foi de vos afastar de Deus,","convertidos, buscai-o com dez vezes mais ardor;"],np:1},
{v:29,l:["pois aquele que fez vir sobre vós essas desgraças","vos trará a alegria eterna com a vossa salvação."],np:1},
{s:"Consolação para Jerusalém"},
{v:30,l:["Coragem, Jerusalém!","Aquele que te deu o nome te consolará."]},
{v:31,l:["Infelizes os que te maltrataram","e se alegraram com a tua queda!"],np:1},
{v:32,l:["Infelizes as cidades a que os teus filhos serviram como escravos;","infeliz a que recebeu os teus filhos!"],np:1},
{v:33,l:["Pois, assim como se alegrou com a tua ruína","e se regozijou com a tua queda,","assim se entristecerá com a sua própria desolação."],np:1},
{v:34,l:["Tirarei dela a alegria da sua multidão,","e o seu orgulho se transformará em luto."],np:1},
{v:35,l:["Pois um fogo virá sobre ela da parte do Eterno","por longos dias,","e será habitada por demônios por muito tempo."],np:1,n:"Compare Isaías 13,19–22; 34,14."},
{v:36,l:["Olha para o oriente, Jerusalém,","e vê a alegria que te vem de Deus."],np:1},
{v:37,l:["Eis que voltam os teus filhos, que viste partir;","voltam reunidos do oriente ao ocidente","pela palavra do Santo, alegrando-se na glória de Deus."],np:1}
];

window.TEXTOS_SEED["baruc"][5] = [
{s:"Jerusalém revestida de glória"},
{v:1,l:["Tira, Jerusalém, a veste do teu luto e da tua aflição","e reveste-te para sempre do esplendor","da glória que vem de Deus."]},
{v:2,l:["Cobre-te com o manto da justiça que vem de Deus,","põe na cabeça o diadema da glória do Eterno."],np:1},
{v:3,l:["Pois Deus mostrará o teu esplendor","a toda a terra que há debaixo do céu."],np:1},
{v:4,l:["Deus te dará para sempre este nome:","Paz da justiça e Glória da piedade."],np:1},
{v:5,l:["Levanta-te, Jerusalém, põe-te no alto,","olha para o oriente e vê os teus filhos reunidos","desde o nascer ao pôr do sol,","pela palavra do Santo, alegres porque Deus se lembrou deles."],np:1},
{v:6,l:["Saíram de ti a pé, levados pelos inimigos;","mas Deus os traz de volta a ti,","carregados com honra, como num trono real."],np:1},
{v:7,l:["Pois Deus ordenou que se abaixem","todo monte elevado e as colinas eternas,","e que se encham os vales até nivelar a terra,","para que Israel caminhe seguro, sob a glória de Deus."],np:1,n:"Compare Isaías 40,3–5."},
{v:8,l:["Os bosques e todas as árvores perfumadas","darão sombra a Israel por ordem de Deus."],np:1},
{v:9,l:["Pois Deus conduzirá Israel com alegria,","à luz da sua glória,","com a misericórdia e a justiça","que vêm dele."],np:1}
];

window.TEXTOS_SEED["baruc"][6] = [
{s:"A Carta de Jeremias"},
{v:1,t:"Cópia da carta que Jeremias enviou aos que iam ser levados cativos para a Babilônia pelo rei dos babilônios, para lhes comunicar o que Deus lhe tinha ordenado. Por causa dos pecados que cometestes diante de Deus, sereis levados cativos para a Babilônia por Nabucodonosor, rei dos babilônios.",n:"O título da carta não é numerado na Nova Vulgata; em outras Bíblias ele é o versículo 1, e a numeração avança uma unidade (6,2–73). A carta desenvolve a sátira contra os ídolos de Jeremias 10,1–16."},
{v:2,t:"Chegando à Babilônia, ficareis lá muitos anos, por um longo tempo, até sete gerações; depois disso eu vos farei sair de lá em paz.",n:"Sete gerações: número redondo; compare os setenta anos de Jeremias 25,11; 29,10."},
{v:3,t:"Pois bem, vereis na Babilônia deuses de prata, de ouro e de madeira, carregados aos ombros, que infundem temor às nações."},
{v:4,t:"Tomai cuidado, portanto, para não vos tornardes semelhantes aos estrangeiros e para que o temor desses deuses não se apodere de vós.",np:1},
{v:5,t:"Quando virdes a multidão que se prostra diante deles e atrás deles, dizei no vosso coração: É a ti, Senhor, que se deve adorar."},
{v:6,t:"Pois o meu anjo está convosco, e ele cuida das vossas vidas."},
{v:7,t:"A língua deles foi polida por um artesão; eles mesmos são dourados e prateados, mas são falsos e não podem falar."},
{s:"Ídolos enfeitados e impotentes"},
{v:8,t:"Como para uma moça que gosta de enfeites, tomam ouro e fazem"},
{v:9,t:"coroas para a cabeça dos seus deuses. Às vezes até acontece que os sacerdotes tiram dos deuses ouro e prata e os gastam consigo mesmos,"},
{v:10,t:"e dão parte disso até às prostitutas do prostíbulo. Enfeitam com roupas, como se fossem homens, esses deuses de prata, de ouro e de madeira;"},
{v:11,t:"mas eles não se livram da ferrugem nem da traça."},
{v:12,t:"Depois de vesti-los com um manto de púrpura, limpam o rosto deles, por causa da poeira do templo, que se acumula muito sobre eles.",np:1},
{v:13,t:"Um tem cetro como um homem, como o juiz de uma região, mas não pode fazer morrer quem o ofende."},
{v:14,t:"Outro tem na mão direita uma espada e um machado, mas não se livrará da guerra nem dos ladrões. Por aí se vê que não são deuses;"},
{v:15,t:"portanto, não os temais. Como um vaso de um homem, quando se quebra, se torna inútil, assim são os deuses deles."},
{v:16,t:"Colocados nos templos, os seus olhos se enchem da poeira levantada pelos pés dos que entram."},
{v:17,t:"Como se cercam as portas de alguém que ofendeu o rei e é levado à morte, assim os sacerdotes protegem os templos deles com portas, fechaduras e trancas, para que não sejam roubados pelos ladrões."},
{v:18,t:"Acendem para eles lâmpadas, e mais do que para si mesmos, mas eles não podem ver nenhuma."},
{v:19,t:"São como as vigas do templo; dizem que o seu interior é roído pelos bichos que saem da terra, que os devoram, a eles e às suas roupas, sem que eles o sintam."},
{v:20,t:"O rosto deles fica preto com a fumaça do templo."},
{v:21,t:"Sobre o corpo e a cabeça deles pousam morcegos, andorinhas e outras aves, e também os gatos."},
{v:22,t:"Por aí sabereis que não são deuses; portanto, não os temais."},
{s:"Sem vida e sem sentimento"},
{v:23,t:"O ouro que os cobre para enfeitá-los não brilha se alguém não lhes tira a ferrugem; nem quando eram fundidos sentiam alguma coisa."},
{v:24,t:"Foram comprados a qualquer preço, e não há sopro de vida neles."},
{v:25,t:"Sem pés, são carregados aos ombros, mostrando aos homens a sua vergonha; e ficam envergonhados também os que os servem,"},
{v:26,t:"pois, se um deles cai por terra, precisa deles para ser levantado. Se alguém o põe de pé, ele não se move por si mesmo; se fica inclinado, não se endireita; põem-se diante deles as ofertas como diante de mortos."},
{v:27,t:"Os sacerdotes vendem as vítimas oferecidas a eles e tiram proveito delas; também as suas mulheres salgam uma parte, e não dão nada ao pobre nem ao doente. Mulheres menstruadas e mulheres de parto tocam nos seus sacrifícios.",n:"Pela Lei, essas mulheres ficavam impuras e não podiam tocar em coisas sagradas (Levítico 12,4; 15,19–24)."},
{v:28,t:"Sabendo por tudo isso que não são deuses, não os temais."},
{s:"Nem sequer ajudam os seus devotos"},
{v:29,t:"Como então podem ser chamados deuses? Pois são mulheres que servem as ofertas a esses deuses de prata, de ouro e de madeira;"},
{v:30,t:"e nos seus templos os sacerdotes se sentam com as túnicas rasgadas, a cabeça e a barba raspadas e a cabeça descoberta.",n:"Ritos de luto, proibidos aos sacerdotes de Israel (Levítico 21,5.10)."},
{v:31,t:"Gritam e urram diante dos seus deuses, como num banquete fúnebre."},
{v:32,t:"Os sacerdotes tiram das vestes deles para vestir as suas mulheres e os seus filhos."},
{v:33,t:"Se alguém lhes faz mal ou bem, não podem retribuir; não podem estabelecer um rei nem destituí-lo."},
{v:34,t:"Do mesmo modo, não podem dar riquezas nem dinheiro. Se alguém lhes faz um voto e não o cumpre, eles não o cobram."},
{v:35,t:"Não livram um homem da morte, nem arrancam o fraco das mãos do mais forte."},
{v:36,t:"Não devolvem a vista ao cego, não livram o homem da necessidade."},
{v:37,t:"Não têm compaixão da viúva, nem fazem o bem ao órfão."},
{v:38,t:"São semelhantes às pedras da montanha esses objetos de madeira, dourados e prateados; e os que os servem serão envergonhados."},
{v:39,t:"Como, então, se pode pensar ou dizer que são deuses?"},
{s:"Os próprios caldeus os desonram"},
{v:40,t:"Além disso, os próprios caldeus os desonram: quando veem um mudo que não pode falar, levam-no a Bel e pedem que ele fale,",n:"Bel: título de Marduk, o deus principal da Babilônia."},
{v:41,t:"como se Bel pudesse entender. E eles mesmos, embora o compreendam, não são capazes de abandonar os ídolos, pois não têm entendimento."},
{v:42,t:"As mulheres, cingidas com cordas, sentam-se nos caminhos, queimando farelo como incenso;",np:1,n:"Alusão à prostituição ritual ligada a certos cultos babilônicos, descrita também pelo historiador grego Heródoto."},
{v:43,t:"e quando uma delas, atraída por algum passante, se deita com ele, zomba da vizinha, porque não foi considerada digna como ela, nem teve a sua corda rompida."},
{v:44,t:"Tudo o que se faz por eles é falso. Como, então, se pode pensar ou dizer que são deuses?"},
{s:"Obra de mãos humanas"},
{v:45,t:"Foram feitos por artesãos e ourives; não serão outra coisa senão o que os artesãos quiserem que sejam."},
{v:46,t:"Os próprios que os fazem não vivem muito tempo; como, então, poderiam ser deuses as coisas que eles fabricaram?"},
{v:47,t:"Deixaram mentira e vergonha para os que vierem depois."},
{v:48,t:"Pois, quando vem sobre eles a guerra ou a desgraça, os sacerdotes pensam entre si onde se esconderão com eles."},
{v:49,t:"Como, então, não perceber que não são deuses, se não se livram nem da guerra nem das desgraças?"},
{v:50,t:"Sendo de madeira, dourados e prateados, depois se saberá que são falsos; ficará claro para todas as nações e para os reis que não são deuses, mas obras de mãos humanas, e que não há neles nenhuma obra de Deus."},
{v:51,t:"A quem, pois, não é evidente que não são deuses?"},
{s:"Não podem salvar ninguém"},
{v:52,t:"Não estabelecem um rei para o país, nem dão chuva aos homens."},
{v:53,t:"Não fazem justiça nas suas causas, nem livram os países que sofrem injustiça, pois não têm poder algum; são como gralhas entre o céu e a terra."},
{v:54,t:"Quando o fogo cai sobre o templo desses deuses de madeira, dourados ou prateados, os seus sacerdotes fogem e se salvam, mas eles queimam no meio, como vigas."},
{v:55,t:"Não resistem a um rei nem aos inimigos. Como, então, se pode pensar ou admitir que sejam deuses?"},
{v:56,t:"Os deuses de madeira, dourados e prateados, não se livram dos ladrões nem dos salteadores;",np:1},
{v:57,t:"estes são mais fortes do que eles: tiram-lhes o ouro, a prata e a veste que os cobre, e vão embora, e eles não conseguem ajudar-se a si mesmos."},
{v:58,t:"Por isso é melhor ser um rei que mostra a sua força, ou um utensílio útil numa casa, de que o dono pode se servir, do que esses falsos deuses; ou ainda a porta de uma casa, que guarda o que há dentro, do que esses falsos deuses; ou uma coluna de madeira num palácio, do que esses falsos deuses."},
{v:59,t:"O sol, a lua e as estrelas, que são brilhantes e enviados para servir, obedecem;"},
{v:60,t:"do mesmo modo o relâmpago, quando aparece, é bem visível; e também o vento sopra em toda a região;"},
{v:61,t:"e as nuvens, quando Deus lhes ordena percorrer o mundo inteiro, cumprem o que lhes foi ordenado;"},
{v:62,t:"também o fogo, enviado do alto para consumir montes e florestas, faz o que lhe foi mandado. Mas esses ídolos não se comparam a nenhuma dessas coisas, nem na forma nem no poder."},
{v:63,t:"Por isso não se deve pensar nem dizer que são deuses, pois não podem fazer justiça nem fazer o bem aos homens."},
{v:64,t:"Sabendo, pois, que não são deuses, não os temais."},
{s:"Melhor é o justo sem ídolos"},
{v:65,t:"Não podem amaldiçoar nem abençoar os reis."},
{v:66,t:"Não mostram às nações sinais no céu, não brilham como o sol, nem iluminam como a lua."},
{v:67,t:"Os animais são melhores do que eles, pois podem fugir para um abrigo e se proteger.",np:1},
{v:68,t:"De modo algum, portanto, é evidente para nós que sejam deuses; por isso, não os temais."},
{v:69,t:"Como um espantalho num pepinal, que nada guarda, assim são os seus deuses de madeira, dourados e prateados.",n:"Compare Jeremias 10,5."},
{v:70,t:"São também como um espinheiro num jardim, onde pousam todas as aves, ou como um cadáver jogado nas trevas: assim são os seus deuses de madeira, dourados e prateados."},
{v:71,t:"Pela púrpura e pelo linho fino que apodrecem sobre eles, sabereis que não são deuses; eles mesmos acabarão sendo devorados e serão uma vergonha para o país."},
{v:72,t:"Melhor é, portanto, o homem justo que não tem ídolos, pois estará longe da vergonha."}
];
