// =====================================================================
// Colossenses — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["colossenses"][1] = [
{s:"Saudação"},
{v:1,t:"Paulo, apóstolo de Cristo Jesus pela vontade de Deus, e o irmão Timóteo,"},
{v:2,t:"aos santos de Colossos, irmãos fiéis em Cristo: graça a vós e paz, da parte de Deus, nosso Pai."},
{s:"Ação de graças"},
{v:3,t:"Damos graças a Deus, Pai de nosso Senhor Jesus Cristo, orando sempre por vós,"},
{v:4,t:"desde que ouvimos falar da vossa fé em Cristo Jesus e do amor que tendes a todos os santos,"},
{v:5,t:"por causa da esperança que vos está reservada nos céus, e da qual já ouvistes pela palavra da verdade, o Evangelho"},
{v:6,t:"que chegou até vós. E, assim como no mundo inteiro, ele frutifica e cresce também entre vós, desde o dia em que ouvistes e conhecestes verdadeiramente a graça de Deus."},
{v:7,t:"Foi o que aprendestes de Epafras, nosso amado companheiro de serviço, fiel ministro de Cristo em vosso favor,"},
{v:8,t:"e foi ele quem nos falou do vosso amor no Espírito."},
{s:"Oração pelos colossenses"},
{v:9,t:"Por isso também nós, desde o dia em que o ouvimos, não cessamos de orar por vós, pedindo que sejais cheios do conhecimento da sua vontade, em toda sabedoria e inteligência espiritual;"},
{v:10,t:"para caminhardes de modo digno do Senhor, agradando-lhe em tudo, frutificando em toda boa obra e crescendo no conhecimento de Deus;"},
{v:11,t:"fortalecidos em tudo pelo poder da sua glória, para toda paciência e longanimidade, com alegria;"},
{v:12,t:"dando graças ao Pai, que vos tornou capazes de participar da herança dos santos, na luz."},
{v:13,t:"Ele nos arrancou do poder das trevas e nos transferiu para o Reino do Filho do seu amor,"},
{v:14,t:"no qual temos a redenção, a remissão dos pecados."},
{s:"Hino a Cristo, primogênito de toda criatura"},
{v:15,l:["Ele é a imagem do Deus invisível,","o primogênito de toda criatura;"],n:"Primogênito não o põe entre as criaturas: diz o seu primado sobre todas elas. O hino, provavelmente cantado na liturgia, responde aos que punham anjos e potências entre Deus e o mundo."},
{v:16,l:["porque nele foram criadas todas as coisas,","nos céus e na terra,","as visíveis e as invisíveis:","tronos, dominações, principados, potestades.","Tudo foi criado por ele e para ele."]},
{v:17,l:["Ele existe antes de tudo,","e tudo nele subsiste."]},
{v:18,l:["Ele é a cabeça do corpo, que é a Igreja;","é o princípio, o primogênito dentre os mortos,","para ter em tudo a primazia,"]},
{v:19,l:["porque aprouve a Deus","que nele habitasse toda a plenitude,"]},
{v:20,l:["e que por ele reconciliasse consigo todas as coisas,","pacificando pelo sangue da sua cruz","tanto as da terra como as dos céus."]},
{s:"A reconciliação"},
{v:21,t:"Também vós, que outrora éreis estranhos e inimigos, pelo pensamento e pelas obras más,"},
{v:22,t:"agora fostes reconciliados no corpo de carne dele, pela sua morte, para vos apresentar santos, imaculados e irrepreensíveis diante dele;"},
{v:23,t:"contanto que permaneçais fundados e firmes na fé, sem vos afastardes da esperança do Evangelho que ouvistes, o qual foi pregado a toda criatura debaixo do céu e do qual eu, Paulo, me tornei ministro."},
{s:"O ministério do Apóstolo"},
{v:24,t:"Agora me alegro nos sofrimentos por vós, e completo na minha carne o que falta às tribulações de Cristo, em favor do seu corpo, que é a Igreja.",n:"Nada falta à paixão do Senhor. O que falta é a parte de sofrimento que cabe aos membros do seu corpo, ao longo do tempo, até que a obra esteja consumada em todos."},
{v:25,t:"Dela me tornei ministro, segundo a missão que Deus me confiou em vosso favor: levar à plenitude a palavra de Deus,"},
{v:26,t:"o mistério escondido desde os séculos e desde as gerações, e agora manifestado aos seus santos."},
{v:27,t:"A eles quis Deus dar a conhecer a riqueza da glória deste mistério entre os gentios: Cristo em vós, a esperança da glória."},
{v:28,t:"É a ele que anunciamos, admoestando e instruindo todo homem em toda sabedoria, para apresentar todo homem perfeito em Cristo."},
{v:29,t:"É para isso que trabalho e luto, segundo a força dele, que age poderosamente em mim."}
];

window.TEXTOS_SEED["colossenses"][2] = [
{s:"A solicitude do Apóstolo"},
{v:1,t:"Quero, com efeito, que saibais quão grande é o combate que sustento por vós, pelos de Laodiceia e por todos os que nunca me viram pessoalmente,"},
{v:2,t:"para que os seus corações se animem e, unidos no amor, alcancem toda a riqueza de uma plena inteligência, no conhecimento do mistério de Deus, que é Cristo,"},
{v:3,t:"em quem estão escondidos todos os tesouros da sabedoria e da ciência."},
{v:4,t:"Digo isto para que ninguém vos engane com discursos persuasivos."},
{v:5,t:"Porque, ainda que ausente em corpo, estou convosco em espírito, e me alegro ao ver a vossa boa ordem e a firmeza da vossa fé em Cristo."},
{s:"A plenitude está em Cristo"},
{v:6,t:"Assim como recebestes Cristo Jesus, o Senhor, nele caminhai:"},
{v:7,t:"arraigados e edificados nele, firmes na fé, como fostes ensinados, transbordando em ação de graças."},
{v:8,t:"Cuidai que ninguém vos escravize pela filosofia e por vãs sutilezas, segundo a tradição dos homens, segundo os elementos do mundo, e não segundo Cristo."},
{v:9,t:"Porque nele habita corporalmente toda a plenitude da divindade,"},
{v:10,t:"e nele tendes a vossa plenitude — ele, que é a cabeça de todo principado e potestade."},
{v:11,t:"Nele também fostes circuncidados, com a circuncisão não feita por mão de homem, mas a de Cristo: o despojar-se do corpo de carne.",np:1},
{v:12,t:"Sepultados com ele no batismo, nele também fostes ressuscitados, pela fé no poder de Deus, que o ressuscitou dos mortos."},
{v:13,t:"E a vós, que estáveis mortos pelas vossas faltas e pela incircuncisão da vossa carne, deu-vos vida com ele, perdoando-nos todas as faltas."},
{v:14,t:"Cancelou o documento que nos era contrário, com as suas exigências, e o suprimiu, cravando-o na cruz."},
{v:15,t:"Despojou os principados e as potestades, e os expôs publicamente, levando-os no seu cortejo de triunfo."},
{s:"Contra as práticas vãs"},
{v:16,t:"Ninguém, portanto, vos julgue por causa de comida ou bebida, ou a respeito de festas, luas novas ou sábados:"},
{v:17,t:"tudo isso é sombra das coisas futuras; a realidade é o corpo de Cristo."},
{v:18,t:"Ninguém vos prive do prêmio, comprazendo-se em falsas humilhações e no culto dos anjos, deixando-se levar pelas suas visões, vãmente inchado pelo seu pensar carnal,"},
{v:19,t:"sem se apegar à cabeça, da qual o corpo inteiro, sustentado e unido pelas junturas e ligamentos, recebe o crescimento que vem de Deus."},
{v:20,t:"Se morrestes com Cristo para os elementos do mundo, por que ainda vos sujeitais a preceitos, como se vivêsseis no mundo:",np:1},
{v:21,t:"não pegues, não proves, não toques"},
{v:22,t:"— coisas todas que se destroem pelo uso —, segundo preceitos e doutrinas dos homens?"},
{v:23,t:"Tais coisas têm, é certo, aparência de sabedoria, com a sua devoção afetada, a sua humildade e o seu rigor para com o corpo; mas de nada valem contra os apetites da carne."}
];

window.TEXTOS_SEED["colossenses"][3] = [
{s:"Buscar as coisas do alto"},
{v:1,t:"Portanto, se ressuscitastes com Cristo, buscai as coisas do alto, onde Cristo está sentado à direita de Deus."},
{v:2,t:"Pensai nas coisas do alto, não nas da terra."},
{v:3,t:"Porque morrestes, e a vossa vida está escondida com Cristo em Deus."},
{v:4,t:"Quando Cristo, que é a vossa vida, se manifestar, então também vós vos manifestareis com ele, na glória."},
{s:"Despir o homem velho"},
{v:5,t:"Fazei, pois, morrer o que em vós é terreno: fornicação, impureza, paixão, mau desejo, e a avareza, que é idolatria."},
{v:6,t:"Por essas coisas vem a ira de Deus sobre os filhos da rebeldia."},
{v:7,t:"Também vós outrora andastes nelas, quando nelas vivíeis."},
{v:8,t:"Agora, porém, deixai vós também tudo isso: ira, indignação, malícia, maledicência e as palavras torpes da vossa boca."},
{v:9,t:"Não mintais uns aos outros; despistes o homem velho com as suas obras"},
{v:10,t:"e vos revestistes do novo, que se renova para o conhecimento, segundo a imagem daquele que o criou."},
{v:11,t:"Aí já não há grego nem judeu, circuncisão nem incircuncisão, bárbaro, cita, escravo, livre; mas Cristo é tudo em todos."},
{v:12,t:"Revesti-vos, pois, como eleitos de Deus, santos e amados, de sentimentos de misericórdia, de bondade, humildade, mansidão e paciência.",np:1},
{v:13,t:"Suportai-vos uns aos outros e perdoai-vos mutuamente, se alguém tiver queixa contra outro. Como o Senhor vos perdoou, assim também perdoai vós."},
{v:14,t:"E, acima de tudo isso, revesti-vos do amor, que é o vínculo da perfeição."},
{v:15,t:"Reine em vossos corações a paz de Cristo, à qual fostes chamados, num só corpo. E sede agradecidos."},
{v:16,t:"A palavra de Cristo habite em vós com abundância: instruí-vos e admoestai-vos uns aos outros em toda sabedoria; com salmos, hinos e cânticos espirituais, cantai a Deus, com gratidão, em vossos corações."},
{v:17,t:"E tudo o que fizerdes, por palavra ou por obra, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai."},
{s:"A vida doméstica"},
{v:18,t:"Mulheres, sede submissas aos vossos maridos, como convém no Senhor."},
{v:19,t:"Maridos, amai as vossas mulheres e não sejais ásperos com elas."},
{v:20,t:"Filhos, obedecei em tudo a vossos pais, porque isso agrada ao Senhor."},
{v:21,t:"Pais, não exaspereis os vossos filhos, para que não se desanimem."},
{v:22,t:"Servos, obedecei em tudo aos vossos senhores segundo a carne, não servindo só quando observados, para agradar aos homens, mas com simplicidade de coração, no temor do Senhor."},
{v:23,t:"Tudo o que fizerdes, fazei-o de coração, como para o Senhor e não para os homens,"},
{v:24,t:"sabendo que do Senhor recebereis a herança como recompensa. Servi a Cristo, o Senhor."},
{v:25,t:"Quem comete injustiça receberá conforme a injustiça que cometeu; e não há acepção de pessoas."}
];

window.TEXTOS_SEED["colossenses"][4] = [
{s:"Exortações finais"},
{v:1,t:"Senhores, dai aos vossos servos o que é justo e equitativo, sabendo que também vós tendes um Senhor no céu."},
{v:2,t:"Perseverai na oração, vigiando nela com ação de graças."},
{v:3,t:"Orai também por nós, para que Deus nos abra uma porta à palavra, a fim de anunciarmos o mistério de Cristo — por causa do qual estou preso —,"},
{v:4,t:"e para que eu o manifeste, falando dele como devo."},
{v:5,t:"Comportai-vos com sabedoria diante dos de fora, aproveitando bem o tempo."},
{v:6,t:"A vossa palavra seja sempre amável, temperada com sal, para saberdes como responder a cada um."},
{s:"Notícias e saudações"},
{v:7,t:"De tudo o que me diz respeito vos informará Tíquico, o irmão amado, fiel ministro e companheiro de serviço no Senhor."},
{v:8,t:"Eu vo-lo envio para isto mesmo: para que saibais o que nos vai e para que ele console os vossos corações."},
{v:9,t:"Com ele vai Onésimo, o irmão fiel e amado, que é dos vossos. Eles vos contarão tudo o que aqui se passa."},
{v:10,t:"Saúda-vos Aristarco, meu companheiro de prisão, e Marcos, o primo de Barnabé, a respeito de quem recebestes instruções: se for ter convosco, acolhei-o.",np:1},
{v:11,t:"Saúda-vos também Jesus, chamado Justo. Destes, que são da circuncisão, só eles trabalham comigo pelo Reino de Deus, e têm sido para mim um conforto."},
{v:12,t:"Saúda-vos Epafras, que é dos vossos, servo de Cristo Jesus, sempre lutando por vós nas suas orações, para que permaneçais perfeitos e plenamente firmes em tudo o que Deus quer."},
{v:13,t:"Dou-lhe testemunho de que muito se afadiga por vós, pelos de Laodiceia e pelos de Hierápolis."},
{v:14,t:"Saúda-vos Lucas, o médico amado, e também Demas."},
{v:15,t:"Saudai os irmãos de Laodiceia, e Ninfa, e a Igreja que se reúne na sua casa."},
{v:16,t:"Depois de lida esta carta entre vós, fazei que seja lida também na Igreja de Laodiceia; e lede vós a que vier de Laodiceia.",n:"A carta aos laodicenses perdeu-se, ou é a que hoje se chama aos Efésios, escrita como circular. A troca de cartas entre Igrejas vizinhas era já uma prática, e foi por ela que os escritos apostólicos se difundiram."},
{v:17,t:"E dizei a Arquipo: Atende ao ministério que recebeste no Senhor, para o cumprires."},
{v:18,t:"A saudação é de meu próprio punho: Paulo. Lembrai-vos das minhas cadeias. A graça esteja convosco."}
];
