// =====================================================================
// Daniel — tradução do hebraico e do aramaico; os acréscimos (3,24–90; 13–14),
// do grego (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["daniel"][1] = [
{s:"Os jovens judeus na corte da Babilônia"},
{v:1,t:"No terceiro ano do reinado de Joaquim, rei de Judá, Nabucodonosor, rei da Babilônia, veio a Jerusalém e a sitiou;",n:"Por volta de 606 antes de Cristo; a data não coincide com o que se sabe pelos outros livros (compare 2 Reis 24,1; Jeremias 25,1). O livro de Daniel, composto no tempo da perseguição de Antíoco IV Epífanes (167–164 antes de Cristo), usa a história do exílio como moldura do seu ensinamento."},
{v:2,t:"e o Senhor entregou nas suas mãos Joaquim, rei de Judá, e parte dos utensílios da casa de Deus; ele os levou para a terra de Senaar, para o templo dos seus deuses, e colocou os utensílios no tesouro dos seus deuses."},
{v:3,t:"O rei disse a Asfanaz, chefe dos seus eunucos, que trouxesse alguns dos filhos de Israel, de linhagem real e de famílias nobres,",np:1},
{v:4,t:"jovens sem nenhum defeito, de boa aparência, instruídos em toda a sabedoria, cultos e inteligentes, capazes de servir no palácio do rei, e que lhes ensinasse a literatura e a língua dos caldeus."},
{v:5,t:"O rei lhes destinou uma ração diária das iguarias da sua mesa e do vinho que ele mesmo bebia; deviam ser educados durante três anos e, depois, servir diante do rei."},
{v:6,t:"Entre eles estavam, dos filhos de Judá, Daniel, Ananias, Misael e Azarias."},
{v:7,t:"O chefe dos eunucos lhes deu outros nomes: a Daniel, Baltasar; a Ananias, Sedrac; a Misael, Misac; e a Azarias, Abdênago."},
{s:"A fidelidade de Daniel e dos companheiros"},
{v:8,t:"Daniel decidiu no seu coração não se contaminar com as iguarias da mesa do rei nem com o vinho que ele bebia, e pediu ao chefe dos eunucos que lhe permitisse não se contaminar.",n:"Os alimentos do rei não seguiam as leis de pureza (Levítico 11) e podiam ter sido oferecidos aos ídolos."},
{v:9,t:"Deus concedeu a Daniel encontrar favor e simpatia diante do chefe dos eunucos;"},
{v:10,t:"mas o chefe dos eunucos disse a Daniel: Tenho medo do meu senhor, o rei, que determinou a vossa comida e a vossa bebida; se ele vir os vossos rostos mais abatidos que os dos outros jovens da vossa idade, poreis em perigo a minha cabeça diante do rei."},
{v:11,t:"Daniel disse então ao guarda que o chefe dos eunucos tinha posto sobre Daniel, Ananias, Misael e Azarias:"},
{v:12,t:"Põe à prova os teus servos, por favor, durante dez dias: que nos deem legumes para comer e água para beber;"},
{v:13,t:"depois compara os nossos rostos com os dos jovens que comem as iguarias do rei, e faze com os teus servos conforme o que vires."},
{v:14,t:"Ele aceitou a proposta e os pôs à prova durante dez dias.",np:1},
{v:15,t:"Ao fim dos dez dias, tinham melhor aparência e estavam mais robustos que todos os jovens que comiam as iguarias do rei."},
{v:16,t:"Desde então, o guarda retirava as iguarias e o vinho que deviam beber e lhes dava legumes.",np:1},
{v:17,t:"A estes quatro jovens Deus deu conhecimento e compreensão de toda a literatura e sabedoria; e Daniel entendia toda espécie de visões e de sonhos.",np:1},
{v:18,t:"Ao fim do tempo que o rei tinha marcado para que fossem apresentados, o chefe dos eunucos os levou à presença de Nabucodonosor."},
{v:19,t:"O rei conversou com eles, e entre todos não se encontrou ninguém como Daniel, Ananias, Misael e Azarias; e ficaram ao serviço do rei."},
{v:20,t:"Em todas as questões de sabedoria e de inteligência sobre as quais o rei os interrogou, achou-os dez vezes superiores a todos os magos e adivinhos que havia em todo o seu reino."},
{v:21,t:"E Daniel ficou ali até o primeiro ano do rei Ciro.",n:"Em 539 antes de Cristo, quando Ciro tomou a Babilônia."}
];

window.TEXTOS_SEED["daniel"][2] = [
{s:"O sonho de Nabucodonosor"},
{v:1,t:"No segundo ano do reinado de Nabucodonosor, Nabucodonosor teve um sonho; o seu espírito ficou perturbado, e o sono fugiu dele."},
{v:2,t:"O rei mandou chamar os magos, os adivinhos, os feiticeiros e os caldeus, para que lhe explicassem os seus sonhos; eles vieram e se apresentaram diante do rei.",n:"Caldeus: aqui, a casta dos sábios e astrólogos da Babilônia."},
{v:3,t:"O rei lhes disse: Tive um sonho, e o meu espírito está perturbado, querendo compreender o sonho."},
{v:4,t:"Os caldeus responderam ao rei, em aramaico: Ó rei, vive para sempre! Conta o sonho aos teus servos, e nós te daremos a interpretação.",n:"A partir daqui, até o fim do capítulo 7, o texto original está em aramaico."},
{v:5,t:"O rei respondeu aos caldeus: A decisão já saiu da minha boca: se não me fizerdes conhecer o sonho e a sua interpretação, sereis cortados em pedaços, e as vossas casas serão transformadas em monturo;"},
{v:6,t:"mas, se me contardes o sonho e a sua interpretação, recebereis de mim presentes, recompensas e grandes honras. Contai-me, pois, o sonho e a sua interpretação."},
{v:7,t:"Eles responderam pela segunda vez: Que o rei conte o sonho aos seus servos, e nós lhe daremos a interpretação.",np:1},
{v:8,t:"O rei respondeu: Vejo bem que quereis ganhar tempo, porque sabeis que a minha decisão está tomada."},
{v:9,t:"Se não me contardes o sonho, uma só sentença vos espera. Combinastes dizer-me palavras mentirosas e enganosas, até que as coisas mudem; por isso contai-me o sonho, e saberei que podeis dar-me a sua interpretação."},
{v:10,t:"Os caldeus responderam ao rei: Não há ninguém na terra que possa fazer o que o rei pede; por isso nenhum rei, por grande e poderoso que seja, jamais pediu tal coisa a nenhum mago, adivinho ou caldeu."},
{v:11,t:"O que o rei pede é difícil, e não há ninguém que o possa revelar ao rei, a não ser os deuses, que não habitam entre os homens."},
{v:12,t:"Ao ouvir isso, o rei se enfureceu e, muito irritado, ordenou que matassem todos os sábios da Babilônia."},
{v:13,t:"Publicado o decreto que mandava matar os sábios, procuraram Daniel e os seus companheiros para matá-los.",np:1},
{s:"Deus revela o mistério a Daniel"},
{v:14,t:"Então Daniel dirigiu-se com prudência e sensatez a Arioc, chefe da guarda do rei, que tinha saído para matar os sábios da Babilônia;"},
{v:15,t:"perguntou a Arioc, a quem o rei tinha dado a ordem, por que razão o rei tinha dado uma sentença tão cruel. Arioc explicou o caso a Daniel,"},
{v:16,t:"e Daniel foi pedir ao rei que lhe desse tempo para revelar ao rei a interpretação."},
{v:17,t:"Daniel foi para casa e contou o caso aos seus companheiros Ananias, Misael e Azarias,"},
{v:18,t:"para que pedissem misericórdia ao Deus do céu a respeito desse mistério, a fim de que Daniel e os seus companheiros não morressem com os outros sábios da Babilônia."},
{v:19,t:"Então o mistério foi revelado a Daniel numa visão noturna, e Daniel bendisse o Deus do céu."},
{v:20,l:["Daniel tomou a palavra e disse:","Bendito seja o nome de Deus","desde sempre e para sempre,","pois a ele pertencem a sabedoria e o poder;"]},
{v:21,l:["ele muda os tempos e as épocas,","depõe reis e estabelece reis,","dá a sabedoria aos sábios","e o conhecimento aos que sabem discernir;"],np:1},
{v:22,l:["ele revela as coisas profundas e ocultas,","conhece o que está nas trevas,","e a luz habita com ele."],np:1},
{v:23,l:["A ti, Deus dos meus pais, dou graças e louvo,","porque me deste a sabedoria e o poder","e agora me fizeste conhecer o que te pedimos,","pois nos revelaste o assunto do rei."],np:1},
{s:"Daniel revela o sonho"},
{v:24,t:"Por isso Daniel foi ter com Arioc, a quem o rei tinha encarregado de matar os sábios da Babilônia, e lhe disse: Não mates os sábios da Babilônia; leva-me à presença do rei, e darei ao rei a interpretação."},
{v:25,t:"Arioc levou depressa Daniel à presença do rei e lhe disse: Encontrei entre os deportados de Judá um homem que dará ao rei a interpretação."},
{v:26,t:"O rei perguntou a Daniel, cujo nome era Baltasar: És tu capaz de me contar o sonho que tive e a sua interpretação?"},
{v:27,t:"Daniel respondeu diante do rei: O mistério que o rei pergunta, nenhum sábio, mago, adivinho ou astrólogo o pode revelar ao rei;"},
{v:28,t:"mas há um Deus no céu que revela os mistérios; ele fez saber ao rei Nabucodonosor o que acontecerá no fim dos tempos. Este é o teu sonho, e estas são as visões que passaram pela tua cabeça, quando estavas deitado:"},
{v:29,t:"Tu, ó rei, estando deitado, pensavas no que aconteceria depois; e aquele que revela os mistérios te fez saber o que vai acontecer."},
{v:30,t:"Quanto a mim, este mistério me foi revelado, não porque eu tenha mais sabedoria do que todos os vivos, mas para que a interpretação fosse dada a conhecer ao rei e tu conhecesses os pensamentos do teu coração."},
{v:31,t:"Tu, ó rei, olhavas, e eis uma grande estátua; essa estátua, enorme e de extraordinário esplendor, estava de pé diante de ti, e o seu aspecto era terrível.",np:1},
{v:32,t:"A cabeça dessa estátua era de ouro fino; o peito e os braços, de prata; o ventre e as coxas, de bronze;"},
{v:33,t:"as pernas, de ferro; os pés, parte de ferro e parte de barro."},
{v:34,t:"Enquanto olhavas, uma pedra se desprendeu, sem intervenção de mão alguma, atingiu a estátua nos pés de ferro e de barro e os despedaçou."},
{v:35,t:"Então o ferro, o barro, o bronze, a prata e o ouro se despedaçaram juntos e ficaram como a palha das eiras no verão: o vento os levou, e não ficou nenhum vestígio deles; mas a pedra que tinha atingido a estátua tornou-se uma grande montanha e encheu toda a terra."},
{s:"A interpretação: os quatro reinos"},
{v:36,t:"Este é o sonho; agora diremos ao rei a sua interpretação."},
{v:37,t:"Tu, ó rei, és o rei dos reis, a quem o Deus do céu deu o reino, o poder, a força e a glória;"},
{v:38,t:"ele entregou nas tuas mãos os filhos dos homens, os animais do campo e as aves do céu, onde quer que habitem, e te fez senhor de todos eles: tu és a cabeça de ouro."},
{v:39,t:"Depois de ti surgirá outro reino, inferior ao teu, e um terceiro reino, de bronze, que dominará toda a terra.",n:"Os reinos são geralmente identificados com a Babilônia, os medos, os persas e os gregos de Alexandre e dos seus sucessores; o reino que não terá fim é o reino de Deus."},
{v:40,t:"O quarto reino será forte como o ferro: assim como o ferro despedaça e esmaga tudo, e como o ferro que tritura, ele despedaçará e triturará todos esses."},
{v:41,t:"Quanto aos pés e aos dedos que viste, parte de barro de oleiro e parte de ferro, será um reino dividido; mas terá algo da solidez do ferro, pois viste o ferro misturado com o barro de argila."},
{v:42,t:"E como os dedos dos pés eram parte de ferro e parte de barro, assim o reino será em parte forte e em parte frágil.",np:1},
{v:43,t:"Quanto ao ferro misturado com o barro de argila, que viste, eles se misturarão por meio de casamentos, mas não se unirão uns aos outros, assim como o ferro não se mistura com o barro."},
{v:44,t:"Nos dias desses reinos, o Deus do céu suscitará um reino que nunca será destruído, e esse reino não passará a outro povo; esmagará e aniquilará todos esses reinos, e ele mesmo permanecerá para sempre;"},
{v:45,t:"foi o que viste: uma pedra se desprendeu da montanha, sem intervenção de mão alguma, e despedaçou o barro, o ferro, o bronze, a prata e o ouro. O grande Deus fez saber ao rei o que vai acontecer depois disso. O sonho é verdadeiro, e a sua interpretação, digna de fé.",n:"Os Padres da Igreja leram na pedra desprendida sem mão humana uma figura de Cristo."},
{s:"Daniel honrado pelo rei"},
{v:46,t:"Então o rei Nabucodonosor caiu com o rosto por terra, prostrou-se diante de Daniel e mandou que lhe oferecessem sacrifícios e incenso."},
{v:47,t:"O rei disse a Daniel: Verdadeiramente o vosso Deus é o Deus dos deuses e o Senhor dos reis, e revela os mistérios, pois tu pudeste revelar este mistério."},
{v:48,t:"Então o rei elevou Daniel a uma alta posição, deu-lhe muitos e grandes presentes e o constituiu governador de toda a província da Babilônia e chefe supremo de todos os sábios da Babilônia."},
{v:49,t:"A pedido de Daniel, o rei pôs Sedrac, Misac e Abdênago à frente da administração da província da Babilônia; Daniel, porém, ficou na corte do rei."}
];

window.TEXTOS_SEED["daniel"][3] = [
{s:"A estátua de ouro"},
{v:1,t:"O rei Nabucodonosor fez uma estátua de ouro de sessenta côvados de altura e seis côvados de largura, e a levantou na planície de Dura, na província da Babilônia.",n:"Cerca de trinta metros de altura."},
{v:2,t:"O rei Nabucodonosor mandou reunir os sátrapas, os magistrados, os juízes, os generais, os governadores, os prefeitos e todas as autoridades das províncias, para que viessem à dedicação da estátua que o rei Nabucodonosor tinha levantado.",np:1},
{v:3,t:"Reuniram-se então os sátrapas, os magistrados, os juízes, os generais, os governadores, os altos funcionários que ocupavam os cargos de poder e todas as autoridades das províncias, para a dedicação da estátua que o rei Nabucodonosor tinha levantado. Estavam de pé diante da estátua que Nabucodonosor tinha levantado,"},
{v:4,t:"e o arauto gritava com força: A vós é dito, povos, nações e línguas:"},
{v:5,t:"no momento em que ouvirdes o som da trombeta, da flauta, da cítara, da sambuca, do saltério, da gaita de foles e de toda espécie de instrumentos musicais, prostrai-vos e adorai a estátua de ouro que o rei Nabucodonosor levantou."},
{v:6,t:"Quem não se prostrar e não a adorar será lançado imediatamente na fornalha de fogo ardente."},
{v:7,t:"Por isso, assim que todos os povos ouviram o som da trombeta, da flauta, da cítara, da sambuca, do saltério, da gaita de foles e de toda espécie de instrumentos musicais, todos os povos, nações e línguas se prostraram e adoraram a estátua de ouro que o rei Nabucodonosor tinha levantado."},
{s:"Os três jovens denunciados"},
{v:8,t:"Naquele mesmo momento, alguns caldeus se aproximaram e acusaram os judeus;"},
{v:9,t:"disseram ao rei Nabucodonosor: Ó rei, vive para sempre!"},
{v:10,t:"Tu, ó rei, deste um decreto: todo homem que ouvir o som da trombeta, da flauta, da cítara, da sambuca, do saltério, da gaita de foles e de toda espécie de instrumentos musicais deve prostrar-se e adorar a estátua de ouro;"},
{v:11,t:"e quem não se prostrar e não a adorar será lançado na fornalha de fogo ardente."},
{v:12,t:"Pois bem, há uns judeus que puseste à frente da administração da província da Babilônia, Sedrac, Misac e Abdênago; esses homens não fazem caso de ti, ó rei: não servem os teus deuses e não adoram a estátua de ouro que levantaste."},
{v:13,t:"Então Nabucodonosor, furioso e irado, mandou trazer Sedrac, Misac e Abdênago; e esses homens foram trazidos à presença do rei.",np:1},
{v:14,t:"Nabucodonosor lhes disse: É verdade, Sedrac, Misac e Abdênago, que não servis os meus deuses e não adorais a estátua de ouro que levantei?"},
{v:15,t:"Estais agora prontos, no momento em que ouvirdes o som da trombeta, da flauta, da cítara, da sambuca, do saltério, da gaita de foles e de toda espécie de instrumentos musicais, a vos prostrar e adorar a estátua que fiz? Se não a adorardes, sereis lançados imediatamente na fornalha de fogo ardente; e qual é o deus que vos livrará das minhas mãos?"},
{v:16,t:"Sedrac, Misac e Abdênago responderam ao rei Nabucodonosor: Não precisamos responder-te sobre isso:",np:1},
{v:17,t:"se o nosso Deus, a quem servimos, pode livrar-nos da fornalha de fogo ardente, ele nos livrará também das tuas mãos, ó rei."},
{v:18,t:"E, ainda que não o faça, fica sabendo, ó rei, que não serviremos os teus deuses nem adoraremos a estátua de ouro que levantaste.",np:1},
{s:"Na fornalha ardente"},
{v:19,t:"Então Nabucodonosor se encheu de furor, e o seu rosto se transformou contra Sedrac, Misac e Abdênago; e ordenou que se aquecesse a fornalha sete vezes mais do que de costume;"},
{v:20,t:"e mandou aos homens mais fortes do seu exército que amarrassem Sedrac, Misac e Abdênago e os lançassem na fornalha de fogo ardente."},
{v:21,t:"Imediatamente esses homens foram amarrados, com os seus mantos, as suas túnicas, os seus turbantes e as suas outras roupas, e lançados no meio da fornalha de fogo ardente;"},
{v:22,t:"e, como a ordem do rei era urgente e a fornalha estava extremamente quente, a chama do fogo matou os homens que tinham levado Sedrac, Misac e Abdênago."},
{v:23,t:"E os três homens, Sedrac, Misac e Abdênago, caíram amarrados no meio da fornalha de fogo ardente.",n:"A Nova Vulgata reproduz aqui uma nota de São Jerônimo: O que segue não o encontrei nos volumes hebraicos. Os vv. 24–90 foram conservados em grego, na tradução de Teodocião."},
{s:"A oração de Azarias"},
{v:24,t:"Eles andavam no meio das chamas, louvando a Deus e bendizendo o Senhor."},
{v:25,t:"Azarias, de pé, rezou assim, abrindo a boca no meio do fogo:"},
{v:26,l:["Bendito sejas, Senhor, Deus dos nossos pais,","digno de louvor, e glorioso é o teu nome para sempre,"],np:1},
{v:27,l:["pois és justo em tudo o que nos fizeste;","todas as tuas obras são verdadeiras, retos os teus caminhos,","e verdadeiros todos os teus julgamentos."],np:1},
{v:28,l:["Justos foram os julgamentos que executaste","em tudo o que fizeste cair sobre nós","e sobre Jerusalém, a cidade santa dos nossos pais,","pois com verdade e justiça fizeste vir tudo isso","por causa dos nossos pecados."],np:1},
{v:29,l:["Pecamos, cometemos a iniquidade, afastando-nos de ti,","e erramos em tudo;"],np:1},
{v:30,l:["não escutamos os teus mandamentos,","não os observamos,","nem fizemos o que nos tinhas ordenado","para o nosso bem."],np:1},
{v:31,l:["Tudo o que fizeste cair sobre nós","e tudo o que nos fizeste,","fizeste-o com justo julgamento;"],np:1},
{v:32,l:["entregaste-nos nas mãos dos nossos inimigos,","injustos, perversos e rebeldes,","e de um rei injusto, o pior de toda a terra."],np:1},
{v:33,l:["E agora não podemos abrir a boca;","a vergonha e o opróbrio caíram","sobre os teus servos e sobre os que te adoram."],np:1},
{v:34,l:["Não nos abandones para sempre,","por causa do teu nome,","e não anules a tua aliança;"],np:1},
{v:35,l:["não retires de nós a tua misericórdia,","por amor de Abraão, teu amigo,","de Isaac, teu servo,","e de Israel, teu santo,"],np:1},
{v:36,l:["aos quais prometeste","multiplicar a sua descendência como as estrelas do céu","e como a areia da praia do mar."],np:1},
{v:37,l:["Pois, Senhor,","tornamo-nos menores que todas as nações","e hoje somos humilhados em toda a terra","por causa dos nossos pecados."],np:1},
{v:38,l:["Neste tempo já não temos","príncipe, nem profeta, nem chefe,","nem holocausto, nem sacrifício,","nem oblação, nem incenso,","nem lugar onde oferecer as primícias diante de ti","e encontrar misericórdia."],np:1},
{v:39,l:["Mas, com a alma arrependida e o espírito humilhado, sejamos acolhidos,","como se fosse com holocaustos de carneiros e de touros"],np:1},
{v:40,l:["e com milhares de cordeiros gordos;","assim seja hoje o nosso sacrifício diante de ti,","e leva à perfeição os que te seguem,","pois não serão confundidos os que confiam em ti."],np:1},
{v:41,l:["E agora te seguimos de todo o coração,","te tememos e procuramos a tua face;"],np:1},
{v:42,l:["não nos cubras de vergonha,","mas trata-nos segundo a tua bondade","e segundo a grandeza da tua misericórdia;"],np:1},
{v:43,l:["livra-nos com os teus prodígios","e dá glória ao teu nome, Senhor."],np:1},
{v:44,l:["Sejam confundidos todos os que fazem mal aos teus servos;","sejam cobertos de vergonha, privados de todo o poder,","e seja quebrada a sua força."]},
{v:45,l:["Saibam que tu és o Senhor,","o único Deus, glorioso sobre toda a terra."],np:1},
{s:"O anjo do Senhor na fornalha"},
{v:46,t:"Os servos do rei que os tinham lançado na fornalha não cessavam de alimentar o fogo com nafta, estopa, piche e sarmentos;"},
{v:47,t:"e a chama se elevava por cima da fornalha a quarenta e nove côvados,"},
{v:48,t:"saía e queimava os caldeus que encontrava ao redor da fornalha."},
{v:49,t:"Mas o anjo do Senhor desceu à fornalha junto com Azarias e os seus companheiros, afastou da fornalha a chama do fogo"},
{v:50,t:"e fez soprar no meio da fornalha como que um vento fresco de orvalho; e o fogo não os tocou de modo algum, nem os feriu, nem os molestou."},
{s:"O cântico dos três jovens"},
{v:51,t:"Então os três, como que a uma só voz, louvavam, glorificavam e bendiziam a Deus na fornalha, dizendo:"},
{v:52,l:["Bendito sejas, Senhor, Deus dos nossos pais,","digno de louvor e exaltado para sempre;","bendito o teu nome santo e glorioso,","digno de louvor e exaltado para sempre."],np:1,n:"Este cântico é rezado na Liturgia das Horas, nas Laudes dos domingos e das festas."},
{v:53,l:["Bendito sejas no templo da tua santa glória,","digno de louvor e de glória para sempre."],np:1},
{v:54,l:["Bendito sejas no trono do teu reino,","digno de louvor e exaltado para sempre."],np:1},
{v:55,l:["Bendito sejas tu, que sondas os abismos, sentado sobre os querubins,","digno de louvor e exaltado para sempre."],np:1},
{v:56,l:["Bendito sejas no firmamento do céu,","digno de louvor e de glória para sempre."],np:1},
{v:57,l:["Bendizei o Senhor, todas as obras do Senhor,","louvai-o e exaltai-o para sempre."],np:1},
{v:58,l:["Bendizei o Senhor, céus,","louvai-o e exaltai-o para sempre."],np:1},
{v:59,l:["Bendizei o Senhor, anjos do Senhor,","louvai-o e exaltai-o para sempre."],np:1},
{v:60,l:["Bendizei o Senhor, águas todas que estão acima dos céus,","louvai-o e exaltai-o para sempre."],np:1},
{v:61,l:["Bendizei o Senhor, todos os poderes do céu,","louvai-o e exaltai-o para sempre."],np:1},
{v:62,l:["Bendizei o Senhor, sol e lua,","louvai-o e exaltai-o para sempre."],np:1},
{v:63,l:["Bendizei o Senhor, estrelas do céu,","louvai-o e exaltai-o para sempre."],np:1},
{v:64,l:["Bendizei o Senhor, chuvas e orvalhos,","louvai-o e exaltai-o para sempre."],np:1},
{v:65,l:["Bendizei o Senhor, ventos todos,","louvai-o e exaltai-o para sempre."],np:1},
{v:66,l:["Bendizei o Senhor, fogo e calor,","louvai-o e exaltai-o para sempre."],np:1},
{v:67,l:["Bendizei o Senhor, frio e ardor,","louvai-o e exaltai-o para sempre."],np:1},
{v:68,l:["Bendizei o Senhor, orvalhos e geadas,","louvai-o e exaltai-o para sempre."],np:1},
{v:69,l:["Bendizei o Senhor, gelo e frio,","louvai-o e exaltai-o para sempre."],np:1},
{v:70,l:["Bendizei o Senhor, gelos e neves,","louvai-o e exaltai-o para sempre."],np:1},
{v:71,l:["Bendizei o Senhor, noites e dias,","louvai-o e exaltai-o para sempre."],np:1},
{v:72,l:["Bendizei o Senhor, luz e trevas,","louvai-o e exaltai-o para sempre."],np:1},
{v:73,l:["Bendizei o Senhor, relâmpagos e nuvens,","louvai-o e exaltai-o para sempre."],np:1},
{v:74,l:["Bendiga a terra o Senhor,","louve-o e exalte-o para sempre."],np:1},
{v:75,l:["Bendizei o Senhor, montes e colinas,","louvai-o e exaltai-o para sempre."],np:1},
{v:76,l:["Bendizei o Senhor, plantas todas que brotais da terra,","louvai-o e exaltai-o para sempre."],np:1},
{v:77,l:["Bendizei o Senhor, mares e rios,","louvai-o e exaltai-o para sempre."],np:1},
{v:78,l:["Bendizei o Senhor, fontes,","louvai-o e exaltai-o para sempre."],np:1},
{v:79,l:["Bendizei o Senhor, monstros marinhos e tudo o que se move nas águas,","louvai-o e exaltai-o para sempre."],np:1},
{v:80,l:["Bendizei o Senhor, aves todas do céu,","louvai-o e exaltai-o para sempre."],np:1},
{v:81,l:["Bendizei o Senhor, feras e rebanhos,","louvai-o e exaltai-o para sempre."],np:1},
{v:82,l:["Bendizei o Senhor, filhos dos homens,","louvai-o e exaltai-o para sempre."],np:1},
{v:83,l:["Bendize o Senhor, Israel,","louvai-o e exaltai-o para sempre."],np:1},
{v:84,l:["Bendizei o Senhor, sacerdotes do Senhor,","louvai-o e exaltai-o para sempre."],np:1},
{v:85,l:["Bendizei o Senhor, servos do Senhor,","louvai-o e exaltai-o para sempre."],np:1},
{v:86,l:["Bendizei o Senhor, espíritos e almas dos justos,","louvai-o e exaltai-o para sempre."],np:1},
{v:87,l:["Bendizei o Senhor, santos e humildes de coração,","louvai-o e exaltai-o para sempre."],np:1},
{v:88,l:["Bendizei o Senhor, Ananias, Azarias e Misael,","louvai-o e exaltai-o para sempre;","pois ele nos arrancou da morada dos mortos e nos salvou da mão da morte,","nos livrou do meio da fornalha de chamas ardentes","e nos arrancou do meio do fogo."],np:1},
{v:89,l:["Dai graças ao Senhor, porque ele é bom,","porque o seu amor é para sempre."],np:1},
{v:90,l:["Bendizei o Deus dos deuses, todos vós que temeis o Senhor;","louvai-o e dai-lhe graças, porque o seu amor é para sempre."],np:1,n:"A Nova Vulgata reproduz aqui outra nota de São Jerônimo: Até aqui, o texto não se encontra no hebraico; o que pusemos foi traduzido da edição de Teodocião."},
{s:"Nabucodonosor reconhece o Deus altíssimo"},
{v:91,t:"Então o rei Nabucodonosor, espantado, levantou-se às pressas e perguntou aos seus conselheiros: Não foram três homens amarrados que lançamos no meio do fogo? Eles responderam ao rei: Certamente, ó rei.",n:"Os vv. 91–100 correspondem a 3,24–33 do texto aramaico (em outras Bíblias, 3,24–30 e 4,1–3)."},
{v:92,t:"Ele disse: Mas eu vejo quatro homens soltos, andando no meio do fogo, sem sofrer dano algum, e o aspecto do quarto é semelhante a um filho dos deuses.",n:"Um filho dos deuses: um ser divino, um anjo (v. 95)."},
{v:93,t:"Nabucodonosor aproximou-se da boca da fornalha de fogo ardente e disse: Sedrac, Misac e Abdênago, servos do Deus altíssimo, saí e vinde! Então Sedrac, Misac e Abdênago saíram do meio do fogo."},
{v:94,t:"Os sátrapas, os magistrados, os juízes e os conselheiros do rei se reuniram e viram que o fogo não tivera poder algum sobre o corpo desses homens: nem o cabelo da sua cabeça fora queimado, nem as suas roupas tinham sido alteradas, nem sequer o cheiro do fogo passara por eles."},
{v:95,t:"Nabucodonosor exclamou: Bendito seja o Deus de Sedrac, Misac e Abdênago, que enviou o seu anjo e livrou os seus servos, que confiaram nele, desobedeceram à ordem do rei e entregaram o próprio corpo, para não servir nem adorar nenhum outro deus além do seu Deus."},
{v:96,t:"Por isso decreto que todo povo, nação ou língua que disser uma blasfêmia contra o Deus de Sedrac, Misac e Abdênago seja cortado em pedaços, e a sua casa, transformada em monturo, pois não há outro deus que possa salvar desta maneira."},
{v:97,t:"Então o rei promoveu Sedrac, Misac e Abdênago na província da Babilônia."},
{v:98,t:"O rei Nabucodonosor, a todos os povos, nações e línguas que habitam em toda a terra: Que a vossa paz seja abundante!",np:1},
{v:99,t:"Aprouve-me dar a conhecer os sinais e as maravilhas que o Deus altíssimo realizou comigo."},
{v:100,l:["Como são grandes os seus sinais,","como são poderosas as suas maravilhas!","O seu reino é um reino eterno,","e o seu domínio, de geração em geração."],np:1}
];
