// =====================================================================
// Daniel — tradução do hebraico e do aramaico; os acréscimos (3,24–90; 13–14),
// do grego (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["daniel"][1] = [
{s:"Os jovens judeus na corte da Babilônia"},
{v:1,t:"No terceiro ano do reinado de Joaquim, rei de Judá, Nabucodonosor, rei da Babilônia, veio a Jerusalém e a sitiou;",n:"Por volta de 606 antes de Cristo; a data não coincide com o que se sabe pelos outros livros (compare 2 Reis 24,1; Jeremias 25,1). O livro de Daniel, composto no tempo da perseguição de Antíoco IV Epífanes (167–164 antes de Cristo), usa a história do exílio como moldura do seu ensinamento."},
{v:2,t:"e o Senhor entregou nas suas mãos Joaquim, rei de Judá, e parte dos utensílios da casa de Deus; ele os levou para a terra de Senaar, para o templo dos seus deuses, e colocou os utensílios no tesouro dos seus deuses."},
{v:3,t:"O rei disse a Asfanaz, chefe dos seus eunucos, que trouxesse alguns dos filhos de Israel, de linhagem real e de famílias nobres,",np:1},
{v:4,t:"jovens sem nenhum defeito, de boa aparência, instruídos em toda a sabedoria, cultos e inteligentes, capazes de servir no palácio do rei, e que lhes ensinasse a literatura e a língua dos caldeus."},
{v:5,t:"O rei lhes destinou uma ração diária das iguarias da sua mesa e do vinho que ele mesmo bebia; deviam ser educados durante três anos e, depois, servir diante do rei."},
{v:6,t:"Entre eles estavam, dos filhos de Judá, Daniel, Ananias, Misael e Azarias."},
{v:7,t:"O chefe dos eunucos lhes deu outros nomes: a Daniel, Baltassar; a Ananias, Sedrac; a Misael, Misac; e a Azarias, Abdênago."},
{s:"A fidelidade de Daniel e dos companheiros"},
{v:8,t:"Daniel decidiu no seu coração não se contaminar com as iguarias da mesa do rei nem com o vinho que ele bebia, e pediu ao chefe dos eunucos que lhe permitisse não se contaminar.",n:"Os alimentos do rei não seguiam as leis de pureza (Levítico 11) e podiam ter sido oferecidos aos ídolos."},
{v:9,t:"Deus concedeu a Daniel encontrar favor e simpatia diante do chefe dos eunucos;"},
{v:10,t:"mas o chefe dos eunucos disse a Daniel: Tenho medo do meu senhor, o rei, que determinou a vossa comida e a vossa bebida; se ele vir os vossos rostos mais abatidos que os dos outros jovens da vossa idade, poreis em perigo a minha cabeça diante do rei."},
{v:11,t:"Daniel disse então ao guarda que o chefe dos eunucos tinha posto sobre Daniel, Ananias, Misael e Azarias:"},
{v:12,t:"Põe à prova os teus servos, por favor, durante dez dias: que nos deem legumes para comer e água para beber;"},
{v:13,t:"depois compara os nossos rostos com os dos jovens que comem as iguarias do rei, e faze com os teus servos conforme o que vires."},
{v:14,t:"Ele aceitou a proposta e os pôs à prova durante dez dias.",np:1},
{v:15,t:"Ao fim dos dez dias, tinham melhor aparência e estavam mais robustos que todos os jovens que comiam as iguarias do rei."},
{v:16,t:"Desde então, o guarda retirava as iguarias e o vinho que deviam beber e lhes dava legumes.",np:1},
{v:17,t:"A estes quatro jovens Deus deu conhecimento e compreensão de toda a literatura e sabedoria; e Daniel entendia toda espécie de visões e de sonhos.",np:1},
{v:18,t:"Ao fim do tempo que o rei tinha marcado para que fossem apresentados, o chefe dos eunucos os levou à presença de Nabucodonosor."},
{v:19,t:"O rei conversou com eles, e entre todos não se encontrou ninguém como Daniel, Ananias, Misael e Azarias; e ficaram ao serviço do rei."},
{v:20,t:"Em todas as questões de sabedoria e de inteligência sobre as quais o rei os interrogou, achou-os dez vezes superiores a todos os magos e adivinhos que havia em todo o seu reino."},
{v:21,t:"E Daniel ficou ali até o primeiro ano do rei Ciro.",n:"Em 539 antes de Cristo, quando Ciro tomou a Babilônia."}
];

window.TEXTOS_SEED["daniel"][2] = [
{s:"O sonho de Nabucodonosor"},
{v:1,t:"No segundo ano do reinado de Nabucodonosor, Nabucodonosor teve um sonho; o seu espírito ficou perturbado, e o sono fugiu dele."},
{v:2,t:"O rei mandou chamar os magos, os adivinhos, os feiticeiros e os caldeus, para que lhe explicassem os seus sonhos; eles vieram e se apresentaram diante do rei.",n:"Caldeus: aqui, a casta dos sábios e astrólogos da Babilônia."},
{v:3,t:"O rei lhes disse: Tive um sonho, e o meu espírito está perturbado, querendo compreender o sonho."},
{v:4,t:"Os caldeus responderam ao rei, em aramaico: Ó rei, vive para sempre! Conta o sonho aos teus servos, e nós te daremos a interpretação.",n:"A partir daqui, até o fim do capítulo 7, o texto original está em aramaico."},
{v:5,t:"O rei respondeu aos caldeus: A decisão já saiu da minha boca: se não me fizerdes conhecer o sonho e a sua interpretação, sereis cortados em pedaços, e as vossas casas serão transformadas em monturo;"},
{v:6,t:"mas, se me contardes o sonho e a sua interpretação, recebereis de mim presentes, recompensas e grandes honras. Contai-me, pois, o sonho e a sua interpretação."},
{v:7,t:"Eles responderam pela segunda vez: Que o rei conte o sonho aos seus servos, e nós lhe daremos a interpretação.",np:1},
{v:8,t:"O rei respondeu: Vejo bem que quereis ganhar tempo, porque sabeis que a minha decisão está tomada."},
{v:9,t:"Se não me contardes o sonho, uma só sentença vos espera. Combinastes dizer-me palavras mentirosas e enganosas, até que as coisas mudem; por isso contai-me o sonho, e saberei que podeis dar-me a sua interpretação."},
{v:10,t:"Os caldeus responderam ao rei: Não há ninguém na terra que possa fazer o que o rei pede; por isso nenhum rei, por grande e poderoso que seja, jamais pediu tal coisa a nenhum mago, adivinho ou caldeu."},
{v:11,t:"O que o rei pede é difícil, e não há ninguém que o possa revelar ao rei, a não ser os deuses, que não habitam entre os homens."},
{v:12,t:"Ao ouvir isso, o rei se enfureceu e, muito irritado, ordenou que matassem todos os sábios da Babilônia."},
{v:13,t:"Publicado o decreto que mandava matar os sábios, procuraram Daniel e os seus companheiros para matá-los.",np:1},
{s:"Deus revela o mistério a Daniel"},
{v:14,t:"Então Daniel dirigiu-se com prudência e sensatez a Arioc, chefe da guarda do rei, que tinha saído para matar os sábios da Babilônia;"},
{v:15,t:"perguntou a Arioc, a quem o rei tinha dado a ordem, por que razão o rei tinha dado uma sentença tão cruel. Arioc explicou o caso a Daniel,"},
{v:16,t:"e Daniel foi pedir ao rei que lhe desse tempo para revelar ao rei a interpretação."},
{v:17,t:"Daniel foi para casa e contou o caso aos seus companheiros Ananias, Misael e Azarias,"},
{v:18,t:"para que pedissem misericórdia ao Deus do céu a respeito desse mistério, a fim de que Daniel e os seus companheiros não morressem com os outros sábios da Babilônia."},
{v:19,t:"Então o mistério foi revelado a Daniel numa visão noturna, e Daniel bendisse o Deus do céu."},
{v:20,l:["Daniel tomou a palavra e disse:","Bendito seja o nome de Deus","desde sempre e para sempre,","pois a ele pertencem a sabedoria e o poder;"]},
{v:21,l:["ele muda os tempos e as épocas,","depõe reis e estabelece reis,","dá a sabedoria aos sábios","e o conhecimento aos que sabem discernir;"],np:1},
{v:22,l:["ele revela as coisas profundas e ocultas,","conhece o que está nas trevas,","e a luz habita com ele."],np:1},
{v:23,l:["A ti, Deus dos meus pais, dou graças e louvo,","porque me deste a sabedoria e o poder","e agora me fizeste conhecer o que te pedimos,","pois nos revelaste o assunto do rei."],np:1},
{s:"Daniel revela o sonho"},
{v:24,t:"Por isso Daniel foi ter com Arioc, a quem o rei tinha encarregado de matar os sábios da Babilônia, e lhe disse: Não mates os sábios da Babilônia; leva-me à presença do rei, e darei ao rei a interpretação."},
{v:25,t:"Arioc levou depressa Daniel à presença do rei e lhe disse: Encontrei entre os deportados de Judá um homem que dará ao rei a interpretação."},
{v:26,t:"O rei perguntou a Daniel, cujo nome era Baltassar: És tu capaz de me contar o sonho que tive e a sua interpretação?"},
{v:27,t:"Daniel respondeu diante do rei: O mistério que o rei pergunta, nenhum sábio, mago, adivinho ou astrólogo o pode revelar ao rei;"},
{v:28,t:"mas há um Deus no céu que revela os mistérios; ele fez saber ao rei Nabucodonosor o que acontecerá no fim dos tempos. Este é o teu sonho, e estas são as visões que passaram pela tua cabeça, quando estavas deitado:"},
{v:29,t:"Tu, ó rei, estando deitado, pensavas no que aconteceria depois; e aquele que revela os mistérios te fez saber o que vai acontecer."},
{v:30,t:"Quanto a mim, este mistério me foi revelado, não porque eu tenha mais sabedoria do que todos os vivos, mas para que a interpretação fosse dada a conhecer ao rei e tu conhecesses os pensamentos do teu coração."},
{v:31,t:"Tu, ó rei, olhavas, e eis uma grande estátua; essa estátua, enorme e de extraordinário esplendor, estava de pé diante de ti, e o seu aspecto era terrível.",np:1},
{v:32,t:"A cabeça dessa estátua era de ouro fino; o peito e os braços, de prata; o ventre e as coxas, de bronze;"},
{v:33,t:"as pernas, de ferro; os pés, parte de ferro e parte de barro."},
{v:34,t:"Enquanto olhavas, uma pedra se desprendeu, sem intervenção de mão alguma, atingiu a estátua nos pés de ferro e de barro e os despedaçou."},
{v:35,t:"Então o ferro, o barro, o bronze, a prata e o ouro se despedaçaram juntos e ficaram como a palha das eiras no verão: o vento os levou, e não ficou nenhum vestígio deles; mas a pedra que tinha atingido a estátua tornou-se uma grande montanha e encheu toda a terra."},
{s:"A interpretação: os quatro reinos"},
{v:36,t:"Este é o sonho; agora diremos ao rei a sua interpretação."},
{v:37,t:"Tu, ó rei, és o rei dos reis, a quem o Deus do céu deu o reino, o poder, a força e a glória;"},
{v:38,t:"ele entregou nas tuas mãos os filhos dos homens, os animais do campo e as aves do céu, onde quer que habitem, e te fez senhor de todos eles: tu és a cabeça de ouro."},
{v:39,t:"Depois de ti surgirá outro reino, inferior ao teu, e um terceiro reino, de bronze, que dominará toda a terra.",n:"Os reinos são geralmente identificados com a Babilônia, os medos, os persas e os gregos de Alexandre e dos seus sucessores; o reino que não terá fim é o reino de Deus."},
{v:40,t:"O quarto reino será forte como o ferro: assim como o ferro despedaça e esmaga tudo, e como o ferro que tritura, ele despedaçará e triturará todos esses."},
{v:41,t:"Quanto aos pés e aos dedos que viste, parte de barro de oleiro e parte de ferro, será um reino dividido; mas terá algo da solidez do ferro, pois viste o ferro misturado com o barro de argila."},
{v:42,t:"E como os dedos dos pés eram parte de ferro e parte de barro, assim o reino será em parte forte e em parte frágil.",np:1},
{v:43,t:"Quanto ao ferro misturado com o barro de argila, que viste, eles se misturarão por meio de casamentos, mas não se unirão uns aos outros, assim como o ferro não se mistura com o barro."},
{v:44,t:"Nos dias desses reinos, o Deus do céu suscitará um reino que nunca será destruído, e esse reino não passará a outro povo; esmagará e aniquilará todos esses reinos, e ele mesmo permanecerá para sempre;"},
{v:45,t:"foi o que viste: uma pedra se desprendeu da montanha, sem intervenção de mão alguma, e despedaçou o barro, o ferro, o bronze, a prata e o ouro. O grande Deus fez saber ao rei o que vai acontecer depois disso. O sonho é verdadeiro, e a sua interpretação, digna de fé.",n:"Os Padres da Igreja leram na pedra desprendida sem mão humana uma figura de Cristo."},
{s:"Daniel honrado pelo rei"},
{v:46,t:"Então o rei Nabucodonosor caiu com o rosto por terra, prostrou-se diante de Daniel e mandou que lhe oferecessem sacrifícios e incenso."},
{v:47,t:"O rei disse a Daniel: Verdadeiramente o vosso Deus é o Deus dos deuses e o Senhor dos reis, e revela os mistérios, pois tu pudeste revelar este mistério."},
{v:48,t:"Então o rei elevou Daniel a uma alta posição, deu-lhe muitos e grandes presentes e o constituiu governador de toda a província da Babilônia e chefe supremo de todos os sábios da Babilônia."},
{v:49,t:"A pedido de Daniel, o rei pôs Sedrac, Misac e Abdênago à frente da administração da província da Babilônia; Daniel, porém, ficou na corte do rei."}
];

window.TEXTOS_SEED["daniel"][3] = [
{s:"A estátua de ouro"},
{v:1,t:"O rei Nabucodonosor fez uma estátua de ouro de sessenta côvados de altura e seis côvados de largura, e a levantou na planície de Dura, na província da Babilônia.",n:"Cerca de trinta metros de altura."},
{v:2,t:"O rei Nabucodonosor mandou reunir os sátrapas, os magistrados, os juízes, os generais, os governadores, os prefeitos e todas as autoridades das províncias, para que viessem à dedicação da estátua que o rei Nabucodonosor tinha levantado.",np:1},
{v:3,t:"Reuniram-se então os sátrapas, os magistrados, os juízes, os generais, os governadores, os altos funcionários que ocupavam os cargos de poder e todas as autoridades das províncias, para a dedicação da estátua que o rei Nabucodonosor tinha levantado. Estavam de pé diante da estátua que Nabucodonosor tinha levantado,"},
{v:4,t:"e o arauto gritava com força: A vós é dito, povos, nações e línguas:"},
{v:5,t:"no momento em que ouvirdes o som da trombeta, da flauta, da cítara, da sambuca, do saltério, da gaita de foles e de toda espécie de instrumentos musicais, prostrai-vos e adorai a estátua de ouro que o rei Nabucodonosor levantou."},
{v:6,t:"Quem não se prostrar e não a adorar será lançado imediatamente na fornalha de fogo ardente."},
{v:7,t:"Por isso, assim que todos os povos ouviram o som da trombeta, da flauta, da cítara, da sambuca, do saltério, da gaita de foles e de toda espécie de instrumentos musicais, todos os povos, nações e línguas se prostraram e adoraram a estátua de ouro que o rei Nabucodonosor tinha levantado."},
{s:"Os três jovens denunciados"},
{v:8,t:"Naquele mesmo momento, alguns caldeus se aproximaram e acusaram os judeus;"},
{v:9,t:"disseram ao rei Nabucodonosor: Ó rei, vive para sempre!"},
{v:10,t:"Tu, ó rei, deste um decreto: todo homem que ouvir o som da trombeta, da flauta, da cítara, da sambuca, do saltério, da gaita de foles e de toda espécie de instrumentos musicais deve prostrar-se e adorar a estátua de ouro;"},
{v:11,t:"e quem não se prostrar e não a adorar será lançado na fornalha de fogo ardente."},
{v:12,t:"Pois bem, há uns judeus que puseste à frente da administração da província da Babilônia, Sedrac, Misac e Abdênago; esses homens não fazem caso de ti, ó rei: não servem os teus deuses e não adoram a estátua de ouro que levantaste."},
{v:13,t:"Então Nabucodonosor, furioso e irado, mandou trazer Sedrac, Misac e Abdênago; e esses homens foram trazidos à presença do rei.",np:1},
{v:14,t:"Nabucodonosor lhes disse: É verdade, Sedrac, Misac e Abdênago, que não servis os meus deuses e não adorais a estátua de ouro que levantei?"},
{v:15,t:"Estais agora prontos, no momento em que ouvirdes o som da trombeta, da flauta, da cítara, da sambuca, do saltério, da gaita de foles e de toda espécie de instrumentos musicais, a vos prostrar e adorar a estátua que fiz? Se não a adorardes, sereis lançados imediatamente na fornalha de fogo ardente; e qual é o deus que vos livrará das minhas mãos?"},
{v:16,t:"Sedrac, Misac e Abdênago responderam ao rei Nabucodonosor: Não precisamos responder-te sobre isso:",np:1},
{v:17,t:"se o nosso Deus, a quem servimos, pode livrar-nos da fornalha de fogo ardente, ele nos livrará também das tuas mãos, ó rei."},
{v:18,t:"E, ainda que não o faça, fica sabendo, ó rei, que não serviremos os teus deuses nem adoraremos a estátua de ouro que levantaste.",np:1},
{s:"Na fornalha ardente"},
{v:19,t:"Então Nabucodonosor se encheu de furor, e o seu rosto se transformou contra Sedrac, Misac e Abdênago; e ordenou que se aquecesse a fornalha sete vezes mais do que de costume;"},
{v:20,t:"e mandou aos homens mais fortes do seu exército que amarrassem Sedrac, Misac e Abdênago e os lançassem na fornalha de fogo ardente."},
{v:21,t:"Imediatamente esses homens foram amarrados, com os seus mantos, as suas túnicas, os seus turbantes e as suas outras roupas, e lançados no meio da fornalha de fogo ardente;"},
{v:22,t:"e, como a ordem do rei era urgente e a fornalha estava extremamente quente, a chama do fogo matou os homens que tinham levado Sedrac, Misac e Abdênago."},
{v:23,t:"E os três homens, Sedrac, Misac e Abdênago, caíram amarrados no meio da fornalha de fogo ardente.",n:"A Nova Vulgata reproduz aqui uma nota de São Jerônimo: O que segue não o encontrei nos volumes hebraicos. Os vv. 24–90 foram conservados em grego, na tradução de Teodocião."},
{s:"A oração de Azarias"},
{v:24,t:"Eles andavam no meio das chamas, louvando a Deus e bendizendo o Senhor."},
{v:25,t:"Azarias, de pé, rezou assim, abrindo a boca no meio do fogo:"},
{v:26,l:["Bendito sejas, Senhor, Deus dos nossos pais,","digno de louvor, e glorioso é o teu nome para sempre,"],np:1},
{v:27,l:["pois és justo em tudo o que nos fizeste;","todas as tuas obras são verdadeiras, retos os teus caminhos,","e verdadeiros todos os teus julgamentos."],np:1},
{v:28,l:["Justos foram os julgamentos que executaste","em tudo o que fizeste cair sobre nós","e sobre Jerusalém, a cidade santa dos nossos pais,","pois com verdade e justiça fizeste vir tudo isso","por causa dos nossos pecados."],np:1},
{v:29,l:["Pecamos, cometemos a iniquidade, afastando-nos de ti,","e erramos em tudo;"],np:1},
{v:30,l:["não escutamos os teus mandamentos,","não os observamos,","nem fizemos o que nos tinhas ordenado","para o nosso bem."],np:1},
{v:31,l:["Tudo o que fizeste cair sobre nós","e tudo o que nos fizeste,","fizeste-o com justo julgamento;"],np:1},
{v:32,l:["entregaste-nos nas mãos dos nossos inimigos,","injustos, perversos e rebeldes,","e de um rei injusto, o pior de toda a terra."],np:1},
{v:33,l:["E agora não podemos abrir a boca;","a vergonha e o opróbrio caíram","sobre os teus servos e sobre os que te adoram."],np:1},
{v:34,l:["Não nos abandones para sempre,","por causa do teu nome,","e não anules a tua aliança;"],np:1},
{v:35,l:["não retires de nós a tua misericórdia,","por amor de Abraão, teu amigo,","de Isaac, teu servo,","e de Israel, teu santo,"],np:1},
{v:36,l:["aos quais prometeste","multiplicar a sua descendência como as estrelas do céu","e como a areia da praia do mar."],np:1},
{v:37,l:["Pois, Senhor,","tornamo-nos menores que todas as nações","e hoje somos humilhados em toda a terra","por causa dos nossos pecados."],np:1},
{v:38,l:["Neste tempo já não temos","príncipe, nem profeta, nem chefe,","nem holocausto, nem sacrifício,","nem oblação, nem incenso,","nem lugar onde oferecer as primícias diante de ti","e encontrar misericórdia."],np:1},
{v:39,l:["Mas, com a alma arrependida e o espírito humilhado, sejamos acolhidos,","como se fosse com holocaustos de carneiros e de touros"],np:1},
{v:40,l:["e com milhares de cordeiros gordos;","assim seja hoje o nosso sacrifício diante de ti,","e leva à perfeição os que te seguem,","pois não serão confundidos os que confiam em ti."],np:1},
{v:41,l:["E agora te seguimos de todo o coração,","te tememos e procuramos a tua face;"],np:1},
{v:42,l:["não nos cubras de vergonha,","mas trata-nos segundo a tua bondade","e segundo a grandeza da tua misericórdia;"],np:1},
{v:43,l:["livra-nos com os teus prodígios","e dá glória ao teu nome, Senhor."],np:1},
{v:44,l:["Sejam confundidos todos os que fazem mal aos teus servos;","sejam cobertos de vergonha, privados de todo o poder,","e seja quebrada a sua força."]},
{v:45,l:["Saibam que tu és o Senhor,","o único Deus, glorioso sobre toda a terra."],np:1},
{s:"O anjo do Senhor na fornalha"},
{v:46,t:"Os servos do rei que os tinham lançado na fornalha não cessavam de alimentar o fogo com nafta, estopa, piche e sarmentos;"},
{v:47,t:"e a chama se elevava por cima da fornalha a quarenta e nove côvados,"},
{v:48,t:"saía e queimava os caldeus que encontrava ao redor da fornalha."},
{v:49,t:"Mas o anjo do Senhor desceu à fornalha junto com Azarias e os seus companheiros, afastou da fornalha a chama do fogo"},
{v:50,t:"e fez soprar no meio da fornalha como que um vento fresco de orvalho; e o fogo não os tocou de modo algum, nem os feriu, nem os molestou."},
{s:"O cântico dos três jovens"},
{v:51,t:"Então os três, como que a uma só voz, louvavam, glorificavam e bendiziam a Deus na fornalha, dizendo:"},
{v:52,l:["Bendito sejas, Senhor, Deus dos nossos pais,","digno de louvor e exaltado para sempre;","bendito o teu nome santo e glorioso,","digno de louvor e exaltado para sempre."],np:1,n:"Este cântico é rezado na Liturgia das Horas, nas Laudes dos domingos e das festas."},
{v:53,l:["Bendito sejas no templo da tua santa glória,","digno de louvor e de glória para sempre."],np:1},
{v:54,l:["Bendito sejas no trono do teu reino,","digno de louvor e exaltado para sempre."],np:1},
{v:55,l:["Bendito sejas tu, que sondas os abismos, sentado sobre os querubins,","digno de louvor e exaltado para sempre."],np:1},
{v:56,l:["Bendito sejas no firmamento do céu,","digno de louvor e de glória para sempre."],np:1},
{v:57,l:["Bendizei o Senhor, todas as obras do Senhor,","louvai-o e exaltai-o para sempre."],np:1},
{v:58,l:["Bendizei o Senhor, céus,","louvai-o e exaltai-o para sempre."],np:1},
{v:59,l:["Bendizei o Senhor, anjos do Senhor,","louvai-o e exaltai-o para sempre."],np:1},
{v:60,l:["Bendizei o Senhor, águas todas que estão acima dos céus,","louvai-o e exaltai-o para sempre."],np:1},
{v:61,l:["Bendizei o Senhor, todos os poderes do céu,","louvai-o e exaltai-o para sempre."],np:1},
{v:62,l:["Bendizei o Senhor, sol e lua,","louvai-o e exaltai-o para sempre."],np:1},
{v:63,l:["Bendizei o Senhor, estrelas do céu,","louvai-o e exaltai-o para sempre."],np:1},
{v:64,l:["Bendizei o Senhor, chuvas e orvalhos,","louvai-o e exaltai-o para sempre."],np:1},
{v:65,l:["Bendizei o Senhor, ventos todos,","louvai-o e exaltai-o para sempre."],np:1},
{v:66,l:["Bendizei o Senhor, fogo e calor,","louvai-o e exaltai-o para sempre."],np:1},
{v:67,l:["Bendizei o Senhor, frio e ardor,","louvai-o e exaltai-o para sempre."],np:1},
{v:68,l:["Bendizei o Senhor, orvalhos e geadas,","louvai-o e exaltai-o para sempre."],np:1},
{v:69,l:["Bendizei o Senhor, gelo e frio,","louvai-o e exaltai-o para sempre."],np:1},
{v:70,l:["Bendizei o Senhor, gelos e neves,","louvai-o e exaltai-o para sempre."],np:1},
{v:71,l:["Bendizei o Senhor, noites e dias,","louvai-o e exaltai-o para sempre."],np:1},
{v:72,l:["Bendizei o Senhor, luz e trevas,","louvai-o e exaltai-o para sempre."],np:1},
{v:73,l:["Bendizei o Senhor, relâmpagos e nuvens,","louvai-o e exaltai-o para sempre."],np:1},
{v:74,l:["Bendiga a terra o Senhor,","louve-o e exalte-o para sempre."],np:1},
{v:75,l:["Bendizei o Senhor, montes e colinas,","louvai-o e exaltai-o para sempre."],np:1},
{v:76,l:["Bendizei o Senhor, plantas todas que brotais da terra,","louvai-o e exaltai-o para sempre."],np:1},
{v:77,l:["Bendizei o Senhor, mares e rios,","louvai-o e exaltai-o para sempre."],np:1},
{v:78,l:["Bendizei o Senhor, fontes,","louvai-o e exaltai-o para sempre."],np:1},
{v:79,l:["Bendizei o Senhor, monstros marinhos e tudo o que se move nas águas,","louvai-o e exaltai-o para sempre."],np:1},
{v:80,l:["Bendizei o Senhor, aves todas do céu,","louvai-o e exaltai-o para sempre."],np:1},
{v:81,l:["Bendizei o Senhor, feras e rebanhos,","louvai-o e exaltai-o para sempre."],np:1},
{v:82,l:["Bendizei o Senhor, filhos dos homens,","louvai-o e exaltai-o para sempre."],np:1},
{v:83,l:["Bendize o Senhor, Israel,","louvai-o e exaltai-o para sempre."],np:1},
{v:84,l:["Bendizei o Senhor, sacerdotes do Senhor,","louvai-o e exaltai-o para sempre."],np:1},
{v:85,l:["Bendizei o Senhor, servos do Senhor,","louvai-o e exaltai-o para sempre."],np:1},
{v:86,l:["Bendizei o Senhor, espíritos e almas dos justos,","louvai-o e exaltai-o para sempre."],np:1},
{v:87,l:["Bendizei o Senhor, santos e humildes de coração,","louvai-o e exaltai-o para sempre."],np:1},
{v:88,l:["Bendizei o Senhor, Ananias, Azarias e Misael,","louvai-o e exaltai-o para sempre;","pois ele nos arrancou da morada dos mortos e nos salvou da mão da morte,","nos livrou do meio da fornalha de chamas ardentes","e nos arrancou do meio do fogo."],np:1},
{v:89,l:["Dai graças ao Senhor, porque ele é bom,","porque o seu amor é para sempre."],np:1},
{v:90,l:["Bendizei o Deus dos deuses, todos vós que temeis o Senhor;","louvai-o e dai-lhe graças, porque o seu amor é para sempre."],np:1,n:"A Nova Vulgata reproduz aqui outra nota de São Jerônimo: Até aqui, o texto não se encontra no hebraico; o que pusemos foi traduzido da edição de Teodocião."},
{s:"Nabucodonosor reconhece o Deus altíssimo"},
{v:91,t:"Então o rei Nabucodonosor, espantado, levantou-se às pressas e perguntou aos seus conselheiros: Não foram três homens amarrados que lançamos no meio do fogo? Eles responderam ao rei: Certamente, ó rei.",n:"Os vv. 91–100 correspondem a 3,24–33 do texto aramaico (em outras Bíblias, 3,24–30 e 4,1–3)."},
{v:92,t:"Ele disse: Mas eu vejo quatro homens soltos, andando no meio do fogo, sem sofrer dano algum, e o aspecto do quarto é semelhante a um filho dos deuses.",n:"Um filho dos deuses: um ser divino, um anjo (v. 95)."},
{v:93,t:"Nabucodonosor aproximou-se da boca da fornalha de fogo ardente e disse: Sedrac, Misac e Abdênago, servos do Deus altíssimo, saí e vinde! Então Sedrac, Misac e Abdênago saíram do meio do fogo."},
{v:94,t:"Os sátrapas, os magistrados, os juízes e os conselheiros do rei se reuniram e viram que o fogo não tivera poder algum sobre o corpo desses homens: nem o cabelo da sua cabeça fora queimado, nem as suas roupas tinham sido alteradas, nem sequer o cheiro do fogo passara por eles."},
{v:95,t:"Nabucodonosor exclamou: Bendito seja o Deus de Sedrac, Misac e Abdênago, que enviou o seu anjo e livrou os seus servos, que confiaram nele, desobedeceram à ordem do rei e entregaram o próprio corpo, para não servir nem adorar nenhum outro deus além do seu Deus."},
{v:96,t:"Por isso decreto que todo povo, nação ou língua que disser uma blasfêmia contra o Deus de Sedrac, Misac e Abdênago seja cortado em pedaços, e a sua casa, transformada em monturo, pois não há outro deus que possa salvar desta maneira."},
{v:97,t:"Então o rei promoveu Sedrac, Misac e Abdênago na província da Babilônia."},
{v:98,t:"O rei Nabucodonosor, a todos os povos, nações e línguas que habitam em toda a terra: Que a vossa paz seja abundante!",np:1},
{v:99,t:"Aprouve-me dar a conhecer os sinais e as maravilhas que o Deus altíssimo realizou comigo."},
{v:100,l:["Como são grandes os seus sinais,","como são poderosas as suas maravilhas!","O seu reino é um reino eterno,","e o seu domínio, de geração em geração."],np:1}
];

window.TEXTOS_SEED["daniel"][4] = [
{s:"O sonho da grande árvore"},
{v:1,t:"Eu, Nabucodonosor, vivia tranquilo em minha casa e próspero no meu palácio;",n:"Em outras Bíblias, 4,1–34 é numerado 4,4–37."},
{v:2,t:"tive um sonho que me aterrorizou; os pensamentos que tive na cama e as visões que passaram pela minha cabeça me perturbaram."},
{v:3,t:"Dei ordem para que trouxessem à minha presença todos os sábios da Babilônia, para que me dessem a interpretação do sonho."},
{v:4,t:"Vieram então os magos, os adivinhos, os caldeus e os astrólogos; contei-lhes o sonho, mas não me deram a sua interpretação;"},
{v:5,t:"até que, por fim, apresentou-se diante de mim Daniel, cujo nome é Baltassar, segundo o nome do meu deus, e em quem está o espírito dos deuses santos; e eu lhe contei o sonho:",n:"Baltassar: nome babilônico que o autor relaciona com Bel, o deus de Nabucodonosor."},
{v:6,t:"Baltassar, chefe dos magos, sei que o espírito dos deuses santos está em ti e que nenhum mistério te é difícil; eis as visões do sonho que tive: dá-me a sua interpretação."},
{v:7,l:["Estas foram as visões que passaram pela minha cabeça quando estava deitado:","Eu olhava, e eis uma árvore no meio da terra,","de altura imensa."]},
{v:8,l:["A árvore cresceu e se tornou forte,","a sua altura chegava até o céu,","e era vista até os confins de toda a terra."],np:1},
{v:9,l:["A sua folhagem era belíssima,","o seu fruto, abundante,","e nela havia alimento para todos.","Debaixo dela se abrigavam os animais do campo,","nos seus ramos moravam as aves do céu,","e dela se alimentava todo ser vivo."],np:1},
{v:10,l:["Eu olhava, nas visões que passavam pela minha cabeça quando estava deitado,","e eis que um vigilante, um santo, desceu do céu."],np:1,n:"Vigilante: nome dado aos anjos (compare vv. 14.20)."},
{v:11,l:["Ele gritou com força e disse:","Derrubai a árvore e cortai os seus ramos,","arrancai as suas folhas e espalhai os seus frutos;","fujam os animais de debaixo dela","e as aves dos seus ramos."],np:1},
{v:12,l:["Mas deixai na terra o toco das suas raízes,","preso com correntes de ferro e de bronze, entre a erva do campo;","seja molhado pelo orvalho do céu","e tenha a sua parte com os animais, na erva da terra."],np:1},
{v:13,l:["Seja mudado o seu coração de homem","e lhe seja dado um coração de animal,","e passem sobre ele sete tempos."],np:1,n:"Sete tempos: talvez sete anos."},
{v:14,l:["Esta é a sentença decretada pelos vigilantes,","a decisão pedida pela palavra dos santos,","para que os vivos saibam","que o Altíssimo domina sobre o reino dos homens,","e o dá a quem quer,","e põe sobre ele o mais humilde dos homens."],np:1},
{v:15,t:"Este é o sonho que eu, o rei Nabucodonosor, tive. Tu, Baltassar, dá-me a sua interpretação, pois todos os sábios do meu reino não puderam dar-me a interpretação; mas tu podes, porque o espírito dos deuses santos está em ti.",np:1},
{s:"Daniel interpreta o sonho"},
{v:16,t:"Então Daniel, cujo nome é Baltassar, ficou por um momento atônito, e os seus pensamentos o perturbavam. O rei lhe disse: Baltassar, que o sonho e a sua interpretação não te perturbem. Baltassar respondeu: Meu senhor, que o sonho seja para os que te odeiam, e a sua interpretação, para os teus inimigos!"},
{v:17,t:"A árvore que viste, alta e forte, cuja altura chegava até o céu e que era vista por toda a terra,"},
{v:18,t:"de folhagem belíssima e fruto abundante, na qual havia alimento para todos, debaixo da qual se abrigavam os animais do campo e em cujos ramos moravam as aves do céu,"},
{v:19,t:"és tu, ó rei, que te tornaste grande e forte: a tua grandeza cresceu e chegou até o céu, e o teu domínio, até os confins da terra."},
{v:20,t:"Quanto ao que o rei viu, um vigilante, um santo, descendo do céu e dizendo: Derrubai a árvore e destruí-a; mas deixai na terra o toco das suas raízes, preso com correntes de ferro e de bronze, entre a erva do campo; seja molhado pelo orvalho do céu e tenha a sua parte com os animais, até que passem sobre ele sete tempos,"},
{v:21,t:"esta é a interpretação, ó rei, e esta é a sentença do Altíssimo que caiu sobre o rei, meu senhor:"},
{v:22,t:"serás expulso do meio dos homens, e a tua morada será com os animais do campo; comerás erva como os bois e serás molhado pelo orvalho do céu; passarão sobre ti sete tempos, até que reconheças que o Altíssimo domina sobre o reino dos homens e o dá a quem quer."},
{v:23,t:"E a ordem de deixar o toco das raízes da árvore significa que o teu reino te será conservado, depois que tiveres reconhecido o poder do céu."},
{v:24,t:"Por isso, ó rei, aceita o meu conselho: resgata os teus pecados com esmolas e as tuas iniquidades com a misericórdia para com os pobres; assim se prolongará a tua prosperidade.",np:1},
{s:"O sonho se cumpre"},
{v:25,t:"Tudo isso aconteceu ao rei Nabucodonosor."},
{v:26,t:"Doze meses depois, passeando no palácio real da Babilônia,"},
{v:27,t:"o rei tomou a palavra e disse: Não é esta a grande Babilônia que eu construí como residência real, com a força do meu poder e para a glória da minha majestade?"},
{v:28,t:"Estas palavras ainda estavam na boca do rei, quando caiu do céu uma voz: A ti se diz, rei Nabucodonosor: O reino te foi tirado;"},
{v:29,t:"serás expulso do meio dos homens, e a tua morada será com os animais do campo; comerás erva como os bois, e passarão sobre ti sete tempos, até que reconheças que o Altíssimo domina sobre o reino dos homens e o dá a quem quer."},
{v:30,t:"Naquele mesmo instante a palavra se cumpriu em Nabucodonosor: foi expulso do meio dos homens, comeu erva como os bois, e o seu corpo foi molhado pelo orvalho do céu, até que o seu cabelo cresceu como as penas da águia, e as suas unhas, como as garras das aves."},
{v:31,l:["Terminado aquele tempo, eu, Nabucodonosor, levantei os olhos para o céu, e a razão me voltou; bendisse o Altíssimo, louvei e glorifiquei aquele que vive eternamente,","porque o seu domínio é um domínio eterno,","e o seu reino, de geração em geração;"],np:1},
{v:32,l:["todos os habitantes da terra são como nada diante dele:","ele faz o que quer","tanto com o exército do céu como com os habitantes da terra,","e não há quem possa deter a sua mão","e dizer-lhe: Que fazes?"],np:1},
{v:33,t:"Naquele mesmo tempo a razão me voltou, e, para a glória do meu reino, voltaram-me a majestade e o esplendor; os meus conselheiros e os meus magistrados vieram me procurar, fui restabelecido no meu reino, e foi-me acrescentada ainda maior grandeza.",np:1},
{v:34,t:"Agora, pois, eu, Nabucodonosor, louvo, exalto e glorifico o Rei do céu, porque todas as suas obras são verdade, e os seus caminhos, justiça; e ele pode humilhar os que andam com soberba."}
];

window.TEXTOS_SEED["daniel"][5] = [
{s:"O banquete de Baltasar"},
{v:1,t:"O rei Baltasar deu um grande banquete aos seus mil nobres e bebia vinho diante deles.",n:"Baltasar (Belsazar), filho de Nabonido, governou a Babilônia em nome do pai; o livro o chama filho de Nabucodonosor no sentido de sucessor. Não confundir com Baltassar, o nome babilônico de Daniel."},
{v:2,t:"Já embriagado, Baltasar mandou trazer os vasos de ouro e de prata que Nabucodonosor, seu pai, tinha levado do templo de Jerusalém, para que bebessem neles o rei e os seus nobres, as suas mulheres e as suas concubinas."},
{v:3,t:"Trouxeram então os vasos de ouro que tinham sido levados do templo de Jerusalém, e beberam neles o rei e os seus nobres, as suas mulheres e as suas concubinas:"},
{v:4,t:"bebiam vinho e louvavam os seus deuses de ouro e de prata, de bronze, de ferro, de madeira e de pedra."},
{v:5,t:"Naquele mesmo instante apareceram dedos de mão humana, que escreviam, diante do candelabro, sobre o reboco da parede do palácio real; e o rei via a mão que escrevia.",np:1},
{v:6,t:"Então o rosto do rei mudou de cor, os seus pensamentos o perturbaram, as articulações dos seus rins se afrouxaram, e os seus joelhos batiam um no outro."},
{v:7,t:"O rei gritou com força que trouxessem os magos, os caldeus e os astrólogos; e disse aos sábios da Babilônia: Quem ler esta escrita e me der a sua interpretação será vestido de púrpura, terá um colar de ouro no pescoço e será o terceiro no governo do meu reino."},
{v:8,t:"Entraram então todos os sábios do rei, mas não puderam ler a escrita nem dar ao rei a sua interpretação;"},
{v:9,t:"por isso o rei Baltasar ficou muito perturbado, o seu rosto mudou de cor, e os seus nobres ficaram consternados."},
{v:10,t:"A rainha, por causa das palavras do rei e dos seus nobres, entrou na sala do banquete e disse: Ó rei, vive para sempre! Não te perturbem os teus pensamentos, e não mude de cor o teu rosto.",n:"A rainha: provavelmente a rainha-mãe."},
{v:11,t:"Há no teu reino um homem em quem está o espírito dos deuses santos; no tempo do teu pai, encontraram-se nele conhecimento, inteligência e sabedoria como a sabedoria dos deuses; e o rei Nabucodonosor, teu pai, o nomeou chefe dos magos, dos encantadores, dos caldeus e dos astrólogos; sim, o teu pai, ó rei,"},
{v:12,t:"porque se encontrou nele, em Daniel, a quem o rei deu o nome de Baltassar, um espírito extraordinário, conhecimento e inteligência para interpretar sonhos, explicar enigmas e resolver problemas. Chame-se, pois, Daniel, e ele dará a interpretação."},
{s:"Daniel lê a escrita"},
{v:13,t:"Daniel foi levado à presença do rei, e o rei lhe disse: És tu Daniel, um dos deportados de Judá, que o rei, meu pai, trouxe de Judá?"},
{v:14,t:"Ouvi dizer de ti que tens o espírito dos deuses e que se encontraram em ti conhecimento, inteligência e sabedoria extraordinários."},
{v:15,t:"Os sábios e os magos foram trazidos à minha presença para ler esta escrita e dar-me a sua interpretação, mas não puderam explicar o sentido destas palavras."},
{v:16,t:"Ouvi dizer de ti que podes dar interpretações e resolver problemas; se puderes, pois, ler esta escrita e dar-me a sua interpretação, serás vestido de púrpura, terás um colar de ouro no pescoço e serás o terceiro no governo do meu reino."},
{v:17,t:"Daniel respondeu diante do rei: Fica com os teus presentes e dá as tuas recompensas a outro; contudo lerei ao rei a escrita e lhe darei a sua interpretação.",np:1},
{v:18,t:"Ó rei, o Deus altíssimo deu a Nabucodonosor, teu pai, o reino, a grandeza, a glória e a honra."},
{v:19,t:"Por causa da grandeza que lhe deu, todos os povos, nações e línguas tremiam e tinham medo dele: matava a quem queria, deixava viver a quem queria, exaltava a quem queria e humilhava a quem queria.",n:"Deixava viver: assim o aramaico; a Nova Vulgata entende: feria."},
{v:20,t:"Mas, quando o seu coração se exaltou e o seu espírito se endureceu na soberba, foi deposto do seu trono real, e a sua glória lhe foi tirada;"},
{v:21,t:"foi expulso do meio dos filhos dos homens, o seu coração se tornou semelhante ao dos animais, e a sua morada foi com os jumentos selvagens; comia erva como os bois, e o seu corpo foi molhado pelo orvalho do céu, até que reconheceu que o Deus altíssimo domina sobre o reino dos homens e põe sobre ele a quem quer."},
{v:22,t:"E tu, Baltasar, seu filho, não humilhaste o teu coração, embora soubesses tudo isso,"},
{v:23,t:"mas te levantaste contra o Senhor do céu: trouxeram diante de ti os vasos da sua casa, e tu, os teus nobres, as tuas mulheres e as tuas concubinas bebestes vinho neles; louvaste os deuses de prata e de ouro, de bronze, de ferro, de madeira e de pedra, que não veem, nem ouvem, nem entendem; mas não glorificaste o Deus que tem na mão o teu sopro de vida e todos os teus caminhos."},
{v:24,t:"Por isso ele enviou a mão que traçou esta escrita."},
{v:25,t:"Esta é a escrita que foi traçada: Mané, Técel, Ufarsin.",n:"Mané, Técel, Parsin: nomes de pesos ou moedas (mina, siclo e meia-mina); Daniel os lê como verbos: contado, pesado, dividido. Parsin evoca também os persas."},
{v:26,t:"E esta é a interpretação das palavras: Mané: Deus contou os dias do teu reino e lhe pôs fim;"},
{v:27,t:"Técel: foste pesado na balança e achado em falta;"},
{v:28,t:"Farés: o teu reino foi dividido e entregue aos medos e aos persas."},
{v:29,t:"Então, por ordem de Baltasar, Daniel foi vestido de púrpura, puseram-lhe no pescoço um colar de ouro, e proclamou-se que ele seria o terceiro no governo do reino."},
{v:30,t:"Naquela mesma noite, Baltasar, rei dos caldeus, foi morto.",np:1,n:"A Babilônia caiu diante de Ciro em outubro de 539 antes de Cristo."}
];

window.TEXTOS_SEED["daniel"][6] = [
{s:"Daniel na cova dos leões"},
{v:1,t:"E Dario, o medo, recebeu o reino, com a idade de sessenta e dois anos.",n:"Em outras Bíblias, este versículo é 5,31, e a numeração do capítulo 6 diminui de uma unidade. Dario, o medo, não é conhecido pela história; o autor talvez pense em Ciro ou em Dario I, rei da Pérsia."},
{v:2,t:"Pareceu bem a Dario estabelecer sobre o reino cento e vinte sátrapas, distribuídos por todo o reino,"},
{v:3,t:"e acima deles três ministros, dos quais Daniel era um, aos quais os sátrapas deviam prestar contas, para que o rei não sofresse prejuízo."},
{v:4,t:"Daniel se distinguia entre todos os ministros e sátrapas, porque nele havia um espírito extraordinário; e o rei pensava em colocá-lo sobre todo o reino."},
{v:5,t:"Por isso os ministros e os sátrapas procuravam encontrar um motivo de acusação contra Daniel na administração do reino; mas não conseguiram encontrar nenhum motivo nem nenhuma falta, porque ele era fiel, e não se encontrava nele nenhuma negligência nem falta."},
{v:6,t:"Aqueles homens disseram então: Não encontraremos nenhum motivo de acusação contra este Daniel, a não ser que o encontremos na lei do seu Deus."},
{v:7,t:"Então esses ministros e sátrapas foram depressa ao rei e lhe disseram: Rei Dario, vive para sempre!"},
{v:8,t:"Todos os ministros do reino, os magistrados e os sátrapas, os conselheiros e os governadores concordaram em que o rei publique um decreto e confirme uma proibição: todo aquele que, durante trinta dias, dirigir um pedido a qualquer deus ou homem, a não ser a ti, ó rei, será lançado na cova dos leões.",np:1},
{v:9,t:"Agora, pois, ó rei, confirma a proibição e assina o decreto, para que não possa ser mudado, segundo a lei dos medos e dos persas, que não pode ser revogada."},
{v:10,t:"O rei Dario assinou o decreto e a proibição."},
{v:11,t:"Quando Daniel soube que o decreto tinha sido assinado, entrou em sua casa; e, com as janelas do seu quarto de cima abertas na direção de Jerusalém, três vezes por dia se ajoelhava, rezava e louvava o seu Deus, como costumava fazer antes.",np:1},
{v:12,t:"Aqueles homens foram depressa e encontraram Daniel rezando e suplicando ao seu Deus."},
{v:13,t:"Então se apresentaram ao rei e lhe falaram da proibição: Ó rei, não assinaste um decreto segundo o qual todo aquele que, durante trinta dias, dirigisse um pedido a qualquer deus ou homem, a não ser a ti, ó rei, seria lançado na cova dos leões? O rei respondeu: A coisa está decidida, segundo a lei dos medos e dos persas, que não pode ser revogada."},
{v:14,t:"Eles disseram então ao rei: Daniel, um dos deportados de Judá, não faz caso de ti, ó rei, nem da proibição que assinaste, mas três vezes por dia faz a sua oração."},
{v:15,t:"Ao ouvir isso, o rei ficou muito aflito; decidiu salvar Daniel e, até o pôr do sol, esforçou-se para livrá-lo."},
{v:16,t:"Mas aqueles homens foram ao rei e lhe disseram: Sabe, ó rei, que é lei dos medos e dos persas que nenhum decreto ou proibição estabelecido pelo rei pode ser mudado."},
{v:17,t:"Então o rei deu a ordem, e trouxeram Daniel e o lançaram na cova dos leões. O rei disse a Daniel: O teu Deus, a quem serves sem cessar, ele te livrará.",np:1},
{v:18,t:"Trouxeram uma pedra e a puseram sobre a boca da cova; o rei a selou com o seu anel e com o anel dos seus nobres, para que nada se mudasse a respeito de Daniel."},
{v:19,t:"O rei voltou ao seu palácio e se deitou sem cear; não lhe trouxeram nenhuma comida, e o sono fugiu dele.",np:1},
{v:20,t:"Ao amanhecer, bem cedo, o rei se levantou e foi depressa à cova dos leões;"},
{v:21,t:"aproximando-se da cova, chamou Daniel com voz aflita e lhe disse: Daniel, servo do Deus vivo, o teu Deus, a quem serves sem cessar, pôde livrar-te dos leões?"},
{v:22,t:"Daniel respondeu ao rei: Ó rei, vive para sempre!"},
{v:23,t:"O meu Deus enviou o seu anjo, que fechou a boca dos leões, e eles não me fizeram mal, porque fui achado inocente diante dele; e também diante de ti, ó rei, não cometi nenhum crime.",np:1},
{v:24,t:"Então o rei se alegrou muito e mandou tirar Daniel da cova; Daniel foi tirado da cova, e não se encontrou nele nenhuma ferida, porque tinha confiado no seu Deus."},
{v:25,t:"Por ordem do rei, trouxeram os homens que tinham acusado Daniel e os lançaram na cova dos leões, eles, os seus filhos e as suas mulheres; e ainda não tinham chegado ao fundo da cova quando os leões se apoderaram deles e lhes quebraram todos os ossos.",n:"Nota do tradutor: o castigo coletivo reflete os costumes da época; o texto não foi suavizado."},
{s:"O decreto de Dario"},
{v:26,t:"Então o rei Dario escreveu a todos os povos, nações e línguas que habitam em toda a terra: Que a vossa paz seja abundante!"},
{v:27,l:["Decreto que, em todo o domínio do meu reino, se tema e se respeite o Deus de Daniel:","pois ele é o Deus vivo,","que permanece para sempre;","o seu reino não será destruído,","e o seu domínio durará até o fim."]},
{v:28,l:["Ele salva e liberta,","realiza sinais e prodígios","no céu e na terra;","ele livrou Daniel","do poder dos leões."],np:1},
{v:29,t:"E Daniel prosperou durante o reinado de Dario e o reinado de Ciro, o persa.",np:1}
];

window.TEXTOS_SEED["daniel"][7] = [
{s:"As quatro feras"},
{v:1,t:"No primeiro ano de Baltasar, rei da Babilônia, Daniel teve um sonho e visões que passaram pela sua cabeça, quando estava deitado; então escreveu o sonho. Eis o começo do relato:"},
{v:2,t:"Daniel tomou a palavra e disse: Eu olhava, na minha visão noturna, e eis que os quatro ventos do céu agitavam o mar Grande,"},
{v:3,t:"e quatro grandes feras, diferentes umas das outras, subiam do mar."},
{v:4,t:"A primeira era como uma leoa e tinha asas de águia; eu olhava, até que lhe arrancaram as asas; ela foi levantada da terra e posta de pé como um homem, e lhe foi dado um coração de homem."},
{v:5,t:"E eis outra fera, a segunda, semelhante a um urso; estava erguida de um lado e tinha três costelas na boca, entre os dentes; e lhe diziam: Levanta-te, devora muita carne."},
{v:6,t:"Depois disso eu olhava, e eis outra fera, semelhante a um leopardo, com quatro asas de ave nas costas; a fera tinha quatro cabeças, e lhe foi dado o domínio."},
{v:7,t:"Depois disso eu olhava, nas visões da noite, e eis uma quarta fera, terrível, espantosa e extraordinariamente forte; tinha grandes dentes de ferro, devorava, triturava e pisava com os pés o que restava; era diferente de todas as feras que eu tinha visto antes dela e tinha dez chifres.",np:1},
{v:8,t:"Eu observava os chifres, e eis que outro chifre, pequeno, surgiu no meio deles, e três dos primeiros chifres foram arrancados diante dele; e eis que esse chifre tinha olhos como olhos de homem e uma boca que dizia coisas arrogantes.",n:"O pequeno chifre: Antíoco IV Epífanes, rei selêucida que perseguiu os judeus (167–164 antes de Cristo)."},
{s:"O Ancião dos dias e o Filho do homem"},
{v:9,l:["Eu olhava,","até que foram postos tronos,","e um Ancião dos dias se sentou.","A sua veste era branca como a neve,","e os cabelos da sua cabeça, como lã pura;","o seu trono eram chamas de fogo,","e as suas rodas, fogo ardente."]},
{v:10,l:["Um rio de fogo corria","e saía diante dele;","milhares de milhares o serviam,","e miríades de miríades estavam de pé diante dele:","o tribunal se assentou,","e os livros foram abertos."],np:1},
{v:11,t:"Eu olhava então, por causa do ruído das palavras arrogantes que o chifre dizia; e vi que a fera foi morta, o seu corpo destruído e entregue ao fogo para ser queimado;",np:1},
{v:12,t:"também às outras feras foi tirado o domínio, mas lhes foi concedido prolongar a vida até um tempo determinado."},
{v:13,l:["Eu olhava, nas visões da noite,","e eis que, com as nuvens do céu,","vinha um como Filho de homem;","chegou até o Ancião dos dias","e foi levado à sua presença;"],np:1,n:"Um como Filho de homem: uma figura humana, em contraste com as feras; representa o povo dos santos do Altíssimo (vv. 18.27). Jesus tomou para si este título (Marcos 14,62)."},
{v:14,l:["e lhe foram dados o domínio, a glória e o reino;","todos os povos, nações e línguas","o serviram:","o seu domínio é um domínio eterno,","que não passará,","e o seu reino jamais será destruído."],np:1},
{s:"A interpretação da visão"},
{v:15,t:"O meu espírito estremeceu; eu, Daniel, fiquei aterrado com isso, e as visões que passaram pela minha cabeça me perturbaram."},
{v:16,t:"Aproximei-me de um dos que estavam ali de pé e lhe perguntei o que significava tudo aquilo; ele me respondeu e me deu a interpretação das coisas:"},
{v:17,t:"Estas quatro grandes feras são quatro reinos que surgirão da terra;"},
{v:18,t:"mas os santos do Altíssimo receberão o reino e o possuirão para sempre, pelos séculos dos séculos."},
{v:19,t:"Depois quis saber com exatidão o que significava a quarta fera, que era tão diferente de todas as outras, extremamente terrível, com dentes de ferro e garras de bronze, que devorava, triturava e pisava com os pés o que restava,",np:1},
{v:20,t:"e os dez chifres que tinha na cabeça, e o outro chifre que tinha surgido, diante do qual tinham caído três chifres, o chifre que tinha olhos e uma boca que dizia coisas arrogantes, e que parecia maior que os outros."},
{v:21,t:"Eu olhava, e eis que esse chifre fazia guerra contra os santos e os vencia,"},
{v:22,t:"até que veio o Ancião dos dias e fez justiça aos santos do Altíssimo; e chegou o tempo em que os santos possuíram o reino."},
{v:23,t:"Ele me disse assim: A quarta fera é um quarto reino, que haverá na terra, maior que todos os reinos; devorará toda a terra, a pisará e a triturará.",np:1},
{v:24,t:"Os dez chifres são dez reis que surgirão desse reino; e outro surgirá depois deles, mais poderoso que os anteriores, e abaterá três reis;",np:1},
{v:25,t:"proferirá palavras contra o Altíssimo, oprimirá os santos do Altíssimo e pensará em mudar os tempos e a lei; e os santos serão entregues nas suas mãos por um tempo, dois tempos e metade de um tempo.",n:"Um tempo, dois tempos e metade de um tempo: três anos e meio, a duração aproximada da perseguição de Antíoco."},
{v:26,t:"Mas o tribunal se assentará, e lhe tirarão o domínio, para que seja destruído e aniquilado para sempre;"},
{v:27,t:"e o reino, o domínio e a grandeza de todos os reinos que há debaixo do céu serão dados ao povo dos santos do Altíssimo, cujo reino é um reino eterno, e todos os soberanos o servirão e lhe obedecerão."},
{v:28,t:"Aqui termina o relato. Eu, Daniel, fiquei muito perturbado com os meus pensamentos, e o meu rosto mudou de cor; mas guardei tudo isso no coração.",n:"Aqui termina a parte do livro escrita em aramaico (2,4–7,28)."}
];

window.TEXTOS_SEED["daniel"][8] = [
{s:"A visão do carneiro e do bode"},
{v:1,t:"No terceiro ano do reinado do rei Baltasar, eu, Daniel, tive uma visão, depois daquela que tinha tido no princípio.",n:"Com este capítulo o livro volta ao hebraico."},
{v:2,t:"Vi na visão — e, enquanto via, eu estava em Susa, a cidadela, na província de Elam —, vi na visão que eu estava junto ao rio Ulai."},
{v:3,t:"Levantei os olhos e olhei: eis um carneiro de pé diante do rio, com dois chifres altos, um mais alto que o outro, e o mais alto cresceu por último."},
{v:4,t:"Vi o carneiro dar chifradas para o ocidente, para o norte e para o sul; nenhum animal podia resistir-lhe nem livrar-se do seu poder; fazia o que queria e se engrandeceu."},
{v:5,t:"Enquanto eu refletia, eis que um bode vinha do ocidente, percorrendo toda a terra sem tocar o chão; e o bode tinha um chifre imponente entre os olhos."},
{v:6,t:"Chegou até o carneiro de dois chifres, que eu tinha visto de pé diante do rio, e correu contra ele com toda a força da sua fúria."},
{v:7,t:"Eu o vi aproximar-se do carneiro; enfureceu-se contra ele, feriu o carneiro e lhe quebrou os dois chifres, e o carneiro não teve força para resistir-lhe; derrubou-o por terra e o pisou, e não houve ninguém que livrasse o carneiro do seu poder."},
{v:8,t:"O bode se tornou muito grande; mas, quando estava no auge da sua força, o grande chifre se quebrou, e em seu lugar surgiram quatro chifres, voltados para os quatro ventos do céu.",n:"O bode é o reino grego; o grande chifre, Alexandre Magno, cujo império foi dividido entre os seus generais (vv. 21–22)."},
{v:9,t:"De um deles saiu um pequeno chifre, que cresceu muito para o sul, para o oriente e para a Terra Magnífica;",n:"A Terra Magnífica: a terra de Israel; a Nova Vulgata entende: contra a força."},
{v:10,t:"cresceu até o exército do céu, fez cair por terra parte desse exército e das estrelas e as pisou;"},
{v:11,t:"chegou a engrandecer-se até contra o chefe do exército, tirou-lhe o sacrifício perpétuo e derrubou o lugar do seu santuário.",n:"O sacrifício perpétuo, oferecido de manhã e à tarde no templo, foi suprimido por Antíoco IV em 167 antes de Cristo (1 Macabeus 1,45–47)."},
{v:12,t:"Um exército foi posto contra o sacrifício perpétuo, por causa dos pecados, e a verdade foi lançada por terra; o chifre agiu e prosperou."},
{v:13,t:"Ouvi então um santo que falava, e outro santo perguntou àquele que falava: Até quando durará a visão sobre o sacrifício perpétuo, o pecado da devastação, o santuário e o exército pisados?",np:1},
{v:14,t:"Ele lhe respondeu: Até duas mil e trezentas tardes e manhãs; depois o santuário será purificado.",n:"Duas mil e trezentas tardes e manhãs: mil cento e cinquenta dias, pouco mais de três anos; o templo foi purificado por Judas Macabeu em dezembro de 164 antes de Cristo (1 Macabeus 4,36–59)."},
{s:"Gabriel explica a visão"},
{v:15,t:"Enquanto eu, Daniel, contemplava a visão e procurava compreendê-la, eis que se pôs diante de mim alguém com aparência de homem;"},
{v:16,t:"e ouvi uma voz humana, do meio do Ulai, que gritava: Gabriel, explica a este homem a visão."},
{v:17,t:"Ele veio para perto do lugar onde eu estava; quando chegou, fiquei aterrado e caí com o rosto por terra. Ele me disse: Compreende, filho do homem, que a visão se refere ao tempo do fim.",np:1},
{v:18,t:"Enquanto ele me falava, caí desmaiado, com o rosto por terra; mas ele me tocou e me pôs de pé no lugar onde eu estava,"},
{v:19,t:"e disse: Vou dar-te a conhecer o que acontecerá no fim da ira, pois a visão se refere ao tempo determinado do fim."},
{v:20,t:"O carneiro que viste, com os dois chifres, são os reis da Média e da Pérsia;",np:1},
{v:21,t:"o bode é o rei da Grécia, e o grande chifre que estava entre os seus olhos é o primeiro rei."},
{v:22,t:"E os quatro chifres que surgiram no lugar do que foi quebrado são quatro reinos que surgirão da sua nação, mas não com a mesma força."},
{v:23,t:"No fim do reinado deles, quando os pecadores tiverem chegado ao cúmulo, surgirá um rei de rosto insolente, hábil em intrigas;",np:1},
{v:24,t:"o seu poder crescerá, mas não por força própria; causará destruições incríveis, prosperará no que empreender, destruirá os poderosos e o povo dos santos;"},
{v:25,t:"graças à sua astúcia, o engano prosperará nas suas mãos; ele se engrandecerá no seu coração e, com tranquilidade, destruirá muitos; e se levantará contra o Príncipe dos príncipes; mas será quebrado sem intervenção de mão humana.",n:"Antíoco IV morreu na Pérsia em 164 antes de Cristo (1 Macabeus 6,1–16)."},
{v:26,t:"A visão das tardes e das manhãs de que se falou é verdadeira; mas tu guarda em segredo a visão, pois se refere a dias distantes."},
{v:27,t:"Eu, Daniel, fiquei esgotado e doente durante alguns dias; depois me levantei e cuidei dos negócios do rei; mas fiquei atônito com a visão, e ninguém a compreendia."}
];

window.TEXTOS_SEED["daniel"][9] = [
{s:"A oração de Daniel"},
{v:1,t:"No primeiro ano de Dario, filho de Assuero, da descendência dos medos, que reinou sobre o reino dos caldeus,"},
{v:2,t:"no primeiro ano do seu reinado, eu, Daniel, compreendi pelos livros o número dos anos de que o Senhor tinha falado ao profeta Jeremias, e que deviam cumprir-se sobre as ruínas de Jerusalém: setenta anos.",n:"Compare Jeremias 25,11–12; 29,10."},
{v:3,t:"Voltei o rosto para o Senhor Deus, para lhe dirigir orações e súplicas, com jejum, pano de saco e cinza."},
{v:4,t:"Rezei ao Senhor, meu Deus, fiz a minha confissão e disse: Ah, Senhor, Deus grande e temível, que guardas a aliança e a misericórdia para com os que te amam e guardam os teus mandamentos,"},
{v:5,t:"pecamos, cometemos a iniquidade, agimos com impiedade, nos rebelamos e nos desviamos dos teus mandamentos e dos teus decretos;"},
{v:6,t:"não escutamos os teus servos, os profetas, que falaram em teu nome aos nossos reis, aos nossos chefes, aos nossos pais e a todo o povo da terra."},
{v:7,t:"A ti, Senhor, a justiça; a nós, a vergonha no rosto, como acontece hoje aos homens de Judá, aos habitantes de Jerusalém e a todo Israel, aos que estão perto e aos que estão longe, em todos os países para onde os expulsaste por causa das infidelidades que cometeram contra ti.",np:1},
{v:8,t:"Senhor, a nós a vergonha no rosto, aos nossos reis, aos nossos chefes e aos nossos pais, porque pecamos contra ti;"},
{v:9,t:"mas ao Senhor, nosso Deus, a misericórdia e o perdão, porque nos rebelamos contra ele,"},
{v:10,t:"e não escutamos a voz do Senhor, nosso Deus, para andarmos na sua lei, que ele nos deu por meio dos seus servos, os profetas;"},
{v:11,t:"todo Israel transgrediu a tua lei e se desviou, para não escutar a tua voz; por isso caíram sobre nós a maldição e a imprecação escritas na Lei de Moisés, servo de Deus, porque pecamos contra ele."},
{v:12,t:"Ele cumpriu as palavras que tinha pronunciado contra nós e contra os nossos juízes que nos governaram, fazendo vir sobre nós uma desgraça tão grande como nunca houve debaixo do céu, como a que aconteceu em Jerusalém.",np:1},
{v:13,t:"Conforme está escrito na Lei de Moisés, toda essa desgraça veio sobre nós; e não suplicamos ao Senhor, nosso Deus, convertendo-nos das nossas iniquidades e atendendo à tua verdade."},
{v:14,t:"O Senhor vigiou sobre essa desgraça e a fez cair sobre nós, pois o Senhor, nosso Deus, é justo em todas as obras que faz; mas nós não escutamos a sua voz."},
{v:15,t:"E agora, Senhor, nosso Deus, que tiraste o teu povo da terra do Egito com mão forte e adquiriste para ti um nome, como se vê hoje, pecamos, cometemos a iniquidade."},
{v:16,t:"Senhor, segundo toda a tua justiça, afaste-se, por favor, a tua ira e o teu furor da tua cidade, Jerusalém, o teu santo monte; pois, por causa dos nossos pecados e das iniquidades dos nossos pais, Jerusalém e o teu povo são objeto de insulto para todos os que nos rodeiam."},
{v:17,t:"Agora, pois, escuta, nosso Deus, a oração do teu servo e as suas súplicas, e faze brilhar o teu rosto sobre o teu santuário devastado, por amor de ti mesmo.",np:1},
{v:18,t:"Inclina, meu Deus, o teu ouvido e escuta; abre os olhos e vê a nossa desolação e a cidade sobre a qual é invocado o teu nome; pois não é confiados nos nossos méritos que apresentamos as nossas súplicas diante de ti, mas na tua grande misericórdia.",np:1},
{v:19,t:"Escuta, Senhor! Perdoa, Senhor! Atende e age! Não tardes, por amor de ti mesmo, meu Deus, pois o teu nome é invocado sobre a tua cidade e sobre o teu povo."},
{s:"As setenta semanas"},
{v:20,t:"Eu ainda estava falando e rezando, confessando o meu pecado e o pecado do meu povo Israel, e apresentando a minha súplica diante do Senhor, meu Deus, pelo santo monte do meu Deus,"},
{v:21,t:"ainda estava falando na oração, quando Gabriel, o homem que eu tinha visto antes na visão, voou rapidamente e me tocou na hora do sacrifício da tarde;"},
{v:22,t:"e me instruiu, falou comigo e disse: Daniel, vim agora para te instruir e te dar entendimento."},
{v:23,t:"Desde o começo das tuas súplicas saiu uma palavra, e eu vim para te comunicá-la, porque és muito amado; presta, pois, atenção à palavra e compreende a visão."},
{v:24,l:["Setenta semanas foram fixadas","para o teu povo e para a tua cidade santa,","para acabar com a transgressão,","pôr fim ao pecado,","expiar a iniquidade,","trazer a justiça eterna,","cumprir a visão e o profeta","e ungir o Santo dos Santos."],np:1,n:"Setenta semanas de anos: quatrocentos e noventa anos, que reinterpretam os setenta anos de Jeremias. A tradição cristã leu estes versículos como anúncio da vinda e da morte do Messias."},
{v:25,l:["Sabe, pois, e compreende:","desde a saída da ordem","de reconstruir Jerusalém","até um ungido, um chefe,","haverá sete semanas;","e durante sessenta e duas semanas","serão reconstruídas a praça e as muralhas,","em tempos de angústia."],np:1},
{v:26,l:["Depois das sessenta e duas semanas,","um ungido será eliminado,","e não haverá nada para ele.","O povo de um chefe que virá","destruirá a cidade e o santuário;","o seu fim será a devastação,","e até o fim da guerra","estão decretadas as desolações."],np:1,n:"Um ungido: talvez o sumo sacerdote Onias III, assassinado em 171 antes de Cristo (2 Macabeus 4,33–35); a tradição cristã o aplicou a Cristo."},
{v:27,l:["Ele firmará uma aliança com muitos","durante uma semana;","e na metade da semana","fará cessar o sacrifício e a oblação;","e sobre a asa das abominações estará o devastador,","até que a destruição decretada","se derrame sobre o devastador."],np:1,n:"A abominação da desolação: o altar pagão erguido por Antíoco IV no templo (1 Macabeus 1,54); compare Mateus 24,15."}
];

window.TEXTOS_SEED["daniel"][10] = [
{s:"A visão junto ao Tigre"},
{v:1,t:"No terceiro ano de Ciro, rei da Pérsia, foi revelada uma palavra a Daniel, chamado Baltassar; a palavra era verdadeira e se referia a uma grande guerra; ele compreendeu a palavra e teve entendimento da visão.",n:"Em 536 antes de Cristo. Os capítulos 10–12 formam uma única revelação."},
{v:2,t:"Naqueles dias, eu, Daniel, estive de luto durante três semanas inteiras;"},
{v:3,t:"não comi alimento saboroso, nem carne nem vinho entraram na minha boca, e não me ungi com perfume, até se completarem as três semanas."},
{v:4,t:"No dia vinte e quatro do primeiro mês, eu estava à margem do grande rio, o Tigre;",np:1},
{v:5,t:"levantei os olhos e olhei: eis um homem vestido de linho, com um cinto de ouro puro na cintura;"},
{v:6,t:"o seu corpo era como o crisólito, o seu rosto tinha o brilho do relâmpago, os seus olhos eram como tochas acesas, os seus braços e as suas pernas tinham o brilho do bronze polido, e o som das suas palavras era como o ruído de uma multidão."},
{v:7,t:"Só eu, Daniel, vi a visão; os homens que estavam comigo não a viram, mas caiu sobre eles um grande terror, e fugiram para se esconder."},
{v:8,t:"Fiquei sozinho e vi esta grande visão; não me restou força alguma, o meu semblante se desfigurou, e fiquei sem nenhum vigor."},
{v:9,t:"Ouvi o som das suas palavras; e, ao ouvir o som das suas palavras, caí atordoado, com o rosto por terra."},
{v:10,t:"E eis que uma mão me tocou e me fez levantar, trêmulo, sobre os joelhos e as palmas das mãos;",np:1},
{v:11,t:"e ele me disse: Daniel, homem muito amado, compreende as palavras que vou dizer-te e põe-te de pé, pois agora fui enviado a ti. Quando ele me disse isso, pus-me de pé, tremendo."},
{v:12,t:"Ele me disse: Não tenhas medo, Daniel, pois desde o primeiro dia em que decidiste compreender e humilhar-te diante do teu Deus, as tuas palavras foram ouvidas, e eu vim por causa das tuas palavras."},
{v:13,t:"Mas o príncipe do reino da Pérsia me resistiu durante vinte e um dias; então Miguel, um dos primeiros príncipes, veio em meu auxílio, e eu fiquei lá, junto ao rei da Pérsia.",n:"O príncipe do reino da Pérsia: o anjo que preside à Pérsia; Miguel é o anjo protetor de Israel (v. 21; 12,1)."},
{v:14,t:"Vim para te fazer compreender o que acontecerá ao teu povo no fim dos dias, pois a visão ainda se refere a esses dias."},
{v:15,t:"Enquanto ele me dizia estas palavras, baixei o rosto para o chão e fiquei calado."},
{v:16,t:"E eis que alguém semelhante aos filhos dos homens tocou os meus lábios; abri a boca, falei e disse àquele que estava de pé diante de mim: Meu senhor, por causa da visão fui tomado de angústias, e não me restou força alguma."},
{v:17,t:"Como poderia o servo do meu senhor falar com o meu senhor? Pois agora não me resta força alguma, e já nem respiro."},
{v:18,t:"Então aquele que tinha aparência de homem me tocou de novo e me fortaleceu,"},
{v:19,t:"e disse: Não tenhas medo, homem muito amado; a paz esteja contigo; sê forte, sê forte! Enquanto ele me falava, recobrei as forças e disse: Fala, meu senhor, pois me fortaleceste."},
{v:20,t:"Ele disse: Sabes por que vim a ti? Agora voltarei para combater contra o príncipe da Pérsia; e, quando eu sair, eis que virá o príncipe da Grécia.",np:1},
{v:21,t:"Contudo, vou anunciar-te o que está escrito no livro da verdade; e ninguém me ajuda contra eles, a não ser Miguel, o vosso príncipe."}
];

window.TEXTOS_SEED["daniel"][11] = [
{s:"Os reis do sul e do norte"},
{v:1,t:"Eu, desde o primeiro ano de Dario, o medo, estive ao seu lado para o ajudar e fortalecer."},
{v:2,t:"E agora vou anunciar-te a verdade: Ainda haverá três reis na Pérsia, e o quarto acumulará riquezas maiores que todos; e, quando se tiver fortalecido pelas suas riquezas, levantará todos contra o reino da Grécia.",n:"O quarto: provavelmente Xerxes, que atacou a Grécia em 480 antes de Cristo."},
{v:3,t:"Depois surgirá um rei poderoso, que dominará com grande poder e fará o que quiser;",n:"Alexandre Magno."},
{v:4,t:"mas, quando estiver no auge, o seu reino será despedaçado e dividido aos quatro ventos do céu, não entre os seus descendentes, nem com o poder com que ele dominou; pois o seu reino será arrancado e dado a outros, além deles."},
{v:5,t:"O rei do sul se tornará forte; mas um dos seus chefes se tornará mais forte que ele e dominará, e o seu domínio será maior que o dele.",np:1,n:"O rei do sul: os Ptolomeus do Egito; o rei do norte: os Selêucidas da Síria. Aqui, Ptolomeu I e Seleuco I."},
{v:6,t:"Ao fim de alguns anos, farão aliança: a filha do rei do sul irá ao rei do norte para fazer um acordo. Mas ela não conservará a força do seu braço, nem o seu braço permanecerá; ela será entregue, com os que a tinham trazido, com o seu filho e com quem a apoiava naqueles tempos.",n:"Berenice, filha de Ptolomeu II, casada com Antíoco II e assassinada com o filho em 246 antes de Cristo."},
{v:7,t:"Mas um rebento das raízes dela surgirá no seu lugar; virá contra o exército, entrará na fortaleza do rei do norte, agirá contra eles e prevalecerá.",n:"Ptolomeu III, irmão de Berenice."},
{v:8,t:"Levará também para o Egito, como presa, os seus deuses, com as suas imagens fundidas e os seus objetos preciosos de prata e de ouro; e durante alguns anos prevalecerá sobre o rei do norte."},
{v:9,t:"Este invadirá o reino do rei do sul, mas voltará para a sua terra."},
{v:10,t:"Os seus filhos se prepararão para a guerra e reunirão uma multidão de tropas numerosas; um deles avançará como uma inundação, passará adiante, voltará e levará a guerra até a fortaleza do rei do sul."},
{v:11,t:"O rei do sul se irritará, sairá e combaterá contra ele, contra o rei do norte; este reunirá uma grande multidão, mas essa multidão será entregue nas mãos do outro.",n:"A batalha de Ráfia, em 217 antes de Cristo, vencida por Ptolomeu IV contra Antíoco III."},
{v:12,t:"A multidão será aniquilada, e o seu coração se encherá de orgulho; ele abaterá dezenas de milhares, mas não prevalecerá."},
{v:13,t:"Pois o rei do norte voltará e reunirá uma multidão maior que a primeira; e, ao fim de alguns anos, virá às pressas com um grande exército e muitas riquezas."},
{v:14,t:"Naqueles tempos muitos se levantarão contra o rei do sul; e homens violentos do teu povo se revoltarão para cumprir a visão, mas cairão."},
{v:15,t:"O rei do norte virá, levantará rampas e tomará uma cidade fortificada; as forças do sul não resistirão, nem mesmo as suas tropas escolhidas terão força para resistir."},
{v:16,t:"Aquele que vier contra ele fará o que quiser, e ninguém lhe poderá resistir; ele se estabelecerá na Terra Magnífica, e a destruição estará nas suas mãos.",n:"Antíoco III conquista a Palestina em 200 antes de Cristo."},
{v:17,t:"Decidirá vir para se apoderar de todo o reino dele; fará com ele um acordo e lhe dará a sua filha em casamento, para arruiná-lo; mas isso não dará certo nem lhe trará proveito.",n:"Cleópatra I, dada em casamento a Ptolomeu V."},
{v:18,t:"Voltará então o rosto para as ilhas e tomará muitas; mas um chefe porá fim à sua afronta, fazendo recair sobre ele a sua afronta.",n:"O cônsul romano Lúcio Cipião, vencedor de Antíoco III em Magnésia, em 190 antes de Cristo."},
{v:19,t:"Voltará o rosto para as fortalezas da sua terra, mas tropeçará, cairá e não será mais encontrado."},
{v:20,t:"No seu lugar surgirá um que mandará um cobrador de impostos à joia do reino; mas em poucos dias será destruído, não pela ira nem pela guerra.",n:"Seleuco IV, que mandou Heliodoro ao templo de Jerusalém (2 Macabeus 3)."},
{s:"O rei desprezível"},
{v:21,t:"No seu lugar surgirá um homem desprezível, a quem não será dada a honra real; virá às escondidas e se apoderará do reino por meio de intrigas.",n:"Antíoco IV Epífanes (175–164 antes de Cristo)."},
{v:22,t:"As forças que se lhe opuserem serão varridas diante dele e destruídas, e também o chefe da aliança.",n:"O chefe da aliança: talvez o sumo sacerdote Onias III."},
{v:23,t:"Depois de fazer aliança com ele, agirá com falsidade; subirá e se tornará forte com pouca gente."},
{v:24,t:"Em tempo de paz entrará nas regiões mais ricas e fará o que nem os seus pais nem os pais dos seus pais fizeram: distribuirá entre os seus o saque, os despojos e as riquezas, e tramará planos contra as fortalezas, mas só por um tempo.",np:1},
{v:25,t:"Com um grande exército despertará a sua força e o seu ânimo contra o rei do sul; e o rei do sul se preparará para a guerra com um exército muito grande e poderoso, mas não resistirá, porque tramarão planos contra ele."},
{v:26,t:"Os que comem da sua mesa o destruirão; o seu exército será arrasado, e muitos cairão mortos."},
{v:27,t:"Os dois reis, com o coração inclinado a fazer o mal, sentados à mesma mesa, dirão mentiras; mas nada conseguirão, pois o fim ainda está reservado para o tempo determinado.",np:1},
{v:28,t:"Ele voltará para a sua terra com muitas riquezas, com o coração contrário à santa aliança; agirá e voltará para a sua terra.",n:"Antíoco IV saqueia o templo em 169 antes de Cristo (1 Macabeus 1,20–24)."},
{v:29,t:"No tempo determinado voltará e virá contra o sul; mas desta vez não será como da primeira."},
{v:30,t:"Virão contra ele navios, os romanos; ele perderá o ânimo e voltará; se enfurecerá contra a santa aliança e agirá; voltará e favorecerá os que abandonaram a santa aliança.",n:"Em 168 antes de Cristo, o embaixador romano Popílio Lenas obrigou Antíoco IV a deixar o Egito."},
{v:31,t:"Tropas enviadas por ele se levantarão, profanarão o santuário, a fortaleza, suprimirão o sacrifício perpétuo e instalarão a abominação do devastador.",n:"Compare 9,27; 1 Macabeus 1,54."},
{v:32,t:"Com lisonjas ele fará apostatar os que violam a aliança; mas o povo dos que conhecem o seu Deus se manterá firme e agirá.",n:"Alusão aos fiéis que resistiram à perseguição, entre eles os Macabeus."},
{v:33,t:"Os sábios do povo instruirão a muitos; mas durante algum tempo cairão pela espada, pelo fogo, pelo cativeiro e pelo saque."},
{v:34,t:"Quando caírem, receberão um pequeno socorro, e muitos se juntarão a eles com hipocrisia."},
{v:35,t:"Alguns dos sábios cairão, para serem purificados, depurados e alvejados, até o tempo do fim; pois ainda haverá outro tempo determinado."},
{s:"A arrogância do rei"},
{v:36,t:"O rei fará o que quiser; se exaltará e se engrandecerá acima de todo deus; contra o Deus dos deuses dirá coisas inauditas e prosperará até que se complete a ira, pois o que está decretado se cumprirá."},
{v:37,t:"Não fará caso dos deuses dos seus pais, nem do deus preferido das mulheres, nem de nenhum outro deus, pois se engrandecerá acima de todos;",n:"O deus preferido das mulheres: talvez Tamuz, também chamado Adônis."},
{v:38,t:"em lugar deles honrará o deus das fortalezas; um deus que os seus pais não conheceram, ele o honrará com ouro, prata, pedras preciosas e objetos de valor;",n:"O deus das fortalezas: talvez Zeus Olímpico, cujo culto Antíoco impôs no templo de Jerusalém (2 Macabeus 6,2)."},
{v:39,t:"agirá contra as cidades fortificadas com a ajuda de um deus estrangeiro; aos que o reconhecerem multiplicará as honras; a esses dará poder sobre muitos e distribuirá terras como recompensa."},
{s:"O fim do perseguidor"},
{v:40,t:"No tempo do fim, o rei do sul lutará contra ele; e o rei do norte se lançará contra ele como uma tempestade, com carros, cavaleiros e muitos navios; invadirá os países, os inundará e passará adiante.",n:"A partir daqui a profecia já não corresponde aos fatos conhecidos: Antíoco IV morreu na Pérsia (1 Macabeus 6,1–16)."},
{v:41,t:"Entrará na Terra Magnífica, e muitos cairão; mas estes escaparão das suas mãos: Edom, Moab e o principal dos amonitas."},
{v:42,t:"Estenderá a mão sobre os países, e a terra do Egito não escapará;"},
{v:43,t:"ele se apoderará dos tesouros de ouro e de prata e de todas as riquezas do Egito; os líbios e os etíopes seguirão os seus passos."},
{v:44,t:"Mas notícias vindas do oriente e do norte o perturbarão, e ele partirá com grande furor para destruir e exterminar muitos;"},
{v:45,t:"armará as tendas do seu palácio entre os mares e o monte santo e magnífico; mas chegará ao seu fim, e ninguém o socorrerá."}
];
