// =====================================================================
// Daniel — tradução do hebraico e do aramaico; os acréscimos (3,24–90; 13–14),
// do grego (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["daniel"][1] = [
{s:"Os jovens judeus na corte da Babilônia"},
{v:1,t:"No terceiro ano do reinado de Joaquim, rei de Judá, Nabucodonosor, rei da Babilônia, veio a Jerusalém e a sitiou;",n:"Por volta de 606 antes de Cristo; a data não coincide com o que se sabe pelos outros livros (compare 2 Reis 24,1; Jeremias 25,1). O livro de Daniel, composto no tempo da perseguição de Antíoco IV Epífanes (167–164 antes de Cristo), usa a história do exílio como moldura do seu ensinamento."},
{v:2,t:"e o Senhor entregou nas suas mãos Joaquim, rei de Judá, e parte dos utensílios da casa de Deus; ele os levou para a terra de Senaar, para o templo dos seus deuses, e colocou os utensílios no tesouro dos seus deuses."},
{v:3,t:"O rei disse a Asfanaz, chefe dos seus eunucos, que trouxesse alguns dos filhos de Israel, de linhagem real e de famílias nobres,",np:1},
{v:4,t:"jovens sem nenhum defeito, de boa aparência, instruídos em toda a sabedoria, cultos e inteligentes, capazes de servir no palácio do rei, e que lhes ensinasse a literatura e a língua dos caldeus."},
{v:5,t:"O rei lhes destinou uma ração diária das iguarias da sua mesa e do vinho que ele mesmo bebia; deviam ser educados durante três anos e, depois, servir diante do rei."},
{v:6,t:"Entre eles estavam, dos filhos de Judá, Daniel, Ananias, Misael e Azarias."},
{v:7,t:"O chefe dos eunucos lhes deu outros nomes: a Daniel, Baltasar; a Ananias, Sedrac; a Misael, Misac; e a Azarias, Abdênago."},
{s:"A fidelidade de Daniel e dos companheiros"},
{v:8,t:"Daniel decidiu no seu coração não se contaminar com as iguarias da mesa do rei nem com o vinho que ele bebia, e pediu ao chefe dos eunucos que lhe permitisse não se contaminar.",n:"Os alimentos do rei não seguiam as leis de pureza (Levítico 11) e podiam ter sido oferecidos aos ídolos."},
{v:9,t:"Deus concedeu a Daniel encontrar favor e simpatia diante do chefe dos eunucos;"},
{v:10,t:"mas o chefe dos eunucos disse a Daniel: Tenho medo do meu senhor, o rei, que determinou a vossa comida e a vossa bebida; se ele vir os vossos rostos mais abatidos que os dos outros jovens da vossa idade, poreis em perigo a minha cabeça diante do rei."},
{v:11,t:"Daniel disse então ao guarda que o chefe dos eunucos tinha posto sobre Daniel, Ananias, Misael e Azarias:"},
{v:12,t:"Põe à prova os teus servos, por favor, durante dez dias: que nos deem legumes para comer e água para beber;"},
{v:13,t:"depois compara os nossos rostos com os dos jovens que comem as iguarias do rei, e faze com os teus servos conforme o que vires."},
{v:14,t:"Ele aceitou a proposta e os pôs à prova durante dez dias.",np:1},
{v:15,t:"Ao fim dos dez dias, tinham melhor aparência e estavam mais robustos que todos os jovens que comiam as iguarias do rei."},
{v:16,t:"Desde então, o guarda retirava as iguarias e o vinho que deviam beber e lhes dava legumes.",np:1},
{v:17,t:"A estes quatro jovens Deus deu conhecimento e compreensão de toda a literatura e sabedoria; e Daniel entendia toda espécie de visões e de sonhos.",np:1},
{v:18,t:"Ao fim do tempo que o rei tinha marcado para que fossem apresentados, o chefe dos eunucos os levou à presença de Nabucodonosor."},
{v:19,t:"O rei conversou com eles, e entre todos não se encontrou ninguém como Daniel, Ananias, Misael e Azarias; e ficaram ao serviço do rei."},
{v:20,t:"Em todas as questões de sabedoria e de inteligência sobre as quais o rei os interrogou, achou-os dez vezes superiores a todos os magos e adivinhos que havia em todo o seu reino."},
{v:21,t:"E Daniel ficou ali até o primeiro ano do rei Ciro.",n:"Em 539 antes de Cristo, quando Ciro tomou a Babilônia."}
];

window.TEXTOS_SEED["daniel"][2] = [
{s:"O sonho de Nabucodonosor"},
{v:1,t:"No segundo ano do reinado de Nabucodonosor, Nabucodonosor teve um sonho; o seu espírito ficou perturbado, e o sono fugiu dele."},
{v:2,t:"O rei mandou chamar os magos, os adivinhos, os feiticeiros e os caldeus, para que lhe explicassem os seus sonhos; eles vieram e se apresentaram diante do rei.",n:"Caldeus: aqui, a casta dos sábios e astrólogos da Babilônia."},
{v:3,t:"O rei lhes disse: Tive um sonho, e o meu espírito está perturbado, querendo compreender o sonho."},
{v:4,t:"Os caldeus responderam ao rei, em aramaico: Ó rei, vive para sempre! Conta o sonho aos teus servos, e nós te daremos a interpretação.",n:"A partir daqui, até o fim do capítulo 7, o texto original está em aramaico."},
{v:5,t:"O rei respondeu aos caldeus: A decisão já saiu da minha boca: se não me fizerdes conhecer o sonho e a sua interpretação, sereis cortados em pedaços, e as vossas casas serão transformadas em monturo;"},
{v:6,t:"mas, se me contardes o sonho e a sua interpretação, recebereis de mim presentes, recompensas e grandes honras. Contai-me, pois, o sonho e a sua interpretação."},
{v:7,t:"Eles responderam pela segunda vez: Que o rei conte o sonho aos seus servos, e nós lhe daremos a interpretação.",np:1},
{v:8,t:"O rei respondeu: Vejo bem que quereis ganhar tempo, porque sabeis que a minha decisão está tomada."},
{v:9,t:"Se não me contardes o sonho, uma só sentença vos espera. Combinastes dizer-me palavras mentirosas e enganosas, até que as coisas mudem; por isso contai-me o sonho, e saberei que podeis dar-me a sua interpretação."},
{v:10,t:"Os caldeus responderam ao rei: Não há ninguém na terra que possa fazer o que o rei pede; por isso nenhum rei, por grande e poderoso que seja, jamais pediu tal coisa a nenhum mago, adivinho ou caldeu."},
{v:11,t:"O que o rei pede é difícil, e não há ninguém que o possa revelar ao rei, a não ser os deuses, que não habitam entre os homens."},
{v:12,t:"Ao ouvir isso, o rei se enfureceu e, muito irritado, ordenou que matassem todos os sábios da Babilônia."},
{v:13,t:"Publicado o decreto que mandava matar os sábios, procuraram Daniel e os seus companheiros para matá-los.",np:1},
{s:"Deus revela o mistério a Daniel"},
{v:14,t:"Então Daniel dirigiu-se com prudência e sensatez a Arioc, chefe da guarda do rei, que tinha saído para matar os sábios da Babilônia;"},
{v:15,t:"perguntou a Arioc, a quem o rei tinha dado a ordem, por que razão o rei tinha dado uma sentença tão cruel. Arioc explicou o caso a Daniel,"},
{v:16,t:"e Daniel foi pedir ao rei que lhe desse tempo para revelar ao rei a interpretação."},
{v:17,t:"Daniel foi para casa e contou o caso aos seus companheiros Ananias, Misael e Azarias,"},
{v:18,t:"para que pedissem misericórdia ao Deus do céu a respeito desse mistério, a fim de que Daniel e os seus companheiros não morressem com os outros sábios da Babilônia."},
{v:19,t:"Então o mistério foi revelado a Daniel numa visão noturna, e Daniel bendisse o Deus do céu."},
{v:20,l:["Daniel tomou a palavra e disse:","Bendito seja o nome de Deus","desde sempre e para sempre,","pois a ele pertencem a sabedoria e o poder;"]},
{v:21,l:["ele muda os tempos e as épocas,","depõe reis e estabelece reis,","dá a sabedoria aos sábios","e o conhecimento aos que sabem discernir;"],np:1},
{v:22,l:["ele revela as coisas profundas e ocultas,","conhece o que está nas trevas,","e a luz habita com ele."],np:1},
{v:23,l:["A ti, Deus dos meus pais, dou graças e louvo,","porque me deste a sabedoria e o poder","e agora me fizeste conhecer o que te pedimos,","pois nos revelaste o assunto do rei."],np:1},
{s:"Daniel revela o sonho"},
{v:24,t:"Por isso Daniel foi ter com Arioc, a quem o rei tinha encarregado de matar os sábios da Babilônia, e lhe disse: Não mates os sábios da Babilônia; leva-me à presença do rei, e darei ao rei a interpretação."},
{v:25,t:"Arioc levou depressa Daniel à presença do rei e lhe disse: Encontrei entre os deportados de Judá um homem que dará ao rei a interpretação."},
{v:26,t:"O rei perguntou a Daniel, cujo nome era Baltasar: És tu capaz de me contar o sonho que tive e a sua interpretação?"},
{v:27,t:"Daniel respondeu diante do rei: O mistério que o rei pergunta, nenhum sábio, mago, adivinho ou astrólogo o pode revelar ao rei;"},
{v:28,t:"mas há um Deus no céu que revela os mistérios; ele fez saber ao rei Nabucodonosor o que acontecerá no fim dos tempos. Este é o teu sonho, e estas são as visões que passaram pela tua cabeça, quando estavas deitado:"},
{v:29,t:"Tu, ó rei, estando deitado, pensavas no que aconteceria depois; e aquele que revela os mistérios te fez saber o que vai acontecer."},
{v:30,t:"Quanto a mim, este mistério me foi revelado, não porque eu tenha mais sabedoria do que todos os vivos, mas para que a interpretação fosse dada a conhecer ao rei e tu conhecesses os pensamentos do teu coração."},
{v:31,t:"Tu, ó rei, olhavas, e eis uma grande estátua; essa estátua, enorme e de extraordinário esplendor, estava de pé diante de ti, e o seu aspecto era terrível.",np:1},
{v:32,t:"A cabeça dessa estátua era de ouro fino; o peito e os braços, de prata; o ventre e as coxas, de bronze;"},
{v:33,t:"as pernas, de ferro; os pés, parte de ferro e parte de barro."},
{v:34,t:"Enquanto olhavas, uma pedra se desprendeu, sem intervenção de mão alguma, atingiu a estátua nos pés de ferro e de barro e os despedaçou."},
{v:35,t:"Então o ferro, o barro, o bronze, a prata e o ouro se despedaçaram juntos e ficaram como a palha das eiras no verão: o vento os levou, e não ficou nenhum vestígio deles; mas a pedra que tinha atingido a estátua tornou-se uma grande montanha e encheu toda a terra."},
{s:"A interpretação: os quatro reinos"},
{v:36,t:"Este é o sonho; agora diremos ao rei a sua interpretação."},
{v:37,t:"Tu, ó rei, és o rei dos reis, a quem o Deus do céu deu o reino, o poder, a força e a glória;"},
{v:38,t:"ele entregou nas tuas mãos os filhos dos homens, os animais do campo e as aves do céu, onde quer que habitem, e te fez senhor de todos eles: tu és a cabeça de ouro."},
{v:39,t:"Depois de ti surgirá outro reino, inferior ao teu, e um terceiro reino, de bronze, que dominará toda a terra.",n:"Os reinos são geralmente identificados com a Babilônia, os medos, os persas e os gregos de Alexandre e dos seus sucessores; o reino que não terá fim é o reino de Deus."},
{v:40,t:"O quarto reino será forte como o ferro: assim como o ferro despedaça e esmaga tudo, e como o ferro que tritura, ele despedaçará e triturará todos esses."},
{v:41,t:"Quanto aos pés e aos dedos que viste, parte de barro de oleiro e parte de ferro, será um reino dividido; mas terá algo da solidez do ferro, pois viste o ferro misturado com o barro de argila."},
{v:42,t:"E como os dedos dos pés eram parte de ferro e parte de barro, assim o reino será em parte forte e em parte frágil.",np:1},
{v:43,t:"Quanto ao ferro misturado com o barro de argila, que viste, eles se misturarão por meio de casamentos, mas não se unirão uns aos outros, assim como o ferro não se mistura com o barro."},
{v:44,t:"Nos dias desses reinos, o Deus do céu suscitará um reino que nunca será destruído, e esse reino não passará a outro povo; esmagará e aniquilará todos esses reinos, e ele mesmo permanecerá para sempre;"},
{v:45,t:"foi o que viste: uma pedra se desprendeu da montanha, sem intervenção de mão alguma, e despedaçou o barro, o ferro, o bronze, a prata e o ouro. O grande Deus fez saber ao rei o que vai acontecer depois disso. O sonho é verdadeiro, e a sua interpretação, digna de fé.",n:"Os Padres da Igreja leram na pedra desprendida sem mão humana uma figura de Cristo."},
{s:"Daniel honrado pelo rei"},
{v:46,t:"Então o rei Nabucodonosor caiu com o rosto por terra, prostrou-se diante de Daniel e mandou que lhe oferecessem sacrifícios e incenso."},
{v:47,t:"O rei disse a Daniel: Verdadeiramente o vosso Deus é o Deus dos deuses e o Senhor dos reis, e revela os mistérios, pois tu pudeste revelar este mistério."},
{v:48,t:"Então o rei elevou Daniel a uma alta posição, deu-lhe muitos e grandes presentes e o constituiu governador de toda a província da Babilônia e chefe supremo de todos os sábios da Babilônia."},
{v:49,t:"A pedido de Daniel, o rei pôs Sedrac, Misac e Abdênago à frente da administração da província da Babilônia; Daniel, porém, ficou na corte do rei."}
];
