// =====================================================================
// Eclesiastes (Coélet) — tradução do hebraico (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["eclesiastes"][1] = [
{s:"Tudo é vaidade"},
{v:1,t:"Palavras de Coélet, filho de Davi, rei em Jerusalém.",n:"Coélet: em hebraico Qohelet, aquele que convoca a assembleia ou fala nela; o grego traduziu Eclesiastes. A atribuição a Salomão, filho de Davi, é uma ficção literária: o livro é dos últimos séculos antes de Cristo."},
{v:2,l:["Vaidade das vaidades,","diz Coélet,","vaidade das vaidades, tudo é vaidade!"],np:1,n:"Vaidade: em hebraico hebel, sopro, vapor, fumaça: o que é passageiro e sem consistência. A palavra aparece quase quarenta vezes no livro."},
{v:3,l:["Que proveito tem o homem","de todo o trabalho com que se afadiga debaixo do sol?"],np:1},
{v:4,l:["Uma geração vai, outra geração vem,","e a terra permanece para sempre."],np:1},
{v:5,l:["O sol nasce, e o sol se põe,","e se apressa a voltar ao seu lugar, de onde torna a nascer."],np:1},
{v:6,l:["O vento sopra para o sul e gira para o norte;","gira e gira, e vai girando o vento,","e volta aos seus circuitos."],np:1},
{v:7,l:["Todos os rios correm para o mar, e o mar não transborda;","ao lugar para onde correm os rios, para lá continuam a correr."],np:1},
{v:8,l:["Todas as coisas cansam;","ninguém é capaz de dizê-las.","O olho não se farta de ver,","nem o ouvido se sacia de ouvir."],np:1},
{v:9,l:["O que foi","é o que será;","o que se fez","é o que se fará:"],np:1},
{v:10,l:["nada há de novo debaixo do sol.","Se de alguma coisa se diz: Vê, isto é novo!,","ela já existiu nos séculos que nos precederam."],np:1},
{v:11,l:["Não há lembrança dos antigos,","e também dos que virão depois","não haverá lembrança","entre os que vierem mais tarde."],np:1},
{s:"A experiência de Coélet"},
{v:12,t:"Eu, Coélet, fui rei de Israel em Jerusalém,"},
{v:13,t:"e apliquei o meu coração a investigar e a explorar com sabedoria tudo o que se faz debaixo do céu. É uma tarefa penosa que Deus deu aos filhos dos homens para que nela se ocupem."},
{v:14,t:"Vi todas as obras que se fazem debaixo do sol, e eis que tudo é vaidade e correr atrás do vento.",n:"Correr atrás do vento: assim se entende hoje o hebraico; a Nova Vulgata traduz: aflição de espírito."},
{v:15,l:["O que é torto não se pode endireitar,","e o que falta não se pode contar."],np:1},
{v:16,t:"Eu disse no meu coração: Eis que me engrandeci e acumulei sabedoria mais do que todos os que me precederam em Jerusalém, e o meu coração viu muita sabedoria e conhecimento.",np:1},
{v:17,t:"Apliquei o coração a conhecer a sabedoria e a conhecer a loucura e a insensatez, e compreendi que também isto é correr atrás do vento."},
{v:18,l:["Pois muita sabedoria traz muito desgosto,","e quem aumenta o saber aumenta a dor."],np:1}
];

window.TEXTOS_SEED["eclesiastes"][2] = [
{s:"A experiência dos prazeres"},
{v:1,t:"Eu disse no meu coração: Vamos, vou te pôr à prova com a alegria: goza do bem-estar! Mas também isto é vaidade."},
{v:2,l:["Do riso eu disse: É loucura;","e da alegria: De que serve?"],np:1},
{v:3,t:"Resolvi no meu coração entregar o corpo ao vinho, enquanto o coração se guiava pela sabedoria, e abraçar a insensatez, até ver o que é bom para os filhos dos homens fazerem debaixo do céu durante os poucos dias da sua vida.",np:1},
{v:4,t:"Realizei grandes obras: construí para mim casas, plantei vinhas,"},
{v:5,t:"fiz jardins e pomares e plantei neles árvores frutíferas de toda espécie;"},
{v:6,t:"construí reservatórios de água para regar o bosque onde cresciam as árvores."},
{v:7,t:"Adquiri escravos e escravas e tive servos nascidos em casa; tive também mais gado e rebanhos do que todos os que me precederam em Jerusalém."},
{v:8,t:"Ajuntei também prata e ouro, os tesouros dos reis e das províncias; arranjei cantores e cantoras e as delícias dos filhos dos homens, e muitas concubinas.",n:"Hebraico obscuro; a Nova Vulgata entende: taças e jarros para servir o vinho."},
{v:9,t:"Engrandeci-me e superei todos os que me precederam em Jerusalém; e a minha sabedoria permaneceu comigo."},
{v:10,t:"Não recusei aos meus olhos nada do que desejaram, nem privei o coração de nenhuma alegria; o meu coração se alegrava com todo o meu trabalho, e essa foi a minha recompensa por todo o meu trabalho."},
{v:11,t:"Então considerei todas as obras que as minhas mãos tinham feito e o trabalho que me custara realizá-las, e eis que tudo era vaidade e correr atrás do vento; não há proveito algum debaixo do sol."},
{s:"O sábio e o insensato"},
{v:12,t:"Voltei-me então para considerar a sabedoria, a loucura e a insensatez. Pois que fará o homem que vier depois do rei? O que já foi feito antes."},
{v:13,t:"E vi que a sabedoria leva vantagem sobre a insensatez, como a luz leva vantagem sobre as trevas."},
{v:14,l:["O sábio tem os olhos na cabeça,","e o insensato anda nas trevas;","mas eu sei também que uma mesma sorte","atinge a ambos."],np:1},
{v:15,t:"E disse no meu coração: A sorte do insensato será também a minha; para que, então, me tornei mais sábio? E disse no meu coração que também isto é vaidade.",np:1},
{v:16,t:"Pois não há lembrança duradoura do sábio, como não há do insensato; nos dias que virão, tudo será esquecido. E o sábio morre, tal como o insensato!"},
{v:17,t:"Por isso detestei a vida, porque me pareceu mau o que se faz debaixo do sol: tudo é vaidade e correr atrás do vento.",np:1},
{v:18,t:"Detestei todo o trabalho com que me afadiguei debaixo do sol, e que terei de deixar ao homem que vier depois de mim;"},
{v:19,t:"e quem sabe se ele será sábio ou insensato? No entanto, será dono de todo o trabalho em que pus o meu esforço e a minha sabedoria debaixo do sol. Também isto é vaidade."},
{v:20,t:"E cheguei a desesperar no meu coração de todo o trabalho com que me afadiguei debaixo do sol."},
{v:21,t:"Pois há quem trabalhe com sabedoria, com conhecimento e com êxito, e tenha de deixar a sua parte a quem não trabalhou nela. Também isto é vaidade e um grande mal.",np:1},
{v:22,t:"Pois que fica para o homem de todo o seu trabalho e da preocupação do seu coração, com que se afadiga debaixo do sol?",np:1},
{v:23,t:"Todos os seus dias são dor, e a sua ocupação é aflição; nem de noite o seu coração descansa. Também isto é vaidade."},
{v:24,t:"Não há nada melhor para o homem do que comer, beber e gozar o fruto do seu trabalho. E vi que também isto vem da mão de Deus."},
{v:25,t:"Pois quem pode comer e quem pode gozar sem ele?",n:"Sem ele: assim a Nova Vulgata, com o grego; o hebraico diz: sem mim."},
{v:26,t:"Pois ao homem que lhe agrada Deus dá sabedoria, conhecimento e alegria; mas ao pecador dá a tarefa de ajuntar e acumular, para deixar tudo a quem agrada a Deus. Também isto é vaidade e correr atrás do vento.",np:1}
];

window.TEXTOS_SEED["eclesiastes"][3] = [
{s:"Há um tempo para tudo"},
{v:1,l:["Para tudo há um momento,","e um tempo para cada coisa debaixo do céu:"]},
{v:2,l:["tempo de nascer e tempo de morrer,","tempo de plantar e tempo de arrancar o que se plantou;"],np:1},
{v:3,l:["tempo de matar e tempo de curar,","tempo de destruir e tempo de construir;"],np:1},
{v:4,l:["tempo de chorar e tempo de rir,","tempo de lamentar e tempo de dançar;"],np:1},
{v:5,l:["tempo de atirar pedras e tempo de ajuntar pedras,","tempo de abraçar e tempo de se abster de abraços;"],np:1},
{v:6,l:["tempo de procurar e tempo de perder,","tempo de guardar e tempo de jogar fora;"],np:1},
{v:7,l:["tempo de rasgar e tempo de costurar,","tempo de calar e tempo de falar;"],np:1},
{v:8,l:["tempo de amar e tempo de odiar,","tempo de guerra e tempo de paz."],np:1},
{v:9,t:"Que proveito tem o trabalhador daquilo com que se afadiga?",np:1},
{v:10,t:"Vi a tarefa que Deus deu aos filhos dos homens para que nela se ocupem.",np:1},
{v:11,t:"Ele fez tudo belo a seu tempo; pôs também no coração do homem o sentido da eternidade, sem que o homem possa compreender a obra que Deus fez do princípio ao fim.",np:1,n:"O sentido da eternidade: em hebraico ha-olam, a eternidade ou a duração do mundo; a Nova Vulgata traduz: o mundo."},
{v:12,t:"Compreendi que não há nada melhor para o homem do que alegrar-se e fazer o bem durante a sua vida;"},
{v:13,t:"e que todo homem que come, bebe e goza o fruto do seu trabalho recebe um dom de Deus.",np:1},
{v:14,t:"Compreendi que tudo o que Deus faz permanece para sempre: nada se lhe pode acrescentar, nada se lhe pode tirar; e Deus assim fez para que o temam."},
{v:15,t:"O que existe já existia, e o que há de ser já foi; e Deus procura o que passou."},
{s:"A injustiça e a morte"},
{v:16,t:"Vi ainda debaixo do sol: no lugar do julgamento, a impiedade; no lugar da justiça, a iniquidade."},
{v:17,t:"E disse no meu coração: Deus julgará o justo e o ímpio, pois há um tempo para cada coisa e para cada ação."},
{v:18,t:"Disse ainda no meu coração, a respeito dos filhos dos homens: Deus os põe à prova para mostrar-lhes que, por si mesmos, são como os animais.",np:1},
{v:19,t:"Pois a sorte dos filhos dos homens e a sorte dos animais é uma só: como morre um, morre o outro; todos têm o mesmo sopro de vida, e o homem não leva vantagem sobre o animal, pois tudo é vaidade.",n:"Nota do tradutor: Coélet olha apenas para o que se vê debaixo do sol. A esperança de uma vida além da morte será afirmada mais tarde, no livro da Sabedoria (3,1–9), e plenamente no Novo Testamento."},
{v:20,l:["Todos vão para o mesmo lugar:","todos vêm do pó,","e todos voltam ao pó."],np:1},
{v:21,t:"Quem sabe se o sopro dos filhos dos homens sobe para o alto, e se o sopro dos animais desce para baixo, para a terra?",np:1},
{v:22,t:"Vi, pois, que não há nada melhor para o homem do que alegrar-se com as suas obras, pois essa é a sua parte. Quem o fará ver o que acontecerá depois dele?"}
];

window.TEXTOS_SEED["eclesiastes"][4] = [
{s:"A opressão e a solidão"},
{v:1,t:"Voltei a considerar todas as opressões que se cometem debaixo do sol: eis as lágrimas dos oprimidos, e não há quem os console; a força está do lado dos opressores, e não há quem os console."},
{v:2,t:"E julguei mais felizes os mortos, que já morreram, do que os vivos, que ainda estão vivos;"},
{v:3,t:"e mais feliz que uns e outros aquele que ainda não existe, que não viu as más obras que se fazem debaixo do sol."},
{v:4,t:"Vi também que todo trabalho e todo êxito numa obra nascem da inveja de um contra o outro. Também isto é vaidade e correr atrás do vento.",np:1},
{v:5,l:["O insensato cruza os braços","e devora a própria carne."],np:1},
{v:6,l:["Mais vale uma mão cheia com tranquilidade","do que as duas mãos cheias com fadiga e correr atrás do vento."],np:1},
{v:7,t:"Considerei ainda outra vaidade debaixo do sol:",np:1},
{v:8,t:"um homem sozinho, sem companheiro, sem filho nem irmão; não há fim para todo o seu trabalho, e os seus olhos não se fartam de riquezas. Para quem trabalho eu e me privo de todo bem? Também isto é vaidade e uma tarefa penosa."},
{v:9,t:"Mais valem dois do que um só, pois têm melhor recompensa pelo seu trabalho."},
{v:10,t:"Se um cair, o outro levanta o companheiro. Mas ai de quem está sozinho e cai, sem ter quem o levante!"},
{v:11,t:"Também, se dois dormem juntos, se aquecem; mas como pode um só se aquecer?"},
{v:12,t:"E, se alguém atacar um deles, os dois lhe resistirão; e o cordão de três fios não se rompe facilmente.",np:1},
{s:"O jovem sábio e o rei insensato"},
{v:13,l:["Mais vale um jovem pobre e sábio","do que um rei velho e insensato,","que já não sabe aceitar conselhos."]},
{v:14,t:"Pois um saiu da prisão para reinar, embora tivesse nascido pobre no reino do outro.",np:1},
{v:15,t:"Vi todos os viventes que andam debaixo do sol seguirem o jovem, o segundo, que ocuparia o lugar do rei."},
{v:16,t:"Era sem fim a multidão de todos aqueles à frente dos quais ele estava; mas os que vierem depois não se alegrarão com ele. Também isto é vaidade e correr atrás do vento."},
{v:17,t:"Vigia os teus passos quando fores à casa de Deus: aproximar-se para escutar vale mais do que o sacrifício oferecido pelos insensatos, que nem sabem que fazem o mal.",np:1}
];

window.TEXTOS_SEED["eclesiastes"][5] = [
{s:"Palavras e votos diante de Deus"},
{v:1,t:"Não te precipites com a boca, nem o teu coração se apresse a proferir palavras diante de Deus, porque Deus está no céu e tu estás na terra: por isso, sejam poucas as tuas palavras."},
{v:2,l:["Pois dos muitos cuidados vêm os sonhos,","e das muitas palavras, a fala do insensato."],np:1},
{v:3,t:"Quando fizeres um voto a Deus, não tardes a cumpri-lo, porque ele não se agrada dos insensatos; cumpre o que prometeste.",np:1},
{v:4,t:"Mais vale não fazer votos do que fazê-los e não os cumprir."},
{v:5,t:"Não deixes que a tua boca te faça pecar, e não digas diante do mensageiro: Foi um engano. Por que haveria Deus de se irritar com as tuas palavras e destruir a obra das tuas mãos?",n:"O mensageiro: provavelmente o sacerdote, mensageiro do Senhor (Malaquias 2,7); a Nova Vulgata diz: o anjo."},
{v:6,t:"Pois nos muitos sonhos há muitas vaidades e muitas palavras; tu, porém, teme a Deus."},
{s:"A ilusão das riquezas"},
{v:7,t:"Se vires na província o pobre oprimido e o direito e a justiça violados, não te espantes com isso: acima de um alto funcionário vigia outro mais alto, e acima deles há outros ainda."},
{v:8,t:"Mas uma vantagem para a terra, em tudo, é um rei que cuida do campo cultivado.",n:"Hebraico obscuro."},
{v:9,t:"Quem ama o dinheiro nunca se farta de dinheiro, e quem ama a riqueza nunca tem lucro bastante. Também isto é vaidade."},
{v:10,t:"Quando aumentam os bens, aumentam também os que os devoram; e que proveito tem o dono, a não ser vê-los com os olhos?"},
{v:11,l:["Doce é o sono do trabalhador,","quer coma pouco, quer coma muito;","mas a fartura do rico","não o deixa dormir."]},
{v:12,t:"Há um mal doloroso que vi debaixo do sol: riquezas guardadas pelo dono para a sua própria desgraça.",np:1},
{v:13,t:"Essas riquezas se perdem num mau negócio, e, se ele gerou um filho, este fica sem nada nas mãos."},
{v:14,t:"Como saiu do ventre da sua mãe, assim voltará, nu como veio; e do seu trabalho nada levará que possa carregar na mão."},
{v:15,t:"Também isto é um mal doloroso: ele se vai exatamente como veio. Que proveito tem de ter trabalhado para o vento?"},
{v:16,t:"E todos os seus dias come nas trevas, no meio de muita aflição, de doença e de irritação."},
{v:17,t:"Eis o que vi de bom e de belo: comer, beber e gozar o fruto de todo o trabalho com que o homem se afadiga debaixo do sol, durante os dias de vida que Deus lhe concede; pois essa é a sua parte.",np:1},
{v:18,t:"E todo homem a quem Deus deu riquezas e bens, e a quem permitiu comer deles, tomar a sua parte e alegrar-se com o seu trabalho, isso é um dom de Deus."},
{v:19,t:"Pois ele não pensará muito nos dias da sua vida, porque Deus o mantém ocupado com a alegria do seu coração."}
];

window.TEXTOS_SEED["eclesiastes"][6] = [
{s:"Bens de que não se goza"},
{v:1,t:"Há um mal que vi debaixo do sol, e que pesa muito sobre os homens:"},
{v:2,t:"um homem a quem Deus deu riquezas, bens e honra, e a quem nada falta de tudo o que deseja; mas Deus não lhe permite desfrutar deles, e um estranho os desfruta. Isto é vaidade e um mal doloroso."},
{v:3,t:"Se um homem gerar cem filhos e viver muitos anos, por mais numerosos que sejam os dias dos seus anos, se a sua alma não se saciar de felicidade e ele nem sequer tiver sepultura, eu digo que um aborto é mais feliz do que ele."},
{v:4,t:"Pois esse vem em vão e se vai nas trevas, e o seu nome fica coberto de trevas;"},
{v:5,t:"nem sequer viu o sol, nem o conheceu; e, no entanto, tem mais descanso que o outro.",np:1},
{v:6,t:"Ainda que vivesse duas vezes mil anos, sem gozar a felicidade, não vão todos para o mesmo lugar?"},
{v:7,l:["Todo o trabalho do homem é para a sua boca,","e, no entanto, o seu apetite nunca se sacia."],np:1},
{v:8,t:"Que vantagem tem o sábio sobre o insensato? E que vantagem tem o pobre que sabe conduzir-se diante dos vivos?",np:1},
{v:9,t:"Mais vale o que os olhos veem do que o vaguear do desejo. Também isto é vaidade e correr atrás do vento."},
{v:10,t:"O que existe já recebeu o seu nome, e sabe-se o que é o homem: ele não pode disputar com quem é mais forte do que ele."},
{v:11,t:"Quanto mais palavras, mais vaidade; e que proveito tem o homem?"},
{v:12,t:"Pois quem sabe o que é bom para o homem na vida, durante os poucos dias da sua vida vã, que passam como uma sombra? E quem poderá dizer ao homem o que acontecerá depois dele debaixo do sol?"}
];

window.TEXTOS_SEED["eclesiastes"][7] = [
{s:"Conselhos de sabedoria"},
{v:1,l:["Mais vale o bom nome que o perfume precioso,","e o dia da morte que o dia do nascimento."]},
{v:2,l:["Mais vale ir a uma casa de luto","do que a uma casa de banquete,","pois ali está o fim de todo homem,","e quem vive deve refletir nisso."],np:1},
{v:3,l:["Mais vale a tristeza que o riso,","pois com o rosto triste o coração melhora."],np:1},
{v:4,l:["O coração dos sábios está na casa de luto,","e o coração dos insensatos, na casa da alegria."],np:1},
{v:5,l:["Mais vale ouvir a repreensão do sábio","do que ouvir a canção dos insensatos,"],np:1},
{v:6,l:["pois como o crepitar dos espinhos debaixo da panela,","assim é o riso do insensato.","Também isto é vaidade."],np:1,n:"Em hebraico há um jogo de palavras entre sirim, espinhos, e sir, panela."},
{v:7,l:["Pois a opressão enlouquece o sábio,","e o suborno corrompe o coração."],np:1},
{v:8,l:["Mais vale o fim de uma coisa que o seu começo;","mais vale o paciente que o arrogante."],np:1},
{v:9,t:"Não te apresses em irritar-te, porque a irritação repousa no peito dos insensatos.",np:1},
{v:10,t:"Não digas: Por que os tempos passados eram melhores que os de agora? Pois não é a sabedoria que te faz perguntar isso.",np:1},
{v:11,t:"A sabedoria é boa como uma herança, e é proveitosa para os que veem o sol."},
{v:12,t:"Pois estar à sombra da sabedoria é como estar à sombra do dinheiro; mas a vantagem do conhecimento é que a sabedoria dá vida a quem a possui."},
{v:13,t:"Considera a obra de Deus: quem poderá endireitar o que ele fez torto?"},
{v:14,t:"No dia da felicidade, sê feliz; no dia da desgraça, reflete: Deus fez tanto um como o outro, para que o homem nada possa descobrir do que virá depois dele."},
{v:15,t:"Vi de tudo nos dias da minha vida vã: há justos que perecem apesar da sua justiça, e há ímpios que vivem muito apesar da sua maldade.",np:1},
{v:16,l:["Não sejas justo demais,","nem sábio em excesso:","por que te arruinarias?"],np:1},
{v:17,l:["Não sejas ímpio demais,","nem sejas insensato:","por que morrerias antes do tempo?"],np:1},
{v:18,t:"É bom que te agarres a um sem largar o outro, pois quem teme a Deus se sai bem de tudo isso.",np:1},
{v:19,t:"A sabedoria torna o sábio mais forte do que dez governantes que há numa cidade."},
{v:20,t:"Pois não há na terra homem justo que faça o bem e nunca peque.",n:"Compare Romanos 3,10–12."},
{v:21,t:"Não dês atenção a todas as palavras que se dizem, para não ouvires o teu servo falar mal de ti;"},
{v:22,t:"pois a tua consciência sabe que também tu, muitas vezes, falaste mal dos outros."},
{v:23,t:"Tudo isso eu experimentei com sabedoria. Eu disse: Quero ser sábio.",np:1},
{v:24,t:"Mas a sabedoria ficou longe de mim. O que existe está longe e é profundo, muito profundo: quem poderá encontrá-lo?"},
{v:25,t:"Voltei-me com o meu coração a conhecer, a explorar e a buscar a sabedoria e a razão das coisas, e a reconhecer que a impiedade é estupidez, e a insensatez, loucura.",np:1},
{v:26,t:"E achei mais amarga que a morte a mulher que é uma armadilha, cujo coração é uma rede e cujas mãos são correntes. Quem agrada a Deus escapa dela, mas o pecador fica preso nela."},
{v:27,t:"Eis o que descobri, diz Coélet, examinando as coisas uma por uma para encontrar a razão delas,"},
{v:28,l:["razão que a minha alma ainda procura e não encontrou:","entre mil encontrei um homem,","mas entre todas elas não encontrei uma mulher."],n:"Nota do tradutor: os versículos 26–28 refletem a amarga experiência de um homem do seu tempo e visam sobretudo a mulher sedutora de que falam os Provérbios (5,3–6; 7,5–27). O próprio Coélet aconselha a gozar a vida com a mulher amada (9,9)."},
{v:29,l:["Só isto descobri:","Deus fez o homem reto,","mas eles buscam muitos artifícios."],np:1}
];

window.TEXTOS_SEED["eclesiastes"][8] = [
{s:"O sábio diante do rei"},
{v:1,l:["Quem é como o sábio?","Quem conhece a explicação das coisas?","A sabedoria do homem ilumina o seu rosto,","e a dureza do seu semblante se transforma."]},
{v:2,t:"Eu te digo: observa a ordem do rei, por causa do juramento feito diante de Deus;",np:1},
{v:3,t:"não te apresses em te afastar da sua presença, nem persistas numa coisa má, porque ele faz tudo o que quer."},
{v:4,t:"Pois a palavra do rei é soberana, e quem lhe dirá: Que fazes?"},
{v:5,t:"Quem observa o mandamento não conhecerá o mal, e o coração do sábio conhece o tempo e o julgamento."},
{v:6,t:"Pois para cada coisa há um tempo e um julgamento, e a desgraça do homem pesa muito sobre ele;"},
{v:7,t:"pois ele não sabe o que acontecerá; e quem lhe dirá como acontecerá?"},
{v:8,t:"Nenhum homem tem poder sobre o sopro da vida para retê-lo, nem tem poder sobre o dia da morte; não há dispensa nesta guerra, e a impiedade não salva quem a pratica."},
{s:"A retribuição incerta"},
{v:9,t:"Vi tudo isso, aplicando o coração a todas as obras que se fazem debaixo do sol, num tempo em que um homem domina outro para lhe fazer mal."},
{v:10,t:"Vi também ímpios sepultados com honra; iam e vinham do lugar santo, e na cidade se esquecia como tinham agido. Também isto é vaidade.",n:"Hebraico difícil; outros leem: e na cidade eram louvados por terem agido assim."},
{v:11,t:"Porque a sentença contra a má ação não é executada logo, o coração dos filhos dos homens se enche de vontade de fazer o mal."},
{v:12,t:"Ainda que o pecador faça o mal cem vezes e prolongue os seus dias, eu sei que será bom para os que temem a Deus, porque o temem;"},
{v:13,t:"mas não será bom para o ímpio, e ele não prolongará os seus dias, que são como a sombra, porque não teme a Deus."},
{v:14,t:"Há uma vaidade que acontece sobre a terra: há justos que são tratados como se tivessem agido como ímpios, e há ímpios que são tratados como se tivessem agido como justos. Digo que também isto é vaidade."},
{v:15,t:"Por isso louvei a alegria, pois não há nada melhor para o homem debaixo do sol do que comer, beber e alegrar-se; isso o acompanhará no seu trabalho durante os dias de vida que Deus lhe dá debaixo do sol."},
{v:16,t:"Quando apliquei o coração a conhecer a sabedoria e a observar a tarefa que se realiza sobre a terra, pois nem de dia nem de noite os olhos do homem conhecem o sono,"},
{v:17,t:"vi que o homem não pode compreender toda a obra de Deus, a obra que se faz debaixo do sol; por mais que o homem se afadigue em procurar, não a encontrará; e, ainda que o sábio diga que a conhece, não poderá compreendê-la."}
];

window.TEXTOS_SEED["eclesiastes"][9] = [
{s:"Uma mesma sorte para todos"},
{v:1,t:"Refleti sobre tudo isso e procurei esclarecê-lo: os justos e os sábios, com as suas obras, estão na mão de Deus. O homem não sabe se receberá amor ou ódio: tudo está diante dele."},
{v:2,l:["Tudo é igual para todos:","uma mesma sorte para o justo e para o ímpio,","para o bom e para o mau,","para o puro e para o impuro,","para quem oferece sacrifícios e para quem não oferece.","O bom é como o pecador,","e quem jura, como quem tem medo de jurar."],np:1,n:"Para o bom e para o mau: assim a Nova Vulgata, com as antigas versões; o hebraico diz apenas: para o bom."},
{v:3,t:"Este é o mal que há em tudo o que se faz debaixo do sol: uma mesma sorte para todos. Por isso o coração dos filhos dos homens está cheio de maldade, e a loucura está no seu coração durante a vida; e depois, vão para os mortos.",np:1},
{v:4,t:"Para quem está unido a todos os vivos há esperança: mais vale um cão vivo que um leão morto."},
{v:5,t:"Pois os vivos sabem que vão morrer, mas os mortos não sabem mais nada; já não há para eles recompensa, porque a sua memória está esquecida.",n:"Nota do tradutor: veja a nota a 3,19."},
{v:6,t:"O seu amor, o seu ódio e a sua inveja já pereceram, e nunca mais terão parte em nada do que se faz debaixo do sol."},
{s:"Goza a vida"},
{v:7,l:["Vai, come com alegria o teu pão","e bebe de bom coração o teu vinho,","pois Deus já aprovou as tuas obras."]},
{v:8,l:["Que as tuas roupas sejam sempre brancas,","e que não falte perfume na tua cabeça."],np:1},
{v:9,t:"Goza a vida com a mulher que amas, todos os dias da tua vida passageira que Deus te deu debaixo do sol, todos os teus dias passageiros; pois essa é a tua parte na vida e no trabalho com que te afadigas debaixo do sol.",np:1},
{v:10,t:"Tudo o que a tua mão encontrar para fazer, faze-o com todas as tuas forças, pois na morada dos mortos, para onde vais, não há obra, nem razão, nem conhecimento, nem sabedoria."},
{s:"O tempo e o acaso"},
{v:11,t:"Vi ainda debaixo do sol que a corrida não é dos mais velozes, nem a batalha dos mais valentes, nem o pão dos sábios, nem a riqueza dos inteligentes, nem o favor dos instruídos: o tempo e o acaso atingem a todos."},
{v:12,t:"Pois o homem não conhece a sua hora: como os peixes apanhados na rede traiçoeira e como os pássaros presos no laço, assim os filhos dos homens são apanhados no tempo da desgraça, quando ela cai de repente sobre eles."},
{v:13,t:"Vi também debaixo do sol este exemplo de sabedoria, que me pareceu grande:",np:1},
{v:14,t:"havia uma pequena cidade, com poucos habitantes; um grande rei marchou contra ela, cercou-a e levantou contra ela grandes obras de assédio."},
{v:15,t:"Encontrava-se nela um homem pobre e sábio, que salvou a cidade com a sua sabedoria; mas ninguém se lembrou daquele homem pobre."},
{v:16,l:["E eu disse: Mais vale a sabedoria que a força;","mas a sabedoria do pobre é desprezada,","e as suas palavras não são ouvidas."],np:1},
{v:17,l:["As palavras dos sábios, ditas com calma, são mais ouvidas","do que os gritos de quem governa entre insensatos."],np:1},
{v:18,l:["Mais vale a sabedoria que as armas de guerra,","mas um só pecador destrói muito bem."],np:1}
];

window.TEXTOS_SEED["eclesiastes"][10] = [
{s:"O sábio e o insensato"},
{v:1,l:["Moscas mortas fazem cheirar mal e fermentar o óleo do perfumista;","um pouco de insensatez pesa mais que a sabedoria e a glória."]},
{v:2,l:["O coração do sábio o leva para a direita,","e o coração do insensato, para a esquerda."],np:1},
{v:3,t:"E, quando o insensato anda pelo caminho, falta-lhe o juízo, e ele acha que todos são insensatos.",np:1},
{v:4,t:"Se a ira do governante se levantar contra ti, não deixes o teu lugar, pois a calma evita grandes faltas.",np:1},
{v:5,t:"Há um mal que vi debaixo do sol, como um erro que procede de quem governa:",np:1},
{v:6,t:"o insensato é posto em lugares muito elevados, e os ricos ficam sentados em lugares baixos."},
{v:7,t:"Vi escravos a cavalo e príncipes andando a pé como escravos."},
{v:8,l:["Quem cava uma cova nela pode cair,","e quem derruba um muro pode ser picado por uma serpente."]},
{v:9,l:["Quem extrai pedras pode ferir-se com elas,","e quem racha lenha corre perigo."],np:1},
{v:10,t:"Se o ferro está cego e não se afia o gume, é preciso redobrar a força; mas a vantagem de ter êxito está na sabedoria.",np:1},
{v:11,t:"Se a serpente morde antes de ser encantada, de nada serve o encantador.",np:1},
{v:12,l:["As palavras da boca do sábio são cheias de graça,","mas os lábios do insensato o devoram."],np:1},
{v:13,l:["O começo das suas palavras é insensatez,","e o fim da sua fala, loucura perversa."],np:1},
{v:14,l:["O insensato multiplica as palavras;","mas o homem não sabe o que acontecerá,","e quem lhe dirá o que virá depois dele?"],np:1},
{v:15,l:["O trabalho do insensato o cansa,","pois nem sabe o caminho da cidade."],np:1},
{v:16,l:["Ai de ti, terra, cujo rei é um menino,","e cujos príncipes banqueteiam desde a manhã!"],np:1},
{v:17,l:["Feliz de ti, terra, cujo rei é de estirpe nobre,","e cujos príncipes comem na hora certa,","para se fortalecer, e não para se embriagar!"],np:1},
{v:18,l:["Pela preguiça o madeiramento cede,","e pela negligência das mãos a casa goteja."],np:1},
{v:19,l:["Para rir se fazem banquetes,","o vinho alegra a vida,","e o dinheiro responde a tudo."],np:1},
{v:20,l:["Nem em pensamento amaldiçoes o rei,","nem no teu quarto de dormir amaldiçoes o rico,","pois uma ave do céu levaria a tua voz,","e um ser alado contaria o que disseste."],np:1}
];

window.TEXTOS_SEED["eclesiastes"][11] = [
{s:"Lança o teu pão sobre as águas"},
{v:1,t:"Lança o teu pão sobre as águas, pois depois de muitos dias o encontrarás."},
{v:2,t:"Reparte com sete e até com oito, pois não sabes que desgraça pode vir sobre a terra.",np:1},
{v:3,l:["Quando as nuvens estão cheias,","derramam a chuva sobre a terra;","se uma árvore cai para o sul ou para o norte,","no lugar onde cair, ali ficará."],np:1},
{v:4,t:"Quem fica observando o vento não semeia, e quem fica olhando as nuvens não colhe."},
{v:5,t:"Assim como não sabes qual é o caminho do sopro de vida, nem como se formam os ossos no ventre da mulher grávida, assim também não conheces a obra de Deus, que faz todas as coisas.",np:1},
{v:6,l:["De manhã semeia a tua semente,","e à tarde não deixes descansar a tua mão,","pois não sabes o que dará certo,","isto ou aquilo,","ou se ambos serão igualmente bons."],np:1},
{s:"A juventude e a velhice"},
{v:7,l:["Doce é a luz,","e é agradável aos olhos ver o sol."]},
{v:8,l:["Se o homem viver muitos anos,","que se alegre em todos eles,","mas lembre-se dos dias de trevas, que serão muitos:","tudo o que vem é vaidade."],np:1},
{v:9,l:["Alegra-te, jovem, na tua juventude,","e que o teu coração seja feliz nos dias da tua mocidade;","segue os caminhos do teu coração","e o que os teus olhos desejam;","mas sabe que por tudo isso","Deus te chamará a juízo."],np:1},
{v:10,l:["Afasta do teu coração a tristeza","e livra o teu corpo do sofrimento,","pois a juventude e a aurora da vida são passageiras."],np:1}
];

window.TEXTOS_SEED["eclesiastes"][12] = [
{s:"Lembra-te do teu Criador"},
{v:1,l:["Lembra-te do teu Criador","nos dias da tua juventude,","antes que venham os dias maus","e cheguem os anos dos quais dirás:","Não sinto neles prazer algum;"]},
{v:2,l:["antes que se escureçam","o sol, a luz, a lua e as estrelas,","e voltem as nuvens depois da chuva;"],np:1},
{v:3,l:["no dia em que tremerem os guardas da casa","e se curvarem os homens fortes,","em que pararem as que moem, por serem poucas,","e se escurecerem as que olham pelas janelas;"],np:1,n:"O poema descreve a velhice e a morte com imagens: os guardas da casa seriam os braços; os homens fortes, as pernas; as que moem, os dentes; as que olham pelas janelas, os olhos."},
{v:4,l:["quando se fecharem as portas da rua","e diminuir o ruído do moinho,","quando se levantar ao canto do pássaro","e se calarem todas as canções;"],np:1},
{v:5,l:["quando se tiver medo das alturas","e dos sustos pelo caminho;","quando a amendoeira florescer,","o gafanhoto se arrastar","e a alcaparra perder o sabor;","pois o homem vai para a sua morada eterna,","e os que choram rondam pela rua;"],np:1},
{v:6,l:["antes que se rompa o fio de prata","e se quebre a taça de ouro,","antes que se despedace o cântaro junto à fonte","e se quebre a roldana sobre o poço,"],np:1},
{v:7,l:["e o pó volte à terra de onde veio,","e o espírito volte a Deus, que o deu."],np:1},
{v:8,l:["Vaidade das vaidades,","diz Coélet,","tudo é vaidade."],np:1},
{s:"Epílogo"},
{v:9,t:"Além de ser sábio, Coélet ensinou também o conhecimento ao povo; ponderou, investigou e compôs muitos provérbios."},
{v:10,t:"Coélet procurou encontrar palavras agradáveis e escreveu com retidão palavras de verdade."},
{v:11,t:"As palavras dos sábios são como aguilhões, e as sentenças reunidas são como pregos bem fixados: foram dadas por um só pastor."},
{v:12,t:"Além disso, meu filho, fica prevenido: fazer muitos livros é coisa sem fim, e muito estudo cansa o corpo."},
{v:13,t:"Fim do discurso; tudo foi ouvido: teme a Deus e guarda os seus mandamentos, porque isto é o homem todo."},
{v:14,t:"Pois Deus levará a juízo toda obra, e até tudo o que está oculto, seja bom, seja mau."}
];
