// =====================================================================
// Eclesiástico (Sirácida) — tradução segundo o texto da Nova Vulgata, cotejado
// com o grego e com os fragmentos hebraicos (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["eclesiastico"][1] = [
{s:"Prólogo do tradutor grego"},
{v:"Pról. 1",t:"Muitos e grandes ensinamentos nos foram dados pela Lei, pelos Profetas e pelos outros escritores que os seguiram, e por eles Israel merece ser louvado pela sua instrução e sabedoria. E, como não basta que os próprios leitores se tornem sábios, mas é preciso que os estudiosos sejam úteis também aos de fora, pela palavra e pela escrita, meu avô Jesus, depois de se ter dedicado intensamente à leitura da Lei, dos Profetas e dos outros livros dos nossos pais, e de ter adquirido neles uma grande familiaridade, decidiu ele também escrever alguma coisa sobre a instrução e a sabedoria, para que os que desejam aprender, familiarizando-se também com isso, progridam ainda mais numa vida conforme à Lei.",n:"O prólogo, escrito pelo neto do autor, não faz parte do livro propriamente dito e não é numerado."},
{v:"Pról. 2",t:"Sois, pois, convidados a fazer esta leitura com benevolência e atenção, e a ser indulgentes onde parecer que, apesar do nosso esforço de tradução, não conseguimos exprimir bem algumas expressões; pois as coisas ditas em hebraico não têm a mesma força quando traduzidas para outra língua. E não só este livro: também a própria Lei, os Profetas e os demais livros apresentam uma diferença não pequena quando lidos na língua original.",np:1},
{v:"Pról. 3",t:"No trigésimo oitavo ano do rei Evérgetes, cheguei ao Egito e, tendo ali permanecido algum tempo, encontrei um exemplar de não pequena instrução. Julguei então muito necessário dedicar eu também algum esforço e trabalho a traduzir este livro. Empreguei muitas vigílias e muito saber durante esse tempo, para levar a obra a termo e publicá-la também para os que, vivendo no estrangeiro, desejam instruir-se, preparando os seus costumes para viver segundo a Lei.",np:1,n:"Ptolomeu VIII Evérgetes: o trigésimo oitavo ano do seu reinado corresponde a 132 antes de Cristo. O livro foi escrito em hebraico por Jesus, filho de Sirac (50,29), por volta de 180 antes de Cristo."},
{s:"A origem da sabedoria"},
{v:1,l:["Toda sabedoria vem do Senhor Deus,","esteve sempre com ele e existe antes de todos os tempos."],n:"O Eclesiástico foi escrito em hebraico e traduzido para o grego pelo neto do autor. A tradução segue aqui o texto latino da Nova Vulgata, que contém versos ausentes do grego principal; indicam-se só as diferenças mais importantes."},
{v:2,l:["A areia do mar, as gotas da chuva","e os dias do mundo, quem os contou?","A altura do céu, a largura da terra","e a profundidade do abismo, quem as mediu?"],np:1},
{v:3,l:["A sabedoria de Deus, que precede todas as coisas, quem a investigou?"],np:1},
{v:4,l:["Antes de todas as coisas foi criada a sabedoria,","e a inteligência prudente, desde a eternidade."],np:1},
{v:5,l:["A fonte da sabedoria é a palavra de Deus nas alturas,","e os seus caminhos são os mandamentos eternos."],np:1},
{v:6,l:["A raiz da sabedoria, a quem foi revelada?","E as suas sutilezas, quem as conheceu?"],np:1},
{v:7,l:["A ciência da sabedoria, a quem foi revelada e manifestada?","E a sua grande experiência, quem a compreendeu?"],np:1},
{v:8,l:["Um só é o Altíssimo, criador onipotente,","rei poderoso e muito temível,","que está sentado no seu trono e domina: é Deus."],np:1},
{v:9,l:["Ele a criou no espírito santo,","a viu, a contou e a mediu;"],np:1},
{v:10,l:["derramou-a sobre todas as suas obras","e sobre toda carne, segundo a sua generosidade,","e a concedeu aos que o amam."],np:1},
{s:"O temor do Senhor"},
{v:11,l:["O temor do Senhor é glória e motivo de orgulho,","alegria e coroa de júbilo."]},
{v:12,l:["O temor do Senhor alegra o coração,","dá contentamento, alegria e longa vida."],np:1},
{v:13,l:["Quem teme o Senhor terá um bom fim,","e no dia da sua morte será abençoado."],np:1},
{v:14,l:["O amor de Deus é sabedoria digna de honra;"],np:1},
{v:15,l:["e àqueles a quem ela aparece, ele a reparte,","para que o contemplem","e conheçam as suas maravilhas."],np:1},
{v:16,l:["O princípio da sabedoria é o temor do Senhor;","ela foi criada com os fiéis no seio materno,","estabeleceu-se desde sempre com os homens verdadeiros","e se confiará à sua descendência."],np:1},
{v:17,l:["O temor do Senhor é a piedade do conhecimento;"],np:1},
{v:18,l:["a piedade guardará e justificará o coração,","dará contentamento e alegria."],np:1,n:"A Nova Vulgata omite o versículo 19 da antiga versão latina, que falta no grego."},
{v:20,l:["A plenitude da sabedoria é temer a Deus;","ela embriaga os homens com os seus frutos."]},
{v:21,l:["Enche de bens preciosos toda a sua casa,","e os seus celeiros, de tesouros."],np:1},
{v:22,l:["A coroa da sabedoria é o temor do Senhor,","que faz florescer a paz e o fruto da salvação:"],np:1},
{v:23,l:["ambas são dons de Deus."],np:1},
{v:24,l:["A sabedoria derrama como chuva a ciência e a inteligência prudente,","e exalta a glória dos que a possuem."],np:1},
{v:25,l:["A raiz da sabedoria é temer o Senhor,","e os seus ramos são de longa vida."],np:1},
{v:26,l:["Nos tesouros da sabedoria estão a inteligência e a piedade do conhecimento;","mas para os pecadores a sabedoria é abominável."],np:1},
{v:27,l:["O temor do Senhor expulsa o pecado;","onde ele está, afasta toda ira."],np:1},
{v:28,l:["Quem não tem temor não poderá ser justificado,","pois o ímpeto da sua ira será a sua ruína."],np:1},
{v:29,l:["O homem paciente suporta até o tempo oportuno,","e depois lhe será restituída a alegria."],np:1},
{v:30,l:["O homem sensato guarda as suas palavras até o tempo oportuno,","e os lábios de muitos proclamarão o seu bom senso."],np:1},
{v:31,l:["Nos tesouros da sabedoria estão as máximas da instrução;"],np:1},
{v:32,l:["mas para o pecador o culto de Deus é abominável."],np:1},
{s:"Sabedoria e sinceridade"},
{v:33,l:["Filho, se desejas a sabedoria, guarda a justiça,","e Deus te dará a sabedoria."]},
{v:34,l:["Pois a sabedoria e a instrução são o temor do Senhor,","e o que lhe agrada"],np:1},
{v:35,l:["é a fidelidade e a mansidão."],np:1},
{v:36,l:["Não sejas incrédulo para com o temor do Senhor,","nem te aproximes dele com coração dobre."],np:1},
{v:37,l:["Não sejas hipócrita diante dos homens","e toma cuidado com os teus lábios."],np:1},
{v:38,l:["Não te exaltes, para não caíres","e atraíres a desonra sobre ti,"],np:1},
{v:39,l:["e para que Deus não revele os teus segredos","e não te humilhe no meio da assembleia,"],np:1},
{v:40,l:["porque te aproximaste com malícia do temor do Senhor,","e o teu coração está cheio de engano e falsidade."],np:1}
];

window.TEXTOS_SEED["eclesiastico"][2] = [
{s:"A fidelidade na provação"},
{v:1,l:["Filho, se te aproximas para servir a Deus,","permanece na justiça e no temor","e prepara-te para a provação."]},
{v:2,l:["Endireita o teu coração e sê constante,","inclina o ouvido e acolhe as palavras da inteligência,","e não te perturbes no tempo da adversidade."],np:1},
{v:3,l:["Suporta as demoras de Deus, une-te a ele e não te afastes,","para que sejas sábio nos teus caminhos."],np:1},
{v:4,l:["Aceita tudo o que te acontecer, suporta-o na dor","e sê paciente na tua humilhação,"],np:1},
{v:5,l:["pois o ouro e a prata se provam no fogo,","e os homens agradáveis a Deus, no crisol da humilhação."],np:1},
{v:6,l:["Confia em Deus, e ele te amparará;","espera nele, e ele endireitará o teu caminho;","guarda o seu temor e envelhece nele."],np:1},
{v:7,l:["Vós que temeis o Senhor, esperai a sua misericórdia;","não vos desvieis dele, para não cairdes."],np:1},
{v:8,l:["Vós que temeis o Senhor, confiai nele,","e a vossa recompensa não se perderá."],np:1},
{v:9,l:["Vós que temeis o Senhor, esperai os seus bens,","a alegria eterna e a misericórdia."],np:1},
{v:10,l:["Vós que temeis o Senhor, amai-o, e os vossos corações serão iluminados."],np:1},
{v:11,l:["Olhai, filhos, as gerações antigas e vede:","quem confiou no Senhor e ficou confundido?"],np:1},
{v:12,l:["Quem perseverou nos seus mandamentos e foi abandonado?","Quem o invocou e foi desprezado por ele?"],np:1},
{v:13,l:["Pois o Senhor é piedoso e misericordioso,","perdoa os pecados no dia da tribulação","e protege todos os que o buscam com sinceridade."],np:1},
{v:14,l:["Ai dos corações dobres, dos lábios perversos e das mãos preguiçosas,","e do pecador que anda por dois caminhos!"],np:1},
{v:15,l:["Ai dos corações fracos, que não têm fé:","por isso não serão protegidos!"],np:1},
{v:16,l:["Ai de vós, que perdestes a perseverança,","que deixastes os caminhos retos e vos desviastes por caminhos tortos!"],np:1},
{v:17,l:["Que fareis quando o Senhor vier visitar-vos?"],np:1},
{v:18,l:["Os que temem o Senhor não desobedecem às suas palavras,","e os que o amam guardam os seus caminhos."],np:1},
{v:19,l:["Os que temem o Senhor procuram o que lhe agrada,","e os que o amam se enchem da sua lei."],np:1},
{v:20,l:["Os que temem o Senhor preparam os seus corações","e se santificam na sua presença."],np:1},
{v:21,l:["Os que temem o Senhor guardam os seus mandamentos","e terão paciência até que ele os visite,"],np:1},
{v:22,l:["dizendo: Se não fizermos penitência,","cairemos nas mãos do Senhor, e não nas mãos dos homens;"],np:1,n:"O grego diz: Caiamos nas mãos do Senhor, e não nas mãos dos homens (compare 2 Samuel 24,14)."},
{v:23,l:["pois, como é a sua grandeza,","assim é também a sua misericórdia."],np:1}
];

window.TEXTOS_SEED["eclesiastico"][3] = [
{s:"Deveres para com os pais"},
{v:1,l:["Os filhos da sabedoria são a assembleia dos justos,","e a sua raça é obediência e amor."],n:"Este versículo falta no grego."},
{v:2,l:["Filhos, escutai o juízo de vosso pai","e procedei assim, para que sejais salvos."],np:1},
{v:3,l:["Pois Deus honrou o pai nos filhos","e firmou sobre os filhos o direito da mãe."],np:1},
{v:4,l:["Quem honra o pai expia os pecados,","se abstém deles","e será ouvido na oração de cada dia."],np:1},
{v:5,l:["Como quem ajunta tesouros,","assim é quem honra a sua mãe."],np:1},
{v:6,l:["Quem honra o pai terá alegria nos filhos","e será ouvido no dia da sua oração;"],np:1},
{v:7,l:["quem honra o pai terá vida longa,","e quem obedece ao pai consola a mãe."],np:1},
{v:8,l:["Quem teme o Senhor honra os pais","e serve como a senhores aos que o geraram."],np:1},
{v:9,l:["Honra o teu pai por obras e palavras,"],np:1},
{v:10,l:["para que venha sobre ti a sua bênção."],np:1},
{v:11,l:["A bênção do pai firma a casa dos filhos,","mas a maldição da mãe arranca os seus alicerces."],np:1},
{v:12,l:["Não te glories da desonra do teu pai,","pois a desonra dele não é glória para ti;"],np:1},
{v:13,l:["a glória do homem vem da honra do seu pai,","e uma mãe sem honra é a vergonha do filho."],np:1},
{v:14,l:["Filho, ampara o teu pai na velhice","e não o entristeças durante a sua vida;"],np:1},
{v:15,l:["se ele perder a razão, sê indulgente","e não o desprezes em nenhum dos dias da sua vida.","A caridade feita ao pai não será esquecida:"],np:1},
{v:16,l:["ela te será contada em compensação dos pecados"],np:1},
{v:17,l:["e se tornará para ti um edifício de justiça;","no dia da tribulação ela se lembrará de ti,","e os teus pecados se desfarão como o gelo sob o sol."],np:1},
{v:18,l:["Quão infame é quem abandona o pai,","e maldito por Deus quem irrita a mãe!"],np:1},
{s:"A humildade"},
{v:19,l:["Filho, realiza as tuas obras com mansidão,","e serás amado mais que o homem generoso."]},
{v:20,l:["Quanto maior fores, tanto mais te humilha em tudo,","e encontrarás graça diante de Deus.","Muitos são os grandes e os ilustres,","mas é aos humildes que ele revela os seus segredos."],np:1},
{v:21,l:["Pois grande é o poder só de Deus,","e ele é honrado pelos humildes."],np:1},
{v:22,l:["Não procures o que é alto demais para ti,","nem investigues o que excede as tuas forças;","mas pensa sempre no que Deus te mandou","e não sejas curioso de muitas das suas obras."],np:1},
{v:23,l:["Não tens necessidade","de ver com os teus olhos as coisas ocultas."],np:1},
{v:24,l:["Não te ocupes demais com coisas supérfluas;"],np:1},
{v:25,l:["pois já te foram mostradas muitas coisas que ultrapassam a inteligência humana."],np:1},
{v:26,l:["A muitos a sua presunção enganou,","e uma falsa imaginação lhes desviou o juízo.","Sem pupila falta a luz;","sem conhecimento falta a sabedoria."],np:1},
{s:"O coração obstinado"},
{v:27,l:["O coração duro acabará mal,","e quem ama o perigo nele perecerá."]},
{v:28,l:["O coração que anda por dois caminhos não terá êxito,","e o de coração perverso tropeçará neles."],np:1},
{v:29,l:["O coração perverso se carregará de dores,","e o pecador acrescentará pecado a pecado."],np:1},
{v:30,l:["Para as feridas dos soberbos não há cura,","pois a planta do mal se enraizou neles sem que o percebam."],np:1},
{v:31,l:["O coração do sábio compreende as palavras dos sábios,","e o ouvido atento deseja a sabedoria."],np:1},
{v:32,l:["O coração sábio e inteligente se abstém do pecado","e terá êxito nas obras da justiça."],np:1},
{v:33,l:["A água apaga o fogo ardente,","e a esmola expia os pecados."],np:1},
{v:34,l:["Deus olha para quem retribui um favor;","lembra-se dele no futuro,","e no tempo da queda ele encontrará apoio."],np:1}
];
