// =====================================================================
// Efésios — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["efesios"][1] = [
{s:"Saudação"},
{v:1,t:"Paulo, apóstolo de Cristo Jesus pela vontade de Deus, aos santos que estão em Éfeso e fiéis em Cristo Jesus:",n:"Os melhores manuscritos não trazem em Éfeso, e o tom da carta é o de uma circular endereçada às Igrejas da Ásia. Éfeso era a primeira delas, e cedo lhe deu o nome."},
{v:2,t:"graça a vós e paz, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo."},
{s:"O desígnio de Deus em Cristo"},
{v:3,t:"Bendito seja Deus, Pai de nosso Senhor Jesus Cristo, que nos abençoou com toda bênção espiritual, nos céus, em Cristo."},
{v:4,t:"Nele nos escolheu, antes da criação do mundo, para sermos santos e imaculados diante dele, no amor."},
{v:5,t:"Ele nos predestinou a ser seus filhos adotivos, por Jesus Cristo, segundo o beneplácito da sua vontade,"},
{v:6,t:"para louvor da glória da sua graça, com que nos agraciou no Amado."},
{v:7,t:"Nele temos a redenção pelo seu sangue, a remissão dos pecados, segundo a riqueza da sua graça,"},
{v:8,t:"que ele derramou sobre nós com abundância, em toda sabedoria e inteligência,"},
{v:9,t:"dando-nos a conhecer o mistério da sua vontade, segundo o beneplácito que nele de antemão estabelecera,"},
{v:10,t:"para realizá-lo na plenitude dos tempos: recapitular em Cristo todas as coisas, as que estão nos céus e as que estão na terra.",n:"O verbo grego evoca a soma que se escreve ao pé de uma coluna de números. Tudo o que existe encontra em Cristo o seu total e a sua unidade."},
{v:11,t:"Nele fomos também constituídos herdeiros, predestinados segundo o propósito daquele que tudo realiza conforme o conselho da sua vontade,"},
{v:12,t:"para sermos, nós que primeiro esperamos em Cristo, louvor da sua glória."},
{v:13,t:"Nele também vós, tendo ouvido a palavra da verdade, o Evangelho da vossa salvação, e nele tendo crido, fostes selados com o Espírito Santo da promessa,"},
{v:14,t:"que é o penhor da nossa herança, para a redenção do povo que ele adquiriu, para louvor da sua glória."},
{s:"Oração pelos fiéis"},
{v:15,t:"Por isso também eu, tendo ouvido falar da fé que tendes no Senhor Jesus e do amor para com todos os santos,"},
{v:16,t:"não cesso de dar graças por vós, lembrando-me de vós nas minhas orações,"},
{v:17,t:"para que o Deus de nosso Senhor Jesus Cristo, o Pai da glória, vos dê espírito de sabedoria e de revelação, no seu conhecimento;"},
{v:18,t:"e ilumine os olhos do vosso coração, para saberdes qual é a esperança do seu chamamento, qual a riqueza da glória da sua herança entre os santos,"},
{v:19,t:"e qual a grandeza sem medida do seu poder para conosco, os que cremos, segundo a eficácia da sua força poderosa,"},
{v:20,t:"que ele exerceu em Cristo, ressuscitando-o dos mortos e fazendo-o sentar-se à sua direita, nos céus,"},
{v:21,t:"acima de todo principado, potestade, poder e dominação, e de todo nome que se possa nomear, não só neste século, mas também no vindouro."},
{v:22,t:"Tudo sujeitou debaixo dos seus pés, e o constituiu, acima de tudo, cabeça da Igreja,"},
{v:23,t:"que é o seu corpo, a plenitude daquele que a tudo enche em todas as coisas."}
];

window.TEXTOS_SEED["efesios"][2] = [
{s:"De mortos a vivos pela graça"},
{v:1,t:"E vós estáveis mortos pelas vossas faltas e pecados,"},
{v:2,t:"nos quais outrora andastes, segundo o modo deste mundo, segundo o príncipe do poder do ar, o espírito que agora age nos filhos da rebeldia."},
{v:3,t:"Entre eles também todos nós vivemos outrora, nos desejos da nossa carne, fazendo a vontade da carne e dos pensamentos; e éramos, por natureza, filhos da ira, como os demais."},
{v:4,t:"Mas Deus, que é rico em misericórdia, pelo grande amor com que nos amou,",np:1},
{v:5,t:"estando nós mortos pelas faltas, deu-nos vida com Cristo — é pela graça que fostes salvos —"},
{v:6,t:"e com ele nos ressuscitou e nos fez sentar nos céus, em Cristo Jesus,"},
{v:7,t:"para mostrar, nos séculos vindouros, a riqueza sobreabundante da sua graça, pela bondade que teve para conosco em Cristo Jesus."},
{v:8,t:"Porque é pela graça que fostes salvos, mediante a fé; e isso não vem de vós: é dom de Deus."},
{v:9,t:"Não vem das obras, para que ninguém se glorie."},
{v:10,t:"Somos, com efeito, obra sua, criados em Cristo Jesus para as boas obras que Deus de antemão preparou, a fim de que nelas caminhemos."},
{s:"De dois povos, um só"},
{v:11,t:"Lembrai-vos, pois, de que outrora vós, gentios na carne, chamados incircuncisos pelos que se dizem circuncisos — circuncisão feita na carne, por mão de homem —,"},
{v:12,t:"estáveis naquele tempo sem Cristo, excluídos da cidadania de Israel, estranhos às alianças da promessa, sem esperança e sem Deus no mundo."},
{v:13,t:"Agora, porém, em Cristo Jesus, vós, que outrora estáveis longe, fostes aproximados pelo sangue de Cristo."},
{v:14,t:"Porque ele é a nossa paz: de dois povos fez um só, derrubando na sua carne o muro de separação, a inimizade;",np:1},
{v:15,t:"aboliu a lei dos preceitos com as suas prescrições, para criar em si mesmo, dos dois, um só homem novo, fazendo a paz,"},
{v:16,t:"e para reconciliar ambos com Deus, num só corpo, pela cruz, nela matando a inimizade."},
{v:17,t:"E veio anunciar a paz a vós, que estáveis longe, e a paz aos que estavam perto;"},
{v:18,t:"porque, por ele, uns e outros temos acesso ao Pai, num só Espírito."},
{v:19,t:"Já não sois, portanto, estrangeiros nem hóspedes, mas concidadãos dos santos e membros da casa de Deus,",np:1},
{v:20,t:"edificados sobre o fundamento dos apóstolos e dos profetas, sendo o próprio Cristo Jesus a pedra angular."},
{v:21,t:"Nele toda a construção, harmoniosamente ajustada, cresce para ser templo santo no Senhor;"},
{v:22,t:"nele também vós sois edificados juntamente, para serdes morada de Deus no Espírito."}
];

window.TEXTOS_SEED["efesios"][3] = [
{s:"O mistério confiado a Paulo"},
{v:1,t:"Por isso eu, Paulo, prisioneiro de Cristo Jesus por vós, gentios —"},
{v:2,t:"se é que ouvistes falar da dispensação da graça de Deus, que me foi dada em vosso favor:"},
{v:3,t:"por revelação me foi dado a conhecer o mistério, como acima vos escrevi em poucas palavras."},
{v:4,t:"Lendo-o, podeis perceber a inteligência que tenho do mistério de Cristo,"},
{v:5,t:"o qual, nas gerações passadas, não foi dado a conhecer aos filhos dos homens, como agora foi revelado, no Espírito, aos seus santos apóstolos e profetas:"},
{v:6,t:"que os gentios são coerdeiros, membros do mesmo corpo e participantes da promessa, em Cristo Jesus, pelo Evangelho,"},
{v:7,t:"do qual me tornei ministro, por dom da graça de Deus, a mim concedida segundo a eficácia do seu poder."},
{v:8,t:"A mim, o menor de todos os santos, foi dada esta graça: anunciar aos gentios a insondável riqueza de Cristo,",np:1},
{v:9,t:"e esclarecer a todos qual seja a dispensação do mistério escondido desde os séculos em Deus, que tudo criou;"},
{v:10,t:"para que, agora, pela Igreja, a multiforme sabedoria de Deus seja dada a conhecer aos principados e potestades, nos céus,"},
{v:11,t:"segundo o desígnio eterno que realizou em Cristo Jesus, nosso Senhor,"},
{v:12,t:"no qual temos, pela fé nele, a ousadia de nos aproximarmos com confiança."},
{v:13,t:"Por isso vos peço que não desanimeis nas tribulações que padeço por vós: elas são a vossa glória."},
{s:"Oração pela Igreja"},
{v:14,t:"Por isso dobro os joelhos diante do Pai,"},
{v:15,t:"de quem toda família, nos céus e na terra, recebe o nome,"},
{v:16,t:"para que vos conceda, segundo a riqueza da sua glória, que sejais robustecidos com força, pelo seu Espírito, no homem interior;"},
{v:17,t:"que Cristo habite pela fé nos vossos corações; e que, arraigados e fundados no amor,"},
{v:18,t:"possais compreender, com todos os santos, qual seja a largura e o comprimento, a altura e a profundidade,"},
{v:19,t:"e conhecer o amor de Cristo, que excede todo conhecimento, para serdes cheios de toda a plenitude de Deus."},
{v:20,t:"Àquele que pode fazer infinitamente mais do que tudo quanto pedimos ou pensamos, segundo o poder que age em nós,",np:1},
{v:21,t:"a ele seja a glória, na Igreja e em Cristo Jesus, por todas as gerações, pelos séculos dos séculos. Amém."}
];

window.TEXTOS_SEED["efesios"][4] = [
{s:"A unidade do corpo"},
{v:1,t:"Exorto-vos, pois, eu, prisioneiro no Senhor, a caminhardes de modo digno do chamamento que recebestes:"},
{v:2,t:"com toda humildade e mansidão, com paciência, suportando-vos uns aos outros no amor,"},
{v:3,t:"empenhados em conservar a unidade do Espírito pelo vínculo da paz."},
{v:4,t:"Há um só corpo e um só Espírito, como também fostes chamados a uma só esperança, a do vosso chamamento."},
{v:5,t:"Um só Senhor, uma só fé, um só batismo;"},
{v:6,t:"um só Deus e Pai de todos, que está acima de todos, age por todos e habita em todos."},
{v:7,t:"A cada um de nós foi dada a graça segundo a medida do dom de Cristo.",np:1},
{v:8,l:["Por isso diz:","Subindo ao alto, levou cativo o cativeiro","e deu dons aos homens."]},
{v:9,t:"Ora, que quer dizer subiu, senão que primeiro havia descido às regiões inferiores da terra?",np:1},
{v:10,t:"Aquele que desceu é o mesmo que subiu acima de todos os céus, para encher todas as coisas."},
{v:11,t:"E ele mesmo constituiu uns apóstolos, outros profetas, outros evangelistas, outros pastores e mestres,"},
{v:12,t:"para o aperfeiçoamento dos santos, para a obra do ministério, para a edificação do corpo de Cristo,"},
{v:13,t:"até que todos cheguemos à unidade da fé e do conhecimento do Filho de Deus, ao estado de homem perfeito, à medida da plena estatura de Cristo."},
{v:14,t:"Assim não seremos mais crianças, levados ao sabor das ondas e arrastados por todo vento de doutrina, pela astúcia dos homens e pela esperteza que conduz ao erro."},
{v:15,t:"Antes, vivendo a verdade no amor, cresçamos em tudo naquele que é a cabeça, Cristo."},
{v:16,t:"Dele o corpo inteiro, bem ajustado e unido por todas as junturas que o sustentam, segundo a atividade própria de cada membro, recebe o crescimento, para edificar-se no amor."},
{s:"Despir o homem velho"},
{v:17,t:"Digo-vos, pois, e vos conjuro no Senhor: não caminheis mais como os gentios, que caminham na vaidade dos seus pensamentos,"},
{v:18,t:"obscurecidos na inteligência, alheios à vida de Deus, por causa da ignorância que neles há e do endurecimento do seu coração."},
{v:19,t:"Tornados insensíveis, entregaram-se à devassidão, à prática ávida de toda impureza."},
{v:20,t:"Não foi assim que aprendestes a Cristo,"},
{v:21,t:"se é que o ouvistes e nele fostes instruídos, segundo a verdade que está em Jesus:"},
{v:22,t:"que deveis despojar-vos do homem velho, do vosso modo antigo de viver, corrompido pelas concupiscências enganadoras,"},
{v:23,t:"renovar-vos no espírito da vossa mente,"},
{v:24,t:"e revestir-vos do homem novo, criado segundo Deus na justiça e na santidade da verdade."},
{s:"Regras da vida nova"},
{v:25,t:"Por isso, deixando a mentira, fale cada um a verdade ao seu próximo, porque somos membros uns dos outros."},
{v:26,t:"Irai-vos, mas não pequeis; não se ponha o sol sobre a vossa ira,"},
{v:27,t:"nem deis lugar ao diabo."},
{v:28,t:"Quem furtava, não furte mais; trabalhe antes, fazendo com as próprias mãos algo de bom, para ter o que repartir com quem passa necessidade."},
{v:29,t:"Não saia da vossa boca nenhuma palavra má, mas apenas a que for boa para edificar, quando convier, e fazer bem aos que ouvem."},
{v:30,t:"E não entristeçais o Espírito Santo de Deus, com o qual fostes selados para o dia da redenção."},
{v:31,t:"Toda amargura, ira, indignação, gritaria e maledicência sejam banidas de entre vós, com toda malícia."},
{v:32,t:"Sede antes benignos uns para com os outros, compassivos, perdoando-vos mutuamente, como também Deus vos perdoou em Cristo."}
];

window.TEXTOS_SEED["efesios"][5] = [
{s:"Filhos da luz"},
{v:1,t:"Sede, pois, imitadores de Deus, como filhos amados,"},
{v:2,t:"e caminhai no amor, como também Cristo nos amou e se entregou por nós, como oferenda e sacrifício de suave odor a Deus."},
{v:3,t:"Quanto à fornicação e a toda impureza ou avareza, nem sequer se mencionem entre vós, como convém a santos;"},
{v:4,t:"nem torpezas, nem conversas tolas ou chocarreiras, que não vêm a propósito, mas antes ações de graças."},
{v:5,t:"Porque bem sabeis: nenhum fornicador, impuro ou avarento — que é idólatra — tem herança no Reino de Cristo e de Deus."},
{v:6,t:"Ninguém vos engane com palavras vãs; porque é por essas coisas que vem a ira de Deus sobre os filhos da rebeldia."},
{v:7,t:"Não vos façais, pois, cúmplices deles."},
{v:8,t:"Outrora éreis trevas, mas agora sois luz no Senhor: caminhai como filhos da luz.",np:1},
{v:9,t:"Porque o fruto da luz está em toda bondade, justiça e verdade."},
{v:10,t:"Procurai discernir o que é agradável ao Senhor."},
{v:11,t:"E não tomeis parte nas obras infrutuosas das trevas; ao contrário, denunciai-as."},
{v:12,t:"Porque o que eles fazem às ocultas é vergonhoso até de dizer."},
{v:13,t:"Mas tudo o que é denunciado fica manifesto pela luz,"},
{v:14,t:"e tudo o que se manifesta é luz. Por isso se diz: Desperta, tu que dormes, levanta-te dentre os mortos, e Cristo te iluminará.",n:"A fórmula parece ser de um hino batismal da Igreja primitiva. O batizado era chamado iluminado, e a cerimônia se fazia de madrugada."},
{v:15,t:"Vede, pois, com cuidado como andais: não como insensatos, mas como sábios,",np:1},
{v:16,t:"aproveitando bem o tempo, porque os dias são maus."},
{v:17,t:"Por isso não sejais imprudentes, mas compreendei qual é a vontade do Senhor."},
{v:18,t:"E não vos embriagueis com vinho, que leva à devassidão; enchei-vos antes do Espírito."},
{v:19,t:"Falai entre vós com salmos, hinos e cânticos espirituais, cantando e salmodiando de coração ao Senhor."},
{v:20,t:"Dai graças sempre e por tudo a Deus Pai, em nome de nosso Senhor Jesus Cristo."},
{s:"Marido e mulher, à imagem de Cristo e da Igreja"},
{v:21,t:"Submetei-vos uns aos outros no temor de Cristo."},
{v:22,t:"As mulheres sejam submissas aos maridos, como ao Senhor,"},
{v:23,t:"porque o marido é cabeça da mulher, como Cristo é cabeça da Igreja, ele, o salvador do corpo."},
{v:24,t:"Ora, como a Igreja é submissa a Cristo, assim também o sejam em tudo as mulheres aos maridos."},
{v:25,t:"Maridos, amai as vossas mulheres, como também Cristo amou a Igreja e se entregou por ela,",np:1},
{v:26,t:"para a santificar, purificando-a pelo banho da água, com a palavra,"},
{v:27,t:"a fim de apresentar a si mesmo a Igreja gloriosa, sem mancha nem ruga nem coisa semelhante, mas santa e imaculada."},
{v:28,t:"Assim devem os maridos amar as suas mulheres, como aos próprios corpos. Quem ama a sua mulher, ama-se a si mesmo."},
{v:29,t:"Ninguém jamais odiou a própria carne; ao contrário, alimenta-a e cuida dela, como também Cristo faz à Igreja,"},
{v:30,t:"porque somos membros do seu corpo."},
{v:31,t:"Por isso deixará o homem o pai e a mãe, e se unirá à sua mulher, e os dois serão uma só carne."},
{v:32,t:"Grande é este mistério — digo-o em relação a Cristo e à Igreja."},
{v:33,t:"De resto, ame cada um de vós a sua mulher como a si mesmo; e a mulher respeite o marido."}
];

window.TEXTOS_SEED["efesios"][6] = [
{s:"Filhos e pais, servos e senhores"},
{v:1,t:"Filhos, obedecei a vossos pais no Senhor, porque isso é justo."},
{v:2,t:"Honra teu pai e tua mãe — é este o primeiro mandamento acompanhado de promessa —"},
{v:3,t:"para que sejas feliz e tenhas longa vida sobre a terra."},
{v:4,t:"E vós, pais, não irriteis os vossos filhos; criai-os antes na disciplina e na instrução do Senhor."},
{v:5,t:"Servos, obedecei aos vossos senhores segundo a carne, com temor e respeito, na simplicidade do vosso coração, como a Cristo;",np:1},
{v:6,t:"não servindo só quando observados, para agradar aos homens, mas como servos de Cristo, fazendo de coração a vontade de Deus."},
{v:7,t:"Servi de boa vontade, como ao Senhor e não aos homens,"},
{v:8,t:"sabendo que cada um, escravo ou livre, receberá do Senhor o bem que tiver feito."},
{v:9,t:"E vós, senhores, procedei do mesmo modo para com eles, deixando as ameaças, sabendo que tanto eles como vós tendes um Senhor nos céus, e que nele não há acepção de pessoas."},
{s:"A armadura de Deus"},
{v:10,t:"Enfim, fortalecei-vos no Senhor e no seu poder soberano."},
{v:11,t:"Revesti-vos da armadura de Deus, para poderdes resistir às ciladas do diabo."},
{v:12,t:"Porque não é contra a carne e o sangue que temos de lutar, mas contra os principados, contra as potestades, contra os dominadores deste mundo de trevas, contra os espíritos do mal que estão nos céus."},
{v:13,t:"Tomai, pois, a armadura de Deus, para poderdes resistir no dia mau e permanecer de pé, depois de tudo superado."},
{v:14,t:"Ficai firmes, então: cingi os rins com a verdade, revesti a couraça da justiça,"},
{v:15,t:"e calçai os pés com o zelo pelo Evangelho da paz."},
{v:16,t:"Sobretudo, empunhai o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno."},
{v:17,t:"Tomai também o capacete da salvação e a espada do Espírito, que é a palavra de Deus."},
{v:18,t:"Orai sempre no Espírito, com toda sorte de orações e súplicas; e, para isso, vigiai com toda perseverança, suplicando por todos os santos —",np:1},
{v:19,t:"e também por mim, para que me seja dada a palavra, ao abrir a boca, a fim de anunciar com ousadia o mistério do Evangelho,"},
{v:20,t:"do qual sou embaixador em cadeias, para que eu fale dele com a ousadia que devo ter."},
{s:"Saudações finais"},
{v:21,t:"Para que também vós saibais da minha situação e do que faço, Tíquico, o irmão amado e fiel ministro no Senhor, vos informará de tudo."},
{v:22,t:"Eu vo-lo envio para isto mesmo: para que saibais o que nos vai e para que ele console os vossos corações."},
{v:23,t:"Paz aos irmãos, e amor com fé, da parte de Deus Pai e do Senhor Jesus Cristo."},
{v:24,t:"A graça esteja com todos os que amam a nosso Senhor Jesus Cristo com amor incorruptível."}
];
