// =====================================================================
// Esdras — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["esdras"][1] = [
{s:"O edito de Ciro"},
{v:1,t:"No primeiro ano de Ciro, rei da Pérsia, para que se cumprisse a palavra do Senhor dita pela boca de Jeremias, o Senhor despertou o espírito de Ciro, rei da Pérsia, que mandou publicar em todo o seu reino, de viva voz e por escrito, esta proclamação:",n:"Em 538 antes de Cristo, logo depois da conquista da Babilônia. O livro de Esdras continua as Crônicas e repete o seu final (2 Crônicas 36,22-23). Ciro permitia aos povos deportados voltar às suas terras e restaurar os seus cultos, como confirma um cilindro de argila com uma inscrição sua. Isaías o chamou ungido do Senhor (Isaías 45,1)."},
{v:2,t:"Assim diz Ciro, rei da Pérsia: O Senhor, o Deus do céu, deu-me todos os reinos da terra, e ele me encarregou de lhe construir uma casa em Jerusalém, que está em Judá."},
{v:3,t:"Quem dentre vós pertence a todo o seu povo? Que o seu Deus esteja com ele, e que suba a Jerusalém, que está em Judá, e construa a casa do Senhor, Deus de Israel: ele é o Deus que está em Jerusalém."},
{v:4,t:"E todos os que restarem, em qualquer lugar onde morem, sejam ajudados pela gente do lugar com prata, ouro, bens e gado, além das ofertas voluntárias para a casa de Deus que está em Jerusalém.",n:"Como os israelitas, ao sair do Egito, receberam dos egípcios objetos de prata e de ouro (Êxodo 12,35-36): a volta do exílio é um novo êxodo."},
{s:"A volta dos exilados"},
{v:5,t:"Então os chefes das famílias de Judá e de Benjamim, os sacerdotes e os levitas, e todos aqueles cujo espírito Deus tinha despertado, levantaram-se para subir e construir a casa do Senhor, que está em Jerusalém.",np:1},
{v:6,t:"E todos os seus vizinhos os ajudaram com objetos de prata e de ouro, bens, gado e presentes, além de todas as ofertas voluntárias."},
{v:7,t:"O rei Ciro devolveu também os objetos da casa do Senhor que Nabucodonosor tinha levado de Jerusalém e posto no templo do seu deus."},
{v:8,t:"Ciro, rei da Pérsia, mandou-os tirar por meio de Mitridates, o tesoureiro, que os contou e entregou a Sasabassar, príncipe de Judá.",n:"Sasabassar, nome babilônico, era talvez um filho de Joaquin, o Senaser de 1 Crônicas 3,18. O seu papel passará logo a Zorobabel."},
{v:9,t:"Esta é a sua lista: trinta bacias de ouro, mil bacias de prata, vinte e nove facas, trinta taças de ouro,"},
{v:10,t:"quatrocentas e dez taças de prata e muitos outros objetos:"},
{v:11,t:"ao todo, cinco mil e quatrocentos objetos de ouro e de prata. Sasabassar levou tudo isso, quando os exilados subiram da Babilônia para Jerusalém.",n:"O total não corresponde à soma dos números anteriores: o texto sofreu na transmissão."}
];

window.TEXTOS_SEED["esdras"][2] = [
{s:"A lista dos que voltaram do exílio"},
{v:1,t:"Estes são os filhos da província que voltaram do cativeiro, dentre os exilados que Nabucodonosor, rei da Babilônia, tinha deportado para a Babilônia, e que voltaram para Jerusalém e para Judá, cada um para a sua cidade.",n:"A província: Judá, agora uma pequena província do império persa. A lista, repetida em Neemias 7, reúne talvez os que voltaram em várias levas, até o tempo de Neemias."},
{v:2,t:"Vieram com Zorobabel, Josué, Neemias, Saraías, Reelaías, Mardoqueu, Belsã, Mesfar, Beguai, Reum e Baana. Este é o número dos homens do povo de Israel:",n:"Onze nomes, doze em Neemias 7,7: um para cada tribo. Zorobabel, neto de Joaquin, é da linhagem de Davi; Josué é o sumo sacerdote (3,2). O Neemias e o Mardoqueu daqui não são os dos livros de Neemias e de Ester."},
{v:3,t:"os filhos de Farós, dois mil cento e setenta e dois;",np:1},
{v:4,t:"os filhos de Safatias, trezentos e setenta e dois;"},
{v:5,t:"os filhos de Area, setecentos e setenta e cinco;"},
{v:6,t:"os filhos de Faat-Moab, isto é, os filhos de Jesua e de Joab, dois mil oitocentos e doze;"},
{v:7,t:"os filhos de Elam, mil duzentos e cinquenta e quatro;"},
{v:8,t:"os filhos de Zetua, novecentos e quarenta e cinco;"},
{v:9,t:"os filhos de Zacai, setecentos e sessenta;"},
{v:10,t:"os filhos de Bani, seiscentos e quarenta e dois;"},
{v:11,t:"os filhos de Bebai, seiscentos e vinte e três;"},
{v:12,t:"os filhos de Azgad, mil duzentos e vinte e dois;"},
{v:13,t:"os filhos de Adonicam, seiscentos e sessenta e seis;"},
{v:14,t:"os filhos de Beguai, dois mil e cinquenta e seis;"},
{v:15,t:"os filhos de Adin, quatrocentos e cinquenta e quatro;"},
{v:16,t:"os filhos de Ater, da família de Ezequias, noventa e oito;"},
{v:17,t:"os filhos de Besai, trezentos e vinte e três;"},
{v:18,t:"os filhos de Jora, cento e doze;"},
{v:19,t:"os filhos de Hasum, duzentos e vinte e três;"},
{v:20,t:"os filhos de Gebar, noventa e cinco;"},
{v:21,t:"os filhos de Belém, cento e vinte e três;",n:"A partir daqui, a lista segue as cidades de origem."},
{v:22,t:"os homens de Netofa, cinquenta e seis;"},
{v:23,t:"os homens de Anatot, cento e vinte e oito;"},
{v:24,t:"os filhos de Azmavet, quarenta e dois;"},
{v:25,t:"os filhos de Cariat-Iarim, de Cafira e de Berot, setecentos e quarenta e três;"},
{v:26,t:"os filhos de Ramá e de Gaba, seiscentos e vinte e um;"},
{v:27,t:"os homens de Macmas, cento e vinte e dois;"},
{v:28,t:"os homens de Betel e de Hai, duzentos e vinte e três;"},
{v:29,t:"os filhos de Nebo, cinquenta e dois;"},
{v:30,t:"os filhos de Megbis, cento e cinquenta e seis;"},
{v:31,t:"os filhos do outro Elam, mil duzentos e cinquenta e quatro;"},
{v:32,t:"os filhos de Harim, trezentos e vinte;"},
{v:33,t:"os filhos de Lod, de Hadid e de Ono, setecentos e vinte e cinco;"},
{v:34,t:"os filhos de Jericó, trezentos e quarenta e cinco;"},
{v:35,t:"os filhos de Senaá, três mil seiscentos e trinta."},
{v:36,t:"Os sacerdotes: os filhos de Jedaías, da casa de Jesua, novecentos e setenta e três;",np:1},
{v:37,t:"os filhos de Emer, mil e cinquenta e dois;"},
{v:38,t:"os filhos de Fassur, mil duzentos e quarenta e sete;"},
{v:39,t:"os filhos de Harim, mil e dezessete.",n:"Só quatro famílias sacerdotais, das vinte e quatro de 1 Crônicas 24; mas numerosas: um décimo dos que voltaram."},
{v:40,t:"Os levitas: os filhos de Jesua, isto é, os filhos de Cadmiel, de Benui e de Odovias, setenta e quatro.",np:1,n:"Poucos levitas voltaram, em comparação com os sacerdotes; Esdras terá de procurá-los (8,15-20)."},
{v:41,t:"Os cantores: os filhos de Asaf, cento e vinte e oito."},
{v:42,t:"Os porteiros: os filhos de Selum, os filhos de Ater, os filhos de Telmon, os filhos de Acub, os filhos de Hatita, os filhos de Sobai: ao todo, cento e trinta e nove."},
{v:43,t:"Os natineus: os filhos de Siá, os filhos de Hasufa, os filhos de Tabaot,",np:1,n:"Os natineus, isto é, os doados, eram servidores do templo (ver 1 Crônicas 9,2)."},
{v:44,t:"os filhos de Queros, os filhos de Siaa, os filhos de Fadon,"},
{v:45,t:"os filhos de Lebana, os filhos de Hagaba, os filhos de Acub,"},
{v:46,t:"os filhos de Hagab, os filhos de Semlai, os filhos de Hanã,"},
{v:47,t:"os filhos de Gidel, os filhos de Gaer, os filhos de Raaías,"},
{v:48,t:"os filhos de Rasin, os filhos de Necoda, os filhos de Gazam,"},
{v:49,t:"os filhos de Oza, os filhos de Faseia, os filhos de Besai,"},
{v:50,t:"os filhos de Asena, os filhos dos meunitas, os filhos dos nefuseus,"},
{v:51,t:"os filhos de Bacbuc, os filhos de Hacufa, os filhos de Harur,"},
{v:52,t:"os filhos de Baslut, os filhos de Maida, os filhos de Harsa,"},
{v:53,t:"os filhos de Barcos, os filhos de Sísara, os filhos de Tema,"},
{v:54,t:"os filhos de Nasias, os filhos de Hatifa."},
{v:55,t:"Os filhos dos servos de Salomão: os filhos de Sotai, os filhos de Soferet, os filhos de Feruda,",np:1,n:"Os servos de Salomão: descendentes dos estrangeiros que Salomão pôs a trabalhar nas obras do templo (1 Reis 9,20-21)."},
{v:56,t:"os filhos de Jaala, os filhos de Darcon, os filhos de Gidel,"},
{v:57,t:"os filhos de Safatias, os filhos de Hatil, os filhos de Foqueret-Hasebaim, os filhos de Ami."},
{v:58,t:"Ao todo, os natineus e os filhos dos servos de Salomão eram trezentos e noventa e dois."},
{v:59,t:"Estes são os que vieram de Tel-Mela, de Tel-Harsa, de Querub, de Adon e de Emer, e não puderam provar se a sua família e a sua descendência eram de Israel:",np:1},
{v:60,t:"os filhos de Dalaías, os filhos de Tobias, os filhos de Necoda, seiscentos e cinquenta e dois."},
{v:61,t:"E, entre os filhos dos sacerdotes, os filhos de Hobias, os filhos de Acos e os filhos de Berzelai, que tinha tomado por mulher uma das filhas de Berzelai, o galaadita, e foi chamado pelo nome deles.",n:"Berzelai, o galaadita, que socorreu Davi na fuga diante de Absalão (2 Samuel 19,32-40). O genro tomou o nome da família da mulher."},
{v:62,t:"Estes procuraram o seu registro nas genealogias, mas não o encontraram, e foram excluídos do sacerdócio como impuros."},
{v:63,t:"O governador disse-lhes que não comessem das coisas santíssimas enquanto não se apresentasse um sacerdote para consultar os Urim e os Tumim.",n:"O governador: em persa, tirshata, título de Sasabassar ou de Zorobabel. Os Urim e os Tumim eram as sortes sagradas com que o sumo sacerdote consultava a Deus (Êxodo 28,30); depois do exílio já não se usavam."},
{v:64,t:"Toda a assembleia era de quarenta e dois mil trezentos e sessenta,",np:1,n:"A soma das cifras da lista dá cerca de trinta mil: talvez o total inclua grupos não enumerados."},
{v:65,t:"sem contar os seus servos e servas, que eram sete mil trezentos e trinta e sete; tinham também duzentos cantores e cantoras."},
{v:66,t:"Tinham setecentos e trinta e seis cavalos, duzentas e quarenta e cinco mulas,"},
{v:67,t:"quatrocentos e trinta e cinco camelos e seis mil setecentos e vinte jumentos."},
{v:68,t:"Alguns chefes de famílias, quando chegaram à casa do Senhor, em Jerusalém, fizeram ofertas voluntárias para a casa de Deus, para reconstruí-la no seu lugar.",np:1},
{v:69,t:"Deram ao tesouro da obra, segundo as suas posses, sessenta e um mil dracmas de ouro, cinco mil minas de prata e cem túnicas sacerdotais."},
{v:70,t:"Os sacerdotes, os levitas e uma parte do povo habitaram ali; os cantores, os porteiros e os natineus nas suas cidades, e todo o Israel nas suas cidades."}
];

window.TEXTOS_SEED["esdras"][3] = [
{s:"A reconstrução do altar"},
{v:1,t:"Quando chegou o sétimo mês, estando os filhos de Israel nas suas cidades, o povo reuniu-se como um só homem em Jerusalém.",n:"O sétimo mês era o das grandes festas: o dia das Aclamações, o dia da Expiação e a festa das Tendas (Levítico 23,23-43)."},
{v:2,t:"Então Josué, filho de Josedec, com os seus irmãos, os sacerdotes, e Zorobabel, filho de Salatiel, com os seus irmãos, puseram-se a construir o altar do Deus de Israel, para oferecerem sobre ele holocaustos, como está escrito na lei de Moisés, homem de Deus.",n:"Josué, em hebraico Jesua, forma tardia do mesmo nome, é o sumo sacerdote, filho de Josedec, que foi deportado, e neto de Saraías, o último sumo sacerdote antes do exílio (1 Crônicas 5,40-41; 2 Reis 25,18-21). Ageu e Zacarias o chamam Josué (Ageu 1,1; Zacarias 3,1)."},
{v:3,t:"Assentaram o altar sobre os seus alicerces, apesar do medo que tinham dos povos das terras vizinhas, e ofereceram sobre ele holocaustos ao Senhor, os holocaustos da manhã e da tarde."},
{v:4,t:"Celebraram a festa das Tendas, como está escrito, e ofereceram holocaustos cada dia, segundo o número prescrito para cada dia;"},
{v:5,t:"e depois disso, o holocausto perpétuo, os das luas novas e de todas as festas consagradas ao Senhor, e os de todos os que faziam ofertas voluntárias ao Senhor."},
{v:6,t:"Desde o primeiro dia do sétimo mês começaram a oferecer holocaustos ao Senhor, embora os alicerces do templo de Deus ainda não tivessem sido lançados."},
{s:"Os alicerces do templo"},
{v:7,t:"Deram dinheiro aos cortadores de pedra e aos carpinteiros, e comida, bebida e azeite aos sidônios e aos tírios, para que trouxessem madeira de cedro do Líbano, por mar, até Jope, conforme a autorização que Ciro, rei da Pérsia, lhes tinha dado.",np:1,n:"Como para o primeiro templo (1 Crônicas 22,4; 2 Crônicas 2,15)."},
{v:8,t:"No segundo mês do segundo ano da sua chegada à casa de Deus, em Jerusalém, Zorobabel, filho de Salatiel, e Josué, filho de Josedec, com o resto dos seus irmãos, os sacerdotes e os levitas, e todos os que tinham voltado do cativeiro para Jerusalém, começaram a obra; e encarregaram os levitas de vinte anos para cima de dirigir os trabalhos da casa do Senhor."},
{v:9,t:"Jesua, com os seus filhos e os seus irmãos, e Cadmiel, Benui e Odovias, como um só homem, dirigiam os que trabalhavam na casa de Deus; e também os filhos de Henadad, com os seus filhos e os seus irmãos, levitas.",n:"Este Jesua é o levita de 2,40, não o sumo sacerdote."},
{v:10,t:"Quando os construtores lançaram os alicerces do templo do Senhor, os sacerdotes, com as suas vestes, puseram-se de pé com as trombetas, e os levitas, filhos de Asaf, com os címbalos, para louvar o Senhor, segundo as disposições de Davi, rei de Israel.",np:1},
{v:11,t:"E cantavam, louvando e dando graças ao Senhor: Porque ele é bom, porque é eterna a sua misericórdia para com Israel! E todo o povo erguia grandes aclamações, louvando o Senhor, porque tinham sido lançados os alicerces da casa do Senhor."},
{v:12,t:"Muitos dos sacerdotes, dos levitas e dos chefes de famílias, já idosos, que tinham visto o primeiro templo no seu lugar, choravam em alta voz, enquanto muitos outros erguiam a voz em aclamações de alegria.",n:"Os velhos que tinham visto o templo de Salomão, destruído cinquenta anos antes, choram diante da modéstia da nova obra (Ageu 2,3)."},
{v:13,t:"E ninguém podia distinguir o clamor das aclamações de alegria do clamor do choro do povo, porque o povo erguia grandes aclamações, e o ruído se ouvia de longe."}
];
