// =====================================================================
// Ester — tradução do hebraico; as partes que só existem em grego ou em latim
// (versículos com letra) seguem a Nova Vulgata, cotejada com o grego
// (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["ester"][1] = [
{s:"O sonho de Mardoqueu"},
{v:"1a",t:"No segundo ano do reinado do grande rei Artaxerxes, no primeiro dia do mês de Nisan, teve um sonho Mardoqueu, filho de Jair, filho de Semei, filho de Cis, da tribo de Benjamim,",n:"O livro de Ester chegou até nós em duas formas: o texto hebraico, mais breve, que nunca menciona o nome de Deus, e a tradução grega, que acrescenta seis trechos maiores (o sonho de Mardoqueu, as duas cartas do rei, as orações de Mardoqueu e de Ester, a entrada de Ester diante do rei e a explicação do sonho) e várias frases menores. São Jerônimo traduziu o hebraico e reuniu os acréscimos no fim do livro (10,4–16,24 da antiga Vulgata); a Nova Vulgata os recoloca no seu lugar, com números de versículo seguidos de letra. Nesta tradução, as partes hebraicas vêm do hebraico; as partes marcadas com letra seguem o texto latino da Nova Vulgata, que nelas acompanha muitas vezes a antiga versão latina, anterior a São Jerônimo, e foram cotejadas com o grego. Estes versículos 1a–1k estavam em 11,2–12 na antiga Vulgata. O grego chama o rei de Artaxerxes; o hebraico, de Assuero (veja a nota a 1,1)."},
{v:"1b",t:"homem importante, que servia na corte do rei."},
{v:"1c",t:"Este foi o seu sonho: houve vozes e tumulto, trovões e terremoto, e grande confusão sobre a terra.",np:1},
{v:"1d",t:"E eis que avançaram dois grandes dragões, ambos prontos para lutar;"},
{v:"1e",t:"travou-se entre eles uma grande batalha, e eles dominavam, e as nações se reuniram",n:"O grego diz: deram um grande rugido, e ao seu rugido todas as nações se prepararam para a guerra, para combater a nação dos justos. A Nova Vulgata segue aqui a antiga versão latina."},
{v:"1f",t:"num dia de trevas e de desgraça; e houve grande perturbação entre os habitantes da terra."},
{v:"1g",t:"Tiveram medo de ser destruídos",n:"O grego precisa: toda a nação dos justos se perturbou, temendo os males que a ameaçavam, e preparou-se para morrer."},
{v:"1h",t:"e clamaram a Deus. E do som do seu clamor nasceu uma pequena fonte, que cresceu até se tornar um rio muito grande e transbordou em águas abundantes."},
{v:"1i",t:"A luz e o sol se levantaram; os humildes foram exaltados e devoraram os ilustres.",np:1},
{v:"1k",t:"Quando Mardoqueu, depois de ver esse sonho, se levantou do leito, pôs-se a pensar no que Deus queria fazer; e guardou o sonho gravado no espírito até que lhe fosse revelado.",np:1,n:"O grego acrescenta aqui a conspiração de dois eunucos do rei, descoberta por Mardoqueu, e o ódio que Amã passou a ter por ele (12,1–6 na antiga Vulgata); o mesmo episódio é narrado pelo hebraico em 2,21–23. A Nova Vulgata não traz esse trecho."},
{s:"O banquete do rei Assuero"},
{v:1,t:"Nos dias de Assuero — o Assuero que reinou desde a Índia até a Etiópia, sobre cento e vinte e sete províncias —,",n:"Assuero é o nome hebraico de Xerxes I, rei da Pérsia de 486 a 465 a.C. A Índia é a região do rio Indo; a Etiópia (em hebraico, Cuch) é a Núbia, ao sul do Egito."},
{v:2,t:"naqueles dias, quando o rei Assuero se sentava no trono do seu reino, na cidadela de Susa,"},
{v:3,t:"no terceiro ano do seu reinado, ele deu um banquete a todos os seus príncipes e servidores; o exército da Pérsia e da Média, os nobres e os governadores das províncias estavam na sua presença,"},
{v:4,t:"enquanto ele mostrava a riqueza gloriosa do seu reino e o esplendor magnífico da sua grandeza, durante muitos dias: cento e oitenta dias."},
{v:5,t:"Terminados esses dias, o rei deu a todo o povo que se encontrava na cidadela de Susa, do maior ao menor, um banquete de sete dias no pátio do jardim do palácio real.",np:1},
{v:6,t:"Havia tapeçarias de linho branco, de algodão e de púrpura violeta, presas por cordões de linho fino e de púrpura a argolas de prata e a colunas de mármore; havia leitos de ouro e de prata sobre um pavimento de pórfiro e de mármore, de nácar e de pedras coloridas.",n:"Os nomes das pedras do pavimento são raros e de sentido incerto."},
{v:7,t:"Serviam-se as bebidas em taças de ouro, cada uma diferente da outra, e o vinho real corria em abundância, conforme a generosidade do rei."},
{v:8,t:"E bebia-se conforme a regra: ninguém era obrigado; pois o rei tinha ordenado a todos os mordomos do seu palácio que fizessem conforme a vontade de cada um."},
{v:9,t:"Também a rainha Vasti deu um banquete para as mulheres, no palácio real do rei Assuero.",np:1},
{s:"A rainha Vasti é deposta"},
{v:10,t:"No sétimo dia, quando o coração do rei estava alegre com o vinho, ele ordenou a Maumã, Bazata, Harbona, Bagata, Abgata, Zetar e Carcas, os sete eunucos que serviam na presença do rei Assuero,"},
{v:11,t:"que trouxessem à presença do rei a rainha Vasti, com a coroa real, para mostrar aos povos e aos príncipes a sua beleza, pois era muito formosa."},
{v:12,t:"Mas a rainha Vasti recusou-se a vir, como o rei lhe mandara dizer pelos eunucos. O rei enfureceu-se muito, e a sua ira ardeu dentro dele.",np:1},
{v:13,t:"Então o rei consultou os sábios que conheciam os tempos (pois era assim que se tratavam os assuntos do rei, diante de todos os que conheciam a lei e o direito,"},
{v:14,t:"e os mais próximos dele eram Carsena, Setar, Admata, Társis, Mares, Marsana e Mamucã, os sete príncipes da Pérsia e da Média, que viam a face do rei e ocupavam os primeiros lugares no reino):"},
{v:15,t:"Segundo a lei, que se deve fazer à rainha Vasti, por não ter cumprido a ordem do rei Assuero, transmitida pelos eunucos?"},
{v:16,t:"Mamucã respondeu diante do rei e dos príncipes: A rainha Vasti não ofendeu somente o rei, mas também todos os príncipes e todos os povos que há em todas as províncias do rei Assuero.",np:1},
{v:17,t:"Pois o procedimento da rainha chegará ao conhecimento de todas as mulheres, e elas passarão a desprezar os seus maridos, dizendo: O rei Assuero mandou trazer à sua presença a rainha Vasti, e ela não foi."},
{v:18,t:"Hoje mesmo as princesas da Pérsia e da Média, que souberem do procedimento da rainha, falarão disso a todos os príncipes do rei; e haverá desprezo e cólera de sobra."},
{v:19,t:"Se parecer bem ao rei, saia da sua parte um decreto real, e seja escrito entre as leis da Pérsia e da Média, que não podem ser revogadas: que Vasti não volte mais à presença do rei Assuero, e que o rei dê a sua dignidade de rainha a outra melhor do que ela."},
{v:20,t:"E, quando o edito que o rei promulgar for conhecido em todo o seu reino, que é imenso, todas as mulheres honrarão os seus maridos, do maior ao menor."},
{v:21,t:"A proposta agradou ao rei e aos príncipes, e o rei fez conforme a palavra de Mamucã.",np:1},
{v:22,t:"Enviou cartas a todas as províncias do rei, a cada província segundo a sua escrita e a cada povo segundo a sua língua, para que todo homem fosse senhor na sua casa e falasse a língua do seu povo.",n:"E falasse a língua do seu povo: isto é, que em casa prevalecesse a língua do marido, quando a mulher fosse de outro povo. A Nova Vulgata, seguindo São Jerônimo, diz em lugar disso: e tivesse sujeitas todas as mulheres da sua casa."}
];

window.TEXTOS_SEED["ester"][2] = [
{s:"A procura de uma nova rainha"},
{v:1,t:"Depois desses acontecimentos, quando a ira do rei Assuero se acalmou, ele se lembrou de Vasti, do que ela tinha feito e do que fora decretado contra ela."},
{v:2,t:"Então os jovens que serviam o rei disseram: Procurem-se para o rei moças virgens de bela aparência;"},
{v:3,t:"nomeie o rei comissários em todas as províncias do seu reino, e reúnam eles todas as moças virgens de bela aparência na cidadela de Susa, na casa das mulheres, aos cuidados de Egeu, eunuco do rei, guarda das mulheres; e que lhes sejam dados os unguentos de beleza."},
{v:4,t:"E a moça que agradar aos olhos do rei reinará em lugar de Vasti. A proposta agradou ao rei, e ele assim fez."},
{s:"Mardoqueu e Ester"},
{v:5,t:"Havia na cidadela de Susa um judeu chamado Mardoqueu, filho de Jair, filho de Semei, filho de Cis, benjaminita,"},
{v:6,t:"que fora levado de Jerusalém para o exílio com os deportados que foram levados com Jeconias, rei de Judá, deportados por Nabucodonosor, rei da Babilônia.",n:"Jeconias é o rei Joaquin, deportado em 597 a.C. (2 Reis 24,8–16). Se quem foi deportado é Mardoqueu, ele teria mais de cem anos no tempo de Xerxes; por isso muitos entendem que a frase se refere ao seu bisavô Cis."},
{v:7,t:"Ele criava Edissa, isto é, Ester, filha do seu tio, porque ela não tinha pai nem mãe. A moça era de belo porte e de bela aparência; e, quando o pai e a mãe dela morreram, Mardoqueu adotou-a como filha.",n:"Edissa: em hebraico, Hadassa, que quer dizer murta. Ester é nome persa (talvez estrela) ou babilônico (de Ishtar)."},
{v:8,t:"Quando se divulgaram a ordem do rei e o seu decreto, e muitas moças foram reunidas na cidadela de Susa aos cuidados de Egeu, também Ester foi levada ao palácio do rei, aos cuidados de Egeu, guarda das mulheres.",np:1},
{v:9,t:"A moça agradou-lhe e ganhou a sua benevolência; ele se apressou a dar-lhe os unguentos de beleza e as suas porções de comida, e também as sete moças escolhidas do palácio do rei que lhe cabiam; e transferiu-a com as suas moças para o melhor lugar da casa das mulheres."},
{v:10,t:"Ester não tinha revelado o seu povo nem a sua origem, porque Mardoqueu lhe ordenara que não o revelasse."},
{v:11,t:"E todos os dias Mardoqueu passeava diante do pátio da casa das mulheres, para saber como Ester estava e o que acontecia com ela."},
{v:12,t:"Quando chegava a vez de cada moça ir ao rei Assuero, depois de ter cumprido o regulamento das mulheres durante doze meses — pois assim se completavam os dias dos seus tratamentos de beleza: seis meses com óleo de mirra e seis meses com bálsamos e unguentos de mulheres —,",np:1},
{v:13,t:"a moça ia ao rei deste modo: tudo o que ela pedisse lhe era dado, para levar consigo da casa das mulheres ao palácio do rei."},
{v:14,t:"Ela ia à tarde e, pela manhã, voltava para a segunda casa das mulheres, aos cuidados de Sasagaz, eunuco do rei, guarda das concubinas. Não voltava mais ao rei, a não ser que o rei a desejasse e ela fosse chamada pelo nome."},
{s:"Ester torna-se rainha"},
{v:15,t:"Quando chegou a vez de Ester, filha de Abiail, tio de Mardoqueu, que a adotara como filha, de ir ao rei, ela não pediu nada além do que Egeu, eunuco do rei, guarda das mulheres, lhe indicou. E Ester ganhava a simpatia de todos os que a viam."},
{v:16,t:"Ester foi levada ao rei Assuero, ao seu palácio real, no décimo mês, que é o mês de Tebet, no sétimo ano do seu reinado."},
{v:17,t:"O rei amou Ester mais do que todas as mulheres, e ela ganhou a sua simpatia e o seu favor mais do que todas as virgens. Ele pôs a coroa real na cabeça dela e a fez rainha em lugar de Vasti."},
{v:18,t:"Depois o rei deu um grande banquete a todos os seus príncipes e servidores, o banquete de Ester; concedeu às províncias uma dispensa de impostos e distribuiu presentes com generosidade real."},
{s:"Mardoqueu descobre uma conspiração"},
{v:19,t:"Mardoqueu estava sentado à porta do rei.",n:"O hebraico começa: Quando as virgens foram reunidas pela segunda vez... Essas palavras, de sentido obscuro, faltam no grego e na Nova Vulgata."},
{v:20,t:"Ester ainda não tinha revelado a sua origem nem o seu povo, como Mardoqueu lhe ordenara; pois Ester cumpria as ordens de Mardoqueu, como no tempo em que era criada por ele."},
{v:21,t:"Naqueles dias, enquanto Mardoqueu estava sentado à porta do rei, Bagatã e Tares, dois eunucos do rei, guardas da entrada, se irritaram e procuravam um modo de atentar contra o rei Assuero.",np:1},
{v:22,t:"Mardoqueu soube da trama e a contou à rainha Ester, e Ester a comunicou ao rei em nome de Mardoqueu."},
{v:23,t:"Investigou-se o caso e foi comprovado, e os dois foram pendurados numa forca. E isso foi escrito no livro dos Anais, na presença do rei.",n:"Forca: literalmente, madeiro. Talvez se trate de empalamento, suplício usado pelos persas."}
];

window.TEXTOS_SEED["ester"][3] = [
{s:"Amã decide exterminar os judeus"},
{v:1,t:"Depois desses acontecimentos, o rei Assuero engrandeceu Amã, filho de Amadata, o agagita; elevou-o e pôs o seu assento acima de todos os príncipes que estavam com ele.",n:"Agagita: descendente de Agag, rei de Amalec, o antigo inimigo de Israel, a quem Saul poupou (1 Samuel 15). Mardoqueu, da família de Cis, pai de Saul, vê-se de novo diante de um descendente de Agag."},
{v:2,t:"Todos os servidores do rei que ficavam à porta do rei dobravam o joelho e se prostravam diante de Amã, porque assim o rei tinha ordenado a respeito dele. Mas Mardoqueu não dobrava o joelho nem se prostrava.",n:"O hebraico não diz por que Mardoqueu se recusava; a sua oração, em 4,17f–17g, dá a razão."},
{v:3,t:"Os servidores do rei que ficavam à porta do rei disseram a Mardoqueu: Por que transgrides a ordem do rei?"},
{v:4,t:"Como lhe diziam isso todos os dias e ele não os escutava, contaram-no a Amã, para ver se as palavras de Mardoqueu se sustentariam; pois ele lhes tinha dito que era judeu."},
{v:5,t:"Amã viu que Mardoqueu não dobrava o joelho nem se prostrava diante dele, e encheu-se de furor.",np:1},
{v:6,t:"Mas achou pouco pôr as mãos somente em Mardoqueu, porque lhe tinham dito qual era o povo de Mardoqueu; e Amã procurou exterminar todos os judeus que havia em todo o reino de Assuero, o povo de Mardoqueu."},
{v:7,t:"No primeiro mês, que é o mês de Nisan, no décimo segundo ano do rei Assuero, lançou-se o pur, isto é, a sorte, diante de Amã, para saber em que dia e em que mês o povo judeu devia ser exterminado; e a sorte caiu no dia treze do décimo segundo mês, que é o mês de Adar.",np:1,n:"O hebraico diz apenas: de dia em dia e de mês em mês, até o décimo segundo mês, que é o mês de Adar. A Nova Vulgata completa a frase com o que se lê em 3,13. Pur é palavra acádica que quer dizer sorte; dela vem o nome da festa de Purim (9,26)."},
{v:8,t:"Então Amã disse ao rei Assuero: Há um povo espalhado e disperso entre os povos, em todas as províncias do teu reino, cujas leis são diferentes das de todos os outros povos, e que não cumpre as leis do rei. Não convém ao rei deixá-lo em paz."},
{v:9,t:"Se parecer bem ao rei, escreva-se um decreto para exterminá-los, e eu pesarei dez mil talentos de prata nas mãos dos funcionários, para que sejam levados ao tesouro do rei.",n:"Dez mil talentos: soma enorme, mais de trezentas toneladas de prata. Segundo Heródoto, todo o império persa pagava ao rei, por ano, cerca de catorze mil e quinhentos talentos."},
{v:10,t:"O rei tirou o anel da sua mão e o deu a Amã, filho de Amadata, o agagita, inimigo dos judeus."},
{v:11,t:"E o rei disse a Amã: A prata fica contigo, e o povo também; faze com ele o que te parecer bem."},
{s:"O decreto contra os judeus"},
{v:12,t:"No dia treze do primeiro mês foram convocados os escribas do rei, e escreveu-se tudo o que Amã ordenou aos sátrapas do rei, aos governadores de cada província e aos chefes de cada povo, a cada província segundo a sua escrita e a cada povo segundo a sua língua. Foi escrito em nome do rei Assuero e selado com o anel do rei."},
{v:13,t:"As cartas foram enviadas por meio de mensageiros a todas as províncias do rei, com ordem de exterminar, matar e aniquilar todos os judeus, jovens e velhos, crianças e mulheres, num só dia, o dia treze do décimo segundo mês, que é o mês de Adar, e de saquear os seus bens."},
{v:"13a",t:"Esta era a cópia da carta: O grande rei Artaxerxes escreve o seguinte aos sátrapas e governadores das cento e vinte e sete províncias, da Índia até a Etiópia, que estão sujeitos ao seu domínio:",np:1,n:"Os versículos 13a–13g reproduzem o texto do decreto segundo o grego (13,1–7 na antiga Vulgata)."},
{v:"13b",t:"Tendo eu domínio sobre muitíssimas nações e havendo submetido ao meu poder o mundo inteiro, quis não abusar da grandeza do meu poder, mas, procedendo sempre com clemência e brandura, governar a vida dos meus súditos sem nenhum temor, oferecer um reino tranquilo e transitável até os seus confins e restabelecer a paz que todos os mortais desejam."},
{v:"13c",t:"Quando perguntei aos meus conselheiros como se poderia realizar isso, um deles, que se distingue entre todos pela prudência, pela boa vontade e pela fidelidade constante, e que ocupa o segundo lugar depois do rei, chamado Amã,"},
{v:"13d",t:"mostrou-me que, entre as tribos de toda a terra, está disperso um povo hostil, que, com as suas leis, age contra os costumes de todas as nações e despreza continuamente as ordens dos reis, de modo que não pode subsistir a concórdia das nações que consolidamos."},
{v:"13e",t:"Informados disso, e vendo que esta nação, a única rebelde a todo o gênero humano, segue leis perversas, se opõe aos nossos interesses, comete os piores crimes e impede a paz do reino,"},
{v:"13f",t:"ordenamos que todos os que Amã, que está à frente dos negócios públicos e a quem honramos como a um pai, vos indicar por carta sejam exterminados pela raiz, com as mulheres e os filhos, pela espada dos inimigos, sem que ninguém tenha piedade deles, no dia catorze do décimo segundo mês, Adar, deste ano;",n:"Dia catorze: assim o grego; o hebraico, em 3,13, diz dia treze."},
{v:"13g",t:"para que esses homens, perversos desde há muito tempo, descendo violentamente num só dia à morada dos mortos, nos deixem para o futuro os negócios do Estado plenamente estáveis e tranquilos."},
{v:"13h",t:"Quem esconder alguém dessa raça ficará sem lugar onde morar, não só entre os homens, mas nem mesmo entre as aves, e será queimado no fogo sagrado; e os seus bens serão confiscados para o reino. Passai bem.",n:"Este versículo só existe na antiga versão latina. O fogo sagrado era venerado pelos persas."},
{v:14,t:"Uma cópia do escrito devia ser promulgada como lei em cada província e dada a conhecer a todos os povos, para que estivessem preparados para aquele dia.",np:1},
{v:15,t:"Os mensageiros partiram apressados por ordem do rei, e o decreto foi promulgado na cidadela de Susa. E, enquanto o rei e Amã se sentavam para beber, a cidade de Susa estava consternada."},
{s:"A oração dos judeus"},
{v:"15a",t:"Todos os povos fizeram festa; e o rei e Amã, tendo entrado no palácio, entregavam-se aos prazeres com os seus amigos.",n:"Os versículos 15a–15i, com a oração dos judeus, não estão no hebraico nem no grego; a Nova Vulgata os toma da antiga versão latina."},
{v:"15b",t:"E, onde quer que se afixasse a cópia da carta, havia pranto e grande luto entre todos os judeus."},
{v:"15c",t:"E os judeus invocavam o Deus dos seus pais, dizendo:"},
{v:"15d",l:["Senhor Deus, só tu és Deus lá no alto do céu,","e não há outro Deus além de ti."],np:1},
{v:"15e",l:["Se tivéssemos cumprido a tua lei e os teus mandamentos,","teríamos vivido em segurança e em paz todo o tempo da nossa vida."],np:1},
{v:"15f",l:["Mas agora, porque não cumprimos os teus mandamentos,","veio sobre nós toda esta tribulação."],np:1},
{v:"15g",l:["Tu és justo e clemente, altíssimo e grande, Senhor,","e todos os teus caminhos são justiça."],np:1},
{v:"15h",l:["E agora, Senhor, não entregues os teus filhos ao cativeiro,","nem as nossas mulheres à violação e à perdição,","tu que foste propício para conosco desde o Egito até hoje."],np:1},
{v:"15i",l:["Tem piedade da tua porção principal","e não entregues à infâmia a tua herança,","deixando que os inimigos nos dominem."],np:1}
];

window.TEXTOS_SEED["ester"][4] = [
{s:"O luto dos judeus"},
{v:1,t:"Quando Mardoqueu soube de tudo o que tinha acontecido, rasgou as suas vestes, vestiu-se de saco e cobriu-se de cinza; e saiu pelo meio da cidade, soltando um grito forte e amargo,"},
{v:2,t:"e chegou até diante da porta do rei; pois não era permitido entrar pela porta do rei vestido de saco."},
{v:3,t:"Em cada província, em todo lugar aonde chegavam a ordem do rei e o seu decreto, havia grande luto entre os judeus, com jejum, choro e lamentação; e muitos se deitavam sobre saco e cinza."},
{s:"Mardoqueu pede a intercessão de Ester"},
{v:4,t:"As moças de Ester e os seus eunucos vieram contar-lhe isso, e a rainha ficou muito angustiada. Mandou roupas para que Mardoqueu se vestisse e tirasse o saco; mas ele não as aceitou."},
{v:5,t:"Então Ester chamou Atac, um dos eunucos do rei, que ele pusera ao serviço dela, e mandou-o ter com Mardoqueu, para saber o que era aquilo e por que era."},
{v:6,t:"Atac saiu ao encontro de Mardoqueu, na praça da cidade, que ficava diante da porta do rei.",np:1},
{v:7,t:"Mardoqueu contou-lhe tudo o que lhe tinha acontecido e a quantia exata de prata que Amã prometera pagar ao tesouro do rei em troca da destruição dos judeus."},
{v:8,t:"Deu-lhe também uma cópia do texto do decreto promulgado em Susa para exterminá-los, para que a mostrasse a Ester, a pusesse a par de tudo e lhe ordenasse que se apresentasse ao rei, para lhe suplicar e interceder diante dele pelo seu povo."},
{v:"8a",t:"Lembra-te, disse ele, dos dias da tua humildade, quando eras criada pela minha mão; porque Amã, o segundo depois do rei, falou contra nós para nos dar a morte. Invoca o Senhor, fala ao rei em nosso favor e livra-nos da morte.",n:"Este versículo vem do grego (15,1–3 na antiga Vulgata)."},
{v:9,t:"Atac voltou e contou a Ester as palavras de Mardoqueu."},
{v:10,t:"Então Ester falou a Atac e mandou-o dizer a Mardoqueu:",np:1},
{v:11,t:"Todos os servidores do rei e o povo das províncias do rei sabem que, para todo homem ou mulher que se apresenta ao rei no pátio interior sem ser chamado, há uma só lei: a morte; a não ser que o rei lhe estenda o cetro de ouro, e então viverá. E eu já faz trinta dias que não sou chamada para ir ao rei."},
{v:12,t:"Quando contaram a Mardoqueu as palavras de Ester,"},
{v:13,t:"Mardoqueu mandou responder a Ester: Não penses que, por estares no palácio do rei, escaparás sozinha entre todos os judeus."},
{v:14,t:"Porque, se te calares agora, o alívio e a libertação virão para os judeus de outra parte, mas tu e a casa de teu pai perecereis. E quem sabe se não foi para uma ocasião como esta que chegaste à realeza?",n:"De outra parte: discreta alusão a Deus, cujo nome o texto hebraico nunca pronuncia."},
{v:15,t:"Então Ester mandou responder a Mardoqueu:",np:1},
{v:16,t:"Vai, reúne todos os judeus que se encontram em Susa, e jejuai por mim: não comais nem bebais durante três dias, noite e dia. Também eu e as minhas moças jejuaremos assim; e depois irei ao rei, contra a lei; e, se eu perecer, pereci."},
{v:17,t:"Mardoqueu retirou-se e fez tudo como Ester lhe ordenara."},
{s:"A oração de Mardoqueu"},
{v:"17a",t:"Mardoqueu rasgou as suas vestes, estendeu no chão um cilício e prostrou-se com o rosto em terra, e com ele os anciãos do povo, desde a manhã até a tarde,",n:"Os versículos 17a–17kk trazem as orações de Mardoqueu e de Ester (13,8–14,19 na antiga Vulgata). Este versículo vem da antiga versão latina; o grego começa: Mardoqueu suplicou ao Senhor, recordando todas as obras do Senhor."},
{v:"17b",l:["e disse:","Deus de Abraão, Deus de Isaac e Deus de Jacó, bendito és tu."],np:1},
{v:"17c",l:["Senhor, Senhor, rei todo-poderoso,","todas as coisas estão sob o teu poder,","e não há quem possa resistir à tua vontade,","se decidires salvar Israel."],np:1},
{v:"17d",l:["Tu fizeste o céu e a terra","e todas as maravilhas que o céu abrange;"],np:1},
{v:"17e",l:["és o Senhor de todas as coisas,","e não há quem resista à tua majestade."],np:1},
{v:"17f",l:["Tu sabes, Senhor, que eu de bom grado beijaria","as plantas dos pés de Amã pela salvação de Israel;"],np:1},
{v:"17g",l:["se não me prostrei diante dele,","foi para não pôr a glória de um homem acima da glória do meu Deus;","e não adorarei ninguém senão a ti, Senhor, meu Deus."],np:1},
{v:"17h",l:["E não faço isso por arrogância","nem por desejo de glória, Senhor.","Aparece, Senhor; manifesta-te, Senhor!"],np:1},
{v:"17i",l:["E agora, Senhor rei, Deus de Abraão, Deus de Isaac e Deus de Jacó,","poupa o teu povo,","porque os nossos inimigos querem destruir-nos","e aniquilar a tua herança."],np:1},
{v:"17k",l:["Não desprezes a tua porção,","que resgataste para ti da terra do Egito."],np:1},
{v:"17l",l:["Ouve a minha súplica","e sê propício ao teu quinhão;","muda o nosso luto em alegria,","para que, vivos, louvemos o teu nome, Senhor;","não feches a boca dos que te cantam."],np:1},
{v:"17m",t:"E todo o Israel clamou ao Senhor com todas as suas forças, porque uma morte certa o ameaçava.",np:1},
{s:"A oração de Ester"},
{v:"17n",t:"Também a rainha Ester buscou refúgio no Senhor, temendo o perigo de morte que a ameaçava."},
{v:"17o",t:"Despiu as vestes de glória, pôs roupas de luto e, em lugar dos perfumes de luxo, cobriu a cabeça de cinza e humilhou muito o seu corpo com jejuns."},
{v:"17p",t:"E prostrou-se por terra com as suas servas, desde a manhã até a tarde, e disse:",n:"No grego, a oração de Ester é diferente em vários pontos; a Nova Vulgata segue aqui a antiga versão latina, que traz, por exemplo, a lista das libertações de 17s–17aa."},
{v:"17q",l:["Deus de Abraão, Deus de Isaac e Deus de Jacó, bendito és tu.","Socorre-me, a mim que estou só","e não tenho outro defensor além de ti, Senhor,"],np:1},
{v:"17r",l:["porque o perigo está nas minhas mãos."]},
{v:"17s",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que guardaste Noé nas águas do dilúvio."],np:1},
{v:"17t",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que a Abraão, com trezentos e dezoito homens,","entregaste nove reis."],np:1,n:"Nove reis: os quatro que Abraão derrotou (Gênesis 14,14–15) e os cinco que eles tinham vencido antes, contados juntos."},
{v:"17u",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que livraste Jonas do ventre do grande peixe."],np:1},
{v:"17v",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que livraste Ananias, Azarias e Misael da fornalha de fogo."],np:1},
{v:"17x",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que arrancaste Daniel da cova dos leões."],np:1},
{v:"17y",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que tiveste compaixão de Ezequias, rei dos judeus,","condenado à morte e rezando pela sua vida,","e lhe deste mais quinze anos de vida."],np:1},
{v:"17z",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que a Ana, que te pedia com todo o desejo da sua alma,","concedeste gerar um filho."],np:1},
{v:"17aa",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que livras, Senhor, todos os que te agradam,","até o fim."],np:1},
{v:"17bb",l:["E agora ajuda-me, a mim que estou sozinha","e não tenho ninguém senão a ti,","Senhor, meu Deus."],np:1},
{v:"17cc",l:["Tu sabes","que a tua serva abomina o leito dos incircuncisos."],np:1},
{v:"17dd",l:["Deus, tu sabes","que não comi da mesa das abominações","nem bebi o vinho das suas libações."],np:1},
{v:"17ee",l:["Tu sabes","que, desde o dia em que fui levada para cá,","não me alegrei, Senhor,","senão em ti somente."],np:1},
{v:"17ff",l:["Tu sabes, Deus,","que, desde que trago este adorno sobre a cabeça,","eu o detesto como um pano de mulher menstruada","e não o visto em dia de festa."],np:1,n:"Este adorno é o diadema real. O grego diz: não o uso nos meus dias de descanso; isto é, Ester só o põe quando tem de aparecer em público."},
{v:"17gg",l:["E agora socorre-me, a mim que sou órfã;","põe na minha boca uma palavra oportuna diante do leão,","faze que eu lhe seja agradável","e muda o seu coração, para que odeie aquele que nos combate,","para a ruína dele e dos que estão de acordo com ele."],np:1,n:"O leão é o rei."},
{v:"17hh",l:["Livra-nos das mãos dos nossos inimigos;","muda o nosso luto em alegria","e as nossas dores em saúde."],np:1},
{v:"17ii",l:["E os que se levantam contra a tua porção, ó Deus,","faze deles um exemplo."],np:1},
{v:"17kk",l:["Aparece, Senhor; manifesta-te, Senhor!"],np:1}
];

window.TEXTOS_SEED["ester"][5] = [
{s:"Ester apresenta-se ao rei"},
{v:1,t:"No terceiro dia, Ester vestiu-se com as vestes reais e ficou de pé no pátio interior do palácio do rei, em frente à sala do rei. O rei estava sentado no seu trono real, na sala do trono, em frente à entrada do palácio."},
{v:2,t:"Quando o rei viu a rainha Ester de pé no pátio, ela lhe agradou; e o rei estendeu para Ester o cetro de ouro que tinha na mão. Ester aproximou-se e tocou a ponta do cetro."},
{v:"2a",t:"Resplandecendo nos trajes reais, depois de invocar a Deus, que tudo governa e salva, Ester tomara consigo duas servas:",np:1,n:"Os versículos 2a–2p (15,5–19 na antiga Vulgata) contam de novo, segundo o grego, a entrada de Ester diante do rei, com mais pormenores."},
{v:"2b",t:"numa delas se apoiava, como mulher delicada,"},
{v:"2c",t:"e a outra seguia a sua senhora, segurando-lhe as vestes, que arrastavam pelo chão."},
{v:"2d",t:"Ela, com o rosto corado e os olhos graciosos e brilhantes, escondia um coração triste e apertado pelo medo da morte."},
{v:"2e",t:"Tendo passado, uma após outra, todas as portas, parou na sala interior, diante do rei, que estava sentado no trono do seu reino, vestido com as vestes reais, resplandecente de ouro e de pedras preciosas; tinha um aspecto terrível, e o cetro de ouro na mão."},
{v:"2f",t:"Quando levantou o rosto, olhou para ela como um touro no ímpeto da sua ira e, pensando em matá-la, gritou, hesitante: Quem ousou entrar na sala sem ser chamado? A rainha desfaleceu e, mudando de cor, pálida, deixou-se cair, sem forças, sobre a cabeça da servinha que ia à sua frente.",np:1,n:"O touro e a pergunta do rei vêm da antiga versão latina; o grego diz: levantando o rosto, afogueado de esplendor, olhou-a no auge da ira."},
{v:"2g",t:"Mas o Deus dos judeus, Senhor de toda a criação, mudou o espírito do rei em mansidão; e ele, apressado e aflito, saltou do trono e, amparando-a nos braços até que voltasse a si, acalmava-a com palavras de paz:"},
{v:"2h",t:"Que tens, rainha Ester, minha irmã e companheira no reino? Eu sou teu irmão; não tenhas medo."},
{v:"2i",t:"Não morrerás; esta lei não foi feita para ti, mas para todos os outros."},
{v:"2k",t:"Aproxima-te."},
{v:"2l",t:"E, levantando o cetro de ouro, pô-lo sobre o pescoço dela, beijou-a e disse: Fala comigo.",np:1},
{v:"2m",t:"Ela respondeu: Eu te vi, senhor, como um anjo de Deus, e o meu coração perturbou-se de temor diante da tua glória;"},
{v:"2n",t:"pois és muito admirável, senhor, e o teu rosto é cheio de graça."},
{v:"2o",t:"Enquanto falava, desfaleceu de novo e quase perdeu os sentidos."},
{v:"2p",t:"O rei ficou perturbado, e todos os seus servidores também."},
{s:"O primeiro banquete de Ester"},
{v:3,t:"Então o rei lhe disse: Que tens, rainha Ester? Qual é o teu pedido? Ainda que seja a metade do reino, te será dado."},
{v:4,t:"Ester respondeu: Se parecer bem ao rei, venha hoje o rei com Amã ao banquete que lhe preparei."},
{v:5,t:"O rei disse: Chamai depressa Amã, para que se faça o que Ester deseja. E o rei e Amã foram ao banquete que Ester tinha preparado."},
{v:6,t:"Enquanto bebiam vinho, o rei disse a Ester: Qual é a tua petição? Ela te será concedida. Qual é o teu pedido? Ainda que seja a metade do reino, será feito."},
{v:7,t:"Ester respondeu: A minha petição e o meu pedido são estes:"},
{v:8,t:"se encontrei graça aos olhos do rei, e se parecer bem ao rei conceder a minha petição e atender ao meu pedido, venha o rei com Amã ao banquete que lhes prepararei, e amanhã farei como o rei diz."},
{s:"Amã prepara a forca para Mardoqueu"},
{v:9,t:"Naquele dia Amã saiu alegre e de bom humor. Mas, quando viu Mardoqueu à porta do rei, e que ele não se levantava nem se movia diante dele, encheu-se de furor contra Mardoqueu."},
{v:10,t:"Contudo Amã se conteve e foi para casa. Mandou chamar os seus amigos e Zares, sua mulher,"},
{v:11,t:"e falou-lhes do esplendor da sua riqueza, do grande número dos seus filhos e de tudo aquilo com que o rei o tinha engrandecido, e de como o elevara acima dos príncipes e dos servidores do rei."},
{v:12,t:"E acrescentou: Além disso, a rainha Ester não convidou ninguém, senão a mim, para ir com o rei ao banquete que ela preparou; e também amanhã estou convidado por ela, com o rei."},
{v:13,t:"Mas tudo isso não significa nada para mim, enquanto eu vir o judeu Mardoqueu sentado à porta do rei.",np:1},
{v:14,t:"Zares, sua mulher, e todos os seus amigos lhe disseram: Manda levantar uma forca de cinquenta côvados de altura e, amanhã de manhã, pede ao rei que Mardoqueu seja pendurado nela; depois irás alegre com o rei ao banquete. A proposta agradou a Amã, e ele mandou levantar a forca.",n:"Cinquenta côvados: uns vinte e dois metros."}
];

window.TEXTOS_SEED["ester"][6] = [
{s:"Mardoqueu é honrado pelo rei"},
{v:1,t:"Naquela noite o rei não conseguia dormir, e mandou trazer o livro das Memórias, os Anais; e foram lidos diante do rei."},
{v:2,t:"Encontrou-se escrito ali como Mardoqueu tinha denunciado Bagatã e Tares, dois eunucos do rei, guardas da entrada, que tinham procurado atentar contra o rei Assuero."},
{v:3,t:"O rei perguntou: Que honra e que distinção se deu a Mardoqueu por isso? Os jovens que serviam o rei responderam: Nada se fez por ele.",np:1},
{v:4,t:"O rei perguntou: Quem está no pátio? Ora, Amã acabava de entrar no pátio exterior do palácio do rei, para pedir ao rei que mandasse pendurar Mardoqueu na forca que ele lhe tinha preparado."},
{v:5,t:"Os jovens do rei lhe responderam: É Amã, que está no pátio. O rei disse: Que entre."},
{v:6,t:"Amã entrou, e o rei lhe perguntou: Que se deve fazer ao homem a quem o rei deseja honrar? Amã pensou consigo: A quem o rei desejaria honrar mais do que a mim?",np:1},
{v:7,t:"E Amã respondeu ao rei: Para o homem a quem o rei deseja honrar,"},
{v:8,t:"tragam uma veste real que o rei já tenha usado e um cavalo que o rei tenha montado, e em cuja cabeça se tenha posto uma coroa real;",n:"Em cuja cabeça: a do cavalo, que nos relevos da Assíria e da Pérsia aparece com um penacho em forma de coroa. A Nova Vulgata entende que a coroa é posta na cabeça do homem."},
{v:9,t:"entreguem-se a veste e o cavalo a um dos príncipes mais nobres do rei; vistam com ela o homem a quem o rei deseja honrar e o levem a cavalo pela praça da cidade, proclamando diante dele: Assim se faz ao homem a quem o rei deseja honrar."},
{v:10,t:"Então o rei disse a Amã: Depressa, toma a veste e o cavalo, como disseste, e faze assim ao judeu Mardoqueu, que está sentado à porta do rei. Não omitas nada de tudo o que disseste.",np:1},
{v:11,t:"Amã tomou a veste e o cavalo, vestiu Mardoqueu e o levou a cavalo pela praça da cidade, proclamando diante dele: Assim se faz ao homem a quem o rei deseja honrar."},
{v:12,t:"Depois Mardoqueu voltou à porta do rei, e Amã correu para casa, de luto e com a cabeça coberta.",np:1},
{v:13,t:"Amã contou a Zares, sua mulher, e a todos os seus amigos tudo o que lhe tinha acontecido. Os seus sábios e Zares, sua mulher, lhe disseram: Se Mardoqueu, diante de quem começaste a cair, é da raça dos judeus, não prevalecerás contra ele; pelo contrário, certamente cairás diante dele."},
{v:14,t:"Ainda estavam falando com ele, quando chegaram os eunucos do rei e o levaram às pressas ao banquete que Ester tinha preparado."}
];

window.TEXTOS_SEED["ester"][7] = [
{s:"O segundo banquete e a queda de Amã"},
{v:1,t:"O rei e Amã foram, pois, beber com a rainha Ester."},
{v:2,t:"Também nesse segundo dia, enquanto bebiam vinho, o rei disse a Ester: Qual é a tua petição, rainha Ester? Ela te será concedida. Qual é o teu pedido? Ainda que seja a metade do reino, será feito."},
{v:3,t:"A rainha Ester respondeu: Se encontrei graça aos teus olhos, ó rei, e se parecer bem ao rei, seja-me concedida a vida — é a minha petição — e a do meu povo — é o meu pedido."},
{v:4,t:"Porque fomos vendidos, eu e o meu povo, para sermos exterminados, mortos e aniquilados. Se tivéssemos sido vendidos como escravos e escravas, eu me teria calado, pois essa desgraça não valeria o incômodo do rei.",n:"Frase de sentido incerto; pode também significar: mas o inimigo não poderia compensar o prejuízo do rei."},
{v:5,t:"O rei Assuero perguntou à rainha Ester: Quem é e onde está aquele que teve o atrevimento de fazer isso?"},
{v:6,t:"Ester respondeu: O adversário e inimigo é este perverso Amã. Amã ficou aterrorizado diante do rei e da rainha."},
{v:7,t:"O rei, enfurecido, levantou-se do banquete e foi para o jardim do palácio; Amã, porém, ficou para implorar pela sua vida à rainha Ester, porque viu que o rei já tinha decidido a sua desgraça.",np:1},
{v:8,t:"Quando o rei voltou do jardim do palácio para a sala do banquete, Amã tinha caído sobre o divã em que Ester estava. Então o rei disse: Ainda por cima quer violentar a rainha, estando eu em casa? Mal essa palavra saiu da boca do rei, cobriram o rosto de Amã."},
{v:9,t:"Harbona, um dos eunucos que serviam o rei, disse: Além disso, está na casa de Amã a forca de cinquenta côvados de altura que Amã preparou para Mardoqueu, que falou em favor do rei. O rei disse: Pendurai-o nela."},
{v:10,t:"Penduraram Amã na forca que ele tinha preparado para Mardoqueu; e a ira do rei se acalmou."}
];

window.TEXTOS_SEED["ester"][8] = [
{s:"Mardoqueu recebe o anel do rei"},
{v:1,t:"Naquele mesmo dia, o rei Assuero deu à rainha Ester a casa de Amã, o inimigo dos judeus; e Mardoqueu apresentou-se diante do rei, porque Ester lhe tinha revelado o que ele era para ela."},
{v:2,t:"O rei tirou o seu anel, que tinha retomado de Amã, e o deu a Mardoqueu. E Ester pôs Mardoqueu à frente da casa de Amã."},
{s:"Ester intercede pelo seu povo"},
{v:3,t:"Ester falou de novo diante do rei, lançou-se aos seus pés e, chorando, suplicou-lhe que anulasse a maldade de Amã, o agagita, e o plano que ele tinha tramado contra os judeus."},
{v:4,t:"O rei estendeu para Ester o cetro de ouro; Ester levantou-se e ficou de pé diante do rei,"},
{v:5,t:"e disse: Se parecer bem ao rei, se encontrei graça diante dele, se a coisa parecer justa ao rei e se eu lhe agrado, escreva-se para revogar as cartas, o plano de Amã, filho de Amadata, o agagita, que ele escreveu para exterminar os judeus que estão em todas as províncias do rei."},
{v:6,t:"Pois como poderia eu ver a desgraça que vai atingir o meu povo? Como poderia eu ver a destruição da minha família?"},
{v:7,t:"O rei Assuero respondeu à rainha Ester e ao judeu Mardoqueu: Eis que dei a Ester a casa de Amã, e ele foi pendurado na forca por ter levantado a mão contra os judeus.",np:1},
{v:8,t:"Escrevei vós, pois, a respeito dos judeus o que vos parecer bem, em nome do rei, e selai com o anel do rei; porque um documento escrito em nome do rei e selado com o anel do rei não pode ser revogado."},
{s:"O decreto a favor dos judeus"},
{v:9,t:"Foram então convocados os escribas do rei, no terceiro mês, que é o mês de Sivan, no dia vinte e três; e escreveu-se tudo o que Mardoqueu ordenou aos judeus, aos sátrapas, aos governadores e aos chefes das províncias, da Índia até a Etiópia, cento e vinte e sete províncias, a cada província segundo a sua escrita e a cada povo segundo a sua língua, e também aos judeus segundo a sua escrita e a sua língua."},
{v:10,t:"Escreveu em nome do rei Assuero, selou com o anel do rei e enviou as cartas por meio de mensageiros montados nos cavalos velozes do serviço real, criados nas coudelarias do rei.",n:"Os termos persas que designam esses cavalos são de sentido incerto."},
{v:11,t:"Nelas o rei concedia aos judeus de cada cidade o direito de se reunirem e defenderem a sua vida, de exterminar, matar e aniquilar todas as forças armadas de qualquer povo ou província que os atacassem, com as suas crianças e mulheres, e de saquear os seus bens,",n:"Nota do tradutor: O novo decreto retoma, palavra por palavra, os termos do decreto de Amã (3,13), agora voltados contra os agressores: exterminar, matar e aniquilar, com crianças e mulheres, e saquear. Alguns entendem que as crianças e mulheres são as dos próprios judeus, a quem se permite defender a família. O texto não é atenuado: o livro narra, com a linguagem da guerra antiga, a inversão da sorte de um povo condenado ao extermínio."},
{v:12,t:"num só dia, em todas as províncias do rei Assuero: o dia treze do décimo segundo mês, que é o mês de Adar."},
{v:"12a",t:"Assim ele lhes ordenou que seguissem as suas próprias leis em toda cidade, que se ajudassem e que tratassem os seus inimigos e adversários como quisessem, num só dia,",np:1,n:"Os versículos 12a–12b resumem, segundo o grego, o que foi dito em 8,11–12."},
{v:"12b",t:"em todo o reino de Artaxerxes, no dia catorze do décimo segundo mês, que é Adar.",n:"Dia catorze: assim a Nova Vulgata aqui e em 8,12y; o hebraico diz dia treze (8,12; 9,1)."},
{s:"A carta do rei a favor dos judeus"},
{v:"12c",t:"Esta é a cópia da carta:",n:"Os versículos 12c–12cc trazem, segundo o grego, o texto do segundo decreto (16,1–24 na antiga Vulgata)."},
{v:"12d",t:"O grande rei Artaxerxes saúda os sátrapas das cento e vinte e sete províncias, da Índia até a Etiópia, e todos os que obedecem às nossas ordens.",np:1},
{v:"12e",t:"Muitos, abusando da excessiva bondade dos príncipes e da honra que lhes foi conferida, encheram-se de soberba;"},
{v:"12f",t:"e não somente procuram oprimir os súditos dos reis, mas, incapazes de suportar a glória que lhes foi dada, tramam ciladas contra aqueles mesmos que a deram."},
{v:"12g",t:"Não se contentam em banir dentre os homens a gratidão, mas, inchados pelas palavras vãs dos que não conhecem o bem, julgam poder escapar até à sentença de Deus, que tudo vê e odeia o mal.",np:1},
{v:"12h",t:"Muitas vezes também muitos dos que estão constituídos em autoridade, pelo conselho de amigos a quem tinham confiado os negócios, tornaram-se cúmplices do derramamento de sangue inocente e se envolveram em desgraças irremediáveis,"},
{v:"12i",t:"quando esses amigos, com artifícios perversos e mentirosos, enganavam a sincera benevolência dos príncipes."},
{v:"12k",t:"Isso não se comprova tanto pelas histórias antigas quanto pelo que está à vista de quem observa os crimes cometidos pela peste dos que governam indignamente."},
{v:"12l",t:"Por isso, para o futuro, é preciso zelar pela paz de todas as províncias."},
{v:"12m",t:"Se mudamos as nossas ordens, é porque sempre julgamos com a mais clemente atenção os casos que nos chegam aos olhos."},
{v:"12n",t:"Pois Amã, filho de Amadata, macedônio, estranho ao sangue dos persas e muito distante da nossa bondade, foi acolhido por nós como hóspede.",np:1,n:"Macedônio: no grego, Amã é um estrangeiro que trama entregar o império persa aos macedônios (8,12r), o que reflete a época em que o texto grego foi escrito, depois de Alexandre Magno."},
{v:"12o",t:"E experimentou em si a benevolência que temos para com todos os povos, a ponto de ser publicamente chamado nosso pai e reverenciado por todos como o segundo depois do rei."},
{v:"12p",t:"Mas ele se inflou de tamanha arrogância que procurou privar-nos do reino e da vida."},
{v:"12q",t:"Com efeito, por meio de tramas tortuosas e enganadoras, pediu a morte de Mardoqueu, nosso salvador e benfeitor constante, e de Ester, irrepreensível companheira do nosso reino, com todo o povo deles,"},
{v:"12r",t:"pensando em, depois de os matar, atacar-nos à traição, a nós que ficaríamos sozinhos, e transferir para os macedônios o reino dos persas.",np:1},
{v:"12s",t:"Nós, porém, verificamos que os judeus, destinados à morte por esse homem, o pior dos mortais, não têm culpa alguma; pelo contrário, vivem segundo leis justíssimas",np:1},
{v:"12t",t:"e são filhos do Deus altíssimo, grandíssimo e sempre vivo, graças ao qual o reino foi conduzido, para nós e para os nossos pais, na melhor ordem.",n:"Filhos do Deus altíssimo: no texto grego, é o próprio rei persa quem reconhece o Deus de Israel."},
{v:"12u",t:"Fareis bem, portanto, em não fazer uso das cartas enviadas por Amã, filho de Amadata.",np:1},
{v:"12v",t:"Por esse crime, o próprio autor da trama está pendurado na forca, com toda a sua família, diante das portas desta cidade, isto é, de Susa; pois Deus, que governa todas as coisas, rapidamente lhe deu o que merecia."},
{v:"12x",t:"Seja afixada em todas as cidades a cópia deste edito que agora enviamos, para que os judeus possam viver segundo as suas leis.",np:1},
{v:"12y",t:"Deveis ajudá-los, para que possam defender-se dos que os atacarem no tempo da tribulação, no dia catorze do décimo segundo mês, que se chama Adar."},
{v:"12z",t:"Porque Deus todo-poderoso mudou para eles em alegria este dia, que estava destinado à ruína do povo escolhido."},
{v:"12aa",t:"Por isso também vós, entre os vossos dias de festa, tende este dia por insigne e celebrai-o com toda a alegria,"},
{v:"12bb",t:"para que, agora e no futuro, ele seja a salvação para nós e para os persas que nos são fiéis, e para os que nos armam ciladas, uma lembrança da sua perdição."},
{v:"12cc",t:"Toda cidade ou província que não quiser participar desta festa pereça, na ira, pelo fogo e pela espada; e seja destruída de tal modo que fique para sempre não só inacessível aos homens, mas odiosa até às feras e às aves. Passai bem.",np:1},
{v:13,t:"Uma cópia do escrito devia ser promulgada como lei em cada província e dada a conhecer a todos os povos, para que os judeus estivessem preparados para aquele dia, para se vingarem dos seus inimigos.",np:1},
{v:14,t:"Os mensageiros, montados nos cavalos velozes do serviço real, partiram às pressas, impelidos pela ordem do rei; e o decreto foi promulgado na cidadela de Susa."},
{s:"A alegria dos judeus"},
{v:15,t:"Mardoqueu saiu da presença do rei com uma veste real de púrpura violeta e de linho branco, uma grande coroa de ouro e um manto de linho fino e de púrpura; e a cidade de Susa gritava de alegria e se regozijava."},
{v:16,t:"Para os judeus houve luz e alegria, júbilo e honra."},
{v:17,t:"Em cada província e em cada cidade, em todo lugar aonde chegavam a ordem do rei e o seu decreto, havia alegria e júbilo para os judeus, banquetes e dias de festa. E muitos dentre os povos da terra se fizeram judeus, porque o temor dos judeus caíra sobre eles."}
];

window.TEXTOS_SEED["ester"][9] = [
{s:"Os judeus vencem os seus inimigos"},
{v:1,t:"No décimo segundo mês, que é o mês de Adar, no dia treze, quando a ordem do rei e o seu decreto deviam ser executados, no dia em que os inimigos dos judeus esperavam dominá-los, aconteceu o contrário: foram os judeus que dominaram os que os odiavam."},
{v:2,t:"Os judeus se reuniram nas suas cidades, em todas as províncias do rei Assuero, para pôr as mãos nos que procuravam a sua desgraça; e ninguém lhes resistiu, porque o temor deles caíra sobre todos os povos."},
{v:3,t:"Todos os chefes das províncias, os sátrapas, os governadores e os funcionários do rei apoiavam os judeus, porque o temor de Mardoqueu caíra sobre eles."},
{v:4,t:"Pois Mardoqueu era poderoso no palácio do rei, e a sua fama se espalhava por todas as províncias; o homem Mardoqueu ia-se tornando cada vez mais poderoso."},
{v:5,t:"Os judeus feriram todos os seus inimigos a golpes de espada, matando-os e destruindo-os, e fizeram o que quiseram com os que os odiavam.",np:1,n:"A Nova Vulgata, seguindo São Jerônimo, diz: retribuindo-lhes o que eles tinham preparado para fazer."},
{v:6,t:"Na cidadela de Susa, os judeus mataram e destruíram quinhentos homens;"},
{v:7,t:"mataram também Farsandata, Delfon, Esfata,"},
{v:8,t:"Forata, Adalia, Aridata,"},
{v:9,t:"Fermesta, Arisai, Aridai e Jezata,"},
{v:10,t:"os dez filhos de Amã, filho de Amadata, o inimigo dos judeus; mas não puseram as mãos no saque."},
{s:"O segundo dia em Susa"},
{v:11,t:"Naquele mesmo dia, o número dos mortos na cidadela de Susa chegou ao conhecimento do rei."},
{v:12,t:"E o rei disse à rainha Ester: Na cidadela de Susa os judeus mataram e destruíram quinhentos homens e os dez filhos de Amã; que terão feito nas outras províncias do rei? Qual é a tua petição? Ela te será concedida. Que mais pedes? Será feito.",np:1},
{v:13,t:"Ester respondeu: Se parecer bem ao rei, seja permitido também amanhã aos judeus que estão em Susa agir conforme o decreto de hoje; e que os dez filhos de Amã sejam pendurados na forca.",np:1,n:"Nota do tradutor: O pedido de Ester, de mais um dia de combate em Susa e da exposição dos corpos dos filhos de Amã, já mortos (9,10), não é atenuado. O relato insiste em que os judeus lutaram contra os que os atacavam (9,2.16) e não tocaram nos bens deles (9,10.15.16), embora o decreto o permitisse (8,11)."},
{v:14,t:"O rei mandou que assim se fizesse. O decreto foi promulgado em Susa, e os dez filhos de Amã foram pendurados."},
{v:15,t:"Os judeus que estavam em Susa reuniram-se também no dia catorze do mês de Adar e mataram em Susa trezentos homens; mas não puseram as mãos no saque."},
{v:16,t:"Os outros judeus que estavam nas províncias do rei também se reuniram para defender a sua vida e ficar livres dos seus inimigos; mataram setenta e cinco mil dos que os odiavam, mas não puseram as mãos no saque.",np:1,n:"Setenta e cinco mil: o grego diz quinze mil."},
{s:"A origem da festa de Purim"},
{v:17,t:"Isso aconteceu no dia treze do mês de Adar; no dia catorze descansaram e fizeram dele um dia de banquete e de alegria."},
{v:18,t:"Mas os judeus que estavam em Susa reuniram-se no dia treze e no dia catorze; no dia quinze descansaram e fizeram dele um dia de banquete e de alegria."},
{v:19,t:"Por isso os judeus do campo, que moram em povoados sem muralhas, fazem do dia catorze do mês de Adar um dia de alegria e de banquete, um dia de festa, em que mandam porções de comida uns aos outros. Mas os que moram nas cidades celebram também o dia quinze do mês de Adar com alegria e banquete, como dia de festa, e nele mandam porções de comida uns aos outros.",n:"A última frase (Mas os que moram nas cidades...) vem do grego."},
{v:"19a",t:"E os sátrapas das províncias, os príncipes e os escribas do rei honravam a Deus, porque o temor de Mardoqueu se apoderara deles; pois o decreto do rei tinha sido proclamado em todo o reino.",np:1,n:"Este versículo não está no hebraico; repete, de forma um pouco diferente, o que o grego diz em 9,3–4."},
{s:"As cartas de Mardoqueu e de Ester"},
{v:20,t:"Mardoqueu escreveu esses acontecimentos e enviou cartas a todos os judeus que estavam em todas as províncias do rei Assuero, aos de perto e aos de longe,"},
{v:21,t:"estabelecendo que celebrassem todos os anos o dia catorze e o dia quinze do mês de Adar,"},
{v:22,t:"como os dias em que os judeus ficaram livres dos seus inimigos, e o mês em que a sua tristeza se transformou em alegria e o seu luto em dia de festa; que fizessem deles dias de banquete e de alegria, mandando porções de comida uns aos outros e presentes aos pobres."},
{v:23,t:"Os judeus adotaram como costume o que tinham começado a fazer e o que Mardoqueu lhes tinha escrito.",np:1},
{v:24,t:"Pois Amã, filho de Amadata, o agagita, inimigo de todos os judeus, tinha tramado exterminar os judeus, e lançara o pur, isto é, a sorte, para os aterrorizar e exterminar."},
{v:25,t:"Mas, quando Ester se apresentou ao rei, ele ordenou por escrito que o plano perverso que Amã tramara contra os judeus recaísse sobre a sua cabeça; e o penduraram na forca, a ele e aos seus filhos."},
{v:26,t:"Por isso esses dias foram chamados Purim, do nome pur. Por isso, por causa de tudo o que dizia essa carta,"},
{v:27,t:"e do que eles mesmos tinham visto a esse respeito e do que lhes tinha acontecido, os judeus estabeleceram e aceitaram, para si, para a sua descendência e para todos os que se unissem a eles, como obrigação irrevogável, celebrar esses dois dias conforme o que estava escrito e no tempo fixado, todos os anos."},
{v:28,t:"Esses dias seriam lembrados e celebrados de geração em geração, em cada família, em cada província e em cada cidade; e esses dias de Purim não deixariam de ser celebrados entre os judeus, nem a sua lembrança se apagaria entre os seus descendentes."},
{v:29,t:"A rainha Ester, filha de Abiail, e o judeu Mardoqueu escreveram, com toda a autoridade, para confirmar esta segunda carta sobre o Purim.",np:1},
{v:30,t:"E enviaram cartas a todos os judeus, às cento e vinte e sete províncias do reino de Assuero, com palavras de paz e de verdade,"},
{v:31,t:"para confirmar esses dias de Purim nas suas datas, como o judeu Mardoqueu e a rainha Ester lhes tinham prescrito, e como eles mesmos tinham estabelecido para si e para a sua descendência, com os jejuns e as lamentações."},
{v:32,t:"A ordem de Ester confirmou estas prescrições do Purim, e isso foi escrito num livro."}
];

window.TEXTOS_SEED["ester"][10] = [
{s:"A grandeza de Mardoqueu"},
{v:1,t:"O rei Assuero impôs tributo à terra firme e às ilhas do mar."},
{v:2,t:"Todos os feitos do seu poder e da sua força, e a descrição exata da grandeza a que o rei elevou Mardoqueu, não estão escritos no livro dos Anais dos reis da Média e da Pérsia?"},
{v:3,t:"Pois o judeu Mardoqueu era o segundo depois do rei Assuero, grande entre os judeus e querido pela multidão dos seus irmãos; procurava o bem do seu povo e falava pela paz de toda a sua descendência."},
{s:"A explicação do sonho de Mardoqueu"},
{v:"3a",t:"E Mardoqueu disse a todos: Foi Deus quem fez essas coisas!",n:"Os versículos 3a–3k (10,4–13 na antiga Vulgata) explicam, segundo o grego, o sonho do início do livro (1,1a–1k)."},
{v:"3b",t:"Pois Mardoqueu se lembrou do sonho que tinha tido, que significava essas mesmas coisas; e nada dele deixou de se cumprir."},
{v:"3c",t:"A pequena fonte que se tornou um rio, e a luz, e o sol, e as águas abundantes: a fonte e o rio são Ester, que o rei tomou por esposa e quis que fosse rainha;"},
{v:"3d",t:"os dois dragões somos eu e Amã;"},
{v:"3e",t:"as nações que se tinham reunido são as que tentaram apagar o nome dos judeus;"},
{v:"3f",t:"e o meu povo, isto é, Israel, são os que clamaram ao Senhor; e o Senhor salvou o seu povo, livrou-nos de todos os males e fez grandes sinais e prodígios, como nunca se fizeram entre as nações."},
{v:"3g",t:"Ele determinou que houvesse duas sortes: uma para o povo de Deus e outra para todas as nações.",n:"Duas sortes: jogo com a palavra pur, sorte, de onde vem o nome da festa. A sorte lançada por Amã (3,7) foi mudada por Deus."},
{v:"3h",t:"E as duas sortes chegaram à hora e ao dia do julgamento, diante de Deus, para todas as nações."},
{v:"3i",t:"E Deus se lembrou do seu povo e fez justiça à sua herança."},
{v:"3k",t:"Esses dias do mês de Adar, o dia catorze e o dia quinze desse mês, serão celebrados como dias de reunião, de júbilo e de alegria diante de Deus, de geração em geração, para sempre, no povo de Israel.",n:"O grego termina com uma nota sobre a tradução desta carta de Purim, levada ao Egito no reinado de Ptolomeu e Cleópatra (11,1 na antiga Vulgata); a Nova Vulgata não a traz."}
];
