// =====================================================================
// Ester — tradução do hebraico; as partes que só existem em grego ou em latim
// (versículos com letra) seguem a Nova Vulgata, cotejada com o grego
// (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["ester"][1] = [
{s:"O sonho de Mardoqueu"},
{v:"1a",t:"No segundo ano do reinado do grande rei Artaxerxes, no primeiro dia do mês de Nisan, teve um sonho Mardoqueu, filho de Jair, filho de Semei, filho de Cis, da tribo de Benjamim,",n:"O livro de Ester chegou até nós em duas formas: o texto hebraico, mais breve, que nunca menciona o nome de Deus, e a tradução grega, que acrescenta seis trechos maiores (o sonho de Mardoqueu, as duas cartas do rei, as orações de Mardoqueu e de Ester, a entrada de Ester diante do rei e a explicação do sonho) e várias frases menores. São Jerônimo traduziu o hebraico e reuniu os acréscimos no fim do livro (10,4–16,24 da antiga Vulgata); a Nova Vulgata os recoloca no seu lugar, com números de versículo seguidos de letra. Nesta tradução, as partes hebraicas vêm do hebraico; as partes marcadas com letra seguem o texto latino da Nova Vulgata, que nelas acompanha muitas vezes a antiga versão latina, anterior a São Jerônimo, e foram cotejadas com o grego. Estes versículos 1a–1k estavam em 11,2–12 na antiga Vulgata. O grego chama o rei de Artaxerxes; o hebraico, de Assuero (veja a nota a 1,1)."},
{v:"1b",t:"homem importante, que servia na corte do rei."},
{v:"1c",t:"Este foi o seu sonho: houve vozes e tumulto, trovões e terremoto, e grande confusão sobre a terra.",np:1},
{v:"1d",t:"E eis que avançaram dois grandes dragões, ambos prontos para lutar;"},
{v:"1e",t:"travou-se entre eles uma grande batalha, e eles dominavam, e as nações se reuniram",n:"O grego diz: deram um grande rugido, e ao seu rugido todas as nações se prepararam para a guerra, para combater a nação dos justos. A Nova Vulgata segue aqui a antiga versão latina."},
{v:"1f",t:"num dia de trevas e de desgraça; e houve grande perturbação entre os habitantes da terra."},
{v:"1g",t:"Tiveram medo de ser destruídos",n:"O grego precisa: toda a nação dos justos se perturbou, temendo os males que a ameaçavam, e preparou-se para morrer."},
{v:"1h",t:"e clamaram a Deus. E do som do seu clamor nasceu uma pequena fonte, que cresceu até se tornar um rio muito grande e transbordou em águas abundantes."},
{v:"1i",t:"A luz e o sol se levantaram; os humildes foram exaltados e devoraram os ilustres.",np:1},
{v:"1k",t:"Quando Mardoqueu, depois de ver esse sonho, se levantou do leito, pôs-se a pensar no que Deus queria fazer; e guardou o sonho gravado no espírito até que lhe fosse revelado.",np:1,n:"O grego acrescenta aqui a conspiração de dois eunucos do rei, descoberta por Mardoqueu, e o ódio que Amã passou a ter por ele (12,1–6 na antiga Vulgata); o mesmo episódio é narrado pelo hebraico em 2,21–23. A Nova Vulgata não traz esse trecho."},
{s:"O banquete do rei Assuero"},
{v:1,t:"Nos dias de Assuero — o Assuero que reinou desde a Índia até a Etiópia, sobre cento e vinte e sete províncias —,",n:"Assuero é o nome hebraico de Xerxes I, rei da Pérsia de 486 a 465 a.C. A Índia é a região do rio Indo; a Etiópia (em hebraico, Cuch) é a Núbia, ao sul do Egito."},
{v:2,t:"naqueles dias, quando o rei Assuero se sentava no trono do seu reino, na cidadela de Susa,"},
{v:3,t:"no terceiro ano do seu reinado, ele deu um banquete a todos os seus príncipes e servidores; o exército da Pérsia e da Média, os nobres e os governadores das províncias estavam na sua presença,"},
{v:4,t:"enquanto ele mostrava a riqueza gloriosa do seu reino e o esplendor magnífico da sua grandeza, durante muitos dias: cento e oitenta dias."},
{v:5,t:"Terminados esses dias, o rei deu a todo o povo que se encontrava na cidadela de Susa, do maior ao menor, um banquete de sete dias no pátio do jardim do palácio real.",np:1},
{v:6,t:"Havia tapeçarias de linho branco, de algodão e de púrpura violeta, presas por cordões de linho fino e de púrpura a argolas de prata e a colunas de mármore; havia leitos de ouro e de prata sobre um pavimento de pórfiro e de mármore, de nácar e de pedras coloridas.",n:"Os nomes das pedras do pavimento são raros e de sentido incerto."},
{v:7,t:"Serviam-se as bebidas em taças de ouro, cada uma diferente da outra, e o vinho real corria em abundância, conforme a generosidade do rei."},
{v:8,t:"E bebia-se conforme a regra: ninguém era obrigado; pois o rei tinha ordenado a todos os mordomos do seu palácio que fizessem conforme a vontade de cada um."},
{v:9,t:"Também a rainha Vasti deu um banquete para as mulheres, no palácio real do rei Assuero.",np:1},
{s:"A rainha Vasti é deposta"},
{v:10,t:"No sétimo dia, quando o coração do rei estava alegre com o vinho, ele ordenou a Maumã, Bazata, Harbona, Bagata, Abgata, Zetar e Carcas, os sete eunucos que serviam na presença do rei Assuero,"},
{v:11,t:"que trouxessem à presença do rei a rainha Vasti, com a coroa real, para mostrar aos povos e aos príncipes a sua beleza, pois era muito formosa."},
{v:12,t:"Mas a rainha Vasti recusou-se a vir, como o rei lhe mandara dizer pelos eunucos. O rei enfureceu-se muito, e a sua ira ardeu dentro dele.",np:1},
{v:13,t:"Então o rei consultou os sábios que conheciam os tempos (pois era assim que se tratavam os assuntos do rei, diante de todos os que conheciam a lei e o direito,"},
{v:14,t:"e os mais próximos dele eram Carsena, Setar, Admata, Társis, Mares, Marsana e Mamucã, os sete príncipes da Pérsia e da Média, que viam a face do rei e ocupavam os primeiros lugares no reino):"},
{v:15,t:"Segundo a lei, que se deve fazer à rainha Vasti, por não ter cumprido a ordem do rei Assuero, transmitida pelos eunucos?"},
{v:16,t:"Mamucã respondeu diante do rei e dos príncipes: A rainha Vasti não ofendeu somente o rei, mas também todos os príncipes e todos os povos que há em todas as províncias do rei Assuero.",np:1},
{v:17,t:"Pois o procedimento da rainha chegará ao conhecimento de todas as mulheres, e elas passarão a desprezar os seus maridos, dizendo: O rei Assuero mandou trazer à sua presença a rainha Vasti, e ela não foi."},
{v:18,t:"Hoje mesmo as princesas da Pérsia e da Média, que souberem do procedimento da rainha, falarão disso a todos os príncipes do rei; e haverá desprezo e cólera de sobra."},
{v:19,t:"Se parecer bem ao rei, saia da sua parte um decreto real, e seja escrito entre as leis da Pérsia e da Média, que não podem ser revogadas: que Vasti não volte mais à presença do rei Assuero, e que o rei dê a sua dignidade de rainha a outra melhor do que ela."},
{v:20,t:"E, quando o edito que o rei promulgar for conhecido em todo o seu reino, que é imenso, todas as mulheres honrarão os seus maridos, do maior ao menor."},
{v:21,t:"A proposta agradou ao rei e aos príncipes, e o rei fez conforme a palavra de Mamucã.",np:1},
{v:22,t:"Enviou cartas a todas as províncias do rei, a cada província segundo a sua escrita e a cada povo segundo a sua língua, para que todo homem fosse senhor na sua casa e falasse a língua do seu povo.",n:"E falasse a língua do seu povo: isto é, que em casa prevalecesse a língua do marido, quando a mulher fosse de outro povo. A Nova Vulgata, seguindo São Jerônimo, diz em lugar disso: e tivesse sujeitas todas as mulheres da sua casa."}
];

window.TEXTOS_SEED["ester"][2] = [
{s:"A procura de uma nova rainha"},
{v:1,t:"Depois desses acontecimentos, quando a ira do rei Assuero se acalmou, ele se lembrou de Vasti, do que ela tinha feito e do que fora decretado contra ela."},
{v:2,t:"Então os jovens que serviam o rei disseram: Procurem-se para o rei moças virgens de bela aparência;"},
{v:3,t:"nomeie o rei comissários em todas as províncias do seu reino, e reúnam eles todas as moças virgens de bela aparência na cidadela de Susa, na casa das mulheres, aos cuidados de Egeu, eunuco do rei, guarda das mulheres; e que lhes sejam dados os unguentos de beleza."},
{v:4,t:"E a moça que agradar aos olhos do rei reinará em lugar de Vasti. A proposta agradou ao rei, e ele assim fez."},
{s:"Mardoqueu e Ester"},
{v:5,t:"Havia na cidadela de Susa um judeu chamado Mardoqueu, filho de Jair, filho de Semei, filho de Cis, benjaminita,"},
{v:6,t:"que fora levado de Jerusalém para o exílio com os deportados que foram levados com Jeconias, rei de Judá, deportados por Nabucodonosor, rei da Babilônia.",n:"Jeconias é o rei Joaquin, deportado em 597 a.C. (2 Reis 24,8–16). Se quem foi deportado é Mardoqueu, ele teria mais de cem anos no tempo de Xerxes; por isso muitos entendem que a frase se refere ao seu bisavô Cis."},
{v:7,t:"Ele criava Edissa, isto é, Ester, filha do seu tio, porque ela não tinha pai nem mãe. A moça era de belo porte e de bela aparência; e, quando o pai e a mãe dela morreram, Mardoqueu adotou-a como filha.",n:"Edissa: em hebraico, Hadassa, que quer dizer murta. Ester é nome persa (talvez estrela) ou babilônico (de Ishtar)."},
{v:8,t:"Quando se divulgaram a ordem do rei e o seu decreto, e muitas moças foram reunidas na cidadela de Susa aos cuidados de Egeu, também Ester foi levada ao palácio do rei, aos cuidados de Egeu, guarda das mulheres.",np:1},
{v:9,t:"A moça agradou-lhe e ganhou a sua benevolência; ele se apressou a dar-lhe os unguentos de beleza e as suas porções de comida, e também as sete moças escolhidas do palácio do rei que lhe cabiam; e transferiu-a com as suas moças para o melhor lugar da casa das mulheres."},
{v:10,t:"Ester não tinha revelado o seu povo nem a sua origem, porque Mardoqueu lhe ordenara que não o revelasse."},
{v:11,t:"E todos os dias Mardoqueu passeava diante do pátio da casa das mulheres, para saber como Ester estava e o que acontecia com ela."},
{v:12,t:"Quando chegava a vez de cada moça ir ao rei Assuero, depois de ter cumprido o regulamento das mulheres durante doze meses — pois assim se completavam os dias dos seus tratamentos de beleza: seis meses com óleo de mirra e seis meses com bálsamos e unguentos de mulheres —,",np:1},
{v:13,t:"a moça ia ao rei deste modo: tudo o que ela pedisse lhe era dado, para levar consigo da casa das mulheres ao palácio do rei."},
{v:14,t:"Ela ia à tarde e, pela manhã, voltava para a segunda casa das mulheres, aos cuidados de Sasagaz, eunuco do rei, guarda das concubinas. Não voltava mais ao rei, a não ser que o rei a desejasse e ela fosse chamada pelo nome."},
{s:"Ester torna-se rainha"},
{v:15,t:"Quando chegou a vez de Ester, filha de Abiail, tio de Mardoqueu, que a adotara como filha, de ir ao rei, ela não pediu nada além do que Egeu, eunuco do rei, guarda das mulheres, lhe indicou. E Ester ganhava a simpatia de todos os que a viam."},
{v:16,t:"Ester foi levada ao rei Assuero, ao seu palácio real, no décimo mês, que é o mês de Tebet, no sétimo ano do seu reinado."},
{v:17,t:"O rei amou Ester mais do que todas as mulheres, e ela ganhou a sua simpatia e o seu favor mais do que todas as virgens. Ele pôs a coroa real na cabeça dela e a fez rainha em lugar de Vasti."},
{v:18,t:"Depois o rei deu um grande banquete a todos os seus príncipes e servidores, o banquete de Ester; concedeu às províncias uma dispensa de impostos e distribuiu presentes com generosidade real."},
{s:"Mardoqueu descobre uma conspiração"},
{v:19,t:"Mardoqueu estava sentado à porta do rei.",n:"O hebraico começa: Quando as virgens foram reunidas pela segunda vez... Essas palavras, de sentido obscuro, faltam no grego e na Nova Vulgata."},
{v:20,t:"Ester ainda não tinha revelado a sua origem nem o seu povo, como Mardoqueu lhe ordenara; pois Ester cumpria as ordens de Mardoqueu, como no tempo em que era criada por ele."},
{v:21,t:"Naqueles dias, enquanto Mardoqueu estava sentado à porta do rei, Bagatã e Tares, dois eunucos do rei, guardas da entrada, se irritaram e procuravam um modo de atentar contra o rei Assuero.",np:1},
{v:22,t:"Mardoqueu soube da trama e a contou à rainha Ester, e Ester a comunicou ao rei em nome de Mardoqueu."},
{v:23,t:"Investigou-se o caso e foi comprovado, e os dois foram pendurados numa forca. E isso foi escrito no livro dos Anais, na presença do rei.",n:"Forca: literalmente, madeiro. Talvez se trate de empalamento, suplício usado pelos persas."}
];

window.TEXTOS_SEED["ester"][3] = [
{s:"Amã decide exterminar os judeus"},
{v:1,t:"Depois desses acontecimentos, o rei Assuero engrandeceu Amã, filho de Amadata, o agagita; elevou-o e pôs o seu assento acima de todos os príncipes que estavam com ele.",n:"Agagita: descendente de Agag, rei de Amalec, o antigo inimigo de Israel, a quem Saul poupou (1 Samuel 15). Mardoqueu, da família de Cis, pai de Saul, vê-se de novo diante de um descendente de Agag."},
{v:2,t:"Todos os servidores do rei que ficavam à porta do rei dobravam o joelho e se prostravam diante de Amã, porque assim o rei tinha ordenado a respeito dele. Mas Mardoqueu não dobrava o joelho nem se prostrava.",n:"O hebraico não diz por que Mardoqueu se recusava; a sua oração, em 4,17f–17g, dá a razão."},
{v:3,t:"Os servidores do rei que ficavam à porta do rei disseram a Mardoqueu: Por que transgrides a ordem do rei?"},
{v:4,t:"Como lhe diziam isso todos os dias e ele não os escutava, contaram-no a Amã, para ver se as palavras de Mardoqueu se sustentariam; pois ele lhes tinha dito que era judeu."},
{v:5,t:"Amã viu que Mardoqueu não dobrava o joelho nem se prostrava diante dele, e encheu-se de furor.",np:1},
{v:6,t:"Mas achou pouco pôr as mãos somente em Mardoqueu, porque lhe tinham dito qual era o povo de Mardoqueu; e Amã procurou exterminar todos os judeus que havia em todo o reino de Assuero, o povo de Mardoqueu."},
{v:7,t:"No primeiro mês, que é o mês de Nisan, no décimo segundo ano do rei Assuero, lançou-se o pur, isto é, a sorte, diante de Amã, para saber em que dia e em que mês o povo judeu devia ser exterminado; e a sorte caiu no dia treze do décimo segundo mês, que é o mês de Adar.",np:1,n:"O hebraico diz apenas: de dia em dia e de mês em mês, até o décimo segundo mês, que é o mês de Adar. A Nova Vulgata completa a frase com o que se lê em 3,13. Pur é palavra acádica que quer dizer sorte; dela vem o nome da festa de Purim (9,26)."},
{v:8,t:"Então Amã disse ao rei Assuero: Há um povo espalhado e disperso entre os povos, em todas as províncias do teu reino, cujas leis são diferentes das de todos os outros povos, e que não cumpre as leis do rei. Não convém ao rei deixá-lo em paz."},
{v:9,t:"Se parecer bem ao rei, escreva-se um decreto para exterminá-los, e eu pesarei dez mil talentos de prata nas mãos dos funcionários, para que sejam levados ao tesouro do rei.",n:"Dez mil talentos: soma enorme, mais de trezentas toneladas de prata. Segundo Heródoto, todo o império persa pagava ao rei, por ano, cerca de catorze mil e quinhentos talentos."},
{v:10,t:"O rei tirou o anel da sua mão e o deu a Amã, filho de Amadata, o agagita, inimigo dos judeus."},
{v:11,t:"E o rei disse a Amã: A prata fica contigo, e o povo também; faze com ele o que te parecer bem."},
{s:"O decreto contra os judeus"},
{v:12,t:"No dia treze do primeiro mês foram convocados os escribas do rei, e escreveu-se tudo o que Amã ordenou aos sátrapas do rei, aos governadores de cada província e aos chefes de cada povo, a cada província segundo a sua escrita e a cada povo segundo a sua língua. Foi escrito em nome do rei Assuero e selado com o anel do rei."},
{v:13,t:"As cartas foram enviadas por meio de mensageiros a todas as províncias do rei, com ordem de exterminar, matar e aniquilar todos os judeus, jovens e velhos, crianças e mulheres, num só dia, o dia treze do décimo segundo mês, que é o mês de Adar, e de saquear os seus bens."},
{v:"13a",t:"Esta era a cópia da carta: O grande rei Artaxerxes escreve o seguinte aos sátrapas e governadores das cento e vinte e sete províncias, da Índia até a Etiópia, que estão sujeitos ao seu domínio:",np:1,n:"Os versículos 13a–13g reproduzem o texto do decreto segundo o grego (13,1–7 na antiga Vulgata)."},
{v:"13b",t:"Tendo eu domínio sobre muitíssimas nações e havendo submetido ao meu poder o mundo inteiro, quis não abusar da grandeza do meu poder, mas, procedendo sempre com clemência e brandura, governar a vida dos meus súditos sem nenhum temor, oferecer um reino tranquilo e transitável até os seus confins e restabelecer a paz que todos os mortais desejam."},
{v:"13c",t:"Quando perguntei aos meus conselheiros como se poderia realizar isso, um deles, que se distingue entre todos pela prudência, pela boa vontade e pela fidelidade constante, e que ocupa o segundo lugar depois do rei, chamado Amã,"},
{v:"13d",t:"mostrou-me que, entre as tribos de toda a terra, está disperso um povo hostil, que, com as suas leis, age contra os costumes de todas as nações e despreza continuamente as ordens dos reis, de modo que não pode subsistir a concórdia das nações que consolidamos."},
{v:"13e",t:"Informados disso, e vendo que esta nação, a única rebelde a todo o gênero humano, segue leis perversas, se opõe aos nossos interesses, comete os piores crimes e impede a paz do reino,"},
{v:"13f",t:"ordenamos que todos os que Amã, que está à frente dos negócios públicos e a quem honramos como a um pai, vos indicar por carta sejam exterminados pela raiz, com as mulheres e os filhos, pela espada dos inimigos, sem que ninguém tenha piedade deles, no dia catorze do décimo segundo mês, Adar, deste ano;",n:"Dia catorze: assim o grego; o hebraico, em 3,13, diz dia treze."},
{v:"13g",t:"para que esses homens, perversos desde há muito tempo, descendo violentamente num só dia à morada dos mortos, nos deixem para o futuro os negócios do Estado plenamente estáveis e tranquilos."},
{v:"13h",t:"Quem esconder alguém dessa raça ficará sem lugar onde morar, não só entre os homens, mas nem mesmo entre as aves, e será queimado no fogo sagrado; e os seus bens serão confiscados para o reino. Passai bem.",n:"Este versículo só existe na antiga versão latina. O fogo sagrado era venerado pelos persas."},
{v:14,t:"Uma cópia do escrito devia ser promulgada como lei em cada província e dada a conhecer a todos os povos, para que estivessem preparados para aquele dia.",np:1},
{v:15,t:"Os mensageiros partiram apressados por ordem do rei, e o decreto foi promulgado na cidadela de Susa. E, enquanto o rei e Amã se sentavam para beber, a cidade de Susa estava consternada."},
{s:"A oração dos judeus"},
{v:"15a",t:"Todos os povos fizeram festa; e o rei e Amã, tendo entrado no palácio, entregavam-se aos prazeres com os seus amigos.",n:"Os versículos 15a–15i, com a oração dos judeus, não estão no hebraico nem no grego; a Nova Vulgata os toma da antiga versão latina."},
{v:"15b",t:"E, onde quer que se afixasse a cópia da carta, havia pranto e grande luto entre todos os judeus."},
{v:"15c",t:"E os judeus invocavam o Deus dos seus pais, dizendo:"},
{v:"15d",l:["Senhor Deus, só tu és Deus lá no alto do céu,","e não há outro Deus além de ti."],np:1},
{v:"15e",l:["Se tivéssemos cumprido a tua lei e os teus mandamentos,","teríamos vivido em segurança e em paz todo o tempo da nossa vida."],np:1},
{v:"15f",l:["Mas agora, porque não cumprimos os teus mandamentos,","veio sobre nós toda esta tribulação."],np:1},
{v:"15g",l:["Tu és justo e clemente, altíssimo e grande, Senhor,","e todos os teus caminhos são justiça."],np:1},
{v:"15h",l:["E agora, Senhor, não entregues os teus filhos ao cativeiro,","nem as nossas mulheres à violação e à perdição,","tu que foste propício para conosco desde o Egito até hoje."],np:1},
{v:"15i",l:["Tem piedade da tua porção principal","e não entregues à infâmia a tua herança,","deixando que os inimigos nos dominem."],np:1}
];

window.TEXTOS_SEED["ester"][4] = [
{s:"O luto dos judeus"},
{v:1,t:"Quando Mardoqueu soube de tudo o que tinha acontecido, rasgou as suas vestes, vestiu-se de saco e cobriu-se de cinza; e saiu pelo meio da cidade, soltando um grito forte e amargo,"},
{v:2,t:"e chegou até diante da porta do rei; pois não era permitido entrar pela porta do rei vestido de saco."},
{v:3,t:"Em cada província, em todo lugar aonde chegavam a ordem do rei e o seu decreto, havia grande luto entre os judeus, com jejum, choro e lamentação; e muitos se deitavam sobre saco e cinza."},
{s:"Mardoqueu pede a intercessão de Ester"},
{v:4,t:"As moças de Ester e os seus eunucos vieram contar-lhe isso, e a rainha ficou muito angustiada. Mandou roupas para que Mardoqueu se vestisse e tirasse o saco; mas ele não as aceitou."},
{v:5,t:"Então Ester chamou Atac, um dos eunucos do rei, que ele pusera ao serviço dela, e mandou-o ter com Mardoqueu, para saber o que era aquilo e por que era."},
{v:6,t:"Atac saiu ao encontro de Mardoqueu, na praça da cidade, que ficava diante da porta do rei.",np:1},
{v:7,t:"Mardoqueu contou-lhe tudo o que lhe tinha acontecido e a quantia exata de prata que Amã prometera pagar ao tesouro do rei em troca da destruição dos judeus."},
{v:8,t:"Deu-lhe também uma cópia do texto do decreto promulgado em Susa para exterminá-los, para que a mostrasse a Ester, a pusesse a par de tudo e lhe ordenasse que se apresentasse ao rei, para lhe suplicar e interceder diante dele pelo seu povo."},
{v:"8a",t:"Lembra-te, disse ele, dos dias da tua humildade, quando eras criada pela minha mão; porque Amã, o segundo depois do rei, falou contra nós para nos dar a morte. Invoca o Senhor, fala ao rei em nosso favor e livra-nos da morte.",n:"Este versículo vem do grego (15,1–3 na antiga Vulgata)."},
{v:9,t:"Atac voltou e contou a Ester as palavras de Mardoqueu."},
{v:10,t:"Então Ester falou a Atac e mandou-o dizer a Mardoqueu:",np:1},
{v:11,t:"Todos os servidores do rei e o povo das províncias do rei sabem que, para todo homem ou mulher que se apresenta ao rei no pátio interior sem ser chamado, há uma só lei: a morte; a não ser que o rei lhe estenda o cetro de ouro, e então viverá. E eu já faz trinta dias que não sou chamada para ir ao rei."},
{v:12,t:"Quando contaram a Mardoqueu as palavras de Ester,"},
{v:13,t:"Mardoqueu mandou responder a Ester: Não penses que, por estares no palácio do rei, escaparás sozinha entre todos os judeus."},
{v:14,t:"Porque, se te calares agora, o alívio e a libertação virão para os judeus de outra parte, mas tu e a casa de teu pai perecereis. E quem sabe se não foi para uma ocasião como esta que chegaste à realeza?",n:"De outra parte: discreta alusão a Deus, cujo nome o texto hebraico nunca pronuncia."},
{v:15,t:"Então Ester mandou responder a Mardoqueu:",np:1},
{v:16,t:"Vai, reúne todos os judeus que se encontram em Susa, e jejuai por mim: não comais nem bebais durante três dias, noite e dia. Também eu e as minhas moças jejuaremos assim; e depois irei ao rei, contra a lei; e, se eu perecer, pereci."},
{v:17,t:"Mardoqueu retirou-se e fez tudo como Ester lhe ordenara."},
{s:"A oração de Mardoqueu"},
{v:"17a",t:"Mardoqueu rasgou as suas vestes, estendeu no chão um cilício e prostrou-se com o rosto em terra, e com ele os anciãos do povo, desde a manhã até a tarde,",n:"Os versículos 17a–17kk trazem as orações de Mardoqueu e de Ester (13,8–14,19 na antiga Vulgata). Este versículo vem da antiga versão latina; o grego começa: Mardoqueu suplicou ao Senhor, recordando todas as obras do Senhor."},
{v:"17b",l:["e disse:","Deus de Abraão, Deus de Isaac e Deus de Jacó, bendito és tu."],np:1},
{v:"17c",l:["Senhor, Senhor, rei todo-poderoso,","todas as coisas estão sob o teu poder,","e não há quem possa resistir à tua vontade,","se decidires salvar Israel."],np:1},
{v:"17d",l:["Tu fizeste o céu e a terra","e todas as maravilhas que o céu abrange;"],np:1},
{v:"17e",l:["és o Senhor de todas as coisas,","e não há quem resista à tua majestade."],np:1},
{v:"17f",l:["Tu sabes, Senhor, que eu de bom grado beijaria","as plantas dos pés de Amã pela salvação de Israel;"],np:1},
{v:"17g",l:["se não me prostrei diante dele,","foi para não pôr a glória de um homem acima da glória do meu Deus;","e não adorarei ninguém senão a ti, Senhor, meu Deus."],np:1},
{v:"17h",l:["E não faço isso por arrogância","nem por desejo de glória, Senhor.","Aparece, Senhor; manifesta-te, Senhor!"],np:1},
{v:"17i",l:["E agora, Senhor rei, Deus de Abraão, Deus de Isaac e Deus de Jacó,","poupa o teu povo,","porque os nossos inimigos querem destruir-nos","e aniquilar a tua herança."],np:1},
{v:"17k",l:["Não desprezes a tua porção,","que resgataste para ti da terra do Egito."],np:1},
{v:"17l",l:["Ouve a minha súplica","e sê propício ao teu quinhão;","muda o nosso luto em alegria,","para que, vivos, louvemos o teu nome, Senhor;","não feches a boca dos que te cantam."],np:1},
{v:"17m",t:"E todo o Israel clamou ao Senhor com todas as suas forças, porque uma morte certa o ameaçava.",np:1},
{s:"A oração de Ester"},
{v:"17n",t:"Também a rainha Ester buscou refúgio no Senhor, temendo o perigo de morte que a ameaçava."},
{v:"17o",t:"Despiu as vestes de glória, pôs roupas de luto e, em lugar dos perfumes de luxo, cobriu a cabeça de cinza e humilhou muito o seu corpo com jejuns."},
{v:"17p",t:"E prostrou-se por terra com as suas servas, desde a manhã até a tarde, e disse:",n:"No grego, a oração de Ester é diferente em vários pontos; a Nova Vulgata segue aqui a antiga versão latina, que traz, por exemplo, a lista das libertações de 17s–17aa."},
{v:"17q",l:["Deus de Abraão, Deus de Isaac e Deus de Jacó, bendito és tu.","Socorre-me, a mim que estou só","e não tenho outro defensor além de ti, Senhor,"],np:1},
{v:"17r",l:["porque o perigo está nas minhas mãos."],np:1},
{v:"17s",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que guardaste Noé nas águas do dilúvio."],np:1},
{v:"17t",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que a Abraão, com trezentos e dezoito homens,","entregaste nove reis."],np:1,n:"Nove reis: os quatro que Abraão derrotou (Gênesis 14,14–15) e os cinco que eles tinham vencido antes, contados juntos."},
{v:"17u",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que livraste Jonas do ventre do grande peixe."],np:1},
{v:"17v",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que livraste Ananias, Azarias e Misael da fornalha de fogo."],np:1},
{v:"17x",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que arrancaste Daniel da cova dos leões."],np:1},
{v:"17y",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que tiveste compaixão de Ezequias, rei dos judeus,","condenado à morte e rezando pela sua vida,","e lhe deste mais quinze anos de vida."],np:1},
{v:"17z",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que a Ana, que te pedia com todo o desejo da sua alma,","concedeste gerar um filho."],np:1},
{v:"17aa",l:["Ouvi ler nos livros dos meus antepassados, Senhor,","que livras, Senhor, todos os que te agradam,","até o fim."],np:1},
{v:"17bb",l:["E agora ajuda-me, a mim que estou sozinha","e não tenho ninguém senão a ti,","Senhor, meu Deus."],np:1},
{v:"17cc",l:["Tu sabes","que a tua serva abomina o leito dos incircuncisos."],np:1},
{v:"17dd",l:["Deus, tu sabes","que não comi da mesa das abominações","nem bebi o vinho das suas libações."],np:1},
{v:"17ee",l:["Tu sabes","que, desde o dia em que fui levada para cá,","não me alegrei, Senhor,","senão em ti somente."],np:1},
{v:"17ff",l:["Tu sabes, Deus,","que, desde que trago este adorno sobre a cabeça,","eu o detesto como um pano de mulher menstruada","e não o visto em dia de festa."],np:1,n:"Este adorno é o diadema real. O grego diz: não o uso nos meus dias de descanso; isto é, Ester só o põe quando tem de aparecer em público."},
{v:"17gg",l:["E agora socorre-me, a mim que sou órfã;","põe na minha boca uma palavra oportuna diante do leão,","faze que eu lhe seja agradável","e muda o seu coração, para que odeie aquele que nos combate,","para a ruína dele e dos que estão de acordo com ele."],np:1,n:"O leão é o rei."},
{v:"17hh",l:["Livra-nos das mãos dos nossos inimigos;","muda o nosso luto em alegria","e as nossas dores em saúde."],np:1},
{v:"17ii",l:["E os que se levantam contra a tua porção, ó Deus,","faze deles um exemplo."],np:1},
{v:"17kk",l:["Aparece, Senhor; manifesta-te, Senhor!"],np:1}
];
