// =====================================================================
// Êxodo — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["exodo"][1] = [
{s:"Os israelitas oprimidos no Egito"},
{v:1,t:"Estes são os nomes dos filhos de Israel que foram para o Egito com Jacó, cada um com a sua família:",n:"O Êxodo retoma a história onde o Gênesis a deixou (Gênesis 46,8–27; 50,26). A família de setenta pessoas vai se tornar um povo, e o povo escravizado vai conhecer o nome do seu Deus."},
{v:2,t:"Rúben, Simeão, Levi e Judá,"},
{v:3,t:"Issacar, Zabulon e Benjamim,"},
{v:4,t:"Dã e Neftali, Gad e Aser."},
{v:5,t:"Os descendentes de Jacó eram, ao todo, setenta pessoas; José já estava no Egito."},
{v:6,t:"José morreu, e também todos os seus irmãos e toda aquela geração;"},
{v:7,t:"mas os filhos de Israel foram fecundos, multiplicaram-se, cresceram e se tornaram muito poderosos, e a terra ficou cheia deles.",n:"Eco da bênção da criação: sede fecundos, multiplicai-vos e enchei a terra (Gênesis 1,28)."},
{v:8,t:"Subiu ao trono do Egito um novo rei, que não tinha conhecido José.",np:1},
{v:9,t:"Ele disse ao seu povo: Vede: o povo dos filhos de Israel é mais numeroso e mais forte do que nós."},
{v:10,t:"Vamos agir com astúcia contra ele, para que não se multiplique mais; do contrário, em caso de guerra, pode aliar-se aos nossos inimigos, combater contra nós e sair do país.",np:1},
{v:11,t:"Puseram sobre eles capatazes, para oprimi-los com trabalhos forçados; e eles construíram para o faraó as cidades-armazéns de Pitom e Ramessés.",n:"Ramessés: provavelmente a cidade de Ramsés II, no século XIII antes de Cristo, o faraó sob o qual muitos situam o Êxodo."},
{v:12,t:"Mas, quanto mais os oprimiam, tanto mais eles se multiplicavam e cresciam.",np:1},
{v:13,t:"Os egípcios passaram a ter medo dos filhos de Israel e os reduziram à escravidão"},
{v:14,t:"e lhes amarguravam a vida com trabalhos pesados de barro e de tijolos e com toda espécie de trabalhos no campo, a que os obrigavam com dureza."},
{v:15,t:"O rei do Egito falou também às parteiras dos hebreus, uma das quais se chamava Sefra, e a outra Fua,",np:1},
{v:16,t:"e lhes ordenou: Quando assistirdes as mulheres hebreias no parto, observai: se for menino, matai-o; se for menina, deixai-a viver."},
{v:17,t:"Mas as parteiras temiam a Deus e não fizeram o que o rei do Egito lhes tinha ordenado: deixavam viver os meninos.",n:"Primeira desobediência civil da Bíblia: duas mulheres, cujos nomes o texto guarda, enquanto o faraó fica sem nome."},
{v:18,t:"O rei do Egito chamou as parteiras e lhes disse: Por que fizestes isso, deixando viver os meninos?"},
{v:19,t:"As parteiras responderam ao faraó: As mulheres hebreias não são como as egípcias: são robustas e dão à luz antes que a parteira chegue.",np:1},
{v:20,t:"Deus fez bem às parteiras; e o povo se multiplicou e se tornou muito forte."},
{v:21,t:"E, porque as parteiras temeram a Deus, ele lhes deu uma família."},
{v:22,t:"Então o faraó deu esta ordem a todo o seu povo: Todo menino que nascer, lançai-o ao Rio; mas deixai viver todas as meninas.",np:1,n:"O Rio: o Nilo. Mateus verá um eco deste relato na matança dos inocentes por Herodes (Mateus 2,16)."}
];

window.TEXTOS_SEED["exodo"][2] = [
{s:"O nascimento de Moisés"},
{v:1,t:"Um homem da casa de Levi foi tomar por mulher uma filha de Levi."},
{v:2,t:"Ela concebeu e deu à luz um filho; e, vendo que era bonito, escondeu-o durante três meses."},
{v:3,t:"Quando não pôde mais escondê-lo, tomou um cesto de papiro, vedou-o com betume e piche, pôs dentro o menino e o colocou entre os juncos, à beira do Rio,",np:1,n:"Cesto: a mesma palavra hebraica da arca de Noé (Gênesis 6,14); outra vez uma caixa vedada com betume salva a vida sobre as águas."},
{v:4,t:"enquanto a irmã do menino ficava de longe, para ver o que lhe aconteceria."},
{v:5,t:"Nisso a filha do faraó desceu para se banhar no Rio, enquanto as suas criadas andavam pela margem. Ela viu o cesto no meio do juncal e mandou uma das suas servas buscá-lo.",np:1},
{v:6,t:"Abriu-o e viu a criança: era um menino que chorava. Teve pena dele e disse: É um dos filhos dos hebreus."},
{v:7,t:"A irmã do menino disse à filha do faraó: Queres que eu vá chamar uma ama entre as mulheres hebreias, para que te amamente o menino?"},
{v:8,t:"A filha do faraó respondeu: Vai. E a moça foi chamar a mãe do menino."},
{v:9,t:"A filha do faraó lhe disse: Leva este menino e amamenta-o para mim; eu te pagarei o teu salário. A mulher tomou o menino e o amamentou; e, quando ele cresceu, levou-o à filha do faraó."},
{v:10,t:"Ela o adotou como filho e lhe deu o nome de Moisés, dizendo: Eu o tirei das águas.",n:"Moisés é um nome egípcio, que significa filho, como em Ramsés, filho de Rá; o texto o aproxima do verbo hebraico mashah, tirar das águas."},
{s:"Moisés foge para Madiã"},
{v:11,t:"Naqueles dias, quando Moisés já era adulto, saiu para ver os seus irmãos e viu os trabalhos pesados que faziam; viu também um egípcio que batia num hebreu, um dos seus irmãos."},
{v:12,t:"Olhou para um lado e para o outro e, vendo que não havia ninguém, matou o egípcio e o escondeu na areia.",n:"Nota do tradutor: o narrador não aprova nem condena o gesto de Moisés; o texto não foi suavizado. Estêvão o interpreta como uma primeira tentativa, incompreendida, de libertar os irmãos (Atos 7,23–29)."},
{v:13,t:"No dia seguinte, saiu de novo e viu dois hebreus brigando; e disse ao que estava errado: Por que bates no teu companheiro?"},
{v:14,t:"Ele respondeu: Quem te constituiu chefe e juiz sobre nós? Queres matar-me, como mataste o egípcio? Moisés ficou com medo e pensou: Com certeza o caso se tornou conhecido."},
{v:15,t:"O faraó soube do caso e procurou matar Moisés. Moisés fugiu da presença do faraó e foi morar na terra de Madiã; chegando à terra de Madiã, sentou-se junto a um poço.",np:1},
{v:16,t:"O sacerdote de Madiã tinha sete filhas, que vieram tirar água e encheram os bebedouros para dar de beber ao rebanho de seu pai."},
{v:17,t:"Chegaram uns pastores e as expulsaram; mas Moisés se levantou, defendeu as moças e deu de beber ao rebanho delas.",np:1,n:"Encontro junto a um poço, como o do servo de Abraão com Rebeca (Gênesis 24) e o de Jacó com Raquel (Gênesis 29): o leitor já sabe como a história termina."},
{v:18,t:"Quando voltaram para junto de Raguel, seu pai, ele lhes perguntou: Por que voltastes hoje tão cedo?",n:"Raguel: o sogro de Moisés é chamado também Jetro (3,1) e Hobab (Juízes 4,11; compare Números 10,29): tradições diferentes."},
{v:19,t:"Responderam: Um egípcio nos defendeu dos pastores; e ainda tirou água para nós e deu de beber ao rebanho."},
{v:20,t:"Ele disse às filhas: E onde está ele? Por que deixastes ir embora esse homem? Chamai-o para comer conosco."},
{v:21,t:"Moisés aceitou morar com aquele homem, que lhe deu por mulher sua filha Séfora."},
{v:22,t:"Ela deu à luz um filho, a quem Moisés chamou Gersam, porque dizia: Sou um estrangeiro em terra estranha.",n:"Gersam soa em hebraico como estrangeiro ali."},
{s:"Deus ouve o clamor do seu povo"},
{v:23,t:"Muito tempo depois, o rei do Egito morreu. Os filhos de Israel gemiam por causa da escravidão e clamavam; e do fundo da sua escravidão o seu clamor subiu até Deus."},
{v:24,t:"Deus ouviu os seus gemidos e se lembrou da sua aliança com Abraão, com Isaac e com Jacó."},
{v:25,t:"O Senhor olhou para os filhos de Israel e se manifestou a eles.",n:"E se manifestou a eles: assim a Nova Vulgata, com a tradução grega; o hebraico diz: e Deus tomou conhecimento."}
];

window.TEXTOS_SEED["exodo"][3] = [
{s:"A sarça ardente"},
{v:1,t:"Moisés apascentava o rebanho de Jetro, seu sogro, sacerdote de Madiã. Levou o rebanho para além do deserto e chegou ao Horeb, a montanha de Deus.",n:"O Horeb é outro nome do Sinai, o monte da aliança."},
{v:2,t:"O anjo do Senhor lhe apareceu numa chama de fogo, do meio de uma sarça. Moisés olhou: a sarça ardia no fogo, mas não se consumia."},
{v:3,t:"Moisés disse: Vou aproximar-me para ver este grande espetáculo: por que a sarça não se consome?",np:1},
{v:4,t:"O Senhor viu que ele se aproximava para ver; e Deus o chamou do meio da sarça: Moisés, Moisés! Ele respondeu: Aqui estou."},
{v:5,t:"Deus disse: Não te aproximes daqui; tira as sandálias dos pés, porque o lugar onde estás é terra santa."},
{v:6,t:"E acrescentou: Eu sou o Deus de teu pai, o Deus de Abraão, o Deus de Isaac e o Deus de Jacó. Moisés cobriu o rosto, porque tinha medo de olhar para Deus.",n:"Jesus cita estas palavras para mostrar que Deus é Deus dos vivos (Marcos 12,26–27)."},
{v:7,t:"O Senhor disse: Eu vi a aflição do meu povo no Egito e ouvi o seu clamor por causa da dureza dos seus opressores.",np:1},
{v:8,t:"Conheço os seus sofrimentos; por isso desci para libertá-lo das mãos dos egípcios e fazê-lo subir daquela terra para uma terra boa e espaçosa, uma terra onde corre leite e mel, o território dos cananeus, dos heteus, dos amorreus, dos ferezeus, dos heveus e dos jebuseus.",n:"Terra onde corre leite e mel: imagem de fartura para pastores, que viviam do rebanho e do mel silvestre."},
{v:9,t:"Agora, o clamor dos filhos de Israel chegou até mim, e eu vi a opressão com que os egípcios os oprimem;"},
{v:10,t:"vai, pois; eu te envio ao faraó, para que tires do Egito o meu povo, os filhos de Israel."},
{v:11,t:"Moisés disse a Deus: Quem sou eu para ir ao faraó e tirar do Egito os filhos de Israel?"},
{v:12,t:"Deus respondeu: Eu estarei contigo; e este será para ti o sinal de que sou eu que te envio: quando tiveres tirado o povo do Egito, servireis a Deus sobre esta montanha."},
{s:"O nome de Deus"},
{v:13,t:"Moisés disse a Deus: Quando eu for aos filhos de Israel e lhes disser: O Deus de vossos pais me enviou a vós, e eles me perguntarem qual é o seu nome, que lhes direi?"},
{v:14,t:"Deus disse a Moisés: Eu sou aquele que sou. E acrescentou: Assim dirás aos filhos de Israel: Eu Sou me enviou a vós.",n:"Eu sou aquele que sou: assim a Nova Vulgata, com a tradução grega. O hebraico ehyeh asher ehyeh pode querer dizer também eu serei o que serei, ou eu sou aquele que estará convosco (compare 3,12). O nome divino YHWH, que vem do mesmo verbo ser, não era pronunciado pelos judeus por respeito; em seu lugar se dizia Senhor, e é assim que esta tradução o traz."},
{v:15,t:"Deus disse ainda a Moisés: Assim dirás aos filhos de Israel: O Senhor, o Deus de vossos pais, o Deus de Abraão, o Deus de Isaac e o Deus de Jacó, enviou-me a vós. Este é o meu nome para sempre, e assim serei lembrado de geração em geração."},
{v:16,t:"Vai, reúne os anciãos de Israel e dize-lhes: O Senhor, o Deus de vossos pais, o Deus de Abraão, de Isaac e de Jacó, apareceu-me e disse: Eu vos visitei e vi o que vos fazem no Egito;"},
{v:17,t:"e decidi tirar-vos da aflição do Egito e levar-vos para a terra dos cananeus, dos heteus, dos amorreus, dos ferezeus, dos heveus e dos jebuseus, uma terra onde corre leite e mel."},
{v:18,t:"Eles ouvirão a tua voz; e tu irás com os anciãos de Israel ao rei do Egito, e lhe direis: O Senhor, o Deus dos hebreus, veio ao nosso encontro; deixa-nos, pois, ir ao deserto, a três dias de caminho, para oferecer sacrifícios ao Senhor, nosso Deus."},
{v:19,t:"Mas eu sei que o rei do Egito não vos deixará ir, a não ser forçado por uma mão poderosa.",np:1},
{v:20,t:"Por isso estenderei a minha mão e ferirei o Egito com todos os prodígios que farei no meio dele; depois disso, ele vos deixará ir."},
{v:21,t:"Farei que este povo encontre favor aos olhos dos egípcios; e, quando partirdes, não saireis de mãos vazias.",np:1},
{v:22,t:"Cada mulher pedirá à sua vizinha e à hóspede da sua casa objetos de prata e de ouro e roupas; e vós os poreis nos vossos filhos e nas vossas filhas, e assim despojareis os egípcios.",n:"Os escravos não sairão de mãos vazias: é o salário de anos de trabalho forçado (compare Deuteronômio 15,13–14)."}
];

window.TEXTOS_SEED["exodo"][4] = [
{s:"Os sinais dados a Moisés"},
{v:1,t:"Moisés respondeu: E se não acreditarem em mim nem ouvirem a minha voz, e disserem: O Senhor não te apareceu?"},
{v:2,t:"O Senhor lhe perguntou: Que tens na mão? Ele respondeu: Um cajado."},
{v:3,t:"O Senhor disse: Joga-o no chão! Ele o jogou no chão, e o cajado se transformou numa serpente, e Moisés fugiu dela."},
{v:4,t:"O Senhor disse a Moisés: Estende a mão e pega-a pela cauda! Ele estendeu a mão e a pegou, e ela se transformou de novo em cajado na sua mão."},
{v:5,t:"Isto é para que acreditem que te apareceu o Senhor, o Deus de seus pais, o Deus de Abraão, o Deus de Isaac e o Deus de Jacó."},
{v:6,t:"O Senhor lhe disse ainda: Põe a mão no peito! Ele pôs a mão no peito e, quando a tirou, a mão estava leprosa, branca como a neve.",np:1,n:"Leprosa: o termo bíblico designa várias doenças de pele, e não só a lepra propriamente dita."},
{v:7,t:"O Senhor disse: Põe de novo a mão no peito! Ele pôs de novo a mão no peito e, quando a tirou, ela estava como o resto do seu corpo."},
{v:8,t:"Se não acreditarem em ti nem derem atenção ao primeiro sinal, acreditarão no segundo sinal."},
{v:9,t:"E, se não acreditarem nem mesmo nestes dois sinais e não ouvirem a tua voz, tira água do Rio e derrama-a sobre a terra seca, e a água que tirares do Rio se transformará em sangue sobre a terra seca."},
{v:10,t:"Moisés disse ao Senhor: Por favor, meu Senhor, eu não sou homem de palavra fácil, nem de ontem nem de anteontem, nem desde que falaste ao teu servo; tenho a boca pesada e a língua pesada.",np:1},
{v:11,t:"O Senhor lhe disse: Quem deu a boca ao homem? Quem faz o mudo ou o surdo, o que vê ou o cego? Não sou eu, o Senhor?"},
{v:12,t:"Vai, pois; eu estarei na tua boca e te ensinarei o que deves dizer."},
{v:13,t:"Moisés disse: Por favor, meu Senhor, envia quem quiseres enviar."},
{v:14,t:"Então a ira do Senhor se acendeu contra Moisés, e ele disse: Aarão, o levita, é teu irmão: sei que ele fala bem. Ele mesmo está vindo ao teu encontro; e, quando te vir, se alegrará no seu coração."},
{v:15,t:"Falarás com ele e porás as minhas palavras na sua boca; e eu estarei na tua boca e na boca dele e vos ensinarei o que deveis fazer."},
{v:16,t:"Ele falará por ti ao povo: ele será a tua boca, e tu serás para ele como Deus."},
{v:17,t:"Toma também na mão este cajado, com o qual farás os sinais."},
{s:"Moisés volta ao Egito"},
{v:18,t:"Moisés partiu e voltou para junto de Jetro, seu sogro, e lhe disse: Deixa-me ir, por favor, voltar para junto dos meus irmãos no Egito, para ver se ainda estão vivos. Jetro lhe disse: Vai em paz."},
{v:19,t:"O Senhor disse a Moisés em Madiã: Volta para o Egito, porque morreram todos os que procuravam tirar-te a vida."},
{v:20,t:"Moisés tomou a mulher e os filhos, pô-los sobre um jumento e voltou para a terra do Egito; e levava na mão o cajado de Deus."},
{v:21,t:"O Senhor disse a Moisés: Quando voltares ao Egito, faze diante do faraó todos os prodígios que pus na tua mão; mas eu endurecerei o coração dele, e ele não deixará o povo partir.",n:"Nota do tradutor: o texto diz ora que Deus endurece o coração do faraó, ora que o faraó endurece o próprio coração (8,11; 9,34); para o pensamento hebraico, nada escapa ao governo de Deus, sem que o homem deixe de ser responsável. O texto não foi suavizado (compare Romanos 9,17–18)."},
{v:22,t:"Dirás ao faraó: Assim diz o Senhor: Israel é o meu filho primogênito."},
{v:23,t:"Eu te digo: Deixa partir o meu filho, para que me preste culto; se te recusas a deixá-lo partir, eu matarei o teu filho primogênito.",np:1},
{v:24,t:"No caminho, no lugar onde passavam a noite, o Senhor foi ao encontro de Moisés e quis matá-lo.",np:1,n:"Nota do tradutor: um dos trechos mais enigmáticos da Bíblia, e o texto não foi suavizado. O perigo parece ligado à falta de circuncisão do filho de Moisés; Séfora o afasta com um rito de sangue."},
{v:25,t:"Então Séfora tomou uma pedra afiada, cortou o prepúcio do filho, tocou-lhe os pés e disse: Tu és para mim um esposo de sangue."},
{v:26,t:"E o Senhor o deixou. Ela tinha dito esposo de sangue por causa da circuncisão."},
{v:27,t:"O Senhor disse a Aarão: Vai ao deserto, ao encontro de Moisés. Ele foi, encontrou-o na montanha de Deus e o beijou.",np:1},
{v:28,t:"Moisés contou a Aarão todas as palavras que o Senhor lhe tinha mandado dizer e todos os sinais que lhe tinha ordenado fazer."},
{v:29,t:"Moisés e Aarão foram e reuniram todos os anciãos dos filhos de Israel."},
{v:30,t:"Aarão repetiu todas as palavras que o Senhor tinha dito a Moisés e fez os sinais diante do povo."},
{v:31,t:"O povo acreditou; e, quando ouviram que o Senhor tinha visitado os filhos de Israel e visto a sua aflição, inclinaram-se e se prostraram."}
];

window.TEXTOS_SEED["exodo"][5] = [
{s:"Diante do faraó: o trabalho aumenta"},
{v:1,t:"Depois disso, Moisés e Aarão foram ao faraó e disseram: Assim diz o Senhor, o Deus de Israel: Deixa partir o meu povo, para que me ofereça sacrifícios no deserto."},
{v:2,t:"O faraó respondeu: Quem é o Senhor, para que eu ouça a sua voz e deixe Israel partir? Não conheço o Senhor, e não deixarei Israel partir.",n:"Não conheço o Senhor: toda a história das pragas responde a esta frase; o refrão será: sabereis que eu sou o Senhor (7,5.17; 8,18; 14,4)."},
{v:3,t:"Eles disseram: O Deus dos hebreus veio ao nosso encontro; deixa-nos ir ao deserto, a três dias de caminho, para oferecer sacrifícios ao Senhor, nosso Deus, para que ele não nos fira com a peste ou com a espada."},
{v:4,t:"O rei do Egito lhes disse: Moisés e Aarão, por que distraís o povo do seu trabalho? Ide cuidar das vossas tarefas!"},
{v:5,t:"E o faraó acrescentou: Esse povo já é numeroso demais no país, e vós ainda quereis dar-lhe descanso das suas tarefas?"},
{v:6,t:"Naquele mesmo dia, o faraó deu esta ordem aos capatazes do povo e aos seus inspetores:",np:1},
{v:7,t:"Não deis mais palha ao povo para fazer tijolos, como antes; que eles mesmos vão juntar palha."},
{v:8,t:"Mas exigi deles a mesma quantidade de tijolos que faziam antes, sem diminuir nada; são uns preguiçosos, e é por isso que gritam: Vamos oferecer sacrifícios ao nosso Deus."},
{v:9,t:"Que o trabalho pese sobre esses homens e que se ocupem dele, e não deem ouvidos a palavras mentirosas."},
{v:10,t:"Os capatazes do povo e os seus inspetores saíram e disseram ao povo: Assim diz o faraó: Não vos darei mais palha.",np:1},
{v:11,t:"Ide vós mesmos buscar palha onde a encontrardes; mas nada será diminuído do vosso trabalho."},
{v:12,t:"O povo se espalhou por toda a terra do Egito para juntar restolho em lugar de palha."},
{v:13,t:"Os capatazes os pressionavam, dizendo: Completai o vosso trabalho de cada dia, como quando havia palha."},
{v:14,t:"E os inspetores dos filhos de Israel, que os capatazes do faraó tinham posto sobre eles, foram espancados, e lhes diziam: Por que não completastes, nem ontem nem hoje, a vossa quantidade de tijolos, como antes?"},
{v:15,t:"Os inspetores dos filhos de Israel foram queixar-se ao faraó, dizendo: Por que tratas assim os teus servos?",np:1},
{v:16,t:"Não se dá palha aos teus servos, e nos dizem: Fazei tijolos! E eis que os teus servos são espancados, e a culpa é do teu povo."},
{v:17,t:"Ele respondeu: Preguiçosos! Sois uns preguiçosos! Por isso dizeis: Vamos oferecer sacrifícios ao Senhor."},
{v:18,t:"Ide agora trabalhar! Não vos será dada palha, e entregareis a mesma quantidade de tijolos."},
{v:19,t:"Os inspetores dos filhos de Israel viram-se em apuros, porque lhes diziam: Não diminuireis nada da quantidade diária de tijolos.",np:1},
{v:20,t:"Ao saírem da presença do faraó, encontraram Moisés e Aarão, que os esperavam,"},
{v:21,t:"e lhes disseram: Que o Senhor vos veja e vos julgue! Vós nos tornastes odiosos ao faraó e aos seus servos, e pusestes na mão deles a espada para nos matar."},
{v:22,t:"Moisés voltou-se para o Senhor e disse: Senhor, por que maltratas este povo? Para que me enviaste?",n:"A primeira oração de Moisés é uma queixa: como os profetas e os salmistas, ele fala com Deus sem disfarçar a revolta."},
{v:23,t:"Desde que fui ao faraó para falar em teu nome, ele maltrata este povo, e tu não libertaste o teu povo."}
];

window.TEXTOS_SEED["exodo"][6] = [
{s:"O Senhor renova a promessa"},
{v:1,t:"O Senhor respondeu a Moisés: Agora verás o que vou fazer ao faraó: forçado por uma mão poderosa, ele os deixará partir; forçado por uma mão poderosa, ele os expulsará da sua terra."},
{v:2,t:"O Senhor falou a Moisés e lhe disse: Eu sou o Senhor,",np:1},
{v:3,t:"que apareci a Abraão, a Isaac e a Jacó como o Deus Todo-Poderoso; mas não lhes dei a conhecer o meu nome, Senhor.",n:"O Deus Todo-Poderoso: em hebraico, El Shaddai. O narrador sabe que o nome divino já aparece no Gênesis; quer dizer que só agora Deus revela o seu sentido, na libertação do povo."},
{v:4,t:"Também fiz com eles a minha aliança, para lhes dar a terra de Canaã, a terra em que moravam como estrangeiros."},
{v:5,t:"Eu ouvi os gemidos dos filhos de Israel, a quem os egípcios escravizam, e me lembrei da minha aliança."},
{v:6,t:"Por isso dize aos filhos de Israel: Eu sou o Senhor; eu vos tirarei dos trabalhos forçados dos egípcios, vos livrarei da escravidão e vos resgatarei com braço estendido e com grandes julgamentos."},
{v:7,t:"Eu vos tomarei como meu povo e serei o vosso Deus; e sabereis que eu sou o Senhor, vosso Deus, que vos tira dos trabalhos forçados do Egito"},
{v:8,t:"e vos leva à terra que jurei, de mão levantada, dar a Abraão, a Isaac e a Jacó; eu a darei a vós como propriedade, eu, o Senhor."},
{v:9,t:"Moisés falou assim aos filhos de Israel, mas eles não o ouviram, por causa do desânimo e da dureza da escravidão.",np:1},
{v:10,t:"O Senhor disse a Moisés:"},
{v:11,t:"Vai dizer ao faraó, rei do Egito, que deixe os filhos de Israel saírem da sua terra."},
{v:12,t:"Moisés respondeu diante do Senhor: Se os filhos de Israel não me ouvem, como o faraó me ouvirá, a mim, que tenho os lábios incircuncisos?",n:"Lábios incircuncisos: palavra difícil, que não sabe falar (compare 4,10)."},
{v:13,t:"Mas o Senhor falou a Moisés e a Aarão e lhes deu ordens para os filhos de Israel e para o faraó, rei do Egito, a fim de que tirassem do Egito os filhos de Israel.",np:1},
{s:"A genealogia de Moisés e de Aarão"},
{v:14,t:"Estes são os chefes das suas famílias. Filhos de Rúben, primogênito de Israel: Henoc, Falu, Hesron e Carmi; são os clãs de Rúben.",n:"A genealogia interrompe o relato para situar Moisés e Aarão na tribo de Levi; por isso só as três primeiras tribos são mencionadas."},
{v:15,t:"Filhos de Simeão: Jamuel, Jamin, Aod, Jaquin, Soar e Saul, filho da cananeia; são os clãs de Simeão.",np:1},
{v:16,t:"Estes são os nomes dos filhos de Levi, segundo os seus clãs: Gérson, Caat e Merari. Levi viveu cento e trinta e sete anos.",np:1},
{v:17,t:"Filhos de Gérson: Lobni e Semei, segundo os seus clãs.",np:1},
{v:18,t:"Filhos de Caat: Amram, Isaar, Hebron e Oziel. Caat viveu cento e trinta e três anos.",np:1},
{v:19,t:"Filhos de Merari: Mooli e Musi. São estes os clãs de Levi, segundo as suas famílias.",np:1},
{v:20,t:"Amram tomou por mulher Jocabed, sua tia, que lhe deu Aarão e Moisés. Amram viveu cento e trinta e sete anos.",np:1,n:"Casar com a tia seria proibido pela lei posterior (Levítico 18,12): o texto conserva uma tradição antiga sem corrigi-la."},
{v:21,t:"Filhos de Isaar: Coré, Nafeg e Zecri.",np:1},
{v:22,t:"Filhos de Oziel: Misael, Elisafã e Setri.",np:1},
{v:23,t:"Aarão tomou por mulher Eliseba, filha de Aminadab e irmã de Naasson, que lhe deu Nadab, Abiú, Eleazar e Itamar.",np:1},
{v:24,t:"Filhos de Coré: Asir, Elcana e Abiasaf; são os clãs dos coreítas.",np:1},
{v:25,t:"Eleazar, filho de Aarão, tomou por mulher uma das filhas de Putiel, que lhe deu Fineias. São estes os chefes das famílias levíticas, segundo os seus clãs.",np:1},
{v:26,t:"São estes o Aarão e o Moisés a quem o Senhor disse: Tirai do Egito os filhos de Israel, organizados em exércitos.",np:1},
{v:27,t:"Foram eles que falaram ao faraó, rei do Egito, para tirar do Egito os filhos de Israel; são estes Moisés e Aarão,"},
{v:28,t:"do dia em que o Senhor falou a Moisés na terra do Egito."},
{v:29,t:"O Senhor disse a Moisés: Eu sou o Senhor; dize ao faraó, rei do Egito, tudo o que eu te digo.",np:1},
{v:30,t:"Moisés respondeu diante do Senhor: Eu tenho os lábios incircuncisos; como o faraó me ouvirá?"}
];

window.TEXTOS_SEED["exodo"][7] = [
{s:"Moisés e Aarão diante do faraó"},
{v:1,t:"O Senhor disse a Moisés: Olha, eu te constituí como um deus para o faraó, e Aarão, teu irmão, será o teu profeta."},
{v:2,t:"Tu dirás tudo o que eu te ordenar, e Aarão, teu irmão, falará ao faraó, para que deixe os filhos de Israel saírem da sua terra."},
{v:3,t:"Mas eu endurecerei o coração do faraó e multiplicarei os meus sinais e os meus prodígios na terra do Egito."},
{v:4,t:"O faraó não vos ouvirá; então porei a minha mão sobre o Egito e tirarei da terra do Egito os meus exércitos, o meu povo, os filhos de Israel, com grandes julgamentos.",np:1},
{v:5,t:"E os egípcios saberão que eu sou o Senhor, quando eu estender a minha mão sobre o Egito e tirar do meio deles os filhos de Israel."},
{v:6,t:"Moisés e Aarão fizeram como o Senhor lhes tinha ordenado; assim fizeram.",np:1},
{v:7,t:"Moisés tinha oitenta anos, e Aarão, oitenta e três, quando falaram ao faraó."},
{s:"O cajado transformado em serpente"},
{v:8,t:"O Senhor disse a Moisés e a Aarão:"},
{v:9,t:"Quando o faraó vos pedir que façais um prodígio, dirás a Aarão: Toma o teu cajado e joga-o diante do faraó, e ele se transformará numa serpente."},
{v:10,t:"Moisés e Aarão foram ao faraó e fizeram como o Senhor tinha ordenado: Aarão jogou o cajado diante do faraó e dos seus servos, e o cajado se transformou numa serpente."},
{v:11,t:"Mas o faraó chamou os sábios e os feiticeiros; e também os magos do Egito fizeram o mesmo com os seus encantamentos:",np:1,n:"A tradição judaica conservou os nomes de dois desses magos, Janes e Jambres (2 Timóteo 3,8)."},
{v:12,t:"cada um jogou o seu cajado, e os cajados se transformaram em serpentes; mas o cajado de Aarão engoliu os cajados deles."},
{v:13,t:"Contudo, o coração do faraó se endureceu, e ele não os ouviu, como o Senhor tinha dito.",np:1},
{s:"Primeira praga: a água transformada em sangue"},
{v:14,t:"O Senhor disse a Moisés: O coração do faraó está obstinado: ele se recusa a deixar o povo partir.",n:"As pragas atingem as forças que o Egito venerava como divinas, a começar pelo Nilo: o Senhor se mostra senhor da natureza e da história."},
{v:15,t:"Vai ao faraó amanhã cedo, quando ele sair para ir à água; espera-o à beira do Rio e leva na mão o cajado que se transformou em serpente."},
{v:16,t:"Dize-lhe: O Senhor, o Deus dos hebreus, enviou-me a ti para dizer: Deixa partir o meu povo, para que me ofereça sacrifícios no deserto; mas até agora não quiseste ouvir."},
{v:17,t:"Assim diz o Senhor: Nisto saberás que eu sou o Senhor: com o cajado que tenho na mão vou ferir as águas do Rio, e elas se transformarão em sangue."},
{v:18,t:"Os peixes do Rio morrerão, o Rio ficará podre, e os egípcios terão nojo de beber a água do Rio."},
{v:19,t:"O Senhor disse ainda a Moisés: Dize a Aarão: Toma o teu cajado e estende a mão sobre as águas do Egito, sobre os seus rios, os seus canais, os seus pântanos e todos os seus reservatórios, para que se transformem em sangue; e haverá sangue em toda a terra do Egito, até nas vasilhas de madeira e de pedra.",np:1},
{v:20,t:"Moisés e Aarão fizeram como o Senhor tinha ordenado. Aarão levantou o cajado e feriu as águas do Rio diante do faraó e dos seus servos; e toda a água do Rio se transformou em sangue."},
{v:21,t:"Os peixes do Rio morreram, o Rio ficou podre, e os egípcios não podiam beber a água do Rio; e houve sangue em toda a terra do Egito."},
{v:22,t:"Mas os magos do Egito fizeram o mesmo com os seus encantamentos; e o coração do faraó se endureceu, e ele não os ouviu, como o Senhor tinha dito.",np:1},
{v:23,t:"O faraó deu as costas e voltou para casa, sem dar importância a isso."},
{v:24,t:"Todos os egípcios cavaram ao redor do Rio, em busca de água para beber, porque não podiam beber a água do Rio."},
{v:25,t:"Passaram-se sete dias depois que o Senhor feriu o Rio."},
{s:"Segunda praga: as rãs"},
{v:26,t:"O Senhor disse a Moisés: Vai ao faraó e dize-lhe: Assim diz o Senhor: Deixa partir o meu povo, para que me ofereça sacrifícios.",n:"Em outras Bíblias, 7,26–29 é 8,1–4, e a numeração do capítulo 8 diminui de quatro unidades."},
{v:27,t:"Se te recusares a deixá-lo partir, eu ferirei todo o teu território com rãs."},
{v:28,t:"O Rio fervilhará de rãs, que subirão e entrarão no teu palácio, no teu quarto de dormir e na tua cama, nas casas dos teus servos e do teu povo, nos teus fornos e nas tuas amassadeiras."},
{v:29,t:"As rãs subirão sobre ti, sobre o teu povo e sobre todos os teus servos."}
];

window.TEXTOS_SEED["exodo"][8] = [
{s:"As rãs cobrem o Egito"},
{v:1,t:"O Senhor disse a Moisés: Dize a Aarão: Estende a mão com o teu cajado sobre os rios, os canais e os pântanos, e faze subir as rãs sobre a terra do Egito.",n:"Em outras Bíblias, 8,1–28 é 8,5–32."},
{v:2,t:"Aarão estendeu a mão sobre as águas do Egito, e as rãs subiram e cobriram a terra do Egito."},
{v:3,t:"Mas os magos fizeram o mesmo com os seus encantamentos e fizeram subir rãs sobre a terra do Egito."},
{v:4,t:"O faraó chamou Moisés e Aarão e disse: Rogai ao Senhor que afaste as rãs de mim e do meu povo, e eu deixarei o povo partir para oferecer sacrifícios ao Senhor.",np:1},
{v:5,t:"Moisés disse ao faraó: Marca tu mesmo quando devo rogar por ti, pelos teus servos e pelo teu povo, para que as rãs se afastem de ti e das tuas casas e fiquem somente no Rio."},
{v:6,t:"Ele respondeu: Amanhã. Moisés disse: Será como disseste, para que saibas que não há ninguém como o Senhor, nosso Deus."},
{v:7,t:"As rãs se afastarão de ti, das tuas casas, dos teus servos e do teu povo; ficarão somente no Rio."},
{v:8,t:"Moisés e Aarão saíram da presença do faraó, e Moisés clamou ao Senhor a respeito das rãs, como tinha combinado com o faraó."},
{v:9,t:"O Senhor fez como Moisés tinha pedido: as rãs morreram nas casas, nos pátios e nos campos.",np:1},
{v:10,t:"Juntaram-nas em montões, e a terra ficou cheirando mal."},
{v:11,t:"Mas, quando o faraó viu que tinha alívio, endureceu o coração e não os ouviu, como o Senhor tinha dito."},
{s:"Terceira praga: os mosquitos"},
{v:12,t:"O Senhor disse a Moisés: Dize a Aarão: Estende o teu cajado e fere o pó da terra, e ele se transformará em mosquitos em toda a terra do Egito."},
{v:13,t:"Assim fizeram: Aarão estendeu a mão com o cajado e feriu o pó da terra, e houve mosquitos sobre os homens e sobre os animais; todo o pó da terra se transformou em mosquitos em toda a terra do Egito."},
{v:14,t:"Os magos tentaram fazer o mesmo com os seus encantamentos, para produzir mosquitos, mas não conseguiram. E os mosquitos estavam sobre os homens e sobre os animais;",np:1},
{v:15,t:"e os magos disseram ao faraó: Isto é o dedo de Deus. Mas o coração do faraó se endureceu, e ele não os ouviu, como o Senhor tinha dito.",n:"O dedo de Deus: os magos reconhecem o limite das suas artes. Jesus usa a mesma expressão para falar dos seus exorcismos (Lucas 11,20)."},
{s:"Quarta praga: as moscas"},
{v:16,t:"O Senhor disse a Moisés: Levanta-te cedo, apresenta-te ao faraó quando ele sair para ir à água e dize-lhe: Assim diz o Senhor: Deixa partir o meu povo, para que me ofereça sacrifícios."},
{v:17,t:"Se não deixares o meu povo partir, mandarei contra ti, contra os teus servos, contra o teu povo e contra as tuas casas enxames de moscas de toda espécie; as casas dos egípcios e até o chão em que pisam ficarão cheios de moscas."},
{v:18,t:"Mas naquele dia porei à parte a terra de Gessen, onde habita o meu povo, para que ali não haja moscas; assim saberás que eu, o Senhor, estou no meio desta terra."},
{v:19,t:"Farei distinção entre o meu povo e o teu povo; amanhã acontecerá este sinal."},
{v:20,t:"Assim fez o Senhor: enxames enormes de moscas entraram no palácio do faraó, nas casas dos seus servos e em toda a terra do Egito, e a terra ficou arruinada por causa das moscas."},
{v:21,t:"O faraó chamou Moisés e Aarão e disse: Ide oferecer sacrifícios ao vosso Deus, aqui no país.",np:1},
{v:22,t:"Moisés respondeu: Não convém fazer isso, porque os sacrifícios que oferecemos ao Senhor, nosso Deus, são uma abominação para os egípcios; se imolarmos diante deles os animais que os egípcios veneram, eles nos apedrejarão."},
{v:23,t:"Iremos ao deserto, a três dias de caminho, e ofereceremos sacrifícios ao Senhor, nosso Deus, como ele nos ordenou."},
{v:24,t:"O faraó disse: Eu vos deixarei partir para oferecerdes sacrifícios ao Senhor, vosso Deus, no deserto; mas não vos afasteis demais. Rogai por mim."},
{v:25,t:"Moisés disse: Logo que eu sair da tua presença, rogarei ao Senhor, e amanhã as moscas se afastarão do faraó, dos seus servos e do seu povo. Mas que o faraó não volte a nos enganar, recusando deixar o povo partir para oferecer sacrifícios ao Senhor."},
{v:26,t:"Moisés saiu da presença do faraó e rogou ao Senhor;"},
{v:27,t:"e o Senhor fez como Moisés tinha pedido: afastou as moscas do faraó, dos seus servos e do seu povo; não ficou nem uma."},
{v:28,t:"Mas também desta vez o faraó endureceu o coração e não deixou o povo partir."}
];

window.TEXTOS_SEED["exodo"][9] = [
{s:"Quinta praga: a peste dos animais"},
{v:1,t:"O Senhor disse a Moisés: Vai ao faraó e dize-lhe: Assim diz o Senhor, o Deus dos hebreus: Deixa partir o meu povo, para que me ofereça sacrifícios."},
{v:2,t:"Se te recusares a deixá-lo partir e continuares a retê-lo,"},
{v:3,t:"eis que a mão do Senhor ferirá com uma peste muito grave os teus rebanhos que estão nos campos: os cavalos, os jumentos, os camelos, os bois e as ovelhas."},
{v:4,t:"Mas o Senhor fará distinção entre os rebanhos de Israel e os rebanhos dos egípcios, e nada morrerá de tudo o que pertence aos filhos de Israel."},
{v:5,t:"O Senhor marcou o prazo, dizendo: Amanhã o Senhor fará isto no país."},
{v:6,t:"No dia seguinte o Senhor o fez: morreram todos os rebanhos dos egípcios, mas dos rebanhos dos filhos de Israel não morreu nenhum.",np:1,n:"Todos: modo de dizer; os rebanhos dos egípcios reaparecem na praga do granizo (9,19–21)."},
{v:7,t:"O faraó mandou verificar: não tinha morrido nenhum animal dos rebanhos de Israel. Mas o coração do faraó continuou obstinado, e ele não deixou o povo partir."},
{s:"Sexta praga: as úlceras"},
{v:8,t:"O Senhor disse a Moisés e a Aarão: Enchei as mãos de cinza de forno, e Moisés a atirará para o céu diante do faraó;"},
{v:9,t:"ela se tornará uma poeira sobre toda a terra do Egito e produzirá em homens e animais úlceras que se abrirão em feridas, em toda a terra do Egito."},
{v:10,t:"Eles tomaram cinza de forno e se apresentaram ao faraó; Moisés a atirou para o céu, e ela produziu em homens e animais úlceras que se abriam em feridas.",np:1},
{v:11,t:"Os magos não puderam ficar diante de Moisés por causa das úlceras, porque as úlceras estavam neles e em todos os egípcios."},
{v:12,t:"Mas o Senhor endureceu o coração do faraó, e ele não os ouviu, como o Senhor tinha dito a Moisés."},
{s:"Sétima praga: o granizo"},
{v:13,t:"O Senhor disse a Moisés: Levanta-te cedo, apresenta-te ao faraó e dize-lhe: Assim diz o Senhor, o Deus dos hebreus: Deixa partir o meu povo, para que me ofereça sacrifícios;"},
{v:14,t:"porque desta vez vou mandar todas as minhas pragas contra ti, contra os teus servos e contra o teu povo, para que saibas que não há ninguém como eu em toda a terra."},
{v:15,t:"Se eu já tivesse estendido a mão e ferido a ti e ao teu povo com a peste, tu terias desaparecido da terra."},
{v:16,t:"Mas eu te conservei para mostrar em ti o meu poder, e para que o meu nome seja anunciado em toda a terra.",n:"São Paulo cita este versículo em Romanos 9,17."},
{v:17,t:"Ainda te opões ao meu povo e não queres deixá-lo partir?"},
{v:18,t:"Pois amanhã, a esta mesma hora, farei cair uma chuva de granizo tão forte como nunca houve no Egito, desde o dia em que foi fundado até hoje."},
{v:19,t:"Manda, pois, desde já recolher os teus rebanhos e tudo o que tens no campo; porque o granizo cairá sobre todos os homens e animais que se encontrarem no campo e não tiverem sido recolhidos, e eles morrerão."},
{v:20,t:"Os servos do faraó que temeram a palavra do Senhor fizeram os seus escravos e os seus rebanhos se abrigarem nas casas;"},
{v:21,t:"mas os que não deram importância à palavra do Senhor deixaram os seus escravos e os seus rebanhos no campo."},
{v:22,t:"O Senhor disse a Moisés: Estende a mão para o céu, e cairá granizo em toda a terra do Egito, sobre os homens, sobre os animais e sobre toda a vegetação dos campos na terra do Egito.",np:1},
{v:23,t:"Moisés estendeu o cajado para o céu, e o Senhor mandou trovões e granizo, e raios caíram sobre a terra; o Senhor fez cair granizo sobre a terra do Egito."},
{v:24,t:"Caíam granizo e fogo misturados, e o granizo era tão violento como nunca tinha havido em toda a terra do Egito desde que ela se tornou uma nação."},
{v:25,t:"O granizo feriu em toda a terra do Egito tudo o que estava no campo, homens e animais; feriu toda a vegetação dos campos e quebrou todas as árvores do campo."},
{v:26,t:"Somente na terra de Gessen, onde estavam os filhos de Israel, não caiu granizo."},
{v:27,t:"O faraó mandou chamar Moisés e Aarão e lhes disse: Desta vez eu pequei; o Senhor é justo, e eu e o meu povo somos culpados.",np:1},
{v:28,t:"Rogai ao Senhor: já basta de trovões de Deus e de granizo. Eu vos deixarei partir, e não ficareis mais aqui.",np:1},
{v:29,t:"Moisés lhe disse: Quando eu sair da cidade, estenderei as mãos para o Senhor; os trovões cessarão, e não haverá mais granizo, para que saibas que a terra pertence ao Senhor.",np:1},
{v:30,t:"Mas eu sei que tu e os teus servos ainda não temeis o Senhor Deus.",np:1},
{v:31,t:"O linho e a cevada foram destruídos, porque a cevada já estava espigada, e o linho, em flor;",np:1},
{v:32,t:"mas o trigo e a espelta não foram destruídos, porque são tardios."},
{v:33,t:"Moisés saiu da presença do faraó e da cidade e estendeu as mãos para o Senhor; os trovões e o granizo cessaram, e a chuva parou de cair sobre a terra.",np:1},
{v:34,t:"Quando o faraó viu que a chuva, o granizo e os trovões tinham cessado, continuou a pecar:",np:1},
{v:35,t:"endureceu o coração, ele e os seus servos; o coração do faraó se endureceu, e ele não deixou partir os filhos de Israel, como o Senhor tinha dito por meio de Moisés."}
];

window.TEXTOS_SEED["exodo"][10] = [
{s:"Oitava praga: os gafanhotos"},
{v:1,t:"O Senhor disse a Moisés: Vai ao faraó, porque eu endureci o coração dele e o dos seus servos, para realizar estes meus sinais no meio deles,"},
{v:2,t:"e para que contes ao teu filho e ao teu neto como tratei os egípcios e os sinais que fiz no meio deles; e sabereis que eu sou o Senhor.",n:"A história das pragas é contada para ser transmitida de pai para filho: a memória da libertação faz parte da fé de Israel (compare 12,26–27; 13,8.14)."},
{v:3,t:"Moisés e Aarão foram ao faraó e lhe disseram: Assim diz o Senhor, o Deus dos hebreus: Até quando te recusarás a humilhar-te diante de mim? Deixa partir o meu povo, para que me ofereça sacrifícios.",np:1},
{v:4,t:"Se te recusares a deixá-lo partir, amanhã farei vir gafanhotos sobre o teu território,",np:1},
{v:5,t:"que cobrirão a face da terra, a ponto de não se poder ver o chão; eles devorarão o que escapou do granizo e roerão todas as árvores que brotam nos campos."},
{v:6,t:"Encherão o teu palácio, as casas dos teus servos e as casas de todos os egípcios, como nunca viram os teus pais nem os teus avós, desde que existem sobre a terra até hoje. E Moisés deu as costas e saiu da presença do faraó.",np:1},
{v:7,t:"Os servos do faraó lhe disseram: Até quando esse homem será uma armadilha para nós? Deixa esses homens partir, para que ofereçam sacrifícios ao Senhor, seu Deus. Ainda não vês que o Egito está arruinado?",np:1},
{v:8,t:"Mandaram chamar de novo Moisés e Aarão ao faraó, e ele lhes disse: Ide oferecer sacrifícios ao Senhor, vosso Deus. Mas quem são os que vão?",np:1},
{v:9,t:"Moisés respondeu: Iremos com as nossas crianças e os nossos velhos, com os nossos filhos e as nossas filhas, com as nossas ovelhas e os nossos bois, porque é uma festa do Senhor para nós.",np:1},
{v:10,t:"O faraó lhes disse: Que o Senhor esteja convosco, assim como eu vou deixar partir a vós e as vossas crianças! Está claro que tendes más intenções.",np:1,n:"Ironia do faraó: tão certo como o Senhor estará convosco, eu não vos deixarei partir com as crianças."},
{v:11,t:"Não será assim: ide somente vós, os homens, e oferecei sacrifícios ao Senhor, pois foi isso que pedistes. E os expulsaram da presença do faraó.",np:1},
{v:12,t:"O Senhor disse a Moisés: Estende a mão sobre a terra do Egito, para que venham os gafanhotos, subam sobre a terra do Egito e devorem toda a vegetação da terra, tudo o que o granizo deixou.",np:1},
{v:13,t:"Moisés estendeu o cajado sobre a terra do Egito, e o Senhor fez soprar um vento abrasador sobre a terra durante todo aquele dia e toda a noite. Pela manhã, o vento abrasador tinha trazido os gafanhotos."},
{v:14,t:"Os gafanhotos subiram sobre toda a terra do Egito e pousaram em todo o território egípcio, em quantidade enorme: nunca antes tinha havido tantos gafanhotos, nem haverá depois."},
{v:15,t:"Cobriram a face de toda a terra, e a terra ficou escura. Devoraram toda a vegetação da terra e todos os frutos das árvores que o granizo tinha deixado; não ficou nada verde nas árvores nem na vegetação dos campos, em todo o Egito."},
{v:16,t:"O faraó mandou chamar depressa Moisés e Aarão e disse: Pequei contra o Senhor, vosso Deus, e contra vós.",np:1},
{v:17,t:"Mas agora perdoai o meu pecado, só desta vez, e rogai ao Senhor, vosso Deus, que afaste de mim ao menos esta praga mortal."},
{v:18,t:"Moisés saiu da presença do faraó e rogou ao Senhor;"},
{v:19,t:"e o Senhor fez soprar do ocidente um vento muito forte, que levou os gafanhotos e os lançou no mar Vermelho; não ficou nem um gafanhoto em todo o território do Egito.",n:"Mar Vermelho: o hebraico diz mar dos Juncos; a tradução grega e a Vulgata o chamaram mar Vermelho, e é esse o nome que ficou."},
{v:20,t:"Mas o Senhor endureceu o coração do faraó, e ele não deixou partir os filhos de Israel."},
{s:"Nona praga: as trevas"},
{v:21,t:"O Senhor disse a Moisés: Estende a mão para o céu, e haverá sobre a terra do Egito trevas tão densas que se possam apalpar."},
{v:22,t:"Moisés estendeu a mão para o céu, e houve trevas espessas em toda a terra do Egito durante três dias."},
{v:23,t:"Ninguém via o seu irmão, e ninguém se movia do lugar onde estava; mas onde habitavam os filhos de Israel havia luz.",n:"As trevas atingem o sol, o maior dos deuses do Egito; a luz fica com Israel (compare Sabedoria 17,1–18,4)."},
{v:24,t:"O faraó chamou Moisés e Aarão e disse: Ide oferecer sacrifícios ao Senhor; só as vossas ovelhas e os vossos bois ficarão; as vossas crianças podem ir convosco.",np:1},
{v:25,t:"Moisés respondeu: Ainda que tu mesmo nos desses vítimas e holocaustos para oferecermos ao Senhor, nosso Deus,"},
{v:26,t:"os nossos rebanhos também irão conosco; não ficará nem um casco, porque é deles que tiraremos o que for necessário para o culto do Senhor, nosso Deus; e nós mesmos não sabemos o que devemos oferecer enquanto não chegarmos lá."},
{v:27,t:"Mas o Senhor endureceu o coração do faraó, e ele não quis deixá-los partir.",np:1},
{v:28,t:"O faraó disse a Moisés: Sai da minha presença! Toma cuidado para não voltares a ver o meu rosto, porque no dia em que o vires, morrerás."},
{v:29,t:"Moisés respondeu: Será como disseste: não verei mais o teu rosto."}
];

window.TEXTOS_SEED["exodo"][11] = [
{s:"O anúncio da última praga"},
{v:1,t:"O Senhor disse a Moisés: Ainda uma praga farei cair sobre o faraó e sobre o Egito; depois disso ele vos deixará partir daqui; mais ainda: ele vos expulsará."},
{v:2,t:"Dize, pois, ao povo que cada homem peça ao seu vizinho, e cada mulher à sua vizinha, objetos de prata e de ouro."},
{v:3,t:"O Senhor fez que o povo encontrasse favor aos olhos dos egípcios. E Moisés era um homem muito considerado na terra do Egito, aos olhos dos servos do faraó e de todo o povo."},
{v:4,t:"Moisés disse: Assim diz o Senhor: À meia-noite passarei pelo meio do Egito,",np:1},
{v:5,t:"e morrerá todo primogênito na terra do Egito, desde o primogênito do faraó, que se senta no seu trono, até o primogênito da escrava que está atrás da mó, e todos os primogênitos dos animais.",n:"Nota do tradutor: a morte dos primogênitos é o ponto mais duro da narrativa do Êxodo, e o texto não foi suavizado. Ela responde à ordem do faraó de matar os meninos hebreus (1,22) e à ameaça anunciada desde o começo (4,22–23)."},
{v:6,t:"Haverá um grande clamor em toda a terra do Egito, como nunca houve nem haverá jamais."},
{v:7,t:"Mas contra os filhos de Israel nem um cão latirá, nem contra os homens nem contra os animais, para que saibais que o Senhor faz distinção entre os egípcios e Israel."},
{v:8,t:"Então todos esses teus servos descerão até mim e se prostrarão diante de mim, dizendo: Sai, tu e todo o povo que te segue! E depois disso sairei. E Moisés saiu da presença do faraó, ardendo de ira."},
{v:9,t:"O Senhor disse a Moisés: O faraó não vos ouvirá, para que se multipliquem os meus prodígios na terra do Egito.",np:1},
{v:10,t:"Moisés e Aarão fizeram todos estes prodígios diante do faraó; mas o Senhor endureceu o coração do faraó, e ele não deixou os filhos de Israel saírem da sua terra."}
];

window.TEXTOS_SEED["exodo"][12] = [
{s:"A instituição da Páscoa"},
{v:1,t:"O Senhor disse a Moisés e a Aarão, na terra do Egito:"},
{v:2,t:"Este mês será para vós o princípio dos meses: será o primeiro mês do ano.",n:"O mês de Abib, mais tarde chamado Nisã, entre março e abril: o calendário de Israel começa pela libertação."},
{v:3,t:"Falai a toda a comunidade de Israel e dizei: No dia dez deste mês, cada um tomará um cordeiro por família, um cordeiro por casa."},
{v:4,t:"Se a família for pequena demais para um cordeiro, tomará consigo o vizinho mais próximo da sua casa, segundo o número de pessoas; calculareis o cordeiro conforme o que cada um pode comer."},
{v:5,t:"O cordeiro será sem defeito, macho, de um ano; podereis tomá-lo entre os cordeiros ou entre os cabritos,"},
{v:6,t:"e o guardareis até o dia catorze deste mês; e toda a assembleia da comunidade de Israel o imolará ao entardecer."},
{v:7,t:"Tomarão do seu sangue e o porão nos dois batentes e na verga da porta das casas em que o comerem;"},
{v:8,t:"e comerão a carne naquela noite, assada no fogo, com pães sem fermento e ervas amargas."},
{v:9,t:"Não comereis nada dele cru nem cozido na água, mas só assado no fogo, com a cabeça, as pernas e as entranhas."},
{v:10,t:"Não deixareis nada dele para a manhã seguinte; o que sobrar, vós o queimareis no fogo."},
{v:11,t:"Assim o comereis: com a cintura cingida, as sandálias nos pés e o cajado na mão; comereis às pressas. É a Páscoa do Senhor!",n:"A Nova Vulgata acrescenta entre parênteses a explicação de São Jerônimo: Páscoa, isto é, Passagem. Em hebraico, pesah soa como o verbo que significa passar adiante, poupar (12,13.23)."},
{v:12,t:"Naquela noite passarei pela terra do Egito e ferirei todos os primogênitos da terra do Egito, tanto dos homens como dos animais; e farei justiça contra todos os deuses do Egito, eu, o Senhor.",np:1},
{v:13,t:"O sangue será para vós um sinal nas casas em que estiverdes: quando eu vir o sangue, passarei adiante, e não haverá entre vós praga destruidora quando eu ferir a terra do Egito."},
{v:14,t:"Este dia será para vós um memorial, e o celebrareis como festa do Senhor; de geração em geração o celebrareis, como lei perpétua.",n:"Memorial: na liturgia de Israel, fazer memória é tornar presente a obra de Deus. Jesus celebrará a sua última ceia no contexto da Páscoa (Lucas 22,15–20; compare 1 Coríntios 5,7)."},
{s:"A festa dos Ázimos"},
{v:15,t:"Durante sete dias comereis pães sem fermento. Desde o primeiro dia tirareis o fermento das vossas casas; quem comer pão fermentado, do primeiro ao sétimo dia, essa pessoa será eliminada de Israel.",n:"Será eliminada: expressão que designa a exclusão da comunidade, e talvez a morte decretada por Deus."},
{v:16,t:"O primeiro dia será santo e solene, e o sétimo dia também será santo, com a mesma solenidade. Nesses dias não se fará nenhum trabalho, a não ser o preparo do que cada um deve comer.",np:1},
{v:17,t:"Observareis a festa dos Ázimos, porque foi neste mesmo dia que tirei os vossos exércitos da terra do Egito; observareis este dia de geração em geração, como lei perpétua.",np:1},
{v:18,t:"No primeiro mês, desde a tarde do dia catorze até a tarde do dia vinte e um, comereis pães sem fermento."},
{v:19,t:"Durante sete dias não se encontrará fermento nas vossas casas. Quem comer pão fermentado será eliminado da comunidade de Israel, seja estrangeiro, seja natural do país.",np:1},
{v:20,t:"Não comereis nada fermentado; em todas as vossas moradas comereis pães sem fermento."},
{s:"Moisés transmite as ordens"},
{v:21,t:"Moisés chamou todos os anciãos de Israel e lhes disse: Ide tomar um animal para cada família e imolai a Páscoa."},
{v:22,t:"Tomai um ramo de hissopo, molhai-o no sangue que estiver na bacia e marcai com o sangue a verga e os dois batentes da porta. E nenhum de vós saia da porta da sua casa até de manhã."},
{v:23,t:"Pois o Senhor passará para ferir os egípcios; mas, quando vir o sangue na verga e nos dois batentes, passará adiante da porta e não deixará o exterminador entrar nas vossas casas para ferir.",np:1},
{v:24,t:"Observareis esta ordem como lei perpétua para ti e para os teus filhos."},
{v:25,t:"Quando tiverdes entrado na terra que o Senhor vos dará, como prometeu, observareis este rito;"},
{v:26,t:"e, quando os vossos filhos vos perguntarem que rito é este,",n:"A pergunta dos filhos se tornou parte do rito pascal judaico: a noite da Páscoa é uma catequese em família."},
{v:27,t:"respondereis: É o sacrifício da Páscoa do Senhor, que passou adiante das casas dos filhos de Israel no Egito, quando feriu os egípcios e poupou as nossas casas. Então o povo se inclinou e se prostrou;"},
{v:28,t:"e os filhos de Israel foram e fizeram como o Senhor tinha ordenado a Moisés e a Aarão."},
{s:"A morte dos primogênitos"},
{v:29,t:"À meia-noite, o Senhor feriu todos os primogênitos na terra do Egito, desde o primogênito do faraó, que se sentava no seu trono, até o primogênito do prisioneiro que estava no cárcere, e todos os primogênitos dos animais."},
{v:30,t:"O faraó se levantou de noite, ele e todos os seus servos e todos os egípcios; e houve um grande clamor no Egito, porque não havia casa onde não houvesse um morto.",np:1},
{v:31,t:"O faraó chamou Moisés e Aarão de noite e disse: Levantai-vos, saí do meio do meu povo, vós e os filhos de Israel; ide oferecer sacrifícios ao Senhor, como dissestes.",np:1},
{v:32,t:"Levai também as vossas ovelhas e os vossos bois, como pedistes; ide, e abençoai-me também a mim."},
{v:33,t:"Os egípcios apressavam o povo a sair depressa do país, pois diziam: Vamos todos morrer!",np:1},
{v:34,t:"O povo levou a massa antes que fermentasse; e, amarrando as amassadeiras nos mantos, carregou-as nos ombros."},
{v:35,t:"Os filhos de Israel fizeram o que Moisés tinha dito e pediram aos egípcios objetos de prata e de ouro e muitas roupas.",np:1},
{v:36,t:"O Senhor fez que o povo encontrasse favor aos olhos dos egípcios, que lhes deram o que pediam; e assim despojaram os egípcios."},
{s:"A saída do Egito"},
{v:37,t:"Os filhos de Israel partiram de Ramessés para Sucot, cerca de seiscentos mil homens a pé, sem contar as crianças.",n:"Seiscentos mil homens, com as mulheres e as crianças, fariam mais de dois milhões de pessoas: o número exprime a grandeza do povo e da libertação, mais do que um recenseamento."},
{v:38,t:"Subiu também com eles uma multidão de gente misturada, e ovelhas e bois, um rebanho muito numeroso."},
{v:39,t:"Com a massa que tinham trazido do Egito, cozeram pães sem fermento, porque a massa não tinha fermentado: tinham sido expulsos do Egito sem poder demorar-se, e não tinham preparado provisões para si."},
{v:40,t:"A permanência dos filhos de Israel no Egito foi de quatrocentos e trinta anos.",np:1,n:"A tradução grega e o texto samaritano contam os quatrocentos e trinta anos a partir de Abraão, somando o tempo passado em Canaã; São Paulo segue essa contagem (Gálatas 3,17)."},
{v:41,t:"No fim dos quatrocentos e trinta anos, naquele mesmo dia, todos os exércitos do Senhor saíram da terra do Egito."},
{v:42,t:"Foi uma noite de vigília para o Senhor, quando os tirou da terra do Egito: esta noite, todos os filhos de Israel devem passá-la em vigília em honra do Senhor, de geração em geração.",n:"Desta noite de vigília nasceu a Vigília Pascal cristã, chamada por Santo Agostinho a mãe de todas as vigílias."},
{s:"Normas sobre a Páscoa"},
{v:43,t:"O Senhor disse a Moisés e a Aarão: Esta é a lei da Páscoa: nenhum estrangeiro comerá dela;"},
{v:44,t:"mas todo escravo comprado a dinheiro, depois de circuncidado, poderá comer dela;"},
{v:45,t:"o estrangeiro de passagem e o trabalhador assalariado não comerão dela."},
{v:46,t:"Será comida numa só casa; não levareis nenhum pedaço da carne para fora da casa, e não quebrareis nenhum dos seus ossos.",n:"São João aplica esta norma a Jesus crucificado, o verdadeiro cordeiro pascal (João 19,36)."},
{v:47,t:"Toda a comunidade de Israel a celebrará.",np:1},
{v:48,t:"Se um estrangeiro que mora contigo quiser celebrar a Páscoa do Senhor, todos os homens da sua casa deverão ser circuncidados; então poderá aproximar-se para celebrá-la e será como um natural do país. Mas nenhum incircunciso comerá dela."},
{v:49,t:"A mesma lei valerá para o natural do país e para o estrangeiro que mora no meio de vós."},
{v:50,t:"Todos os filhos de Israel fizeram como o Senhor tinha ordenado a Moisés e a Aarão;"},
{v:51,t:"e naquele mesmo dia o Senhor tirou da terra do Egito os filhos de Israel, organizados em exércitos."}
];

window.TEXTOS_SEED["exodo"][13] = [
{s:"A consagração dos primogênitos"},
{v:1,t:"O Senhor falou a Moisés e disse:"},
{v:2,t:"Consagra-me todo primogênito, todo o que abre o seio materno entre os filhos de Israel, tanto dos homens como dos animais: ele me pertence.",n:"O primogênito pertence a Deus, que poupou os primogênitos de Israel na noite da Páscoa (13,15). Maria e José apresentam Jesus no templo segundo esta lei (Lucas 2,22–23)."},
{v:3,t:"Moisés disse ao povo: Lembrai-vos deste dia, em que saístes do Egito, da casa da escravidão, porque o Senhor vos tirou daqui com mão poderosa; não se comerá pão fermentado.",np:1},
{v:4,t:"Hoje saís, no mês de Abib.",n:"Abib quer dizer espigas novas, como explica a Nova Vulgata, seguindo São Jerônimo."},
{v:5,t:"Quando o Senhor te tiver introduzido na terra dos cananeus, dos heteus, dos amorreus, dos heveus e dos jebuseus, que jurou aos teus pais que te daria, terra onde corre leite e mel, celebrarás este rito neste mês."},
{v:6,t:"Durante sete dias comerás pães sem fermento, e no sétimo dia haverá uma festa em honra do Senhor.",np:1},
{v:7,t:"Comerás pães sem fermento durante os sete dias; não se verá contigo pão fermentado, nem fermento em todo o teu território.",np:1},
{v:8,t:"Naquele dia explicarás ao teu filho: É por causa do que o Senhor fez por mim quando saí do Egito."},
{v:9,t:"Isto será para ti como um sinal na tua mão e como uma lembrança entre os teus olhos, para que a lei do Senhor esteja sempre na tua boca; pois foi com mão poderosa que o Senhor te tirou do Egito."},
{v:10,t:"Observarás este rito no tempo marcado, de ano em ano.",np:1},
{v:11,t:"Quando o Senhor te tiver introduzido na terra dos cananeus, como jurou a ti e aos teus pais, e a tiver dado a ti,",np:1},
{v:12,t:"consagrarás ao Senhor todo o que abre o seio materno; também todo primeiro filhote do teu gado, se for macho, pertencerá ao Senhor."},
{v:13,t:"Resgatarás com um cordeiro todo primeiro filhote de jumenta; se não o resgatares, tu o matarás. Mas resgatarás todo primogênito dos teus filhos."},
{v:14,t:"E, quando amanhã o teu filho te perguntar o que significa isso, tu lhe responderás: Com mão poderosa o Senhor nos tirou do Egito, da casa da escravidão."},
{v:15,t:"Como o faraó se obstinava em não nos deixar partir, o Senhor matou todos os primogênitos na terra do Egito, desde o primogênito do homem até o primogênito dos animais; por isso eu sacrifico ao Senhor todo macho que abre o seio materno, e resgato todo primogênito dos meus filhos."},
{v:16,t:"Isto será como um sinal na tua mão e como um distintivo entre os teus olhos, porque o Senhor nos tirou do Egito com mão poderosa.",n:"Israel tomou estas palavras à letra: delas vêm os filactérios, pequenos estojos com textos da Lei, atados ao braço e à testa para a oração (compare Deuteronômio 6,8)."},
{s:"O caminho do deserto"},
{v:17,t:"Quando o faraó deixou o povo partir, Deus não o conduziu pelo caminho da terra dos filisteus, embora fosse o mais curto, porque pensou: Não aconteça que o povo, vendo-se diante da guerra, se arrependa e volte para o Egito;"},
{v:18,t:"mas o fez dar uma volta pelo caminho do deserto, junto ao mar Vermelho. E os filhos de Israel subiram armados da terra do Egito."},
{v:19,t:"Moisés levou consigo os ossos de José, porque José tinha feito os filhos de Israel jurarem, dizendo: Deus vos visitará; levai daqui convosco os meus ossos.",n:"Cumpre-se o juramento de Gênesis 50,25."},
{v:20,t:"Partiram de Sucot e acamparam em Etam, na orla do deserto.",np:1},
{v:21,t:"O Senhor ia à frente deles, de dia numa coluna de nuvem, para lhes mostrar o caminho, e de noite numa coluna de fogo, para os iluminar; assim podiam caminhar de dia e de noite."},
{v:22,t:"A coluna de nuvem durante o dia e a coluna de fogo durante a noite nunca se afastavam da frente do povo."}
];

window.TEXTOS_SEED["exodo"][14] = [
{s:"A travessia do mar"},
{v:1,t:"O Senhor falou a Moisés e disse:"},
{v:2,t:"Dize aos filhos de Israel que voltem atrás e acampem diante de Fiairot, entre Magdol e o mar, defronte de Baal-Sefon; acampareis diante desse lugar, junto ao mar."},
{v:3,t:"O faraó dirá dos filhos de Israel: Estão perdidos no país; o deserto os cercou."},
{v:4,t:"Eu endurecerei o coração do faraó, e ele os perseguirá; mas eu serei glorificado à custa do faraó e de todo o seu exército, e os egípcios saberão que eu sou o Senhor. E os israelitas assim fizeram."},
{v:5,t:"Anunciaram ao rei do Egito que o povo tinha fugido; e o coração do faraó e dos seus servos mudou em relação ao povo, e disseram: Que fizemos, deixando Israel sair do nosso serviço?",np:1},
{v:6,t:"O faraó mandou atrelar o seu carro e levou consigo o seu exército;"},
{v:7,t:"tomou seiscentos carros escolhidos e todos os carros do Egito, com oficiais em cada um deles."},
{v:8,t:"O Senhor endureceu o coração do faraó, rei do Egito, e ele perseguiu os filhos de Israel; mas os filhos de Israel tinham saído de mão levantada."},
{v:9,t:"Os egípcios os perseguiram e os alcançaram acampados junto ao mar: todos os cavalos e carros do faraó, os seus cavaleiros e o seu exército estavam junto de Fiairot, defronte de Baal-Sefon."},
{v:10,t:"Quando o faraó se aproximava, os filhos de Israel levantaram os olhos e viram que os egípcios marchavam atrás deles; tiveram muito medo e clamaram ao Senhor;",np:1},
{v:11,t:"e disseram a Moisés: Será que não havia sepulturas no Egito, para nos trazeres a morrer no deserto? Que nos fizeste, tirando-nos do Egito?"},
{v:12,t:"Não era isto que te dizíamos no Egito: Deixa-nos servir os egípcios? Melhor nos era servir os egípcios do que morrer no deserto."},
{v:13,t:"Moisés respondeu ao povo: Não tenhais medo! Ficai firmes e vede a salvação que o Senhor vai realizar hoje em vosso favor; os egípcios que hoje vedes, nunca mais os vereis."},
{v:14,t:"O Senhor combaterá por vós, e vós ficareis tranquilos."},
{v:15,t:"O Senhor disse a Moisés: Por que clamas a mim? Dize aos filhos de Israel que se ponham em marcha.",np:1},
{v:16,t:"E tu, levanta o teu cajado, estende a mão sobre o mar e divide-o, para que os filhos de Israel passem pelo meio do mar, em terra seca."},
{v:17,t:"Eu endurecerei o coração dos egípcios, e eles entrarão atrás deles; e serei glorificado à custa do faraó e de todo o seu exército, dos seus carros e dos seus cavaleiros.",np:1},
{v:18,t:"E os egípcios saberão que eu sou o Senhor, quando eu for glorificado à custa do faraó, dos seus carros e dos seus cavaleiros."},
{v:19,t:"O anjo de Deus, que ia à frente do acampamento de Israel, mudou de lugar e passou para trás deles; também a coluna de nuvem deixou a frente e se pôs atrás deles,",np:1},
{v:20,t:"ficando entre o acampamento dos egípcios e o acampamento de Israel; a nuvem era escura de um lado e iluminava a noite do outro, de modo que durante toda a noite um não pôde aproximar-se do outro."},
{v:21,t:"Moisés estendeu a mão sobre o mar, e o Senhor fez recuar o mar com um vento forte e abrasador, que soprou a noite toda, e o mar ficou seco; as águas se dividiram.",np:1},
{v:22,t:"Os filhos de Israel entraram pelo meio do mar em terra seca, e as águas formavam como uma muralha à direita e à esquerda deles."},
{v:23,t:"Os egípcios os perseguiram e entraram atrás deles até o meio do mar: todos os cavalos do faraó, os seus carros e os seus cavaleiros."},
{v:24,t:"Na vigília da manhã, o Senhor olhou da coluna de fogo e de nuvem para o acampamento dos egípcios e lançou a confusão no seu exército;"},
{v:25,t:"travou as rodas dos seus carros, de modo que só avançavam com dificuldade. Então os egípcios disseram: Fujamos de Israel, porque o Senhor combate por eles contra nós!"},
{v:26,t:"O Senhor disse a Moisés: Estende a mão sobre o mar, para que as águas voltem sobre os egípcios, sobre os seus carros e os seus cavaleiros.",np:1},
{v:27,t:"Moisés estendeu a mão sobre o mar, e ao romper da manhã o mar voltou ao seu lugar; os egípcios, fugindo, foram ao encontro das águas, e o Senhor os precipitou no meio do mar."},
{v:28,t:"As águas voltaram e cobriram os carros e os cavaleiros de todo o exército do faraó, que tinham entrado no mar atrás deles; não escapou nem um só."},
{v:29,t:"Mas os filhos de Israel caminharam em terra seca pelo meio do mar, e as águas formavam como uma muralha à direita e à esquerda deles."},
{v:30,t:"Naquele dia o Senhor salvou Israel da mão dos egípcios, e Israel viu os egípcios mortos à beira do mar;",np:1},
{v:31,t:"viu a grande obra que o Senhor tinha realizado contra os egípcios; e o povo temeu o Senhor e acreditou no Senhor e em Moisés, seu servo.",n:"A travessia do mar é o coração da fé de Israel e, para os cristãos, figura do batismo (1 Coríntios 10,1–2)."}
];

window.TEXTOS_SEED["exodo"][15] = [
{s:"O cântico de Moisés"},
{v:1,l:["Então Moisés e os filhos de Israel cantaram este cântico ao Senhor, dizendo:","Cantemos ao Senhor,","que se cobriu de glória:","cavalo e cavaleiro","ele lançou no mar!"],n:"Um dos poemas mais antigos da Bíblia. A Igreja o canta na Vigília Pascal, depois da leitura da travessia do mar."},
{v:2,l:["O Senhor é a minha força e o meu vigor,","ele foi a minha salvação.","Ele é o meu Deus,","e eu o glorificarei;","o Deus de meu pai,","e eu o exaltarei!"],np:1},
{v:3,l:["O Senhor é um guerreiro;","Senhor é o seu nome!"],np:1},
{v:4,l:["Os carros do faraó e o seu exército","ele lançou no mar;","os seus melhores guerreiros","afundaram no mar Vermelho."],np:1},
{v:5,l:["Os abismos os cobriram,","desceram às profundezas como uma pedra."],np:1},
{v:6,l:["A tua direita, Senhor,","é magnífica em poder;","a tua direita, Senhor,","esmagou o inimigo."],np:1},
{v:7,l:["Na grandeza da tua glória","derrubaste os teus adversários;","soltaste a tua ira,","que os devorou como palha."],np:1},
{v:8,l:["Ao sopro da tua ira","as águas se amontoaram;","as ondas se ergueram","como um dique,","os abismos se coalharam","no meio do mar."],np:1},
{v:9,l:["O inimigo dizia:","Vou persegui-los, alcançá-los,","repartir os despojos;","vou saciar-me deles,","desembainhar a espada:","a minha mão os destruirá!"],np:1},
{v:10,l:["Sopraste com o teu vento,","e o mar os cobriu;","afundaram como chumbo","nas águas impetuosas."],np:1},
{v:11,l:["Quem é semelhante a ti","entre os deuses, Senhor?","Quem é semelhante a ti,","magnífico em santidade,","terrível e digno de louvor,","que realizas maravilhas?"],np:1},
{v:12,l:["Estendeste a tua direita,","e a terra os engoliu."],np:1},
{v:13,l:["Guiaste com o teu amor","o povo que resgataste,","e com o teu poder o conduziste","à tua santa morada."],np:1},
{v:14,l:["Os povos ouviram e tremeram;","as dores se apoderaram dos habitantes da Filisteia."],np:1},
{v:15,l:["Então os chefes de Edom se perturbaram,","o tremor tomou conta dos poderosos de Moab,","todos os habitantes de Canaã ficaram paralisados."],np:1},
{v:16,l:["Caíram sobre eles","o terror e o pavor;","pela grandeza do teu braço","ficaram imóveis como pedra,","até que passasse o teu povo, Senhor,","até que passasse este povo","que adquiriste."],np:1},
{v:17,l:["Tu os levarás e os plantarás","no monte da tua herança,","no lugar que fizeste, Senhor,","para a tua morada,","no santuário, Senhor,","que as tuas mãos estabeleceram."],np:1,n:"O monte da tua herança: o monte Sião, onde será construído o templo. O cântico, cantado por séculos em Israel, já olha para a chegada à terra."},
{v:18,l:["O Senhor reinará","para sempre e eternamente!"],np:1},
{v:19,t:"Pois os cavalos do faraó, com os seus carros e cavaleiros, entraram no mar, e o Senhor fez voltar sobre eles as águas do mar; mas os filhos de Israel caminharam em terra seca pelo meio do mar.",np:1},
{v:20,t:"Então a profetisa Míriam, irmã de Aarão, tomou na mão um tamborim, e todas as mulheres saíram atrás dela com tamborins, dançando;",n:"Míriam: em hebraico Miryam, o mesmo nome que em grego se tornou Maria, e assim o escreve a Nova Vulgata."},
{v:21,l:["e Míriam entoava para elas:","Cantai ao Senhor,","que se cobriu de glória:","cavalo e cavaleiro","ele lançou no mar!"],np:1},
{s:"As águas de Mara"},
{v:22,t:"Moisés fez Israel partir do mar Vermelho, e eles saíram para o deserto de Sur; caminharam três dias pelo deserto sem encontrar água."},
{v:23,t:"Chegaram a Mara, mas não puderam beber as águas de Mara, porque eram amargas; por isso deram ao lugar o nome de Mara.",n:"Mara quer dizer amargura, como explica a Nova Vulgata, seguindo São Jerônimo."},
{v:24,t:"O povo murmurou contra Moisés, dizendo: Que vamos beber?"},
{v:25,t:"Moisés clamou ao Senhor, e o Senhor lhe mostrou um pedaço de madeira; Moisés o lançou nas águas, e as águas se tornaram doces. Ali o Senhor deu ao povo uma lei e um direito, e ali o pôs à prova,"},
{v:26,t:"dizendo: Se ouvires atentamente a voz do Senhor, teu Deus, e fizeres o que é reto aos seus olhos, se obedeceres aos seus mandamentos e guardares todos os seus preceitos, não mandarei sobre ti nenhuma das doenças que mandei sobre o Egito, pois eu sou o Senhor, aquele que te cura."},
{v:27,t:"Chegaram a Elim, onde havia doze fontes de água e setenta palmeiras; e acamparam ali, junto às águas.",np:1}
];

window.TEXTOS_SEED["exodo"][16] = [
{s:"O maná e as codornizes"},
{v:1,t:"Partiram de Elim, e toda a comunidade dos filhos de Israel chegou ao deserto de Sin, que fica entre Elim e o Sinai, no dia quinze do segundo mês depois da saída da terra do Egito."},
{v:2,t:"No deserto, toda a comunidade dos filhos de Israel murmurou contra Moisés e Aarão,",np:1},
{v:3,t:"e os filhos de Israel lhes disseram: Antes tivéssemos morrido pela mão do Senhor na terra do Egito, quando nos sentávamos junto às panelas de carne e comíamos pão à vontade! Por que nos trouxestes a este deserto, para matar de fome toda esta multidão?"},
{v:4,t:"O Senhor disse a Moisés: Eis que farei chover pão do céu para vós; o povo sairá e recolherá cada dia a porção de cada dia, para que eu o ponha à prova e veja se anda ou não segundo a minha lei.",np:1,n:"Pão do céu: Jesus retoma a imagem e se apresenta como o verdadeiro pão descido do céu (João 6,31–35)."},
{v:5,t:"No sexto dia, quando prepararem o que tiverem trazido, haverá o dobro do que recolhem nos outros dias."},
{v:6,l:["Moisés e Aarão disseram a todos os filhos de Israel:","Esta tarde sabereis","que foi o Senhor quem vos tirou","da terra do Egito;"],np:1},
{v:7,l:["e amanhã vereis","a glória do Senhor.","Pois ele ouviu as vossas murmurações contra o Senhor. E nós, quem somos, para murmurardes contra nós?"],np:1},
{v:8,l:["E Moisés disse:","O Senhor vos dará","à tarde carne para comer","e pela manhã pão à vontade,","porque ouviu as murmurações que fizestes contra ele. Pois nós, quem somos? Não é contra nós que murmurais, mas contra o Senhor."],np:1},
{v:9,t:"Moisés disse a Aarão: Dize a toda a comunidade dos filhos de Israel: Aproximai-vos da presença do Senhor, porque ele ouviu as vossas murmurações.",np:1},
{v:10,t:"Enquanto Aarão falava a toda a comunidade dos filhos de Israel, eles se voltaram para o deserto, e eis que a glória do Senhor apareceu na nuvem."},
{v:11,t:"O Senhor falou a Moisés e disse:"},
{v:12,t:"Ouvi as murmurações dos filhos de Israel. Dize-lhes: Ao entardecer comereis carne, e pela manhã vos fartareis de pão; e sabereis que eu sou o Senhor, vosso Deus."},
{v:13,t:"À tarde subiram codornizes, que cobriram o acampamento; e pela manhã havia uma camada de orvalho ao redor do acampamento.",np:1},
{v:14,t:"Quando a camada de orvalho evaporou, apareceu sobre a superfície do deserto uma coisa miúda, granulosa, fina como a geada sobre a terra.",np:1},
{v:15,t:"Ao vê-la, os filhos de Israel perguntavam uns aos outros: Man hu? Pois não sabiam o que era. Moisés lhes disse: Este é o pão que o Senhor vos deu para comer.",n:"Man hu, isto é, que é isto: a Nova Vulgata reproduz entre parênteses a explicação de São Jerônimo. Daí o nome maná (16,31)."},
{v:16,t:"Eis o que o Senhor ordenou: Recolha cada um o quanto precisa para comer, um ômer por pessoa, segundo o número de pessoas que cada um tiver na sua tenda."},
{v:17,t:"Os filhos de Israel assim fizeram, e recolheram uns mais, outros menos."},
{v:18,t:"Quando o mediram com o ômer, quem tinha recolhido mais não teve de sobra, e quem tinha recolhido menos não teve falta: cada um tinha recolhido o que podia comer.",np:1,n:"São Paulo cita este versículo a propósito da partilha entre as Igrejas (2 Coríntios 8,15)."},
{v:19,t:"Moisés lhes disse: Ninguém deixe nada para a manhã seguinte.",np:1},
{v:20,t:"Mas eles não ouviram Moisés, e alguns deixaram uma parte para a manhã seguinte; mas encheu-se de vermes e cheirou mal. E Moisés se irritou contra eles."},
{v:21,t:"Recolhiam-no todas as manhãs, cada um o quanto precisava para comer; e, quando o sol esquentava, ele se derretia."},
{s:"O maná e o sábado"},
{v:22,t:"No sexto dia recolheram o dobro de pão, dois ômeres por pessoa. Todos os chefes da comunidade vieram contar isso a Moisés."},
{v:23,t:"Ele lhes disse: É isto o que o Senhor disse: Amanhã é dia de repouso, sábado consagrado ao Senhor. Assai o que tiverdes de assar e cozinhai o que tiverdes de cozinhar; e o que sobrar, guardai-o para amanhã.",np:1},
{v:24,t:"Eles o guardaram para a manhã seguinte, como Moisés tinha ordenado, e não cheirou mal nem se encheu de vermes."},
{v:25,t:"Moisés disse: Comei-o hoje, porque hoje é sábado em honra do Senhor; hoje não o encontrareis no campo.",np:1},
{v:26,t:"Recolhereis durante seis dias; mas o sétimo dia é sábado: nesse dia não haverá maná."},
{v:27,t:"No sétimo dia, alguns do povo saíram para recolher, mas não encontraram nada.",np:1},
{v:28,t:"O Senhor disse a Moisés: Até quando vos recusareis a guardar os meus mandamentos e as minhas leis?"},
{v:29,t:"Vede: o Senhor vos deu o sábado; por isso, no sexto dia, ele vos dá pão para dois dias. Que cada um fique onde está: ninguém saia do seu lugar no sétimo dia."},
{v:30,t:"E o povo descansou no sétimo dia."},
{v:31,t:"A casa de Israel deu a esse alimento o nome de maná; era como semente de coentro, branco, e o seu sabor era como o de bolo de flor de farinha com mel.",np:1},
{v:32,t:"Moisés disse: É isto o que o Senhor ordenou: Enchei um ômer de maná e guardai-o para as vossas gerações, para que vejam o pão com que vos alimentei no deserto, quando vos tirei da terra do Egito.",np:1},
{v:33,t:"Moisés disse a Aarão: Toma um vaso, põe nele um ômer cheio de maná e deposita-o diante do Senhor, para ser guardado para as vossas gerações."},
{v:34,t:"Como o Senhor tinha ordenado a Moisés, Aarão o depositou diante do Testemunho, para ser guardado.",n:"O Testemunho: as tábuas da Lei, guardadas na arca (25,16); o narrador antecipa o que ainda vai acontecer (compare Hebreus 9,4)."},
{v:35,t:"Os filhos de Israel comeram o maná durante quarenta anos, até chegarem a uma terra habitada; comeram o maná até chegarem aos limites da terra de Canaã.",np:1},
{v:36,t:"O ômer é a décima parte do efá.",np:1}
];
