// =====================================================================
// Ezequiel — tradução do hebraico (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["ezequiel"][1] = [
{s:"Introdução"},
{v:1,t:"No trigésimo ano, no quarto mês, no dia cinco do mês, quando eu estava entre os deportados, junto ao rio Cobar, os céus se abriram, e tive visões de Deus.",n:"O trigésimo ano: talvez a idade do profeta. Cobar: canal do Eufrates, perto de Nipur, na Babilônia."},
{v:2,t:"No dia cinco do mês — era o quinto ano da deportação do rei Joaquin —,",n:"Em julho de 593 antes de Cristo."},
{v:3,t:"a palavra do Senhor foi dirigida a Ezequiel, filho de Buzi, sacerdote, na terra dos caldeus, junto ao rio Cobar; e ali a mão do Senhor esteve sobre ele."},
{s:"A visão da glória do Senhor"},
{v:4,t:"Olhei, e eis que um vento tempestuoso vinha do norte, uma grande nuvem e um fogo que se revolvia, com um esplendor ao redor; e no meio dele havia como que o brilho do electro, no meio do fogo.",n:"Electro: liga brilhante de ouro e prata; o sentido exato da palavra hebraica (hashmal) é incerto."},
{v:5,t:"E no meio havia a forma de quatro seres vivos, e esta era a sua aparência: tinham forma humana."},
{v:6,t:"Cada um tinha quatro faces, e cada um tinha quatro asas."},
{v:7,t:"As suas pernas eram retas, e a planta dos seus pés era como a planta do pé de um bezerro; e brilhavam como o bronze polido."},
{v:8,t:"Debaixo das asas, nos quatro lados, tinham mãos humanas. Os quatro tinham faces e asas;"},
{v:9,t:"as suas asas tocavam uma na outra; ao andar, não se voltavam: cada um andava para a frente."},
{v:10,t:"Quanto à forma das suas faces: os quatro tinham face de homem e face de leão à direita, face de touro à esquerda, e os quatro tinham face de águia.",np:1,n:"A tradição cristã viu nestas quatro faces os símbolos dos quatro evangelistas (compare Apocalipse 4,7)."},
{v:11,t:"Tinham as asas estendidas para o alto; cada um tinha duas asas que se tocavam e duas que lhe cobriam o corpo.",np:1},
{v:12,t:"Cada um andava para a frente: iam para onde o espírito os impelia, e não se voltavam ao andar."},
{v:13,t:"No meio dos seres vivos havia algo semelhante a brasas de fogo acesas, semelhante a tochas que se moviam entre os seres vivos; o fogo resplandecia, e do fogo saíam relâmpagos.",np:1},
{v:14,t:"E os seres vivos iam e vinham como o clarão do relâmpago."},
{v:15,t:"Enquanto eu olhava os seres vivos, vi uma roda no chão, ao lado de cada um dos quatro seres vivos.",np:1},
{v:16,t:"O aspecto das rodas e a sua estrutura eram como o brilho do crisólito, e as quatro tinham a mesma forma; o seu aspecto e a sua estrutura eram como se uma roda estivesse dentro da outra."},
{v:17,t:"Quando se moviam, iam nas quatro direções, sem se voltarem ao andar."},
{v:18,t:"Os seus aros eram altos e terríveis de ver; e os aros das quatro rodas estavam cheios de olhos ao redor."},
{v:19,t:"Quando os seres vivos andavam, as rodas andavam ao lado deles; e quando os seres vivos se elevavam da terra, as rodas também se elevavam."},
{v:20,t:"Iam para onde o espírito os impelia, e as rodas se elevavam junto com eles, pois o espírito dos seres vivos estava nas rodas."},
{v:21,t:"Quando eles andavam, elas andavam; quando eles paravam, elas paravam; e quando se elevavam da terra, as rodas se elevavam junto com eles, pois o espírito dos seres vivos estava nas rodas."},
{v:22,t:"Acima das cabeças dos seres vivos havia algo semelhante a um firmamento, com o brilho terrível do cristal, estendido sobre as suas cabeças.",np:1},
{v:23,t:"Debaixo do firmamento, as suas asas estavam estendidas, uma em direção à outra; cada um tinha duas asas que lhe cobriam o corpo."},
{v:24,t:"Ouvi o ruído das suas asas, como o ruído de muitas águas, como a voz do Todo-poderoso; quando andavam, era um estrondo como o de um exército; quando paravam, baixavam as asas.",np:1},
{v:25,t:"E quando se ouvia uma voz acima do firmamento que estava sobre as suas cabeças, eles paravam e baixavam as asas."},
{v:26,t:"Acima do firmamento que estava sobre as suas cabeças, havia algo semelhante a um trono, com o aspecto de pedra de safira; e sobre essa forma de trono, no alto, havia uma figura com aparência humana.",np:1},
{v:27,t:"Vi também algo como o brilho do electro, com aspecto de fogo ao redor, desde o que parecia ser a sua cintura para cima; e desde o que parecia ser a sua cintura para baixo, vi algo como fogo, e um esplendor ao seu redor."},
{v:28,t:"Como o aspecto do arco que aparece nas nuvens em dia de chuva, assim era o aspecto do esplendor ao redor. Era esta a aparência da imagem da glória do Senhor. Ao vê-la, caí com o rosto por terra e ouvi a voz de alguém que falava.",n:"Ezequiel acumula as comparações (algo semelhante, como que) para indicar que a glória de Deus supera toda descrição."}
];

window.TEXTOS_SEED["ezequiel"][2] = [
{s:"A missão do profeta"},
{v:1,t:"Ele me disse: Filho do homem, põe-te de pé, e eu falarei contigo.",n:"Filho do homem: em hebraico, ben-adam, isto é, ser humano, mortal; é assim que Deus chama o profeta ao longo do livro."},
{v:2,t:"Enquanto ele me falava, o espírito entrou em mim e me pôs de pé, e ouvi aquele que me falava.",np:1},
{v:3,t:"Ele me disse: Filho do homem, eu te envio aos filhos de Israel, a nações rebeldes, que se revoltaram contra mim; eles e os seus pais pecaram contra mim até hoje."},
{v:4,t:"São filhos de rosto duro e de coração obstinado aqueles a quem eu te envio; e tu lhes dirás: Assim diz o Senhor Deus."},
{v:5,t:"Quer escutem, quer não escutem — pois são uma casa rebelde —, saberão que houve um profeta no meio deles."},
{v:6,t:"E tu, filho do homem, não tenhas medo deles nem das suas palavras, ainda que estejas entre urtigas e espinhos e mores entre escorpiões; não tenhas medo das suas palavras nem te assustes diante deles, pois são uma casa rebelde."},
{v:7,t:"Tu lhes dirás as minhas palavras, quer escutem, quer não escutem, pois são rebeldes."},
{v:8,t:"E tu, filho do homem, escuta o que te digo: não sejas rebelde como essa casa rebelde; abre a boca e come o que te dou.",np:1},
{v:9,t:"Olhei, e eis que uma mão estava estendida para mim, e nela havia o rolo de um livro."},
{v:10,t:"Ele o desenrolou diante de mim: estava escrito por dentro e por fora, e nele estavam escritos lamentações, gemidos e ais."}
];

window.TEXTOS_SEED["ezequiel"][3] = [
{s:"O profeta come o rolo"},
{v:1,t:"Ele me disse: Filho do homem, come o que encontras diante de ti; come este rolo e vai falar à casa de Israel."},
{v:2,t:"Abri a boca, e ele me fez comer aquele rolo,"},
{v:3,t:"e me disse: Filho do homem, alimenta o teu ventre e enche as tuas entranhas com este rolo que te dou. Eu o comi, e na minha boca ele era doce como o mel.",n:"Compare Jeremias 15,16; Apocalipse 10,9–10."},
{v:4,t:"Ele me disse: Filho do homem, vai à casa de Israel e fala-lhes as minhas palavras."},
{v:5,t:"Pois não és enviado a um povo de fala obscura e de língua difícil, mas à casa de Israel;"},
{v:6,t:"não a povos numerosos de fala obscura e de língua difícil, cujas palavras não entenderias; se eu te enviasse a eles, eles te escutariam."},
{v:7,t:"Mas a casa de Israel não quererá escutar-te, porque não quer escutar-me; pois toda a casa de Israel tem a fronte dura e o coração obstinado."},
{v:8,t:"Eis que tornei o teu rosto tão duro como o rosto deles, e a tua fronte tão dura como a fronte deles;"},
{v:9,t:"fiz a tua fronte como o diamante, mais dura que a pederneira. Não tenhas medo deles nem te assustes diante deles, pois são uma casa rebelde.",n:"Jogo de palavras com o nome do profeta: Ezequiel significa Deus fortalece."},
{v:10,t:"Disse-me ainda: Filho do homem, todas as palavras que eu te disser, recebe-as no teu coração e ouve-as com os teus ouvidos."},
{v:11,t:"Vai aos deportados, aos filhos do teu povo; fala-lhes e dize-lhes: Assim diz o Senhor Deus; quer escutem, quer não escutem."},
{v:12,t:"Então o espírito me levantou, e ouvi atrás de mim o ruído de um grande estrondo, quando a glória do Senhor se elevou do seu lugar:",np:1,n:"Assim a Nova Vulgata, com uma pequena correção do hebraico, que diz: Bendita seja a glória do Senhor no seu lugar!"},
{v:13,t:"era o ruído das asas dos seres vivos, que batiam uma na outra, o ruído das rodas ao lado deles e o ruído de um grande estrondo."},
{v:14,t:"O espírito me levantou e me levou; e eu fui, amargurado e com o espírito irritado, enquanto a mão do Senhor pesava fortemente sobre mim."},
{v:15,t:"Cheguei aos deportados de Tel-Abib, que moravam junto ao rio Cobar, e fiquei sentado ali, onde eles moravam, durante sete dias, atordoado no meio deles.",np:1,n:"Tel-Abib: colina das espigas, aldeia de deportados na Babilônia."},
{s:"A sentinela de Israel"},
{v:16,t:"Ao fim dos sete dias, a palavra do Senhor me foi dirigida:"},
{v:17,t:"Filho do homem, eu te constituí sentinela para a casa de Israel; quando ouvires uma palavra da minha boca, tu os advertirás da minha parte."},
{v:18,t:"Se eu disser ao ímpio: Certamente morrerás, e tu não o advertires nem lhe falares para desviá-lo do seu mau caminho, a fim de que viva, esse ímpio morrerá pela sua iniquidade, mas eu pedirei contas do seu sangue a ti."},
{v:19,t:"Mas, se advertires o ímpio, e ele não se converter da sua impiedade e do seu mau caminho, ele morrerá pela sua iniquidade, mas tu terás salvado a tua vida."},
{v:20,t:"Se o justo se afastar da sua justiça e praticar o mal, eu porei diante dele uma pedra de tropeço, e ele morrerá; porque não o advertiste, morrerá no seu pecado, e as obras justas que praticou não serão lembradas; mas eu pedirei contas do seu sangue a ti."},
{v:21,t:"Se, porém, advertires o justo para que não peque, e ele não pecar, certamente viverá, porque foi advertido, e tu terás salvado a tua vida."},
{s:"O profeta mudo"},
{v:22,t:"Ali a mão do Senhor esteve sobre mim, e ele me disse: Levanta-te, sai para a planície, e lá falarei contigo."},
{v:23,t:"Levantei-me e saí para a planície, e eis que ali estava a glória do Senhor, como a glória que eu tinha visto junto ao rio Cobar; e caí com o rosto por terra."},
{v:24,t:"Então o espírito entrou em mim e me pôs de pé; ele falou comigo e me disse: Vai fechar-te em tua casa."},
{v:25,t:"E tu, filho do homem, eis que porão cordas sobre ti e te amarrarão com elas, e não poderás sair para o meio deles."},
{v:26,t:"Farei que a tua língua se cole ao teu palato, e ficarás mudo e não serás para eles alguém que os repreende, pois são uma casa rebelde."},
{v:27,t:"Mas, quando eu te falar, abrirei a tua boca, e tu lhes dirás: Assim diz o Senhor Deus. Quem quiser escutar, que escute; quem não quiser, que não escute, pois são uma casa rebelde."}
];

window.TEXTOS_SEED["ezequiel"][4] = [
{s:"O cerco de Jerusalém encenado"},
{v:1,t:"E tu, filho do homem, toma um tijolo, põe-no diante de ti e desenha nele uma cidade, Jerusalém.",n:"O profeta encena o cerco de Jerusalém (588–587 antes de Cristo) alguns anos antes de acontecer."},
{v:2,t:"Monta contra ela um cerco: constrói trincheiras, levanta uma rampa, põe acampamentos contra ela e coloca aríetes ao redor."},
{v:3,t:"Toma também uma assadeira de ferro e põe-na como um muro de ferro entre ti e a cidade; fixa o teu olhar nela, e ela ficará sitiada, e tu a cercarás: é um sinal para a casa de Israel."},
{v:4,t:"Depois deita-te sobre o lado esquerdo e põe sobre ele a iniquidade da casa de Israel; carregarás a iniquidade deles pelo número de dias em que ficares deitado sobre esse lado.",np:1},
{v:5,t:"Eu te fixo os anos da iniquidade deles num número de dias: trezentos e noventa dias; e carregarás a iniquidade da casa de Israel.",n:"Trezentos e noventa: assim o hebraico; a tradução grega diz cento e noventa. O sentido dos números é discutido."},
{v:6,t:"Quando os tiveres completado, tu te deitarás de novo, agora sobre o lado direito, e carregarás a iniquidade da casa de Judá durante quarenta dias; um dia por ano, eu te fixo um dia por ano."},
{v:7,t:"Voltarás o rosto para o cerco de Jerusalém, com o braço descoberto, e profetizarás contra ela."},
{v:8,t:"Eis que te amarrei com cordas, e não te virarás de um lado para o outro, até completares os dias do teu cerco."},
{s:"O pão do cerco"},
{v:9,t:"Toma também trigo, cevada, favas, lentilhas, milhete e espelta, põe tudo numa só vasilha e faze com isso o teu pão; tu o comerás durante os trezentos e noventa dias em que ficares deitado sobre o teu lado."},
{v:10,t:"A comida que comerás será pesada: vinte siclos por dia; tu a comerás de tempos em tempos.",n:"Cerca de duzentos e trinta gramas."},
{v:11,t:"Beberás também a água medida: a sexta parte de um hin; tu a beberás de tempos em tempos.",n:"Pouco mais de meio litro."},
{v:12,t:"Tu o comerás como pão de cevada cozido sob as cinzas; e o cozerás à vista deles sobre excrementos humanos."},
{v:13,t:"E o Senhor disse: Assim os filhos de Israel comerão o seu pão impuro entre as nações para onde eu os expulsarei."},
{v:14,t:"Eu disse: Ah, Senhor Deus! Eis que eu nunca me contaminei; desde a minha juventude até agora nunca comi animal morto ou despedaçado por feras, e nunca entrou na minha boca carne impura."},
{v:15,t:"Ele me respondeu: Pois bem, eu te permito usar esterco de boi em vez de excrementos humanos; sobre ele cozerás o teu pão."},
{v:16,t:"E me disse: Filho do homem, eis que vou quebrar o sustento do pão em Jerusalém; eles comerão o pão pesado e com ansiedade, e beberão a água medida e com angústia,"},
{v:17,t:"para que, faltando o pão e a água, fiquem consternados uns com os outros e definhem na sua iniquidade."}
];

window.TEXTOS_SEED["ezequiel"][5] = [
{s:"Os cabelos cortados: o destino de Jerusalém"},
{v:1,t:"E tu, filho do homem, toma uma espada afiada, usa-a como navalha de barbeiro e passa-a sobre a cabeça e a barba; depois toma uma balança e divide os pelos."},
{v:2,t:"Queimarás um terço no fogo, no meio da cidade, quando se completarem os dias do cerco; tomarás outro terço e o cortarás com a espada ao redor da cidade; e o último terço espalharás ao vento, e eu desembainharei a espada atrás deles."},
{v:3,t:"Tomarás deles um pequeno número e os amarrarás na barra do teu manto;"},
{v:4,t:"e destes ainda tomarás alguns, os jogarás no fogo e os queimarás; dali sairá um fogo. E dirás a toda a casa de Israel:"},
{v:5,t:"Assim diz o Senhor Deus: Esta é Jerusalém! Eu a pus no meio das nações, com os países ao seu redor."},
{v:6,t:"Mas ela se rebelou contra os meus decretos, com mais impiedade que as nações, e contra os meus preceitos, mais que os países que a rodeiam; pois rejeitaram os meus decretos e não andaram nos meus preceitos."},
{v:7,t:"Por isso assim diz o Senhor Deus: Porque fostes mais turbulentos que as nações que vos rodeiam, não andastes nos meus preceitos e não cumpristes os meus decretos, e nem sequer agistes segundo os costumes das nações que vos rodeiam,",np:1},
{v:8,t:"por isso assim diz o Senhor Deus: Eis que também eu estou contra ti, e executarei no meio de ti os meus julgamentos, à vista das nações."},
{v:9,t:"Farei em ti o que nunca fiz e o que nunca mais farei, por causa de todas as tuas abominações."},
{v:10,t:"Por isso, no meio de ti, os pais comerão os filhos, e os filhos comerão os pais; executarei em ti os meus julgamentos e espalharei a todos os ventos tudo o que restar de ti.",n:"Nota do tradutor: compare Levítico 26,29; Deuteronômio 28,53; Lamentações 4,10; o texto não foi suavizado."},
{v:11,t:"Por isso, pela minha vida, oráculo do Senhor Deus, porque profanaste o meu santuário com todas as tuas coisas detestáveis e com todas as tuas abominações, também eu te rasparei, sem que o meu olho tenha piedade, e não terei compaixão."},
{v:12,t:"Um terço de ti morrerá de peste e será consumido pela fome no meio de ti; um terço cairá pela espada ao teu redor; e o outro terço espalharei a todos os ventos, e desembainharei a espada atrás deles."},
{v:13,t:"Assim esgotarei a minha ira, saciarei neles o meu furor e ficarei satisfeito; e saberão que eu, o Senhor, falei no meu zelo, quando tiver esgotado neles o meu furor."},
{v:14,t:"Farei de ti uma ruína e um objeto de insulto entre as nações que te rodeiam, à vista de todos os que passarem."},
{v:15,t:"Serás objeto de insulto e de escárnio, uma lição e um espanto para as nações que te rodeiam, quando eu executar em ti os meus julgamentos com ira, furor e castigos violentos."},
{v:16,t:"Eu, o Senhor, falei. Quando eu lançar contra vós as flechas terríveis da fome, que trazem a morte, e que lançarei para vos destruir, aumentarei a fome sobre vós e quebrarei o sustento do pão;"},
{v:17,t:"mandarei contra vós a fome e as feras, que te deixarão sem filhos; a peste e o sangue passarão por ti, e farei vir a espada sobre ti. Eu, o Senhor, falei."}
];

window.TEXTOS_SEED["ezequiel"][6] = [
{s:"Contra os montes de Israel"},
{v:1,t:"A palavra do Senhor me foi dirigida:"},
{v:2,t:"Filho do homem, volta o rosto para os montes de Israel e profetiza contra eles."},
{v:3,t:"Dize: Montes de Israel, ouvi a palavra do Senhor Deus. Assim diz o Senhor Deus aos montes e às colinas, às ravinas e aos vales: Eis que vou fazer vir sobre vós a espada e destruirei os vossos lugares altos;"},
{v:4,t:"os vossos altares serão demolidos, os vossos altares de incenso serão quebrados, e farei cair os vossos mortos diante dos vossos ídolos.",n:"Ídolos: em hebraico, gillulim, termo de desprezo muito usado por Ezequiel, talvez ligado a bolotas de esterco."},
{v:5,t:"Porei os cadáveres dos filhos de Israel diante dos seus ídolos e espalharei os vossos ossos ao redor dos vossos altares."},
{v:6,t:"Em todos os lugares onde morais, as cidades ficarão desertas e os lugares altos serão demolidos, para que os vossos altares sejam arrasados e destruídos, os vossos ídolos quebrados e eliminados, os vossos altares de incenso despedaçados e as vossas obras apagadas."},
{v:7,t:"Os mortos cairão no meio de vós, e sabereis que eu sou o Senhor."},
{v:8,t:"Mas deixarei entre vós alguns que escaparão da espada entre as nações, quando eu vos dispersar pelos países;",np:1},
{v:9,t:"e os vossos sobreviventes se lembrarão de mim entre as nações para onde tiverem sido levados cativos, porque eu quebrarei o seu coração adúltero, que se afastou de mim, e os seus olhos, que se prostituíram atrás dos seus ídolos; e terão nojo de si mesmos por causa das maldades que cometeram com todas as suas abominações,"},
{v:10,t:"e saberão que eu, o Senhor, não falei em vão, quando disse que lhes faria este mal."},
{s:"Lamento sobre as abominações"},
{v:11,t:"Assim diz o Senhor Deus: Bate palmas, bate com o pé e dize: Ai de todas as horríveis abominações da casa de Israel, que cairá pela espada, pela fome e pela peste!"},
{v:12,t:"Quem estiver longe morrerá de peste; quem estiver perto cairá pela espada; e quem sobreviver e estiver sitiado morrerá de fome; assim esgotarei neles o meu furor."},
{v:13,t:"E sabereis que eu sou o Senhor, quando os seus mortos jazerem no meio dos seus ídolos, ao redor dos seus altares, em toda colina elevada, em todos os cumes dos montes, debaixo de toda árvore frondosa e de todo carvalho copado, lugares onde ofereciam incenso perfumado a todos os seus ídolos."},
{v:14,t:"Estenderei a minha mão contra eles e farei da terra uma desolação e um deserto, desde o deserto até Rebla, em todos os lugares onde moram; e saberão que eu sou o Senhor.",n:"Rebla: assim a Nova Vulgata, com alguns manuscritos; o hebraico diz Dibla. O deserto fica no extremo sul, e Rebla, no extremo norte."}
];

window.TEXTOS_SEED["ezequiel"][7] = [
{s:"O fim chegou"},
{v:1,t:"A palavra do Senhor me foi dirigida:"},
{v:2,t:"E tu, filho do homem, fala. Assim diz o Senhor Deus à terra de Israel: O fim! Chegou o fim sobre os quatro cantos da terra!"},
{v:3,t:"Agora o fim está sobre ti: lançarei contra ti a minha ira, eu te julgarei segundo os teus caminhos e farei cair sobre ti todas as tuas abominações."},
{v:4,t:"O meu olho não terá piedade de ti, e não terei compaixão; mas farei cair sobre ti os teus caminhos, e as tuas abominações estarão no meio de ti; e sabereis que eu sou o Senhor.",np:1},
{v:5,t:"Assim diz o Senhor Deus: Eis que vem desgraça após desgraça.",np:1},
{v:6,t:"Chegou o fim, chegou o fim; ele despertou contra ti; eis que chegou.",n:"No hebraico, jogo de palavras entre o fim (qets) e despertar (heqits)."},
{v:7,t:"Chegou para ti a ruína, habitante da terra; chegou o tempo, está perto o dia do tumulto, e não dos gritos de alegria nos montes.",n:"A ruína: palavra hebraica de sentido incerto."},
{v:8,t:"Agora, bem depressa, derramarei sobre ti a minha ira e esgotarei em ti o meu furor; eu te julgarei segundo os teus caminhos e farei cair sobre ti todas as tuas abominações;"},
{v:9,t:"o meu olho não terá piedade, e não terei compaixão; farei cair sobre ti os teus caminhos, e as tuas abominações estarão no meio de ti; e sabereis que sou eu, o Senhor, quem fere."},
{s:"O dia da ira"},
{v:10,t:"Eis o dia, eis que chega! Saiu a ruína, floresceu a injustiça, brotou o orgulho;"},
{v:11,t:"a violência se levantou como vara da impiedade; nada restará deles, nem da sua multidão, nem do seu tumulto, e não haverá descanso para eles."},
{v:12,t:"Chegou o tempo, aproximou-se o dia: quem compra não se alegre, e quem vende não se lamente, pois a ira está sobre toda a sua multidão."},
{v:13,t:"Pois quem vende não recuperará o que vendeu, ainda que continue vivo. Porque a visão contra toda a sua multidão não será revogada, e ninguém, por causa da sua iniquidade, conservará a vida.",n:"Alusão à lei do jubileu (Levítico 25,13–16): não haverá mais volta à propriedade de família."},
{v:14,t:"Tocai a trombeta, preparai tudo! Mas ninguém vai à batalha, pois a minha ira está sobre toda a sua multidão."},
{v:15,t:"Fora, a espada; dentro, a peste e a fome. Quem estiver no campo morrerá pela espada, e quem estiver na cidade será devorado pela fome e pela peste.",np:1},
{v:16,t:"Os que dentre eles escaparem se salvarão e estarão nos montes, como as pombas dos vales, todos gemendo, cada um pela sua iniquidade."},
{s:"O desespero do povo"},
{v:17,t:"Todas as mãos desfalecerão, e todos os joelhos se desfarão em água.",n:"Expressão do pavor extremo; alguns entendem que se urinarão de medo."},
{v:18,t:"Vestirão pano de saco, e o terror os cobrirá; haverá vergonha em todos os rostos e calvície em todas as cabeças."},
{v:19,t:"Jogarão a sua prata nas ruas, e o seu ouro se tornará imundície; a sua prata e o seu ouro não poderão salvá-los no dia do furor do Senhor; não saciarão a sua fome nem encherão o seu ventre, pois isso foi para eles ocasião de pecado,"},
{v:20,t:"e com o esplendor dos seus enfeites alimentaram o seu orgulho e fizeram deles as imagens das suas abominações e dos seus ídolos; por isso farei que isso se torne para eles imundície."},
{v:21,t:"Eu o entregarei como saque nas mãos dos estrangeiros e como presa aos ímpios da terra, que o profanarão."},
{v:22,t:"Desviarei deles o meu rosto, e profanarão o meu tesouro escondido; entrarão nele os salteadores e o profanarão,",n:"O meu tesouro escondido: o templo."},
{v:23,t:"e farão correntes; pois a terra está cheia de crimes de sangue, e a cidade, cheia de violência."},
{v:24,t:"Trarei as piores das nações, e elas possuirão as suas casas; porei fim ao orgulho dos poderosos, e eles possuirão os seus santuários."},
{v:25,t:"Chegará a angústia; procurarão a paz, e não haverá."},
{v:26,t:"Virá desgraça sobre desgraça, e boato sobre boato; pedirão uma visão ao profeta, mas a lei faltará ao sacerdote, e o conselho, aos anciãos."},
{v:27,t:"O rei ficará de luto, o príncipe se vestirá de desolação, e as mãos do povo da terra tremerão. Eu os tratarei segundo o seu procedimento e os julgarei segundo os seus próprios julgamentos; e saberão que eu sou o Senhor."}
];

window.TEXTOS_SEED["ezequiel"][8] = [
{s:"As abominações no templo"},
{v:1,t:"No sexto ano, no sexto mês, no dia cinco do mês, eu estava sentado em minha casa, e os anciãos de Judá estavam sentados diante de mim; e ali a mão do Senhor Deus caiu sobre mim.",n:"Em setembro de 592 antes de Cristo."},
{v:2,t:"Olhei, e eis uma figura com aparência de homem: desde o que parecia ser a sua cintura para baixo, era fogo; e desde a cintura para cima, algo como um esplendor, como o brilho do electro.",n:"Homem: assim a Nova Vulgata, com a tradução grega; o hebraico diz fogo."},
{v:3,t:"Ele estendeu algo semelhante a uma mão e me pegou por uma mecha de cabelo; e o espírito me levantou entre a terra e o céu e me levou a Jerusalém, em visões de Deus, à entrada da porta interior que dá para o norte, onde estava colocado o ídolo do ciúme, que provoca o ciúme.",n:"O ídolo do ciúme: talvez uma imagem de Aserá (compare 2 Reis 21,7), que provocava o ciúme do Senhor."},
{v:4,t:"E eis que ali estava a glória do Deus de Israel, como na visão que eu tinha tido na planície;"},
{v:5,t:"e ele me disse: Filho do homem, levanta os olhos na direção do norte. Levantei os olhos na direção do norte, e eis que, ao norte da porta do altar, estava aquele ídolo do ciúme, na entrada."},
{v:6,t:"E me disse: Filho do homem, vês o que eles fazem? As grandes abominações que a casa de Israel pratica aqui, para que eu me afaste do meu santuário? Mas verás ainda abominações maiores."},
{v:7,t:"Ele me levou à entrada do átrio, e olhei: eis que havia um buraco na parede.",np:1},
{v:8,t:"Ele me disse: Filho do homem, cava a parede. Cavei a parede, e apareceu uma porta."},
{v:9,t:"E me disse: Entra e vê as horríveis abominações que eles praticam aqui."},
{v:10,t:"Entrei e olhei: eis toda espécie de figuras de répteis e de animais abomináveis, e todos os ídolos da casa de Israel, pintados na parede, ao redor, por toda parte;"},
{v:11,t:"e setenta homens dos anciãos da casa de Israel, com Jezonias, filho de Safã, de pé no meio deles, estavam diante das pinturas, cada um com o seu incensório na mão, e subia a fumaça perfumada do incenso."},
{v:12,t:"Ele me disse: Viste, filho do homem, o que os anciãos da casa de Israel fazem nas trevas, cada um na sala da sua imagem? Pois dizem: O Senhor não nos vê; o Senhor abandonou a terra."},
{v:13,t:"E me disse: Verás ainda abominações maiores que eles praticam."},
{v:14,t:"Ele me levou à entrada da porta da casa do Senhor que dá para o norte, e eis que ali estavam sentadas mulheres chorando Tamuz.",np:1,n:"Tamuz: divindade babilônica da vegetação, cuja morte anual era chorada pelas mulheres."},
{v:15,t:"Ele me disse: Viste, filho do homem? Verás ainda abominações maiores do que estas."},
{v:16,t:"Ele me levou ao átrio interior da casa do Senhor, e eis que, à entrada do templo do Senhor, entre o vestíbulo e o altar, havia uns vinte e cinco homens, de costas para o templo do Senhor e com o rosto voltado para o oriente: adoravam o sol, voltados para o oriente.",np:1},
{v:17,t:"Ele me disse: Viste, filho do homem? Será pouca coisa para a casa de Judá praticar as abominações que praticam aqui? Pois encheram a terra de violência e voltaram a me provocar; e eis que levam o ramo ao nariz.",n:"Gesto de culto pagão, de sentido desconhecido."},
{v:18,t:"Por isso também eu agirei com furor: o meu olho não terá piedade, e não terei compaixão; e, ainda que gritem aos meus ouvidos em alta voz, não os escutarei."}
];

window.TEXTOS_SEED["ezequiel"][9] = [
{s:"O sinal na fronte e o castigo da cidade"},
{v:1,t:"Então ele gritou aos meus ouvidos em alta voz: Aproximam-se os castigos da cidade; cada um tenha na mão a sua arma de destruição."},
{v:2,t:"E eis que seis homens vinham pelo caminho da porta superior, que dá para o norte, cada um com a sua arma de destruição na mão; no meio deles havia um homem vestido de linho, com um estojo de escriba à cintura. Entraram e ficaram de pé junto do altar de bronze."},
{v:3,t:"A glória do Deus de Israel se elevou de cima do querubim sobre o qual estava e foi até o limiar do templo; e chamou o homem vestido de linho, que tinha o estojo de escriba à cintura."},
{v:4,t:"O Senhor lhe disse: Passa pelo meio da cidade, pelo meio de Jerusalém, e marca com um tau a fronte dos homens que gemem e se lamentam por todas as abominações que se praticam no meio dela.",n:"Tau: a última letra do alfabeto hebraico, que na escrita antiga tinha a forma de uma cruz. Os Padres da Igreja viram nela o sinal da cruz; compare Apocalipse 7,3."},
{v:5,t:"E aos outros disse, enquanto eu ouvia: Passai pela cidade atrás dele e feri; o vosso olho não tenha piedade, e não tenhais compaixão:"},
{v:6,t:"matai velhos, jovens e moças, crianças e mulheres, até exterminá-los; mas não toqueis em ninguém que tenha o tau. Começai pelo meu santuário. Começaram, então, pelos anciãos que estavam diante do templo.",n:"Nota do tradutor: a visão descreve o julgamento de Deus sobre a cidade culpada com a linguagem das guerras antigas; o texto não foi suavizado. O julgamento começa pelo santuário (compare 1 Pedro 4,17)."},
{v:7,t:"E lhes disse: Profanai o templo e enchei os átrios de mortos. Saí! Eles saíram e começaram a matar na cidade."},
{v:8,t:"Enquanto matavam, eu fiquei sozinho; caí com o rosto por terra e gritei: Ah, Senhor Deus! Vais destruir todo o resto de Israel, derramando o teu furor sobre Jerusalém?",np:1},
{v:9,t:"Ele me respondeu: A iniquidade da casa de Israel e de Judá é imensamente grande; a terra está cheia de sangue, e a cidade, cheia de injustiça. Pois dizem: O Senhor abandonou a terra, e o Senhor não vê."},
{v:10,t:"Por isso também o meu olho não terá piedade, e não terei compaixão: farei cair sobre a cabeça deles o seu procedimento."},
{v:11,t:"E eis que o homem vestido de linho, que tinha o estojo de escriba à cintura, veio dar conta, dizendo: Fiz como me ordenaste."}
];
