// =====================================================================
// Filipenses — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["filipenses"][1] = [
{s:"Saudação"},
{v:1,t:"Paulo e Timóteo, servos de Cristo Jesus, a todos os santos em Cristo Jesus que estão em Filipos, com os bispos e diáconos:",n:"Filipos foi a primeira comunidade fundada por Paulo em solo europeu, e a que mais o amou. Escreve-lhes da prisão, e a carta inteira respira alegria."},
{v:2,t:"graça a vós e paz, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo."},
{s:"Ação de graças e oração"},
{v:3,t:"Dou graças ao meu Deus todas as vezes que me lembro de vós —"},
{v:4,t:"sempre, em todas as minhas orações por todos vós, orando com alegria —"},
{v:5,t:"pela vossa participação no Evangelho, desde o primeiro dia até agora."},
{v:6,t:"E estou certo de que aquele que começou em vós a boa obra há de levá-la a bom termo até o dia de Cristo Jesus."},
{v:7,t:"É justo que eu assim pense de todos vós, porque vos trago no coração: tanto nas minhas cadeias como na defesa e confirmação do Evangelho, todos vós sois participantes da graça comigo."},
{v:8,t:"Deus é testemunha de quanto anseio por todos vós, na ternura de Cristo Jesus."},
{v:9,t:"E é esta a minha oração: que o vosso amor cresça cada vez mais em conhecimento e em plena percepção,"},
{v:10,t:"para discernirdes o que é melhor, e assim sejais puros e irrepreensíveis para o dia de Cristo,"},
{v:11,t:"cheios do fruto da justiça, que vem por Jesus Cristo, para glória e louvor de Deus."},
{s:"As cadeias servem ao Evangelho"},
{v:12,t:"Quero que saibais, irmãos, que o que me aconteceu serviu antes para o progresso do Evangelho."},
{v:13,t:"Tornou-se, com efeito, manifesto em todo o pretório, e a todos os demais, que estou em cadeias por Cristo;"},
{v:14,t:"e a maior parte dos irmãos, animados no Senhor pelas minhas cadeias, ousam agora anunciar a palavra de Deus sem temor."},
{v:15,t:"É verdade que alguns pregam a Cristo por inveja e rivalidade; outros, porém, com boa intenção.",np:1},
{v:16,t:"Estes, por amor, sabendo que estou aqui para a defesa do Evangelho;"},
{v:17,t:"aqueles anunciam a Cristo por espírito de intriga, sem pureza de intenção, pensando agravar as minhas cadeias."},
{v:18,t:"Mas que importa? Contanto que, de um modo ou de outro, por pretexto ou em verdade, Cristo seja anunciado. E nisso me alegro, e hei de alegrar-me ainda."},
{v:19,t:"Porque sei que isso resultará em minha salvação, pela vossa oração e pelo auxílio do Espírito de Jesus Cristo,",np:1},
{v:20,t:"conforme a minha expectativa e esperança: que em nada serei confundido, mas que, com toda a ousadia, agora como sempre, Cristo será glorificado no meu corpo, seja pela vida, seja pela morte."},
{v:21,t:"Porque, para mim, viver é Cristo, e morrer é lucro."},
{v:22,t:"Mas, se o viver na carne me permite trabalhar com fruto, então não sei o que escolher."},
{v:23,t:"Sinto-me apertado dos dois lados: tenho o desejo de partir e estar com Cristo, o que seria muito melhor;"},
{v:24,t:"mas permanecer na carne é mais necessário por vossa causa."},
{v:25,t:"E, convencido disto, sei que ficarei e permanecerei com todos vós, para o vosso progresso e alegria na fé,"},
{v:26,t:"a fim de que, pela minha volta a vós, cresça em Cristo Jesus o vosso motivo de orgulho em mim."},
{s:"Viver de modo digno do Evangelho"},
{v:27,t:"Vivei somente de modo digno do Evangelho de Cristo, para que, quer eu vá ver-vos, quer esteja ausente, ouça dizer de vós que permaneceis firmes num só espírito, lutando juntos, com uma só alma, pela fé do Evangelho,"},
{v:28,t:"sem vos deixardes intimidar em nada pelos adversários. Isso é para eles sinal de perdição, e para vós, de salvação — e isso vem de Deus."},
{v:29,t:"Porque vos foi concedida a graça, a respeito de Cristo, não só de crer nele, mas também de sofrer por ele,"},
{v:30,t:"sustentando o mesmo combate que me vistes travar e que, segundo ouvis, travo ainda."}
];

window.TEXTOS_SEED["filipenses"][2] = [
{s:"O exemplo de Cristo"},
{v:1,t:"Se há, pois, algum conforto em Cristo, algum consolo do amor, alguma comunhão no Espírito, alguma ternura e compaixão,"},
{v:2,t:"completai a minha alegria: tende o mesmo sentir, o mesmo amor, uma só alma, um só pensamento."},
{v:3,t:"Nada façais por rivalidade ou vanglória; pela humildade, tenha cada um o outro por superior a si."},
{v:4,t:"Não busque cada um o que é seu, mas também o que é dos outros."},
{v:5,t:"Tende entre vós o mesmo sentir que houve em Cristo Jesus:"},
{v:6,l:["Ele, que é de condição divina,","não considerou um tesouro a reter ciosamente","o ser igual a Deus;"],n:"Os versículos 6 a 11 são um hino anterior a Paulo, que ele cita. Descem da condição divina até a morte de cruz e tornam a subir até o nome que está acima de todo nome."},
{v:7,l:["mas esvaziou-se a si mesmo,","tomando a condição de servo,","tornando-se semelhante aos homens;","e, reconhecido em figura humana,"]},
{v:8,l:["humilhou-se a si mesmo,","feito obediente até a morte,","e morte de cruz."]},
{v:9,l:["Por isso Deus o exaltou soberanamente","e lhe deu o nome","que está acima de todo nome,"]},
{v:10,l:["para que, ao nome de Jesus,","todo joelho se dobre","nos céus, na terra e nos abismos,"]},
{v:11,l:["e toda língua confesse","que Jesus Cristo é o Senhor,","para a glória de Deus Pai."]},
{s:"Trabalhar a própria salvação"},
{v:12,t:"Portanto, meus caríssimos, assim como sempre obedecestes, não só na minha presença, mas muito mais agora, na minha ausência, trabalhai a vossa salvação com temor e tremor."},
{v:13,t:"Porque é Deus quem opera em vós o querer e o realizar, segundo o seu beneplácito."},
{v:14,t:"Fazei tudo sem murmurações nem discussões,"},
{v:15,t:"para serdes irrepreensíveis e puros, filhos de Deus sem mácula, no meio de uma geração tortuosa e perversa, na qual resplandeceis como luzeiros no mundo,"},
{v:16,t:"apresentando a palavra da vida, para minha glória no dia de Cristo: sinal de que não corri em vão, nem em vão trabalhei."},
{v:17,t:"E, ainda que eu seja derramado em libação sobre o sacrifício e o serviço da vossa fé, alegro-me e me congratulo com todos vós."},
{v:18,t:"Do mesmo modo, alegrai-vos também vós, e congratulai-vos comigo."},
{s:"Timóteo e Epafrodito"},
{v:19,t:"Espero, no Senhor Jesus, enviar-vos em breve Timóteo, para que eu também me anime com as vossas notícias."},
{v:20,t:"Não tenho ninguém que se lhe iguale no cuidado sincero pelo que vos diz respeito;"},
{v:21,t:"porque todos buscam os próprios interesses, não os de Jesus Cristo."},
{v:22,t:"Mas conheceis as provas que ele deu: serviu comigo ao Evangelho, como um filho ao lado do pai."},
{v:23,t:"Espero, pois, enviá-lo logo que veja o rumo das minhas coisas;"},
{v:24,t:"e confio no Senhor que também eu irei em breve."},
{v:25,t:"Julguei necessário, entretanto, enviar-vos Epafrodito, meu irmão, colaborador e companheiro de combate, que me enviastes para me assistir na necessidade.",np:1},
{v:26,t:"Ele tinha saudades de todos vós, e andava angustiado por terdes sabido da sua doença."},
{v:27,t:"De fato, esteve doente, e à morte; mas Deus teve compaixão dele — e não só dele, mas também de mim, para que eu não tivesse tristeza sobre tristeza."},
{v:28,t:"Por isso, com tanto mais pressa o envio: para que, ao vê-lo de novo, vos alegreis, e eu fique menos triste."},
{v:29,t:"Acolhei-o, pois, no Senhor, com toda alegria, e tende em honra homens assim;"},
{v:30,t:"porque foi pela obra de Cristo que chegou às portas da morte, arriscando a vida para suprir o que faltava ao vosso serviço para comigo."}
];

window.TEXTOS_SEED["filipenses"][3] = [
{s:"A verdadeira justiça"},
{v:1,t:"De resto, meus irmãos, alegrai-vos no Senhor. Escrever-vos as mesmas coisas não me é penoso, e a vós dá segurança."},
{v:2,t:"Acautelai-vos dos cães, acautelai-vos dos maus operários, acautelai-vos dos que mutilam a carne."},
{v:3,t:"Porque a verdadeira circuncisão somos nós, que damos culto no Espírito de Deus e nos gloriamos em Cristo Jesus, sem pôr a confiança na carne —"},
{v:4,t:"embora também eu pudesse pô-la na carne. Se algum outro julga poder confiar na carne, eu mais:"},
{v:5,t:"circuncidado ao oitavo dia, da raça de Israel, da tribo de Benjamim, hebreu, filho de hebreus; quanto à lei, fariseu;"},
{v:6,t:"quanto ao zelo, perseguidor da Igreja; quanto à justiça que está na lei, irrepreensível."},
{v:7,t:"Mas o que era para mim lucro, isso considerei perda por causa de Cristo.",np:1},
{v:8,t:"Sim, tudo considero perda, diante da sublimidade do conhecimento de Cristo Jesus, meu Senhor. Por ele perdi tudo, e tudo tenho por esterco, para ganhar a Cristo"},
{v:9,t:"e nele ser achado, não com a minha justiça, a que vem da lei, mas com a que vem pela fé em Cristo, a justiça que vem de Deus e se apoia na fé;"},
{v:10,t:"para conhecê-lo, e à força da sua ressurreição, e à comunhão dos seus sofrimentos, conformando-me à sua morte,"},
{v:11,t:"para ver se de algum modo chego à ressurreição dentre os mortos."},
{s:"Correr para a meta"},
{v:12,t:"Não que eu já o tenha alcançado, ou que já seja perfeito; mas prossigo, para ver se alcanço aquilo para que fui alcançado por Cristo Jesus."},
{v:13,t:"Irmãos, não julgo tê-lo alcançado. Uma coisa, porém, faço: esquecendo o que fica para trás e lançando-me ao que está adiante,"},
{v:14,t:"corro para a meta, em vista do prêmio do chamamento celeste de Deus, em Cristo Jesus."},
{v:15,t:"Todos nós, pois, que somos perfeitos, pensemos assim; e, se em alguma coisa pensais de outro modo, também isso Deus vos revelará."},
{v:16,t:"Entretanto, no ponto a que chegamos, sigamos o mesmo caminho."},
{v:17,t:"Sede, irmãos, meus imitadores, e observai os que caminham segundo o exemplo que tendes em nós.",np:1},
{v:18,t:"Porque muitos — de quem já vos falei muitas vezes, e agora repito com lágrimas — caminham como inimigos da cruz de Cristo."},
{v:19,t:"O fim deles é a perdição; o deus deles é o ventre; a glória deles está na sua vergonha; e só pensam nas coisas da terra."},
{v:20,t:"A nossa cidade, porém, está nos céus, de onde aguardamos como salvador o Senhor Jesus Cristo,"},
{v:21,t:"que há de transfigurar o nosso corpo humilhado, para o conformar ao seu corpo glorioso, com o poder que o torna capaz de sujeitar a si todas as coisas."}
];

window.TEXTOS_SEED["filipenses"][4] = [
{s:"Exortações"},
{v:1,t:"Portanto, meus irmãos amados e saudosos, minha alegria e minha coroa, permanecei assim firmes no Senhor, caríssimos."},
{v:2,t:"Peço a Evódia e peço a Síntique que tenham o mesmo sentir no Senhor."},
{v:3,t:"E a ti, fiel companheiro, peço que as ajudes: elas lutaram comigo pelo Evangelho, com Clemente e os demais colaboradores meus, cujos nomes estão no livro da vida."},
{v:4,t:"Alegrai-vos sempre no Senhor. Repito: alegrai-vos!",np:1},
{v:5,t:"Seja conhecida de todos os homens a vossa bondade. O Senhor está perto."},
{v:6,t:"Não vos inquieteis com coisa alguma; em toda oração e súplica, com ação de graças, sejam apresentadas a Deus as vossas petições."},
{v:7,t:"E a paz de Deus, que excede todo entendimento, guardará os vossos corações e os vossos pensamentos em Cristo Jesus."},
{v:8,t:"De resto, irmãos, tudo o que é verdadeiro, tudo o que é nobre, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se há alguma virtude e algum louvor, seja isso o que ocupe os vossos pensamentos."},
{v:9,t:"O que aprendestes, recebestes, ouvistes e vistes em mim, isso praticai; e o Deus da paz estará convosco."},
{s:"Gratidão pela ajuda recebida"},
{v:10,t:"Muito me alegrei no Senhor por ter enfim reflorescido o vosso cuidado por mim. Vós o tínheis, é certo, mas faltava-vos ocasião."},
{v:11,t:"Não falo por causa da necessidade, pois aprendi a contentar-me com o que tenho."},
{v:12,t:"Sei viver na pobreza e sei viver na abundância; em tudo e por tudo estou iniciado: a ter fartura e a passar fome, a ter de sobra e a sofrer privação."},
{v:13,t:"Tudo posso naquele que me fortalece."},
{v:14,t:"Fizestes bem, entretanto, em tomar parte na minha tribulação."},
{v:15,t:"Vós bem sabeis, filipenses, que, no princípio da pregação do Evangelho, quando parti da Macedônia, nenhuma Igreja abriu comigo conta de dar e de receber, senão vós somente;"},
{v:16,t:"pois até em Tessalônica me mandastes, por duas vezes, o necessário."},
{v:17,t:"Não que eu busque o donativo; busco, sim, o fruto que abunda em vosso favor."},
{v:18,t:"Tenho tudo, e de sobra; estou plenamente abastecido, desde que recebi de Epafrodito o que enviastes: suave odor, sacrifício aceito, agradável a Deus."},
{v:19,t:"E o meu Deus há de suprir com largueza toda necessidade vossa, segundo a sua riqueza, na glória, em Cristo Jesus."},
{v:20,t:"A Deus, nosso Pai, a glória pelos séculos dos séculos. Amém."},
{s:"Saudações finais"},
{v:21,t:"Saudai todos os santos em Cristo Jesus. Saúdam-vos os irmãos que estão comigo."},
{v:22,t:"Saúdam-vos todos os santos, principalmente os da casa de César.",n:"Entre os servos e funcionários do palácio imperial já havia cristãos. A observação, dita de passagem, mostra o Evangelho instalado no coração do Império."},
{v:23,t:"A graça do Senhor Jesus Cristo esteja com o vosso espírito. Amém."}
];
