// =====================================================================
// Gálatas — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["galatas"][1] = [
{s:"Saudação"},
{v:1,t:"Paulo, apóstolo — não da parte dos homens, nem por meio de homem algum, mas por Jesus Cristo e por Deus Pai, que o ressuscitou dos mortos —,",n:"É a mais veemente das cartas de São Paulo. Escrita talvez pelo ano 54, defende contra os que exigiam a circuncisão dos convertidos que o Evangelho não se acrescenta à lei: substitui-a."},
{v:2,t:"e todos os irmãos que estão comigo, às Igrejas da Galácia:"},
{v:3,t:"graça a vós e paz, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo,"},
{v:4,t:"que se entregou a si mesmo pelos nossos pecados, para nos arrancar deste mundo presente e mau, segundo a vontade de Deus, nosso Pai,"},
{v:5,t:"a quem seja a glória pelos séculos dos séculos. Amém."},
{s:"Não há outro Evangelho"},
{v:6,t:"Admiro-me de que tão depressa vos afasteis daquele que vos chamou pela graça de Cristo, para passardes a outro evangelho."},
{v:7,t:"Não que haja outro; há apenas quem vos perturbe e queira subverter o Evangelho de Cristo."},
{v:8,t:"Mas, ainda que nós mesmos, ou um anjo do céu, vos anuncie um evangelho diferente do que vos anunciamos, seja anátema."},
{v:9,t:"Como já dissemos, e agora repito: se alguém vos anuncia um evangelho diferente do que recebestes, seja anátema."},
{v:10,t:"Porventura busco agora o favor dos homens, ou o de Deus? Ou procuro agradar aos homens? Se ainda quisesse agradar aos homens, não seria servo de Cristo."},
{s:"O Evangelho que Paulo recebeu"},
{v:11,t:"Faço-vos saber, irmãos, que o Evangelho por mim anunciado não é segundo o homem;"},
{v:12,t:"pois não o recebi nem o aprendi de homem algum, mas por revelação de Jesus Cristo."},
{v:13,t:"Ouvistes falar de como outrora me portei no judaísmo: com que excesso perseguia a Igreja de Deus e a devastava,"},
{v:14,t:"e de como progredia no judaísmo mais do que muitos da minha idade e do meu povo, zeloso até o extremo das tradições dos meus pais."},
{v:15,t:"Mas, quando aprouve àquele que me separou desde o seio de minha mãe e me chamou pela sua graça,",np:1},
{v:16,t:"revelar em mim o seu Filho, para que eu o anunciasse entre os gentios, no mesmo instante, sem consultar carne e sangue,"},
{v:17,t:"sem subir a Jerusalém, aos que eram apóstolos antes de mim, parti para a Arábia e voltei depois a Damasco."},
{v:18,t:"Três anos mais tarde, subi a Jerusalém para conhecer Cefas, e fiquei com ele quinze dias."},
{v:19,t:"De outro apóstolo nenhum vi, senão Tiago, o irmão do Senhor."},
{v:20,t:"E, no que vos escrevo, diante de Deus, não minto."},
{v:21,t:"Depois fui para as regiões da Síria e da Cilícia.",np:1},
{v:22,t:"Pessoalmente, porém, era desconhecido das Igrejas da Judeia que estão em Cristo;"},
{v:23,t:"tinham apenas ouvido dizer: Aquele que outrora nos perseguia anuncia agora a fé que antes devastava;"},
{v:24,t:"e glorificavam a Deus por causa de mim."}
];

window.TEXTOS_SEED["galatas"][2] = [
{s:"O acordo de Jerusalém"},
{v:1,t:"Catorze anos depois, subi outra vez a Jerusalém, com Barnabé, levando também Tito comigo."},
{v:2,t:"Subi em virtude de uma revelação, e expus-lhes o Evangelho que prego entre os gentios — em particular, porém, aos mais considerados —, para não correr, ou ter corrido, em vão."},
{v:3,t:"Ora, nem sequer Tito, que estava comigo, sendo grego, foi obrigado a circuncidar-se."},
{v:4,t:"E isso por causa dos falsos irmãos intrusos, que se infiltraram para espiar a liberdade que temos em Cristo Jesus, a fim de nos reduzirem à escravidão."},
{v:5,t:"A esses não cedemos nem por um instante, para que a verdade do Evangelho permanecesse entre vós."},
{v:6,t:"Quanto aos que eram tidos por alguma coisa — o que tenham sido não me importa: Deus não faz acepção de pessoas —, esses, digo, nada me acrescentaram."},
{v:7,t:"Ao contrário, vendo que me fora confiado o Evangelho dos incircuncisos, como a Pedro o dos circuncisos"},
{v:8,t:"— pois aquele que agiu em Pedro para o apostolado dos circuncisos agiu também em mim para o dos gentios —,"},
{v:9,t:"e reconhecendo a graça que me fora dada, Tiago, Cefas e João, tidos por colunas, deram-nos a mão, a mim e a Barnabé, em sinal de comunhão: nós iríamos aos gentios; eles, aos circuncisos."},
{v:10,t:"Pediram-nos apenas que nos lembrássemos dos pobres — o que justamente me esforcei por fazer."},
{s:"Paulo repreende Cefas em Antioquia"},
{v:11,t:"Mas, quando Cefas veio a Antioquia, resisti-lhe face a face, porque era repreensível."},
{v:12,t:"Com efeito, antes de chegarem alguns da parte de Tiago, comia com os gentios; quando chegaram, porém, retraiu-se e apartou-se, com medo dos circuncisos."},
{v:13,t:"E os demais judeus dissimularam com ele, a ponto de o próprio Barnabé se deixar levar pela dissimulação."},
{v:14,t:"Ao ver que não andavam retamente, segundo a verdade do Evangelho, disse a Cefas, diante de todos: Se tu, sendo judeu, vives como os gentios e não como os judeus, como obrigas os gentios a viver como judeus?",n:"O episódio não põe em dúvida o primado de Pedro: discute-lhe a conduta, não a autoridade. Santo Agostinho e São Jerônimo dividiram-se sobre o alcance da repreensão, e a carta guarda ambas as coisas — a firmeza e a comunhão."},
{s:"Justificados pela fé, não pela lei"},
{v:15,t:"Nós, que somos judeus de nascimento e não pecadores vindos dos gentios,"},
{v:16,t:"sabendo que o homem não é justificado pelas obras da lei, mas pela fé em Jesus Cristo, também nós cremos em Cristo Jesus, para sermos justificados pela fé em Cristo e não pelas obras da lei; porque pelas obras da lei ninguém será justificado."},
{v:17,t:"Ora, se, buscando ser justificados em Cristo, fomos também nós achados pecadores, seria então Cristo ministro do pecado? De modo nenhum!"},
{v:18,t:"Pois, se torno a edificar o que destruí, constituo-me a mim mesmo transgressor."},
{v:19,t:"Na verdade, pela lei morri para a lei, a fim de viver para Deus. Estou crucificado com Cristo;"},
{v:20,t:"e já não sou eu que vivo: é Cristo que vive em mim. E a vida que agora vivo na carne, vivo-a na fé no Filho de Deus, que me amou e se entregou por mim."},
{v:21,t:"Não anulo a graça de Deus; porque, se a justiça vem pela lei, então Cristo morreu em vão."}
];

window.TEXTOS_SEED["galatas"][3] = [
{s:"A fé e as obras da lei"},
{v:1,t:"Ó gálatas insensatos! Quem vos enfeitiçou, a vós, diante de cujos olhos foi pintado Jesus Cristo crucificado?"},
{v:2,t:"Só isto quero saber de vós: foi pelas obras da lei que recebestes o Espírito, ou pela pregação da fé?"},
{v:3,t:"Sois tão insensatos que, tendo começado pelo Espírito, acabais agora na carne?"},
{v:4,t:"Foi em vão que passastes por tanta coisa? Se é que foi em vão!"},
{v:5,t:"Aquele que vos dá o Espírito e opera milagres entre vós, fá-lo pelas obras da lei, ou pela pregação da fé?"},
{v:6,t:"Assim também Abraão creu em Deus, e isso lhe foi contado como justiça.",np:1},
{v:7,t:"Reconhecei, pois: os que vivem da fé, esses é que são filhos de Abraão."},
{v:8,t:"E a Escritura, prevendo que Deus justificaria os gentios pela fé, anunciou de antemão a Abraão: Em ti serão abençoadas todas as nações."},
{v:9,t:"Portanto, os que vivem da fé são abençoados com Abraão, o crente."},
{v:10,t:"Com efeito, todos os que se apoiam nas obras da lei estão sob maldição; porque está escrito: Maldito todo aquele que não permanece em tudo o que está escrito no livro da lei, para o cumprir.",np:1},
{v:11,t:"Ora, é evidente que pela lei ninguém é justificado diante de Deus, pois o justo viverá da fé;"},
{v:12,t:"e a lei não se funda na fé, mas: Quem praticar estes preceitos viverá por eles."},
{v:13,t:"Cristo resgatou-nos da maldição da lei, fazendo-se por nós maldição — porque está escrito: Maldito todo aquele que é suspenso no madeiro —,"},
{v:14,t:"para que a bênção de Abraão alcançasse os gentios em Cristo Jesus, e para que recebêssemos, pela fé, a promessa do Espírito."},
{s:"A promessa é anterior à lei"},
{v:15,t:"Irmãos, falo à maneira humana: ninguém anula o testamento de um homem, uma vez ratificado, nem lhe acrescenta cláusula alguma."},
{v:16,t:"Ora, as promessas foram feitas a Abraão e à sua descendência. Não diz: e aos descendentes, como se fossem muitos, mas, como de um só: e à tua descendência — e essa descendência é Cristo."},
{v:17,t:"Quero dizer: um testamento, ratificado por Deus, não é anulado pela lei, vinda quatrocentos e trinta anos depois, de modo a invalidar a promessa."},
{v:18,t:"Porque, se a herança viesse da lei, já não viria da promessa; ora, foi por promessa que Deus a concedeu a Abraão."},
{v:19,t:"Para que serve, então, a lei? Foi acrescentada por causa das transgressões, até que viesse a descendência a quem a promessa fora feita; e foi promulgada por anjos, pela mão de um mediador.",np:1},
{v:20,t:"Ora, não há mediador de um só; e Deus é um só."},
{v:21,t:"Será, então, a lei contrária às promessas de Deus? De modo nenhum! Porque, se tivesse sido dada uma lei capaz de dar a vida, a justiça viria realmente da lei."},
{v:22,t:"Mas a Escritura encerrou tudo sob o pecado, para que a promessa fosse dada aos crentes pela fé em Jesus Cristo."},
{s:"Filhos de Deus pela fé"},
{v:23,t:"Antes que viesse a fé, estávamos guardados sob a lei, encerrados até que a fé se revelasse."},
{v:24,t:"Assim, a lei foi o nosso pedagogo até Cristo, para que fôssemos justificados pela fé.",n:"O pedagogo não era o mestre, mas o escravo que levava o menino à escola e o vigiava pelo caminho. A lei conduz a Cristo e cessa quando ele chega."},
{v:25,t:"Mas, chegada a fé, já não estamos sob um pedagogo."},
{v:26,t:"Porque todos sois filhos de Deus pela fé em Cristo Jesus."},
{v:27,t:"Pois todos vós, que fostes batizados em Cristo, de Cristo vos revestistes."},
{v:28,t:"Já não há judeu nem grego, não há escravo nem livre, não há homem nem mulher: todos vós sois um só em Cristo Jesus."},
{v:29,t:"E, se sois de Cristo, sois então descendência de Abraão, herdeiros segundo a promessa."}
];

window.TEXTOS_SEED["galatas"][4] = [
{s:"De escravos a filhos"},
{v:1,t:"Digo, porém: enquanto o herdeiro é menor, em nada difere do escravo, embora seja senhor de tudo;"},
{v:2,t:"está sob tutores e administradores, até o tempo fixado pelo pai."},
{v:3,t:"Assim também nós: quando éramos menores, estávamos reduzidos à escravidão dos elementos do mundo."},
{v:4,t:"Mas, quando veio a plenitude do tempo, Deus enviou o seu Filho, nascido de mulher, nascido sob a lei,"},
{v:5,t:"para resgatar os que estavam sob a lei, a fim de recebermos a adoção de filhos."},
{v:6,t:"E, porque sois filhos, Deus enviou aos nossos corações o Espírito de seu Filho, que clama: Abba, Pai!"},
{v:7,t:"Portanto, já não és escravo, mas filho; e, se filho, também herdeiro, por graça de Deus."},
{s:"O temor do Apóstolo pelos gálatas"},
{v:8,t:"Outrora, quando não conhecíeis a Deus, servíeis a deuses que na verdade o não são."},
{v:9,t:"Agora, porém, que conheceis a Deus — ou antes, que sois por ele conhecidos —, como voltais outra vez aos elementos fracos e pobres, aos quais quereis servir de novo?"},
{v:10,t:"Observais dias, meses, estações e anos!"},
{v:11,t:"Temo ter trabalhado em vão por vós."},
{v:12,t:"Tornai-vos como eu, irmãos, eu vos peço, pois também eu me tornei como vós. Em nada me ofendestes.",np:1},
{v:13,t:"Sabeis que foi por causa de uma doença que vos anunciei o Evangelho da primeira vez;"},
{v:14,t:"e, embora a minha condição fosse uma provação para vós, não me tratastes com desprezo nem com repugnância: acolhestes-me como um anjo de Deus, como a Cristo Jesus."},
{v:15,t:"Onde está, então, a vossa alegria de outrora? Porque dou-vos testemunho de que, se fosse possível, teríeis arrancado os próprios olhos para mos dar."},
{v:16,t:"Tornei-me acaso vosso inimigo por vos dizer a verdade?"},
{v:17,t:"Esses vos cortejam, mas não com boa intenção: querem apartar-vos de mim, para que sejam eles os cortejados."},
{v:18,t:"Bom é ser cortejado no bem, e sempre, e não apenas quando estou entre vós."},
{v:19,t:"Meus filhinhos, por quem de novo sofro dores de parto, até que Cristo seja formado em vós!"},
{v:20,t:"Bem quisera estar agora convosco e mudar o tom da minha voz, porque não sei o que fazer a vosso respeito."},
{s:"Agar e Sara"},
{v:21,t:"Dizei-me, vós que quereis estar sob a lei: não ouvis a lei?"},
{v:22,t:"Está escrito que Abraão teve dois filhos: um da escrava, outro da livre."},
{v:23,t:"O da escrava nasceu segundo a carne; o da livre, em virtude da promessa."},
{v:24,t:"Há nisso uma alegoria: estas mulheres são as duas alianças. Uma, a do monte Sinai, gera para a escravidão: é Agar.",n:"Alegoria, aqui, não quer dizer que o relato seja fábula. Paulo lê nos fatos antigos a figura do que se cumpre agora, à maneira dos doutores do seu tempo."},
{v:25,t:"Agar é o monte Sinai, na Arábia, e corresponde à Jerusalém de agora, que é escrava com os seus filhos."},
{v:26,t:"Mas a Jerusalém do alto é livre, e essa é a nossa mãe."},
{v:27,l:["Porque está escrito:","Alegra-te, estéril, que não davas à luz;","rompe em gritos de júbilo, tu que não conhecias as dores;","porque são mais numerosos os filhos da abandonada","do que os da que tem marido."]},
{v:28,t:"Vós, irmãos, sois filhos da promessa, à maneira de Isaac.",np:1},
{v:29,t:"Mas, como então o que nascera segundo a carne perseguia o que nascera segundo o Espírito, assim é também agora."},
{v:30,t:"Que diz, porém, a Escritura? Expulsa a escrava e o seu filho; porque o filho da escrava não será herdeiro com o filho da livre."},
{v:31,t:"Portanto, irmãos, não somos filhos da escrava, mas da livre."}
];

window.TEXTOS_SEED["galatas"][5] = [
{s:"A liberdade cristã"},
{v:1,t:"Foi para a liberdade que Cristo nos libertou. Permanecei, pois, firmes, e não vos submetais de novo ao jugo da escravidão."},
{v:2,t:"Eis que eu, Paulo, vos digo: se vos deixardes circuncidar, Cristo de nada vos servirá."},
{v:3,t:"Torno a declarar a todo homem que se deixa circuncidar: fica obrigado a cumprir a lei inteira."},
{v:4,t:"Ficastes separados de Cristo, vós que buscais a justiça na lei; decaístes da graça."},
{v:5,t:"Nós, porém, pelo Espírito, aguardamos da fé a esperança da justiça."},
{v:6,t:"Porque, em Cristo Jesus, nem a circuncisão vale coisa alguma, nem a incircuncisão, mas a fé que age pelo amor."},
{v:7,t:"Corríeis bem; quem vos impediu de obedecer à verdade?",np:1},
{v:8,t:"Essa persuasão não vem daquele que vos chama."},
{v:9,t:"Um pouco de fermento leveda toda a massa."},
{v:10,t:"Eu confio em vós, no Senhor, que não pensareis de outro modo; mas quem vos perturba sofrerá a condenação, seja ele quem for."},
{v:11,t:"Quanto a mim, irmãos, se ainda prego a circuncisão, por que continuo a ser perseguido? Estaria então abolido o escândalo da cruz."},
{v:12,t:"Oxalá se mutilassem de uma vez os que vos andam perturbando!"},
{s:"A liberdade serve ao amor"},
{v:13,t:"Vós, irmãos, fostes chamados à liberdade. Não useis, porém, a liberdade como pretexto para a carne; ao contrário, servi-vos uns aos outros pelo amor."},
{v:14,t:"Porque toda a lei se cumpre numa só palavra: Amarás o teu próximo como a ti mesmo."},
{v:15,t:"Mas, se vos mordeis e vos devorais uns aos outros, tende cuidado: acabareis por vos destruir mutuamente."},
{s:"As obras da carne e o fruto do Espírito"},
{v:16,t:"Digo, pois: caminhai segundo o Espírito, e não satisfareis os desejos da carne."},
{v:17,t:"Porque a carne deseja contra o Espírito, e o Espírito, contra a carne; um se opõe ao outro, de modo que não fazeis o que quereríeis."},
{v:18,t:"Mas, se sois conduzidos pelo Espírito, não estais sob a lei."},
{v:19,t:"Ora, as obras da carne são manifestas: fornicação, impureza, devassidão,"},
{v:20,t:"idolatria, feitiçaria, inimizades, discórdia, ciúme, ira, intrigas, dissensões, facções,"},
{v:21,t:"invejas, bebedeiras, orgias e coisas semelhantes. Previno-vos, como já vos preveni: os que tais coisas praticam não herdarão o Reino de Deus."},
{v:22,t:"O fruto do Espírito, porém, é caridade, alegria, paz, paciência, benignidade, bondade, fidelidade,",np:1},
{v:23,t:"mansidão, domínio de si. Contra tais coisas não há lei."},
{v:24,t:"Os que são de Cristo Jesus crucificaram a carne, com as suas paixões e concupiscências."},
{v:25,t:"Se vivemos pelo Espírito, caminhemos também segundo o Espírito."},
{v:26,t:"Não sejamos ávidos de vanglória, provocando-nos uns aos outros, invejando-nos uns aos outros."}
];

window.TEXTOS_SEED["galatas"][6] = [
{s:"Levai as cargas uns dos outros"},
{v:1,t:"Irmãos, se alguém for surpreendido em alguma falta, vós, que sois espirituais, corrigi-o com espírito de mansidão. E olha por ti mesmo, para que não sejas também tentado."},
{v:2,t:"Levai as cargas uns dos outros, e assim cumprireis a lei de Cristo."},
{v:3,t:"Porque, se alguém julga ser alguma coisa, não sendo nada, engana-se a si mesmo."},
{v:4,t:"Examine cada um a sua própria obra, e então terá motivo de glória em si mesmo, e não em comparação com outro;"},
{v:5,t:"pois cada um levará a sua própria carga."},
{v:6,t:"Quem recebe a instrução da palavra reparta de todos os seus bens com aquele que o instrui."},
{v:7,t:"Não vos enganeis: de Deus ninguém zomba. O que o homem semear, isso colherá.",np:1},
{v:8,t:"Quem semeia na sua carne, da carne colherá corrupção; quem semeia no Espírito, do Espírito colherá a vida eterna."},
{v:9,t:"Não nos cansemos de fazer o bem; porque, se não desfalecermos, a seu tempo colheremos."},
{v:10,t:"Portanto, enquanto temos tempo, façamos o bem a todos, mas principalmente aos que são da família da fé."},
{s:"A cruz, única glória"},
{v:11,t:"Vede com que letras grandes vos escrevo de meu próprio punho.",n:"Paulo toma a pena das mãos do secretário para assinar a carta. As letras grandes traem a mão pouco habituada, e talvez a vista cansada de que se queixa aos gálatas."},
{v:12,t:"Todos os que querem causar boa impressão na carne é que vos obrigam a circuncidar-vos, só para não serem perseguidos por causa da cruz de Cristo."},
{v:13,t:"Porque nem os próprios circuncisos guardam a lei; querem que sejais circuncidados para se gloriarem na vossa carne."},
{v:14,t:"Quanto a mim, longe de mim gloriar-me, a não ser na cruz de nosso Senhor Jesus Cristo, pela qual o mundo está crucificado para mim, e eu, para o mundo."},
{v:15,t:"Porque nem a circuncisão é coisa alguma, nem a incircuncisão, mas a nova criatura."},
{v:16,t:"E sobre todos os que seguirem esta regra, paz e misericórdia, e sobre o Israel de Deus."},
{v:17,t:"De ora em diante, ninguém me moleste; porque trago no meu corpo as marcas de Jesus."},
{v:18,t:"A graça de nosso Senhor Jesus Cristo esteja com o vosso espírito, irmãos. Amém."}
];
