// =====================================================================
// Hebreus — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["hebreus"][1] = [
{s:"Deus falou-nos pelo Filho"},
{v:1,t:"Muitas vezes e de muitos modos falou Deus, outrora, aos pais, pelos profetas;",n:"A carta não traz nome de autor nem saudação inicial, e o seu grego é o mais apurado do Novo Testamento. A tradição juntou-a ao corpo paulino sem nunca resolver a questão de quem a escreveu."},
{v:2,t:"nestes dias, que são os últimos, falou-nos pelo Filho, a quem constituiu herdeiro de todas as coisas e por quem também fez os séculos."},
{v:3,t:"Ele é o resplendor da sua glória e a expressão do seu ser, e sustenta todas as coisas com a sua palavra poderosa. E, depois de realizar a purificação dos pecados, sentou-se à direita da Majestade, nas alturas,"},
{v:4,t:"tornando-se tanto maior que os anjos quanto mais excelente é o nome que herdou."},
{s:"O Filho, superior aos anjos"},
{v:5,l:["Pois a qual dos anjos disse Deus alguma vez:","Tu és meu Filho,","eu hoje te gerei?","E ainda:","Eu serei para ele um pai,","e ele será para mim um filho?"]},
{v:6,l:["E, ao introduzir de novo o Primogênito no mundo, diz:","E adorem-no todos os anjos de Deus."]},
{v:7,l:["Quanto aos anjos, diz:","Ele faz dos seus anjos ventos,","e dos seus ministros, chama de fogo."]},
{v:8,l:["Mas ao Filho:","O teu trono, ó Deus, é pelos séculos dos séculos,","e o cetro da retidão é o cetro do teu reino."]},
{v:9,l:["Amaste a justiça e odiaste a iniquidade;","por isso Deus, o teu Deus, te ungiu","com óleo de exultação, de preferência aos teus companheiros."]},
{v:10,l:["E ainda:","No princípio, Senhor, fundaste a terra,","e os céus são obra das tuas mãos."]},
{v:11,l:["Eles perecerão, mas tu permaneces;","todos envelhecerão como um manto,"]},
{v:12,l:["e como uma capa os enrolarás,","e como um manto serão mudados.","Tu, porém, és o mesmo,","e os teus anos não terão fim."]},
{v:13,l:["E a qual dos anjos disse alguma vez:","Senta-te à minha direita,","até que eu ponha os teus inimigos","por escabelo dos teus pés?"]},
{v:14,t:"Não são todos eles espíritos a serviço, enviados em missão em favor dos que hão de herdar a salvação?",np:1}
];

window.TEXTOS_SEED["hebreus"][2] = [
{s:"Uma salvação tão grande"},
{v:1,t:"Por isso devemos atender com mais cuidado ao que ouvimos, para que não sejamos arrastados para longe."},
{v:2,t:"Porque, se a palavra promulgada por anjos teve força de lei, e toda transgressão e desobediência recebeu justa retribuição,"},
{v:3,t:"como escaparemos nós, se desprezarmos tão grande salvação? Ela, anunciada primeiro pelo Senhor, foi-nos confirmada pelos que o ouviram,"},
{v:4,t:"dando Deus testemunho com sinais, prodígios, milagres variados e dons do Espírito Santo, repartidos segundo a sua vontade."},
{s:"O Filho fez-se semelhante aos irmãos"},
{v:5,t:"Porque não foi a anjos que Deus submeteu o mundo vindouro, de que falamos."},
{v:6,l:["Alguém, em certo lugar, deu este testemunho:","Que é o homem, para que dele te lembres,","ou o filho do homem, para que o visites?"]},
{v:7,l:["Por um pouco o fizeste menor que os anjos;","de glória e de honra o coroaste,"]},
{v:8,t:"e tudo sujeitaste debaixo dos seus pés. Ao sujeitar-lhe todas as coisas, nada deixou que não lhe ficasse sujeito. Ora, presentemente, ainda não vemos que tudo lhe esteja sujeito.",np:1},
{v:9,t:"Vemos, porém, Jesus, que por um pouco foi feito menor que os anjos, coroado de glória e de honra por ter sofrido a morte — para que, pela graça de Deus, experimentasse a morte em favor de todos."},
{v:10,t:"Convinha, com efeito, que aquele por quem e para quem tudo existe, querendo conduzir muitos filhos à glória, levasse à perfeição, pelo sofrimento, o autor da sua salvação."},
{v:11,t:"Porque tanto o que santifica como os que são santificados vêm todos de um só. Por isso não se envergonha de os chamar irmãos,"},
{v:12,l:["quando diz:","Anunciarei o teu nome aos meus irmãos,","no meio da assembleia te louvarei."]},
{v:13,l:["E ainda:","Eu porei nele a minha confiança.","E outra vez:","Eis-me aqui, eu e os filhos que Deus me deu."]},
{v:14,t:"Portanto, como os filhos participam do sangue e da carne, também ele, do mesmo modo, os partilhou, para destruir, pela morte, aquele que tinha o poder da morte — isto é, o diabo —,",np:1},
{v:15,t:"e libertar os que, pelo medo da morte, estavam sujeitos à escravidão a vida inteira."},
{v:16,t:"Porque não é dos anjos que ele se ocupa, mas da descendência de Abraão."},
{v:17,t:"Por isso devia tornar-se em tudo semelhante aos irmãos, para ser um sumo sacerdote misericordioso e fiel no que toca a Deus, a fim de expiar os pecados do povo."},
{v:18,t:"E, porque ele mesmo sofreu e foi provado, pode socorrer os que são provados."}
];

window.TEXTOS_SEED["hebreus"][3] = [
{s:"Jesus e Moisés"},
{v:1,t:"Por isso, irmãos santos, participantes de uma vocação celeste, considerai o apóstolo e sumo sacerdote da nossa fé, Jesus."},
{v:2,t:"Ele é fiel àquele que o constituiu, como também o foi Moisés em toda a sua casa."},
{v:3,t:"Mas foi julgado digno de glória tanto maior que a de Moisés, quanto maior honra tem o construtor do que a casa."},
{v:4,t:"Toda casa, com efeito, é construída por alguém; e aquele que construiu todas as coisas é Deus."},
{v:5,t:"Moisés foi fiel em toda a casa, como servo, para dar testemunho do que havia de ser anunciado;"},
{v:6,t:"Cristo, porém, como filho, à frente da sua casa. E essa casa somos nós, contanto que guardemos a confiança e a esperança de que nos gloriamos."},
{s:"Não endureçais os vossos corações"},
{v:7,l:["Por isso, como diz o Espírito Santo:","Hoje, se ouvirdes a sua voz,"]},
{v:8,l:["não endureçais os vossos corações,","como na revolta, no dia da provação, no deserto,"]},
{v:9,l:["onde os vossos pais me tentaram,","pondo-me à prova, embora vissem as minhas obras"]},
{v:10,l:["durante quarenta anos. Por isso me indignei contra aquela geração","e disse: Eles têm sempre o coração transviado","e não conheceram os meus caminhos."]},
{v:11,l:["Assim jurei na minha ira:","Não entrarão no meu repouso."]},
{v:12,t:"Cuidai, irmãos, que não haja em nenhum de vós um coração mau e incrédulo, que se afaste do Deus vivo.",np:1},
{v:13,t:"Antes, exortai-vos uns aos outros, cada dia, enquanto se pode dizer hoje, para que nenhum de vós se endureça, seduzido pelo pecado."},
{v:14,t:"Porque nos tornamos participantes de Cristo, contanto que mantenhamos firme até o fim a confiança do princípio."},
{v:15,t:"Quando se diz: Hoje, se ouvirdes a sua voz, não endureçais os vossos corações, como na revolta —"},
{v:16,t:"quem foram os que ouviram e se revoltaram? Não foram todos os que saíram do Egito com Moisés?"},
{v:17,t:"E contra quem se indignou Deus durante quarenta anos? Não foi contra os que pecaram, cujos corpos caíram no deserto?"},
{v:18,t:"E a quem jurou que não entrariam no seu repouso, senão aos que foram desobedientes?"},
{v:19,t:"E vemos que não puderam entrar, por causa da incredulidade."}
];

window.TEXTOS_SEED["hebreus"][4] = [
{s:"O repouso prometido"},
{v:1,t:"Temamos, pois, enquanto permanece a promessa de entrar no seu repouso, que algum de vós seja tido por excluído."},
{v:2,t:"Porque também a nós foi anunciada a boa nova, como a eles; mas a palavra que ouviram de nada lhes serviu, por não estar unida à fé nos que a ouviram."},
{v:3,t:"Nós, porém, que cremos, entramos nesse repouso, conforme ele disse: Assim jurei na minha ira: Não entrarão no meu repouso — e isso embora as suas obras estivessem acabadas desde a criação do mundo."},
{v:4,t:"Pois em certo lugar diz, a respeito do sétimo dia: E Deus repousou no sétimo dia de todas as suas obras."},
{v:5,t:"E, no texto citado: Não entrarão no meu repouso."},
{v:6,t:"Como, pois, resta que alguns entrem nele, e aqueles a quem primeiro foi anunciada a boa nova não entraram, por causa da desobediência,",np:1},
{v:7,t:"Deus fixa de novo um dia — hoje —, dizendo por Davi, muito tempo depois, como já se disse: Hoje, se ouvirdes a sua voz, não endureçais os vossos corações."},
{v:8,t:"Porque, se Josué lhes tivesse dado o repouso, Deus não falaria, depois disso, de outro dia."},
{v:9,t:"Resta, portanto, um repouso sabático para o povo de Deus."},
{v:10,t:"Pois quem entra no repouso de Deus também descansa das suas obras, como Deus das suas."},
{v:11,t:"Esforcemo-nos, pois, por entrar nesse repouso, para que ninguém caia, seguindo o mesmo exemplo de desobediência."},
{v:12,t:"Porque a palavra de Deus é viva e eficaz, mais cortante que qualquer espada de dois gumes: penetra até dividir alma e espírito, juntas e medulas, e discerne os pensamentos e as intenções do coração.",np:1},
{v:13,t:"Não há criatura que lhe fique oculta; tudo está nu e descoberto aos olhos daquele a quem havemos de prestar contas."},
{s:"Jesus, o sumo sacerdote compassivo"},
{v:14,t:"Tendo, pois, um grande sumo sacerdote que penetrou os céus, Jesus, o Filho de Deus, permaneçamos firmes na fé que professamos."},
{v:15,t:"Porque não temos um sumo sacerdote incapaz de compadecer-se das nossas fraquezas: ele foi provado em tudo, à nossa semelhança, exceto no pecado."},
{v:16,t:"Acheguemo-nos, pois, com confiança ao trono da graça, para alcançarmos misericórdia e encontrarmos graça, em vista de um socorro oportuno."}
];

window.TEXTOS_SEED["hebreus"][5] = [
{s:"O sumo sacerdote é tomado dentre os homens"},
{v:1,t:"Todo sumo sacerdote, tomado dentre os homens, é constituído em favor dos homens, nas coisas que se referem a Deus, para oferecer dons e sacrifícios pelos pecados."},
{v:2,t:"Pode ser indulgente com os ignorantes e os transviados, porque também ele está rodeado de fraqueza;"},
{v:3,t:"e por isso deve oferecer sacrifícios pelos próprios pecados, como pelos do povo."},
{v:4,t:"Ninguém toma para si esta honra: é preciso ser chamado por Deus, como Aarão."},
{v:5,t:"Assim também Cristo não se atribuiu a glória de ser sumo sacerdote; foi aquele que lhe disse: Tu és meu Filho, eu hoje te gerei;"},
{v:6,t:"como diz ainda em outro lugar: Tu és sacerdote para sempre, segundo a ordem de Melquisedec."},
{v:7,t:"Ele, nos dias da sua carne, dirigiu preces e súplicas, com grande clamor e lágrimas, àquele que podia salvá-lo da morte; e foi atendido, por causa da sua reverência.",np:1},
{v:8,t:"Embora fosse Filho, aprendeu pelo sofrimento a obediência;"},
{v:9,t:"e, levado à perfeição, tornou-se, para todos os que lhe obedecem, causa de salvação eterna,"},
{v:10,t:"proclamado por Deus sumo sacerdote segundo a ordem de Melquisedec."},
{s:"Leite e alimento sólido"},
{v:11,t:"Sobre isso teríamos muito que dizer, e coisas difíceis de explicar, porque vos tornastes lentos para ouvir."},
{v:12,t:"Com efeito, quando já devíeis ser mestres, pelo tempo decorrido, ainda precisais que alguém vos ensine os primeiros rudimentos dos oráculos de Deus; chegastes a precisar de leite, e não de alimento sólido."},
{v:13,t:"Ora, quem se alimenta de leite não está habituado à palavra da justiça, porque é criança."},
{v:14,t:"O alimento sólido é para os adultos, para aqueles que, pelo exercício, têm os sentidos treinados no discernimento do bem e do mal."}
];

window.TEXTOS_SEED["hebreus"][6] = [
{s:"O perigo da apostasia"},
{v:1,t:"Por isso, deixando os rudimentos da doutrina de Cristo, elevemo-nos ao que é perfeito, sem tornar a lançar o fundamento: a conversão das obras mortas, a fé em Deus,"},
{v:2,t:"a doutrina dos batismos e da imposição das mãos, a ressurreição dos mortos e o juízo eterno."},
{v:3,t:"E isso faremos, se Deus o permitir."},
{v:4,t:"Porque é impossível que os que uma vez foram iluminados, que provaram o dom celeste e se tornaram participantes do Espírito Santo,"},
{v:5,t:"que saborearam a boa palavra de Deus e as forças do mundo vindouro,"},
{v:6,t:"e depois caíram, sejam renovados outra vez para a conversão, pois crucificam de novo, por sua conta, o Filho de Deus e o expõem à ignomínia."},
{v:7,t:"A terra que bebe a chuva que muitas vezes cai sobre ela e produz plantas úteis aos que a cultivam recebe a bênção de Deus;",np:1},
{v:8,t:"mas, se produz espinhos e abrolhos, é reprovada e está perto da maldição — e o seu fim é ser queimada."},
{s:"A firmeza da promessa"},
{v:9,t:"Quanto a vós, caríssimos, estamos persuadidos de coisas melhores, que conduzem à salvação, ainda que falemos assim."},
{v:10,t:"Porque Deus não é injusto para esquecer a vossa obra e o amor que mostrastes ao seu nome, servindo aos santos, como ainda servis."},
{v:11,t:"Desejamos, porém, que cada um de vós mostre o mesmo zelo até o fim, para a plena realização da esperança;"},
{v:12,t:"e que não vos torneis indolentes, mas imitadores dos que, pela fé e pela paciência, herdam as promessas."},
{v:13,t:"Quando Deus fez a promessa a Abraão, não tendo por quem maior jurar, jurou por si mesmo,",np:1},
{v:14,t:"dizendo: Sim, hei de abençoar-te com abundância e multiplicar-te sem medida."},
{v:15,t:"E assim, esperando com paciência, Abraão alcançou a promessa."},
{v:16,t:"Os homens juram por alguém maior, e o juramento é, para eles, garantia que põe fim a toda contestação."},
{v:17,t:"Por isso Deus, querendo mostrar com maior evidência aos herdeiros da promessa a imutabilidade do seu desígnio, interpôs o juramento;"},
{v:18,t:"para que, por duas realidades imutáveis, nas quais é impossível que Deus minta, tenhamos poderoso encorajamento nós, que buscamos refúgio agarrando-nos à esperança proposta."},
{v:19,t:"Nela temos como que uma âncora da alma, segura e firme, que penetra além do véu,"},
{v:20,t:"onde Jesus entrou por nós, como precursor, feito sumo sacerdote para sempre, segundo a ordem de Melquisedec."}
];

window.TEXTOS_SEED["hebreus"][7] = [
{s:"Melquisedec"},
{v:1,t:"Este Melquisedec, rei de Salém, sacerdote do Deus altíssimo, saiu ao encontro de Abraão, que voltava da derrota dos reis, e o abençoou."},
{v:2,t:"A ele Abraão deu o dízimo de tudo. O seu nome significa, primeiro, rei de justiça; depois, rei de Salém, isto é, rei de paz."},
{v:3,t:"Sem pai, sem mãe, sem genealogia, sem princípio de dias nem fim de vida, feito semelhante ao Filho de Deus, permanece sacerdote para sempre.",n:"A Escritura nada diz dos pais nem da morte de Melquisedec. O autor lê esse silêncio como figura: o sacerdócio que não começa nem acaba é o de Cristo."},
{v:4,t:"Vede quão grande é aquele a quem o patriarca Abraão deu o dízimo do melhor despojo."},
{v:5,t:"Os filhos de Levi que recebem o sacerdócio têm ordem de cobrar o dízimo do povo, segundo a lei, isto é, de seus irmãos, embora também estes tenham saído dos lombos de Abraão."},
{v:6,t:"Mas aquele que não é da sua linhagem cobrou o dízimo de Abraão e abençoou o que tinha as promessas."},
{v:7,t:"Ora, sem contestação alguma, é o inferior que é abençoado pelo superior."},
{v:8,t:"Além disso, aqui são homens mortais que recebem os dízimos; ali, porém, é aquele de quem se atesta que vive."},
{v:9,t:"E, por assim dizer, até Levi, que recebe os dízimos, pagou o dízimo por meio de Abraão;"},
{v:10,t:"pois estava ainda nos lombos do seu pai quando Melquisedec lhe saiu ao encontro."},
{s:"Um sacerdócio novo"},
{v:11,t:"Ora, se a perfeição se alcançasse pelo sacerdócio levítico — pois sobre ele se fundou a lei dada ao povo —, que necessidade haveria de se levantar outro sacerdote, segundo a ordem de Melquisedec, e não segundo a ordem de Aarão?"},
{v:12,t:"Porque, mudado o sacerdócio, muda-se necessariamente também a lei."},
{v:13,t:"De fato, aquele de quem se diz isso pertence a outra tribo, da qual ninguém serviu ao altar."},
{v:14,t:"É notório que o nosso Senhor procede de Judá, tribo a respeito da qual Moisés nada disse sobre sacerdotes."},
{v:15,t:"E isso se torna mais evidente ainda, se um outro sacerdote se levanta à semelhança de Melquisedec,"},
{v:16,t:"constituído não segundo a lei de uma prescrição carnal, mas segundo o poder de uma vida indestrutível."},
{v:17,t:"Porque está atestado: Tu és sacerdote para sempre, segundo a ordem de Melquisedec."},
{v:18,t:"Assim se anula a prescrição anterior, por causa da sua fraqueza e inutilidade —",np:1},
{v:19,t:"pois a lei nada levou à perfeição —, e se introduz uma esperança melhor, pela qual nos aproximamos de Deus."},
{v:20,t:"E isso não se fez sem juramento. Os outros tornaram-se sacerdotes sem juramento;"},
{v:21,t:"este, porém, com juramento, por aquele que lhe disse: O Senhor jurou e não se arrependerá: Tu és sacerdote para sempre."},
{v:22,t:"Por isso mesmo, Jesus se tornou fiador de uma aliança muito melhor."},
{v:23,t:"Além disso, aqueles sacerdotes foram muitos, porque a morte os impedia de permanecer;",np:1},
{v:24,t:"este, porém, porque permanece para sempre, tem um sacerdócio que não passa a outro."},
{v:25,t:"Por isso pode salvar definitivamente os que por ele se aproximam de Deus, sempre vivo para interceder por eles."},
{v:26,t:"Convinha-nos, de fato, um sumo sacerdote assim: santo, inocente, imaculado, separado dos pecadores e elevado acima dos céus;"},
{v:27,t:"que não precisa, como os sumos sacerdotes, de oferecer cada dia sacrifícios, primeiro pelos próprios pecados e depois pelos do povo — porque isso o fez de uma vez por todas, oferecendo-se a si mesmo."},
{v:28,t:"A lei constitui sumos sacerdotes homens sujeitos à fraqueza; mas a palavra do juramento, posterior à lei, constitui o Filho, levado à perfeição para sempre."}
];

window.TEXTOS_SEED["hebreus"][8] = [
{s:"O ministro do santuário verdadeiro"},
{v:1,t:"O ponto capital do que dizemos é este: temos um sumo sacerdote tal, que se sentou à direita do trono da Majestade, nos céus,"},
{v:2,t:"ministro do santuário e do verdadeiro tabernáculo, erguido pelo Senhor e não por homem algum."},
{v:3,t:"Todo sumo sacerdote é constituído para oferecer dons e sacrifícios; por isso é necessário que também este tenha algo para oferecer."},
{v:4,t:"Se estivesse na terra, nem sequer seria sacerdote, pois já há os que oferecem dons segundo a lei."},
{v:5,t:"Estes servem a um esboço e a uma sombra das realidades celestes, conforme o que foi dito a Moisés, quando ia construir o tabernáculo: Olha, disse Deus, e faze tudo segundo o modelo que te foi mostrado no monte."},
{s:"A aliança nova"},
{v:6,t:"Agora, porém, coube a ele um ministério tanto mais excelente quanto é melhor a aliança de que é mediador, fundada em promessas melhores."},
{v:7,t:"Se a primeira fosse irrepreensível, não haveria lugar para uma segunda."},
{v:8,l:["Porque, repreendendo-os, Deus diz:","Eis que vêm dias, diz o Senhor,","em que firmarei com a casa de Israel","e com a casa de Judá uma aliança nova;"]},
{v:9,l:["não como a aliança que fiz com os seus pais,","no dia em que os tomei pela mão","para os tirar da terra do Egito.","Eles não permaneceram na minha aliança,","e eu me desinteressei deles, diz o Senhor."]},
{v:10,l:["Esta é a aliança que firmarei com a casa de Israel","depois daqueles dias, diz o Senhor:","porei as minhas leis no seu entendimento","e as escreverei no seu coração;","eu serei o seu Deus, e eles serão o meu povo."]},
{v:11,l:["Ninguém mais ensinará o seu concidadão,","nem ninguém ao seu irmão, dizendo: Conhece o Senhor;","porque todos me conhecerão,","do menor ao maior."]},
{v:12,l:["Porque serei clemente com as suas iniquidades","e não me lembrarei mais dos seus pecados."]},
{v:13,t:"Ao dizer nova, tornou velha a primeira; e o que envelhece e se torna antigo está perto de desaparecer.",np:1}
];

window.TEXTOS_SEED["hebreus"][9] = [
{s:"O culto da primeira aliança"},
{v:1,t:"A primeira aliança tinha também prescrições de culto e um santuário terrestre."},
{v:2,t:"Foi armada uma tenda, a primeira, na qual estavam o candelabro, a mesa e os pães da proposição: chama-se o Santo."},
{v:3,t:"Por trás do segundo véu, havia a tenda chamada o Santo dos Santos,"},
{v:4,t:"com o altar de ouro para os perfumes e a arca da aliança, toda revestida de ouro, na qual estavam a urna de ouro com o maná, a vara de Aarão que floresceu e as tábuas da aliança;"},
{v:5,t:"e sobre ela, os querubins da glória, que cobriam com a sua sombra o propiciatório. Disso não é o momento de falar em pormenor."},
{v:6,t:"Assim dispostas as coisas, os sacerdotes entram continuamente na primeira tenda, para cumprir os atos do culto;",np:1},
{v:7,t:"mas, na segunda, só o sumo sacerdote entra, uma vez por ano, e não sem sangue, que oferece pelas faltas cometidas por ignorância, suas e do povo."},
{v:8,t:"Com isso o Espírito Santo dá a entender que o caminho do santuário ainda não estava manifesto, enquanto subsistia a primeira tenda."},
{v:9,t:"Tudo isso é figura do tempo presente: oferecem-se dons e sacrifícios que não podem tornar perfeita, na consciência, a pessoa que presta o culto;"},
{v:10,t:"são apenas prescrições carnais, sobre comidas, bebidas e abluções diversas, impostas até o tempo da reforma."},
{s:"O sangue de Cristo"},
{v:11,t:"Cristo, porém, veio como sumo sacerdote dos bens vindouros, por meio de uma tenda maior e mais perfeita, não feita por mão de homem — isto é, não deste mundo criado —,"},
{v:12,t:"e entrou uma vez por todas no santuário, não com sangue de bodes e de novilhos, mas com o próprio sangue, obtendo uma redenção eterna."},
{v:13,t:"Porque, se o sangue de bodes e de touros e a cinza de uma novilha, aspergidos sobre os contaminados, os santificam para a pureza da carne,"},
{v:14,t:"quanto mais o sangue de Cristo, que, pelo Espírito eterno, se ofereceu a si mesmo, imaculado, a Deus, purificará a nossa consciência das obras mortas, para servirmos ao Deus vivo!"},
{v:15,t:"Por isso é mediador de uma aliança nova: uma vez sobrevinda a morte para remir as transgressões cometidas sob a primeira aliança, os chamados recebem a herança eterna prometida.",np:1},
{v:16,t:"Onde há testamento, é necessário que se verifique a morte do testador."},
{v:17,t:"O testamento só tem valor depois da morte; não entra em vigor enquanto vive o testador."},
{v:18,t:"Por isso nem a primeira aliança foi inaugurada sem sangue."},
{v:19,t:"Moisés, com efeito, depois de promulgar a toda a assembleia todos os preceitos da lei, tomou o sangue dos novilhos e dos bodes, com água, lã escarlate e hissopo, e aspergiu o próprio livro e todo o povo,"},
{v:20,t:"dizendo: Este é o sangue da aliança que Deus prescreveu para vós."},
{v:21,t:"Do mesmo modo aspergiu com sangue o tabernáculo e todos os objetos do culto."},
{v:22,t:"Segundo a lei, quase tudo se purifica com sangue; e sem derramamento de sangue não há remissão."},
{v:23,t:"Era, pois, necessário que as figuras das realidades celestes fossem purificadas desse modo; mas as próprias realidades celestes, por sacrifícios superiores a esses.",np:1},
{v:24,t:"Porque Cristo não entrou num santuário feito por mão de homem, figura do verdadeiro, mas no próprio céu, para comparecer agora, por nós, diante de Deus."},
{v:25,t:"E não para se oferecer muitas vezes, como o sumo sacerdote, que entra cada ano no santuário com sangue alheio;"},
{v:26,t:"do contrário, teria sido necessário que padecesse muitas vezes desde a criação do mundo. Agora, porém, manifestou-se uma só vez, no fim dos tempos, para destruir o pecado pelo sacrifício de si mesmo."},
{v:27,t:"E, assim como aos homens está determinado morrer uma só vez, e depois disso o juízo,"},
{v:28,t:"assim também Cristo, oferecido uma só vez para tirar os pecados de muitos, aparecerá segunda vez, sem relação com o pecado, aos que o esperam para a salvação."}
];

window.TEXTOS_SEED["hebreus"][10] = [
{s:"O sacrifício único e definitivo"},
{v:1,t:"A lei, tendo apenas a sombra dos bens futuros, e não a imagem real das coisas, jamais pode, com os mesmos sacrifícios oferecidos continuamente, ano após ano, levar à perfeição os que se aproximam."},
{v:2,t:"Do contrário, não teriam deixado de ser oferecidos? Pois os que prestam o culto, uma vez purificados, não teriam mais consciência de pecado."},
{v:3,t:"Mas, por esses sacrifícios, faz-se cada ano a memória dos pecados;"},
{v:4,t:"porque é impossível que o sangue de touros e de bodes tire os pecados."},
{v:5,l:["Por isso, ao entrar no mundo, Cristo diz:","Não quiseste sacrifício nem oblação,","mas um corpo me formaste."]},
{v:6,l:["Não te agradaram holocaustos","nem sacrifícios pelo pecado."]},
{v:7,l:["Então eu disse: Eis que venho","— no rolo do livro está escrito a meu respeito —","para fazer, ó Deus, a tua vontade."]},
{v:8,t:"Dizendo primeiro: Sacrifícios e oblações, holocaustos e sacrifícios pelo pecado não quiseste nem te agradaram — coisas que são oferecidas segundo a lei —,",np:1},
{v:9,t:"acrescenta depois: Eis que venho para fazer a tua vontade. Assim suprime o primeiro regime, para estabelecer o segundo."},
{v:10,t:"É por essa vontade que somos santificados, pela oblação do corpo de Jesus Cristo, feita uma vez por todas."},
{v:11,t:"Todo sacerdote está de pé, dia após dia, oferecendo muitas vezes os mesmos sacrifícios, que jamais podem tirar os pecados."},
{v:12,t:"Este, porém, tendo oferecido um único sacrifício pelos pecados, sentou-se para sempre à direita de Deus,"},
{v:13,t:"aguardando que os seus inimigos sejam postos por escabelo dos seus pés."},
{v:14,t:"Porque, com uma só oblação, levou à perfeição para sempre os que são santificados."},
{v:15,t:"E disso nos dá testemunho também o Espírito Santo; pois, depois de dizer:"},
{v:16,t:"Esta é a aliança que firmarei com eles depois daqueles dias, diz o Senhor: porei as minhas leis nos seus corações e as escreverei no seu entendimento —"},
{v:17,t:"acrescenta: E dos seus pecados e das suas iniquidades não me lembrarei mais."},
{v:18,t:"Ora, onde há remissão, já não há oblação pelo pecado."},
{s:"Acheguemo-nos com confiança"},
{v:19,t:"Tendo, pois, irmãos, plena confiança para entrar no santuário, pelo sangue de Jesus,"},
{v:20,t:"por esse caminho novo e vivo que ele nos abriu através do véu — isto é, da sua carne —,"},
{v:21,t:"e tendo um sumo sacerdote à frente da casa de Deus,"},
{v:22,t:"acheguemo-nos com coração sincero, na plenitude da fé, purificados os corações de toda má consciência e lavado o corpo com água pura."},
{v:23,t:"Conservemos inabalável a confissão da nossa esperança, porque fiel é aquele que fez a promessa."},
{v:24,t:"E atentemos uns pelos outros, para nos estimularmos à caridade e às boas obras."},
{v:25,t:"Não abandonemos a nossa assembleia, como alguns têm por costume; ao contrário, animemo-nos mutuamente, e tanto mais quanto vedes aproximar-se o Dia."},
{s:"Não recair"},
{v:26,t:"Porque, se pecamos voluntariamente depois de haver recebido o conhecimento da verdade, já não resta sacrifício pelos pecados,"},
{v:27,t:"mas a terrível expectativa do juízo e o ardor de um fogo que há de devorar os rebeldes."},
{v:28,t:"Quem viola a lei de Moisés morre sem misericórdia, por duas ou três testemunhas."},
{v:29,t:"Quanto pior castigo julgais que merecerá aquele que pisou aos pés o Filho de Deus, teve por profano o sangue da aliança que o santificou e ultrajou o Espírito da graça?"},
{v:30,t:"Conhecemos, com efeito, aquele que disse: A mim pertence a vingança, eu retribuirei; e ainda: O Senhor julgará o seu povo."},
{v:31,t:"É coisa terrível cair nas mãos do Deus vivo."},
{v:32,t:"Lembrai-vos dos primeiros dias, em que, depois de iluminados, suportastes grande combate de sofrimentos:",np:1},
{v:33,t:"ora expostos publicamente a injúrias e tribulações, ora solidários com os que assim eram tratados."},
{v:34,t:"De fato, compadecestes-vos dos encarcerados e aceitastes com alegria o roubo dos vossos bens, sabendo que tendes uma riqueza melhor e permanente."},
{v:35,t:"Não percais, pois, a vossa confiança, à qual está reservada grande recompensa."},
{v:36,t:"Tendes necessidade de constância, para que, cumprindo a vontade de Deus, alcanceis a promessa."},
{v:37,l:["Porque ainda um pouco, bem pouco,","e aquele que há de vir virá, e não tardará."]},
{v:38,l:["O meu justo viverá da fé;","mas, se recuar, a minha alma não se agradará dele."]},
{v:39,t:"Nós, porém, não somos dos que recuam para a perdição, mas dos que têm fé para a salvação da alma.",np:1}
];

window.TEXTOS_SEED["hebreus"][11] = [
{s:"A fé dos antigos"},
{v:1,t:"A fé é a garantia dos bens que se esperam, a prova das realidades que não se veem.",n:"O capítulo percorre a história inteira de Israel como uma procissão de crentes. A palavra pela fé volta dezoito vezes, e cada retorno é um degrau."},
{v:2,t:"Por ela os antigos receberam bom testemunho."},
{v:3,t:"Pela fé compreendemos que os séculos foram formados pela palavra de Deus, de modo que o que se vê não provém do que aparece."},
{v:4,t:"Pela fé Abel ofereceu a Deus um sacrifício melhor que o de Caim; por ela recebeu testemunho de que era justo, pois Deus aprovou as suas ofertas; e por ela, mesmo morto, ainda fala."},
{v:5,t:"Pela fé Henoc foi arrebatado, para não ver a morte, e não foi encontrado, porque Deus o arrebatara. Antes de ser arrebatado, recebeu testemunho de que agradara a Deus."},
{v:6,t:"Ora, sem a fé é impossível agradar-lhe; pois é preciso que aquele que se aproxima de Deus creia que ele existe e que recompensa os que o buscam."},
{v:7,t:"Pela fé Noé, advertido por Deus a respeito do que ainda não se via, tomado de temor religioso, construiu a arca para salvar a sua família; por ela condenou o mundo e se tornou herdeiro da justiça que vem da fé."},
{s:"A fé de Abraão"},
{v:8,t:"Pela fé Abraão, chamado, obedeceu e partiu para uma terra que havia de receber em herança; e partiu sem saber para onde ia."},
{v:9,t:"Pela fé habitou na terra prometida como em terra estranha, morando em tendas, com Isaac e Jacó, coerdeiros da mesma promessa;"},
{v:10,t:"porque esperava a cidade de sólidos fundamentos, cujo arquiteto e construtor é Deus."},
{v:11,t:"Pela fé também Sara recebeu o poder de conceber, apesar da idade avançada, porque teve por fiel aquele que fizera a promessa."},
{v:12,t:"Por isso, de um só homem — e já amortecido — nasceu uma descendência tão numerosa como as estrelas do céu e inumerável como a areia da praia do mar."},
{v:13,t:"Na fé morreram todos estes, sem terem recebido as promessas; viram-nas e saudaram-nas de longe, confessando-se estrangeiros e peregrinos sobre a terra.",np:1},
{v:14,t:"Os que assim falam mostram claramente que buscam uma pátria."},
{v:15,t:"Se pensassem naquela de onde tinham saído, teriam tido tempo de voltar;"},
{v:16,t:"mas aspiravam a uma melhor, isto é, à celeste. Por isso Deus não se envergonha de ser chamado o Deus deles: preparou-lhes uma cidade."},
{v:17,t:"Pela fé Abraão, posto à prova, ofereceu Isaac; e oferecia o filho único aquele que recebera as promessas,",np:1},
{v:18,t:"ao qual fora dito: Em Isaac terás a tua descendência."},
{v:19,t:"Pensava que Deus é poderoso até para ressuscitar dos mortos; e por isso recobrou o filho — e isso é uma figura."},
{s:"Dos patriarcas a Moisés"},
{v:20,t:"Pela fé Isaac abençoou Jacó e Esaú, em vista do futuro."},
{v:21,t:"Pela fé Jacó, ao morrer, abençoou cada um dos filhos de José e adorou, apoiado na extremidade do seu bordão."},
{v:22,t:"Pela fé José, no fim da vida, falou do êxodo dos filhos de Israel e deu instruções acerca dos seus ossos."},
{v:23,t:"Pela fé Moisés, recém-nascido, foi escondido três meses por seus pais, porque viram que a criança era formosa, e não temeram o decreto do rei."},
{v:24,t:"Pela fé Moisés, já crescido, recusou ser chamado filho de uma filha do faraó,"},
{v:25,t:"preferindo ser maltratado com o povo de Deus a gozar por breve tempo do pecado;"},
{v:26,t:"porque tinha por riqueza maior que os tesouros do Egito o opróbrio de Cristo, pois olhava para a recompensa."},
{v:27,t:"Pela fé deixou o Egito, sem temer a ira do rei, e manteve-se firme como quem vê o invisível."},
{v:28,t:"Pela fé celebrou a Páscoa e fez a aspersão do sangue, para que o exterminador não tocasse nos primogênitos."},
{v:29,t:"Pela fé atravessaram o mar Vermelho como por terra seca; e os egípcios, ao tentarem o mesmo, foram engolidos."},
{v:30,t:"Pela fé caíram os muros de Jericó, depois de rodeados durante sete dias."},
{v:31,t:"Pela fé Raab, a prostituta, não pereceu com os incrédulos, porque acolhera em paz os espias."},
{s:"A nuvem das testemunhas"},
{v:32,t:"E que mais direi? O tempo me há de faltar, se eu contar de Gedeão, de Baraque, de Sansão, de Jefté, de Davi, de Samuel e dos profetas."},
{v:33,t:"Pela fé venceram reinos, praticaram a justiça, alcançaram promessas, fecharam a boca de leões,"},
{v:34,t:"apagaram a violência do fogo, escaparam ao fio da espada, sararam das suas fraquezas, tornaram-se fortes na guerra, puseram em fuga exércitos estrangeiros."},
{v:35,t:"Mulheres receberam de volta, pela ressurreição, os seus mortos. Outros foram torturados, recusando a libertação, para alcançarem uma ressurreição melhor."},
{v:36,t:"Outros passaram pela prova das zombarias e dos açoites, e ainda das cadeias e da prisão."},
{v:37,t:"Foram apedrejados, serrados, mortos à espada; andaram errantes, cobertos de peles de ovelha e de cabra, necessitados, oprimidos, maltratados —"},
{v:38,t:"homens de quem o mundo não era digno —, vagando por desertos e montanhas, por covas e cavernas da terra."},
{v:39,t:"E todos estes, embora aprovados pelo testemunho da fé, não receberam o que fora prometido,",np:1},
{v:40,t:"porque Deus dispunha para nós algo melhor, a fim de que não chegassem sem nós à perfeição."}
];

window.TEXTOS_SEED["hebreus"][12] = [
{s:"Correr com os olhos em Jesus"},
{v:1,t:"Por isso, rodeados de tão grande nuvem de testemunhas, deixemos todo peso e o pecado que nos envolve, e corramos com perseverança a prova que nos é proposta,"},
{v:2,t:"fixos os olhos em Jesus, autor e consumador da fé. Em vista da alegria que lhe era proposta, suportou a cruz, sem fazer caso da ignomínia, e está sentado à direita do trono de Deus."},
{v:3,t:"Pensai naquele que suportou tamanha hostilidade dos pecadores contra si, para que não desfaleçais, deixando abater-se a vossa alma."},
{s:"A correção do Pai"},
{v:4,t:"Ainda não resististes até o sangue, no combate contra o pecado."},
{v:5,t:"E esquecestes a exortação que vos é dirigida como a filhos: Meu filho, não desprezes a correção do Senhor, nem desanimes quando por ele fores repreendido;"},
{v:6,t:"porque o Senhor corrige a quem ama, e açoita a todo aquele que recebe por filho."},
{v:7,t:"É para a vossa correção que sofreis. Deus vos trata como filhos; e que filho há que o pai não corrija?"},
{v:8,t:"Se ficásseis sem a correção, de que todos se tornam participantes, seríeis bastardos, e não filhos."},
{v:9,t:"Além disso, tivemos os nossos pais segundo a carne, que nos corrigiam, e os respeitávamos; não nos submeteremos muito mais ao Pai dos espíritos, para vivermos?"},
{v:10,t:"Eles corrigiam-nos por pouco tempo, como lhes parecia; ele, porém, o faz para nosso proveito, a fim de nos tornar participantes da sua santidade."},
{v:11,t:"Toda correção, no momento, não parece motivo de alegria, mas de tristeza; depois, porém, produz um fruto de paz e de justiça nos que por ela foram exercitados."},
{v:12,t:"Por isso, reerguei as mãos cansadas e os joelhos vacilantes,",np:1},
{v:13,t:"e endireitai as veredas para os vossos pés, a fim de que o que é manco não se desloque, mas antes se cure."},
{s:"Não recuseis aquele que fala"},
{v:14,t:"Buscai a paz com todos, e a santificação, sem a qual ninguém verá o Senhor."},
{v:15,t:"Vigiai para que ninguém se prive da graça de Deus; para que nenhuma raiz amarga cresça e cause perturbação, contaminando com isso a muitos;"},
{v:16,t:"para que ninguém seja impuro ou profano, como Esaú, que por um só prato vendeu o seu direito de primogenitura."},
{v:17,t:"Sabeis que depois, querendo herdar a bênção, foi rejeitado, e não encontrou lugar para arrependimento, embora a procurasse com lágrimas."},
{v:18,t:"Não vos aproximastes de uma realidade palpável: fogo ardente, escuridão, trevas, tempestade,",np:1},
{v:19,t:"som de trombeta e voz de palavras, tal que os que a ouviram pediram que não se lhes falasse mais."},
{v:20,t:"Não podiam suportar esta ordem: Até o animal que tocar o monte será apedrejado."},
{v:21,t:"E tão terrível era o espetáculo, que Moisés disse: Estou apavorado e trêmulo."},
{v:22,t:"Vós, porém, vos aproximastes do monte Sião, da cidade do Deus vivo, a Jerusalém celeste, de milhares de anjos em festa,",np:1},
{v:23,t:"da assembleia dos primogênitos inscritos nos céus, de Deus, juiz de todos, dos espíritos dos justos que chegaram à perfeição,"},
{v:24,t:"de Jesus, mediador da aliança nova, e do sangue da aspersão, que fala melhor que o de Abel."},
{v:25,t:"Cuidai de não recusar aquele que fala. Porque, se não escaparam os que recusaram aquele que os advertia na terra, muito menos escaparemos nós, se nos desviarmos daquele que fala dos céus."},
{v:26,t:"A sua voz abalou então a terra; agora, porém, promete: Mais uma vez abalarei não só a terra, mas também o céu."},
{v:27,t:"As palavras mais uma vez indicam a transformação das coisas abaláveis, por serem criadas, para que permaneçam as inabaláveis."},
{v:28,t:"Por isso, recebendo um reino inabalável, guardemos a graça, e por ela prestemos a Deus um culto que lhe seja agradável, com reverência e temor;"},
{v:29,t:"porque o nosso Deus é um fogo devorador."}
];

window.TEXTOS_SEED["hebreus"][13] = [
{s:"Recomendações finais"},
{v:1,t:"Permaneça entre vós o amor fraterno."},
{v:2,t:"Não esqueçais a hospitalidade: por ela alguns, sem o saberem, hospedaram anjos."},
{v:3,t:"Lembrai-vos dos presos, como se estivésseis presos com eles; e dos que são maltratados, pois também vós tendes um corpo."},
{v:4,t:"Seja honrado entre todos o matrimônio, e sem mácula o leito conjugal; porque Deus julgará os impudicos e os adúlteros."},
{v:5,t:"Que a vossa conduta seja sem avareza; contentai-vos com o que tendes, porque ele mesmo disse: Não te deixarei nem te abandonarei."},
{v:6,t:"De modo que podemos dizer com confiança: O Senhor é o meu auxílio, não temerei; que me poderá fazer um homem?"},
{s:"Fora do acampamento"},
{v:7,t:"Lembrai-vos dos vossos guias, que vos anunciaram a palavra de Deus; considerai o fim da sua vida e imitai-lhes a fé."},
{v:8,t:"Jesus Cristo é o mesmo ontem, hoje e pelos séculos."},
{v:9,t:"Não vos deixeis arrastar por doutrinas várias e estranhas; porque é bom que o coração se fortaleça com a graça, e não com alimentos, que de nada aproveitaram aos que os seguiram."},
{v:10,t:"Temos um altar do qual não têm direito de comer os que servem ao tabernáculo."},
{v:11,t:"Porque os corpos dos animais, cujo sangue o sumo sacerdote leva ao santuário pelo pecado, são queimados fora do acampamento."},
{v:12,t:"Por isso também Jesus, para santificar o povo com o próprio sangue, padeceu fora da porta."},
{v:13,t:"Saiamos, pois, a ele, fora do acampamento, levando o seu opróbrio."},
{v:14,t:"Porque não temos aqui cidade permanente: buscamos a futura."},
{v:15,t:"Por ele, pois, ofereçamos a Deus, sem cessar, um sacrifício de louvor, isto é, o fruto dos lábios que confessam o seu nome."},
{v:16,t:"Não esqueçais a beneficência e a partilha, porque é com tais sacrifícios que Deus se agrada."},
{v:17,t:"Obedecei aos vossos guias e sede-lhes submissos, porque velam pelas vossas almas, como quem há de prestar contas; para que o façam com alegria, e não a gemer, o que não vos seria proveitoso."},
{s:"Bênção e despedida"},
{v:18,t:"Orai por nós; porque estamos convencidos de ter boa consciência, querendo em tudo portar-nos bem."},
{v:19,t:"Com maior insistência vos peço que o façais, para que eu vos seja restituído quanto antes."},
{v:20,t:"O Deus da paz, que pelo sangue de uma aliança eterna fez voltar dentre os mortos o grande pastor das ovelhas, nosso Senhor Jesus,"},
{v:21,t:"vos torne aptos para todo bem, a fim de cumprirdes a sua vontade, realizando ele em nós o que lhe é agradável, por Jesus Cristo, a quem seja a glória pelos séculos dos séculos. Amém."},
{v:22,t:"Rogo-vos, irmãos, que aceiteis esta palavra de exortação, pois vos escrevi brevemente."},
{v:23,t:"Sabei que o nosso irmão Timóteo foi posto em liberdade; se ele vier logo, irei ver-vos com ele."},
{v:24,t:"Saudai todos os vossos guias e todos os santos. Saúdam-vos os da Itália."},
{v:25,t:"A graça esteja com todos vós."}
];
