// =====================================================================
// Isaías — tradução do hebraico (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["isaias"][1] = [
{s:"Título do livro"},
{v:1,t:"Visão de Isaías, filho de Amós, que ele teve a respeito de Judá e de Jerusalém, nos dias de Ozias, Joatão, Acaz e Ezequias, reis de Judá.",n:"Isaías exerceu o seu ministério em Jerusalém na segunda metade do século VIII antes de Cristo, mais ou menos entre 740 e 700. O livro reúne os seus oráculos (sobretudo nos capítulos 1–39) e outros de discípulos posteriores, do tempo do exílio na Babilônia (40–55) e da volta a Jerusalém (56–66)."},
{s:"O processo do Senhor contra o seu povo"},
{v:2,l:["Ouvi, ó céus, e escuta, ó terra,","pois o Senhor falou:","Criei filhos e os fiz crescer,","mas eles se revoltaram contra mim."]},
{v:3,l:["O boi conhece o seu dono,","e o jumento, a manjedoura do seu senhor;","mas Israel não conhece,","o meu povo não entende."],np:1},
{v:4,l:["Ai da nação pecadora,","do povo carregado de culpa,","da raça de malfeitores, dos filhos corruptos!","Abandonaram o Senhor,","desprezaram o Santo de Israel,","voltaram-lhe as costas."],np:1,n:"O Santo de Israel: título de Deus característico de Isaías (compare 6,3)."},
{v:5,l:["Por que ainda quereis ser feridos,","persistindo na revolta?","A cabeça inteira está doente,","e o coração inteiro, abatido."],np:1},
{v:6,l:["Da planta do pé até a cabeça","não há nele nada são:","ferimentos, contusões e chagas abertas,","que não foram limpas nem enfaixadas","nem aliviadas com óleo."],np:1},
{v:7,l:["A vossa terra está devastada,","as vossas cidades, queimadas pelo fogo;","o vosso solo, diante dos vossos olhos, estrangeiros o devoram;","é uma desolação, como a destruição feita por estrangeiros."],np:1},
{v:8,l:["A filha de Sião ficou","como uma cabana numa vinha,","como uma choupana num pepinal,","como uma cidade sitiada."],np:1,n:"A filha de Sião: personificação de Jerusalém."},
{v:9,l:["Se o Senhor dos exércitos","não nos tivesse deixado alguns sobreviventes,","seríamos como Sodoma,","semelhantes a Gomorra."],np:1,n:"O Senhor dos exércitos: título frequente em Isaías, que apresenta o Senhor como chefe das hostes celestes. Paulo cita este versículo em Romanos 9,29."},
{s:"O culto que Deus rejeita"},
{v:10,l:["Ouvi a palavra do Senhor,","chefes de Sodoma;","escutai o ensinamento do nosso Deus,","povo de Gomorra."]},
{v:11,l:["De que me serve a multidão dos vossos sacrifícios?","— diz o Senhor.","Estou farto de holocaustos de carneiros","e da gordura de novilhos cevados;","o sangue de touros,","de cordeiros e de bodes não me agrada."],np:1},
{v:12,l:["Quando vindes apresentar-vos diante de mim,","quem vos pediu isso,","que pisásseis os meus átrios?"],np:1},
{v:13,l:["Não continueis a trazer ofertas vãs:","o incenso é para mim uma abominação.","Lua nova, sábado, convocação de assembleias:","não suporto a iniquidade unida à festa."],np:1},
{v:14,l:["As vossas luas novas e as vossas festas, a minha alma as detesta;","tornaram-se um peso para mim,","estou cansado de suportá-las."],np:1},
{v:15,l:["Quando estendeis as mãos,","desvio de vós os meus olhos;","ainda que multipliqueis as orações,","não escuto:","as vossas mãos estão cheias de sangue."],np:1},
{v:16,l:["Lavai-vos, purificai-vos,","tirai da minha vista a maldade das vossas ações,","deixai de fazer o mal,"],np:1},
{v:17,l:["aprendei a fazer o bem:","buscai o direito, socorrei o oprimido,","fazei justiça ao órfão, defendei a causa da viúva."],np:1},
{v:18,l:["Vinde, pois, e discutamos,","diz o Senhor.","Ainda que os vossos pecados sejam como o escarlate,","ficarão brancos como a neve;","ainda que sejam vermelhos como a púrpura,","ficarão como a lã."],np:1},
{v:19,l:["Se quiserdes obedecer,","comereis os bens da terra;"],np:1},
{v:20,l:["mas, se recusardes e vos rebelardes,","sereis devorados pela espada,","pois a boca do Senhor falou."],np:1},
{s:"Lamento e promessa sobre Jerusalém"},
{v:21,l:["Como se tornou prostituta","a cidade fiel!","Ela, que era cheia de direito,","onde habitava a justiça,","agora está cheia de assassinos."],n:"Prostituta: imagem da infidelidade ao Senhor, como em Oseias 2 e Ezequiel 16."},
{v:22,l:["A tua prata se tornou escória,","o teu vinho está misturado com água."],np:1},
{v:23,l:["Os teus chefes são rebeldes","e companheiros de ladrões;","todos amam o suborno","e correm atrás de presentes;","não fazem justiça ao órfão,","e a causa da viúva não chega até eles."],np:1},
{v:24,l:["Por isso, diz o Senhor, o Senhor dos exércitos, o Poderoso de Israel:","Ai! Vou desafogar-me dos meus adversários","e vingar-me dos meus inimigos."],np:1},
{v:25,l:["Voltarei a minha mão contra ti,","limparei a tua escória como com potassa","e removerei todas as tuas impurezas."],np:1},
{v:26,l:["Restituirei os teus juízes como eram antes","e os teus conselheiros como no princípio;","depois disso serás chamada Cidade da Justiça, Cidade Fiel."],np:1},
{v:27,l:["Sião será resgatada pelo direito,","e os que nela se converterem, pela justiça."],np:1},
{v:28,l:["Mas os rebeldes e os pecadores serão destruídos juntos,","e os que abandonam o Senhor perecerão."],np:1},
{v:29,l:["Sim, sereis envergonhados por causa dos terebintos que amastes","e corareis por causa dos jardins que escolhestes."],np:1,n:"Árvores e jardins sagrados dos cultos idolátricos da fertilidade."},
{v:30,l:["Pois sereis como o terebinto de folhas murchas","e como um jardim sem água."],np:1},
{v:31,l:["O poderoso se tornará estopa,","e a sua obra, uma faísca;","os dois arderão juntos,","e não haverá quem apague o fogo."],np:1}
];

window.TEXTOS_SEED["isaias"][2] = [
{s:"O monte da casa do Senhor"},
{v:1,t:"Palavra que Isaías, filho de Amós, recebeu em visão a respeito de Judá e de Jerusalém."},
{v:2,l:["Nos últimos dias acontecerá","que o monte da casa do Senhor","estará firme no cume dos montes","e se elevará acima das colinas;","e todas as nações afluirão para ele."],np:1,n:"Um oráculo quase idêntico se encontra em Miqueias 4,1–3."},
{v:3,l:["Muitos povos virão e dirão:","Vinde, subamos ao monte do Senhor,","à casa do Deus de Jacó,","para que ele nos ensine os seus caminhos","e andemos pelas suas veredas.","Pois de Sião sairá a instrução,","e de Jerusalém, a palavra do Senhor."],np:1},
{v:4,l:["Ele julgará entre as nações","e será o árbitro de povos numerosos.","Das suas espadas forjarão arados,","e das suas lanças, foices.","Uma nação não levantará a espada contra outra,","e não se prepararão mais para a guerra."],np:1},
{v:5,l:["Casa de Jacó, vinde,","andemos na luz do Senhor!"],np:1},
{s:"O dia do Senhor"},
{v:6,l:["Rejeitaste o teu povo, a casa de Jacó,","porque estão cheios de adivinhos do Oriente","e de feiticeiros, como os filisteus,","e fazem acordos com estrangeiros."]},
{v:7,l:["A sua terra está cheia de prata e de ouro,","e os seus tesouros não têm fim;"],np:1},
{v:8,l:["a sua terra está cheia de cavalos,","e os seus carros são inumeráveis;","a sua terra está cheia de ídolos:","adoram a obra das suas mãos,","aquilo que os seus dedos fizeram."],np:1,n:"A Nova Vulgata põe neste versículo a menção dos cavalos e dos carros, que o hebraico traz no versículo 7."},
{v:9,l:["O homem se curva,","o mortal se humilha:","não os perdoes!"],np:1,n:"Hebraico de sentido discutido; a Nova Vulgata entende, como aqui: não os perdoes."},
{v:10,l:["Entra na rocha, esconde-te no pó,","diante do terror do Senhor","e do esplendor da sua majestade."],np:1},
{v:11,l:["Os olhos altivos do homem serão abaixados,","e a arrogância dos mortais será humilhada;","só o Senhor será exaltado naquele dia."],np:1},
{v:12,l:["Pois o Senhor dos exércitos tem um dia","contra todo soberbo e altivo,","contra todo arrogante, para que seja abatido;"],np:1},
{v:13,l:["contra todos os cedros do Líbano, altos e elevados,","e contra todos os carvalhos de Basã;"],np:1},
{v:14,l:["contra todos os montes altos","e contra todas as colinas elevadas;"],np:1},
{v:15,l:["contra toda torre alta","e contra toda muralha fortificada;"],np:1},
{v:16,l:["contra todos os navios de Társis","e contra todas as embarcações preciosas."],np:1,n:"Navios de Társis: os grandes navios de longo curso."},
{v:17,l:["A altivez do homem será abatida,","e a arrogância dos mortais será humilhada;","só o Senhor será exaltado naquele dia,"],np:1},
{v:18,l:["e os ídolos desaparecerão por completo."],np:1},
{v:19,l:["Os homens entrarão nas cavernas das rochas","e nos buracos da terra,","diante do terror do Senhor","e do esplendor da sua majestade,","quando ele se levantar para fazer tremer a terra."],np:1},
{v:20,t:"Naquele dia, o homem lançará às toupeiras e aos morcegos os ídolos de prata e os ídolos de ouro que tinha feito para adorar,",np:1},
{v:21,t:"e entrará nas fendas das rochas e nas cavidades dos penhascos, diante do terror do Senhor e do esplendor da sua majestade, quando ele se levantar para fazer tremer a terra."},
{v:22,t:"Deixai, pois, de confiar no homem, que tem apenas um sopro nas narinas: que valor tem ele?",n:"Este versículo falta na antiga tradução grega."}
];

window.TEXTOS_SEED["isaias"][3] = [
{s:"A anarquia em Jerusalém"},
{v:1,l:["Eis que o Senhor, o Senhor dos exércitos,","tira de Jerusalém e de Judá o apoio e o sustento,","todo sustento de pão e todo sustento de água:"]},
{v:2,l:["o valente e o guerreiro,","o juiz e o profeta, o adivinho e o ancião,"],np:1},
{v:3,l:["o chefe de cinquenta e o homem de prestígio,","o conselheiro, o mago hábil","e o perito em encantamentos."],np:1},
{v:4,l:["Eu lhes darei meninos por chefes,","e crianças os governarão."],np:1},
{v:5,l:["O povo se oprimirá uns aos outros,","cada um ao seu próximo;","o jovem se levantará contra o ancião,","e o desprezível, contra o nobre."],np:1},
{v:6,l:["Quando alguém agarrar o seu irmão","na casa do seu pai, dizendo:","Tu tens um manto,","sê o nosso chefe","e toma conta destas ruínas,"],np:1},
{v:7,l:["naquele dia ele protestará:","Não sou médico,","e na minha casa não há pão nem manto;","não me façais chefe do povo."],np:1},
{v:8,l:["Jerusalém tropeçou, e Judá caiu,","porque as suas palavras e as suas obras são contra o Senhor,","afrontando os olhos da sua glória."],np:1},
{v:9,l:["A expressão do seu rosto testemunha contra eles;","como Sodoma, eles proclamam o seu pecado","e não o escondem.","Ai deles,","pois fazem mal a si mesmos!"],np:1},
{v:10,l:["Dizei ao justo que tudo lhe irá bem,","pois comerá o fruto das suas obras."],np:1},
{v:11,l:["Ai do ímpio! Tudo lhe irá mal,","pois receberá o que as suas mãos fizeram."],np:1},
{v:12,l:["O meu povo é oprimido por uma criança,","e mulheres o governam.","Povo meu, os teus guias te enganam","e confundem o caminho que deves seguir."],np:1},
{v:13,l:["O Senhor se levanta para acusar,","está de pé para julgar os povos."],np:1},
{v:14,l:["O Senhor entra em julgamento","com os anciãos do seu povo e os seus chefes:","Fostes vós que devorastes a vinha;","o despojo do pobre está nas vossas casas."],np:1,n:"A vinha é o povo de Deus (compare 5,1–7)."},
{v:15,l:["Com que direito esmagais o meu povo","e moeis o rosto dos pobres?","— oráculo do Senhor Deus dos exércitos."],np:1},
{s:"As mulheres de Sião"},
{v:16,l:["O Senhor disse:","Porque as filhas de Sião são altivas","e andam de pescoço esticado,","lançando olhares provocantes,","caminham a passos miúdos","e fazem tilintar os enfeites dos pés,"]},
{v:17,l:["o Senhor cobrirá de sarna o alto da cabeça das filhas de Sião,","e o Senhor lhes desnudará as partes íntimas."],np:1,n:"Nota do tradutor: o sentido do hebraico pot é discutido; muitos entendem as partes íntimas, outros a fronte, e a Nova Vulgata entende que lhes serão raspados os cabelos. É a humilhação reservada às prisioneiras de guerra, e o texto não a atenua."},
{v:18,l:["Naquele dia, o Senhor tirará o luxo","das tornozeleiras, das tiaras e das luazinhas,"],np:1,n:"Vários termos desta lista (vv. 18–23) são raros e de sentido incerto."},
{v:19,l:["dos brincos, das pulseiras e dos véus,"],np:1},
{v:20,l:["dos enfeites de cabeça e das correntinhas dos pés,","das faixas, dos frascos de perfume e dos amuletos,"],np:1},
{v:21,l:["dos anéis e das argolas do nariz,"],np:1},
{v:22,l:["dos vestidos de festa e dos mantos,","dos xales e das bolsas,"],np:1},
{v:23,l:["dos espelhos e das roupas de linho,","dos turbantes e das mantilhas."],np:1},
{v:24,l:["Em vez de perfume haverá mau cheiro;","em vez de cinto, uma corda;","em vez de cabelos bem penteados, a calvície;","em vez de vestido rico, um saco apertado;","e uma marca de fogo em vez de beleza."],np:1},
{v:25,l:["Os teus homens cairão pela espada,","e os teus valentes, na guerra."],np:1},
{v:26,l:["As portas da cidade gemerão e ficarão de luto;","devastada, ela se sentará no chão."],np:1}
];

window.TEXTOS_SEED["isaias"][4] = [
{s:"Sete mulheres por um homem"},
{v:1,l:["Naquele dia, sete mulheres","agarrarão um só homem, dizendo:","Comeremos o nosso próprio pão","e vestiremos as nossas próprias roupas;","basta que sejamos chamadas pelo teu nome:","tira de nós a nossa vergonha."],n:"Com a morte dos homens na guerra (3,25), as mulheres buscarão um marido para escapar à vergonha de ficar sem filhos."},
{s:"O rebento do Senhor"},
{v:2,l:["Naquele dia, o rebento do Senhor","será esplendor e glória,","e o fruto da terra será orgulho e ornamento","para os sobreviventes de Israel."],n:"O rebento do Senhor: a vegetação que o Senhor fará brotar na terra renovada; a tradição cristã leu aqui também um anúncio do Messias (compare Jeremias 23,5; Zacarias 3,8)."},
{v:3,l:["Então, o que restar em Sião","e o que sobrar em Jerusalém será chamado santo:","todos os que estão inscritos para a vida em Jerusalém,"],np:1},
{v:4,l:["quando o Senhor tiver lavado a imundície das filhas de Sião","e limpado de Jerusalém o sangue derramado","com o espírito de julgamento e o espírito de fogo."],np:1},
{v:5,l:["Então o Senhor criará, sobre todo o espaço do monte Sião","e sobre as suas assembleias,","uma nuvem de dia","e, de noite, fumaça e o brilho de um fogo flamejante.","Pois sobre toda a glória haverá uma cobertura,"],np:1,n:"Como a nuvem e o fogo que guiavam Israel no deserto (Êxodo 13,21–22)."},
{v:6,l:["e uma tenda servirá de sombra durante o dia contra o calor,","e de refúgio e abrigo contra a tempestade e a chuva."],np:1}
];

window.TEXTOS_SEED["isaias"][5] = [
{s:"O cântico da vinha"},
{v:1,l:["Vou cantar ao meu amigo","o cântico do meu amado sobre a sua vinha.","O meu amigo tinha uma vinha","numa colina fértil."],n:"Canção de amor que se transforma em parábola: a vinha é Israel (v. 7). Compare Mateus 21,33–41."},
{v:2,l:["Ele a cavou e tirou as pedras","e plantou nela videiras escolhidas;","construiu no meio dela uma torre","e cavou nela também um lagar.","Esperava que desse uvas boas,","mas ela deu uvas azedas."],np:1},
{v:3,l:["E agora, habitantes de Jerusalém","e homens de Judá,","julgai entre mim e a minha vinha."],np:1},
{v:4,l:["Que mais poderia eu ter feito pela minha vinha","que não tenha feito?","Por que, quando eu esperava que desse uvas boas,","ela deu uvas azedas?"],np:1},
{v:5,l:["Pois agora vou dizer-vos","o que farei com a minha vinha:","arrancarei a sua sebe,","e ela será devastada;","derrubarei o seu muro,","e ela será pisada."],np:1},
{v:6,l:["Farei dela um terreno abandonado:","não será podada nem cavada,","e nela crescerão espinhos e sarças;","e darei ordem às nuvens","para não mandarem chuva sobre ela."],np:1},
{v:7,l:["Pois a vinha do Senhor dos exércitos é a casa de Israel,","e os homens de Judá são a plantação que ele amava.","Esperava o direito, e eis o derramamento de sangue;","esperava a justiça, e eis o grito de socorro."],np:1,n:"No hebraico há um jogo de palavras: mishpat (direito) e mispah (derramamento de sangue), tsedaqah (justiça) e tseaqah (grito)."},
{s:"Ai dos injustos"},
{v:8,l:["Ai dos que juntam casa com casa","e emendam campo com campo,","até não sobrar espaço,","e habitam sozinhos no meio da terra!"]},
{v:9,l:["Aos meus ouvidos o Senhor dos exércitos jurou:","Muitas casas ficarão desertas,","casas grandes e belas, sem moradores."],np:1},
{v:10,l:["Pois dez jeiras de vinha produzirão só um bat,","e um hômer de semente produzirá só um efá."],np:1,n:"O bat é uma medida de líquidos, de uns vinte litros; o efá é a décima parte do hômer. A colheita renderá uma décima parte da semente."},
{v:11,l:["Ai dos que se levantam de madrugada","para correr atrás da bebida","e ficam até tarde da noite","inflamados pelo vinho!"],np:1},
{v:12,l:["Cítara e harpa,","tamborim e flauta","e vinho animam os seus banquetes,","mas não olham para a obra do Senhor","nem veem o que as suas mãos fazem."],np:1},
{v:13,l:["Por isso o meu povo vai para o exílio,","por falta de conhecimento;","os seus nobres morrem de fome,","e a sua multidão fica seca de sede."],np:1},
{v:14,l:["Por isso a morada dos mortos alargou a garganta","e abriu a boca sem medida;","para lá descem a nobreza e a multidão de Jerusalém,","o seu tumulto e a sua alegria."],np:1},
{v:15,l:["O homem será curvado, o mortal será humilhado,","e os olhos dos altivos serão abaixados;"],np:1},
{v:16,l:["mas o Senhor dos exércitos será exaltado no julgamento,","e o Deus santo mostrará a sua santidade na justiça."],np:1},
{v:17,l:["Os cordeiros pastarão ali como nas suas pastagens,","e estrangeiros comerão nas ruínas dos ricos."],np:1},
{v:18,l:["Ai dos que arrastam a iniquidade com cordas de mentira","e o pecado como com tirantes de carroça!"],np:1},
{v:19,l:["Eles dizem: Que ele se apresse,","que acelere a sua obra, para que a vejamos!","Que se aproxime e se cumpra o plano do Santo de Israel,","para que o conheçamos!"],np:1},
{v:20,l:["Ai dos que chamam ao mal bem e ao bem mal,","que fazem das trevas luz e da luz trevas,","que fazem do amargo doce e do doce amargo!"],np:1},
{v:21,l:["Ai dos que são sábios aos próprios olhos","e inteligentes na própria opinião!"],np:1},
{v:22,l:["Ai dos que são valentes para beber vinho","e fortes para misturar bebidas,"],np:1},
{v:23,l:["que absolvem o culpado por suborno","e negam ao justo o seu direito!"],np:1},
{v:24,l:["Por isso, como a língua de fogo devora a palha","e o feno se desfaz na chama,","assim a sua raiz apodrecerá","e a sua flor se desfará como pó;","pois rejeitaram a lei do Senhor dos exércitos","e desprezaram a palavra do Santo de Israel."],np:1},
{s:"A ira do Senhor e a invasão"},
{v:25,l:["Por isso a ira do Senhor se inflamou contra o seu povo;","ele estendeu a mão contra ele e o feriu;","os montes estremeceram,","e os seus cadáveres ficaram como lixo no meio das ruas.","Com tudo isso, a sua ira não se aplacou,","e a sua mão continua estendida."],n:"Refrão que volta em 9,11.16.20 e 10,4."},
{v:26,l:["Ele erguerá um estandarte para as nações distantes","e assobiará chamando uma delas desde os confins da terra;","e eis que ela vem, rápida e veloz."],np:1},
{v:27,l:["Ninguém nela está cansado ou tropeça,","ninguém cochila nem dorme;","não se solta o cinto dos seus rins,","nem se rompe a correia das suas sandálias."],np:1},
{v:28,l:["As suas flechas são afiadas,","e todos os seus arcos estão retesados;","os cascos dos seus cavalos parecem de pedra,","e as rodas dos seus carros, um furacão."],np:1},
{v:29,l:["O seu rugido é como o do leão;","ruge como os leõezinhos,","rosna e agarra a presa,","leva-a embora, e ninguém a pode livrar."],np:1},
{v:30,l:["Naquele dia rugirá contra ele","como o rugido do mar.","Olhará para a terra: eis trevas e angústia,","e a luz se escurece nas nuvens."],np:1}
];

window.TEXTOS_SEED["isaias"][6] = [
{s:"A vocação de Isaías"},
{v:1,t:"No ano da morte do rei Ozias, vi o Senhor sentado num trono alto e elevado; a orla do seu manto enchia o templo.",n:"O rei Ozias morreu por volta de 740 antes de Cristo."},
{v:2,t:"Serafins estavam de pé acima dele; cada um tinha seis asas: com duas cobria o rosto, com duas cobria os pés e com duas voava.",n:"Serafins: seres celestes; o nome evoca a ideia de fogo."},
{v:3,l:["E clamavam um para o outro:","Santo, santo, santo é o Senhor dos exércitos;","toda a terra está cheia da sua glória."],n:"Aclamação que a liturgia retoma no Santo da missa."},
{v:4,t:"Os batentes das portas estremeceram com a voz dos que clamavam, e o templo se encheu de fumaça.",np:1},
{v:5,l:["Então eu disse:","Ai de mim, estou perdido!","Pois sou um homem de lábios impuros","e habito no meio de um povo de lábios impuros,","e os meus olhos viram o Rei, o Senhor dos exércitos."],np:1},
{v:6,t:"Um dos serafins voou até mim, trazendo na mão uma brasa que tinha tirado do altar com uma tenaz;",np:1},
{v:7,l:["tocou com ela a minha boca e disse:","Eis que isto tocou os teus lábios:","a tua culpa foi tirada,","e o teu pecado, perdoado."]},
{v:8,t:"Então ouvi a voz do Senhor, que dizia: Quem enviarei? Quem irá por nós? Eu respondi: Eis-me aqui, envia-me.",np:1},
{v:9,l:["Ele disse: Vai e dize a este povo:","Ouvi, ouvi, e não entendais;","vede, vede, e não compreendais."]},
{v:10,l:["Torna insensível o coração deste povo,","endurece-lhe os ouvidos","e fecha-lhe os olhos,","para que não veja com os olhos","nem ouça com os ouvidos,","nem entenda com o coração,","e não se converta e seja curado."],np:1,n:"Nota do tradutor: o profeta exprime em forma de ordem o resultado da sua pregação: quanto mais ele fala, mais o povo se endurece. Jesus cita estas palavras a propósito das parábolas (Mateus 13,14–15), e Paulo no fim dos Atos (Atos 28,26–27)."},
{v:11,l:["Eu perguntei: Até quando, Senhor?","Ele respondeu:","Até que as cidades fiquem arruinadas,","sem habitantes,","as casas sem ninguém,","e a terra, reduzida a um deserto."],np:1},
{v:12,l:["O Senhor levará para longe os homens,","e será grande o abandono no meio da terra."],np:1},
{v:13,l:["E, se ainda restar nela um décimo,","também ele será destruído,","como o terebinto e o carvalho,","dos quais, depois de cortados, fica o toco.","O toco é uma semente santa."],np:1,n:"A última frase falta na antiga tradução grega. Ela anuncia que do resto sobrevivente Deus fará brotar um povo santo."}
];
