// =====================================================================
// Isaías — tradução do hebraico (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["isaias"][1] = [
{s:"Título do livro"},
{v:1,t:"Visão de Isaías, filho de Amós, que ele teve a respeito de Judá e de Jerusalém, nos dias de Ozias, Joatão, Acaz e Ezequias, reis de Judá.",n:"Isaías exerceu o seu ministério em Jerusalém na segunda metade do século VIII antes de Cristo, mais ou menos entre 740 e 700. O livro reúne os seus oráculos (sobretudo nos capítulos 1–39) e outros de discípulos posteriores, do tempo do exílio na Babilônia (40–55) e da volta a Jerusalém (56–66)."},
{s:"O processo do Senhor contra o seu povo"},
{v:2,l:["Ouvi, ó céus, e escuta, ó terra,","pois o Senhor falou:","Criei filhos e os fiz crescer,","mas eles se revoltaram contra mim."]},
{v:3,l:["O boi conhece o seu dono,","e o jumento, a manjedoura do seu senhor;","mas Israel não conhece,","o meu povo não entende."],np:1},
{v:4,l:["Ai da nação pecadora,","do povo carregado de culpa,","da raça de malfeitores, dos filhos corruptos!","Abandonaram o Senhor,","desprezaram o Santo de Israel,","voltaram-lhe as costas."],np:1,n:"O Santo de Israel: título de Deus característico de Isaías (compare 6,3)."},
{v:5,l:["Por que ainda quereis ser feridos,","persistindo na revolta?","A cabeça inteira está doente,","e o coração inteiro, abatido."],np:1},
{v:6,l:["Da planta do pé até a cabeça","não há nele nada são:","ferimentos, contusões e chagas abertas,","que não foram limpas nem enfaixadas","nem aliviadas com óleo."],np:1},
{v:7,l:["A vossa terra está devastada,","as vossas cidades, queimadas pelo fogo;","o vosso solo, diante dos vossos olhos, estrangeiros o devoram;","é uma desolação, como a destruição feita por estrangeiros."],np:1},
{v:8,l:["A filha de Sião ficou","como uma cabana numa vinha,","como uma choupana num pepinal,","como uma cidade sitiada."],np:1,n:"A filha de Sião: personificação de Jerusalém."},
{v:9,l:["Se o Senhor dos exércitos","não nos tivesse deixado alguns sobreviventes,","seríamos como Sodoma,","semelhantes a Gomorra."],np:1,n:"O Senhor dos exércitos: título frequente em Isaías, que apresenta o Senhor como chefe das hostes celestes. Paulo cita este versículo em Romanos 9,29."},
{s:"O culto que Deus rejeita"},
{v:10,l:["Ouvi a palavra do Senhor,","chefes de Sodoma;","escutai o ensinamento do nosso Deus,","povo de Gomorra."]},
{v:11,l:["De que me serve a multidão dos vossos sacrifícios?","— diz o Senhor.","Estou farto de holocaustos de carneiros","e da gordura de novilhos cevados;","o sangue de touros,","de cordeiros e de bodes não me agrada."],np:1},
{v:12,l:["Quando vindes apresentar-vos diante de mim,","quem vos pediu isso,","que pisásseis os meus átrios?"],np:1},
{v:13,l:["Não continueis a trazer ofertas vãs:","o incenso é para mim uma abominação.","Lua nova, sábado, convocação de assembleias:","não suporto a iniquidade unida à festa."],np:1},
{v:14,l:["As vossas luas novas e as vossas festas, a minha alma as detesta;","tornaram-se um peso para mim,","estou cansado de suportá-las."],np:1},
{v:15,l:["Quando estendeis as mãos,","desvio de vós os meus olhos;","ainda que multipliqueis as orações,","não escuto:","as vossas mãos estão cheias de sangue."],np:1},
{v:16,l:["Lavai-vos, purificai-vos,","tirai da minha vista a maldade das vossas ações,","deixai de fazer o mal,"],np:1},
{v:17,l:["aprendei a fazer o bem:","buscai o direito, socorrei o oprimido,","fazei justiça ao órfão, defendei a causa da viúva."],np:1},
{v:18,l:["Vinde, pois, e discutamos,","diz o Senhor.","Ainda que os vossos pecados sejam como o escarlate,","ficarão brancos como a neve;","ainda que sejam vermelhos como a púrpura,","ficarão como a lã."],np:1},
{v:19,l:["Se quiserdes obedecer,","comereis os bens da terra;"],np:1},
{v:20,l:["mas, se recusardes e vos rebelardes,","sereis devorados pela espada,","pois a boca do Senhor falou."],np:1},
{s:"Lamento e promessa sobre Jerusalém"},
{v:21,l:["Como se tornou prostituta","a cidade fiel!","Ela, que era cheia de direito,","onde habitava a justiça,","agora está cheia de assassinos."],n:"Prostituta: imagem da infidelidade ao Senhor, como em Oseias 2 e Ezequiel 16."},
{v:22,l:["A tua prata se tornou escória,","o teu vinho está misturado com água."],np:1},
{v:23,l:["Os teus chefes são rebeldes","e companheiros de ladrões;","todos amam o suborno","e correm atrás de presentes;","não fazem justiça ao órfão,","e a causa da viúva não chega até eles."],np:1},
{v:24,l:["Por isso, diz o Senhor, o Senhor dos exércitos, o Poderoso de Israel:","Ai! Vou desafogar-me dos meus adversários","e vingar-me dos meus inimigos."],np:1},
{v:25,l:["Voltarei a minha mão contra ti,","limparei a tua escória como com potassa","e removerei todas as tuas impurezas."],np:1},
{v:26,l:["Restituirei os teus juízes como eram antes","e os teus conselheiros como no princípio;","depois disso serás chamada Cidade da Justiça, Cidade Fiel."],np:1},
{v:27,l:["Sião será resgatada pelo direito,","e os que nela se converterem, pela justiça."],np:1},
{v:28,l:["Mas os rebeldes e os pecadores serão destruídos juntos,","e os que abandonam o Senhor perecerão."],np:1},
{v:29,l:["Sim, sereis envergonhados por causa dos terebintos que amastes","e corareis por causa dos jardins que escolhestes."],np:1,n:"Árvores e jardins sagrados dos cultos idolátricos da fertilidade."},
{v:30,l:["Pois sereis como o terebinto de folhas murchas","e como um jardim sem água."],np:1},
{v:31,l:["O poderoso se tornará estopa,","e a sua obra, uma faísca;","os dois arderão juntos,","e não haverá quem apague o fogo."],np:1}
];

window.TEXTOS_SEED["isaias"][2] = [
{s:"O monte da casa do Senhor"},
{v:1,t:"Palavra que Isaías, filho de Amós, recebeu em visão a respeito de Judá e de Jerusalém."},
{v:2,l:["Nos últimos dias acontecerá","que o monte da casa do Senhor","estará firme no cume dos montes","e se elevará acima das colinas;","e todas as nações afluirão para ele."],np:1,n:"Um oráculo quase idêntico se encontra em Miqueias 4,1–3."},
{v:3,l:["Muitos povos virão e dirão:","Vinde, subamos ao monte do Senhor,","à casa do Deus de Jacó,","para que ele nos ensine os seus caminhos","e andemos pelas suas veredas.","Pois de Sião sairá a instrução,","e de Jerusalém, a palavra do Senhor."],np:1},
{v:4,l:["Ele julgará entre as nações","e será o árbitro de povos numerosos.","Das suas espadas forjarão arados,","e das suas lanças, foices.","Uma nação não levantará a espada contra outra,","e não se prepararão mais para a guerra."],np:1},
{v:5,l:["Casa de Jacó, vinde,","andemos na luz do Senhor!"],np:1},
{s:"O dia do Senhor"},
{v:6,l:["Rejeitaste o teu povo, a casa de Jacó,","porque estão cheios de adivinhos do Oriente","e de feiticeiros, como os filisteus,","e fazem acordos com estrangeiros."]},
{v:7,l:["A sua terra está cheia de prata e de ouro,","e os seus tesouros não têm fim;"],np:1},
{v:8,l:["a sua terra está cheia de cavalos,","e os seus carros são inumeráveis;","a sua terra está cheia de ídolos:","adoram a obra das suas mãos,","aquilo que os seus dedos fizeram."],np:1,n:"A Nova Vulgata põe neste versículo a menção dos cavalos e dos carros, que o hebraico traz no versículo 7."},
{v:9,l:["O homem se curva,","o mortal se humilha:","não os perdoes!"],np:1,n:"Hebraico de sentido discutido; a Nova Vulgata entende, como aqui: não os perdoes."},
{v:10,l:["Entra na rocha, esconde-te no pó,","diante do terror do Senhor","e do esplendor da sua majestade."],np:1},
{v:11,l:["Os olhos altivos do homem serão abaixados,","e a arrogância dos mortais será humilhada;","só o Senhor será exaltado naquele dia."],np:1},
{v:12,l:["Pois o Senhor dos exércitos tem um dia","contra todo soberbo e altivo,","contra todo arrogante, para que seja abatido;"],np:1},
{v:13,l:["contra todos os cedros do Líbano, altos e elevados,","e contra todos os carvalhos de Basã;"],np:1},
{v:14,l:["contra todos os montes altos","e contra todas as colinas elevadas;"],np:1},
{v:15,l:["contra toda torre alta","e contra toda muralha fortificada;"],np:1},
{v:16,l:["contra todos os navios de Társis","e contra todas as embarcações preciosas."],np:1,n:"Navios de Társis: os grandes navios de longo curso."},
{v:17,l:["A altivez do homem será abatida,","e a arrogância dos mortais será humilhada;","só o Senhor será exaltado naquele dia,"],np:1},
{v:18,l:["e os ídolos desaparecerão por completo."],np:1},
{v:19,l:["Os homens entrarão nas cavernas das rochas","e nos buracos da terra,","diante do terror do Senhor","e do esplendor da sua majestade,","quando ele se levantar para fazer tremer a terra."],np:1},
{v:20,t:"Naquele dia, o homem lançará às toupeiras e aos morcegos os ídolos de prata e os ídolos de ouro que tinha feito para adorar,",np:1},
{v:21,t:"e entrará nas fendas das rochas e nas cavidades dos penhascos, diante do terror do Senhor e do esplendor da sua majestade, quando ele se levantar para fazer tremer a terra."},
{v:22,t:"Deixai, pois, de confiar no homem, que tem apenas um sopro nas narinas: que valor tem ele?",n:"Este versículo falta na antiga tradução grega."}
];

window.TEXTOS_SEED["isaias"][3] = [
{s:"A anarquia em Jerusalém"},
{v:1,l:["Eis que o Senhor, o Senhor dos exércitos,","tira de Jerusalém e de Judá o apoio e o sustento,","todo sustento de pão e todo sustento de água:"]},
{v:2,l:["o valente e o guerreiro,","o juiz e o profeta, o adivinho e o ancião,"],np:1},
{v:3,l:["o chefe de cinquenta e o homem de prestígio,","o conselheiro, o mago hábil","e o perito em encantamentos."],np:1},
{v:4,l:["Eu lhes darei meninos por chefes,","e crianças os governarão."],np:1},
{v:5,l:["O povo se oprimirá uns aos outros,","cada um ao seu próximo;","o jovem se levantará contra o ancião,","e o desprezível, contra o nobre."],np:1},
{v:6,l:["Quando alguém agarrar o seu irmão","na casa do seu pai, dizendo:","Tu tens um manto,","sê o nosso chefe","e toma conta destas ruínas,"],np:1},
{v:7,l:["naquele dia ele protestará:","Não sou médico,","e na minha casa não há pão nem manto;","não me façais chefe do povo."],np:1},
{v:8,l:["Jerusalém tropeçou, e Judá caiu,","porque as suas palavras e as suas obras são contra o Senhor,","afrontando os olhos da sua glória."],np:1},
{v:9,l:["A expressão do seu rosto testemunha contra eles;","como Sodoma, eles proclamam o seu pecado","e não o escondem.","Ai deles,","pois fazem mal a si mesmos!"],np:1},
{v:10,l:["Dizei ao justo que tudo lhe irá bem,","pois comerá o fruto das suas obras."],np:1},
{v:11,l:["Ai do ímpio! Tudo lhe irá mal,","pois receberá o que as suas mãos fizeram."],np:1},
{v:12,l:["O meu povo é oprimido por uma criança,","e mulheres o governam.","Povo meu, os teus guias te enganam","e confundem o caminho que deves seguir."],np:1},
{v:13,l:["O Senhor se levanta para acusar,","está de pé para julgar os povos."],np:1},
{v:14,l:["O Senhor entra em julgamento","com os anciãos do seu povo e os seus chefes:","Fostes vós que devorastes a vinha;","o despojo do pobre está nas vossas casas."],np:1,n:"A vinha é o povo de Deus (compare 5,1–7)."},
{v:15,l:["Com que direito esmagais o meu povo","e moeis o rosto dos pobres?","— oráculo do Senhor Deus dos exércitos."],np:1},
{s:"As mulheres de Sião"},
{v:16,l:["O Senhor disse:","Porque as filhas de Sião são altivas","e andam de pescoço esticado,","lançando olhares provocantes,","caminham a passos miúdos","e fazem tilintar os enfeites dos pés,"]},
{v:17,l:["o Senhor cobrirá de sarna o alto da cabeça das filhas de Sião,","e o Senhor lhes desnudará as partes íntimas."],np:1,n:"Nota do tradutor: o sentido do hebraico pot é discutido; muitos entendem as partes íntimas, outros a fronte, e a Nova Vulgata entende que lhes serão raspados os cabelos. É a humilhação reservada às prisioneiras de guerra, e o texto não a atenua."},
{v:18,l:["Naquele dia, o Senhor tirará o luxo","das tornozeleiras, das tiaras e das luazinhas,"],np:1,n:"Vários termos desta lista (vv. 18–23) são raros e de sentido incerto."},
{v:19,l:["dos brincos, das pulseiras e dos véus,"],np:1},
{v:20,l:["dos enfeites de cabeça e das correntinhas dos pés,","das faixas, dos frascos de perfume e dos amuletos,"],np:1},
{v:21,l:["dos anéis e das argolas do nariz,"],np:1},
{v:22,l:["dos vestidos de festa e dos mantos,","dos xales e das bolsas,"],np:1},
{v:23,l:["dos espelhos e das roupas de linho,","dos turbantes e das mantilhas."],np:1},
{v:24,l:["Em vez de perfume haverá mau cheiro;","em vez de cinto, uma corda;","em vez de cabelos bem penteados, a calvície;","em vez de vestido rico, um saco apertado;","e uma marca de fogo em vez de beleza."],np:1},
{v:25,l:["Os teus homens cairão pela espada,","e os teus valentes, na guerra."],np:1},
{v:26,l:["As portas da cidade gemerão e ficarão de luto;","devastada, ela se sentará no chão."],np:1}
];

window.TEXTOS_SEED["isaias"][4] = [
{s:"Sete mulheres por um homem"},
{v:1,l:["Naquele dia, sete mulheres","agarrarão um só homem, dizendo:","Comeremos o nosso próprio pão","e vestiremos as nossas próprias roupas;","basta que sejamos chamadas pelo teu nome:","tira de nós a nossa vergonha."],n:"Com a morte dos homens na guerra (3,25), as mulheres buscarão um marido para escapar à vergonha de ficar sem filhos."},
{s:"O rebento do Senhor"},
{v:2,l:["Naquele dia, o rebento do Senhor","será esplendor e glória,","e o fruto da terra será orgulho e ornamento","para os sobreviventes de Israel."],n:"O rebento do Senhor: a vegetação que o Senhor fará brotar na terra renovada; a tradição cristã leu aqui também um anúncio do Messias (compare Jeremias 23,5; Zacarias 3,8)."},
{v:3,l:["Então, o que restar em Sião","e o que sobrar em Jerusalém será chamado santo:","todos os que estão inscritos para a vida em Jerusalém,"],np:1},
{v:4,l:["quando o Senhor tiver lavado a imundície das filhas de Sião","e limpado de Jerusalém o sangue derramado","com o espírito de julgamento e o espírito de fogo."],np:1},
{v:5,l:["Então o Senhor criará, sobre todo o espaço do monte Sião","e sobre as suas assembleias,","uma nuvem de dia","e, de noite, fumaça e o brilho de um fogo flamejante.","Pois sobre toda a glória haverá uma cobertura,"],np:1,n:"Como a nuvem e o fogo que guiavam Israel no deserto (Êxodo 13,21–22)."},
{v:6,l:["e uma tenda servirá de sombra durante o dia contra o calor,","e de refúgio e abrigo contra a tempestade e a chuva."],np:1}
];

window.TEXTOS_SEED["isaias"][5] = [
{s:"O cântico da vinha"},
{v:1,l:["Vou cantar ao meu amigo","o cântico do meu amado sobre a sua vinha.","O meu amigo tinha uma vinha","numa colina fértil."],n:"Canção de amor que se transforma em parábola: a vinha é Israel (v. 7). Compare Mateus 21,33–41."},
{v:2,l:["Ele a cavou e tirou as pedras","e plantou nela videiras escolhidas;","construiu no meio dela uma torre","e cavou nela também um lagar.","Esperava que desse uvas boas,","mas ela deu uvas azedas."],np:1},
{v:3,l:["E agora, habitantes de Jerusalém","e homens de Judá,","julgai entre mim e a minha vinha."],np:1},
{v:4,l:["Que mais poderia eu ter feito pela minha vinha","que não tenha feito?","Por que, quando eu esperava que desse uvas boas,","ela deu uvas azedas?"],np:1},
{v:5,l:["Pois agora vou dizer-vos","o que farei com a minha vinha:","arrancarei a sua sebe,","e ela será devastada;","derrubarei o seu muro,","e ela será pisada."],np:1},
{v:6,l:["Farei dela um terreno abandonado:","não será podada nem cavada,","e nela crescerão espinhos e sarças;","e darei ordem às nuvens","para não mandarem chuva sobre ela."],np:1},
{v:7,l:["Pois a vinha do Senhor dos exércitos é a casa de Israel,","e os homens de Judá são a plantação que ele amava.","Esperava o direito, e eis o derramamento de sangue;","esperava a justiça, e eis o grito de socorro."],np:1,n:"No hebraico há um jogo de palavras: mishpat (direito) e mispah (derramamento de sangue), tsedaqah (justiça) e tseaqah (grito)."},
{s:"Ai dos injustos"},
{v:8,l:["Ai dos que juntam casa com casa","e emendam campo com campo,","até não sobrar espaço,","e habitam sozinhos no meio da terra!"]},
{v:9,l:["Aos meus ouvidos o Senhor dos exércitos jurou:","Muitas casas ficarão desertas,","casas grandes e belas, sem moradores."],np:1},
{v:10,l:["Pois dez jeiras de vinha produzirão só um bat,","e um hômer de semente produzirá só um efá."],np:1,n:"O bat é uma medida de líquidos, de uns vinte litros; o efá é a décima parte do hômer. A colheita renderá uma décima parte da semente."},
{v:11,l:["Ai dos que se levantam de madrugada","para correr atrás da bebida","e ficam até tarde da noite","inflamados pelo vinho!"],np:1},
{v:12,l:["Cítara e harpa,","tamborim e flauta","e vinho animam os seus banquetes,","mas não olham para a obra do Senhor","nem veem o que as suas mãos fazem."],np:1},
{v:13,l:["Por isso o meu povo vai para o exílio,","por falta de conhecimento;","os seus nobres morrem de fome,","e a sua multidão fica seca de sede."],np:1},
{v:14,l:["Por isso a morada dos mortos alargou a garganta","e abriu a boca sem medida;","para lá descem a nobreza e a multidão de Jerusalém,","o seu tumulto e a sua alegria."],np:1},
{v:15,l:["O homem será curvado, o mortal será humilhado,","e os olhos dos altivos serão abaixados;"],np:1},
{v:16,l:["mas o Senhor dos exércitos será exaltado no julgamento,","e o Deus santo mostrará a sua santidade na justiça."],np:1},
{v:17,l:["Os cordeiros pastarão ali como nas suas pastagens,","e estrangeiros comerão nas ruínas dos ricos."],np:1},
{v:18,l:["Ai dos que arrastam a iniquidade com cordas de mentira","e o pecado como com tirantes de carroça!"],np:1},
{v:19,l:["Eles dizem: Que ele se apresse,","que acelere a sua obra, para que a vejamos!","Que se aproxime e se cumpra o plano do Santo de Israel,","para que o conheçamos!"],np:1},
{v:20,l:["Ai dos que chamam ao mal bem e ao bem mal,","que fazem das trevas luz e da luz trevas,","que fazem do amargo doce e do doce amargo!"],np:1},
{v:21,l:["Ai dos que são sábios aos próprios olhos","e inteligentes na própria opinião!"],np:1},
{v:22,l:["Ai dos que são valentes para beber vinho","e fortes para misturar bebidas,"],np:1},
{v:23,l:["que absolvem o culpado por suborno","e negam ao justo o seu direito!"],np:1},
{v:24,l:["Por isso, como a língua de fogo devora a palha","e o feno se desfaz na chama,","assim a sua raiz apodrecerá","e a sua flor se desfará como pó;","pois rejeitaram a lei do Senhor dos exércitos","e desprezaram a palavra do Santo de Israel."],np:1},
{s:"A ira do Senhor e a invasão"},
{v:25,l:["Por isso a ira do Senhor se inflamou contra o seu povo;","ele estendeu a mão contra ele e o feriu;","os montes estremeceram,","e os seus cadáveres ficaram como lixo no meio das ruas.","Com tudo isso, a sua ira não se aplacou,","e a sua mão continua estendida."],n:"Refrão que volta em 9,11.16.20 e 10,4."},
{v:26,l:["Ele erguerá um estandarte para as nações distantes","e assobiará chamando uma delas desde os confins da terra;","e eis que ela vem, rápida e veloz."],np:1},
{v:27,l:["Ninguém nela está cansado ou tropeça,","ninguém cochila nem dorme;","não se solta o cinto dos seus rins,","nem se rompe a correia das suas sandálias."],np:1},
{v:28,l:["As suas flechas são afiadas,","e todos os seus arcos estão retesados;","os cascos dos seus cavalos parecem de pedra,","e as rodas dos seus carros, um furacão."],np:1},
{v:29,l:["O seu rugido é como o do leão;","ruge como os leõezinhos,","rosna e agarra a presa,","leva-a embora, e ninguém a pode livrar."],np:1},
{v:30,l:["Naquele dia rugirá contra ele","como o rugido do mar.","Olhará para a terra: eis trevas e angústia,","e a luz se escurece nas nuvens."],np:1}
];

window.TEXTOS_SEED["isaias"][6] = [
{s:"A vocação de Isaías"},
{v:1,t:"No ano da morte do rei Ozias, vi o Senhor sentado num trono alto e elevado; a orla do seu manto enchia o templo.",n:"O rei Ozias morreu por volta de 740 antes de Cristo."},
{v:2,t:"Serafins estavam de pé acima dele; cada um tinha seis asas: com duas cobria o rosto, com duas cobria os pés e com duas voava.",n:"Serafins: seres celestes; o nome evoca a ideia de fogo."},
{v:3,l:["E clamavam um para o outro:","Santo, santo, santo é o Senhor dos exércitos;","toda a terra está cheia da sua glória."],n:"Aclamação que a liturgia retoma no Santo da missa."},
{v:4,t:"Os batentes das portas estremeceram com a voz dos que clamavam, e o templo se encheu de fumaça.",np:1},
{v:5,l:["Então eu disse:","Ai de mim, estou perdido!","Pois sou um homem de lábios impuros","e habito no meio de um povo de lábios impuros,","e os meus olhos viram o Rei, o Senhor dos exércitos."],np:1},
{v:6,t:"Um dos serafins voou até mim, trazendo na mão uma brasa que tinha tirado do altar com uma tenaz;",np:1},
{v:7,l:["tocou com ela a minha boca e disse:","Eis que isto tocou os teus lábios:","a tua culpa foi tirada,","e o teu pecado, perdoado."]},
{v:8,t:"Então ouvi a voz do Senhor, que dizia: Quem enviarei? Quem irá por nós? Eu respondi: Eis-me aqui, envia-me.",np:1},
{v:9,l:["Ele disse: Vai e dize a este povo:","Ouvi, ouvi, e não entendais;","vede, vede, e não compreendais."]},
{v:10,l:["Torna insensível o coração deste povo,","endurece-lhe os ouvidos","e fecha-lhe os olhos,","para que não veja com os olhos","nem ouça com os ouvidos,","nem entenda com o coração,","e não se converta e seja curado."],np:1,n:"Nota do tradutor: o profeta exprime em forma de ordem o resultado da sua pregação: quanto mais ele fala, mais o povo se endurece. Jesus cita estas palavras a propósito das parábolas (Mateus 13,14–15), e Paulo no fim dos Atos (Atos 28,26–27)."},
{v:11,l:["Eu perguntei: Até quando, Senhor?","Ele respondeu:","Até que as cidades fiquem arruinadas,","sem habitantes,","as casas sem ninguém,","e a terra, reduzida a um deserto."],np:1},
{v:12,l:["O Senhor levará para longe os homens,","e será grande o abandono no meio da terra."],np:1},
{v:13,l:["E, se ainda restar nela um décimo,","também ele será destruído,","como o terebinto e o carvalho,","dos quais, depois de cortados, fica o toco.","O toco é uma semente santa."],np:1,n:"A última frase falta na antiga tradução grega. Ela anuncia que do resto sobrevivente Deus fará brotar um povo santo."}
];

window.TEXTOS_SEED["isaias"][7] = [
{s:"Isaías e o rei Acaz"},
{v:1,t:"Nos dias de Acaz, filho de Joatão, filho de Ozias, rei de Judá, Rasin, rei da Síria, e Faceia, filho de Romelias, rei de Israel, subiram contra Jerusalém para atacá-la, mas não conseguiram conquistá-la.",n:"Por volta de 734 antes de Cristo, a Síria e o reino do norte quiseram forçar Judá a entrar na sua coligação contra a Assíria (2 Reis 16,5–9)."},
{v:2,t:"Anunciaram à casa de Davi: Os arameus acamparam em Efraim. Então o coração do rei e o coração do seu povo se agitaram, como as árvores da floresta se agitam com o vento."},
{v:3,t:"O Senhor disse a Isaías: Sai ao encontro de Acaz, tu e o teu filho Sear-Iasub, na extremidade do aqueduto do tanque superior, no caminho do campo do lavandeiro,",n:"Sear-Iasub significa: um resto voltará."},
{v:4,t:"e dize-lhe: Toma cuidado e fica tranquilo; não tenhas medo, e que o teu coração não desanime por causa destes dois tocos de tições fumegantes, por causa da ira ardente de Rasin, da Síria e do filho de Romelias,"},
{v:5,t:"porque a Síria, Efraim e o filho de Romelias tramaram o mal contra ti, dizendo:"},
{v:6,t:"Subamos contra Judá, aterrorizemo-lo, conquistemo-lo para nós e ponhamos nele como rei o filho de Tabeel."},
{v:7,l:["Assim diz o Senhor Deus:","Isso não se realizará,","não acontecerá!"],np:1},
{v:8,l:["Pois a cabeça da Síria é Damasco,","e a cabeça de Damasco é Rasin;","dentro de sessenta e cinco anos","Efraim será destruído e deixará de ser um povo;"],np:1,n:"Samaria foi tomada pelos assírios em 722 antes de Cristo, e o reino do norte desapareceu."},
{v:9,l:["a cabeça de Efraim é Samaria,","e a cabeça de Samaria é o filho de Romelias.","Se não crerdes,","não vos mantereis firmes."],np:1,n:"No hebraico há um jogo de palavras entre crer (taaminu) e manter-se firme (teamenu)."},
{v:10,t:"O Senhor falou ainda a Acaz:",np:1},
{v:11,t:"Pede um sinal ao Senhor teu Deus, seja nas profundezas da morada dos mortos, seja nas alturas lá em cima."},
{v:12,t:"Acaz respondeu: Não pedirei, não quero tentar o Senhor."},
{v:13,t:"Então Isaías disse: Ouvi, pois, casa de Davi: não vos basta cansar a paciência dos homens, e quereis cansar também a do meu Deus?"},
{v:14,t:"Por isso o próprio Senhor vos dará um sinal: Eis que a virgem conceberá e dará à luz um filho, e lhe porá o nome de Emanuel.",n:"O hebraico almah designa a jovem em idade de casar; a antiga tradução grega traduziu virgem (parthenos), e é esse o texto citado em Mateus 1,23, que vê o sinal cumprido em Jesus, nascido da Virgem Maria. Emanuel significa: Deus conosco."},
{v:15,t:"Ele comerá coalhada e mel, até que saiba rejeitar o mal e escolher o bem."},
{v:16,t:"Pois, antes que o menino saiba rejeitar o mal e escolher o bem, ficará abandonada a terra dos dois reis que tu temes."},
{v:17,t:"O Senhor fará vir sobre ti, sobre o teu povo e sobre a casa do teu pai dias como não houve desde que Efraim se separou de Judá: o rei da Assíria."},
{s:"Naquele dia"},
{v:18,l:["Naquele dia,","o Senhor assobiará para as moscas","que estão nos confins dos rios do Egito","e para as abelhas que estão na terra da Assíria;"]},
{v:19,l:["elas virão e pousarão todas","nos vales escarpados","e nas fendas das rochas,","em todos os espinheiros","e em todas as pastagens."],np:1},
{v:20,l:["Naquele dia, o Senhor raspará,","com uma navalha alugada do outro lado do Rio","— com o rei da Assíria —,","a cabeça e os pelos dos pés,","e cortará também a barba."],np:1,n:"Os pelos dos pés: eufemismo para os pelos do púbis. Raspar a cabeça, a barba e os pelos do corpo era a humilhação infligida aos prisioneiros de guerra. O Rio: o Eufrates."},
{v:21,l:["Naquele dia,","cada um criará uma novilha e duas ovelhas;"],np:1},
{v:22,l:["e, pela abundância de leite que darão,","comerá coalhada;","sim, comerão coalhada e mel","todos os que ficarem no meio da terra."],np:1,n:"Coalhada e mel: alimento de pastores numa terra despovoada, que voltou ao estado selvagem."},
{v:23,l:["Naquele dia,","todo lugar onde havia mil videiras, que valiam mil moedas de prata,","ficará coberto de espinhos e sarças."],np:1},
{v:24,l:["Ali se entrará com flechas e arco,","pois toda a terra será espinhos e sarças."],np:1},
{v:25,l:["E em todos os montes que se cultivavam com a enxada","ninguém entrará, por medo dos espinhos e das sarças;","serão pasto para os bois e terreno pisado pelas ovelhas."],np:1}
];

window.TEXTOS_SEED["isaias"][8] = [
{s:"O filho do profeta, sinal para o povo"},
{v:1,t:"O Senhor me disse: Toma uma tábua grande e escreve nela com letras comuns: Maher-Salal-Has-Baz.",n:"O nome significa: Rápido saque, pronta pilhagem."},
{v:2,t:"Tomei como testemunhas fiéis o sacerdote Urias e Zacarias, filho de Jeberequias.",np:1},
{v:3,t:"Depois me uni à profetisa, e ela concebeu e deu à luz um filho. O Senhor me disse: Dá-lhe o nome de Maher-Salal-Has-Baz,",n:"A profetisa: a mulher de Isaías."},
{v:4,t:"pois, antes que o menino saiba dizer meu pai e minha mãe, as riquezas de Damasco e os despojos de Samaria serão levados diante do rei da Assíria."},
{v:5,t:"O Senhor me falou ainda:"},
{v:6,l:["Porque este povo rejeitou","as águas de Siloé, que correm mansamente,","e se alegra por causa de Rasin e do filho de Romelias,"],np:1,n:"Siloé: o canal que levava a Jerusalém as águas da fonte de Gion, imagem da proteção tranquila do Senhor. No último verso, a Nova Vulgata entende: e desfalece diante de Rasin."},
{v:7,l:["por isso o Senhor fará subir contra eles","as águas do Rio, poderosas e abundantes","— o rei da Assíria com toda a sua glória —;","ele transbordará por todos os seus canais","e inundará todas as suas margens;"],np:1},
{v:8,l:["invadirá Judá, transbordando e passando,","e chegará até o pescoço;","e as suas asas abertas","cobrirão toda a largura da tua terra, ó Emanuel."],np:1},
{v:9,l:["Enfurecei-vos, povos, e sereis despedaçados;","escutai, vós todas, terras distantes:","armai-vos, e sereis despedaçados;","armai-vos, e sereis despedaçados."],np:1},
{v:10,l:["Fazei planos, e eles fracassarão;","dai ordens, e elas não se cumprirão,","pois Deus está conosco."],np:1,n:"Deus está conosco: em hebraico, immanu El (compare 7,14)."},
{v:11,t:"Pois assim me falou o Senhor, quando a sua mão me dominou e me advertiu para não seguir o caminho deste povo:",np:1},
{v:12,l:["Não chameis conspiração","a tudo o que este povo chama conspiração;","não temais o que ele teme","nem vos assusteis."],np:1},
{v:13,l:["É ao Senhor dos exércitos que deveis reconhecer como santo:","é ele que deveis temer,","é diante dele que deveis tremer."],np:1,n:"Compare 1 Pedro 3,14–15."},
{v:14,l:["Ele será um santuário,","mas também uma pedra de tropeço e uma rocha de escândalo","para as duas casas de Israel,","um laço e uma armadilha","para os habitantes de Jerusalém."],np:1,n:"Compare Romanos 9,33 e 1 Pedro 2,8."},
{v:15,l:["Muitos tropeçarão neles,","cairão e se despedaçarão,","ficarão presos no laço e serão apanhados."],np:1},
{v:16,t:"Guarda o testemunho, sela a instrução entre os meus discípulos.",np:1},
{v:17,t:"Esperarei no Senhor, que esconde o seu rosto da casa de Jacó; nele porei a minha esperança."},
{v:18,t:"Eis que eu e os filhos que o Senhor me deu somos sinais e presságios em Israel, da parte do Senhor dos exércitos, que habita no monte Sião.",n:"Os nomes do profeta e dos seus filhos são mensagens para o povo: Isaías significa o Senhor salva. A Carta aos Hebreus aplica estas palavras a Cristo (Hebreus 2,13)."},
{v:19,t:"E, se vos disserem: Consultai os necromantes e os adivinhos, que sussurram e murmuram; acaso um povo não deve consultar os seus deuses, e os mortos em favor dos vivos?"},
{v:20,t:"À instrução e ao testemunho! Se não falarem conforme esta palavra, não haverá aurora para eles."},
{v:21,l:["Ele passará pela terra, oprimido e faminto;","e, quando tiver fome, se enfurecerá","e amaldiçoará o seu rei e o seu Deus;","olhará para o alto"],np:1},
{v:22,l:["e olhará para a terra:","eis angústia e trevas,","escuridão opressiva e noite espessa."],np:1},
{v:23,l:["Mas não haverá mais escuridão","para a terra que estava em angústia.","No passado, ele humilhou a terra de Zabulon e a terra de Neftali;","no futuro, cobrirá de glória o caminho do mar,","o outro lado do Jordão, a Galileia das nações."],np:1,n:"Em outras Bíblias, este versículo é 9,1. Mateus 4,15–16 o aplica ao começo da pregação de Jesus na Galileia."}
];

window.TEXTOS_SEED["isaias"][9] = [
{s:"Um menino nos nasceu"},
{v:1,l:["O povo que andava nas trevas","viu uma grande luz;","sobre os que habitavam na terra da sombra da morte","uma luz resplandeceu."],n:"Em outras Bíblias, 9,2. Este oráculo é lido na missa da noite de Natal."},
{v:2,l:["Multiplicaste a alegria,","aumentaste o júbilo;","eles se alegram diante de ti","como se alegram na colheita,","como exultam quando repartem os despojos."],np:1,n:"Assim a Nova Vulgata, com uma correção comum; o hebraico diz: multiplicaste a nação."},
{v:3,l:["Pois o jugo que pesava sobre ele,","a vara sobre os seus ombros","e o bastão do seu opressor,","tu os quebraste, como no dia de Madiã."],np:1,n:"A vitória de Gedeão sobre os madianitas (Juízes 7)."},
{v:4,l:["Pois toda bota que pisava com estrondo","e todo manto revolvido no sangue","serão queimados, pasto do fogo."],np:1},
{v:5,l:["Pois um menino nasceu para nós,","um filho nos foi dado;","o poder repousa sobre os seus ombros,","e ele será chamado","Maravilhoso Conselheiro, Deus forte,","Pai para sempre, Príncipe da paz."],np:1,n:"Nomes do rei ideal, descendente de Davi. A Igreja reconhece neste menino o Cristo, o Filho de Deus feito homem."},
{v:6,l:["Grande será o seu domínio,","e a paz não terá fim","sobre o trono de Davi e sobre o seu reino,","para firmá-lo e consolidá-lo com o direito e a justiça,","desde agora e para sempre:","o zelo do Senhor dos exércitos fará isso."],np:1},
{s:"A mão estendida do Senhor"},
{v:7,l:["O Senhor enviou uma palavra contra Jacó,","e ela caiu sobre Israel."]},
{v:8,l:["Todo o povo a conhecerá,","Efraim e os habitantes de Samaria,","que dizem com orgulho e arrogância no coração:"],np:1},
{v:9,l:["Os tijolos caíram,","mas construiremos com pedras lavradas;","os sicômoros foram cortados,","mas os substituiremos por cedros."],np:1},
{v:10,l:["Mas o Senhor levantou contra ele os adversários","e incitou os seus inimigos:"],np:1,n:"O hebraico diz: os adversários de Rasin."},
{v:11,l:["os arameus a oriente e os filisteus a ocidente,","que devoraram Israel a boca cheia.","Com tudo isso, a sua ira não se aplacou,","e a sua mão continua estendida."],np:1},
{v:12,l:["Mas o povo não voltou para aquele que o feria,","e não buscou o Senhor dos exércitos."],np:1},
{v:13,l:["Por isso o Senhor cortou de Israel a cabeça e a cauda,","a palmeira e o junco, num só dia:"],np:1},
{v:14,l:["o ancião e o homem de prestígio são a cabeça,","e o profeta que ensina a mentira é a cauda."],np:1},
{v:15,l:["Os que guiam este povo o extraviam,","e os que são guiados se perdem."],np:1},
{v:16,l:["Por isso o Senhor não se alegrará com os seus jovens","nem terá compaixão dos seus órfãos e das suas viúvas,","pois todos são ímpios e malvados,","e toda boca fala insensatez.","Com tudo isso, a sua ira não se aplacou,","e a sua mão continua estendida."],np:1},
{v:17,l:["Pois a impiedade arde como fogo,","devora espinhos e sarças,","incendeia os matagais da floresta,","e eles sobem em colunas de fumaça."],np:1},
{v:18,l:["Pela ira do Senhor dos exércitos a terra está em chamas,","e o povo é como pasto do fogo:","ninguém poupa o seu irmão."],np:1},
{v:19,l:["Corta-se à direita, e ainda se tem fome;","come-se à esquerda, e não se fica saciado;","cada um devora a carne do seu próximo:"],np:1,n:"Assim a Nova Vulgata; o hebraico diz: a carne do seu próprio braço."},
{v:20,l:["Manassés devora Efraim, e Efraim, Manassés,","e os dois juntos se voltam contra Judá.","Com tudo isso, a sua ira não se aplacou,","e a sua mão continua estendida."],np:1}
];

window.TEXTOS_SEED["isaias"][10] = [
{s:"Ai dos legisladores injustos"},
{v:1,l:["Ai dos que decretam leis iníquas","e dos escribas que escrevem a opressão,"]},
{v:2,l:["para negar a justiça aos fracos","e fraudar o direito dos pobres do meu povo,","para fazer das viúvas a sua presa","e despojar os órfãos!"],np:1},
{v:3,l:["Que fareis no dia do castigo,","na tempestade que vem de longe?","A quem recorrereis em busca de socorro,","e onde deixareis as vossas riquezas?"],np:1},
{v:4,l:["Não vos restará senão curvar-vos entre os prisioneiros","ou cair entre os mortos.","Com tudo isso, a sua ira não se aplacou,","e a sua mão continua estendida."],np:1},
{s:"A Assíria, vara da ira do Senhor"},
{v:5,l:["Ai da Assíria, vara da minha ira,","o bastão que tem na mão é o meu furor!"]},
{v:6,l:["Eu a envio contra uma nação ímpia,","eu a mando contra o povo que provocou a minha ira,","para saquear e pilhar","e pisá-lo como a lama das ruas."],np:1},
{v:7,l:["Mas ela não pensa assim,","o seu coração não calcula assim;","o que ela tem no coração é destruir","e exterminar nações sem conta."],np:1},
{v:8,l:["Pois diz: Não são reis todos os meus chefes?"],np:1},
{v:9,l:["Não aconteceu a Calno como a Carquemis?","Não aconteceu a Emat como a Arfad?","Não aconteceu a Samaria como a Damasco?"],np:1,n:"Cidades da Síria conquistadas pelos assírios entre 740 e 720 antes de Cristo."},
{v:10,l:["Assim como a minha mão alcançou os reinos dos ídolos,","cujas imagens eram mais numerosas que as de Jerusalém e de Samaria,"],np:1},
{v:11,l:["não farei a Jerusalém e às suas imagens","o que fiz a Samaria e aos seus ídolos?"],np:1},
{v:12,t:"Quando o Senhor tiver terminado toda a sua obra no monte Sião e em Jerusalém, castigarei o fruto do coração orgulhoso do rei da Assíria e a arrogância do seu olhar altivo.",np:1},
{v:13,l:["Pois ele diz:","Foi com a força da minha mão que agi,","e com a minha sabedoria, pois sou inteligente;","removi as fronteiras dos povos,","saqueei os seus tesouros","e, como um valente, derrubei os que estavam no trono."]},
{v:14,l:["A minha mão alcançou, como um ninho, a riqueza dos povos;","como se recolhem ovos abandonados,","assim eu recolhi toda a terra,","e não houve quem batesse as asas,","quem abrisse o bico ou piasse."],np:1},
{v:15,l:["Acaso o machado se gloria","contra quem corta com ele?","Ou a serra se exalta","contra quem a maneja?","Como se a vara manejasse quem a levanta,","ou o bastão levantasse quem não é de madeira!"],np:1},
{v:16,l:["Por isso o Senhor, o Senhor dos exércitos,","enviará a magreza aos seus guerreiros robustos;","e sob a sua glória","arderá um incêndio como o fogo."],np:1},
{v:17,l:["A Luz de Israel se tornará um fogo,","e o seu Santo, uma chama;","ela queimará e devorará os seus espinhos","e as suas sarças num só dia."],np:1},
{v:18,l:["Consumirá a glória da sua floresta e do seu pomar,","da alma até a carne,","e ele ficará como um doente que definha;"],np:1},
{v:19,l:["e as árvores que restarem da sua floresta","serão tão poucas","que um menino poderá contá-las."],np:1},
{s:"O resto voltará"},
{v:20,l:["Naquele dia,","o resto de Israel","e os sobreviventes da casa de Jacó","não se apoiarão mais naquele que os feriu,","mas se apoiarão com lealdade no Senhor,","o Santo de Israel."]},
{v:21,l:["Um resto voltará, o resto de Jacó,","para o Deus forte."],np:1,n:"Alusão ao nome do filho de Isaías, Sear-Iasub (7,3)."},
{v:22,l:["Pois, ainda que o teu povo, ó Israel, seja como a areia do mar,","só um resto voltará;","a destruição está decretada, transbordante de justiça."],np:1,n:"Paulo cita os versículos 22–23 em Romanos 9,27–28."},
{v:23,l:["Pois o extermínio decretado,","o Senhor Deus dos exércitos o executará no meio de toda a terra."],np:1},
{v:24,t:"Por isso assim diz o Senhor Deus dos exércitos: Povo meu, que habitas em Sião, não tenhas medo da Assíria, que te fere com a vara e levanta contra ti o bastão, como fez o Egito.",np:1},
{v:25,t:"Pois ainda um pouco, bem pouco, e a minha indignação acabará, e a minha ira se voltará para a destruição deles."},
{v:26,t:"O Senhor dos exércitos brandirá contra ela o chicote, como quando feriu Madiã na rocha de Oreb, e levantará o seu bastão sobre o mar, como fez no Egito.",n:"Juízes 7,25; Êxodo 14,16."},
{v:27,l:["Naquele dia,","o seu fardo cairá dos teus ombros,","e o seu jugo, do teu pescoço.","O devastador sobe de Remon."],np:1,n:"A última linha segue a Nova Vulgata, que corrige um hebraico obscuro (literalmente: e o jugo será destruído por causa da gordura)."},
{s:"A marcha do invasor"},
{v:28,l:["Ele chega a Aiat, passa por Magron,","em Micmás deixa a sua bagagem;"]},
{v:29,l:["atravessam o desfiladeiro: Passaremos a noite em Gaba!","Ramá treme, Gabaá de Saul foge."],np:1},
{v:30,l:["Grita alto, Bat-Galim!","Escuta, Laisa! Responde, Anatot!"],np:1},
{v:31,l:["Madmena foge,","os habitantes de Gebim se escondem."],np:1},
{v:32,l:["Hoje mesmo fará parada em Nob;","agita a mão contra o monte da filha de Sião,","contra a colina de Jerusalém."],np:1,n:"O invasor avança do norte, de aldeia em aldeia, até as portas de Jerusalém."},
{v:33,l:["Eis que o Senhor, o Senhor dos exércitos,","corta os ramos com violência;","as árvores mais altas são abatidas,","e as mais elevadas caem."],np:1},
{v:34,l:["Ele derruba com o ferro os matagais da floresta,","e o Líbano cai com o seu esplendor."],np:1}
];
