// =====================================================================
// Jeremias — tradução do hebraico (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["jeremias"][1] = [
{s:"Título do livro"},
{v:1,t:"Palavras de Jeremias, filho de Helcias, um dos sacerdotes que viviam em Anatot, na terra de Benjamim.",n:"Jeremias exerceu o seu ministério em Jerusalém desde 627 até depois da destruição da cidade pelos babilônios, em 587 antes de Cristo. A antiga tradução grega tem um texto bem mais curto e em outra ordem; a Nova Vulgata segue o texto hebraico."},
{v:2,t:"A ele foi dirigida a palavra do Senhor nos dias de Josias, filho de Amon, rei de Judá, no décimo terceiro ano do seu reinado,",np:1,n:"Em 627 antes de Cristo."},
{v:3,t:"e depois nos dias de Joaquim, filho de Josias, rei de Judá, até o fim do décimo primeiro ano de Sedecias, filho de Josias, rei de Judá, até a deportação de Jerusalém, no quinto mês.",np:1,n:"Em 587 antes de Cristo."},
{s:"A vocação de Jeremias"},
{v:4,t:"A palavra do Senhor me foi dirigida nestes termos:"},
{v:5,l:["Antes de te formar no ventre materno, eu te conheci;","antes que saísses do seio, eu te consagrei","e te constituí profeta das nações."],np:1},
{v:6,t:"Eu disse: Ah, Senhor Deus! Eis que não sei falar, porque sou jovem.",np:1},
{v:7,l:["Mas o Senhor me respondeu: Não digas: Sou jovem,","pois irás a todos aqueles a quem eu te enviar","e dirás tudo o que eu te ordenar."],np:1},
{v:8,l:["Não tenhas medo deles,","pois estou contigo para te livrar,","oráculo do Senhor."],np:1},
{v:9,l:["Então o Senhor estendeu a mão e tocou a minha boca, e o Senhor me disse:","Eis que ponho as minhas palavras na tua boca;"],np:1},
{v:10,l:["vê: hoje te constituo sobre as nações e sobre os reinos,","para arrancar e para derrubar,","para destruir e para demolir,","para construir e para plantar."],np:1},
{s:"Duas visões"},
{v:11,t:"A palavra do Senhor me foi dirigida nestes termos: Que vês, Jeremias? Eu respondi: Vejo um ramo de amendoeira.",n:"Jogo de palavras no hebraico: shaqed (amendoeira, a árvore que desperta primeiro depois do inverno) e shoqed (vigilante)."},
{v:12,t:"E o Senhor me disse: Viste bem, pois eu vigio sobre a minha palavra, para realizá-la."},
{v:13,t:"A palavra do Senhor me foi dirigida uma segunda vez: Que vês? Eu respondi: Vejo uma panela fervendo, com a boca voltada do lado norte.",np:1},
{v:14,l:["E o Senhor me disse:","Do norte se derramará a desgraça","sobre todos os habitantes da terra."]},
{v:15,l:["Pois eis que vou chamar","todas as famílias dos reinos do norte,","oráculo do Senhor;","eles virão, e cada um porá o seu trono","à entrada das portas de Jerusalém,","contra todas as suas muralhas ao redor","e contra todas as cidades de Judá."],np:1},
{v:16,l:["Pronunciarei contra eles as minhas sentenças","por toda a sua maldade,","porque me abandonaram,","queimaram incenso a outros deuses","e adoraram a obra das suas mãos."],np:1},
{v:17,l:["Mas tu, cinge os teus rins,","levanta-te e dize-lhes","tudo o que eu te ordenar;","não tenhas medo deles,","senão eu te farei ter medo diante deles."],np:1},
{v:18,l:["Eis que hoje faço de ti","uma cidade fortificada,","uma coluna de ferro","e uma muralha de bronze","contra toda a terra,","contra os reis de Judá, contra os seus chefes,","contra os seus sacerdotes e contra o povo da terra."],np:1},
{v:19,l:["Eles lutarão contra ti, mas não te vencerão,","pois estou contigo,","oráculo do Senhor,","para te livrar."],np:1}
];

window.TEXTOS_SEED["jeremias"][2] = [
{s:"A infidelidade de Israel"},
{v:1,t:"A palavra do Senhor me foi dirigida nestes termos:"},
{v:2,l:["Vai e grita aos ouvidos de Jerusalém:","Assim diz o Senhor:","Lembro-me do amor da tua juventude,","do amor do teu noivado,","quando me seguias no deserto,","numa terra não semeada."],np:1},
{v:3,l:["Israel era consagrado ao Senhor,","as primícias da sua colheita;","todos os que o devoravam se tornavam culpados,","e a desgraça caía sobre eles,","oráculo do Senhor."],np:1},
{v:4,l:["Ouvi a palavra do Senhor, casa de Jacó,","e todas as famílias da casa de Israel."],np:1},
{v:5,l:["Assim diz o Senhor:","Que injustiça encontraram em mim os vossos pais,","para se afastarem de mim,","correrem atrás do nada","e se tornarem eles mesmos nada?"],np:1},
{v:6,l:["Eles não disseram: Onde está o Senhor,","que nos fez subir da terra do Egito,","que nos conduziu pelo deserto,","por uma terra de estepes e barrancos,","por uma terra de seca e de trevas,","por uma terra por onde ninguém passa","e onde nenhum homem habita?"],np:1},
{v:7,l:["Eu vos trouxe para uma terra de pomares,","para comerdes os seus frutos e os seus bens;","mas vós entrastes e contaminastes a minha terra","e fizestes da minha herança uma abominação."],np:1},
{v:8,l:["Os sacerdotes não disseram:","Onde está o Senhor?","Os que manejavam a lei não me conheceram,","os pastores se rebelaram contra mim,","os profetas profetizaram em nome de Baal","e seguiram os que não servem para nada."],np:1},
{v:9,l:["Por isso ainda entrarei em julgamento convosco,","oráculo do Senhor,","e pleitearei com os filhos dos vossos filhos."],np:1},
{v:10,l:["Passai às ilhas de Quitim e vede,","mandai alguém a Cedar e observai bem,","e vede se aconteceu coisa semelhante:"],np:1,n:"Quitim, no ocidente, e Cedar, no oriente: de um extremo ao outro do mundo conhecido."},
{v:11,l:["acaso uma nação trocou os seus deuses,","que nem sequer são deuses?","Mas o meu povo trocou a sua Glória","por aquilo que não serve para nada."],np:1},
{v:12,l:["Pasmai, ó céus, diante disto,","estremecei de horror, ficai assombrados,","oráculo do Senhor."],np:1},
{v:13,l:["Pois o meu povo cometeu dois males:","abandonaram a mim, fonte de água viva,","para cavar para si cisternas,","cisternas rachadas,","que não retêm a água."],np:1},
{v:14,l:["Acaso Israel é um escravo,","um servo nascido em casa?","Por que então se tornou uma presa?","Contra ele rugiram os leões"],np:1},
{v:15,l:["e soltaram o seu rugido;","reduziram a sua terra a um deserto;","as suas cidades foram incendiadas","e ficaram sem habitantes."],np:1},
{v:16,l:["Até os filhos de Mênfis e de Táfnis","te raparam o alto da cabeça."],np:1},
{v:17,l:["Não foi isto que atraíste sobre ti,","por teres abandonado o Senhor, teu Deus,","quando ele te guiava pelo caminho?"],np:1},
{v:18,l:["E agora, que vais fazer no caminho do Egito,","para beber a água do Nilo?","Que vais fazer no caminho da Assíria,","para beber a água do Rio?"],np:1},
{v:19,l:["A tua maldade te castigará,","e as tuas infidelidades te condenarão;","reconhece e vê como é mau e amargo","teres abandonado o Senhor, teu Deus,","e não teres mais temor de mim,","oráculo do Senhor Deus dos exércitos."],np:1},
{v:20,l:["Há muito tempo quebraste o teu jugo,","rompeste as tuas correntes","e disseste: Não servirei!","Em toda colina elevada","e debaixo de toda árvore frondosa","tu te deitavas como prostituta."],np:1,n:"A prostituição é imagem da idolatria praticada nos santuários dos cultos cananeus."},
{v:21,l:["Eu te plantei como uma vinha escolhida,","toda de semente legítima;","como te transformaste para mim","em ramos de uma vinha estranha?"],np:1},
{v:22,l:["Ainda que te laves com salitre","e uses muito sabão,","a tua culpa continua como uma mancha diante de mim,","oráculo do Senhor Deus."],np:1},
{v:23,l:["Como podes dizer: Não estou contaminada,","não corri atrás dos baals?","Olha o teu caminho no vale,","reconhece o que fizeste,","camela nova e ligeira, que corre para lá e para cá,"],np:1},
{v:24,l:["jumenta selvagem acostumada ao deserto,","que no ardor do cio aspira o vento:","quem a conterá no seu desejo?","Todos os que a procuram não precisam cansar-se:","encontram-na no seu mês."],np:1,n:"Nota do tradutor: imagens tiradas do cio dos animais para descrever a ânsia de Israel pelos cultos estrangeiros; o texto não as atenua."},
{v:25,l:["Poupa o teu pé de andar descalço","e a tua garganta da sede!","Mas disseste: É inútil! Não!","Pois amo os estrangeiros","e quero correr atrás deles."],np:1},
{v:26,l:["Como o ladrão fica envergonhado quando é apanhado,","assim ficará envergonhada a casa de Israel,","eles, os seus reis, os seus chefes,","os seus sacerdotes e os seus profetas,"],np:1},
{v:27,l:["que dizem a um pedaço de pau: Tu és o meu pai,","e a uma pedra: Tu me geraste.","Pois voltaram para mim as costas, e não o rosto;","mas no tempo da desgraça dizem:","Levanta-te e salva-nos!"],np:1},
{v:28,l:["Onde estão os teus deuses, que fizeste para ti?","Que se levantem, se podem salvar-te","no tempo da tua desgraça!","Pois tens tantos deuses, ó Judá,","quantas são as tuas cidades."],np:1},
{v:29,l:["Por que discutis comigo?","Todos vós vos rebelastes contra mim,","oráculo do Senhor."],np:1},
{v:30,l:["Em vão feri os vossos filhos:","não aceitaram a correção.","A vossa espada devorou os vossos profetas,","como um leão devastador."],np:1},
{v:31,l:["Ó geração, prestai atenção à palavra do Senhor:","acaso fui para Israel um deserto,","uma terra de trevas espessas?","Por que o meu povo diz: Somos livres,","não voltaremos mais a ti?"],np:1},
{v:32,l:["Acaso uma jovem esquece os seus enfeites,","ou uma noiva o seu cinto?","Mas o meu povo se esqueceu de mim","há dias sem conta."],np:1},
{v:33,l:["Como sabes bem escolher o teu caminho","para buscar o amor!","Por isso ensinaste os teus caminhos","até às mulheres más."],np:1},
{v:34,l:["Até nas barras da tua roupa se encontra","o sangue de pobres inocentes,","que não surpreendeste arrombando a casa.","E, apesar de tudo isso,"],np:1,n:"A Lei só desculpava a morte de quem era surpreendido arrombando uma casa (Êxodo 22,1)."},
{v:35,l:["dizes: Sou inocente,","certamente a sua ira se afastou de mim.","Eis que vou entrar em julgamento contigo,","porque dizes: Não pequei."],np:1},
{v:36,l:["Com que leviandade mudas de caminho!","Também do Egito sairás envergonhada,","como saíste envergonhada da Assíria."],np:1},
{v:37,l:["Também de lá sairás com as mãos na cabeça,","pois o Senhor rejeitou aqueles em quem confiavas,","e não terás êxito com eles."],np:1}
];

window.TEXTOS_SEED["jeremias"][3] = [
{s:"A esposa infiel"},
{v:1,l:["Se um homem repudia a sua mulher,","e ela o deixa","e se casa com outro homem,","acaso ele voltará para ela?","Não ficaria aquela terra","completamente contaminada?","E tu, que te prostituíste com muitos amantes,","queres voltar para mim?","— oráculo do Senhor."],n:"A Lei proibia que o primeiro marido retomasse a mulher repudiada que se casara com outro (Deuteronômio 24,1–4)."},
{v:2,l:["Ergue os olhos para as colinas e vê:","onde é que não te deitaste com eles?","À beira dos caminhos te sentavas à espera deles,","como o árabe no deserto;","contaminaste a terra","com as tuas prostituições e a tua maldade."],np:1},
{v:3,l:["Por isso as chuvas foram retidas,","e não houve a chuva da primavera;","mas tu tens a fronte de uma prostituta,","recusas envergonhar-te."],np:1},
{v:4,l:["E agora me chamas: Meu pai,","tu és o amigo da minha juventude!"],np:1},
{v:5,l:["Acaso ele ficará irado para sempre,","guardará rancor até o fim?","Eis o que dizes,","mas fazes o mal quanto podes."],np:1},
{s:"As duas irmãs infiéis"},
{v:6,t:"O Senhor me disse no tempo do rei Josias: Viste o que fez Israel, a infiel? Ela foi a todo monte alto e debaixo de toda árvore frondosa, e ali se prostituiu."},
{v:7,t:"Eu pensava: Depois de ter feito tudo isso, ela voltará para mim; mas ela não voltou. E a sua irmã, Judá, a traidora, viu tudo isso."},
{v:8,t:"Viu que, por causa de todos os adultérios de Israel, a infiel, eu a tinha repudiado e lhe tinha dado a carta de divórcio; mas a sua irmã, Judá, a traidora, não teve medo: também ela foi e se prostituiu."},
{v:9,t:"Com a sua prostituição leviana contaminou a terra e cometeu adultério com a pedra e com a madeira.",n:"A pedra e a madeira: os ídolos e os postes sagrados."},
{v:10,t:"E, apesar de tudo isso, Judá, a sua irmã traidora, não voltou para mim de todo o coração, mas só com fingimento, oráculo do Senhor."},
{v:11,t:"O Senhor me disse: Israel, a infiel, mostrou-se mais justa do que Judá, a traidora.",np:1},
{s:"Convite à conversão"},
{v:12,l:["Vai e proclama estas palavras voltado para o norte e dize:","Volta, Israel, a infiel,","oráculo do Senhor;","não voltarei para vós um rosto irado,","pois eu sou misericordioso,","oráculo do Senhor,","e não guardo rancor para sempre."],n:"No hebraico há um jogo de palavras entre voltar (shuv) e infiel (meshuvá)."},
{v:13,l:["Reconhece somente a tua culpa:","te revoltaste contra o Senhor, teu Deus,","espalhaste os teus caminhos para os estrangeiros","debaixo de toda árvore frondosa,","e não ouvistes a minha voz,","oráculo do Senhor."],np:1},
{v:14,t:"Voltai, filhos rebeldes, oráculo do Senhor, pois eu sou o vosso esposo; tomarei um de cada cidade e dois de cada família e vos conduzirei a Sião.",np:1,n:"Esposo: o verbo hebraico (baal) significa ser senhor e ser marido; a Nova Vulgata traduz: eu sou o vosso Senhor."},
{v:15,t:"Eu vos darei pastores segundo o meu coração, que vos apascentarão com inteligência e sabedoria."},
{v:16,t:"E, quando vos tiverdes multiplicado e crescido na terra, naqueles dias, oráculo do Senhor, não se falará mais da arca da aliança do Senhor; ninguém pensará mais nela, ninguém se lembrará dela, ninguém sentirá a sua falta, nem se fará outra.",n:"A arca provavelmente desapareceu na destruição de 587 antes de Cristo; Jerusalém inteira será o trono do Senhor (v. 17)."},
{v:17,t:"Naquele tempo, chamarão Jerusalém Trono do Senhor; todas as nações se reunirão nela, em nome do Senhor, em Jerusalém, e não seguirão mais a obstinação do seu coração perverso."},
{v:18,t:"Naqueles dias, a casa de Judá se unirá à casa de Israel, e virão juntas da terra do norte para a terra que dei como herança aos vossos pais."},
{s:"O pai e os filhos"},
{v:19,l:["Eu tinha dito:","Como gostaria de te colocar entre os meus filhos","e te dar uma terra desejável,","a herança mais bela entre as nações!","E pensava: Vós me chamareis Meu pai","e não vos afastareis de mim."]},
{v:20,l:["Mas, como uma mulher trai o seu companheiro,","assim vós me traístes, casa de Israel,","oráculo do Senhor."],np:1},
{v:21,l:["Ouve-se uma voz sobre as colinas:","o choro e as súplicas dos filhos de Israel,","porque perverteram o seu caminho","e se esqueceram do Senhor, seu Deus."],np:1},
{v:22,l:["Voltai, filhos rebeldes,","e eu curarei as vossas rebeldias.","Eis-nos aqui, vimos a ti,","pois tu és o Senhor, nosso Deus."],np:1},
{v:23,l:["Na verdade, são mentira as colinas","e o tumulto dos montes;","na verdade, está no Senhor, nosso Deus,","a salvação de Israel."],np:1},
{v:24,l:["A Vergonha devorou o fruto do trabalho dos nossos pais,","desde a nossa juventude:","as suas ovelhas e os seus bois,","os seus filhos e as suas filhas."],np:1,n:"A Vergonha: nome de desprezo dado a Baal (compare 11,13)."},
{v:25,l:["Deitemo-nos na nossa vergonha,","e que a nossa desonra nos cubra,","pois pecamos contra o Senhor, nosso Deus,","nós e os nossos pais,","desde a nossa juventude até hoje,","e não ouvimos a voz do Senhor, nosso Deus."],np:1}
];

window.TEXTOS_SEED["jeremias"][4] = [
{s:"A verdadeira conversão"},
{v:1,l:["Se voltares, Israel,","oráculo do Senhor,","é para mim que deves voltar;","se tirares da minha presença as tuas abominações,","não andarás mais errante,"]},
{v:2,l:["e se jurares: Pela vida do Senhor!,","com verdade, com direito e com justiça,","então as nações se abençoarão nele","e nele se gloriarão."],np:1,n:"Compare Gênesis 12,3."},
{v:3,l:["Pois assim diz o Senhor","aos homens de Judá e a Jerusalém:","Lavrai para vós um campo novo","e não semeeis entre os espinhos."],np:1},
{v:4,l:["Circuncidai-vos para o Senhor,","tirai o prepúcio do vosso coração,","homens de Judá e habitantes de Jerusalém,","para que a minha ira não irrompa como fogo","e arda sem que ninguém a possa apagar,","por causa da maldade das vossas ações."],np:1,n:"Compare Deuteronômio 10,16 e Romanos 2,29."},
{s:"A invasão vinda do norte"},
{v:5,l:["Anunciai em Judá,","proclamai em Jerusalém,","dizei: Tocai a trombeta pela terra,","gritai com toda a força e dizei:","Reuni-vos, e entremos nas cidades fortificadas!"]},
{v:6,l:["Erguei um estandarte na direção de Sião,","fugi, não pareis,","pois faço vir do norte a desgraça","e uma grande ruína."],np:1},
{v:7,l:["O leão saiu da sua toca,","o destruidor das nações se pôs em marcha,","saiu do seu lugar","para reduzir a tua terra a um deserto:","as tuas cidades serão arrasadas","e ficarão sem habitantes."],np:1},
{v:8,l:["Por isso vesti-vos de saco,","lamentai-vos e gemei,","pois a ira ardente do Senhor","não se afastou de nós."],np:1},
{v:9,l:["Naquele dia,","oráculo do Senhor,","perderão a coragem o rei","e os chefes,","os sacerdotes ficarão aterrados,","e os profetas, estupefatos."],np:1},
{v:10,l:["Então eu disse: Ah, Senhor Deus!","Na verdade enganaste completamente este povo e Jerusalém,","dizendo: Tereis paz!","E eis que a espada chega à garganta."],np:1,n:"Nota do tradutor: o profeta atribui a Deus o engano dos falsos profetas, que prometiam a paz (compare 14,13–14); é a queixa de quem não compreende, e o texto não a atenua."},
{v:11,l:["Naquele tempo se dirá a este povo e a Jerusalém:","Um vento ardente das colinas do deserto","avança contra a filha do meu povo,","não para joeirar nem para limpar;"],np:1},
{v:12,l:["um vento forte demais para isso vem da minha parte.","Agora também eu pronunciarei contra eles as minhas sentenças."],np:1},
{v:13,l:["Eis que ele sobe como as nuvens,","os seus carros são como o furacão,","os seus cavalos, mais velozes que as águias.","Ai de nós, estamos perdidos!"],np:1},
{v:14,l:["Lava o teu coração da maldade,","Jerusalém, para seres salva;","até quando abrigarás dentro de ti","os teus pensamentos iníquos?"],np:1},
{v:15,l:["Pois uma voz anuncia desde Dã,","e proclama a desgraça desde as montanhas de Efraim."],np:1},
{v:16,l:["Avisai as nações: Eis que chegam!","Anunciai a Jerusalém:","Sitiantes vêm de uma terra distante","e lançam os seus gritos contra as cidades de Judá;"],np:1},
{v:17,l:["como guardas de um campo, cercam-na por todos os lados,","porque ela se rebelou contra mim,","oráculo do Senhor."],np:1},
{v:18,l:["O teu comportamento e as tuas ações","te trouxeram isto;","esta é a tua desgraça: como é amarga,","como te atinge o coração!"],np:1},
{s:"A angústia do profeta"},
{v:19,l:["As minhas entranhas, as minhas entranhas! Contorço-me de dor!","As paredes do meu coração!","O meu coração se agita dentro de mim;","não posso calar-me,","pois ouvi o som da trombeta,","o grito de guerra."]},
{v:20,l:["Anuncia-se desastre sobre desastre,","pois toda a terra está devastada;","de repente as minhas tendas foram destruídas,","num instante, as minhas lonas."],np:1},
{v:21,l:["Até quando verei o estandarte","e ouvirei o som da trombeta?"],np:1},
{v:22,l:["Pois o meu povo é insensato,","não me conhece;","são filhos tolos,","sem inteligência;","são hábeis para fazer o mal,","mas não sabem fazer o bem."],np:1},
{s:"A visão do caos"},
{v:23,l:["Olhei para a terra, e eis que era caos e vazio;","para os céus, e não havia luz."],n:"Caos e vazio: em hebraico tohu e bohu, as palavras de Gênesis 1,2; a criação parece voltar ao estado anterior à luz."},
{v:24,l:["Olhei para os montes, e eis que tremiam,","e todas as colinas oscilavam."],np:1},
{v:25,l:["Olhei, e eis que não havia ninguém,","e todas as aves do céu tinham fugido."],np:1},
{v:26,l:["Olhei, e eis que o pomar era um deserto,","e todas as suas cidades estavam arrasadas","diante do Senhor, diante da sua ira ardente."],np:1},
{v:27,l:["Pois assim diz o Senhor:","Toda a terra ficará desolada,","mas não farei o extermínio total."],np:1},
{v:28,l:["Por isso a terra estará de luto,","e os céus lá em cima se escurecerão,","porque eu falei, eu decidi,","e não me arrependo nem volto atrás."],np:1},
{v:29,l:["Ao grito dos cavaleiros e dos arqueiros","foge toda a cidade;","entram nas moitas","e sobem aos rochedos;","todas as cidades estão abandonadas,","e ninguém habita nelas."],np:1},
{v:30,l:["E tu, devastada, que farás?","Ainda que te vistas de escarlate,","ainda que te enfeites com joias de ouro","e alargues os olhos com pintura,","em vão te embelezas;","os teus amantes te desprezam,","procuram a tua vida."],np:1},
{v:31,l:["Ouço gritos como de mulher em trabalho de parto,","angústia como de quem dá à luz o primeiro filho:","é a voz da filha de Sião, que ofega","e estende as mãos:","Ai de mim! Desfaleço","diante dos assassinos!"],np:1}
];

window.TEXTOS_SEED["jeremias"][5] = [
{s:"Nem um justo em Jerusalém"},
{v:1,l:["Percorrei as ruas de Jerusalém,","olhai e informai-vos,","procurai nas suas praças","se encontrais um homem,","um só que pratique o direito e busque a fidelidade,","e eu perdoarei a cidade."],n:"Compare a intercessão de Abraão por Sodoma (Gênesis 18,22–32)."},
{v:2,l:["Mesmo quando dizem: Pela vida do Senhor!,","juram falsamente."],np:1},
{v:3,l:["Senhor, não é a fidelidade que os teus olhos procuram?","Tu os feriste, mas não sentiram dor;","tu os esmagaste, mas recusaram a correção;","endureceram o rosto mais que a pedra,","recusaram converter-se."],np:1},
{v:4,l:["Eu pensava: São os pobres, que agem como insensatos,","porque não conhecem o caminho do Senhor,","o direito do seu Deus."],np:1},
{v:5,l:["Irei aos grandes","e lhes falarei;","eles, sim, conhecem o caminho do Senhor,","o direito do seu Deus.","Mas também eles, todos juntos, quebraram o jugo,","romperam as correntes."],np:1},
{v:6,l:["Por isso o leão da floresta os fere,","o lobo da estepe os devasta,","o leopardo vigia as suas cidades:","todo aquele que sair delas será despedaçado,","pois multiplicaram as suas transgressões,","aumentaram as suas infidelidades."],np:1},
{v:7,l:["Como poderia eu perdoar-te?","Os teus filhos me abandonaram","e juraram por quem não é Deus;","eu os saciei, e eles cometeram adultério","e se aglomeravam na casa da prostituta."]},
{v:8,l:["São cavalos bem nutridos e fogosos:","cada um relincha pela mulher do seu próximo."],np:1},
{v:9,l:["Não os castigaria eu por estas coisas,","oráculo do Senhor,","e não me vingaria de uma nação como esta?"],np:1},
{v:10,l:["Subi às suas vinhas e destruí,","mas não façais o extermínio total;","arrancai os seus ramos,","pois não são do Senhor."],np:1},
{v:11,l:["Pois a casa de Israel e a casa de Judá","me foram completamente infiéis,","oráculo do Senhor."],np:1},
{v:12,l:["Renegaram o Senhor","e disseram: Ele não conta;","nenhuma desgraça virá sobre nós,","não veremos nem a espada nem a fome."],np:1},
{v:13,l:["Os profetas não passam de vento,","e a palavra não está neles.","Que isto lhes aconteça!"],np:1},
{v:14,l:["Por isso assim diz o Senhor, o Deus dos exércitos:","Porque falaram assim,","eis que farei das minhas palavras na tua boca um fogo,","e deste povo, a lenha,","e o fogo os devorará."],np:1},
{v:15,l:["Eis que vou trazer contra vós uma nação de longe,","casa de Israel,","oráculo do Senhor;","uma nação invencível,","uma nação antiga,","uma nação cuja língua não conheces","e cuja fala não compreendes."],np:1},
{v:16,l:["A sua aljava é um sepulcro aberto;","todos eles são guerreiros valentes."],np:1},
{v:17,l:["Ela devorará a tua colheita e o teu pão,","devorará os teus filhos e as tuas filhas,","devorará as tuas ovelhas e os teus bois,","devorará a tua vinha e a tua figueira;","destruirá pela espada as cidades fortificadas","em que confias."],np:1},
{v:18,l:["Mas nem naqueles dias,","oráculo do Senhor,","farei convosco o extermínio total."],np:1},
{v:19,t:"E, quando perguntarem: Por que o Senhor, nosso Deus, nos fez tudo isto?, tu lhes responderás: Assim como me abandonastes e servistes deuses estrangeiros na vossa terra, assim servireis a estrangeiros numa terra que não é vossa.",np:1},
{s:"Um povo sem coração"},
{v:20,l:["Anunciai isto na casa de Jacó","e proclamai-o em Judá, dizendo:"]},
{v:21,l:["Ouvi isto, povo insensato e sem coração,","que tem olhos e não vê,","que tem ouvidos e não ouve."],np:1,n:"Compare Marcos 8,18."},
{v:22,l:["Não me temereis,","oráculo do Senhor,","não tremereis diante de mim,","que pus a areia como limite para o mar,","fronteira eterna que ele não ultrapassa?","Agitam-se as suas ondas, mas não podem vencê-la;","rugem, mas não a ultrapassam."],np:1},
{v:23,l:["Mas este povo tem um coração rebelde e obstinado;","eles se desviaram e foram embora,"],np:1},
{v:24,l:["e não disseram no seu coração:","Temamos o Senhor, nosso Deus,","que dá a chuva no tempo certo,","a do outono e a da primavera,","e nos garante as semanas","fixadas para a colheita."],np:1},
{v:25,l:["As vossas iniquidades desviaram estas coisas,","e os vossos pecados vos privaram dos bens,"],np:1},
{v:26,l:["pois há no meu povo homens ímpios,","que espreitam como caçadores de pássaros agachados,","armam ciladas","para apanhar homens."],np:1},
{v:27,l:["Como uma gaiola cheia de pássaros,","assim as suas casas estão cheias de fraudes;","por isso se tornaram grandes e ricos,"],np:1},
{v:28,l:["engordaram, estão reluzentes;","ultrapassaram toda medida no mal.","Não defendem o direito,","o direito do órfão, para que prospere,","nem fazem justiça aos pobres."],np:1},
{v:29,l:["Não os castigaria eu por estas coisas,","oráculo do Senhor,","e não me vingaria de uma nação como esta?"],np:1},
{v:30,l:["Uma coisa espantosa e horrível","aconteceu na terra:"],np:1},
{v:31,l:["os profetas profetizam a mentira,","os sacerdotes governam a seu bel-prazer,","e o meu povo gosta disso.","Mas que fareis quando chegar o fim?"],np:1}
];

window.TEXTOS_SEED["jeremias"][6] = [
{s:"O cerco de Jerusalém"},
{v:1,l:["Fugi, filhos de Benjamim,","do meio de Jerusalém!","Em Técua tocai a trombeta,","sobre Bet-Carem erguei um sinal,","pois do norte ameaça a desgraça","e uma grande ruína."],n:"No hebraico, jogo de palavras entre Técua e tocai (tiqeú)."},
{v:2,l:["A formosa e delicada,","a filha de Sião, eu a reduzirei ao silêncio."],np:1},
{v:3,l:["Contra ela vêm pastores com os seus rebanhos;","armam as suas tendas ao redor dela,","e cada um apascenta a sua parte."],np:1},
{v:4,l:["Declarai contra ela a guerra santa!","De pé! Ataquemos ao meio-dia!","Ai de nós, o dia declina,","as sombras da tarde se alongam!"],np:1},
{v:5,l:["De pé! Ataquemos de noite","e destruamos os seus palácios!"],np:1},
{v:6,l:["Pois assim diz o Senhor dos exércitos:","Cortai as suas árvores","e levantai contra Jerusalém uma rampa de cerco;","é a cidade que deve ser castigada:","dentro dela só há opressão."],np:1},
{v:7,l:["Como a fonte faz jorrar as suas águas,","assim ela faz jorrar a sua maldade;","nela só se ouve violência e destruição;","diante de mim há sempre doenças e feridas."],np:1},
{v:8,l:["Deixa-te corrigir, Jerusalém,","para que a minha alma não se afaste de ti,","para que eu não faça de ti um deserto,","uma terra desabitada."],np:1},
{v:9,l:["Assim diz o Senhor dos exércitos:","Rebuscarão como numa vinha","o resto de Israel.","Passa de novo a mão,","como o vindimador sobre os ramos."],np:1},
{v:10,l:["A quem falarei, a quem advertirei, para que me ouçam?","Eis que os seus ouvidos são incircuncisos,","e não conseguem prestar atenção;","eis que a palavra do Senhor se tornou para eles um motivo de zombaria,","e não gostam dela."],np:1},
{v:11,l:["Por isso estou cheio da ira do Senhor,","canso-me de contê-la.","Derrama-a sobre a criança na rua","e sobre o grupo dos jovens reunidos;","pois serão presos o marido com a mulher,","o velho com o homem cheio de dias."],np:1},
{v:12,l:["As suas casas passarão a outros,","os campos e as mulheres também,","pois estenderei a minha mão","sobre os habitantes da terra,","oráculo do Senhor."],np:1},
{v:13,l:["Pois, do menor ao maior,","todos correm atrás do lucro;","do profeta ao sacerdote,","todos praticam a fraude."],np:1},
{v:14,l:["Tratam superficialmente a ferida do meu povo,","dizendo: Paz, paz!","E não há paz."],np:1},
{v:15,l:["Deveriam envergonhar-se, pois praticaram abominações;","mas não sentem vergonha nenhuma,","não sabem o que é corar.","Por isso cairão com os que caem;","no tempo do castigo tropeçarão,","diz o Senhor."],np:1},
{s:"Os caminhos antigos"},
{v:16,l:["Assim diz o Senhor:","Parai nos caminhos e olhai,","perguntai pelas veredas antigas,","qual é o bom caminho, e andai por ele,","e encontrareis descanso para as vossas almas.","Mas eles disseram: Não andaremos!"],n:"Compare Mateus 11,29."},
{v:17,l:["Pus sentinelas sobre vós:","Prestai atenção ao som da trombeta!","Mas eles disseram: Não prestaremos atenção!"],np:1},
{v:18,l:["Por isso ouvi, nações,","e tu, assembleia, reconhece","o que vou fazer com eles."],np:1},
{v:19,l:["Ouve, terra: Eis que vou trazer a desgraça sobre este povo,","fruto dos seus pensamentos,","pois não prestaram atenção às minhas palavras","e rejeitaram a minha instrução."],np:1},
{v:20,l:["Que me importa o incenso que vem de Sabá,","e a cana aromática de uma terra distante?","Os vossos holocaustos não me agradam,","os vossos sacrifícios não me dão prazer."],np:1},
{v:21,l:["Por isso assim diz o Senhor:","Eis que porei tropeços diante deste povo;","neles tropeçarão pais e filhos juntos,","o vizinho e o amigo perecerão."],np:1},
{s:"O povo que vem do norte"},
{v:22,l:["Assim diz o Senhor:","Eis que um povo vem da terra do norte,","uma grande nação se levanta dos confins da terra;"]},
{v:23,l:["empunham o arco e a lança;","são cruéis e não têm piedade;","o seu tropel é como o rugido do mar;","montam cavalos,","alinhados como um só homem para a batalha","contra ti, filha de Sião."],np:1},
{v:24,l:["Ouvimos a notícia;","as nossas mãos desfalecem,","a angústia se apodera de nós,","dores como de mulher em trabalho de parto."],np:1},
{v:25,l:["Não saiais para o campo,","não andeis pelo caminho,","pois lá está a espada do inimigo,","terror por todos os lados."],np:1},
{v:26,l:["Filha do meu povo, veste-te de saco","e revolve-te na cinza;","faze luto como por um filho único,","uma lamentação amarga,","pois de repente o devastador cairá sobre nós."],np:1},
{s:"O profeta, provador do povo"},
{v:27,l:["Eu te pus no meio do meu povo como provador de metais,","para que conheças e proves o seu caminho."]},
{v:28,l:["Todos eles são rebeldes obstinados,","andam espalhando calúnias;","são bronze e ferro,","todos eles são corruptos."],np:1},
{v:29,l:["O fole sopra no fogo,","o chumbo se consome;","em vão o fundidor trabalha,","pois as escórias não se separam."],np:1},
{v:30,l:["Chamai-os prata rejeitada,","pois o Senhor os rejeitou."],np:1}
];

window.TEXTOS_SEED["jeremias"][7] = [
{s:"O discurso no templo"},
{v:1,t:"Palavra que o Senhor dirigiu a Jeremias:",n:"O mesmo discurso é narrado em 26,1–19, no início do reinado de Joaquim, por volta de 609 antes de Cristo."},
{v:2,t:"Põe-te à porta da casa do Senhor e proclama ali esta palavra: Ouvi a palavra do Senhor, todos vós, homens de Judá, que entrais por estas portas para adorar o Senhor."},
{v:3,t:"Assim diz o Senhor dos exércitos, o Deus de Israel: Endireitai os vossos caminhos e as vossas ações, e eu vos farei habitar neste lugar."},
{v:4,t:"Não confieis em palavras mentirosas, dizendo: É o templo do Senhor, o templo do Senhor, o templo do Senhor!"},
{v:5,t:"Pois, se endireitardes de verdade os vossos caminhos e as vossas ações, se praticardes de verdade a justiça entre um homem e o seu próximo,"},
{v:6,t:"se não oprimirdes o estrangeiro, o órfão e a viúva, se não derramardes sangue inocente neste lugar e não correrdes atrás de outros deuses para a vossa desgraça,"},
{v:7,t:"então eu vos farei habitar neste lugar, na terra que dei aos vossos pais, desde sempre e para sempre."},
{v:8,t:"Mas vós confiais em palavras mentirosas, que não servem para nada.",np:1},
{v:9,t:"O quê? Roubais, matais, cometeis adultério, jurais falso, queimais incenso a Baal e correis atrás de outros deuses que não conheceis,"},
{v:10,t:"e depois vindes apresentar-vos diante de mim, nesta casa sobre a qual é invocado o meu nome, e dizeis: Estamos salvos!, para continuar a praticar todas essas abominações?"},
{v:11,t:"Será que esta casa, sobre a qual é invocado o meu nome, se tornou aos vossos olhos um covil de ladrões? Eu também vejo tudo isso, oráculo do Senhor.",n:"Jesus cita estas palavras ao expulsar os vendedores do templo (Mateus 21,13)."},
{v:12,t:"Ide, pois, ao meu santuário que estava em Silo, onde no princípio fiz habitar o meu nome, e vede o que lhe fiz por causa da maldade do meu povo Israel.",n:"O santuário de Silo foi destruído, provavelmente pelos filisteus, no tempo de Samuel (compare 1 Samuel 4)."},
{v:13,t:"E agora, porque praticastes todas essas ações, oráculo do Senhor, e, quando vos falei insistentemente e sem cessar, não ouvistes, e, quando vos chamei, não respondestes,"},
{v:14,t:"farei a esta casa, sobre a qual é invocado o meu nome e na qual confiais, e ao lugar que dei a vós e aos vossos pais, o mesmo que fiz a Silo;"},
{v:15,t:"e vos expulsarei da minha presença, como expulsei todos os vossos irmãos, toda a descendência de Efraim."},
{s:"O culto da Rainha do céu"},
{v:16,t:"Quanto a ti, não intercedas por este povo, não levantes por eles súplica nem oração, não insistas comigo, pois não te ouvirei."},
{v:17,t:"Não vês o que eles fazem nas cidades de Judá e nas ruas de Jerusalém?"},
{v:18,t:"Os filhos recolhem a lenha, os pais acendem o fogo e as mulheres amassam a farinha, para fazer bolos para a Rainha do céu; e oferecem libações a outros deuses, para me ofenderem.",n:"A Rainha do céu: a deusa Astarte, ou Ishtar, cultuada sobretudo pelas mulheres (compare 44,15–19)."},
{v:19,t:"É a mim que ofendem?, oráculo do Senhor. Não é antes a si mesmos, para a sua própria vergonha?"},
{v:20,t:"Por isso assim diz o Senhor Deus: Eis que a minha ira e o meu furor vão se derramar sobre este lugar, sobre os homens e sobre os animais, sobre as árvores do campo e sobre os frutos da terra; ela arderá e não se apagará."},
{s:"Obediência, e não sacrifícios"},
{v:21,t:"Assim diz o Senhor dos exércitos, o Deus de Israel: Acrescentai os vossos holocaustos aos vossos sacrifícios e comei a carne!",n:"Ironia: os holocaustos eram queimados inteiros; o Senhor diz que podem comê-los, pois não os aceita."},
{v:22,t:"Pois, quando tirei os vossos pais da terra do Egito, não lhes falei nem lhes dei ordens a respeito de holocaustos e sacrifícios."},
{v:23,t:"Mas esta foi a ordem que lhes dei: Escutai a minha voz, e eu serei o vosso Deus, e vós sereis o meu povo; andai em todo o caminho que eu vos ordenar, para que sejais felizes."},
{v:24,t:"Mas eles não escutaram nem deram ouvidos; seguiram os desígnios e a obstinação do seu coração perverso, e andaram para trás e não para a frente,"},
{v:25,t:"desde o dia em que os vossos pais saíram da terra do Egito até hoje. Eu vos enviei todos os meus servos, os profetas, todos os dias, com insistência;"},
{v:26,t:"mas não me escutaram nem deram ouvidos; endureceram a cerviz e agiram pior que os seus pais."},
{v:27,t:"Tu lhes dirás todas estas palavras, mas eles não te escutarão; tu os chamarás, mas eles não te responderão."},
{v:28,t:"Então lhes dirás: Esta é a nação que não escutou a voz do Senhor, seu Deus, nem aceitou a correção. A fidelidade desapareceu, foi arrancada da sua boca."},
{v:29,l:["Corta a tua cabeleira e joga-a fora,","entoa nas colinas um lamento,","pois o Senhor rejeitou","e abandonou a geração que provocou a sua ira."],np:1,n:"Cortar os cabelos: sinal de luto."},
{s:"O vale da Matança"},
{v:30,t:"Pois os filhos de Judá fizeram o que é mau aos meus olhos, oráculo do Senhor; puseram as suas abominações na casa sobre a qual é invocado o meu nome, para contaminá-la;"},
{v:31,t:"e construíram os lugares altos de Tofet, no vale de Ben-Enom, para queimar no fogo os seus filhos e as suas filhas: coisa que eu não ordenei nem me passou pela mente.",n:"Ben-Enom: o vale ao sul de Jerusalém, de cujo nome veio a palavra Geena."},
{v:32,t:"Por isso eis que virão dias, oráculo do Senhor, em que não se dirá mais Tofet nem vale de Ben-Enom, mas vale da Matança; e sepultarão em Tofet, por falta de outro lugar."},
{v:33,t:"Os cadáveres deste povo servirão de alimento às aves do céu e aos animais da terra, e não haverá quem os espante."},
{v:34,t:"Farei cessar nas cidades de Judá e nas ruas de Jerusalém a voz da alegria e a voz do júbilo, a voz do noivo e a voz da noiva, pois a terra se tornará uma ruína."}
];

window.TEXTOS_SEED["jeremias"][8] = [
{s:"Os ossos desenterrados"},
{v:1,t:"Naquele tempo, oráculo do Senhor, tirarão dos seus sepulcros os ossos dos reis de Judá, os ossos dos seus chefes, os ossos dos sacerdotes, os ossos dos profetas e os ossos dos habitantes de Jerusalém;"},
{v:2,t:"e os estenderão diante do sol, da lua e de todo o exército do céu, que eles amaram, serviram, seguiram, consultaram e adoraram; não serão recolhidos nem sepultados: ficarão como esterco sobre a face da terra."},
{v:3,t:"E todos os que restarem desta raça perversa, em todos os lugares para onde eu os tiver expulsado, preferirão a morte à vida, oráculo do Senhor dos exércitos."},
{s:"Um povo que não se converte"},
{v:4,l:["Tu lhes dirás: Assim diz o Senhor:","Quem cai não se levanta?","Quem se desvia não volta?"]},
{v:5,l:["Por que então este povo se desvia,","Jerusalém, num desvio sem fim?","Agarram-se à mentira","e recusam converter-se."],np:1},
{v:6,l:["Prestei atenção e escutei:","eles não falam com retidão;","ninguém se arrepende da sua maldade,","dizendo: Que fiz eu?","Todos voltam à sua corrida,","como o cavalo que se lança na batalha."],np:1},
{v:7,l:["Até a cegonha no céu","conhece as suas estações;","a rola, a andorinha e o grou","observam o tempo da sua volta;","mas o meu povo não conhece","o direito do Senhor."],np:1},
{v:8,l:["Como podeis dizer: Somos sábios,","e a lei do Senhor está conosco?","Na verdade, a pena mentirosa dos escribas","a transformou em mentira."],np:1},
{v:9,l:["Os sábios ficarão envergonhados,","aterrados e apanhados;","pois rejeitaram a palavra do Senhor:","que sabedoria podem ter?"],np:1},
{v:10,l:["Por isso darei as suas mulheres a outros,","os seus campos aos conquistadores,","pois, do menor ao maior,","todos correm atrás do lucro;","do profeta ao sacerdote,","todos praticam a fraude."],np:1},
{v:11,l:["Tratam superficialmente a ferida","da filha do meu povo,","dizendo: Paz, paz!","E não há paz."],np:1},
{v:12,l:["Deveriam envergonhar-se, pois praticaram abominações;","mas não sentem vergonha nenhuma,","não sabem o que é corar.","Por isso cairão com os que caem;","no tempo do castigo tropeçarão,","diz o Senhor."],np:1},
{v:13,l:["Eu os recolherei para acabar com eles,","oráculo do Senhor;","não há uvas na videira,","não há figos na figueira,","até as folhas murcharam;","e o que lhes dei passará a outros."],np:1,n:"O último verso é obscuro no hebraico."},
{v:14,l:["Por que ficamos sentados?","Reuni-vos, entremos nas cidades fortificadas","e ali pereçamos,","pois o Senhor, nosso Deus, nos condenou à morte","e nos deu a beber água envenenada,","porque pecamos contra o Senhor."],np:1},
{v:15,l:["Esperávamos a paz, e nada de bom;","o tempo da cura, e eis o terror."],np:1},
{v:16,l:["Desde Dã se ouve o resfolegar dos seus cavalos;","ao som do relinchar dos seus garanhões","toda a terra treme;","eles vêm e devoram a terra e tudo o que ela contém,","a cidade e os seus habitantes."],np:1},
{v:17,l:["Pois eis que vou mandar contra vós","serpentes venenosas,","contra as quais não há encantamento,","e elas vos morderão,","oráculo do Senhor."],np:1},
{s:"O lamento do profeta"},
{v:18,l:["A minha alegria se foi, a dor se apodera de mim,","o meu coração desfalece."]},
{v:19,l:["Eis o grito da filha do meu povo","de uma terra distante:","Não está o Senhor em Sião?","Não está nela o seu rei?","Por que me provocaram com os seus ídolos,","com as vaidades estrangeiras?"],np:1},
{v:20,l:["Passou a colheita, acabou o verão,","e nós não fomos salvos."],np:1},
{v:21,l:["Pela ferida da filha do meu povo","estou ferido, estou de luto;","o espanto se apoderou de mim."],np:1},
{v:22,l:["Não há bálsamo em Galaad?","Não há médico ali?","Por que então não se cura","a ferida da filha do meu povo?"],np:1},
{v:23,l:["Quem dera a minha cabeça fosse uma fonte de água,","e os meus olhos, uma fonte de lágrimas,","para eu chorar dia e noite","os mortos da filha do meu povo!"],np:1,n:"Em outras Bíblias, 9,1."}
];

window.TEXTOS_SEED["jeremias"][9] = [
{s:"A língua mentirosa"},
{v:1,l:["Quem me dera ter no deserto","uma pousada de viajantes!","Eu deixaria o meu povo","e me afastaria dele;","pois todos são adúlteros,","um bando de traidores."],n:"Em outras Bíblias, 9,2."},
{v:2,l:["Eles retesam a língua como um arco;","é a mentira, e não a verdade,","que domina na terra;","vão de maldade em maldade","e não me conhecem,","oráculo do Senhor."],np:1},
{v:3,l:["Que cada um se guarde do seu amigo,","e ninguém confie no seu irmão,","pois todo irmão engana como Jacó,","e todo amigo espalha calúnias."],np:1,n:"Jogo de palavras com o nome de Jacó, o que suplanta (Gênesis 27,36)."},
{v:4,l:["Cada um engana o seu próximo,","e ninguém diz a verdade;","acostumaram a língua a dizer mentiras,","cansam-se de praticar o mal."],np:1},
{v:5,l:["Vives no meio da fraude;","por causa da fraude recusam conhecer-me,","oráculo do Senhor."],np:1},
{v:6,l:["Por isso assim diz o Senhor dos exércitos:","Eis que vou fundi-los e prová-los;","pois que mais posso fazer","diante da filha do meu povo?"],np:1},
{v:7,l:["A língua deles é uma flecha mortal,","só diz mentiras;","com a boca falam de paz com o próximo,","mas no coração lhe armam ciladas."],np:1},
{v:8,l:["Não os castigaria eu por estas coisas,","oráculo do Senhor,","e não me vingaria de uma nação como esta?"],np:1},
{s:"Lamento sobre Jerusalém"},
{v:9,l:["Sobre os montes erguerei o choro e o lamento,","e sobre as pastagens do deserto a lamentação,","pois estão queimadas, e ninguém passa por elas,","não se ouve o mugido do gado;","desde as aves do céu até os animais,","todos fugiram, foram embora."]},
{v:10,l:["Farei de Jerusalém um monte de ruínas,","um covil de chacais,","e das cidades de Judá um deserto,","sem habitantes."],np:1},
{v:11,l:["Quem é o homem sábio que compreenda isto?","A quem falou a boca do Senhor,","para que o anuncie?","Por que a terra pereceu,","foi queimada como o deserto,","sem ninguém que passe por ela?"],np:1},
{v:12,t:"O Senhor disse: Porque abandonaram a minha lei, que eu lhes tinha dado, não escutaram a minha voz e não a seguiram,",np:1},
{v:13,t:"mas seguiram a obstinação do seu coração e os baals, como os seus pais lhes ensinaram,"},
{v:14,t:"por isso assim diz o Senhor dos exércitos, o Deus de Israel: Eis que vou dar de comer a este povo absinto e de beber água envenenada;"},
{v:15,t:"vou dispersá-los entre nações que nem eles nem os seus pais conheceram, e mandarei atrás deles a espada, até exterminá-los."},
{s:"As carpideiras"},
{v:16,l:["Assim diz o Senhor dos exércitos:","Prestai atenção, chamai as carpideiras, que venham;","mandai buscar as mais hábeis, que se apressem!"],n:"Carpideiras: mulheres pagas para chorar nos funerais."},
{v:17,l:["Que se apressem","e entoem sobre nós um lamento;","que os nossos olhos se desfaçam em lágrimas,","e as nossas pálpebras destilem água."],np:1},
{v:18,l:["Pois de Sião se ouve um grito de lamento:","Como estamos arruinados,","cobertos de vergonha!","Pois tivemos de abandonar a terra,","porque derrubaram as nossas moradas."],np:1},
{v:19,l:["Ouvi, pois, mulheres, a palavra do Senhor;","que os vossos ouvidos recebam a palavra da sua boca;","ensinai às vossas filhas o lamento,","e cada uma à sua vizinha a elegia."],np:1},
{v:20,l:["Pois a morte subiu pelas nossas janelas,","entrou nos nossos palácios,","para exterminar as crianças da rua","e os jovens das praças."],np:1},
{v:21,l:["Fala: Assim diz o Senhor:","Os cadáveres dos homens jazerão","como esterco sobre a face do campo,","como o feixe atrás do ceifeiro,","e não há quem o recolha."],np:1},
{s:"A verdadeira glória"},
{v:22,l:["Assim diz o Senhor:","Que o sábio não se glorie da sua sabedoria,","nem o forte da sua força,","nem o rico da sua riqueza;"]},
{v:23,l:["mas quem quiser gloriar-se glorie-se disto:","de ter inteligência e de me conhecer,","de saber que eu sou o Senhor, que pratico a bondade,","o direito e a justiça na terra;","pois é disso que eu gosto,","oráculo do Senhor."],np:1,n:"Paulo cita este versículo em 1 Coríntios 1,31 e 2 Coríntios 10,17."},
{v:24,t:"Eis que virão dias, oráculo do Senhor, em que castigarei todos os circuncidados na carne:",np:1},
{v:25,t:"o Egito, Judá, Edom, os amonitas, Moab e todos os que cortam o cabelo nas têmporas e habitam no deserto; pois todas essas nações são incircuncisas, e toda a casa de Israel é incircuncisa de coração.",n:"Cortar o cabelo nas têmporas: costume de tribos árabes, proibido aos israelitas (Levítico 19,27)."}
];

window.TEXTOS_SEED["jeremias"][10] = [
{s:"Os ídolos e o Deus verdadeiro"},
{v:1,t:"Ouvi a palavra que o Senhor vos dirige, casa de Israel."},
{v:2,l:["Assim diz o Senhor:","Não aprendais o caminho das nações,","não vos assusteis com os sinais do céu,","com os quais as nações se assustam."]},
{v:3,l:["Pois os costumes dos povos são vazios:","cortam uma árvore na floresta,","obra das mãos do artesão, trabalhada com o formão;"],np:1},
{v:4,l:["enfeitam-na com prata e ouro,","fixam-na com pregos e martelos,","para que não se mova."],np:1},
{v:5,l:["São como espantalhos num pepinal,","e não falam;","precisam ser carregados, porque não andam.","Não tenhais medo deles,","pois não podem fazer mal,","nem são capazes de fazer bem."],np:1},
{v:6,l:["Não há ninguém como tu, Senhor;","tu és grande,","e grande é o poder do teu nome."],np:1},
{v:7,l:["Quem não te temeria, rei das nações?","Isto te é devido,","pois entre todos os sábios das nações","e em todos os seus reinos não há ninguém como tu."],np:1},
{v:8,l:["Todos juntos são estúpidos e insensatos;","a instrução dos ídolos é madeira."],np:1},
{v:9,l:["Prata laminada trazida de Társis,","ouro de Ufaz,","obra do artesão e das mãos do ourives;","violeta e púrpura são as suas vestes;","tudo obra de artesãos."],np:1},
{v:10,l:["Mas o Senhor é o Deus verdadeiro,","ele é o Deus vivo e o rei eterno;","diante da sua ira a terra treme,","e as nações não suportam o seu furor."],np:1},
{v:11,t:"Assim lhes direis: Os deuses que não fizeram o céu e a terra desaparecerão da terra e de debaixo do céu.",np:1,n:"Este versículo está em aramaico no original: talvez uma frase que os exilados deviam dizer aos babilônios na língua deles."},
{v:12,l:["Ele fez a terra com o seu poder,","firmou o mundo com a sua sabedoria","e com a sua inteligência estendeu os céus."],np:1},
{v:13,l:["Quando ele faz ouvir a sua voz, rugem as águas no céu;","ele faz subir as nuvens desde os confins da terra,","produz os relâmpagos para a chuva","e faz sair o vento dos seus reservatórios."],np:1},
{v:14,l:["Todo homem se torna estúpido, sem conhecimento;","todo ourives se envergonha do seu ídolo,","pois as suas imagens são mentira,","e não há sopro de vida nelas."],np:1},
{v:15,l:["São vazias, obra ridícula;","no tempo do castigo perecerão."],np:1},
{v:16,l:["Não é assim a Porção de Jacó,","pois ele é o criador de todas as coisas,","e Israel é a tribo da sua herança;","Senhor dos exércitos é o seu nome."],np:1,n:"Os versículos 12–16 se repetem em 51,15–19."},
{s:"O exílio próximo"},
{v:17,l:["Recolhe do chão a tua trouxa,","tu que estás sitiada,"]},
{v:18,l:["pois assim diz o Senhor:","Eis que desta vez vou lançar fora","os habitantes da terra","e os afligirei, para que me encontrem."],np:1},
{v:19,l:["Ai de mim, por causa da minha ferida!","A minha chaga é incurável!","Mas eu disse:","Este é o meu sofrimento,","e devo suportá-lo."],np:1},
{v:20,l:["A minha tenda está destruída,","todas as minhas cordas foram arrancadas;","os meus filhos me deixaram e não existem mais;","não há ninguém que arme de novo a minha tenda","e levante as minhas lonas."],np:1},
{v:21,l:["Pois os pastores se tornaram insensatos","e não buscaram o Senhor;","por isso não tiveram êxito,","e todo o seu rebanho se dispersou."],np:1},
{v:22,l:["Ouve! Uma notícia se aproxima,","um grande tumulto vindo da terra do norte,","para reduzir as cidades de Judá a um deserto,","a um covil de chacais."],np:1},
{s:"Oração do profeta"},
{v:23,l:["Eu sei, Senhor, que o homem não é dono do seu caminho,","que não cabe ao homem que caminha","dirigir os seus passos."]},
{v:24,l:["Corrige-me, Senhor, mas com justiça,","e não na tua ira,","para não me reduzires a nada."],np:1},
{v:25,l:["Derrama a tua ira sobre as nações","que não te conhecem,","e sobre os povos","que não invocam o teu nome;","pois devoraram Jacó,","o devoraram e consumiram,","e devastaram a sua pastagem."],np:1,n:"Nota do tradutor: prece de vingança, quase idêntica ao Salmo 79,6–7; como nos salmos imprecatórios, o texto não é atenuado."}
];

window.TEXTOS_SEED["jeremias"][11] = [
{s:"A aliança quebrada"},
{v:1,t:"Palavra que o Senhor dirigiu a Jeremias:"},
{v:2,t:"Ouvi as palavras desta aliança e dizei-as aos homens de Judá e aos habitantes de Jerusalém."},
{v:3,t:"Tu lhes dirás: Assim diz o Senhor, o Deus de Israel: Maldito o homem que não escutar as palavras desta aliança,"},
{v:4,t:"que prescrevi aos vossos pais quando os tirei da terra do Egito, da fornalha de ferro, dizendo: Escutai a minha voz e fazei tudo o que vos ordeno; então sereis o meu povo, e eu serei o vosso Deus,"},
{v:5,t:"para que eu cumpra o juramento que fiz aos vossos pais, de lhes dar uma terra onde corre leite e mel, como acontece hoje. Eu respondi: Amém, Senhor!"},
{v:6,t:"O Senhor me disse: Proclama todas estas palavras nas cidades de Judá e nas ruas de Jerusalém, dizendo: Ouvi as palavras desta aliança e ponde-as em prática.",np:1},
{v:7,t:"Pois adverti solenemente os vossos pais, desde o dia em que os tirei da terra do Egito até hoje; adverti-os sem cessar, dizendo: Escutai a minha voz!"},
{v:8,t:"Mas não escutaram nem deram ouvidos; cada um seguiu a obstinação do seu coração perverso. Por isso fiz cair sobre eles todas as palavras desta aliança, que eu lhes tinha mandado cumprir e que não cumpriram."},
{v:9,t:"O Senhor me disse: Há uma conspiração entre os homens de Judá e os habitantes de Jerusalém.",np:1},
{v:10,t:"Voltaram às iniquidades dos seus antepassados, que recusaram escutar as minhas palavras; também eles correram atrás de outros deuses para servi-los. A casa de Israel e a casa de Judá romperam a minha aliança, que eu tinha feito com os seus pais."},
{v:11,t:"Por isso assim diz o Senhor: Eis que vou fazer cair sobre eles uma desgraça da qual não poderão escapar; clamarão a mim, mas não os escutarei."},
{v:12,t:"Então as cidades de Judá e os habitantes de Jerusalém irão clamar aos deuses a quem queimam incenso, mas eles não os salvarão no tempo da sua desgraça."},
{v:13,t:"Pois tens tantos deuses, ó Judá, quantas são as tuas cidades, e erguestes tantos altares à Vergonha quantas são as ruas de Jerusalém, altares para queimar incenso a Baal."},
{v:14,t:"Quanto a ti, não intercedas por este povo, não levantes por eles súplica nem oração, pois não os escutarei quando clamarem a mim na sua desgraça.",np:1},
{s:"A oliveira queimada"},
{v:15,l:["Que faz a minha amada na minha casa,","ela que tramou tantas maldades?","Acaso os votos e a carne consagrada","afastarão de ti a desgraça,","para que possas exultar?"],n:"Hebraico obscuro; a Nova Vulgata entende, como aqui: os votos e as carnes consagradas."},
{v:16,l:["Oliveira verdejante, bela, de frutos formosos:","assim o Senhor te chamava;","com um grande estrondo","ele lhe põe fogo,","e os seus ramos se queimam."],np:1},
{v:17,t:"O Senhor dos exércitos, que te plantou, decretou contra ti a desgraça, por causa da maldade que a casa de Israel e a casa de Judá cometeram, provocando-me ao queimar incenso a Baal.",np:1},
{s:"Conspiração contra Jeremias"},
{v:18,l:["O Senhor me fez saber, e eu soube;","então me mostraste as suas ações."],n:"Começam aqui as chamadas confissões de Jeremias (11,18–12,6; 15,10–21; 17,14–18; 18,18–23; 20,7–18)."},
{v:19,t:"Eu era como um cordeiro manso, levado ao matadouro, e não sabia que tramavam contra mim, dizendo: Destruamos a árvore com o seu fruto, arranquemo-lo da terra dos vivos, e que o seu nome não seja mais lembrado.",np:1,n:"Compare Isaías 53,7."},
{v:20,l:["Mas tu, Senhor dos exércitos,","que julgas com justiça, que sondas os rins e o coração,","que eu veja a tua vingança contra eles,","pois a ti confiei a minha causa."],np:1,n:"Nota do tradutor: o profeta pede a vingança divina, como nos salmos imprecatórios, e o texto não a suaviza; mas entrega a causa a Deus, sem fazer justiça por si mesmo."},
{v:21,t:"Por isso assim diz o Senhor a respeito dos homens de Anatot, que procuram a tua vida e dizem: Não profetizes em nome do Senhor, se não queres morrer pelas nossas mãos!",np:1},
{v:22,t:"Por isso assim diz o Senhor dos exércitos: Eis que vou castigá-los: os jovens morrerão pela espada, os seus filhos e as suas filhas morrerão de fome,"},
{v:23,t:"e não restará deles ninguém, pois farei cair a desgraça sobre os homens de Anatot, no ano do seu castigo."}
];

window.TEXTOS_SEED["jeremias"][12] = [
{s:"Por que prospera o caminho dos ímpios?"},
{v:1,l:["Tu és justo, Senhor, quando discuto contigo;","contudo, quero falar contigo sobre a justiça:","por que prospera o caminho dos ímpios?","Por que vivem tranquilos todos os traidores?"]},
{v:2,l:["Tu os plantas, e eles lançam raízes,","crescem e dão fruto;","tu estás perto da sua boca,","mas longe do seu íntimo."],np:1},
{v:3,l:["Mas tu, Senhor, me conheces, tu me vês","e provas que o meu coração está contigo.","Separa-os como ovelhas para o matadouro,","reserva-os para o dia da matança."],np:1},
{v:4,l:["Até quando a terra estará de luto,","e a erva de todo o campo secará?","Pela maldade dos seus habitantes","morrem os animais e as aves,","pois dizem: Ele não verá o nosso fim."],np:1},
{v:5,l:["Se, correndo com os de a pé, te cansas,","como poderás competir com os cavalos?","Se só numa terra tranquila te sentes seguro,","que farás na mata do Jordão?"],np:1},
{v:6,l:["Pois até os teus irmãos e a casa do teu pai,","até eles te traíram,","também eles gritam atrás de ti a plenos pulmões;","não confies neles,","mesmo quando te dizem coisas agradáveis."],np:1},
{s:"O lamento do Senhor pela sua herança"},
{v:7,l:["Abandonei a minha casa,","rejeitei a minha herança;","entreguei a amada da minha alma","nas mãos dos seus inimigos."]},
{v:8,l:["A minha herança se tornou para mim","como um leão na floresta;","rugiu contra mim,","por isso a detesto."],np:1},
{v:9,l:["Acaso a minha herança é para mim uma ave de muitas cores,","que as aves de rapina atacam de todos os lados?","Ide, reuni todos os animais do campo,","trazei-os para devorar!"],np:1},
{v:10,l:["Muitos pastores devastaram a minha vinha,","pisaram a minha porção;","fizeram da minha porção preciosa","um deserto desolado."],np:1},
{v:11,l:["Fizeram dela uma desolação;","desolada, ela está de luto diante de mim;","toda a terra está devastada,","e ninguém se importa com isso."],np:1},
{v:12,l:["Sobre todas as colinas nuas do deserto","chegaram os devastadores,","pois a espada do Senhor devora","de um extremo ao outro da terra;","não há paz para ninguém."],np:1},
{v:13,l:["Semearam trigo e colheram espinhos,","cansaram-se sem proveito;","envergonhai-vos das vossas colheitas,","por causa da ira ardente do Senhor."],np:1},
{s:"Os vizinhos de Israel"},
{v:14,t:"Assim diz o Senhor contra todos os meus maus vizinhos, que atacam a herança que dei ao meu povo Israel: Eis que vou arrancá-los da sua terra e arrancarei do meio deles a casa de Judá."},
{v:15,t:"Mas, depois de arrancá-los, voltarei a ter compaixão deles e os farei voltar, cada um à sua herança e cada um à sua terra."},
{v:16,t:"E, se aprenderem bem os caminhos do meu povo e jurarem pelo meu nome, dizendo: Pela vida do Senhor!, assim como ensinaram o meu povo a jurar por Baal, então serão estabelecidos no meio do meu povo."},
{v:17,t:"Mas, se não escutarem, arrancarei essa nação, a arrancarei e a destruirei, oráculo do Senhor."}
];

window.TEXTOS_SEED["jeremias"][13] = [
{s:"O cinto de linho"},
{v:1,t:"Assim me disse o Senhor: Vai comprar um cinto de linho, põe-no na cintura, mas não o molhes na água."},
{v:2,t:"Comprei o cinto, conforme a palavra do Senhor, e o pus na cintura."},
{v:3,t:"A palavra do Senhor me foi dirigida uma segunda vez:"},
{v:4,t:"Toma o cinto que compraste e que tens na cintura, levanta-te, vai até o Eufrates e esconde-o ali, na fenda de uma rocha.",n:"O Eufrates, em hebraico Perat, fica a centenas de quilômetros; talvez se trate de Pará, perto de Anatot (Josué 18,23), com um jogo de palavras."},
{v:5,t:"Fui e o escondi junto ao Eufrates, como o Senhor me tinha ordenado."},
{v:6,t:"Depois de muitos dias, o Senhor me disse: Levanta-te, vai até o Eufrates e tira dali o cinto que te mandei esconder."},
{v:7,t:"Fui até o Eufrates, cavei e tirei o cinto do lugar onde o tinha escondido; e eis que o cinto estava apodrecido, não servia para mais nada."},
{v:8,t:"Então a palavra do Senhor me foi dirigida:"},
{v:9,t:"Assim diz o Senhor: Assim farei apodrecer o orgulho de Judá e o grande orgulho de Jerusalém."},
{v:10,t:"Este povo perverso, que recusa escutar as minhas palavras, que segue a obstinação do seu coração e corre atrás de outros deuses para servi-los e adorá-los, será como este cinto, que não serve para nada."},
{v:11,t:"Pois, assim como o cinto se ajusta à cintura do homem, assim eu tinha ajustado a mim toda a casa de Israel e toda a casa de Judá, oráculo do Senhor, para que fossem o meu povo, o meu renome, o meu louvor e a minha glória; mas eles não me escutaram."},
{s:"Os jarros cheios de vinho"},
{v:12,t:"Tu lhes dirás esta palavra: Assim diz o Senhor, o Deus de Israel: Todo jarro se enche de vinho. E eles te responderão: Acaso não sabemos que todo jarro se enche de vinho?"},
{v:13,t:"Então lhes dirás: Assim diz o Senhor: Eis que vou encher de embriaguez todos os habitantes desta terra, os reis que se sentam no trono de Davi, os sacerdotes, os profetas e todos os habitantes de Jerusalém;"},
{v:14,t:"e os farei chocar-se uns contra os outros, os pais junto com os filhos, oráculo do Senhor; não terei piedade, nem pouparei, nem terei compaixão que me impeça de destruí-los."},
{s:"Advertência antes das trevas"},
{v:15,l:["Escutai e prestai atenção, não sejais orgulhosos,","pois o Senhor falou."]},
{v:16,l:["Dai glória ao Senhor, vosso Deus,","antes que ele traga as trevas,","antes que os vossos pés tropecem","nos montes, ao anoitecer;","esperareis a luz,","mas ele a transformará em sombra de morte","e a mudará em escuridão."],np:1},
{v:17,l:["Se não escutardes,","a minha alma chorará em segredo","por causa do vosso orgulho;","os meus olhos derramarão lágrimas amargas","e se desfarão em pranto,","porque o rebanho do Senhor foi levado cativo."],np:1},
{v:18,l:["Dize ao rei e à rainha-mãe:","Sentai-vos no chão,","pois caiu da vossa cabeça","a vossa coroa gloriosa."],np:1,n:"Talvez o rei Joaquin e sua mãe, Neesta, levados para a Babilônia em 597 antes de Cristo (2 Reis 24,8–15)."},
{v:19,l:["As cidades do Negueb estão fechadas,","e não há quem as abra;","todo Judá foi deportado,","deportado por completo."],np:1},
{v:20,l:["Ergue os olhos e vê","os que vêm do norte:","onde está o rebanho que te foi confiado,","as tuas ovelhas magníficas?"],np:1},
{v:21,l:["Que dirás quando ele puser sobre ti como chefes","os amigos que tu mesma instruíste contra ti?","Não se apoderarão de ti as dores,","como da mulher em trabalho de parto?"],np:1},
{v:22,l:["E, se disseres no teu coração:","Por que me aconteceu isto?,","é pela multidão das tuas iniquidades","que foram levantadas as tuas saias","e violentados os teus calcanhares."],np:1,n:"Nota do tradutor: calcanhares é eufemismo; a humilhação da cidade conquistada é descrita com a imagem da mulher violentada, e o texto não a atenua."},
{v:23,l:["Pode um etíope mudar a sua pele,","ou um leopardo as suas manchas?","Então também vós podereis fazer o bem,","vós que estais acostumados a fazer o mal."],np:1},
{v:24,l:["Eu os dispersarei como a palha","levada pelo vento do deserto."],np:1},
{v:25,l:["Esta é a tua sorte, a parte que te medi,","oráculo do Senhor,","porque te esqueceste de mim","e confiaste na mentira."],np:1},
{v:26,l:["Também eu levantarei as tuas saias até o rosto,","e a tua vergonha será vista:"],np:1},
{v:27,l:["os teus adultérios e os teus relinchos,","a infâmia da tua prostituição.","Sobre as colinas, no campo,","vi as tuas abominações.","Ai de ti, Jerusalém! Não te purificarás?","Até quando ainda?"],np:1}
];

window.TEXTOS_SEED["jeremias"][14] = [
{s:"A grande seca"},
{v:1,t:"Palavra do Senhor que foi dirigida a Jeremias a respeito da seca."},
{v:2,l:["Judá está de luto,","as suas portas definham,","jazem por terra, tristes,","e sobe o grito de Jerusalém."],np:1},
{v:3,l:["Os nobres mandam os seus servos buscar água:","vão às cisternas,","não encontram água;","voltam com os jarros vazios,","envergonhados e confusos,","e cobrem a cabeça."],np:1},
{v:4,l:["Por causa do solo rachado,","pois não há chuva na terra,","os lavradores ficam envergonhados","e cobrem a cabeça."],np:1},
{v:5,l:["Até a corça no campo dá à luz e abandona a cria,","porque não há erva."],np:1},
{v:6,l:["Os jumentos selvagens ficam de pé sobre as colinas nuas,","aspiram o ar como chacais;","os seus olhos se apagam,","porque não há pasto."],np:1},
{s:"Súplica do povo"},
{v:7,l:["Ainda que as nossas iniquidades testemunhem contra nós,","age, Senhor, por amor do teu nome;","sim, as nossas infidelidades são muitas,","pecamos contra ti."]},
{v:8,l:["Esperança de Israel,","seu salvador no tempo da angústia,","por que és como um estrangeiro na terra,","como um viajante que só se detém para passar a noite?"],np:1},
{v:9,l:["Por que és como um homem desnorteado,","como um guerreiro incapaz de salvar?","Mas tu estás no meio de nós, Senhor,","e o teu nome é invocado sobre nós:","não nos abandones!"],np:1},
{s:"A resposta do Senhor"},
{v:10,t:"Assim diz o Senhor a este povo: Gostam tanto de andar errantes que não poupam os pés; por isso o Senhor não se agrada deles. Agora ele se lembra das suas iniquidades e castiga os seus pecados.",n:"Compare Oseias 8,13."},
{v:11,t:"O Senhor me disse: Não intercedas por este povo, para o seu bem.",np:1},
{v:12,t:"Ainda que jejuem, não escutarei a sua súplica; ainda que ofereçam holocaustos e oblações, não os aceitarei; ao contrário, vou exterminá-los pela espada, pela fome e pela peste."},
{v:13,t:"Então eu disse: Ah, Senhor Deus! Eis que os profetas lhes dizem: Não vereis a espada, e a fome não chegará até vós; ao contrário, eu vos darei uma paz verdadeira neste lugar."},
{v:14,t:"O Senhor me respondeu: Os profetas profetizam mentiras em meu nome; eu não os enviei, não lhes dei ordens nem lhes falei. Visões mentirosas, adivinhações vazias e as fantasias do seu coração: é isto que eles vos profetizam."},
{v:15,t:"Por isso assim diz o Senhor a respeito dos profetas que profetizam em meu nome, sem que eu os tenha enviado, e que dizem: Não haverá espada nem fome nesta terra: pela espada e pela fome acabarão esses profetas;"},
{v:16,t:"e as pessoas a quem eles profetizam serão lançadas nas ruas de Jerusalém, vítimas da fome e da espada, e não haverá quem as sepulte, nem a elas, nem às suas mulheres, nem aos seus filhos e filhas; farei cair sobre eles a sua própria maldade."},
{s:"Lamento e nova súplica"},
{v:17,l:["Tu lhes dirás esta palavra:","Os meus olhos derramam lágrimas","noite e dia, sem cessar,","pois a virgem, filha do meu povo,","foi ferida com uma grande ferida,","com um golpe mortal."]},
{v:18,l:["Se saio para o campo,","eis os mortos pela espada;","se entro na cidade,","eis os que definham de fome;","até o profeta e o sacerdote","andam por uma terra que não conhecem."],np:1},
{v:19,l:["Acaso rejeitaste de vez Judá?","Tens aversão a Sião?","Por que nos feriste","sem que haja cura para nós?","Esperávamos a paz, e nada de bom;","o tempo da cura, e eis o terror."],np:1},
{v:20,l:["Reconhecemos, Senhor, a nossa maldade,","a iniquidade dos nossos pais:","pecamos contra ti."],np:1},
{v:21,l:["Por amor do teu nome, não nos rejeites,","não desonres o trono da tua glória;","lembra-te, não rompas a tua aliança conosco."],np:1},
{v:22,l:["Há entre os ídolos das nações quem faça chover?","Ou podem os céus dar os aguaceiros?","Não és tu, Senhor, nosso Deus?","Em ti esperamos,","pois és tu que fazes todas estas coisas."],np:1}
];

window.TEXTOS_SEED["jeremias"][15] = [
{s:"Nem Moisés nem Samuel"},
{v:1,t:"O Senhor me disse: Ainda que Moisés e Samuel se apresentassem diante de mim, o meu coração não se voltaria para este povo; expulsa-os da minha presença, que se vão!"},
{v:2,l:["E, se te perguntarem: Para onde iremos?, tu lhes responderás: Assim diz o Senhor:","Quem é para a morte, para a morte;","quem é para a espada, para a espada;","quem é para a fome, para a fome;","quem é para o cativeiro, para o cativeiro."]},
{v:3,t:"Mandarei contra eles quatro espécies de flagelos, oráculo do Senhor: a espada para matar, os cães para despedaçar, as aves do céu e os animais da terra para devorar e destruir.",np:1},
{v:4,t:"Farei deles um motivo de espanto para todos os reinos da terra, por causa de Manassés, filho de Ezequias, rei de Judá, por tudo o que ele fez em Jerusalém.",n:"Compare 2 Reis 21,1–16; 23,26."},
{s:"Lamento sobre Jerusalém"},
{v:5,l:["Quem terá compaixão de ti, Jerusalém?","Quem lamentará a tua sorte?","Quem se desviará do caminho","para perguntar como estás?"]},
{v:6,l:["Tu me rejeitaste,","oráculo do Senhor,","voltaste-me as costas;","por isso estendi a mão contra ti e te destruí:","estou cansado de ter compaixão."],np:1},
{v:7,l:["Joeirei-os com a pá","às portas da terra;","privei de filhos e fiz perecer o meu povo,","pois não se converteram dos seus caminhos."],np:1},
{v:8,l:["As suas viúvas se tornaram, diante de mim,","mais numerosas que a areia do mar;","trouxe contra as mães dos jovens","o devastador em pleno meio-dia;","fiz cair de repente sobre ela","a angústia e o terror."],np:1},
{v:9,l:["A mãe de sete filhos desfalece,","exala o último suspiro;","o seu sol se põe quando ainda é dia;","ela fica envergonhada e confusa.","E o que deles restar, eu o entregarei à espada","diante dos seus inimigos,","oráculo do Senhor."],np:1},
{s:"Queixa do profeta e resposta do Senhor"},
{v:10,l:["Ai de mim, minha mãe, por me teres dado à luz,","homem de briga e de discórdia para toda a terra!","Não emprestei dinheiro, nem ninguém me emprestou,","e todos me amaldiçoam."]},
{v:11,l:["Na verdade, Senhor, eu te servi para o bem deles,","intercedi junto a ti no tempo da desgraça","e no tempo da angústia em favor do inimigo."],np:1,n:"Assim a Nova Vulgata, com a tradução grega; o hebraico diz: O Senhor disse: Eu te libertarei para o bem."},
{v:12,l:["Pode alguém quebrar o ferro,","o ferro do norte, e o bronze?"],np:1},
{v:13,l:["Os teus bens e os teus tesouros","entregarei ao saque, sem preço,","por causa de todos os teus pecados,","em todo o teu território."],np:1},
{v:14,l:["Farei de ti escravo dos teus inimigos,","numa terra que não conheces;","pois um fogo se acendeu na minha ira,","e arderá contra vós."],np:1,n:"Os versículos 13–14 se repetem, com variações, em 17,3–4."},
{v:15,l:["Tu sabes, Senhor;","lembra-te de mim, visita-me","e vinga-me dos meus perseguidores;","não me deixes perecer por causa da tua paciência com eles;","sabe que é por ti que suporto os insultos."],np:1},
{v:16,l:["Quando encontrei as tuas palavras, eu as devorei;","a tua palavra foi para mim o gozo","e a alegria do coração,","pois sobre mim é invocado o teu nome,","Senhor, Deus dos exércitos."],np:1,n:"Compare Ezequiel 3,1–3 e Apocalipse 10,9–10."},
{v:17,l:["Não me sentei na roda dos que se divertem","para me alegrar com eles;","por causa da tua mão eu me sentava sozinho,","pois me encheste de indignação."],np:1},
{v:18,l:["Por que a minha dor não tem fim,","e a minha ferida é incurável,","recusa ser curada?","Serás para mim como um riacho enganador,","de águas com que não se pode contar?"],np:1},
{v:19,l:["Por isso assim diz o Senhor:","Se voltares, eu te farei voltar,","e estarás diante de mim;","se separares o que é precioso do que é vil,","serás como a minha boca.","Eles é que voltarão a ti,","e não tu a eles."],np:1},
{v:20,l:["Eu farei de ti para este povo","uma muralha de bronze inexpugnável;","eles lutarão contra ti,","mas não te vencerão,","pois estou contigo","para te salvar e te livrar,","oráculo do Senhor."],np:1},
{v:21,l:["Eu te livrarei da mão dos maus","e te resgatarei da mão dos violentos."],np:1}
];

window.TEXTOS_SEED["jeremias"][16] = [
{s:"A vida do profeta como sinal"},
{v:1,t:"A palavra do Senhor me foi dirigida nestes termos:"},
{v:2,t:"Não tomarás mulher, e não terás filhos nem filhas neste lugar."},
{v:3,t:"Pois assim diz o Senhor a respeito dos filhos e das filhas que nascerem neste lugar, das mães que os derem à luz e dos pais que os gerarem nesta terra:"},
{v:4,t:"Morrerão de doenças mortais, não serão lamentados nem sepultados; serão como esterco sobre a face da terra; acabarão pela espada e pela fome, e os seus cadáveres servirão de alimento às aves do céu e aos animais da terra."},
{v:5,t:"Pois assim diz o Senhor: Não entres numa casa de luto, não vás lamentar nem te compadeças deles, pois retirei deste povo a minha paz, oráculo do Senhor, a bondade e a compaixão.",n:"Casa de luto: em hebraico marzeah, o banquete fúnebre."},
{v:6,t:"Grandes e pequenos morrerão nesta terra, e não serão sepultados nem lamentados; ninguém fará incisões nem raspará a cabeça por eles.",n:"Ritos de luto proibidos pela Lei (Deuteronômio 14,1), mas praticados pelo povo."},
{v:7,t:"Não se partirá o pão para quem estiver de luto, para consolá-lo pela morte de alguém, nem lhe darão a beber o cálice da consolação pelo pai ou pela mãe.",np:1},
{v:8,t:"Também não entres numa casa em festa, para te sentares com eles a comer e a beber."},
{v:9,t:"Pois assim diz o Senhor dos exércitos, o Deus de Israel: Eis que vou fazer cessar neste lugar, diante dos vossos olhos e nos vossos dias, a voz da alegria e a voz do júbilo, a voz do noivo e a voz da noiva."},
{v:10,t:"E, quando anunciares a este povo todas estas palavras e eles te perguntarem: Por que o Senhor decretou contra nós toda esta grande desgraça? Qual é a nossa culpa, qual é o pecado que cometemos contra o Senhor, nosso Deus?,",np:1},
{v:11,t:"tu lhes responderás: É porque os vossos pais me abandonaram, oráculo do Senhor, correram atrás de outros deuses, serviram-nos e os adoraram; abandonaram-me e não guardaram a minha lei."},
{v:12,t:"E vós agistes pior que os vossos pais: eis que cada um segue a obstinação do seu coração perverso, sem me escutar."},
{v:13,t:"Por isso vos expulsarei desta terra para uma terra que nem vós nem os vossos pais conhecestes; e lá servireis a outros deuses dia e noite, pois não vos concederei a minha graça.",np:1},
{s:"O novo êxodo"},
{v:14,t:"Por isso eis que virão dias, oráculo do Senhor, em que não se dirá mais: Pela vida do Senhor, que tirou os filhos de Israel da terra do Egito!,"},
{v:15,t:"mas: Pela vida do Senhor, que tirou os filhos de Israel da terra do norte e de todos os países para onde os tinha expulsado! E eu os farei voltar para a sua terra, que dei aos seus pais.",n:"Os versículos 14–15 se repetem em 23,7–8."},
{s:"Pescadores e caçadores"},
{v:16,t:"Eis que vou mandar muitos pescadores, oráculo do Senhor, e eles os pescarão; depois mandarei muitos caçadores, e eles os caçarão em todo monte, em toda colina e nas fendas das rochas."},
{v:17,t:"Pois os meus olhos estão sobre todos os seus caminhos: eles não estão escondidos de mim, e a sua iniquidade não está oculta aos meus olhos."},
{v:18,t:"Primeiro lhes retribuirei em dobro a sua iniquidade e o seu pecado, pois profanaram a minha terra com os cadáveres dos seus ídolos e encheram a minha herança com as suas abominações."},
{s:"As nações virão ao Senhor"},
{v:19,l:["Senhor, minha força e minha fortaleza,","meu refúgio no dia da angústia,","a ti virão as nações desde os confins da terra e dirão:","Os nossos pais só herdaram mentira,","ídolos vazios, que não servem para nada."]},
{v:20,l:["Pode um homem fazer para si deuses?","Esses não são deuses!"],np:1},
{v:21,l:["Por isso eis que lhes farei conhecer,","desta vez lhes farei conhecer","a minha mão e o meu poder,","e saberão que o meu nome é Senhor."],np:1}
];

window.TEXTOS_SEED["jeremias"][17] = [
{s:"O pecado gravado no coração"},
{v:1,l:["O pecado de Judá está escrito com um estilete de ferro,","gravado com ponta de diamante","na tábua do seu coração","e nas pontas dos seus altares,"],n:"Os versículos 1–4 faltam na antiga tradução grega."},
{v:2,l:["de modo que os seus filhos se lembram dos seus altares","e dos seus postes sagrados, junto às árvores frondosas,","sobre as colinas elevadas"],np:1},
{v:3,l:["e sobre os montes do campo.","Os teus bens e todos os teus tesouros","entregarei ao saque,","e também os teus lugares altos, por causa do pecado,","em todo o teu território."],np:1},
{v:4,l:["Perderás a herança","que eu te tinha dado,","e farei de ti escravo dos teus inimigos","numa terra que não conheces,","pois acendestes o fogo da minha ira,","que arderá para sempre."],np:1},
{s:"Os dois caminhos"},
{v:5,l:["Assim diz o Senhor:","Maldito o homem que confia no homem,","que faz da carne o seu apoio,","e cujo coração se afasta do Senhor!"]},
{v:6,l:["Será como um arbusto no deserto:","não verá chegar o bem;","habitará nos lugares secos do deserto,","numa terra salgada e inabitável."],np:1},
{v:7,l:["Bendito o homem que confia no Senhor,","cuja esperança é o Senhor!"],np:1},
{v:8,l:["Será como uma árvore plantada junto às águas,","que estende as raízes para o riacho:","não teme quando chega o calor,","a sua folhagem permanece verde;","no ano da seca não se inquieta","e não deixa de dar fruto."],np:1,n:"Compare Salmo 1,3."},
{v:9,l:["O coração é mais enganador que tudo","e incurável: quem o pode conhecer?"],np:1},
{v:10,l:["Eu, o Senhor, sondo o coração","e provo os rins,","para dar a cada um segundo o seu caminho,","segundo o fruto das suas ações."],np:1},
{v:11,l:["Como a perdiz que choca ovos que não pôs,","assim é quem ajunta riquezas injustamente:","na metade dos seus dias terá de deixá-las,","e no fim se mostrará um insensato."],np:1},
{s:"O trono glorioso"},
{v:12,l:["Trono de glória, exaltado desde o princípio,","é o lugar do nosso santuário!"]},
{v:13,l:["Esperança de Israel, Senhor,","todos os que te abandonam ficarão envergonhados;","os que se afastam de ti serão inscritos no pó,","porque abandonaram o Senhor,","fonte de água viva."],np:1,n:"Inscritos no pó: o seu nome se apagará."},
{s:"Nova súplica do profeta"},
{v:14,l:["Cura-me, Senhor, e ficarei curado;","salva-me, e serei salvo,","pois tu és o meu louvor."]},
{v:15,l:["Eis que eles me dizem:","Onde está a palavra do Senhor?","Que ela se cumpra!"],np:1},
{v:16,l:["Mas eu não insisti contigo para a desgraça,","nem desejei o dia fatal, tu o sabes:","o que saiu dos meus lábios","estava diante de ti."],np:1,n:"Assim a Nova Vulgata; o hebraico diz: não fugi de ser pastor atrás de ti."},
{v:17,l:["Não sejas para mim motivo de terror,","tu, meu refúgio no dia da desgraça."],np:1},
{v:18,l:["Que os meus perseguidores fiquem envergonhados,","mas não eu;","que eles fiquem aterrados,","mas não eu;","faze vir sobre eles o dia da desgraça,","esmaga-os com dupla ruína."],np:1},
{s:"A observância do sábado"},
{v:19,t:"Assim me disse o Senhor: Vai e põe-te à porta dos Filhos do Povo, pela qual entram e saem os reis de Judá, e em todas as portas de Jerusalém,"},
{v:20,t:"e dize-lhes: Ouvi a palavra do Senhor, reis de Judá, todo Judá e todos os habitantes de Jerusalém, que entrais por estas portas."},
{v:21,t:"Assim diz o Senhor: Cuidai de vós mesmos: não carregueis fardos em dia de sábado, nem os façais entrar pelas portas de Jerusalém;"},
{v:22,t:"não tireis fardos das vossas casas em dia de sábado e não façais trabalho algum; santificai o dia de sábado, como ordenei aos vossos pais."},
{v:23,t:"Mas eles não escutaram nem deram ouvidos; endureceram a cerviz para não escutar e não receber a correção."},
{v:24,t:"Se me escutardes de verdade, oráculo do Senhor, se não fizerdes entrar fardos pelas portas desta cidade em dia de sábado e santificardes o dia de sábado, sem fazer nele trabalho algum,"},
{v:25,t:"então entrarão pelas portas desta cidade reis e príncipes que se sentam no trono de Davi, montados em carros e cavalos, eles e os seus príncipes, os homens de Judá e os habitantes de Jerusalém; e esta cidade será habitada para sempre."},
{v:26,t:"Virão das cidades de Judá, dos arredores de Jerusalém, da terra de Benjamim, da Sefelá, da montanha e do Negueb, trazendo holocaustos, sacrifícios, oblações e incenso, e trazendo sacrifícios de ação de graças à casa do Senhor."},
{v:27,t:"Mas, se não me escutardes, santificando o dia de sábado e não carregando fardos ao entrar pelas portas de Jerusalém em dia de sábado, porei fogo às suas portas, e ele devorará os palácios de Jerusalém e não se apagará."}
];

window.TEXTOS_SEED["jeremias"][18] = [
{s:"Na casa do oleiro"},
{v:1,t:"Palavra que o Senhor dirigiu a Jeremias:"},
{v:2,t:"Levanta-te e desce à casa do oleiro; lá te farei ouvir as minhas palavras."},
{v:3,t:"Desci à casa do oleiro, e eis que ele trabalhava no torno."},
{v:4,t:"E, quando o vaso que ele fazia com o barro se estragava nas suas mãos, ele fazia outro vaso, como lhe parecia bem."},
{v:5,t:"Então a palavra do Senhor me foi dirigida:"},
{v:6,t:"Não posso eu fazer convosco como fez este oleiro, casa de Israel?, oráculo do Senhor. Eis que, como o barro na mão do oleiro, assim sois vós na minha mão, casa de Israel.",n:"Compare Romanos 9,20–21."},
{v:7,t:"Às vezes falo contra uma nação ou contra um reino, para arrancá-lo, derrubá-lo e destruí-lo;"},
{v:8,t:"mas, se essa nação contra a qual falei se converter da sua maldade, eu também me arrependerei do mal que tinha pensado fazer-lhe."},
{v:9,t:"Outras vezes falo a respeito de uma nação ou de um reino, para edificá-lo e plantá-lo;"},
{v:10,t:"mas, se ele fizer o que é mau aos meus olhos, sem escutar a minha voz, eu também me arrependerei do bem que tinha prometido fazer-lhe."},
{v:11,t:"Agora, pois, fala aos homens de Judá e aos habitantes de Jerusalém: Assim diz o Senhor: Eis que estou preparando contra vós uma desgraça e tramando contra vós um plano; convertei-vos cada um do seu mau caminho, endireitai os vossos caminhos e as vossas ações."},
{v:12,t:"Mas eles responderam: É inútil! Seguiremos os nossos próprios planos, e cada um agirá segundo a obstinação do seu coração perverso."},
{s:"O povo que esqueceu o Senhor"},
{v:13,l:["Por isso assim diz o Senhor:","Perguntai entre as nações:","quem ouviu coisa semelhante?","A virgem de Israel cometeu","uma coisa horrível."]},
{v:14,l:["Acaso a neve do Líbano","desaparece dos rochedos do campo?","Ou secam as águas que brotam de longe,","frescas e correntes?"],np:1},
{v:15,l:["Mas o meu povo se esqueceu de mim:","queimam incenso ao nada;","tropeçaram nos seus caminhos,","nas veredas antigas,","para andar por atalhos,","por um caminho não aterrado,"],np:1},
{v:16,l:["fazendo da sua terra uma desolação,","motivo de assobios para sempre:","todo aquele que passar por ela ficará espantado","e sacudirá a cabeça."],np:1},
{v:17,l:["Como o vento leste, eu os dispersarei","diante do inimigo;","mostrarei a eles as costas, e não o rosto,","no dia da sua desgraça."],np:1},
{s:"Nova conspiração e súplica do profeta"},
{v:18,t:"Eles disseram: Vinde, tramemos um plano contra Jeremias, pois não faltará a lei ao sacerdote, nem o conselho ao sábio, nem a palavra ao profeta. Vinde, ataquemo-lo com a língua e não prestemos atenção a nenhuma das suas palavras."},
{v:19,l:["Presta atenção a mim, Senhor,","e ouve a voz dos meus adversários."],np:1},
{v:20,l:["Acaso se paga o bem com o mal?","Pois cavaram uma cova para a minha vida.","Lembra-te de que estive diante de ti","para falar em favor deles","e afastar deles a tua ira."],np:1},
{v:21,l:["Por isso entrega os seus filhos à fome","e deixa-os à mercê da espada;","que as suas mulheres fiquem sem filhos e viúvas,","que os seus homens sejam mortos pela peste,","e os seus jovens, feridos pela espada na batalha."],np:1,n:"Nota do tradutor: é a súplica mais dura das confissões de Jeremias, traduzida sem atenuação: o grito do perseguido que entrega a Deus a sua causa, como nos salmos imprecatórios. Jesus ensinará a orar pelos que nos perseguem (Mateus 5,44)."},
{v:22,l:["Que se ouçam gritos nas suas casas,","quando de repente fizeres cair sobre eles os saqueadores;","pois cavaram uma cova para me apanhar","e esconderam laços para os meus pés."],np:1},
{v:23,l:["Mas tu, Senhor, conheces todos os planos deles","contra mim, para me matar;","não perdoes a sua iniquidade,","não apagues da tua presença o seu pecado.","Que eles tropecem diante de ti;","age contra eles no tempo da tua ira."],np:1}
];

window.TEXTOS_SEED["jeremias"][19] = [
{s:"O jarro quebrado"},
{v:1,t:"Assim diz o Senhor: Vai comprar um jarro de barro de um oleiro e leva contigo alguns anciãos do povo e alguns anciãos dos sacerdotes;"},
{v:2,t:"sai para o vale de Ben-Enom, que fica à entrada da porta dos Cacos, e proclama ali as palavras que eu te disser."},
{v:3,t:"Tu dirás: Ouvi a palavra do Senhor, reis de Judá e habitantes de Jerusalém: Assim diz o Senhor dos exércitos, o Deus de Israel: Eis que vou fazer vir sobre este lugar uma desgraça tal, que zunirão os ouvidos de todo aquele que dela ouvir falar,"},
{v:4,t:"porque me abandonaram, profanaram este lugar e nele queimaram incenso a outros deuses, que nem eles, nem os seus pais, nem os reis de Judá conheciam, e encheram este lugar com o sangue de inocentes;"},
{v:5,t:"construíram os lugares altos de Baal, para queimar no fogo os seus filhos em holocausto a Baal: coisa que eu não ordenei, nem disse, nem me passou pela mente."},
{v:6,t:"Por isso eis que virão dias, oráculo do Senhor, em que este lugar não se chamará mais Tofet nem vale de Ben-Enom, mas vale da Matança."},
{v:7,t:"Neste lugar frustrarei os planos de Judá e de Jerusalém; eu os farei cair pela espada diante dos seus inimigos e pela mão dos que procuram a sua vida, e darei os seus cadáveres como alimento às aves do céu e aos animais da terra."},
{v:8,t:"Farei desta cidade um motivo de espanto e de assobios; todo aquele que passar por ela ficará espantado e assobiará diante de todas as suas feridas."},
{v:9,t:"Eu os farei comer a carne dos seus filhos e a carne das suas filhas, e cada um comerá a carne do seu próximo, durante o cerco e na angústia a que os reduzirão os seus inimigos e os que procuram a sua vida.",n:"Nota do tradutor: a antropofagia durante os cercos é descrita sem atenuação, como em Deuteronômio 28,53–57 e Lamentações 4,10."},
{v:10,t:"Depois quebrarás o jarro diante dos homens que forem contigo,",np:1},
{v:11,t:"e lhes dirás: Assim diz o Senhor dos exércitos: Assim vou quebrar este povo e esta cidade, como se quebra um vaso de oleiro, que não pode mais ser consertado; e serão sepultados em Tofet, por falta de outro lugar para sepultar."},
{v:12,t:"É assim que farei a este lugar, oráculo do Senhor, e aos seus habitantes, tornando esta cidade semelhante a Tofet;"},
{v:13,t:"as casas de Jerusalém e as casas dos reis de Judá ficarão impuras como o lugar de Tofet: todas as casas sobre cujos terraços queimaram incenso a todo o exército do céu e ofereceram libações a outros deuses."},
{v:14,t:"Jeremias voltou de Tofet, para onde o Senhor o tinha enviado a profetizar, e se pôs no átrio da casa do Senhor e disse a todo o povo:",np:1},
{v:15,t:"Assim diz o Senhor dos exércitos, o Deus de Israel: Eis que vou fazer vir sobre esta cidade e sobre todas as cidades vizinhas todas as desgraças que anunciei contra ela, porque endureceram a cerviz para não escutar as minhas palavras."}
];

window.TEXTOS_SEED["jeremias"][20] = [
{s:"Jeremias e o sacerdote Fassur"},
{v:1,t:"O sacerdote Fassur, filho de Emer, que era o chefe da guarda da casa do Senhor, ouviu Jeremias profetizar estas palavras."},
{v:2,t:"Então Fassur mandou açoitar o profeta Jeremias e o pôs no tronco que ficava na porta superior de Benjamim, na casa do Senhor."},
{v:3,t:"No dia seguinte, Fassur tirou Jeremias do tronco, e Jeremias lhe disse: O Senhor já não te chama Fassur, mas Terror-por-todos-os-lados.",n:"Em hebraico, Magor-Missabib."},
{v:4,t:"Pois assim diz o Senhor: Eis que farei de ti um terror para ti mesmo e para todos os teus amigos; eles cairão pela espada dos seus inimigos, e os teus olhos o verão; entregarei todo Judá nas mãos do rei da Babilônia, que os deportará para a Babilônia e os ferirá à espada."},
{v:5,t:"Entregarei todas as riquezas desta cidade, todo o fruto do seu trabalho, tudo o que ela tem de precioso e todos os tesouros dos reis de Judá nas mãos dos seus inimigos, que os saquearão, os tomarão e os levarão para a Babilônia."},
{v:6,t:"E tu, Fassur, com todos os que moram na tua casa, irás para o cativeiro; irás para a Babilônia, e lá morrerás e lá serás sepultado, tu e todos os teus amigos, a quem profetizaste mentiras."},
{s:"Seduziste-me, Senhor"},
{v:7,l:["Seduziste-me, Senhor, e eu me deixei seduzir;","foste mais forte do que eu e venceste.","Tornei-me objeto de zombaria o dia inteiro,","todos caçoam de mim."],n:"Nota do tradutor: seduzir traduz o hebraico patah, que se usa também para o homem que seduz uma virgem (Êxodo 22,15); a força da imagem é mantida."},
{v:8,l:["Pois, cada vez que falo, tenho de gritar,","de proclamar: Violência e destruição!","A palavra do Senhor se tornou para mim","motivo de insulto e de zombaria o dia inteiro."],np:1},
{v:9,l:["Eu dizia: Não pensarei mais nele,","não falarei mais em seu nome.","Mas ela era no meu coração como um fogo ardente,","encerrado nos meus ossos:","esforcei-me para contê-lo, e não pude."],np:1},
{v:10,l:["Ouvi as calúnias de muitos,","terror por todos os lados:","Denunciai-o! Vamos denunciá-lo!","Todos os meus amigos espreitavam a minha queda:","Talvez ele se deixe enganar, e o venceremos","e nos vingaremos dele."],np:1},
{v:11,l:["Mas o Senhor está comigo como um guerreiro poderoso;","por isso os meus perseguidores","tropeçarão e não prevalecerão.","Ficarão muito envergonhados, porque fracassaram;","uma vergonha eterna, que nunca será esquecida."],np:1},
{v:12,l:["Senhor dos exércitos,","que provas o justo e vês os rins e o coração,","que eu veja a tua vingança contra eles,","pois a ti confiei a minha causa."],np:1},
{v:13,l:["Cantai ao Senhor, louvai o Senhor,","pois ele livrou a vida do pobre","da mão dos malfeitores."],np:1},
{s:"Maldito o dia em que nasci"},
{v:14,l:["Maldito o dia em que nasci!","O dia em que minha mãe me deu à luz","não seja bendito!"]},
{v:15,l:["Maldito o homem que levou a notícia a meu pai,","dizendo: Nasceu-te um filho homem!,","e o encheu de alegria!"],np:1},
{v:16,l:["Que esse homem seja como as cidades","que o Senhor destruiu sem piedade;","que ouça gritos de manhã","e o alarido de guerra ao meio-dia,"],np:1,n:"As cidades destruídas: Sodoma e Gomorra (Gênesis 19,24–25)."},
{v:17,l:["porque não me fez morrer no seio materno,","para que minha mãe fosse o meu sepulcro,","e o seu seio ficasse grávido para sempre."]},
{v:18,l:["Por que saí do seio materno","para ver sofrimento e aflição,","e para que os meus dias se consumam na vergonha?"],np:1,n:"Nota do tradutor: a maldição do próprio nascimento, como em Jó 3, é o desabafo extremo do profeta; o texto não a suaviza."}
];

window.TEXTOS_SEED["jeremias"][21] = [
{s:"Resposta ao rei Sedecias"},
{v:1,t:"Palavra que o Senhor dirigiu a Jeremias, quando o rei Sedecias lhe enviou Fassur, filho de Melquias, e o sacerdote Sofonias, filho de Maasias, para lhe dizer:",n:"Durante o cerco de Jerusalém pelos babilônios, entre 589 e 587 antes de Cristo."},
{v:2,t:"Consulta o Senhor por nós, pois Nabucodonosor, rei da Babilônia, nos faz guerra; talvez o Senhor faça por nós algum dos seus prodígios, e ele se retire."},
{v:3,t:"Jeremias lhes respondeu: Assim direis a Sedecias:"},
{v:4,t:"Assim diz o Senhor, o Deus de Israel: Eis que vou fazer voltar para trás as armas de guerra que tendes nas mãos, com as quais combateis o rei da Babilônia e os caldeus que vos cercam fora das muralhas, e as reunirei no meio desta cidade."},
{v:5,t:"Eu mesmo combaterei contra vós, com mão estendida e braço forte, com ira, com furor e com grande indignação."},
{v:6,t:"Ferirei os habitantes desta cidade, homens e animais: morrerão de uma grande peste."},
{v:7,t:"Depois disso, oráculo do Senhor, entregarei Sedecias, rei de Judá, os seus servos e o povo, os que nesta cidade tiverem escapado da peste, da espada e da fome, nas mãos de Nabucodonosor, rei da Babilônia, nas mãos dos seus inimigos e nas mãos dos que procuram a sua vida; ele os passará ao fio da espada, sem piedade, sem poupar ninguém, sem compaixão."},
{v:8,t:"E a este povo dirás: Assim diz o Senhor: Eis que ponho diante de vós o caminho da vida e o caminho da morte:",np:1},
{v:9,t:"quem ficar nesta cidade morrerá pela espada, pela fome e pela peste; mas quem sair e se entregar aos caldeus que vos cercam viverá, e salvará a vida como um despojo."},
{v:10,t:"Pois voltei o meu rosto contra esta cidade, para o mal e não para o bem, oráculo do Senhor: ela será entregue nas mãos do rei da Babilônia, que a incendiará."},
{s:"À casa real de Judá"},
{v:11,l:["E à casa do rei de Judá:","Ouvi a palavra do Senhor,"]},
{v:12,l:["casa de Davi! Assim diz o Senhor:","Fazei justiça cada manhã","e livrai o oprimido da mão do opressor,","para que a minha ira não irrompa como fogo","e arda sem que ninguém a possa apagar,","por causa da maldade das vossas ações."],np:1},
{v:13,l:["Eis que estou contra ti, que habitas no vale,","rocha da planície,","oráculo do Senhor;","contra vós, que dizeis: Quem descerá contra nós?","Quem entrará nas nossas moradas?"],np:1},
{v:14,l:["Eu vos castigarei segundo o fruto das vossas ações,","oráculo do Senhor;","porei fogo à sua floresta,","e ele devorará tudo ao seu redor."],np:1}
];
