// =====================================================================
// Jeremias — tradução do hebraico (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["jeremias"][1] = [
{s:"Título do livro"},
{v:1,t:"Palavras de Jeremias, filho de Helcias, um dos sacerdotes que viviam em Anatot, na terra de Benjamim.",n:"Jeremias exerceu o seu ministério em Jerusalém desde 627 até depois da destruição da cidade pelos babilônios, em 587 antes de Cristo. A antiga tradução grega tem um texto bem mais curto e em outra ordem; a Nova Vulgata segue o texto hebraico."},
{v:2,t:"A ele foi dirigida a palavra do Senhor nos dias de Josias, filho de Amon, rei de Judá, no décimo terceiro ano do seu reinado,",np:1,n:"Em 627 antes de Cristo."},
{v:3,t:"e depois nos dias de Joaquim, filho de Josias, rei de Judá, até o fim do décimo primeiro ano de Sedecias, filho de Josias, rei de Judá, até a deportação de Jerusalém, no quinto mês.",np:1,n:"Em 587 antes de Cristo."},
{s:"A vocação de Jeremias"},
{v:4,t:"A palavra do Senhor me foi dirigida nestes termos:"},
{v:5,l:["Antes de te formar no ventre materno, eu te conheci;","antes que saísses do seio, eu te consagrei","e te constituí profeta das nações."],np:1},
{v:6,t:"Eu disse: Ah, Senhor Deus! Eis que não sei falar, porque sou jovem.",np:1},
{v:7,l:["Mas o Senhor me respondeu: Não digas: Sou jovem,","pois irás a todos aqueles a quem eu te enviar","e dirás tudo o que eu te ordenar."],np:1},
{v:8,l:["Não tenhas medo deles,","pois estou contigo para te livrar,","oráculo do Senhor."],np:1},
{v:9,l:["Então o Senhor estendeu a mão e tocou a minha boca, e o Senhor me disse:","Eis que ponho as minhas palavras na tua boca;"],np:1},
{v:10,l:["vê: hoje te constituo sobre as nações e sobre os reinos,","para arrancar e para derrubar,","para destruir e para demolir,","para construir e para plantar."],np:1},
{s:"Duas visões"},
{v:11,t:"A palavra do Senhor me foi dirigida nestes termos: Que vês, Jeremias? Eu respondi: Vejo um ramo de amendoeira.",n:"Jogo de palavras no hebraico: shaqed (amendoeira, a árvore que desperta primeiro depois do inverno) e shoqed (vigilante)."},
{v:12,t:"E o Senhor me disse: Viste bem, pois eu vigio sobre a minha palavra, para realizá-la."},
{v:13,t:"A palavra do Senhor me foi dirigida uma segunda vez: Que vês? Eu respondi: Vejo uma panela fervendo, com a boca voltada do lado norte.",np:1},
{v:14,l:["E o Senhor me disse:","Do norte se derramará a desgraça","sobre todos os habitantes da terra."]},
{v:15,l:["Pois eis que vou chamar","todas as famílias dos reinos do norte,","oráculo do Senhor;","eles virão, e cada um porá o seu trono","à entrada das portas de Jerusalém,","contra todas as suas muralhas ao redor","e contra todas as cidades de Judá."],np:1},
{v:16,l:["Pronunciarei contra eles as minhas sentenças","por toda a sua maldade,","porque me abandonaram,","queimaram incenso a outros deuses","e adoraram a obra das suas mãos."],np:1},
{v:17,l:["Mas tu, cinge os teus rins,","levanta-te e dize-lhes","tudo o que eu te ordenar;","não tenhas medo deles,","senão eu te farei ter medo diante deles."],np:1},
{v:18,l:["Eis que hoje faço de ti","uma cidade fortificada,","uma coluna de ferro","e uma muralha de bronze","contra toda a terra,","contra os reis de Judá, contra os seus chefes,","contra os seus sacerdotes e contra o povo da terra."],np:1},
{v:19,l:["Eles lutarão contra ti, mas não te vencerão,","pois estou contigo,","oráculo do Senhor,","para te livrar."],np:1}
];

window.TEXTOS_SEED["jeremias"][2] = [
{s:"A infidelidade de Israel"},
{v:1,t:"A palavra do Senhor me foi dirigida nestes termos:"},
{v:2,l:["Vai e grita aos ouvidos de Jerusalém:","Assim diz o Senhor:","Lembro-me do amor da tua juventude,","do amor do teu noivado,","quando me seguias no deserto,","numa terra não semeada."],np:1},
{v:3,l:["Israel era consagrado ao Senhor,","as primícias da sua colheita;","todos os que o devoravam se tornavam culpados,","e a desgraça caía sobre eles,","oráculo do Senhor."],np:1},
{v:4,l:["Ouvi a palavra do Senhor, casa de Jacó,","e todas as famílias da casa de Israel."],np:1},
{v:5,l:["Assim diz o Senhor:","Que injustiça encontraram em mim os vossos pais,","para se afastarem de mim,","correrem atrás do nada","e se tornarem eles mesmos nada?"],np:1},
{v:6,l:["Eles não disseram: Onde está o Senhor,","que nos fez subir da terra do Egito,","que nos conduziu pelo deserto,","por uma terra de estepes e barrancos,","por uma terra de seca e de trevas,","por uma terra por onde ninguém passa","e onde nenhum homem habita?"],np:1},
{v:7,l:["Eu vos trouxe para uma terra de pomares,","para comerdes os seus frutos e os seus bens;","mas vós entrastes e contaminastes a minha terra","e fizestes da minha herança uma abominação."],np:1},
{v:8,l:["Os sacerdotes não disseram:","Onde está o Senhor?","Os que manejavam a lei não me conheceram,","os pastores se rebelaram contra mim,","os profetas profetizaram em nome de Baal","e seguiram os que não servem para nada."],np:1},
{v:9,l:["Por isso ainda entrarei em julgamento convosco,","oráculo do Senhor,","e pleitearei com os filhos dos vossos filhos."],np:1},
{v:10,l:["Passai às ilhas de Quitim e vede,","mandai alguém a Cedar e observai bem,","e vede se aconteceu coisa semelhante:"],np:1,n:"Quitim, no ocidente, e Cedar, no oriente: de um extremo ao outro do mundo conhecido."},
{v:11,l:["acaso uma nação trocou os seus deuses,","que nem sequer são deuses?","Mas o meu povo trocou a sua Glória","por aquilo que não serve para nada."],np:1},
{v:12,l:["Pasmai, ó céus, diante disto,","estremecei de horror, ficai assombrados,","oráculo do Senhor."],np:1},
{v:13,l:["Pois o meu povo cometeu dois males:","abandonaram a mim, fonte de água viva,","para cavar para si cisternas,","cisternas rachadas,","que não retêm a água."],np:1},
{v:14,l:["Acaso Israel é um escravo,","um servo nascido em casa?","Por que então se tornou uma presa?","Contra ele rugiram os leões"],np:1},
{v:15,l:["e soltaram o seu rugido;","reduziram a sua terra a um deserto;","as suas cidades foram incendiadas","e ficaram sem habitantes."],np:1},
{v:16,l:["Até os filhos de Mênfis e de Táfnis","te raparam o alto da cabeça."],np:1},
{v:17,l:["Não foi isto que atraíste sobre ti,","por teres abandonado o Senhor, teu Deus,","quando ele te guiava pelo caminho?"],np:1},
{v:18,l:["E agora, que vais fazer no caminho do Egito,","para beber a água do Nilo?","Que vais fazer no caminho da Assíria,","para beber a água do Rio?"],np:1},
{v:19,l:["A tua maldade te castigará,","e as tuas infidelidades te condenarão;","reconhece e vê como é mau e amargo","teres abandonado o Senhor, teu Deus,","e não teres mais temor de mim,","oráculo do Senhor Deus dos exércitos."],np:1},
{v:20,l:["Há muito tempo quebraste o teu jugo,","rompeste as tuas correntes","e disseste: Não servirei!","Em toda colina elevada","e debaixo de toda árvore frondosa","tu te deitavas como prostituta."],np:1,n:"A prostituição é imagem da idolatria praticada nos santuários dos cultos cananeus."},
{v:21,l:["Eu te plantei como uma vinha escolhida,","toda de semente legítima;","como te transformaste para mim","em ramos de uma vinha estranha?"],np:1},
{v:22,l:["Ainda que te laves com salitre","e uses muito sabão,","a tua culpa continua como uma mancha diante de mim,","oráculo do Senhor Deus."],np:1},
{v:23,l:["Como podes dizer: Não estou contaminada,","não corri atrás dos baals?","Olha o teu caminho no vale,","reconhece o que fizeste,","camela nova e ligeira, que corre para lá e para cá,"],np:1},
{v:24,l:["jumenta selvagem acostumada ao deserto,","que no ardor do cio aspira o vento:","quem a conterá no seu desejo?","Todos os que a procuram não precisam cansar-se:","encontram-na no seu mês."],np:1,n:"Nota do tradutor: imagens tiradas do cio dos animais para descrever a ânsia de Israel pelos cultos estrangeiros; o texto não as atenua."},
{v:25,l:["Poupa o teu pé de andar descalço","e a tua garganta da sede!","Mas disseste: É inútil! Não!","Pois amo os estrangeiros","e quero correr atrás deles."],np:1},
{v:26,l:["Como o ladrão fica envergonhado quando é apanhado,","assim ficará envergonhada a casa de Israel,","eles, os seus reis, os seus chefes,","os seus sacerdotes e os seus profetas,"],np:1},
{v:27,l:["que dizem a um pedaço de pau: Tu és o meu pai,","e a uma pedra: Tu me geraste.","Pois voltaram para mim as costas, e não o rosto;","mas no tempo da desgraça dizem:","Levanta-te e salva-nos!"],np:1},
{v:28,l:["Onde estão os teus deuses, que fizeste para ti?","Que se levantem, se podem salvar-te","no tempo da tua desgraça!","Pois tens tantos deuses, ó Judá,","quantas são as tuas cidades."],np:1},
{v:29,l:["Por que discutis comigo?","Todos vós vos rebelastes contra mim,","oráculo do Senhor."],np:1},
{v:30,l:["Em vão feri os vossos filhos:","não aceitaram a correção.","A vossa espada devorou os vossos profetas,","como um leão devastador."],np:1},
{v:31,l:["Ó geração, prestai atenção à palavra do Senhor:","acaso fui para Israel um deserto,","uma terra de trevas espessas?","Por que o meu povo diz: Somos livres,","não voltaremos mais a ti?"],np:1},
{v:32,l:["Acaso uma jovem esquece os seus enfeites,","ou uma noiva o seu cinto?","Mas o meu povo se esqueceu de mim","há dias sem conta."],np:1},
{v:33,l:["Como sabes bem escolher o teu caminho","para buscar o amor!","Por isso ensinaste os teus caminhos","até às mulheres más."],np:1},
{v:34,l:["Até nas barras da tua roupa se encontra","o sangue de pobres inocentes,","que não surpreendeste arrombando a casa.","E, apesar de tudo isso,"],np:1,n:"A Lei só desculpava a morte de quem era surpreendido arrombando uma casa (Êxodo 22,1)."},
{v:35,l:["dizes: Sou inocente,","certamente a sua ira se afastou de mim.","Eis que vou entrar em julgamento contigo,","porque dizes: Não pequei."],np:1},
{v:36,l:["Com que leviandade mudas de caminho!","Também do Egito sairás envergonhada,","como saíste envergonhada da Assíria."],np:1},
{v:37,l:["Também de lá sairás com as mãos na cabeça,","pois o Senhor rejeitou aqueles em quem confiavas,","e não terás êxito com eles."],np:1}
];

window.TEXTOS_SEED["jeremias"][3] = [
{s:"A esposa infiel"},
{v:1,l:["Se um homem repudia a sua mulher,","e ela o deixa","e se casa com outro homem,","acaso ele voltará para ela?","Não ficaria aquela terra","completamente contaminada?","E tu, que te prostituíste com muitos amantes,","queres voltar para mim?","— oráculo do Senhor."],n:"A Lei proibia que o primeiro marido retomasse a mulher repudiada que se casara com outro (Deuteronômio 24,1–4)."},
{v:2,l:["Ergue os olhos para as colinas e vê:","onde é que não te deitaste com eles?","À beira dos caminhos te sentavas à espera deles,","como o árabe no deserto;","contaminaste a terra","com as tuas prostituições e a tua maldade."],np:1},
{v:3,l:["Por isso as chuvas foram retidas,","e não houve a chuva da primavera;","mas tu tens a fronte de uma prostituta,","recusas envergonhar-te."],np:1},
{v:4,l:["E agora me chamas: Meu pai,","tu és o amigo da minha juventude!"],np:1},
{v:5,l:["Acaso ele ficará irado para sempre,","guardará rancor até o fim?","Eis o que dizes,","mas fazes o mal quanto podes."],np:1},
{s:"As duas irmãs infiéis"},
{v:6,t:"O Senhor me disse no tempo do rei Josias: Viste o que fez Israel, a infiel? Ela foi a todo monte alto e debaixo de toda árvore frondosa, e ali se prostituiu."},
{v:7,t:"Eu pensava: Depois de ter feito tudo isso, ela voltará para mim; mas ela não voltou. E a sua irmã, Judá, a traidora, viu tudo isso."},
{v:8,t:"Viu que, por causa de todos os adultérios de Israel, a infiel, eu a tinha repudiado e lhe tinha dado a carta de divórcio; mas a sua irmã, Judá, a traidora, não teve medo: também ela foi e se prostituiu."},
{v:9,t:"Com a sua prostituição leviana contaminou a terra e cometeu adultério com a pedra e com a madeira.",n:"A pedra e a madeira: os ídolos e os postes sagrados."},
{v:10,t:"E, apesar de tudo isso, Judá, a sua irmã traidora, não voltou para mim de todo o coração, mas só com fingimento, oráculo do Senhor."},
{v:11,t:"O Senhor me disse: Israel, a infiel, mostrou-se mais justa do que Judá, a traidora.",np:1},
{s:"Convite à conversão"},
{v:12,l:["Vai e proclama estas palavras voltado para o norte e dize:","Volta, Israel, a infiel,","oráculo do Senhor;","não voltarei para vós um rosto irado,","pois eu sou misericordioso,","oráculo do Senhor,","e não guardo rancor para sempre."],n:"No hebraico há um jogo de palavras entre voltar (shuv) e infiel (meshuvá)."},
{v:13,l:["Reconhece somente a tua culpa:","te revoltaste contra o Senhor, teu Deus,","espalhaste os teus caminhos para os estrangeiros","debaixo de toda árvore frondosa,","e não ouvistes a minha voz,","oráculo do Senhor."],np:1},
{v:14,t:"Voltai, filhos rebeldes, oráculo do Senhor, pois eu sou o vosso esposo; tomarei um de cada cidade e dois de cada família e vos conduzirei a Sião.",np:1,n:"Esposo: o verbo hebraico (baal) significa ser senhor e ser marido; a Nova Vulgata traduz: eu sou o vosso Senhor."},
{v:15,t:"Eu vos darei pastores segundo o meu coração, que vos apascentarão com inteligência e sabedoria."},
{v:16,t:"E, quando vos tiverdes multiplicado e crescido na terra, naqueles dias, oráculo do Senhor, não se falará mais da arca da aliança do Senhor; ninguém pensará mais nela, ninguém se lembrará dela, ninguém sentirá a sua falta, nem se fará outra.",n:"A arca provavelmente desapareceu na destruição de 587 antes de Cristo; Jerusalém inteira será o trono do Senhor (v. 17)."},
{v:17,t:"Naquele tempo, chamarão Jerusalém Trono do Senhor; todas as nações se reunirão nela, em nome do Senhor, em Jerusalém, e não seguirão mais a obstinação do seu coração perverso."},
{v:18,t:"Naqueles dias, a casa de Judá se unirá à casa de Israel, e virão juntas da terra do norte para a terra que dei como herança aos vossos pais."},
{s:"O pai e os filhos"},
{v:19,l:["Eu tinha dito:","Como gostaria de te colocar entre os meus filhos","e te dar uma terra desejável,","a herança mais bela entre as nações!","E pensava: Vós me chamareis Meu pai","e não vos afastareis de mim."]},
{v:20,l:["Mas, como uma mulher trai o seu companheiro,","assim vós me traístes, casa de Israel,","oráculo do Senhor."],np:1},
{v:21,l:["Ouve-se uma voz sobre as colinas:","o choro e as súplicas dos filhos de Israel,","porque perverteram o seu caminho","e se esqueceram do Senhor, seu Deus."],np:1},
{v:22,l:["Voltai, filhos rebeldes,","e eu curarei as vossas rebeldias.","Eis-nos aqui, vimos a ti,","pois tu és o Senhor, nosso Deus."],np:1},
{v:23,l:["Na verdade, são mentira as colinas","e o tumulto dos montes;","na verdade, está no Senhor, nosso Deus,","a salvação de Israel."],np:1},
{v:24,l:["A Vergonha devorou o fruto do trabalho dos nossos pais,","desde a nossa juventude:","as suas ovelhas e os seus bois,","os seus filhos e as suas filhas."],np:1,n:"A Vergonha: nome de desprezo dado a Baal (compare 11,13)."},
{v:25,l:["Deitemo-nos na nossa vergonha,","e que a nossa desonra nos cubra,","pois pecamos contra o Senhor, nosso Deus,","nós e os nossos pais,","desde a nossa juventude até hoje,","e não ouvimos a voz do Senhor, nosso Deus."],np:1}
];

window.TEXTOS_SEED["jeremias"][4] = [
{s:"A verdadeira conversão"},
{v:1,l:["Se voltares, Israel,","oráculo do Senhor,","é para mim que deves voltar;","se tirares da minha presença as tuas abominações,","não andarás mais errante,"]},
{v:2,l:["e se jurares: Pela vida do Senhor!,","com verdade, com direito e com justiça,","então as nações se abençoarão nele","e nele se gloriarão."],np:1,n:"Compare Gênesis 12,3."},
{v:3,l:["Pois assim diz o Senhor","aos homens de Judá e a Jerusalém:","Lavrai para vós um campo novo","e não semeeis entre os espinhos."],np:1},
{v:4,l:["Circuncidai-vos para o Senhor,","tirai o prepúcio do vosso coração,","homens de Judá e habitantes de Jerusalém,","para que a minha ira não irrompa como fogo","e arda sem que ninguém a possa apagar,","por causa da maldade das vossas ações."],np:1,n:"Compare Deuteronômio 10,16 e Romanos 2,29."},
{s:"A invasão vinda do norte"},
{v:5,l:["Anunciai em Judá,","proclamai em Jerusalém,","dizei: Tocai a trombeta pela terra,","gritai com toda a força e dizei:","Reuni-vos, e entremos nas cidades fortificadas!"]},
{v:6,l:["Erguei um estandarte na direção de Sião,","fugi, não pareis,","pois faço vir do norte a desgraça","e uma grande ruína."],np:1},
{v:7,l:["O leão saiu da sua toca,","o destruidor das nações se pôs em marcha,","saiu do seu lugar","para reduzir a tua terra a um deserto:","as tuas cidades serão arrasadas","e ficarão sem habitantes."],np:1},
{v:8,l:["Por isso vesti-vos de saco,","lamentai-vos e gemei,","pois a ira ardente do Senhor","não se afastou de nós."],np:1},
{v:9,l:["Naquele dia,","oráculo do Senhor,","perderão a coragem o rei","e os chefes,","os sacerdotes ficarão aterrados,","e os profetas, estupefatos."],np:1},
{v:10,l:["Então eu disse: Ah, Senhor Deus!","Na verdade enganaste completamente este povo e Jerusalém,","dizendo: Tereis paz!","E eis que a espada chega à garganta."],np:1,n:"Nota do tradutor: o profeta atribui a Deus o engano dos falsos profetas, que prometiam a paz (compare 14,13–14); é a queixa de quem não compreende, e o texto não a atenua."},
{v:11,l:["Naquele tempo se dirá a este povo e a Jerusalém:","Um vento ardente das colinas do deserto","avança contra a filha do meu povo,","não para joeirar nem para limpar;"],np:1},
{v:12,l:["um vento forte demais para isso vem da minha parte.","Agora também eu pronunciarei contra eles as minhas sentenças."],np:1},
{v:13,l:["Eis que ele sobe como as nuvens,","os seus carros são como o furacão,","os seus cavalos, mais velozes que as águias.","Ai de nós, estamos perdidos!"],np:1},
{v:14,l:["Lava o teu coração da maldade,","Jerusalém, para seres salva;","até quando abrigarás dentro de ti","os teus pensamentos iníquos?"],np:1},
{v:15,l:["Pois uma voz anuncia desde Dã,","e proclama a desgraça desde as montanhas de Efraim."],np:1},
{v:16,l:["Avisai as nações: Eis que chegam!","Anunciai a Jerusalém:","Sitiantes vêm de uma terra distante","e lançam os seus gritos contra as cidades de Judá;"],np:1},
{v:17,l:["como guardas de um campo, cercam-na por todos os lados,","porque ela se rebelou contra mim,","oráculo do Senhor."],np:1},
{v:18,l:["O teu comportamento e as tuas ações","te trouxeram isto;","esta é a tua desgraça: como é amarga,","como te atinge o coração!"],np:1},
{s:"A angústia do profeta"},
{v:19,l:["As minhas entranhas, as minhas entranhas! Contorço-me de dor!","As paredes do meu coração!","O meu coração se agita dentro de mim;","não posso calar-me,","pois ouvi o som da trombeta,","o grito de guerra."]},
{v:20,l:["Anuncia-se desastre sobre desastre,","pois toda a terra está devastada;","de repente as minhas tendas foram destruídas,","num instante, as minhas lonas."],np:1},
{v:21,l:["Até quando verei o estandarte","e ouvirei o som da trombeta?"],np:1},
{v:22,l:["Pois o meu povo é insensato,","não me conhece;","são filhos tolos,","sem inteligência;","são hábeis para fazer o mal,","mas não sabem fazer o bem."],np:1},
{s:"A visão do caos"},
{v:23,l:["Olhei para a terra, e eis que era caos e vazio;","para os céus, e não havia luz."],n:"Caos e vazio: em hebraico tohu e bohu, as palavras de Gênesis 1,2; a criação parece voltar ao estado anterior à luz."},
{v:24,l:["Olhei para os montes, e eis que tremiam,","e todas as colinas oscilavam."],np:1},
{v:25,l:["Olhei, e eis que não havia ninguém,","e todas as aves do céu tinham fugido."],np:1},
{v:26,l:["Olhei, e eis que o pomar era um deserto,","e todas as suas cidades estavam arrasadas","diante do Senhor, diante da sua ira ardente."],np:1},
{v:27,l:["Pois assim diz o Senhor:","Toda a terra ficará desolada,","mas não farei o extermínio total."],np:1},
{v:28,l:["Por isso a terra estará de luto,","e os céus lá em cima se escurecerão,","porque eu falei, eu decidi,","e não me arrependo nem volto atrás."],np:1},
{v:29,l:["Ao grito dos cavaleiros e dos arqueiros","foge toda a cidade;","entram nas moitas","e sobem aos rochedos;","todas as cidades estão abandonadas,","e ninguém habita nelas."],np:1},
{v:30,l:["E tu, devastada, que farás?","Ainda que te vistas de escarlate,","ainda que te enfeites com joias de ouro","e alargues os olhos com pintura,","em vão te embelezas;","os teus amantes te desprezam,","procuram a tua vida."],np:1},
{v:31,l:["Ouço gritos como de mulher em trabalho de parto,","angústia como de quem dá à luz o primeiro filho:","é a voz da filha de Sião, que ofega","e estende as mãos:","Ai de mim! Desfaleço","diante dos assassinos!"],np:1}
];
