// =====================================================================
// Josué — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["josue"][1] = [
{s:"O Senhor fala a Josué"},
{v:1,t:"Depois da morte de Moisés, servo do Senhor, o Senhor falou a Josué, filho de Nun, auxiliar de Moisés, e disse-lhe:",n:"O livro de Josué abre a série que a Bíblia hebraica chama Profetas anteriores — Josué, Juízes, Samuel e Reis —: a história de Israel na terra, da entrada até o exílio. Josué, Yehoshua, quer dizer o Senhor salva; é o mesmo nome de Jesus."},
{v:2,t:"Moisés, meu servo, morreu. Agora, pois, levanta-te e atravessa este Jordão, tu e todo este povo, para a terra que eu vou dar aos filhos de Israel."},
{v:3,t:"Eu vos dei todo lugar que a planta dos vossos pés pisar, como disse a Moisés."},
{v:4,t:"Desde o deserto e este Líbano até o grande rio, o Eufrates, toda a terra dos heteus, e até o mar Grande, para o poente, será o vosso território.",n:"São as fronteiras ideais da promessa, que Israel só alcançou, e em parte, no tempo de Davi e de Salomão. O mar Grande é o Mediterrâneo."},
{v:5,t:"Ninguém te poderá resistir em todos os dias da tua vida: como estive com Moisés, estarei contigo; não te deixarei nem te abandonarei."},
{v:6,t:"Sê forte e corajoso, porque tu farás este povo herdar a terra que jurei a seus pais que lhes daria.",np:1},
{v:7,t:"Tão somente sê forte e muito corajoso, para cuidares de agir segundo toda a lei que Moisés, meu servo, te prescreveu. Não te desvies dela nem para a direita nem para a esquerda, para que sejas bem-sucedido em tudo o que empreenderes."},
{v:8,t:"Que este livro da lei não se aparte da tua boca; medita nele dia e noite, para cuidares de agir segundo tudo o que nele está escrito: então prosperarás no teu caminho e serás bem-sucedido.",n:"Meditar, em hebraico, é também murmurar: a leitura antiga fazia-se a meia-voz. O primeiro salmo retoma a frase: feliz o homem que medita a lei do Senhor dia e noite."},
{v:9,t:"Não te mandei eu? Sê forte e corajoso; não te atemorizes nem te espantes, porque o Senhor teu Deus está contigo em tudo o que empreenderes."},
{s:"Preparativos para a travessia"},
{v:10,t:"Então Josué deu ordem aos oficiais do povo, dizendo:",np:1},
{v:11,t:"Passai pelo meio do acampamento e dai esta ordem ao povo: Preparai provisões, porque daqui a três dias atravessareis este Jordão, para entrardes na posse da terra que o Senhor vosso Deus vos dá."},
{v:12,t:"Aos rubenitas, aos gaditas e à meia tribo de Manassés, Josué disse:",np:1},
{v:13,t:"Lembrai-vos da palavra que Moisés, servo do Senhor, vos ordenou, dizendo: O Senhor vosso Deus vos concede repouso e vos dá esta terra.",n:"Estas tribos tinham recebido a sua parte a leste do Jordão, em Galaad e em Basã, como conta o livro dos Números, com a condição de ajudarem as outras na conquista."},
{v:14,t:"As vossas mulheres, os vossos filhos e os vossos rebanhos ficarão na terra que Moisés vos deu do outro lado do Jordão; mas vós, todos os guerreiros valentes, passareis armados à frente dos vossos irmãos e os ajudareis,"},
{v:15,t:"até que o Senhor dê repouso a vossos irmãos, como a vós, e também eles tomem posse da terra que o Senhor vosso Deus lhes dá. Então voltareis para a terra da vossa posse e a possuireis, a terra que Moisés, servo do Senhor, vos deu do outro lado do Jordão, para o nascente."},
{v:16,t:"Eles responderam a Josué: Faremos tudo o que nos ordenaste e iremos aonde quer que nos enviares.",np:1},
{v:17,t:"Assim como obedecemos em tudo a Moisés, assim também te obedeceremos; somente esteja contigo o Senhor teu Deus, como esteve com Moisés."},
{v:18,t:"Todo aquele que se rebelar contra as tuas ordens e não obedecer às tuas palavras, em tudo o que lhe mandares, será morto. Tão somente sê forte e corajoso."}
];

window.TEXTOS_SEED["josue"][2] = [
{s:"Raab e os espiões"},
{v:1,t:"Josué, filho de Nun, enviou secretamente de Setim dois homens como espiões, dizendo-lhes: Ide, examinai a terra e Jericó. Eles foram, entraram na casa de uma prostituta chamada Raab, e ali pousaram.",n:"Setim, à letra as acácias, era o último acampamento de Israel a leste do Jordão, nas planícies de Moab. Raab é lembrada no Evangelho segundo São Mateus entre as antepassadas de Jesus, e a Carta aos Hebreus e a de Tiago louvam-lhe a fé e as obras."},
{v:2,t:"Foi dito ao rei de Jericó: Eis que alguns homens dos filhos de Israel entraram aqui esta noite para explorar a terra."},
{v:3,t:"O rei de Jericó mandou dizer a Raab: Faze sair os homens que vieram a ti e entraram na tua casa, porque vieram explorar toda a terra."},
{v:4,t:"Mas a mulher tomou os dois homens e os escondeu; e disse: É verdade que esses homens vieram a mim, mas eu não sabia de onde eram;"},
{v:5,t:"e, quando a porta da cidade ia ser fechada, ao escurecer, eles saíram; não sei para onde foram. Persegui-os depressa, e os alcançareis.",n:"Nota do tradutor: a Escritura conta a mentira de Raab sem a aprovar nem a condenar. O que a Carta aos Hebreus e a de Tiago louvam nela é a fé e a acolhida aos enviados; Santo Agostinho, que tratou do caso, distingue a bondade, que foi recompensada, da mentira, que foi perdoada."},
{v:6,t:"Ela, porém, os tinha feito subir ao terraço e os escondera debaixo dos feixes de linho que ali tinha estendidos."},
{v:7,t:"Os homens os perseguiram pelo caminho do Jordão, até os vaus; e, assim que saíram os perseguidores, a porta foi fechada."},
{v:8,t:"Antes que os espiões se deitassem, ela subiu ao terraço onde eles estavam",np:1},
{v:9,t:"e disse-lhes: Sei que o Senhor vos deu esta terra, que o terror de vós caiu sobre nós, e que todos os habitantes da terra desfalecem diante de vós."},
{v:10,t:"Pois ouvimos como o Senhor secou as águas do mar Vermelho diante de vós, quando saístes do Egito, e o que fizestes aos dois reis dos amorreus do outro lado do Jordão, Seon e Og, que votastes ao extermínio.",n:"Votar ao extermínio traduz o hebraico herem: a consagração total ao Senhor dos vencidos e dos despojos, que eram destruídos. Veja-se a nota ao capítulo 6, versículo 17."},
{v:11,t:"Ao ouvirmos isso, o nosso coração desfaleceu, e ninguém mais tem ânimo diante de vós, porque o Senhor vosso Deus é Deus lá em cima, nos céus, e cá embaixo, na terra.",n:"Uma pagã de Jericó faz, com as palavras do Deuteronômio, a confissão de fé mais completa do livro."},
{v:12,t:"Agora, pois, jurai-me pelo Senhor que, assim como eu vos tratei com bondade, também vós tratareis com bondade a casa de meu pai; e dai-me um sinal seguro"},
{v:13,t:"de que conservareis a vida de meu pai e de minha mãe, de meus irmãos e de minhas irmãs, e de tudo o que é deles, e livrareis da morte as nossas vidas."},
{v:14,t:"Os homens responderam-lhe: A nossa vida responde pela vossa, contanto que não denuncieis o que estamos fazendo; e, quando o Senhor nos der a terra, usaremos contigo de bondade e de fidelidade."},
{v:15,t:"Então ela os desceu com uma corda pela janela, porque a sua casa ficava encostada à muralha da cidade, e ela morava na muralha."},
{v:16,t:"E disse-lhes: Ide para a montanha, para que os perseguidores não vos encontrem; escondei-vos ali três dias, até que eles voltem; depois seguireis o vosso caminho."},
{v:17,t:"Os homens disseram-lhe: Estaremos livres deste juramento que nos fizeste jurar,",np:1},
{v:18,t:"se não fizeres assim: quando entrarmos na terra, atarás este cordão de fio escarlate à janela pela qual nos desceste, e reunirás contigo em casa teu pai, tua mãe, teus irmãos e toda a família de teu pai.",n:"O cordão escarlate, como o sangue do cordeiro nas portas das casas no Egito, marca a casa que será poupada. Os Padres, desde São Clemente de Roma, viram nele uma figura do sangue de Cristo."},
{v:19,t:"Qualquer que sair pelas portas da tua casa para a rua, o seu sangue cairá sobre a sua cabeça, e nós seremos inocentes; mas o sangue de qualquer um que estiver contigo em casa cairá sobre a nossa cabeça, se alguém puser a mão nele."},
{v:20,t:"E, se denunciares o que estamos fazendo, estaremos livres do juramento que nos fizeste jurar."},
{v:21,t:"Ela respondeu: Seja conforme as vossas palavras. E despediu-os, e eles partiram; e ela atou o cordão escarlate à janela."},
{v:22,t:"Eles partiram e foram para a montanha, e ficaram ali três dias, até que voltaram os perseguidores; estes os procuraram por todo o caminho, mas não os encontraram.",np:1},
{v:23,t:"Então os dois homens voltaram, desceram da montanha, atravessaram o Jordão e foram ter com Josué, filho de Nun; e contaram-lhe tudo o que lhes acontecera."},
{v:24,t:"E disseram a Josué: O Senhor entregou toda a terra em nossas mãos, e todos os habitantes da terra desfalecem diante de nós."}
];

window.TEXTOS_SEED["josue"][3] = [
{s:"A travessia do Jordão"},
{v:1,t:"Josué levantou-se de madrugada; partiram de Setim e chegaram ao Jordão, ele e todos os filhos de Israel; e pernoitaram ali antes de atravessar."},
{v:2,t:"Ao fim de três dias, os oficiais passaram pelo meio do acampamento",np:1},
{v:3,t:"e deram esta ordem ao povo: Quando virdes a arca da aliança do Senhor vosso Deus, levada pelos sacerdotes levitas, partireis também vós do vosso lugar e a seguireis",n:"A arca da aliança, cofre de madeira revestido de ouro que guardava as tábuas da Lei, era o sinal da presença do Senhor no meio do povo. Na travessia, é ela que vai à frente: quem abre o caminho é o Senhor."},
{v:4,t:"— haja, porém, entre vós e ela a distância de uns dois mil côvados; não vos aproximeis dela —, para que saibais o caminho por onde deveis ir, pois nunca passastes por este caminho.",n:"Dois mil côvados são cerca de um quilômetro: a distância do respeito diante do sagrado, que permitia também a todos verem a arca."},
{v:5,t:"Josué disse ao povo: Santificai-vos, porque amanhã o Senhor fará maravilhas no meio de vós."},
{v:6,t:"E disse aos sacerdotes: Levantai a arca da aliança e passai à frente do povo. Eles levantaram a arca da aliança e foram à frente do povo."},
{v:7,t:"O Senhor disse a Josué: Hoje começarei a engrandecer-te aos olhos de todo o Israel, para que saibam que, assim como estive com Moisés, estarei contigo.",np:1},
{v:8,t:"Quanto a ti, dá esta ordem aos sacerdotes que levam a arca da aliança: Quando chegardes à beira das águas do Jordão, parai no Jordão."},
{v:9,t:"Josué disse aos filhos de Israel: Aproximai-vos e ouvi as palavras do Senhor vosso Deus.",np:1},
{v:10,t:"E acrescentou: Nisto conhecereis que o Deus vivo está no meio de vós, e que expulsará diante de vós os cananeus, os heteus, os heveus, os ferezeus, os gergeseus, os amorreus e os jebuseus:"},
{v:11,t:"eis que a arca da aliança do Senhor de toda a terra vai atravessar o Jordão à vossa frente."},
{v:12,t:"Escolhei, pois, doze homens das tribos de Israel, um homem de cada tribo;"},
{v:13,t:"e, logo que as plantas dos pés dos sacerdotes que levam a arca do Senhor, Senhor de toda a terra, pousarem nas águas do Jordão, as águas do Jordão serão cortadas: as águas que descem de cima pararão, formando um só dique."},
{v:14,t:"Quando o povo partiu das suas tendas para atravessar o Jordão, os sacerdotes que levavam a arca da aliança iam à frente do povo.",np:1},
{v:15,t:"E, quando os que levavam a arca chegaram ao Jordão, e os pés dos sacerdotes que levavam a arca tocaram a beira das águas — o Jordão transborda por todas as suas margens durante todo o tempo da colheita —,",n:"A colheita da cevada, na primavera, é o tempo das cheias do Jordão, engrossado pelo degelo do Hermon."},
{v:16,t:"as águas que desciam de cima pararam e formaram um só dique, muito longe, junto de Adam, a cidade que fica ao lado de Sartã; e as que desciam para o mar da Arabá, o mar Salgado, escoaram-se completamente.",n:"Adam fica junto ao vau de Damiya, uns trinta quilômetros ao norte de Jericó. Ali, em 1267 e em 1927, desmoronamentos das margens represaram o rio durante horas. O texto, porém, não conta um fenômeno natural, mas um sinal: o Deus que abriu o mar Vermelho abre o Jordão."},
{v:17,t:"O povo passava defronte de Jericó, e os sacerdotes que levavam a arca da aliança do Senhor estavam parados, a pé firme, em terra seca, no meio do Jordão, enquanto todo o Israel passava a pé enxuto, até que toda a nação acabou de atravessar o Jordão."}
];

window.TEXTOS_SEED["josue"][4] = [
{s:"As doze pedras"},
{v:1,t:"Quando toda a nação acabou de atravessar o Jordão, o Senhor disse a Josué:"},
{v:2,t:"Escolhei dentre o povo doze homens, um homem de cada tribo,"},
{v:3,t:"e dai-lhes esta ordem: Tirai daqui, do meio do Jordão, do lugar onde os pés dos sacerdotes estiveram firmes, doze pedras; levai-as convosco e depositai-as no lugar onde passareis esta noite."},
{v:4,t:"Josué chamou os doze homens que escolhera dentre os filhos de Israel, um homem de cada tribo,",np:1},
{v:5,t:"e disse-lhes: Passai à frente da arca do Senhor vosso Deus até o meio do Jordão, e cada um de vós ponha uma pedra sobre o ombro, conforme o número das tribos dos filhos de Israel,"},
{v:6,t:"para que isto seja um sinal no meio de vós. Quando amanhã os vossos filhos vos perguntarem: Que significam para vós estas pedras?,"},
{v:7,t:"respondereis: As águas do Jordão foram cortadas diante da arca da aliança do Senhor; quando ela atravessou o Jordão, as águas do Jordão foram cortadas. Estas pedras serão para os filhos de Israel um memorial para sempre.",n:"A pergunta dos filhos é a que o Êxodo põe na boca das crianças na noite da Páscoa: que significa este rito? A fé de Israel transmite-se em respostas a perguntas de crianças."},
{v:8,t:"Os filhos de Israel fizeram como Josué lhes ordenara: tiraram doze pedras do meio do Jordão, como o Senhor dissera a Josué, conforme o número das tribos dos filhos de Israel; levaram-nas consigo até o lugar onde pernoitaram, e ali as depositaram."},
{v:9,t:"Josué erigiu também doze pedras no meio do Jordão, no lugar onde tinham estado os pés dos sacerdotes que levavam a arca da aliança; e ali estão até o dia de hoje.",n:"Há no capítulo duas tradições sobre as pedras: umas levadas para Guilgal, outras erguidas no leito do rio. O narrador conserva as duas."},
{v:10,t:"Os sacerdotes que levavam a arca ficaram parados no meio do Jordão até que se cumpriu tudo o que o Senhor mandara Josué dizer ao povo, segundo tudo o que Moisés ordenara a Josué; e o povo apressou-se a atravessar.",np:1},
{v:11,t:"Quando todo o povo acabou de atravessar, passou também a arca do Senhor, e os sacerdotes foram à frente do povo."},
{v:12,t:"Os filhos de Rúben, os filhos de Gad e a meia tribo de Manassés passaram armados à frente dos filhos de Israel, como Moisés lhes dissera;"},
{v:13,t:"uns quarenta mil homens armados para a guerra passaram diante do Senhor para o combate, nas planícies de Jericó."},
{v:14,t:"Naquele dia, o Senhor engrandeceu Josué aos olhos de todo o Israel, e temeram-no, como tinham temido Moisés, todos os dias da sua vida."},
{v:15,t:"O Senhor disse a Josué:",np:1},
{v:16,t:"Ordena aos sacerdotes que levam a arca do testemunho que subam do Jordão."},
{v:17,t:"Josué ordenou aos sacerdotes: Subi do Jordão."},
{v:18,t:"E, quando os sacerdotes que levavam a arca da aliança do Senhor subiram do meio do Jordão, mal as plantas dos pés dos sacerdotes pisaram a terra seca, as águas do Jordão voltaram ao seu lugar e correram como antes, por cima de todas as margens."},
{s:"Guilgal"},
{v:19,t:"O povo subiu do Jordão no décimo dia do primeiro mês e acampou em Guilgal, no limite oriental de Jericó.",np:1,n:"O décimo dia do primeiro mês é aquele em que, segundo o Êxodo, se escolhia o cordeiro da Páscoa: quarenta anos depois de sair do Egito, Israel entra na terra no tempo da Páscoa. Guilgal quer dizer círculo, talvez de pedras."},
{v:20,t:"E Josué erigiu em Guilgal aquelas doze pedras que tinham tirado do Jordão."},
{v:21,t:"E disse aos filhos de Israel: Quando amanhã os vossos filhos perguntarem a seus pais: Que significam estas pedras?,"},
{v:22,t:"fareis saber a vossos filhos: Israel atravessou este Jordão a pé enxuto,"},
{v:23,t:"porque o Senhor vosso Deus secou as águas do Jordão diante de vós, até que atravessastes,"},
{v:24,t:"como o Senhor vosso Deus tinha feito ao mar Vermelho, que ele secou diante de nós até que atravessamos,"},
{v:25,t:"para que todos os povos da terra saibam que a mão do Senhor é forte, e para que temais o Senhor vosso Deus todos os dias.",n:"A Nova Vulgata divide em três versículos, 23 a 25, o que o hebraico conta em dois; por isso este capítulo tem aqui um versículo a mais que outras Bíblias."}
];

window.TEXTOS_SEED["josue"][5] = [
{s:"A circuncisão em Guilgal"},
{v:1,t:"Quando todos os reis dos amorreus que estavam do outro lado do Jordão, para o ocidente, e todos os reis dos cananeus que estavam junto ao mar souberam que o Senhor tinha secado as águas do Jordão diante dos filhos de Israel até que atravessaram, desfaleceu-lhes o coração, e não houve mais ânimo neles diante dos filhos de Israel."},
{v:2,t:"Naquele tempo, o Senhor disse a Josué: Faze facas de pedra e circuncida de novo os filhos de Israel, pela segunda vez.",np:1,n:"Facas de pedra: o rito conserva um instrumento mais antigo que o metal. Pela segunda vez não quer dizer que se circuncidassem os já circuncidados, mas que se retomava no povo o rito interrompido no deserto, como explicam os versículos seguintes."},
{v:3,t:"Josué fez facas de pedra e circuncidou os filhos de Israel na colina dos Prepúcios."},
{v:4,t:"Eis a razão por que Josué os circuncidou: todo o povo que tinha saído do Egito, os homens, todos os guerreiros, tinham morrido no deserto, pelo caminho, depois de saírem do Egito."},
{v:5,t:"Todo o povo que saíra estava circuncidado; mas todo o povo nascido no deserto, pelo caminho, depois da saída do Egito, não fora circuncidado."},
{v:6,t:"Pois os filhos de Israel andaram quarenta anos pelo deserto, até que desapareceu toda a nação, os guerreiros que tinham saído do Egito e não tinham escutado a voz do Senhor; a eles o Senhor jurara que não os deixaria ver a terra que prometera com juramento a seus pais dar-nos, terra onde corre leite e mel."},
{v:7,t:"Foram os seus filhos, que ele suscitou em lugar deles, que Josué circuncidou; eram incircuncisos, porque não os tinham circuncidado pelo caminho."},
{v:8,t:"Quando acabaram de circuncidar toda a nação, ficaram no seu lugar, no acampamento, até se curarem."},
{v:9,t:"E o Senhor disse a Josué: Hoje tirei de cima de vós a vergonha do Egito. Por isso aquele lugar se chama Guilgal até o dia de hoje.",n:"Tirei, em hebraico galloti, soa como Guilgal: o nome do lugar é explicado por um jogo de palavras, como tantas vezes na Bíblia."},
{s:"A primeira Páscoa na terra"},
{v:10,t:"Os filhos de Israel acamparam em Guilgal e celebraram a Páscoa no décimo quarto dia do mês, à tarde, nas planícies de Jericó.",np:1},
{v:11,t:"E, no dia seguinte à Páscoa, comeram dos produtos da terra, pães ázimos e grãos tostados, naquele mesmo dia."},
{v:12,t:"O maná cessou no dia seguinte, quando comeram dos produtos da terra; e os filhos de Israel não tiveram mais maná, mas comeram, naquele ano, dos frutos da terra de Canaã.",n:"O maná acompanhou o povo durante os quarenta anos do deserto e cessa quando a terra dá o seu pão. A Igreja leu no maná uma figura da Eucaristia, pão do caminho até a terra definitiva."},
{s:"O chefe do exército do Senhor"},
{v:13,t:"Estando Josué perto de Jericó, levantou os olhos e viu um homem de pé diante dele, com a espada desembainhada na mão. Josué foi ter com ele e perguntou-lhe: És dos nossos ou dos nossos inimigos?",np:1},
{v:14,t:"Ele respondeu: Não; mas eu sou o chefe do exército do Senhor, e acabo de chegar.",n:"Não: a pergunta de Josué está mal posta. O Senhor não é de um partido; é Israel que tem de estar do lado dele."},
{v:15,t:"Josué prostrou-se com o rosto por terra, adorou e disse-lhe: Que diz o meu senhor ao seu servo?"},
{v:16,t:"O chefe do exército do Senhor disse a Josué: Tira as sandálias dos pés, porque o lugar em que estás é santo. E Josué assim fez.",n:"São as palavras ditas a Moisés diante da sarça: Josué é confirmado como sucessor de Moisés. A Nova Vulgata divide em dois versículos, 14 e 15, o que o hebraico conta como um só; por isso o capítulo tem um versículo a mais que em outras Bíblias."}
];

window.TEXTOS_SEED["josue"][6] = [
{s:"A tomada de Jericó"},
{v:1,t:"Jericó estava fechada e bem trancada por causa dos filhos de Israel: ninguém saía nem entrava."},
{v:2,t:"O Senhor disse a Josué: Vê, entreguei nas tuas mãos Jericó, o seu rei e os seus valentes guerreiros.",np:1},
{v:3,t:"Vós, todos os homens de guerra, rodeareis a cidade, dando uma volta em torno dela; assim farás durante seis dias."},
{v:4,t:"Sete sacerdotes levarão sete trombetas de chifre de carneiro à frente da arca. No sétimo dia, dareis sete voltas à cidade, e os sacerdotes tocarão as trombetas.",n:"O número sete domina o relato: sete sacerdotes, sete trombetas, sete dias, sete voltas. A tomada de Jericó é contada como uma liturgia, e não como uma batalha."},
{v:5,t:"Quando se tocar longamente o chifre de carneiro e ouvirdes o som da trombeta, todo o povo soltará um grande grito; a muralha da cidade cairá por terra, e o povo subirá, cada um em frente de si."},
{v:6,t:"Josué, filho de Nun, chamou os sacerdotes e disse-lhes: Levantai a arca da aliança, e sete sacerdotes levem sete trombetas de chifre de carneiro à frente da arca do Senhor.",np:1},
{v:7,t:"E disse ao povo: Avançai e rodeai a cidade, e os homens armados passem à frente da arca do Senhor."},
{v:8,t:"Quando Josué acabou de falar ao povo, os sete sacerdotes que levavam as sete trombetas de chifre de carneiro diante do Senhor avançaram e tocaram as trombetas, e a arca da aliança do Senhor os seguia."},
{v:9,t:"Os homens armados iam à frente dos sacerdotes que tocavam as trombetas, e a retaguarda seguia a arca; tocavam-se as trombetas sem parar."},
{v:10,t:"Josué dera esta ordem ao povo: Não griteis, não deixeis ouvir a vossa voz, nem saia palavra da vossa boca, até o dia em que eu vos disser: Gritai! Então gritareis."},
{v:11,t:"Assim, a arca do Senhor deu uma volta em torno da cidade; depois voltaram ao acampamento e ali pernoitaram."},
{v:12,t:"Josué levantou-se de madrugada, e os sacerdotes levaram a arca do Senhor.",np:1},
{v:13,t:"Os sete sacerdotes que levavam as sete trombetas de chifre de carneiro à frente da arca do Senhor avançavam, tocando as trombetas; os homens armados iam à frente deles, e a retaguarda seguia a arca do Senhor; tocavam-se as trombetas sem parar."},
{v:14,t:"No segundo dia, deram uma volta em torno da cidade e voltaram ao acampamento. Assim fizeram durante seis dias."},
{v:15,t:"No sétimo dia, levantaram-se ao romper da aurora e deram sete voltas à cidade, da mesma maneira; somente naquele dia deram sete voltas à cidade.",np:1},
{v:16,t:"Na sétima vez, quando os sacerdotes tocavam as trombetas, Josué disse ao povo: Gritai, porque o Senhor vos entregou a cidade!"},
{v:17,t:"A cidade será votada ao extermínio para o Senhor, ela e tudo o que nela há; somente Raab, a prostituta, viverá, ela e todos os que estiverem com ela em casa, porque escondeu os mensageiros que enviamos.",n:"Nota do tradutor: votar ao extermínio traduz o hebraico herem, a consagração total ao Senhor de uma cidade vencida, que devia ser inteiramente destruída, sem saque. A prática é conhecida fora de Israel: Mesa, rei de Moab, numa inscrição do século IX antes de Cristo, gaba-se de ter votado ao seu deus uma cidade israelita. Estas páginas estão entre as mais difíceis da Escritura, e traduzem-se sem atenuar. A própria Bíblia mostra que a conquista não foi total nem instantânea — o livro dos Juízes o diz logo no começo —, e muitos estudiosos leem estes relatos, escritos séculos depois, como linguagem de guerra própria do antigo Oriente e como catequese contra a idolatria, mais do que como crônica. A Igreja lê-os à luz de Cristo, que não veio para perder vidas, mas para salvá-las; e os Padres viram neles uma figura do combate contra o pecado. Não autorizam violência alguma: nenhum povo tem hoje mandato divino para exterminar outro."},
{v:18,t:"Mas vós, guardai-vos do que é votado ao extermínio, para que não vos torneis também vós anátema tomando alguma coisa dele, e não façais do acampamento de Israel um anátema, trazendo-lhe a desgraça."},
{v:19,t:"Toda a prata e o ouro, e os objetos de bronze e de ferro, serão consagrados ao Senhor e entrarão no tesouro do Senhor."},
{v:20,t:"O povo gritou, e tocaram-se as trombetas. Quando o povo ouviu o som da trombeta e soltou um grande grito, a muralha caiu por terra; o povo subiu à cidade, cada um em frente de si, e tomaram a cidade.",np:1,n:"As escavações de Jericó não encontraram muralhas do tempo em que a conquista costuma ser situada; a cidade estava então em grande parte abandonada. O relato fala a linguagem da fé: não são as armas de Israel que derrubam as muralhas, mas o Senhor. A Carta aos Hebreus lê o episódio assim: pela fé caíram as muralhas de Jericó."},
{v:21,t:"E votaram ao extermínio, ao fio da espada, tudo o que havia na cidade: homens e mulheres, crianças e velhos, bois, ovelhas e jumentos."},
{v:22,t:"Josué disse aos dois homens que tinham espionado a terra: Entrai na casa da prostituta e fazei sair dali a mulher e tudo o que é dela, como lhe jurastes.",np:1},
{v:23,t:"Os jovens espiões entraram e fizeram sair Raab, seu pai, sua mãe, seus irmãos e tudo o que era dela; fizeram sair toda a sua família e os instalaram fora do acampamento de Israel.",n:"Fora do acampamento: os que vinham de fora ficavam primeiro à margem, até serem integrados. Raab acabou fazendo parte do povo, diz o versículo 25."},
{v:24,t:"Depois incendiaram a cidade e tudo o que nela havia; somente a prata e o ouro, e os objetos de bronze e de ferro, puseram-nos no tesouro da casa do Senhor."},
{v:25,t:"Mas Josué conservou a vida de Raab, a prostituta, da casa de seu pai e de tudo o que era dela; e ela habitou no meio de Israel até o dia de hoje, porque escondeu os mensageiros que Josué enviara para espionar Jericó. Naquele tempo, Josué pronunciou esta maldição:"},
{v:26,t:"Maldito diante do Senhor seja o homem que se levantar para reedificar esta cidade de Jericó! Sobre o seu primogênito lançará os alicerces, e sobre o seu filho mais novo levantará as portas.",n:"A maldição cumpre-se no Primeiro Livro dos Reis, no tempo de Acab: Hiel de Betel reconstruiu Jericó à custa do filho mais velho e do mais novo."},
{v:27,t:"O Senhor estava com Josué, e a sua fama espalhou-se por toda a terra."}
];

window.TEXTOS_SEED["josue"][7] = [
{s:"O pecado de Acã"},
{v:1,t:"Mas os filhos de Israel cometeram uma infidelidade a respeito do que era votado ao extermínio: Acã, filho de Carmi, filho de Zabdi, filho de Zara, da tribo de Judá, tomou alguma coisa do que era votado ao extermínio, e a ira do Senhor inflamou-se contra os filhos de Israel.",n:"O pecado de um só atinge o povo inteiro: Israel é pensado como um corpo. São Paulo dirá o mesmo da Igreja: se um membro sofre, todos sofrem com ele."},
{v:2,t:"Josué enviou homens de Jericó a Hai, que fica perto de Bet-Áven, a leste de Betel, e disse-lhes: Subi e explorai a terra. Os homens subiram e exploraram Hai.",np:1,n:"Hai quer dizer a ruína."},
{v:3,t:"Voltaram a Josué e disseram-lhe: Não suba todo o povo; subam uns dois ou três mil homens e destruam Hai. Não fatigues todo o povo lá, porque eles são poucos."},
{v:4,t:"Subiram, pois, para lá cerca de três mil homens do povo; mas fugiram diante dos homens de Hai."},
{v:5,t:"Os homens de Hai mataram-lhes uns trinta e seis homens, perseguiram-nos desde a porta até Sebarim e os derrotaram na descida. E o coração do povo desfaleceu e tornou-se como água."},
{v:6,t:"Josué rasgou as vestes e prostrou-se com o rosto em terra diante da arca do Senhor até a tarde, ele e os anciãos de Israel; e lançaram pó sobre a cabeça.",np:1},
{v:7,t:"E Josué disse: Ah, Senhor Deus! Por que fizeste este povo atravessar o Jordão, para nos entregar nas mãos dos amorreus e nos fazer perecer? Antes nos tivéssemos contentado em ficar do outro lado do Jordão!",n:"A oração de Josué lembra as queixas do povo no deserto: antes tivéssemos ficado no Egito. Mas é oração, feita diante da arca: a queixa dirigida a Deus é ainda fé."},
{v:8,t:"Ah, Senhor! Que direi, depois que Israel virou as costas diante dos seus inimigos?"},
{v:9,t:"Os cananeus e todos os habitantes da terra vão saber disso; vão cercar-nos e apagar o nosso nome da terra. E que farás tu pelo teu grande nome?"},
{v:10,t:"O Senhor disse a Josué: Levanta-te! Por que estás prostrado com o rosto em terra?",np:1},
{v:11,t:"Israel pecou; transgrediram a minha aliança, que eu lhes prescrevi; tomaram do que era votado ao extermínio, roubaram, mentiram e o puseram entre as suas bagagens."},
{v:12,t:"Por isso os filhos de Israel não podem resistir aos seus inimigos: viram as costas diante deles, porque se tornaram eles mesmos anátema. Não estarei mais convosco, se não eliminardes do meio de vós o que é votado ao extermínio."},
{v:13,t:"Levanta-te, santifica o povo e dize: Santificai-vos para amanhã, porque assim diz o Senhor, Deus de Israel: Há um anátema no meio de ti, Israel; não poderás resistir aos teus inimigos enquanto não tirardes o anátema do meio de vós."},
{v:14,t:"Amanhã vos apresentareis por tribos; a tribo que o Senhor designar se apresentará por clãs; o clã que o Senhor designar se apresentará por famílias; e a família que o Senhor designar se apresentará homem por homem.",n:"Designar, à letra tomar: a escolha fazia-se provavelmente por sorte, com os Urim e Tumim do sumo sacerdote, como na escolha de Saul, no Primeiro Livro de Samuel."},
{v:15,t:"Aquele que for apanhado com o anátema será queimado no fogo, ele e tudo o que lhe pertence, porque transgrediu a aliança do Senhor e cometeu uma infâmia em Israel."},
{v:16,t:"Josué levantou-se de madrugada e fez Israel apresentar-se por tribos, e foi designada a tribo de Judá.",np:1},
{v:17,t:"Fez aproximar-se os clãs de Judá, e foi designado o clã de Zara; fez o clã de Zara apresentar-se por famílias, e foi designado Zabdi."},
{v:18,t:"Fez a família de Zabdi apresentar-se homem por homem, e foi designado Acã, filho de Carmi, filho de Zabdi, filho de Zara, da tribo de Judá."},
{v:19,t:"Josué disse a Acã: Meu filho, dá glória ao Senhor, Deus de Israel, e faze-lhe a confissão; dize-me o que fizeste, não me escondas nada.",n:"Dar glória a Deus era a fórmula com que se pedia a alguém que dissesse a verdade como sob juramento; os fariseus dirão o mesmo ao cego de nascença, no Evangelho de São João."},
{v:20,t:"Acã respondeu a Josué: É verdade, pequei contra o Senhor, Deus de Israel; eis o que fiz:"},
{v:21,t:"Vi entre os despojos um belo manto de Senaar, duzentos siclos de prata e uma barra de ouro de cinquenta siclos de peso; cobicei-os e tomei-os. Estão escondidos na terra, no meio da minha tenda, e a prata está debaixo.",n:"Vi, cobicei, tomei: são os verbos do pecado no jardim — a mulher viu que a árvore era boa, desejável, e tomou do fruto. Senaar é a Babilônia; um manto dali era peça de luxo."},
{v:22,t:"Josué enviou mensageiros, que correram à tenda; e eis que tudo estava escondido na tenda, e a prata debaixo.",np:1},
{v:23,t:"Tiraram tudo do meio da tenda, trouxeram-no a Josué e a todos os filhos de Israel, e depositaram-no diante do Senhor."},
{v:24,t:"Então Josué, e todo o Israel com ele, tomou Acã, filho de Zara, a prata, o manto, a barra de ouro, os seus filhos e as suas filhas, os seus bois, os seus jumentos, as suas ovelhas, a sua tenda e tudo o que lhe pertencia, e levaram-nos ao vale de Acor."},
{v:25,t:"Josué disse: Por que nos trouxeste a desgraça? O Senhor te trará a desgraça neste dia. E todo o Israel o apedrejou; queimaram-nos no fogo e cobriram-nos de pedras.",n:"Nota do tradutor: o hebraico não diz com clareza quem foi queimado e apedrejado com Acã; a Nova Vulgata entende que foram os seus bens. Se o relato inclui a família, pertence à lógica antiga da responsabilidade coletiva, que a própria Escritura corrigiu: o Deuteronômio e Ezequiel ensinam que os filhos não morrem pelos pecados dos pais. Acor quer dizer desgraça, e o nome ecoa a pergunta de Josué; o profeta Oseias dirá que o Senhor fará do vale de Acor uma porta de esperança."},
{v:26,t:"E levantaram sobre ele um grande montão de pedras, que existe até o dia de hoje. E o Senhor aplacou o ardor da sua ira. Por isso aquele lugar se chama vale de Acor até o dia de hoje."}
];

window.TEXTOS_SEED["josue"][8] = [
{s:"A tomada de Hai"},
{v:1,t:"O Senhor disse a Josué: Não temas nem te atemorizes. Toma contigo todos os homens de guerra, levanta-te e sobe contra Hai. Vê, entreguei nas tuas mãos o rei de Hai, o seu povo, a sua cidade e a sua terra."},
{v:2,t:"Farás a Hai e ao seu rei como fizeste a Jericó e ao seu rei; mas podereis tomar para vós os seus despojos e o seu gado. Arma uma emboscada contra a cidade, por detrás dela.",n:"Desta vez os despojos são permitidos: o extermínio total de Jericó, primícias da terra, não é a regra para todas as cidades."},
{v:3,t:"Josué levantou-se com todos os homens de guerra para subir contra Hai. Escolheu trinta mil homens valentes e enviou-os de noite,",np:1,n:"Os números dos livros históricos são muitas vezes difíceis: aqui trinta mil em emboscada, e no versículo 12 cinco mil. A palavra hebraica traduzida por mil, elef, designava também um contingente ou um clã, o que talvez explique cifras tão altas."},
{v:4,t:"dando-lhes esta ordem: Atenção! Ficareis de emboscada contra a cidade, por detrás dela; não vos afasteis muito da cidade, e estai todos prontos."},
{v:5,t:"Eu e todo o povo que está comigo nos aproximaremos da cidade; e, quando eles saírem ao nosso encontro, como da primeira vez, fugiremos diante deles."},
{v:6,t:"Eles sairão atrás de nós, até que os tenhamos atraído para longe da cidade, porque dirão: Fogem diante de nós, como da primeira vez. E nós fugiremos diante deles."},
{v:7,t:"Então saireis da emboscada e tomareis posse da cidade; o Senhor vosso Deus a entregará nas vossas mãos."},
{v:8,t:"Quando tiverdes tomado a cidade, ateai-lhe fogo; agireis segundo a palavra do Senhor. Eis a ordem que vos dou."},
{v:9,t:"Josué despediu-os, e eles foram para o lugar da emboscada e ficaram entre Betel e Hai, a oeste de Hai. Josué passou aquela noite no meio do povo."},
{v:10,t:"Josué levantou-se de madrugada, passou o povo em revista e subiu, com os anciãos de Israel, à frente do povo, contra Hai.",np:1},
{v:11,t:"Todos os homens de guerra que estavam com ele subiram, aproximaram-se, chegaram defronte da cidade e acamparam ao norte de Hai; o vale ficava entre eles e Hai."},
{v:12,t:"Tomou cerca de cinco mil homens e os pôs de emboscada entre Betel e Hai, a oeste da cidade."},
{v:13,t:"Assim dispuseram o povo: todo o acampamento ao norte da cidade e a emboscada a oeste da cidade. Josué foi naquela noite para o meio do vale."},
{v:14,t:"Quando o rei de Hai viu isso, apressou-se, levantou-se cedo, e os homens da cidade saíram ao encontro de Israel para o combate, ele e todo o seu povo, no lugar marcado, diante da Arabá; mas não sabia que havia uma emboscada contra ele, por detrás da cidade.",np:1},
{v:15,t:"Josué e todo o Israel fingiram-se derrotados diante deles e fugiram pelo caminho do deserto."},
{v:16,t:"Todo o povo que estava na cidade foi convocado para persegui-los; perseguiram Josué e foram atraídos para longe da cidade."},
{v:17,t:"Não ficou em Hai um só homem que não saísse atrás de Israel; deixaram a cidade aberta e perseguiram Israel."},
{v:18,t:"O Senhor disse então a Josué: Estende contra Hai o dardo que tens na mão, porque eu a entregarei nas tuas mãos.",n:"Dardo, kidon: talvez um alfanje curto. O gesto de Josué, com a mão estendida até o fim da batalha, lembra o de Moisés com os braços levantados contra Amalec."},
{v:19,t:"Quando ele estendeu o dardo contra a cidade, os da emboscada levantaram-se depressa do seu lugar, correram, entraram na cidade, tomaram-na e logo lhe atearam fogo."},
{v:20,t:"Os homens de Hai, voltando-se, viram a fumaça da cidade subir ao céu, e não tiveram para onde fugir, nem para um lado nem para o outro; e o povo que fugia para o deserto voltou-se contra os perseguidores."},
{v:21,t:"Josué e todo o Israel, vendo que a emboscada tinha tomado a cidade e que a fumaça da cidade subia, voltaram-se e derrotaram os homens de Hai."},
{v:22,t:"Os outros saíram da cidade ao encontro deles, e assim os homens de Hai ficaram no meio de Israel, uns de um lado e outros do outro; e foram derrotados, sem que ficasse deles sobrevivente nem fugitivo."},
{v:23,t:"Quanto ao rei de Hai, apanharam-no vivo e o levaram a Josué."},
{v:24,t:"Quando Israel acabou de matar todos os habitantes de Hai no campo e no deserto, para onde os tinham perseguido, e todos caíram ao fio da espada até o último, todo o Israel voltou a Hai e passou-a ao fio da espada.",np:1},
{v:25,t:"O total dos que caíram naquele dia, homens e mulheres, foi de doze mil, toda a gente de Hai."},
{v:26,t:"Josué não retirou a mão que estendera com o dardo, enquanto não foram votados ao extermínio todos os habitantes de Hai."},
{v:27,t:"Só o gado e os despojos daquela cidade os filhos de Israel tomaram para si, segundo a palavra que o Senhor ordenara a Josué."},
{v:28,t:"Josué incendiou Hai e fez dela para sempre um montão de ruínas, uma desolação até o dia de hoje.",n:"Um montão de ruínas: em hebraico tel, a colina formada pelas ruínas das cidades antigas. E Hai quer dizer ruína."},
{v:29,t:"Quanto ao rei de Hai, suspendeu-o numa árvore até a tarde; ao pôr do sol, Josué mandou que descessem o cadáver da árvore; lançaram-no à entrada da porta da cidade e levantaram sobre ele um grande montão de pedras, que existe até o dia de hoje.",n:"Descer o cadáver ao pôr do sol era mandamento do Deuteronômio: o corpo de um executado não devia ficar suspenso durante a noite. É a regra lembrada no Evangelho de São João, na tarde da crucifixão."},
{s:"O altar do monte Ebal"},
{v:30,t:"Então Josué construiu um altar ao Senhor, Deus de Israel, no monte Ebal,",np:1,n:"O Deuteronômio mandara esta cerimônia de renovação da aliança entre os montes Ebal e Garizim, junto de Siquém, no coração da terra. A versão grega põe o episódio mais adiante, depois do capítulo 9, versículo 2; a Nova Vulgata segue a ordem do hebraico."},
{v:31,t:"como Moisés, servo do Senhor, tinha ordenado aos filhos de Israel, segundo o que está escrito no livro da lei de Moisés: um altar de pedras brutas, sobre as quais ninguém tinha passado o ferro. Ofereceram sobre ele holocaustos ao Senhor e imolaram sacrifícios pacíficos."},
{v:32,t:"Ali, sobre as pedras, Josué escreveu uma cópia da lei que Moisés tinha escrito diante dos filhos de Israel."},
{v:33,t:"Todo o Israel, com os seus anciãos, os seus oficiais e os seus juízes, estava de pé de um lado e do outro da arca, diante dos sacerdotes levitas que levavam a arca da aliança do Senhor, tanto os estrangeiros como os naturais; metade deles do lado do monte Garizim e metade do lado do monte Ebal, como Moisés, servo do Senhor, tinha ordenado antes, para abençoar o povo de Israel."},
{v:34,t:"Depois Josué leu todas as palavras da lei, a bênção e a maldição, conforme tudo o que está escrito no livro da lei."},
{v:35,t:"Não houve palavra de tudo o que Moisés ordenara que Josué não lesse diante de toda a assembleia de Israel, com as mulheres, as crianças e os estrangeiros que viviam no meio deles.",n:"Mulheres, crianças, estrangeiros: toda a comunidade ouve a Lei, e não só os homens adultos. A aliança é de todos."}
];

window.TEXTOS_SEED["josue"][9] = [
{s:"A astúcia dos gabaonitas"},
{v:1,t:"Quando souberam disso todos os reis que estavam do outro lado do Jordão, na montanha, na Sefelá e em todo o litoral do mar Grande até o Líbano — os heteus, os amorreus, os cananeus, os ferezeus, os heveus e os jebuseus —,"},
{v:2,t:"reuniram-se todos juntos, de comum acordo, para combater contra Josué e contra Israel."},
{v:3,t:"Os habitantes de Gabaon, porém, quando souberam o que Josué tinha feito a Jericó e a Hai,",np:1,n:"Gabaon, a noroeste de Jerusalém, era uma cidade importante, como dirá o capítulo seguinte. Os gabaonitas eram heveus."},
{v:4,t:"agiram também eles com astúcia: puseram-se a caminho disfarçados, levando sacos velhos sobre os jumentos e odres de vinho velhos, rasgados e remendados,"},
{v:5,t:"sandálias velhas e remendadas nos pés e roupas velhas sobre o corpo; e todo o pão das suas provisões estava seco e esmigalhado."},
{v:6,t:"Foram ter com Josué, ao acampamento de Guilgal, e disseram a ele e aos homens de Israel: Viemos de uma terra distante; fazei agora aliança conosco. Os homens de Israel responderam aos heveus:"},
{v:7,t:"Talvez habiteis no meio de nós; como poderíamos então fazer aliança convosco?",n:"A Lei proibia fazer aliança com os povos da terra; não, porém, com os de longe."},
{v:8,t:"Eles disseram a Josué: Somos teus servos. Josué perguntou-lhes: Quem sois e de onde vindes?"},
{v:9,t:"Responderam-lhe: Os teus servos vieram de uma terra muito distante, por causa do nome do Senhor teu Deus; pois ouvimos falar da sua fama, de tudo o que fez no Egito,"},
{v:10,t:"e de tudo o que fez aos dois reis dos amorreus do outro lado do Jordão, a Seon, rei de Hesbon, e a Og, rei de Basã, que estava em Astarot.",n:"Os gabaonitas falam do Egito e da outra margem do Jordão, e não de Jericó e de Hai: gente de longe só poderia saber das notícias antigas. A astúcia está também no que calam."},
{v:11,t:"Os nossos anciãos e todos os habitantes da nossa terra disseram-nos: Tomai convosco provisões para a viagem, ide ao encontro deles e dizei-lhes: Somos vossos servos; fazei, pois, aliança conosco."},
{v:12,t:"Eis o nosso pão: estava quente quando o tomamos das nossas casas como provisão, no dia em que saímos para vir ter convosco; e agora está seco e esmigalhado."},
{v:13,t:"Estes odres de vinho, que enchemos novos, estão rasgados; e as nossas roupas e sandálias gastaram-se com a viagem, que foi longuíssima."},
{v:14,t:"Os homens de Israel tomaram das suas provisões, mas não consultaram o oráculo do Senhor.",np:1,n:"Tomaram das provisões: provaram o pão, para verificar a viagem, ou comeram com eles, selando a aliança. O erro está na segunda metade da frase: não consultaram o Senhor."},
{v:15,t:"Josué fez paz com eles e concluiu com eles uma aliança, garantindo-lhes a vida; e os chefes da comunidade lhes fizeram juramento."},
{v:16,t:"Três dias depois de terem feito aliança com eles, souberam que eram vizinhos e que habitavam no meio deles.",np:1},
{v:17,t:"Os filhos de Israel partiram e, no terceiro dia, chegaram às cidades deles, que eram Gabaon, Cafira, Berot e Cariat-Iarim."},
{v:18,t:"Os filhos de Israel não os atacaram, porque os chefes da comunidade lhes tinham jurado pelo Senhor, Deus de Israel. Mas toda a comunidade murmurou contra os chefes."},
{v:19,t:"Todos os chefes disseram a toda a comunidade: Nós lhes juramos pelo Senhor, Deus de Israel; por isso não podemos tocar neles.",n:"O juramento feito em nome do Senhor vale mesmo quando obtido por engano. Séculos depois, o Segundo Livro de Samuel contará a fome que caiu sobre Israel porque Saul o violou."},
{v:20,t:"Eis o que faremos com eles: vamos deixá-los viver, para que não caia sobre nós a ira por causa do juramento que lhes fizemos."},
{v:21,t:"Que vivam, disseram os chefes, mas sejam rachadores de lenha e carregadores de água para toda a comunidade. E assim foi, como os chefes lhes tinham dito."},
{v:22,t:"Josué chamou os gabaonitas e disse-lhes: Por que nos enganastes, dizendo: Moramos muito longe de vós, quando habitais no meio de nós?",np:1},
{v:23,t:"Pois agora sois malditos: nunca deixará de haver entre vós servos, rachadores de lenha e carregadores de água para a casa do meu Deus.",n:"A servidão liga os gabaonitas para sempre ao santuário; terão depois lugar no culto de Israel."},
{v:24,t:"Eles responderam a Josué: É que foi contado aos teus servos que o Senhor teu Deus ordenara a Moisés, seu servo, que vos desse toda esta terra e exterminasse diante de vós todos os seus habitantes; tivemos muito medo por nossas vidas, por causa de vós, e fizemos isto."},
{v:25,t:"E agora estamos nas tuas mãos: faze conosco o que te parecer bom e justo."},
{v:26,t:"Assim fez Josué com eles: livrou-os das mãos dos filhos de Israel, e não os mataram."},
{v:27,t:"Naquele dia, Josué fez deles rachadores de lenha e carregadores de água para a comunidade e para o altar do Senhor, até o dia de hoje, no lugar que o Senhor escolhesse."}
];

window.TEXTOS_SEED["josue"][10] = [
{s:"A batalha de Gabaon"},
{v:1,t:"Quando Adonisedec, rei de Jerusalém, soube que Josué tomara Hai e a votara ao extermínio — fazendo a Hai e ao seu rei o que fizera a Jericó e ao seu rei —, e que os habitantes de Gabaon tinham feito paz com Israel e estavam no meio deles,",n:"Adonisedec quer dizer o meu senhor é justiça, nome parecido com o de Melquisedec, rei de Salém no tempo de Abraão."},
{v:2,t:"tiveram grande medo, porque Gabaon era uma cidade grande, como uma das cidades reais, maior do que Hai, e todos os seus homens eram valentes."},
{v:3,t:"Então Adonisedec, rei de Jerusalém, mandou dizer a Hoam, rei de Hebron, a Faram, rei de Jarmut, a Jáfia, rei de Laquis, e a Dabir, rei de Eglon:"},
{v:4,t:"Subi até mim e ajudai-me a atacar Gabaon, porque fez paz com Josué e com os filhos de Israel."},
{v:5,t:"Reuniram-se, pois, e subiram os cinco reis dos amorreus: o rei de Jerusalém, o rei de Hebron, o rei de Jarmut, o rei de Laquis e o rei de Eglon, eles e todos os seus exércitos; acamparam diante de Gabaon e atacaram-na."},
{v:6,t:"Os homens de Gabaon mandaram dizer a Josué, ao acampamento de Guilgal: Não retires a tua mão dos teus servos! Sobe depressa até nós, salva-nos e socorre-nos, porque se aliaram contra nós todos os reis dos amorreus que habitam a montanha.",np:1},
{v:7,t:"Josué subiu de Guilgal, ele e todos os homens de guerra com ele, todos os guerreiros valentes."},
{v:8,t:"O Senhor disse a Josué: Não os temas, porque os entreguei nas tuas mãos; nenhum deles te poderá resistir."},
{v:9,t:"Josué caiu sobre eles de surpresa, depois de subir de Guilgal toda a noite.",np:1,n:"De Guilgal a Gabaon são uns trinta quilômetros de subida, feitos de noite."},
{v:10,t:"O Senhor lançou-os em pânico diante de Israel, que lhes infligiu uma grande derrota em Gabaon; perseguiu-os pelo caminho da subida de Bet-Horon e bateu-os até Azeca e até Maceda."},
{v:11,t:"Enquanto fugiam diante de Israel, na descida de Bet-Horon, o Senhor lançou do céu sobre eles grandes pedras, até Azeca, e morreram; foram mais os que morreram pelas pedras de granizo do que os que os filhos de Israel mataram à espada."},
{v:12,l:["Então Josué falou ao Senhor, no dia em que o Senhor entregou os amorreus aos filhos de Israel, e disse à vista de Israel:","Sol, detém-te sobre Gabaon,","e tu, lua, sobre o vale de Aialon!"],np:1,n:"Nota do tradutor: é um fragmento de um antigo poema de guerra, tirado do livro do Justo, coleção de cânticos hoje perdida, citada também no Segundo Livro de Samuel. A linguagem é a da poesia: o grito de Josué pede que o dia dure até a vitória. A Igreja não lê aqui uma lição de astronomia; o caso de Galileu, contra quem se invocou este versículo, ficou como lembrança de que a Escritura ensina, segundo a frase do cardeal Barônio que o próprio Galileu recolheu, como se vai para o céu, e não como vai o céu."},
{v:13,l:["E o sol se deteve, e a lua parou,","até que o povo se vingou dos seus inimigos.","Não está isto escrito no livro do Justo? O sol parou no meio do céu e não se apressou a pôr-se durante quase um dia inteiro."]},
{v:14,t:"Nem antes nem depois houve dia como aquele, em que o Senhor atendeu à voz de um homem; porque o Senhor combatia por Israel."},
{v:15,t:"E Josué, com todo o Israel, voltou ao acampamento de Guilgal.",n:"O versículo repete-se no fim do capítulo, no versículo 43, e parece fora do lugar aqui; a versão grega não o traz."},
{s:"Os cinco reis na caverna de Maceda"},
{v:16,t:"Os cinco reis tinham fugido e se escondido na caverna de Maceda.",np:1},
{v:17,t:"Deram a notícia a Josué: Os cinco reis foram encontrados, escondidos na caverna de Maceda."},
{v:18,t:"Josué disse: Rolai grandes pedras para a entrada da caverna e ponde junto dela homens que os guardem."},
{v:19,t:"Mas vós não pareis: persegui os vossos inimigos e atacai-lhes a retaguarda; não os deixeis entrar nas suas cidades, porque o Senhor vosso Deus os entregou nas vossas mãos."},
{v:20,t:"Quando Josué e os filhos de Israel acabaram de infligir-lhes uma derrota muito grande, até exterminá-los, e os que escaparam se refugiaram nas cidades fortificadas,"},
{v:21,t:"todo o povo voltou em paz para junto de Josué, ao acampamento de Maceda; e ninguém ousou mover a língua contra os filhos de Israel."},
{v:22,t:"Então Josué disse: Abri a entrada da caverna e trazei-me esses cinco reis.",np:1},
{v:23,t:"Assim fizeram, e trouxeram-lhe da caverna aqueles cinco reis: o rei de Jerusalém, o rei de Hebron, o rei de Jarmut, o rei de Laquis e o rei de Eglon."},
{v:24,t:"Quando os trouxeram a Josué, ele chamou todos os homens de Israel e disse aos chefes dos guerreiros que o tinham acompanhado: Aproximai-vos e ponde os pés sobre o pescoço destes reis. Eles se aproximaram e puseram os pés sobre o pescoço deles.",n:"Pôr o pé sobre o pescoço do vencido era o gesto da vitória nos relevos do antigo Oriente. O Salmo 110 usa a mesma imagem: até que eu ponha os teus inimigos por escabelo dos teus pés."},
{v:25,t:"Josué disse-lhes: Não temais nem vos atemorizeis; sede fortes e corajosos, porque assim fará o Senhor a todos os inimigos contra os quais combateis."},
{v:26,t:"Depois disso, Josué feriu-os, matou-os e suspendeu-os em cinco árvores; e ficaram suspensos nas árvores até a tarde."},
{v:27,t:"Ao pôr do sol, Josué mandou que os descessem das árvores; lançaram-nos na caverna em que se tinham escondido e puseram grandes pedras à entrada da caverna, que ali estão até o dia de hoje."},
{s:"A conquista do sul"},
{v:28,t:"Naquele mesmo dia, Josué tomou Maceda e passou-a ao fio da espada, com o seu rei; votou-os ao extermínio, com todos os seus habitantes, sem deixar sobrevivente; e fez ao rei de Maceda como fizera ao rei de Jericó.",np:1,n:"Os versículos 28 a 43 repetem, cidade após cidade, a mesma fórmula, à maneira das crônicas reais do antigo Oriente. Sobre o sentido destas fórmulas de extermínio, veja-se a nota ao capítulo 6, versículo 17. O livro dos Juízes mostrará várias destas cidades ainda nas mãos dos cananeus."},
{v:29,t:"Depois Josué passou de Maceda a Lebna, com todo o Israel, e atacou Lebna."},
{v:30,t:"O Senhor entregou-a também, com o seu rei, nas mãos de Israel, que a passou ao fio da espada, com todos os seus habitantes, sem deixar sobrevivente; e fez ao seu rei como fizera ao rei de Jericó."},
{v:31,t:"De Lebna, Josué passou a Laquis, com todo o Israel; cercou-a e atacou-a."},
{v:32,t:"O Senhor entregou Laquis nas mãos de Israel, que a tomou no segundo dia e a passou ao fio da espada, com todos os seus habitantes, como fizera a Lebna."},
{v:33,t:"Então Horam, rei de Gazer, subiu em socorro de Laquis; mas Josué derrotou-o, a ele e ao seu povo, sem lhe deixar sobrevivente."},
{v:34,t:"De Laquis, Josué passou a Eglon, com todo o Israel; cercaram-na"},
{v:35,t:"e atacaram-na, e tomaram-na naquele mesmo dia; passaram-na ao fio da espada e votaram ao extermínio, naquele dia, todos os seus habitantes, como tinham feito a Laquis."},
{v:36,t:"De Eglon, Josué subiu a Hebron, com todo o Israel, e atacaram-na."},
{v:37,t:"Tomaram-na e passaram-na ao fio da espada, com o seu rei, todas as suas cidades e todos os seus habitantes, sem deixar sobrevivente; como fizera a Eglon, votou-a ao extermínio, com todos os seus habitantes.",n:"Hebron será dada a Caleb no capítulo 14 e conquistada por ele no 15: as tradições da conquista cruzam-se."},
{v:38,t:"Depois Josué voltou-se, com todo o Israel, contra Dabir e atacou-a;"},
{v:39,t:"tomou-a, com o seu rei e todas as suas cidades; passaram-nas ao fio da espada e votaram ao extermínio todos os seus habitantes, sem deixar sobrevivente. Como fizera a Hebron, e como fizera a Lebna e ao seu rei, assim fez a Dabir e ao seu rei."},
{v:40,t:"Assim Josué conquistou toda a terra: a montanha, o Negueb, a Sefelá e as encostas, com todos os seus reis, sem deixar sobrevivente; votou ao extermínio tudo o que respirava, como o Senhor, Deus de Israel, tinha ordenado.",np:1},
{v:41,t:"Josué conquistou-os desde Cades-Barne até Gaza, e toda a terra de Gósen até Gabaon.",n:"Gósen é aqui uma região no sul da Judeia, e não a do Egito, que tinha o mesmo nome."},
{v:42,t:"Todos esses reis e as suas terras, Josué tomou-os de uma só vez, porque o Senhor, Deus de Israel, combatia por Israel."},
{v:43,t:"Depois Josué voltou, com todo o Israel, ao acampamento de Guilgal."}
];
