// =====================================================================
// Judite — tradução do grego, cotejado com a Nova Vulgata (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["judite"][1] = [
{s:"Nabucodonosor contra Arfaxad"},
{v:1,t:"No décimo segundo ano do reinado de Nabucodonosor, que reinou sobre os assírios em Nínive, a grande cidade, no tempo de Arfaxad, que reinou sobre os medos em Ecbátana",n:"O livro de Judite é uma narrativa edificante, escrita provavelmente no século II antes de Cristo, que mistura de propósito épocas e lugares: Nabucodonosor foi rei da Babilônia, e não da Assíria, e Nínive já estava destruída quando ele reinava. O autor não quer fazer história, mas mostrar como Deus salva o seu povo pela mão de uma mulher. O texto chegou até nós em grego."},
{v:2,t:"e que construiu em volta de Ecbátana muralhas de pedras talhadas, de três côvados de largura e seis de comprimento; deu à muralha setenta côvados de altura e cinquenta de largura;"},
{v:3,t:"levantou junto às suas portas torres de cem côvados, sobre alicerces de sessenta côvados de largura;"},
{v:4,t:"e fez as suas portas elevando-se a setenta côvados de altura, com quarenta de largura, para a saída dos seus poderosos exércitos e para a formação da sua infantaria —"},
{v:5,t:"naqueles dias, o rei Nabucodonosor fez guerra contra o rei Arfaxad na grande planície, que é a planície do território de Ragau.",np:1},
{v:6,t:"Juntaram-se para a batalha todos os habitantes da montanha, todos os habitantes da região do Eufrates, do Tigre e do Hidaspes, e da planície de Arioc, rei dos elimeus; e muitos povos se reuniram para a guerra dos filhos dos caldeus."},
{v:7,t:"Então Nabucodonosor, rei dos assírios, mandou mensageiros a todos os habitantes da Pérsia e a todos os habitantes do Ocidente: aos habitantes da Cilícia, de Damasco, do Líbano e do Antilíbano, e a todos os habitantes da costa;"},
{v:8,t:"aos povos do Carmelo e de Galaad, à alta Galileia e à grande planície de Esdrelon;"},
{v:9,t:"a todos os que estavam em Samaria e nas suas cidades, e além do Jordão até Jerusalém, Batana, Quelus, Cades e a torrente do Egito, Táfnis, Ramessés e toda a terra de Gessen,"},
{v:10,t:"até além de Tânis e de Mênfis, e a todos os habitantes do Egito, até as fronteiras da Etiópia."},
{v:11,t:"Mas todos os habitantes de toda a terra desprezaram a palavra de Nabucodonosor, rei dos assírios, e não se juntaram a ele para a guerra, porque não tinham medo dele, mas o tinham por um homem qualquer; e despediram os seus embaixadores de mãos vazias e com desprezo.",np:1},
{v:12,t:"Então o rei Nabucodonosor irou-se muito contra toda aquela terra, e jurou pelo seu trono e pelo seu reino que se vingaria de todo o território da Cilícia, de Damasco e da Síria, e que exterminaria com a sua espada todos os habitantes de Moab, os filhos de Amon, toda a Judeia e todos os que estavam no Egito, até as fronteiras dos dois mares."},
{v:13,t:"No décimo sétimo ano, preparou-se com o seu exército contra o rei Arfaxad, venceu-o na batalha e desbaratou todo o exército de Arfaxad, toda a sua cavalaria e todos os seus carros;",np:1},
{v:14,t:"e apoderou-se das suas cidades. Chegou até Ecbátana, tomou as suas torres, saqueou as suas praças e fez da sua beleza uma vergonha."},
{v:15,t:"Apanhou Arfaxad nos montes de Ragau, traspassou-o com as suas lanças e o exterminou para sempre."},
{v:16,t:"Depois voltou para Nínive, ele e todo o seu exército de muitos povos, uma multidão imensa de guerreiros; e ali descansou e banqueteou-se, ele e o seu exército, durante cento e vinte dias."}
];

window.TEXTOS_SEED["judite"][2] = [
{s:"A campanha de Holofernes"},
{v:1,t:"No décimo oitavo ano, no vigésimo segundo dia do primeiro mês, saiu a ordem de Nabucodonosor, rei dos assírios, de vingar-se de toda a terra, como tinha dito."},
{v:2,t:"Convocou todos os seus servos e todos os seus nobres, expôs-lhes o seu plano secreto e decretou com a sua própria boca toda a desgraça daquela terra;"},
{v:3,t:"e eles decidiram exterminar todos os que não tinham obedecido à palavra da sua boca."},
{v:4,t:"Terminado o seu conselho, Nabucodonosor, rei dos assírios, chamou Holofernes, general-chefe do seu exército, o segundo depois dele,",np:1},
{v:5,t:"e lhe disse: Assim diz o grande rei, senhor de toda a terra: Eis que partirás da minha presença e levarás contigo homens confiantes na sua força: cento e vinte mil soldados de infantaria e uma multidão de cavalos com doze mil cavaleiros;",n:"Senhor de toda a terra: título que só a Deus pertence. O conflito do livro é entre o rei que se faz deus e o Deus de Israel (3,8; 6,2)."},
{v:6,t:"e sairás contra toda a terra do Ocidente, porque não obedeceram à palavra da minha boca."},
{v:7,t:"Anuncia-lhes que me preparem a terra e a água, porque sairei contra eles na minha ira, cobrirei toda a face da terra com os pés do meu exército e os entregarei ao saque.",n:"A terra e a água: sinal de submissão que os reis persas exigiam dos povos vencidos."},
{v:8,t:"Os seus feridos encherão os seus vales, e toda torrente e todo rio transbordante se encherão dos seus mortos."},
{v:9,t:"E levarei os seus cativos até os confins de toda a terra."},
{v:10,t:"Tu, pois, sai e ocupa para mim todo o seu território; eles se renderão a ti, e tu os guardarás para mim até o dia do seu castigo."},
{v:11,t:"Mas, quanto aos rebeldes, o teu olho não os poupe: entrega-os à morte e ao saque em toda a terra que te está confiada,"},
{v:12,t:"porque, pela minha vida e pelo poder do meu reino, eu disse e farei tudo isto com a minha mão."},
{v:13,t:"E tu não transgredirás uma só palavra do teu senhor, mas cumprirás tudo exatamente, como te ordenei, sem demora."},
{v:14,t:"Holofernes saiu da presença do seu senhor e convocou todos os governadores, os generais e os oficiais do exército da Assíria,",np:1},
{v:15,t:"e recrutou homens escolhidos para a campanha, como o seu senhor lhe tinha ordenado: cento e vinte mil homens e doze mil arqueiros a cavalo."},
{v:16,t:"E os organizou como se organiza um grande exército para a guerra."},
{v:17,t:"Tomou camelos, jumentos e mulas para as bagagens, em grande quantidade, e ovelhas, bois e cabras sem número para o seu sustento,"},
{v:18,t:"e provisões em abundância para cada homem, e muito ouro e prata do palácio do rei."},
{v:19,t:"Partiu com todo o seu exército, à frente do rei Nabucodonosor, para cobrir toda a face da terra do Ocidente com os seus carros, os seus cavaleiros e a sua infantaria escolhida."},
{v:20,t:"Uma multidão de toda espécie, numerosa como os gafanhotos e como a areia da terra, partiu com eles: não se podia contá-los, de tão numerosos."},
{v:21,t:"Partiram de Nínive e, depois de três dias de caminho, chegaram à planície de Bectilet, e acamparam perto de Bectilet, junto ao monte que fica à esquerda da alta Cilícia.",np:1,n:"O itinerário de Holofernes é fantasioso: em três dias não se chegaria de Nínive à Cilícia."},
{v:22,t:"Depois tomou todo o seu exército, a infantaria, a cavalaria e os carros, e partiu dali para a montanha."},
{v:23,t:"Destruiu Fut e Lud, e saquearam todos os filhos de Rassis e os filhos de Ismael, que habitavam na orla do deserto, ao sul dos queleus."},
{v:24,t:"Atravessou o Eufrates, passou pela Mesopotâmia e arrasou todas as cidades fortificadas que havia ao longo da torrente de Abrona, até o mar."},
{v:25,t:"Ocupou o território da Cilícia, massacrou todos os que lhe resistiam e chegou até as fronteiras de Jafet, ao sul, diante da Arábia."},
{v:26,t:"Cercou todos os filhos de Madiã, incendiou as suas tendas e saqueou os seus apriscos."},
{v:27,t:"Desceu à planície de Damasco no tempo da colheita do trigo, incendiou todos os seus campos, exterminou os rebanhos e o gado, saqueou as suas cidades, devastou as suas planícies e passou ao fio da espada todos os seus jovens."},
{v:28,t:"O medo e o terror dele caíram sobre os habitantes da costa, que estavam em Sidônia e em Tiro, e sobre os habitantes de Sur e de Ocina e todos os que moravam em Jâmnia; os habitantes de Azoto, de Ascalon e de Gaza tiveram muito medo dele."}
];

window.TEXTOS_SEED["judite"][3] = [
{s:"A submissão dos povos da costa"},
{v:1,t:"Enviaram-lhe mensageiros com palavras de paz, dizendo:"},
{v:2,t:"Eis que nós, servos do grande rei Nabucodonosor, estamos diante de ti: trata-nos como te parecer bem."},
{v:3,t:"Eis as nossas aldeias, todo o nosso território, todos os campos de trigo, os rebanhos e o gado, e todos os currais dos nossos animais estão à tua disposição: usa-os como te agradar."},
{v:4,t:"Também as nossas cidades e os que nelas habitam são teus servos: vem e trata-os como te parecer bem."},
{v:5,t:"Os homens foram ter com Holofernes e lhe transmitiram estas palavras.",np:1},
{v:6,t:"Ele desceu à costa com o seu exército, pôs guarnições nas cidades fortificadas e tomou delas homens escolhidos como tropas auxiliares."},
{v:7,t:"E eles e toda a região ao redor o receberam com coroas, danças e tamborins."},
{v:8,t:"Mas ele destruiu todos os seus santuários e cortou os seus bosques sagrados, porque lhe tinha sido ordenado exterminar todos os deuses da terra, para que todas as nações adorassem só a Nabucodonosor, e todas as línguas e todas as tribos o invocassem como deus.",n:"A pretensão de ser adorado como deus lembra Antíoco IV Epífanes, que no século II antes de Cristo quis impor aos judeus o culto pagão (1 Macabeus 1,41-50)."},
{v:9,t:"Chegou diante de Esdrelon, perto de Dotaim, que fica em frente da grande serra da Judeia,",np:1},
{v:10,t:"e acamparam entre Gaba e Citópolis; e ficou ali um mês inteiro, para reunir todas as bagagens do seu exército.",n:"Citópolis, a cidade dos citas: a antiga Bet-Sã, no vale do Jordão."}
];

window.TEXTOS_SEED["judite"][4] = [
{s:"Israel se prepara para resistir"},
{v:1,t:"Os filhos de Israel que habitavam na Judeia souberam de tudo o que Holofernes, general-chefe de Nabucodonosor, rei dos assírios, tinha feito às nações, e como tinha saqueado e destruído todos os seus santuários."},
{v:2,t:"Tiveram um medo enorme dele e ficaram aterrorizados por Jerusalém e pelo templo do Senhor seu Deus,"},
{v:3,t:"porque tinham voltado havia pouco do cativeiro, e havia pouco todo o povo da Judeia se tinha reunido, e os objetos sagrados, o altar e o templo tinham sido purificados da profanação.",n:"Nova mistura de épocas: a volta do exílio é posterior a Nabucodonosor. A purificação do templo lembra a de Judas Macabeu (1 Macabeus 4,36-59)."},
{v:4,t:"Mandaram avisar todo o território de Samaria e as aldeias, Bet-Horon, Abel-Maim, Jericó, Coba, Esora e o vale de Salem."},
{v:5,t:"Ocuparam todos os cumes dos montes altos, fortificaram as aldeias que neles havia e armazenaram provisões para a guerra, porque os seus campos tinham sido colhidos havia pouco."},
{v:6,t:"O sumo sacerdote Joaquim, que estava naqueles dias em Jerusalém, escreveu aos habitantes de Betúlia e de Betomestaim, que fica diante de Esdrelon, em frente da planície perto de Dotaim,",np:1,n:"Betúlia é uma cidade desconhecida; o nome lembra betulah, virgem, e Betel, casa de Deus: é o símbolo do povo sitiado."},
{v:7,t:"mandando-lhes ocupar as subidas da montanha, porque por elas se entrava na Judeia, e era fácil deter os que subissem, porque a passagem era estreita, para dois homens no máximo."},
{v:8,t:"Os filhos de Israel fizeram como lhes tinham ordenado o sumo sacerdote Joaquim e o conselho dos anciãos de todo o povo de Israel, que se reunia em Jerusalém."},
{v:9,t:"Todos os homens de Israel clamaram a Deus com grande fervor e se humilharam com um grande jejum;",np:1},
{v:10,t:"eles, as suas mulheres, as suas crianças, os seus animais, e todo estrangeiro, assalariado e escravo comprado com dinheiro, puseram sacos à cintura."},
{v:11,t:"Todos os homens de Israel, as mulheres e as crianças que habitavam em Jerusalém prostraram-se diante do templo, cobriram a cabeça de cinza e estenderam os seus sacos diante do templo do Senhor."},
{v:12,t:"Cobriram também o altar com um saco e clamaram a uma só voz, com insistência, ao Deus de Israel, que não entregasse ao saque as suas crianças, as suas mulheres ao cativeiro, as cidades da sua herança à destruição, e o santuário à profanação e à zombaria, para alegria das nações."},
{v:13,t:"O Senhor ouviu a sua voz e viu a sua aflição. O povo jejuou muitos dias em toda a Judeia e em Jerusalém, prostrado diante do santuário do Senhor todo-poderoso."},
{v:14,t:"O sumo sacerdote Joaquim e todos os sacerdotes que estavam diante do Senhor e o serviam, com sacos à cintura, ofereciam o holocausto perpétuo, os votos e as ofertas voluntárias do povo."},
{v:15,t:"Tinham cinza sobre os turbantes, e clamavam ao Senhor com todas as forças, para que visitasse favoravelmente toda a casa de Israel."}
];

window.TEXTOS_SEED["judite"][5] = [
{s:"O discurso de Aquior"},
{v:1,t:"Anunciaram a Holofernes, general-chefe do exército da Assíria, que os filhos de Israel se tinham preparado para a guerra, tinham fechado as passagens da montanha, fortificado todos os cumes dos montes altos e posto obstáculos nas planícies."},
{v:2,t:"Ele se irritou muito e convocou todos os chefes de Moab, os generais de Amon e todos os governadores da costa,"},
{v:3,t:"e lhes disse: Dizei-me, filhos de Canaã: que povo é este que habita na montanha? Que cidades são essas em que habita? Qual é o tamanho do seu exército? Em que está o seu poder e a sua força? Que rei está à frente deles, como chefe do seu exército?"},
{v:4,t:"E por que desdenharam vir ao meu encontro, ao contrário de todos os habitantes do Ocidente?"},
{v:5,t:"Aquior, chefe dos filhos de Amon, respondeu-lhe: Que o meu senhor ouça a palavra da boca do seu servo, e eu te direi a verdade sobre este povo que habita estas montanhas perto de ti; não sairá mentira da boca do teu servo.",np:1,n:"Aquior, um estrangeiro, resume a história de Israel e a sua lei fundamental: enquanto é fiel ao seu Deus, ninguém o vence. Aquior acabará por se converter (14,10)."},
{v:6,t:"Este povo descende dos caldeus."},
{v:7,t:"Habitaram primeiro na Mesopotâmia, porque não quiseram seguir os deuses dos seus pais, que eram venerados na terra dos caldeus."},
{v:8,t:"Afastaram-se do caminho dos seus pais e adoraram o Deus do céu, o Deus que tinham conhecido; por isso os expulsaram da presença dos seus deuses, e eles fugiram para a Mesopotâmia e ali habitaram muito tempo.",n:"Resumo da vocação de Abraão, que deixou Ur dos caldeus (Gênesis 11,31-12,5)."},
{v:9,t:"O seu Deus mandou-lhes que saíssem do lugar onde moravam como estrangeiros e fossem para a terra de Canaã. Estabeleceram-se ali e enriqueceram-se de ouro, de prata e de muito gado."},
{v:10,t:"Depois desceram ao Egito, porque a fome tinha coberto a face da terra de Canaã, e ficaram lá enquanto houve com que se alimentar; e ali se tornaram uma grande multidão, e a sua raça era incontável."},
{v:11,t:"Mas os egípcios se levantaram contra eles, oprimiram-nos com o trabalho da argila e dos tijolos, humilharam-nos e fizeram deles escravos."},
{v:12,t:"Eles clamaram ao seu Deus, e ele feriu toda a terra do Egito com pragas incuráveis; e os egípcios os expulsaram da sua presença."},
{v:13,t:"Deus secou diante deles o mar Vermelho"},
{v:14,t:"e os conduziu pelo caminho do Sinai e de Cades-Barne. Expulsaram todos os habitantes do deserto"},
{v:15,t:"e habitaram na terra dos amorreus, e com a sua força exterminaram todos os de Hesbon. Depois atravessaram o Jordão e possuíram toda a montanha,"},
{v:16,t:"e expulsaram diante deles os cananeus, os ferezeus, os jebuseus, os siquemitas e todos os gergeseus, e habitaram ali muito tempo."},
{v:17,t:"Enquanto não pecaram diante do seu Deus, a prosperidade esteve com eles, porque está com eles um Deus que odeia a iniquidade.",np:1},
{v:18,t:"Mas, quando se afastaram do caminho que ele lhes tinha traçado, foram exterminados em muitas guerras, levados cativos para uma terra estrangeira, o templo do seu Deus foi arrasado, e as suas cidades foram tomadas pelos inimigos."},
{v:19,t:"E agora, voltando para o seu Deus, subiram dos lugares por onde tinham sido dispersos, tomaram posse de Jerusalém, onde está o seu santuário, e estabeleceram-se na montanha, que estava deserta."},
{v:20,t:"Agora, pois, soberano senhor, se há alguma falta neste povo e se pecam contra o seu Deus, veremos que há neles essa causa de ruína, e subiremos e os venceremos;",np:1},
{v:21,t:"mas, se não há iniquidade nesta nação, que o meu senhor passe adiante, para que o seu Senhor e o seu Deus não os proteja, e fiquemos cobertos de vergonha diante de toda a terra."},
{v:22,t:"Quando Aquior acabou de dizer estas palavras, todo o povo que estava em volta da tenda começou a murmurar; e os nobres de Holofernes e todos os habitantes da costa e de Moab diziam que ele devia ser despedaçado:",np:1},
{v:23,t:"Não temeremos os filhos de Israel: é um povo sem força nem poder para uma batalha dura."},
{v:24,t:"Por isso subiremos, e eles serão devorados pelo teu exército, soberano Holofernes!"}
];

window.TEXTOS_SEED["judite"][6] = [
{s:"Aquior entregue aos israelitas"},
{v:1,t:"Quando cessou o tumulto dos homens que estavam em volta do conselho, Holofernes, general-chefe do exército da Assíria, disse a Aquior, diante de todo o povo estrangeiro e de todos os filhos de Moab:"},
{v:2,t:"E quem és tu, Aquior, e vós, mercenários de Efraim, para nos profetizar como fizeste hoje, dizendo que não se deve combater a raça dos filhos de Israel, porque o seu Deus os protegerá? E quem é Deus, senão Nabucodonosor, rei de toda a terra? Ele enviará o seu poder e os exterminará da face da terra, e o seu Deus não os livrará.",n:"Quem é Deus, senão Nabucodonosor? Toda a narrativa responde a esta pergunta."},
{v:3,t:"Nós, os seus servos, os derrotaremos como a um só homem, e eles não resistirão à força dos nossos cavalos."},
{v:4,t:"Nós os esmagaremos com eles; os seus montes se embriagarão do seu sangue, as suas planícies se encherão dos seus mortos; não poderão resistir diante de nós, mas perecerão completamente. Assim diz o rei Nabucodonosor, senhor de toda a terra; porque ele falou, e as palavras da sua boca não falharão."},
{v:5,t:"Quanto a ti, Aquior, mercenário de Amon, que disseste estas palavras no dia da tua iniquidade, não verás mais o meu rosto, a partir de hoje, até que me vingue dessa raça saída do Egito."},
{v:6,t:"Então o ferro do meu exército e a lança dos meus servos traspassarão os teus flancos, e cairás entre os feridos deles, quando eu voltar."},
{v:7,t:"Os meus servos te levarão para a montanha e te deixarão numa das cidades das subidas,"},
{v:8,t:"e não morrerás enquanto não fores exterminado com eles."},
{v:9,t:"E, se esperas no teu coração que eles não serão tomados, não fiques de rosto abatido! Eu disse, e nenhuma das minhas palavras cairá por terra."},
{v:10,t:"Holofernes ordenou aos servos que estavam na sua tenda que prendessem Aquior, o levassem a Betúlia e o entregassem nas mãos dos filhos de Israel.",np:1},
{v:11,t:"Os servos o prenderam, levaram-no para fora do acampamento, para a planície, e da planície subiram para a montanha e chegaram às fontes que estavam abaixo de Betúlia."},
{v:12,t:"Quando os homens da cidade os viram do alto do monte, pegaram nas armas e saíram da cidade para o cume do monte, e todos os fundibulários ocuparam a subida e lhes atiravam pedras."},
{v:13,t:"Eles, abrigando-se ao pé do monte, amarraram Aquior, deixaram-no estendido no sopé do monte e voltaram para o seu senhor."},
{v:14,t:"Os filhos de Israel desceram da cidade, aproximaram-se dele, desamarraram-no, levaram-no para Betúlia e o apresentaram aos chefes da sua cidade,",np:1},
{v:15,t:"que eram naqueles dias Ozias, filho de Micas, da tribo de Simeão, Cabris, filho de Gotoniel, e Carmis, filho de Melquiel."},
{v:16,t:"Convocaram todos os anciãos da cidade, e acorreram à assembleia todos os jovens e também as mulheres e as crianças. Puseram Aquior no meio de todo o povo, e Ozias interrogou-o sobre o que tinha acontecido."},
{v:17,t:"Ele respondeu contando-lhes as palavras do conselho de Holofernes, tudo o que tinha dito no meio dos chefes dos assírios, e tudo o que Holofernes tinha proferido com arrogância contra a casa de Israel."},
{v:18,t:"Então todo o povo se prostrou, adorou a Deus e clamou, dizendo:"},
{v:19,t:"Senhor, Deus do céu, olha para a arrogância deles, tem compaixão da humilhação da nossa raça, e olha hoje para o rosto dos que te são consagrados!"},
{v:20,t:"E consolaram Aquior e o elogiaram muito."},
{v:21,t:"Ozias levou-o da assembleia para a sua casa e deu um banquete aos anciãos; e durante toda aquela noite invocaram o Deus de Israel, pedindo o seu auxílio."}
];

window.TEXTOS_SEED["judite"][7] = [
{s:"O cerco de Betúlia"},
{v:1,t:"No dia seguinte, Holofernes ordenou a todo o seu exército e a todas as tropas que tinham vindo em sua ajuda que marchassem contra Betúlia, ocupassem as subidas da montanha e fizessem guerra contra os filhos de Israel."},
{v:2,t:"Naquele dia, todos os seus guerreiros se puseram em marcha; o seu exército era de cento e setenta mil homens de infantaria e doze mil cavaleiros, sem contar a bagagem e os homens que iam a pé com ela, uma multidão muito grande."},
{v:3,t:"Acamparam no vale, perto de Betúlia, junto à fonte, e estenderam-se em largura para o lado de Dotaim até Abel-Maim, e em comprimento de Betúlia até Ciamon, que fica em frente de Esdrelon."},
{v:4,t:"Quando os filhos de Israel viram a sua multidão, ficaram muito perturbados e disseram uns aos outros: Agora eles vão devorar a face de toda a terra: nem os montes altos, nem os vales, nem as colinas suportarão o seu peso."},
{v:5,t:"Cada um pegou nas suas armas, acenderam fogueiras nas torres das suas muralhas e ficaram de guarda toda aquela noite."},
{v:6,t:"No segundo dia, Holofernes fez sair toda a sua cavalaria diante dos filhos de Israel que estavam em Betúlia,",np:1},
{v:7,t:"inspecionou as subidas da sua cidade, percorreu as fontes de água e ocupou-as; pôs junto delas guarnições de guerreiros e voltou para o seu exército."},
{v:8,t:"Então todos os chefes dos filhos de Esaú, todos os generais do povo de Moab e os governadores da costa vieram ter com ele e disseram:"},
{v:9,t:"Que o nosso soberano ouça uma palavra, para que não haja derrota no teu exército."},
{v:10,t:"Este povo dos filhos de Israel não confia nas suas lanças, mas na altura dos montes onde habita; porque não é fácil subir aos cumes dos seus montes."},
{v:11,t:"Agora, pois, soberano, não combatas contra eles em batalha campal, e não cairá um só homem do teu povo."},
{v:12,t:"Fica no teu acampamento, poupando todos os homens do teu exército, e que os teus servos ocupem a fonte de água que brota ao pé do monte,"},
{v:13,t:"porque é dali que todos os habitantes de Betúlia tiram água. A sede os matará, e entregarão a sua cidade. Nós e o teu povo subiremos aos cumes dos montes vizinhos e acamparemos neles, de guarda, para que não saia da cidade um só homem."},
{v:14,t:"Eles se consumirão de fome e de sede, com as suas mulheres e os seus filhos, e, antes que a espada chegue até eles, cairão estendidos nas ruas da sua cidade."},
{v:15,t:"E tu lhes darás uma dura paga, porque se rebelaram e não vieram em paz ao teu encontro."},
{v:16,t:"As suas palavras agradaram a Holofernes e a todos os seus servos, e ele decidiu fazer como tinham dito.",np:1},
{v:17,t:"Os filhos de Moab moveram o acampamento, e com eles cinco mil assírios; acamparam no vale e ocuparam as águas e as fontes dos filhos de Israel."},
{v:18,t:"Os filhos de Amon e os filhos de Esaú subiram e acamparam na montanha, em frente de Dotaim, e mandaram alguns dos seus para o sul e para o oriente, em frente de Egrebel, que fica perto de Cus, junto à torrente de Mocmur. O resto do exército assírio acampou na planície e cobriu toda a face da terra; as suas tendas e as suas bagagens formavam uma multidão imensa."},
{v:19,t:"Os filhos de Israel clamaram ao Senhor seu Deus, porque perdiam o ânimo, vendo-se cercados por todos os seus inimigos, sem poder escapar do meio deles.",np:1},
{v:20,t:"Todo o exército da Assíria, a infantaria, os carros e a cavalaria, ficou em volta deles durante trinta e quatro dias. Todos os habitantes de Betúlia viram esgotar-se toda a água dos seus reservatórios,"},
{v:21,t:"e as cisternas se esvaziavam; não tinham água para beber à vontade um só dia, porque lhes davam de beber em quantidade medida."},
{v:22,t:"As crianças desfaleciam, e as mulheres e os jovens desmaiavam de sede e caíam nas ruas da cidade e nas passagens das portas, sem forças."},
{v:23,t:"Todo o povo, os jovens, as mulheres e as crianças, reuniu-se junto de Ozias e dos chefes da cidade, e clamaram em alta voz, dizendo diante de todos os anciãos:",np:1},
{v:24,t:"Que Deus seja juiz entre vós e nós, porque nos fizestes um grande mal não fazendo a paz com os assírios."},
{v:25,t:"Agora não há quem nos ajude: Deus nos vendeu nas suas mãos, para cairmos diante deles de sede e de total ruína."},
{v:26,t:"Agora, pois, chamai-os e entregai toda a cidade ao saque do povo de Holofernes e de todo o seu exército."},
{v:27,t:"Porque é melhor para nós ser presa deles: seremos seus escravos e escravas, mas viveremos, e não veremos com os nossos olhos a morte das nossas crianças, nem as nossas mulheres e os nossos filhos a desfalecer."},
{v:28,t:"Tomamos por testemunhas contra vós o céu e a terra, e o nosso Deus e Senhor de nossos pais, que nos castiga segundo os nossos pecados e os pecados de nossos pais, para que não nos trate hoje segundo estas palavras."},
{v:29,t:"Houve então um grande pranto no meio da assembleia, de todos juntos, e clamaram ao Senhor Deus em alta voz."},
{v:30,t:"Ozias lhes disse: Coragem, irmãos! Aguentemos ainda cinco dias, nos quais o Senhor nosso Deus voltará para nós a sua misericórdia; porque ele não nos abandonará até o fim.",np:1},
{v:31,t:"Mas, se estes cinco dias passarem sem que nos venha socorro, farei o que dizeis."},
{v:32,t:"E despediu o povo, cada um para o seu posto; subiram às muralhas e às torres da cidade, e mandaram as mulheres e as crianças para as suas casas. E estavam na maior humilhação.",n:"Cinco dias: Ozias impõe um prazo a Deus. Judite o repreenderá por isso (8,11-17)."}
];
