// =====================================================================
// Juízes — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["juizes"][1] = [
{s:"Judá e Simeão"},
{v:1,t:"Depois da morte de Josué, os filhos de Israel consultaram o Senhor, dizendo: Quem de nós subirá primeiro contra os cananeus, para lutar contra eles?",n:"O livro dos Juízes cobre o tempo entre a morte de Josué e o surgimento da monarquia, uns dois séculos. Os juízes não são magistrados, mas chefes carismáticos que Deus suscita para libertar uma ou outra tribo. O primeiro capítulo corrige a imagem de uma conquista total: registra, cidade por cidade, o que Israel não conseguiu tomar."},
{v:2,t:"O Senhor respondeu: Judá subirá; eis que entreguei a terra nas suas mãos."},
{v:3,t:"Judá disse a Simeão, seu irmão: Sobe comigo ao território que me coube, e lutaremos contra os cananeus; depois também eu irei contigo ao território que te coube. E Simeão foi com ele."},
{v:4,t:"Judá subiu, e o Senhor entregou-lhes nas mãos os cananeus e os ferezeus; e derrotaram em Bezec dez mil homens."},
{v:5,t:"Encontraram Adonibezec em Bezec, lutaram contra ele e derrotaram os cananeus e os ferezeus."},
{v:6,t:"Adonibezec fugiu, mas perseguiram-no, apanharam-no e cortaram-lhe os polegares das mãos e dos pés.",n:"Cortar os polegares inutilizava o guerreiro para a espada e para a corrida."},
{v:7,t:"Adonibezec disse: Setenta reis, com os polegares das mãos e dos pés cortados, apanhavam as migalhas debaixo da minha mesa. Como eu fiz, assim Deus me pagou. Levaram-no a Jerusalém, e ali morreu.",n:"O próprio pagão reconhece na sua sorte a justiça de Deus: é a pena de talião, olho por olho."},
{v:8,t:"Os filhos de Judá atacaram Jerusalém, tomaram-na, passaram-na ao fio da espada e incendiaram a cidade.",n:"O versículo 21 dirá que os jebuseus continuaram em Jerusalém, e só Davi a tomará de fato. Talvez se trate de uma incursão, ou da parte baixa da cidade."},
{v:9,t:"Depois os filhos de Judá desceram para lutar contra os cananeus que habitavam na montanha, no Negueb e na Sefelá."},
{v:10,t:"Judá marchou contra os cananeus que habitavam em Hebron, cujo nome era antes Cariat-Arbe, e derrotou Sesai, Aimã e Tolmai."},
{v:11,t:"Dali marchou contra os habitantes de Dabir, cujo nome era antes Cariat-Séfer, isto é, cidade das Letras.",np:1},
{v:12,t:"E Caleb disse: A quem atacar Cariat-Séfer e a tomar, darei minha filha Acsa por mulher."},
{v:13,t:"Otoniel, filho de Cenez, irmão mais novo de Caleb, tomou-a; e Caleb deu-lhe sua filha Acsa por mulher.",n:"O episódio é o mesmo contado em Josué 15, 15-19."},
{v:14,t:"Quando ela veio para junto dele, incitou-o a pedir um campo a seu pai. Ela desceu do jumento, e Caleb perguntou-lhe: Que desejas?"},
{v:15,t:"Ela respondeu: Dá-me um presente. Já que me deste uma terra seca, dá-me também fontes de água. E Caleb deu-lhe as fontes de cima e as fontes de baixo."},
{v:16,t:"Os filhos de Hobab, o quenita, parente de Moisés, subiram da cidade das Palmeiras com os filhos de Judá ao deserto de Judá, que está ao sul de Arad, e foram habitar com os amalecitas.",np:1,n:"Os quenitas, nômades ferreiros aparentados com Moisés, acompanharam Israel desde o deserto. A cidade das Palmeiras é Jericó. O hebraico diz habitaram com o povo; a Nova Vulgata, com a versão grega, lê com os amalecitas."},
{v:17,t:"Judá partiu com Simeão, seu irmão, e derrotaram os cananeus que habitavam em Sefat; votaram a cidade ao extermínio, e deram-lhe o nome de Horma.",n:"Horma soa como herem, o extermínio: quer dizer consagração ao anátema."},
{v:18,t:"Judá tomou também Gaza e o seu território, Ascalon e o seu território, e Acaron e o seu território.",n:"A versão grega diz que Judá não tomou estas cidades filisteias, o que concorda melhor com o versículo seguinte e com o resto da história; o hebraico e a Nova Vulgata dizem que as tomou."},
{v:19,t:"O Senhor estava com Judá, que se apoderou da montanha; mas não pôde expulsar os habitantes da planície, porque tinham carros de ferro."},
{v:20,t:"Deram Hebron a Caleb, como Moisés dissera; e ele expulsou dali os três filhos de Enac."},
{v:21,t:"Quanto aos jebuseus que habitavam em Jerusalém, os filhos de Benjamim não os expulsaram; e os jebuseus habitam com os filhos de Benjamim em Jerusalém até o dia de hoje.",n:"O livro de Josué dizia o mesmo dos filhos de Judá: Jerusalém ficava na fronteira das duas tribos."},
{s:"A casa de José e as outras tribos"},
{v:22,t:"Também a casa de José subiu contra Betel, e o Senhor estava com eles.",np:1},
{v:23,t:"Quando a casa de José mandou explorar Betel — cujo nome era antes Luza —,"},
{v:24,t:"os espiões viram um homem que saía da cidade e disseram-lhe: Mostra-nos por onde se entra na cidade, e usaremos de bondade contigo."},
{v:25,t:"Ele mostrou-lhes por onde se entrava na cidade, e eles a passaram ao fio da espada; mas deixaram ir aquele homem com toda a sua família."},
{v:26,t:"O homem foi para a terra dos heteus, construiu uma cidade e deu-lhe o nome de Luza; e esse é o seu nome até o dia de hoje.",n:"O homem de Luza repete ao contrário a história de Raab: ela escolheu Israel e ficou no meio do povo; ele salvou a vida e foi construir longe uma nova Luza."},
{v:27,t:"Manassés não expulsou os habitantes de Bet-San e das suas cidades dependentes, nem os de Tanac e das suas cidades dependentes, nem os de Dor e das suas cidades dependentes, nem os de Jeblaam e das suas cidades dependentes, nem os de Meguido e das suas cidades dependentes; os cananeus conseguiram continuar habitando nessa terra.",np:1},
{v:28,t:"Quando Israel se tornou mais forte, sujeitou os cananeus a trabalhos forçados, mas não os expulsou."},
{v:29,t:"Também Efraim não expulsou os cananeus que habitavam em Gazer; e os cananeus continuaram habitando no meio dele, em Gazer."},
{v:30,t:"Zabulon não expulsou os habitantes de Cetron nem os habitantes de Naalol; os cananeus habitaram no meio dele e foram sujeitos a trabalhos forçados."},
{v:31,t:"Aser não expulsou os habitantes de Aco, nem os de Sidônia, de Aalab, de Aczib, de Helba, de Afec e de Roob;"},
{v:32,t:"e os de Aser habitaram no meio dos cananeus, habitantes da terra, porque não os expulsaram."},
{v:33,t:"Neftali não expulsou os habitantes de Bet-Sames nem os de Bet-Anat, e habitou no meio dos cananeus, habitantes da terra; mas os habitantes de Bet-Sames e de Bet-Anat foram-lhe sujeitos a trabalhos forçados."},
{v:34,t:"Os amorreus repeliram os filhos de Dã para a montanha, e não os deixaram descer à planície.",n:"É a razão da migração de Dã para o norte, que o capítulo 18 vai contar."},
{v:35,t:"Os amorreus conseguiram continuar habitando em Har-Heres, em Aialon e em Salebim; mas a mão da casa de José pesou sobre eles, e foram sujeitos a trabalhos forçados."},
{v:36,t:"O território dos amorreus ia desde a subida de Acrabim até a Rocha, e mais acima."}
];

window.TEXTOS_SEED["juizes"][2] = [
{s:"O anjo do Senhor em Boquim"},
{v:1,t:"O anjo do Senhor subiu de Guilgal a Boquim e disse: Eu vos fiz subir do Egito e vos trouxe à terra que jurara dar a vossos pais; e disse: Nunca romperei a minha aliança convosco,",n:"O anjo do Senhor é, em muitas páginas antigas, o próprio Senhor que se torna visível e fala: aqui fala na primeira pessoa, em nome de Deus."},
{v:2,t:"com a condição de que não fizésseis aliança com os habitantes desta terra, mas derrubásseis os seus altares. Mas não obedecestes à minha voz. Por que fizestes isto?"},
{v:3,t:"Por isso também eu digo: Não os expulsarei de diante de vós; eles serão para vós um laço, e os seus deuses, uma armadilha."},
{v:4,t:"Quando o anjo do Senhor disse estas palavras a todos os filhos de Israel, o povo levantou a voz e chorou."},
{v:5,t:"E deram àquele lugar o nome de Boquim; e ofereceram ali sacrifícios ao Senhor.",n:"Boquim quer dizer os que choram."},
{s:"A geração que não conhecia o Senhor"},
{v:6,t:"Quando Josué despediu o povo, os filhos de Israel foram, cada um para a sua herança, para tomar posse da terra.",np:1,n:"Os versículos 6 a 9 retomam, quase à letra, o fim do livro de Josué: o livro dos Juízes começa pela segunda vez."},
{v:7,t:"O povo serviu o Senhor durante toda a vida de Josué e durante toda a vida dos anciãos que sobreviveram a Josué e que tinham visto toda a grande obra que o Senhor fizera por Israel."},
{v:8,t:"Josué, filho de Nun, servo do Senhor, morreu com a idade de cento e dez anos,"},
{v:9,t:"e sepultaram-no no território da sua herança, em Tamnat-Saré, na montanha de Efraim, ao norte do monte Gaás."},
{v:10,t:"Também toda aquela geração foi reunida a seus pais, e depois dela levantou-se outra geração, que não conhecia o Senhor, nem a obra que ele fizera por Israel.",n:"Conhecer, na Bíblia, é mais do que saber: é ter a experiência viva de alguém. A fé que não se transmite morre numa geração."},
{v:11,t:"Os filhos de Israel fizeram o que era mau aos olhos do Senhor e serviram os baais.",np:1,n:"Começa aqui o esquema que o livro vai repetir: Israel peca, Deus o entrega aos inimigos, Israel clama, Deus suscita um juiz que o liberta, a terra descansa — até o juiz morrer e tudo recomeçar. Os baais eram as figuras locais de Baal, deus cananeu da tempestade e da fertilidade."},
{v:12,t:"Abandonaram o Senhor, Deus de seus pais, que os fizera sair da terra do Egito, e seguiram outros deuses, dos deuses dos povos que os rodeavam; prostraram-se diante deles e irritaram o Senhor."},
{v:13,t:"Abandonaram o Senhor e serviram Baal e as Astartes.",n:"Astarte, ou Astarot, era a deusa cananeia do amor e da guerra, companheira de Baal."},
{v:14,t:"A ira do Senhor inflamou-se contra Israel, e ele os entregou nas mãos de saqueadores, que os saquearam; vendeu-os às mãos dos inimigos que os rodeavam, e eles não puderam mais resistir aos seus inimigos."},
{v:15,t:"Em tudo o que empreendiam, a mão do Senhor estava contra eles para o mal, como o Senhor dissera e como lhes jurara; e ficaram em grande aflição."},
{v:16,t:"Então o Senhor suscitou juízes, que os livraram das mãos dos que os saqueavam.",np:1},
{v:17,t:"Mas também não escutaram os seus juízes, porque se prostituíram com outros deuses e se prostraram diante deles. Desviaram-se depressa do caminho por onde tinham andado os seus pais, que obedeciam aos mandamentos do Senhor; não fizeram como eles.",n:"Prostituir-se é a imagem que os profetas usarão para a idolatria: a aliança é um casamento, e o culto a outros deuses, um adultério."},
{v:18,t:"Quando o Senhor lhes suscitava juízes, o Senhor estava com o juiz e os livrava das mãos dos seus inimigos durante toda a vida do juiz; pois o Senhor se compadecia dos seus gemidos por causa dos que os oprimiam e maltratavam.",n:"Compadecia-se: o verbo hebraico, nicham, diz também mudar de sentimento. Deus não é indiferente ao gemido dos oprimidos, mesmo quando a opressão é consequência do pecado."},
{v:19,t:"Mas, quando o juiz morria, voltavam a corromper-se mais do que os seus pais, seguindo outros deuses, servindo-os e prostrando-se diante deles; não renunciavam às suas práticas nem ao seu caminho obstinado."},
{v:20,t:"Por isso a ira do Senhor inflamou-se contra Israel, e ele disse: Porque esta nação transgrediu a aliança que eu prescrevi a seus pais e não escutou a minha voz,",np:1},
{v:21,t:"também eu não expulsarei mais de diante deles nenhuma das nações que Josué deixou quando morreu,"},
{v:22,t:"para por meio delas pôr Israel à prova, se guardam ou não o caminho do Senhor, andando nele como os seus pais o guardaram."},
{v:23,t:"Por isso o Senhor deixou ficar essas nações, sem as expulsar logo, e não as entregou nas mãos de Josué."}
];

window.TEXTOS_SEED["juizes"][3] = [
{s:"As nações que ficaram"},
{v:1,t:"Estas são as nações que o Senhor deixou ficar para por meio delas pôr à prova Israel, todos os que não tinham conhecido nenhuma das guerras de Canaã",n:"Três razões diferentes explicam, nos capítulos 2 e 3, a presença das nações: castigo, prova, aprendizado da guerra. O livro não escolhe entre elas."},
{v:2,t:"— somente para que as gerações dos filhos de Israel aprendessem a guerra, ao menos as que antes não a tinham conhecido —:"},
{v:3,t:"os cinco príncipes dos filisteus, todos os cananeus, os sidônios e os heveus que habitavam na montanha do Líbano, desde o monte de Baal-Hermon até a entrada de Emat."},
{v:4,t:"Elas ficaram para que por meio delas se pusesse Israel à prova, para saber se obedeceria aos mandamentos que o Senhor dera a seus pais por meio de Moisés."},
{v:5,t:"Assim, os filhos de Israel habitaram no meio dos cananeus, dos heteus, dos amorreus, dos ferezeus, dos heveus e dos jebuseus;",np:1},
{v:6,t:"tomaram as filhas deles por mulheres, deram as suas próprias filhas aos filhos deles e serviram os seus deuses."},
{s:"Otoniel"},
{v:7,t:"Os filhos de Israel fizeram o que era mau aos olhos do Senhor; esqueceram o Senhor seu Deus e serviram os baais e as aserás.",np:1,n:"As aserás eram postes sagrados de madeira, símbolos da deusa Aserá. A Nova Vulgata diz aqui Astarot."},
{v:8,t:"A ira do Senhor inflamou-se contra Israel, e ele os entregou nas mãos de Cusã-Rasataim, rei da Mesopotâmia; e os filhos de Israel serviram Cusã-Rasataim durante oito anos.",n:"Cusã-Rasataim quer dizer Cusã da dupla maldade: o nome parece ser uma deformação irônica. Mesopotâmia traduz Aram dos dois rios, no norte da Síria."},
{v:9,t:"Os filhos de Israel clamaram ao Senhor, e o Senhor suscitou-lhes um salvador, que os libertou: Otoniel, filho de Cenez, irmão mais novo de Caleb."},
{v:10,t:"O Espírito do Senhor veio sobre ele, e ele julgou Israel. Saiu para a guerra, e o Senhor entregou-lhe nas mãos Cusã-Rasataim, rei da Mesopotâmia; e a sua mão prevaleceu contra Cusã-Rasataim.",n:"O Espírito do Senhor, que virá sobre Gedeão, Jefté e Sansão, é a força de Deus que se apodera de um homem para uma missão. Otoniel é o juiz modelo, contado só com as fórmulas do esquema."},
{v:11,t:"A terra descansou quarenta anos, e Otoniel, filho de Cenez, morreu."},
{s:"Aod"},
{v:12,t:"Os filhos de Israel voltaram a fazer o que era mau aos olhos do Senhor; e o Senhor fortaleceu Eglon, rei de Moab, contra Israel, porque tinham feito o que era mau aos olhos do Senhor.",np:1},
{v:13,t:"Eglon aliou-se aos filhos de Amon e a Amalec, marchou, derrotou Israel e apoderou-se da cidade das Palmeiras."},
{v:14,t:"E os filhos de Israel serviram Eglon, rei de Moab, durante dezoito anos."},
{v:15,t:"Os filhos de Israel clamaram ao Senhor, e o Senhor suscitou-lhes um salvador: Aod, filho de Gera, benjaminita, que era canhoto. Os filhos de Israel enviaram por meio dele o tributo a Eglon, rei de Moab.",n:"Canhoto, à letra impedido da mão direita. Há ironia: Benjamim quer dizer filho da direita. Um guarda revistaria o lado esquerdo, onde um destro traz a espada."},
{v:16,t:"Aod fez para si um punhal de dois gumes, de um palmo de comprimento, e cingiu-o debaixo da roupa, sobre a coxa direita."},
{v:17,t:"E apresentou o tributo a Eglon, rei de Moab. Ora, Eglon era um homem muito gordo.",n:"Eglon soa como egel, bezerro: o rei gordo é o novilho cevado para o sacrifício. A narrativa, com os seus detalhes crus, é uma sátira do opressor."},
{v:18,t:"Depois de apresentar o tributo, despediu os homens que o tinham carregado;"},
{v:19,t:"mas ele mesmo voltou dos ídolos que estão perto de Guilgal e disse: Tenho uma palavra secreta para ti, ó rei. O rei disse: Silêncio! E saíram todos os que estavam junto dele.",n:"Os ídolos, pesilim, eram talvez estátuas de pedra junto de Guilgal, que serviam de marco."},
{v:20,t:"Aod aproximou-se dele, que estava sentado sozinho no quarto fresco do andar de cima, e disse: Tenho uma palavra de Deus para ti. O rei levantou-se do trono."},
{v:21,t:"Então Aod estendeu a mão esquerda, tirou o punhal da coxa direita e cravou-o no ventre do rei,"},
{v:22,t:"de tal modo que também o cabo entrou atrás da lâmina, e a gordura fechou-se sobre a lâmina; pois ele não tirou o punhal do ventre. E os excrementos saíram."},
{v:23,t:"Aod saiu pelo vestíbulo, fechou atrás de si as portas do quarto de cima e passou o ferrolho."},
{v:24,t:"Depois que ele saiu, chegaram os servos do rei e viram que as portas do quarto de cima estavam trancadas; e disseram: Certamente está fazendo as suas necessidades no quarto fresco.",n:"À letra, está cobrindo os pés, eufemismo hebraico. O cheiro confirmava a suposição dos servos, e a demora deu a Aod o tempo da fuga."},
{v:25,t:"Esperaram até ficarem constrangidos; e, como ele não abria as portas do quarto, tomaram a chave e abriram: o seu senhor estava caído no chão, morto."},
{v:26,t:"Enquanto eles hesitavam, Aod escapara; passou pelos ídolos e refugiou-se em Seira.",np:1},
{v:27,t:"Quando chegou, tocou a trombeta na montanha de Efraim, e os filhos de Israel desceram com ele da montanha; e ele ia à frente deles."},
{v:28,t:"E disse-lhes: Segui-me, porque o Senhor entregou nas vossas mãos os vossos inimigos, os moabitas. Desceram atrás dele, ocuparam os vaus do Jordão, na direção de Moab, e não deixaram passar ninguém."},
{v:29,t:"Naquele tempo, derrotaram os moabitas, uns dez mil homens, todos robustos e valentes; e nenhum escapou."},
{v:30,t:"Naquele dia, Moab foi humilhado sob a mão de Israel; e a terra descansou oitenta anos."},
{s:"Samgar"},
{v:31,t:"Depois dele veio Samgar, filho de Anat, que derrotou seiscentos filisteus com uma aguilhada de bois; também ele salvou Israel.",np:1,n:"Anat é o nome de uma deusa cananeia da guerra: Samgar talvez não fosse israelita. Os juízes que o livro menciona de passagem, sem história, costumam chamar-se juízes menores."}
];

window.TEXTOS_SEED["juizes"][4] = [
{s:"Débora e Barac"},
{v:1,t:"Depois da morte de Aod, os filhos de Israel voltaram a fazer o que era mau aos olhos do Senhor;"},
{v:2,t:"e o Senhor os entregou nas mãos de Jabin, rei de Canaã, que reinava em Hasor. O chefe do seu exército chamava-se Sísara e habitava em Haroset-Goim.",n:"Jabin, rei de Hasor, é também o nome do rei vencido por Josué no capítulo 11: as tradições não se ajustam com exatidão. Haroset-Goim quer dizer Haroset das nações."},
{v:3,t:"Os filhos de Israel clamaram ao Senhor, porque Jabin tinha novecentos carros de ferro e oprimira duramente os filhos de Israel durante vinte anos."},
{v:4,t:"Naquele tempo, Débora, uma profetisa, mulher de Lapidot, julgava Israel.",np:1,n:"Débora quer dizer abelha. É a única juíza de Israel e a primeira profetisa depois de Míriam: exerce ao mesmo tempo a justiça e a palavra de Deus."},
{v:5,t:"Ela se sentava debaixo da palmeira de Débora, entre Ramá e Betel, na montanha de Efraim; e os filhos de Israel subiam a ela para os julgamentos."},
{v:6,t:"Ela mandou chamar Barac, filho de Abinoem, de Cedes de Neftali, e disse-lhe: O Senhor, Deus de Israel, te ordena: Vai, reúne gente no monte Tabor e toma contigo dez mil homens dos filhos de Neftali e dos filhos de Zabulon."},
{v:7,t:"Eu atrairei para ti, à torrente de Quison, Sísara, chefe do exército de Jabin, com os seus carros e a sua multidão, e o entregarei nas tuas mãos."},
{v:8,t:"Barac respondeu-lhe: Se vieres comigo, irei; mas, se não vieres comigo, não irei."},
{v:9,t:"Ela disse: Irei contigo, certamente; mas não será tua a glória no caminho que vais seguir, porque o Senhor entregará Sísara nas mãos de uma mulher. Débora levantou-se e foi com Barac a Cedes.",n:"O leitor pensa em Débora; a mulher será outra, Jael."},
{v:10,t:"Barac convocou Zabulon e Neftali a Cedes; dez mil homens subiram atrás dele, e Débora subiu com ele."},
{v:11,t:"Héber, o quenita, tinha-se separado dos quenitas, descendentes de Hobab, parente de Moisés, e armara a sua tenda junto ao carvalho de Saananim, perto de Cedes.",np:1},
{v:12,t:"Anunciaram a Sísara que Barac, filho de Abinoem, tinha subido ao monte Tabor."},
{v:13,t:"Sísara reuniu todos os seus carros, novecentos carros de ferro, e todo o povo que estava com ele, desde Haroset-Goim até a torrente de Quison."},
{v:14,t:"Débora disse a Barac: Levanta-te, porque este é o dia em que o Senhor entregou Sísara nas tuas mãos. Não é o Senhor que sai à tua frente? Barac desceu do monte Tabor, e dez mil homens atrás dele.",np:1},
{v:15,t:"O Senhor lançou o pânico em Sísara, em todos os seus carros e em todo o seu exército, diante de Barac, ao fio da espada; e Sísara desceu do carro e fugiu a pé.",n:"O cântico do capítulo 5 dirá como: a torrente de Quison transbordou, e os carros atolaram na lama. A arma temida tornou-se inútil."},
{v:16,t:"Barac perseguiu os carros e o exército até Haroset-Goim, e todo o exército de Sísara caiu ao fio da espada; não ficou nenhum."},
{v:17,t:"Sísara fugiu a pé para a tenda de Jael, mulher de Héber, o quenita, porque havia paz entre Jabin, rei de Hasor, e a casa de Héber, o quenita.",np:1},
{v:18,t:"Jael saiu ao encontro de Sísara e disse-lhe: Entra, meu senhor, entra aqui; não tenhas medo. Ele entrou na tenda dela, e ela o cobriu com um manto."},
{v:19,t:"Ele lhe disse: Dá-me, por favor, um pouco de água para beber, porque tenho sede. Ela abriu o odre de leite, deu-lhe de beber e o cobriu."},
{v:20,t:"Ele lhe disse: Fica à entrada da tenda; e, se alguém vier e te perguntar: Há alguém aqui?, responde: Não."},
{v:21,t:"Mas Jael, mulher de Héber, tomou uma estaca da tenda, pegou o martelo, aproximou-se dele devagar e cravou-lhe a estaca na têmpora, até pregá-la no chão; ele estava profundamente adormecido, esgotado, e morreu.",n:"Nota do tradutor: o gesto de Jael viola a lei sagrada da hospitalidade, e o texto não o esconde. O livro celebra-o como libertação de um povo oprimido, e o cântico do capítulo seguinte chama-a bendita entre as mulheres. A Escritura narra a violência de uma época sem a propor como modelo; a própria fé de Israel, e mais ainda o Evangelho, ensinarão a não pagar o mal com o mal. Armar e desarmar a tenda era trabalho das mulheres: Jael usa as ferramentas que conhecia."},
{v:22,t:"E eis que Barac, que perseguia Sísara, chegou. Jael saiu ao seu encontro e disse-lhe: Vem, que eu te mostrarei o homem que procuras. Ele entrou com ela: Sísara jazia morto, com a estaca na têmpora.",np:1},
{v:23,t:"Assim, naquele dia, Deus humilhou Jabin, rei de Canaã, diante dos filhos de Israel;"},
{v:24,t:"e a mão dos filhos de Israel foi pesando cada vez mais sobre Jabin, rei de Canaã, até que o exterminaram."}
];

window.TEXTOS_SEED["juizes"][5] = [
{s:"O cântico de Débora"},
{v:1,t:"Naquele dia, Débora e Barac, filho de Abinoem, cantaram este cântico:",n:"O cântico de Débora é tido por um dos textos mais antigos da Bíblia, talvez do século XII antes de Cristo, próximo dos fatos que canta. O hebraico é arcaico e em muitos versos obscuro; a tradução segue o sentido mais provável e, onde o texto é incerto, a leitura da Nova Vulgata."},
{v:2,l:["Quando em Israel os guerreiros soltam a cabeleira,","quando o povo se oferece de boa vontade,","bendizei o Senhor!"],n:"Soltar a cabeleira: talvez o voto dos guerreiros consagrados à guerra santa, que não cortavam o cabelo, como Sansão. Outros entendem: quando os chefes tomam a frente."},
{v:3,l:["Ouvi, reis; escutai, príncipes:","eu, eu cantarei ao Senhor,","salmodiarei ao Senhor, Deus de Israel!"]},
{v:4,l:["Senhor, quando saíste de Seir,","quando avançaste dos campos de Edom,","a terra tremeu, os céus gotejaram, e as nuvens desfizeram-se em água;"],n:"O Senhor vem do sul, de Seir e de Edom, onde fica o Sinai: a teofania do Sinai repete-se na tempestade que decide a batalha."},
{v:5,l:["os montes derreteram-se diante do Senhor, o do Sinai,","diante do Senhor, Deus de Israel."]},
{v:6,l:["Nos dias de Samgar, filho de Anat,","nos dias de Jael, os caminhos estavam desertos, e os viajantes","seguiam por atalhos tortuosos."]},
{v:7,l:["Faltaram os chefes em Israel, faltaram,","até que te levantaste, Débora,","te levantaste como mãe em Israel."]},
{v:8,l:["Escolheram deuses novos;","então a guerra estava às portas.","Não se via escudo nem lança","entre quarenta mil em Israel."],n:"Os versos 8 a 11 estão entre os mais obscuros do texto hebraico."},
{v:9,l:["O meu coração está com os chefes de Israel.","Vós, que vos oferecestes de boa vontade no meio do povo, bendizei o Senhor!"]},
{v:10,l:["Vós, que montais em jumentas brancas","e vos sentais sobre tapetes,","e vós, que andais pelo caminho, falai!"]},
{v:11,l:["Ao som dos que repartem as águas","junto aos bebedouros,","ali se celebram os atos de justiça do Senhor,","os atos de justiça do seu poder em Israel.","Então o povo do Senhor desceu às portas."]},
{v:12,l:["Desperta, desperta, Débora;","desperta, desperta, entoa um cântico!","Levanta-te, Barac, e leva os teus cativos,","filho de Abinoem!"]},
{v:13,l:["Então o resto desceu ao encontro dos nobres,","o povo do Senhor desceu com ele entre os valentes."]},
{v:14,l:["De Efraim vieram os chefes para o vale,","atrás de ti, Benjamim, entre as tuas tropas.","De Maquir desceram os comandantes, e de Zabulon os que empunham o bastão de chefe."],n:"O cântico passa em revista as tribos: umas vieram — Efraim, Benjamim, Maquir, Zabulon, Issacar, Neftali —, outras ficaram em casa — Rúben, Galaad, Dã, Aser. Judá e Simeão nem são nomeados: Israel ainda não é um povo unido."},
{v:15,l:["Os príncipes de Issacar estavam com Débora,","e Barac foi lançado ao vale com os seus soldados a pé.","Entre os clãs de Rúben, grandes deliberações do coração."]},
{v:16,l:["Por que ficaste sentado entre os currais,","para ouvir a flauta junto dos rebanhos?","Entre os clãs de Rúben, grandes indecisões do coração."],n:"Ironia amarga: Rúben muito deliberou e nada fez."},
{v:17,l:["Galaad ficou do outro lado do Jordão;","e Dã, por que se demora junto aos navios?","Aser ficou na costa do mar","e permaneceu nos seus portos."]},
{v:18,l:["Mas Zabulon é um povo que expôs a vida à morte,","e Neftali, nas alturas do campo."]},
{v:19,l:["Vieram os reis e combateram,","combateram então os reis de Canaã,","em Tanac, junto às águas de Meguido; mas não levaram despojo de prata!"]},
{v:20,l:["Do céu combateram as estrelas,","das suas órbitas combateram contra Sísara."],n:"As estrelas eram imaginadas como o exército do céu. A chuva torrencial que fez transbordar o Quison é cantada como o céu inteiro em guerra por Israel."},
{v:21,l:["A torrente de Quison arrastou-os,","a torrente antiga, a torrente de Quison. Avança, ó minha alma, com força!"]},
{v:22,l:["Então ressoaram os cascos dos cavalos","no galope, no galope dos seus corcéis."]},
{v:23,l:["Amaldiçoai Meroz, diz o anjo do Senhor,","amaldiçoai, amaldiçoai os seus habitantes,","porque não vieram em socorro do Senhor,","em socorro do Senhor entre os valentes."]},
{v:24,l:["Bendita entre as mulheres seja Jael, mulher de Héber, o quenita,","entre as mulheres da tenda seja bendita!"],n:"Bendita entre as mulheres: a mesma saudação que Isabel dirigirá a Maria, no Evangelho segundo São Lucas. Os Padres viram em Jael, que esmaga a cabeça do inimigo, uma figura da mulher do Gênesis e de Maria."},
{v:25,l:["Ele pediu água, ela deu-lhe leite;","numa taça de príncipes ofereceu-lhe coalhada."]},
{v:26,l:["Estendeu a mão esquerda para a estaca,","e a direita para o martelo dos trabalhadores;","feriu Sísara, esmagou-lhe a cabeça,","furou e traspassou-lhe a têmpora."]},
{v:27,l:["Aos pés dela ele se curvou, caiu, ficou estendido;","aos pés dela se curvou e caiu;","onde se curvou, ali caiu, sem vida."]},
{v:28,l:["Pela janela olha e lamenta","a mãe de Sísara, através da grade:","Por que tarda a chegar o seu carro? Por que se atrasam as rodas dos seus carros?"],n:"A cena passa de repente à mãe do vencido, que espera à janela. O poeta não sente pena dela, mas a sua ironia deixa entrever o outro lado da guerra."},
{v:29,l:["As mais sábias das suas damas respondem-lhe,","e ela mesma repete para si as suas palavras:"]},
{v:30,l:["Certamente estão repartindo os despojos que acharam: uma moça, duas moças para cada guerreiro;","um despojo de tecidos coloridos","para Sísara;","um ou dois bordados de cores","para o meu pescoço, como despojo."]},
{v:31,l:["Assim pereçam todos os teus inimigos, Senhor!","Mas os que o amam sejam","como o sol quando se levanta em todo o seu esplendor."],n:"A Nova Vulgata divide em dois versículos, 31 e 32, o que o hebraico conta como um só; por isso o capítulo tem aqui um versículo a mais."},
{v:32,t:"E a terra descansou quarenta anos.",np:1}
];

window.TEXTOS_SEED["juizes"][6] = [
{s:"A opressão de Madiã"},
{v:1,t:"Os filhos de Israel fizeram o que era mau aos olhos do Senhor, e o Senhor os entregou nas mãos de Madiã durante sete anos."},
{v:2,t:"A mão de Madiã pesou sobre Israel; por causa de Madiã, os filhos de Israel fizeram para si os esconderijos que há nas montanhas, as cavernas e os lugares fortificados."},
{v:3,t:"Sempre que Israel semeava, subiam Madiã, Amalec e os filhos do Oriente, e subiam contra ele;",n:"Os madianitas, nômades do deserto a leste, fazem incursões no tempo da colheita. É a primeira vez que a Bíblia mostra camelos usados em grande número na guerra."},
{v:4,t:"acampavam diante deles, destruíam os produtos da terra até a entrada de Gaza e não deixavam em Israel nada que desse sustento, nem ovelha, nem boi, nem jumento."},
{v:5,t:"Pois subiam com os seus rebanhos e as suas tendas, e chegavam numerosos como gafanhotos; eles e os seus camelos eram inumeráveis, e invadiam a terra para devastá-la."},
{v:6,t:"Israel ficou muito empobrecido por causa de Madiã."},
{v:7,t:"E clamou ao Senhor, pedindo socorro contra os madianitas."},
{v:8,t:"O Senhor enviou-lhes um profeta, que lhes disse: Assim diz o Senhor, Deus de Israel: Eu vos fiz subir do Egito e vos tirei da casa da escravidão;",np:1},
{v:9,t:"livrei-vos das mãos dos egípcios e das mãos de todos os que vos oprimiam; expulsei-os de diante de vós e vos dei a terra deles."},
{v:10,t:"E disse-vos: Eu sou o Senhor vosso Deus; não temais os deuses dos amorreus, em cuja terra habitais. Mas não escutastes a minha voz.",n:"O profeta sem nome faz, antes do libertador, o diagnóstico: o problema de Israel não é Madiã; é a infidelidade."},
{s:"O chamado de Gedeão"},
{v:11,t:"O anjo do Senhor veio e sentou-se debaixo do carvalho de Efra, que pertencia a Joás, do clã de Abiezer. Gedeão, seu filho, malhava o trigo no lagar, para escondê-lo de Madiã.",np:1,n:"Malhar o trigo no lagar, uma cavidade escavada na rocha, e não na eira aberta ao vento, era o modo de escondê-lo dos saqueadores. O libertador é chamado enquanto se esconde."},
{v:12,t:"O anjo do Senhor apareceu-lhe e disse: O Senhor está contigo, valente guerreiro!",n:"O Senhor está contigo: é a saudação que o anjo dirá a Maria. Valente guerreiro, a um homem que se escondia: Deus chama alguém por aquilo que vai fazer dele."},
{v:13,t:"Gedeão respondeu: Ah, meu senhor! Se o Senhor está conosco, por que nos aconteceu tudo isto? Onde estão todas as suas maravilhas, que os nossos pais nos contaram, dizendo: O Senhor nos fez subir do Egito? Agora o Senhor nos abandonou e nos entregou nas mãos de Madiã."},
{v:14,t:"O Senhor voltou-se para ele e disse: Vai com essa força que tens e livra Israel das mãos de Madiã. Não sou eu que te envio?"},
{v:15,t:"Ele respondeu: Ah, meu Senhor! Com que livrarei Israel? O meu clã é o mais fraco de Manassés, e eu sou o menor na casa de meu pai.",n:"O menor, o mais fraco: como Moisés, Saul, Davi e Jeremias, Gedeão alega a sua pequenez, e é por ela que Deus o escolhe."},
{v:16,t:"O Senhor disse-lhe: Eu estarei contigo, e derrotarás Madiã como se fosse um só homem."},
{v:17,t:"Ele disse: Se encontrei graça aos teus olhos, dá-me um sinal de que és tu que falas comigo."},
{v:18,t:"Não te retires daqui, peço-te, até que eu volte a ti, trazendo a minha oferta e colocando-a diante de ti. Ele respondeu: Ficarei aqui até que voltes."},
{v:19,t:"Gedeão entrou em casa, preparou um cabrito e, com um efá de farinha, pães sem fermento; pôs a carne num cesto e o caldo numa panela, trouxe-os para debaixo do carvalho e os apresentou.",np:1,n:"Um efá eram perto de vinte e dois litros: uma quantidade generosa, num tempo de fome."},
{v:20,t:"O anjo de Deus disse-lhe: Toma a carne e os pães sem fermento, põe-nos sobre esta rocha e derrama o caldo. Ele assim fez."},
{v:21,t:"O anjo do Senhor estendeu a ponta do cajado que tinha na mão e tocou a carne e os pães sem fermento; subiu da rocha um fogo que consumiu a carne e os pães. E o anjo do Senhor desapareceu dos seus olhos."},
{v:22,t:"Gedeão viu que era o anjo do Senhor e disse: Ai de mim, Senhor Deus, porque vi o anjo do Senhor face a face!",n:"Ninguém pode ver Deus e continuar vivo, dizia o Êxodo: daí o medo de Gedeão."},
{v:23,t:"O Senhor disse-lhe: A paz esteja contigo! Não temas; não morrerás."},
{v:24,t:"Gedeão construiu ali um altar ao Senhor e chamou-o: O Senhor é paz. Ele está ainda hoje em Efra dos abiezritas.",n:"O Senhor é paz, em hebraico Yahweh shalom."},
{s:"Gedeão derruba o altar de Baal"},
{v:25,t:"Naquela noite, o Senhor disse-lhe: Toma o touro de teu pai, o segundo touro, de sete anos; derruba o altar de Baal que pertence a teu pai e corta o poste sagrado que está junto dele;",np:1,n:"A primeira missão de Gedeão é dentro da própria casa: o pai tinha um altar a Baal. A reforma começa em casa."},
{v:26,t:"e constrói ao Senhor teu Deus, no alto desta fortaleza, um altar bem-disposto; depois toma o segundo touro e oferece-o em holocausto, com a lenha do poste sagrado que tiveres cortado."},
{v:27,t:"Gedeão tomou dez homens dentre os seus servos e fez como o Senhor lhe dissera; mas, como tinha medo da família de seu pai e dos homens da cidade, fê-lo de noite, e não de dia."},
{v:28,t:"Quando os homens da cidade se levantaram de manhã, viram que o altar de Baal tinha sido derrubado, o poste sagrado que estava junto dele cortado, e o segundo touro oferecido sobre o altar que fora construído."},
{v:29,t:"Perguntaram uns aos outros: Quem fez isto? Informaram-se e procuraram, e disseram: Foi Gedeão, filho de Joás, quem fez isto."},
{v:30,t:"Os homens da cidade disseram a Joás: Traze para fora o teu filho, para que morra, porque derrubou o altar de Baal e cortou o poste sagrado que estava junto dele."},
{v:31,t:"Joás respondeu a todos os que o cercavam: Quereis vós defender a causa de Baal? Quereis vós salvá-lo? Quem defender a causa dele será morto antes de amanhecer. Se ele é deus, que defenda ele mesmo a sua causa, já que derrubaram o seu altar.",n:"O argumento de Joás é o dos profetas: um deus que precisa ser defendido pelos homens não é Deus."},
{v:32,t:"Naquele dia, Gedeão recebeu o nome de Jerobaal, porque disseram: Que Baal dispute com ele, pois derrubou o seu altar.",n:"Jerobaal quer dizer que Baal dispute. O nome, que parecia honrar Baal, é relido como desafio ao ídolo."},
{s:"O sinal do velo"},
{v:33,t:"Todo o Madiã, Amalec e os filhos do Oriente reuniram-se, atravessaram o Jordão e acamparam no vale de Jezrael.",np:1},
{v:34,t:"O Espírito do Senhor revestiu Gedeão; ele tocou a trombeta, e os abiezritas foram convocados para segui-lo.",n:"Revestiu, à letra vestiu-se de Gedeão: o Espírito entra nele como numa roupa."},
{v:35,t:"Enviou mensageiros por todo o Manassés, que também o seguiu; e enviou mensageiros a Aser, a Zabulon e a Neftali, que subiram ao seu encontro."},
{v:36,t:"Gedeão disse a Deus: Se vais salvar Israel pela minha mão, como disseste,",np:1},
{v:37,t:"eis que vou pôr um velo de lã na eira: se houver orvalho só no velo, e todo o chão ficar seco, saberei que salvarás Israel pela minha mão, como disseste."},
{v:38,t:"E assim aconteceu. Levantou-se de madrugada, espremeu o velo e tirou dele orvalho, uma taça cheia de água."},
{v:39,t:"Gedeão disse ainda a Deus: Não se inflame contra mim a tua ira, se falar ainda uma vez; deixa-me fazer só mais uma prova com o velo: que fique seco só o velo, e haja orvalho em todo o chão."},
{v:40,t:"E Deus assim fez naquela noite: só o velo ficou seco, e houve orvalho em todo o chão.",n:"Pedir sinais a Deus não é caminho recomendado pela Escritura, e Gedeão pede dois, com medo de irritá-lo; Deus tem paciência com a sua fraqueza. Os Padres viram no velo orvalhado uma figura de Maria, que recebeu em si o orvalho do céu."}
];

window.TEXTOS_SEED["juizes"][7] = [
{s:"Os trezentos homens"},
{v:1,t:"Jerobaal, isto é, Gedeão, levantou-se de madrugada, com todo o povo que estava com ele, e acamparam junto à fonte de Harod; o acampamento de Madiã ficava ao norte dele, no vale, junto à colina de Moré.",n:"Harod quer dizer tremor: o nome prepara a triagem dos medrosos."},
{v:2,t:"O Senhor disse a Gedeão: O povo que está contigo é numeroso demais para que eu entregue Madiã nas suas mãos; Israel poderia gloriar-se contra mim, dizendo: A minha mão me salvou.",n:"Toda a história é uma lição sobre isto: a vitória vem de Deus, e não do número. São Paulo dirá que Deus escolhe o que é fraco para confundir o que é forte."},
{v:3,t:"Anuncia, pois, aos ouvidos do povo: Quem tiver medo e tremer, volte e retire-se do monte Gelboé. Voltaram vinte e dois mil homens do povo, e ficaram dez mil.",n:"O hebraico diz aqui monte Galaad, que fica do outro lado do Jordão; a Nova Vulgata lê Gelboé, que fica perto. A dispensa dos medrosos era lei da guerra santa, segundo o Deuteronômio."},
{v:4,t:"O Senhor disse a Gedeão: O povo ainda é numeroso demais. Faze-os descer à água, e ali os porei à prova para ti. Aquele de quem eu te disser: Este irá contigo, esse irá contigo; e todo aquele de quem eu te disser: Este não irá contigo, esse não irá.",np:1},
{v:5,t:"Gedeão fez o povo descer à água, e o Senhor disse-lhe: Todos os que lamberem a água com a língua, como lambe o cão, põe-nos de um lado; e todos os que se ajoelharem para beber, põe-nos do outro."},
{v:6,t:"O número dos que lamberam a água, levando-a à boca com a mão, foi de trezentos homens; todo o resto do povo se ajoelhou para beber.",n:"Não está claro o que o teste revela: talvez os que bebem levando a água com a mão fiquem atentos ao inimigo. O mais provável é que a escolha seja de propósito arbitrária: o que importa é que fiquem poucos."},
{v:7,t:"O Senhor disse a Gedeão: Com os trezentos homens que lamberam a água vos salvarei e entregarei Madiã nas tuas mãos; que todo o resto do povo volte, cada um para o seu lugar."},
{v:8,t:"Tomaram as provisões do povo e as suas trombetas, e Gedeão mandou todos os homens de Israel para as suas tendas, ficando só com os trezentos. O acampamento de Madiã estava abaixo dele, no vale."},
{s:"O sonho do pão de cevada"},
{v:9,t:"Naquela mesma noite, o Senhor disse-lhe: Levanta-te, desce contra o acampamento, porque o entreguei nas tuas mãos.",np:1},
{v:10,t:"Mas, se tens medo de descer, desce ao acampamento com Fara, teu servo;"},
{v:11,t:"ouvirás o que eles dizem, e depois as tuas mãos se fortalecerão, e descerás contra o acampamento. Ele desceu, pois, com Fara, seu servo, até a extremidade dos postos avançados do acampamento."},
{v:12,t:"Madiã, Amalec e todos os filhos do Oriente estavam estendidos no vale, numerosos como gafanhotos; os seus camelos eram inumeráveis, como a areia da praia do mar."},
{v:13,t:"Quando Gedeão chegou, um homem contava um sonho ao seu companheiro, dizendo: Tive um sonho: um pão de cevada rolava pelo acampamento de Madiã; chegou até a tenda, bateu nela, e ela caiu; revirou-a de cima para baixo, e a tenda ficou por terra.",n:"O pão de cevada, alimento dos pobres e dos agricultores, é Israel; a tenda é Madiã, o povo nômade."},
{v:14,t:"O companheiro respondeu: Isto não é outra coisa senão a espada de Gedeão, filho de Joás, homem de Israel; Deus entregou-lhe nas mãos Madiã e todo o acampamento."},
{v:15,t:"Quando Gedeão ouviu o relato do sonho e a sua interpretação, prostrou-se em adoração; voltou ao acampamento de Israel e disse: Levantai-vos, porque o Senhor entregou nas vossas mãos o acampamento de Madiã.",np:1},
{s:"A vitória sobre Madiã"},
{v:16,t:"Dividiu os trezentos homens em três grupos e deu-lhes a todos trombetas e cântaros vazios, com tochas dentro dos cântaros,",np:1},
{v:17,t:"e disse-lhes: Olhai para mim e fazei como eu. Quando eu chegar à extremidade do acampamento, fazei o que eu fizer."},
{v:18,t:"Quando eu e todos os que estão comigo tocarmos a trombeta, tocai também vós as trombetas em redor de todo o acampamento e gritai: Pelo Senhor e por Gedeão!"},
{v:19,t:"Gedeão e os cem homens que estavam com ele chegaram à extremidade do acampamento no começo da vigília do meio da noite, logo depois de rendidas as sentinelas; tocaram as trombetas e quebraram os cântaros que tinham nas mãos.",n:"O hebraico diz cem, um dos três grupos; a Nova Vulgata, com a Vulgata antiga, diz trezentos."},
{v:20,t:"Os três grupos tocaram as trombetas e quebraram os cântaros; com a mão esquerda seguravam as tochas, e com a direita as trombetas para tocar, e gritavam: Espada pelo Senhor e por Gedeão!"},
{v:21,t:"Ficaram cada um no seu lugar, em redor do acampamento; e todo o acampamento se pôs a correr, gritando e fugindo.",n:"Os trezentos não combatem: ficam no seu lugar. O barulho, as luzes e o pânico noturno fazem o resto."},
{v:22,t:"Enquanto os trezentos tocavam as trombetas, o Senhor fez que a espada de cada um se voltasse contra o companheiro, em todo o acampamento; e o exército fugiu até Bet-Seta, na direção de Sereda, até a margem de Abel-Meula, perto de Tebat."},
{v:23,t:"Os homens de Israel, de Neftali, de Aser e de todo o Manassés, foram convocados e perseguiram Madiã.",np:1},
{v:24,t:"Gedeão enviou mensageiros por toda a montanha de Efraim, dizendo: Descei ao encontro de Madiã e ocupai antes deles as águas até Bet-Bera, e o Jordão. Todos os homens de Efraim foram convocados e ocuparam as águas até Bet-Bera, e o Jordão."},
{v:25,t:"Capturaram os dois chefes de Madiã, Oreb e Zeb; mataram Oreb no rochedo de Oreb, e Zeb no lagar de Zeb; perseguiram Madiã e levaram a Gedeão, do outro lado do Jordão, as cabeças de Oreb e de Zeb.",n:"Oreb quer dizer corvo, e Zeb, lobo. Isaías lembrará o dia de Madiã como o grande exemplo da vitória de Deus."}
];
