// =====================================================================
// Neemias — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["neemias"][1] = [
{s:"A oração de Neemias"},
{v:1,t:"Palavras de Neemias, filho de Hacalias. No mês de Casleu, no vigésimo ano, estando eu na cidadela de Susa,",n:"Casleu: novembro e dezembro. O vigésimo ano de Artaxerxes I é 445 antes de Cristo (2,1). Susa era a residência de inverno dos reis persas. O livro começa com as memórias de Neemias, escritas na primeira pessoa."},
{v:2,t:"Hanani, um dos meus irmãos, chegou com alguns homens de Judá. Perguntei-lhes pelos judeus que tinham escapado, os que tinham sobrevivido ao cativeiro, e por Jerusalém."},
{v:3,t:"Eles me responderam: Os que sobreviveram ao cativeiro, lá na província, estão em grande miséria e humilhação; a muralha de Jerusalém está em ruínas, e as suas portas foram queimadas.",n:"Talvez depois da tentativa de reconstrução interrompida por ordem de Artaxerxes (Esdras 4,7-23)."},
{v:4,t:"Ao ouvir estas palavras, sentei-me e chorei; fiquei de luto durante vários dias, jejuando e orando diante do Deus do céu."},
{v:5,t:"E disse: Ah, Senhor, Deus do céu, Deus grande e temível, que guardas a aliança e a misericórdia para com os que te amam e guardam os teus mandamentos!",np:1},
{v:6,t:"Que os teus ouvidos estejam atentos e os teus olhos abertos, para ouvires a oração que o teu servo faz hoje diante de ti, dia e noite, pelos filhos de Israel, teus servos, confessando os pecados dos filhos de Israel, que cometemos contra ti. Também eu e a casa de meu pai pecamos."},
{v:7,t:"Agimos muito mal contra ti, e não guardamos os mandamentos, os estatutos e as normas que prescreveste a Moisés, teu servo."},
{v:8,t:"Lembra-te da palavra que ordenaste a Moisés, teu servo: Se fordes infiéis, eu vos dispersarei entre os povos;"},
{v:9,t:"mas, se voltardes a mim, guardardes os meus mandamentos e os puserdes em prática, ainda que os vossos dispersos estejam nos confins do céu, de lá os reunirei e os trarei ao lugar que escolhi para nele fazer habitar o meu nome.",n:"Citação livre de Deuteronômio 30,1-5 e 12,5."},
{v:10,t:"Eles são os teus servos e o teu povo, que resgataste com o teu grande poder e com a tua mão forte."},
{v:11,t:"Ah, Senhor, que os teus ouvidos estejam atentos à oração do teu servo e à oração dos teus servos, que desejam temer o teu nome! Faze que hoje o teu servo seja bem-sucedido e encontre compaixão diante deste homem. Eu era então copeiro do rei.",n:"O copeiro, que servia e provava o vinho do rei, era um homem da sua inteira confiança."}
];

window.TEXTOS_SEED["neemias"][2] = [
{s:"Neemias enviado a Jerusalém"},
{v:1,t:"No mês de Nisan, no vigésimo ano do rei Artaxerxes, estando o vinho diante dele, tomei o vinho e o servi ao rei. Nunca antes eu tinha aparecido triste diante dele.",n:"Nisan: março e abril, quatro meses depois da notícia (1,1)."},
{v:2,t:"O rei perguntou-me: Por que está triste o teu rosto, se não estás doente? Isto não é senão tristeza do coração. Tive muito medo,",n:"Mostrar tristeza diante do rei podia ser tomado como descontentamento, e até como ameaça."},
{v:3,t:"e respondi ao rei: Viva o rei para sempre! Como não estaria triste o meu rosto, se a cidade onde estão os túmulos de meus pais está em ruínas, e as suas portas foram consumidas pelo fogo?"},
{v:4,t:"O rei me disse: Que pedes? Então orei ao Deus do céu",n:"Uma oração rápida, no coração, antes de responder: a oração acompanha cada passo da ação de Neemias."},
{v:5,t:"e respondi ao rei: Se parecer bem ao rei, e se o teu servo te for agradável, envia-me a Judá, à cidade dos túmulos de meus pais, para reconstruí-la."},
{v:6,t:"O rei, que tinha a rainha sentada ao seu lado, perguntou-me: Quanto tempo durará a tua viagem, e quando voltarás? Pareceu bem ao rei enviar-me, e eu lhe indiquei um prazo.",n:"Neemias ficará em Jerusalém doze anos (5,14; 13,6)."},
{v:7,t:"E disse ao rei: Se parecer bem ao rei, deem-me cartas para os governadores da Transeufratênia, para que me deixem passar até chegar a Judá;"},
{v:8,t:"e uma carta para Asaf, guarda do parque real, para que me dê madeira para vigar as portas da cidadela do templo, a muralha da cidade e a casa onde vou morar. E o rei concedeu-me as cartas, porque a mão bondosa do meu Deus estava sobre mim."},
{v:9,t:"Fui ter com os governadores da Transeufratênia e entreguei-lhes as cartas do rei. O rei tinha mandado comigo oficiais do exército e cavaleiros.",np:1},
{v:10,t:"Quando Sanabalat, o horonita, e Tobias, o servo amonita, souberam disso, ficaram muito desgostosos de que tivesse vindo alguém para procurar o bem dos filhos de Israel.",n:"Sanabalat, governador de Samaria, é conhecido também por papiros judaicos de Elefantina, no Egito. Tobias governava talvez a região de Amon, a leste do Jordão; servo seria o título de um funcionário do rei."},
{s:"Neemias examina as muralhas"},
{v:11,t:"Cheguei a Jerusalém e fiquei ali três dias.",np:1},
{v:12,t:"Depois levantei-me de noite, com alguns homens, sem dizer a ninguém o que o meu Deus me tinha posto no coração fazer por Jerusalém; e não levava comigo outro animal senão aquele em que eu montava."},
{v:13,t:"Saí de noite pela porta do Vale, na direção da fonte do Dragão e da porta do Monturo, e examinei a muralha de Jerusalém, que estava em ruínas, e as suas portas, consumidas pelo fogo."},
{v:14,t:"Passei à porta da Fonte e ao tanque do Rei, e não havia lugar por onde o animal em que eu montava pudesse passar."},
{v:15,t:"Subi de noite pela torrente e examinei a muralha; depois voltei pela porta do Vale e regressei.",n:"Neemias contorna o sul e o leste da cidade, pelo vale do Cedron."},
{v:16,t:"Os magistrados não sabiam aonde eu tinha ido nem o que tinha feito; até então nada tinha dito aos judeus, nem aos sacerdotes, nem aos nobres, nem aos magistrados, nem aos outros que iam fazer a obra."},
{v:17,t:"Então lhes disse: Vós vedes a miséria em que estamos: Jerusalém está em ruínas, e as suas portas foram consumidas pelo fogo. Vinde, reconstruamos a muralha de Jerusalém, e não sejamos mais objeto de vergonha!",np:1},
{v:18,t:"E contei-lhes como a mão bondosa do meu Deus estava sobre mim, e as palavras que o rei me tinha dito. Eles disseram: Levantemo-nos e construamos! E encheram-se de coragem para a boa obra."},
{v:19,t:"Quando Sanabalat, o horonita, Tobias, o servo amonita, e Gosem, o árabe, souberam disso, zombaram de nós e nos desprezaram, dizendo: Que é isso que estais fazendo? Acaso vos revoltais contra o rei?",n:"Gosem, o árabe, era chefe das tribos árabes do sul da Palestina."},
{v:20,t:"Eu lhes respondi: O próprio Deus do céu nos fará prosperar; nós, os seus servos, vamos levantar-nos e construir. Mas vós não tendes parte, nem direito, nem memória em Jerusalém."}
];

window.TEXTOS_SEED["neemias"][3] = [
{s:"A reconstrução das muralhas"},
{v:1,t:"O sumo sacerdote Eliasib levantou-se com os seus irmãos, os sacerdotes, e construíram a porta das Ovelhas; cobriram-na de vigas e colocaram as suas folhas, e continuaram até a torre dos Cem e a torre de Hananeel.",n:"A porta das Ovelhas ficava ao norte do templo, perto do tanque de Betesda (João 5,2). A descrição dá a volta às muralhas: norte, oeste, sul e leste."},
{v:2,t:"Ao lado deles construíram os homens de Jericó; e ao lado deles construiu Zacur, filho de Imri."},
{v:3,t:"Os filhos de Senaá construíram a porta dos Peixes; cobriram-na de vigas e colocaram as suas folhas, as fechaduras e as trancas.",np:1},
{v:4,t:"Ao lado deles trabalhou nos reparos Meremot, filho de Urias, filho de Acos; ao lado dele trabalhou Mosolam, filho de Baraquias, filho de Mesezabel; ao lado dele trabalhou Sadoc, filho de Baana;"},
{v:5,t:"ao lado dele trabalharam os de Técua; mas os seus nobres não quiseram dobrar a nuca para o serviço do seu Senhor."},
{v:6,t:"Joiada, filho de Faseia, e Mosolam, filho de Besodias, restauraram a porta Velha; cobriram-na de vigas e colocaram as suas folhas, as fechaduras e as trancas.",np:1},
{v:7,t:"Ao lado deles trabalharam Melcias, de Gabaon, e Jadon, de Meronot, homens de Gabaon e de Masfa, que dependiam da sede do governador da Transeufratênia;"},
{v:8,t:"ao lado deles trabalhou Oziel, filho de Haraías, dos ourives; e ao lado dele trabalhou Hananias, dos perfumistas; e restauraram Jerusalém até a muralha Larga."},
{v:9,t:"Ao lado deles trabalhou Rafaías, filho de Hur, chefe da metade do distrito de Jerusalém;"},
{v:10,t:"ao lado dele trabalhou Jedaías, filho de Haromaf, em frente da sua casa; e ao lado dele trabalhou Hatus, filho de Hasabnias."},
{v:11,t:"Melquias, filho de Harim, e Hasub, filho de Faat-Moab, restauraram outro trecho, até a torre dos Fornos."},
{v:12,t:"Ao lado deles trabalhou Selum, filho de Aloes, chefe da outra metade do distrito de Jerusalém, ele e as suas filhas.",n:"Também as mulheres trabalham na muralha."},
{v:13,t:"Hanun e os habitantes de Zanoa restauraram a porta do Vale; construíram-na, colocaram as suas folhas, as fechaduras e as trancas, e restauraram mil côvados de muralha, até a porta do Monturo.",np:1},
{v:14,t:"Melquias, filho de Recab, chefe do distrito de Bet-Carem, restaurou a porta do Monturo; construiu-a e colocou as suas folhas, as fechaduras e as trancas."},
{v:15,t:"Selum, filho de Col-Hoze, chefe do distrito de Masfa, restaurou a porta da Fonte; construiu-a, cobriu-a e colocou as suas folhas, as fechaduras e as trancas; e restaurou também a muralha do tanque de Siloé, junto ao jardim do rei, até os degraus que descem da Cidade de Davi."},
{v:16,t:"Depois dele trabalhou Neemias, filho de Azboc, chefe da metade do distrito de Bet-Sur, até em frente dos túmulos de Davi, até o tanque artificial e até a casa dos Valentes.",np:1},
{v:17,t:"Depois dele trabalharam os levitas: Reum, filho de Bani; ao lado dele trabalhou Hasabias, chefe da metade do distrito de Ceila, pelo seu distrito;"},
{v:18,t:"depois dele trabalharam os seus irmãos: Bavai, filho de Henadad, chefe da outra metade do distrito de Ceila."},
{v:19,t:"Ao lado dele, Ezer, filho de Jesua, chefe de Masfa, restaurou outro trecho, em frente da subida do arsenal, no ângulo."},
{v:20,t:"Depois dele, Baruc, filho de Zacai, restaurou outro trecho, desde o ângulo até a porta da casa do sumo sacerdote Eliasib."},
{v:21,t:"Depois dele, Meremot, filho de Urias, filho de Acos, restaurou outro trecho, desde a porta da casa de Eliasib até o fim da casa de Eliasib."},
{v:22,t:"Depois dele trabalharam os sacerdotes, homens da planície.",n:"A planície: o vale do Jordão, em volta de Jericó."},
{v:23,t:"Depois deles, Benjamim e Hasub trabalharam em frente da sua casa; depois deles, Azarias, filho de Maasias, filho de Ananias, trabalhou junto da sua casa."},
{v:24,t:"Depois dele, Benui, filho de Henadad, restaurou outro trecho, desde a casa de Azarias até o ângulo e a esquina."},
{v:25,t:"Falal, filho de Ozi, trabalhou em frente do ângulo e da torre que se eleva do palácio superior do rei, junto ao pátio da prisão; depois dele, Fadaías, filho de Farós, trabalhou"},
{v:26,t:"até em frente da porta das Águas, a oriente, e da torre saliente."},
{v:27,t:"Depois dele, os de Técua restauraram outro trecho, desde em frente da grande torre saliente até a muralha do templo."},
{v:28,t:"A partir da porta dos Cavalos, os sacerdotes trabalharam, cada um em frente da sua casa.",np:1},
{v:29,t:"Depois deles, Sadoc, filho de Emer, trabalhou em frente da sua casa; e depois dele trabalhou Semeías, filho de Secenias, guarda da porta Oriental."},
{v:30,t:"Depois dele, Hananias, filho de Selemias, e Hanun, sexto filho de Selef, restauraram outro trecho. Depois deles, Mosolam, filho de Baraquias, trabalhou em frente do seu quarto."},
{v:31,t:"Depois dele, Melquias, dos ourives, trabalhou até a casa dos natineus e dos mercadores, em frente da porta da Inspeção, e até a sala alta do ângulo."},
{v:32,t:"E entre a sala alta do ângulo e a porta das Ovelhas trabalharam os ourives e os mercadores."},
{s:"A zombaria de Sanabalat e de Tobias"},
{v:33,t:"Quando Sanabalat soube que estávamos reconstruindo a muralha, irou-se, ficou muito indignado e zombou dos judeus,",np:1,n:"Nas traduções que seguem a numeração grega, os versículos 33 a 38 são 4,1-6, e o capítulo 4 começa depois deles no versículo 7."},
{v:34,t:"e disse diante dos seus irmãos e dos notáveis de Samaria: Que fazem estes judeus miseráveis? Vão deixá-los fazer? Vão oferecer sacrifícios? Vão acabar num só dia? Farão reviver as pedras dos montões de entulho, que foram queimadas?"},
{v:35,t:"E Tobias, o amonita, que estava ao lado dele, disse: Deixai-os construir! Se uma raposa subir, derrubará a muralha de pedra deles."},
{v:36,t:"Ouve, nosso Deus, como somos desprezados! Faze recair o seu insulto sobre a cabeça deles e entrega-os ao desprezo numa terra de cativeiro!",n:"Nota do tradutor: Neemias responde ao insulto com uma prece de vingança, como nos salmos imprecatórios, e o texto não a suaviza. Mas a vingança é entregue a Deus, e não praticada pelas próprias mãos (Romanos 12,19); e Jesus ensinará a orar pelos que nos perseguem (Mateus 5,44)."},
{v:37,t:"Não cubras a sua iniquidade, e que o seu pecado não se apague diante de ti, porque ofenderam os que constroem."},
{v:38,t:"Assim reconstruímos a muralha, e toda a muralha ficou completa até a metade da altura; e o povo tinha ânimo para trabalhar."}
];

window.TEXTOS_SEED["neemias"][4] = [
{s:"A espada numa mão"},
{v:1,t:"Quando Sanabalat, Tobias, os árabes, os amonitas e os de Azoto souberam que a restauração das muralhas de Jerusalém progredia e que as brechas começavam a fechar-se, irritaram-se muito;"},
{v:2,t:"e conspiraram todos juntos para vir atacar Jerusalém e semear a confusão."},
{v:3,t:"Mas nós oramos ao nosso Deus e pusemos guardas contra eles, dia e noite."},
{v:4,t:"E Judá dizia: As forças dos carregadores estão falhando, e o entulho é muito; não conseguiremos construir a muralha.",n:"Talvez um canto de trabalho, em ritmo de lamentação, que exprime o desânimo."},
{v:5,t:"E os nossos inimigos diziam: Que não saibam nem vejam nada, até que caiamos no meio deles, os matemos e façamos parar a obra."},
{v:6,t:"Quando os judeus que moravam perto deles vieram dizer-nos dez vezes, de todos os lugares de onde vinham até nós, que eles iam atacar,",np:1},
{v:7,t:"pusemo-nos nas partes mais baixas, atrás da muralha, nos lugares descobertos, e dispus o povo por famílias, com as suas espadas, as suas lanças e os seus arcos."},
{v:8,t:"Depois de examinar tudo, levantei-me e disse aos nobres, aos magistrados e ao resto do povo: Não tenhais medo deles! Lembrai-vos do Senhor, grande e temível, e combatei pelos vossos irmãos, pelos vossos filhos e pelas vossas filhas, pelas vossas mulheres e pelas vossas casas!"},
{v:9,t:"Quando os nossos inimigos souberam que estávamos avisados e que Deus tinha frustrado o seu plano, voltamos todos à muralha, cada um ao seu trabalho.",np:1},
{v:10,t:"Desde aquele dia, metade dos meus homens trabalhava na obra, e a outra metade segurava as lanças, os escudos, os arcos e as couraças; e os chefes estavam por trás de toda a casa de Judá."},
{v:11,t:"Os que construíam a muralha e os que carregavam os fardos trabalhavam com uma mão e com a outra seguravam a arma."},
{v:12,t:"Cada um dos construtores tinha a espada cingida à cintura, e assim construíam; e o que tocava a corneta estava junto de mim.",n:"Construir com a espada numa mão tornou-se imagem da vigilância de quem trabalha na obra de Deus."},
{v:13,t:"Eu disse aos nobres, aos magistrados e ao resto do povo: A obra é grande e extensa, e nós estamos espalhados pela muralha, longe uns dos outros."},
{v:14,t:"No lugar onde ouvirdes o som da corneta, ali vos reunireis junto de nós. O nosso Deus combaterá por nós."},
{v:15,t:"Assim trabalhávamos na obra, e metade de nós segurava as lanças, desde o romper da aurora até o aparecer das estrelas.",np:1},
{v:16,t:"Naquele tempo disse também ao povo: Que cada um passe a noite em Jerusalém com o seu servo: de noite faremos a guarda, e de dia trabalharemos."},
{v:17,t:"Nem eu, nem os meus irmãos, nem os meus servos, nem os homens da guarda que me seguiam tirávamos a roupa; cada um tinha a arma na mão direita."}
];

window.TEXTOS_SEED["neemias"][5] = [
{s:"Neemias defende os pobres"},
{v:1,t:"Levantou-se um grande clamor do povo e das suas mulheres contra os seus irmãos judeus."},
{v:2,t:"Uns diziam: Penhoramos os nossos filhos e as nossas filhas para conseguir trigo, para comermos e vivermos!"},
{v:3,t:"Outros diziam: Hipotecamos os nossos campos, as nossas vinhas e as nossas casas, para conseguir trigo durante a fome!"},
{v:4,t:"E outros diziam: Tomamos dinheiro emprestado, dando em garantia os nossos campos e as nossas vinhas, para pagar o tributo do rei."},
{v:5,t:"E, no entanto, a nossa carne é como a carne dos nossos irmãos, e os nossos filhos são como os filhos deles; e eis que temos de sujeitar à escravidão os nossos filhos e as nossas filhas, e algumas das nossas filhas já são escravas, sem que possamos resgatá-las, porque os nossos campos e as nossas vinhas pertencem a outros.",n:"A Lei proibia emprestar a juros a um irmão israelita e limitava a servidão por dívidas (Êxodo 22,24; Levítico 25,35-43; Deuteronômio 23,20-21)."},
{v:6,t:"Fiquei muito irritado quando ouvi o seu clamor e estas palavras.",np:1},
{v:7,t:"Depois de refletir comigo mesmo, repreendi os nobres e os magistrados, e disse-lhes: Emprestais a juros aos vossos irmãos! E convoquei contra eles uma grande assembleia."},
{v:8,t:"E disse-lhes: Nós, segundo as nossas possibilidades, resgatamos os nossos irmãos judeus que tinham sido vendidos às nações; e vós vendeis os vossos irmãos, para que depois sejam vendidos a nós! Eles se calaram e não souberam o que responder."},
{v:9,t:"Eu disse ainda: Não está bem o que fazeis. Não deveríeis andar no temor do nosso Deus, para não sermos insultados pelas nações, nossas inimigas?"},
{v:10,t:"Também eu, os meus irmãos e os meus servos emprestamos a muitos dinheiro e trigo. Deixemos de cobrar esses juros!"},
{v:11,t:"Devolvei-lhes hoje mesmo os seus campos, as suas vinhas, os seus olivais e as suas casas, e o juro de um por cento do dinheiro, do trigo, do vinho e do azeite que costumais exigir deles.",n:"Um por cento ao mês, talvez: doze por cento ao ano."},
{v:12,t:"Eles responderam: Devolveremos, e não lhes exigiremos nada; faremos como dizes. Então chamei os sacerdotes e os fiz jurar que fariam o que tinham prometido."},
{v:13,t:"Depois sacudi a dobra do meu manto e disse: Assim sacuda Deus da sua casa e dos seus bens todo homem que não cumprir esta palavra; assim seja ele sacudido e fique vazio! E toda a assembleia respondeu: Amém! E louvaram o Senhor. E o povo fez como tinha prometido.",n:"Um gesto profético: como se sacode o manto, Deus sacudirá o perjuro. Jesus mandará os discípulos sacudir o pó dos pés (Mateus 10,14)."},
{s:"O desinteresse de Neemias"},
{v:14,t:"Desde o dia em que o rei me nomeou governador na terra de Judá, do vigésimo ao trigésimo segundo ano do rei Artaxerxes, durante doze anos, nem eu nem os meus irmãos comemos a provisão devida ao governador.",np:1},
{v:15,t:"Os governadores anteriores, que me precederam, oprimiam o povo, exigindo dele cada dia quarenta siclos de prata pelo seu sustento; e até os seus servos tiranizavam o povo. Mas eu não fiz assim, por temor de Deus."},
{v:16,t:"Pelo contrário, dediquei-me ao trabalho da muralha, e não comprei nenhum campo; e todos os meus servos estavam reunidos ali para a obra."},
{v:17,t:"À minha mesa comiam cento e cinquenta homens, judeus e magistrados, além dos que vinham a nós das nações vizinhas."},
{v:18,t:"Preparava-se para mim, cada dia, um boi, seis ovelhas escolhidas e aves; e de dez em dez dias, vinho de toda espécie em abundância. Apesar disso, não exigi a provisão devida ao governador, porque o trabalho pesava muito sobre este povo."},
{v:19,t:"Lembra-te de mim, meu Deus, para o meu bem, por tudo o que fiz por este povo.",n:"Refrão das memórias de Neemias (13,14.22.31): ele confia a Deus a lembrança das suas obras."}
];

window.TEXTOS_SEED["neemias"][6] = [
{s:"As ciladas contra Neemias"},
{v:1,t:"Quando Sanabalat, Tobias, Gosem, o árabe, e os nossos outros inimigos souberam que eu tinha reconstruído a muralha e que não restava nela nenhuma brecha — embora até então eu não tivesse colocado as folhas nas portas —,"},
{v:2,t:"Sanabalat e Gosem mandaram dizer-me: Vem, e encontremo-nos em Cefirim, na planície de Ono. Mas eles tramavam fazer-me mal."},
{v:3,t:"Enviei-lhes mensageiros para dizer: Estou fazendo uma grande obra e não posso descer. Por que haveria a obra de parar, enquanto eu a deixo para descer até vós?"},
{v:4,t:"Mandaram-me a mesma mensagem quatro vezes, e eu lhes dei a mesma resposta."},
{v:5,t:"Então Sanabalat mandou-me pela quinta vez o seu servo, com a mesma mensagem, trazendo na mão uma carta aberta, na qual estava escrito:",np:1,n:"Uma carta aberta, para que o seu conteúdo se espalhasse."},
{v:6,t:"Corre entre as nações, e Gosem o confirma, que tu e os judeus pensais revoltar-vos, e que é por isso que reconstróis a muralha; e, segundo estes rumores, queres tornar-te rei deles;"},
{v:7,t:"e até puseste profetas para proclamarem a teu respeito em Jerusalém: Há um rei em Judá! Ora, estes rumores vão chegar ao rei. Vem, pois, e aconselhemo-nos juntos."},
{v:8,t:"Mandei-lhe responder: Nada disso que dizes aconteceu; és tu que o inventas no teu coração."},
{v:9,t:"Porque todos eles queriam amedrontar-nos, pensando: As suas mãos se cansarão da obra, e ela não se fará. Mas eu fortaleci ainda mais as minhas mãos."},
{v:10,t:"Fui à casa de Semeías, filho de Dalaías, filho de Meetabel, que estava impedido de sair. Ele me disse: Encontremo-nos na casa de Deus, dentro do santuário, e fechemos as portas do templo, porque virão matar-te; é de noite que virão matar-te.",np:1,n:"Semeías, fingindo-se profeta, queria levar Neemias, que não era sacerdote, a esconder-se no santuário: seria sacrilégio e covardia, e o desacreditaria diante do povo."},
{v:11,t:"Respondi: Um homem como eu fugiria? E quem, sendo como eu, poderia entrar no templo e continuar vivo? Não entrarei.",n:"Só os sacerdotes podiam entrar no santuário (Números 18,7)."},
{v:12,t:"E compreendi que não era Deus que o tinha enviado, mas que ele pronunciara aquela profecia contra mim porque Tobias e Sanabalat o tinham subornado."},
{v:13,t:"Tinha sido pago para que eu tivesse medo, agisse assim e pecasse, e eles tivessem um motivo para me difamar."},
{v:14,t:"Lembra-te, meu Deus, de Tobias e de Sanabalat, segundo estas suas obras, e também da profetisa Noadias e dos outros profetas que procuravam amedrontar-me!"},
{s:"A muralha terminada"},
{v:15,t:"A muralha foi terminada no vigésimo quinto dia do mês de Elul, em cinquenta e dois dias.",np:1,n:"Elul: agosto e setembro. Cinquenta e dois dias, graças ao entusiasmo do povo e às partes da antiga muralha que ainda estavam de pé."},
{v:16,t:"Quando todos os nossos inimigos souberam disso, e todas as nações vizinhas o viram, ficaram muito abatidos e reconheceram que esta obra tinha sido feita pelo nosso Deus."},
{v:17,t:"Naqueles dias, também muitos nobres de Judá mandavam cartas a Tobias, e as cartas de Tobias chegavam a eles."},
{v:18,t:"Porque muitos em Judá estavam ligados a ele por juramento, pois ele era genro de Secenias, filho de Area, e seu filho Joanã tinha casado com a filha de Mosolam, filho de Baraquias."},
{v:19,t:"Até falavam bem dele diante de mim e lhe contavam as minhas palavras; e Tobias mandava cartas para me amedrontar."}
];

window.TEXTOS_SEED["neemias"][7] = [
{s:"A guarda de Jerusalém"},
{v:1,t:"Quando a muralha foi reconstruída e coloquei as folhas das portas, e foram designados os porteiros, os cantores e os levitas,"},
{v:2,t:"confiei o governo de Jerusalém a meu irmão Hanani e a Hananias, comandante da cidadela, porque era um homem fiel e temente a Deus mais do que muitos outros;"},
{v:3,t:"e disse-lhes: As portas de Jerusalém não se abrirão antes que o sol aqueça; e, enquanto os guardas ainda estiverem de serviço, fechem-se as portas e passem-se as trancas. Ponham-se guardas dentre os habitantes de Jerusalém, cada um no seu posto, cada um em frente da sua casa."},
{v:4,t:"A cidade era espaçosa e grande, mas havia pouca gente dentro dela, e as casas não tinham sido reconstruídas.",np:1,n:"Neemias resolverá o problema fazendo vir para Jerusalém um décimo da população (11,1-2)."},
{s:"A lista dos que voltaram do exílio"},
{v:5,t:"Então o meu Deus me pôs no coração reunir os nobres, os magistrados e o povo, para fazer o seu recenseamento; e encontrei o registro genealógico dos que tinham voltado primeiro, e encontrei escrito nele:",np:1,n:"A lista que segue é a de Esdras 2, com pequenas diferenças nos nomes e nos números."},
{v:6,t:"Estes são os filhos da província que voltaram do cativeiro, dentre os exilados que Nabucodonosor, rei da Babilônia, tinha deportado, e que voltaram para Jerusalém e para Judá, cada um para a sua cidade."},
{v:7,t:"Vieram com Zorobabel, Josué, Neemias, Azarias, Raamias, Naamani, Mardoqueu, Belsã, Mesferet, Beguai, Naum e Baana. Este é o número dos homens do povo de Israel:"},
{v:8,t:"os filhos de Farós, dois mil cento e setenta e dois;",np:1},
{v:9,t:"os filhos de Safatias, trezentos e setenta e dois;"},
{v:10,t:"os filhos de Area, seiscentos e cinquenta e dois;"},
{v:11,t:"os filhos de Faat-Moab, isto é, os filhos de Jesua e de Joab, dois mil oitocentos e dezoito;"},
{v:12,t:"os filhos de Elam, mil duzentos e cinquenta e quatro;"},
{v:13,t:"os filhos de Zetua, oitocentos e quarenta e cinco;"},
{v:14,t:"os filhos de Zacai, setecentos e sessenta;"},
{v:15,t:"os filhos de Benui, seiscentos e quarenta e oito;"},
{v:16,t:"os filhos de Bebai, seiscentos e vinte e oito;"},
{v:17,t:"os filhos de Azgad, dois mil trezentos e vinte e dois;"},
{v:18,t:"os filhos de Adonicam, seiscentos e sessenta e sete;"},
{v:19,t:"os filhos de Beguai, dois mil e sessenta e sete;"},
{v:20,t:"os filhos de Adin, seiscentos e cinquenta e cinco;"},
{v:21,t:"os filhos de Ater, da família de Ezequias, noventa e oito;"},
{v:22,t:"os filhos de Hasum, trezentos e vinte e oito;"},
{v:23,t:"os filhos de Besai, trezentos e vinte e quatro;"},
{v:24,t:"os filhos de Haref, cento e doze;"},
{v:25,t:"os filhos de Gabaon, noventa e cinco;"},
{v:26,t:"os homens de Belém e de Netofa, cento e oitenta e oito;"},
{v:27,t:"os homens de Anatot, cento e vinte e oito;"},
{v:28,t:"os homens de Bet-Azmavet, quarenta e dois;"},
{v:29,t:"os homens de Cariat-Iarim, de Cafira e de Berot, setecentos e quarenta e três;"},
{v:30,t:"os homens de Ramá e de Gaba, seiscentos e vinte e um;"},
{v:31,t:"os homens de Macmas, cento e vinte e dois;"},
{v:32,t:"os homens de Betel e de Hai, cento e vinte e três;"},
{v:33,t:"os homens do outro Nebo, cinquenta e dois;"},
{v:34,t:"os homens do outro Elam, mil duzentos e cinquenta e quatro;"},
{v:35,t:"os filhos de Harim, trezentos e vinte;"},
{v:36,t:"os filhos de Jericó, trezentos e quarenta e cinco;"},
{v:37,t:"os filhos de Lod, de Hadid e de Ono, setecentos e vinte e um;"},
{v:38,t:"os filhos de Senaá, três mil novecentos e trinta."},
{v:39,t:"Os sacerdotes: os filhos de Jedaías, da casa de Jesua, novecentos e setenta e três;",np:1},
{v:40,t:"os filhos de Emer, mil e cinquenta e dois;"},
{v:41,t:"os filhos de Fassur, mil duzentos e quarenta e sete;"},
{v:42,t:"os filhos de Harim, mil e dezessete."},
{v:43,t:"Os levitas: os filhos de Jesua, isto é, os filhos de Cadmiel, de Benui e de Odovias, setenta e quatro.",np:1},
{v:44,t:"Os cantores: os filhos de Asaf, cento e quarenta e oito."},
{v:45,t:"Os porteiros: os filhos de Selum, os filhos de Ater, os filhos de Telmon, os filhos de Acub, os filhos de Hatita, os filhos de Sobai: cento e trinta e oito."},
{v:46,t:"Os natineus: os filhos de Siá, os filhos de Hasufa, os filhos de Tabaot,",np:1},
{v:47,t:"os filhos de Queros, os filhos de Siaa, os filhos de Fadon,"},
{v:48,t:"os filhos de Lebana, os filhos de Hagaba, os filhos de Selmai,"},
{v:49,t:"os filhos de Hanã, os filhos de Gidel, os filhos de Gaer,"},
{v:50,t:"os filhos de Raaías, os filhos de Rasin, os filhos de Necoda,"},
{v:51,t:"os filhos de Gazam, os filhos de Oza, os filhos de Faseia,"},
{v:52,t:"os filhos de Besai, os filhos dos meunitas, os filhos dos nefuseus,"},
{v:53,t:"os filhos de Bacbuc, os filhos de Hacufa, os filhos de Harur,"},
{v:54,t:"os filhos de Baslut, os filhos de Maida, os filhos de Harsa,"},
{v:55,t:"os filhos de Barcos, os filhos de Sísara, os filhos de Tema,"},
{v:56,t:"os filhos de Nasias, os filhos de Hatifa."},
{v:57,t:"Os filhos dos servos de Salomão: os filhos de Sotai, os filhos de Soferet, os filhos de Feruda,",np:1},
{v:58,t:"os filhos de Jaala, os filhos de Darcon, os filhos de Gidel,"},
{v:59,t:"os filhos de Safatias, os filhos de Hatil, os filhos de Foqueret-Hasebaim, os filhos de Amon."},
{v:60,t:"Ao todo, os natineus e os filhos dos servos de Salomão eram trezentos e noventa e dois."},
{v:61,t:"Estes são os que vieram de Tel-Mela, de Tel-Harsa, de Querub, de Adon e de Emer, e não puderam provar se a sua família e a sua descendência eram de Israel:",np:1},
{v:62,t:"os filhos de Dalaías, os filhos de Tobias, os filhos de Necoda, seiscentos e quarenta e dois."},
{v:63,t:"E, entre os sacerdotes, os filhos de Hobias, os filhos de Acos e os filhos de Berzelai, que tinha tomado por mulher uma das filhas de Berzelai, o galaadita, e foi chamado pelo nome deles."},
{v:64,t:"Estes procuraram o seu registro nas genealogias, mas não o encontraram, e foram excluídos do sacerdócio como impuros."},
{v:65,t:"O governador disse-lhes que não comessem das coisas santíssimas enquanto não se apresentasse um sacerdote para consultar os Urim e os Tumim."},
{v:66,t:"Toda a assembleia era de quarenta e dois mil trezentos e sessenta,",np:1},
{v:67,t:"sem contar os seus servos e servas, que eram sete mil trezentos e trinta e sete; tinham também duzentos e quarenta e cinco cantores e cantoras."},
{v:68,t:"Tinham setecentos e trinta e seis cavalos, duzentas e quarenta e cinco mulas,"},
{v:69,t:"quatrocentos e trinta e cinco camelos e seis mil setecentos e vinte jumentos."},
{v:70,t:"Alguns chefes de famílias fizeram doações para a obra. O governador deu ao tesouro mil dracmas de ouro, cinquenta bacias e quinhentas e trinta túnicas sacerdotais.",np:1},
{v:71,t:"E alguns chefes de famílias deram ao tesouro da obra vinte mil dracmas de ouro e duas mil e duzentas minas de prata."},
{v:72,t:"O que o resto do povo deu foi vinte mil dracmas de ouro, duas mil minas de prata e sessenta e sete túnicas sacerdotais. Os sacerdotes e os levitas habitaram ali; os porteiros, os cantores, uma parte do povo, os natineus e todo o Israel habitaram nas suas cidades. Chegou o sétimo mês, e os filhos de Israel estavam nas suas cidades.",n:"A última frase introduz a leitura da Lei (capítulo 8), como em Esdras 3,1."}
];

window.TEXTOS_SEED["neemias"][8] = [
{s:"Esdras lê a Lei diante do povo"},
{v:1,t:"Todo o povo reuniu-se como um só homem na praça que está diante da porta das Águas, e disseram ao escriba Esdras que trouxesse o livro da lei de Moisés, que o Senhor tinha prescrito a Israel.",n:"Esdras e Neemias aparecem juntos: depois das muralhas, é o povo que se reconstrói em torno da Lei. Esta assembleia é vista como o nascimento do judaísmo, a religião do Livro, e como o modelo da liturgia da Palavra."},
{v:2,t:"O sacerdote Esdras trouxe a Lei diante da assembleia, homens e mulheres e todos os que eram capazes de compreender. Era o primeiro dia do sétimo mês.",n:"O primeiro dia do sétimo mês, dia das Aclamações (Levítico 23,24), é hoje o Ano-Novo judaico."},
{v:3,t:"E leu o livro na praça que está diante da porta das Águas, desde a manhã até o meio-dia, na presença dos homens, das mulheres e dos que eram capazes de compreender; e os ouvidos de todo o povo estavam atentos ao livro da Lei."},
{v:4,t:"O escriba Esdras estava de pé sobre um estrado de madeira, feito para esse fim; e junto dele estavam, à sua direita, Matatias, Sema, Anaías, Urias, Helcias e Maasias; e, à sua esquerda, Fadaías, Misael, Melquias, Hasum, Hasbadana, Zacarias e Mosolam."},
{v:5,t:"Esdras abriu o livro à vista de todo o povo, porque estava mais alto do que todo o povo; e, quando o abriu, todo o povo se pôs de pé.",np:1,n:"O povo se levanta diante do livro da Palavra de Deus, como ainda hoje a assembleia cristã se levanta para ouvir o Evangelho."},
{v:6,t:"Esdras bendisse o Senhor, o grande Deus, e todo o povo respondeu, levantando as mãos: Amém! Amém! Depois inclinaram-se e prostraram-se diante do Senhor com o rosto em terra."},
{v:7,t:"Os levitas Jesua, Bani, Serebias, Jamin, Acub, Sabetai, Hodias, Maasias, Celita, Azarias, Jozabad, Hanã e Falaías explicavam a Lei ao povo, enquanto o povo permanecia no seu lugar."},
{v:8,t:"Liam no livro da lei de Deus de modo claro, explicavam o sentido e faziam compreender a leitura.",n:"De modo claro: talvez traduzindo para o aramaico, a língua que o povo então falava. Daqui nascerão os targuns, traduções comentadas da Escritura lidas na sinagoga."},
{v:9,t:"Neemias, o governador, o sacerdote e escriba Esdras e os levitas que instruíam o povo disseram a todo o povo: Este dia é consagrado ao Senhor vosso Deus; não fiqueis de luto nem choreis! Porque todo o povo chorava ao ouvir as palavras da Lei.",np:1,n:"O povo chora ao descobrir quanto se afastou da Lei; mas o dia do Senhor é dia de alegria."},
{v:10,t:"E Neemias lhes disse: Ide, comei carnes gordas e bebei bebidas doces, e mandai porções aos que nada têm preparado, porque este dia é consagrado ao nosso Senhor. Não vos entristeçais, porque a alegria do Senhor é a vossa força."},
{v:11,t:"Os levitas acalmavam todo o povo, dizendo: Calai-vos, porque este dia é santo; não vos entristeçais!"},
{v:12,t:"E todo o povo foi comer e beber, mandar porções e fazer uma grande festa, porque tinham compreendido as palavras que lhes tinham sido ensinadas."},
{s:"A festa das Tendas"},
{v:13,t:"No segundo dia, os chefes das famílias de todo o povo, os sacerdotes e os levitas reuniram-se junto do escriba Esdras, para estudar as palavras da Lei.",np:1},
{v:14,t:"E encontraram escrito na Lei que o Senhor tinha prescrito por meio de Moisés que os filhos de Israel deviam habitar em tendas durante a festa do sétimo mês,",n:"Ver Levítico 23,39-43."},
{v:15,t:"e que deviam proclamar e fazer anunciar em todas as suas cidades e em Jerusalém: Saí ao monte e trazei ramos de oliveira, ramos de oliveira brava, ramos de murta, folhas de palmeira e ramos de árvores frondosas, para fazer tendas, como está escrito."},
{v:16,t:"O povo saiu e trouxe os ramos, e fizeram tendas, cada um no seu terraço, nos seus pátios, nos átrios da casa de Deus, na praça da porta das Águas e na praça da porta de Efraim."},
{v:17,t:"Toda a assembleia dos que tinham voltado do cativeiro fez tendas e habitou nelas. Desde os dias de Josué, filho de Nun, até aquele dia, os filhos de Israel não tinham feito assim; e houve uma alegria muito grande.",n:"A festa era celebrada antes (Esdras 3,4), mas não com tanta participação e fidelidade à Lei."},
{v:18,t:"Esdras leu no livro da lei de Deus cada dia, desde o primeiro até o último. Celebraram a festa durante sete dias, e no oitavo dia houve uma assembleia solene, conforme o rito."}
];

window.TEXTOS_SEED["neemias"][9] = [
{s:"A confissão dos pecados"},
{v:1,t:"No vigésimo quarto dia do mesmo mês, os filhos de Israel reuniram-se para um jejum, vestidos de saco e com terra sobre a cabeça."},
{v:2,t:"Os da raça de Israel separaram-se de todos os estrangeiros; puseram-se de pé e confessaram os seus pecados e as iniquidades de seus pais."},
{v:3,t:"Levantaram-se, cada um no seu lugar, e leram no livro da lei do Senhor seu Deus durante a quarta parte do dia; e durante outra quarta parte confessavam os pecados e se prostravam diante do Senhor seu Deus.",n:"A quarta parte do dia: umas três horas."},
{v:4,t:"Sobre o estrado dos levitas estavam de pé Jesua, Bani, Cadmiel, Sebanias, Buni, Serebias, Bani e Canani, e clamaram em alta voz ao Senhor seu Deus."},
{s:"A grande oração dos levitas"},
{v:5,l:["Os levitas Jesua, Cadmiel, Bani, Hasabnias, Serebias, Hodias, Sebanias e Fetaías disseram:","Levantai-vos, bendizei o Senhor vosso Deus,","desde sempre e para sempre!","E bendigam o teu nome glorioso,","exaltado acima de toda bênção e louvor."],np:1,n:"Esta oração percorre a história de Israel, da criação ao exílio, como os Salmos 105 e 106: a fidelidade de Deus diante da infidelidade do povo. Inspirou muitas orações penitenciais da liturgia judaica e cristã."},
{v:6,l:["Só tu és o Senhor;","tu fizeste os céus, os céus dos céus","e todo o seu exército,","a terra e tudo o que ela contém, os mares e tudo o que neles há;","tu dás a vida a todos eles,","e o exército do céu te adora."],n:"O exército do céu: os astros, e também os anjos."},
{v:7,l:["Tu és o Senhor Deus, que escolheste Abrão,","o tiraste de Ur dos caldeus","e lhe deste o nome de Abraão."]},
{v:8,l:["Achaste o seu coração fiel diante de ti","e fizeste com ele a aliança,","para dar a terra do cananeu, do heteu e do amorreu,","do ferezeu, do jebuseu e do gergeseu,","para dá-la à sua descendência;","e cumpriste a tua palavra,","porque és justo."],n:"Achaste o seu coração fiel: a fé de Abraão (Gênesis 15,6), que Paulo tomará como modelo (Romanos 4)."},
{v:9,l:["Viste a aflição de nossos pais no Egito","e ouviste o seu clamor junto ao mar Vermelho."],np:1},
{v:10,l:["Fizeste sinais e prodígios contra o faraó,","contra todos os seus servos e todo o povo da sua terra,","porque sabias que tinham agido com arrogância contra eles;","e fizeste para ti um nome, como ainda hoje."]},
{v:11,l:["Abriste o mar diante deles,","e passaram pelo meio do mar a pé enxuto;","mas lançaste nas profundezas os seus perseguidores,","como uma pedra nas águas impetuosas."]},
{v:12,l:["Com uma coluna de nuvem os guiaste de dia,","e com uma coluna de fogo de noite,","para iluminar o caminho por onde deviam andar."]},
{v:13,l:["Desceste sobre o monte Sinai","e falaste com eles do céu;","deste-lhes normas justas","e leis verdadeiras, estatutos e mandamentos bons."]},
{v:14,l:["Deste-lhes a conhecer o teu santo sábado,","e lhes prescreveste mandamentos, estatutos e uma lei","por meio de Moisés, teu servo."]},
{v:15,l:["Deste-lhes pão do céu na sua fome","e fizeste sair água da rocha na sua sede;","e lhes disseste que entrassem e possuíssem a terra","que tinhas jurado, de mão erguida, dar-lhes."]},
{v:16,l:["Mas eles, os nossos pais, agiram com arrogância,","endureceram a cerviz e não ouviram os teus mandamentos."],np:1},
{v:17,l:["Recusaram-se a ouvir","e não se lembraram das maravilhas que fizeste por eles;","endureceram a cerviz","e escolheram um chefe","para voltar à sua escravidão no Egito.","Mas tu és um Deus que perdoa, clemente e misericordioso,","lento para a ira e rico em misericórdia, e não os abandonaste."],n:"Ver Números 14,4. Clemente e misericordioso: as palavras da revelação do Senhor a Moisés (Êxodo 34,6)."},
{v:18,l:["E mesmo quando fizeram para si um bezerro de metal fundido","e disseram: Este é o teu Deus,","que te tirou do Egito,","e cometeram grandes blasfêmias,"]},
{v:19,l:["tu, na tua grande misericórdia,","não os abandonaste no deserto:","a coluna de nuvem não se afastou deles de dia,","para guiá-los no caminho,","nem a coluna de fogo de noite,","para iluminar o caminho por onde deviam andar."]},
{v:20,l:["Deste-lhes o teu bom espírito para os instruir,","não recusaste o teu maná à sua boca","e lhes deste água na sua sede."],n:"O teu bom espírito: talvez o espírito dado aos setenta anciãos (Números 11,17-25)."},
{v:21,l:["Durante quarenta anos os sustentaste no deserto,","e nada lhes faltou;","as suas vestes não se gastaram,","e os seus pés não incharam."],n:"Ver Deuteronômio 8,4."},
{v:22,l:["Deste-lhes reinos e povos","e os repartiste por regiões;","possuíram a terra de Seon, a terra do rei de Hesbon,","e a terra de Og, rei de Basã."],np:1},
{v:23,l:["Multiplicaste os seus filhos como as estrelas do céu","e os levaste à terra da qual tinhas dito a seus pais","que nela entrariam para possuí-la."]},
{v:24,l:["Os filhos entraram e possuíram a terra;","humilhaste diante deles os habitantes da terra, os cananeus,","e os entregaste nas suas mãos,","com os seus reis e os povos da terra,","para que fizessem deles o que quisessem."]},
{v:25,l:["Tomaram cidades fortificadas e uma terra fértil,","e possuíram casas cheias de toda espécie de bens,","cisternas já cavadas, vinhas, olivais","e árvores frutíferas em abundância.","Comeram, saciaram-se, engordaram","e deleitaram-se na tua grande bondade."]},
{v:26,l:["Mas foram desobedientes e revoltaram-se contra ti,","lançaram a tua lei para trás das costas,","mataram os teus profetas,","que os advertiam para os fazer voltar a ti,","e cometeram grandes blasfêmias."],np:1,n:"Mataram os teus profetas: Jesus e Estêvão retomarão esta acusação (Mateus 23,37; Atos 7,52)."},
{v:27,l:["Então os entregaste nas mãos dos seus inimigos,","que os oprimiram;","e no tempo da sua angústia clamaram a ti,","e tu os ouviste do céu","e, na tua grande misericórdia, lhes deste salvadores,","que os livraram das mãos dos seus inimigos."],n:"O ciclo do livro dos Juízes: pecado, opressão, clamor, salvação (Juízes 2,11-19)."},
{v:28,l:["Mas, logo que tinham descanso, voltavam","a fazer o mal diante de ti;","e tu os abandonavas nas mãos dos seus inimigos,","que os dominavam.","Eles voltavam a clamar a ti,","e tu os ouvias do céu","e, na tua misericórdia, os livraste muitas vezes."]},
{v:29,l:["Tu os advertiste, para reconduzi-los à tua lei;","mas eles agiram com arrogância e não ouviram os teus mandamentos,","pecaram contra as tuas normas, que dão a vida a quem as pratica, e voltaram as costas rebeldes,","endureceram a cerviz e não quiseram ouvir."],n:"Que dão a vida a quem as pratica: citação de Levítico 18,5, que Paulo comentará (Romanos 10,5; Gálatas 3,12)."},
{v:30,l:["Tiveste paciência com eles durante muitos anos","e os advertiste pelo teu espírito,","por meio dos teus profetas; mas não quiseram ouvir;","e os entregaste nas mãos dos povos das terras."]},
{v:31,l:["Mas, na tua grande misericórdia,","não os aniquilaste","nem os abandonaste,","porque és um Deus clemente e misericordioso."]},
{v:32,l:["E agora, nosso Deus, Deus grande, forte e temível,","que guardas a aliança e a misericórdia,","não tenhas por pouca coisa toda a aflição","que caiu sobre nós, sobre os nossos reis, os nossos chefes,","os nossos sacerdotes, os nossos profetas,","os nossos pais e todo o teu povo,","desde o tempo dos reis da Assíria até hoje."],np:1},
{v:33,l:["Tu foste justo em tudo o que nos aconteceu,","porque agiste com fidelidade,","enquanto nós agimos com impiedade."]},
{v:34,l:["Os nossos reis, os nossos chefes, os nossos sacerdotes e os nossos pais","não praticaram a tua lei","nem atenderam aos teus mandamentos e aos teus testemunhos,","com que os advertias."]},
{v:35,l:["Mesmo no seu reino, no meio dos muitos bens que lhes deste,","na terra vasta e fértil","que puseste diante deles,","não te serviram nem se converteram das suas más obras."]},
{v:36,l:["Eis que hoje somos escravos;","e na terra que deste a nossos pais,","para comerem os seus frutos e os seus bens, eis que somos escravos."]},
{v:37,l:["Os seus ricos produtos são para os reis","que puseste sobre nós por causa dos nossos pecados;","eles dominam sobre os nossos corpos e sobre o nosso gado","como lhes agrada,","e estamos em grande angústia."],n:"A oração termina sem um pedido explícito: a própria confissão da miséria já é súplica."}
];

window.TEXTOS_SEED["neemias"][10] = [
{s:"O compromisso do povo"},
{v:1,t:"Por causa de tudo isto, nós firmamos um compromisso e o pomos por escrito; e os nossos chefes, os nossos levitas e os nossos sacerdotes o selam.",n:"Nas traduções que seguem a numeração grega, este versículo é 9,38, e os seguintes são numerados de 10,1 a 10,39."},
{v:2,t:"Os que selaram foram: Neemias, o governador, filho de Hacalias, e Sedecias,",np:1},
{v:3,t:"Saraías, Azarias, Jeremias,"},
{v:4,t:"Fassur, Amarias, Melquias,"},
{v:5,t:"Hatus, Sebanias, Maluc,"},
{v:6,t:"Harim, Meremot, Abdias,"},
{v:7,t:"Daniel, Gentom, Baruc,"},
{v:8,t:"Mosolam, Abias, Miamin,"},
{v:9,t:"Maazias, Belgai e Semeías: estes eram os sacerdotes."},
{v:10,t:"Os levitas: Jesua, filho de Azanias, Benui, dos filhos de Henadad, Cadmiel,",np:1},
{v:11,t:"e os seus irmãos Sebanias, Hodias, Celita, Falaías, Hanã,"},
{v:12,t:"Mica, Roob, Hasabias,"},
{v:13,t:"Zacur, Serebias, Sebanias,"},
{v:14,t:"Hodias, Bani e Beninu."},
{v:15,t:"Os chefes do povo: Farós, Faat-Moab, Elam, Zetua, Bani,",np:1},
{v:16,t:"Buni, Azgad, Bebai,"},
{v:17,t:"Adonias, Beguai, Adin,"},
{v:18,t:"Ater, Ezequias, Azur,"},
{v:19,t:"Hodias, Hasum, Besai,"},
{v:20,t:"Haref, Anatot, Nebai,"},
{v:21,t:"Megfias, Mosolam, Hezir,"},
{v:22,t:"Mesezabel, Sadoc, Jedua,"},
{v:23,t:"Feltias, Hanã, Anaías,"},
{v:24,t:"Oseias, Hananias, Hasub,"},
{v:25,t:"Aloes, Faleia, Sobec,"},
{v:26,t:"Reum, Hasabna, Maasias,"},
{v:27,t:"Aías, Hanã, Anã,"},
{v:28,t:"Maluc, Harim e Baana."},
{v:29,t:"E o resto do povo, os sacerdotes, os levitas, os porteiros, os cantores, os natineus e todos os que se tinham separado dos povos das terras para seguir a lei de Deus, as suas mulheres, os seus filhos e as suas filhas, todos os que tinham conhecimento e entendimento,",np:1},
{v:30,t:"uniram-se aos seus irmãos, os nobres, comprometendo-se com juramento a andar na lei de Deus, dada por meio de Moisés, servo de Deus, e a guardar e praticar todos os mandamentos do Senhor nosso Deus, as suas normas e os seus estatutos:"},
{v:31,t:"a não dar as nossas filhas aos povos da terra e a não tomar as filhas deles para os nossos filhos;"},
{v:32,t:"a não comprar nada, no sábado ou em dia santo, dos povos da terra que trouxessem mercadorias ou qualquer cereal para vender no dia de sábado; e a deixar a terra descansar no sétimo ano e perdoar toda dívida.",n:"O ano sabático (Êxodo 23,10-11; Deuteronômio 15,1-3)."},
{v:33,t:"Impusemo-nos também a obrigação de dar cada ano um terço de siclo para o serviço da casa do nosso Deus,",np:1,n:"Mais tarde, meio siclo (Êxodo 30,13; Mateus 17,24)."},
{v:34,t:"para os pães da proposição, para a oblação perpétua e para o holocausto perpétuo, para os sábados, as luas novas, as festas, as coisas santas e os sacrifícios pelo pecado, para fazer a expiação por Israel, e para todo o serviço da casa do nosso Deus."},
{v:35,t:"Tiramos também a sorte, entre os sacerdotes, os levitas e o povo, para a oferta da lenha, que devia ser trazida à casa do nosso Deus, por famílias, em datas fixas, cada ano, para queimar sobre o altar do Senhor nosso Deus, como está escrito na Lei;"},
{v:36,t:"e comprometemo-nos a trazer cada ano à casa do Senhor as primícias do nosso solo e as primícias de todos os frutos de todas as árvores,"},
{v:37,t:"e os primogênitos dos nossos filhos e do nosso gado, como está escrito na Lei, e os primogênitos dos nossos bois e das nossas ovelhas, para levá-los à casa do nosso Deus, aos sacerdotes que servem na casa do nosso Deus."},
{v:38,t:"Traremos aos sacerdotes, às salas da casa do nosso Deus, as primícias da nossa massa e das nossas ofertas, dos frutos de todas as árvores, do vinho novo e do azeite; e aos levitas o dízimo do nosso solo. Os próprios levitas recolherão os dízimos em todas as cidades onde trabalhamos a terra."},
{v:39,t:"Um sacerdote, filho de Aarão, estará com os levitas quando eles recolherem os dízimos; e os levitas levarão o dízimo do dízimo à casa do nosso Deus, às salas do tesouro."},
{v:40,t:"Porque às salas os filhos de Israel e os filhos de Levi trarão as ofertas do trigo, do vinho novo e do azeite; ali estão os objetos do santuário, os sacerdotes que servem, os porteiros e os cantores. E não abandonaremos a casa do nosso Deus."}
];
