// =====================================================================
// Neemias — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================

window.TEXTOS_SEED["neemias"][1] = [
{s:"A oração de Neemias"},
{v:1,t:"Palavras de Neemias, filho de Hacalias. No mês de Casleu, no vigésimo ano, estando eu na cidadela de Susa,",n:"Casleu: novembro e dezembro. O vigésimo ano de Artaxerxes I é 445 antes de Cristo (2,1). Susa era a residência de inverno dos reis persas. O livro começa com as memórias de Neemias, escritas na primeira pessoa."},
{v:2,t:"Hanani, um dos meus irmãos, chegou com alguns homens de Judá. Perguntei-lhes pelos judeus que tinham escapado, os que tinham sobrevivido ao cativeiro, e por Jerusalém."},
{v:3,t:"Eles me responderam: Os que sobreviveram ao cativeiro, lá na província, estão em grande miséria e humilhação; a muralha de Jerusalém está em ruínas, e as suas portas foram queimadas.",n:"Talvez depois da tentativa de reconstrução interrompida por ordem de Artaxerxes (Esdras 4,7-23)."},
{v:4,t:"Ao ouvir estas palavras, sentei-me e chorei; fiquei de luto durante vários dias, jejuando e orando diante do Deus do céu."},
{v:5,t:"E disse: Ah, Senhor, Deus do céu, Deus grande e temível, que guardas a aliança e a misericórdia para com os que te amam e guardam os teus mandamentos!",np:1},
{v:6,t:"Que os teus ouvidos estejam atentos e os teus olhos abertos, para ouvires a oração que o teu servo faz hoje diante de ti, dia e noite, pelos filhos de Israel, teus servos, confessando os pecados dos filhos de Israel, que cometemos contra ti. Também eu e a casa de meu pai pecamos."},
{v:7,t:"Agimos muito mal contra ti, e não guardamos os mandamentos, os estatutos e as normas que prescreveste a Moisés, teu servo."},
{v:8,t:"Lembra-te da palavra que ordenaste a Moisés, teu servo: Se fordes infiéis, eu vos dispersarei entre os povos;"},
{v:9,t:"mas, se voltardes a mim, guardardes os meus mandamentos e os puserdes em prática, ainda que os vossos dispersos estejam nos confins do céu, de lá os reunirei e os trarei ao lugar que escolhi para nele fazer habitar o meu nome.",n:"Citação livre de Deuteronômio 30,1-5 e 12,5."},
{v:10,t:"Eles são os teus servos e o teu povo, que resgataste com o teu grande poder e com a tua mão forte."},
{v:11,t:"Ah, Senhor, que os teus ouvidos estejam atentos à oração do teu servo e à oração dos teus servos, que desejam temer o teu nome! Faze que hoje o teu servo seja bem-sucedido e encontre compaixão diante deste homem. Eu era então copeiro do rei.",n:"O copeiro, que servia e provava o vinho do rei, era um homem da sua inteira confiança."}
];

window.TEXTOS_SEED["neemias"][2] = [
{s:"Neemias enviado a Jerusalém"},
{v:1,t:"No mês de Nisan, no vigésimo ano do rei Artaxerxes, estando o vinho diante dele, tomei o vinho e o servi ao rei. Nunca antes eu tinha aparecido triste diante dele.",n:"Nisan: março e abril, quatro meses depois da notícia (1,1)."},
{v:2,t:"O rei perguntou-me: Por que está triste o teu rosto, se não estás doente? Isto não é senão tristeza do coração. Tive muito medo,",n:"Mostrar tristeza diante do rei podia ser tomado como descontentamento, e até como ameaça."},
{v:3,t:"e respondi ao rei: Viva o rei para sempre! Como não estaria triste o meu rosto, se a cidade onde estão os túmulos de meus pais está em ruínas, e as suas portas foram consumidas pelo fogo?"},
{v:4,t:"O rei me disse: Que pedes? Então orei ao Deus do céu",n:"Uma oração rápida, no coração, antes de responder: a oração acompanha cada passo da ação de Neemias."},
{v:5,t:"e respondi ao rei: Se parecer bem ao rei, e se o teu servo te for agradável, envia-me a Judá, à cidade dos túmulos de meus pais, para reconstruí-la."},
{v:6,t:"O rei, que tinha a rainha sentada ao seu lado, perguntou-me: Quanto tempo durará a tua viagem, e quando voltarás? Pareceu bem ao rei enviar-me, e eu lhe indiquei um prazo.",n:"Neemias ficará em Jerusalém doze anos (5,14; 13,6)."},
{v:7,t:"E disse ao rei: Se parecer bem ao rei, deem-me cartas para os governadores da Transeufratênia, para que me deixem passar até chegar a Judá;"},
{v:8,t:"e uma carta para Asaf, guarda do parque real, para que me dê madeira para vigar as portas da cidadela do templo, a muralha da cidade e a casa onde vou morar. E o rei concedeu-me as cartas, porque a mão bondosa do meu Deus estava sobre mim."},
{v:9,t:"Fui ter com os governadores da Transeufratênia e entreguei-lhes as cartas do rei. O rei tinha mandado comigo oficiais do exército e cavaleiros.",np:1},
{v:10,t:"Quando Sanabalat, o horonita, e Tobias, o servo amonita, souberam disso, ficaram muito desgostosos de que tivesse vindo alguém para procurar o bem dos filhos de Israel.",n:"Sanabalat, governador de Samaria, é conhecido também por papiros judaicos de Elefantina, no Egito. Tobias governava talvez a região de Amon, a leste do Jordão; servo seria o título de um funcionário do rei."},
{s:"Neemias examina as muralhas"},
{v:11,t:"Cheguei a Jerusalém e fiquei ali três dias.",np:1},
{v:12,t:"Depois levantei-me de noite, com alguns homens, sem dizer a ninguém o que o meu Deus me tinha posto no coração fazer por Jerusalém; e não levava comigo outro animal senão aquele em que eu montava."},
{v:13,t:"Saí de noite pela porta do Vale, na direção da fonte do Dragão e da porta do Monturo, e examinei a muralha de Jerusalém, que estava em ruínas, e as suas portas, consumidas pelo fogo."},
{v:14,t:"Passei à porta da Fonte e ao tanque do Rei, e não havia lugar por onde o animal em que eu montava pudesse passar."},
{v:15,t:"Subi de noite pela torrente e examinei a muralha; depois voltei pela porta do Vale e regressei.",n:"Neemias contorna o sul e o leste da cidade, pelo vale do Cedron."},
{v:16,t:"Os magistrados não sabiam aonde eu tinha ido nem o que tinha feito; até então nada tinha dito aos judeus, nem aos sacerdotes, nem aos nobres, nem aos magistrados, nem aos outros que iam fazer a obra."},
{v:17,t:"Então lhes disse: Vós vedes a miséria em que estamos: Jerusalém está em ruínas, e as suas portas foram consumidas pelo fogo. Vinde, reconstruamos a muralha de Jerusalém, e não sejamos mais objeto de vergonha!",np:1},
{v:18,t:"E contei-lhes como a mão bondosa do meu Deus estava sobre mim, e as palavras que o rei me tinha dito. Eles disseram: Levantemo-nos e construamos! E encheram-se de coragem para a boa obra."},
{v:19,t:"Quando Sanabalat, o horonita, Tobias, o servo amonita, e Gosem, o árabe, souberam disso, zombaram de nós e nos desprezaram, dizendo: Que é isso que estais fazendo? Acaso vos revoltais contra o rei?",n:"Gosem, o árabe, era chefe das tribos árabes do sul da Palestina."},
{v:20,t:"Eu lhes respondi: O próprio Deus do céu nos fará prosperar; nós, os seus servos, vamos levantar-nos e construir. Mas vós não tendes parte, nem direito, nem memória em Jerusalém."}
];

window.TEXTOS_SEED["neemias"][3] = [
{s:"A reconstrução das muralhas"},
{v:1,t:"O sumo sacerdote Eliasib levantou-se com os seus irmãos, os sacerdotes, e construíram a porta das Ovelhas; cobriram-na de vigas e colocaram as suas folhas, e continuaram até a torre dos Cem e a torre de Hananeel.",n:"A porta das Ovelhas ficava ao norte do templo, perto do tanque de Betesda (João 5,2). A descrição dá a volta às muralhas: norte, oeste, sul e leste."},
{v:2,t:"Ao lado deles construíram os homens de Jericó; e ao lado deles construiu Zacur, filho de Imri."},
{v:3,t:"Os filhos de Senaá construíram a porta dos Peixes; cobriram-na de vigas e colocaram as suas folhas, as fechaduras e as trancas.",np:1},
{v:4,t:"Ao lado deles trabalhou nos reparos Meremot, filho de Urias, filho de Acos; ao lado dele trabalhou Mosolam, filho de Baraquias, filho de Mesezabel; ao lado dele trabalhou Sadoc, filho de Baana;"},
{v:5,t:"ao lado dele trabalharam os de Técua; mas os seus nobres não quiseram dobrar a nuca para o serviço do seu Senhor."},
{v:6,t:"Joiada, filho de Faseia, e Mosolam, filho de Besodias, restauraram a porta Velha; cobriram-na de vigas e colocaram as suas folhas, as fechaduras e as trancas.",np:1},
{v:7,t:"Ao lado deles trabalharam Melcias, de Gabaon, e Jadon, de Meronot, homens de Gabaon e de Masfa, que dependiam da sede do governador da Transeufratênia;"},
{v:8,t:"ao lado deles trabalhou Oziel, filho de Haraías, dos ourives; e ao lado dele trabalhou Hananias, dos perfumistas; e restauraram Jerusalém até a muralha Larga."},
{v:9,t:"Ao lado deles trabalhou Rafaías, filho de Hur, chefe da metade do distrito de Jerusalém;"},
{v:10,t:"ao lado dele trabalhou Jedaías, filho de Haromaf, em frente da sua casa; e ao lado dele trabalhou Hatus, filho de Hasabnias."},
{v:11,t:"Melquias, filho de Harim, e Hasub, filho de Faat-Moab, restauraram outro trecho, até a torre dos Fornos."},
{v:12,t:"Ao lado deles trabalhou Selum, filho de Aloes, chefe da outra metade do distrito de Jerusalém, ele e as suas filhas.",n:"Também as mulheres trabalham na muralha."},
{v:13,t:"Hanun e os habitantes de Zanoa restauraram a porta do Vale; construíram-na, colocaram as suas folhas, as fechaduras e as trancas, e restauraram mil côvados de muralha, até a porta do Monturo.",np:1},
{v:14,t:"Melquias, filho de Recab, chefe do distrito de Bet-Carem, restaurou a porta do Monturo; construiu-a e colocou as suas folhas, as fechaduras e as trancas."},
{v:15,t:"Selum, filho de Col-Hoze, chefe do distrito de Masfa, restaurou a porta da Fonte; construiu-a, cobriu-a e colocou as suas folhas, as fechaduras e as trancas; e restaurou também a muralha do tanque de Siloé, junto ao jardim do rei, até os degraus que descem da Cidade de Davi."},
{v:16,t:"Depois dele trabalhou Neemias, filho de Azboc, chefe da metade do distrito de Bet-Sur, até em frente dos túmulos de Davi, até o tanque artificial e até a casa dos Valentes.",np:1},
{v:17,t:"Depois dele trabalharam os levitas: Reum, filho de Bani; ao lado dele trabalhou Hasabias, chefe da metade do distrito de Ceila, pelo seu distrito;"},
{v:18,t:"depois dele trabalharam os seus irmãos: Bavai, filho de Henadad, chefe da outra metade do distrito de Ceila."},
{v:19,t:"Ao lado dele, Ezer, filho de Jesua, chefe de Masfa, restaurou outro trecho, em frente da subida do arsenal, no ângulo."},
{v:20,t:"Depois dele, Baruc, filho de Zacai, restaurou outro trecho, desde o ângulo até a porta da casa do sumo sacerdote Eliasib."},
{v:21,t:"Depois dele, Meremot, filho de Urias, filho de Acos, restaurou outro trecho, desde a porta da casa de Eliasib até o fim da casa de Eliasib."},
{v:22,t:"Depois dele trabalharam os sacerdotes, homens da planície.",n:"A planície: o vale do Jordão, em volta de Jericó."},
{v:23,t:"Depois deles, Benjamim e Hasub trabalharam em frente da sua casa; depois deles, Azarias, filho de Maasias, filho de Ananias, trabalhou junto da sua casa."},
{v:24,t:"Depois dele, Benui, filho de Henadad, restaurou outro trecho, desde a casa de Azarias até o ângulo e a esquina."},
{v:25,t:"Falal, filho de Ozi, trabalhou em frente do ângulo e da torre que se eleva do palácio superior do rei, junto ao pátio da prisão; depois dele, Fadaías, filho de Farós, trabalhou"},
{v:26,t:"até em frente da porta das Águas, a oriente, e da torre saliente."},
{v:27,t:"Depois dele, os de Técua restauraram outro trecho, desde em frente da grande torre saliente até a muralha do templo."},
{v:28,t:"A partir da porta dos Cavalos, os sacerdotes trabalharam, cada um em frente da sua casa.",np:1},
{v:29,t:"Depois deles, Sadoc, filho de Emer, trabalhou em frente da sua casa; e depois dele trabalhou Semeías, filho de Secenias, guarda da porta Oriental."},
{v:30,t:"Depois dele, Hananias, filho de Selemias, e Hanun, sexto filho de Selef, restauraram outro trecho. Depois deles, Mosolam, filho de Baraquias, trabalhou em frente do seu quarto."},
{v:31,t:"Depois dele, Melquias, dos ourives, trabalhou até a casa dos natineus e dos mercadores, em frente da porta da Inspeção, e até a sala alta do ângulo."},
{v:32,t:"E entre a sala alta do ângulo e a porta das Ovelhas trabalharam os ourives e os mercadores."},
{s:"A zombaria de Sanabalat e de Tobias"},
{v:33,t:"Quando Sanabalat soube que estávamos reconstruindo a muralha, irou-se, ficou muito indignado e zombou dos judeus,",np:1,n:"Nas traduções que seguem a numeração grega, os versículos 33 a 38 são 4,1-6, e o capítulo 4 começa depois deles no versículo 7."},
{v:34,t:"e disse diante dos seus irmãos e dos notáveis de Samaria: Que fazem estes judeus miseráveis? Vão deixá-los fazer? Vão oferecer sacrifícios? Vão acabar num só dia? Farão reviver as pedras dos montões de entulho, que foram queimadas?"},
{v:35,t:"E Tobias, o amonita, que estava ao lado dele, disse: Deixai-os construir! Se uma raposa subir, derrubará a muralha de pedra deles."},
{v:36,t:"Ouve, nosso Deus, como somos desprezados! Faze recair o seu insulto sobre a cabeça deles e entrega-os ao desprezo numa terra de cativeiro!",n:"Nota do tradutor: Neemias responde ao insulto com uma prece de vingança, como nos salmos imprecatórios, e o texto não a suaviza. Mas a vingança é entregue a Deus, e não praticada pelas próprias mãos (Romanos 12,19); e Jesus ensinará a orar pelos que nos perseguem (Mateus 5,44)."},
{v:37,t:"Não cubras a sua iniquidade, e que o seu pecado não se apague diante de ti, porque ofenderam os que constroem."},
{v:38,t:"Assim reconstruímos a muralha, e toda a muralha ficou completa até a metade da altura; e o povo tinha ânimo para trabalhar."}
];

window.TEXTOS_SEED["neemias"][4] = [
{s:"A espada numa mão"},
{v:1,t:"Quando Sanabalat, Tobias, os árabes, os amonitas e os de Azoto souberam que a restauração das muralhas de Jerusalém progredia e que as brechas começavam a fechar-se, irritaram-se muito;"},
{v:2,t:"e conspiraram todos juntos para vir atacar Jerusalém e semear a confusão."},
{v:3,t:"Mas nós oramos ao nosso Deus e pusemos guardas contra eles, dia e noite."},
{v:4,t:"E Judá dizia: As forças dos carregadores estão falhando, e o entulho é muito; não conseguiremos construir a muralha.",n:"Talvez um canto de trabalho, em ritmo de lamentação, que exprime o desânimo."},
{v:5,t:"E os nossos inimigos diziam: Que não saibam nem vejam nada, até que caiamos no meio deles, os matemos e façamos parar a obra."},
{v:6,t:"Quando os judeus que moravam perto deles vieram dizer-nos dez vezes, de todos os lugares de onde vinham até nós, que eles iam atacar,",np:1},
{v:7,t:"pusemo-nos nas partes mais baixas, atrás da muralha, nos lugares descobertos, e dispus o povo por famílias, com as suas espadas, as suas lanças e os seus arcos."},
{v:8,t:"Depois de examinar tudo, levantei-me e disse aos nobres, aos magistrados e ao resto do povo: Não tenhais medo deles! Lembrai-vos do Senhor, grande e temível, e combatei pelos vossos irmãos, pelos vossos filhos e pelas vossas filhas, pelas vossas mulheres e pelas vossas casas!"},
{v:9,t:"Quando os nossos inimigos souberam que estávamos avisados e que Deus tinha frustrado o seu plano, voltamos todos à muralha, cada um ao seu trabalho.",np:1},
{v:10,t:"Desde aquele dia, metade dos meus homens trabalhava na obra, e a outra metade segurava as lanças, os escudos, os arcos e as couraças; e os chefes estavam por trás de toda a casa de Judá."},
{v:11,t:"Os que construíam a muralha e os que carregavam os fardos trabalhavam com uma mão e com a outra seguravam a arma."},
{v:12,t:"Cada um dos construtores tinha a espada cingida à cintura, e assim construíam; e o que tocava a corneta estava junto de mim.",n:"Construir com a espada numa mão tornou-se imagem da vigilância de quem trabalha na obra de Deus."},
{v:13,t:"Eu disse aos nobres, aos magistrados e ao resto do povo: A obra é grande e extensa, e nós estamos espalhados pela muralha, longe uns dos outros."},
{v:14,t:"No lugar onde ouvirdes o som da corneta, ali vos reunireis junto de nós. O nosso Deus combaterá por nós."},
{v:15,t:"Assim trabalhávamos na obra, e metade de nós segurava as lanças, desde o romper da aurora até o aparecer das estrelas.",np:1},
{v:16,t:"Naquele tempo disse também ao povo: Que cada um passe a noite em Jerusalém com o seu servo: de noite faremos a guarda, e de dia trabalharemos."},
{v:17,t:"Nem eu, nem os meus irmãos, nem os meus servos, nem os homens da guarda que me seguiam tirávamos a roupa; cada um tinha a arma na mão direita."}
];

window.TEXTOS_SEED["neemias"][5] = [
{s:"Neemias defende os pobres"},
{v:1,t:"Levantou-se um grande clamor do povo e das suas mulheres contra os seus irmãos judeus."},
{v:2,t:"Uns diziam: Penhoramos os nossos filhos e as nossas filhas para conseguir trigo, para comermos e vivermos!"},
{v:3,t:"Outros diziam: Hipotecamos os nossos campos, as nossas vinhas e as nossas casas, para conseguir trigo durante a fome!"},
{v:4,t:"E outros diziam: Tomamos dinheiro emprestado, dando em garantia os nossos campos e as nossas vinhas, para pagar o tributo do rei."},
{v:5,t:"E, no entanto, a nossa carne é como a carne dos nossos irmãos, e os nossos filhos são como os filhos deles; e eis que temos de sujeitar à escravidão os nossos filhos e as nossas filhas, e algumas das nossas filhas já são escravas, sem que possamos resgatá-las, porque os nossos campos e as nossas vinhas pertencem a outros.",n:"A Lei proibia emprestar a juros a um irmão israelita e limitava a servidão por dívidas (Êxodo 22,24; Levítico 25,35-43; Deuteronômio 23,20-21)."},
{v:6,t:"Fiquei muito irritado quando ouvi o seu clamor e estas palavras.",np:1},
{v:7,t:"Depois de refletir comigo mesmo, repreendi os nobres e os magistrados, e disse-lhes: Emprestais a juros aos vossos irmãos! E convoquei contra eles uma grande assembleia."},
{v:8,t:"E disse-lhes: Nós, segundo as nossas possibilidades, resgatamos os nossos irmãos judeus que tinham sido vendidos às nações; e vós vendeis os vossos irmãos, para que depois sejam vendidos a nós! Eles se calaram e não souberam o que responder."},
{v:9,t:"Eu disse ainda: Não está bem o que fazeis. Não deveríeis andar no temor do nosso Deus, para não sermos insultados pelas nações, nossas inimigas?"},
{v:10,t:"Também eu, os meus irmãos e os meus servos emprestamos a muitos dinheiro e trigo. Deixemos de cobrar esses juros!"},
{v:11,t:"Devolvei-lhes hoje mesmo os seus campos, as suas vinhas, os seus olivais e as suas casas, e o juro de um por cento do dinheiro, do trigo, do vinho e do azeite que costumais exigir deles.",n:"Um por cento ao mês, talvez: doze por cento ao ano."},
{v:12,t:"Eles responderam: Devolveremos, e não lhes exigiremos nada; faremos como dizes. Então chamei os sacerdotes e os fiz jurar que fariam o que tinham prometido."},
{v:13,t:"Depois sacudi a dobra do meu manto e disse: Assim sacuda Deus da sua casa e dos seus bens todo homem que não cumprir esta palavra; assim seja ele sacudido e fique vazio! E toda a assembleia respondeu: Amém! E louvaram o Senhor. E o povo fez como tinha prometido.",n:"Um gesto profético: como se sacode o manto, Deus sacudirá o perjuro. Jesus mandará os discípulos sacudir o pó dos pés (Mateus 10,14)."},
{s:"O desinteresse de Neemias"},
{v:14,t:"Desde o dia em que o rei me nomeou governador na terra de Judá, do vigésimo ao trigésimo segundo ano do rei Artaxerxes, durante doze anos, nem eu nem os meus irmãos comemos a provisão devida ao governador.",np:1},
{v:15,t:"Os governadores anteriores, que me precederam, oprimiam o povo, exigindo dele cada dia quarenta siclos de prata pelo seu sustento; e até os seus servos tiranizavam o povo. Mas eu não fiz assim, por temor de Deus."},
{v:16,t:"Pelo contrário, dediquei-me ao trabalho da muralha, e não comprei nenhum campo; e todos os meus servos estavam reunidos ali para a obra."},
{v:17,t:"À minha mesa comiam cento e cinquenta homens, judeus e magistrados, além dos que vinham a nós das nações vizinhas."},
{v:18,t:"Preparava-se para mim, cada dia, um boi, seis ovelhas escolhidas e aves; e de dez em dez dias, vinho de toda espécie em abundância. Apesar disso, não exigi a provisão devida ao governador, porque o trabalho pesava muito sobre este povo."},
{v:19,t:"Lembra-te de mim, meu Deus, para o meu bem, por tudo o que fiz por este povo.",n:"Refrão das memórias de Neemias (13,14.22.31): ele confia a Deus a lembrança das suas obras."}
];

window.TEXTOS_SEED["neemias"][6] = [
{s:"As ciladas contra Neemias"},
{v:1,t:"Quando Sanabalat, Tobias, Gosem, o árabe, e os nossos outros inimigos souberam que eu tinha reconstruído a muralha e que não restava nela nenhuma brecha — embora até então eu não tivesse colocado as folhas nas portas —,"},
{v:2,t:"Sanabalat e Gosem mandaram dizer-me: Vem, e encontremo-nos em Cefirim, na planície de Ono. Mas eles tramavam fazer-me mal."},
{v:3,t:"Enviei-lhes mensageiros para dizer: Estou fazendo uma grande obra e não posso descer. Por que haveria a obra de parar, enquanto eu a deixo para descer até vós?"},
{v:4,t:"Mandaram-me a mesma mensagem quatro vezes, e eu lhes dei a mesma resposta."},
{v:5,t:"Então Sanabalat mandou-me pela quinta vez o seu servo, com a mesma mensagem, trazendo na mão uma carta aberta, na qual estava escrito:",np:1,n:"Uma carta aberta, para que o seu conteúdo se espalhasse."},
{v:6,t:"Corre entre as nações, e Gosem o confirma, que tu e os judeus pensais revoltar-vos, e que é por isso que reconstróis a muralha; e, segundo estes rumores, queres tornar-te rei deles;"},
{v:7,t:"e até puseste profetas para proclamarem a teu respeito em Jerusalém: Há um rei em Judá! Ora, estes rumores vão chegar ao rei. Vem, pois, e aconselhemo-nos juntos."},
{v:8,t:"Mandei-lhe responder: Nada disso que dizes aconteceu; és tu que o inventas no teu coração."},
{v:9,t:"Porque todos eles queriam amedrontar-nos, pensando: As suas mãos se cansarão da obra, e ela não se fará. Mas eu fortaleci ainda mais as minhas mãos."},
{v:10,t:"Fui à casa de Semeías, filho de Dalaías, filho de Meetabel, que estava impedido de sair. Ele me disse: Encontremo-nos na casa de Deus, dentro do santuário, e fechemos as portas do templo, porque virão matar-te; é de noite que virão matar-te.",np:1,n:"Semeías, fingindo-se profeta, queria levar Neemias, que não era sacerdote, a esconder-se no santuário: seria sacrilégio e covardia, e o desacreditaria diante do povo."},
{v:11,t:"Respondi: Um homem como eu fugiria? E quem, sendo como eu, poderia entrar no templo e continuar vivo? Não entrarei.",n:"Só os sacerdotes podiam entrar no santuário (Números 18,7)."},
{v:12,t:"E compreendi que não era Deus que o tinha enviado, mas que ele pronunciara aquela profecia contra mim porque Tobias e Sanabalat o tinham subornado."},
{v:13,t:"Tinha sido pago para que eu tivesse medo, agisse assim e pecasse, e eles tivessem um motivo para me difamar."},
{v:14,t:"Lembra-te, meu Deus, de Tobias e de Sanabalat, segundo estas suas obras, e também da profetisa Noadias e dos outros profetas que procuravam amedrontar-me!"},
{s:"A muralha terminada"},
{v:15,t:"A muralha foi terminada no vigésimo quinto dia do mês de Elul, em cinquenta e dois dias.",np:1,n:"Elul: agosto e setembro. Cinquenta e dois dias, graças ao entusiasmo do povo e às partes da antiga muralha que ainda estavam de pé."},
{v:16,t:"Quando todos os nossos inimigos souberam disso, e todas as nações vizinhas o viram, ficaram muito abatidos e reconheceram que esta obra tinha sido feita pelo nosso Deus."},
{v:17,t:"Naqueles dias, também muitos nobres de Judá mandavam cartas a Tobias, e as cartas de Tobias chegavam a eles."},
{v:18,t:"Porque muitos em Judá estavam ligados a ele por juramento, pois ele era genro de Secenias, filho de Area, e seu filho Joanã tinha casado com a filha de Mosolam, filho de Baraquias."},
{v:19,t:"Até falavam bem dele diante de mim e lhe contavam as minhas palavras; e Tobias mandava cartas para me amedrontar."}
];

window.TEXTOS_SEED["neemias"][7] = [
{s:"A guarda de Jerusalém"},
{v:1,t:"Quando a muralha foi reconstruída e coloquei as folhas das portas, e foram designados os porteiros, os cantores e os levitas,"},
{v:2,t:"confiei o governo de Jerusalém a meu irmão Hanani e a Hananias, comandante da cidadela, porque era um homem fiel e temente a Deus mais do que muitos outros;"},
{v:3,t:"e disse-lhes: As portas de Jerusalém não se abrirão antes que o sol aqueça; e, enquanto os guardas ainda estiverem de serviço, fechem-se as portas e passem-se as trancas. Ponham-se guardas dentre os habitantes de Jerusalém, cada um no seu posto, cada um em frente da sua casa."},
{v:4,t:"A cidade era espaçosa e grande, mas havia pouca gente dentro dela, e as casas não tinham sido reconstruídas.",np:1,n:"Neemias resolverá o problema fazendo vir para Jerusalém um décimo da população (11,1-2)."},
{s:"A lista dos que voltaram do exílio"},
{v:5,t:"Então o meu Deus me pôs no coração reunir os nobres, os magistrados e o povo, para fazer o seu recenseamento; e encontrei o registro genealógico dos que tinham voltado primeiro, e encontrei escrito nele:",np:1,n:"A lista que segue é a de Esdras 2, com pequenas diferenças nos nomes e nos números."},
{v:6,t:"Estes são os filhos da província que voltaram do cativeiro, dentre os exilados que Nabucodonosor, rei da Babilônia, tinha deportado, e que voltaram para Jerusalém e para Judá, cada um para a sua cidade."},
{v:7,t:"Vieram com Zorobabel, Josué, Neemias, Azarias, Raamias, Naamani, Mardoqueu, Belsã, Mesferet, Beguai, Naum e Baana. Este é o número dos homens do povo de Israel:"},
{v:8,t:"os filhos de Farós, dois mil cento e setenta e dois;",np:1},
{v:9,t:"os filhos de Safatias, trezentos e setenta e dois;"},
{v:10,t:"os filhos de Area, seiscentos e cinquenta e dois;"},
{v:11,t:"os filhos de Faat-Moab, isto é, os filhos de Jesua e de Joab, dois mil oitocentos e dezoito;"},
{v:12,t:"os filhos de Elam, mil duzentos e cinquenta e quatro;"},
{v:13,t:"os filhos de Zetua, oitocentos e quarenta e cinco;"},
{v:14,t:"os filhos de Zacai, setecentos e sessenta;"},
{v:15,t:"os filhos de Benui, seiscentos e quarenta e oito;"},
{v:16,t:"os filhos de Bebai, seiscentos e vinte e oito;"},
{v:17,t:"os filhos de Azgad, dois mil trezentos e vinte e dois;"},
{v:18,t:"os filhos de Adonicam, seiscentos e sessenta e sete;"},
{v:19,t:"os filhos de Beguai, dois mil e sessenta e sete;"},
{v:20,t:"os filhos de Adin, seiscentos e cinquenta e cinco;"},
{v:21,t:"os filhos de Ater, da família de Ezequias, noventa e oito;"},
{v:22,t:"os filhos de Hasum, trezentos e vinte e oito;"},
{v:23,t:"os filhos de Besai, trezentos e vinte e quatro;"},
{v:24,t:"os filhos de Haref, cento e doze;"},
{v:25,t:"os filhos de Gabaon, noventa e cinco;"},
{v:26,t:"os homens de Belém e de Netofa, cento e oitenta e oito;"},
{v:27,t:"os homens de Anatot, cento e vinte e oito;"},
{v:28,t:"os homens de Bet-Azmavet, quarenta e dois;"},
{v:29,t:"os homens de Cariat-Iarim, de Cafira e de Berot, setecentos e quarenta e três;"},
{v:30,t:"os homens de Ramá e de Gaba, seiscentos e vinte e um;"},
{v:31,t:"os homens de Macmas, cento e vinte e dois;"},
{v:32,t:"os homens de Betel e de Hai, cento e vinte e três;"},
{v:33,t:"os homens do outro Nebo, cinquenta e dois;"},
{v:34,t:"os homens do outro Elam, mil duzentos e cinquenta e quatro;"},
{v:35,t:"os filhos de Harim, trezentos e vinte;"},
{v:36,t:"os filhos de Jericó, trezentos e quarenta e cinco;"},
{v:37,t:"os filhos de Lod, de Hadid e de Ono, setecentos e vinte e um;"},
{v:38,t:"os filhos de Senaá, três mil novecentos e trinta."},
{v:39,t:"Os sacerdotes: os filhos de Jedaías, da casa de Jesua, novecentos e setenta e três;",np:1},
{v:40,t:"os filhos de Emer, mil e cinquenta e dois;"},
{v:41,t:"os filhos de Fassur, mil duzentos e quarenta e sete;"},
{v:42,t:"os filhos de Harim, mil e dezessete."},
{v:43,t:"Os levitas: os filhos de Jesua, isto é, os filhos de Cadmiel, de Benui e de Odovias, setenta e quatro.",np:1},
{v:44,t:"Os cantores: os filhos de Asaf, cento e quarenta e oito."},
{v:45,t:"Os porteiros: os filhos de Selum, os filhos de Ater, os filhos de Telmon, os filhos de Acub, os filhos de Hatita, os filhos de Sobai: cento e trinta e oito."},
{v:46,t:"Os natineus: os filhos de Siá, os filhos de Hasufa, os filhos de Tabaot,",np:1},
{v:47,t:"os filhos de Queros, os filhos de Siaa, os filhos de Fadon,"},
{v:48,t:"os filhos de Lebana, os filhos de Hagaba, os filhos de Selmai,"},
{v:49,t:"os filhos de Hanã, os filhos de Gidel, os filhos de Gaer,"},
{v:50,t:"os filhos de Raaías, os filhos de Rasin, os filhos de Necoda,"},
{v:51,t:"os filhos de Gazam, os filhos de Oza, os filhos de Faseia,"},
{v:52,t:"os filhos de Besai, os filhos dos meunitas, os filhos dos nefuseus,"},
{v:53,t:"os filhos de Bacbuc, os filhos de Hacufa, os filhos de Harur,"},
{v:54,t:"os filhos de Baslut, os filhos de Maida, os filhos de Harsa,"},
{v:55,t:"os filhos de Barcos, os filhos de Sísara, os filhos de Tema,"},
{v:56,t:"os filhos de Nasias, os filhos de Hatifa."},
{v:57,t:"Os filhos dos servos de Salomão: os filhos de Sotai, os filhos de Soferet, os filhos de Feruda,",np:1},
{v:58,t:"os filhos de Jaala, os filhos de Darcon, os filhos de Gidel,"},
{v:59,t:"os filhos de Safatias, os filhos de Hatil, os filhos de Foqueret-Hasebaim, os filhos de Amon."},
{v:60,t:"Ao todo, os natineus e os filhos dos servos de Salomão eram trezentos e noventa e dois."},
{v:61,t:"Estes são os que vieram de Tel-Mela, de Tel-Harsa, de Querub, de Adon e de Emer, e não puderam provar se a sua família e a sua descendência eram de Israel:",np:1},
{v:62,t:"os filhos de Dalaías, os filhos de Tobias, os filhos de Necoda, seiscentos e quarenta e dois."},
{v:63,t:"E, entre os sacerdotes, os filhos de Hobias, os filhos de Acos e os filhos de Berzelai, que tinha tomado por mulher uma das filhas de Berzelai, o galaadita, e foi chamado pelo nome deles."},
{v:64,t:"Estes procuraram o seu registro nas genealogias, mas não o encontraram, e foram excluídos do sacerdócio como impuros."},
{v:65,t:"O governador disse-lhes que não comessem das coisas santíssimas enquanto não se apresentasse um sacerdote para consultar os Urim e os Tumim."},
{v:66,t:"Toda a assembleia era de quarenta e dois mil trezentos e sessenta,",np:1},
{v:67,t:"sem contar os seus servos e servas, que eram sete mil trezentos e trinta e sete; tinham também duzentos e quarenta e cinco cantores e cantoras."},
{v:68,t:"Tinham setecentos e trinta e seis cavalos, duzentas e quarenta e cinco mulas,"},
{v:69,t:"quatrocentos e trinta e cinco camelos e seis mil setecentos e vinte jumentos."},
{v:70,t:"Alguns chefes de famílias fizeram doações para a obra. O governador deu ao tesouro mil dracmas de ouro, cinquenta bacias e quinhentas e trinta túnicas sacerdotais.",np:1},
{v:71,t:"E alguns chefes de famílias deram ao tesouro da obra vinte mil dracmas de ouro e duas mil e duzentas minas de prata."},
{v:72,t:"O que o resto do povo deu foi vinte mil dracmas de ouro, duas mil minas de prata e sessenta e sete túnicas sacerdotais. Os sacerdotes e os levitas habitaram ali; os porteiros, os cantores, uma parte do povo, os natineus e todo o Israel habitaram nas suas cidades. Chegou o sétimo mês, e os filhos de Israel estavam nas suas cidades.",n:"A última frase introduz a leitura da Lei (capítulo 8), como em Esdras 3,1."}
];
