// =====================================================================
// Números — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["numeros"][1] = [
{s:"O recenseamento ordenado no Sinai"},
{v:1,t:"O Senhor falou a Moisés no deserto do Sinai, na tenda do encontro, no primeiro dia do segundo mês, no segundo ano depois da saída da terra do Egito, dizendo:",n:"O título hebraico do livro é Bemidbar, no deserto, tomado desta primeira frase; Números vem do grego e do latim, pelos dois recenseamentos que o livro narra."},
{v:2,t:"Fazei o recenseamento de toda a assembleia dos filhos de Israel, segundo as suas famílias e as casas de seus pais, contando os nomes de todo varão, um por um,"},
{v:3,t:"dos vinte anos para cima, todos os que em Israel podem sair para a guerra; tu e Aarão os contareis segundo os seus grupos."},
{v:4,t:"Convosco estará um homem de cada tribo, o chefe da casa de seus pais."},
{s:"Os chefes de cada tribo"},
{v:5,t:"Estes são os nomes dos homens que estarão convosco: de Rúben, Elisur, filho de Sedeur;"},
{v:6,t:"de Simeão, Salamiel, filho de Surisadai;"},
{v:7,t:"de Judá, Naasson, filho de Aminadab;"},
{v:8,t:"de Issacar, Natanael, filho de Suar;"},
{v:9,t:"de Zabulon, Eliab, filho de Helon;"},
{v:10,t:"dos filhos de José: de Efraim, Elisama, filho de Amiud; de Manassés, Gamaliel, filho de Fadassur;"},
{v:11,t:"de Benjamim, Abidan, filho de Gedeon;"},
{v:12,t:"de Dã, Aiezer, filho de Amisadai;"},
{v:13,t:"de Aser, Fegiel, filho de Ocran;"},
{v:14,t:"de Gad, Eliasaf, filho de Duel;"},
{v:15,t:"de Neftali, Aíra, filho de Enan."},
{v:16,t:"Estes eram os chamados da assembleia, príncipes das tribos de seus pais, chefes dos milhares de Israel."},
{s:"O recenseamento executado"},
{v:17,t:"Moisés e Aarão tomaram esses homens designados pelos seus nomes"},
{v:18,t:"e reuniram toda a assembleia no primeiro dia do segundo mês. Foram registrados por famílias, segundo as casas de seus pais, contando os nomes, dos vinte anos para cima, um por um,"},
{v:19,t:"como o Senhor ordenara a Moisés. E os recenseou no deserto do Sinai."},
{s:"Os recenseados, tribo por tribo"},
{v:20,t:"Dos filhos de Rúben, primogênito de Israel: as suas gerações por famílias e casas de seus pais, contados os nomes um por um, todo varão dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:21,t:"os recenseados da tribo de Rúben foram quarenta e seis mil e quinhentos."},
{v:22,t:"Dos filhos de Simeão: as suas gerações por famílias e casas de seus pais, os recenseados, contados os nomes um por um, todo varão dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:23,t:"os recenseados da tribo de Simeão foram cinquenta e nove mil e trezentos."},
{v:24,t:"Dos filhos de Gad: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:25,t:"os recenseados da tribo de Gad foram quarenta e cinco mil, seiscentos e cinquenta."},
{v:26,t:"Dos filhos de Judá: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:27,t:"os recenseados da tribo de Judá foram setenta e quatro mil e seiscentos."},
{v:28,t:"Dos filhos de Issacar: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:29,t:"os recenseados da tribo de Issacar foram cinquenta e quatro mil e quatrocentos."},
{v:30,t:"Dos filhos de Zabulon: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:31,t:"os recenseados da tribo de Zabulon foram cinquenta e sete mil e quatrocentos."},
{v:32,t:"Dos filhos de José, dos filhos de Efraim: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:33,t:"os recenseados da tribo de Efraim foram quarenta mil e quinhentos."},
{v:34,t:"Dos filhos de Manassés: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:35,t:"os recenseados da tribo de Manassés foram trinta e dois mil e duzentos."},
{v:36,t:"Dos filhos de Benjamim: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:37,t:"os recenseados da tribo de Benjamim foram trinta e cinco mil e quatrocentos."},
{v:38,t:"Dos filhos de Dã: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:39,t:"os recenseados da tribo de Dã foram sessenta e dois mil e setecentos."},
{v:40,t:"Dos filhos de Aser: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:41,t:"os recenseados da tribo de Aser foram quarenta e um mil e quinhentos."},
{v:42,t:"Dos filhos de Neftali: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:43,t:"os recenseados da tribo de Neftali foram cinquenta e três mil e quatrocentos."},
{s:"A soma de todos os recenseados"},
{v:44,t:"Estes são os que Moisés e Aarão recensearam, com os doze príncipes de Israel, um por cada casa paterna."},
{v:45,t:"Todos os recenseados dos filhos de Israel, segundo as casas de seus pais, dos vinte anos para cima, todos os que em Israel podiam sair para a guerra,"},
{v:46,t:"todos os recenseados foram seiscentos e três mil, quinhentos e cinquenta.",n:"O número, muito elevado para um grupo em marcha pelo deserto, é discutido desde a antiguidade: a palavra elef, mil, designa também o clã ou o contingente que ele fornecia, o que permitiria uma leitura bem menor. Conservo a tradução literal, que é a da tradição."},
{s:"Os levitas postos à parte"},
{v:47,t:"Mas os levitas, segundo a tribo de seus pais, não foram recenseados entre eles."},
{v:48,t:"O Senhor falou a Moisés, dizendo:"},
{v:49,t:"Não recensearás a tribo de Levi nem contarás os seus filhos entre os filhos de Israel;"},
{v:50,t:"mas confia aos levitas a Morada do testemunho, todos os seus utensílios e tudo o que pertence a ela. Eles levarão a Morada e todos os seus utensílios, prestarão nela o serviço e acamparão ao redor dela.",np:1,n:"Morada traduz mishkan, a tenda santa como lugar em que o Senhor habita no meio do povo; testemunho, edut, são as tábuas da Lei guardadas na arca."},
{v:51,t:"Quando a Morada tiver de partir, os levitas a desmontarão; quando tiver de acampar, os levitas a levantarão; o estranho que se aproximar será morto."},
{v:52,t:"Os filhos de Israel acamparão cada um no seu acampamento e cada um junto ao seu estandarte, segundo os seus grupos;"},
{v:53,t:"mas os levitas acamparão ao redor da Morada do testemunho, para que não haja ira sobre a assembleia dos filhos de Israel; e os levitas guardarão o encargo da Morada do testemunho."},
{v:54,t:"Os filhos de Israel fizeram tudo o que o Senhor ordenara a Moisés; assim fizeram."}
];

window.TEXTOS_SEED["numeros"][2] = [
{s:"A ordem do acampamento"},
{v:1,t:"O Senhor falou a Moisés e a Aarão, dizendo:"},
{v:2,t:"Os filhos de Israel acamparão cada um junto ao seu estandarte, sob as insígnias das casas de seus pais; acamparão ao redor da tenda do encontro, defronte dela."},
{s:"A leste: Judá, Issacar e Zabulon"},
{v:3,t:"Ao oriente acampará o estandarte do acampamento de Judá, segundo os seus grupos; o príncipe dos filhos de Judá é Naasson, filho de Aminadab,"},
{v:4,t:"e o seu exército recenseado é de setenta e quatro mil e seiscentos."},
{v:5,t:"Junto a ele acampará a tribo de Issacar; o seu príncipe é Natanael, filho de Suar,",np:1},
{v:6,t:"e o seu exército recenseado é de cinquenta e quatro mil e quatrocentos."},
{v:7,t:"Depois, a tribo de Zabulon; o príncipe dos filhos de Zabulon é Eliab, filho de Helon,",np:1},
{v:8,t:"e o seu exército recenseado é de cinquenta e sete mil e quatrocentos."},
{v:9,t:"Todos os recenseados do acampamento de Judá são cento e oitenta e seis mil e quatrocentos, segundo os seus grupos; estes marcharão primeiro.",np:1},
{s:"Ao sul: Rúben, Simeão e Gad"},
{v:10,t:"Ao sul, o estandarte do acampamento de Rúben, segundo os seus grupos; o seu príncipe é Elisur, filho de Sedeur,"},
{v:11,t:"e o seu exército recenseado é de quarenta e seis mil e quinhentos."},
{v:12,t:"Junto a ele acampará a tribo de Simeão; o seu príncipe é Salamiel, filho de Surisadai,",np:1},
{v:13,t:"e o seu exército recenseado é de cinquenta e nove mil e trezentos."},
{v:14,t:"Depois, a tribo de Gad; o seu príncipe é Eliasaf, filho de Duel,",np:1},
{v:15,t:"e o seu exército recenseado é de quarenta e cinco mil, seiscentos e cinquenta."},
{v:16,t:"Todos os recenseados do acampamento de Rúben são cento e cinquenta e um mil, quatrocentos e cinquenta, segundo os seus grupos; marcharão em segundo lugar.",np:1},
{s:"A tenda do encontro no meio do arraial"},
{v:17,t:"Então partirá a tenda do encontro, com o acampamento dos levitas no meio dos demais acampamentos; como acamparem, assim marcharão, cada um no seu lugar, junto ao seu estandarte."},
{s:"A oeste: Efraim, Manassés e Benjamim"},
{v:18,t:"Ao ocidente, o estandarte do acampamento de Efraim, segundo os seus grupos; o seu príncipe é Elisama, filho de Amiud,"},
{v:19,t:"e o seu exército recenseado é de quarenta mil e quinhentos."},
{v:20,t:"Junto a ele, a tribo de Manassés; o seu príncipe é Gamaliel, filho de Fadassur,",np:1},
{v:21,t:"e o seu exército recenseado é de trinta e dois mil e duzentos."},
{v:22,t:"Depois, a tribo de Benjamim; o seu príncipe é Abidan, filho de Gedeon,",np:1},
{v:23,t:"e o seu exército recenseado é de trinta e cinco mil e quatrocentos."},
{v:24,t:"Todos os recenseados do acampamento de Efraim são cento e oito mil e cem, segundo os seus grupos; marcharão em terceiro lugar.",np:1},
{s:"Ao norte: Dã, Aser e Neftali"},
{v:25,t:"Ao norte, o estandarte do acampamento de Dã, segundo os seus grupos; o seu príncipe é Aiezer, filho de Amisadai,"},
{v:26,t:"e o seu exército recenseado é de sessenta e dois mil e setecentos."},
{v:27,t:"Junto a ele acampará a tribo de Aser; o seu príncipe é Fegiel, filho de Ocran,",np:1},
{v:28,t:"e o seu exército recenseado é de quarenta e um mil e quinhentos."},
{v:29,t:"Depois, a tribo de Neftali; o seu príncipe é Aíra, filho de Enan,",np:1},
{v:30,t:"e o seu exército recenseado é de cinquenta e três mil e quatrocentos."},
{v:31,t:"Todos os recenseados do acampamento de Dã são cento e cinquenta e sete mil e seiscentos; marcharão por último, junto aos seus estandartes.",np:1},
{s:"A soma e a conclusão"},
{v:32,t:"Estes são os recenseados dos filhos de Israel, segundo as casas de seus pais; todos os recenseados dos acampamentos, segundo os seus grupos, foram seiscentos e três mil, quinhentos e cinquenta."},
{v:33,t:"Mas os levitas não foram recenseados entre os filhos de Israel, como o Senhor ordenara a Moisés."},
{v:34,t:"E os filhos de Israel fizeram tudo o que o Senhor ordenara a Moisés: assim acampavam junto aos seus estandartes e assim marchavam, cada um segundo as suas famílias e as casas de seus pais."}
];

window.TEXTOS_SEED["numeros"][3] = [
{s:"Os filhos de Aarão"},
{v:1,t:"Estas são as gerações de Aarão e de Moisés, no dia em que o Senhor falou com Moisés no monte Sinai."},
{v:2,t:"Estes são os nomes dos filhos de Aarão: o primogênito Nadab, depois Abiú, Eleazar e Itamar."},
{v:3,t:"Estes são os nomes dos filhos de Aarão, sacerdotes ungidos, cujas mãos foram consagradas para exercerem o sacerdócio."},
{v:4,t:"Nadab e Abiú morreram diante do Senhor, quando ofereceram fogo estranho diante do Senhor no deserto do Sinai, e não tiveram filhos; Eleazar e Itamar exerceram o sacerdócio na presença de Aarão, seu pai."},
{s:"Os levitas dados a Aarão"},
{v:5,t:"O Senhor falou a Moisés, dizendo:"},
{v:6,t:"Faze aproximar a tribo de Levi e apresenta-a diante do sacerdote Aarão, para que o sirvam"},
{v:7,t:"e cumpram o seu encargo e o encargo de toda a assembleia diante da tenda do encontro, prestando o serviço da Morada."},
{v:8,t:"Guardarão todos os utensílios da tenda do encontro e cumprirão o encargo dos filhos de Israel, prestando o serviço da Morada."},
{v:9,t:"Darás os levitas a Aarão e a seus filhos: dentre os filhos de Israel, estão inteiramente entregues a eles."},
{v:10,t:"A Aarão e a seus filhos confiarás o sacerdócio; o estranho que se aproximar será morto."},
{s:"Os levitas em lugar dos primogênitos"},
{v:11,t:"O Senhor falou a Moisés, dizendo:"},
{v:12,t:"Eis que eu tomei os levitas dentre os filhos de Israel, em lugar de todo primogênito que abre o ventre entre os filhos de Israel; os levitas serão meus,"},
{v:13,t:"porque todo primogênito é meu. No dia em que feri todos os primogênitos na terra do Egito, consagrei para mim todo primogênito em Israel, de homem e de animal: serão meus. Eu sou o Senhor."},
{s:"Recenseamento dos levitas"},
{v:14,t:"O Senhor falou a Moisés no deserto do Sinai, dizendo:"},
{v:15,t:"Recenseia os filhos de Levi segundo as casas de seus pais e as suas famílias; recensearás todo varão de um mês para cima.",n:"Ao contrário das demais tribos, contadas dos vinte anos para cima para a guerra, os levitas são contados desde o primeiro mês, porque não se trata de um exército, mas de uma consagração ao Senhor."},
{v:16,t:"Moisés os recenseou conforme a palavra do Senhor, como fora ordenado."},
{v:17,t:"Estes são os filhos de Levi pelos seus nomes: Gérson, Caat e Merari.",np:1},
{v:18,t:"Os nomes dos filhos de Gérson, por famílias: Lobni e Semei."},
{v:19,t:"Os filhos de Caat, por famílias: Amram, Isaar, Hebron e Oziel."},
{v:20,t:"Os filhos de Merari, por famílias: Mooli e Musi. Estas são as famílias de Levi, segundo as casas de seus pais."},
{s:"Os gérsonitas"},
{v:21,t:"De Gérson procedem as famílias de Lobni e de Semei: são as famílias dos gersonitas."},
{v:22,t:"Os seus recenseados, contando todo varão de um mês para cima, foram sete mil e quinhentos."},
{v:23,t:"Acamparão atrás da Morada, ao ocidente."},
{v:24,t:"O príncipe da casa paterna dos gersonitas é Eliasaf, filho de Lael.",np:1},
{v:25,t:"O encargo dos filhos de Gérson na tenda do encontro é a Morada e a tenda, a sua cobertura e o véu da entrada da tenda do encontro,"},
{v:26,t:"as cortinas do átrio e o véu da entrada do átrio, que está ao redor da Morada e do altar, e as cordas para todo o seu serviço."},
{s:"Os caatitas"},
{v:27,t:"De Caat procedem as famílias dos amramitas, dos isaaritas, dos hebronitas e dos ozielitas: são as famílias dos caatitas."},
{v:28,t:"Contando todo varão de um mês para cima, eram oito mil e seiscentos, encarregados de guardar o santuário."},
{v:29,t:"As famílias dos filhos de Caat acamparão ao lado sul da Morada."},
{v:30,t:"O príncipe da casa paterna das famílias dos caatitas é Elisafan, filho de Oziel.",np:1},
{v:31,t:"O seu encargo é a arca, a mesa, o candelabro, os altares, os utensílios do santuário com que fazem o serviço, o véu e tudo o que pertence ao seu serviço."},
{v:32,t:"O príncipe dos príncipes dos levitas é Eleazar, filho do sacerdote Aarão; a ele cabe a superintendência dos que guardam o santuário."},
{s:"Os meraritas"},
{v:33,t:"De Merari procedem as famílias de Mooli e de Musi: são as famílias dos meraritas."},
{v:34,t:"Os seus recenseados, contando todo varão de um mês para cima, foram seis mil e duzentos."},
{v:35,t:"O príncipe da casa paterna é Suriel, filho de Abiail; acamparão ao lado norte da Morada.",np:1},
{v:36,t:"O encargo confiado aos filhos de Merari são as tábuas da Morada, os seus travessões, as colunas e as suas bases, todos os seus utensílios e tudo o que pertence ao seu serviço,"},
{v:37,t:"as colunas do átrio ao redor, com as suas bases, as estacas e as cordas."},
{s:"Moisés e Aarão diante da tenda"},
{v:38,t:"Diante da Morada, ao oriente, defronte da tenda do encontro, acamparão Moisés, Aarão e seus filhos, encarregados de guardar o santuário em favor dos filhos de Israel; o estranho que se aproximar será morto."},
{v:39,t:"Todos os levitas recenseados por Moisés e Aarão, por ordem do Senhor, segundo as suas famílias, todo varão de um mês para cima, foram vinte e dois mil."},
{s:"O recenseamento dos primogênitos"},
{v:40,t:"O Senhor disse a Moisés: Recenseia todos os primogênitos varões dos filhos de Israel, de um mês para cima, e faze a conta dos seus nomes."},
{v:41,t:"Tomarás para mim os levitas em lugar de todos os primogênitos dos filhos de Israel — eu sou o Senhor — e o gado dos levitas em lugar de todos os primogênitos do gado dos filhos de Israel."},
{v:42,t:"Moisés recenseou todos os primogênitos dos filhos de Israel, como o Senhor lhe ordenara,"},
{v:43,t:"e todos os primogênitos varões, contados os nomes de um mês para cima, foram vinte e dois mil duzentos e setenta e três."},
{s:"O resgate dos primogênitos"},
{v:44,t:"O Senhor falou a Moisés, dizendo:"},
{v:45,t:"Toma os levitas em lugar de todos os primogênitos dos filhos de Israel, e o gado dos levitas em lugar do seu gado; os levitas serão meus. Eu sou o Senhor."},
{v:46,t:"Para o resgate dos duzentos e setenta e três primogênitos dos filhos de Israel que excedem o número dos levitas,",np:1},
{v:47,t:"tomarás cinco siclos por cabeça, segundo o siclo do santuário, de vinte gueras o siclo;",n:"O siclo do santuário é o padrão de peso oficial, cerca de onze gramas e meia de prata; a guera é a sua vigésima parte."},
{v:48,t:"e darás o dinheiro a Aarão e a seus filhos, como resgate dos que excedem."},
{v:49,t:"Moisés recebeu o dinheiro dos que excediam o número dos resgatados pelos levitas:",np:1},
{v:50,t:"dos primogênitos dos filhos de Israel recebeu mil trezentos e sessenta e cinco siclos, segundo o siclo do santuário,"},
{v:51,t:"e Moisés deu o dinheiro do resgate a Aarão e a seus filhos, conforme a palavra do Senhor, como o Senhor ordenara a Moisés."}
];

window.TEXTOS_SEED["numeros"][4] = [
{s:"O recenseamento dos caatitas"},
{v:1,t:"O Senhor falou a Moisés e a Aarão, dizendo:"},
{v:2,t:"Fazei o recenseamento dos filhos de Caat, dentre os filhos de Levi, segundo as suas famílias e as casas de seus pais,"},
{v:3,t:"dos trinta aos cinquenta anos, de todos os que entram no serviço para trabalhar na tenda do encontro.",n:"A idade não vale para o levita em geral, mas para o que carrega o santuário em marcha: pedia-se a força de um homem feito. Em 8,24 o começo do serviço é aos vinte e cinco anos, e a diferença sempre deu que pensar aos comentadores."},
{v:4,t:"Este é o ofício dos filhos de Caat na tenda do encontro: as coisas santíssimas."},
{s:"O que Aarão e seus filhos hão de cobrir"},
{v:5,t:"Quando o arraial partir, Aarão e seus filhos entrarão, tirarão o véu que pende diante da arca do testemunho e com ele cobrirão a arca;"},
{v:6,t:"porão sobre ela uma cobertura de peles finas, estenderão por cima um pano todo de púrpura violácea e ajustarão os varais.",n:"Peles finas traduz tahash, palavra de sentido incerto: já se entendeu pele de golfinho, de dugongo ou couro tratado. O certo é tratar-se da cobertura exterior, resistente à intempérie."},
{v:7,t:"Sobre a mesa da proposição estenderão um pano de púrpura violácea e porão sobre ele os pratos, as taças, as tigelas e os copos das libações; o pão estará sempre sobre ela.",np:1},
{v:8,t:"Estenderão por cima um pano de carmesim, que cobrirão com uma cobertura de peles finas, e ajustarão os varais."},
{v:9,t:"Tomarão um pano de púrpura violácea e cobrirão o candelabro com as suas lâmpadas, as suas tenazes, os seus apagadores e todos os vasos do azeite necessários ao serviço das lâmpadas;",np:1},
{v:10,t:"e o porão, com todos os seus utensílios, numa cobertura de peles finas, e o colocarão sobre os varais."},
{v:11,t:"Sobre o altar de ouro estenderão um pano de púrpura violácea, o cobrirão com uma cobertura de peles finas e ajustarão os varais.",np:1},
{v:12,t:"Tomarão todos os utensílios do serviço com que servem no santuário, os envolverão num pano de púrpura violácea, os cobrirão com uma cobertura de peles finas e os porão sobre os varais."},
{v:13,t:"Tirarão as cinzas do altar e estenderão sobre ele um pano de púrpura escarlate;",np:1},
{v:14,t:"porão sobre ele todos os utensílios com que servem no altar: os braseiros, os garfos, as pás e as bacias; cobrirão o altar com uma cobertura de peles finas e ajustarão os varais."},
{s:"O encargo dos caatitas"},
{v:15,t:"Quando Aarão e seus filhos acabarem de cobrir o santuário e todos os seus utensílios, ao partir o arraial, os filhos de Caat virão para os levar; mas não tocarão as coisas santas, para que não morram. Este é o encargo dos filhos de Caat na tenda do encontro.",n:"Os caatitas carregam o mais santo, e é justamente por isso que não podem tocá-lo: só o levam depois de coberto pelos sacerdotes. É a morte de Oza, em 2 Samuel 6, que mostra o que estava em jogo."},
{v:16,t:"A Eleazar, filho do sacerdote Aarão, cabe o cuidado do azeite das lâmpadas, do incenso aromático, da oblação perpétua e do óleo da unção: o cuidado de todo o tabernáculo e de tudo o que nele há, do santuário e dos seus utensílios."},
{s:"Aviso para que os caatitas não pereçam"},
{v:17,t:"O Senhor falou a Moisés e a Aarão, dizendo:"},
{v:18,t:"Não deixeis que a tribo das famílias dos caatitas seja exterminada do meio dos levitas."},
{v:19,t:"Fazei assim com eles, para que vivam e não morram ao aproximar-se das coisas santíssimas: Aarão e seus filhos entrarão e designarão a cada um o seu serviço e o que há de levar."},
{v:20,t:"E eles não entrem para ver, nem por um instante, as coisas santas, para que não morram."},
{s:"O recenseamento e o encargo dos gérsonitas"},
{v:21,t:"O Senhor falou a Moisés, dizendo:"},
{v:22,t:"Faze também o recenseamento dos filhos de Gérson, segundo as casas de seus pais e as suas famílias;"},
{v:23,t:"dos trinta aos cinquenta anos recensearás todos os que entram no serviço para trabalhar na tenda do encontro."},
{v:24,t:"Este é o ofício das famílias dos gérsonitas, no que hão de fazer e levar:",np:1},
{v:25,t:"levarão as cortinas do tabernáculo, a tenda do encontro com a sua cobertura, a cobertura de peles finas que se põe por cima e o véu da entrada da tenda do encontro;"},
{v:26,t:"as cortinas do átrio e o véu da entrada do átrio que está ao redor do tabernáculo e do altar, as suas cordas e todos os utensílios do seu serviço; e farão tudo o que a isso pertence."},
{v:27,t:"Todo o serviço dos filhos de Gérson será feito por ordem de Aarão e de seus filhos, tudo o que hão de levar e fazer; e confiareis ao seu cuidado tudo o que lhes cabe levar.",np:1},
{v:28,t:"Este é o ofício das famílias dos gérsonitas na tenda do encontro; e estarão sob a direção de Itamar, filho do sacerdote Aarão."},
{s:"O recenseamento e o encargo dos meraritas"},
{v:29,t:"Recensearás também os filhos de Merari, segundo as suas famílias e as casas de seus pais;"},
{v:30,t:"dos trinta aos cinquenta anos recensearás todos os que entram no serviço para trabalhar na tenda do encontro."},
{v:31,t:"Este é o encargo do que hão de levar, segundo todo o seu serviço na tenda do encontro: as tábuas do tabernáculo, os seus travessões, as suas colunas e as suas bases;",np:1},
{v:32,t:"as colunas do átrio ao redor, com as suas bases, as suas estacas e as suas cordas, com todos os seus utensílios e tudo o que a eles pertence. Designareis por nome os objetos que a cada um cabe levar."},
{v:33,t:"Este é o ofício das famílias dos filhos de Merari, segundo todo o seu serviço na tenda do encontro, sob a direção de Itamar, filho do sacerdote Aarão."},
{s:"Os levitas recenseados"},
{v:34,t:"Moisés, Aarão e os príncipes da assembleia recensearam os filhos dos caatitas, segundo as suas famílias e as casas de seus pais,"},
{v:35,t:"dos trinta aos cinquenta anos, todos os que entram no serviço para trabalhar na tenda do encontro;"},
{v:36,t:"e os recenseados por famílias foram dois mil setecentos e cinquenta."},
{v:37,t:"Estes são os recenseados das famílias dos caatitas, todos os que servem na tenda do encontro, os que Moisés e Aarão recensearam por ordem do Senhor, dada por meio de Moisés."},
{v:38,t:"Os filhos de Gérson foram recenseados segundo as suas famílias e as casas de seus pais,",np:1},
{v:39,t:"dos trinta aos cinquenta anos, todos os que entram no serviço para trabalhar na tenda do encontro;"},
{v:40,t:"e os recenseados, por famílias e casas de seus pais, foram dois mil seiscentos e trinta."},
{v:41,t:"Estes são os recenseados das famílias dos filhos de Gérson, todos os que servem na tenda do encontro, os que Moisés e Aarão recensearam por ordem do Senhor."},
{v:42,t:"As famílias dos filhos de Merari foram recenseadas segundo as suas famílias e as casas de seus pais,",np:1},
{v:43,t:"dos trinta aos cinquenta anos, todos os que entram no serviço para trabalhar na tenda do encontro;"},
{v:44,t:"e os recenseados por famílias foram três mil e duzentos."},
{v:45,t:"Estes são os recenseados das famílias dos filhos de Merari, os que Moisés e Aarão recensearam por ordem do Senhor, dada por meio de Moisés."},
{v:46,t:"Todos os levitas que Moisés, Aarão e os príncipes de Israel recensearam, segundo as suas famílias e as casas de seus pais,",np:1},
{v:47,t:"dos trinta aos cinquenta anos, todos os que entravam para fazer o serviço e para levar as cargas na tenda do encontro,"},
{v:48,t:"foram oito mil quinhentos e oitenta."},
{v:49,t:"Por ordem do Senhor, dada por meio de Moisés, foi designado a cada um o seu serviço e a sua carga, conforme o Senhor ordenara a Moisés."}
];

window.TEXTOS_SEED["numeros"][5] = [
{s:"Os impuros afastados do arraial"},
{v:1,t:"O Senhor falou a Moisés, dizendo:"},
{v:2,t:"Ordena aos filhos de Israel que lancem fora do arraial todo leproso, todo o que tem fluxo e todo o que está impuro por causa de um morto."},
{v:3,t:"Lançareis fora tanto o homem como a mulher, para fora do arraial, a fim de que não o contaminem, pois eu habito no meio dele.",n:"A razão dada não é sanitária, mas a presença de Deus no meio do povo: é ela que torna o arraial um lugar que se pode profanar."},
{v:4,t:"Os filhos de Israel assim fizeram, e os lançaram fora do arraial; como o Senhor dissera a Moisés, assim fizeram."},
{s:"A restituição pelo dano"},
{v:5,t:"O Senhor falou a Moisés, dizendo:"},
{v:6,t:"Dize aos filhos de Israel: Quando um homem ou uma mulher cometer algum dos pecados que os homens costumam cometer, sendo infiel ao Senhor, e essa alma for culpada,"},
{v:7,t:"confessará o seu pecado e restituirá integralmente o dano, acrescentando-lhe a quinta parte, e o dará àquele contra quem pecou.",n:"O dano ao próximo é tratado como infidelidade ao Senhor, e por isso a reparação tem duas faces: a restituição a quem se lesou e o sacrifício diante de Deus."},
{v:8,t:"Se não houver quem receba a restituição, ela será do Senhor e caberá ao sacerdote, além do carneiro da expiação, com que se fará expiação por ele."},
{v:9,t:"Toda oferta que os filhos de Israel consagrarem e apresentarem ao sacerdote será dele.",np:1},
{v:10,t:"As coisas consagradas por qualquer um são dele; e o que alguém der ao sacerdote, ao sacerdote pertence."},
{s:"A lei do ciúme"},
{v:11,t:"O Senhor falou a Moisés, dizendo:"},
{v:12,t:"Fala aos filhos de Israel e dize a eles: Se a mulher de alguém se desviar e lhe for infiel,"},
{v:13,t:"e outro homem se deitar com ela, sem que o marido o saiba, e ela se tiver contaminado em segredo, e não houver testemunha contra ela nem for apanhada,"},
{v:14,t:"mas sobrevier ao marido o espírito de ciúme, e ele tiver ciúmes da mulher que se contaminou — ou lhe sobrevier o espírito de ciúme, e ele tiver ciúmes dela sem que ela se tenha contaminado —,"},
{v:15,t:"o homem levará a sua mulher ao sacerdote e apresentará por ela a oferta devida: a décima parte de um efá de farinha de cevada; não derramará azeite sobre ela nem porá incenso, porque é oblação de ciúme, oblação de lembrança, que traz o pecado à memória.",n:"Cevada, e não trigo; sem azeite nem incenso: a oferta é despojada de tudo o que faz a alegria das outras, e o próprio material diz o que ali se passa."},
{v:16,t:"O sacerdote a fará aproximar-se e a porá diante do Senhor.",np:1},
{v:17,t:"Tomará água santa num vaso de barro e, do pó do chão do tabernáculo, lançará na água."},
{v:18,t:"Estando a mulher diante do Senhor, o sacerdote lhe descobrirá a cabeça e lhe porá nas mãos a oblação de lembrança, que é a oblação de ciúme; e na sua mão terá a água amarga que traz maldição."},
{v:19,t:"E a conjurará, dizendo: Se nenhum homem se deitou contigo, e se não te desviaste para a impureza, deixando o teu marido, estas águas amargas que trazem maldição não te façam mal.",np:1},
{v:20,t:"Mas, se te desviaste do teu marido e te contaminaste, e algum homem, além do teu marido, se deitou contigo —"},
{v:21,t:"então o sacerdote conjurará a mulher com o juramento da maldição, e dirá a ela: O Senhor te ponha por maldição e imprecação no meio do teu povo, fazendo apodrecer as tuas entranhas e inchar o teu ventre."},
{v:22,t:"Entrem estas águas que trazem maldição nas tuas entranhas, para que inche o teu ventre e apodreçam as tuas entranhas. E a mulher responderá: Amém, amém."},
{v:23,t:"O sacerdote escreverá num rolo estas maldições e as apagará na água amarga,",np:1,n:"A maldição escrita é diluída na água e bebida: o rito não fere ninguém, entrega o julgamento a Deus. De todas as provas do antigo Oriente, esta é a única cujo elemento — água, pó do santuário e tinta — é inofensivo."},
{v:24,t:"e dará a beber à mulher as águas amargas que trazem maldição; e as águas da maldição entrarão nela e se tornarão amargas."},
{v:25,t:"O sacerdote tomará da mão da mulher a oblação de ciúme, a agitará diante do Senhor e a apresentará sobre o altar;"},
{v:26,t:"tomará da oblação um punhado, como memorial, e o queimará sobre o altar; depois dará a beber à mulher as águas."},
{v:27,t:"Depois de lhe dar a beber, sucederá que, se ela se contaminou e foi infiel ao seu marido, as águas da maldição entrarão nela e se tornarão amargas: o seu ventre inchará e as suas entranhas apodrecerão, e ela será por maldição no meio do seu povo.",np:1},
{v:28,t:"Mas, se a mulher não se contaminou e está pura, ficará ilesa e terá filhos."},
{v:29,t:"Esta é a lei do ciúme, quando a mulher se desvia do seu marido e se contamina,",np:1},
{v:30,t:"ou quando ao homem sobrevém o espírito de ciúme e ele tem ciúmes da sua mulher: há de apresentá-la diante do Senhor, e o sacerdote fará com ela tudo o que está nesta lei."},
{v:31,t:"O marido ficará sem culpa, e a mulher levará a sua iniquidade."}
];

window.TEXTOS_SEED["numeros"][6] = [
{s:"O voto de nazireu"},
{v:1,t:"O Senhor falou a Moisés, dizendo:"},
{v:2,t:"Fala aos filhos de Israel e dize a eles: Quando um homem ou uma mulher fizer voto de nazireu, para se consagrar ao Senhor,",n:"Nazireu vem de nazir, o separado, o consagrado; nada tem que ver com Nazaré, embora o parentesco sonoro tenha dado azo a confusões antigas. O voto era temporário, e qualquer um podia fazê-lo, homem ou mulher."},
{v:3,t:"há de abster-se de vinho e de bebida forte; não beberá vinagre de vinho nem vinagre de bebida forte, nem suco algum de uvas, nem comerá uvas frescas ou secas."},
{v:4,t:"Todos os dias da sua consagração não comerá nada do que se faz da videira, desde os caroços até à casca."},
{v:5,t:"Todos os dias do voto da sua consagração, navalha não passará sobre a sua cabeça; até se cumprirem os dias em que está consagrado ao Senhor, será santo, e deixará crescer livremente o cabelo da sua cabeça.",np:1},
{v:6,t:"Todos os dias em que está consagrado ao Senhor, não se aproximará de nenhum morto;"},
{v:7,t:"nem por seu pai, nem por sua mãe, nem por seu irmão, nem por sua irmã se contaminará quando morrerem, porque a consagração do seu Deus está sobre a sua cabeça.",n:"É a mesma exigência que recai sobre o sumo sacerdote em Levítico 21,11: enquanto dura o voto, o leigo fica sujeito à regra dos que servem no santuário."},
{v:8,t:"Todos os dias da sua consagração é santo ao Senhor."},
{s:"Se alguém morre de repente junto dele"},
{v:9,t:"Se alguém morrer de repente junto dele, e assim contaminar a cabeça consagrada, rapará a cabeça no dia da sua purificação, ao sétimo dia."},
{v:10,t:"Ao oitavo dia levará duas rolas ou dois pombinhos ao sacerdote, à entrada da tenda do encontro;"},
{v:11,t:"e o sacerdote oferecerá um pelo pecado e o outro em holocausto, e fará expiação por ele, do que pecou por causa do morto; e naquele mesmo dia consagrará de novo a sua cabeça."},
{v:12,t:"Consagrará ao Senhor os dias da sua consagração e trará um cordeiro de um ano como sacrifício de reparação; os dias anteriores serão perdidos, porque a sua consagração foi contaminada."},
{s:"O cumprimento do voto"},
{v:13,t:"Esta é a lei do nazireu: no dia em que se cumprirem os dias da sua consagração, será levado à entrada da tenda do encontro,"},
{v:14,t:"e apresentará a sua oferta ao Senhor: um cordeiro de um ano, sem defeito, em holocausto; uma cordeira de um ano, sem defeito, pelo pecado; e um carneiro sem defeito, como sacrifício pacífico;"},
{v:15,t:"um cesto de pães ázimos de flor de farinha amassados com azeite, e bolos ázimos untados de azeite, com a sua oblação e as suas libações."},
{v:16,t:"O sacerdote os apresentará diante do Senhor e oferecerá o sacrifício pelo pecado e o holocausto;",np:1},
{v:17,t:"e oferecerá o carneiro como sacrifício pacífico ao Senhor, com o cesto dos pães ázimos; e o sacerdote fará também a sua oblação e as suas libações."},
{v:18,t:"Então o nazireu rapará, à entrada da tenda do encontro, a sua cabeça consagrada, tomará os cabelos da sua cabeça consagrada e os porá no fogo que está sob o sacrifício pacífico.",np:1},
{v:19,t:"O sacerdote tomará a espádua cozida do carneiro, um pão ázimo do cesto e um bolo ázimo, e os porá nas mãos do nazireu, depois de este ter rapado a sua consagração;"},
{v:20,t:"e o sacerdote os agitará como oferta diante do Senhor: é coisa santa, que cabe ao sacerdote, além do peito da oferta agitada e da coxa da oferta erguida. Depois disso o nazireu poderá beber vinho."},
{v:21,t:"Esta é a lei do nazireu que fez voto, e a sua oferta ao Senhor pela sua consagração, além do que os seus recursos permitirem; conforme o voto que fizer, assim fará, segundo a lei da sua consagração."},
{s:"A bênção sacerdotal"},
{v:22,t:"O Senhor falou a Moisés, dizendo:"},
{v:23,t:"Fala a Aarão e a seus filhos e dize: Assim abençoareis os filhos de Israel; direis a eles:"},
{v:24,l:["O Senhor te abençoe","e te guarde."],n:"No hebraico, as três bênçãos crescem de três para cinco e para sete palavras, e o nome do Senhor abre cada uma: a forma imita o que diz, uma graça que se alarga. É a mais antiga passagem bíblica de que se achou cópia — em duas lâminas de prata do século VII antes de Cristo, encontradas em Ketef Hinom, junto a Jerusalém."},
{v:25,l:["O Senhor faça brilhar sobre ti a sua face","e tenha piedade de ti."],n:"Fazer brilhar a face é, na linguagem da corte, o sorriso do rei que acolhe quem se apresenta; dito de Deus, é o favor que se concede sem que se tenha merecido."},
{v:26,l:["O Senhor volte para ti o seu rosto","e te dê a paz."],n:"Paz traduz shalom, que não é só ausência de guerra, mas a inteireza de quem nada tem quebrado — e é a última palavra da bênção, o seu termo e o seu resumo."},
{v:27,t:"Assim porão o meu nome sobre os filhos de Israel, e eu os abençoarei."}
];

window.TEXTOS_SEED["numeros"][7] = [
{s:"Os carros e os bois entregues aos levitas"},
{v:1,t:"No dia em que Moisés acabou de erguer o tabernáculo, ungiu-o e consagrou-o com todos os seus utensílios, e também o altar com todos os seus utensílios; depois de os ungir e consagrar,"},
{v:2,t:"os príncipes de Israel, chefes das casas de seus pais, que eram os príncipes das tribos e presidiam aos recenseados, apresentaram a sua oferta:"},
{v:3,t:"trouxeram diante do Senhor seis carros cobertos e doze bois — um carro por cada dois príncipes e um boi por cada um — e os apresentaram diante do tabernáculo."},
{v:4,t:"O Senhor disse a Moisés:",np:1},
{v:5,t:"Recebe deles, para que sirvam no ministério da tenda do encontro, e entrega-os aos levitas, a cada um segundo o seu serviço."},
{v:6,t:"Moisés recebeu os carros e os bois e os entregou aos levitas:",np:1},
{v:7,t:"dois carros e quatro bois deu aos filhos de Gérson, segundo o seu serviço;"},
{v:8,t:"quatro carros e oito bois deu aos filhos de Merari, segundo o seu serviço, sob a direção de Itamar, filho do sacerdote Aarão."},
{v:9,t:"Aos filhos de Caat nada deu, porque o serviço deles é o do santuário, e levam as cargas aos ombros.",n:"Os meraritas carregam as tábuas e as colunas, peso de carro; os gérsonitas, os panos. Aos caatitas, que levam a arca e os objetos santos, não se dá veículo: aquilo se leva ao ombro, e é a razão por que Davi errou, em 2 Samuel 6, ao pôr a arca num carro novo."},
{s:"A dedicação do altar"},
{v:10,t:"Os príncipes apresentaram a sua oferta para a dedicação do altar, no dia em que foi ungido; apresentaram a sua oferta diante do altar."},
{v:11,t:"O Senhor disse a Moisés: Cada dia um príncipe apresentará a sua oferta para a dedicação do altar."},
{s:"As ofertas dos doze príncipes"},
{v:12,t:"No primeiro dia, apresentou a sua oferta Naasson, filho de Aminadab, da tribo de Judá.",n:"As doze ofertas são idênticas, e o texto as repete uma a uma em lugar de as resumir: nenhuma tribo é abreviada, e a igualdade entre elas fica dita pela própria extensão."},
{v:13,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:14,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:15,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:16,t:"um bode, pelo pecado;"},
{v:17,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Naasson, filho de Aminadab."},
{v:18,t:"No segundo dia, apresentou a sua oferta Natanael, filho de Suar, príncipe de Issacar.",np:1},
{v:19,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:20,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:21,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:22,t:"um bode, pelo pecado;"},
{v:23,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Natanael, filho de Suar."},
{v:24,t:"No terceiro dia, o príncipe dos filhos de Zabulon, Eliab, filho de Helon.",np:1},
{v:25,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:26,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:27,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:28,t:"um bode, pelo pecado;"},
{v:29,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Eliab, filho de Helon."},
{v:30,t:"No quarto dia, o príncipe dos filhos de Rúben, Elisur, filho de Sedeur.",np:1},
{v:31,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:32,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:33,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:34,t:"um bode, pelo pecado;"},
{v:35,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Elisur, filho de Sedeur."},
{v:36,t:"No quinto dia, o príncipe dos filhos de Simeão, Salamiel, filho de Surisadai.",np:1},
{v:37,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:38,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:39,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:40,t:"um bode, pelo pecado;"},
{v:41,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Salamiel, filho de Surisadai."},
{v:42,t:"No sexto dia, o príncipe dos filhos de Gad, Eliasaf, filho de Duel.",np:1},
{v:43,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:44,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:45,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:46,t:"um bode, pelo pecado;"},
{v:47,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Eliasaf, filho de Duel."},
{v:48,t:"No sétimo dia, o príncipe dos filhos de Efraim, Elisama, filho de Amiud.",np:1},
{v:49,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:50,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:51,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:52,t:"um bode, pelo pecado;"},
{v:53,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Elisama, filho de Amiud."},
{v:54,t:"No oitavo dia, o príncipe dos filhos de Manassés, Gamaliel, filho de Fadassur.",np:1},
{v:55,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:56,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:57,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:58,t:"um bode, pelo pecado;"},
{v:59,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Gamaliel, filho de Fadassur."},
{v:60,t:"No nono dia, o príncipe dos filhos de Benjamim, Abidan, filho de Gedeon.",np:1},
{v:61,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:62,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:63,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:64,t:"um bode, pelo pecado;"},
{v:65,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Abidan, filho de Gedeon."},
{v:66,t:"No décimo dia, o príncipe dos filhos de Dã, Aiezer, filho de Amisadai.",np:1},
{v:67,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:68,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:69,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:70,t:"um bode, pelo pecado;"},
{v:71,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Aiezer, filho de Amisadai."},
{v:72,t:"No décimo primeiro dia, o príncipe dos filhos de Aser, Fegiel, filho de Ocran.",np:1},
{v:73,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:74,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:75,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:76,t:"um bode, pelo pecado;"},
{v:77,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Fegiel, filho de Ocran."},
{v:78,t:"No décimo segundo dia, o príncipe dos filhos de Neftali, Aíra, filho de Enan.",np:1},
{v:79,t:"A sua oferta foi: um prato de prata de cento e trinta siclos, uma bacia de prata de setenta siclos, segundo o siclo do santuário, ambos cheios de flor de farinha amassada com azeite, para a oblação;"},
{v:80,t:"uma taça de ouro de dez siclos, cheia de incenso;"},
{v:81,t:"um novilho, um carneiro e um cordeiro de um ano, em holocausto;"},
{v:82,t:"um bode, pelo pecado;"},
{v:83,t:"e, para o sacrifício pacífico, dois bois, cinco carneiros, cinco bodes e cinco cordeiros de um ano. Esta foi a oferta de Aíra, filho de Enan."},
{s:"A soma das ofertas"},
{v:84,t:"Esta foi a oferta dos príncipes de Israel para a dedicação do altar, no dia em que foi ungido: doze pratos de prata, doze bacias de prata, doze taças de ouro;"},
{v:85,t:"cada prato de prata de cento e trinta siclos e cada bacia de setenta; toda a prata dos vasos foi de dois mil e quatrocentos siclos, segundo o siclo do santuário."},
{v:86,t:"As doze taças de ouro cheias de incenso, de dez siclos cada uma, segundo o siclo do santuário: todo o ouro das taças foi de cento e vinte siclos."},
{v:87,t:"Todos os animais para o holocausto: doze novilhos, doze carneiros e doze cordeiros de um ano, com as suas oblações; e doze bodes pelo pecado.",np:1},
{v:88,t:"Todos os animais para o sacrifício pacífico: vinte e quatro bois, sessenta carneiros, sessenta bodes e sessenta cordeiros de um ano. Esta foi a oferta para a dedicação do altar, depois de ele ter sido ungido."},
{s:"A voz que falava a Moisés"},
{v:89,t:"Quando Moisés entrava na tenda do encontro para falar com Deus, ouvia a voz que lhe falava de cima do propiciatório que está sobre a arca do testemunho, entre os dois querubins; e falava com ele.",n:"Propiciatório traduz kapporet, a lâmina de ouro que cobre a arca; é dali, e não do céu, que a voz se faz ouvir. O verbo hebraico está no reflexivo, e sugere uma voz que fala consigo mesma e que Moisés surpreende."}
];

window.TEXTOS_SEED["numeros"][8] = [
{s:"As lâmpadas do candelabro"},
{v:1,t:"O Senhor falou a Moisés, dizendo:"},
{v:2,t:"Fala a Aarão e dize a ele: Quando puseres as lâmpadas, as sete lâmpadas darão luz para a frente do candelabro."},
{v:3,t:"Aarão assim fez: pôs as lâmpadas voltadas para a frente do candelabro, como o Senhor ordenara a Moisés."},
{v:4,t:"O candelabro era feito assim: de ouro batido, desde o pé até às flores era de ouro batido; conforme o modelo que o Senhor mostrara a Moisés, assim fez o candelabro.",n:"Batido traduz miqshah: peça única, lavrada a martelo, sem soldas nem partes montadas. O candelabro não é feito de peças reunidas, mas tirado de um só bloco."},
{s:"A purificação dos levitas"},
{v:5,t:"O Senhor falou a Moisés, dizendo:"},
{v:6,t:"Toma os levitas do meio dos filhos de Israel e purifica-os."},
{v:7,t:"Farás assim para os purificar: aspergirás sobre eles a água da expiação; passarão a navalha por todo o corpo, lavarão as suas vestes e ficarão puros."},
{v:8,t:"Tomarão um novilho com a sua oblação de flor de farinha amassada com azeite; e tu tomarás outro novilho pelo pecado."},
{v:9,t:"Farás chegar os levitas diante da tenda do encontro e reunirás toda a assembleia dos filhos de Israel.",np:1},
{v:10,t:"Farás chegar os levitas diante do Senhor, e os filhos de Israel porão sobre eles as suas mãos;",n:"O gesto é o mesmo com que se impõem as mãos sobre a vítima do sacrifício: o povo põe nos levitas o que lhe cabia fazer, e eles servem em seu lugar."},
{v:11,t:"e Aarão apresentará os levitas diante do Senhor, como oferta agitada da parte dos filhos de Israel, para que sirvam no ministério do Senhor."},
{v:12,t:"Os levitas porão as mãos sobre a cabeça dos novilhos: oferecerás um pelo pecado e o outro em holocausto ao Senhor, para fazer expiação pelos levitas."},
{v:13,t:"Porás os levitas diante de Aarão e de seus filhos, e os apresentarás como oferta agitada ao Senhor;",np:1},
{v:14,t:"assim separarás os levitas do meio dos filhos de Israel, e os levitas serão meus."},
{v:15,t:"Depois disso os levitas entrarão para servir na tenda do encontro. Assim os purificarás e os apresentarás como oferta agitada,"},
{v:16,t:"porque me foram inteiramente dados do meio dos filhos de Israel; tomei-os para mim em lugar de todo primogênito, do que abre o ventre em Israel."},
{v:17,t:"Porque meu é todo primogênito entre os filhos de Israel, tanto de homens como de animais; desde o dia em que feri todo primogênito na terra do Egito, os consagrei para mim."},
{v:18,t:"Tomei os levitas em lugar de todos os primogênitos dos filhos de Israel,"},
{v:19,t:"e dei os levitas a Aarão e a seus filhos, do meio dos filhos de Israel, para servirem no ministério dos filhos de Israel na tenda do encontro e para fazerem expiação por eles, a fim de que não haja praga entre os filhos de Israel quando se aproximarem do santuário."},
{v:20,t:"Moisés, Aarão e toda a assembleia dos filhos de Israel fizeram com os levitas tudo o que o Senhor ordenara a Moisés a respeito deles; assim fizeram com eles os filhos de Israel.",np:1},
{v:21,t:"Os levitas purificaram-se e lavaram as suas vestes; Aarão os apresentou como oferta agitada diante do Senhor e fez expiação por eles, para os purificar."},
{v:22,t:"Depois disso, os levitas entraram para fazer o seu serviço na tenda do encontro, diante de Aarão e de seus filhos; como o Senhor ordenara a Moisés a respeito dos levitas, assim fizeram com eles."},
{s:"A idade do serviço levítico"},
{v:23,t:"O Senhor falou a Moisés, dizendo:"},
{v:24,t:"Isto é o que toca aos levitas: dos vinte e cinco anos para cima entrarão para servir no ministério da tenda do encontro;",n:"Em 4,3 o serviço começa aos trinta anos. Os antigos explicavam a diferença por cinco anos de aprendizado, ou entendiam que os trinta valiam só para o transporte do santuário, mais pesado."},
{v:25,t:"e dos cinquenta anos deixarão o serviço e não servirão mais."},
{v:26,t:"Ajudarão os seus irmãos na tenda do encontro, guardando o que lhes está confiado, mas não farão o serviço. Assim farás com os levitas quanto aos seus encargos."}
];

window.TEXTOS_SEED["numeros"][9] = [
{s:"A Páscoa no deserto do Sinai"},
{v:1,t:"O Senhor falou a Moisés, no deserto do Sinai, no segundo ano depois da saída da terra do Egito, no primeiro mês, dizendo:",n:"O capítulo recua no tempo: os anteriores já estavam no segundo mês do segundo ano. A ordem do livro não é a do calendário, e aqui a Páscoa vem antes por ser o que dá sentido à partida."},
{v:2,t:"Celebrem os filhos de Israel a Páscoa no seu tempo."},
{v:3,t:"No dia catorze deste mês, ao entardecer, a celebrareis no seu tempo; segundo todos os seus preceitos e todos os seus ritos a celebrareis."},
{v:4,t:"Moisés disse aos filhos de Israel que celebrassem a Páscoa;",np:1},
{v:5,t:"e a celebraram no primeiro mês, no dia catorze, ao entardecer, no deserto do Sinai; conforme tudo o que o Senhor ordenara a Moisés, assim fizeram os filhos de Israel."},
{s:"Os que não podiam celebrá-la no seu tempo"},
{v:6,t:"Havia alguns homens que estavam impuros por causa de um morto e não podiam celebrar a Páscoa naquele dia; apresentaram-se diante de Moisés e de Aarão naquele mesmo dia,"},
{v:7,t:"e disseram a eles: Estamos impuros por causa de um morto; por que havemos de ser privados de apresentar a oferta do Senhor no seu tempo, no meio dos filhos de Israel?"},
{v:8,t:"Moisés respondeu a eles: Esperai, para que eu ouça o que o Senhor ordena a vosso respeito.",n:"Moisés não decide por si nem despacha o caso: a lei ainda não previa aquilo, e a resposta vem por consulta. É um dos quatro casos do Pentateuco resolvidos assim."},
{v:9,t:"O Senhor falou a Moisés, dizendo:",np:1},
{v:10,t:"Fala aos filhos de Israel e dize: Se alguém de vós ou dos vossos descendentes estiver impuro por causa de um morto, ou andar em viagem para longe, celebrará a Páscoa ao Senhor:"},
{v:11,t:"no segundo mês, no dia catorze, ao entardecer, a celebrarão; com pães ázimos e ervas amargas a comerão."},
{v:12,t:"Não deixarão nada dela até à manhã, nem lhe quebrarão osso algum; segundo todo o rito da Páscoa a celebrarão.",n:"São João cita este preceito ao contar que não quebraram as pernas de Jesus na cruz, vendo nele o Cordeiro pascal."},
{v:13,t:"Mas quem estiver puro e não estiver em viagem, e deixar de celebrar a Páscoa, essa alma será eliminada do seu povo, porque não apresentou a oferta do Senhor no seu tempo: levará o seu pecado."},
{v:14,t:"Se um estrangeiro peregrinar entre vós e quiser celebrar a Páscoa ao Senhor, há de celebrá-la segundo os preceitos e os ritos da Páscoa. Uma só lei haverá entre vós, tanto para o estrangeiro como para o natural da terra."},
{s:"A nuvem sobre o tabernáculo"},
{v:15,t:"No dia em que se ergueu o tabernáculo, a nuvem cobriu o tabernáculo, a tenda do testemunho; e desde a tarde até à manhã havia sobre o tabernáculo como que uma aparência de fogo."},
{v:16,t:"Assim era sempre: a nuvem o cobria, e de noite, uma aparência de fogo."},
{v:17,t:"Quando a nuvem se levantava de sobre a tenda, os filhos de Israel partiam; e no lugar em que a nuvem parava, ali acampavam."},
{v:18,t:"Por ordem do Senhor os filhos de Israel partiam, e por ordem do Senhor acampavam; todos os dias em que a nuvem permanecia sobre o tabernáculo, ficavam acampados.",np:1},
{v:19,t:"Quando a nuvem se detinha muitos dias sobre o tabernáculo, os filhos de Israel guardavam a ordem do Senhor e não partiam."},
{v:20,t:"Às vezes a nuvem ficava poucos dias sobre o tabernáculo: por ordem do Senhor acampavam e por ordem do Senhor partiam."},
{v:21,t:"Às vezes a nuvem ficava desde a tarde até à manhã; e, levantando-se pela manhã, partiam. Fosse de dia ou de noite, quando a nuvem se levantava, partiam."},
{v:22,t:"Fosse dois dias, um mês ou mais tempo que a nuvem se detivesse sobre o tabernáculo, os filhos de Israel ficavam acampados e não partiam; mas, quando ela se levantava, partiam."},
{v:23,t:"Por ordem do Senhor acampavam e por ordem do Senhor partiam; guardavam a ordem do Senhor, conforme a sua palavra dada por meio de Moisés.",n:"A repetição insistente de por ordem do Senhor — sete vezes em nove versículos — é o próprio assunto do trecho: a marcha não tem itinerário, tem obediência."}
];

window.TEXTOS_SEED["numeros"][10] = [
{s:"As trombetas de prata"},
{v:1,t:"O Senhor falou a Moisés, dizendo:"},
{v:2,t:"Faze para ti duas trombetas de prata; de prata batida as farás, e servirão para convocar a assembleia e para levantar o arraial."},
{v:3,t:"Quando se tocarem as duas, toda a assembleia se reunirá junto a ti, à entrada da tenda do encontro."},
{v:4,t:"Se se tocar uma só, hão de reunir-se junto a ti os príncipes, os chefes dos milhares de Israel."},
{v:5,t:"Quando tocardes o alarme, partirão os que estão acampados ao oriente;"},
{v:6,t:"quando tocardes o alarme segunda vez, partirão os que estão acampados ao sul. Tocarão o alarme para partirem."},
{v:7,t:"Para reunir a assembleia, tocareis, mas não em alarme.",n:"Distinguem-se dois toques: o prolongado, que convoca, e o entrecortado, que põe em marcha. Um chama, o outro move."},
{v:8,t:"Os filhos de Aarão, os sacerdotes, tocarão as trombetas; e isto será para vós preceito perpétuo, por vossas gerações."},
{v:9,t:"Quando na vossa terra sairdes à guerra contra o inimigo que vos oprime, tocareis o alarme com as trombetas, e o Senhor, vosso Deus, se lembrará de vós, e sereis salvos dos vossos inimigos.",np:1},
{v:10,t:"No dia da vossa alegria, nas vossas solenidades e nos princípios dos vossos meses, tocareis as trombetas sobre os vossos holocaustos e sobre os vossos sacrifícios pacíficos; e elas vos porão em memória diante do vosso Deus. Eu sou o Senhor, vosso Deus."},
{s:"A partida do Sinai"},
{v:11,t:"No segundo ano, no segundo mês, no vigésimo dia do mês, a nuvem se levantou de sobre o tabernáculo do testemunho."},
{v:12,t:"Os filhos de Israel partiram, por suas etapas, do deserto do Sinai; e a nuvem parou no deserto de Farã."},
{v:13,t:"Partiram pela primeira vez, por ordem do Senhor dada por meio de Moisés."},
{s:"A ordem de marcha"},
{v:14,t:"Partiu primeiro o estandarte do arraial dos filhos de Judá, segundo os seus grupos; e o seu exército era comandado por Naasson, filho de Aminadab."},
{v:15,t:"O exército da tribo dos filhos de Issacar era comandado por Natanael, filho de Suar;"},
{v:16,t:"e o exército da tribo dos filhos de Zabulon, por Eliab, filho de Helon."},
{v:17,t:"Desarmado o tabernáculo, partiram os filhos de Gérson e os filhos de Merari, que o levavam.",np:1},
{v:18,t:"Partiu o estandarte do arraial de Rúben, segundo os seus grupos; e o seu exército era comandado por Elisur, filho de Sedeur."},
{v:19,t:"O exército da tribo dos filhos de Simeão era comandado por Salamiel, filho de Surisadai;"},
{v:20,t:"e o exército da tribo dos filhos de Gad, por Eliasaf, filho de Duel."},
{v:21,t:"Partiram então os caatitas, que levavam o santuário; e o tabernáculo era erguido antes que eles chegassem.",np:1},
{v:22,t:"Partiu o estandarte do arraial dos filhos de Efraim, segundo os seus grupos; e o seu exército era comandado por Elisama, filho de Amiud."},
{v:23,t:"O exército da tribo dos filhos de Manassés era comandado por Gamaliel, filho de Fadassur;"},
{v:24,t:"e o exército da tribo dos filhos de Benjamim, por Abidan, filho de Gedeon."},
{v:25,t:"Partiu, por último de todos os arraiais, o estandarte do arraial dos filhos de Dã, segundo os seus grupos; e o seu exército era comandado por Aiezer, filho de Amisadai.",np:1},
{v:26,t:"O exército da tribo dos filhos de Aser era comandado por Fegiel, filho de Ocran;"},
{v:27,t:"e o exército da tribo dos filhos de Neftali, por Aíra, filho de Enan."},
{v:28,t:"Esta era a ordem de marcha dos filhos de Israel, segundo os seus grupos, quando partiam."},
{s:"Hobab, convidado a ir com eles"},
{v:29,t:"Moisés disse a Hobab, filho de Raguel, o madianita, sogro de Moisés: Nós partimos para o lugar que o Senhor disse: Eu o darei a vós. Vem conosco, e te faremos bem, porque o Senhor prometeu bens a Israel."},
{v:30,t:"Ele respondeu: Não irei, mas voltarei para a minha terra e para a minha parentela."},
{v:31,t:"Moisés disse: Não nos deixes, por favor, pois tu sabes onde devemos acampar no deserto, e serás os nossos olhos.",n:"O pedido soa estranho logo depois de a nuvem guiar o povo: quem tem Deus por guia pede a um homem que seja os seus olhos. Os comentadores veem aí não desconfiança, mas o modo comum de Deus agir, que se serve dos meios humanos sem os dispensar."},
{v:32,t:"Se vieres conosco, o bem que o Senhor nos fizer, esse mesmo te faremos."},
{s:"A arca vai adiante"},
{v:33,t:"Partiram do monte do Senhor caminho de três dias; e a arca da aliança do Senhor ia adiante deles, caminho de três dias, para lhes procurar lugar de descanso."},
{v:34,t:"A nuvem do Senhor estava sobre eles de dia, quando partiam do arraial."},
{v:35,l:["Quando a arca partia, Moisés dizia:","Levanta-te, Senhor,","e dispersem-se os teus inimigos,","e fujam de diante da tua face os que te odeiam."],n:"Nos manuscritos hebraicos estes dois versículos vêm cercados por dois nun invertidos, sinal de escriba que os marca como bloco à parte; a tradição judaica chega a contá-los como um livro inteiro da Escritura."},
{v:36,l:["E, quando ela pousava, dizia:","Volta, Senhor,","para a multidão do exército de Israel."]}
];

window.TEXTOS_SEED["numeros"][11] = [
{s:"O fogo em Taberá"},
{v:1,t:"O povo começou a queixar-se amargamente aos ouvidos do Senhor. O Senhor ouviu e a sua ira se acendeu; o fogo do Senhor ardeu entre eles e devorou a extremidade do arraial."},
{v:2,t:"O povo clamou a Moisés; Moisés orou ao Senhor, e o fogo se apagou."},
{v:3,t:"Chamou-se àquele lugar Taberá, porque ali ardeu contra eles o fogo do Senhor.",n:"Taberá quer dizer incêndio. É o primeiro de três lugares que neste livro recebem nome de uma desgraça: seguem-se Quibrot-Hataavá, no fim deste capítulo, e Meribá, no capítulo 20."},
{s:"O desejo de carne; o maná"},
{v:4,t:"A turba de estrangeiros que estava no meio deles foi tomada de grande desejo; e também os filhos de Israel tornaram a chorar e diziam: Quem nos dará carne para comer?"},
{v:5,t:"Lembramo-nos dos peixes que comíamos de graça no Egito; dos pepinos, dos melões, dos alhos-porros, das cebolas e dos alhos.",n:"De graça é o que diz o hebraico, e a ironia é do próprio texto: chamam gratuito o que lhes custava a escravidão."},
{v:6,t:"Agora a nossa alma está ressequida; nada vemos senão o maná."},
{v:7,t:"O maná era como semente de coentro, e a sua aparência como a do bdélio.",np:1,n:"O bdélio é uma resina translúcida, de brilho pálido; a mesma palavra aparece em Gênesis 2, entre as riquezas da terra de Havilá."},
{v:8,t:"O povo andava a recolhê-lo, moía-o em mós ou o pisava no almofariz, cozia-o numa panela e fazia dele bolos, cujo sabor era como o de bolo amassado com azeite."},
{v:9,t:"Quando de noite descia o orvalho sobre o arraial, descia também o maná."},
{s:"A queixa de Moisés"},
{v:10,t:"Moisés ouviu o povo chorar, cada família à entrada da sua tenda; a ira do Senhor se acendeu grandemente, e aquilo pareceu mal aos olhos de Moisés."},
{v:11,t:"Moisés disse ao Senhor: Por que fizeste mal ao teu servo? Por que não achei graça aos teus olhos, para que puseses sobre mim o peso de todo este povo?"},
{v:12,t:"Concebi eu, porventura, todo este povo? Gerei-o eu, para que me digas: Leva-o ao teu colo, como a ama leva o menino de peito, até à terra que juraste a seus pais?",n:"Moisés devolve a Deus a imagem materna: se este povo não é filho meu, é teu; e é a ti que cabe carregá-lo ao colo."},
{v:13,t:"Donde tirarei carne para dar a todo este povo? Choram diante de mim e dizem: Dá-nos carne para comer."},
{v:14,t:"Não posso sozinho carregar todo este povo, porque é pesado demais para mim."},
{v:15,t:"Se assim hás de tratar-me, mata-me antes, por favor, se achei graça aos teus olhos, para que eu não veja o meu mal."},
{s:"Os setenta anciãos e a promessa de carne"},
{v:16,t:"O Senhor disse a Moisés: Reúne-me setenta homens dos anciãos de Israel, que saibas serem anciãos e chefes do povo; leva-os à tenda do encontro, e ali estarão contigo."},
{v:17,t:"Eu descerei e ali falarei contigo; tomarei do espírito que está sobre ti e o porei sobre eles, para que levem contigo o peso do povo, e não o carregues tu sozinho.",n:"Tomar do espírito que está sobre Moisés não o diminui: o dom reparte-se sem se dividir, como a chama que acende outras e não se apaga."},
{v:18,t:"Ao povo dirás: Santificai-vos para amanhã, e comereis carne, pois chorastes aos ouvidos do Senhor, dizendo: Quem nos dará carne para comer? Estávamos bem no Egito. O Senhor vos dará carne, e comereis.",np:1},
{v:19,t:"Não comereis um dia só, nem dois, nem cinco, nem dez, nem vinte,"},
{v:20,t:"mas um mês inteiro, até vos sair pelas narinas e vos causar náusea, porque rejeitastes o Senhor, que está no meio de vós, e chorastes diante dele, dizendo: Por que saímos do Egito?"},
{v:21,t:"Moisés disse: Seiscentos mil homens de pé é o povo no meio do qual estou, e tu dizes: Eu lhes darei carne, e comerão um mês inteiro.",np:1},
{v:22,t:"Acaso se degolarão para eles ovelhas e bois, que lhes bastem? Ou se ajuntarão para eles todos os peixes do mar, que lhes bastem?"},
{v:23,t:"O Senhor respondeu a Moisés: Porventura a mão do Senhor é curta? Agora verás se a minha palavra se cumpre ou não."},
{s:"O espírito sobre os anciãos; Eldad e Medad"},
{v:24,t:"Moisés saiu e disse ao povo as palavras do Senhor; reuniu setenta homens dos anciãos do povo e os pôs ao redor da tenda."},
{v:25,t:"O Senhor desceu na nuvem e falou a Moisés; tomou do espírito que estava sobre ele e o pôs sobre os setenta anciãos. Quando o espírito repousou sobre eles, profetizaram — e não continuaram.",n:"E não continuaram: o hebraico é ambíguo e admite também não cessaram. As versões antigas dividem-se; a Vulgata entendeu que profetizaram uma só vez, sinal de que o dom era para aquele encargo e não um estado permanente."},
{v:26,t:"Dois homens tinham ficado no arraial: um chamava-se Eldad e o outro, Medad; sobre eles repousou o espírito, pois estavam entre os inscritos, mas não tinham ido à tenda; e profetizavam no arraial.",np:1},
{v:27,t:"Um moço correu e anunciou a Moisés: Eldad e Medad profetizam no arraial."},
{v:28,t:"Josué, filho de Nun, servo de Moisés desde a sua juventude, disse: Meu senhor Moisés, proíbe-os."},
{v:29,t:"Moisés respondeu: Tens ciúmes por minha causa? Oxalá todo o povo do Senhor fosse profeta, e o Senhor pusesse sobre eles o seu espírito!",n:"O desejo de Moisés é o que Joel anuncia e o Pentecostes cumpre: o espírito derramado sobre toda a carne, e não sobre uns poucos escolhidos."},
{v:30,t:"E Moisés voltou ao arraial, ele e os anciãos de Israel."},
{s:"As codornizes e a praga"},
{v:31,t:"Levantou-se um vento da parte do Senhor que, vindo do mar, trouxe codornizes e as espalhou sobre o arraial, caminho de um dia para um lado e caminho de um dia para o outro, ao redor do arraial, a cerca de dois côvados sobre a face da terra."},
{v:32,t:"O povo esteve de pé todo aquele dia, toda a noite e todo o dia seguinte, e ajuntou codornizes; quem menos ajuntou, ajuntou dez ômeres; e as estenderam ao redor do arraial."},
{v:33,t:"A carne ainda estava entre os seus dentes, e ainda não fora mastigada, quando a ira do Senhor se acendeu contra o povo, e o Senhor o feriu com praga muito grande."},
{v:34,t:"Chamou-se àquele lugar Quibrot-Hataavá, porque ali sepultaram o povo que tivera o desejo.",n:"Quibrot-Hataavá quer dizer sepulcros do desejo: o nome guarda ao mesmo tempo o pedido e o seu desfecho."},
{v:35,t:"De Quibrot-Hataavá o povo partiu para Haserot, e ficou em Haserot."}
];

window.TEXTOS_SEED["numeros"][12] = [
{s:"Maria e Aarão falam contra Moisés"},
{v:1,t:"Maria e Aarão falaram contra Moisés por causa da mulher etíope que ele tomara — pois tinha tomado uma mulher etíope —",n:"Etíope traduz kushita, mulher de Cuxe, a Núbia. Uns veem aí Séfora, a madianita; outros, uma segunda mulher. O texto não explica, e a queixa do versículo seguinte mostra que o casamento era só o pretexto."},
{v:2,t:"e disseram: Acaso o Senhor falou somente por Moisés? Não falou também por nós? E o Senhor ouviu."},
{v:3,t:"Ora, Moisés era um homem muito manso, mais que todos os homens que havia sobre a terra.",n:"Manso verte anav, que diz tanto a humildade quanto a condição de quem é oprimido e não revida. É a mesma palavra da terceira bem-aventurança."},
{s:"O Senhor os chama à tenda"},
{v:4,t:"Imediatamente o Senhor disse a Moisés, a Aarão e a Maria: Saí vós três à tenda do encontro. E saíram os três."},
{v:5,t:"O Senhor desceu na coluna de nuvem, pôs-se à entrada da tenda e chamou Aarão e Maria; e ambos se aproximaram."},
{v:6,l:["Ele disse: Ouvi as minhas palavras.","Se houver entre vós um profeta do Senhor,","em visão me revelarei a ele,","em sonho falarei com ele."]},
{v:7,l:["Não é assim com o meu servo Moisés,","que é fiel em toda a minha casa:"]},
{v:8,l:["boca a boca falo com ele,","com clareza, e não por enigmas,","e ele contempla a figura do Senhor.","Por que, então, não temestes falar contra o meu servo Moisés?"],n:"Boca a boca, e não face a face: o hebraico insiste na palavra, não na visão. Figura traduz temunah, o que se deixa ver de Deus sem que ninguém lhe veja a essência — a mesma reserva que o Êxodo guarda em 33,20."},
{s:"A lepra de Maria"},
{v:9,t:"A ira do Senhor se acendeu contra eles, e ele se retirou."},
{v:10,t:"A nuvem se afastou da tenda, e eis que Maria estava leprosa, branca como a neve. Aarão olhou para ela e viu a lepra.",n:"Só Maria é ferida, embora ambos tenham falado. Os comentadores antigos notam que o verbo do versículo 1 está no feminino singular, como se dela partisse a queixa e Aarão a tivesse acompanhado."},
{v:11,t:"Disse a Moisés: Rogo-te, meu senhor, não ponhas sobre nós o pecado que loucamente cometemos."},
{v:12,t:"Que ela não fique como um morto, como um aborto que sai do ventre da mãe com a carne já meio consumida."},
{v:13,t:"Moisés clamou ao Senhor, dizendo: Ó Deus, rogo-te, cura-a.",np:1,n:"Cinco palavras no hebraico, a mais curta oração do Pentateuco — e feita por quem acabava de ser acusado."},
{v:14,t:"O Senhor respondeu a Moisés: Se o pai dela lhe tivesse cuspido no rosto, não teria de ficar envergonhada sete dias? Fique sete dias fechada fora do arraial, e depois será readmitida."},
{v:15,t:"Maria ficou sete dias fechada fora do arraial, e o povo não partiu enquanto ela não foi readmitida."},
{v:16,t:"Depois disso o povo partiu de Haserot e acampou no deserto de Farã."}
];

window.TEXTOS_SEED["numeros"][13] = [
{s:"Os exploradores enviados"},
{v:1,t:"O Senhor falou a Moisés, dizendo:"},
{v:2,t:"Envia homens que explorem a terra de Canaã, que eu hei de dar aos filhos de Israel; enviarás um homem de cada tribo de seus pais, todos príncipes entre eles."},
{v:3,t:"Moisés os enviou do deserto de Farã, por ordem do Senhor; todos aqueles homens eram chefes dos filhos de Israel."},
{v:4,t:"Estes são os seus nomes: da tribo de Rúben, Samua, filho de Zacur;",np:1},
{v:5,t:"da tribo de Simeão, Safat, filho de Huri;"},
{v:6,t:"da tribo de Judá, Caleb, filho de Jefoné;"},
{v:7,t:"da tribo de Issacar, Igal, filho de José;"},
{v:8,t:"da tribo de Efraim, Oseias, filho de Nun;"},
{v:9,t:"da tribo de Benjamim, Falti, filho de Rafu;"},
{v:10,t:"da tribo de Zabulon, Gediel, filho de Sodi;"},
{v:11,t:"da tribo de José, isto é, da tribo de Manassés, Gadi, filho de Susi;"},
{v:12,t:"da tribo de Dã, Amiel, filho de Gemali;"},
{v:13,t:"da tribo de Aser, Setur, filho de Miguel;"},
{v:14,t:"da tribo de Neftali, Naabi, filho de Vapsi;"},
{v:15,t:"da tribo de Gad, Guel, filho de Maqui."},
{v:16,t:"Estes são os nomes dos homens que Moisés enviou a explorar a terra. A Oseias, filho de Nun, Moisés chamou Josué.",n:"Oseias quer dizer salvação; Josué, o Senhor salva. Moisés acrescenta ao nome do discípulo o nome de Deus, e é esse nome que a forma grega verte por Jesus."},
{s:"As instruções de Moisés"},
{v:17,t:"Moisés os enviou a explorar a terra de Canaã e disse a eles: Subi pelo Negueb e ide à montanha;"},
{v:18,t:"examinai a terra, como ela é, e o povo que a habita, se é forte ou fraco, se é pouco ou muito;"},
{v:19,t:"como é a terra em que habita, se boa ou má; como são as cidades em que mora, se abertas ou muradas;"},
{v:20,t:"como é o solo, se fértil ou estéril, se tem árvores ou não. Sede corajosos e trazei-nos dos frutos da terra. Era o tempo das primeiras uvas."},
{s:"A exploração da terra"},
{v:21,t:"Subiram e exploraram a terra, desde o deserto de Sin até Roob, à entrada de Emat."},
{v:22,t:"Subiram pelo Negueb e chegaram a Hebron, onde estavam Aquimã, Sisai e Tolmai, filhos de Enac. Hebron fora edificada sete anos antes de Tanis, no Egito."},
{v:23,t:"Chegando ao vale de Escol, cortaram um ramo com um cacho de uvas, e o levaram numa vara entre dois; levaram também romãs e figos.",np:1},
{v:24,t:"Aquele lugar foi chamado vale de Escol, por causa do cacho que dali cortaram os filhos de Israel.",n:"Escol quer dizer cacho. O sinal que os dois carregam ao ombro é o mesmo que a assembleia verá; a diferença estará no que se disser dele."},
{v:25,t:"Voltaram da exploração da terra ao fim de quarenta dias."},
{s:"O relato dos exploradores"},
{v:26,t:"Vieram ter com Moisés, com Aarão e com toda a assembleia dos filhos de Israel, no deserto de Farã, em Cades; deram conta a eles e a toda a assembleia, e lhes mostraram os frutos da terra."},
{v:27,t:"E contaram: Fomos à terra à qual nos enviaste; ela mana leite e mel, e estes são os seus frutos."},
{v:28,t:"Mas o povo que habita nessa terra é forte, e as cidades são muradas e muito grandes; vimos ali também os filhos de Enac.",n:"O relato não mente em nada: tudo o que dizem é verdade. O erro está no mas, que põe a força do inimigo acima da promessa."},
{v:29,t:"Amalec habita no Negueb; o heteu, o jebuseu e o amorreu, na montanha; o cananeu, junto ao mar e ao longo do Jordão."},
{v:30,t:"Caleb fez calar o povo diante de Moisés e disse: Subamos e tomemos posse dela, porque bem a podemos conquistar.",np:1},
{v:31,t:"Mas os homens que tinham ido com ele diziam: Não podemos subir contra este povo, porque é mais forte do que nós."},
{v:32,t:"E, diante dos filhos de Israel, difamaram a terra que tinham explorado, dizendo: A terra que percorremos para a explorar é terra que devora os seus habitantes; e todo o povo que nela vimos é de homens de grande estatura."},
{v:33,t:"Ali vimos os gigantes, filhos de Enac, da raça dos gigantes; e parecíamos gafanhotos aos nossos olhos, e assim parecíamos aos deles.",n:"Aos nossos olhos vem primeiro: mediram-se a si mesmos antes de serem medidos, e o juízo que os outros fariam deles é suposição sua."}
];

window.TEXTOS_SEED["numeros"][14] = [
{s:"A revolta do povo"},
{v:1,t:"Toda a assembleia levantou a voz e clamou; e o povo chorou aquela noite."},
{v:2,t:"Todos os filhos de Israel murmuraram contra Moisés e Aarão, e toda a assembleia disse a eles: Oxalá tivéssemos morrido na terra do Egito! Oxalá morrêssemos neste deserto!",n:"O desejo será atendido ao pé da letra, no versículo 29: morrerão naquele deserto. É a mais severa das respostas, conceder o que se pediu."},
{v:3,t:"Por que nos traz o Senhor a esta terra, para cairmos à espada? As nossas mulheres e os nossos filhos serão presa. Não é melhor voltarmos ao Egito?"},
{v:4,t:"E diziam uns aos outros: Constituamos um chefe e voltemos ao Egito."},
{s:"Josué e Caleb"},
{v:5,t:"Moisés e Aarão caíram de rosto por terra diante de toda a assembleia reunida dos filhos de Israel."},
{v:6,t:"Josué, filho de Nun, e Caleb, filho de Jefoné, que estavam entre os que tinham explorado a terra, rasgaram as suas vestes"},
{v:7,t:"e disseram a toda a assembleia dos filhos de Israel: A terra que percorremos para a explorar é muito boa."},
{v:8,t:"Se o Senhor nos for favorável, ele nos levará a essa terra e a entregará a nós: terra que mana leite e mel."},
{v:9,t:"Não vos revolteis contra o Senhor, nem temais o povo dessa terra, porque os devoraremos como pão. Retirou-se deles toda a proteção, e o Senhor está conosco; não os temais.",n:"Proteção traduz uma palavra que diz literalmente sombra: a que abrigava aqueles povos foi-lhes tirada, e ficaram expostos."},
{v:10,t:"Toda a assembleia falava em apedrejá-los, quando a glória do Senhor apareceu sobre a tenda do encontro a todos os filhos de Israel."},
{s:"A intercessão de Moisés"},
{v:11,t:"O Senhor disse a Moisés: Até quando me desprezará este povo? Até quando não crerão em mim, apesar de todos os sinais que fiz no meio deles?"},
{v:12,t:"Hei de feri-lo com a peste e destruí-lo; e farei de ti uma nação maior e mais forte do que ele.",n:"É a mesma oferta feita depois do bezerro de ouro, no Êxodo, e a mesma recusa: Moisés não aceita ser um novo Abraão à custa do povo que lhe foi confiado."},
{v:13,t:"Moisés disse ao Senhor: Os egípcios saberão que, com a tua força, tiraste este povo do meio deles,",np:1},
{v:14,t:"e dirão aos habitantes desta terra, que ouviram que tu, Senhor, estás no meio deste povo, que face a face és visto, Senhor, e que a tua nuvem está sobre eles, e que vais adiante deles numa coluna de nuvem de dia e numa coluna de fogo de noite."},
{v:15,t:"Se matares este povo como a um só homem, as nações que ouviram falar de ti dirão:"},
{v:16,t:"Não podendo o Senhor introduzir este povo na terra que lhes jurara, matou-os no deserto.",n:"O argumento de Moisés não invoca o mérito de Israel, que não tem, mas o nome de Deus: o que dele se dirá entre as nações se a promessa ficar por cumprir."},
{v:17,t:"Agora, pois, mostre-se grande a força do Senhor, como juraste, dizendo:",np:1},
{v:18,t:"O Senhor é paciente e cheio de misericórdia, que perdoa a iniquidade e a transgressão, mas não deixa impune o culpado, e castiga a iniquidade dos pais nos filhos até à terceira e à quarta geração.",n:"Moisés cita a Deus as palavras com que Deus se definiu no Sinai, em Êxodo 34, mas para na metade da fórmula: recorda a misericórdia até mil gerações omitindo-a, e deixa o resto por conta de quem o ouve."},
{v:19,t:"Perdoa, por favor, a iniquidade deste povo, segundo a grandeza da tua misericórdia, como o perdoaste desde o Egito até aqui."},
{s:"A sentença do Senhor"},
{v:20,t:"O Senhor disse: Perdoo, conforme a tua palavra."},
{v:21,t:"Mas, tão certo como eu vivo e como toda a terra se encherá da glória do Senhor:"},
{v:22,t:"nenhum dos homens que viram a minha glória e os sinais que fiz no Egito e no deserto, e que me tentaram já dez vezes e não ouviram a minha voz,",n:"Dez vezes é número redondo, e diz o cúmulo mais que a conta exata; os rabinos, ainda assim, enumeravam-nas uma a uma."},
{v:23,t:"verá a terra que jurei a seus pais; nenhum dos que me desprezaram a verá."},
{v:24,t:"Mas o meu servo Caleb, que teve outro espírito e me seguiu inteiramente, eu o levarei à terra em que entrou, e a sua descendência a possuirá."},
{v:25,t:"Como o amalecita e o cananeu habitam nos vales, amanhã voltai e parti para o deserto pelo caminho do mar Vermelho."},
{s:"Quarenta anos no deserto"},
{v:26,t:"O Senhor falou a Moisés e a Aarão, dizendo:"},
{v:27,t:"Até quando esta assembleia perversa murmurará contra mim? Ouvi as murmurações dos filhos de Israel."},
{v:28,t:"Dize a eles: Tão certo como eu vivo, diz o Senhor, farei convosco conforme falastes aos meus ouvidos."},
{v:29,t:"Neste deserto cairão os vossos cadáveres; todos os que fostes recenseados, dos vinte anos para cima, que murmurastes contra mim,",np:1},
{v:30,t:"não entrareis na terra sobre a qual levantei a minha mão, jurando que vos faria habitar nela — exceto Caleb, filho de Jefoné, e Josué, filho de Nun."},
{v:31,t:"Os vossos filhos, dos quais dissestes que seriam presa, eu os introduzirei, e eles conhecerão a terra que desprezastes."},
{v:32,t:"Os vossos cadáveres cairão neste deserto."},
{v:33,t:"Os vossos filhos serão pastores no deserto por quarenta anos e levarão a vossa infidelidade, até que se consumam os vossos cadáveres no deserto."},
{v:34,t:"Segundo o número dos quarenta dias em que explorastes a terra, um ano por cada dia, levareis as vossas iniquidades por quarenta anos, e sabereis o que é afastar-vos de mim.",n:"Um ano por dia: a pena tem a medida da culpa, e o tempo que gastaram a duvidar torna-se o tempo que hão de esperar."},
{v:35,t:"Eu, o Senhor, falei: assim farei a toda esta assembleia perversa, que se levantou contra mim; neste deserto se consumirão e nele morrerão."},
{v:36,t:"Os homens que Moisés enviara a explorar a terra e que, voltando, fizeram murmurar contra ele toda a assembleia, difamando a terra,",np:1},
{v:37,t:"morreram feridos diante do Senhor, os que difamaram a terra."},
{v:38,t:"Dos homens que tinham ido explorar a terra, só ficaram Josué, filho de Nun, e Caleb, filho de Jefoné."},
{s:"A derrota em Horma"},
{v:39,t:"Moisés disse estas palavras a todos os filhos de Israel, e o povo chorou amargamente."},
{v:40,t:"Levantando-se de madrugada, subiram ao cume do monte e disseram: Estamos prontos a subir ao lugar de que o Senhor falou, porque pecamos."},
{v:41,t:"Moisés disse a eles: Por que transgredis a ordem do Senhor? Isso não vos há de sair bem.",n:"Ontem não quiseram subir, quando lhes era mandado; hoje sobem, quando lhes é proibido. A desobediência é a mesma nas duas vezes, e só muda de sinal."},
{v:42,t:"Não subais, porque o Senhor não está no meio de vós; não sejais feridos diante dos vossos inimigos."},
{v:43,t:"O amalecita e o cananeu estão diante de vós, e caireis à espada; porque vos desviastes do Senhor, o Senhor não estará convosco."},
{v:44,t:"Eles, porém, obstinaram-se e subiram ao cume do monte; mas a arca da aliança do Senhor e Moisés não se afastaram do arraial."},
{v:45,t:"Desceram o amalecita e o cananeu que habitavam naquela montanha, e os feriram e derrotaram, perseguindo-os até Horma."}
];
