// =====================================================================
// Números — tradução dos originais (versificação: Nova Vulgata)
// Formato: {v: número, t: texto, n: nota (opcional)}
// =====================================================================

window.TEXTOS_SEED["numeros"][1] = [
{v:1,t:"O Senhor falou a Moisés no deserto do Sinai, na tenda do encontro, no primeiro dia do segundo mês, no segundo ano depois da saída da terra do Egito, dizendo:",n:"O título hebraico do livro é Bemidbar, no deserto, tomado desta primeira frase; Números vem do grego e do latim, pelos dois recenseamentos que o livro narra."},
{v:2,t:"Fazei o recenseamento de toda a assembleia dos filhos de Israel, segundo as suas famílias e as casas de seus pais, contando os nomes de todo varão, um por um,"},
{v:3,t:"dos vinte anos para cima, todos os que em Israel podem sair para a guerra; tu e Aarão os contareis segundo os seus grupos."},
{v:4,t:"Convosco estará um homem de cada tribo, o chefe da casa de seus pais."},
{v:5,t:"Estes são os nomes dos homens que estarão convosco: de Rúben, Elisur, filho de Sedeur;"},
{v:6,t:"de Simeão, Salamiel, filho de Surisadai;"},
{v:7,t:"de Judá, Naasson, filho de Aminadab;"},
{v:8,t:"de Issacar, Natanael, filho de Suar;"},
{v:9,t:"de Zabulon, Eliab, filho de Helon;"},
{v:10,t:"dos filhos de José: de Efraim, Elisama, filho de Amiud; de Manassés, Gamaliel, filho de Fadassur;"},
{v:11,t:"de Benjamim, Abidan, filho de Gedeon;"},
{v:12,t:"de Dã, Aiezer, filho de Amisadai;"},
{v:13,t:"de Aser, Fegiel, filho de Ocran;"},
{v:14,t:"de Gad, Eliasaf, filho de Duel;"},
{v:15,t:"de Neftali, Aíra, filho de Enan."},
{v:16,t:"Estes eram os chamados da assembleia, príncipes das tribos de seus pais, chefes dos milhares de Israel."},
{v:17,t:"Moisés e Aarão tomaram esses homens designados pelos seus nomes"},
{v:18,t:"e reuniram toda a assembleia no primeiro dia do segundo mês. Foram registrados por famílias, segundo as casas de seus pais, contando os nomes, dos vinte anos para cima, um por um,"},
{v:19,t:"como o Senhor ordenara a Moisés. E os recenseou no deserto do Sinai."},
{v:20,t:"Dos filhos de Rúben, primogênito de Israel: as suas gerações por famílias e casas de seus pais, contados os nomes um por um, todo varão dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:21,t:"os recenseados da tribo de Rúben foram quarenta e seis mil e quinhentos."},
{v:22,t:"Dos filhos de Simeão: as suas gerações por famílias e casas de seus pais, os recenseados, contados os nomes um por um, todo varão dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:23,t:"os recenseados da tribo de Simeão foram cinquenta e nove mil e trezentos."},
{v:24,t:"Dos filhos de Gad: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:25,t:"os recenseados da tribo de Gad foram quarenta e cinco mil, seiscentos e cinquenta."},
{v:26,t:"Dos filhos de Judá: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:27,t:"os recenseados da tribo de Judá foram setenta e quatro mil e seiscentos."},
{v:28,t:"Dos filhos de Issacar: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:29,t:"os recenseados da tribo de Issacar foram cinquenta e quatro mil e quatrocentos."},
{v:30,t:"Dos filhos de Zabulon: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:31,t:"os recenseados da tribo de Zabulon foram cinquenta e sete mil e quatrocentos."},
{v:32,t:"Dos filhos de José, dos filhos de Efraim: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:33,t:"os recenseados da tribo de Efraim foram quarenta mil e quinhentos."},
{v:34,t:"Dos filhos de Manassés: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:35,t:"os recenseados da tribo de Manassés foram trinta e dois mil e duzentos."},
{v:36,t:"Dos filhos de Benjamim: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:37,t:"os recenseados da tribo de Benjamim foram trinta e cinco mil e quatrocentos."},
{v:38,t:"Dos filhos de Dã: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:39,t:"os recenseados da tribo de Dã foram sessenta e dois mil e setecentos."},
{v:40,t:"Dos filhos de Aser: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:41,t:"os recenseados da tribo de Aser foram quarenta e um mil e quinhentos."},
{v:42,t:"Dos filhos de Neftali: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:43,t:"os recenseados da tribo de Neftali foram cinquenta e três mil e quatrocentos."},
{v:44,t:"Estes são os que Moisés e Aarão recensearam, com os doze príncipes de Israel, um por cada casa paterna."},
{v:45,t:"Todos os recenseados dos filhos de Israel, segundo as casas de seus pais, dos vinte anos para cima, todos os que em Israel podiam sair para a guerra,"},
{v:46,t:"todos os recenseados foram seiscentos e três mil, quinhentos e cinquenta.",n:"O número, muito elevado para um grupo em marcha pelo deserto, é discutido desde a antiguidade: a palavra elef, mil, designa também o clã ou o contingente que ele fornecia, o que permitiria uma leitura bem menor. Conservo a tradução literal, que é a da tradição."},
{v:47,t:"Mas os levitas, segundo a tribo de seus pais, não foram recenseados entre eles."},
{v:48,t:"O Senhor falou a Moisés, dizendo:"},
{v:49,t:"Não recensearás a tribo de Levi nem contarás os seus filhos entre os filhos de Israel;"},
{v:50,t:"mas confia aos levitas a Morada do testemunho, todos os seus utensílios e tudo o que pertence a ela. Eles levarão a Morada e todos os seus utensílios, prestarão nela o serviço e acamparão ao redor dela.",n:"Morada traduz mishkan, a tenda santa como lugar em que o Senhor habita no meio do povo; testemunho, edut, são as tábuas da Lei guardadas na arca."},
{v:51,t:"Quando a Morada tiver de partir, os levitas a desmontarão; quando tiver de acampar, os levitas a levantarão; o estranho que se aproximar será morto."},
{v:52,t:"Os filhos de Israel acamparão cada um no seu acampamento e cada um junto ao seu estandarte, segundo os seus grupos;"},
{v:53,t:"mas os levitas acamparão ao redor da Morada do testemunho, para que não haja ira sobre a assembleia dos filhos de Israel; e os levitas guardarão o encargo da Morada do testemunho."},
{v:54,t:"Os filhos de Israel fizeram tudo o que o Senhor ordenara a Moisés; assim fizeram."}
];

window.TEXTOS_SEED["numeros"][2] = [
{v:1,t:"O Senhor falou a Moisés e a Aarão, dizendo:"},
{v:2,t:"Os filhos de Israel acamparão cada um junto ao seu estandarte, sob as insígnias das casas de seus pais; acamparão ao redor da tenda do encontro, defronte dela."},
{v:3,t:"Ao oriente acampará o estandarte do acampamento de Judá, segundo os seus grupos; o príncipe dos filhos de Judá é Naasson, filho de Aminadab,"},
{v:4,t:"e o seu exército recenseado é de setenta e quatro mil e seiscentos."},
{v:5,t:"Junto a ele acampará a tribo de Issacar; o seu príncipe é Natanael, filho de Suar,"},
{v:6,t:"e o seu exército recenseado é de cinquenta e quatro mil e quatrocentos."},
{v:7,t:"Depois, a tribo de Zabulon; o príncipe dos filhos de Zabulon é Eliab, filho de Helon,"},
{v:8,t:"e o seu exército recenseado é de cinquenta e sete mil e quatrocentos."},
{v:9,t:"Todos os recenseados do acampamento de Judá são cento e oitenta e seis mil e quatrocentos, segundo os seus grupos; estes marcharão primeiro."},
{v:10,t:"Ao sul, o estandarte do acampamento de Rúben, segundo os seus grupos; o seu príncipe é Elisur, filho de Sedeur,"},
{v:11,t:"e o seu exército recenseado é de quarenta e seis mil e quinhentos."},
{v:12,t:"Junto a ele acampará a tribo de Simeão; o seu príncipe é Salamiel, filho de Surisadai,"},
{v:13,t:"e o seu exército recenseado é de cinquenta e nove mil e trezentos."},
{v:14,t:"Depois, a tribo de Gad; o seu príncipe é Eliasaf, filho de Duel,"},
{v:15,t:"e o seu exército recenseado é de quarenta e cinco mil, seiscentos e cinquenta."},
{v:16,t:"Todos os recenseados do acampamento de Rúben são cento e cinquenta e um mil, quatrocentos e cinquenta, segundo os seus grupos; marcharão em segundo lugar."},
{v:17,t:"Então partirá a tenda do encontro, com o acampamento dos levitas no meio dos demais acampamentos; como acamparem, assim marcharão, cada um no seu lugar, junto ao seu estandarte."},
{v:18,t:"Ao ocidente, o estandarte do acampamento de Efraim, segundo os seus grupos; o seu príncipe é Elisama, filho de Amiud,"},
{v:19,t:"e o seu exército recenseado é de quarenta mil e quinhentos."},
{v:20,t:"Junto a ele, a tribo de Manassés; o seu príncipe é Gamaliel, filho de Fadassur,"},
{v:21,t:"e o seu exército recenseado é de trinta e dois mil e duzentos."},
{v:22,t:"Depois, a tribo de Benjamim; o seu príncipe é Abidan, filho de Gedeon,"},
{v:23,t:"e o seu exército recenseado é de trinta e cinco mil e quatrocentos."},
{v:24,t:"Todos os recenseados do acampamento de Efraim são cento e oito mil e cem, segundo os seus grupos; marcharão em terceiro lugar."},
{v:25,t:"Ao norte, o estandarte do acampamento de Dã, segundo os seus grupos; o seu príncipe é Aiezer, filho de Amisadai,"},
{v:26,t:"e o seu exército recenseado é de sessenta e dois mil e setecentos."},
{v:27,t:"Junto a ele acampará a tribo de Aser; o seu príncipe é Fegiel, filho de Ocran,"},
{v:28,t:"e o seu exército recenseado é de quarenta e um mil e quinhentos."},
{v:29,t:"Depois, a tribo de Neftali; o seu príncipe é Aíra, filho de Enan,"},
{v:30,t:"e o seu exército recenseado é de cinquenta e três mil e quatrocentos."},
{v:31,t:"Todos os recenseados do acampamento de Dã são cento e cinquenta e sete mil e seiscentos; marcharão por último, junto aos seus estandartes."},
{v:32,t:"Estes são os recenseados dos filhos de Israel, segundo as casas de seus pais; todos os recenseados dos acampamentos, segundo os seus grupos, foram seiscentos e três mil, quinhentos e cinquenta."},
{v:33,t:"Mas os levitas não foram recenseados entre os filhos de Israel, como o Senhor ordenara a Moisés."},
{v:34,t:"E os filhos de Israel fizeram tudo o que o Senhor ordenara a Moisés: assim acampavam junto aos seus estandartes e assim marchavam, cada um segundo as suas famílias e as casas de seus pais."}
];

window.TEXTOS_SEED["numeros"][3] = [
{v:1,t:"Estas são as gerações de Aarão e de Moisés, no dia em que o Senhor falou com Moisés no monte Sinai."},
{v:2,t:"Estes são os nomes dos filhos de Aarão: o primogênito Nadab, depois Abiú, Eleazar e Itamar."},
{v:3,t:"Estes são os nomes dos filhos de Aarão, sacerdotes ungidos, cujas mãos foram consagradas para exercerem o sacerdócio."},
{v:4,t:"Nadab e Abiú morreram diante do Senhor, quando ofereceram fogo estranho diante do Senhor no deserto do Sinai, e não tiveram filhos; Eleazar e Itamar exerceram o sacerdócio na presença de Aarão, seu pai."},
{v:5,t:"O Senhor falou a Moisés, dizendo:"},
{v:6,t:"Faze aproximar a tribo de Levi e apresenta-a diante do sacerdote Aarão, para que o sirvam"},
{v:7,t:"e cumpram o seu encargo e o encargo de toda a assembleia diante da tenda do encontro, prestando o serviço da Morada."},
{v:8,t:"Guardarão todos os utensílios da tenda do encontro e cumprirão o encargo dos filhos de Israel, prestando o serviço da Morada."},
{v:9,t:"Darás os levitas a Aarão e a seus filhos: dentre os filhos de Israel, estão inteiramente entregues a eles."},
{v:10,t:"A Aarão e a seus filhos confiarás o sacerdócio; o estranho que se aproximar será morto."},
{v:11,t:"O Senhor falou a Moisés, dizendo:"},
{v:12,t:"Eis que eu tomei os levitas dentre os filhos de Israel, em lugar de todo primogênito que abre o ventre entre os filhos de Israel; os levitas serão meus,"},
{v:13,t:"porque todo primogênito é meu. No dia em que feri todos os primogênitos na terra do Egito, consagrei para mim todo primogênito em Israel, de homem e de animal: serão meus. Eu sou o Senhor."},
{v:14,t:"O Senhor falou a Moisés no deserto do Sinai, dizendo:"},
{v:15,t:"Recenseia os filhos de Levi segundo as casas de seus pais e as suas famílias; recensearás todo varão de um mês para cima.",n:"Ao contrário das demais tribos, contadas dos vinte anos para cima para a guerra, os levitas são contados desde o primeiro mês, porque não se trata de um exército, mas de uma consagração ao Senhor."},
{v:16,t:"Moisés os recenseou conforme a palavra do Senhor, como fora ordenado."},
{v:17,t:"Estes são os filhos de Levi pelos seus nomes: Gérson, Caat e Merari."},
{v:18,t:"Os nomes dos filhos de Gérson, por famílias: Lobni e Semei."},
{v:19,t:"Os filhos de Caat, por famílias: Amram, Isaar, Hebron e Oziel."},
{v:20,t:"Os filhos de Merari, por famílias: Mooli e Musi. Estas são as famílias de Levi, segundo as casas de seus pais."},
{v:21,t:"De Gérson procedem as famílias de Lobni e de Semei: são as famílias dos gersonitas."},
{v:22,t:"Os seus recenseados, contando todo varão de um mês para cima, foram sete mil e quinhentos."},
{v:23,t:"Acamparão atrás da Morada, ao ocidente."},
{v:24,t:"O príncipe da casa paterna dos gersonitas é Eliasaf, filho de Lael."},
{v:25,t:"O encargo dos filhos de Gérson na tenda do encontro é a Morada e a tenda, a sua cobertura e o véu da entrada da tenda do encontro,"},
{v:26,t:"as cortinas do átrio e o véu da entrada do átrio, que está ao redor da Morada e do altar, e as cordas para todo o seu serviço."},
{v:27,t:"De Caat procedem as famílias dos amramitas, dos isaaritas, dos hebronitas e dos ozielitas: são as famílias dos caatitas."},
{v:28,t:"Contando todo varão de um mês para cima, eram oito mil e seiscentos, encarregados de guardar o santuário."},
{v:29,t:"As famílias dos filhos de Caat acamparão ao lado sul da Morada."},
{v:30,t:"O príncipe da casa paterna das famílias dos caatitas é Elisafan, filho de Oziel."},
{v:31,t:"O seu encargo é a arca, a mesa, o candelabro, os altares, os utensílios do santuário com que fazem o serviço, o véu e tudo o que pertence ao seu serviço."},
{v:32,t:"O príncipe dos príncipes dos levitas é Eleazar, filho do sacerdote Aarão; a ele cabe a superintendência dos que guardam o santuário."},
{v:33,t:"De Merari procedem as famílias de Mooli e de Musi: são as famílias dos meraritas."},
{v:34,t:"Os seus recenseados, contando todo varão de um mês para cima, foram seis mil e duzentos."},
{v:35,t:"O príncipe da casa paterna é Suriel, filho de Abiail; acamparão ao lado norte da Morada."},
{v:36,t:"O encargo confiado aos filhos de Merari são as tábuas da Morada, os seus travessões, as colunas e as suas bases, todos os seus utensílios e tudo o que pertence ao seu serviço,"},
{v:37,t:"as colunas do átrio ao redor, com as suas bases, as estacas e as cordas."},
{v:38,t:"Diante da Morada, ao oriente, defronte da tenda do encontro, acamparão Moisés, Aarão e seus filhos, encarregados de guardar o santuário em favor dos filhos de Israel; o estranho que se aproximar será morto."},
{v:39,t:"Todos os levitas recenseados por Moisés e Aarão, por ordem do Senhor, segundo as suas famílias, todo varão de um mês para cima, foram vinte e dois mil."},
{v:40,t:"O Senhor disse a Moisés: Recenseia todos os primogênitos varões dos filhos de Israel, de um mês para cima, e faze a conta dos seus nomes."},
{v:41,t:"Tomarás para mim os levitas em lugar de todos os primogênitos dos filhos de Israel — eu sou o Senhor — e o gado dos levitas em lugar de todos os primogênitos do gado dos filhos de Israel."},
{v:42,t:"Moisés recenseou todos os primogênitos dos filhos de Israel, como o Senhor lhe ordenara,"},
{v:43,t:"e todos os primogênitos varões, contados os nomes de um mês para cima, foram vinte e dois mil duzentos e setenta e três."},
{v:44,t:"O Senhor falou a Moisés, dizendo:"},
{v:45,t:"Toma os levitas em lugar de todos os primogênitos dos filhos de Israel, e o gado dos levitas em lugar do seu gado; os levitas serão meus. Eu sou o Senhor."},
{v:46,t:"Para o resgate dos duzentos e setenta e três primogênitos dos filhos de Israel que excedem o número dos levitas,"},
{v:47,t:"tomarás cinco siclos por cabeça, segundo o siclo do santuário, de vinte gueras o siclo;",n:"O siclo do santuário é o padrão de peso oficial, cerca de onze gramas e meia de prata; a guera é a sua vigésima parte."},
{v:48,t:"e darás o dinheiro a Aarão e a seus filhos, como resgate dos que excedem."},
{v:49,t:"Moisés recebeu o dinheiro dos que excediam o número dos resgatados pelos levitas:"},
{v:50,t:"dos primogênitos dos filhos de Israel recebeu mil trezentos e sessenta e cinco siclos, segundo o siclo do santuário,"},
{v:51,t:"e Moisés deu o dinheiro do resgate a Aarão e a seus filhos, conforme a palavra do Senhor, como o Senhor ordenara a Moisés."}
];
