// =====================================================================
// Números — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["numeros"][1] = [
{s:"O recenseamento ordenado no Sinai"},
{v:1,t:"O Senhor falou a Moisés no deserto do Sinai, na tenda do encontro, no primeiro dia do segundo mês, no segundo ano depois da saída da terra do Egito, dizendo:",n:"O título hebraico do livro é Bemidbar, no deserto, tomado desta primeira frase; Números vem do grego e do latim, pelos dois recenseamentos que o livro narra."},
{v:2,t:"Fazei o recenseamento de toda a assembleia dos filhos de Israel, segundo as suas famílias e as casas de seus pais, contando os nomes de todo varão, um por um,"},
{v:3,t:"dos vinte anos para cima, todos os que em Israel podem sair para a guerra; tu e Aarão os contareis segundo os seus grupos."},
{v:4,t:"Convosco estará um homem de cada tribo, o chefe da casa de seus pais."},
{s:"Os chefes de cada tribo"},
{v:5,t:"Estes são os nomes dos homens que estarão convosco: de Rúben, Elisur, filho de Sedeur;"},
{v:6,t:"de Simeão, Salamiel, filho de Surisadai;"},
{v:7,t:"de Judá, Naasson, filho de Aminadab;"},
{v:8,t:"de Issacar, Natanael, filho de Suar;"},
{v:9,t:"de Zabulon, Eliab, filho de Helon;"},
{v:10,t:"dos filhos de José: de Efraim, Elisama, filho de Amiud; de Manassés, Gamaliel, filho de Fadassur;"},
{v:11,t:"de Benjamim, Abidan, filho de Gedeon;"},
{v:12,t:"de Dã, Aiezer, filho de Amisadai;"},
{v:13,t:"de Aser, Fegiel, filho de Ocran;"},
{v:14,t:"de Gad, Eliasaf, filho de Duel;"},
{v:15,t:"de Neftali, Aíra, filho de Enan."},
{v:16,t:"Estes eram os chamados da assembleia, príncipes das tribos de seus pais, chefes dos milhares de Israel."},
{s:"O recenseamento executado"},
{v:17,t:"Moisés e Aarão tomaram esses homens designados pelos seus nomes"},
{v:18,t:"e reuniram toda a assembleia no primeiro dia do segundo mês. Foram registrados por famílias, segundo as casas de seus pais, contando os nomes, dos vinte anos para cima, um por um,"},
{v:19,t:"como o Senhor ordenara a Moisés. E os recenseou no deserto do Sinai."},
{s:"Os recenseados, tribo por tribo"},
{v:20,t:"Dos filhos de Rúben, primogênito de Israel: as suas gerações por famílias e casas de seus pais, contados os nomes um por um, todo varão dos vinte anos para cima, todos os que podiam sair para a guerra;"},
{v:21,t:"os recenseados da tribo de Rúben foram quarenta e seis mil e quinhentos."},
{v:22,t:"Dos filhos de Simeão: as suas gerações por famílias e casas de seus pais, os recenseados, contados os nomes um por um, todo varão dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:23,t:"os recenseados da tribo de Simeão foram cinquenta e nove mil e trezentos."},
{v:24,t:"Dos filhos de Gad: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:25,t:"os recenseados da tribo de Gad foram quarenta e cinco mil, seiscentos e cinquenta."},
{v:26,t:"Dos filhos de Judá: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:27,t:"os recenseados da tribo de Judá foram setenta e quatro mil e seiscentos."},
{v:28,t:"Dos filhos de Issacar: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:29,t:"os recenseados da tribo de Issacar foram cinquenta e quatro mil e quatrocentos."},
{v:30,t:"Dos filhos de Zabulon: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:31,t:"os recenseados da tribo de Zabulon foram cinquenta e sete mil e quatrocentos."},
{v:32,t:"Dos filhos de José, dos filhos de Efraim: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:33,t:"os recenseados da tribo de Efraim foram quarenta mil e quinhentos."},
{v:34,t:"Dos filhos de Manassés: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:35,t:"os recenseados da tribo de Manassés foram trinta e dois mil e duzentos."},
{v:36,t:"Dos filhos de Benjamim: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:37,t:"os recenseados da tribo de Benjamim foram trinta e cinco mil e quatrocentos."},
{v:38,t:"Dos filhos de Dã: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:39,t:"os recenseados da tribo de Dã foram sessenta e dois mil e setecentos."},
{v:40,t:"Dos filhos de Aser: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:41,t:"os recenseados da tribo de Aser foram quarenta e um mil e quinhentos."},
{v:42,t:"Dos filhos de Neftali: as suas gerações por famílias e casas de seus pais, contados os nomes dos vinte anos para cima, todos os que podiam sair para a guerra;",np:1},
{v:43,t:"os recenseados da tribo de Neftali foram cinquenta e três mil e quatrocentos."},
{s:"A soma de todos os recenseados"},
{v:44,t:"Estes são os que Moisés e Aarão recensearam, com os doze príncipes de Israel, um por cada casa paterna."},
{v:45,t:"Todos os recenseados dos filhos de Israel, segundo as casas de seus pais, dos vinte anos para cima, todos os que em Israel podiam sair para a guerra,"},
{v:46,t:"todos os recenseados foram seiscentos e três mil, quinhentos e cinquenta.",n:"O número, muito elevado para um grupo em marcha pelo deserto, é discutido desde a antiguidade: a palavra elef, mil, designa também o clã ou o contingente que ele fornecia, o que permitiria uma leitura bem menor. Conservo a tradução literal, que é a da tradição."},
{s:"Os levitas postos à parte"},
{v:47,t:"Mas os levitas, segundo a tribo de seus pais, não foram recenseados entre eles."},
{v:48,t:"O Senhor falou a Moisés, dizendo:"},
{v:49,t:"Não recensearás a tribo de Levi nem contarás os seus filhos entre os filhos de Israel;"},
{v:50,t:"mas confia aos levitas a Morada do testemunho, todos os seus utensílios e tudo o que pertence a ela. Eles levarão a Morada e todos os seus utensílios, prestarão nela o serviço e acamparão ao redor dela.",np:1,n:"Morada traduz mishkan, a tenda santa como lugar em que o Senhor habita no meio do povo; testemunho, edut, são as tábuas da Lei guardadas na arca."},
{v:51,t:"Quando a Morada tiver de partir, os levitas a desmontarão; quando tiver de acampar, os levitas a levantarão; o estranho que se aproximar será morto."},
{v:52,t:"Os filhos de Israel acamparão cada um no seu acampamento e cada um junto ao seu estandarte, segundo os seus grupos;"},
{v:53,t:"mas os levitas acamparão ao redor da Morada do testemunho, para que não haja ira sobre a assembleia dos filhos de Israel; e os levitas guardarão o encargo da Morada do testemunho."},
{v:54,t:"Os filhos de Israel fizeram tudo o que o Senhor ordenara a Moisés; assim fizeram."}
];

window.TEXTOS_SEED["numeros"][2] = [
{s:"A ordem do acampamento"},
{v:1,t:"O Senhor falou a Moisés e a Aarão, dizendo:"},
{v:2,t:"Os filhos de Israel acamparão cada um junto ao seu estandarte, sob as insígnias das casas de seus pais; acamparão ao redor da tenda do encontro, defronte dela."},
{s:"A leste: Judá, Issacar e Zabulon"},
{v:3,t:"Ao oriente acampará o estandarte do acampamento de Judá, segundo os seus grupos; o príncipe dos filhos de Judá é Naasson, filho de Aminadab,"},
{v:4,t:"e o seu exército recenseado é de setenta e quatro mil e seiscentos."},
{v:5,t:"Junto a ele acampará a tribo de Issacar; o seu príncipe é Natanael, filho de Suar,",np:1},
{v:6,t:"e o seu exército recenseado é de cinquenta e quatro mil e quatrocentos."},
{v:7,t:"Depois, a tribo de Zabulon; o príncipe dos filhos de Zabulon é Eliab, filho de Helon,",np:1},
{v:8,t:"e o seu exército recenseado é de cinquenta e sete mil e quatrocentos."},
{v:9,t:"Todos os recenseados do acampamento de Judá são cento e oitenta e seis mil e quatrocentos, segundo os seus grupos; estes marcharão primeiro.",np:1},
{s:"Ao sul: Rúben, Simeão e Gad"},
{v:10,t:"Ao sul, o estandarte do acampamento de Rúben, segundo os seus grupos; o seu príncipe é Elisur, filho de Sedeur,"},
{v:11,t:"e o seu exército recenseado é de quarenta e seis mil e quinhentos."},
{v:12,t:"Junto a ele acampará a tribo de Simeão; o seu príncipe é Salamiel, filho de Surisadai,",np:1},
{v:13,t:"e o seu exército recenseado é de cinquenta e nove mil e trezentos."},
{v:14,t:"Depois, a tribo de Gad; o seu príncipe é Eliasaf, filho de Duel,",np:1},
{v:15,t:"e o seu exército recenseado é de quarenta e cinco mil, seiscentos e cinquenta."},
{v:16,t:"Todos os recenseados do acampamento de Rúben são cento e cinquenta e um mil, quatrocentos e cinquenta, segundo os seus grupos; marcharão em segundo lugar.",np:1},
{s:"A tenda do encontro no meio do arraial"},
{v:17,t:"Então partirá a tenda do encontro, com o acampamento dos levitas no meio dos demais acampamentos; como acamparem, assim marcharão, cada um no seu lugar, junto ao seu estandarte."},
{s:"A oeste: Efraim, Manassés e Benjamim"},
{v:18,t:"Ao ocidente, o estandarte do acampamento de Efraim, segundo os seus grupos; o seu príncipe é Elisama, filho de Amiud,"},
{v:19,t:"e o seu exército recenseado é de quarenta mil e quinhentos."},
{v:20,t:"Junto a ele, a tribo de Manassés; o seu príncipe é Gamaliel, filho de Fadassur,",np:1},
{v:21,t:"e o seu exército recenseado é de trinta e dois mil e duzentos."},
{v:22,t:"Depois, a tribo de Benjamim; o seu príncipe é Abidan, filho de Gedeon,",np:1},
{v:23,t:"e o seu exército recenseado é de trinta e cinco mil e quatrocentos."},
{v:24,t:"Todos os recenseados do acampamento de Efraim são cento e oito mil e cem, segundo os seus grupos; marcharão em terceiro lugar.",np:1},
{s:"Ao norte: Dã, Aser e Neftali"},
{v:25,t:"Ao norte, o estandarte do acampamento de Dã, segundo os seus grupos; o seu príncipe é Aiezer, filho de Amisadai,"},
{v:26,t:"e o seu exército recenseado é de sessenta e dois mil e setecentos."},
{v:27,t:"Junto a ele acampará a tribo de Aser; o seu príncipe é Fegiel, filho de Ocran,",np:1},
{v:28,t:"e o seu exército recenseado é de quarenta e um mil e quinhentos."},
{v:29,t:"Depois, a tribo de Neftali; o seu príncipe é Aíra, filho de Enan,",np:1},
{v:30,t:"e o seu exército recenseado é de cinquenta e três mil e quatrocentos."},
{v:31,t:"Todos os recenseados do acampamento de Dã são cento e cinquenta e sete mil e seiscentos; marcharão por último, junto aos seus estandartes.",np:1},
{s:"A soma e a conclusão"},
{v:32,t:"Estes são os recenseados dos filhos de Israel, segundo as casas de seus pais; todos os recenseados dos acampamentos, segundo os seus grupos, foram seiscentos e três mil, quinhentos e cinquenta."},
{v:33,t:"Mas os levitas não foram recenseados entre os filhos de Israel, como o Senhor ordenara a Moisés."},
{v:34,t:"E os filhos de Israel fizeram tudo o que o Senhor ordenara a Moisés: assim acampavam junto aos seus estandartes e assim marchavam, cada um segundo as suas famílias e as casas de seus pais."}
];

window.TEXTOS_SEED["numeros"][3] = [
{s:"Os filhos de Aarão"},
{v:1,t:"Estas são as gerações de Aarão e de Moisés, no dia em que o Senhor falou com Moisés no monte Sinai."},
{v:2,t:"Estes são os nomes dos filhos de Aarão: o primogênito Nadab, depois Abiú, Eleazar e Itamar."},
{v:3,t:"Estes são os nomes dos filhos de Aarão, sacerdotes ungidos, cujas mãos foram consagradas para exercerem o sacerdócio."},
{v:4,t:"Nadab e Abiú morreram diante do Senhor, quando ofereceram fogo estranho diante do Senhor no deserto do Sinai, e não tiveram filhos; Eleazar e Itamar exerceram o sacerdócio na presença de Aarão, seu pai."},
{s:"Os levitas dados a Aarão"},
{v:5,t:"O Senhor falou a Moisés, dizendo:"},
{v:6,t:"Faze aproximar a tribo de Levi e apresenta-a diante do sacerdote Aarão, para que o sirvam"},
{v:7,t:"e cumpram o seu encargo e o encargo de toda a assembleia diante da tenda do encontro, prestando o serviço da Morada."},
{v:8,t:"Guardarão todos os utensílios da tenda do encontro e cumprirão o encargo dos filhos de Israel, prestando o serviço da Morada."},
{v:9,t:"Darás os levitas a Aarão e a seus filhos: dentre os filhos de Israel, estão inteiramente entregues a eles."},
{v:10,t:"A Aarão e a seus filhos confiarás o sacerdócio; o estranho que se aproximar será morto."},
{s:"Os levitas em lugar dos primogênitos"},
{v:11,t:"O Senhor falou a Moisés, dizendo:"},
{v:12,t:"Eis que eu tomei os levitas dentre os filhos de Israel, em lugar de todo primogênito que abre o ventre entre os filhos de Israel; os levitas serão meus,"},
{v:13,t:"porque todo primogênito é meu. No dia em que feri todos os primogênitos na terra do Egito, consagrei para mim todo primogênito em Israel, de homem e de animal: serão meus. Eu sou o Senhor."},
{s:"Recenseamento dos levitas"},
{v:14,t:"O Senhor falou a Moisés no deserto do Sinai, dizendo:"},
{v:15,t:"Recenseia os filhos de Levi segundo as casas de seus pais e as suas famílias; recensearás todo varão de um mês para cima.",n:"Ao contrário das demais tribos, contadas dos vinte anos para cima para a guerra, os levitas são contados desde o primeiro mês, porque não se trata de um exército, mas de uma consagração ao Senhor."},
{v:16,t:"Moisés os recenseou conforme a palavra do Senhor, como fora ordenado."},
{v:17,t:"Estes são os filhos de Levi pelos seus nomes: Gérson, Caat e Merari.",np:1},
{v:18,t:"Os nomes dos filhos de Gérson, por famílias: Lobni e Semei."},
{v:19,t:"Os filhos de Caat, por famílias: Amram, Isaar, Hebron e Oziel."},
{v:20,t:"Os filhos de Merari, por famílias: Mooli e Musi. Estas são as famílias de Levi, segundo as casas de seus pais."},
{s:"Os gérsonitas"},
{v:21,t:"De Gérson procedem as famílias de Lobni e de Semei: são as famílias dos gersonitas."},
{v:22,t:"Os seus recenseados, contando todo varão de um mês para cima, foram sete mil e quinhentos."},
{v:23,t:"Acamparão atrás da Morada, ao ocidente."},
{v:24,t:"O príncipe da casa paterna dos gersonitas é Eliasaf, filho de Lael.",np:1},
{v:25,t:"O encargo dos filhos de Gérson na tenda do encontro é a Morada e a tenda, a sua cobertura e o véu da entrada da tenda do encontro,"},
{v:26,t:"as cortinas do átrio e o véu da entrada do átrio, que está ao redor da Morada e do altar, e as cordas para todo o seu serviço."},
{s:"Os caatitas"},
{v:27,t:"De Caat procedem as famílias dos amramitas, dos isaaritas, dos hebronitas e dos ozielitas: são as famílias dos caatitas."},
{v:28,t:"Contando todo varão de um mês para cima, eram oito mil e seiscentos, encarregados de guardar o santuário."},
{v:29,t:"As famílias dos filhos de Caat acamparão ao lado sul da Morada."},
{v:30,t:"O príncipe da casa paterna das famílias dos caatitas é Elisafan, filho de Oziel.",np:1},
{v:31,t:"O seu encargo é a arca, a mesa, o candelabro, os altares, os utensílios do santuário com que fazem o serviço, o véu e tudo o que pertence ao seu serviço."},
{v:32,t:"O príncipe dos príncipes dos levitas é Eleazar, filho do sacerdote Aarão; a ele cabe a superintendência dos que guardam o santuário."},
{s:"Os meraritas"},
{v:33,t:"De Merari procedem as famílias de Mooli e de Musi: são as famílias dos meraritas."},
{v:34,t:"Os seus recenseados, contando todo varão de um mês para cima, foram seis mil e duzentos."},
{v:35,t:"O príncipe da casa paterna é Suriel, filho de Abiail; acamparão ao lado norte da Morada.",np:1},
{v:36,t:"O encargo confiado aos filhos de Merari são as tábuas da Morada, os seus travessões, as colunas e as suas bases, todos os seus utensílios e tudo o que pertence ao seu serviço,"},
{v:37,t:"as colunas do átrio ao redor, com as suas bases, as estacas e as cordas."},
{s:"Moisés e Aarão diante da tenda"},
{v:38,t:"Diante da Morada, ao oriente, defronte da tenda do encontro, acamparão Moisés, Aarão e seus filhos, encarregados de guardar o santuário em favor dos filhos de Israel; o estranho que se aproximar será morto."},
{v:39,t:"Todos os levitas recenseados por Moisés e Aarão, por ordem do Senhor, segundo as suas famílias, todo varão de um mês para cima, foram vinte e dois mil."},
{s:"O recenseamento dos primogênitos"},
{v:40,t:"O Senhor disse a Moisés: Recenseia todos os primogênitos varões dos filhos de Israel, de um mês para cima, e faze a conta dos seus nomes."},
{v:41,t:"Tomarás para mim os levitas em lugar de todos os primogênitos dos filhos de Israel — eu sou o Senhor — e o gado dos levitas em lugar de todos os primogênitos do gado dos filhos de Israel."},
{v:42,t:"Moisés recenseou todos os primogênitos dos filhos de Israel, como o Senhor lhe ordenara,"},
{v:43,t:"e todos os primogênitos varões, contados os nomes de um mês para cima, foram vinte e dois mil duzentos e setenta e três."},
{s:"O resgate dos primogênitos"},
{v:44,t:"O Senhor falou a Moisés, dizendo:"},
{v:45,t:"Toma os levitas em lugar de todos os primogênitos dos filhos de Israel, e o gado dos levitas em lugar do seu gado; os levitas serão meus. Eu sou o Senhor."},
{v:46,t:"Para o resgate dos duzentos e setenta e três primogênitos dos filhos de Israel que excedem o número dos levitas,",np:1},
{v:47,t:"tomarás cinco siclos por cabeça, segundo o siclo do santuário, de vinte gueras o siclo;",n:"O siclo do santuário é o padrão de peso oficial, cerca de onze gramas e meia de prata; a guera é a sua vigésima parte."},
{v:48,t:"e darás o dinheiro a Aarão e a seus filhos, como resgate dos que excedem."},
{v:49,t:"Moisés recebeu o dinheiro dos que excediam o número dos resgatados pelos levitas:",np:1},
{v:50,t:"dos primogênitos dos filhos de Israel recebeu mil trezentos e sessenta e cinco siclos, segundo o siclo do santuário,"},
{v:51,t:"e Moisés deu o dinheiro do resgate a Aarão e a seus filhos, conforme a palavra do Senhor, como o Senhor ordenara a Moisés."}
];

window.TEXTOS_SEED["numeros"][4] = [
{s:"O recenseamento dos caatitas"},
{v:1,t:"O Senhor falou a Moisés e a Aarão, dizendo:"},
{v:2,t:"Fazei o recenseamento dos filhos de Caat, dentre os filhos de Levi, segundo as suas famílias e as casas de seus pais,"},
{v:3,t:"dos trinta aos cinquenta anos, de todos os que entram no serviço para trabalhar na tenda do encontro.",n:"A idade não vale para o levita em geral, mas para o que carrega o santuário em marcha: pedia-se a força de um homem feito. Em 8,24 o começo do serviço é aos vinte e cinco anos, e a diferença sempre deu que pensar aos comentadores."},
{v:4,t:"Este é o ofício dos filhos de Caat na tenda do encontro: as coisas santíssimas."},
{s:"O que Aarão e seus filhos hão de cobrir"},
{v:5,t:"Quando o arraial partir, Aarão e seus filhos entrarão, tirarão o véu que pende diante da arca do testemunho e com ele cobrirão a arca;"},
{v:6,t:"porão sobre ela uma cobertura de peles finas, estenderão por cima um pano todo de púrpura violácea e ajustarão os varais.",n:"Peles finas traduz tahash, palavra de sentido incerto: já se entendeu pele de golfinho, de dugongo ou couro tratado. O certo é tratar-se da cobertura exterior, resistente à intempérie."},
{v:7,t:"Sobre a mesa da proposição estenderão um pano de púrpura violácea e porão sobre ele os pratos, as taças, as tigelas e os copos das libações; o pão estará sempre sobre ela.",np:1},
{v:8,t:"Estenderão por cima um pano de carmesim, que cobrirão com uma cobertura de peles finas, e ajustarão os varais."},
{v:9,t:"Tomarão um pano de púrpura violácea e cobrirão o candelabro com as suas lâmpadas, as suas tenazes, os seus apagadores e todos os vasos do azeite necessários ao serviço das lâmpadas;",np:1},
{v:10,t:"e o porão, com todos os seus utensílios, numa cobertura de peles finas, e o colocarão sobre os varais."},
{v:11,t:"Sobre o altar de ouro estenderão um pano de púrpura violácea, o cobrirão com uma cobertura de peles finas e ajustarão os varais.",np:1},
{v:12,t:"Tomarão todos os utensílios do serviço com que servem no santuário, os envolverão num pano de púrpura violácea, os cobrirão com uma cobertura de peles finas e os porão sobre os varais."},
{v:13,t:"Tirarão as cinzas do altar e estenderão sobre ele um pano de púrpura escarlate;",np:1},
{v:14,t:"porão sobre ele todos os utensílios com que servem no altar: os braseiros, os garfos, as pás e as bacias; cobrirão o altar com uma cobertura de peles finas e ajustarão os varais."},
{s:"O encargo dos caatitas"},
{v:15,t:"Quando Aarão e seus filhos acabarem de cobrir o santuário e todos os seus utensílios, ao partir o arraial, os filhos de Caat virão para os levar; mas não tocarão as coisas santas, para que não morram. Este é o encargo dos filhos de Caat na tenda do encontro.",n:"Os caatitas carregam o mais santo, e é justamente por isso que não podem tocá-lo: só o levam depois de coberto pelos sacerdotes. É a morte de Oza, em 2 Samuel 6, que mostra o que estava em jogo."},
{v:16,t:"A Eleazar, filho do sacerdote Aarão, cabe o cuidado do azeite das lâmpadas, do incenso aromático, da oblação perpétua e do óleo da unção: o cuidado de todo o tabernáculo e de tudo o que nele há, do santuário e dos seus utensílios."},
{s:"Aviso para que os caatitas não pereçam"},
{v:17,t:"O Senhor falou a Moisés e a Aarão, dizendo:"},
{v:18,t:"Não deixeis que a tribo das famílias dos caatitas seja exterminada do meio dos levitas."},
{v:19,t:"Fazei assim com eles, para que vivam e não morram ao aproximar-se das coisas santíssimas: Aarão e seus filhos entrarão e designarão a cada um o seu serviço e o que há de levar."},
{v:20,t:"E eles não entrem para ver, nem por um instante, as coisas santas, para que não morram."},
{s:"O recenseamento e o encargo dos gérsonitas"},
{v:21,t:"O Senhor falou a Moisés, dizendo:"},
{v:22,t:"Faze também o recenseamento dos filhos de Gérson, segundo as casas de seus pais e as suas famílias;"},
{v:23,t:"dos trinta aos cinquenta anos recensearás todos os que entram no serviço para trabalhar na tenda do encontro."},
{v:24,t:"Este é o ofício das famílias dos gérsonitas, no que hão de fazer e levar:",np:1},
{v:25,t:"levarão as cortinas do tabernáculo, a tenda do encontro com a sua cobertura, a cobertura de peles finas que se põe por cima e o véu da entrada da tenda do encontro;"},
{v:26,t:"as cortinas do átrio e o véu da entrada do átrio que está ao redor do tabernáculo e do altar, as suas cordas e todos os utensílios do seu serviço; e farão tudo o que a isso pertence."},
{v:27,t:"Todo o serviço dos filhos de Gérson será feito por ordem de Aarão e de seus filhos, tudo o que hão de levar e fazer; e confiareis ao seu cuidado tudo o que lhes cabe levar.",np:1},
{v:28,t:"Este é o ofício das famílias dos gérsonitas na tenda do encontro; e estarão sob a direção de Itamar, filho do sacerdote Aarão."},
{s:"O recenseamento e o encargo dos meraritas"},
{v:29,t:"Recensearás também os filhos de Merari, segundo as suas famílias e as casas de seus pais;"},
{v:30,t:"dos trinta aos cinquenta anos recensearás todos os que entram no serviço para trabalhar na tenda do encontro."},
{v:31,t:"Este é o encargo do que hão de levar, segundo todo o seu serviço na tenda do encontro: as tábuas do tabernáculo, os seus travessões, as suas colunas e as suas bases;",np:1},
{v:32,t:"as colunas do átrio ao redor, com as suas bases, as suas estacas e as suas cordas, com todos os seus utensílios e tudo o que a eles pertence. Designareis por nome os objetos que a cada um cabe levar."},
{v:33,t:"Este é o ofício das famílias dos filhos de Merari, segundo todo o seu serviço na tenda do encontro, sob a direção de Itamar, filho do sacerdote Aarão."},
{s:"Os levitas recenseados"},
{v:34,t:"Moisés, Aarão e os príncipes da assembleia recensearam os filhos dos caatitas, segundo as suas famílias e as casas de seus pais,"},
{v:35,t:"dos trinta aos cinquenta anos, todos os que entram no serviço para trabalhar na tenda do encontro;"},
{v:36,t:"e os recenseados por famílias foram dois mil setecentos e cinquenta."},
{v:37,t:"Estes são os recenseados das famílias dos caatitas, todos os que servem na tenda do encontro, os que Moisés e Aarão recensearam por ordem do Senhor, dada por meio de Moisés."},
{v:38,t:"Os filhos de Gérson foram recenseados segundo as suas famílias e as casas de seus pais,",np:1},
{v:39,t:"dos trinta aos cinquenta anos, todos os que entram no serviço para trabalhar na tenda do encontro;"},
{v:40,t:"e os recenseados, por famílias e casas de seus pais, foram dois mil seiscentos e trinta."},
{v:41,t:"Estes são os recenseados das famílias dos filhos de Gérson, todos os que servem na tenda do encontro, os que Moisés e Aarão recensearam por ordem do Senhor."},
{v:42,t:"As famílias dos filhos de Merari foram recenseadas segundo as suas famílias e as casas de seus pais,",np:1},
{v:43,t:"dos trinta aos cinquenta anos, todos os que entram no serviço para trabalhar na tenda do encontro;"},
{v:44,t:"e os recenseados por famílias foram três mil e duzentos."},
{v:45,t:"Estes são os recenseados das famílias dos filhos de Merari, os que Moisés e Aarão recensearam por ordem do Senhor, dada por meio de Moisés."},
{v:46,t:"Todos os levitas que Moisés, Aarão e os príncipes de Israel recensearam, segundo as suas famílias e as casas de seus pais,",np:1},
{v:47,t:"dos trinta aos cinquenta anos, todos os que entravam para fazer o serviço e para levar as cargas na tenda do encontro,"},
{v:48,t:"foram oito mil quinhentos e oitenta."},
{v:49,t:"Por ordem do Senhor, dada por meio de Moisés, foi designado a cada um o seu serviço e a sua carga, conforme o Senhor ordenara a Moisés."}
];

window.TEXTOS_SEED["numeros"][5] = [
{s:"Os impuros afastados do arraial"},
{v:1,t:"O Senhor falou a Moisés, dizendo:"},
{v:2,t:"Ordena aos filhos de Israel que lancem fora do arraial todo leproso, todo o que tem fluxo e todo o que está impuro por causa de um morto."},
{v:3,t:"Lançareis fora tanto o homem como a mulher, para fora do arraial, a fim de que não o contaminem, pois eu habito no meio dele.",n:"A razão dada não é sanitária, mas a presença de Deus no meio do povo: é ela que torna o arraial um lugar que se pode profanar."},
{v:4,t:"Os filhos de Israel assim fizeram, e os lançaram fora do arraial; como o Senhor dissera a Moisés, assim fizeram."},
{s:"A restituição pelo dano"},
{v:5,t:"O Senhor falou a Moisés, dizendo:"},
{v:6,t:"Dize aos filhos de Israel: Quando um homem ou uma mulher cometer algum dos pecados que os homens costumam cometer, sendo infiel ao Senhor, e essa alma for culpada,"},
{v:7,t:"confessará o seu pecado e restituirá integralmente o dano, acrescentando-lhe a quinta parte, e o dará àquele contra quem pecou.",n:"O dano ao próximo é tratado como infidelidade ao Senhor, e por isso a reparação tem duas faces: a restituição a quem se lesou e o sacrifício diante de Deus."},
{v:8,t:"Se não houver quem receba a restituição, ela será do Senhor e caberá ao sacerdote, além do carneiro da expiação, com que se fará expiação por ele."},
{v:9,t:"Toda oferta que os filhos de Israel consagrarem e apresentarem ao sacerdote será dele.",np:1},
{v:10,t:"As coisas consagradas por qualquer um são dele; e o que alguém der ao sacerdote, ao sacerdote pertence."},
{s:"A lei do ciúme"},
{v:11,t:"O Senhor falou a Moisés, dizendo:"},
{v:12,t:"Fala aos filhos de Israel e dize a eles: Se a mulher de alguém se desviar e lhe for infiel,"},
{v:13,t:"e outro homem se deitar com ela, sem que o marido o saiba, e ela se tiver contaminado em segredo, e não houver testemunha contra ela nem for apanhada,"},
{v:14,t:"mas sobrevier ao marido o espírito de ciúme, e ele tiver ciúmes da mulher que se contaminou — ou lhe sobrevier o espírito de ciúme, e ele tiver ciúmes dela sem que ela se tenha contaminado —,"},
{v:15,t:"o homem levará a sua mulher ao sacerdote e apresentará por ela a oferta devida: a décima parte de um efá de farinha de cevada; não derramará azeite sobre ela nem porá incenso, porque é oblação de ciúme, oblação de lembrança, que traz o pecado à memória.",n:"Cevada, e não trigo; sem azeite nem incenso: a oferta é despojada de tudo o que faz a alegria das outras, e o próprio material diz o que ali se passa."},
{v:16,t:"O sacerdote a fará aproximar-se e a porá diante do Senhor.",np:1},
{v:17,t:"Tomará água santa num vaso de barro e, do pó do chão do tabernáculo, lançará na água."},
{v:18,t:"Estando a mulher diante do Senhor, o sacerdote lhe descobrirá a cabeça e lhe porá nas mãos a oblação de lembrança, que é a oblação de ciúme; e na sua mão terá a água amarga que traz maldição."},
{v:19,t:"E a conjurará, dizendo: Se nenhum homem se deitou contigo, e se não te desviaste para a impureza, deixando o teu marido, estas águas amargas que trazem maldição não te façam mal.",np:1},
{v:20,t:"Mas, se te desviaste do teu marido e te contaminaste, e algum homem, além do teu marido, se deitou contigo —"},
{v:21,t:"então o sacerdote conjurará a mulher com o juramento da maldição, e dirá a ela: O Senhor te ponha por maldição e imprecação no meio do teu povo, fazendo apodrecer as tuas entranhas e inchar o teu ventre."},
{v:22,t:"Entrem estas águas que trazem maldição nas tuas entranhas, para que inche o teu ventre e apodreçam as tuas entranhas. E a mulher responderá: Amém, amém."},
{v:23,t:"O sacerdote escreverá num rolo estas maldições e as apagará na água amarga,",np:1,n:"A maldição escrita é diluída na água e bebida: o rito não fere ninguém, entrega o julgamento a Deus. De todas as provas do antigo Oriente, esta é a única cujo elemento — água, pó do santuário e tinta — é inofensivo."},
{v:24,t:"e dará a beber à mulher as águas amargas que trazem maldição; e as águas da maldição entrarão nela e se tornarão amargas."},
{v:25,t:"O sacerdote tomará da mão da mulher a oblação de ciúme, a agitará diante do Senhor e a apresentará sobre o altar;"},
{v:26,t:"tomará da oblação um punhado, como memorial, e o queimará sobre o altar; depois dará a beber à mulher as águas."},
{v:27,t:"Depois de lhe dar a beber, sucederá que, se ela se contaminou e foi infiel ao seu marido, as águas da maldição entrarão nela e se tornarão amargas: o seu ventre inchará e as suas entranhas apodrecerão, e ela será por maldição no meio do seu povo.",np:1},
{v:28,t:"Mas, se a mulher não se contaminou e está pura, ficará ilesa e terá filhos."},
{v:29,t:"Esta é a lei do ciúme, quando a mulher se desvia do seu marido e se contamina,",np:1},
{v:30,t:"ou quando ao homem sobrevém o espírito de ciúme e ele tem ciúmes da sua mulher: há de apresentá-la diante do Senhor, e o sacerdote fará com ela tudo o que está nesta lei."},
{v:31,t:"O marido ficará sem culpa, e a mulher levará a sua iniquidade."}
];

window.TEXTOS_SEED["numeros"][6] = [
{s:"O voto de nazireu"},
{v:1,t:"O Senhor falou a Moisés, dizendo:"},
{v:2,t:"Fala aos filhos de Israel e dize a eles: Quando um homem ou uma mulher fizer voto de nazireu, para se consagrar ao Senhor,",n:"Nazireu vem de nazir, o separado, o consagrado; nada tem que ver com Nazaré, embora o parentesco sonoro tenha dado azo a confusões antigas. O voto era temporário, e qualquer um podia fazê-lo, homem ou mulher."},
{v:3,t:"há de abster-se de vinho e de bebida forte; não beberá vinagre de vinho nem vinagre de bebida forte, nem suco algum de uvas, nem comerá uvas frescas ou secas."},
{v:4,t:"Todos os dias da sua consagração não comerá nada do que se faz da videira, desde os caroços até à casca."},
{v:5,t:"Todos os dias do voto da sua consagração, navalha não passará sobre a sua cabeça; até se cumprirem os dias em que está consagrado ao Senhor, será santo, e deixará crescer livremente o cabelo da sua cabeça.",np:1},
{v:6,t:"Todos os dias em que está consagrado ao Senhor, não se aproximará de nenhum morto;"},
{v:7,t:"nem por seu pai, nem por sua mãe, nem por seu irmão, nem por sua irmã se contaminará quando morrerem, porque a consagração do seu Deus está sobre a sua cabeça.",n:"É a mesma exigência que recai sobre o sumo sacerdote em Levítico 21,11: enquanto dura o voto, o leigo fica sujeito à regra dos que servem no santuário."},
{v:8,t:"Todos os dias da sua consagração é santo ao Senhor."},
{s:"Se alguém morre de repente junto dele"},
{v:9,t:"Se alguém morrer de repente junto dele, e assim contaminar a cabeça consagrada, rapará a cabeça no dia da sua purificação, ao sétimo dia."},
{v:10,t:"Ao oitavo dia levará duas rolas ou dois pombinhos ao sacerdote, à entrada da tenda do encontro;"},
{v:11,t:"e o sacerdote oferecerá um pelo pecado e o outro em holocausto, e fará expiação por ele, do que pecou por causa do morto; e naquele mesmo dia consagrará de novo a sua cabeça."},
{v:12,t:"Consagrará ao Senhor os dias da sua consagração e trará um cordeiro de um ano como sacrifício de reparação; os dias anteriores serão perdidos, porque a sua consagração foi contaminada."},
{s:"O cumprimento do voto"},
{v:13,t:"Esta é a lei do nazireu: no dia em que se cumprirem os dias da sua consagração, será levado à entrada da tenda do encontro,"},
{v:14,t:"e apresentará a sua oferta ao Senhor: um cordeiro de um ano, sem defeito, em holocausto; uma cordeira de um ano, sem defeito, pelo pecado; e um carneiro sem defeito, como sacrifício pacífico;"},
{v:15,t:"um cesto de pães ázimos de flor de farinha amassados com azeite, e bolos ázimos untados de azeite, com a sua oblação e as suas libações."},
{v:16,t:"O sacerdote os apresentará diante do Senhor e oferecerá o sacrifício pelo pecado e o holocausto;",np:1},
{v:17,t:"e oferecerá o carneiro como sacrifício pacífico ao Senhor, com o cesto dos pães ázimos; e o sacerdote fará também a sua oblação e as suas libações."},
{v:18,t:"Então o nazireu rapará, à entrada da tenda do encontro, a sua cabeça consagrada, tomará os cabelos da sua cabeça consagrada e os porá no fogo que está sob o sacrifício pacífico.",np:1},
{v:19,t:"O sacerdote tomará a espádua cozida do carneiro, um pão ázimo do cesto e um bolo ázimo, e os porá nas mãos do nazireu, depois de este ter rapado a sua consagração;"},
{v:20,t:"e o sacerdote os agitará como oferta diante do Senhor: é coisa santa, que cabe ao sacerdote, além do peito da oferta agitada e da coxa da oferta erguida. Depois disso o nazireu poderá beber vinho."},
{v:21,t:"Esta é a lei do nazireu que fez voto, e a sua oferta ao Senhor pela sua consagração, além do que os seus recursos permitirem; conforme o voto que fizer, assim fará, segundo a lei da sua consagração."},
{s:"A bênção sacerdotal"},
{v:22,t:"O Senhor falou a Moisés, dizendo:"},
{v:23,t:"Fala a Aarão e a seus filhos e dize: Assim abençoareis os filhos de Israel; direis a eles:"},
{v:24,l:["O Senhor te abençoe","e te guarde."],n:"No hebraico, as três bênçãos crescem de três para cinco e para sete palavras, e o nome do Senhor abre cada uma: a forma imita o que diz, uma graça que se alarga. É a mais antiga passagem bíblica de que se achou cópia — em duas lâminas de prata do século VII antes de Cristo, encontradas em Ketef Hinom, junto a Jerusalém."},
{v:25,l:["O Senhor faça brilhar sobre ti a sua face","e tenha piedade de ti."],n:"Fazer brilhar a face é, na linguagem da corte, o sorriso do rei que acolhe quem se apresenta; dito de Deus, é o favor que se concede sem que se tenha merecido."},
{v:26,l:["O Senhor volte para ti o seu rosto","e te dê a paz."],n:"Paz traduz shalom, que não é só ausência de guerra, mas a inteireza de quem nada tem quebrado — e é a última palavra da bênção, o seu termo e o seu resumo."},
{v:27,t:"Assim porão o meu nome sobre os filhos de Israel, e eu os abençoarei."}
];
