// =====================================================================
// Provérbios — tradução do hebraico (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["proverbios"][1] = [
{s:"Finalidade do livro"},
{v:1,t:"Provérbios de Salomão, filho de Davi, rei de Israel.",n:"O livro reúne várias coleções de sentenças (10,1; 22,17; 24,23; 25,1; 30,1; 31,1), atribuídas em conjunto a Salomão, o sábio por excelência (1 Reis 5,9–14)."},
{v:2,l:["Para conhecer a sabedoria e a disciplina,","para entender as palavras da inteligência;"],np:1},
{v:3,l:["para receber uma educação esclarecida,","justiça, direito e retidão;"],np:1},
{v:4,l:["para dar aos ingênuos a prudência,","ao jovem o conhecimento e a reflexão."],np:1},
{v:5,l:["Que o sábio escute e aumente o seu saber,","e o inteligente adquira a arte de se conduzir,"],np:1},
{v:6,l:["para entender o provérbio e a alegoria,","as palavras dos sábios e os seus enigmas."],np:1},
{v:7,l:["O temor do Senhor é o princípio do conhecimento;","os insensatos desprezam a sabedoria e a disciplina."],np:1,n:"O temor do Senhor: a reverência e a fidelidade a Deus. É o lema de todo o livro (9,10; 15,33)."},
{s:"Contra as más companhias"},
{v:8,l:["Escuta, meu filho, a disciplina do teu pai","e não rejeites o ensinamento da tua mãe,"]},
{v:9,l:["pois serão uma coroa graciosa para a tua cabeça","e um colar para o teu pescoço."],np:1},
{v:10,l:["Meu filho, se os pecadores quiserem te seduzir,","não consintas."],np:1},
{v:11,l:["Se disserem: Vem conosco, armemos emboscadas para derramar sangue,","façamos tocaia ao inocente sem motivo;"],np:1},
{v:12,l:["vamos engoli-los vivos, como a morada dos mortos,","inteiros, como os que descem à cova;"],np:1},
{v:13,l:["acharemos toda espécie de riquezas preciosas,","encheremos de despojos as nossas casas;"],np:1},
{v:14,l:["lança a tua sorte conosco,","teremos todos uma só bolsa;"],np:1},
{v:15,l:["meu filho, não andes com eles no caminho,","afasta o teu pé das suas veredas,"],np:1},
{v:16,l:["pois os seus pés correm para o mal","e se apressam a derramar sangue."],np:1},
{v:17,l:["É inútil estender a rede à vista de qualquer ave."],np:1},
{v:18,l:["Mas eles armam emboscadas contra o próprio sangue","e fazem tocaia contra a própria vida."],np:1},
{v:19,l:["Tais são os caminhos de todo aquele que é ávido de lucro:","o lucro tira a vida de quem o possui."],np:1},
{s:"A Sabedoria chama"},
{v:20,l:["A Sabedoria clama nas ruas,","nas praças levanta a sua voz;"],n:"A Sabedoria aparece aqui personificada, como uma mulher que fala nas praças (compare 8,1–9,6)."},
{v:21,l:["no alto dos lugares movimentados ela chama,","à entrada das portas da cidade pronuncia as suas palavras:"],np:1},
{v:22,l:["Até quando, ingênuos, amareis a ingenuidade?","Até quando os zombadores se comprazerão na zombaria","e os insensatos odiarão o conhecimento?"],np:1},
{v:23,l:["Voltai-vos para a minha repreensão:","eis que derramarei sobre vós o meu espírito","e vos darei a conhecer as minhas palavras."],np:1},
{v:24,l:["Porque eu chamei, e vós recusastes;","estendi a mão, e ninguém prestou atenção;"],np:1},
{v:25,l:["rejeitastes todos os meus conselhos","e não quisestes a minha repreensão;"],np:1},
{v:26,l:["também eu me rirei da vossa desgraça,","zombarei quando vier sobre vós o terror,"],np:1},
{v:27,l:["quando o terror vier sobre vós como uma tempestade","e a desgraça chegar como um furacão,","quando vierem sobre vós a angústia e a aflição."],np:1},
{v:28,l:["Então me chamarão, e eu não responderei;","hão de me procurar, e não me encontrarão,"],np:1},
{v:29,l:["porque odiaram o conhecimento","e não escolheram o temor do Senhor;"],np:1},
{v:30,l:["não quiseram o meu conselho","e desprezaram toda a minha repreensão."],np:1},
{v:31,l:["Comerão, pois, o fruto da sua conduta","e se fartarão dos seus próprios conselhos."],np:1},
{v:32,l:["Pois o desvio dos ingênuos os matará,","e a despreocupação dos insensatos os perderá."],np:1},
{v:33,l:["Mas quem me escuta habitará em segurança,","tranquilo, sem temer o mal."],np:1}
];

window.TEXTOS_SEED["proverbios"][2] = [
{s:"Os frutos da sabedoria"},
{v:1,l:["Meu filho, se acolheres as minhas palavras","e guardares contigo os meus mandamentos,"]},
{v:2,l:["prestando ouvido à sabedoria","e inclinando o coração para a inteligência;"],np:1},
{v:3,l:["se invocares o discernimento","e chamares em voz alta a inteligência;"],np:1},
{v:4,l:["se a procurares como a prata","e a buscares como a um tesouro escondido,"],np:1},
{v:5,l:["então compreenderás o temor do Senhor","e encontrarás o conhecimento de Deus."],np:1},
{v:6,l:["Pois é o Senhor quem dá a sabedoria;","da sua boca procedem o conhecimento e a inteligência."],np:1},
{v:7,l:["Ele reserva o êxito para os retos,","é um escudo para os que caminham na integridade,"],np:1},
{v:8,l:["guardando as veredas da justiça","e protegendo o caminho dos seus fiéis."],np:1},
{v:9,l:["Então compreenderás a justiça, o direito","e a retidão, todos os caminhos do bem."],np:1},
{v:10,l:["Pois a sabedoria entrará no teu coração,","e o conhecimento será agradável à tua alma;"],np:1},
{v:11,l:["a reflexão velará sobre ti,","e a inteligência te guardará,"],np:1},
{v:12,l:["para te livrar do mau caminho,","do homem que fala coisas perversas,"],np:1},
{v:13,l:["dos que deixam as veredas retas","para andar pelos caminhos das trevas,"],np:1},
{v:14,l:["que se alegram em fazer o mal","e exultam com as perversidades do mal,"],np:1},
{v:15,l:["cujas veredas são tortuosas","e cujos caminhos são desviados;"],np:1},
{v:16,l:["para te livrar da mulher estranha,","da estrangeira de palavras sedutoras,"],np:1,n:"A mulher estranha, a estrangeira: a mulher de outro homem, a adúltera, que não pertence ao próprio lar (compare 5,3–20; 7,5–27)."},
{v:17,l:["que abandona o companheiro da sua juventude","e esquece a aliança do seu Deus;"],np:1},
{v:18,l:["pois a sua casa se inclina para a morte,","e as suas veredas levam às sombras dos mortos;"],np:1},
{v:19,l:["nenhum dos que vão até ela volta,","nem alcança de novo as veredas da vida."],np:1},
{v:20,l:["Assim andarás no caminho dos bons","e seguirás as veredas dos justos."],np:1},
{v:21,l:["Pois os retos habitarão a terra,","e os íntegros nela permanecerão;"],np:1},
{v:22,l:["mas os ímpios serão exterminados da terra,","e os traidores serão arrancados dela."],np:1}
];

window.TEXTOS_SEED["proverbios"][3] = [
{s:"Confiança no Senhor"},
{v:1,l:["Meu filho, não esqueças o meu ensinamento,","e que o teu coração guarde os meus mandamentos,"]},
{v:2,l:["pois eles te darão longos dias,","anos de vida e paz."],np:1},
{v:3,l:["Que a bondade e a fidelidade não te abandonem:","ata-as ao teu pescoço,","escreve-as na tábua do teu coração;"],np:1},
{v:4,l:["e encontrarás favor e bom êxito","aos olhos de Deus e dos homens."],np:1},
{v:5,l:["Confia no Senhor de todo o coração","e não te apoies na tua própria inteligência."],np:1},
{v:6,l:["Em todos os teus caminhos, pensa nele,","e ele endireitará as tuas veredas."],np:1},
{v:7,l:["Não sejas sábio aos teus próprios olhos;","teme o Senhor e afasta-te do mal:"],np:1},
{v:8,l:["isso será saúde para o teu corpo","e refrigério para os teus ossos."],np:1},
{v:9,l:["Honra o Senhor com os teus bens","e com as primícias de todas as tuas colheitas;"],np:1},
{v:10,l:["e os teus celeiros se encherão com fartura,","e os teus lagares transbordarão de vinho novo."],np:1},
{v:11,l:["Meu filho, não desprezes a disciplina do Senhor,","nem te aborreças com a sua repreensão,"],np:1},
{v:12,l:["pois o Senhor repreende a quem ama,","como um pai ao filho a quem quer bem."],np:1,n:"Citado em Hebreus 12,5–6, segundo o grego: e castiga todo filho que acolhe."},
{s:"Feliz quem encontra a sabedoria"},
{v:13,l:["Feliz o homem que encontrou a sabedoria,","o homem que alcançou a inteligência!"]},
{v:14,l:["Pois ganhá-la vale mais que ganhar prata,","e o seu lucro é melhor que o ouro fino."],np:1},
{v:15,l:["Ela é mais preciosa que as pérolas,","e nada do que desejas se compara a ela."],np:1},
{v:16,l:["Na sua mão direita, longos dias;","na esquerda, riqueza e honra."],np:1},
{v:17,l:["Os seus caminhos são caminhos de delícias,","e todas as suas veredas são paz."],np:1},
{v:18,l:["Ela é árvore de vida para os que a abraçam,","e felizes os que a retêm."],np:1},
{v:19,l:["O Senhor fundou a terra com sabedoria,","firmou os céus com inteligência;"],np:1},
{v:20,l:["pelo seu conhecimento se abriram os abismos,","e as nuvens destilam o orvalho."],np:1},
{v:21,l:["Meu filho, que elas não se afastem dos teus olhos:","guarda o bom senso e a reflexão;"],np:1},
{v:22,l:["serão vida para a tua alma","e adorno para o teu pescoço."],np:1},
{v:23,l:["Então andarás seguro pelo teu caminho,","e o teu pé não tropeçará."],np:1},
{v:24,l:["Se te deitares, não terás medo;","repousarás, e o teu sono será tranquilo."],np:1},
{v:25,l:["Não temas o terror repentino,","nem a ruína dos ímpios, quando vier,"],np:1},
{v:26,l:["pois o Senhor será a tua confiança","e guardará o teu pé da armadilha."],np:1},
{s:"Deveres para com o próximo"},
{v:27,l:["Não negues um benefício a quem dele precisa,","quando está em teu poder fazê-lo."]},
{v:28,l:["Não digas ao teu próximo: Vai e volta,","amanhã te darei, quando o tens contigo."],np:1},
{v:29,l:["Não trames o mal contra o teu próximo,","quando ele vive confiante ao teu lado."],np:1},
{v:30,l:["Não brigues com ninguém sem motivo,","se não te fez nenhum mal."],np:1},
{v:31,l:["Não invejes o homem violento,","nem escolhas nenhum dos seus caminhos,"],np:1},
{v:32,l:["pois o perverso é abominação para o Senhor,","mas ele tem intimidade com os retos."],np:1},
{v:33,l:["A maldição do Senhor está na casa do ímpio,","mas ele abençoa a morada dos justos."],np:1},
{v:34,l:["Ele zomba dos zombadores,","mas aos humildes concede a sua graça."],np:1,n:"Citado segundo o grego em Tiago 4,6 e 1 Pedro 5,5: Deus resiste aos soberbos, mas dá a sua graça aos humildes."},
{v:35,l:["Os sábios herdarão a honra,","mas os insensatos só acumulam desonra."],np:1}
];

window.TEXTOS_SEED["proverbios"][4] = [
{s:"Adquire a sabedoria"},
{v:1,l:["Escutai, filhos, a disciplina de um pai;","prestai atenção para conhecer a inteligência,"]},
{v:2,l:["pois eu vos dou uma boa doutrina:","não abandoneis o meu ensinamento."],np:1},
{v:3,l:["Também eu fui filho para o meu pai,","terno e único aos olhos da minha mãe."],np:1},
{v:4,l:["Ele me ensinava e me dizia:","Que o teu coração retenha as minhas palavras;","guarda os meus mandamentos e viverás."],np:1},
{v:5,l:["Adquire a sabedoria, adquire a inteligência;","não esqueças as palavras da minha boca nem te desvies delas."],np:1},
{v:6,l:["Não a abandones, e ela te guardará;","ama-a, e ela te protegerá."],np:1},
{v:7,l:["O princípio da sabedoria é: adquire a sabedoria;","com tudo o que possuis, adquire a inteligência."],np:1},
{v:8,l:["Estima-a, e ela te exaltará;","ela te honrará, se a abraçares."],np:1},
{v:9,l:["Porá na tua cabeça uma coroa graciosa,","te dará um diadema de glória."],np:1},
{s:"Os dois caminhos"},
{v:10,l:["Escuta, meu filho, e acolhe as minhas palavras,","e se multiplicarão os anos da tua vida."]},
{v:11,l:["Eu te ensinei o caminho da sabedoria,","te conduzi pelas veredas da retidão."],np:1},
{v:12,l:["Quando andares, os teus passos não serão estorvados;","se correres, não tropeçarás."],np:1},
{v:13,l:["Agarra-te à disciplina, não a largues;","guarda-a, porque ela é a tua vida."],np:1},
{v:14,l:["Não entres na vereda dos ímpios,","nem sigas pelo caminho dos maus."],np:1},
{v:15,l:["Evita-o, não passes por ele;","desvia-te dele e segue adiante."],np:1},
{v:16,l:["Pois eles não dormem se não fizerem o mal;","perdem o sono se não fizerem alguém cair."],np:1},
{v:17,l:["Comem o pão da impiedade","e bebem o vinho da violência."],np:1},
{v:18,l:["Mas a vereda dos justos é como a luz da aurora,","que vai brilhando mais e mais até o pleno dia."],np:1},
{v:19,l:["O caminho dos ímpios é como a escuridão:","não sabem em que tropeçam."],np:1},
{s:"Guarda o teu coração"},
{v:20,l:["Meu filho, presta atenção às minhas palavras,","inclina o ouvido aos meus discursos;"]},
{v:21,l:["que não se afastem dos teus olhos;","guarda-os no fundo do coração,"],np:1},
{v:22,l:["pois são vida para quem os encontra","e saúde para todo o seu corpo."],np:1},
{v:23,l:["Acima de tudo o que se guarda, guarda o teu coração,","porque dele procedem as fontes da vida."],np:1},
{v:24,l:["Afasta de ti a boca perversa,","e mantém longe de ti os lábios enganadores."],np:1},
{v:25,l:["Que os teus olhos olhem para a frente,","e o teu olhar se dirija direto diante de ti."],np:1},
{v:26,l:["Aplana a vereda dos teus pés,","e todos os teus caminhos serão firmes."],np:1},
{v:27,l:["Não te desvies nem para a direita nem para a esquerda;","afasta o teu pé do mal."],np:1}
];

window.TEXTOS_SEED["proverbios"][5] = [
{s:"Contra a mulher adúltera"},
{v:1,l:["Meu filho, presta atenção à minha sabedoria,","inclina o ouvido à minha inteligência,"]},
{v:2,l:["para que conserves a reflexão,","e os teus lábios guardem o conhecimento."],np:1},
{v:3,l:["Pois os lábios da mulher estranha destilam mel,","e a sua boca é mais suave que o azeite;"],np:1},
{v:4,l:["mas no fim ela é amarga como o absinto,","cortante como espada de dois gumes."],np:1},
{v:5,l:["Os seus pés descem para a morte,","os seus passos vão direto à morada dos mortos."],np:1},
{v:6,l:["Para não seguir a vereda da vida,","os seus caminhos se desviam, sem que ela o perceba."],np:1},
{v:7,l:["Agora, pois, filhos, escutai-me","e não vos afasteis das palavras da minha boca."],np:1},
{v:8,l:["Afasta dela o teu caminho","e não te aproximes da porta da sua casa,"],np:1},
{v:9,l:["para não entregares a outros a tua honra","e os teus anos a um homem cruel;"],np:1},
{v:10,l:["para que estranhos não se fartem dos teus bens,","e o fruto das tuas fadigas não vá para a casa de outro;"],np:1},
{v:11,l:["e tenhas de gemer no fim,","quando se consumirem a tua carne e o teu corpo,"],np:1},
{v:12,l:["e digas: Como pude odiar a disciplina,","e o meu coração desprezar a repreensão?"],np:1},
{v:13,l:["Não escutei a voz dos meus mestres,","nem inclinei o ouvido aos que me ensinavam."],np:1},
{v:14,l:["Por pouco não caí em toda espécie de mal,","no meio da assembleia e da comunidade."],np:1},
{s:"Fidelidade à esposa"},
{v:15,l:["Bebe a água da tua cisterna,","as águas que brotam do teu poço."]},
{v:16,l:["Deverão as tuas fontes derramar-se pela rua,","e os teus regatos pelas praças?"],np:1},
{v:17,l:["Que sejam só para ti,","e não para estranhos contigo."],np:1},
{v:18,l:["Bendita seja a tua fonte!","Alegra-te com a mulher da tua juventude,"],np:1},
{v:19,l:["corça amável, gazela graciosa:","que os seus seios te saciem em todo o tempo,","e que o seu amor te embriague sempre."],np:1},
{v:20,l:["Por que, meu filho, te deixarias embriagar por uma estranha","e abraçarias o seio de uma estrangeira?"],np:1},
{v:21,l:["Pois os caminhos do homem estão diante dos olhos do Senhor,","que observa todas as suas veredas."],np:1},
{v:22,l:["O ímpio é preso pelas suas próprias iniquidades","e fica amarrado pelas cordas do seu pecado."],np:1},
{v:23,l:["Morrerá por falta de disciplina,","e cambaleará pela grandeza da sua insensatez."],np:1}
];

window.TEXTOS_SEED["proverbios"][6] = [
{s:"Contra a fiança imprudente"},
{v:1,l:["Meu filho, se ficaste por fiador do teu próximo,","se deste a mão a um estranho,"]},
{v:2,l:["ficaste preso pelas palavras da tua boca,","apanhado pelas palavras dos teus lábios."],np:1},
{v:3,l:["Faze então isto, meu filho, e livra-te,","pois caíste nas mãos do teu próximo:","vai, humilha-te e insiste com ele."],np:1},
{v:4,l:["Não concedas sono aos teus olhos,","nem descanso às tuas pálpebras;"],np:1},
{v:5,l:["livra-te como a gazela da mão do caçador,","como o pássaro da mão do passarinheiro."],np:1},
{s:"Contra a preguiça"},
{v:6,l:["Vai ter com a formiga, ó preguiçoso;","observa os seus caminhos e torna-te sábio."]},
{v:7,l:["Ela não tem chefe,","nem inspetor, nem governante;"],np:1},
{v:8,l:["no verão prepara o seu pão,","na colheita ajunta o seu alimento."],np:1},
{v:9,l:["Até quando, preguiçoso, ficarás deitado?","Quando te levantarás do teu sono?"],np:1},
{v:10,l:["Um pouco de sono, um pouco de cochilo,","um pouco de braços cruzados para descansar,"],np:1},
{v:11,l:["e a pobreza chegará como um vagabundo,","e a necessidade, como um homem armado."],np:1},
{s:"O homem perverso"},
{v:12,l:["Homem sem valor, homem iníquo","é quem anda com a boca perversa,"]},
{v:13,l:["pisca os olhos, faz sinais com os pés,","aponta com os dedos;"],np:1},
{v:14,l:["tem a perversidade no coração, trama o mal em todo o tempo,","semeia discórdias."],np:1},
{v:15,l:["Por isso a sua ruína virá de repente;","num instante será despedaçado, e não haverá remédio."],np:1},
{s:"O que o Senhor detesta"},
{v:16,l:["Há seis coisas que o Senhor odeia,","e sete que lhe são abomináveis:"]},
{v:17,l:["olhos altivos, língua mentirosa,","mãos que derramam sangue inocente,"],np:1},
{v:18,l:["coração que trama projetos iníquos,","pés que se apressam a correr para o mal,"],np:1},
{v:19,l:["testemunha falsa que profere mentiras,","e quem semeia discórdias entre irmãos."],np:1},
{s:"Contra o adultério"},
{v:20,l:["Guarda, meu filho, o mandamento do teu pai","e não rejeites o ensinamento da tua mãe."]},
{v:21,l:["Traze-os sempre atados ao coração,","pendura-os ao pescoço."],np:1},
{v:22,l:["Quando andares, eles te guiarão;","quando dormires, velarão por ti;","quando acordares, falarão contigo."],np:1},
{v:23,l:["Pois o mandamento é uma lâmpada, e o ensinamento, uma luz;","e as repreensões da disciplina são o caminho da vida,"],np:1},
{v:24,l:["para te guardar da mulher má,","da língua lisonjeira da estrangeira."],np:1},
{v:25,l:["Não cobices no teu coração a sua beleza,","nem te deixes prender pelos seus olhares."],np:1},
{v:26,l:["Pois a prostituta custa apenas um pedaço de pão,","mas a mulher casada caça uma vida preciosa."],np:1,n:"Nota do tradutor: o sábio não aprova a prostituição; compara os dois males para mostrar que o adultério custa ao homem a própria vida (versículos 32–35)."},
{v:27,l:["Pode alguém pôr fogo no peito","sem que as suas roupas se queimem?"],np:1},
{v:28,l:["Ou pode andar sobre brasas","sem queimar os pés?"],np:1},
{v:29,l:["Assim é quem se une à mulher do seu próximo:","quem a tocar não ficará impune."],np:1},
{v:30,l:["Não se despreza o ladrão quando rouba","para matar a fome;"],np:1},
{v:31,l:["mas, se for apanhado, pagará sete vezes,","entregará todos os bens da sua casa."],np:1},
{v:32,l:["Quem comete adultério com uma mulher não tem juízo;","quem faz isso arruína a si mesmo."],np:1},
{v:33,l:["Encontrará golpes e desonra,","e a sua vergonha não se apagará."],np:1},
{v:34,l:["Pois o ciúme enfurece o marido,","e ele não terá piedade no dia da vingança;"],np:1},
{v:35,l:["não aceitará nenhuma compensação,","nem se deixará aplacar, ainda que multipliques os presentes."],np:1}
];
