// =====================================================================
// Provérbios — tradução do hebraico (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["proverbios"][1] = [
{s:"Finalidade do livro"},
{v:1,t:"Provérbios de Salomão, filho de Davi, rei de Israel.",n:"O livro reúne várias coleções de sentenças (10,1; 22,17; 24,23; 25,1; 30,1; 31,1), atribuídas em conjunto a Salomão, o sábio por excelência (1 Reis 5,9–14)."},
{v:2,l:["Para conhecer a sabedoria e a disciplina,","para entender as palavras da inteligência;"],np:1},
{v:3,l:["para receber uma educação esclarecida,","justiça, direito e retidão;"],np:1},
{v:4,l:["para dar aos ingênuos a prudência,","ao jovem o conhecimento e a reflexão."],np:1},
{v:5,l:["Que o sábio escute e aumente o seu saber,","e o inteligente adquira a arte de se conduzir,"],np:1},
{v:6,l:["para entender o provérbio e a alegoria,","as palavras dos sábios e os seus enigmas."],np:1},
{v:7,l:["O temor do Senhor é o princípio do conhecimento;","os insensatos desprezam a sabedoria e a disciplina."],np:1,n:"O temor do Senhor: a reverência e a fidelidade a Deus. É o lema de todo o livro (9,10; 15,33)."},
{s:"Contra as más companhias"},
{v:8,l:["Escuta, meu filho, a disciplina do teu pai","e não rejeites o ensinamento da tua mãe,"]},
{v:9,l:["pois serão uma coroa graciosa para a tua cabeça","e um colar para o teu pescoço."],np:1},
{v:10,l:["Meu filho, se os pecadores quiserem te seduzir,","não consintas."],np:1},
{v:11,l:["Se disserem: Vem conosco, armemos emboscadas para derramar sangue,","façamos tocaia ao inocente sem motivo;"],np:1},
{v:12,l:["vamos engoli-los vivos, como a morada dos mortos,","inteiros, como os que descem à cova;"],np:1},
{v:13,l:["acharemos toda espécie de riquezas preciosas,","encheremos de despojos as nossas casas;"],np:1},
{v:14,l:["lança a tua sorte conosco,","teremos todos uma só bolsa;"],np:1},
{v:15,l:["meu filho, não andes com eles no caminho,","afasta o teu pé das suas veredas,"],np:1},
{v:16,l:["pois os seus pés correm para o mal","e se apressam a derramar sangue."],np:1},
{v:17,l:["É inútil estender a rede à vista de qualquer ave."],np:1},
{v:18,l:["Mas eles armam emboscadas contra o próprio sangue","e fazem tocaia contra a própria vida."],np:1},
{v:19,l:["Tais são os caminhos de todo aquele que é ávido de lucro:","o lucro tira a vida de quem o possui."],np:1},
{s:"A Sabedoria chama"},
{v:20,l:["A Sabedoria clama nas ruas,","nas praças levanta a sua voz;"],n:"A Sabedoria aparece aqui personificada, como uma mulher que fala nas praças (compare 8,1–9,6)."},
{v:21,l:["no alto dos lugares movimentados ela chama,","à entrada das portas da cidade pronuncia as suas palavras:"],np:1},
{v:22,l:["Até quando, ingênuos, amareis a ingenuidade?","Até quando os zombadores se comprazerão na zombaria","e os insensatos odiarão o conhecimento?"],np:1},
{v:23,l:["Voltai-vos para a minha repreensão:","eis que derramarei sobre vós o meu espírito","e vos darei a conhecer as minhas palavras."],np:1},
{v:24,l:["Porque eu chamei, e vós recusastes;","estendi a mão, e ninguém prestou atenção;"],np:1},
{v:25,l:["rejeitastes todos os meus conselhos","e não quisestes a minha repreensão;"],np:1},
{v:26,l:["também eu me rirei da vossa desgraça,","zombarei quando vier sobre vós o terror,"],np:1},
{v:27,l:["quando o terror vier sobre vós como uma tempestade","e a desgraça chegar como um furacão,","quando vierem sobre vós a angústia e a aflição."],np:1},
{v:28,l:["Então me chamarão, e eu não responderei;","hão de me procurar, e não me encontrarão,"],np:1},
{v:29,l:["porque odiaram o conhecimento","e não escolheram o temor do Senhor;"],np:1},
{v:30,l:["não quiseram o meu conselho","e desprezaram toda a minha repreensão."],np:1},
{v:31,l:["Comerão, pois, o fruto da sua conduta","e se fartarão dos seus próprios conselhos."],np:1},
{v:32,l:["Pois o desvio dos ingênuos os matará,","e a despreocupação dos insensatos os perderá."],np:1},
{v:33,l:["Mas quem me escuta habitará em segurança,","tranquilo, sem temer o mal."],np:1}
];

window.TEXTOS_SEED["proverbios"][2] = [
{s:"Os frutos da sabedoria"},
{v:1,l:["Meu filho, se acolheres as minhas palavras","e guardares contigo os meus mandamentos,"]},
{v:2,l:["prestando ouvido à sabedoria","e inclinando o coração para a inteligência;"],np:1},
{v:3,l:["se invocares o discernimento","e chamares em voz alta a inteligência;"],np:1},
{v:4,l:["se a procurares como a prata","e a buscares como a um tesouro escondido,"],np:1},
{v:5,l:["então compreenderás o temor do Senhor","e encontrarás o conhecimento de Deus."],np:1},
{v:6,l:["Pois é o Senhor quem dá a sabedoria;","da sua boca procedem o conhecimento e a inteligência."],np:1},
{v:7,l:["Ele reserva o êxito para os retos,","é um escudo para os que caminham na integridade,"],np:1},
{v:8,l:["guardando as veredas da justiça","e protegendo o caminho dos seus fiéis."],np:1},
{v:9,l:["Então compreenderás a justiça, o direito","e a retidão, todos os caminhos do bem."],np:1},
{v:10,l:["Pois a sabedoria entrará no teu coração,","e o conhecimento será agradável à tua alma;"],np:1},
{v:11,l:["a reflexão velará sobre ti,","e a inteligência te guardará,"],np:1},
{v:12,l:["para te livrar do mau caminho,","do homem que fala coisas perversas,"],np:1},
{v:13,l:["dos que deixam as veredas retas","para andar pelos caminhos das trevas,"],np:1},
{v:14,l:["que se alegram em fazer o mal","e exultam com as perversidades do mal,"],np:1},
{v:15,l:["cujas veredas são tortuosas","e cujos caminhos são desviados;"],np:1},
{v:16,l:["para te livrar da mulher estranha,","da estrangeira de palavras sedutoras,"],np:1,n:"A mulher estranha, a estrangeira: a mulher de outro homem, a adúltera, que não pertence ao próprio lar (compare 5,3–20; 7,5–27)."},
{v:17,l:["que abandona o companheiro da sua juventude","e esquece a aliança do seu Deus;"],np:1},
{v:18,l:["pois a sua casa se inclina para a morte,","e as suas veredas levam às sombras dos mortos;"],np:1},
{v:19,l:["nenhum dos que vão até ela volta,","nem alcança de novo as veredas da vida."],np:1},
{v:20,l:["Assim andarás no caminho dos bons","e seguirás as veredas dos justos."],np:1},
{v:21,l:["Pois os retos habitarão a terra,","e os íntegros nela permanecerão;"],np:1},
{v:22,l:["mas os ímpios serão exterminados da terra,","e os traidores serão arrancados dela."],np:1}
];

window.TEXTOS_SEED["proverbios"][3] = [
{s:"Confiança no Senhor"},
{v:1,l:["Meu filho, não esqueças o meu ensinamento,","e que o teu coração guarde os meus mandamentos,"]},
{v:2,l:["pois eles te darão longos dias,","anos de vida e paz."],np:1},
{v:3,l:["Que a bondade e a fidelidade não te abandonem:","ata-as ao teu pescoço,","escreve-as na tábua do teu coração;"],np:1},
{v:4,l:["e encontrarás favor e bom êxito","aos olhos de Deus e dos homens."],np:1},
{v:5,l:["Confia no Senhor de todo o coração","e não te apoies na tua própria inteligência."],np:1},
{v:6,l:["Em todos os teus caminhos, pensa nele,","e ele endireitará as tuas veredas."],np:1},
{v:7,l:["Não sejas sábio aos teus próprios olhos;","teme o Senhor e afasta-te do mal:"],np:1},
{v:8,l:["isso será saúde para o teu corpo","e refrigério para os teus ossos."],np:1},
{v:9,l:["Honra o Senhor com os teus bens","e com as primícias de todas as tuas colheitas;"],np:1},
{v:10,l:["e os teus celeiros se encherão com fartura,","e os teus lagares transbordarão de vinho novo."],np:1},
{v:11,l:["Meu filho, não desprezes a disciplina do Senhor,","nem te aborreças com a sua repreensão,"],np:1},
{v:12,l:["pois o Senhor repreende a quem ama,","como um pai ao filho a quem quer bem."],np:1,n:"Citado em Hebreus 12,5–6, segundo o grego: e castiga todo filho que acolhe."},
{s:"Feliz quem encontra a sabedoria"},
{v:13,l:["Feliz o homem que encontrou a sabedoria,","o homem que alcançou a inteligência!"]},
{v:14,l:["Pois ganhá-la vale mais que ganhar prata,","e o seu lucro é melhor que o ouro fino."],np:1},
{v:15,l:["Ela é mais preciosa que as pérolas,","e nada do que desejas se compara a ela."],np:1},
{v:16,l:["Na sua mão direita, longos dias;","na esquerda, riqueza e honra."],np:1},
{v:17,l:["Os seus caminhos são caminhos de delícias,","e todas as suas veredas são paz."],np:1},
{v:18,l:["Ela é árvore de vida para os que a abraçam,","e felizes os que a retêm."],np:1},
{v:19,l:["O Senhor fundou a terra com sabedoria,","firmou os céus com inteligência;"],np:1},
{v:20,l:["pelo seu conhecimento se abriram os abismos,","e as nuvens destilam o orvalho."],np:1},
{v:21,l:["Meu filho, que elas não se afastem dos teus olhos:","guarda o bom senso e a reflexão;"],np:1},
{v:22,l:["serão vida para a tua alma","e adorno para o teu pescoço."],np:1},
{v:23,l:["Então andarás seguro pelo teu caminho,","e o teu pé não tropeçará."],np:1},
{v:24,l:["Se te deitares, não terás medo;","repousarás, e o teu sono será tranquilo."],np:1},
{v:25,l:["Não temas o terror repentino,","nem a ruína dos ímpios, quando vier,"],np:1},
{v:26,l:["pois o Senhor será a tua confiança","e guardará o teu pé da armadilha."],np:1},
{s:"Deveres para com o próximo"},
{v:27,l:["Não negues um benefício a quem dele precisa,","quando está em teu poder fazê-lo."]},
{v:28,l:["Não digas ao teu próximo: Vai e volta,","amanhã te darei, quando o tens contigo."],np:1},
{v:29,l:["Não trames o mal contra o teu próximo,","quando ele vive confiante ao teu lado."],np:1},
{v:30,l:["Não brigues com ninguém sem motivo,","se não te fez nenhum mal."],np:1},
{v:31,l:["Não invejes o homem violento,","nem escolhas nenhum dos seus caminhos,"],np:1},
{v:32,l:["pois o perverso é abominação para o Senhor,","mas ele tem intimidade com os retos."],np:1},
{v:33,l:["A maldição do Senhor está na casa do ímpio,","mas ele abençoa a morada dos justos."],np:1},
{v:34,l:["Ele zomba dos zombadores,","mas aos humildes concede a sua graça."],np:1,n:"Citado segundo o grego em Tiago 4,6 e 1 Pedro 5,5: Deus resiste aos soberbos, mas dá a sua graça aos humildes."},
{v:35,l:["Os sábios herdarão a honra,","mas os insensatos só acumulam desonra."],np:1}
];

window.TEXTOS_SEED["proverbios"][4] = [
{s:"Adquire a sabedoria"},
{v:1,l:["Escutai, filhos, a disciplina de um pai;","prestai atenção para conhecer a inteligência,"]},
{v:2,l:["pois eu vos dou uma boa doutrina:","não abandoneis o meu ensinamento."],np:1},
{v:3,l:["Também eu fui filho para o meu pai,","terno e único aos olhos da minha mãe."],np:1},
{v:4,l:["Ele me ensinava e me dizia:","Que o teu coração retenha as minhas palavras;","guarda os meus mandamentos e viverás."],np:1},
{v:5,l:["Adquire a sabedoria, adquire a inteligência;","não esqueças as palavras da minha boca nem te desvies delas."],np:1},
{v:6,l:["Não a abandones, e ela te guardará;","ama-a, e ela te protegerá."],np:1},
{v:7,l:["O princípio da sabedoria é: adquire a sabedoria;","com tudo o que possuis, adquire a inteligência."],np:1},
{v:8,l:["Estima-a, e ela te exaltará;","ela te honrará, se a abraçares."],np:1},
{v:9,l:["Porá na tua cabeça uma coroa graciosa,","te dará um diadema de glória."],np:1},
{s:"Os dois caminhos"},
{v:10,l:["Escuta, meu filho, e acolhe as minhas palavras,","e se multiplicarão os anos da tua vida."]},
{v:11,l:["Eu te ensinei o caminho da sabedoria,","te conduzi pelas veredas da retidão."],np:1},
{v:12,l:["Quando andares, os teus passos não serão estorvados;","se correres, não tropeçarás."],np:1},
{v:13,l:["Agarra-te à disciplina, não a largues;","guarda-a, porque ela é a tua vida."],np:1},
{v:14,l:["Não entres na vereda dos ímpios,","nem sigas pelo caminho dos maus."],np:1},
{v:15,l:["Evita-o, não passes por ele;","desvia-te dele e segue adiante."],np:1},
{v:16,l:["Pois eles não dormem se não fizerem o mal;","perdem o sono se não fizerem alguém cair."],np:1},
{v:17,l:["Comem o pão da impiedade","e bebem o vinho da violência."],np:1},
{v:18,l:["Mas a vereda dos justos é como a luz da aurora,","que vai brilhando mais e mais até o pleno dia."],np:1},
{v:19,l:["O caminho dos ímpios é como a escuridão:","não sabem em que tropeçam."],np:1},
{s:"Guarda o teu coração"},
{v:20,l:["Meu filho, presta atenção às minhas palavras,","inclina o ouvido aos meus discursos;"]},
{v:21,l:["que não se afastem dos teus olhos;","guarda-os no fundo do coração,"],np:1},
{v:22,l:["pois são vida para quem os encontra","e saúde para todo o seu corpo."],np:1},
{v:23,l:["Acima de tudo o que se guarda, guarda o teu coração,","porque dele procedem as fontes da vida."],np:1},
{v:24,l:["Afasta de ti a boca perversa,","e mantém longe de ti os lábios enganadores."],np:1},
{v:25,l:["Que os teus olhos olhem para a frente,","e o teu olhar se dirija direto diante de ti."],np:1},
{v:26,l:["Aplana a vereda dos teus pés,","e todos os teus caminhos serão firmes."],np:1},
{v:27,l:["Não te desvies nem para a direita nem para a esquerda;","afasta o teu pé do mal."],np:1}
];

window.TEXTOS_SEED["proverbios"][5] = [
{s:"Contra a mulher adúltera"},
{v:1,l:["Meu filho, presta atenção à minha sabedoria,","inclina o ouvido à minha inteligência,"]},
{v:2,l:["para que conserves a reflexão,","e os teus lábios guardem o conhecimento."],np:1},
{v:3,l:["Pois os lábios da mulher estranha destilam mel,","e a sua boca é mais suave que o azeite;"],np:1},
{v:4,l:["mas no fim ela é amarga como o absinto,","cortante como espada de dois gumes."],np:1},
{v:5,l:["Os seus pés descem para a morte,","os seus passos vão direto à morada dos mortos."],np:1},
{v:6,l:["Para não seguir a vereda da vida,","os seus caminhos se desviam, sem que ela o perceba."],np:1},
{v:7,l:["Agora, pois, filhos, escutai-me","e não vos afasteis das palavras da minha boca."],np:1},
{v:8,l:["Afasta dela o teu caminho","e não te aproximes da porta da sua casa,"],np:1},
{v:9,l:["para não entregares a outros a tua honra","e os teus anos a um homem cruel;"],np:1},
{v:10,l:["para que estranhos não se fartem dos teus bens,","e o fruto das tuas fadigas não vá para a casa de outro;"],np:1},
{v:11,l:["e tenhas de gemer no fim,","quando se consumirem a tua carne e o teu corpo,"],np:1},
{v:12,l:["e digas: Como pude odiar a disciplina,","e o meu coração desprezar a repreensão?"],np:1},
{v:13,l:["Não escutei a voz dos meus mestres,","nem inclinei o ouvido aos que me ensinavam."],np:1},
{v:14,l:["Por pouco não caí em toda espécie de mal,","no meio da assembleia e da comunidade."],np:1},
{s:"Fidelidade à esposa"},
{v:15,l:["Bebe a água da tua cisterna,","as águas que brotam do teu poço."]},
{v:16,l:["Deverão as tuas fontes derramar-se pela rua,","e os teus regatos pelas praças?"],np:1},
{v:17,l:["Que sejam só para ti,","e não para estranhos contigo."],np:1},
{v:18,l:["Bendita seja a tua fonte!","Alegra-te com a mulher da tua juventude,"],np:1},
{v:19,l:["corça amável, gazela graciosa:","que os seus seios te saciem em todo o tempo,","e que o seu amor te embriague sempre."],np:1},
{v:20,l:["Por que, meu filho, te deixarias embriagar por uma estranha","e abraçarias o seio de uma estrangeira?"],np:1},
{v:21,l:["Pois os caminhos do homem estão diante dos olhos do Senhor,","que observa todas as suas veredas."],np:1},
{v:22,l:["O ímpio é preso pelas suas próprias iniquidades","e fica amarrado pelas cordas do seu pecado."],np:1},
{v:23,l:["Morrerá por falta de disciplina,","e cambaleará pela grandeza da sua insensatez."],np:1}
];

window.TEXTOS_SEED["proverbios"][6] = [
{s:"Contra a fiança imprudente"},
{v:1,l:["Meu filho, se ficaste por fiador do teu próximo,","se deste a mão a um estranho,"]},
{v:2,l:["ficaste preso pelas palavras da tua boca,","apanhado pelas palavras dos teus lábios."],np:1},
{v:3,l:["Faze então isto, meu filho, e livra-te,","pois caíste nas mãos do teu próximo:","vai, humilha-te e insiste com ele."],np:1},
{v:4,l:["Não concedas sono aos teus olhos,","nem descanso às tuas pálpebras;"],np:1},
{v:5,l:["livra-te como a gazela da mão do caçador,","como o pássaro da mão do passarinheiro."],np:1},
{s:"Contra a preguiça"},
{v:6,l:["Vai ter com a formiga, ó preguiçoso;","observa os seus caminhos e torna-te sábio."]},
{v:7,l:["Ela não tem chefe,","nem inspetor, nem governante;"],np:1},
{v:8,l:["no verão prepara o seu pão,","na colheita ajunta o seu alimento."],np:1},
{v:9,l:["Até quando, preguiçoso, ficarás deitado?","Quando te levantarás do teu sono?"],np:1},
{v:10,l:["Um pouco de sono, um pouco de cochilo,","um pouco de braços cruzados para descansar,"],np:1},
{v:11,l:["e a pobreza chegará como um vagabundo,","e a necessidade, como um homem armado."],np:1},
{s:"O homem perverso"},
{v:12,l:["Homem sem valor, homem iníquo","é quem anda com a boca perversa,"]},
{v:13,l:["pisca os olhos, faz sinais com os pés,","aponta com os dedos;"],np:1},
{v:14,l:["tem a perversidade no coração, trama o mal em todo o tempo,","semeia discórdias."],np:1},
{v:15,l:["Por isso a sua ruína virá de repente;","num instante será despedaçado, e não haverá remédio."],np:1},
{s:"O que o Senhor detesta"},
{v:16,l:["Há seis coisas que o Senhor odeia,","e sete que lhe são abomináveis:"]},
{v:17,l:["olhos altivos, língua mentirosa,","mãos que derramam sangue inocente,"],np:1},
{v:18,l:["coração que trama projetos iníquos,","pés que se apressam a correr para o mal,"],np:1},
{v:19,l:["testemunha falsa que profere mentiras,","e quem semeia discórdias entre irmãos."],np:1},
{s:"Contra o adultério"},
{v:20,l:["Guarda, meu filho, o mandamento do teu pai","e não rejeites o ensinamento da tua mãe."]},
{v:21,l:["Traze-os sempre atados ao coração,","pendura-os ao pescoço."],np:1},
{v:22,l:["Quando andares, eles te guiarão;","quando dormires, velarão por ti;","quando acordares, falarão contigo."],np:1},
{v:23,l:["Pois o mandamento é uma lâmpada, e o ensinamento, uma luz;","e as repreensões da disciplina são o caminho da vida,"],np:1},
{v:24,l:["para te guardar da mulher má,","da língua lisonjeira da estrangeira."],np:1},
{v:25,l:["Não cobices no teu coração a sua beleza,","nem te deixes prender pelos seus olhares."],np:1},
{v:26,l:["Pois a prostituta custa apenas um pedaço de pão,","mas a mulher casada caça uma vida preciosa."],np:1,n:"Nota do tradutor: o sábio não aprova a prostituição; compara os dois males para mostrar que o adultério custa ao homem a própria vida (versículos 32–35)."},
{v:27,l:["Pode alguém pôr fogo no peito","sem que as suas roupas se queimem?"],np:1},
{v:28,l:["Ou pode andar sobre brasas","sem queimar os pés?"],np:1},
{v:29,l:["Assim é quem se une à mulher do seu próximo:","quem a tocar não ficará impune."],np:1},
{v:30,l:["Não se despreza o ladrão quando rouba","para matar a fome;"],np:1},
{v:31,l:["mas, se for apanhado, pagará sete vezes,","entregará todos os bens da sua casa."],np:1},
{v:32,l:["Quem comete adultério com uma mulher não tem juízo;","quem faz isso arruína a si mesmo."],np:1},
{v:33,l:["Encontrará golpes e desonra,","e a sua vergonha não se apagará."],np:1},
{v:34,l:["Pois o ciúme enfurece o marido,","e ele não terá piedade no dia da vingança;"],np:1},
{v:35,l:["não aceitará nenhuma compensação,","nem se deixará aplacar, ainda que multipliques os presentes."],np:1}
];

window.TEXTOS_SEED["proverbios"][7] = [
{s:"A sedução da adúltera"},
{v:1,l:["Meu filho, guarda as minhas palavras","e conserva contigo os meus mandamentos."]},
{v:2,l:["Guarda os meus mandamentos e viverás;","guarda o meu ensinamento como a menina dos teus olhos."],np:1},
{v:3,l:["Ata-os aos teus dedos,","escreve-os na tábua do teu coração."],np:1},
{v:4,l:["Dize à sabedoria: Tu és minha irmã;","e chama a inteligência de amiga,"],np:1},
{v:5,l:["para que te guardem da mulher estranha,","da estrangeira de palavras sedutoras."],np:1},
{v:6,l:["Da janela da minha casa,","por trás da grade, eu olhava,"],np:1},
{v:7,l:["e vi entre os ingênuos,","notei entre os rapazes um jovem sem juízo,"],np:1},
{v:8,l:["que passava pela rua, perto da esquina dela,","e seguia o caminho da sua casa,"],np:1},
{v:9,l:["ao crepúsculo, ao cair da tarde,","na escuridão da noite e nas trevas."],np:1},
{v:10,l:["E eis que uma mulher vem ao seu encontro,","vestida como prostituta e de coração astuto."],np:1},
{v:11,l:["Ela é barulhenta e rebelde;","os seus pés não param em casa:"],np:1},
{v:12,l:["ora na rua, ora nas praças,","fica à espreita em cada esquina."],np:1},
{v:13,l:["Ela o agarra e o beija,","e com o rosto descarado lhe diz:"],np:1},
{v:14,l:["Eu tinha de oferecer sacrifícios de comunhão;","hoje cumpri os meus votos."],np:1,n:"A carne dos sacrifícios de comunhão devia ser comida no mesmo dia ou no seguinte (Levítico 7,15–16); ela tem, portanto, com que oferecer um banquete."},
{v:15,l:["Por isso saí ao teu encontro,","à tua procura, e te encontrei."],np:1},
{v:16,l:["Cobri a minha cama de colchas,","de tecidos coloridos do Egito;"],np:1},
{v:17,l:["perfumei o meu leito","com mirra, aloés e canela."],np:1},
{v:18,l:["Vem, embriaguemo-nos de amor até a manhã,","gozemos das carícias."],np:1},
{v:19,l:["Pois o meu marido não está em casa;","partiu para uma viagem longa;"],np:1},
{v:20,l:["levou consigo a bolsa do dinheiro","e só voltará para casa na lua cheia."],np:1},
{v:21,l:["Com muita persuasão ela o seduz,","com a lisonja dos lábios o arrasta."],np:1},
{v:22,l:["Ele a segue imediatamente,","como o boi que vai para o matadouro,","como o cervo que corre para o laço,"],np:1,n:"Como o cervo que corre para o laço: assim a Nova Vulgata, com o grego; o hebraico é obscuro."},
{v:23,l:["até que uma flecha lhe atravesse o fígado;","como o pássaro que se precipita na rede,","sem saber que a sua vida está em jogo."],np:1},
{v:24,l:["Agora, pois, filhos, escutai-me,","prestai atenção às palavras da minha boca."],np:1},
{v:25,l:["Que o teu coração não se desvie para os caminhos dela;","não te extravies pelas suas veredas,"],np:1},
{v:26,l:["pois ela fez cair muitas vítimas,","e são numerosos todos os que ela matou."],np:1},
{v:27,l:["A sua casa é o caminho da morada dos mortos,","que desce para as câmaras da morte."],np:1}
];

window.TEXTOS_SEED["proverbios"][8] = [
{s:"O discurso da Sabedoria"},
{v:1,l:["Não é a Sabedoria que chama?","Não é a Inteligência que levanta a voz?"]},
{v:2,l:["No alto das colinas, junto ao caminho,","na encruzilhada ela se põe;"],np:1},
{v:3,l:["ao lado das portas, na entrada da cidade,","no acesso às portas, ela clama:"],np:1},
{v:4,l:["A vós, homens, eu chamo;","a minha voz se dirige aos filhos dos homens."],np:1},
{v:5,l:["Ingênuos, aprendei a prudência;","insensatos, tornai-vos sensatos."],np:1},
{v:6,l:["Escutai, pois vou dizer coisas importantes,","e os meus lábios se abrem para dizer o que é reto."],np:1},
{v:7,l:["A minha boca proclama a verdade,","e a impiedade é abominação para os meus lábios."],np:1},
{v:8,l:["Todas as palavras da minha boca são justas;","não há nelas nada de tortuoso ou perverso."],np:1},
{v:9,l:["Todas são claras para quem as entende,","e retas para os que encontraram o conhecimento."],np:1},
{v:10,l:["Recebei a minha disciplina, e não a prata;","o conhecimento, de preferência ao ouro fino."],np:1},
{v:11,l:["Pois a sabedoria vale mais que as pérolas,","e nada do que se deseja se compara a ela."],np:1},
{v:12,l:["Eu, a Sabedoria, habito com a prudência","e possuo o conhecimento da reflexão."],np:1},
{v:13,l:["Temer o Senhor é odiar o mal:","eu detesto o orgulho, a arrogância,","o mau caminho e a boca perversa."],np:1},
{v:14,l:["Meu é o conselho e o bom senso;","eu sou a inteligência, minha é a força."],np:1},
{v:15,l:["Por mim reinam os reis,","e os governantes decretam o que é justo;"],np:1},
{v:16,l:["por mim os príncipes governam,","e os nobres, todos os que julgam com justiça."],np:1},
{v:17,l:["Eu amo os que me amam,","e os que me procuram com diligência me encontram."],np:1},
{v:18,l:["Comigo estão a riqueza e a honra,","os bens duradouros e a justiça."],np:1},
{v:19,l:["O meu fruto é melhor que o ouro, que o ouro puro,","e o meu rendimento, melhor que a prata escolhida."],np:1},
{v:20,l:["Ando pela vereda da justiça,","no meio das veredas do direito,"],np:1},
{v:21,l:["para dar bens em herança aos que me amam","e encher os seus tesouros."],np:1},
{s:"A Sabedoria antes da criação"},
{v:22,l:["O Senhor me possuiu, primícia dos seus caminhos,","antes das suas obras mais antigas."],n:"Me possuiu: o verbo hebraico significa adquirir, e às vezes gerar ou criar; o grego traduz: me criou. Os Padres da Igreja leram este poema em relação ao Verbo de Deus (compare João 1,1–3; Colossenses 1,15–17)."},
{v:23,l:["Desde a eternidade fui estabelecida,","desde o princípio, antes das origens da terra."],np:1},
{v:24,l:["Quando ainda não havia os abismos, fui gerada,","quando ainda não havia as fontes carregadas de água."],np:1},
{v:25,l:["Antes que os montes fossem assentados,","antes das colinas, eu fui gerada,"],np:1},
{v:26,l:["quando ele ainda não tinha feito a terra e os campos,","nem os primeiros torrões do mundo."],np:1},
{v:27,l:["Quando ele firmava os céus, lá estava eu;","quando traçava um círculo sobre a face do abismo,"],np:1},
{v:28,l:["quando condensava as nuvens no alto,","quando se tornavam fortes as fontes do abismo,"],np:1},
{v:29,l:["quando fixava ao mar o seu limite,","para que as águas não ultrapassassem as suas margens,","quando assentava os fundamentos da terra,"],np:1},
{v:30,l:["eu estava junto dele como artífice;","eu era as suas delícias dia após dia,","brincando diante dele em todo o tempo,"],np:1,n:"Artífice: em hebraico amon; outros entendem: como criança de colo."},
{v:31,l:["brincando sobre a face da sua terra,","e as minhas delícias eram estar com os filhos dos homens."],np:1},
{v:32,l:["Agora, pois, filhos, escutai-me:","felizes os que guardam os meus caminhos!"],np:1},
{v:33,l:["Escutai a disciplina e tornai-vos sábios,","não a rejeiteis."],np:1},
{v:34,l:["Feliz o homem que me escuta,","velando dia após dia às minhas portas,","guardando os umbrais da minha entrada."],np:1},
{v:35,l:["Pois quem me encontra encontra a vida","e alcança o favor do Senhor."],np:1},
{v:36,l:["Mas quem me ofende faz mal a si mesmo;","todos os que me odeiam amam a morte."],np:1}
];

window.TEXTOS_SEED["proverbios"][9] = [
{s:"O banquete da Sabedoria"},
{v:1,l:["A Sabedoria construiu a sua casa,","talhou as suas sete colunas;"]},
{v:2,l:["abateu os seus animais, preparou o seu vinho","e pôs a sua mesa."],np:1},
{v:3,l:["Enviou as suas servas para anunciar","do alto da cidade:"],np:1},
{v:4,l:["Quem for ingênuo, venha para cá!","E a quem não tem juízo, ela diz:"],np:1},
{v:5,l:["Vinde, comei do meu pão","e bebei do vinho que preparei;"],np:1},
{v:6,l:["deixai a ingenuidade e vivereis,","andai pelo caminho da inteligência."],np:1},
{v:7,l:["Quem corrige o zombador atrai sobre si o desprezo;","quem repreende o ímpio recebe insultos."],np:1},
{v:8,l:["Não repreendas o zombador, para que ele não te odeie;","repreende o sábio, e ele te amará."],np:1},
{v:9,l:["Dá ao sábio, e ele se tornará mais sábio;","ensina o justo, e ele aumentará o seu saber."],np:1},
{v:10,l:["O princípio da sabedoria é o temor do Senhor,","e o conhecimento do Santo é a inteligência."],np:1},
{v:11,l:["Pois por mim se multiplicarão os teus dias","e se acrescentarão anos à tua vida."],np:1},
{v:12,l:["Se és sábio, és sábio para teu proveito;","se és zombador, só tu sofrerás as consequências."],np:1},
{s:"A mulher Insensatez"},
{v:13,l:["A mulher Insensatez é barulhenta,","ingênua, e não sabe nada."]},
{v:14,l:["Senta-se à porta da sua casa,","numa cadeira, no alto da cidade,"],np:1},
{v:15,l:["para chamar os que passam pelo caminho,","os que seguem direto pela sua vereda:"],np:1},
{v:16,l:["Quem for ingênuo, venha para cá!","E a quem não tem juízo, ela diz:"],np:1},
{v:17,l:["As águas roubadas são mais doces,","e o pão comido às escondidas é mais saboroso."],np:1},
{v:18,l:["E ele não sabe que ali estão as sombras dos mortos,","e que os convidados dela estão nas profundezas da morada dos mortos."],np:1}
];

window.TEXTOS_SEED["proverbios"][10] = [
{s:"Primeira coleção de Salomão"},
{v:1,l:["Provérbios de Salomão.","O filho sábio alegra o pai,","mas o filho insensato é a tristeza da mãe."],n:"Começa aqui a primeira grande coleção de sentenças de Salomão (10,1–22,16)."},
{v:2,l:["Os tesouros mal adquiridos não trazem proveito,","mas a justiça livra da morte."],np:1},
{v:3,l:["O Senhor não deixa o justo passar fome,","mas repele a cobiça dos ímpios."],np:1},
{v:4,l:["A mão preguiçosa empobrece,","mas a mão dos diligentes enriquece."],np:1},
{v:5,l:["Quem ajunta no verão é um filho sensato;","quem dorme na colheita é um filho que envergonha."],np:1},
{v:6,l:["Bênçãos sobre a cabeça do justo,","mas a boca dos ímpios esconde a violência."],np:1},
{v:7,l:["A memória do justo é abençoada,","mas o nome dos ímpios apodrece."],np:1},
{v:8,l:["O sábio de coração acolhe os mandamentos,","mas o tagarela insensato vai à ruína."],np:1},
{v:9,l:["Quem anda na integridade anda seguro,","mas quem torce os seus caminhos será descoberto."],np:1},
{v:10,l:["Quem pisca o olho causa desgosto,","e o tagarela insensato vai à ruína."],np:1},
{v:11,l:["A boca do justo é fonte de vida,","mas a boca dos ímpios esconde a violência."],np:1},
{v:12,l:["O ódio provoca contendas,","mas o amor cobre todas as faltas."],np:1,n:"Citado em 1 Pedro 4,8 e Tiago 5,20."},
{v:13,l:["Nos lábios do inteligente se encontra a sabedoria,","mas a vara é para as costas de quem não tem juízo."],np:1},
{v:14,l:["Os sábios guardam o conhecimento,","mas a boca do insensato é uma ruína iminente."],np:1},
{v:15,l:["Os bens do rico são a sua cidade fortificada;","a ruína dos pobres é a sua pobreza."],np:1},
{v:16,l:["O salário do justo conduz à vida;","o ganho do ímpio, ao pecado."],np:1},
{v:17,l:["Quem guarda a disciplina está no caminho da vida,","mas quem despreza a repreensão se extravia."],np:1},
{v:18,l:["Quem dissimula o ódio tem lábios mentirosos,","e quem espalha a calúnia é um insensato."],np:1},
{v:19,l:["No muito falar não falta o pecado,","mas quem refreia os lábios é sensato."],np:1},
{v:20,l:["A língua do justo é prata escolhida,","o coração dos ímpios vale pouco."],np:1},
{v:21,l:["Os lábios do justo alimentam a muitos,","mas os insensatos morrem por falta de juízo."],np:1},
{v:22,l:["É a bênção do Senhor que enriquece,","e a fadiga nada lhe acrescenta."],np:1},
{v:23,l:["Para o insensato, fazer o mal é um divertimento,","como a sabedoria para o homem inteligente."],np:1},
{v:24,l:["O que o ímpio teme, isso lhe acontece,","mas o desejo dos justos é atendido."],np:1},
{v:25,l:["Quando passa a tempestade, o ímpio já não existe,","mas o justo tem um fundamento eterno."],np:1},
{v:26,l:["Como o vinagre para os dentes e a fumaça para os olhos,","assim é o preguiçoso para quem o envia."],np:1},
{v:27,l:["O temor do Senhor prolonga os dias,","mas os anos dos ímpios serão abreviados."],np:1},
{v:28,l:["A esperança dos justos é alegria,","mas a expectativa dos ímpios perecerá."],np:1},
{v:29,l:["O caminho do Senhor é fortaleza para o íntegro,","mas ruína para os que praticam o mal."],np:1},
{v:30,l:["O justo jamais será abalado,","mas os ímpios não habitarão a terra."],np:1},
{v:31,l:["A boca do justo produz sabedoria,","mas a língua perversa será cortada."],np:1},
{v:32,l:["Os lábios do justo sabem o que agrada,","mas a boca dos ímpios, só perversidades."],np:1}
];

window.TEXTOS_SEED["proverbios"][11] = [
{s:"O justo e o ímpio"},
{v:1,l:["A balança falsa é abominação para o Senhor,","mas o peso exato lhe agrada."]},
{v:2,l:["Onde entra o orgulho, entra também a desonra,","mas com os humildes está a sabedoria."],np:1},
{v:3,l:["A integridade dos retos os guia,","mas a falsidade dos traidores os destrói."],np:1},
{v:4,l:["As riquezas de nada servem no dia da ira,","mas a justiça livra da morte."],np:1},
{v:5,l:["A justiça do íntegro aplana o seu caminho,","mas o ímpio cai pela sua própria impiedade."],np:1},
{v:6,l:["A justiça dos retos os livra,","mas os traidores são presos pela própria cobiça."],np:1},
{v:7,l:["Quando morre o ímpio, perece a sua esperança,","e se desfaz a expectativa que punha na sua força."],np:1},
{v:8,l:["O justo é livrado da angústia,","e o ímpio vem em seu lugar."],np:1},
{v:9,l:["Com a boca o ímpio arruína o seu próximo,","mas os justos se livram pelo conhecimento."],np:1},
{v:10,l:["Quando os justos prosperam, a cidade se alegra;","quando os ímpios perecem, há gritos de júbilo."],np:1},
{v:11,l:["Pela bênção dos retos a cidade se eleva,","mas pela boca dos ímpios é destruída."],np:1},
{v:12,l:["Quem despreza o seu próximo não tem juízo,","mas o homem inteligente se cala."],np:1},
{v:13,l:["Quem anda fazendo mexericos revela segredos,","mas o de espírito fiel guarda o que lhe confiaram."],np:1},
{v:14,l:["Por falta de direção o povo cai;","a salvação está no grande número de conselheiros."],np:1},
{v:15,l:["Quem fica por fiador de um estranho sai prejudicado,","mas quem recusa dar a mão está seguro."],np:1},
{v:16,l:["A mulher graciosa alcança a honra,","e os violentos alcançam a riqueza."],np:1},
{v:17,l:["O homem bondoso faz bem a si mesmo,","mas o cruel atormenta a própria carne."],np:1},
{v:18,l:["O ímpio obtém um salário enganoso,","mas quem semeia a justiça tem recompensa segura."],np:1},
{v:19,l:["Quem é firme na justiça caminha para a vida,","mas quem persegue o mal caminha para a morte."],np:1},
{v:20,l:["Os de coração perverso são abominação para o Senhor,","mas os de conduta íntegra lhe agradam."],np:1},
{v:21,l:["Com certeza o mau não ficará impune,","mas a descendência dos justos será salva."],np:1,n:"Com certeza: literalmente, mão na mão, como quem aperta a mão para garantir o que diz."},
{v:22,l:["Argola de ouro em focinho de porco","é a mulher bonita sem bom senso."],np:1},
{v:23,l:["O desejo dos justos é só o bem;","a esperança dos ímpios é a ira."],np:1},
{v:24,l:["Há quem distribua com generosidade e fica mais rico,","e há quem retenha mais do que é justo e só empobrece."],np:1},
{v:25,l:["A pessoa generosa prosperará,","e quem dá de beber também será saciado."],np:1},
{v:26,l:["O povo amaldiçoa quem retém o trigo,","mas há bênção sobre a cabeça de quem o vende."],np:1},
{v:27,l:["Quem busca o bem com diligência encontra o favor,","mas o mal vem sobre quem o procura."],np:1},
{v:28,l:["Quem confia nas suas riquezas cairá,","mas os justos brotarão como a folhagem."],np:1},
{v:29,l:["Quem perturba a sua casa herdará o vento,","e o insensato será escravo do sábio."],np:1},
{v:30,l:["O fruto do justo é árvore de vida,","e o sábio conquista as almas."],np:1},
{v:31,l:["Se o justo recebe na terra a sua paga,","quanto mais o ímpio e o pecador!"],np:1,n:"Citado segundo o grego em 1 Pedro 4,18: se o justo a custo se salva, que será do ímpio e do pecador?"}
];

window.TEXTOS_SEED["proverbios"][12] = [
{s:"A disciplina e as palavras"},
{v:1,l:["Quem ama a disciplina ama o conhecimento,","mas quem odeia a repreensão é estúpido."]},
{v:2,l:["O homem bom alcança o favor do Senhor,","mas ele condena o homem de maus desígnios."],np:1},
{v:3,l:["O homem não se firma pela impiedade,","mas a raiz dos justos não será abalada."],np:1},
{v:4,l:["A mulher virtuosa é a coroa do marido,","mas a que o envergonha é como cárie nos seus ossos."],np:1},
{v:5,l:["Os pensamentos dos justos são retidão,","os planos dos ímpios são engano."],np:1},
{v:6,l:["As palavras dos ímpios são emboscadas de sangue,","mas a boca dos retos os livra."],np:1},
{v:7,l:["Os ímpios são derrubados e já não existem,","mas a casa dos justos permanece."],np:1},
{v:8,l:["O homem é louvado segundo o seu bom senso,","mas o de coração perverso será desprezado."],np:1},
{v:9,l:["Mais vale ser simples e ter um servo","do que se dar importância e não ter pão."],np:1},
{v:10,l:["O justo cuida da vida dos seus animais,","mas as entranhas dos ímpios são cruéis."],np:1},
{v:11,l:["Quem cultiva a sua terra se farta de pão,","mas quem corre atrás de coisas vãs não tem juízo."],np:1},
{v:12,l:["O ímpio cobiça a presa dos maus,","mas a raiz dos justos dá fruto."],np:1},
{v:13,l:["No pecado dos lábios há uma armadilha para o mau,","mas o justo escapa da angústia."],np:1},
{v:14,l:["Cada um se farta de bens pelo fruto da sua boca,","e cada um recebe a paga da obra das suas mãos."],np:1},
{v:15,l:["O caminho do insensato é reto aos seus olhos,","mas o sábio escuta os conselhos."],np:1},
{v:16,l:["O insensato mostra logo a sua irritação,","mas o prudente dissimula a afronta."],np:1},
{v:17,l:["Quem diz a verdade declara o que é justo,","mas a testemunha falsa, o engano."],np:1},
{v:18,l:["Há quem fale à toa, ferindo como espada,","mas a língua dos sábios traz a cura."],np:1},
{v:19,l:["O lábio sincero permanece para sempre,","mas a língua mentirosa dura só um instante."],np:1},
{v:20,l:["Há engano no coração dos que tramam o mal,","mas alegria para os que aconselham a paz."],np:1},
{v:21,l:["Nenhum mal acontece ao justo,","mas os ímpios estão cheios de desgraças."],np:1},
{v:22,l:["Os lábios mentirosos são abominação para o Senhor,","mas os que agem com fidelidade lhe agradam."],np:1},
{v:23,l:["O homem prudente esconde o que sabe,","mas o coração dos insensatos proclama a insensatez."],np:1},
{v:24,l:["A mão dos diligentes dominará,","mas a preguiçosa será submetida a trabalhos forçados."],np:1},
{v:25,l:["A ansiedade no coração do homem o abate,","mas uma boa palavra o alegra."],np:1},
{v:26,l:["O justo guia o seu próximo,","mas o caminho dos ímpios os extravia."],np:1},
{v:27,l:["O preguiçoso não assa a sua caça,","mas a diligência é para o homem um bem precioso."],np:1},
{v:28,l:["No caminho da justiça está a vida,","mas há também uma vereda que leva à morte."],np:1,n:"Assim a Nova Vulgata, com as antigas versões; o hebraico diz: e a sua vereda não conduz à morte."}
];

window.TEXTOS_SEED["proverbios"][13] = [
{s:"A disciplina do pai"},
{v:1,l:["O filho sábio aceita a disciplina do pai,","mas o zombador não escuta a repreensão."]},
{v:2,l:["Pelo fruto da sua boca o homem come o bem,","mas o desejo dos traidores é a violência."],np:1},
{v:3,l:["Quem guarda a boca guarda a própria vida;","quem abre demais os lábios corre para a ruína."],np:1},
{v:4,l:["O preguiçoso deseja e nada consegue,","mas o desejo dos diligentes é saciado."],np:1},
{v:5,l:["O justo odeia a palavra mentirosa,","mas o ímpio causa vergonha e desonra."],np:1},
{v:6,l:["A justiça guarda quem anda na integridade,","mas a impiedade derruba o pecador."],np:1},
{v:7,l:["Há quem se faz de rico e nada tem,","e há quem se faz de pobre e tem muitos bens."],np:1},
{v:8,l:["A riqueza do homem serve de resgate da sua vida,","mas o pobre nem ouve ameaças."],np:1},
{v:9,l:["A luz dos justos brilha alegre,","mas a lâmpada dos ímpios se apaga."],np:1},
{v:10,l:["O orgulho só produz contendas,","mas a sabedoria está com os que aceitam conselhos."],np:1},
{v:11,l:["A riqueza ganha sem esforço diminui,","mas quem ajunta aos poucos a aumenta."],np:1},
{v:12,l:["A esperança que tarda adoece o coração,","mas o desejo realizado é árvore de vida."],np:1},
{v:13,l:["Quem despreza a palavra se arruína,","mas quem teme o mandamento será recompensado."],np:1},
{v:14,l:["O ensinamento do sábio é fonte de vida,","para evitar as armadilhas da morte."],np:1},
{v:15,l:["O bom senso atrai o favor,","mas o caminho dos traidores é áspero."],np:1},
{v:16,l:["Todo homem prudente age com conhecimento,","mas o insensato exibe a sua insensatez."],np:1},
{v:17,l:["O mensageiro ímpio cai na desgraça,","mas o enviado fiel traz a cura."],np:1},
{v:18,l:["Pobreza e desonra para quem rejeita a disciplina,","mas quem aceita a repreensão será honrado."],np:1},
{v:19,l:["O desejo realizado é doce para a alma,","mas os insensatos detestam afastar-se do mal."],np:1},
{v:20,l:["Quem anda com os sábios se torna sábio,","mas quem se junta aos insensatos se dá mal."],np:1},
{v:21,l:["A desgraça persegue os pecadores,","mas os justos são recompensados com o bem."],np:1},
{v:22,l:["O homem bom deixa herança aos filhos dos filhos,","mas a riqueza do pecador está reservada para o justo."],np:1},
{v:23,l:["O campo lavrado dos pobres dá muito alimento,","mas há quem pereça por falta de justiça."],np:1},
{v:24,l:["Quem poupa a vara odeia o seu filho,","mas quem o ama o corrige desde cedo."],np:1,n:"Nota do tradutor: a vara é a imagem da correção na educação antiga; o sentido do provérbio é que o amor verdadeiro não deixa de corrigir (compare Hebreus 12,5–11)."},
{v:25,l:["O justo come até se saciar,","mas o ventre dos ímpios passa necessidade."],np:1}
];

window.TEXTOS_SEED["proverbios"][14] = [
{s:"A sabedoria edifica a casa"},
{v:1,l:["A mulher sábia edifica a sua casa,","mas a insensata a destrói com as próprias mãos."]},
{v:2,l:["Quem anda com retidão teme o Senhor,","mas quem se desvia dos seus caminhos o despreza."],np:1},
{v:3,l:["Na boca do insensato está a vara do orgulho,","mas os lábios dos sábios os protegem."],np:1},
{v:4,l:["Onde não há bois, o cocho fica limpo,","mas a força do boi dá colheitas abundantes."],np:1},
{v:5,l:["A testemunha fiel não mente,","mas a testemunha falsa profere mentiras."],np:1},
{v:6,l:["O zombador busca a sabedoria e não a encontra,","mas para o inteligente o conhecimento é fácil."],np:1},
{v:7,l:["Afasta-te do homem insensato,","pois não encontrarás nos seus lábios o conhecimento."],np:1},
{v:8,l:["A sabedoria do prudente é entender o seu caminho,","mas a insensatez dos insensatos é engano."],np:1},
{v:9,l:["Os insensatos zombam da culpa,","mas entre os retos há boa vontade."],np:1},
{v:10,l:["O coração conhece a sua própria amargura,","e nenhum estranho participa da sua alegria."],np:1},
{v:11,l:["A casa dos ímpios será destruída,","mas a tenda dos retos florescerá."],np:1},
{v:12,l:["Há caminhos que ao homem parecem retos,","mas no fim conduzem à morte."],np:1},
{v:13,l:["Mesmo no riso o coração pode sofrer,","e a alegria acaba em tristeza."],np:1},
{v:14,l:["O de coração desviado se fartará dos seus caminhos,","e o homem bom, das suas obras."],np:1},
{v:15,l:["O ingênuo acredita em tudo o que se diz,","mas o prudente examina os seus passos."],np:1},
{v:16,l:["O sábio teme e se afasta do mal,","mas o insensato se irrita e se sente seguro."],np:1},
{v:17,l:["Quem se irrita facilmente faz loucuras,","e o homem de maus desígnios é odiado."],np:1},
{v:18,l:["Os ingênuos herdam a insensatez,","mas os prudentes se coroam de conhecimento."],np:1},
{v:19,l:["Os maus se inclinam diante dos bons,","e os ímpios às portas do justo."],np:1},
{v:20,l:["O pobre é odiado até pelo seu próximo,","mas os amigos do rico são muitos."],np:1},
{v:21,l:["Quem despreza o seu próximo peca,","mas feliz quem tem compaixão dos pobres!"],np:1},
{v:22,l:["Não se extraviam os que tramam o mal?","Bondade e fidelidade para os que planejam o bem."],np:1},
{v:23,l:["Em todo trabalho há proveito,","mas a conversa fiada só leva à pobreza."],np:1},
{v:24,l:["A coroa dos sábios é a sua riqueza;","a insensatez dos insensatos é só insensatez."],np:1},
{v:25,l:["A testemunha verdadeira salva vidas,","mas quem profere mentiras é um enganador."],np:1},
{v:26,l:["No temor do Senhor há confiança firme,","e os seus filhos terão um refúgio."],np:1},
{v:27,l:["O temor do Senhor é fonte de vida,","para evitar as armadilhas da morte."],np:1},
{v:28,l:["Um povo numeroso é a glória do rei;","a falta de gente é a ruína do príncipe."],np:1},
{v:29,l:["Quem é paciente tem muita inteligência,","mas o impaciente exalta a insensatez."],np:1},
{v:30,l:["Um coração tranquilo é vida para o corpo,","mas a inveja é cárie dos ossos."],np:1},
{v:31,l:["Quem oprime o pobre ultraja o seu Criador,","mas quem tem compaixão do necessitado o honra."],np:1},
{v:32,l:["O ímpio é derrubado pela sua maldade,","mas o justo encontra refúgio na sua integridade."],np:1,n:"Assim a Nova Vulgata, com o grego; o hebraico diz: mas o justo encontra refúgio até na sua morte."},
{v:33,l:["A sabedoria repousa no coração do inteligente;","no meio dos insensatos, será ela conhecida?"],np:1},
{v:34,l:["A justiça eleva uma nação,","mas o pecado é a vergonha dos povos."],np:1},
{v:35,l:["O servo sensato tem o favor do rei,","mas a sua ira cai sobre o que o envergonha."],np:1}
];

window.TEXTOS_SEED["proverbios"][15] = [
{s:"A resposta branda"},
{v:1,l:["A resposta branda desvia a ira,","mas a palavra dura provoca a cólera."]},
{v:2,l:["A língua dos sábios torna agradável o conhecimento,","mas a boca dos insensatos derrama insensatez."],np:1},
{v:3,l:["Os olhos do Senhor estão em todo lugar,","observando os maus e os bons."],np:1},
{v:4,l:["A língua que cura é árvore de vida,","mas a língua perversa despedaça o espírito."],np:1},
{v:5,l:["O insensato despreza a disciplina do pai,","mas quem aceita a repreensão se torna prudente."],np:1},
{v:6,l:["Na casa do justo há grande abundância,","mas nos lucros do ímpio há inquietação."],np:1},
{v:7,l:["Os lábios dos sábios espalham o conhecimento,","mas o coração dos insensatos não é assim."],np:1},
{v:8,l:["O sacrifício dos ímpios é abominação para o Senhor,","mas a oração dos retos lhe agrada."],np:1},
{v:9,l:["O caminho do ímpio é abominação para o Senhor,","mas ele ama quem segue a justiça."],np:1},
{v:10,l:["Correção severa para quem abandona o caminho;","quem odeia a repreensão morrerá."],np:1},
{v:11,l:["A morada dos mortos e a Perdição estão diante do Senhor;","quanto mais os corações dos homens!"],np:1},
{v:12,l:["O zombador não gosta de quem o repreende;","não vai ter com os sábios."],np:1},
{v:13,l:["O coração alegre alegra o rosto,","mas a tristeza do coração abate o espírito."],np:1},
{v:14,l:["O coração inteligente busca o conhecimento,","mas a boca dos insensatos se alimenta de insensatez."],np:1},
{v:15,l:["Todos os dias do aflito são maus,","mas o coração contente é um banquete contínuo."],np:1},
{v:16,l:["Mais vale pouco com o temor do Senhor","do que um grande tesouro com inquietação."],np:1},
{v:17,l:["Mais vale um prato de verduras onde há amor","do que um boi cevado onde há ódio."],np:1},
{v:18,l:["O homem irascível provoca contendas,","mas o paciente acalma as disputas."],np:1},
{v:19,l:["O caminho do preguiçoso é como uma sebe de espinhos,","mas a vereda dos retos é uma estrada aplanada."],np:1},
{v:20,l:["O filho sábio alegra o pai,","mas o homem insensato despreza a mãe."],np:1},
{v:21,l:["A insensatez é alegria para quem não tem juízo,","mas o homem inteligente anda direito."],np:1},
{v:22,l:["Os projetos fracassam onde não há conselho,","mas se realizam com muitos conselheiros."],np:1},
{v:23,l:["O homem se alegra com a resposta da sua boca;","e como é boa a palavra dita a seu tempo!"],np:1},
{v:24,l:["Para o sensato, a vereda da vida sobe para o alto,","para que se afaste da morada dos mortos, lá embaixo."],np:1},
{v:25,l:["O Senhor derruba a casa dos soberbos,","mas mantém firmes os limites da viúva."],np:1},
{v:26,l:["Os maus pensamentos são abominação para o Senhor,","mas as palavras bondosas são puras."],np:1},
{v:27,l:["Quem é ávido de lucro perturba a sua casa,","mas quem odeia o suborno viverá."],np:1},
{v:28,l:["O coração do justo pondera antes de responder,","mas a boca dos ímpios derrama maldades."],np:1},
{v:29,l:["O Senhor está longe dos ímpios,","mas ouve a oração dos justos."],np:1},
{v:30,l:["O olhar luminoso alegra o coração,","e a boa notícia fortalece os ossos."],np:1},
{v:31,l:["O ouvido que escuta a repreensão salutar","habitará no meio dos sábios."],np:1},
{v:32,l:["Quem rejeita a disciplina despreza a si mesmo,","mas quem escuta a repreensão adquire juízo."],np:1},
{v:33,l:["O temor do Senhor é escola de sabedoria,","e a humildade precede a glória."],np:1}
];
