// =====================================================================
// Romanos — tradução dos originais (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo.
// =====================================================================


window.TEXTOS_SEED["romanos"][1] = [
{s:"Saudação"},
{v:1,t:"Paulo, servo de Cristo Jesus, chamado a ser apóstolo, separado para o Evangelho de Deus,",n:"A carta foi ditada em Corinto, por volta do ano 57, a uma Igreja que o Apóstolo ainda não conhecia. É a mais extensa e a mais ordenada das suas cartas, e a única dirigida a uma comunidade que ele não fundara."},
{v:2,t:"que ele antes prometera, por seus profetas, nas Escrituras santas,"},
{v:3,t:"acerca de seu Filho, nascido da descendência de Davi segundo a carne,"},
{v:4,t:"constituído Filho de Deus em poder, segundo o Espírito de santidade, pela ressurreição dos mortos: Jesus Cristo, nosso Senhor.",n:"Os versículos 3 e 4 parecem recolher uma fórmula de fé anterior a Paulo. Não dizem que Cristo passou a ser Filho na ressurreição, mas que nela foi entronizado em poder aquele que já o era desde sempre."},
{v:5,t:"Por ele recebemos a graça e o apostolado, para levar à obediência da fé, em favor do seu nome, todos os gentios,"},
{v:6,t:"entre os quais estais também vós, chamados de Jesus Cristo;"},
{v:7,t:"a todos os que estão em Roma, amados de Deus, chamados a ser santos: graça a vós e paz, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo."},
{s:"Desejo de visitar os romanos"},
{v:8,t:"Antes de tudo, dou graças ao meu Deus, por Jesus Cristo, a respeito de todos vós, porque a vossa fé é anunciada no mundo inteiro."},
{v:9,t:"Pois Deus, a quem sirvo em meu espírito no Evangelho de seu Filho, é testemunha de como sem cessar faço memória de vós,"},
{v:10,t:"pedindo sempre, em minhas orações, que enfim, de algum modo, pela vontade de Deus, se me abra caminho para ir até vós."},
{v:11,t:"Porque desejo ver-vos, para vos comunicar algum dom espiritual que vos fortaleça;"},
{v:12,t:"isto é, para que, estando entre vós, juntos nos confortemos pela fé que nos é comum, a vossa e a minha."},
{v:13,t:"Não quero que ignoreis, irmãos, que muitas vezes me propus ir ter convosco — e até agora fui impedido —, para colher também entre vós algum fruto, como entre os demais gentios.",np:1},
{v:14,t:"Sou devedor a gregos e a bárbaros, a sábios e a ignorantes;"},
{v:15,t:"daí o meu empenho em anunciar o Evangelho também a vós, que estais em Roma."},
{s:"O Evangelho, poder de Deus"},
{v:16,t:"Porque não me envergonho do Evangelho: ele é poder de Deus para a salvação de todo o que crê, primeiro do judeu e também do grego."},
{v:17,t:"Pois nele se revela a justiça de Deus, de fé em fé, como está escrito: O justo viverá da fé.",n:"A justiça de Deus não é aqui a que pune, mas a que salva: a fidelidade com que Deus cumpre a sua promessa e torna justo o pecador. É o tema de toda a carta."},
{s:"A ira de Deus contra a impiedade"},
{v:18,t:"Revela-se, com efeito, do céu, a ira de Deus contra toda impiedade e injustiça dos homens que, pela injustiça, retêm cativa a verdade;"},
{v:19,t:"porquanto o que de Deus se pode conhecer é manifesto entre eles, pois Deus lho manifestou."},
{v:20,t:"Com efeito, desde a criação do mundo, as perfeições invisíveis de Deus — o seu eterno poder e a sua divindade — tornaram-se visíveis à inteligência por meio das obras. De sorte que são inescusáveis;"},
{v:21,t:"pois, tendo conhecido a Deus, não o glorificaram como Deus nem lhe deram graças; ao contrário, desvaneceram-se nos seus raciocínios, e o seu coração insensato se obscureceu."},
{v:22,t:"Dizendo-se sábios, tornaram-se loucos,"},
{v:23,t:"e trocaram a glória do Deus incorruptível pela imagem do homem corruptível, e de aves, de quadrúpedes e de répteis."},
{v:24,t:"Por isso Deus os entregou, nos desejos do seu coração, à impureza, de modo que entre si desonraram os próprios corpos —",np:1},
{v:25,t:"eles, que trocaram a verdade de Deus pela mentira, e veneraram e serviram à criatura em lugar do Criador, o qual é bendito pelos séculos. Amém."},
{v:26,t:"Por isso Deus os entregou a paixões infames: as suas mulheres trocaram o uso natural por outro, contra a natureza;"},
{v:27,t:"e do mesmo modo também os homens, deixando o uso natural da mulher, abrasaram-se em desejo uns pelos outros, cometendo torpeza, homens com homens, e recebendo em si mesmos a paga devida ao seu extravio."},
{v:28,t:"E, como não julgaram digno guardar o conhecimento de Deus, Deus os entregou a um pensar reprovado, para fazerem o que não convém:",np:1},
{v:29,t:"cheios de toda injustiça, malícia, cobiça e maldade; repletos de inveja, homicídio, contenda, dolo e malignidade; murmuradores,"},
{v:30,t:"difamadores, inimigos de Deus, insolentes, soberbos, fanfarrões, inventores de males, rebeldes aos pais,"},
{v:31,t:"insensatos, desleais, sem afeição, sem misericórdia."},
{v:32,t:"E, conhecendo embora o decreto de Deus — que são dignos de morte os que tais coisas praticam —, não somente as fazem, mas ainda aprovam os que as praticam."}
];

window.TEXTOS_SEED["romanos"][2] = [
{s:"O juízo de Deus não faz acepção de pessoas"},
{v:1,t:"És, portanto, inescusável, ó homem, tu que julgas, sejas quem fores; porque, naquilo em que julgas o outro, a ti mesmo te condenas, pois praticas o mesmo, tu que julgas."},
{v:2,t:"Ora, sabemos que o juízo de Deus é segundo a verdade contra os que tais coisas praticam."},
{v:3,t:"Pensas, ó homem, tu que julgas os que praticam tais coisas e as fazes, que escaparás ao juízo de Deus?"},
{v:4,t:"Ou desprezas as riquezas da sua bondade, da sua tolerância e da sua longanimidade, ignorando que a bondade de Deus te conduz ao arrependimento?"},
{v:5,t:"Pela tua dureza e pelo teu coração impenitente, acumulas contra ti ira para o dia da ira e da revelação do justo juízo de Deus,"},
{v:6,t:"que retribuirá a cada um segundo as suas obras:"},
{v:7,t:"a vida eterna aos que, perseverando em fazer o bem, buscam glória, honra e incorruptibilidade;"},
{v:8,t:"mas ira e indignação aos que, por espírito de contenda, não obedecem à verdade e se entregam à injustiça."},
{v:9,t:"Tribulação e angústia sobre toda alma humana que faz o mal: primeiro do judeu e também do grego;"},
{v:10,t:"glória, honra e paz a todo o que faz o bem: primeiro ao judeu e também ao grego."},
{v:11,t:"Porque em Deus não há acepção de pessoas."},
{s:"A lei escrita no coração"},
{v:12,t:"Todos os que pecaram sem a lei, sem a lei também perecerão; e todos os que pecaram sob a lei, pela lei serão julgados."},
{v:13,t:"Pois não são justos diante de Deus os que ouvem a lei; serão justificados os que a cumprem."},
{v:14,t:"Quando os gentios, que não têm lei, fazem por natureza o que a lei manda, eles, sem terem lei, são lei para si mesmos;"},
{v:15,t:"e mostram que a obra da lei está escrita nos seus corações, dando disso testemunho a sua consciência e os seus pensamentos, que ora os acusam, ora os defendem,",n:"Não se trata de um saber aprendido, mas da lei impressa na consciência, anterior a toda revelação escrita. Sobre ela se funda a responsabilidade dos que nunca ouviram a Escritura."},
{v:16,t:"no dia em que Deus julgar o que há de oculto nos homens, segundo o meu Evangelho, por Cristo Jesus."},
{s:"O judeu e a lei"},
{v:17,t:"Mas, se tu te chamas judeu, e repousas na lei, e te glorias em Deus,",np:1},
{v:18,t:"e conheces a sua vontade, e, instruído pela lei, discernes o que é melhor,"},
{v:19,t:"e estás persuadido de seres guia de cegos, luz dos que estão nas trevas,"},
{v:20,t:"educador dos ignorantes, mestre dos simples, por teres na lei a expressão do conhecimento e da verdade —"},
{v:21,t:"tu, pois, que ensinas o outro, a ti mesmo não te ensinas? Tu, que pregas que não se deve furtar, furtas?"},
{v:22,t:"Tu, que dizes que não se deve adulterar, adulteras? Tu, que abominas os ídolos, saqueias os templos?"},
{v:23,t:"Tu, que te glorias na lei, desonras a Deus pela transgressão da lei?"},
{v:24,t:"Porque, como está escrito, o nome de Deus é blasfemado entre os gentios por vossa causa."},
{s:"A circuncisão do coração"},
{v:25,t:"A circuncisão é proveitosa, de fato, se guardas a lei; mas, se és transgressor da lei, a tua circuncisão tornou-se incircuncisão."},
{v:26,t:"Se, pois, o incircunciso guarda os preceitos da lei, não será a sua incircuncisão tida por circuncisão?"},
{v:27,t:"E aquele que por natureza é incircunciso, cumprindo a lei, julgará a ti, que, com a letra e a circuncisão, és transgressor da lei."},
{v:28,t:"Porque não é judeu o que o é por fora, nem é circuncisão a que é exterior, na carne;"},
{v:29,t:"mas é judeu o que o é por dentro, e circuncisão é a do coração, segundo o espírito e não a letra; e o seu louvor não vem dos homens, mas de Deus."}
];

window.TEXTOS_SEED["romanos"][3] = [
{s:"A fidelidade de Deus"},
{v:1,t:"Qual é, então, a vantagem do judeu? Ou qual a utilidade da circuncisão?"},
{v:2,t:"Grande, sob todos os aspectos. Em primeiro lugar, porque a eles foram confiados os oráculos de Deus."},
{v:3,t:"Que importa, pois, que alguns tenham sido infiéis? Acaso a sua infidelidade anulará a fidelidade de Deus?"},
{v:4,t:"De modo nenhum! Antes, seja Deus verdadeiro e todo homem mentiroso, como está escrito: Para que sejas justificado nas tuas palavras e venças quando fores julgado."},
{v:5,t:"Mas, se a nossa injustiça faz ressaltar a justiça de Deus, que diremos? Será injusto Deus ao descarregar a sua ira? — falo à maneira humana."},
{v:6,t:"De modo nenhum! Do contrário, como julgaria Deus o mundo?"},
{v:7,t:"Se, porém, pela minha mentira redundou em maior glória sua a verdade de Deus, por que sou eu ainda julgado como pecador?"},
{v:8,t:"E por que não havemos de fazer o mal para que venha o bem — como caluniosamente nos atribuem alguns, afirmando que assim falamos? A condenação desses é justa."},
{s:"Todos estão sob o pecado"},
{v:9,t:"E então? Levamos vantagem? De modo nenhum. Porque já acusamos a todos, judeus e gregos, de estarem sob o pecado,"},
{v:10,l:["como está escrito:","Não há justo, nem um sequer;"]},
{v:11,l:["não há quem entenda,","não há quem busque a Deus."]},
{v:12,l:["Todos se desviaram, juntos se corromperam;","não há quem faça o bem, não há nem um sequer."]},
{v:13,l:["A sua garganta é sepulcro aberto,","com a língua urdem o engano;","veneno de áspides sob os seus lábios."]},
{v:14,l:["A sua boca está cheia de maldição e amargura."]},
{v:15,l:["Os seus pés são velozes para derramar sangue;"]},
{v:16,l:["ruína e miséria há nos seus caminhos,"]},
{v:17,l:["e não conheceram o caminho da paz."]},
{v:18,l:["Não há temor de Deus diante dos seus olhos."]},
{v:19,t:"Ora, sabemos que tudo o que a lei diz, o diz aos que estão sob a lei, para que toda boca se cale e o mundo inteiro se reconheça réu diante de Deus;",np:1},
{v:20,t:"porque nenhuma carne será justificada diante dele pelas obras da lei; pela lei, com efeito, vem o conhecimento do pecado."},
{s:"A justiça de Deus pela fé"},
{v:21,t:"Agora, porém, sem a lei, manifestou-se a justiça de Deus, testemunhada pela Lei e pelos Profetas:"},
{v:22,t:"justiça de Deus pela fé em Jesus Cristo, para todos os que creem. Não há distinção:"},
{v:23,t:"todos pecaram e estão privados da glória de Deus;"},
{v:24,t:"e são justificados gratuitamente, pela graça dele, mediante a redenção que está em Cristo Jesus."},
{v:25,t:"A ele Deus propôs como propiciação, pela fé, em seu sangue, para manifestar a sua justiça — pois deixara passar, na sua paciência, os pecados cometidos antes;",n:"Propiciação traduz hilasterion, que designa a tampa da arca, onde no Dia da Expiação se aspergia o sangue. Cristo é o lugar do encontro entre Deus e o pecador, e a sua própria carne é o santuário."},
{v:26,t:"para manifestar a sua justiça no tempo presente, a fim de ser ele justo e justificar aquele que vive da fé em Jesus."},
{s:"A fé exclui a jactância"},
{v:27,t:"Onde está, pois, a jactância? Foi excluída. Por qual lei? Pela das obras? Não, mas pela lei da fé."},
{v:28,t:"Concluímos, portanto, que o homem é justificado pela fé, sem as obras da lei."},
{v:29,t:"Ou será Deus apenas dos judeus? Não o é também dos gentios? Sim, também dos gentios,"},
{v:30,t:"pois um só é Deus, que justificará pela fé o circunciso, e mediante a fé o incircunciso."},
{v:31,t:"Anulamos, então, a lei pela fé? De modo nenhum! Antes, confirmamos a lei."}
];

window.TEXTOS_SEED["romanos"][4] = [
{s:"Abraão, justificado pela fé"},
{v:1,t:"Que diremos, pois, ter alcançado Abraão, nosso pai segundo a carne?"},
{v:2,t:"Porque, se Abraão foi justificado pelas obras, tem de que se gloriar — mas não diante de Deus."},
{v:3,t:"Pois que diz a Escritura? Abraão creu em Deus, e isso lhe foi contado como justiça."},
{v:4,t:"Ora, ao que trabalha, o salário não é contado como favor, mas como dívida;"},
{v:5,t:"ao que, porém, não trabalha, mas crê naquele que justifica o ímpio, a sua fé lhe é contada como justiça."},
{v:6,t:"Assim também Davi proclama bem-aventurado o homem a quem Deus atribui a justiça sem as obras:"},
{v:7,l:["Bem-aventurados aqueles cujas iniquidades foram perdoadas","e cujos pecados foram cobertos;"]},
{v:8,l:["bem-aventurado o homem a quem o Senhor não imputa o pecado."]},
{s:"A fé precedeu a circuncisão"},
{v:9,t:"Esta bem-aventurança recai sobre os circuncisos, ou também sobre os incircuncisos? Dizemos, com efeito, que a fé foi contada a Abraão como justiça."},
{v:10,t:"Como, então, lhe foi contada? Depois de circuncidado, ou antes? Não depois, mas antes de ser circuncidado."},
{v:11,t:"E recebeu o sinal da circuncisão como selo da justiça da fé que tivera enquanto incircunciso, para ser pai de todos os que creem sem serem circuncidados — de modo que também a eles seja contada a justiça —,"},
{v:12,t:"e pai dos circuncisos: não dos que apenas são circuncisos, mas dos que seguem as pegadas da fé que nosso pai Abraão teve quando ainda era incircunciso."},
{s:"A promessa vem da fé, não da lei"},
{v:13,t:"Porque não foi pela lei que veio a Abraão, ou à sua descendência, a promessa de ser herdeiro do mundo, mas pela justiça da fé."},
{v:14,t:"Pois, se os herdeiros são os da lei, a fé ficou vazia e a promessa, anulada;"},
{v:15,t:"a lei, de fato, produz a ira; onde não há lei, também não há transgressão."},
{v:16,t:"Por isso é pela fé, para que seja por graça, e assim a promessa fique firme para toda a descendência — não só para a que é da lei, mas também para a que é da fé de Abraão, o qual é pai de todos nós,"},
{v:17,t:"conforme está escrito: Eu te constituí pai de muitas nações. E ele o é diante daquele em quem creu, Deus, que vivifica os mortos e chama à existência as coisas que não são."},
{s:"A fé de Abraão, figura da nossa"},
{v:18,t:"Esperando contra toda esperança, creu que viria a ser pai de muitas nações, segundo o que lhe fora dito: Assim será a tua descendência."},
{v:19,t:"E não enfraqueceu na fé ao considerar o seu corpo já amortecido — tinha quase cem anos — e o seio de Sara, igualmente morto."},
{v:20,t:"Diante da promessa de Deus, não vacilou por incredulidade; ao contrário, fortaleceu-se na fé, dando glória a Deus,"},
{v:21,t:"plenamente convencido de que Deus é poderoso para cumprir o que prometeu."},
{v:22,t:"Por isso também lhe foi contado como justiça."},
{v:23,t:"E não foi só por causa dele que se escreveu: Foi-lhe contado;",np:1},
{v:24,t:"mas também por causa de nós, a quem há de ser contado, a nós que cremos naquele que ressuscitou dos mortos a Jesus, nosso Senhor,"},
{v:25,t:"o qual foi entregue por causa das nossas faltas e ressuscitado para a nossa justificação."}
];

window.TEXTOS_SEED["romanos"][5] = [
{s:"Os frutos da justificação"},
{v:1,t:"Justificados, pois, pela fé, estamos em paz com Deus, por nosso Senhor Jesus Cristo,"},
{v:2,t:"por quem também temos acesso, pela fé, a esta graça em que nos mantemos firmes; e gloriamo-nos na esperança da glória de Deus."},
{v:3,t:"E não só isso: gloriamo-nos até nas tribulações, sabendo que a tribulação produz a paciência;"},
{v:4,t:"a paciência, a virtude provada; e a virtude provada, a esperança."},
{v:5,t:"Ora, a esperança não engana, porque o amor de Deus foi derramado nos nossos corações pelo Espírito Santo, que nos foi dado."},
{v:6,t:"Com efeito, quando ainda éramos fracos, Cristo, no tempo devido, morreu pelos ímpios.",np:1},
{v:7,t:"Dificilmente alguém morre por um justo; por um homem de bem, talvez haja quem se atreva a morrer."},
{v:8,t:"Mas Deus prova o seu amor para conosco: quando ainda éramos pecadores, Cristo morreu por nós."},
{v:9,t:"Muito mais, pois, agora que fomos justificados em seu sangue, seremos por ele salvos da ira."},
{v:10,t:"Porque, se, quando éramos inimigos, fomos reconciliados com Deus pela morte de seu Filho, muito mais, já reconciliados, seremos salvos pela sua vida."},
{v:11,t:"E não só isso: gloriamo-nos em Deus, por nosso Senhor Jesus Cristo, por quem agora recebemos a reconciliação."},
{s:"Adão e Cristo"},
{v:12,t:"Portanto, como por um só homem entrou o pecado no mundo, e pelo pecado a morte, assim a morte passou a todos os homens, porque todos pecaram.",n:"Deste versículo a tradição extraiu a doutrina do pecado original: a morte alcança a todos porque o pecado de um só se tornou a condição em que todos nascem e na qual cada um peca por sua conta."},
{v:13,t:"Porque, até a lei, havia pecado no mundo; mas o pecado não é levado em conta quando não há lei."},
{v:14,t:"Todavia, a morte reinou de Adão até Moisés, mesmo sobre aqueles que não pecaram à semelhança da transgressão de Adão, o qual é figura daquele que havia de vir."},
{v:15,t:"Mas o dom não é como a falta. Porque, se pela falta de um só morreram muitos, muito mais transbordaram sobre muitos a graça de Deus e o dom concedido na graça de um só homem, Jesus Cristo.",np:1},
{v:16,t:"E o dom não é como o efeito de um só que pecou: o julgamento, a partir de uma só falta, levou à condenação; mas o dom gratuito, a partir de muitas faltas, leva à justificação."},
{v:17,t:"Se, pela falta de um só, a morte reinou por esse um, muito mais reinarão na vida, por um só, Jesus Cristo, os que recebem a abundância da graça e do dom da justiça."},
{v:18,t:"Assim, pois, como por uma só falta veio a condenação para todos os homens, assim também por um só ato de justiça vem para todos os homens a justificação que dá a vida.",np:1},
{v:19,t:"Porque, como pela desobediência de um só homem muitos se tornaram pecadores, assim também pela obediência de um só muitos se tornarão justos."},
{v:20,t:"Sobreveio a lei, para que abundasse a falta; mas, onde abundou o pecado, superabundou a graça,"},
{v:21,t:"a fim de que, como o pecado reinou na morte, assim também reine a graça pela justiça, para a vida eterna, por Jesus Cristo, nosso Senhor."}
];

window.TEXTOS_SEED["romanos"][6] = [
{s:"Mortos ao pecado pelo batismo"},
{v:1,t:"Que diremos, então? Permaneceremos no pecado, para que abunde a graça?"},
{v:2,t:"De modo nenhum! Nós, que morremos ao pecado, como viveremos ainda nele?"},
{v:3,t:"Ou ignorais que todos nós, batizados em Cristo Jesus, fomos batizados na sua morte?"},
{v:4,t:"Fomos, pois, sepultados com ele pelo batismo na morte, para que, como Cristo ressuscitou dos mortos pela glória do Pai, assim também nós caminhemos em novidade de vida.",n:"Batizar traduz um verbo grego que significa mergulhar. A descida à água e a saída dela desenham a sepultura e a ressurreição, e por isso o rito é figura do que nele se realiza."},
{v:5,t:"Porque, se fomos enxertados nele pela semelhança da sua morte, também o seremos pela da sua ressurreição."},
{v:6,t:"Sabemos isto: o nosso homem velho foi crucificado com ele, para que fosse destruído o corpo do pecado e não sirvamos mais ao pecado."},
{v:7,t:"Pois quem morreu está livre do pecado."},
{v:8,t:"Ora, se morremos com Cristo, cremos que também com ele viveremos,",np:1},
{v:9,t:"sabendo que Cristo, ressuscitado dos mortos, já não morre: a morte não tem mais domínio sobre ele."},
{v:10,t:"Porque, ao morrer, morreu para o pecado de uma vez por todas; e, ao viver, vive para Deus."},
{v:11,t:"Assim também vós: considerai-vos mortos ao pecado e vivos para Deus, em Cristo Jesus."},
{s:"Não reine o pecado em vós"},
{v:12,t:"Não reine, portanto, o pecado no vosso corpo mortal, de modo que obedeçais aos seus desejos;"},
{v:13,t:"nem ofereçais os vossos membros ao pecado como armas de injustiça; mas oferecei-vos a Deus como vivos, saídos da morte, e os vossos membros a Deus, como armas de justiça."},
{v:14,t:"O pecado não terá domínio sobre vós, pois não estais sob a lei, mas sob a graça."},
{s:"Servos da justiça"},
{v:15,t:"Que então? Havemos de pecar, porque não estamos sob a lei, mas sob a graça? De modo nenhum!"},
{v:16,t:"Não sabeis que, quando vos ofereceis a alguém como escravos para lhe obedecer, sois escravos daquele a quem obedeceis — ou do pecado, para a morte, ou da obediência, para a justiça?"},
{v:17,t:"Graças a Deus, porém, porque fostes escravos do pecado, mas obedecestes de coração à forma de doutrina a que fostes entregues;"},
{v:18,t:"e, libertados do pecado, vos tornastes servos da justiça."},
{v:19,t:"Falo à maneira humana, por causa da fraqueza da vossa carne. Assim como oferecestes os vossos membros como escravos da impureza e da iniquidade, para a iniquidade, assim agora oferecei os vossos membros como servos da justiça, para a santificação.",np:1},
{v:20,t:"Quando éreis escravos do pecado, éreis livres quanto à justiça."},
{v:21,t:"Que fruto colhíeis então daquilo de que agora vos envergonhais? O fim de tais coisas é a morte."},
{v:22,t:"Agora, porém, libertados do pecado e feitos servos de Deus, tendes por fruto a santificação, e por fim, a vida eterna."},
{v:23,t:"Porque o salário do pecado é a morte; mas o dom gratuito de Deus é a vida eterna, em Cristo Jesus, nosso Senhor."}
];

window.TEXTOS_SEED["romanos"][7] = [
{s:"Libertos da lei"},
{v:1,t:"Ou ignorais, irmãos — falo a quem conhece a lei —, que a lei tem domínio sobre o homem por todo o tempo em que ele vive?"},
{v:2,t:"A mulher casada está ligada pela lei ao marido enquanto ele vive; mas, se o marido morrer, fica desligada da lei do marido."},
{v:3,t:"Portanto, será chamada adúltera se, vivendo o marido, se unir a outro homem; mas, se o marido morrer, está livre da lei, e não é adúltera ao unir-se a outro."},
{v:4,t:"Assim também vós, meus irmãos, fostes mortos à lei pelo corpo de Cristo, para pertencerdes a outro, àquele que ressuscitou dos mortos, a fim de que frutifiquemos para Deus."},
{v:5,t:"Porque, quando estávamos na carne, as paixões pecaminosas, despertadas pela lei, agiam nos nossos membros e frutificavam para a morte."},
{v:6,t:"Agora, porém, libertados da lei, mortos àquilo que nos prendia, servimos em novidade de espírito, e não na velhice da letra."},
{s:"A lei e o pecado"},
{v:7,t:"Que diremos, pois? Que a lei é pecado? De modo nenhum! Mas eu não teria conhecido o pecado senão pela lei; porque não conheceria a cobiça, se a lei não dissesse: Não cobiçarás."},
{v:8,t:"Tomando ocasião do preceito, o pecado produziu em mim toda espécie de cobiça; porque, sem a lei, o pecado está morto."},
{v:9,t:"Eu vivia outrora sem a lei; mas, sobrevindo o preceito, o pecado reviveu,"},
{v:10,t:"e eu morri. E aquele preceito, que era para a vida, veio a ser para mim morte;"},
{v:11,t:"porque o pecado, tomando ocasião do preceito, me seduziu, e por ele me matou."},
{v:12,t:"Assim, a lei é santa, e o preceito é santo, justo e bom."},
{v:13,t:"Então o que é bom tornou-se morte para mim? De modo nenhum! Foi o pecado que, para se manifestar como pecado, me causou a morte por meio do que é bom — de sorte que o pecado se tornasse, pelo preceito, pecador além de toda medida."},
{s:"O combate interior"},
{v:14,t:"Sabemos que a lei é espiritual; eu, porém, sou carnal, vendido ao pecado.",n:"O eu que aqui fala não é só o de Paulo: é o homem posto diante da lei sem a graça, que reconhece o bem e não tem força para cumpri-lo. A resposta virá no capítulo seguinte."},
{v:15,t:"Não entendo o que faço: não faço o que quero, mas o que detesto, isso faço."},
{v:16,t:"Ora, se faço o que não quero, reconheço que a lei é boa."},
{v:17,t:"Então já não sou eu que o faço, mas o pecado que habita em mim."},
{v:18,t:"Sei que em mim, isto é, na minha carne, não habita o bem; pois o querer está em mim, mas o realizar o bem, não."},
{v:19,t:"Não faço o bem que quero, mas o mal que não quero, esse pratico."},
{v:20,t:"Ora, se faço o que não quero, já não sou eu que o faço, mas o pecado que habita em mim."},
{v:21,t:"Descubro, portanto, esta lei: quando quero fazer o bem, é o mal que se me apresenta.",np:1},
{v:22,t:"Deleito-me, segundo o homem interior, na lei de Deus;"},
{v:23,t:"mas vejo nos meus membros outra lei, que guerreia contra a lei da minha mente e me faz cativo da lei do pecado, que está nos meus membros."},
{v:24,t:"Infeliz homem que sou! Quem me livrará deste corpo de morte?"},
{v:25,t:"Graças a Deus, por Jesus Cristo, nosso Senhor! Assim, eu mesmo, pela mente, sirvo à lei de Deus; pela carne, porém, à lei do pecado."}
];

window.TEXTOS_SEED["romanos"][8] = [
{s:"A vida no Espírito"},
{v:1,t:"Nenhuma condenação, portanto, pesa agora sobre os que estão em Cristo Jesus."},
{v:2,t:"Porque a lei do Espírito da vida, em Cristo Jesus, te libertou da lei do pecado e da morte."},
{v:3,t:"O que era impossível à lei, enfraquecida como estava pela carne, Deus o fez: enviando o seu próprio Filho em carne semelhante à do pecado e por causa do pecado, condenou o pecado na carne,",n:"Semelhante à do pecado: a carne assumida é verdadeiramente a nossa, mas sem pecado. A semelhança está na condição mortal que ele tomou, não em pecado algum que tivesse."},
{v:4,t:"para que a justiça da lei se cumprisse em nós, que não caminhamos segundo a carne, mas segundo o Espírito."},
{v:5,t:"Com efeito, os que vivem segundo a carne pensam nas coisas da carne; os que vivem segundo o Espírito, nas coisas do Espírito."},
{v:6,t:"Ora, a aspiração da carne é morte; a aspiração do Espírito, vida e paz."},
{v:7,t:"Porque a aspiração da carne é inimizade contra Deus: não se submete à lei de Deus, nem o pode."},
{v:8,t:"Os que estão na carne não podem agradar a Deus."},
{v:9,t:"Vós, porém, não estais na carne, mas no Espírito, se de fato o Espírito de Deus habita em vós. Se alguém não tem o Espírito de Cristo, esse não lhe pertence.",np:1},
{v:10,t:"Ora, se Cristo está em vós, o corpo, na verdade, está morto por causa do pecado, mas o espírito é vida por causa da justiça."},
{v:11,t:"E, se o Espírito daquele que ressuscitou Jesus dentre os mortos habita em vós, aquele que ressuscitou Cristo Jesus dos mortos dará vida também aos vossos corpos mortais, pelo seu Espírito que habita em vós."},
{v:12,t:"Assim, irmãos, somos devedores — mas não à carne, para vivermos segundo a carne."},
{v:13,t:"Porque, se viverdes segundo a carne, morrereis; mas, se pelo Espírito fizerdes morrer as obras do corpo, vivereis."},
{s:"Filhos e herdeiros"},
{v:14,t:"Pois todos os que são conduzidos pelo Espírito de Deus, esses são filhos de Deus."},
{v:15,t:"E não recebestes um espírito de escravidão, para recairdes no temor; recebestes o Espírito de adoção, no qual clamamos: Abba, Pai!",n:"Abba é a palavra aramaica com que o filho chama o pai em casa, e é a que o próprio Jesus usou no Getsêmani. Que a oração cristã a repita é o sinal de que a filiação é real."},
{v:16,t:"O próprio Espírito dá testemunho, junto ao nosso espírito, de que somos filhos de Deus."},
{v:17,t:"E, se filhos, também herdeiros: herdeiros de Deus e coerdeiros de Cristo, contanto que soframos com ele, para com ele sermos glorificados."},
{s:"A expectativa da criação"},
{v:18,t:"Considero que os sofrimentos do tempo presente não têm proporção com a glória que há de revelar-se em nós."},
{v:19,t:"Porque a criação, em ansiosa expectativa, aguarda a revelação dos filhos de Deus."},
{v:20,t:"Ela foi submetida à vaidade — não de vontade própria, mas por causa daquele que a submeteu — na esperança"},
{v:21,t:"de que também ela há de ser libertada da escravidão da corrupção, para a liberdade da glória dos filhos de Deus."},
{v:22,t:"Sabemos, com efeito, que toda a criação geme e sofre dores de parto até o dia de hoje."},
{v:23,t:"E não só ela: também nós, que temos as primícias do Espírito, gememos dentro de nós, aguardando a adoção, a redenção do nosso corpo."},
{v:24,t:"Porque na esperança fomos salvos. Ora, esperança que se vê não é esperança: o que alguém já vê, como ainda o esperaria?"},
{v:25,t:"Mas, se esperamos o que não vemos, é na paciência que o aguardamos."},
{s:"O Espírito intercede por nós"},
{v:26,t:"Do mesmo modo, também o Espírito vem em auxílio da nossa fraqueza; porque não sabemos o que pedir como convém, mas o próprio Espírito intercede por nós com gemidos que não se podem exprimir."},
{v:27,t:"E aquele que perscruta os corações sabe qual é a aspiração do Espírito, pois é segundo Deus que ele intercede pelos santos."},
{s:"O desígnio de Deus"},
{v:28,t:"Sabemos que Deus faz concorrer todas as coisas para o bem dos que o amam, daqueles que são chamados segundo o seu desígnio."},
{v:29,t:"Porque aos que de antemão conheceu, também os predestinou a serem conformes à imagem de seu Filho, para que ele seja o primogênito entre muitos irmãos."},
{v:30,t:"E aos que predestinou, também os chamou; aos que chamou, também os justificou; e aos que justificou, também os glorificou."},
{s:"Hino ao amor de Cristo"},
{v:31,t:"Que diremos, pois, diante disso? Se Deus é por nós, quem será contra nós?"},
{v:32,t:"Aquele que nem ao próprio Filho poupou, mas por todos nós o entregou, como não nos dará com ele todas as coisas?"},
{v:33,t:"Quem acusará os eleitos de Deus? É Deus quem justifica."},
{v:34,t:"Quem condenará? Cristo Jesus, que morreu, ou antes, que ressuscitou, está à direita de Deus e intercede por nós."},
{v:35,t:"Quem nos separará do amor de Cristo? A tribulação, a angústia, a perseguição, a fome, a nudez, o perigo, a espada?",np:1},
{v:36,l:["Como está escrito:","Por tua causa somos entregues à morte o dia inteiro;","fomos tidos como ovelhas de matadouro."]},
{v:37,t:"Mas em tudo isso vencemos, e de sobra, por aquele que nos amou.",np:1},
{v:38,t:"Porque estou certo de que nem a morte, nem a vida, nem os anjos, nem os principados, nem o presente, nem o futuro, nem as potestades,"},
{v:39,t:"nem a altura, nem a profundidade, nem qualquer outra criatura poderá separar-nos do amor de Deus, que está em Cristo Jesus, nosso Senhor."}
];

window.TEXTOS_SEED["romanos"][9] = [
{s:"A tristeza do Apóstolo por Israel"},
{v:1,t:"Digo a verdade em Cristo, não minto — disso me dá testemunho a minha consciência no Espírito Santo —:"},
{v:2,t:"tenho no coração grande tristeza e dor contínua."},
{v:3,t:"Pois eu mesmo desejaria ser anátema, separado de Cristo, em favor de meus irmãos, meus parentes segundo a carne,"},
{v:4,t:"que são israelitas: deles são a adoção, a glória, as alianças, a legislação, o culto e as promessas;"},
{v:5,t:"deles são os patriarcas, e deles procede Cristo segundo a carne, ele que está acima de tudo, Deus bendito pelos séculos. Amém.",n:"Os capítulos 9 a 11 formam um bloco à parte: não tratam da salvação do indivíduo, mas do destino de Israel, e do que significa a sua recusa para a fidelidade de Deus."},
{s:"A promessa e a eleição"},
{v:6,t:"Não que a palavra de Deus haja falhado. Porque nem todos os que descendem de Israel são Israel;"},
{v:7,t:"nem, por serem descendência de Abraão, são todos filhos; mas: Em Isaac terás a tua descendência."},
{v:8,t:"Isto é: não são os filhos da carne que são filhos de Deus, mas os filhos da promessa é que são contados como descendência."},
{v:9,t:"Porque esta é a palavra da promessa: Por este tempo virei, e Sara terá um filho."},
{v:10,t:"E não só isso: também Rebeca concebeu de um só homem, Isaac, nosso pai.",np:1},
{v:11,t:"Pois, quando ainda não eram nascidos e nada tinham feito de bem ou de mal — para que permanecesse o desígnio de Deus segundo a eleição,"},
{v:12,t:"o qual não depende das obras, mas daquele que chama —, foi-lhe dito: O mais velho servirá ao mais novo,"},
{v:13,t:"conforme está escrito: Amei a Jacó e odiei a Esaú.",n:"Odiar, na língua da Escritura, diz muitas vezes preterir, amar menos. Não se afirma um ódio de Deus por Esaú, mas a liberdade com que escolhe o mais novo contra o direito do nascimento."},
{s:"A liberdade da misericórdia"},
{v:14,t:"Que diremos, pois? Haverá injustiça em Deus? De modo nenhum!"},
{v:15,t:"Porque a Moisés ele diz: Terei misericórdia de quem me aprouver, e me compadecerei de quem eu quiser."},
{v:16,t:"Assim, não depende do que quer, nem do que corre, mas de Deus, que usa de misericórdia."},
{v:17,t:"Pois a Escritura diz ao faraó: Para isto mesmo te levantei: para mostrar em ti o meu poder e para que o meu nome seja anunciado em toda a terra."},
{v:18,t:"Portanto, de quem quer, tem misericórdia; e a quem quer, endurece."},
{s:"O oleiro e o barro"},
{v:19,t:"Mas tu me dirás: Por que, então, ainda se queixa? Pois quem resiste à sua vontade?"},
{v:20,t:"Ó homem, quem és tu para replicares a Deus? Porventura dirá o vaso ao que o modelou: Por que me fizeste assim?"},
{v:21,t:"Ou não tem o oleiro poder sobre o barro, para da mesma massa fazer um vaso para uso nobre e outro para uso vil?"},
{v:22,t:"E que dizer, se Deus, querendo mostrar a sua ira e dar a conhecer o seu poder, suportou com muita paciência vasos de ira, prontos para a perdição,"},
{v:23,t:"a fim de manifestar as riquezas da sua glória em vasos de misericórdia, que de antemão preparou para a glória?"},
{v:24,t:"E esses somos nós, a quem chamou, não só dentre os judeus, mas também dentre os gentios."},
{s:"Anunciado pelos profetas"},
{v:25,l:["Como também diz em Oseias:","Chamarei meu povo ao que não era meu povo,","e amada à que não era amada."]},
{v:26,l:["E no lugar em que se lhes disse: Vós não sois meu povo,","aí serão chamados filhos do Deus vivo."]},
{v:27,l:["E Isaías clama acerca de Israel:","Ainda que o número dos filhos de Israel seja como a areia do mar,","só um resto será salvo;"]},
{v:28,l:["porque o Senhor cumprirá na terra a sua palavra,","plenamente e sem demora."]},
{v:29,l:["E, como predisse o mesmo Isaías:","Se o Senhor dos exércitos não nos tivesse deixado descendência,","teríamos ficado como Sodoma e seríamos semelhantes a Gomorra."]},
{s:"Israel tropeçou na pedra"},
{v:30,t:"Que diremos, pois? Que os gentios, que não buscavam a justiça, alcançaram a justiça — a justiça que vem da fé;",np:1},
{v:31,t:"ao passo que Israel, que buscava uma lei de justiça, não chegou a essa lei."},
{v:32,t:"Por quê? Porque a buscava não pela fé, mas como se viesse das obras. Tropeçaram na pedra de tropeço,"},
{v:33,l:["conforme está escrito:","Eis que ponho em Sião uma pedra de tropeço","e uma rocha de escândalo;","e quem nela crer não será confundido."]}
];

window.TEXTOS_SEED["romanos"][10] = [
{s:"Um zelo sem discernimento"},
{v:1,t:"Irmãos, o desejo do meu coração e a minha súplica a Deus por eles são para que sejam salvos."},
{v:2,t:"Dou-lhes testemunho de que têm zelo de Deus, mas não segundo o conhecimento."},
{v:3,t:"Porque, desconhecendo a justiça de Deus e procurando estabelecer a sua própria, não se submeteram à justiça de Deus."},
{v:4,t:"Pois o fim da lei é Cristo, para justiça de todo o que crê.",n:"A palavra grega telos diz termo e diz meta. A lei acaba em Cristo porque é nele que chega ao seu destino: não foi revogada, mas cumprida."},
{s:"A justiça que vem da fé"},
{v:5,t:"Moisés escreve, acerca da justiça que vem da lei: O homem que a praticar viverá por ela."},
{v:6,t:"Mas a justiça que vem da fé fala assim: Não digas no teu coração: Quem subirá ao céu? — isto é, para fazer descer a Cristo;"},
{v:7,t:"ou: Quem descerá ao abismo? — isto é, para fazer subir a Cristo dentre os mortos."},
{v:8,t:"Que diz, então? Perto de ti está a palavra, na tua boca e no teu coração — isto é, a palavra da fé que pregamos."},
{v:9,t:"Porque, se com a tua boca confessares que Jesus é Senhor, e no teu coração creres que Deus o ressuscitou dos mortos, serás salvo."},
{v:10,t:"Com o coração se crê para a justiça, e com a boca se confessa para a salvação."},
{v:11,t:"Pois diz a Escritura: Todo o que nele crê não será confundido."},
{v:12,t:"Não há distinção entre judeu e grego: um mesmo é o Senhor de todos, rico para com todos os que o invocam."},
{v:13,t:"Porque todo aquele que invocar o nome do Senhor será salvo."},
{s:"É preciso que alguém anuncie"},
{v:14,t:"Mas como invocarão aquele em quem não creram? E como crerão naquele de quem não ouviram? E como ouvirão, se não há quem pregue?"},
{v:15,t:"E como pregarão, se não forem enviados? Conforme está escrito: Quão formosos os pés dos que anunciam o bem!"},
{v:16,t:"Mas nem todos obedeceram ao Evangelho. Pois Isaías diz: Senhor, quem creu na nossa pregação?"},
{v:17,t:"Logo, a fé vem da pregação, e a pregação, pela palavra de Cristo."},
{v:18,t:"Pergunto, porém: Acaso não ouviram? Ao contrário: Por toda a terra correu a sua voz, e as suas palavras, até os confins do mundo.",np:1},
{v:19,t:"E pergunto ainda: Acaso Israel não entendeu? Já Moisés dizia: Hei de tornar-vos ciumentos de um povo que não é povo; hei de irritar-vos contra uma nação insensata."},
{v:20,t:"E Isaías ousa dizer: Fui achado pelos que não me buscavam; manifestei-me aos que não perguntavam por mim."},
{v:21,t:"Mas de Israel diz: Todo o dia estendi as mãos a um povo desobediente e rebelde."}
];

window.TEXTOS_SEED["romanos"][11] = [
{s:"O resto de Israel"},
{v:1,t:"Pergunto, pois: Acaso Deus rejeitou o seu povo? De modo nenhum! Também eu sou israelita, da descendência de Abraão, da tribo de Benjamim."},
{v:2,t:"Deus não rejeitou o seu povo, que de antemão conheceu. Ou não sabeis o que diz a Escritura a respeito de Elias, quando ele se queixa a Deus contra Israel?"},
{v:3,t:"Senhor, mataram os teus profetas, derrubaram os teus altares; só eu fiquei, e procuram tirar-me a vida."},
{v:4,t:"Mas que lhe responde o oráculo divino? Reservei para mim sete mil homens, que não dobraram o joelho diante de Baal."},
{v:5,t:"Assim também, no tempo presente, subsiste um resto, escolhido pela graça."},
{v:6,t:"E, se é pela graça, já não é pelas obras; do contrário, a graça já não seria graça."},
{v:7,t:"Que dizer, então? O que Israel buscava, não o alcançou; alcançaram-no os eleitos, e os demais foram endurecidos,"},
{v:8,t:"conforme está escrito: Deus lhes deu um espírito de torpor, olhos para não verem e ouvidos para não ouvirem, até o dia de hoje."},
{v:9,l:["E Davi diz:","Torne-se a sua mesa em laço e em armadilha,","em tropeço e em justo castigo;"]},
{v:10,l:["escureçam-se os seus olhos para que não vejam,","e curva-lhes para sempre as costas."]},
{s:"A queda de Israel e a salvação dos gentios"},
{v:11,t:"Pergunto, pois: Tropeçaram para caírem de vez? De modo nenhum! Mas, pela sua queda, veio a salvação aos gentios, para despertar o ciúme deles."},
{v:12,t:"Ora, se a sua queda é riqueza do mundo, e a sua diminuição, riqueza dos gentios, quanto mais o será a sua plenitude!"},
{v:13,t:"A vós, gentios, é que falo. Enquanto sou apóstolo dos gentios, honro o meu ministério,"},
{v:14,t:"para ver se de algum modo desperto o ciúme dos meus irmãos de sangue e salvo alguns deles."},
{v:15,t:"Porque, se a rejeição deles é reconciliação do mundo, que será o seu acolhimento, senão vida dentre os mortos?"},
{v:16,t:"Se as primícias são santas, também a massa o é; e, se a raiz é santa, também os ramos o são."},
{s:"A oliveira e os ramos"},
{v:17,t:"Se alguns ramos foram cortados, e tu, oliveira brava, foste enxertado no lugar deles e feito participante da raiz e da seiva da oliveira,"},
{v:18,t:"não te glories contra os ramos. Se te glorias, lembra-te de que não és tu que sustentas a raiz, mas a raiz é que te sustenta."},
{v:19,t:"Dirás, então: Os ramos foram cortados para que eu fosse enxertado."},
{v:20,t:"Muito bem. Foram cortados por causa da incredulidade; tu, porém, estás firme pela fé. Não te ensoberbeças; antes, teme."},
{v:21,t:"Porque, se Deus não poupou os ramos naturais, também não há de poupar-te a ti."},
{v:22,t:"Considera, pois, a bondade e a severidade de Deus: severidade para com os que caíram; bondade de Deus para contigo, se permaneceres nessa bondade — do contrário, também tu serás cortado."},
{v:23,t:"E eles, se não permanecerem na incredulidade, serão enxertados; porque Deus é poderoso para enxertá-los de novo."},
{v:24,t:"Pois, se tu foste cortado da oliveira brava, à qual pertencias por natureza, e contra a natureza foste enxertado em oliveira boa, quanto mais eles, que lhe pertencem por natureza, serão enxertados na sua própria oliveira!"},
{s:"Todo o Israel será salvo"},
{v:25,t:"Não quero, irmãos, que ignoreis este mistério — para que não vos tenhais por sábios —: o endurecimento de uma parte de Israel dura até que entre a plenitude dos gentios;"},
{v:26,t:"e assim todo o Israel será salvo, conforme está escrito: De Sião virá o libertador; ele afastará de Jacó as impiedades."},
{v:27,t:"E esta será a minha aliança com eles, quando eu tirar os seus pecados."},
{v:28,t:"Quanto ao Evangelho, são inimigos, por vossa causa; mas, quanto à eleição, são amados, por causa dos pais.",np:1},
{v:29,t:"Porque os dons e o chamamento de Deus são irrevogáveis."},
{v:30,t:"Assim como vós, outrora, fostes desobedientes a Deus, mas agora alcançastes misericórdia pela desobediência deles,"},
{v:31,t:"assim também eles agora foram desobedientes, para que, pela misericórdia que alcançastes, também eles alcancem misericórdia."},
{v:32,t:"Porque Deus encerrou a todos na desobediência, para de todos ter misericórdia."},
{s:"Hino à sabedoria de Deus"},
{v:33,l:["Ó profundidade da riqueza, da sabedoria e da ciência de Deus!","Quão insondáveis são os seus juízos","e quão inescrutáveis, os seus caminhos!"]},
{v:34,l:["Pois quem conheceu o pensamento do Senhor?","Ou quem foi o seu conselheiro?"]},
{v:35,l:["Ou quem lhe deu primeiro,","para que lhe seja retribuído?"]},
{v:36,l:["Porque dele, por ele e para ele são todas as coisas.","A ele a glória pelos séculos. Amém."]}
];

window.TEXTOS_SEED["romanos"][12] = [
{s:"O culto espiritual"},
{v:1,t:"Rogo-vos, pois, irmãos, pela misericórdia de Deus, que ofereçais os vossos corpos como sacrifício vivo, santo e agradável a Deus: é este o vosso culto espiritual.",n:"Aqui começa a parte exortativa da carta. O sacrifício deixa de ser o do animal imolado e passa a ser a vida inteira do fiel, oferecida no corpo, isto é, no que ele tem de mais concreto."},
{v:2,t:"E não vos conformeis a este mundo; mas transformai-vos pela renovação da mente, para que saibais discernir qual é a vontade de Deus, o que é bom, o que lhe agrada, o que é perfeito."},
{s:"Muitos membros, um só corpo"},
{v:3,t:"Pela graça que me foi dada, digo a cada um de vós: ninguém se estime além do que convém; ao contrário, tenha cada um de si um juízo sóbrio, segundo a medida de fé que Deus lhe repartiu."},
{v:4,t:"Porque, assim como num só corpo temos muitos membros, e nem todos os membros têm a mesma função,"},
{v:5,t:"assim nós, embora muitos, somos um só corpo em Cristo, e cada um, de per si, membro dos outros."},
{v:6,t:"Temos dons diferentes, segundo a graça que nos foi dada: quem tem a profecia, exerça-a segundo a medida da fé;"},
{v:7,t:"quem tem o ministério, sirva no ministério; quem ensina, no ensino;"},
{v:8,t:"quem exorta, na exortação; quem reparte, faça-o com simplicidade; quem preside, com diligência; quem exerce a misericórdia, com alegria."},
{s:"As regras da caridade"},
{v:9,t:"Seja o amor sem fingimento. Detestai o mal, apegai-vos ao bem."},
{v:10,t:"Amai-vos cordialmente uns aos outros com afeto fraterno; adiantai-vos em honrar uns aos outros."},
{v:11,t:"Na diligência, não sejais preguiçosos; sede fervorosos no espírito; servi ao Senhor."},
{v:12,t:"Alegrai-vos na esperança; sede pacientes na tribulação; perseverai na oração."},
{v:13,t:"Acudi às necessidades dos santos; empenhai-vos na hospitalidade."},
{v:14,t:"Abençoai os que vos perseguem; abençoai e não amaldiçoeis.",np:1},
{v:15,t:"Alegrai-vos com os que se alegram; chorai com os que choram."},
{v:16,t:"Tende entre vós o mesmo sentir; não cultiveis pensamentos de grandeza, mas acompanhai os humildes. Não vos tenhais por sábios."},
{v:17,t:"A ninguém pagueis mal com mal; cuidai de fazer o bem diante de todos os homens."},
{v:18,t:"Se for possível, quanto depender de vós, vivei em paz com todos os homens."},
{v:19,t:"Não vos vingueis, caríssimos, mas dai lugar à ira de Deus; porque está escrito: A mim pertence a vingança, eu retribuirei, diz o Senhor."},
{v:20,t:"Ao contrário: Se o teu inimigo tiver fome, dá-lhe de comer; se tiver sede, dá-lhe de beber; porque, fazendo isso, amontoarás brasas vivas sobre a sua cabeça."},
{v:21,t:"Não te deixes vencer pelo mal; vence o mal com o bem."}
];

window.TEXTOS_SEED["romanos"][13] = [
{s:"A submissão às autoridades"},
{v:1,t:"Toda alma se submeta às autoridades constituídas; porque não há autoridade que não venha de Deus, e as que existem foram por ele ordenadas."},
{v:2,t:"Quem, portanto, resiste à autoridade, resiste à disposição de Deus; e os que resistem atraem sobre si a condenação."},
{v:3,t:"Porque os governantes não são temor para as boas obras, mas para as más. Queres não temer a autoridade? Faze o bem, e dela receberás louvor;"},
{v:4,t:"pois ela é ministra de Deus para o teu bem. Mas, se fizeres o mal, teme: não é sem motivo que traz a espada; é ministra de Deus, vingadora para castigar quem pratica o mal."},
{v:5,t:"Por isso é necessário submeter-se, não só por causa do castigo, mas também por causa da consciência."},
{v:6,t:"É ainda por isso que pagais tributos; porque os que governam são servidores de Deus, aplicados a essa mesma função."},
{v:7,t:"Dai a cada um o que lhe é devido: a quem o tributo, o tributo; a quem o imposto, o imposto; a quem o temor, o temor; a quem a honra, a honra."},
{s:"O amor, plenitude da lei"},
{v:8,t:"A ninguém devais coisa alguma, senão o amor mútuo; porque quem ama o próximo cumpriu a lei."},
{v:9,t:"Com efeito: Não adulterarás, não matarás, não furtarás, não cobiçarás; e qualquer outro preceito se resume nesta palavra: Amarás o teu próximo como a ti mesmo."},
{v:10,t:"O amor não faz mal ao próximo; o amor é, portanto, a plenitude da lei."},
{s:"A noite vai adiantada"},
{v:11,t:"E isto, porque conheceis o tempo: já é hora de despertardes do sono, pois agora a salvação está mais perto de nós do que quando abraçamos a fé."},
{v:12,t:"A noite vai adiantada, o dia se aproxima. Deixemos, pois, as obras das trevas e revistamo-nos das armas da luz."},
{v:13,t:"Comportemo-nos com decência, como em pleno dia: não em orgias e bebedeiras, não em desonestidades e devassidões, não em contendas e ciúmes."},
{v:14,t:"Ao contrário, revesti-vos do Senhor Jesus Cristo, e não cuideis da carne de modo a satisfazer-lhe as concupiscências.",n:"Foi este versículo que Santo Agostinho leu no jardim de Milão, quando a voz da criança lhe disse que tomasse e lesse. Ele conta que não quis ler mais adiante: bastava."}
];

window.TEXTOS_SEED["romanos"][14] = [
{s:"Não julgar o irmão"},
{v:1,t:"Acolhei o que é fraco na fé, sem entrar em discussão de opiniões.",n:"Havia em Roma quem se abstivesse de carne e de vinho e observasse certos dias, por escrúpulo de pureza. Paulo não decide a questão pelo rito: sujeita-a ao amor."},
{v:2,t:"Um crê que pode comer de tudo; o que é fraco come legumes."},
{v:3,t:"Quem come não despreze o que não come; e quem não come não julgue o que come, pois Deus o acolheu."},
{v:4,t:"Quem és tu para julgares o servo alheio? Se está de pé ou se cai, é com o seu senhor. E ficará de pé, porque o Senhor é poderoso para o sustentar."},
{v:5,t:"Um faz diferença entre um dia e outro; outro julga iguais todos os dias. Esteja cada qual plenamente convencido no seu próprio juízo."},
{v:6,t:"Quem faz caso do dia, fá-lo para o Senhor; e quem come, come para o Senhor, pois dá graças a Deus; e quem não come, não come para o Senhor, e também dá graças a Deus."},
{v:7,t:"Porque nenhum de nós vive para si mesmo, e nenhum morre para si mesmo:",np:1},
{v:8,t:"se vivemos, para o Senhor vivemos; se morremos, para o Senhor morremos. Portanto, quer vivamos, quer morramos, somos do Senhor."},
{v:9,t:"Pois foi para isto que Cristo morreu e voltou à vida: para ser Senhor dos mortos e dos vivos."},
{v:10,t:"Tu, então, por que julgas o teu irmão? E tu, por que desprezas o teu irmão? Todos havemos de comparecer diante do tribunal de Deus,"},
{v:11,l:["porque está escrito:","Por minha vida, diz o Senhor, diante de mim se dobrará todo joelho,","e toda língua dará glória a Deus."]},
{v:12,t:"Assim, cada um de nós há de prestar contas de si mesmo a Deus."},
{s:"Não pôr tropeço diante do irmão"},
{v:13,t:"Não nos julguemos mais uns aos outros; julgai antes que não se deve pôr diante do irmão tropeço nem escândalo."},
{v:14,t:"Sei, e estou persuadido no Senhor Jesus, de que nada é impuro em si mesmo; é impuro somente para quem assim o considera."},
{v:15,t:"Se, por causa de um alimento, o teu irmão se entristece, já não caminhas segundo o amor. Não percas, por causa da tua comida, aquele por quem Cristo morreu."},
{v:16,t:"Não seja, pois, blasfemado o bem que possuís."},
{v:17,t:"Porque o Reino de Deus não é comida nem bebida, mas justiça, paz e alegria no Espírito Santo."},
{v:18,t:"Quem assim serve a Cristo é agradável a Deus e aprovado pelos homens."},
{v:19,t:"Busquemos, portanto, o que serve à paz e à edificação mútua.",np:1},
{v:20,t:"Não destruas a obra de Deus por causa de um alimento. Tudo, na verdade, é puro; mas é mau, para o homem, comer dando escândalo."},
{v:21,t:"Bom é não comer carne, nem beber vinho, nem fazer coisa alguma em que o teu irmão tropece."},
{v:22,t:"A convicção que tens, guarda-a para ti, diante de Deus. Feliz aquele que não se condena naquilo que aprova."},
{v:23,t:"Mas quem come na dúvida está condenado, porque não age por fé; e tudo o que não vem da fé é pecado."}
];

window.TEXTOS_SEED["romanos"][15] = [
{s:"Acolher-se como Cristo acolheu"},
{v:1,t:"Nós, que somos fortes, devemos suportar as fraquezas dos que não o são, e não agradar a nós mesmos."},
{v:2,t:"Cada um de nós procure agradar ao próximo no que é bom, para edificá-lo."},
{v:3,t:"Pois também Cristo não buscou o próprio agrado; ao contrário, como está escrito: As injúrias dos que te ultrajavam caíram sobre mim."},
{v:4,t:"Ora, tudo o que antes foi escrito, para nosso ensino foi escrito, a fim de que, pela paciência e pela consolação das Escrituras, tenhamos esperança."},
{v:5,t:"O Deus da paciência e da consolação vos conceda ter entre vós o mesmo sentir, segundo Cristo Jesus,"},
{v:6,t:"para que, unânimes, a uma só voz, glorifiqueis a Deus, Pai de nosso Senhor Jesus Cristo."},
{v:7,t:"Acolhei-vos, pois, uns aos outros, como também Cristo vos acolheu, para a glória de Deus.",np:1},
{v:8,t:"Digo, com efeito, que Cristo se fez servidor dos circuncisos, por fidelidade de Deus, para confirmar as promessas feitas aos pais;"},
{v:9,t:"quanto aos gentios, é pela misericórdia que glorificam a Deus, conforme está escrito: Por isso te louvarei entre as nações e cantarei ao teu nome."},
{v:10,t:"E ainda diz: Alegrai-vos, nações, com o seu povo."},
{v:11,t:"E outra vez: Louvai o Senhor, todas as nações; que todos os povos o glorifiquem."},
{v:12,t:"E Isaías, por sua vez, diz: Virá a raiz de Jessé, aquele que se levanta para governar as nações; nele hão de esperar os gentios."},
{v:13,t:"O Deus da esperança vos encha de toda alegria e paz na fé, para que abundeis na esperança, pela força do Espírito Santo."},
{s:"O ministério de Paulo entre os gentios"},
{v:14,t:"Estou convencido, meus irmãos, a vosso respeito, de que estais cheios de bondade, repletos de todo conhecimento, capazes de admoestar-vos uns aos outros."},
{v:15,t:"Escrevi-vos, porém, com certa ousadia, em parte para vos reavivar a memória, em virtude da graça que Deus me concedeu:"},
{v:16,t:"ser ministro de Cristo Jesus entre os gentios, exercendo o sagrado ofício do Evangelho de Deus, para que a oblação dos gentios seja aceita, santificada no Espírito Santo."},
{v:17,t:"Tenho, pois, de que me gloriar em Cristo Jesus, no que toca a Deus."},
{v:18,t:"Porque não ousaria falar de coisa alguma que Cristo não tenha realizado por meu intermédio, para levar os gentios à obediência, por palavras e por obras,"},
{v:19,t:"pela força de sinais e prodígios, pela força do Espírito de Deus. De sorte que, de Jerusalém e arredores até o Ilírico, levei a termo o Evangelho de Cristo,"},
{v:20,t:"empenhando-me, todavia, em anunciá-lo onde o nome de Cristo ainda não fora pronunciado, para não edificar sobre alicerce alheio;"},
{v:21,t:"mas, como está escrito: Hão de ver aqueles a quem nada se anunciara, e hão de entender os que não tinham ouvido."},
{s:"Projetos de viagem"},
{v:22,t:"Foi isso que muitas vezes me impediu de ir ter convosco."},
{v:23,t:"Agora, porém, não tendo mais campo nestas regiões, e desejando há muitos anos ir ver-vos,"},
{v:24,t:"espero fazê-lo quando partir para a Espanha; pois conto ver-vos de passagem e ser por vós encaminhado para lá, depois de haver gozado um pouco da vossa companhia."},
{v:25,t:"Por ora, vou a Jerusalém, a serviço dos santos.",np:1},
{v:26,t:"Porque a Macedônia e a Acaia houveram por bem fazer uma coleta em favor dos pobres, entre os santos de Jerusalém.",n:"A coleta ocupa o Apóstolo em toda a sua última viagem. Mais que uma esmola, é o sinal visível de que as Igrejas dos gentios e a de Jerusalém são um só corpo."},
{v:27,t:"Assim o houveram por bem, e de fato lhes são devedores; porque, se os gentios se tornaram participantes dos seus bens espirituais, devem também servi-los com os bens materiais."},
{v:28,t:"Concluída essa tarefa, e entregue em mãos esse fruto, partirei para a Espanha, passando por vós."},
{v:29,t:"E sei que, ao ir ter convosco, irei na plenitude da bênção de Cristo."},
{s:"Pedido de orações"},
{v:30,t:"Rogo-vos, irmãos, por nosso Senhor Jesus Cristo e pelo amor do Espírito, que luteis comigo nas orações que por mim fazeis a Deus,"},
{v:31,t:"para que eu seja livrado dos incrédulos da Judeia, e para que o meu serviço em Jerusalém seja bem acolhido pelos santos;"},
{v:32,t:"e para que, pela vontade de Deus, eu chegue até vós com alegria e junto de vós encontre algum repouso."},
{v:33,t:"O Deus da paz esteja com todos vós. Amém."}
];

window.TEXTOS_SEED["romanos"][16] = [
{s:"Recomendação de Febe"},
{v:1,t:"Recomendo-vos Febe, nossa irmã, que é diaconisa da Igreja de Cencreia,",n:"Cencreia era o porto oriental de Corinto. Febe provavelmente levou consigo esta carta, e a recomendação serve-lhe de credencial diante de uma comunidade que não a conhecia."},
{v:2,t:"para que a recebais no Senhor, de modo digno dos santos, e a assistais em tudo o que precisar de vós; pois ela própria foi protetora de muitos, e de mim também."},
{s:"Saudações"},
{v:3,t:"Saudai Prisca e Áquila, meus colaboradores em Cristo Jesus —"},
{v:4,t:"eles arriscaram a cabeça pela minha vida, e não sou só eu que lhes agradeço, mas também todas as Igrejas dos gentios —"},
{v:5,t:"e saudai a Igreja que se reúne na casa deles. Saudai o meu querido Epêneto, primícias da Ásia para Cristo."},
{v:6,t:"Saudai Maria, que muito trabalhou por vós."},
{v:7,t:"Saudai Andrônico e Júnia, meus parentes e companheiros de prisão, que se distinguem entre os apóstolos e que estiveram em Cristo antes de mim."},
{v:8,t:"Saudai Ampliato, a quem amo no Senhor."},
{v:9,t:"Saudai Urbano, nosso colaborador em Cristo, e o meu querido Estáquis."},
{v:10,t:"Saudai Apeles, provado em Cristo. Saudai os da casa de Aristóbulo."},
{v:11,t:"Saudai Herodião, meu parente. Saudai os da casa de Narciso que estão no Senhor."},
{v:12,t:"Saudai Trifena e Trifosa, que trabalham no Senhor. Saudai a querida Pérside, que muito trabalhou no Senhor."},
{v:13,t:"Saudai Rufo, eleito no Senhor, e sua mãe, que é também minha."},
{v:14,t:"Saudai Asíncrito, Flegonte, Hermes, Pátrobas, Hermas e os irmãos que estão com eles."},
{v:15,t:"Saudai Filólogo e Júlia, Nereu e sua irmã, e Olimpas, e todos os santos que estão com eles."},
{v:16,t:"Saudai-vos uns aos outros com ósculo santo. Saúdam-vos todas as Igrejas de Cristo."},
{s:"Guardai-vos dos que dividem"},
{v:17,t:"Rogo-vos, irmãos, que vos acauteleis contra os que provocam divisões e escândalos, contra a doutrina que aprendestes. Afastai-vos deles."},
{v:18,t:"Porque tais homens não servem a Cristo, nosso Senhor, mas ao próprio ventre; e, com palavras suaves e lisonjas, seduzem os corações dos simples."},
{v:19,t:"A vossa obediência chegou ao conhecimento de todos, e por isso me alegro convosco. Mas quero que sejais sábios para o bem e íntegros para o mal."},
{v:20,t:"O Deus da paz em breve esmagará Satanás sob os vossos pés. A graça de nosso Senhor Jesus esteja convosco."},
{s:"Saudações dos companheiros"},
{v:21,t:"Saúda-vos Timóteo, meu colaborador, e também Lúcio, Jasão e Sosípatro, meus parentes."},
{v:22,t:"Eu, Tércio, que escrevi esta carta, saúdo-vos no Senhor.",n:"O secretário toma a palavra por um instante. A carta foi ditada, como era costume, e é o único lugar do Novo Testamento em que o escriba se nomeia."},
{v:23,t:"Saúda-vos Gaio, que me hospeda, e a ele toda a Igreja. Saúda-vos Erasto, tesoureiro da cidade, e o irmão Quarto.",n:"A Nova Vulgata não traz versículo 24. A fórmula de bênção que nele figurava em edições antigas falta nos melhores manuscritos, e por isso a numeração passa aqui do 23 ao 25."},
{s:"Doxologia"},
{v:25,t:"Àquele que é poderoso para vos confirmar, segundo o meu Evangelho e a pregação de Jesus Cristo, segundo a revelação do mistério guardado em silêncio nos tempos eternos,"},
{v:26,t:"e agora manifestado, e, pelas Escrituras proféticas, por ordem do Deus eterno, dado a conhecer a todas as nações, para as conduzir à obediência da fé —"},
{v:27,t:"a Deus, o único sábio, por Jesus Cristo, a glória pelos séculos dos séculos. Amém."}
];
