// =====================================================================
// Sabedoria — tradução do grego, cotejada com a Nova Vulgata (versificação: Nova Vulgata)
// Formato: {s:"subtítulo"} abre trecho; {v,t,n} prosa; {v,l:[...]} verso;
// np:1 marca início de parágrafo (nos poemas, de estrofe).
// =====================================================================

window.TEXTOS_SEED["sabedoria"][1] = [
{s:"Amai a justiça"},
{v:1,l:["Amai a justiça, vós que governais a terra;","pensai no Senhor com retidão","e procurai-o com simplicidade de coração,"],n:"O livro foi escrito em grego, provavelmente em Alexandria, no último século antes de Cristo. O autor fala em nome de Salomão (capítulos 7–9), mas não o nomeia."},
{v:2,l:["pois ele se deixa encontrar pelos que não o põem à prova","e se manifesta aos que não lhe negam a confiança."],np:1},
{v:3,l:["Os pensamentos tortuosos afastam de Deus,","e o seu poder, posto à prova, confunde os insensatos."],np:1},
{v:4,l:["A sabedoria não entra numa alma que trama o mal,","nem habita num corpo escravo do pecado."],np:1},
{v:5,l:["Pois o espírito santo, que educa, foge da falsidade,","afasta-se dos pensamentos insensatos","e se retira quando sobrevém a injustiça."],np:1},
{v:6,l:["A sabedoria é um espírito que ama os homens,","mas não deixa impune o blasfemo pelas suas palavras,","pois Deus é testemunha dos seus rins,","observador verdadeiro do seu coração","e ouvinte da sua língua."],np:1},
{v:7,l:["Pois o espírito do Senhor enche o universo,","e ele, que mantém unidas todas as coisas, conhece toda palavra."],np:1},
{v:8,l:["Por isso, quem diz coisas injustas não passará despercebido,","e a justiça, que condena, não o deixará escapar."],np:1},
{v:9,l:["Os desígnios do ímpio serão examinados,","e o eco das suas palavras chegará até o Senhor,","para condenação das suas iniquidades."],np:1},
{v:10,l:["Pois um ouvido zeloso tudo ouve,","e nem o sussurro das murmurações lhe fica oculto."],np:1},
{v:11,l:["Guardai-vos, pois, da murmuração inútil","e poupai a língua da maledicência,","pois nem a palavra dita em segredo fica sem efeito,","e a boca mentirosa mata a alma."],np:1},
{s:"Deus não fez a morte"},
{v:12,l:["Não procureis a morte com os desvios da vossa vida,","nem atraiais a ruína com as obras das vossas mãos,"]},
{v:13,l:["pois Deus não fez a morte,","nem se alegra com a perdição dos vivos."],np:1},
{v:14,l:["Ele criou todas as coisas para que existissem,","e as criaturas do mundo são salutares;","nelas não há veneno de morte,","nem a morada dos mortos reina sobre a terra."],np:1},
{v:15,l:["Pois a justiça é imortal."],np:1},
{v:16,l:["Mas os ímpios chamam a morte com gestos e palavras;","tendo-a por amiga, consomem-se por ela","e fazem aliança com ela,","pois merecem pertencer-lhe."],np:1}
];

window.TEXTOS_SEED["sabedoria"][2] = [
{s:"O raciocínio dos ímpios"},
{v:1,l:["Pois dizem entre si, raciocinando mal:","Breve e triste é a nossa vida,","não há remédio quando chega o fim do homem,","e não se conhece ninguém que tenha voltado da morada dos mortos."]},
{v:2,l:["Nascemos por acaso,","e depois seremos como se nunca tivéssemos existido;","o sopro das nossas narinas é fumaça,","e o pensamento, uma centelha no bater do nosso coração;"],np:1},
{v:3,l:["quando ela se apaga, o corpo se reduz a cinza,","e o espírito se dissipa como ar leve."],np:1},
{v:4,l:["Com o tempo o nosso nome será esquecido,","e ninguém se lembrará das nossas obras;","a nossa vida passará como o rastro de uma nuvem,","e se dissipará como a névoa","expulsa pelos raios do sol","e desfeita pelo seu calor."],np:1},
{v:5,l:["O nosso tempo é a passagem de uma sombra,","e o nosso fim não tem volta,","pois está selado, e ninguém retorna."],np:1},
{v:6,l:["Vinde, pois, gozemos dos bens presentes,","aproveitemos as criaturas com o ardor da juventude."],np:1},
{v:7,l:["Fartemo-nos de vinho precioso e de perfumes,","e não deixemos passar a flor da primavera;"],np:1},
{v:8,l:["coroemo-nos de botões de rosa antes que murchem."],np:1},
{v:9,l:["Que nenhum de nós fique sem parte na nossa orgia;","deixemos por toda parte sinais da nossa alegria,","pois esta é a nossa parte, esta é a nossa sorte."],np:1,n:"Nenhum de nós: assim o grego; a Nova Vulgata diz: nenhum prado."},
{v:10,l:["Oprimamos o justo que é pobre,","não poupemos a viúva,","nem respeitemos os cabelos brancos do ancião."],np:1},
{v:11,l:["Que a nossa força seja a norma da justiça,","pois o que é fraco se mostra inútil."],np:1},
{v:12,l:["Armemos ciladas ao justo, porque nos incomoda,","opõe-se às nossas obras,","censura-nos as faltas contra a lei","e nos acusa de faltas contra a educação que recebemos."],np:1},
{v:13,l:["Pretende ter o conhecimento de Deus","e se chama filho do Senhor."],np:1,n:"Filho do Senhor: em grego pais, que significa também servo (compare Isaías 52,13–53,12)."},
{v:14,l:["Tornou-se para nós uma censura dos nossos pensamentos;","só de vê-lo nos é insuportável,"],np:1},
{v:15,l:["pois a sua vida é diferente da dos outros,","e os seus caminhos são estranhos."],np:1},
{v:16,l:["Ele nos considera moeda falsa","e se afasta dos nossos caminhos como de imundícies;","proclama feliz o fim dos justos","e se gaba de ter Deus por pai."],np:1},
{v:17,l:["Vejamos se as suas palavras são verdadeiras","e experimentemos o que acontecerá no seu fim."],np:1},
{v:18,l:["Pois, se o justo é filho de Deus, Deus o socorrerá","e o livrará das mãos dos seus adversários."],np:1,n:"Compare Mateus 27,43."},
{v:19,l:["Provemo-lo com ultrajes e torturas,","para conhecermos a sua mansidão","e pormos à prova a sua paciência."],np:1},
{v:20,l:["Condenemo-lo a uma morte infame,","pois, segundo as suas palavras, Deus o visitará."],np:1},
{s:"O erro dos ímpios"},
{v:21,l:["Assim pensam, mas se enganam:","a sua maldade os cegou."]},
{v:22,l:["Não conhecem os segredos de Deus,","não esperam a recompensa da santidade,","nem acreditam no prêmio das almas irrepreensíveis."],np:1},
{v:23,l:["Pois Deus criou o homem para a incorruptibilidade","e o fez imagem da sua própria eternidade."],np:1,n:"Da sua própria eternidade: assim o grego; a Nova Vulgata diz: imagem da sua semelhança."},
{v:24,l:["Mas pela inveja do diabo a morte entrou no mundo,","e a experimentam os que pertencem ao seu partido."],np:1}
];

window.TEXTOS_SEED["sabedoria"][3] = [
{s:"As almas dos justos na mão de Deus"},
{v:1,l:["Mas as almas dos justos estão na mão de Deus,","e nenhum tormento os atingirá."]},
{v:2,l:["Aos olhos dos insensatos pareceram morrer;","a sua partida foi tida como uma desgraça,"],np:1},
{v:3,l:["e o seu afastamento de nós, como uma ruína;","mas eles estão em paz."],np:1},
{v:4,l:["Ainda que, aos olhos dos homens, tenham sido castigados,","a sua esperança está cheia de imortalidade;"],np:1},
{v:5,l:["depois de uma breve correção, receberão grandes benefícios,","pois Deus os provou","e os achou dignos de si."],np:1},
{v:6,l:["Provou-os como o ouro no crisol","e os aceitou como holocausto perfeito."],np:1},
{v:7,l:["No tempo da sua visita, eles brilharão","e correrão como centelhas no meio da palha."],np:1},
{v:8,l:["Julgarão as nações e dominarão os povos,","e o Senhor reinará sobre eles para sempre."],np:1},
{v:9,l:["Os que nele confiam compreenderão a verdade,","e os que são fiéis permanecerão junto dele no amor,","pois a graça e a misericórdia são para os seus eleitos,","e a sua visita, para os seus santos."],np:1},
{s:"A sorte dos ímpios"},
{v:10,l:["Mas os ímpios receberão o castigo que merecem os seus pensamentos,","eles que desprezaram o justo e se afastaram do Senhor."]},
{v:11,l:["Infeliz de quem despreza a sabedoria e a disciplina:","a sua esperança é vã, os seus trabalhos, sem fruto,","e as suas obras, inúteis."],np:1},
{v:12,l:["As suas mulheres são insensatas,","os seus filhos, perversos,","e a sua descendência, maldita."],np:1},
{v:13,l:["Feliz a estéril que é sem mancha,","que não conheceu união culpável:","terá o seu fruto quando Deus visitar as almas."],np:1},
{v:14,l:["Feliz também o eunuco que não cometeu a iniquidade com as mãos,","nem tramou o mal contra o Senhor:","ele receberá pela sua fidelidade uma graça escolhida","e uma parte muito agradável no templo do Senhor."],np:1,n:"Compare Isaías 56,3–5."},
{v:15,l:["Pois glorioso é o fruto dos bons trabalhos,","e a raiz da prudência não falha."],np:1},
{v:16,l:["Mas os filhos dos adúlteros não chegarão à maturidade,","e a descendência de uma união ilegítima desaparecerá."],np:1,n:"Nota do tradutor: o autor segue aqui a mentalidade tradicional, que via nos filhos o prolongamento dos pais; logo adiante (4,1–6) opõe a fecundidade da virtude à dos ímpios. A responsabilidade pessoal de cada um já é afirmada em Ezequiel 18."},
{v:17,l:["Ainda que vivam muito, não serão tidos em conta,","e no fim a sua velhice será sem honra;"],np:1},
{v:18,l:["se morrerem cedo, não terão esperança,","nem consolo no dia do julgamento."],np:1},
{v:19,l:["Pois terrível é o fim de uma geração injusta."],np:1}
];

window.TEXTOS_SEED["sabedoria"][4] = [
{s:"A fecundidade da virtude"},
{v:1,l:["Mais vale não ter filhos e possuir a virtude,","pois a sua memória é imortal:","ela é reconhecida por Deus e pelos homens."]},
{v:2,l:["Quando presente, é imitada;","quando ausente, é desejada;","e para sempre desfila coroada,","vencedora na disputa dos prêmios sem mancha."],np:1},
{v:3,l:["Mas a numerosa prole dos ímpios não servirá para nada:","nascida de rebentos bastardos, não lançará raízes profundas","nem assentará base segura."],np:1},
{v:4,l:["Ainda que por algum tempo reverdeça nos ramos,","mal firmada, será sacudida pelo vento","e arrancada pela violência dos ventos."],np:1},
{v:5,l:["Os seus galhos, ainda tenros, serão quebrados,","e o seu fruto será inútil,","verde demais para se comer, bom para nada."],np:1},
{v:6,l:["Pois os filhos nascidos de uniões ilícitas","são testemunhas da maldade dos pais","quando estes forem julgados."],np:1},
{s:"A morte prematura do justo"},
{v:7,l:["Mas o justo, ainda que morra antes do tempo,","estará em repouso."]},
{v:8,l:["Pois a velhice honrada não é a que dura muito,","nem se mede pelo número dos anos;"],np:1},
{v:9,l:["os cabelos brancos do homem são a prudência,","e a velhice é uma vida sem mancha."],np:1},
{v:10,l:["Tendo agradado a Deus, foi amado por ele,","e, como vivia entre pecadores, foi levado."],np:1,n:"Alusão a Henoc, que andou com Deus e foi levado por ele (Gênesis 5,24)."},
{v:11,l:["Foi arrebatado, para que a maldade não lhe alterasse a inteligência,","nem o engano lhe seduzisse a alma."],np:1},
{v:12,l:["Pois o fascínio do vício obscurece o bem,","e a vertigem da paixão perverte o espírito sem malícia."],np:1},
{v:13,l:["Chegando em pouco tempo à perfeição,","completou uma longa carreira."],np:1},
{v:14,l:["A sua alma era agradável ao Senhor;","por isso ele se apressou em tirá-lo do meio da maldade.","As multidões viram, mas não compreenderam,","nem refletiram nisto:"],np:1},
{v:15,l:["que a graça e a misericórdia são para os seus eleitos,","e a sua visita, para os seus santos."],np:1},
{v:16,l:["O justo que morreu condena os ímpios que vivem,","e a juventude que depressa chegou ao fim condena a longa velhice do injusto."],np:1},
{v:17,l:["Verão o fim do sábio,","mas não compreenderão o que o Senhor quis para ele,","nem por que o pôs em segurança."],np:1},
{v:18,l:["Verão e desprezarão,","mas o Senhor se rirá deles."],np:1},
{v:19,l:["Depois disso se tornarão um cadáver sem honra,","objeto de desprezo entre os mortos para sempre;","pois ele os lançará de cabeça para baixo, sem voz,","e os abalará desde os alicerces;","ficarão completamente arrasados,","estarão na dor,","e a sua memória perecerá."],np:1},
{v:20,l:["Virão aterrorizados quando se fizer a conta dos seus pecados,","e as suas iniquidades se levantarão contra eles para acusá-los."],np:1}
];

window.TEXTOS_SEED["sabedoria"][5] = [
{s:"O justo diante dos seus opressores"},
{v:1,l:["Então o justo estará de pé, com grande firmeza,","diante dos que o oprimiram","e desprezaram os seus sofrimentos."]},
{v:2,l:["Ao vê-lo, ficarão perturbados por um medo terrível","e pasmados diante da sua salvação inesperada."],np:1},
{v:3,l:["Dirão entre si, arrependidos,","gemendo na angústia do seu espírito:"],np:1},
{v:4,l:["Este é aquele de quem outrora zombávamos","e de quem fazíamos objeto de escárnio.","Insensatos! Julgávamos a sua vida uma loucura,","e o seu fim, uma desonra."],np:1},
{v:5,l:["Como é que foi contado entre os filhos de Deus,","e a sua parte está entre os santos?"],np:1},
{v:6,l:["Portanto, nós nos desviamos do caminho da verdade;","a luz da justiça não brilhou para nós,","e o sol não se levantou para nós."],np:1},
{v:7,l:["Andamos até o cansaço pelas veredas da iniquidade e da perdição,","atravessamos desertos sem caminho,","mas não conhecemos o caminho do Senhor."],np:1},
{v:8,l:["De que nos serviu o orgulho?","Que nos trouxe a riqueza com a arrogância?"],np:1},
{v:9,l:["Tudo isso passou como uma sombra,","como uma notícia que corre;"],np:1},
{v:10,l:["como um navio que atravessa as águas agitadas:","quando passou, não se encontra rastro dele,","nem a esteira da sua quilha nas ondas;"],np:1},
{v:11,l:["ou como um pássaro que voa pelo ar:","não se encontra sinal da sua passagem;","o ar leve, açoitado pelo bater das asas","e cortado pela força do seu sibilar,","foi atravessado pelas asas em movimento,","e depois não se encontra nele sinal algum da sua travessia;"],np:1},
{v:12,l:["ou como a flecha lançada ao alvo:","o ar, cortado, logo se fecha sobre si mesmo,","e não se sabe por onde ela passou."],np:1},
{v:13,l:["Assim também nós: mal nascemos, deixamos de existir;","não temos nenhum sinal de virtude para mostrar,","e nos consumimos na nossa maldade."],np:1},
{v:14,l:["Pois a esperança do ímpio é como a palha levada pelo vento,","como a geada fina que a tempestade dispersa,","como a fumaça que o vento dissipa,","como a lembrança de um hóspede de um só dia."],np:1},
{s:"A recompensa dos justos"},
{v:15,l:["Mas os justos vivem para sempre;","a sua recompensa está no Senhor,","e o Altíssimo cuida deles."]},
{v:16,l:["Por isso receberão da mão do Senhor","a coroa real da glória","e o diadema da beleza;","pois ele os protegerá com a sua direita","e os defenderá com o seu braço."],np:1},
{v:17,l:["Tomará o seu zelo como armadura","e armará a criação para castigar os inimigos;"],np:1},
{v:18,l:["vestirá a justiça como couraça","e porá como capacete o julgamento imparcial;"],np:1},
{v:19,l:["tomará a santidade como escudo invencível;"],np:1},
{v:20,l:["afiará a sua ira implacável como espada,","e o universo combaterá com ele contra os insensatos."],np:1,n:"Compare Efésios 6,13–17."},
{v:21,l:["Partirão, certeiros, os dardos dos relâmpagos,","e, como de um arco bem curvado, das nuvens voarão ao alvo;"],np:1},
{v:22,l:["de uma catapulta serão lançadas pedras de granizo cheias de furor;","a água do mar se enfurecerá contra eles,","e os rios os submergirão sem piedade."],np:1},
{v:23,l:["Um sopro poderoso se levantará contra eles","e os dispersará como um furacão.","Assim a iniquidade devastará toda a terra,","e a maldade derrubará os tronos dos poderosos."],np:1}
];

window.TEXTOS_SEED["sabedoria"][6] = [
{s:"Os reis devem buscar a sabedoria"},
{v:1,l:["Escutai, pois, ó reis, e compreendei;","aprendei, juízes dos confins da terra."]},
{v:2,l:["Prestai ouvido, vós que dominais as multidões","e vos orgulhais das turbas de nações."],np:1},
{v:3,l:["Pois é do Senhor que recebestes o poder,","e do Altíssimo, a soberania;","ele examinará as vossas obras","e sondará os vossos desígnios."],np:1},
{v:4,l:["Pois, sendo ministros do seu reino,","não julgastes com retidão,","nem guardastes a lei,","nem andastes segundo a vontade de Deus."],np:1},
{v:5,l:["Terrível e repentino ele virá contra vós,","pois um julgamento implacável espera os que estão no alto."],np:1},
{v:6,l:["O pequeno é digno de perdão e de misericórdia,","mas os poderosos serão examinados com rigor."],np:1},
{v:7,l:["Pois o Senhor de todos não faz acepção de pessoas,","nem se intimida diante da grandeza,","porque ele fez o pequeno e o grande","e cuida igualmente de todos;"],np:1},
{v:8,l:["mas aos poderosos espera um exame rigoroso."],np:1},
{v:9,l:["É a vós, pois, ó soberanos, que se dirigem as minhas palavras,","para que aprendais a sabedoria e não caiais."],np:1},
{v:10,l:["Pois os que observam santamente as coisas santas serão santificados,","e os que as aprenderam encontrarão defesa."],np:1},
{v:11,l:["Desejai, pois, as minhas palavras;","amai-as, e sereis instruídos."],np:1},
{s:"A sabedoria se deixa encontrar"},
{v:12,l:["A sabedoria é radiante e não murcha;","facilmente é contemplada pelos que a amam","e encontrada pelos que a procuram."]},
{v:13,l:["Ela se antecipa aos que a desejam,","dando-se a conhecer primeiro."],np:1},
{v:14,l:["Quem madruga por ela não se cansará,","pois a encontrará sentada à sua porta."],np:1},
{v:15,l:["Pensar nela é a perfeição da prudência,","e quem vigia por causa dela logo estará livre de cuidados."],np:1},
{v:16,l:["Pois ela mesma anda à procura dos que são dignos dela;","nos caminhos lhes aparece com benevolência","e vem ao seu encontro em cada pensamento."],np:1},
{v:17,l:["O seu princípio é o desejo sincero da instrução;","o cuidado da instrução é o amor;"],np:1},
{v:18,l:["o amor é a observância das suas leis;","a obediência às leis é garantia de incorruptibilidade;"],np:1},
{v:19,l:["e a incorruptibilidade aproxima de Deus."],np:1},
{v:20,l:["Assim, o desejo da sabedoria conduz ao reino."],np:1},
{v:21,l:["Se vos comprazeis nos tronos e nos cetros, soberanos dos povos,","honrai a sabedoria, para que reineis para sempre."],np:1},
{s:"Salomão apresenta a sabedoria"},
{v:22,l:["Vou anunciar o que é a sabedoria e como ela nasceu;","não vos esconderei os mistérios,","mas a investigarei desde a sua origem,","porei à luz o seu conhecimento","e não passarei ao largo da verdade."]},
{v:23,l:["Não andarei com a inveja que corrói,","pois ela nada tem em comum com a sabedoria."],np:1},
{v:24,l:["Um grande número de sábios é a salvação do mundo,","e um rei sensato é a estabilidade do povo."],np:1},
{v:25,l:["Recebei, pois, a instrução por meio das minhas palavras,","e vos será de proveito."],np:1}
];

window.TEXTOS_SEED["sabedoria"][7] = [
{s:"Salomão, um homem como os outros"},
{v:1,l:["Também eu sou um homem mortal, igual a todos,","descendente do primeiro homem, formado da terra;","no ventre de uma mãe fui modelado em carne,"]},
{v:2,l:["tomando forma no sangue durante dez meses,","da semente do homem e do prazer que acompanha o sono."],np:1,n:"Dez meses: contados em meses lunares."},
{v:3,l:["Também eu, ao nascer, respirei o ar que é de todos","e caí sobre a terra que a todos acolhe igualmente;","o meu primeiro grito foi um choro, como o de todos."],np:1},
{v:4,l:["Fui criado entre fraldas e cuidados."],np:1},
{v:5,l:["Nenhum rei teve outro começo de vida:"],np:1},
{v:6,l:["para todos há uma só entrada na vida,","e uma saída igual."],np:1},
{s:"Salomão prefere a sabedoria a tudo"},
{v:7,l:["Por isso rezei, e me foi dada a prudência;","invoquei, e veio sobre mim o espírito da sabedoria."],n:"Compare 1 Reis 3,5–14."},
{v:8,l:["Preferi-a aos cetros e aos tronos,","e em comparação com ela tive a riqueza por nada."],np:1},
{v:9,l:["Não a comparei às pedras preciosas,","pois todo o ouro, diante dela, é um pouco de areia,","e a prata, ao seu lado, vale como lama."],np:1},
{v:10,l:["Amei-a mais que a saúde e a beleza,","e preferi possuí-la mais que a própria luz,","pois o brilho que dela emana nunca se apaga."],np:1},
{v:11,l:["Com ela me vieram todos os bens juntos,","e nas suas mãos, riquezas incontáveis."],np:1},
{v:12,l:["Alegrei-me com todos eles, porque a sabedoria os guia,","embora eu ignorasse que ela é a mãe de todos."],np:1},
{v:13,l:["Aprendi-a sem malícia e a comunico sem inveja;","não escondo as suas riquezas."],np:1},
{v:14,l:["Pois ela é para os homens um tesouro inesgotável;","os que o adquirem alcançam a amizade de Deus,","recomendados pelos dons da instrução."],np:1},
{v:15,l:["Conceda-me Deus falar como convém","e pensar de modo digno dos dons recebidos,","pois ele mesmo é o guia da sabedoria","e quem orienta os sábios."],np:1},
{v:16,l:["Na sua mão estamos nós e as nossas palavras,","toda a prudência e a habilidade das obras."],np:1},
{v:17,l:["Foi ele que me deu o conhecimento verdadeiro das coisas:","conhecer a estrutura do mundo e a força dos elementos,"],np:1},
{v:18,l:["o começo, o fim e o meio dos tempos,","a alternância dos solstícios e a mudança das estações,"],np:1},
{v:19,l:["os ciclos do ano e as posições dos astros,"],np:1},
{v:20,l:["a natureza dos animais e os instintos das feras,","o poder dos ventos e os pensamentos dos homens,","as variedades das plantas e as virtudes das raízes."],np:1},
{v:21,l:["Conheci tudo o que está oculto e tudo o que é manifesto,","pois me ensinou a sabedoria, artífice de todas as coisas."],np:1},
{s:"A natureza da sabedoria"},
{v:22,l:["Há nela um espírito inteligente, santo,","único, múltiplo, sutil,","ágil, penetrante, imaculado,","claro, impassível, amigo do bem, perspicaz,"]},
{v:23,l:["livre, benfazejo, amigo dos homens,","firme, seguro, sereno,","que tudo pode e tudo vigia,","e penetra todos os espíritos","inteligentes, puros e os mais sutis."],np:1,n:"São vinte e um qualificativos: três vezes sete, número da perfeição."},
{v:24,l:["Pois a sabedoria é mais ágil que todo movimento;","pela sua pureza, atravessa e penetra todas as coisas."],np:1},
{v:25,l:["Ela é um sopro do poder de Deus,","uma emanação pura da glória do Todo-poderoso;","por isso nada de impuro pode entrar nela."],np:1},
{v:26,l:["Ela é o reflexo da luz eterna,","o espelho sem mancha da atividade de Deus","e a imagem da sua bondade."],np:1,n:"Compare Hebreus 1,3 e Colossenses 1,15."},
{v:27,l:["Sendo única, tudo pode;","permanecendo em si mesma, tudo renova;","e, passando de geração em geração para as almas santas,","forma amigos de Deus e profetas."],np:1},
{v:28,l:["Pois Deus só ama","quem vive com a sabedoria."],np:1},
{v:29,l:["Ela é mais bela que o sol","e supera todas as constelações;","comparada com a luz, é superior,"],np:1},
{v:30,l:["pois à luz sucede a noite,","mas o mal não prevalece contra a sabedoria."],np:1}
];

window.TEXTOS_SEED["sabedoria"][8] = [
{s:"Salomão quer a sabedoria por esposa"},
{v:1,l:["Ela se estende com vigor de um extremo ao outro do mundo","e governa todas as coisas com suavidade."]},
{v:2,l:["Eu a amei e a procurei desde a minha juventude;","procurei tomá-la por esposa","e me enamorei da sua beleza."],np:1},
{v:3,l:["Ela faz brilhar a sua nobreza vivendo na intimidade de Deus,","e o Senhor de todas as coisas a amou."],np:1},
{v:4,l:["Pois ela é iniciada na ciência de Deus","e escolhe as suas obras."],np:1},
{v:5,l:["Se a riqueza é um bem desejável na vida,","que há de mais rico que a sabedoria,","que tudo realiza?"],np:1},
{v:6,l:["Se é a inteligência que opera,","quem mais do que ela é artífice de tudo o que existe?"],np:1},
{v:7,l:["Se alguém ama a justiça,","as virtudes são os frutos dos seus trabalhos:","ela ensina a temperança e a prudência,","a justiça e a fortaleza,","e não há nada mais útil do que isso na vida dos homens."],np:1,n:"São as quatro virtudes que a filosofia grega tinha como principais, e que a tradição cristã chamará cardeais."},
{v:8,l:["Se alguém deseja uma vasta experiência,","ela conhece o passado e adivinha o futuro,","sabe a arte das palavras e a solução dos enigmas,","conhece de antemão os sinais e os prodígios,","e o desenrolar das épocas e dos tempos."],np:1},
{v:9,l:["Decidi, pois, tomá-la por companheira de vida,","sabendo que ela seria a minha conselheira no bem","e o meu conforto nas preocupações e na tristeza."],np:1},
{v:10,l:["Graças a ela, terei glória diante das multidões","e, jovem ainda, honra diante dos anciãos."],np:1},
{v:11,l:["Serei considerado perspicaz no julgamento","e admirado diante dos poderosos."],np:1},
{v:12,l:["Quando eu me calar, esperarão;","quando eu falar, prestarão atenção;","e, se eu me alongar,","porão a mão sobre a boca."],np:1},
{v:13,l:["Graças a ela, terei a imortalidade","e deixarei uma lembrança eterna aos que vierem depois de mim."],np:1},
{v:14,l:["Governarei povos,","e nações me serão submissas."],np:1},
{v:15,l:["Tiranos terríveis me temerão ao ouvirem falar de mim;","no meio do povo me mostrarei bom,","e valente na guerra."],np:1},
{v:16,l:["Entrando em minha casa, descansarei junto dela,","pois a sua companhia não tem amargura,","nem a vida com ela, tristeza,","mas alegria e felicidade."],np:1},
{s:"A sabedoria é dom de Deus"},
{v:17,l:["Refletindo sobre isso comigo mesmo","e considerando no meu coração","que há imortalidade na união com a sabedoria,"]},
{v:18,l:["na sua amizade, um prazer puro,","no trabalho das suas mãos, riqueza inesgotável,","no convívio assíduo com ela, a prudência,","e na conversa com ela, a fama,","eu andava por toda parte procurando como obtê-la."],np:1},
{v:19,l:["Eu era um menino bem dotado,","e me coube em sorte uma alma boa;"],np:1},
{v:20,l:["ou melhor, sendo bom,","vim a um corpo sem mancha."],np:1,n:"Nota do tradutor: o autor usa aqui a linguagem da filosofia grega, sem pretender ensinar que a alma exista antes do corpo; logo em seguida afirma que tudo é dom de Deus (versículo 21)."},
{v:21,l:["Mas, sabendo que não a obteria se Deus não a concedesse","(e já era sinal de prudência saber de quem vem esse dom),","dirigi-me ao Senhor e lhe supliquei,","e disse de todo o coração:"],np:1}
];

window.TEXTOS_SEED["sabedoria"][9] = [
{s:"Oração de Salomão pela sabedoria"},
{v:1,l:["Deus dos meus pais e Senhor de misericórdia,","que fizeste todas as coisas com a tua palavra"]},
{v:2,l:["e com a tua sabedoria formaste o homem,","para que dominasse as criaturas que fizeste,"],np:1},
{v:3,l:["governasse o mundo com santidade e justiça","e julgasse com retidão de alma,"],np:1},
{v:4,l:["dá-me a sabedoria, que se senta junto ao teu trono,","e não me excluas do número dos teus filhos."],np:1},
{v:5,l:["Pois sou teu servo e filho da tua serva,","homem fraco e de vida breve,","pouco capaz de compreender o direito e as leis."],np:1},
{v:6,l:["Ainda que alguém seja perfeito entre os filhos dos homens,","se lhe faltar a sabedoria que vem de ti, não valerá nada."],np:1},
{v:7,l:["Tu me escolheste como rei do teu povo","e juiz dos teus filhos e das tuas filhas;"],np:1},
{v:8,l:["mandaste-me construir um templo no teu monte santo","e um altar na cidade onde habitas,","à imitação da tenda santa","que preparaste desde o princípio."],np:1},
{v:9,l:["Contigo está a sabedoria, que conhece as tuas obras","e estava presente quando fazias o mundo;","ela sabe o que é agradável aos teus olhos","e o que é reto segundo os teus mandamentos."],np:1},
{v:10,l:["Envia-a dos céus santos,","manda-a do trono da tua glória,","para que esteja comigo e trabalhe comigo,","e eu saiba o que te agrada."],np:1},
{v:11,l:["Pois ela tudo sabe e compreende;","me guiará com prudência nas minhas ações","e me protegerá com a sua glória."],np:1},
{v:12,l:["Então as minhas obras te serão agradáveis;","governarei o teu povo com justiça","e serei digno do trono de meu pai."],np:1},
{v:13,l:["Pois que homem pode conhecer o desígnio de Deus?","Ou quem pode imaginar o que o Senhor quer?"],np:1},
{v:14,l:["Os raciocínios dos mortais são tímidos,","e incertos os nossos pensamentos;"],np:1},
{v:15,l:["pois o corpo corruptível pesa sobre a alma,","e a tenda de barro oprime a mente cheia de cuidados."],np:1},
{v:16,l:["Mal conseguimos conhecer o que há na terra,","e com esforço encontramos o que está ao alcance da mão;","quem, então, investigou o que está nos céus?"],np:1},
{v:17,l:["Quem conheceu o teu desígnio,","se tu não lhe deste a sabedoria","e não enviaste do alto o teu santo espírito?"],np:1},
{v:18,l:["Assim foram endireitados os caminhos dos que estão na terra;","assim os homens aprenderam o que te agrada","e foram salvos pela sabedoria."],np:1}
];
